---
sidebar: sidebar 
permalink: ontap-security-hardening/enable-ldap-signing-sealing.html 
keywords: tr-4569, ontap hardening guide, security, queries, LDAP server, none, sign, seal 
summary: Lightweight Directory Access Protocol Signing and Sealing ermöglicht Sitzungssicherheit bei Anfragen an einen LDAP-Server. 
---
= Aktivieren Sie Lightweight Directory Access Protocol Signing and Sealing
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Das Signieren und Versiegeln wird unterstützt, um die Sitzungssicherheit bei Anfragen an einen LDAP-Server zu ermöglichen. Dieser Ansatz bietet eine Alternative zur LDAP-über-TLS-Sitzungssicherheit.

Das Signieren bestätigt die Integrität der LDAP-Nutzlastdaten mithilfe der Geheimschlüsseltechnologie. Das Sealing verschlüsselt die LDAP-Nutzlastdaten, um das Übertragen sensibler Informationen als unverschlüsselten Text zu vermeiden. Die Sitzungssicherheitseinstellungen auf einer SVM entsprechen denen auf dem LDAP-Server. Standardmäßig sind LDAP-Signing und Sealing deaktiviert.

.Schritte
. Um diese Funktion zu aktivieren, führen Sie den `vserver cifs security modify` Befehl mit dem `session-security-for-ad-ldap` Parameter aus.
+
Optionen für LDAP-Sicherheitsfunktionen:

+
** *None*: Standard, keine Signatur oder Versiegelung
** *Zeichen*: LDAP-Verkehr signieren
** *Seal*: LDAP-Verkehr signieren und verschlüsseln
+

NOTE: Die Parameter für Zeichen und Siegel sind kumulativ, d. h. wenn die Option Zeichen verwendet wird, ist das Ergebnis LDAP mit Signing. Wenn jedoch die Option „Siegel“ verwendet wird, ist das Ergebnis sowohl Zeichen als auch Siegel. Wenn für diesen Befehl kein Parameter angegeben wird, ist der Standardwert „none“.

+
Im Folgenden finden Sie eine Beispielkonfiguration:

+
[listing]
----
cluster1::> vserver cifs security modify -vserver vs1 -kerberos-clock-skew 3 -kerberos-ticket-age 8 -session-security-for-ad-ldap seal
----



