---
sidebar: sidebar 
permalink: ontap-security-hardening/sshv2.html 
keywords: tr-4569, ontap hardening guide, security, security ssh modify, SSH key exchange algorithms, SSH ciphers, SSH MAC algorithms, passwords for user sessions, public key for machine access 
summary: Vorhandene Konfigurationen von SSH-Schlüsselaustauschalgorithmen, -Chiffren oder -MAC-Algorithmen für das Cluster oder eine SVM durch von Ihnen angegebene Konfigurationseinstellungen ersetzen. 
---
= SSHv2-Management
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Mit dem `security ssh modify` Befehl werden die vorhandenen Konfigurationen der SSH-Schlüsselaustauschalgorithmen, Chiffren oder MAC-Algorithmen für das Cluster oder eine SVM durch die von Ihnen angegebenen Konfigurationseinstellungen ersetzt.

[TIP]
====
NetApp empfiehlt Folgendes:

* Verwenden Sie Passwörter für Benutzersitzungen.
* Verwenden Sie einen öffentlichen Schlüssel für den Maschinenzugriff.


====


== Unterstützte Chiffren und Schlüsselaustausch

[cols="42%,58%"]
|===
| Verschlüsselung | Schlüsselaustausch 


| aes256-ctr | diffie-hellman-Group-Exchange-sha256 (SHA-2) 


| aes192-ctr | diffie-hellman-Group-Exchange-sha1 (SHA-1) 


| aes128-ctr | diffie-hellman-group14-sha1 (SHA-1) 


| aes256-cbc | diffie-hellman-group1-sha1 (SHA-1) 


| aes192-cbc | - 


| aes128-cbc | - 


| aes128-gcm | - 


| aes256-gcm | - 


| 3des-cbc | - 
|===


== Unterstützte symmetrische AES- und 3DES-Verschlüsselungen

ONTAP unterstützt auch die folgenden Arten von symmetrischen AES- und 3DES-Verschlüsselungen (auch als Chiffren bezeichnet):

* hmac-sha1
* hmac-sha1-96
* hmac-md5
* hmac-md5-96
* hmac-Ripemd160
* umac-64
* umac-64
* umac-128
* hmac-sha2-256
* hmac-sha2-512
* hmac-sha1-etm
* hmac-sha1-96-etm
* hmac-sha2-256-etm
* hmac-sha2-512-etm
* hmac-md5-etm
* hmac-md5-96-etm
* hmac-Ripemd160-etm
* umac-64-etm
* umac-128-etm



NOTE: Die SSH-Verwaltungskonfiguration gilt für ONTAP und die Plattform BMC.
