---
sidebar: sidebar 
permalink: ransomware-solutions/ransomware-fpolicy.html 
keywords: tr-4572, technical report, ransomware, protect, protection, netapp ransomware protection, netapp tr, ontap tr 
summary: Zum Schutz vor Ransomware gehört FPolicy von NetApp, die das Speichern unerwünschter Dateien auf einer Storage Appliance der Enterprise-Klasse verhindert. 
---
= FPolicy Dateisperrung
:allow-uri-read: 


[role="lead"]
FPolicy verhindert das Speichern unerwünschter Dateien auf einer Storage Appliance der Enterprise-Klasse. FPolicy bietet Ihnen auch eine Möglichkeit, bekannte Ransomware-Dateierweiterungen zu blockieren. Ein Benutzer hat weiterhin volle Zugriffsrechte auf den Home-Ordner, aber FPolicy lässt es einem Benutzer nicht zu, Dateien zu speichern, die von seinem Administrator als blockiert markiert wurden. Es spielt keine Rolle, ob diese Dateien MP3-Dateien oder bekannte Ransomware-Dateierweiterungen sind.



== Blockieren Sie bösartige Dateien mit dem nativen FPolicy-Modus

Der native Modus von NetApp FPolicy (eine Weiterentwicklung des Namens, Dateirichtlinie) ist ein blockierendes Framework mit Dateierweiterungen, mit dem Sie unerwünschte Dateierweiterungen je nach Eingang in Ihre Umgebung blockieren können. Seit über einem Jahrzehnt ist ONTAP Cloud Teil von ONTAP. Es ist unglaublich hilfreich, wenn es darum geht, Sie beim Schutz vor Ransomware zu unterstützen. Diese Zero Trust Engine ist wertvoll, weil Sie zusätzliche Sicherheitsmaßnahmen erhalten, die über die Zugriffssteuerungslisten (ACL)-Berechtigungen hinausgehen.

Im ONTAP System Manager und BlueXP  steht eine Liste mit über 3000 Dateierweiterungen als Referenz zur Verfügung.


WARNING: Einige Erweiterungen können in Ihrer Umgebung legitim sein, und das Blockieren kann zu unerwarteten Problemen führen. Erstellen Sie zunächst Ihre eigene Liste, die für die jeweilige Umgebung geeignet ist, bevor Sie native FPolicy konfigurieren.

Der native FPolicy-Modus ist in allen ONTAP Lizenzen enthalten.

.Weitere Informationen .
* https://www.netapp.com/blog/fighting-ransomware-tools/["Blog: Kampf gegen Ransomware: Teil drei – ONTAP FPolicy, ein weiteres leistungsstarkes natives Tool (aka kostenlos)"^]




== Aktivieren Sie UEBA (User and Entity Behavior Analytics) mit dem externen FPolicy-Modus

Der externe FPolicy-Modus ist ein Benachrichtigungs- und Kontrollframework für die Dateiaktivität, das eine Übersicht über die Datei- und Benutzeraktivität bietet. Diese Benachrichtigungen können von einer externen Lösung verwendet werden, um KI-basierte Analysen durchzuführen, um schädliches Verhalten zu erkennen.

Der externe FPolicy-Modus kann auch so konfiguriert werden, dass er auf die Genehmigung des FPolicy-Servers wartet, bevor bestimmte Aktivitäten durchlaufen werden. Mehrere Richtlinien wie diese können auf einem Cluster konfiguriert werden, was für ein hohes Maß an Flexibilität sorgt.


WARNING: FPolicy-Server müssen auf FPolicy-Anfragen reagieren, wenn sie für eine Genehmigung konfiguriert sind. Andernfalls kann die Storage-System-Performance beeinträchtigt werden.

Der externe FPolicy-Modus ist in enthaltenlink:../system-admin/manage-licenses-concept.html["Alle ONTAP Lizenzen"].

.Weitere Informationen .
* https://www.netapp.com/blog/fighting-ransomware-ontap-fpolicy/["Blog: Kampf gegen Ransomware: Teil vier – UBA und ONTAP mit FPolicy externen Modus."^]

