---
permalink: s3-config/create-data-lifs-task.html 
sidebar: sidebar 
keywords: tr-4814, create, data, lifs 
summary: Wenn Sie eine neue SVM erstellt haben, sollten die dedizierten LIFs, die Sie für S3-Zugriff erstellen, Daten-LIFs sein. 
---
= Erstellen Sie Daten-LIFs für ONTAP S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie eine neue SVM erstellt haben, sollten die dedizierten LIFs, die Sie für S3-Zugriff erstellen, Daten-LIFs sein.

.Bevor Sie beginnen
* Der zugrunde liegende physische oder logische Netzwerkport muss im Administratorstatus konfiguriert worden `up` sein. Erfahren Sie mehr über `up` in der link:https://docs.netapp.com/us-en/ontap-cli/up.html["ONTAP-Befehlsreferenz"^].
* Wenn Sie planen, einen Subnetznamen zu verwenden, um die IP-Adresse und den Netzwerkmaskenwert für eine LIF zuzuweisen, muss das Subnetz bereits vorhanden sein.
+
Subnetze enthalten einen Pool mit IP-Adressen, die zum selben Layer-3-Subnetz gehören. Sie werden mit dem `network subnet create` Befehl erstellt.

* Die Richtlinie für den LIF-Dienst muss bereits vorhanden sein.
* Als Best Practice sollten LIFs, die für den Datenzugriff verwendet werden (Daten-s3-Server), und für Managementaufgaben verwendete LIFs (Management-https) getrennt sein. Beide Services sollten nicht auf derselben logischen Schnittstelle aktiviert werden.
* DNS-Einträge sollten nur IP-Adressen der LIFs haben, denen der Daten-s3-Server zugeordnet ist. Wenn IP-Adressen anderer LIFs im DNS-Datensatz angegeben werden, können ONTAP S3-Anfragen von anderen Servern bedient werden, was zu unerwarteten Antworten oder Datenverlusten führt.


.Über diese Aufgabe
* Sie können am gleichen Netzwerkport IPv4- und IPv6-LIFs erstellen.
* Wenn Sie im Cluster eine große Anzahl von LIFs enthalten sind, können Sie die auf dem Cluster unterstützte LIF- `network interface capacity show`Kapazität überprüfen. Verwenden Sie dazu den Befehl und die auf jedem Node unterstützte LIF-Kapazität. Hierzu können Sie mit dem `network interface capacity details show` Befehl (auf der erweiterten Berechtigungsebene) nachprüfen.
+
Erfahren Sie mehr über `network interface capacity show` und `network interface capacity details show` in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface+capacity+show["ONTAP-Befehlsreferenz"^].

* Wenn Sie das Cloud-Tiering (Remote FabricPool Capacity) aktivieren, müssen Sie auch LIFs für Intercluster konfigurieren.


.Schritte
. LIF erstellen:
+
`network interface create -vserver _svm_name_ -lif _lif_name_ -service-policy _service_policy_names_ -home-node _node_name_ -home-port _port_name_ {-address _IP_address_ -netmask _IP_address_ | -subnet-name _subnet_name_} -firewall-policy data -auto-revert {true|false}`

+
** `-home-node` Ist der Node, zu dem das LIF zurückgibt, wenn der `network interface revert` Befehl auf der LIF ausgeführt wird.
+
Erfahren Sie mehr über `network interface revert` in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-revert.html["ONTAP-Befehlsreferenz"^].

+
Sie können außerdem angeben, ob die LIF mithilfe der `-auto-revert` Option automatisch zum Home Node und Home Port zurückgesetzt werden soll.

** `-home-port` Ist der physische oder logische Port, zu dem die LIF zurückgibt, wenn der `network interface revert` Befehl auf der LIF ausgeführt wird.
** Sie können eine IP-Adresse mit den `-address` `-netmask` Optionen und angeben oder die Zuweisung aus einem Subnetz mit der `-subnet_name` Option aktivieren.
** Wenn Sie zur Versorgung der IP-Adresse und Netzwerkmaske ein Subnetz verwenden, wird bei einem Gateway automatisch eine Standardroute zu diesem Gateway zur SVM hinzugefügt, wenn mithilfe dieses Subnetzes eine LIF erstellt wird.
** Wenn Sie IP-Adressen manuell zuweisen (ohne ein Subnetz zu verwenden), müssen Sie möglicherweise eine Standardroute zu einem Gateway konfigurieren, wenn Clients oder Domänen-Controller in einem anderen IP-Subnetz vorhanden sind. Weitere Informationen zum `network route create` Erstellen einer statischen Route innerhalb einer SVM finden Sie im link:https://docs.netapp.com/us-en/ontap-cli/network-route-create.html["ONTAP-Befehlsreferenz"^].
**  `-firewall-policy`Verwenden Sie für die Option denselben Standard `data` wie die LIF-Rolle.
+
Sie können bei Bedarf später eine benutzerdefinierte Firewallrichtlinie erstellen und hinzufügen.

+

NOTE: Ab ONTAP 9.10.1 sind Firewall-Richtlinien veraltet und werden vollständig durch LIF-Servicerichtlinien ersetzt. Weitere Informationen finden Sie unter link:../networking/configure_firewall_policies_for_lifs.html["Konfigurieren Sie Firewallrichtlinien für LIFs"].

** `-auto-revert` Ermöglicht Ihnen die Angabe, ob eine Daten-LIF automatisch auf ihren Home Node zurückgesetzt wird, wenn beispielsweise ein Start erfolgt, Änderungen am Status der Managementdatenbank oder die Netzwerkverbindung hergestellt wird. Die Standardeinstellung ist `false`, Sie können sie jedoch `false` abhängig von den Netzwerkverwaltungsrichtlinien in Ihrer Umgebung auf festlegen.
** Die `-service-policy` Option gibt die Richtlinie für Daten- und Managementservices an, die Sie erstellt haben, sowie weitere Richtlinien, die Sie benötigen.


. Wenn Sie in der `-address` Option eine IPv6-Adresse zuweisen möchten:
+
.. Verwenden Sie den `network ndp prefix show` Befehl, um die Liste der RA-Präfixe anzuzeigen, die an verschiedenen Schnittstellen gelernt wurden.
+
Der `network ndp prefix show` Befehl ist auf der erweiterten Berechtigungsebene verfügbar.

.. Verwenden Sie das Format `prefix:id`, um die IPv6-Adresse manuell zu erstellen.
+
`prefix` Wird das Präfix an verschiedenen Schnittstellen gelernt.

+
 `id`Wählen Sie zum Ableiten der eine zufällige 64-Bit-Hexadezimalzahl aus.



. Überprüfen Sie mit dem `network interface show` Befehl, ob das LIF erfolgreich erstellt wurde.
. Vergewissern Sie sich, dass die konfigurierte IP-Adresse erreichbar ist:
+
[cols="2*"]
|===
| Überprüfen einer... | Verwenden... 


 a| 
IPv4-Adresse
 a| 
`network ping`



 a| 
IPv6-Adresse
 a| 
`network ping6`

|===


.Beispiele
Im folgenden Befehl wird gezeigt, wie eine S3-Daten-LIF erstellt wird, die mit der `my-S3-policy` Service-Richtlinie zugewiesen ist:

[listing]
----
network interface create -vserver svm1.example.com -lif lif2 -home-node node2 -homeport e0d -service-policy my-S3-policy -subnet-name ipspace1
----
Mit dem folgenden Befehl werden alle LIFs in Cluster-1 angezeigt. Datenschnittstellen Datenschnittstellen Datenverbund Daten3 werden mit IPv4-Adressen konfiguriert und Daten3 wird mit einer IPv6-Adresse konfiguriert:

[listing]
----
cluster-1::> network interface show

            Logical    Status     Network          Current      Current Is
Vserver     Interface  Admin/Oper Address/Mask     Node         Port    Home
----------- ---------- ---------- ---------------- ------------ ------- ----
cluster-1
            cluster_mgmt up/up    192.0.2.3/24     node-1       e1a     true
node-1
            clus1        up/up    192.0.2.12/24    node-1       e0a     true
            clus2        up/up    192.0.2.13/24    node-1       e0b     true
            mgmt1        up/up    192.0.2.68/24    node-1       e1a     true
node-2
            clus1        up/up    192.0.2.14/24    node-2       e0a     true
            clus2        up/up    192.0.2.15/24    node-2       e0b     true
            mgmt1        up/up    192.0.2.69/24    node-2       e1a     true
vs1.example.com
            datalif1     up/down  192.0.2.145/30   node-1       e1c     true
vs3.example.com
            datalif3     up/up    192.0.2.146/30   node-2       e0c     true
            datalif4     up/up    2001::2/64       node-2       e0c     true
5 entries were displayed.
----
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/network-ping.html["Netzwerk-Ping"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["Netzwerkschnittstelle"^]

