---
permalink: s3-config/create-bucket-task.html 
sidebar: sidebar 
keywords: s3, bucket, system manager, 
summary: S3-Objekte werden in _Buckets_ gespeichert. Sie sind nicht als Dateien in einem Verzeichnis innerhalb anderer Verzeichnisse verschachtelt. 
---
= Einen ONTAP S3-Bucket erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3-Objekte werden in _Buckets_ gespeichert. Sie sind nicht als Dateien in einem Verzeichnis innerhalb anderer Verzeichnisse verschachtelt.

.Bevor Sie beginnen
Es muss bereits eine Storage-VM mit einem S3-Server existieren.

.Über diese Aufgabe
* Ab ONTAP 9.14.1 ist die automatische Größenanpassung auf S3 FlexGroup Volumes aktiviert, wenn Buckets darauf erstellt werden. Dadurch wird eine übermäßige Kapazitätszuweisung während der Bucket-Erstellung auf bestehenden und neuen FlexGroup Volumes vermieden. FlexGroup Volumes werden anhand der folgenden Richtlinien auf die minimal erforderliche Größe skaliert. Die minimal erforderliche Größe entspricht der Gesamtgröße aller S3 Buckets in einem FlexGroup Volume.
+
** Ab ONTAP 9.14.1 wird, wenn ein S3-FlexGroup-Volume im Rahmen der Erstellung eines neuen Buckets angelegt wird, das FlexGroup-Volume mit der minimal erforderlichen Größe erstellt.
** Wurde ein S3 FlexGroup Volume vor ONTAP 9.14.1 erstellt, wird das erste Bucket, das nach ONTAP 9.14.1 erstellt oder gelöscht wird, das FlexGroup Volume auf die minimal erforderliche Größe anpassen.
** Wenn ein S3 FlexGroup Volume vor ONTAP 9.14.1 erstellt wurde und bereits die erforderliche Mindestgröße hatte, bleibt bei der Erstellung oder Löschung eines Buckets nach ONTAP 9.14.1 die Größe des S3 FlexGroup Volumes erhalten.


* Speicherdienststufen sind vordefinierte adaptive Quality of Service (QoS)-Richtliniengruppen mit den Standardstufen _value_, _performance_ und _extreme_. Statt einer der Standard-Speicherdienststufen kann auch eine benutzerdefinierte QoS-Richtliniengruppe definiert und auf einen Bucket angewendet werden. Weitere Informationen zu Speicherdienstdefinitionen finden sich unter link:storage-service-definitions-reference.html["Definitionen von Speicherdiensten"]. Weitere Informationen zum Leistungsmanagement finden sich unter link:../performance-admin/index.html["Leistungsmanagement"]. Ab ONTAP 9.8 ist QoS bei der Speicherbereitstellung standardmäßig aktiviert. QoS kann während des Bereitstellungsprozesses oder zu einem späteren Zeitpunkt deaktiviert oder eine benutzerdefinierte QoS-Richtlinie ausgewählt werden.


* Wenn Sie lokales Capacity Tiering konfigurieren, werden Buckets und Benutzer in einer Datenspeicher-VM erstellt, nicht in der Systemspeicher-VM, in der sich der S3-Server befindet.
* Für den Remote-Clientzugriff müssen Buckets in einer S3-fähigen Storage-VM konfiguriert werden. Wenn ein Bucket in einer Storage-VM erstellt wird, die nicht S3-fähig ist, steht er nur für lokales Tiering zur Verfügung.
* Ab ONTAP 9.14.1 ist es möglich, link:create-bucket-mcc-task.html["Erstellen eines Buckets auf einem gespiegelten oder nicht gespiegelten Aggregat in einer MetroCluster Konfiguration"].
* Für die CLI stehen beim Erstellen eines Buckets zwei Bereitstellungsoptionen zur Verfügung:
+
** ONTAP wählt die zugrunde liegenden Aggregate und FlexGroup-Komponenten aus (Standardeinstellung)
+
*** ONTAP erstellt und konfiguriert ein FlexGroup Volume für den ersten Bucket, indem die Aggregate automatisch ausgewählt werden. Dabei wird automatisch das höchste für Ihre Plattform verfügbare Servicelevel ausgewählt, oder das Speicherservicelevel kann angegeben werden. Alle weiteren Buckets, die später in der Speicher-VM hinzugefügt werden, verwenden dasselbe zugrunde liegende FlexGroup Volume.
*** Alternativ kann angegeben werden, ob der Bucket für Tiering verwendet wird, wobei ONTAP versucht, kostengünstige Medien mit optimaler Leistung für die gestaffelten Daten auszuwählen.


** Sie wählen die zugrunde liegenden Aggregate und FlexGroup Komponenten aus (erfordert erweiterte Berechtigungsbefehle): Es besteht die Möglichkeit, die Aggregate, auf denen der Bucket und das enthaltene FlexGroup Volume erstellt werden müssen, manuell auszuwählen und anschließend die Anzahl der Bestandteile auf jedem Aggregat anzugeben. Beim Hinzufügen weiterer Buckets:
+
*** Wenn Sie Aggregate und Bestandteile für einen neuen Bucket angeben, wird für den neuen Bucket eine neue FlexGroup erstellt.
*** Wenn Sie für einen neuen Bucket keine Aggregate und Bestandteile angeben, wird der neue Bucket zu einer bestehenden FlexGroup hinzugefügt. Siehe xref:../flexgroup/index.html[FlexGroup Volumenmanagement] für weitere Informationen.
+
Wenn Sie beim Erstellen eines Buckets Aggregate und Bestandteile angeben, werden keine QoS-Richtliniengruppen, weder Standard noch benutzerdefinierte, angewendet. Dies ist später mit dem  `vserver object-store-server bucket modify` Befehl möglich.

+
Weitere Informationen zu  `vserver object-store-server bucket modify` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-object-store-server-show.html["ONTAP-Befehlsreferenz"^].

+
*Hinweis:* Wenn Sie Buckets von Cloud Volumes ONTAP bereitstellen, sollte die CLI-Prozedur verwendet werden. Es wird dringend empfohlen, die zugrunde liegenden Aggregate manuell auszuwählen, um sicherzustellen, dass nur ein Knoten verwendet wird. Die Verwendung von Aggregaten beider Knoten kann die Leistung beeinträchtigen, da sich die Knoten in geografisch getrennten Verfügbarkeitszonen befinden und daher anfällig für Latenzprobleme sind.









[[create-s3-buckets-with-the-ontap-cli]]
== S3-Buckets mit der ONTAP CLI erstellen

. Wenn Sie Aggregate und FlexGroup Komponenten selbst auswählen, ist die Berechtigungsstufe „Erweitert“ erforderlich (ansonsten ist die Administratorberechtigung ausreichend): `set -privilege advanced`
. Einen Bucket erstellen:
+
`vserver object-store-server bucket create -vserver <svm_name> -bucket <bucket_name> -size [integer{KB|MB|GB|TB|PB}] [-comment text] [additional_options]`

+
Der Name der Storage-VM kann entweder eine Datenspeicher-VM oder  `Cluster` (der Name der Systemspeicher-VM) sein, wenn lokales Tiering konfiguriert wird.

+
Wenn ONTAP einen Bucket basierend auf Leistung oder Nutzung erstellen soll, kann eine der folgenden Optionen verwendet werden:

+
** Service Level
+
Die  `-storage-service-level` Option ist mit einem der folgenden Werte anzugeben:  `value`,  `performance` oder  `extreme`.

** Tiering
+
Die Option  `-used-as-capacity-tier true` einschließen.



+
Wenn Sie die Aggregate angeben möchten, auf denen das zugrunde liegende FlexGroup Volume erstellt werden soll, stehen die folgenden Optionen zur Verfügung:

+
** Der  `-aggr-list`Parameter gibt die Liste der Aggregate an, die für FlexGroup Volume-Bestandteile verwendet werden.
+
Jeder Eintrag in der Liste erstellt einen Bestandteil auf dem angegebenen Aggregat. Ein Aggregat kann mehrfach angegeben werden, sodass mehrere Bestandteile auf dem Aggregat erstellt werden.

+
Für eine gleichbleibende Leistung über das FlexGroup Volume hinweg müssen alle Aggregate den gleichen Festplattentyp und die gleiche RAID-Gruppenkonfiguration verwenden.

** Der  `-aggr-list-multiplier`Parameter gibt an, wie oft die mit dem  `-aggr-list`Parameter aufgeführten Aggregate beim Erstellen eines FlexGroup Volume durchlaufen werden.
+
Der Standardwert des  `-aggr-list-multiplier` Parameters ist 4.



. Bei Bedarf kann eine QoS-Richtliniengruppe hinzugefügt werden:
+
`vserver object-store-server bucket modify -bucket _bucket_name_ -qos-policy-group _qos_policy_group_`

. Bucket-Erstellung überprüfen:
+
`vserver object-store-server bucket show [-instance]`



.Beispiel
Das folgende Beispiel erstellt einen Bucket für Storage-VM `vs1` mit der Größe `1TB` und gibt das Aggregat an:

Weitere Informationen zu den in diesem Verfahren beschriebenen Befehlen befinden sich in der link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP-Befehlsreferenz"^].

[listing]
----
cluster-1::*> vserver object-store-server bucket create -vserver svm1.example.com -bucket testbucket -aggr-list aggr1 -size 1TB
----


[[create-s3-buckets-with-system-manager]]
== S3-Buckets mit System Manager erstellen

. Einen neuen Bucket auf einer S3-fähigen Storage-VM hinzufügen.
+
.. Klicken Sie auf *Speicher > Buckets* und anschließend auf *Hinzufügen*.
.. Einen Namen eingeben, die Speicher-VM auswählen und eine Größe angeben.
+
*** Wenn Sie jetzt auf *Speichern* klicken, wird ein Bucket mit diesen Standardeinstellungen erstellt:
+
**** Benutzern wird kein Zugriff auf den Bucket gewährt, es sei denn, es sind bereits Gruppenrichtlinien aktiv.
+

NOTE: Sie sollten den S3 Root-Benutzer nicht zur Verwaltung des ONTAP Objektspeichers und zur Freigabe seiner Berechtigungen verwenden, da dieser uneingeschränkten Zugriff auf den Objektspeicher hat. Stattdessen empfiehlt es sich, einen Benutzer oder eine Gruppe mit administrativen Berechtigungen zu erstellen, die Sie zuweisen.

**** Ein Servicequalitätsniveau (Leistung), das für Ihr System das höchstmögliche verfügbare ist.


*** Klicken Sie auf *Speichern*, um einen Bucket mit diesen Standardwerten zu erstellen.








[[configure-additional-permissions-and-restrictions]]
=== Zusätzliche Berechtigungen und Einschränkungen konfigurieren

Sie können auf *Weitere Optionen* klicken, um Einstellungen für die Objektsperrung, Benutzerberechtigungen und Leistungsstufe bei der Konfiguration des Buckets festzulegen oder diese Einstellungen später ändern.

Wenn Sie den S3 Objektspeicher für FabricPool Tiering verwenden möchten, empfiehlt es sich, die Option *Für Tiering verwenden* (kostengünstige Medien mit optimaler Leistung für die gestaffelten Daten) statt eines Leistungs-Servicelevels auszuwählen.

Wenn die Versionierung für einen Bucket aktiviert ist, kann die Aufbewahrungsdauer der Object Lock für bestimmte Versionen eines Objekts mithilfe von S3-Clients festgelegt werden. Das Sperren einer bestimmten Version eines Objekts verhindert nicht das Löschen anderer Versionen dieses Objekts. Wenn die Versionierung für Ihre Objekte zur späteren Wiederherstellung aktiviert werden soll, ist *Versionierung aktivieren* auszuwählen. Die Versionierung ist standardmäßig aktiviert, wenn die Objektsperrung für den Bucket aktiviert wird. Informationen zur Objektversionierung finden sich unter  https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html["Verwendung der Versionierung in S3-Buckets für Amazon"].

Ab Version 9.14.1 wird die Objektsperrung für S3-Buckets unterstützt. Die S3-Objektsperrung muss beim Erstellen eines Buckets aktiviert werden. Die Objektsperrung kann nicht für bereits vorhandene Buckets aktiviert werden. Die Objektsperrung kann nur in nativen S3-Anwendungsfällen verwendet werden. Multiprotokoll-NAS-Volumes, die für die Verwendung des S3-Protokolls konfiguriert sind, sollten SnapLock verwenden, um Daten im WORM-Speicher zu speichern. Die S3-Objektsperrung erfordert eine Standardlizenz für SnapLock. Diese Lizenz ist mit link:../system-admin/manage-licenses-concept.html["ONTAP One"] enthalten.

Vor ONTAP One war die SnapLock-Lizenz im Security and Compliance Bundle enthalten. Das Security and Compliance Bundle wird nicht mehr angeboten, ist aber weiterhin gültig. Obwohl es derzeit nicht erforderlich ist, können bestehende Kunden sich dafür entscheiden, link:../system-admin/download-nlf-task.html["Upgrade auf ONTAP One"]. Wenn die Objektsperre für einen Bucket aktiviert wird, sollte link:../system-admin/manage-license-task.html["Es sollte überprüft werden, ob eine SnapLock-Lizenz installiert ist."]. Wenn keine SnapLock-Lizenz installiert ist, muss link:../system-admin/install-license-task.html["installieren"] sie vor der Aktivierung der Objektsperre installiert werden.

Nachdem Sie überprüft haben, dass die SnapLock-Lizenz installiert ist, kann zum Schutz von Objekten in Ihrem Bucket vor dem Löschen oder Überschreiben *Objektsperre aktivieren* ausgewählt werden. Die Sperrung kann entweder für alle oder für bestimmte Versionen von Objekten aktiviert werden, und nur, wenn die SnapLock-Compliance-Uhr für die Clusterknoten initialisiert ist. Dabei sind folgende Schritte zu beachten:

. Wenn die SnapLock Compliance-Uhr auf keinem Knoten des Clusters initialisiert ist, erscheint die Schaltfläche *SnapLock Compliance-Uhr initialisieren*. Mit *SnapLock Compliance-Uhr initialisieren* wird die SnapLock Compliance-Uhr auf den Cluster-Knoten initialisiert.
. *Governance*-Modus auswählen, um eine zeitbasierte Sperre zu aktivieren, die _Write once, read many (WORM)_-Berechtigungen für die Objekte ermöglicht. Auch im _Governance_-Modus können die Objekte von Administratorbenutzern mit spezifischen Berechtigungen gelöscht werden.
. *Compliance*-Modus auswählen, um strengere Regeln für das Löschen und Aktualisieren von Objekten festzulegen. In diesem Modus der Objektsperrung können die Objekte erst nach Ablauf der festgelegten Aufbewahrungsfrist ablaufen. Sofern keine Aufbewahrungsfrist angegeben ist, bleiben die Objekte unbegrenzt gesperrt.
. Geben Sie die Aufbewahrungsdauer für die Sperre in Tagen oder Jahren an, wenn die Sperre für einen bestimmten Zeitraum wirksam sein soll.
+

NOTE: Sperren sind sowohl für versionierte als auch für nicht versionierte S3-Buckets möglich. Objektsperren sind für NAS-Objekte nicht möglich.



Sie können die Schutz- und Berechtigungseinstellungen sowie die Performance-Service-Stufe für den Bucket konfigurieren.


NOTE: Benutzer und Gruppen müssen bereits erstellt sein, bevor die Berechtigungen konfiguriert werden.

Weitere Informationen sind unter link:../s3-snapmirror/create-remote-mirror-new-bucket-task.html["Spiegel für neuen Bucket erstellen"] zu finden.



[[verify-access-to-the-bucket]]
=== Zugriff auf den Bucket überprüfen

Bei S3-Clientanwendungen (egal ob ONTAP S3 oder eine externe Drittanbieteranwendung) lässt sich der Zugriff auf den neu erstellten Bucket durch Eingabe des Folgenden überprüfen:

* Das S3-Server-CA-Zertifikat.
* Der Zugriffsschlüssel und der geheime Schlüssel des Benutzers.
* Der FQDN-Name des S3-Servers und der Bucket-Name.

