---
permalink: s3-config/create-intercluster-lifs-remote-fabricpool-tiering-task.html 
sidebar: sidebar 
keywords: create, intercluster, lifs, remote fabricpool, tiering 
summary: 'Wenn Sie die Remote FabricPool Kapazitäts-Tiering (Cloud) mit ONTAP S3 aktivieren, müssen Intercluster-LIFs konfiguriert werden. Intercluster-LIFs können auf Ports konfiguriert werden, die mit dem Datennetzwerk gemeinsam genutzt werden. Dadurch wird die Anzahl der für die Intercluster-Vernetzung benötigten Ports reduziert.' 
---
= Intercluster-LIFs für Remote FabricPool Tiering mit ONTAP S3 erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die Remote FabricPool Kapazitäts-Tiering (Cloud) mit ONTAP S3 aktivieren, müssen Intercluster-LIFs konfiguriert werden. Intercluster-LIFs können auf Ports konfiguriert werden, die mit dem Datennetzwerk gemeinsam genutzt werden. Dadurch wird die Anzahl der für die Intercluster-Vernetzung benötigten Ports reduziert.

.Bevor Sie beginnen
* Der zugrunde liegende physische oder logische Netzwerkport muss auf den administrativen `up` Status konfiguriert sein. Weitere Informationen zu  `up` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/up.html["ONTAP-Befehlsreferenz"^].
* Die LIF-Servicerichtlinie muss bereits existieren.


.Über diese Aufgabe
Intercluster LIFs sind weder für das lokale FabricPool Tiering noch für die Bereitstellung externer S3-Anwendungen erforderlich.

.Schritte
. Die Ports im Cluster werden aufgelistet:
+
`network port show`

+
Das folgende Beispiel zeigt die Netzwerkanschlüsse in `cluster01`:

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
----
+
Weitere Informationen zu  `network port show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html["ONTAP-Befehlsreferenz"^].

. Intercluster-LIFs auf dem System-SVM erstellen:
+
`network interface create -vserver Cluster -lif _LIF_name_ -service-policy default-intercluster -home-node _node_ -home-port _port_ -address _port_IP_ -netmask _netmask_`

+
Das folgende Beispiel erstellt Intercluster-LIFs `cluster01_icl01` und `cluster01_icl02`:

+
[listing]
----

cluster01::> network interface create -vserver Cluster -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0c -address 192.168.1.201
-netmask 255.255.255.0

cluster01::> network interface create -vserver Cluster -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0c -address 192.168.1.202
-netmask 255.255.255.0
----
+
Weitere Informationen zu  `network interface create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-create.html["ONTAP-Befehlsreferenz"^].

. Es sollte überprüft werden, ob die Intercluster-LIFs erstellt wurden:
+
`network interface show -service-policy default-intercluster`

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0c     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0c     true
----
. Es sollte sichergestellt werden, dass die Intercluster-LIFs redundant sind:
+
`network interface show -service-policy default-intercluster -failover`

+
Das folgende Beispiel zeigt, dass die Intercluster-LIFs `cluster01_icl01` und `cluster01_icl02` auf dem `e0c` Port auf den `e0d` Port übergehen.

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster -failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-01:e0c,
                                              cluster01-01:e0d
         cluster01_icl02 cluster01-02:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-02:e0c,
                                              cluster01-02:e0d
----
+
Weitere Informationen zu  `network interface show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["ONTAP-Befehlsreferenz"^].


