---
permalink: s3-config/enable-ontap-s3-access-local-fabricpool-task.html 
sidebar: sidebar 
keywords: enable, ontap, s3 access, local, fabricpool, tiering 
summary: Damit ONTAP S3 als lokale FabricPool Kapazitätsebene verwendet werden kann, muss ein Objektspeicher auf Basis des erstellten Buckets definiert und dieser Objektspeicher einem Performance-Tier-Aggregat zugeordnet werden, um eine FabricPool zu erstellen. 
---
= ONTAP S3-Zugriff für lokales FabricPool Tiering aktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Damit ONTAP S3 als lokale FabricPool Kapazitätsebene verwendet werden kann, muss ein Objektspeicher auf Basis des erstellten Buckets definiert und dieser Objektspeicher einem Performance-Tier-Aggregat zugeordnet werden, um eine FabricPool zu erstellen.

.Bevor Sie beginnen
Sie benötigen den ONTAP S3 Servernamen und einen Bucket-Namen, und der S3-Server muss mithilfe von Cluster-LIFs (mit dem  `-vserver Cluster` Parameter) erstellt worden sein.

.Über diese Aufgabe
Die Objektspeicherkonfiguration enthält Informationen über die lokale Kapazitätsebene, einschließlich der Namen des S3-Servers und des Buckets sowie der Authentifizierungsanforderungen.

Eine einmal erstellte Objektspeicherkonfiguration darf nicht mit einem anderen Objektspeicher oder Bucket verknüpft werden. Es können mehrere Buckets für lokale Tiers erstellt werden, jedoch nicht mehrere Objektspeicher in einem einzelnen Bucket.

Für eine lokale Kapazitätsstufe ist keine FabricPool-Lizenz erforderlich.

.Schritte
. Den Objektspeicher für die lokale Kapazitätsebene erstellen:
+
`storage aggregate object-store config create -object-store-name _store_name_ -ipspace Cluster -provider-type ONTAP_S3 -server _S3_server_name_ -container-name _bucket_name_ -access-key _access_key_ -secret-password password`

+
** Der  `-container-name` ist der von Ihnen erstellte S3-Bucket.
** Der  `-access-key`Parameter autorisiert Anfragen an den ONTAP S3 Server.
** Der  `-secret-password`Parameter (geheimer Zugriffsschlüssel) authentifiziert Anfragen an den ONTAP S3 Server.
** Sie können den  `-is-certificate-validation-enabled` Parameter auf  `false` setzen, um die Zertifikatsprüfung für ONTAP S3 zu deaktivieren.


+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name MyLocalObjStore -ipspace Cluster -provider-type ONTAP_S3 -server s3.example.com
-container-name bucket1 -access-key myS3key -secret-password myS3pass
----
. Anzeige und Überprüfung der Objektspeicher-Konfigurationsinformationen:
+
`storage aggregate object-store config show`

. Optional: link:../fabricpool/determine-data-inactive-reporting-task.html["Ermitteln, wie viele Daten in einem Volume inaktiv sind, indem die Berichterstellung für inaktive Daten verwendet wird."].
+
Die Kenntnis darüber, wie viele Daten in einem Volume inaktiv sind, kann bei der Entscheidung unterstützen, welches Aggregat für FabricPool Local Tiering verwendet wird.

. Den Objektspeicher an ein Aggregat anbinden:
+
`storage aggregate object-store attach -aggregate _aggr_name_ -object-store-name _store_name_`

+
Sie können die  `allow-flexgroup *true*` Option verwenden, um Aggregate anzuhängen, die FlexGroup-Volumenbestandteile enthalten.

+
[listing]
----
cluster1::> storage aggregate object-store attach
-aggregate aggr1 -object-store-name MyLocalObjStore
----
. Die Objektspeicherinformationen werden angezeigt und es wird überprüft, ob der angeschlossene Objektspeicher verfügbar ist:
+
`storage aggregate object-store show`

+
[listing]
----
cluster1::> storage aggregate object-store show

Aggregate    Object Store Name    Availability State
---------    -----------------    ------------------
aggr1        MyLocalObjStore      available
----


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-attach.html["storage aggregate Objektspeicher anhängen"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-create.html["storage aggregate Objektspeicher config create"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-show.html["storage aggregate Objektspeicher-Konfiguration anzeigen"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-show.html["storage aggregate object-store show"^]

