---
permalink: s3-config/generate-access-keys-api.html 
sidebar: sidebar 
keywords: generate, ldap, s3, access keys, secret keys using API 
summary: Schlüssel für den Zugriff auf S3-Clients können von S3-Benutzern über API neu generiert werden. 
---
= Ermöglichen Sie LDAP- oder Domänenbenutzern, ihre eigenen ONTAP S3-Zugriffsschlüssel zu generieren
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.14.1 können Sie als ONTAP-Administrator benutzerdefinierte Rollen erstellen und sie lokalen oder Domänengruppen oder LDAP-Gruppen (Lightweight Directory Access Protocol) zuweisen, sodass die Benutzer dieser Gruppen ihren eigenen Zugriff und geheime Schlüssel für den S3-Clientzugriff generieren können.

Sie müssen für die Storage-VM einige Konfigurationsschritte durchführen, um die benutzerdefinierte Rolle zu erstellen und dem Benutzer zuzuweisen, der die API zur Schlüsselgenerierung nach dem Zugriff aktiviert.


NOTE: Wenn LDAP deaktiviert ist, können Sie so konfigurieren, dass Benutzer Zugriffsschlüssel generieren könnenlink:configure-access-ldap.html["Active Directory und SMB mit domänenbasierter Authentifizierung"].

.Bevor Sie beginnen
Stellen Sie Folgendes sicher:

. Es wurde eine S3-fähige Storage-VM erstellt, die einen S3-Server enthält. Siehe link:../s3-config/create-svm-s3-task.html["Erstellung einer SVM für S3"].
. In dieser Storage-VM wurde ein Bucket erstellt. Siehe link:../s3-config/create-bucket-task.html["Erstellen eines Buckets"].
. DNS ist auf der Storage-VM konfiguriert. Siehe link:../networking/configure_dns_services_auto.html["Konfigurieren Sie DNS-Dienste"].
. Auf der Storage-VM wird ein selbstsigniertes CA-Zertifikat (Root Certification Authority) des LDAP-Servers installiert. Siehe link:../nfs-config/install-self-signed-root-ca-certificate-svm-task.html["Installieren Sie das selbstsignierte Root-CA-Zertifikat auf der SVM"].
. Ein LDAP-Client wird auf der Storage-VM mit aktiviertem TLS konfiguriert. Siehe link:../nfs-config/create-ldap-client-config-task.html["Erstellen Sie eine LDAP-Client-Konfiguration"].
. Verknüpfen Sie die Client-Konfiguration mit dem Vserver. Siehe link:../nfs-config/enable-ldap-svms-task.html["Zuordnen der LDAP-Client-Konfiguration zu SVMs"]. Erfahren Sie mehr über `vserver services name-service ldap create` in der link:https://docs.netapp.com/us-en/ontap-cli//vserver-services-name-service-ldap-create.html["ONTAP-Befehlsreferenz"^].
. Wenn Sie eine Storage-VM verwenden, erstellen Sie eine Management-Netzwerkschnittstelle (LIF) und auf der VM, und außerdem eine Service-Richtlinie für die LIF. Weitere Informationen zu den Befehlen ^] und[`network interface service-policy create`^] finden[`network interface create` Sie in der ONTAP-Befehlsreferenz.




== Konfigurieren Sie Benutzer für die Generierung des Zugriffsschlüssels

. Geben Sie LDAP als _Name Service Database_ der Speicher-VM für die Gruppe und Passwort für LDAP an:
+
[listing]
----
ns-switch modify -vserver <vserver-name> -database group -sources files,ldap
ns-switch modify -vserver <vserver-name> -database passwd -sources files,ldap
----
+
Erfahren Sie mehr über `vserver services name-service ns-switch modify` in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-services-name-service-ns-switch-modify.html["ONTAP-Befehlsreferenz"^].

. Benutzerdefinierte Rolle mit Zugriff auf den REST-API-Endpunkt des S3-Benutzers erstellen:
`security login rest-role create -vserver <vserver-name> -role <custom-role-name> -api "/api/protocols/s3/services/*/users" -access <access-type>` In diesem Beispiel `s3-role` wird die Rolle für Benutzer auf der Storage-VM generiert `svm-1`, denen alle Zugriffsrechte, Lesen, Erstellen und Aktualisieren gewährt werden.
+
[listing]
----
security login rest-role create -vserver svm-1 -role s3role -api "/api/protocols/s3/services/*/users" -access all
----
+
Erfahren Sie mehr über `security login rest-role create` in der link:https://docs.netapp.com/us-en/ontap-cli/security-login-rest-role-create.html["ONTAP-Befehlsreferenz"^].

. Erstellen Sie eine LDAP-Benutzergruppe mit dem Befehl für die Sicherheitsanmeldung, und fügen Sie die neue benutzerdefinierte Rolle für den Zugriff auf den REST-API-Endpunkt des S3-Benutzers hinzu. Erfahren Sie mehr über `security login create` in der link:https://docs.netapp.com/us-en/ontap-cli//security-login-create.html["ONTAP-Befehlsreferenz"^].
+
[listing]
----
security login create -user-or-group-name <ldap-group-name> -application http -authentication-method nsswitch -role <custom-role-name> -is-ns-switch-group yes
----
+
In diesem Beispiel `ldap-group-1` wird die LDAP-Gruppe in erstellt `svm-1`, und die benutzerdefinierte Rolle `s3role` wird ihr für den Zugriff auf den API-Endpunkt hinzugefügt, zusammen mit der Aktivierung des LDAP-Zugriffs im Modus „Fast BIND“.

+
[listing]
----
security login create -user-or-group-name ldap-group-1 -application http -authentication-method nsswitch -role s3role -is-ns-switch-group yes -second-authentication-method none -vserver svm-1 -is-ldap-fastbind yes
----
+
Weitere Informationen finden Sie unter link:../nfs-admin/ldap-fast-bind-nsswitch-authentication-task.html["Verwenden Sie LDAP fast bind für die nswitch-Authentifizierung"].



Durch das Hinzufügen der benutzerdefinierten Rolle zur Domäne oder LDAP-Gruppe erhalten Benutzer in dieser Gruppe eingeschränkten Zugriff auf den ONTAP- `/api/protocols/s3/services/{svm.uuid}/users`Endpunkt. Durch Aufruf der API können die Benutzer der Domäne oder LDAP-Gruppe eigene Zugriffs- und geheime Schlüssel für den Zugriff auf den S3-Client generieren. Sie können die Schlüssel nur für sich selbst und nicht für andere Benutzer generieren.



== Generieren Sie als S3- oder LDAP-Benutzer eigene Zugriffsschlüssel

Ab ONTAP 9.14.1 können Sie eigene Zugriffs- und geheime Schlüssel für den Zugriff auf S3-Clients generieren, sofern Ihr Administrator Ihnen die Rolle zum Generieren eigener Schlüssel eingeräumt hat. Sie können Schlüssel nur für sich selbst generieren, indem Sie den folgenden ONTAP REST-API-Endpunkt verwenden.

.HTTP-Methode und -Endpunkt
Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt. Informationen zu den anderen Methoden dieses Endpunkts finden Sie in der Referenz https://docs.netapp.com/us-en/ontap-automation/reference/api_reference.html#access-a-copy-of-the-ontap-rest-api-reference-documentation["API-Dokumentation"].

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| POST | /API/Protokolle/s3/Services/{svm.uuid}/Benutzer 
|===
.Beispiel für die Wellung
[source, curl]
----
curl
--request POST \
--location "https://$FQDN_IP /api/protocols/s3/services/{svm.uuid}/users " \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
--data '{"name":"_name_"}'
----
.Beispiel für eine JSON-Ausgabe
[listing]
----
{
  "records": [
    {
      "access_key": "Pz3SB54G2B_6dsXQPrA5HrTPcf478qoAW6_Xx6qyqZ948AgZ_7YfCf_9nO87YoZmskxx3cq41U2JAH2M3_fs321B4rkzS3a_oC5_8u7D8j_45N8OsBCBPWGD_1d_ccfq",
      "_links": {
        "next": {
          "href": "/api/resourcelink"
        },
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "name": "user-1",
      "secret_key": "A20_tDhC_cux2C2BmtL45bXB_a_Q65c_96FsAcOdo14Az8V31jBKDTc0uCL62Bh559gPB8s9rrn0868QrF38_1dsV2u1_9H2tSf3qQ5xp9NT259C6z_GiZQ883Qn63X1"
    }
  ],
  "num_records": "1"
}

----