---
permalink: s3-config/ontap-version-support-s3-concept.html 
sidebar: sidebar 
keywords: ontap, version, support, s3, object, storage, AWS S3, Azure S3, cloud volumes ontap, aws, azure 
summary: ONTAP unterstützt S3 Objekt-Storage für On-Premises-Umgebungen ab ONTAP 9.8. Cloud Volumes ONTAP unterstützt S3-Objekt-Storage für Cloud-Umgebungen ab ONTAP 9.9.1. 
---
= ONTAP-Versionsunterstützung für S3 Objekt-Storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP unterstützt S3 Objekt-Storage für On-Premises-Umgebungen ab ONTAP 9.8. Cloud Volumes ONTAP unterstützt S3-Objekt-Storage für Cloud-Umgebungen ab ONTAP 9.9.1.



== S3-Unterstützung mit Cloud Volumes ONTAP

ONTAP S3 ist in Cloud Volumes ONTAP genauso konfiguriert und funktioniert wie in On-Premises-Umgebungen, mit einer Ausnahme:

* Die zugrunde liegenden Aggregate sollten sich nur von einem Node stammen. Weitere Informationen zu link:create-svm-s3-task.html["Bucket-Erstellung in CVO-Umgebungen"].


|===
| Cloud-Provider | ONTAP-Version 


| Azure | ONTAP 9.9.1 und höher 


| AWS | ONTAP 9.11.0 und höher 


| Google Cloud | Derzeit nicht unterstützt 
|===


== Öffentliche S3-Vorschau in ONTAP 9.7

Im ONTAP 9.7 wurde S3 Objekt-Storage als öffentliche Vorschau eingeführt. Diese Version war nicht für Produktionsumgebungen vorgesehen und wird ab ONTAP 9.8 nicht mehr aktualisiert. Nur ONTAP 9.8 und neuere Versionen unterstützen S3 Objekt-Storage in Produktionsumgebungen.

Die mit der öffentlichen Vorschau 9.7 erstellten S3-Buckets können für ONTAP 9.8 und höher verwendet werden, können jedoch nicht von Funktionsverbesserungen profitieren. Wenn bei der öffentlichen Vorschau 9.7 Buckets erstellt wurden, sollten Sie die Inhalte dieser Buckets für Funktionsunterstützung, Sicherheit und Performance-Verbesserungen in 9.8 Buckets migrieren.
