---
permalink: s3-config/ontap-s3-validated-third-party-solutions-reference.html 
sidebar: sidebar 
keywords: configuration, support, third, party, solutions 
summary: Lösungen von Drittanbietern zur Verwendung mit ONTAP S3. 
---
= Validierte Drittanbieterlösungen mit S3 in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 ist ein universeller Standard und dies ist keine umfassende Liste unterstützter Anwendungen – lediglich eine Liste von Lösungen, die in Zusammenarbeit mit den jeweiligen Partnern validiert wurden. Wenn die von Ihnen gesuchte Lösung nicht aufgeführt ist, wenden Sie sich bitte an Ihren NetApp Ansprechpartner.



== Mithilfe nativer S3-Buckets validierte Lösungen von Drittanbietern

* Amazon SageMaker
* Apache Hadoop S3A-Client
* Apache Kafka
* Apache Spark
* CommVault (V11)
* Konfluent Kafka
* NetBackup
* Red Hat Quay
* Rubrik
* Schneeflocke
* Trino
* Veeam (V12)



NOTE: Diese Lösungen werden speziell für die Verwendung nativer S3-Buckets in ONTAP validiert. Einige dieser Lösungen, z. B. im Zusammenhang mit Versionierung, Objektsperren und anderen Funktionen, werden bei der Verwendung von link:../s3-multiprotocol/index.html["S3 NAS-Buckets (S3 in Multiprotokoll-NAS-Volumes)"] .
