---
permalink: snaplock/autocommit-files-worm-task.html 
sidebar: sidebar 
keywords: snaplock, autocommit, commit, files, worm, automatically 
summary: Mit der Funktion für automatische Verschiebungsfunktion von SnapLock können Sie Dateien automatisch in DIE WORM-FUNKTION übertragen. 
---
= Automatisches Versetzen von Dateien in DIE WORM-FUNKTION
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit der Funktion für automatische Verschiebungsfunktion von SnapLock können Sie Dateien automatisch in DIE WORM-FUNKTION übertragen.

.Was Sie und#8217;ll benötigen
* Die Dateien, die automatisch übertragen werden sollen, müssen auf einem SnapLock-Volume gespeichert sein.
* Das SnapLock Volume muss online sein.
* Das SnapLock Volume muss ein Lese- und Schreib-Volume sein.


[NOTE]
====
Die Funktion Autocommit von SnapLock scannt alle Dateien auf dem Volume und begeht eine Datei, wenn sie die Anforderung für automatische Übertragung erfüllt. Es kann ein Zeitintervall zwischen dem Zeitpunkt geben, in dem die Datei für die automatische Übergabe bereit ist und dem SnapLock-Lesegerät für die automatische Übertragung tatsächlich gesetzt wird. Die Datei ist jedoch weiterhin vor Änderungen und Löschung durch das Dateisystem geschützt, sobald sie für die automatische Übertragung geeignet ist.

====
Der Zeitraum _autocommit_ gibt an, wie lange Dateien vor der automatischen Übergabe unverändert bleiben müssen. Durch Ändern einer Datei vor Ablauf des automatischen Verschiebungszeitraums wird der Zeitraum für die automatische Übertragung der Datei neu gestartet.

In der folgenden Tabelle sind die möglichen Werte für den automatischen Commit-Zeitraum aufgeführt:

|===
| Wert | Einheit | Hinweise 


 a| 
Keine
 a| 
-
 a| 
Der Standardwert.



 a| 
5 - 5256000
 a| 
Minuten
 a| 
-



 a| 
1 - 87600
 a| 
Stunden
 a| 
-



 a| 
1 - 3650
 a| 
Tage
 a| 
-



 a| 
1 - 120
 a| 
Monaten
 a| 
-



 a| 
1 - 10
 a| 
Jahren
 a| 
-

|===
[NOTE]
====
Der Mindestwert beträgt 5 Minuten und der Höchstwert beträgt 10 Jahre.

====
.Schritte
. Automatisches Versetzen von Dateien auf einem SnapLock Volume in DIE WORM-FUNKTION:
+
`*volume snaplock modify -vserver _SVM_name_ -volume _volume_name_ -autocommit-period _autocommit_period_*`

+
Eine vollständige Liste der Optionen finden Sie auf der man-Page für den Befehl.

+
Mit dem folgenden Befehl werden die Dateien auf dem Volume automatisch festgeschrieben `vol1` Der SVM vs1, sofern die Dateien 5 Stunden lang unverändert bleiben:

+
[listing]
----
cluster1::>volume snaplock modify -vserver vs1 -volume vol1 -autocommit-period 5hours
----

