---
permalink: snaplock/create-snaplock-aggregate-task.html 
sidebar: sidebar 
keywords: create, snaplock, aggregate, compliance, enterprise, mode, volumes 
summary: 'Sie verwenden die Volume- `-snaplock-type`Option, um einen Compliance- oder Enterprise SnapLock-Volume-Typ anzugeben. Bei älteren Versionen als ONTAP 9.10.1 müssen Sie ein separates SnapLock Aggregat erstellen. Ab ONTAP 9.10.1 können SnapLock- und nicht-SnapLock-Volumes auf demselben Aggregat vorhanden sein. Wenn Sie ONTAP 9.10.1 verwenden, sind Sie daher nicht mehr erforderlich, ein separates SnapLock Aggregat zu erstellen.' 
---
= Erstellen Sie ein SnapLock Aggregat
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie verwenden die Volume- `-snaplock-type`Option, um einen Compliance- oder Enterprise SnapLock-Volume-Typ anzugeben. Bei älteren Versionen als ONTAP 9.10.1 müssen Sie ein separates SnapLock Aggregat erstellen. Ab ONTAP 9.10.1 können SnapLock- und nicht-SnapLock-Volumes auf demselben Aggregat vorhanden sein. Wenn Sie ONTAP 9.10.1 verwenden, sind Sie daher nicht mehr erforderlich, ein separates SnapLock Aggregat zu erstellen.

.Bevor Sie beginnen
* Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.
* Die SnapLock link:../system-admin/install-license-task.html["Lizenz muss installiert sein"]auf dem Node. Diese Lizenz ist in enthaltenlink:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"].
* link:../snaplock/initialize-complianceclock-task.html["Die Compliance Clock auf dem Knoten muss initialisiert werden"].
* Wenn Sie die Festplatten mit „`root`“, „`data1`“ und „`data2`“ partitioniert haben, müssen Sie sicherstellen, dass Ersatzfestplatten verfügbar sind.


.Upgrade-Überlegungen
Bei einem Upgrade auf ONTAP 9.10.1 werden vorhandene SnapLock und Aggregate anderer Anbieter aktualisiert, um sowohl SnapLock als auch nicht SnapLock Volumes zu unterstützen. Die vorhandenen SnapLock Volume-Attribute werden jedoch nicht automatisch aktualisiert. So bleiben beispielsweise Felder für Data-Compaction, Volume-übergreifende Deduplizierung und Volume-übergreifende Hintergrund-Deduplizierung unverändert. Neue SnapLock Volumes, die auf vorhandenen Aggregaten erstellt wurden, verfügen über dieselben Standardwerte wie nicht-SnapLock-Volumes, und die Standardwerte für neue Volumes und Aggregate sind plattformabhängig.

.Überlegungen zurücksetzen
Wenn Sie auf eine ältere ONTAP Version als 9.10.1 zurücksetzen müssen, müssen Sie alle SnapLock-Compliance-, SnapLock Enterprise- und SnapLock-Volumes auf ihre eigenen SnapLock Aggregate verschieben.

.Über diese Aufgabe
* Mit der Option SyncMirror können keine Compliance-Aggregate erstellt werden.
* Sie können gespiegelte Compliance-Aggregate in einer MetroCluster-Konfiguration nur dann erstellen, wenn das Aggregat SnapLock-Audit-Protokoll-Volumes hostet.
+
[NOTE]
====
In einer MetroCluster-Konfiguration wird SnapLock Enterprise auf gespiegelten und nicht gespiegelten Aggregaten unterstützt. SnapLock Compliance wird nur auf nicht gespiegelten Aggregaten unterstützt.

====


.Schritte
. Erstellung eines SnapLock Aggregats:
+
[source, cli]
----
storage aggregate create -aggregate <aggregate_name> -node <node_name> -diskcount <number_of_disks> -snaplock-type <compliance|enterprise>
----
+
Mit dem folgenden Befehl wird ein SnapLock- `Compliance`Aggregat erstellt, `aggr1` das mit drei Festplatten benannt `node1` ist:

+
[listing]
----
cluster1::> storage aggregate create -aggregate aggr1 -node node1 -diskcount 3 -snaplock-type compliance
----
+
Erfahren Sie mehr über `storage aggregate create` in der link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-create.html["ONTAP-Befehlsreferenz"^].


