---
permalink: snaplock/create-snaplock-volume-task.html 
sidebar: sidebar 
keywords: snaplock, volume, shanpshot, copy, create, complianceclock, file, worm, compliance, enterprise 
summary: 'Sie müssen ein SnapLock-Volume für die Dateien oder Snapshot-Kopien erstellen, die Sie in DEN WORM-Zustand versetzen möchten. Ab ONTAP 9.10.1 wird jedes der erstellten Volumes unabhängig vom Aggregattyp standardmäßig als nicht-SnapLock Volume erstellt. Sie müssen den verwenden `-snaplock-type` Option zum explizit Erstellen eines SnapLock-Volumes, indem entweder Compliance oder Enterprise als SnapLock-Typ angegeben werden. Standardmäßig ist der SnapLock-Typ auf festgelegt `non-snaplock`.' 
---
= SnapLock Volumes erstellen und mounten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen ein SnapLock-Volume für die Dateien oder Snapshot-Kopien erstellen, die Sie in DEN WORM-Zustand versetzen möchten. Ab ONTAP 9.10.1 wird jedes der erstellten Volumes unabhängig vom Aggregattyp standardmäßig als nicht-SnapLock Volume erstellt. Sie müssen den verwenden `-snaplock-type` Option zum explizit Erstellen eines SnapLock-Volumes, indem entweder Compliance oder Enterprise als SnapLock-Typ angegeben werden. Standardmäßig ist der SnapLock-Typ auf festgelegt `non-snaplock`.

.Bevor Sie beginnen
* Das SnapLock Aggregat muss online sein.
* Sollten Sie https://docs.netapp.com/us-en/ontap/system-admin/manage-license-task.html["Vergewissern Sie sich, dass eine SnapLock-Lizenz installiert ist"]. Wenn auf dem Node keine SnapLock-Lizenz installiert ist, müssen Sie diese ausführen https://docs.netapp.com/us-en/ontap/system-admin/install-license-task.html["Installieren"] Es. Diese Lizenz ist in enthalten https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["ONTAP One"]. Vor ONTAP One war die SnapLock-Lizenz im Paket für Sicherheit und Compliance enthalten. Das Paket „Sicherheit und Compliance“ wird nicht mehr angeboten, ist aber weiterhin gültig. Bestehende Kunden können diese Option wählen, obwohl sie derzeit nicht benötigt werden https://docs.netapp.com/us-en/ontap/system-admin/download-nlf-task.html["Upgrade auf ONTAP One"].
* link:https://docs.netapp.com/us-en/ontap/snaplock/initialize-complianceclock-task.html["Die Compliance Clock auf dem Knoten muss initialisiert werden"].


.Über diese Aufgabe
Mit den entsprechenden SnapLock Berechtigungen können Sie ein Enterprise-Volume jederzeit zerstören oder umbenennen. Sie können ein Compliance-Volumen erst zerstören, wenn der Aufbewahrungszeitraum abgelaufen ist. Ein Compliance-Volume kann nie umbenannt werden.

Sie können SnapLock Volumes klonen, aber Sie können keine Dateien auf einem SnapLock Volume klonen. Das geklonte Volume hat den gleichen SnapLock-Typ wie das übergeordnete Volume.

[NOTE]
====
LUNs werden in SnapLock Volumes nicht unterstützt. LUNs werden in SnapLock Volumes nur in Szenarien unterstützt, in denen auf einem nicht-SnapLock Volume erstellte Snapshot Kopien zur Sicherung im Rahmen der SnapLock Vault-Beziehung auf ein SnapLock Volume übertragen werden. LUNs werden in SnapLock-Volumes mit Lese-/Schreibzugriff nicht unterstützt. Manipulationssichere Snapshot Kopien werden jedoch auf SnapMirror Quell-Volumes und Ziel-Volumes unterstützt, die LUNs enthalten.

====
Führen Sie diese Aufgabe über ONTAP System Manager oder die ONTAP-CLI aus.

[role="tabbed-block"]
====
.System Manager
--
Ab ONTAP 9.12.1 können Sie mit System Manager ein SnapLock Volume erstellen.

.Schritte
. Navigieren Sie zu *Storage > Volumes* und klicken Sie auf *Hinzufügen*.
. Klicken Sie im Fenster *Volume hinzufügen* auf *Weitere Optionen*.
. Geben Sie die neuen Volume-Informationen ein, einschließlich Name und Größe des Volumes.
. Wählen Sie *SnapLock aktivieren* und wählen Sie den SnapLock-Typ entweder Compliance oder Enterprise.
. Wählen Sie im Abschnitt *Auto-Commit Files* die Option *Modified* aus und geben Sie den Zeitraum ein, in dem eine Datei unverändert bleiben soll, bevor sie automatisch aktiviert wird. Der Mindestwert beträgt 5 Minuten und der Höchstwert beträgt 10 Jahre.
. Wählen Sie im Abschnitt *Datenspeicherung* den minimalen und maximalen Aufbewahrungszeitraum aus.
. Wählen Sie den Standardaufbewahrungszeitraum aus.
. Klicken Sie Auf *Speichern*.
. Wählen Sie auf der Seite *Volumes* das neue Volume aus, um die SnapLock-Einstellungen zu überprüfen.


--
.CLI
--
. SnapLock Volume erstellen:
+
[source, cli]
----
volume create -vserver <SVM_name> -volume <volume_name> -aggregate <aggregate_name> -snaplock-type <compliance|enterprise>
----
+
Eine vollständige Liste der Optionen finden Sie auf der man-Page für den Befehl. Die folgenden Optionen sind für SnapLock Volumes nicht verfügbar: `-nvfail`, `-atime-update`, `-is-autobalance-eligible`, `-space-mgmt-try-first`, und `vmalign`.

+
Mit dem folgenden Befehl wird eine SnapLock erstellt `Compliance` Volume mit Namen `vol1` Ein `aggr1` Ein `vs1`:

+
[listing]
----
cluster1::> volume create -vserver vs1 -volume vol1 -aggregate aggr1 -snaplock-type compliance
----


--
====


== Mounten Sie ein SnapLock Volume

Ein SnapLock Volume kann für den NAS-Client-Zugriff im SVM Namespace an einen Verbindungspfad gemountet werden.

.Was Sie benötigen
Das SnapLock Volume muss online sein.

.Über diese Aufgabe
* Ein SnapLock Volume kann nur unter dem Root-Verzeichnis der SVM gemountet werden.
* Ein normales Volume kann nicht unter einem SnapLock Volume gemountet werden.


.Schritte
. Mounten eines SnapLock Volume:
+
`*volume mount -vserver _SVM_name_ -volume _volume_name_ -junction-path _path_*`

+
Eine vollständige Liste der Optionen finden Sie auf der man-Page für den Befehl.

+
Mit dem folgenden Befehl wird ein SnapLock-Volume mit dem Namen gemountet `vol1` Zum Verbindungspfad `/sales` Im `vs1` Namespace:

+
[listing]
----
cluster1::> volume mount -vserver vs1 -volume vol1 -junction-path /sales
----

