---
permalink: snaplock/create-worm-appendable-file-task.html 
sidebar: sidebar 
keywords: command, program, create, worm, appendable, file, nfs, cifs, chunk 
summary: Sie können jeden entsprechenden Befehl oder Programm über NFS oder CIFS verwenden, um eine WORM-Datei zu erstellen. In einer ANGEHÄNGBAREN WORM-Datei werden die Daten, die inkrementell geschrieben werden, wie Protokolleinträge. Die Daten werden in 256-KB-Blöcken an die Datei angehängt. Wenn jeder Datenblock geschrieben wird, wird der vorherige Datenblock ALS WORM-geschützt. Sie können die Datei erst löschen, wenn der Aufbewahrungszeitraum abgelaufen ist. 
---
= Verwenden Sie einen Befehl oder ein Programm, um eine WORM-Datei zu erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können jeden entsprechenden Befehl oder Programm über NFS oder CIFS verwenden, um eine WORM-Datei zu erstellen. In einer ANGEHÄNGBAREN WORM-Datei werden die Daten, die inkrementell geschrieben werden, wie Protokolleinträge. Die Daten werden in 256-KB-Blöcken an die Datei angehängt. Wenn jeder Datenblock geschrieben wird, wird der vorherige Datenblock ALS WORM-geschützt. Sie können die Datei erst löschen, wenn der Aufbewahrungszeitraum abgelaufen ist.

Die angehängbare WORM-Datei muss sich auf einem SnapLock Volume befinden.

Die Daten müssen nicht sequenziell in den aktiven 256-KB-Datenblock geschrieben werden. Wenn Daten in Byte n×256 KB+1 der Datei geschrieben werden, wird das vorherige 256-KB-Segment ALS WORM-geschützt.

.Schritte
. Verwenden Sie einen geeigneten Befehl oder ein geeignetes Programm, um eine Datei mit der gewünschten Aufbewahrungszeit zu erstellen.
+
Verwenden Sie in einer UNIX-Shell den folgenden Befehl, um eine Aufbewahrungszeit vom 21. November 2020 6:00 Uhr festzulegen In einer Datei mit dem Namen Null-Länge `document.txt`:

+
[listing]
----
touch -a -t 202011210600 document.txt
----
. Verwenden Sie einen geeigneten Befehl oder ein geeignetes Programm, um das Lese-Schreib-Attribut der Datei in schreibgeschützt zu ändern.
+
Verwenden Sie in einer UNIX-Shell den folgenden Befehl, um eine Datei mit dem Namen zu erstellen `document.txt` Schreibgeschützt:

+
[listing]
----
chmod 444 document.txt
----
. Verwenden Sie einen geeigneten Befehl oder ein geeignetes Programm, um das Lese-Schreib-Attribut der Datei wieder in beschreibbar zu ändern.
+
[NOTE]
====
Dieser Schritt gilt nicht als Compliance-Risiko, da sich keine Daten in der Datei befinden.

====
+
Verwenden Sie in einer UNIX-Shell den folgenden Befehl, um eine Datei mit dem Namen zu erstellen `document.txt` Beschreibbar:

+
[listing]
----
chmod 777 document.txt
----
. Verwenden Sie einen geeigneten Befehl oder ein geeignetes Programm, um mit dem Schreiben von Daten in die Datei zu beginnen.
+
Verwenden Sie in einer UNIX-Shell den folgenden Befehl, um Daten in zu schreiben `document.txt`:

+
[listing]
----
echo test data >> document.txt
----
+
[NOTE]
====
Ändern Sie die Dateiberechtigungen zurück in den schreibgeschützten Bereich, wenn Sie keine Daten mehr an die Datei anhängen müssen.

====

