---
permalink: snaplock/create-audit-log-task.html 
sidebar: sidebar 
keywords: create, audit, log, snaplock, protected, administrator, accounts 
summary: Ein durch SnapLock geschütztes Revisionsprotokoll muss erstellt werden, bevor ein privilegierter Löschvorgang oder eine SnapLock Volume-Verschiebung durchgeführt wird. Das Revisionsprotokoll zeichnet die Erstellung und Löschung von SnapLock Administratorkonten, Änderungen am Protokollvolume, ob privilegierter Löschvorgang aktiviert ist, privilegierte Löschvorgänge sowie SnapLock Volume-Verschiebungen auf. 
---
= Ein ONTAP SnapLock-geschütztes Revisionsprotokoll erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei Verwendung von ONTAP 9.9.1 oder älter ist zunächst ein SnapLock Aggregat zu erstellen und anschließend ein SnapLock-geschütztes Revisionsprotokoll, bevor ein privilegierter Löschvorgang oder eine SnapLock Volume-Verschiebung durchgeführt wird. Das Revisionsprotokoll zeichnet die Erstellung und Löschung von SnapLock Administratorkonten, Änderungen am Protokollvolume, ob privilegierter Löschvorgang aktiviert ist, privilegierte Löschvorgänge sowie SnapLock Volume-Verschiebungen auf.

Ab ONTAP 9.10.1 wird kein SnapLock Aggregat mehr erstellt. Die Option -snaplock-type muss verwendet werden, link:../snaplock/create-snaplock-volume-task.html["explizit ein SnapLock Volume erstellen"] indem entweder Compliance oder Enterprise als SnapLock Typ angegeben wird.

.Bevor Sie beginnen
Wenn Sie ONTAP 9.9.1 oder eine frühere Version verwenden, ist die Rolle als Cluster-Administrator erforderlich, um ein SnapLock Aggregat zu erstellen.

.Über diese Aufgabe
Ein Revisionsprotokoll kann erst nach Ablauf der Aufbewahrungsfrist gelöscht werden. Ein Revisionsprotokoll kann auch nach Ablauf der Aufbewahrungsfrist nicht mehr geändert werden. Dies gilt sowohl für den SnapLock Compliance- als auch für den Enterprise-Modus.

[NOTE]
====
In ONTAP 9.4 und früher kann ein SnapLock Enterprise Volume nicht für die Revisionsprotokollierung verwendet werden. Es muss ein SnapLock Compliance Volume verwendet werden. In ONTAP 9.5 und später kann entweder ein SnapLock Enterprise Volume oder ein SnapLock Compliance Volume für die Revisionsprotokollierung verwendet werden. In allen Fällen muss das Revisionsprotokoll-Volume am Verbindungspfad `/snaplock_audit_log` eingebunden sein. Kein anderes Volume kann diesen Verbindungspfad verwenden.

====
Die SnapLock Revisionsprotokolle befinden sich im  `/snaplock_log` Verzeichnis unter dem Stammverzeichnis des Revisionsprotokoll-Volumes, in Unterverzeichnissen mit den Namen  `privdel_log` (privilegierte Löschvorgänge) und  `system_log` (alles andere). Die Dateinamen der Revisionsprotokolle enthalten den Zeitstempel des ersten protokollierten Vorgangs, was die Suche nach Einträgen anhand des ungefähren Ausführungszeitpunkts der Vorgänge erleichtert.

* Mit dem  `snaplock log file show` Befehl lassen sich die Protokolldateien auf dem Revisionsprotokoll Volume anzeigen.
* Der  `snaplock log file archive` Befehl kann verwendet werden, um die aktuelle Protokolldatei zu archivieren und eine neue zu erstellen, was in Fällen nützlich ist, in denen Revisionsprotokollinformationen in einer separaten Datei aufgezeichnet werden müssen.


Weitere Informationen zu  `snaplock log file show` und  `snaplock log file archive` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=snaplock+log+file["ONTAP-Befehlsreferenz"^].

[NOTE]
====
Ein Datensicherungsvolume kann nicht als SnapLock Revisionsprotokollvolume verwendet werden.

====
.Schritte
. Ein SnapLock Aggregat erstellen.
+
xref:create-snaplock-aggregate-task.adoc[Ein SnapLock Aggregat erstellen]

. Erstellen Sie auf der SVM, die für die Revisionsprotokollierung konfiguriert werden soll, ein SnapLock Volume.
+
xref:create-snaplock-volume-task.adoc[Ein SnapLock Volume erstellen]

. Die SVM für die Revisionsprotokollierung konfigurieren:
+
`snaplock log create -vserver _SVM_name_ -volume _snaplock_volume_name_ -max-log-size _size_ -retention-period _default_retention_period_`

+
[NOTE]
====
Die standardmäßige Mindestaufbewahrungsdauer für Revisionsprotokoll-Dateien beträgt sechs Monate. Ist die Aufbewahrungsdauer einer betroffenen Datei länger als die Aufbewahrungsdauer des Revisionsprotokolls, übernimmt die Aufbewahrungsdauer des Protokolls die Aufbewahrungsdauer der Datei. Wenn die Aufbewahrungsdauer einer mit privilegiertem Löschen entfernten Datei beispielsweise zehn Monate beträgt und die Aufbewahrungsdauer des Revisionsprotokolls acht Monate beträgt, wird die Aufbewahrungsdauer des Protokolls auf zehn Monate verlängert. Weitere Informationen zur Aufbewahrungszeit und zur standardmäßigen Aufbewahrungsdauer finden sich unter link:../snaplock/set-retention-period-task.html["Aufbewahrungszeit festlegen"].

====
+
Der folgende Befehl konfiguriert `SVM1` die Protokollierung mithilfe des SnapLock Volumes `logVol`. Das Revisionsprotokoll hat eine maximale Größe von 20 GB und wird acht Monate lang aufbewahrt.

+
[listing]
----
SVM1::> snaplock log create -vserver SVM1 -volume logVol -max-log-size 20GB -retention-period 8months
----
+
Weitere Informationen zu  `snaplock log create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/snaplock-log-create.html["ONTAP-Befehlsreferenz"^].

. Auf der SVM, die für die Protokollierung konfiguriert wurde, das SnapLock-Volume am Verbindungspfad  `/snaplock_audit_log` einbinden.
+
xref:mount-snaplock-volume-task.adoc[Ein SnapLock Volume einbinden]


