---
permalink: snaplock/create-snaplock-security-administrator-account-task.html 
sidebar: sidebar 
keywords: create, snaplock, security, administrator, support, volume, move, user, cluster, role 
summary: Zum Verschieben eines SnapLock Volumes müssen Sie über SnapLock-Sicherheitsadministratorrechte verfügen. Diese Berechtigung erhalten Sie mit der im ONTAP 9.8 eingeführten SnapLock-Rolle. Wenn Sie dieser Rolle noch nicht zugewiesen wurden, können Sie den Cluster-Administrator bitten, einen SnapLock-Sicherheitsbenutzer mit dieser SnapLock-Sicherheitsrolle zu erstellen. 
---
= Erstellen Sie ein SnapLock-Sicherheitsadministratorkonto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zum Verschieben eines SnapLock Volumes müssen Sie über SnapLock-Sicherheitsadministratorrechte verfügen. Dieses Privileg wird Ihnen mit der im ONTAP 9.8 eingeführten _SnapLock_-Rolle gewährt. Wenn Sie dieser Rolle noch nicht zugewiesen wurden, können Sie den Cluster-Administrator bitten, einen SnapLock-Sicherheitsbenutzer mit dieser SnapLock-Sicherheitsrolle zu erstellen.

.Was Sie und#8217;ll benötigen
* Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.
* Sie müssen sich mit einer sicheren Verbindung (SSH, Konsole oder ZAPI) angemeldet haben.


die SnapLock-Rolle ist mit der Admin-SVM verbunden – im Gegensatz zur vsadmin-snaplock-Rolle, die mit der Daten-SVM verknüpft ist.

.Schritt
. SVM-Administratorkonto mit der SnapLock-Administratorrolle erstellen:
+
`*security login create -vserver _SVM_name_ -user-or-group-name _user_or_group_name_ -application _application_ -authmethod _authentication_method_ -role _role_ -comment _comment_*`

+
Mit dem folgenden Befehl wird das SVM-Administratorkonto aktiviert `SnapLockAdmin` Mit dem vordefinierten `snaplock` Rolle für den Zugriff auf Admin-SVM `cluster1` Verwenden eines Passworts:

+
[listing]
----
cluster1::> security login create -vserver cluster1 -user-or-group-name SnapLockAdmin -application ssh -authmethod password -role snaplock
----

