---
permalink: snaplock/implement-privileged-delete-functionality-task.html 
sidebar: sidebar 
keywords: delete, worm, file, priveleged, delete, enterprise, mode, retention, period 
summary: Mit der Funktion Priviledged delete können SIE WORM-Dateien im Enterprise-Modus während des Aufbewahrungszeitraums löschen. 
---
= LÖSCHEN SIE WORM-Dateien mit privilegierter Löschung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit der Funktion Priviledged delete können SIE WORM-Dateien im Enterprise-Modus während des Aufbewahrungszeitraums löschen.

.Was Sie und#8217;ll benötigen
* Sie müssen ein SnapLock-Administrator sein, um diese Aufgabe auszuführen.
* Sie müssen ein SnapLock-Auditprotokoll erstellt und die Funktion zum Löschen von Berechtigungen auf dem Enterprise Volume aktiviert haben.


Sie können eine abgelaufene WORM-Datei nicht mit einem privilegierten Löschvorgang löschen. Sie können das verwenden `volume file retention show` Befehl zum Anzeigen der Aufbewahrungszeit der WORM-Datei, die Sie löschen möchten. Weitere Informationen finden Sie auf der man-Page für den Befehl.

.Schritt
. LÖSCHEN EINER WORM-Datei auf einem Enterprise Volume:
+
`*volume file privileged-delete -vserver _SVM_name_ -file _file_path_*`

+
Mit dem folgenden Befehl wird die Datei gelöscht `/vol/dataVol/f1` Auf der SVM``SVM1``:

+
[listing]
----
SVM1::> volume file privileged-delete -file /vol/dataVol/f1
----

