---
permalink: snaplock/index.html 
sidebar: sidebar 
keywords: decide, archive, compliance, snaplock, unmodified, file, worm, storage, snap lock, mirror, unmirror. license, compliance clock, regulatory, governance, rules, govern 
summary: Mithilfe der NetApp SnapLock Technologie können Dateien zu regulatorischen und Governance-Zwecken in unveränderter Form aufbewahrt werden. 
---
= Archivierung und Compliance: Überblick
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mithilfe der NetApp SnapLock Technologie können Dateien zu regulatorischen und Governance-Zwecken in unveränderter Form aufbewahrt werden. Es zeigt, wie Sie Dateien und Snapshot Kopien in WORM-Storage („write once, read many``“) übertragen und wie Sie Aufbewahrungszeiträume für WORM-geschützte Daten festlegen.

Sie sollten diese Verfahren verwenden, wenn Sie mit SnapLock auf folgende Weise arbeiten möchten:

* Sie möchten die ONTAP Befehlszeilenschnittstelle (CLI) verwenden, nicht System Manager oder ein automatisiertes Scripting Tool.
+
System Manager bietet eine begrenzte, aber wichtige SnapLock Technologie. Sie können SnapLock Lizenzen installieren, die Compliance-Uhr festlegen, SnapLock Aggregate und Volumes erstellen und SnapLock Volumes konfigurieren.

* Sie möchten Compliance- oder Enterprise-Aggregate erstellen, um SnapLock-Auditprotokoll-Volumes auf MetroCluster-Konfigurationen zu hosten, wobei folgende Einschränkung gilt:
+
** SnapLock Enterprise wird auf gespiegelten und nicht gespiegelten Aggregaten unterstützt.
** SnapLock Compliance wird nur auf nicht gespiegelten Aggregaten unterstützt.
+
Alle MetroCluster-Konfigurationen unterstützen gespiegelte Aggregate. Siehe link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Versionshinweise zu ONTAP"] Um festzustellen, ob Ihre MetroCluster Konfiguration nicht gespiegelte Aggregate unterstützt.



* Sie möchten SnapLock Enterprise-Aggregate mit FabricPool verwenden.
+
Ab ONTAP 9.8 werden SnapLock Enterprise Aggregate mit unterstützt link:https://docs.netapp.com/us-en/ontap/fabricpool/index.html["FabricPool"].

* Sie verwenden keine SAN-LUNs
+
SAN LUNs werden auf SnapLock Volumes nicht unterstützt. Obwohl es möglich ist, SAN-LUNs mithilfe älterer Technologie auf ein SnapLock Volume zu verschieben, wird dieser Vorgang nicht unterstützt, noch ist ein anderer Vorgang, der SAN-LUNs auf einem SnapLock Volume betrifft.

* Sie verwenden SMTape nicht.
+
SMTape wird von SnapLock nicht unterstützt.

* Sie erstellen keine Compliance-Aggregate für Array LUNs.
+
SnapLock Compliance-Aggregate unterstützen keine Array-LUNs.

* Sie erstellen mit der Option SyncMirror keine Compliance-Aggregate.
+
SnapLock Compliance-Aggregate unterstützen keine SyncMirror-Plexe.



[NOTE]
====
SSDs und Flash Pool Aggregate werden von SnapLock ab ONTAP 9.1 unterstützt.

====