---
permalink: snaplock/initialize-complianceclock-task.html 
sidebar: sidebar 
keywords: snaplock, complianceclock, compliance clock, initialize, worm, retention, period, node, ntp, reset, resynchronize 
summary: Die SnapLock ComplianceClock sorgt für Manipulationen, die die Aufbewahrungsfrist für WORM-Dateien ändern können. Sie müssen die Compliance-Uhr des Systems auf jedem Node, der ein SnapLock Aggregat hostet, initialisieren. 
---
= Initialisieren der ONTAP Compliance Clock
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapLock verwendet die _Volume Compliance Clock_, um sicherzustellen, dass sich die Aufbewahrungsfrist für WORM-Dateien ändern kann. Sie müssen zuerst auf jedem Knoten, der ein SnapLock-Aggregat hostet, das _System ComplianceClock_ initialisieren.

Ab ONTAP 9.14.1 können Sie die System Compliance Clock initialisieren oder neu initialisieren, wenn keine SnapLock-Volumes oder keine Volumes mit aktivierter Snapshot-Sperre vorhanden sind. Die Möglichkeit zur Neuinitialisierung ermöglicht es Systemadministratoren, die System Compliance Clock in Fällen zurückzusetzen, in denen sie möglicherweise falsch initialisiert wurde oder um eine Taktabweichung im System zu korrigieren. In ONTAP 9.13.1 und früheren Versionen können Sie die Compliance Clock nach der Initialisierung auf einem Node nicht erneut initialisieren.

.Bevor Sie beginnen
So initialisieren Sie die Compliance-Uhr neu:

* Alle Nodes im Cluster müssen sich in einem ordnungsgemäßen Zustand befinden.
* Alle Volumes müssen online sein.
* In der Wiederherstellungswarteschlange dürfen keine Volumes vorhanden sein.
* Es können keine SnapLock Volumes vorhanden sein.
* Es können keine Volumes mit aktivierter Snapshot-Sperrung vorhanden sein.


Allgemeine Anforderungen für die Initialisierung der Compliance Clock:

* Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.
* link:../system-admin/install-license-task.html["Die SnapLock-Lizenz muss auf dem Knoten installiert sein"].


.Über diese Aufgabe
Die Zeit auf dem System Compliance Clock wird von der _Volume Compliance Clock_ übernommen, von der Letzteres die Aufbewahrungsfrist für WORM-Dateien auf dem Volume steuert. Die Volume-Compliance-Uhr wird automatisch initialisiert, wenn Sie ein neues SnapLock-Volume erstellen.

[NOTE]
====
Die anfängliche Einstellung der System-Compliance-Uhr basiert auf der aktuellen Hardware-Systemuhr. Daher sollten Sie vor der Initialisierung der System-Compliance-Uhr auf jedem Knoten überprüfen, ob Systemzeit und Zeitzone korrekt sind. Nachdem Sie die System-Compliance-Uhr auf einem Knoten initialisiert haben, können Sie sie nicht erneut initialisieren, wenn SnapLock-Volumes oder Volumes mit aktivierter Sperrung vorhanden sind.

====
.Schritte
Sie können die ONTAP-CLI verwenden, um die Compliance-Uhr zu initialisieren, oder Sie können ab ONTAP 9.12.1 die Compliance-Uhr mit dem System-Manager initialisieren.

[role="tabbed-block"]
====
.System Manager
--
. Navigieren Sie zu *Cluster > Übersicht*.
. Wählen Sie im Abschnitt *Knoten* die Option *SnapLock Compliance-Uhr initialisieren*.
. Um die Spalte *Compliance Clock* anzuzeigen und zu überprüfen, ob die Compliance Clock initialisiert ist, wählen Sie im Abschnitt *Cluster > Übersicht > Knoten* die Option *Anzeigen/Ausblenden* und wählen Sie *SnapLock Compliance Clock*.


--
--
.CLI
. Initialisieren Sie die System-Compliance-Uhr:
+
`snaplock compliance-clock initialize -node _node_name_`

+
Mit dem folgenden Befehl wird die Systemkonformität-Uhr initialisiert auf `node1`:

+
[listing]
----
cluster1::> snaplock compliance-clock initialize -node node1
----
+
Erfahren Sie mehr über `snaplock compliance-clock initialize` in der link:https://docs.netapp.com/us-en/ontap-cli/snaplock-compliance-clock-initialize.html["ONTAP-Befehlsreferenz"^].

. Wenn Sie dazu aufgefordert werden, bestätigen Sie, dass die Systemuhr korrekt ist und dass Sie die Compliance-Uhr initialisieren möchten:
+
[listing]
----
Warning: You are about to initialize the secure ComplianceClock of
the node "node1" to the current value of the node's system clock.
This procedure can be performed only once on a given node, so you
should ensure that the system time is set correctly before proceeding.

The current node's system clock is: Mon Apr 25 06:04:10 GMT 2016

Do you want to continue? (y|n): y
----
. Wiederholen Sie diese Vorgehensweise für jeden Node, der ein SnapLock Aggregat hostet.


--
====


== Aktivieren Sie die Neusynchronisierung der Compliance Clock für ein NTP-konfiguriertes System

Sie können die SnapLock Compliance Clock-Synchronisierungsfunktion aktivieren, wenn ein NTP-Server konfiguriert ist.

.Bevor Sie beginnen
* Diese Funktion ist nur auf der erweiterten Berechtigungsebene verfügbar.
* Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.
* link:../system-admin/install-license-task.html["Die SnapLock-Lizenz muss auf dem Knoten installiert sein"].
* Diese Funktion ist nur für Cloud Volumes ONTAP-, ONTAP Select- und VSIM-Plattformen verfügbar.


.Über diese Aufgabe
Wenn der SnapLock secure clock daemon eine Abweichung über dem Schwellenwert feststellt, verwendet ONTAP die Systemzeit, um sowohl die System- als auch die Volume Compliance Clocks zurückzusetzen. Ein Zeitraum von 24 Stunden ist als Schwellenwert für die Abweichung festgelegt. Die System Compliance Clock synchronisiert sich nur mit der Systemzeit, wenn die Abweichung mehr als einen Tag alt ist.

Der SnapLock Secure Clock Daemon erkennt eine Zeitabweichung und ändert die Compliance Clock auf die Systemzeit. Jeder Versuch, die Systemzeit zu ändern, um die Compliance Clock zur Synchronisierung mit der Systemzeit zu zwingen, schlägt fehl, da die Compliance Clock nur dann mit der Systemzeit synchronisiert wird, wenn die Systemzeit mit der NTP-Zeit synchronisiert ist.

.Schritte
. Aktivieren Sie die SnapLock Compliance Clock-Synchronisierungsfunktion, wenn ein NTP-Server konfiguriert ist:
+
`snaplock compliance-clock ntp`

+
Der folgende Befehl aktiviert die Synchronisierungsfunktion der Compliance Clock des Systems:

+
[listing]
----
cluster1::*> snaplock compliance-clock ntp modify -is-sync-enabled true
----
+
Erfahren Sie mehr über `snaplock compliance-clock ntp modify` in der link:https://docs.netapp.com/us-en/ontap-cli/snaplock-compliance-clock-ntp-modify.html["ONTAP-Befehlsreferenz"^].

. Bestätigen Sie bei der entsprechenden Aufforderung, dass die konfigurierten NTP-Server vertrauenswürdig sind und der Kommunikationskanal sicher ist, um die Funktion zu aktivieren:
. Überprüfen Sie, ob die Funktion aktiviert ist:
+
`snaplock compliance-clock ntp show`

+
Der folgende Befehl überprüft, ob die Synchronisierungsfunktion der System-Compliance-Uhr aktiviert ist:

+
[listing]
----
cluster1::*> snaplock compliance-clock ntp show

Enable clock sync to NTP system time: true
----
+
Erfahren Sie mehr über `snaplock compliance-clock ntp show` in der link:https://docs.netapp.com/us-en/ontap-cli/snaplock-compliance-clock-ntp-show.html["ONTAP-Befehlsreferenz"^].


