---
permalink: snaplock/initialize-complianceclock-task.html 
sidebar: sidebar 
keywords: snaplock, complianceclock, initialize, worm, retention, period, node, ntp, reset, resynchronize 
summary: Die SnapLock ComplianceClock sorgt für Manipulationen, die die Aufbewahrungsfrist für WORM-Dateien ändern können. Sie müssen die CompleceClock des Systems auf jedem Knoten initialisieren, der ein SnapLock-Aggregat hostet. Sobald Sie die ComplexClock auf einem Knoten initialisiert haben, können Sie sie nicht erneut initialisieren. 
---
= Initialisieren Sie die ComplianceClock
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die SnapLock ComplianceClock sorgt für Manipulationen, die die Aufbewahrungsfrist für WORM-Dateien ändern können. Sie müssen auf jedem Knoten, der ein SnapLock-Aggregat hostet, die ComplexClock _System ComplianceClock_ initialisieren. Sobald Sie die ComplexClock auf einem Knoten initialisiert haben, können Sie sie nicht erneut initialisieren.

.Was Sie benötigen
* Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.
* Die SnapLock-Lizenz muss auf dem Node installiert sein.


.Über diese Aufgabe
Die Zeit auf dem System ComplexanceClock wird durch das _Volume ComplexanceClock_ geerbt, welches die Aufbewahrungsfrist für WORM-Dateien auf dem Volume steuert. Der Datenträger ComplexanceClock wird automatisch initialisiert, wenn Sie ein neues SnapLock Volume erstellen.

[NOTE]
====
Die Ersteinstellung der ComplexanceClock basiert auf der aktuellen Systemuhr. Aus diesem Grund sollten Sie überprüfen, ob die Systemzeit und die Zeitzone korrekt sind, bevor Sie die ComplianceClock initialisieren. Sobald Sie die ComplexClock auf einem Knoten initialisiert haben, können Sie sie nicht erneut initialisieren.

====
[role="tabbed-block"]
====
.System Manager
--
Ab ONTAP 9.12.1 können Sie mit System Manager die SnapLock-Compliance-Uhr initialisieren.

.Schritte
. Navigieren Sie zu *Cluster > Übersicht*.
. Klicken Sie im Abschnitt *Knoten* auf *SnapLock-Konformitätsuhr initialisieren*.
. Um die Spalte „Compliance Clock“ anzuzeigen und zu überprüfen, ob die Compliance Clock initialisiert ist, klicken Sie im Abschnitt *Cluster > Übersicht > Knoten* auf *ein-/Ausblenden* und wählen Sie *SnapLock Compliance Clock*.


--
--
.CLI
. Initialisieren Sie das System ComplianceClock:
+
`*snaplock compliance-clock initialize -node _node_name_*`

+
Mit dem folgenden Befehl wird das System ComplianceClock ON initialisiert `node1`:

+
[listing]
----
cluster1::> snaplock compliance-clock initialize -node node1
----
. Wenn Sie dazu aufgefordert werden, bestätigen Sie, dass die Systemuhr korrekt ist und Sie die ComplianceClock initialisieren möchten:
+
[listing]
----
Warning: You are about to initialize the secure ComplianceClock of
the node "node1" to the current value of the node's system clock.
This procedure can be performed only once on a given node, so you
should ensure that the system time is set correctly before proceeding.

The current node's system clock is: Mon Apr 25 06:04:10 GMT 2016

Do you want to continue? (y|n): y
----
. Wiederholen Sie diese Vorgehensweise für jeden Node, der ein SnapLock Aggregat hostet.


--
====


== Aktivieren Sie die Resynchronisierung der ComplianceClock-Synchronisierung für ein NTP-konfiguriertes System

Wenn ein NTP-Server konfiguriert ist, können Sie die SnapLock CommianceClock-Zeitsynchronisation aktivieren.

.Was Sie benötigen
* Diese Funktion ist nur auf der erweiterten Berechtigungsebene verfügbar.
* Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.
* Die SnapLock-Lizenz muss auf dem Node installiert sein.
* Diese Funktion ist nur für Cloud Volumes ONTAP-, ONTAP Select- und VSIM-Plattformen verfügbar.


.Über diese Aufgabe
Wenn der SnapLock Secure Clock Daemon eine Schräglage über den Schwellenwert hinaus erkennt, verwendet ONTAP die Systemzeit, um sowohl das System als auch die Complexe des Volumes zurückzusetzen. Als Schwellwert wird ein Zeitraum von 24 Stunden festgelegt. Das bedeutet, dass das System ComplexClock nur dann mit der Systemuhr synchronisiert wird, wenn die Skew mehr als einen Tag alt ist.

Der SnapLock Secure Clock Daemon erkennt eine Schräglage und ändert die ComplexanceClock in die Systemzeit. Jeder Versuch, die Systemzeit zu ändern, um die ComplexceClock zu zwingen, mit der Systemzeit zu synchronisieren, schlägt fehl, da die CommianceClock nur dann mit der Systemzeit synchronisiert wird, wenn die Systemzeit mit der NTP-Zeit synchronisiert wird.

.Schritte
. Aktivieren Sie die SnapLock ComplianceClock-Zeitsynchronisierung, wenn ein NTP-Server konfiguriert ist:
+
`*snaplock compliance-clock ntp*`

+
Mit dem folgenden Befehl wird die Systemfunktion CommianceClock Time synchronisiert:

+
[listing]
----
cluster1::*> snaplock compliance-clock ntp modify -is-sync-enabled true
----
. Bestätigen Sie bei der entsprechenden Aufforderung, dass die konfigurierten NTP-Server vertrauenswürdig sind und der Kommunikationskanal sicher ist, um die Funktion zu aktivieren:
. Überprüfen Sie, ob die Funktion aktiviert ist:
+
`*snaplock compliance-clock ntp show*`

+
Mit dem folgenden Befehl wird überprüft, ob die Funktion zur Synchronisierung der Systemzeit CommianceClock aktiviert ist:

+
[listing]
----
cluster1::*> snaplock compliance-clock ntp show

Enable clock sync to NTP system time: true
----

