---
permalink: snaplock/move-snaplock-volume-concept.html 
sidebar: sidebar 
keywords: move, snaplock, volume, aggregate, security, role, enterprise, compliance, create, administrator, support, user, cluster, destination, command 
summary: 'Ab ONTAP 9.8 können Sie ein SnapLock Volume zu einem Zielaggregat desselben Typs verschieben: Von Enterprise zu Enterprise oder Compliance zu Compliance. Zum Verschieben eines SnapLock Volumes muss Ihnen die SnapLock-Sicherheitsrolle zugewiesen werden.' 
---
= Verschieben eines ONTAP SnapLock -Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.8 können Sie ein SnapLock Volume zu einem Zielaggregat desselben Typs verschieben: Von Enterprise zu Enterprise oder Compliance zu Compliance. Zum Verschieben eines SnapLock Volumes muss Ihnen die SnapLock-Sicherheitsrolle zugewiesen werden.



== Erstellen Sie ein SnapLock-Sicherheitsadministratorkonto

Zum Verschieben eines SnapLock Volumes müssen Sie über SnapLock-Sicherheitsadministratorrechte verfügen. Dieses Privileg wird Ihnen mit der im ONTAP 9.8 eingeführten _SnapLock_-Rolle gewährt. Wenn Sie dieser Rolle noch nicht zugewiesen wurden, können Sie den Cluster-Administrator bitten, einen SnapLock-Sicherheitsbenutzer mit dieser SnapLock-Sicherheitsrolle zu erstellen.

.Bevor Sie beginnen
* Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.
* Sie müssen sich mit einer sicheren Verbindung (SSH, Konsole oder ZAPI) angemeldet haben.


.Über diese Aufgabe
die SnapLock-Rolle ist mit der Admin-SVM verbunden – im Gegensatz zur vsadmin-snaplock-Rolle, die mit der Daten-SVM verknüpft ist.

.Schritt
. SVM-Administratorkonto mit der SnapLock-Administratorrolle erstellen:
+
`*security login create -vserver _SVM_name_ -user-or-group-name _user_or_group_name_ -application _application_ -authmethod _authentication_method_ -role _role_ -comment _comment_*`

+
Mit dem folgenden Befehl kann das SVM-Administratorkonto `SnapLockAdmin` mit der vordefinierten `snaplock` Rolle `cluster1` über ein Passwort auf die Admin-SVM zugreifen:

+
[listing]
----
cluster1::> security login create -vserver cluster1 -user-or-group-name SnapLockAdmin -application ssh -authmethod password -role snaplock
----
+
Erfahren Sie mehr über `security login create` in der link:https://docs.netapp.com/us-en/ontap-cli/security-login-create.html["ONTAP-Befehlsreferenz"^].





== SnapLock Volumes werden verschoben

Sie können mit dem `volume move` Befehl ein SnapLock Volume zu einem Ziel-Aggregat verschieben.

.Bevor Sie beginnen
* Vor der Verschiebung eines SnapLock Volumes müssen Sie ein SnapLock-geschütztes Prüfprotokoll erstellt haben.
+
link:create-audit-log-task.html["Erstellen eines Prüfprotokolls"].

* Wenn Sie eine ältere Version von ONTAP als ONTAP 9.10.1 verwenden, muss das Zielaggregat den gleichen SnapLock-Typ sein wie das SnapLock Volume, das Sie verschieben möchten: Compliance zu Compliance oder Enterprise zu Enterprise. Ab ONTAP 9.10.1 wurde diese Einschränkung entfernt und ein Aggregat kann sowohl Compliance- als auch Enterprise SnapLock Volumes enthalten, die nicht von SnapLock stammen.
* Sie müssen ein Benutzer mit der Sicherheitsrolle „SnapLock“ sein.


.Schritte
. Melden Sie sich über eine sichere Verbindung bei der ONTAP Cluster-Management-LIF an:
+
`*ssh snaplock_user@cluster_mgmt_ip*`

. Verschieben eines SnapLock Volumes:
+
`*volume move start -vserver _SVM_name_ -volume _SnapLock_volume_name_ -destination-aggregate _destination_aggregate_name_*`

. Prüfen Sie den Status der Volume-Verschiebung:
+
`*volume move show -volume _SnapLock_volume_name_ -vserver _SVM_name_ -fields volume,phase,vserver*`


