---
permalink: snaplock/set-default-retention-period-task.html 
sidebar: sidebar 
keywords: snaplock, volume, command, modify, retention, period, file, set, default 
summary: Mithilfe des Befehls Volume SnapLock modify können Sie den Standardaufbewahrungszeitraum für Dateien auf einem SnapLock Volume festlegen. 
---
= Legen Sie den Standardaufbewahrungszeitraum fest
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `volume snaplock modify` Befehl zum Festlegen des Standardaufbewahrungszeitraums für Dateien auf einem SnapLock Volume

.Was Sie benötigen
Das SnapLock Volume muss online sein.

.Über diese Aufgabe
In der folgenden Tabelle sind die möglichen Werte für die Option Standardaufbewahrungszeitraum aufgeführt:

[NOTE]
====
Der Standardaufbewahrungszeitraum muss größer oder gleich (>=) dem Mindestaufbewahrungszeitraum und kleiner als oder gleich (\<=) dem maximalen Aufbewahrungszeitraum sein.

====
|===
| Wert | Einheit | Hinweise 


 a| 
0 bis 65535
 a| 
Sekunden
 a| 



 a| 
0 bis 24
 a| 
Stunden
 a| 



 a| 
0 bis 365
 a| 
Tage
 a| 



 a| 
0 bis 12
 a| 
Monaten
 a| 



 a| 
0 bis 100
 a| 
Jahren
 a| 
Ab ONTAP 9.10.1 Bei früheren Versionen von ONTAP beträgt der Wert 0 - 70.



 a| 
maximale
 a| 
-
 a| 
Verwenden Sie den maximalen Aufbewahrungszeitraum.



 a| 
Mindestens
 a| 
-
 a| 
Verwenden Sie den Mindestaufbewahrungszeitraum.



 a| 
Skalierbar
 a| 
-
 a| 
Bewahren Sie die Dateien für immer auf.



 a| 
Nicht angegeben
 a| 
-
 a| 
Bewahren Sie die Dateien so lange auf, bis ein absoluter Aufbewahrungszeitraum festgelegt ist.

|===
Die Werte und Bereiche für die maximale und minimale Aufbewahrungsdauer sind identisch, mit Ausnahme von `max` Und `min`, Die nicht anwendbar sind. Weitere Informationen zu dieser Aufgabe finden Sie unter link:set-retention-period-task.html["Stellen Sie die Übersicht über die Aufbewahrungszeit ein"].

Sie können das verwenden `volume snaplock show` Befehl zum Anzeigen der Einstellungen für den Aufbewahrungszeitraum für das Volume. Weitere Informationen finden Sie auf der man-Page für den Befehl.

[NOTE]
====
Nachdem eine Datei im WORM-Status übergeben wurde, können Sie den Aufbewahrungszeitraum verlängern, jedoch nicht verkürzen.

====
.Schritte
. Legen Sie den Standardaufbewahrungszeitraum für Dateien auf einem SnapLock-Volume fest:
+
`*volume snaplock modify -vserver _SVM_name_ -volume _volume_name_ -default-retention-period _default_retention_period_ -minimum-retention-period _min_retention_period_ -maximum-retention-period _max_retention_period_*`

+
Eine vollständige Liste der Optionen finden Sie auf der man-Page für den Befehl.

+
[NOTE]
====
In den folgenden Beispielen wird davon ausgegangen, dass die minimalen und maximalen Aufbewahrungszeiträume zuvor nicht geändert wurden.

====
+
Mit dem folgenden Befehl wird die Standardaufbewahrungsdauer für Compliance- oder Enterprise-Volumes auf 20 Tage festgelegt:

+
[listing]
----
cluster1::> volume snaplock modify -vserver vs1 -volume vol1 -default-retention-period 20days
----
+
Mit dem folgenden Befehl wird die Standardaufbewahrungsdauer für ein Compliance-Volume auf 70 Jahre festgelegt:

+
[listing]
----
cluster1::> volume snaplock modify -vserver vs1 -volume vol1 -maximum-retention-period 70years
----
+
Mit dem folgenden Befehl wird die Standardaufbewahrungsdauer für ein Enterprise-Volume auf 10 Jahre festgelegt:

+
[listing]
----
cluster1::> volume snaplock modify -vserver vs1 -volume vol1 -default-retention-period max -maximum-retention-period 10years
----
+
Mit den folgenden Befehlen wird die Standardaufbewahrungsdauer für Enterprise-Volumes auf 10 Tage festgelegt:

+
[listing]
----
cluster1::> volume snaplock modify -vserver vs1 -volume vol1 -minimum-retention-period 10days
cluster1::> volume snaplock modify -vserver vs1 -volume vol1 -default-retention-period min
----
+
Mit dem folgenden Befehl wird die Standardaufbewahrungsdauer für ein Compliance-Volume auf „skalierbar“ gesetzt:

+
[listing]
----
cluster1::> volume snaplock modify -vserver vs1 -volume vol1 -default-retention-period infinite -maximum-retention-period infinite
----

