---
permalink: nfs-trunking/client-mount-task.html 
sidebar: sidebar 
keywords: NFS, servers, network, NFS trunking, data shares, Linux, VMware, mounts 
summary: Linux- und VMware-Clients, die Trunking unterstützen, können Volumes oder Data Shares von einem ONTAP NFS-Server mounten, der für das Trunking aktiviert ist. 
---
= Mounten Sie ONTAP Volumes oder Data Shares für NFS Trunking
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Linux- und VMware-Clients, die Trunking unterstützen, können Volumes oder Data Shares von einem ONTAP NFSv4.1 Server mounten, der für das Trunking aktiviert ist.

Erfahren Sie mehr über link:index.html#supported-clients["Unterstützte Clients"].

[role="tabbed-block"]
====
.Anforderungen für den Linux-Client
--
Wenn Sie ONTAP 9.16.1 oder höher und Red hat Enterprise Linux Version 8.7 oder höher (für RHEL 8) oder 9.2 oder höher (für RHEL 9) als Linux-Client verwenden, ist für die Trunking-Gruppe nur ein Bereitstellungspunkt erforderlich. Mounten Sie die exportierten Volumes mit diesem Befehl. Verwenden Sie dazu die `trunkdiscovery` Option:

[source, cli]
----
mount <lif_ip>:<volume_name> </mount_path> -o trunkdiscovery,vers=4.1
----
Andernfalls ist für jede Verbindung in der Trunking-Gruppe ein separater Mount-Punkt erforderlich. Mounten Sie das exportierte Volume mit Befehlen wie den folgenden, indem Sie die Option verwenden `max_connect`:

[source, cli]
----
mount <lif1_ip>:<volume_name> </mount_path1> -o vers=4.1,max_connect=16
----
[source, cli]
----
mount <lif2_ip>:<volume_name> </mount_path2> -o vers=4.1,max_connect=16
----
Der (`vers`Wert Version ) sollte `4.1` oder höher sein.

Der `max_connect` Wert entspricht der Anzahl der Verbindungen in der Trunking-Gruppe.

--
.Anforderungen des VMware-Clients
--
Es ist eine Mount-Anweisung erforderlich, die eine IP-Adresse für jede Verbindung in der Trunking-Gruppe enthält.

Mounten Sie den exportierten Datastore mit einem Befehl wie folgt:

`#esxcli storage nfs41 -H lif1_ip, lif2_ip -s /mnt/sh are1 -v nfs41share`

Die `-H` Werte entsprechen den Verbindungen in der Trunking-Gruppe.

--
====