---
permalink: nfs-trunking/client-mount-task.html 
sidebar: sidebar 
keywords: NFS, servers, network, NFS trunking, data shares, Linux, VMware, mounts 
summary: Linux- und VMware-Clients, die Trunking unterstützen, können Volumes oder Data Shares von einem ONTAP NFS-Server mounten, der für das Trunking aktiviert ist. 
---
= Erstellen Sie Client-Mounts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Linux- und VMware-Clients, die Trunking unterstützen, können Volumes oder Data Shares von einem ONTAP NFSv4.1 Server mounten, der für das Trunking aktiviert ist.

Wenn Sie Mount-Befehle auf den Clients eingeben, müssen Sie IP-Adressen für jede LIF in der Trunking-Gruppe eingeben.

Erfahren Sie mehr über link:index.html#supported-clients["Unterstützte Clients"].

[role="tabbed-block"]
====
.Anforderungen für den Linux-Client
--
Für jede Verbindung in der Trunking-Gruppe ist ein separater Mount-Punkt erforderlich.

Mounten Sie die exportierten Volumes mit Befehlen wie den folgenden:

`mount lif1_ip:/vol-test /mnt/test1 -o vers=4.1,max_connect=16`

`mount lif2_ip:/vol-test /mnt/test2 -o vers=4.1,max_connect=16`

Die Version (`vers`) Wert sollte sein `4.1` Oder höher.

Der `max_connect` Der Wert entspricht der Anzahl der Verbindungen in der Trunking-Gruppe.

--
.Anforderungen des VMware-Clients
--
Es ist eine Mount-Anweisung erforderlich, die eine IP-Adresse für jede Verbindung in der Trunking-Gruppe enthält.

Mounten Sie den exportierten Datastore mit einem Befehl wie folgt:

`#esxcli storage nfs41 -H lif1_ip, lif2_ip -s /mnt/sh are1 -v nfs41share`

Der `-H` Die Werte entsprechen den Verbindungen in der Trunking-Gruppe.

--
====