---
permalink: nfs-trunking/create-server-task.html 
sidebar: sidebar 
keywords: NFS, servers, create, NFS trunking, enabled, multipathing, svm 
summary: Ab ONTAP 9.14.1 kann Trunking auf NFS-Servern mit Version 4.1 oder höher aktiviert werden. NFSv4.1 und höher sind standardmäßig aktiviert, wenn NFS-Server erstellt werden. 
---
= Einen Trunking-fähigen NFS-Server auf einer ONTAP SVM erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.14.1 kann Trunking auf NFS-Servern aktiviert werden. NFSv4.1 ist bei der Erstellung von NFS-Servern standardmäßig aktiviert.

.Bevor Sie beginnen
Das Erstellen eines NFS-Servers mit aktivierter Trunking-Funktion erfordert eine SVM. Die SVM muss folgende Eigenschaften aufweisen:

* unterstützt durch ausreichend Speicherplatz für die Datenanforderungen des Clients.
* Für NFS aktiviert.


Sie können eine bestehende SVM verwenden; allerdings erfordert die Aktivierung von Trunking, dass alle NFSv4.x-Clients neu eingebunden werden, was zu Störungen führen kann. Falls eine Neueinbindung nicht möglich ist, sollte eine neue SVM für den NFS-Server erstellt werden.

.Schritte
. Falls keine geeignete SVM existiert, kann eine erstellt werden:
+
`vserver create -vserver _svm_name_ -rootvolume _root_volume_name_ -aggregate _aggregate_name_ -rootvolume-security-style unix -language C.UTF-8`

. Die Konfiguration und der Status der neu erstellten SVM können überprüft werden:
+
`vserver show -vserver _svm_name_`

+
Weitere Informationen zu link:../nfs-config/create-svms-data-access-task.html["Erstellung einer SVM"].

. Den NFS-Server erstellen:
+
`vserver nfs create -vserver _svm_name_ -v3 disabled -v4.0 disabled -v4.1 enabled -v4.1-trunking enabled -v4-id-domain _my_domain.com_`

. Es sollte überprüft werden, ob NFS ausgeführt wird:
+
`vserver nfs status -vserver _svm_name_`

. Es sollte überprüft werden, ob NFS wie gewünscht konfiguriert ist:
+
`vserver nfs show -vserver _svm_name_`

+
Erfahren Sie mehr überlink:../nfs-config/create-server-task.html["NFS-Serverkonfiguration."]



.Nachdem Sie fertig sind
Die folgenden Dienste können nach Bedarf konfiguriert werden:

* link:../nfs-config/configure-dns-host-name-resolution-task.html["DNS"]
* link:../nfs-config/using-ldap-concept.html["LDAP"]
* link:../nfs-config/kerberos-nfs-strong-security-concept.html["Kerberos"]

