---
permalink: nfs-trunking/update-network-task.html 
sidebar: sidebar 
keywords: NFS, servers, network, prepare, NFS trunking, LIF, trunking group, NIC 
summary: Um das NFS-Trunking zu nutzen, müssen sich mehrere LIFs für jede Trunking-Verbindung auf zwei oder mehr NICs befinden. 
---
= Aktualisieren Sie Ihr Netzwerk für ONTAP NFS Trunking
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um die Vorteile des NFSv4.1 Trunking zu nutzen, müssen sich die LIFs in einer Trunking-Gruppe auf demselben Node befinden und über Home Ports auf demselben Node verfügen. Die LIFs sollten in einer Failover-Gruppe auf demselben Node konfiguriert werden.

.Über diese Aufgabe
Eine 1:1-Zuordnung von LIFs und NICs bietet den größten Performance-Zuwachs, ist jedoch nicht für die Aktivierung des Trunkings erforderlich. Wenn mindestens zwei NICs installiert sind, kann dies einen Leistungsvorteil bieten, der jedoch nicht erforderlich ist.

Alle LIFs in der Trunking-Gruppe sollten derselben Failover-Gruppe angehören. Wenn die LIFs in einer Failover-Gruppe auf demselben Node konfiguriert sind, kann ein Controller Failover auf diesem Node dazu führen, dass die LIFs offline gehen. Wenn die LIFs nicht in einer Failover-Gruppe auf demselben Node und beim Failover zu einem anderen Node konfiguriert sind, funktioniert das Trunking nicht mehr.

Sie sollten die Trunking Failover-Gruppe jedes Mal anpassen, wenn Sie Verbindungen (und zugrunde liegende NICs) zu einer Failover-Gruppe hinzufügen oder entfernen.

.Bevor Sie beginnen
* Sie müssen die mit den NICs verknüpften Portnamen kennen, um eine Failover-Gruppe zu erstellen.
* Die Ports müssen sich alle auf demselben Node befinden.


.Schritte
. Überprüfen Sie die Namen und den Status der Netzwerkports, die Sie verwenden möchten:
+
`network port show`

. Erstellen einer Failover-Trunking-Gruppe oder Ändern einer vorhandenen für Trunking:
+
`network interface failover-groups create -vserver <svm_name> -failover-group <failover_group_name> -targets <ports_list>`

+
`network interface failover-groups modify -vserver <svm_name> -failover-group <failover_group_name> -targets <ports_list>`

+

NOTE: Eine Failover-Gruppe ist nicht erforderlich, wird jedoch dringend empfohlen.

+
** `<svm_name>` Ist der Name der SVM, die den NFS-Server enthält.
** `<ports_list>` Ist die Liste der Ports, die der Failover-Gruppe hinzugefügt werden.
+
Ports werden im Format hinzugefügt `<node_name>:<port_number>`, zum Beispiel `node1:e0c`.

+
Mit dem folgenden Befehl wird eine Failover-Gruppe `fg3` für SVM vs1 erstellt und drei Ports hinzugefügt:

+
`network interface failover-groups create -vserver vs1 -failover-group fg3 -targets cluster1-01:e0c,cluster1-01:e0d,cluster1-01:e0e`

+
Weitere Informationen zu link:../networking/configure_failover_groups_and_policies_for_lifs_overview.html["Failover-Gruppen."]



. Erstellung zusätzlicher LIFs für Mitglieder der Trunking-Gruppe, je nach Bedarf:
+
`network interface create -vserver <svm_name> -lif <lif_name> -home-node <node_name> -home-port <port_name> -address <IP_address> -netmask <IP_address> [-service-policy <policy>] [-auto-revert <true|false>]`

+
** `-home-node` - Der Knoten, zu dem die LIF zurückgibt, wenn der Befehl Network Interface revert auf der LIF ausgeführt wird.
+
Sie können mit der `-auto-revert` Option angeben, ob die LIF automatisch zum Home Node und Home Port zurückgesetzt wird.

** `-home-port` Ist der physische oder logische Port, zu dem die LIF zurückgibt, wenn der Befehl zum Zurücksetzen der Netzwerkschnittstelle auf der LIF ausgeführt wird.
** Mit den `-address` `-netmask` Optionen und können Sie eine IP-Adresse angeben.
** Wenn Sie IP-Adressen manuell zuweisen (ohne ein Subnetz zu verwenden), müssen Sie möglicherweise eine Standardroute zu einem Gateway konfigurieren, wenn Clients oder Domänencontroller in einem anderen IP-Subnetz vorhanden sind. Die man-Seite „Network Route create“ enthält Informationen zum Erstellen einer statischen Route innerhalb einer SVM.
** `-service-policy` - Die Service Policy für die LIF. Wenn keine Richtlinie angegeben wird, wird automatisch eine Standardrichtlinie zugewiesen. Mit dem `network interface service-policy show` Befehl können Sie die verfügbaren Service-Richtlinien überprüfen.
** `-auto-revert` - Geben Sie an, ob eine Daten-LIF automatisch auf ihren Heimatknoten zurückgesetzt wird, unter Umständen wie Start, Änderungen des Status der Management-Datenbank oder wenn die Netzwerkverbindung hergestellt wird. *Die Standardeinstellung ist FALSE*, aber Sie können sie abhängig von den Netzwerkverwaltungsrichtlinien in Ihrer Umgebung auf TRUE setzen.
+
Wiederholen Sie diesen Schritt für jede zusätzliche LIF, die in der Trunking-Gruppe benötigt wird.

+
Der folgende Befehl erstellt `lif-A` für die SVM `vs1`, auf dem Port `e0c` des Knotens `cluster1_01`:

+
`network interface create -vserver vs1 -lif lif-A -service-policy default-intercluster -home-node cluster1_01 -home-port e0c -address 192.0.2.0`

+
Weitere Informationen zu link:../networking/create_lifs.html["LIF-Erstellung:"]



. Vergewissern Sie sich, dass die LIFs erstellt wurden:
+
[source, cli]
----
network interface show
----
. Vergewissern Sie sich, dass die konfigurierte IP-Adresse erreichbar ist:
+
[cols="25,75"]
|===
| Überprüfen einer... | Verwenden... 


| IPv4-Adresse | `network ping` 


| IPv6-Adresse | `network ping6` 
|===

