---
permalink: nfs-trunking/update-network-task.html 
sidebar: sidebar 
keywords: NFS, servers, network, prepare, NFS trunking, LIF, trunking group, NIC 
summary: Um die Vorteile von NFS-Trunking nutzen zu können, benötigen Sie mehrere LIFs, die sich auf zwei oder mehr NICs für jede Trunk-Verbindung befinden. 
---
= Netzwerk für ONTAP NFS Trunking aktualisieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um die Vorteile von NFSv4.1 Trunking zu nutzen, müssen sich die LIFs in einer Trunking-Gruppe auf demselben Knoten befinden und Home-Ports auf demselben Knoten haben. Die LIFs sollten in einer Failover-Gruppe auf demselben Knoten konfiguriert sein.

.Über diese Aufgabe
Eine 1:1-Zuordnung von LIFs und NICs erzielt den größten Leistungszuwachs, ist aber für die Aktivierung von Trunking nicht erforderlich. Mindestens zwei installierte NICs können einen Leistungsvorteil bieten, sind jedoch nicht erforderlich.

Alle LIFs in der Trunking-Gruppe sollten derselben Failover-Gruppe angehören. Es ist zu beachten, dass ein Controller-Failover auf demselben Node dazu führen kann, dass die LIFs offline gehen, wenn sie in einer Failover-Gruppe auf demselben Node konfiguriert sind. Wenn die LIFs nicht in einer Failover-Gruppe auf demselben Node konfiguriert sind und ein Failover auf einen anderen Node erfolgt, funktioniert das Trunking nicht mehr.

Die Trunking Failover-Gruppe ist immer dann anzupassen, wenn Verbindungen (und die zugrunde liegenden Netzwerkkarten) zu einer Failover-Gruppe hinzugefügt oder daraus entfernt werden.

.Bevor Sie beginnen
* Die Port-Namen, die den NICs zugeordnet sind, müssen bekannt sein, um eine Failover-Gruppe zu erstellen.
* Die Ports müssen sich alle auf demselben Node befinden.


.Schritte
. Die Namen und den Status der Netzwerkanschlüsse, die verwendet werden sollen, überprüfen:
+
`network port show`

+
Weitere Informationen zu  `network port show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html["ONTAP-Befehlsreferenz"^].

. Eine Trunking Failover-Gruppe kann erstellt oder eine vorhandene für Trunking angepasst werden:
+
`network interface failover-groups create -vserver <svm_name> -failover-group <failover_group_name> -targets <ports_list>`

+
`network interface failover-groups modify -vserver <svm_name> -failover-group <failover_group_name> -targets <ports_list>`

+

NOTE: Es ist nicht erforderlich, eine Failover-Gruppe zu haben, aber es wird dringend empfohlen.

+
** `<svm_name>` ist der Name der SVM, die den NFS-Server enthält.
** `<ports_list>` ist die Liste der Ports, die der Failover-Gruppe hinzugefügt werden.
+
Ports werden im Format  `<node_name>:<port_number>` hinzugefügt, zum Beispiel  `node1:e0c`.

+
Der folgende Befehl erstellt die Failover-Gruppe `fg3` für SVM vs1 und fügt drei Ports hinzu:

+
`network interface failover-groups create -vserver vs1 -failover-group fg3 -targets cluster1-01:e0c,cluster1-01:e0d,cluster1-01:e0e`

+
Erfahren Sie mehr überlink:../networking/configure_failover_groups_and_policies_for_lifs_overview.html["Failover-Gruppen."]



. Zusätzliche LIFs für Mitglieder der Trunking-Gruppe können bei Bedarf erstellt werden:
+
`network interface create -vserver <svm_name> -lif <lif_name> -home-node <node_name> -home-port <port_name> -address <IP_address> -netmask <IP_address> [-service-policy <policy>] [-auto-revert <true|false>]`

+
** `-home-node` - der Knoten, zu dem die LIF zurückkehrt, wenn der Befehl "network interface revert" auf der LIF ausgeführt wird.
+
Sie können angeben, ob die LIF mit der  `-auto-revert` Option automatisch zum Home-Node und Home-Port zurückkehren soll.

** `-home-port` ist der physische oder logische Port, zu dem die LIF zurückkehrt, wenn der Befehl "network interface revert" auf der LIF ausgeführt wird.
** Sie können eine IP-Adresse mit den  `-address` und  `-netmask` Optionen angeben.
** Wenn Sie IP-Adressen manuell zuweisen (ohne ein Subnetz zu verwenden), kann es erforderlich sein, eine Standardroute zu einem Gateway zu konfigurieren, wenn sich Clients oder Domänencontroller in einem anderen IP-Subnetz befinden. Die  `network route create`Befehlsseite enthält Informationen zum Erstellen einer statischen Route innerhalb einer SVM. Weitere Informationen zu  `network route create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-route-create.html["ONTAP-Befehlsreferenz"^].
** `-service-policy` Die Servicerichtlinie für den LIF. Wenn keine Richtlinie angegeben ist, wird automatisch eine Standardrichtlinie zugewiesen. Mit dem  `network interface service-policy show` Befehl lassen sich die verfügbaren Servicerichtlinien überprüfen.
+
Weitere Informationen zu  `network interface service-policy show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-service-policy-show.html["ONTAP-Befehlsreferenz"^].

** `-auto-revert` - gibt an, ob eine Daten-LIF unter Umständen wie Systemstart, Änderungen am Status der Management-Datenbank oder beim Herstellen der Netzwerkverbindung automatisch auf ihren Heimatknoten zurückkehrt. *Die Standardeinstellung ist false*, kann jedoch abhängig von den Netzwerkverwaltungsrichtlinien in Ihrer Umgebung auf true gesetzt werden.
+
Dieser Schritt ist für jedes weitere LIF zu wiederholen, das in der Bündelungsgruppe benötigt wird.

+
Der folgende Befehl erstellt `lif-A` für die SVM `vs1`, auf Port `e0c` des Knotens `cluster1_01`:

+
`network interface create -vserver vs1 -lif lif-A -service-policy default-intercluster -home-node cluster1_01 -home-port e0c -address 192.0.2.0`

+
Erfahren Sie mehr überlink:../networking/create_lifs.html["LIF Erstellung."]



. Es wird überprüft, ob die LIFs erstellt wurden:
+
[source, cli]
----
network interface show
----
. Es sollte überprüft werden, ob die konfigurierte IP-Adresse erreichbar ist:
+
[cols="25,75"]
|===
| Zur Überprüfung einer... | Verwenden... 


| IPv4-Adresse | `network ping` 


| IPv6-Adresse | `network ping6` 
|===


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/network-ping.html["Netzwerk-Ping"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["Netzwerkschnittstelle"^]

