---
permalink: cloud/manage-ontap-concept.html 
sidebar: sidebar 
keywords: manage, ontap, cloud 
summary: 'Unabhängig davon, ob Sie ONTAP im eigenen Datacenter oder in der Cloud nutzen, können Sie Ihren Storage über dieselben Schnittstellen managen. Das bedeutet, dass Sie bereits wissen, wie Sie ONTAP in der Cloud managen. Darüber hinaus ist NetApp BlueXP eine moderne, benutzerfreundliche grafische Oberfläche für die Implementierung und die ersten Schritte mit Cloud Volumes ONTAP. In bestimmten Fällen ist ein erweitertes Management von Cloud Volumes ONTAP oder Cloud Volumes Service erforderlich. Dies können Sie mit System Manager, der Befehlszeilenschnittstelle (CLI) oder REST-APIs durchführen.' 
---
= Management von ONTAP in der Cloud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unabhängig davon, ob Sie ONTAP im eigenen Datacenter oder in der Cloud nutzen, können Sie Ihren Storage über dieselben Schnittstellen managen. Das bedeutet, dass Sie bereits wissen, wie Sie ONTAP in der Cloud managen. Darüber hinaus ist NetApp BlueXP eine moderne, benutzerfreundliche grafische Oberfläche für die Implementierung und die ersten Schritte mit Cloud Volumes ONTAP. In bestimmten Fällen ist ein erweitertes Management von Cloud Volumes ONTAP oder Cloud Volumes Service erforderlich. Dies können Sie mit System Manager, der Befehlszeilenschnittstelle (CLI) oder REST-APIs durchführen.

*System Manager* wird auf dem Cloud Volumes ONTAP oder Cloud Volumes Service System ausgeführt, sodass Sie Verwaltungsaufgaben ausführen können.

*Die ONTAP CLI* ermöglicht Ihnen die Ausführung aller administrativen Befehle und ist eine gute Wahl für fortgeschrittene Aufgaben oder wenn Sie die CLI bequemer nutzen. Sie stellen über Secure Shell (SSH) eine Verbindung zur CLI her.

*ONTAP REST APIs* ermöglichen das Erstellen und Verwalten von Cloud Volumes und die Entwicklung von Bereitstellungsskripten und Tools. Die ONTAP-Funktionen, die über die Web-Benutzeroberfläche verfügbar sind, sind auch über REST-APIs verfügbar. In manchen Fällen ist diese programmatische Schnittstelle nützlicher, insbesondere für Entwickler, da sie Prozesse mit BlueXP-Vorgängen automatisieren können.

https://docs.netapp.com/us-en/occm/task_connecting_to_otc.html#connecting-to-oncommand-system-manager["Verbindung zu Cloud Volumes ONTAP"]

https://cloud.netapp.com/blog/cloud-automation-with-cloud-volumes-ontap-rest["Cloud-Automatisierung mit Cloud Volumes ONTAP und REST"]

https://docs.netapp.com/us-en/occm/api.html["BlueXP REST-API"]
