---
permalink: cloud/volume-move-concept.html 
sidebar: sidebar 
keywords: volume move 
summary: 'Mit ONTAP können Sie ein FlexVol Volume zu einer anderen lokalen Tier (Aggregat), Node oder beides mit derselben Storage VM (SVM) verschieben, um die Storage-Kapazität auszugleichen, nachdem ein Ungleichgewicht bei der Storage-Kapazität festgestellt wurde. Mit Cloud Volumes ONTAP können Sie ein oder mehrere Volumes auf ein anderes Cloud Volumes ONTAP System oder in ein anderes Aggregat verschieben, um Kapazitätsprobleme zu vermeiden. Möglicherweise müssen Sie dies tun, wenn das System seine Datenträgergrenze erreicht.' 
---
= Volume-Verschiebung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP können Sie ein FlexVol Volume zu einer anderen lokalen Tier (Aggregat), Node oder beides mit derselben Storage VM (SVM) verschieben, um die Storage-Kapazität auszugleichen, nachdem ein Ungleichgewicht bei der Storage-Kapazität festgestellt wurde. Mit Cloud Volumes ONTAP können Sie ein oder mehrere Volumes auf ein anderes Cloud Volumes ONTAP System oder in ein anderes Aggregat verschieben, um Kapazitätsprobleme zu vermeiden. Möglicherweise müssen Sie dies tun, wenn das System seine Datenträgergrenze erreicht.

.Verwandte Informationen
https://docs.netapp.com/us-en/occm/task_managing_storage.html#moving-volumes-to-another-system-to-avoid-capacity-issues["Cloud Volumes ONTAP: Verschieben von Volumes in ein anderes System, um Kapazitätsprobleme zu vermeiden"]

https://docs.netapp.com/us-en/occm/task_managing_storage.html#moving-volumes-to-another-aggregate-to-avoid-capacity-issues["Cloud Volumes ONTAP: Verschieben von Volumes in ein anderes Aggregat, um Kapazitätsprobleme zu vermeiden"]
