---
permalink: flexcache/create-volume-task.html 
sidebar: sidebar 
keywords: creating, flexcache, volume, flex cache, performance, remote cluster, data access, tls encryption, peer permission, 
summary: Sie können ein FlexCache Volume in demselben Cluster erstellen, um die Performance beim Zugriff auf ein Hot Object zu verbessern. Wenn Sie Datacenter an verschiedenen Standorten haben, können Sie FlexCache Volumes auf Remote-Clustern erstellen, um den Datenzugriff zu beschleunigen. 
---
= FlexCache Volume erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein FlexCache Volume in demselben Cluster erstellen, um die Performance beim Zugriff auf ein Hot Object zu verbessern. Wenn Sie Datacenter an verschiedenen Standorten haben, können Sie FlexCache Volumes auf Remote-Clustern erstellen, um den Datenzugriff zu beschleunigen.

.Über diese Aufgabe
Das FlexCache Volume ist immer ein FlexGroup Volume, nicht ein FlexVol Volume.

Ab ONTAP 9.7 werden auch FlexGroup Volumes am Ursprung der FlexCache Beziehung unterstützt.

.Schritte
. Wenn sich das zu erstellenden FlexCache Volume in einem anderen Cluster befindet, erstellen Sie eine Cluster-Peer-Beziehung:
+
.. Erstellen Sie auf dem Ziel-Cluster eine Peer-Beziehung mit dem Datensicherungs-Quell-Cluster: +
`cluster peer create -generate-passphrase -offer-expiration MM/DD/YYYY HH:MM:SS|1...7days|1...168hours -peer-addrs _peer_LIF_IPs_ -initial-allowed-vserver-peers _svm_name_,..|* -ipspace _ipspace_name_`
+
Ab ONTAP 9.6 ist die TLS-Verschlüsselung bei der Erstellung einer Cluster-Peer-Beziehung standardmäßig aktiviert. Die TLS-Verschlüsselung wird für die Cluster-übergreifende Kommunikation zwischen den Ursprungs- und FlexCache Volumes unterstützt. Bei Bedarf können Sie auch die TLS-Verschlüsselung für die Cluster-Peer-Beziehung deaktivieren.

+
[listing]
----
cluster02::> cluster peer create -generate-passphrase -offer-expiration 2days -initial-allowed-vserver-peers *

                     Passphrase: UCa+6lRVICXeL/gq1WrK7ShR
                Expiration Time: 6/7/2017 08:16:10 EST
  Initial Allowed Vserver Peers: *
            Intercluster LIF IP: 192.140.112.101
              Peer Cluster Name: Clus_7ShR (temporary generated)

Warning: make a note of the passphrase - it cannot be displayed again.
----
.. Authentifizierung des Quellclusters im Quellcluster beim Zielcluster: +
`cluster peer create -peer-addrs _peer_LIF_IPs_ -ipspace _ipspace_`
+
[listing]
----
cluster01::> cluster peer create -peer-addrs 192.140.112.101,192.140.112.102

Notice: Use a generated passphrase or choose a passphrase of 8 or more characters.
        To ensure the authenticity of the peering relationship, use a phrase or sequence of characters that would be hard to guess.

Enter the passphrase:
Confirm the passphrase:

Clusters cluster02 and cluster01 are peered.
----


. Wenn sich das FlexCache-Volume in einer anderen SVM als der des Ursprungs-Volume befindet, erstellen Sie eine SVM-Peer-Beziehung mit `flexcache` Als Anwendung:
+
.. Wenn sich die SVM in einem anderen Cluster befindet, erstellen Sie eine SVM-Berechtigung für die Peering SVMs: +
`vserver peer permission create -peer-cluster _cluster_name_ -vserver _svm-name_ -applications flexcache`
+
Das folgende Beispiel veranschaulicht die Erstellung einer SVM-Peer-Berechtigung, die für alle lokalen SVMs gilt:

+
[listing]
----
cluster1::> vserver peer permission create -peer-cluster cluster2 -vserver "*" -applications flexcache

Warning: This Vserver peer permission applies to all local Vservers. After that no explict
"vserver peer accept" command required for Vserver peer relationship creation request
from peer cluster "cluster2" with any of the local Vservers. Do you want to continue? {y|n}: y
----
.. Peer-Beziehung zu SVM: + erstellen
`vserver peer create -vserver local_SVM -peer-vserver _remote_SVM_ -peer-cluster _cluster_name_ -applications flexcache`


. FlexCache Volume erstellen:
+
`volume flexcache create -vserver _cache_svm_ -volume _cache_vol_name_ -auto-provision-as flexgroup -size _vol_size_ -origin-vserver _origin_svm_ -origin-volume _origin_vol_name_`

+
Im folgenden Beispiel wird ein FlexCache Volume erstellt und vorhandene Aggregate für die Bereitstellung automatisch ausgewählt:

+
[listing]
----
cluster1::> volume flexcache create -vserver vs_1 -volume fc1 -auto-provision-as flexgroup -origin-volume vol_1 -size 160MB -origin-vserver vs_1
[Job 443] Job succeeded: Successful
----
+
Im folgenden Beispiel wird ein FlexCache Volume erstellt und der Verbindungspfad festgelegt:

+
[listing]
----
cluster1::> flexcache create -vserver vs34 -volume fc4 -aggr-list aggr34,aggr43 -origin-volume origin1 -size 400m -junction-path /fc4
[Job 903] Job succeeded: Successful
----
. Überprüfen Sie die FlexCache Beziehung vom FlexCache Volume und dem Ursprungs-Volume.
+
.. Anzeigen der FlexCache-Beziehung im Cluster: +
`volume flexcache show`
+
[listing]
----
cluster1::> volume flexcache show
Vserver Volume      Size       Origin-Vserver Origin-Volume Origin-Cluster
------- ----------- ---------- -------------- ------------- --------------
vs_1    fc1         160MB      vs_1           vol_1           cluster1
----
.. Alle FlexCache Beziehungen im Ursprungs-Cluster anzeigen: +
`volume flexcache origin show-caches`
+
[listing]
----
cluster::> volume flexcache origin show-caches
Origin-Vserver Origin-Volume   Cache-Vserver    Cache-Volume   Cache-Cluster
-------------- --------------- ---------------  -------------- ---------------
vs0            ovol1           vs1              cfg1           clusA
vs0            ovol1           vs2              cfg2           clusB
vs_1           vol_1           vs_1             fc1            cluster1
----






== Ergebnis

Das FlexCache Volume wurde erfolgreich erstellt. Clients können das Volume über den Verbindungspfad des FlexCache Volume mounten.

.Verwandte Informationen
link:../peering/index.html["Cluster- und SVM-Peering"]

http://["ONTAP 9-Befehle"^]
