---
permalink: flexcache/delete-relationship-task.html 
sidebar: sidebar 
keywords: deleting, flexcache, relationship 
summary: Sie können eine FlexCache Beziehung und das FlexCache Volume löschen, wenn das FlexCache Volume nicht mehr benötigt wird. 
---
= ONTAP FlexCache Beziehungen löschen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine FlexCache Beziehung und das FlexCache Volume löschen, wenn das FlexCache Volume nicht mehr benötigt wird.

.Bevor Sie beginnen
Wenn Sie die FlexCache Write-Back-Funktion aktiviert haben, müssen Sie sie deaktivieren, bevor Sie ein FlexCache Volume löschen können. Siehe link:../flexcache-writeback/flexcache-writeback-enable-task.html#disable-write-back-on-a-flexcache-volume["Write-Back auf einem FlexCache Volume deaktivieren"].

.Schritte
. Vom Cluster, der das FlexCache Volume enthält, das FlexCache Volume offline nehmen:
+
`volume offline -vserver svm_name -volume volume_name`

. Das FlexCache Volume löschen:
+
`volume flexcache delete -vserver svm_name -volume volume_name`

+
Die FlexCache-Beziehungsdetails werden aus dem Ursprungsvolume und dem FlexCache-Volume entfernt.


