---
permalink: flexcache/enable-file-access-time-updates-task.html 
sidebar: sidebar 
keywords: atime, atime-update, flexcache, flex cache, access time 
summary: 'Sie können das  `-atime-update` Feld auf dem FlexCache Volume aktivieren, um Aktualisierungen der Dateizugriffszeit zu ermöglichen. Ein Aktualisierungszeitraum für die Zugriffszeit kann auch mit dem  `-atime-update-period` Attribut festgelegt werden. Der atime-update-period steuert, wie häufig Aktualisierungen der Zugriffszeit erfolgen und wann diese an das Ursprungsvolume weitergegeben werden können.' 
---
= Aktualisierung der Dateizugriffszeit auf dem ONTAP FlexCache volume aktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.11.1 kann das  `-atime-update` Feld auf dem FlexCache Volume aktiviert werden, um Aktualisierungen der Dateizugriffszeit zu ermöglichen. Ein Aktualisierungszeitraum für die Zugriffszeit kann auch mit dem  `-atime-update-period` Attribut festgelegt werden. Das  `-atime-update-period` Attribut steuert, wie häufig Aktualisierungen der Zugriffszeit erfolgen können und wann diese an das Ursprungsvolume weitergegeben werden.



[[overview]]
== Überblick

ONTAP bietet ein Feld auf Volumenebene namens  `-atime-update`, um Zugriffszeitaktualisierungen für Dateien und Verzeichnisse zu verwalten, die mit READ, READLINK und READDIR gelesen werden. Atime wird für Entscheidungen zum Datenlebenszyklus von Dateien und Verzeichnissen verwendet, auf die selten zugegriffen wird. Die selten genutzten Dateien werden schließlich in den Archivspeicher migriert und werden häufig später auf Band verschoben.

Das Feld „atime-update“ ist auf bestehenden und neu erstellten FlexCache Volumes standardmäßig deaktiviert. Wenn Sie FlexCache Volumes mit ONTAP Releases vor 9.11.1 verwenden, sollte das Feld „atime-update“ deaktiviert bleiben, damit Caches nicht unnötig geleert werden, wenn eine Leseoperation auf dem Ursprungsvolume durchgeführt wird. Bei großen FlexCache Caches verwenden Administratoren jedoch spezielle Tools zur Datenverwaltung, um sicherzustellen, dass häufig genutzte Daten im Cache verbleiben und selten genutzte Daten entfernt werden. Dies ist nicht möglich, wenn „atime-update“ deaktiviert ist. Ab ONTAP 9.11.1 kann „atime-update“ aktiviert  `-atime-update` und  `-atime-update-period,` die erforderlichen Tools zur Verwaltung der zwischengespeicherten Daten verwendet werden.



[[before-you-begin]]
== Bevor Sie beginnen

* Alle FlexCache Volumes müssen unter ONTAP 9.11.1 oder höher ausgeführt werden.
* Sie müssen den  `advanced`privilegierten Modus verwenden.




[[about-this-task]]
== Über diese Aufgabe

Die Einstellung `-atime-update-period` auf 86400 Sekunden erlaubt maximal eine Aktualisierung der Zugriffszeit pro 24-Stunden-Zeitraum, unabhängig von der Anzahl der leseähnlichen Vorgänge, die an einer Datei durchgeführt werden.

Das Setzen des  `-atime-update-period` auf 0 sendet für jeden Lesezugriff Nachrichten an den Ursprung. Der Ursprung informiert dann jedes FlexCache volume darüber, dass die atime veraltet ist, was die Performance beeinträchtigt.

.Schritte
. Den Berechtigungsmodus auf  `advanced` festlegen:
+
`set -privilege advanced`

. Aktualisierungen der Dateizugriffszeit aktivieren und die Aktualisierungshäufigkeit festlegen:
+
`volume modify -volume vol_name -vserver <SVM name> -atime-update true -atime-update-period <seconds>`

+
Das folgende Beispiel aktiviert  `-atime-update` und setzt  `-atime-update-period` auf 86400 Sekunden, also 24 Stunden:

+
[listing]
----
c1: volume modify -volume origin1 vs1_c1 -atime-update true -atime-update-period 86400
----
. Es sollte überprüft werden, ob  `-atime-update` aktiviert ist:
+
`volume show -volume _vol_name_ -fields atime-update,atime-update-period`

+
[listing]
----
c1::*> volume show -volume cache1_origin1 -fields atime-update,atime-update-period
vserver volume         atime-update atime-update-period
------- -------------- ------------ -------------------
vs2_c1  cache1_origin1 true         86400
----
. Nachdem  `-atime-update` aktiviert wurde, kann festgelegt werden, ob die Dateien auf einem FlexCache volume automatisch bereinigt werden und in welchem Intervall die Bereinigung erfolgt:
+
`volume flexcache config modify -vserver <SVM name> -volume <volume_name> -is-atime-scrub-enabled <true|false> -atime-scrub-period <integer>`



Weitere Informationen zum  `-is-atime-scrub-enabled` Parameter finden Sie in der link:https://docs.netapp.com/us-en/ontap-cli/volume-flexcache-config-modify.html#parameters["ONTAP-Befehlsreferenz"^].
