---
permalink: flexcache/flexcache-duality-faq.html 
sidebar: sidebar 
keywords: duality, faq, frequently asked questions, flexcache, ontap s3, s3, nas, smb, nfs 
summary: Häufig gestellte Fragen zur FlexCache Dualität, die in ONTAP 9.18.1 eingeführt wurde. 
---
= Häufig gestellte Fragen zur FlexCache-Dualität
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese FAQ beantwortet häufig gestellte Fragen zur FlexCache-Dualität, die in ONTAP 9.18.1 eingeführt wurde.



== Häufig gestellte Fragen

.Was ist „Dualität“?
Dualität ermöglicht den einheitlichen Zugriff auf dieselben Daten sowohl über Datei- (NAS) als auch Objekt- (S3) Protokolle. Eingeführt in ONTAP 9.12.1 ohne FlexCache-Unterstützung, wurde Dualität in ONTAP 9.18.1 auf FlexCache-Volumes erweitert, sodass der S3-Protokollzugriff auf NAS-Dateien möglich ist, die in einem FlexCache-Volume zwischengespeichert sind.

.Welche S3-Operationen werden für einen FlexCache S3-Bucket unterstützt?
S3-Operationen, die auf Standard-S3-NAS-Buckets unterstützt werden, sind auch auf FlexCache S3-NAS-Buckets verfügbar, mit Ausnahme der  `COPY` Operation. Eine aktuelle Liste der nicht unterstützten Operationen für einen Standard-S3-NAS-Bucket finden Sie unter link:https://docs.netapp.com/us-en/ontap/s3-multiprotocol/index.html#s3-and-nas-interoperability["Interoperabilitätsdokumentation"^].

.Kann ich FlexCache im Write-Back-Modus mit FlexCache-Dualität verwenden?
Nein. Wenn ein FlexCache S3-NAS-Bucket auf einem FlexCache Volume erstellt wird, *muss* sich das FlexCache Volume im Write-Around-Modus befinden. Wenn Sie versuchen, einen FlexCache S3-NAS-Bucket auf einem FlexCache Volume im Write-Back-Modus zu erstellen, schlägt der Vorgang fehl.

.Ich kann einen meiner Cluster aufgrund von Hardwarebeschränkungen nicht auf ONTAP 9.18.1 aktualisieren. Funktioniert die Dualität in meinem Cluster weiterhin, wenn nur der Cache-Cluster mit ONTAP 9.18.1 läuft?
Nein. Sowohl der Cache-Cluster als auch der Ursprungscluster müssen mindestens die effektive Clusterversion 9.18.1 aufweisen. Wenn Sie versuchen, einen FlexCache S3-NAS-Bucket auf einem Cache-Cluster zu erstellen, der mit einem Ursprungscluster verbunden ist, auf dem eine ONTAP Version vor 9.18.1 ausgeführt wird, schlägt der Vorgang fehl.

.Ich habe eine MetroCluster-Konfiguration. Kann ich die FlexCache-Dualität nutzen?
Nein. FlexCache-Dualität wird in MetroCluster-Konfigurationen nicht unterstützt.

.Kann ich den S3-Zugriff auf Dateien in einem FlexCache S3 NAS-Bucket überwachen?
Die S3-Überwachung wird durch die NAS-Überwachungsfunktionalität bereitgestellt, die FlexCache-Volumes verwenden. Weitere Informationen zur NAS-Überwachung von FlexCache-Volumes finden Sie unter link:audit-flexcache-volumes-concept.html["Erfahren Sie mehr über FlexCache-Auditing"].

.Was sollte ich erwarten, wenn das Cache-Cluster vom Origin-Cluster getrennt wird?
S3-Anfragen an einen FlexCache S3-NAS-Bucket schlagen mit einem  `503 Service Unavailable` Fehler fehl, wenn der Cache-Cluster vom Ursprungscluster getrennt ist.

.Kann ich mehrteilige S3-Operationen mit FlexCache Dualität verwenden?
Damit S3-Multipart-Operationen funktionieren, muss das Feld „granulare Daten“ des zugrunde liegenden FlexCache-Volumes auf „erweitert“ gesetzt sein. Dieses Feld wird auf den Wert gesetzt, der für das Ursprungsvolume festgelegt ist.

.Unterstützt die Dualität von FlexCache HTTP- und HTTPS-Zugriff?
Ja. Standardmäßig ist HTTPS erforderlich. Sie können den S3-Dienst so konfigurieren, dass HTTP-Zugriff zugelassen wird, falls erforderlich.
