---
permalink: flexcache/global-file-locking-task.html 
sidebar: sidebar 
keywords: global file locking, flexcache, relationship 
summary: Sie können das globale Sperren von Dateien auf FlexCache Volumes aktivieren, wenn Sie über die Verfügbarkeit auf Konsistenz zugreifen möchten. 
---
= Globale Dateisperrung aktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.10.1 kann die globale Dateisperrung angewendet werden, um Lesevorgänge für alle im Cache gespeicherten Dateien zu vermeiden.

Wenn die globale Dateisperrung aktiviert ist, werden Änderungen am Ursprungs-Volume ausgesetzt, bis alle FlexCache Volumes online sind. Sie sollten die globale Dateisperrung nur aktivieren, wenn Sie die Zuverlässigkeit der Verbindungen zwischen Cache und Ursprung aufgrund von Suspensionen und möglichen Timeouts bei Offline-FlexCache-Volumes kontrollieren.

.Bevor Sie beginnen
* Für die globale Dateisperrung müssen die Cluster, die den Ursprung und alle zugehörigen Caches enthalten, ONTAP 9.9.1 oder höher ausführen. Die globale Dateisperrung kann auf neuen oder bestehenden FlexCache Volumes aktiviert werden. Der Befehl kann auf einem Volume ausgeführt werden und gilt für alle zugehörigen FlexCache Volumes.
* Sie müssen sich in der erweiterten Berechtigungsebene befinden, um die globale Dateisperrung zu aktivieren.
* Wenn Sie auf eine Version von ONTAP vor Version 9.9 zurücksetzen, muss die globale Dateisperrung zunächst für den Ursprung und die zugehörigen Caches deaktiviert werden. Führen Sie zum Deaktivieren vom Ursprungs-Volume aus: `volume flexcache prepare-to-downgrade -disable-feature-set 9.10.0`
* Der Prozess zum Aktivieren der globalen Dateisperrung hängt davon ab, ob der Ursprung über vorhandene Caches verfügt:
+
** <<enable-gfl-new>>
** <<enable-gfl-existing>>






== Globale Dateisperrung auf neuen FlexCache Volumes ermöglichen

.Schritte
. Erstellen Sie das FlexCache Volume mit `-is-global-file-locking` Auf „true“ setzen:
+
`volume flexcache create volume _volume_name_ -is-global-file-locking-enabled true`

+

NOTE: Der Standardwert von `-is-global-file-locking` Ist „`false`“. Wenn nachfolgende Informationen verfügbar sind `volume flexcache create` Befehle werden auf einem Volume ausgeführt, sie müssen mit übergeben werden `-is-global-file-locking enabled` Setzen Sie auf „`true`“.





== Globale Dateisperrung auf vorhandenen FlexCache Volumes ermöglichen

.Schritte
. Die globale Dateisperrung muss vom Ursprungsvolume festgelegt werden.
. Der Ursprung kann keine anderen bestehenden Beziehungen haben (z. B. SnapMirror). Bestehende Beziehungen müssen distanziert werden. Alle Caches und Volumes müssen zum Zeitpunkt der Ausführung des Befehls verbunden sein. Um den Verbindungsstatus zu überprüfen, führen Sie folgende Schritte aus:
+
`volume flexcache connection-status show`

+
Der Status aller aufgeführten Volumes sollte als angezeigt werden `connected.` Weitere Informationen finden Sie unter link:view-connection-status-origin-task.html["Anzeigen des Status einer FlexCache-Beziehung"] Oder link:synchronize-properties-origin-volume-task.html["Eigenschaften eines FlexCache-Volumes von einem Ursprung synchronisieren"].

. Globale Dateisperrung in den Caches aktivieren:
+
`volume flexcache origin config show/modify -volume _volume_name_ -is-global-file-locking-enabled true`


