---
permalink: flexcache/index.html 
sidebar: sidebar 
keywords: flexcache, volumes, faster, data, access, configure, manage, overview, origin volumes 
summary: Sie können FlexCache Volumes konfigurieren und verwalten, um den Datenzugriff zu beschleunigen. 
---
= Informationen zu ONTAP FlexCache Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp FlexCache Technologie beschleunigt den Dateizugriff, reduziert die WAN-Latenz und senkt die WAN-Bandbreite-Kosten für leseintensive Workloads, insbesondere wenn Clients wiederholt auf dieselben Daten zugreifen müssen. Wenn ein FlexCache volume erstellt wird, entsteht ein Remote-Cache eines bereits vorhandenen (Ursprungs-)Volumes, der nur die aktiv abgerufenen Daten (Hot Data) des Ursprungs-Volumes enthält.

Wenn ein FlexCache Volume eine Leseanforderung für die heißen Daten erhält, die es enthält, kann es schneller reagieren als das Ursprungsvolume, da die Daten nicht so weit zum Client übertragen werden müssen. Wenn ein FlexCache Volume eine Leseanforderung für selten gelesene Daten (kalte Daten) erhält, ruft es die benötigten Daten vom Ursprungsvolume ab und speichert sie, bevor die Client-Anfrage bedient wird. Nachfolgende Leseanforderungen für diese Daten werden dann direkt vom FlexCache Volume bedient. Nach der ersten Anfrage müssen die Daten nicht mehr über das Netzwerk übertragen oder von einem stark ausgelasteten System bereitgestellt werden. Ein Beispiel: Im Cluster treten an einem einzelnen Zugriffspunkt für häufig angeforderte Daten Engpässe auf. FlexCache Volumes können innerhalb des Clusters verwendet werden, um mehrere Mountpunkte für die heißen Daten bereitzustellen, wodurch die Engpässe reduziert und die Performance erhöht wird. Ein weiteres Beispiel: Es besteht die Notwendigkeit, den Netzwerkverkehr zu einem Volume zu verringern, auf das von mehreren Clustern zugegriffen wird. FlexCache Volumes können verwendet werden, um die heißen Daten vom Ursprungsvolume auf die Cluster im Netzwerk zu verteilen. Dadurch wird der WAN-Verkehr reduziert, da Benutzern näher gelegene Zugriffspunkte bereitgestellt werden.

Sie können auch die FlexCache Technologie nutzen, um die Leistung in Cloud- und Hybrid Cloud-Umgebungen zu verbessern. Ein FlexCache Volume kann beim Übergang von Workloads in die Hybrid Cloud unterstützen, indem Daten aus einem lokalen Rechenzentrum in die Cloud zwischengespeichert werden. Mit FlexCache Volumes lassen sich zudem Cloud-Silos auflösen, indem Daten von einem Cloud-Anbieter zu einem anderen oder zwischen zwei Regionen desselben Cloud-Anbieters zwischengespeichert werden.

Ab ONTAP 9.19.1 verbessert sich die Leistung, wenn Hunderte bis Tausende von Clients gleichzeitig dasselbe kleine NAS-Verzeichnis, 2 MB oder weniger (ca. 25.000 Dateien), auflisten. Diese Verbesserung reduziert den Bedarf an Workarounds wie lokalen FlexCache-Volumes, um eine hohe Anzahl von Clients zu unterstützen, die Verzeichnisauflistungen durchführen. Bei geringerer Client-Anzahl wird die Leistung nicht negativ beeinflusst. ONTAP 9.19.1 stellt mehr CPU-Ressourcen für die Verarbeitung von Auflistungsanfragen kleiner NAS-Verzeichnisse bereit. Diese Performance-Verbesserung ist automatisch und erfordert keine Konfiguration.

Ab ONTAP 9.10.1 ist es möglich, link:global-file-locking-task.html["Globale Dateisperrung aktivieren"] über alle FlexCache Volumes hinweg durchzuführen. Die globale Dateisperrung verhindert, dass ein Benutzer auf eine Datei zugreift, die bereits von einem anderen Benutzer geöffnet wurde. Aktualisierungen des Ursprungsvolumes werden dann gleichzeitig an alle FlexCache Volumes verteilt.

Ab ONTAP 9.9.1 führen FlexCache Volumes eine Liste nicht gefundener Dateien. Dies trägt zur Reduzierung des Netzwerkverkehrs bei, da nicht mehr mehrere Anfragen an den Ursprung gesendet werden müssen, wenn Clients nach nicht vorhandenen Dateien suchen.

Eine Liste zusätzlicher link:supported-unsupported-features-concept.html["Unterstützte Funktionen für FlexCache volumes und deren Ursprungsvolumes"], einschließlich einer Liste der unterstützten Protokolle nach ONTAP Version, ist ebenfalls verfügbar.

Weitere Informationen zur Architektur der ONTAP FlexCache Technologie finden sich in link:https://www.netapp.com/pdf.html?item=/media/7336-tr4743.pdf["TR-4743: FlexCache in ONTAP"^].



[[videos]]
== Videos



[[how-flexcache-can-reduce-wan-latency-and-read-times-for-global-data]]
=== Wie FlexCache WAN-Latenz und Lesezeiten für globale Daten reduzieren kann

video::rbbH0l74RWc[youtube,width=848,height=480]


[[learn-about-the-performance-benefits-of-ontap-flexcache]]
=== Informationen zu den Leistungsvorteilen von ONTAP FlexCache.

video::bWi1-8Ydkpg[youtube,width=848,height=480]