---
permalink: flexcache/sizing-concept.html 
sidebar: sidebar 
keywords: guidelines, sizing, flexcache, volume 
summary: Sie müssen sich über die Beschränkungen für FlexCache volumes im Klaren sein, bevor Sie mit der Bereitstellung der Volumes beginnen. 
---
= Richtlinien zur Dimensionierung von ONTAP FlexCache Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen sich über die Beschränkungen für FlexCache volumes im Klaren sein, bevor Sie mit der Bereitstellung der Volumes beginnen.

Die Größenbeschränkung eines FlexVol volume gilt für das Ursprungsvolumen. Die Größe eines FlexCache volume kann kleiner oder gleich der des Ursprungsvolumens sein. Die empfohlene Größe eines FlexCache volume beträgt mindestens 10 Prozent der Größe des Ursprungsvolumens.

Es sind außerdem die folgenden zusätzlichen Beschränkungen für FlexCache Volumes zu beachten:

[cols="55,15,15,15"]
|===


| Limit | ONTAP 9.8 und höher | ONTAP 9.7 | ONTAP 9.6 - 9.5 


| Maximale Anzahl von FlexCache Volumes, die aus einem Ursprungsvolume erstellt werden können | 100 | 10 | 10 


| Empfohlene maximale Anzahl von Ursprungsvolumes pro Knoten | 100 | 100 | 10 


| Empfohlene maximale Anzahl von FlexCache volumes pro Knoten | 100 | 100 | 10 


| Empfohlene maximale Anzahl von FlexGroup-Bestandteilen in einem FlexCache volume pro Node | 800 | 800 | 40 


| Maximale Anzahl von Bestandteilen pro FlexCache volume pro Knoten | 32 | 32 | 32 
|===