---
permalink: flexcache/synchronize-properties-origin-volume-task.html 
sidebar: sidebar 
keywords: synchronizing, properties, flexcache, volume, origin 
summary: Einige der Volume-Eigenschaften des FlexCache Volume müssen immer mit denen des Ursprungs-Volume synchronisiert werden. Wenn die Volume-Eigenschaften eines FlexCache-Volumes nicht automatisch synchronisiert werden, nachdem die Eigenschaften am Ursprungs-Volume geändert wurden, können Sie die Eigenschaften manuell synchronisieren. 
---
= Eigenschaften eines FlexCache-Volumes von einem Ursprungs-Volume synchronisieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Einige der Volume-Eigenschaften des FlexCache Volume müssen immer mit denen des Ursprungs-Volume synchronisiert werden. Wenn die Volume-Eigenschaften eines FlexCache-Volumes nicht automatisch synchronisiert werden, nachdem die Eigenschaften am Ursprungs-Volume geändert wurden, können Sie die Eigenschaften manuell synchronisieren.

.Über diese Aufgabe
Die folgenden Volume-Eigenschaften eines FlexCache Volume müssen immer mit denen des Ursprungs-Volume synchronisiert werden:

* Sicherheitsstil (`-security-style`)
* Volume-Name (`-volume-name`)
* Maximale Verzeichnisgröße (`-maxdir-size`)
* Minimale Vorauslesen (`-min-readahead`)


.Schritt
. Synchronisieren Sie auf dem FlexCache Volume die Volume-Eigenschaften:
+
`volume flexcache sync-properties -vserver svm_name -volume flexcache_volume`

+
[listing]
----
cluster1::> volume flexcache sync-properties -vserver vs1 -volume fc1
----

