---
permalink: volumes/assign-quota-policies-concept.html 
sidebar: sidebar 
keywords: considerations for, assigning, quota, policies 
summary: Eine Kontingentrichtlinie ist eine Gruppierung der Kontingentregeln für alle FlexVol Volumes einer SVM. Beim Zuweisen der Kontingentrichtlinien müssen Sie bestimmte Überlegungen beachten. 
---
= Überlegungen für die Zuweisung von Quotenrichtlinien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Eine Kontingentrichtlinie ist eine Gruppierung der Kontingentregeln für alle FlexVol Volumes einer SVM. Beim Zuweisen der Kontingentrichtlinien müssen Sie bestimmte Überlegungen beachten.

* Einer SVM wird eine Kontingentrichtlinie zu einem beliebigen Zeitpunkt zugewiesen. Beim Erstellen einer SVM wird eine leere Kontingentrichtlinie erstellt und dieser SVM zugewiesen. Diese Standard-Kontingentrichtlinie hat den Namen „Standard“, es sei denn, bei der Erstellung der SVM wird ein anderer Name angegeben.
* Eine SVM kann bis zu fünf Kontingentrichtlinien verwenden. Wenn eine SVM über fünf Kontingentrichtlinien verfügt, können Sie keine neue Kontingentrichtlinie für die SVM erstellen, bis Sie eine vorhandene Kontingentrichtlinie löschen.
* Wenn eine Kontingentregel erstellt oder Quotenregeln für eine Kontingentrichtlinie geändert werden müssen, können Sie eine der folgenden Ansätze wählen:
+
** Wenn Sie eine Kontingentrichtlinie verwenden, die einer SVM zugewiesen ist, müssen Sie dieser SVM nicht zuweisen.
** Wenn Sie eine nicht zugewiesene Kontingentrichtlinie verwenden und dann die Kontingentrichtlinie der SVM zuweisen, müssen Sie über ein Backup der Kontingentrichtlinie verfügen, auf die Sie bei Bedarf zurücksetzen können.
+
Sie können beispielsweise eine Kopie der zugewiesenen Kontingentrichtlinie erstellen, die Kopie ändern, die Kopie der SVM zuweisen und die ursprüngliche Kontingentrichtlinie umbenennen.



* Sie können eine Kontingentrichtlinie umbenennen, selbst wenn sie der SVM zugewiesen ist.

