---
permalink: volumes/assign-volume-efficiency-policy-task.html 
sidebar: sidebar 
keywords: assign, volume efficiency policy, volume, efficiency policy 
summary: Einem Volume kann eine Effizienzrichtlinie zugewiesen werden, um Deduplizierungs- oder Datenkomprimierungsvorgänge mit dem Befehl volume efficiency modify auszuführen. 
---
= Weisen Sie einem ONTAP Volume eine Effizienzrichtlinie zu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einem Volume eine Effizienzrichtlinie zuweisen, um Deduplizierungs- oder Datenkomprimierungsvorgänge mithilfe des  `volume efficiency modify` Befehls auszuführen.

.Bevor Sie beginnen
Stellen Sie sicher, dass Sie link:create-efficiency-policy-task.html["die Effizienzrichtlinie für das Volume erstellen"] ausführen, bevor Sie es einem Volume zuweisen.

.Über diese Aufgabe
Wenn einer Effizienzrichtlinie einem SnapVault sekundären Volume zugewiesen ist, wird bei der Ausführung von Volume-Effizienzoperationen nur das Attribut für die Priorität der Volume-Effizienz berücksichtigt. Die Jobpläne werden ignoriert und die Deduplizierungsoperation wird ausgeführt, wenn inkrementelle Aktualisierungen am SnapVault sekundären Volume vorgenommen werden.

.Schritt
. Mit dem  `volume efficiency modify` Befehl lässt sich einem Volume eine Richtlinie zuweisen.


.Beispiel
Der folgende Befehl weist die Effizienzrichtlinie mit dem Namen `new_policy`dem Volume `VolA`zu:

`volume efficiency modify -vserver vs1 -volume VolA -policy new_policy`

Weitere Informationen zu  `volume efficiency modify` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-modify.html["ONTAP-Befehlsreferenz"^].
