---
permalink: volumes/automatic-deduplication-schedule-aff-concept.html 
sidebar: sidebar 
keywords: manage, automatic, volume-level, background, deduplication, aff systems 
summary: Ab ONTAP 9.3 kann die Hintergrund-Deduplizierung auf Volume-Ebene mithilfe einer vordefinierten AutoAll Flash FAS Richtlinie automatisch durchgeführt werden. Es ist keine manuelle Konfiguration der Zeitpläne erforderlich. Die automatische Richtlinie führt eine kontinuierliche Deduplizierung im Hintergrund durch. 
---
= Automatische Hintergrund-Deduplizierung auf Volume-Ebene auf AFF Systemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.3 kann die Hintergrund-Deduplizierung auf Volume-Ebene so konfiguriert werden, dass sie automatisch anhand vorab definierter Konfigurationen ausgeführt wird `auto` AFF-Richtlinie: Es ist keine manuelle Konfiguration der Zeitpläne erforderlich. Der `auto` Die Richtlinie führt eine kontinuierliche Deduplizierung im Hintergrund durch.

Der `auto` Es wird eine Richtlinie für alle neu erstellten Volumes und für alle aktualisierten Volumes festgelegt, die nicht manuell für die Deduplizierung im Hintergrund konfiguriert wurden. Das können Sie link:assign-volume-efficiency-policy-task.html["Ändern Sie die Richtlinie"] Bis `default` Oder andere Richtlinien zum Deaktivieren der Funktion.

Wenn ein Volume sich von einem System anderer Hersteller auf ein AFF System verschiebt, wird der entsprechende Schritt durchgeführt `auto` Die Richtlinie ist standardmäßig auf dem Ziel-Node aktiviert. Wenn ein Volume von einem AFF Node zu einem Node ohne All Flash FAS verschoben wird, wird der `auto` Richtlinien auf dem Ziel-Node werden durch das ersetzt `inline-only` Richtlinie ist standardmäßig festgelegt.

Auf AFF überwacht das System alle Volumes, die über die verfügen `auto` Richtlinien und priorisiert das Volume, das weniger Einsparungen verzeichnet oder häufige Überschreibungen hat. Die deprioritsierten Volumes nehmen nicht mehr an der automatischen Hintergrund-Deduplizierung Teil. Die Änderungsprotokollierung auf deprioritierten Volumes wird deaktiviert und die Metadaten auf dem Volume werden gekürzt.

Benutzer können das Volume mit niedriger Priorität zur erneuten Teilnahme an einer automatischen Hintergrund-Deduplizierung mithilfe der heraufstufen `volume efficiency promote` Befehl ist auf der erweiterten Berechtigungsebene verfügbar.
