---
permalink: volumes/autoshrink-snapshot-copy-deletion-concept.html 
sidebar: sidebar 
keywords: how, autoshrink functionality, interacts with, snapshot copy, deletion, automatic 
summary: Da die Funktion für automatische Snapshot die Größe eines FlexVol Volumes verringert, kann es auch Auswirkungen haben, wenn Volume Snapshot Kopien automatisch gelöscht werden. 
---
= Autoshrink-Funktion und Löschen von Snapshot-Kopien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Da die Funktion für automatische Snapshot die Größe eines FlexVol Volumes verringert, kann es auch Auswirkungen haben, wenn Volume Snapshot Kopien automatisch gelöscht werden.

Die Funktion für automatische Snapshot-Erstellung interagiert mit dem automatischen Löschen von Volume Snapshot-Kopien und bietet folgende Möglichkeiten:

* Wenn sowohl der `grow_shrink` Autosize-Modus als auch das automatische Löschen von Snapshot Kopien aktiviert sind, kann eine verkleinerung der Volume-Größe das Löschen von Snapshot Kopien auslösen.
+
Das liegt daran, dass die Snapshot Reserve auf einem Prozentsatz der Volume-Größe basiert (standardmäßig 5 Prozent), und der Prozentsatz basierend nun auf einer kleineren Volume-Größe. Dadurch können Snapshot Kopien aus der Reserve entfernt und automatisch gelöscht werden.

* Wenn der `grow_shrink` Autosize-Modus aktiviert ist und Sie eine Snapshot Kopie manuell löschen, kann es zu einer automatischen Volume-Verkleinerung kommen.

