---
permalink: volumes/automatic-deduplication-schedule-aff-concept.html 
sidebar: sidebar 
keywords: manage, automatic, volume-level, background, deduplication, aff systems 
summary: Ab ONTAP 9.3 kann die Hintergrund-Deduplizierung auf Volume-Ebene mithilfe einer vordefinierten AutoAll Flash FAS Richtlinie automatisch durchgeführt werden. Es ist keine manuelle Konfiguration der Zeitpläne erforderlich. Die automatische Richtlinie führt eine kontinuierliche Deduplizierung im Hintergrund durch. 
---
= Automatische Hintergrund-Deduplizierung auf Volume-Ebene auf AFF Systemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.3 können Sie die Hintergrund-Deduplizierung auf Volume-Ebene so konfigurieren, dass sie automatisch mithilfe einer vordefinierten `auto` AFF Richtlinie ausgeführt wird. Es ist keine manuelle Konfiguration der Zeitpläne erforderlich. Die `auto` Richtlinie führt eine kontinuierliche Deduplizierung im Hintergrund durch.

Die `auto` Richtlinie gilt für alle neu erstellten Volumes und für alle aktualisierten Volumes, die nicht manuell für die Hintergrund-Deduplizierung konfiguriert wurden. Sie können link:assign-volume-efficiency-policy-task.html["Ändern Sie die Richtlinie"] zu `default` oder jede andere Richtlinie, um die Funktion zu deaktivieren.

Wenn ein Volume von einem nicht-AFF System auf ein AFF System verschoben `auto` wird, ist die Richtlinie standardmäßig auf dem Ziel-Node aktiviert. Wenn ein Volume von einem AFF Node auf einen Node ohne AFF verschoben `auto` wird, wird die Richtlinie für den Ziel-Node `inline-only` standardmäßig durch die Richtlinie ersetzt.

Bei AFF überwacht das System alle Volumes mit der `auto` Richtlinie und priorisiert das Volume mit weniger Einsparungen oder häufigen Überschreibungen. Die deprioritsierten Volumes nehmen nicht mehr an der automatischen Hintergrund-Deduplizierung Teil. Die Änderungsprotokollierung auf deprioritierten Volumes wird deaktiviert und die Metadaten auf dem Volume werden gekürzt.

Die Benutzer können das depriorisierte Volume so erhöhen, dass `volume efficiency promote` sie mithilfe des Befehls auf der erweiterten Berechtigungsebene erneut an eine automatische Hintergrund-Deduplizierung teilnehmen.

Erfahren Sie mehr über `volume efficiency promote` in der link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-promote.html["ONTAP-Befehlsreferenz"^].
