---
permalink: volumes/automatic-deduplication-schedule-aff-concept.html 
sidebar: sidebar 
keywords: manage, automatic, volume-level, background, deduplication, aff systems 
summary: Ab ONTAP 9.3 kann die Hintergrunddeduplizierung auf Volume-Ebene mithilfe einer vordefinierten autoAFF-Richtlinie automatisch gesteuert werden. Eine manuelle Konfiguration der Zeitpläne ist nicht erforderlich. Die auto-Richtlinie führt die Deduplizierung kontinuierlich im Hintergrund durch. 
---
= Automatische Hintergrunddeduplizierung auf Volumenebene auf AFF Systemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.3 kann die Hintergrunddeduplizierung auf Volume-Ebene so konfiguriert werden, dass sie automatisch mithilfe einer vordefinierten `auto` AFF Richtlinie ausgeführt wird. Eine manuelle Konfiguration der Zeitpläne ist nicht erforderlich. Die `auto` Richtlinie führt die Deduplizierung kontinuierlich im Hintergrund durch.

Die `auto` Richtlinie gilt für alle neu erstellten Volumes und für alle aktualisierten Volumes, die nicht manuell für die Hintergrunddeduplizierung konfiguriert wurden. Es besteht die Möglichkeit, link:assign-volume-efficiency-policy-task.html["die Richtlinie ändern"] zu  `default` oder eine andere Richtlinie zu verwenden, um die Funktion zu deaktivieren.

Wenn ein Volume von einem System ohne AFF auf ein AFF System verschoben wird, wird die  `auto` Richtlinie auf dem Zielknoten standardmäßig aktiviert. Wenn ein Volume von einem AFF Knoten auf einen Knoten ohne AFF verschoben wird, wird die  `auto` Richtlinie auf dem Zielknoten standardmäßig durch die  `inline-only` Richtlinie ersetzt.

Auf AFF überwacht das System alle Volumes, die die  `auto` Richtlinie anwenden, und priorisiert das Volume herab, das geringere Einsparungen aufweist oder häufig überschrieben wird. Die herabgestuften Volumes nehmen nicht mehr an der automatischen Hintergrund-Deduplizierung teil. Die Protokollierung von Änderungen auf herabgestuften Volumes ist deaktiviert und die Metadaten auf dem Volume werden gekürzt.

Benutzer können das depriorisierte Volume mithilfe des  `volume efficiency promote` Befehls auf der erweiterten Berechtigungsstufe wieder in die automatische Hintergrunddeduplizierung einbeziehen.

Weitere Informationen zu  `volume efficiency promote` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-promote.html["ONTAP-Befehlsreferenz"^].
