---
permalink: volumes/change-existing-quota-limits-task.html 
sidebar: sidebar 
keywords: modify, resize, quota limits 
summary: Wenn Sie die Größe bestehender Quoten ändern, können Sie die Kontingente auf allen betroffenen Volumes anpassen, was schneller als die Quoten für diese Volumen neu initialisiert werden. 
---
= Ändern (oder Ändern) von Quota-Limits
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die Größe bestehender Quoten ändern, können Sie die Kontingente auf allen betroffenen Volumes anpassen, was schneller als die Quoten für diese Volumen neu initialisiert werden.

Sie verfügen über eine Storage Virtual Machine (SVM, ehemals bekannt als Vserver) mit erzwungenen Kontingenten und Sie möchten entweder die Größenbeschränkungen vorhandener Kontingente ändern oder Quoten für Ziele mit bereits abgeleiteten Kontingenten hinzufügen oder löschen.

.Schritte
. Verwenden Sie die `vserver show` Befehl mit dem `-instance` Parameter, um den Namen der Richtlinie zu bestimmen, die derzeit der SVM zugewiesen ist.
. Ändern Sie die Kontingentregeln, indem Sie eine der folgenden Aktionen ausführen:
+
** Verwenden Sie die `volume quota policy rule modify` Befehl zum Ändern der Festplatten- oder Dateigrenzen vorhandener Kontingentregeln.
** Verwenden Sie die `volume quota policy rule create` Befehl zum Erstellen expliziter Quotenregeln für Ziele (Benutzer, Gruppen oder qtrees), die derzeit Kontingente haben.
** Verwenden Sie die `volume quota policy rule delete` Befehl zum Löschen von expliziten Quotenregeln für Ziele (Benutzer, Gruppen oder qtrees), die auch Standardquoten haben.


. Verwenden Sie die `volume quota policy rule show` Befehl zum Überprüfen der ordnungsgemäßen Konfiguration der Kontingentregeln.
. Verwenden Sie die `volume quota resize` Befehl für jedes Volume, in dem Sie Quoten geändert haben, um die Änderungen für jedes Volume zu aktivieren.
+
Sie können den Größenänderungsprozess auf eine der folgenden Arten überwachen:

+
** Wenn Sie das verwenden `volume quota resize` Befehl, Sie können den hinzufügen `-foreground` Parameter, um die Größe des Jobs im Vordergrund auszuführen. (Der Job wird standardmäßig im Hintergrund ausgeführt.)
+
Wenn der Job im Hintergrund ausgeführt wird, können Sie den Fortschritt mit dem überwachen `job show` Befehl.

** Sie können das verwenden `volume quota show` Befehl zum Überwachen des Status der Größe.


. Verwenden Sie die `volume quota show -instance` Befehl, um die Größe von Fehlern zu überprüfen, z. B. Quota-Regeln, die die Größe nicht abrufen konnten.
+
Überprüfen Sie insbesondere die Fehler „`New Definition`“, die auftreten, wenn Sie die Größe der Quoten ändern, nachdem Sie ein explizites Kontingent für ein Ziel hinzugefügt haben, das noch keine abgeleitete Quote hat.

. Verwenden Sie die `volume quota report` Befehl zum Anzeigen eines Quotenberichts, damit Sie sicherstellen können, dass die erzwungenen Quoten ihren Anforderungen entsprechen.

