---
permalink: volumes/change-maximum-number-files-allowed-concept.html 
sidebar: sidebar 
keywords: considerations, changing, maximum number of files, allowed, flexvol volume, maximum, files, file 
summary: FlexVol volumes haben eine maximale Anzahl an Dateien, die sie enthalten können. Das Maximum kann geändert werden, wobei zu berücksichtigen ist, wie sich dies auf das Volume auswirkt. 
---
= Die standardmäßige und die maximale Anzahl der für ONTAP FlexVol Volumes zulässigen Dateien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexVol volumes haben eine Standard- und eine maximale Anzahl an Dateien, die sie enthalten können. Wenn Ihre Daten eine große Anzahl an Dateien erfordern, kann die Anzahl der für Benutzer sichtbaren Dateien auf einem Volume bis zu einem Maximalwert erhöht werden. Vor dem weiteren Vorgehen sollten die Einschränkungen und Besonderheiten bekannt sein.

Die Anzahl der für Benutzer sichtbaren Dateien, die ein Volume enthalten kann, wird durch die verfügbare Inode-Kapazität des Volumes bestimmt. Ein Inode ist eine Datenstruktur, die Informationen über Dateien enthält.

ONTAP legt die Standard- und Maximalanzahl der verfügbaren Inodes für ein neu erstelltes Volume automatisch anhand der Größe des Volumes wie folgt fest.

[cols="2,2"]
|===
| Standardanzahl an Inodes | Maximale Anzahl von Inodes 


| 1 pro 32 KB Volumengröße | 1 pro 4 KB Volumengröße 
|===
Wird die Größe eines Volumes entweder manuell durch einen Administrator oder automatisch durch die automatische Größenanpassung von ONTAP erhöht, erhöht ONTAP (falls erforderlich) auch die Anzahl der verfügbaren Inodes, sodass mindestens 1 Inode pro 32 KB Volume-Größe vorhanden ist, bis das Volume eine Größe von etwa 680 GB erreicht.

In ONTAP 9.12.1 und früheren Versionen führt das Erstellen eines neuen Volumes oder das Ändern der Größe eines vorhandenen Volumes auf mehr als 680 GB nicht automatisch zu zusätzlicher Inode-Kapazität. Wenn mehr Dateien als die Standardanzahl für ein Volume beliebiger Größe benötigt werden, kann mit dem  `volume modify` Befehl die verfügbare Anzahl an Inodes für das Volume bis zum Maximum erhöht werden.

Ab ONTAP 9.13.1 wird beim Erstellen eines neuen Volumes oder beim Ändern der Größe eines bestehenden Volumes die Standardanzahl der verfügbaren Inodes auf 1 Inode pro 32 KB Volume-Speicherplatz festgelegt, selbst wenn das Volume größer als 680 GB ist. Dieses Verhältnis bleibt bestehen, bis das Volume das absolute Inode-Maximum von 2.040.109.451 erreicht.

Sie können auch die Anzahl der verfügbaren Inodes verringern. Dadurch ändert sich nicht der für Inodes reservierte Speicherplatz, aber die maximale Menge an Speicherplatz, die die öffentliche Inode-Datei belegen kann, wird verringert. Nachdem Speicherplatz für Inodes reserviert wurde, wird er dem Volume nie zurückgegeben. Daher ist es nicht möglich, die maximale Anzahl an Inodes unter die aktuell reservierte Anzahl zu senken.

.Weitere Informationen
* xref:display-file-inode-usage-task.html[Datei- und Inode-Nutzung für ein Volume ermitteln]
* link:++https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/FAQ_-_ONTAP_default_and_maximum_number_of_files_(inodes)++["NetApp Knowledge Base: FAQ – ONTAP Standard- und Maximalanzahl von Dateien (Inodes)"^]

