---
permalink: volumes/commands-manage-quota-rules-policies-reference.html 
sidebar: sidebar 
keywords: commands to, manage, quota rules, quota policies, command, commands, quota, quotas, policy, policies 
summary: ' `volume quota policy rule`Mit den Befehlen können Sie Kontingentregeln konfigurieren, und die `volume quota policy` Befehle und einige Befehle `vserver` ermöglichen das Konfigurieren von Kontingentrichtlinien.' 
---
= Befehle für das Management von Kontingentregeln und Kontingentrichtlinien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 `volume quota policy rule`Mit den Befehlen können Sie Kontingentregeln konfigurieren, und die `volume quota policy` Befehle und einige Befehle `vserver` ermöglichen das Konfigurieren von Kontingentrichtlinien. Verwenden Sie abhängig davon, was Sie tun müssen, die folgenden Befehle, um Quota-Regeln und Quota-Richtlinien zu verwalten:


NOTE: Sie können die folgenden Befehle nur auf FlexVol Volumes ausführen.



== Befehle für das Management von Kontingentregeln

[cols="2*"]
|===
| Ihr Ziel ist | Befehl 


 a| 
Erstellen Sie eine neue Quota-Regel
 a| 
`volume quota policy rule create`



 a| 
Vorhandene Kontingentregel löschen
 a| 
`volume quota policy rule delete`



 a| 
Vorhandene Kontingentregel ändern
 a| 
`volume quota policy rule modify`



 a| 
Informationen zu konfigurierten Quotenregeln anzeigen
 a| 
`volume quota policy rule show`

|===


== Befehle für das Management von Kontingentrichtlinien

[cols="2*"]
|===
| Ihr Ziel ist | Befehl 


 a| 
Eine Kontingentrichtlinie und die darin enthaltenen Kontingentregeln duplizieren
 a| 
`volume quota policy copy`



 a| 
Erstellen Sie eine neue, leere Kontingentrichtlinie
 a| 
`volume quota policy create`



 a| 
Vorhandene Kontingentrichtlinie löschen, die derzeit keiner Storage Virtual Machine (SVM) zugewiesen ist
 a| 
`volume quota policy delete`



 a| 
Benennen Sie eine Kontingentrichtlinie um
 a| 
`volume quota policy rename`



 a| 
Zeigt Informationen zu Kontingentrichtlinien an
 a| 
`volume quota policy show`



 a| 
Zuweisung einer Kontingentrichtlinie zu einer SVM
 a| 
`vserver modify -quota-policy _policy_name_`



 a| 
Zeigt den Namen der Kontingentrichtlinie an, die einer SVM zugewiesen ist
 a| 
`vserver show`

|===
Siehe link:https://docs.netapp.com/us-en/ontap-cli["Befehlsreferenz für ONTAP"^] Für jeden Befehl, um weitere Informationen zu erhalten.
