---
permalink: volumes/commands-display-space-usage-reference.html 
sidebar: sidebar 
keywords: commands for, displaying, space, usage, information, display 
summary: Sie verwenden die Befehle für Storage-Aggregate und Volumes, um zu sehen, wie der Speicherplatz in Ihren Aggregaten und Volumes und ihren Snapshots genutzt wird. 
---
= Befehle zum Anzeigen von Informationen zur Speicherplatznutzung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie verwenden die `storage aggregate` Befehle und `volume`, um zu sehen, wie Platz in Ihren Aggregaten und Volumes und ihren Snapshots verwendet wird.

Ab ONTAP 9.18.1 ändert der `storage aggregate show-space` Befehl die Art und Weise, wie die logische referenzierte Kapazität und die logische nicht referenzierte Kapazität gemeldet werden. Die logische referenzierte Kapazität meldet referenzierte Blöcke in allen Objekten und nicht referenzierte Blöcke in fragmentierten Objekten. Die logische nicht referenzierte Kapazität meldet nur nicht referenzierte Blöcke in Objekten, die den Füllschwellenwert überschritten haben und für die Objektlöschung und Defragmentierung in Frage kommen.

Wenn Sie beispielsweise den standardmäßigen Schwellenwert für die aggregierte Auslastung von 40 % für ONTAP S3 und StorageGRID verwenden, müssen 60 % der Blöcke in einem Objekt nicht referenziert sein, bevor die Blöcke als nicht referenzierte Kapazität gemeldet werden.

In Versionen vor ONTAP 9.18.1 meldet die logische referenzierte Kapazität referenzierte Blöcke in allen Objekten (sowohl vollständigen als auch fragmentierten Objekten). Die logische nicht referenzierte Kapazität meldet nicht referenzierte Blöcke in allen Objekten.

[cols="2*"]
|===
| So zeigen Sie Informationen über... | Befehl 


 a| 
Aggregate, einschließlich Details zu verwendeten und verfügbaren Prozentsätzen, der Größe der Snapshot-Reserve und anderen Informationen zur Speicherplatznutzung
 a| 
`storage aggregate show`

`storage aggregate show-space -fields snap-size-total,used-including-snapshot-reserve`



 a| 
Wie Festplatten und RAID-Gruppen in einem Aggregat und RAID-Status verwendet werden
 a| 
`storage aggregate show-status`



 a| 
Die Menge an Festplattenspeicher, die zurückgewonnen werden würde, wenn Sie einen bestimmten Snapshot gelöscht haben
 a| 
`volume snapshot compute-reclaimable` (Erweitert)



 a| 
Die Menge an Speicherplatz, der von einem Volume verbraucht wird
 a| 
`volume show -fields size,used,available,percent-used`

`volume show-space`



 a| 
Die Menge an Speicherplatz, der von einem Volume im enthaltenden Aggregat genutzt wird
 a| 
`volume show-footprint`

|===
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+aggregate+show["Storage-Aggregate zeigen"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-space.html["Lageraggregat-Show-Space"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-status.html["Speicheraggregat-Status anzeigen"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-compute-reclaimable.html["Rechenbarer Volume-Snapshot"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-show.html["Volumen anzeigen"^]

