---
permalink: volumes/commands-move-volumes-reference.html 
sidebar: sidebar 
keywords: commands, moving, volumes, to move 
summary: Es gibt bestimmte ONTAP Befehle zum Managen der Volume-Verschiebung. 
---
= Befehle zum Verschieben von Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es gibt bestimmte ONTAP Befehle zum Managen der Volume-Verschiebung.

[cols="2*"]
|===
| Ihr Ziel ist | Befehl 


 a| 
Abbrechen eines aktiven Volume-Move-Vorgangs.
 a| 
`volume move abort`



 a| 
Status der Verschiebung eines Volumes von einem Aggregat zu einem anderen Aggregat anzeigen
 a| 
`volume move show`



 a| 
Beginnen Sie mit der Verschiebung eines Volumes von einem Aggregat zu einem anderen Aggregat.
 a| 
`volume move start`



 a| 
Managen von Zielaggregaten für die Verschiebung von Volumes
 a| 
`volume move target-aggr`



 a| 
Stoßen Sie bei der Umstellung eines Move-Jobs an.
 a| 
`volume move trigger-cutover`



 a| 
Ändern Sie die Zeitspanne, in der der Client-Zugriff gesperrt ist, wenn die Standardeinstellung nicht ausreichend ist.
 a| 
`volume move start` Oder `volume move modify` Mit dem `-cutover-window` Parameter. Der `volume move modify` Der Befehl ist ein erweiterter Befehl und der `-cutover-window` Ist ein erweiterter Parameter.



 a| 
Legen Sie fest, was das System tut, wenn die Verschiebung des Volumes nicht während des Sperrens des Client-Zugriffs abgeschlossen werden kann.
 a| 
`volume move start` Oder `volume move modify` Mit dem `-cutover-action` Parameter. Der `volume move modify` Der Befehl ist ein erweiterter Befehl und der `-cutover-action` Ist ein erweiterter Parameter.

|===
Weitere Informationen finden Sie auf der man-Page für jeden Befehl.
