---
permalink: volumes/commands-configure-deletion-flexclone-reference.html 
sidebar: sidebar 
keywords: commands for, configuring, deletion of, flexclone files, configure, command, delete, deletion, files, file 
summary: Wenn Clients FlexClone Dateien löschen, ohne den NetApp Manageability SDK zu verwenden, können Sie die Befehle zum Löschen von Volume-Dateien verwenden, um eine schnellere Löschung von FlexClone Dateien von einem FlexVol Volume zu ermöglichen. 
---
= Befehle zum Konfigurieren des Löschens von FlexClone Dateien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Clients FlexClone-Dateien löschen, ohne das NetApp Manageability SDK zu verwenden, können Sie die `volume file clone deletion` Befehle verwenden, um das schnellere Löschen von FlexClone-Dateien aus einem FlexVol volume zu ermöglichen. Erweiterungen für und eine minimale Größe von FlexClone-Dateien werden verwendet, um schnelleres Löschen zu ermöglichen.

Sie können die `volume file clone deletion` Befehle verwenden, um eine Liste der unterstützten Erweiterungen und eine Mindestgröße für FlexClone-Dateien in einem Volume anzugeben. Die schnellere Löschung wird nur für FlexClone Dateien eingesetzt, die die Anforderungen erfüllen. Bei FlexClone Dateien, die den Anforderungen nicht entsprechen, wird die langsamere Löschmethode verwendet.

Wenn Clients FlexClone Dateien und FlexClone LUNs aus einem Volume mithilfe des NetApp Manageability SDK löschen, gelten die Erweiterungs- und Größenanforderungen nicht, da die schnellere Löschmethode immer verwendet wird.

[cols="2*"]
|===
| An... | Befehl 


 a| 
Fügen Sie eine Erweiterung zur unterstützten Liste von Erweiterungen für das Volume hinzu
 a| 
`volume file clone deletion add-extension`



 a| 
Ändern Sie die minimale Größe von FlexClone Dateien, die aus dem Volume gelöscht werden können, indem Sie die schnellere Löschmethode verwenden
 a| 
`volume file clone deletion modify`



 a| 
Entfernen Sie eine Erweiterung aus der unterstützten Liste der Erweiterungen für das Volume
 a| 
`volume file clone deletion remove-extension`



 a| 
Hier finden Sie eine Liste der unterstützten Erweiterungen und die Mindestgröße von FlexClone Dateien, die Clients mithilfe der schnelleren Löschmethode aus dem Volume löschen können
 a| 
`volume file clone deletion show`

|===
Ausführliche Informationen zu diesen Befehlen finden Sie in der entsprechenden man-Page.
