---
permalink: volumes/configure-automatic-provide-space-when-full-task.html 
sidebar: sidebar 
keywords: configure, volumes, automatically, provide, space, full, increase, size, automatic, grow, autogrow 
summary: Wenn die Kapazität von FlexVol Volumes voll ist, kann ONTAP automatisch versuchen, mit einer der verschiedenen Methoden mehr freien Speicherplatz für das Volume bereitzustellen. 
---
= Konfigurieren Sie Volumes, um automatisch mehr Speicherplatz zur Verfügung zu stellen, wenn diese voll sind
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn FlexVol Volumes voll sind, kann ONTAP verschiedene Methoden verwenden, um automatisch mehr freien Speicherplatz für das Volume bereitzustellen. Je nach den Anforderungen Ihrer Applikations- und Storage-Architektur können Sie wählen, welche ONTAP Methoden in welcher Reihenfolge verwendet werden.

.Über diese Aufgabe
ONTAP kann automatisch mit einer oder beiden der folgenden Methoden mehr freien Speicherplatz für ein vollständiges Volume bereitstellen:

* Vergrößern Sie die Volume-Größe (bekannt als _Autogrow_).
+
Diese Methode ist nützlich, wenn das Aggregat, das ein Volume enthält, genügend Platz zur Unterstützung eines größeren Volumes hat. Sie können ONTAP so konfigurieren, dass für das Volume eine maximale Größe festgelegt wird. Die Erhöhung wird automatisch basierend auf der auf dem Volume geschriebenen Datenmenge in Bezug auf die aktuelle Menge des belegten Speicherplatzes und die festgelegten Grenzwerte ausgelöst.

+
Autogrow wird nicht zur Unterstützung der Snapshot-Erstellung ausgelöst. Wenn Sie versuchen, einen Snapshot zu erstellen, und nicht genügend Speicherplatz vorhanden ist, schlägt die Erstellung des Snapshots fehl, selbst bei aktivierter Autogrow.

* Löschen Sie Snapshots, FlexClone-Dateien oder FlexClone-LUNs.
+
Sie können beispielsweise ONTAP so konfigurieren, dass Snapshots automatisch gelöscht werden, die nicht mit Snapshots in geklonten Volumes oder LUNs verknüpft sind, oder Sie können festlegen, welche Snapshots ONTAP zuerst löschen soll – Ihre ältesten oder neuesten Snapshots. Sie können auch bestimmen, wann ONTAP Snapshots löschen soll - zum Beispiel, wenn das Volume fast voll ist oder wenn die Snapshot-Reserve des Volumes fast voll ist.



Wenn Sie diese beiden Methoden aktivieren, können Sie angeben, welche Methode ONTAP zuerst versucht, wenn ein Volume fast voll ist. Wenn die erste Methode nicht ausreichend zusätzlichen Speicherplatz für das Volume zur Verfügung stellt, versucht ONTAP als Nächstes die andere Methode.

Standardmäßig versucht ONTAP, zuerst die Größe des Volumes zu erhöhen. In den meisten Fällen ist die Standardkonfiguration vorzuziehen, da sie beim Löschen eines Snapshots nicht wiederhergestellt werden kann. Falls Sie jedoch vermeiden müssen, die Größe eines Volumes nach Möglichkeit zu vergrößern, können Sie ONTAP so konfigurieren, dass Snapshots gelöscht werden, bevor Sie die Größe des Volumes erhöhen.

.Schritte
. Wenn Sie möchten, dass ONTAP versucht, die Größe des Volumes zu erhöhen, wenn es voll wird, aktivieren Sie die Autogrow Funktion für das Volume, indem Sie den `volume autosize` Befehl mit dem `grow` Modus verwenden.
+
Beachten Sie, dass wenn das Volume wächst, dass es mehr freien Speicherplatz vom zugehörigen Aggregat verbraucht. Wenn das Volumen nach Bedarf wachsen kann, müssen Sie den freien Speicherplatz im zugehörigen Aggregat überwachen und bei Bedarf weitere hinzufügen.

. Wenn ONTAP Snapshots, FlexClone-Dateien oder FlexClone-LUNs löschen soll, wenn das Volume voll ist, aktivieren Sie Autodelete für diese Objekttypen.
. Wenn Sie sowohl die Volume Autogrow Funktion als auch eine oder mehrere Autodelete-Funktionen aktiviert haben, wählen Sie die erste Methode, die ONTAP verwenden sollte, um einem Volume freien Speicherplatz zu bieten. Verwenden Sie dazu den `volume modify` Befehl mit der `-space-mgmt-try-first` Option.
+
Um festzulegen, wie die Größe des Volumes zuerst erhöht werden soll (Standardeinstellung), verwenden Sie `volume_grow`. Um das Löschen von Snapshots festzulegen, verwenden Sie `snap_delete`.


