---
permalink: volumes/convert-directory-qtree-unix-client-task.html 
sidebar: sidebar 
keywords: convert, directory to a qtree, using, unix client 
summary: Um ein Verzeichnis in UNIX in einen Qtree umzuwandeln, wird das Verzeichnis umbenannt, ein Qtree auf dem Speichersystem erstellt und der Inhalt des Verzeichnisses in den Qtree verschoben. 
---
= Verwenden Sie einen UNIX-Client, um ein ONTAP Volume-Verzeichnis in ein qtree zu konvertieren.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um ein Verzeichnis in UNIX in einen Qtree umzuwandeln, wird das Verzeichnis umbenannt, ein Qtree auf dem Speichersystem erstellt und der Inhalt des Verzeichnisses in den Qtree verschoben.

.Schritte
. Ein UNIX-Clientfenster öffnen.
. Der  `mv`Befehl dient zum Umbenennen des Verzeichnisses.
+
[listing]
----
client: mv /n/user1/vol1/dir1 /n/user1/vol1/olddir
----
. Im Speichersystem wird der  `volume qtree create` Befehl verwendet, um einen Qtree mit dem ursprünglichen Namen zu erstellen.
+
[listing]
----
system1: volume qtree create /n/user1/vol1/dir1
----
+
Weitere Informationen zu  `volume qtree create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-qtree-create.html["ONTAP-Befehlsreferenz"^].

. Vom Client aus mit dem  `mv` Befehl den Inhalt des alten Verzeichnisses in den Qtree verschieben.
+
[NOTE]
====
Je mehr Unterverzeichnisse ein zu verschiebendes Verzeichnis enthält, desto länger dauert der Verschiebevorgang.

====
+
[listing]
----
client: mv /n/user1/vol1/olddir/* /n/user1/vol1/dir1
----
. Mit dem  `rmdir` Befehl lässt sich das alte, jetzt leere Verzeichnis löschen.
+
[listing]
----
client: rmdir /n/user1/vol1/olddir
----


.Nachdem Sie fertig sind
Je nachdem, wie Ihr UNIX-Client den  `mv` Befehl implementiert, werden Dateibesitz und Berechtigungen möglicherweise nicht beibehalten. In diesem Fall sollten Dateibesitzer und Berechtigungen auf ihre vorherigen Werte zurückgesetzt werden.

Weitere Informationen zu den in diesem Verfahren beschriebenen Befehlen befinden sich in der link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP-Befehlsreferenz"^].
