---
permalink: volumes/convert-directory-qtree-task.html 
sidebar: sidebar 
keywords: convert, directory, qtree 
summary: Wenn Sie ein Verzeichnis im Stammverzeichnis eines FlexVol Volume haben, das Sie in einen Qtree konvertieren möchten, müssen die in diesem Verzeichnis enthaltenen Daten in einen neuen Qtree mit demselben Namen migriert werden. 
---
= Konvertieren Sie ein Stammverzeichnis in einem ONTAP FlexVol Volume in einen Qtree
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ein Verzeichnis im Stammverzeichnis eines FlexVol Volume haben, das Sie in einen Qtree konvertieren möchten, müssen die in diesem Verzeichnis enthaltenen Daten mithilfe Ihrer Clientanwendung in einen neuen Qtree mit demselben Namen migriert werden.

.Über diese Aufgabe
Die Schritte zur Konvertierung eines Verzeichnisses in einen Qtree hängen vom verwendeten Client ab. Im folgenden Prozess werden die allgemeinen Aufgaben aufgezeigt, die abgeschlossen werden müssen.

.Bevor Sie beginnen
Ein Verzeichnis kann nicht gelöscht werden, wenn es mit einer bestehenden CIFS-Freigabe verknüpft ist.

.Schritte
. Das Verzeichnis, das in einen Qtree umgewandelt werden soll, umbenennen.
. Einen neuen Qtree mit dem ursprünglichen Verzeichnisnamen erstellen.
. Mit der Clientanwendung werden die Inhalte des Verzeichnisses in den neuen Qtree verschoben.
. Das nun leere Verzeichnis löschen.

