---
permalink: volumes/convert-directory-qtree-windows-client-task.html 
sidebar: sidebar 
keywords: convert, directory to a qtree, using, windows client 
summary: Um ein Verzeichnis mithilfe eines Windows-Clients in einen qtree zu konvertieren, benennen Sie das Verzeichnis um, erstellen einen qtree auf dem Speichersystem und verschieben den Inhalt des Verzeichnisses auf den qtree. 
---
= Konvertieren Sie ein Verzeichnis in einen qtree mithilfe eines Windows Clients
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um ein Verzeichnis mithilfe eines Windows-Clients in einen qtree zu konvertieren, benennen Sie das Verzeichnis um, erstellen einen qtree im Storage-System und verschieben den Inhalt des Verzeichnisses in den qtree.

.Über diese Aufgabe
Hierfür müssen Sie den Windows Explorer verwenden. Sie können nicht die Windows-Befehlszeilenschnittstelle oder die DOS-Eingabeaufforderung verwenden.

.Schritte
. Öffnen Sie Windows Explorer.
. Klicken Sie auf die Ordnerdarstellung des Verzeichnisses, das Sie ändern möchten.
+
[NOTE]
====
Das Verzeichnis muss sich im Stammverzeichnis seines enthaltenden Volumes befinden.

====
. Wählen Sie im Menü *Datei* die Option *Umbenennen* aus, um diesem Verzeichnis einen anderen Namen zu geben.
. Verwenden Sie auf dem Storage-System den `volume qtree create` Befehl, um einen neuen qtree mit dem ursprünglichen Namen des Verzeichnisses zu erstellen.
. Öffnen Sie in Windows Explorer den umbenannten Verzeichnisordner, und wählen Sie die darin enthaltenen Dateien aus.
. Ziehen Sie diese Dateien in die Ordnerdarstellung des neuen qtree.
+
[NOTE]
====
Je mehr Unterordner sich im Ordner befinden, in dem Sie sich verschieben, desto länger dauert der Vorgang Verschieben.

====
. Wählen Sie im Menü *Datei* die Option *Löschen* aus, um den umbenannten, jetzt leeren Verzeichnisordner zu löschen.

