---
permalink: volumes/create-flexclone-file-flexclone-lun-task.html 
sidebar: sidebar 
keywords: create, flexclone file, flexclone lun, efficient, clone 
summary: Es können platzsparende und zeitsparende Klone von Dateien und LUNs in FlexVol oder FlexClone Volumes erstellt werden. 
---
= Erstellen Sie eine ONTAP FlexClone Datei oder FlexClone LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können platz- und zeiteffiziente Klone von Dateien und LUNs erstellen, die sich in FlexVol Volumes oder FlexClone Volumes befinden, indem Sie den  `volume file clone create` Befehl verwenden.

.Bevor Sie beginnen
* Die FlexClone Lizenz muss auf dem Cluster installiert sein. Diese Lizenz ist mit link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"] enthalten.
* Wenn mehrere Blockbereiche für das Klonen von Sub-LUNs oder Sub-Dateien verwendet werden, dürfen sich die Blocknummern nicht überschneiden.
* Wenn Sie eine Sub-LUN oder eine Sub-Datei auf Volumes mit aktivierter adaptiver Datenkomprimierung erstellen, dürfen die Blockbereiche nicht falsch ausgerichtet sein.
+
Dies bedeutet, dass die Startblocknummer der Quelle und die Startblocknummer des Ziels entweder beide gerade oder beide ungerade ausgerichtet sein müssen.



.Über diese Aufgabe
Je nach den vom Cluster-Administrator zugewiesenen Berechtigungen kann ein SVM-Administrator FlexClone Dateien und FlexClone LUNs erstellen.

Sie können die Autodelete-Einstellung für FlexClone Dateien und FlexClone LUNs beim Erstellen und Ändern von Klonen festlegen. Standardmäßig ist die Autodelete-Einstellung deaktiviert.

Sie können eine vorhandene FlexClone Datei oder FlexClone LUN beim Erstellen eines Klons überschreiben, indem der  `volume file clone create` Befehl mit dem  `-overwrite-destination` Parameter verwendet wird.

Wenn der Knoten seine maximale Split-Last erreicht, nimmt der Knoten vorübergehend keine Anfragen zum Erstellen von FlexClone Dateien und FlexClone LUNs mehr an und gibt eine  `EBUSY` Fehlermeldung aus. Sobald die Split-Last des Knotens wieder unter den Maximalwert sinkt, nimmt der Knoten wieder Anfragen zum Erstellen von FlexClone Dateien und FlexClone LUNs entgegen. Es empfiehlt sich, mit der erneuten Erstellungsanfrage zu warten, bis der Knoten wieder Kapazität zum Erstellen der Klone hat.

Die FlexClone LUN erbt das Attribut für Speicherplatzreservierungen der übergeordneten LUN. Eine speicherplatzreservierte FlexClone LUN benötigt genauso viel Speicherplatz wie die speicherplatzreservierte übergeordnete LUN. Wenn die FlexClone LUN nicht speicherplatzreserviert ist, muss das Volume über ausreichend Speicherplatz verfügen, um Änderungen am Klon aufzunehmen.

.Schritte
. Wenn Sie eine LUN klonen, sollte überprüft werden, dass die LUN weder gemappt ist noch beschrieben wird.
. Das FlexClone LUN oder die Datei erstellen:
+
`volume file clone create -vserver _vserver_name_ -volume _volume_name_ -source-path _source_path_ -destination-path _destination_path_`

+
Das folgende Beispiel zeigt, wie eine FlexClone Datei file1_clone der übergeordneten Datei file1_source im Volume vol1 erstellt werden kann:

+
[listing]
----
cluster1::> volume file clone create -vserver vs0 -volume vol1 -source-path /file1_source -destination-path /file1_clone
----
+
Weitere Informationen zu  `volume file clone create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-file-clone-create.html["ONTAP-Befehlsreferenz"^].





[[create-flexclone-luns-from-a-snapshot-in-a-volume]]
== Erstellung von FlexClone LUNs aus einem Snapshot in einem Volume

Sie können einen Snapshot in Ihrem Volume verwenden, um FlexClone Kopien Ihrer LUNs zu erstellen. FlexClone Kopien von LUNs sind sowohl lesbar als auch beschreibbar.

.Bevor Sie beginnen
Eine FlexClone Lizenz muss installiert sein. Diese Lizenz ist mit link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"] enthalten.

.Über diese Aufgabe
Die FlexClone LUN erbt das Attribut für Speicherplatzreservierungen der übergeordneten LUN. Eine speicherplatzreservierte FlexClone LUN benötigt genauso viel Speicherplatz wie die speicherplatzreservierte übergeordnete LUN. Wenn die FlexClone LUN nicht speicherplatzreserviert ist, muss das Volume über ausreichend Speicherplatz verfügen, um Änderungen am Klon aufzunehmen.

.Schritte
. Es sollte sichergestellt werden, dass die LUN weder zugeordnet noch beschrieben wird.
. Einen Snapshot des Volumes erstellen, das die LUNs enthält:
+
`volume snapshot create -vserver _vserver_name_ -volume _volume_name_ -snapshot _snapshot_name_`

+
Es ist erforderlich, einen Snapshot (den zugrunde liegenden Snapshot) der LUN zu erstellen, die geklont werden soll.

. Das FlexClone LUN aus dem Snapshot erstellen:
+
`volume file clone create -vserver _vserver_name_ -volume _volume_name_ -source-path _source_path_ -snapshot-name _snapshot_name_ -destination-path _destination_path_`

+
Wenn die FlexClone LUN für die automatische Löschung verfügbar sein soll, schließen Sie  `-autodelete true` ein. Wenn diese FlexClone LUN in einem Volume mit Semi-Thick Provisioning erstellt wird, muss die automatische Löschung für alle FlexClone LUNs aktiviert sein.

. Es sollte überprüft werden, ob die FlexClone LUN korrekt ist:
+
`lun show -vserver _vserver_name_`

+
[listing]
----

Vserver Path                      State    Mapped    Type     Size
------- ----------------------    -------- --------- -------- -------
vs1     /vol/vol1/lun1_clone      online   unmapped windows   47.07MB
vs1     /vol/vol1/lun1_snap_clone online   unmapped windows   47.07MB
----

