---
permalink: volumes/create-flexclone-file-flexclone-lun-task.html 
sidebar: sidebar 
keywords: create, flexclone file, flexclone lun 
summary: Sie können mit dem Befehl zum Erstellen von Dateiklonen von Volumes oder FlexClone Volumes platzsparende und zeitsparende Klone von Dateien und LUNs erstellen, die in FlexVol Volumes oder FlexClone Volumes vorhanden sind. 
---
= Erstellen einer FlexClone Datei oder einer FlexClone LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mithilfe von lassen sich platzsparende und zeitsparende Klone von Dateien und LUNs, die in FlexVol Volumes oder FlexClone Volumes vorhanden sind, erstellen `volume file clone create` Befehl.

.Was Sie benötigen
* Die FlexClone Lizenz muss auf dem Cluster installiert sein.
* Wenn mehrere Blockbereiche für das Klonen unter LUNs oder das Klonen von Sub-Dateien verwendet werden, dürfen sich die Blocknummern nicht überlappen.
* Wenn Sie eine Sub-LUN oder eine Unterdatei auf Volumes mit aktivierter anpassungsfähiger Komprimierung erstellen, dürfen die Blockbereiche nicht falsch ausgerichtet sein.
+
Das bedeutet, dass die Startblocknummer des Quell- und die Startblocknummer des Ziels entweder gerade ausgerichtet oder ungerade ausgerichtet sein müssen.



.Über diese Aufgabe
Je nach den vom Cluster-Administrator zugewiesenen Berechtigungen kann ein SVM-Administrator FlexClone Dateien und FlexClone LUNs erstellen.

Sie können die Autodelete-Einstellung für FlexClone Dateien und FlexClone LUNs beim Erstellen und Ändern von Klonen festlegen. Standardmäßig ist die Autodelete-Einstellung deaktiviert.

Sie können eine vorhandene FlexClone Datei oder ein FlexClone LUN überschreiben, wenn Sie einen Klon mit verwenden `volume file clone create` Befehl mit dem `-overwrite-destination` Parameter.

Wenn der Node die maximale getrennte Last erreicht, stoppt der Node vorübergehend die Annahme von Anfragen zur Erstellung von FlexClone-Dateien und FlexClone-LUNs, und gibt ein aus `EBUSY` Fehlermeldung. Wenn die Split Load des Node unter das Maximum fällt, akzeptiert der Node Anfragen zur erneuten Erstellung von FlexClone Dateien und FlexClone LUNs. Sie sollten warten, bis der Node die Kapazität zum Erstellen der Klone hat, bevor Sie die Erstellungsanforderung erneut versuchen.

.Schritte
. Erstellen Sie eine FlexClone Datei oder ein FlexClone LUN mit `volume file clone create` Befehl.
+
Das folgende Beispiel zeigt, wie Sie eine FlexClone-Datei file1_Clone der übergeordneten Datei file1_source im Volume vol1 erstellen können:

+
[listing]
----
cluster1::> volume file clone create -vserver vs0 -volume vol1 -source-path /file1_source -destination-path /file1_clone
----
+
Weitere Informationen über diese Verwendung dieses Befehls finden Sie in den man-Pages.



.Verwandte Informationen
http://["ONTAP 9-Befehle"^]
