---
permalink: volumes/deduplication-flexclone-files-luns-concept.html 
sidebar: sidebar 
keywords: deduplication, flexclone files, flexclone luns, files, luns, flexclone, efficiency, efficient, blocks, block 
summary: Sie können die Effizienz des physischen Speicherplatzes verbessern, indem Sie eine FlexClone Datei oder FlexClone LUN der übergeordneten Datei und des übergeordneten LUN in einem Volume mit aktivierter Deduplizierung erstellen. 
---
= Deduplizierung mit FlexClone Files und FlexClone LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den physischen Storage-Speicherplatz der Datenblöcke effizient nutzen, indem Sie eine FlexClone Datei oder eine FlexClone LUN der übergeordneten Datei und einer übergeordneten LUN in einem Volume mit aktivierter Deduplizierung erstellen.

Durch die Deduplizierung wird auch der von FlexClone Dateien und LUNs genutzte Block-Sharing-Mechanismus zur Verfügung stehen. Sie können die Platzeinsparungen in einem FlexVol Volume maximieren, indem Sie die Deduplizierung auf dem Volume aktivieren und dann das deduplizierungsfähige Volume klonen.

[NOTE]
====
Bei der Ausführung des `sis undo` Befehls auf einem Volume mit aktivierter Deduplizierung können keine FlexClone Dateien und FlexClone LUNs der übergeordneten Dateien und übergeordneten LUNs in diesem Volume erstellt werden.

====
Erfahren Sie mehr über die in diesem Verfahren beschriebenen Befehle im link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP-Befehlsreferenz"^].
