---
permalink: volumes/deduplication-flexclone-files-luns-concept.html 
sidebar: sidebar 
keywords: deduplication, flexclone files, flexclone luns, files, luns, flexclone, efficiency, efficient, blocks, block 
summary: Sie können die Effizienz des physischen Speicherplatzes verbessern, indem Sie eine FlexClone Datei oder FlexClone LUN der übergeordneten Datei und der übergeordneten LUN in einem deduplizierungsfähigen Volume erstellen. 
---
= ONTAP Deduplizierung mit FlexClone Dateien und FlexClone LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den physischen Speicherplatz der Datenblöcke effizient nutzen, indem Sie eine FlexClone Datei oder FlexClone LUN der übergeordneten Datei und der übergeordneten LUN in einem deduplizierungsfähigen Volume erstellen.

Der von FlexClone Dateien und LUNs verwendete Block-Sharing-Mechanismus wird auch bei der Deduplizierung eingesetzt. Die Speicherplatzersparnis in einem FlexVol volume lässt sich maximieren, wenn die Deduplizierung für das Volume aktiviert und anschließend das deduplizierte Volume geklont wird.

[NOTE]
====
Beim Ausführen des  `sis undo` Befehls auf einem für Deduplizierung aktivierten Volume ist das Erstellen von FlexClone Dateien und FlexClone LUNs der übergeordneten Dateien und übergeordneten LUNs, die sich in diesem Volume befinden, nicht möglich.

====
Weitere Informationen zu den in diesem Verfahren beschriebenen Befehlen befinden sich in der link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP-Befehlsreferenz"^].
