---
permalink: volumes/delete-snapshot-copies-automatic-task.html 
sidebar: sidebar 
keywords: delete, snapshot, copies, automatically, flexclone luns 
summary: Sie können eine Richtlinie zum automatischen Löschen von Snapshot Kopien und FlexClone LUNs definieren und aktivieren. Durch das automatische Löschen von Snapshot-Kopien und FlexClone LUNs können Sie die Speicherauslastung verwalten. 
---
= Automatisches Löschen von Snapshot Kopien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Richtlinie zum automatischen Löschen von Snapshot Kopien und FlexClone LUNs definieren und aktivieren. Durch das automatische Löschen von Snapshot-Kopien und FlexClone LUNs können Sie die Speicherauslastung verwalten.

.Über diese Aufgabe
Snapshot Kopien werden automatisch von Lese- und Schreib-Volumes und FlexClone LUNs aus übergeordneten Volumes mit Lese- und Schreibvorgängen gelöscht. Es ist nicht möglich, das automatische Löschen von Snapshot Kopien aus schreibgeschützten Volumes, z. B. in SnapMirror Ziel-Volumes, einzurichten.

.Schritt
. Definieren und aktivieren Sie eine Richtlinie zum automatischen Löschen von Snapshot Kopien mit `volume snapshot autodelete modify` Befehl.
+
Siehe `volume snapshot autodelete modify` Man Page enthält Informationen zu den Parametern, die Sie mit diesem Befehl verwenden können, um eine Richtlinie zu definieren, die Ihren Anforderungen entspricht.

+
Mit dem folgenden Befehl wird das automatische Löschen von Snapshot-Kopien aktiviert und die Auslöser auf festgelegt `snap_reserve` Für das Volume vol3, das Teil der vs0.example.com Storage Virtual Machine (SVM) ist:

+
[listing]
----
cluster1::> volume snapshot autodelete modify -vserver vs0.example.com
-volume vol3 -enabled true -trigger snap_reserve
----
+
Mit dem folgenden Befehl können Snapshot-Kopien und der FlexClone LUNs, die für das automatische Löschen des vol3 Volumes markiert sind, automatisch gelöscht werden. Dies ist Teil der vs0.example.com Storage Virtual Machine (SVM):

+
[listing]
----
cluster1::> volume snapshot autodelete modify -vserver vs0.example.com
-volume vol3 -enabled true -trigger volume -commitment try -delete-order
oldest_first -destroy-list lun_clone,file_clone
----
+
[NOTE]
====
Snapshot Kopien auf Aggregatebene funktionieren unterschiedlich als Snapshot Kopien auf Volume-Ebene und werden automatisch von ONTAP gemanagt. Die Option zum Löschen von Aggregat-Snapshot-Kopien ist immer aktiviert und hilft beim Managen der Speicherauslastung.

Wenn der Triggerparameter auf eingestellt ist `snap_reserve` Für ein Aggregat werden die Snapshot Kopien so lange aufbewahrt, bis der reservierte Speicherplatz den Schwellenwert überschreitet. Daher, auch wenn der Triggerparameter nicht auf festgelegt ist `snap_reserve`, Der von der Snapshot Kopie im Befehl genutzte Speicherplatz wird als aufgeführt `0` Da diese Snapshot Kopien automatisch gelöscht werden. Außerdem wird der von Snapshot Kopien in einem Aggregat verwendete Speicherplatz als frei betrachtet und im verfügbaren Parameter des Befehls enthalten.

====

