---
permalink: volumes/determine-space-usage-volume-aggregate-concept.html 
sidebar: sidebar 
keywords: determine, space usage, volume, aggregate 
summary: 'Wenn Sie eine Funktion in ONTAP aktivieren, verbraucht sie möglicherweise Speicherplatz, der Ihnen nicht bekannt ist oder mehr als erwartet entspricht. ONTAP hilft Ihnen zu ermitteln, wie Speicherplatz verbraucht wird, indem Sie drei Perspektiven zur Ansicht von Raum zur Verfügung stellen: Das Volume, der Platzbedarf eines Volumes innerhalb des Aggregats und das Aggregat.' 
---
= Bestimmen Sie die Speicherplatznutzung in einem Volume oder Aggregat
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie eine Funktion in ONTAP aktivieren, verbraucht sie möglicherweise Speicherplatz, der Ihnen nicht bekannt ist oder mehr als erwartet entspricht. ONTAP hilft Ihnen bei der Ermittlung des verbrauchten Speicherplatzes, indem es drei Perspektiven bietet, von denen aus Speicherplatz angezeigt werden kann: Das Volume, der Platzbedarf eines Volumes im Aggregat und das Aggregat.

Auf einem Volume kann aufgrund des Speicherplatzverbrauchs oder des unzureichenden Speicherplatzes im Volume, Aggregat oder einer Kombination aus beidem nicht genügend Platz vorhanden sein. Indem Sie eine funktionsorientierte Aufschlüsselung der Raumnutzung aus verschiedenen Perspektiven sehen, können Sie einschätzen, welche Funktionen Sie anpassen oder deaktivieren möchten, oder andere Maßnahmen ergreifen (z. B. Erhöhung der Größe des Aggregats oder der Volumes).

Sie können Details zur Raumnutzung aus einer der folgenden Perspektiven anzeigen:

* Der Speicherplatzbedarf des Volumes
+
In dieser Perspektive werden Details zur Speicherplatznutzung innerhalb des Volumes angezeigt, einschließlich der Verwendung von Snapshot-Kopien.

+
Sie sehen die Speicherplatznutzung eines Volumes mithilfe von `volume show-space` Befehl.

* Der Platzbedarf des Volumes im Aggregat
+
Diese Perspektive bietet Details zur Menge an Platz, die jedes Volume im enthaltenen Aggregat verwendet, einschließlich der Metadaten des Volume.

+
Mit dem sehen Sie den Platzbedarf eines Volumes mit dem Aggregat `volume show-footprint` Befehl.

* Der Speicherplatznutzung des Aggregats
+
Diese Perspektive umfasst die Gesamtmenge des Volume-Platzbedarfs aller Volumes im Aggregat, den für aggregierte Snapshot Kopien reservierten Speicherplatz und andere Aggregat-Metadaten.

+
WAFL reserviert 10 % des gesamten Speicherplatzes für Metadaten auf Aggregatebene und für eine höhere Performance. Der Platz, der zur Erhaltung der Volumes im Aggregat verwendet wird, stammt aus der WAFL Reserve und kann nicht geändert werden.

+
Ab ONTAP 9.12.1 und neueren FAS Versionen wird die WAFL Reserve für Aggregate von mehr als 30TB von 10 % auf 5 % reduziert, wodurch der nutzbare Speicherplatz im Aggregat erhöht wird. AFF

+
Sie können die Speicherplatznutzung des Aggregats mithilfe von sehen `storage aggregate show-space` Befehl.



Bestimmte Funktionen wie Tape-Backup und -Deduplizierung nutzen Speicherplatz für Metadaten sowohl vom Volume als auch direkt vom Aggregat. Diese Funktionen zeigen unterschiedliche Platzanforderungen zwischen dem Volume und der Volume-Stellfläche.

.Verwandte Informationen
link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Space_Usage["Wissensbasierter Artikel: Platznutzung"]

link:https://www.netapp.com/blog/free-up-storage-capacity-upgrade-ontap/["Setzen Sie beim Upgrade auf ONTAP 9.12.1 auf bis zu 5 % Storage-Kapazität frei"]
