---
permalink: volumes/determine-space-used-flexclone-task.html 
sidebar: sidebar 
keywords: determine, space, used by a flexclone volume 
summary: Sie können den von einem FlexClone Volume genutzten Speicherplatz basierend auf der nominalen Größe und der Menge an Speicherplatz, die gemeinsam mit dem übergeordneten FlexVol Volume genutzt wird, bestimmen. Wird ein FlexClone Volume erstellt, so werden alle zugehörigen Daten gemeinsam mit dem übergeordneten Volume genutzt. Daher, obwohl die nominale Größe des FlexVol-Volumes ist die gleiche wie seine Eltern-Größe, es braucht sehr wenig freien Speicherplatz aus dem Aggregat. 
---
= Bestimmen Sie den von einem FlexClone Volume genutzten Speicherplatz
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den von einem FlexClone Volume genutzten Speicherplatz basierend auf der nominalen Größe und der Menge an Speicherplatz, die gemeinsam mit dem übergeordneten FlexVol Volume genutzt wird, bestimmen. Wird ein FlexClone Volume erstellt, so werden alle zugehörigen Daten gemeinsam mit dem übergeordneten Volume genutzt. Obwohl die nominale Größe des FlexVol-Volumes von der Größe des übergeordneten Volume identisch ist, verbraucht es sehr wenig freien Speicherplatz aus dem Aggregat.

Der von einem neu erstellten FlexClone Volume verwendete freie Speicherplatz liegt bei etwa 0.5 Prozent der Nenngröße. Dieser Speicherplatz wird zur Speicherung der Metadaten des FlexClone Volume genutzt.

Neue Daten, die auf das übergeordnete oder das FlexClone Volume geschrieben werden, werden nicht zwischen den Volumes gemeinsam genutzt. Die Erhöhung der Menge an neuen Daten, die auf das FlexClone Volume geschrieben werden, führt zu einer Erhöhung des Speicherplatzes, den das FlexClone Volume vom zugehörigen Container-Aggregat benötigt.

.Schritt
. Ermitteln Sie den tatsächlich genutzten physischen Speicherplatz, der vom FlexClone Volume mithilfe des genutzt wird `volume show` Befehl.
+
Das folgende Beispiel zeigt den insgesamt genutzten physischen Speicherplatz des FlexClone Volume:

+
[listing]
----

cluster1::> volume show -vserver vs01 -volume clone_vol1 -fields size,used,available,
percent-used,physical-used,physical-used-percent
vserver    volume     size  available  used   percent-used   physical-used     physical-used-percent
-------   ----------  ----  ---------  -----  ------------    -------------   ---------------------
vs01     clone_vol1   20MB   18.45MB   564KB       7%             196KB               1%
----

