---
permalink: volumes/enable-data-compression-volume-task.html 
sidebar: sidebar 
keywords: enable, data compression, FlexVol, space, volume, volume efficiency modify 
summary: 'Die Datenkomprimierung kann aktiviert und ein Komprimierungstyp auf einem FlexVol Volume zugewiesen werden, um Speicherplatz durch den  `volume efficiency modify` Befehl einzusparen.' 
---
= Aktivieren Sie Datenkomprimierung auf einem ONTAP Volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Datenkomprimierung kann auf einem FlexVol volume aktiviert werden, um Speicherplatz einzusparen, indem der  `volume efficiency modify` Befehl verwendet wird. Es kann auch ein Komprimierungstyp für das Volume zugewiesen werden, wenn nicht der Standard-Komprimierungstyp gewünscht ist. Weitere Informationen zu  `volume efficiency modify` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-modify.html["ONTAP-Befehlsreferenz"^].

.Bevor Sie beginnen
Die Deduplizierung muss auf dem Volume aktiviert sein.

[NOTE]
====
* Die Deduplizierung muss lediglich aktiviert sein und muss nicht auf dem Volume ausgeführt werden.
* Der Komprimierungsscanner muss verwendet werden, um die vorhandenen Daten auf den in AFF Plattformen vorhandenen Volumes zu komprimieren.


====
link:enable-deduplication-volume-task.html["Aktivierung der Deduplizierung auf einem Volume"]

.Über diese Aufgabe
* In HDD Aggregaten und Flash Pool Aggregaten kann sowohl die Inline- als auch die Nachbearbeitungskomprimierung oder nur die Nachbearbeitungskomprimierung auf einem Volume aktiviert werden.
+
Wenn Sie beides aktivieren, muss die Nachbearbeitungskomprimierung auf dem Volume aktiviert werden, bevor die Inline-Komprimierung aktiviert wird.

* Auf AFF Plattformen wird nur die Inline-Komprimierung unterstützt.
+
Bevor die Inline-Komprimierung aktiviert wird, muss die Nachbearbeitungskomprimierung für das Volume aktiviert werden. Da die Nachbearbeitungskomprimierung auf AFF Plattformen jedoch nicht unterstützt wird, findet auf diesen Volumes keine Nachbearbeitungskomprimierung statt und es wird eine EMS-Meldung generiert, die darüber informiert, dass die Nachbearbeitungskomprimierung übersprungen wurde.

* Die temperaturabhängige Speichereffizienz wurde in ONTAP 9.8 eingeführt. Mit dieser Funktion wird die Speichereffizienz je nachdem angewendet, ob die Daten als „hot“ oder „cold“ eingestuft werden. Für kalte Daten werden größere Datenblöcke komprimiert, und für heiße Daten, die häufiger überschrieben werden, werden kleinere Datenblöcke komprimiert, wodurch der Prozess effizienter wird. Die temperaturabhängige Speichereffizienz ist auf neu erstellten Thin-Provisioned AFF Volumes automatisch aktiviert.
* Der Komprimierungstyp wird automatisch anhand der Plattform des Aggregats zugewiesen:
+
[cols="2*"]
|===
| Plattform/Aggregate | Kompressionsart 


 a| 
AFF
 a| 
Adaptive Kompression



 a| 
Flash Pool Aggregate
 a| 
Adaptive Kompression



 a| 
HDD Aggregate
 a| 
Sekundäre Komprimierung

|===


.Auswahlmöglichkeiten
* Mit dem  `volume efficiency modify`Befehl wird die Datenkomprimierung mit dem Standardkomprimierungstyp aktiviert.
+
Der folgende Befehl aktiviert die Nachbearbeitungskomprimierung für das Volume VolA von SVM vs1:

+
`volume efficiency modify -vserver vs1 -volume VolA -compression true`

+
Der folgende Befehl aktiviert sowohl die Nachbearbeitungs- als auch die Inline-Datenkomprimierung für das Volume VolA von SVM vs1:

+
`volume efficiency modify -vserver vs1 -volume VolA -compression true -inline-compression true`

* Der  `volume efficiency modify` Befehl auf der Ebene mit erweiterten Berechtigungen ermöglicht die Aktivierung der Datenkomprimierung mit einem bestimmten Komprimierungstyp.
+
.. Mit dem  `set -privilege advanced` Befehl lässt sich die Berechtigungsstufe auf „Erweitert“ ändern.
.. Mit dem  `volume efficiency modify` Befehl lässt sich einem Volume ein Komprimierungstyp zuweisen.
+
Der folgende Befehl aktiviert die Nachbearbeitungskomprimierung und weist dem Volume VolA von SVM vs1 den adaptiven Komprimierungstyp zu:

+
`volume efficiency modify -vserver vs1 -volume VolA -compression true -compression-type adaptive`

+
Der folgende Befehl aktiviert sowohl die Nachbearbeitungs- als auch die Inline-Komprimierung und weist dem Volume VolA von SVM vs1 den adaptiven Komprimierungstyp zu:

+
`volume efficiency modify -vserver vs1 -volume VolA -compression true -compression-type adaptive -inline-compression true`

.. Mit dem  `set -privilege admin`Befehl lässt sich die Berechtigungsstufe auf Administrator ändern.



