---
permalink: volumes/enable-inline-data-compaction-fas-systems-task.html 
sidebar: sidebar 
keywords: enable, inline, data compaction, fas systems, hdd aggregate, volume efficiency 
summary: 'Aktivieren Sie die Inline-Data-Compaction auf FAS Systemen mit Flash Pool (hybride) Aggregaten oder HDD-Aggregaten auf Volume- oder Aggregatebene.' 
---
= Inline-Data-Compaction für FAS Systeme aktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit dem `volume efficiency` Cluster Shell-Befehl können Sie die Inline-Data-Compaction in FAS Systemen mit Flash Pool (hybriden) Aggregaten oder HDD-Aggregaten auf Volume- oder Aggregatebene aktivieren. Für FAS Systeme ist die Data-Compaction standardmäßig deaktiviert.

.Über diese Aufgabe
Wenn Sie die Data-Compaction auf Aggregatebene aktivieren, wird die Data-Compaction auf jedem neuen Volume aktiviert, das mit der Speicherplatzgarantie für Volumes erstellt wird `none` Im Aggregat an. Wenn die Data-Compaction auf einem Volume auf einem HDD-Aggregat aktiviert wird, werden zusätzliche CPU-Ressourcen benötigt.

.Schritte
. Ändern Sie die erweiterte Berechtigungsebene:
+
[source, cli]
----
set -privilege advanced
----
. Prüfen Sie den Data-Compaction-Status der Volumes und Aggregate für den gewünschten Node:
+
[source, cli]
----
volume efficiency show -volume <volume_name>
----
. Data-Compaction auf Volume aktivieren:
+
[source, cli]
----
volume efficiency modify -volume <volume_name> -data-compaction true
----
+
[NOTE]
====
Wenn für die Data-Compaction entweder ein Aggregat oder ein Volume festgelegt `false` ist, schlägt die Data-Compaction fehl. Durch die Aktivierung der Data-Compaction werden vorhandene Daten nicht komprimiert, sondern es werden nur neue Schreibzugriffe auf das System komprimiert. Der `volume efficiency start` Befehl enthält weitere Informationen zum Kompakt vorhandener Daten (ab ONTAP 9.1). Weitere Informationen finden Sie im https://docs.netapp.com/us-en/ontap-cli["Befehlsreferenz für ONTAP"^].

====
. Statistiken zur Data-Compaction:
+
[source, cli]
----
volume efficiency show -volume <volume_name>
----

