---
permalink: volumes/enable-large-vol-file-support-task.html 
sidebar: sidebar 
keywords: create, modify, volume, large file, large volume 
summary: Sie können die Unterstützung für große Volumes und Dateien aktivieren, wenn Sie ein neues Volume erstellen oder ein vorhandenes Volume ändern. 
---
= Unterstützung für große Volumes und große Dateien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.12.1 P2 können Sie ein neues Volume erstellen oder ein vorhandenes Volume ändern, um eine maximale Volume-Größe von 300 TB und eine maximale Datei (LUN)-Größe von 128 TB zu unterstützen.

.Bevor Sie beginnen
* ONTAP 9.12.1 P2 oder höher ist auf dem Cluster installiert.
* Sie sind Cluster- oder SVM-Administrator.




== Erstellen Sie ein neues Volume

.Schritt
. Erstellen Sie ein Volume mit aktivierter Unterstützung für große Volumes und Dateien:
+
`volume create -vserver _svm_name_ -volume _volume_name_ -aggregate _aggregate_name_ -is-large-size-enabled true`



.Beispiel
Im folgenden Beispiel wird ein neues Volume mit aktivierter Unterstützung für große Volumes und Dateigröße erstellt.

[listing]
----
volume create -vserver vs1 -volume big_vol1 -aggregate aggr1 -is-large-size-enabled true
----


== Ändern Sie ein vorhandenes Volume

. Ändern Sie ein Volume, um Unterstützung für große Volumes und Dateien zu aktivieren:
+
`volume modify -vserver _svm_name_ -volume _volume_name_ -aggregate _aggregate_name_ -is-large-size-enabled true`



.Beispiel
Im folgenden Beispiel wird ein vorhandenes Volume geändert, um große Volumes und große Dateien zu unterstützen.

[listing]
----
volume modify -vserver vs2 -volume data_vol -aggregate aggr1 -is-large-size-enabled true
----
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap/volumes/create-volume-task.html["Erstellen eines Volumes"]
* link:https://docs.netapp.com/us-en/ontap-cli-9131/["Befehlsreferenz"]

