---
permalink: volumes/enable-disable-background-deduplication-aff-task.html 
sidebar: sidebar 
keywords: manage, aggregate-level, background, deduplication, aff systems 
summary: Die Deduplizierung auf Aggregatebene für Volumes kann aktiviert oder deaktiviert werden, oder es lässt sich feststellen, ob die Funktion aktiviert ist. 
---
= Verwaltung der Hintergrunddeduplizierung auf Aggregatebene auf AFF Systemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Deduplizierung auf Aggregatebene entfernt doppelte Blöcke über Volumes hinweg, die zum selben Aggregat gehören. Ab ONTAP 9.3 kann die Deduplizierung auf Aggregatebene im Hintergrund auf AFF Systemen durchgeführt werden. Die Funktion ist standardmäßig für alle neu erstellten Volumes und alle aktualisierten Volumes aktiviert, bei denen die Hintergrunddeduplizierung für Volumes eingeschaltet ist.

.Über diese Aufgabe
Der Vorgang wird automatisch ausgelöst, sobald ein ausreichend großer Prozentsatz des Änderungsprotokolls gefüllt ist. Es ist kein Zeitplan oder keine Richtlinie mit dem Vorgang verknüpft.

Ab ONTAP 9.4 können AFF Benutzer auch den Deduplizierungsscanner auf Aggregatebene ausführen, um Duplikate vorhandener Daten über Volumes im Aggregat hinweg zu entfernen. Der  `storage aggregate efficiency cross-volume-dedupe start` Befehl kann zusammen mit der  `-scan-old-data=true` Option zum Starten des Scanners verwendet werden:

[listing]
----
cluster-1::> storage aggregate efficiency cross-volume-dedupe start -aggregate aggr1 -scan-old-data true
----
Die Deduplizierung kann zeitaufwändig sein. Es kann sinnvoll sein, den Vorgang außerhalb der Stoßzeiten auszuführen.

[NOTE]
====
Die Hintergrunddeduplizierung auf Aggregatebene wird manchmal auch als volume-übergreifende Hintergrunddeduplizierung bezeichnet.

====
Weitere Informationen zu  `storage aggregate efficiency cross-volume-dedupe start` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-efficiency-cross-volume-dedupe-start.html["ONTAP-Befehlsreferenz"^].

.Schritte
. Verwaltung der Hintergrunddeduplizierung auf Aggregatebene auf AFF Systemen:
+
[cols="2*"]
|===
| Wenn Sie möchten... | Verwenden Sie diesen Befehl 


 a| 
Hintergrunddeduplizierung auf Aggregatebene aktivieren
 a| 
`volume efficiency modify -vserver <vserver_name\> -volume <vol_name\> -cross-volume-background-dedupe true`



 a| 
Hintergrunddeduplizierung auf Aggregatebene deaktivieren
 a| 
`volume efficiency modify -vserver <vserver_name\> -volume <vol_name\> -cross-volume-background-dedupe false`



 a| 
Status der Hintergrunddeduplizierung auf Aggregatebene anzeigen
 a| 
`aggregate efficiency cross-volume-dedupe show`

|===


Weitere Informationen zu den in diesem Verfahren beschriebenen Befehlen befinden sich in der link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP-Befehlsreferenz"^].

.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-modify.html["Volumeneffizienz ändern"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-efficiency-cross-volume-dedupe-show.html["aggregate efficiency cross-volume-dedupe show"^]

