---
permalink: volumes/enable-storage-efficiency-visualization-concept.html 
sidebar: sidebar 
keywords: storage, efficiency, visualization, storage aggregate 
summary: Zeigen Sie verschiedene Ansichten der Storage-Effizienz aller Aggregate in Ihrem System an. 
---
= Visualisierung der Storage-Effizienz
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verwenden Sie den `storage aggregate show-efficiency` Befehl, um Informationen zur Storage-Effizienz aller Aggregate in Ihrem System anzuzeigen.

Der `storage aggregate show-efficiency` Befehl hat drei verschiedene Ansichten, die durch Übergeben von Befehlsoptionen aufgerufen werden können.



== Standardansicht

In der Standardansicht wird das Gesamtverhältnis für jedes Aggregat angezeigt.

`cluster1::> storage aggregate show-efficiency`



== Detailansicht

Rufen Sie die detaillierte Ansicht mit der `-details` Befehlsoption auf. In dieser Ansicht wird Folgendes angezeigt:

* Gesamteffizienz-Verhältnis für jedes Aggregat.
* Gesamtverhältnis ohne Snapshots.
* Verhältnis-Teilung für die folgenden Effizienztechnologien: Volume-Deduplizierung, Volume-Komprimierung, Snapshots, Klone, Data-Compaction und Aggregat-Inline-Deduplizierung


`cluster1::> storage aggregate show-efficiency -details`



== Erweiterte Ansicht

Die erweiterte Ansicht ähnelt der Detailansicht und zeigt sowohl die logischen als auch die physisch verwendeten Details an.

Sie müssen diesen Befehl auf der erweiterten Berechtigungsebene ausführen. Mit dem `set -privilege advanced` Befehl wechseln Sie zu den erweiterten Berechtigungen.

Die Eingabeaufforderung ändert sich in `cluster::*>`.

`cluster1::> set -privilege advanced`

Rufen Sie die erweiterte Ansicht mit der `-advanced` Befehlsoption auf.

`cluster1::*> storage aggregate show-efficiency -advanced`

Um die Verhältnisse für ein einzelnes Aggregat einzeln anzuzeigen, rufen Sie den `-aggregate _aggregate_name_` Befehl auf. Dieser Befehl kann auf der Administratorebene sowie auf der erweiterten Berechtigungsebene ausgeführt werden.

`cluster1::> storage aggregate show-efficiency -aggregate aggr1`
