---
permalink: volumes/enable-temperature-sensitive-efficiency-concept.html 
sidebar: sidebar 
keywords: enable, temperature, sensitive, storage, efficiency, sequential packing 
summary: Temperaturempfindliche Storage-Effizienz wird seit ONTAP 9 8 automatisch auf einigen AFF Volumes oder manuell auf vorhandenen Volumes aktiviert. 
---
= Temperaturempfindliche Lagereffizienz im Überblick
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP bietet temperaturempfindliche Vorteile bei der Storage-Effizienz, indem Sie ermitteln, wie oft auf die Daten auf Ihrem Volume zugegriffen wird, und diese Frequenz dem Grad der auf diese Daten angewandten Komprimierung zuordnen. Bei selten abgerufenen „kalten“ Daten werden größere Datenblöcke komprimiert. Bei häufig abgerufenen Daten, die häufiger überschrieben werden, werden kleinere Datenblöcke komprimiert, was den Prozess effizienter macht.

Temperaturempfindliche Storage-Effizienz (TSSE) wird seit ONTAP 9.8 eingeführt und wird automatisch auf neu erstellten AFF Volumes mit Thin Provisioning aktiviert. Sie können temperaturabhängige Storage-Effizienz für vorhandene AFF Volumes und auf über Thin Provisioning bereitgestellten nicht-All Flash FAS Volumes aktivieren.


NOTE: Temperaturempfindliche Storage-Effizienz wird auf Plattformen AFF A70, AFF A90 und AFF A1K nicht angewendet. Die Komprimierung basiert nicht auf „heißen“ oder „kalten“ Daten auf diesen Plattformen, sodass das Warten auf selten genutzte Daten beginnt.

.Einführung von „Standard“ und „effizienten“ Modi
Ab ONTAP 9.10.1 sind die Storage-Effizienzmodi _default_ und _Efficient_ auf Volume-Ebene nur für AFF Systeme verfügbar. Die beiden Modi bieten die Wahl zwischen Dateikomprimierung (Standard), dem Standardmodus beim Erstellen neuer AFF-Volumes, oder temperaturempfindlicher Storage-Effizienz (effizient), bei der die automatisch anpassungsfähige Komprimierung verwendet wird, um mehr Komprimierungseinsparungen für Daten mit selten abgerufenen („kalten“) Daten zu erzielen.

Mit ONTAP 9.10.1, link:../volumes/set-efficiency-mode-task.html["Temperaturempfindliche Speichereffizienz muss explizit festgelegt werden"] um die automatisch adaptive Komprimierung zu aktivieren. Weitere Storage-Effizienzfunktionen wie Data-Compaction, Zeitplan für die automatische Deduplizierung, Inline-Deduplizierung, Volume-übergreifende Inline-Deduplizierung und Volume-übergreifende Hintergrund-Deduplizierung sind bei AFF Plattformen standardmäßig sowohl im standardmäßigen als auch im effizienten Modus aktiviert.

Beide Storage-Effizienzmodi (Standard und effizient) werden auf FabricPool-fähigen Aggregaten und allen Tiering-Richtlinientypen unterstützt.

.Temperaturempfindliche Storage-Effizienz auf Plattformen der C-Serie aktiviert
Temperaturempfindliche Storage-Effizienz ist auf Plattformen der AFF C-Serie und bei der Migration von Volumes von einer nicht-TSSE-Plattform zu einer TSSE-fähigen C-Series Plattform per Volume-Verschiebung oder SnapMirror standardmäßig aktiviert; dabei sind die folgenden Versionen auf dem Ziel installiert:

* ONTAP 9.12.1P4 und höher
* ONTAP 9.13.1 und höher


Weitere Informationen finden Sie unter link:../volumes/storage-efficiency-behavior-snapmirror-reference.html["Storage-Effizienzverhalten bei Volume-Verschiebung und SnapMirror Operationen"].

Bei vorhandenen Volumes wird temperaturempfindliche Storage-Effizienz nicht automatisch aktiviert, Sie können jedoch manuell in den effizienten Modus wechseln.link:../volumes/change-efficiency-mode-task.html["Ändern Sie den Storage-Effizienz-Modus"]


NOTE: Wenn Sie den Storage-Effizienzmodus zu „effizient“ ändern, können Sie ihn nicht mehr zurückändern.

.Höhere Storage-Effizienz durch sequenzielle Verpackung zusammenhängender physischer Blöcke
Ab ONTAP 9.13.1 ist bei temperaturempfindlicher Storage-Effizienz eine sequenzielle Verpackung aus zusammenhängenden physischen Blöcken erforderlich, um die Storage-Effizienz weiter zu verbessern. Bei einem Upgrade von Systemen auf ONTAP 9.13.1 haben Volumes mit aktivierter temperaturabhängiger Storage-Effizienz automatisch sequenzielle Packungen aktiviert. Nach dem sequenziellen Packen aktiviert ist, müssen Sie link:../volumes/run-efficiency-operations-manual-task.html["Vorhandene Daten manuell neu packen"].



== Upgrade-Überlegungen

Wenn ein Upgrade auf ONTAP 9.10.1 und höher durchgeführt wird, wird vorhandenen Volumes basierend auf dem aktuell auf den Volumes aktivierten Komprimierungstyp ein Storage-Effizienzmodus zugewiesen. Während eines Upgrades werden Volumes mit aktivierter Komprimierung dem Standardmodus zugewiesen, und Volumes mit aktiviertem temperatursensiblen Storage-Effizienz werden dem Effizienzmodus zugewiesen. Wenn die Komprimierung nicht aktiviert ist, bleibt der Storage-Effizienz-Modus leer.
