---
permalink: volumes/enable-temperature-sensitive-efficiency-concept.html 
sidebar: sidebar 
keywords: enable, temperature, sensitive, storage, efficiency, sequential packing 
summary: Temperaturempfindliche Storage-Effizienz wird seit ONTAP 9 8 automatisch auf einigen AFF Volumes oder manuell auf vorhandenen Volumes aktiviert. 
---
= Erfahren Sie mehr über die Effizienz temperaturempfindlicher Speicherlösungen von ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP bietet Vorteile hinsichtlich der temperaturabhängigen Speichereffizienz (TSSE), indem es ermittelt, wie oft auf die Daten Ihres Volumes zugegriffen wird, und diese Häufigkeit dem auf diese Daten angewendeten Komprimierungsgrad zuordnet.  Bei kalten Daten, auf die selten zugegriffen wird, werden größere Datenblöcke komprimiert, und bei heißen Daten, auf die häufig zugegriffen wird und die häufiger überschrieben werden, werden kleinere Datenblöcke komprimiert, wodurch der Prozess effizienter wird.

TSSE wird in ONTAP 9.8 eingeführt und auf neu erstellten Thin Provisioning AFF -Volumes automatisch aktiviert.  Sie können temperaturempfindliche Speichereffizienz auf vorhandenen AFF Volumes und auf Thin Provisioning-Volumes ohne AFF -DP aktivieren.

Die temperaturabhängige Speichereffizienz wird auf den folgenden Plattformen nicht angewendet:

[cols="2"]
|===
| Plattform | ONTAP-Version 


 a| 
* AFF A1K
* AFF A90
* AFF A70
* FAS90
* FAS70

| 9.15.1 oder höher 


 a| 
* AFF C80
* AFF C60
* AFF C30
* AFF A50
* AFF A30

| 9.16.1 oder höher 
|===
Diese Plattformen nutzenlink:../concepts/builtin-storage-efficiency-concept.html["CPU- oder dedizierte Speichereffizienz des Prozessors"] .  Die Komprimierung erfolgt entweder über die Haupt-CPU oder einen dedizierten Offload-Prozessor und basiert nicht auf heißen oder kalten Daten.


NOTE: Mit der Zeit kann der in Ihrem Volume verwendete Speicherplatz bei TSSE stärker ausgeprägt sein als bei der adaptiven 8K-Komprimierung.  Dieses Verhalten ist aufgrund der Architekturunterschiede zwischen TSSE und adaptiver 8K-Komprimierung zu erwarten.

.Einführung von „Standard“ und „effizienten“ Modi
Ab ONTAP 9.10.1 sind die Storage-Effizienzmodi _default_ und _Efficient_ auf Volume-Ebene nur für AFF Systeme verfügbar. Die beiden Modi bieten die Wahl zwischen Dateikomprimierung (Standard), dem Standardmodus beim Erstellen neuer AFF-Volumes, oder temperaturempfindlicher Storage-Effizienz (effizient), bei der die automatisch anpassungsfähige Komprimierung verwendet wird, um mehr Komprimierungseinsparungen für Daten mit selten abgerufenen („kalten“) Daten zu erzielen.

Wenn ein Upgrade auf ONTAP 9.10.1 und höher durchgeführt wird, wird vorhandenen Volumes basierend auf dem aktuell auf den Volumes aktivierten Komprimierungstyp ein Storage-Effizienzmodus zugewiesen. Während eines Upgrades werden Volumes mit aktivierter Komprimierung dem Standardmodus zugewiesen, und Volumes mit aktiviertem temperatursensiblen Storage-Effizienz werden dem Effizienzmodus zugewiesen. Wenn die Komprimierung nicht aktiviert ist, bleibt der Storage-Effizienz-Modus leer.

Mit ONTAP 9.10.1, link:../volumes/set-efficiency-mode-task.html["Temperaturempfindliche Speichereffizienz muss explizit festgelegt werden"] um die automatisch adaptive Komprimierung zu aktivieren. Weitere Storage-Effizienzfunktionen wie Data-Compaction, Zeitplan für die automatische Deduplizierung, Inline-Deduplizierung, Volume-übergreifende Inline-Deduplizierung und Volume-übergreifende Hintergrund-Deduplizierung sind bei AFF Plattformen standardmäßig sowohl im standardmäßigen als auch im effizienten Modus aktiviert.

Beide Storage-Effizienzmodi (Standard und effizient) werden auf FabricPool-fähigen Aggregaten und allen Tiering-Richtlinientypen unterstützt.

.Temperaturempfindliche Storage-Effizienz auf Plattformen der C-Serie aktiviert
Temperaturempfindliche Storage-Effizienz ist auf Plattformen der AFF C-Serie und bei der Migration von Volumes von einer nicht-TSSE-Plattform zu einer TSSE-fähigen C-Series Plattform per Volume-Verschiebung oder SnapMirror standardmäßig aktiviert; dabei sind die folgenden Versionen auf dem Ziel installiert:

* ONTAP 9.12.1P4 und höher
* ONTAP 9.13.1 und höher


Weitere Informationen finden Sie unter link:../volumes/storage-efficiency-behavior-snapmirror-reference.html["Storage-Effizienzverhalten bei Volume-Verschiebung und SnapMirror Operationen"].

Bei vorhandenen Volumes wird temperaturempfindliche Storage-Effizienz nicht automatisch aktiviert, Sie können jedoch manuell in den effizienten Modus wechseln.link:../volumes/change-efficiency-mode-task.html["Ändern Sie den Storage-Effizienz-Modus"]


NOTE: Wenn Sie den Storage-Effizienzmodus zu „effizient“ ändern, können Sie ihn nicht mehr zurückändern.

.Höhere Storage-Effizienz durch sequenzielle Verpackung zusammenhängender physischer Blöcke
Ab ONTAP 9.13.1 ist bei temperaturempfindlicher Storage-Effizienz eine sequenzielle Verpackung aus zusammenhängenden physischen Blöcken erforderlich, um die Storage-Effizienz weiter zu verbessern. Bei einem Upgrade von Systemen auf ONTAP 9.13.1 haben Volumes mit aktivierter temperaturabhängiger Storage-Effizienz automatisch sequenzielle Packungen aktiviert. Nach dem sequenziellen Packen aktiviert ist, müssen Sie link:../volumes/run-efficiency-operations-manual-task.html["Vorhandene Daten manuell neu packen"].
