---
permalink: volumes/enable-logical-space-reporting-enforcement-task.html 
sidebar: sidebar 
keywords: enable, logical, space, reporting, enforcement 
summary: Ab ONTAP 9.4 ist die Meldung logischer Speicherbereiche zu aktivieren. Ab 9.5 ist entweder die Durchsetzung logischer Speicherbereiche oder sowohl die Meldung als auch die Durchsetzung zu aktivieren. 
---
= Aktivieren Sie die Meldung und Durchsetzung des logischen Speicherplatzes in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.4 kann die Berichterstattung über logischen Speicherplatz aktiviert werden. Ab 9.5 kann die Durchsetzung des logischen Speicherplatzes oder sowohl Berichterstattung als auch Durchsetzung zusammen aktiviert werden.

.Über diese Aufgabe
Zusätzlich zur Aktivierung der logischen Speicherplatzberichterstattung und -durchsetzung auf Ebene einzelner Volumes können diese Funktionen auch auf SVM-Ebene für jedes Volume aktiviert werden, das diese Funktionalität unterstützt. Wenn die Funktionen für den logischen Speicherplatz für die gesamte SVM aktiviert sind, können sie auch für einzelne Volumes deaktiviert werden.

Ab ONTAP 9.8 wird, wenn die logische Speicherplatzberichterstattung auf einem SnapMirror Quellvolume aktiviert ist, diese nach der Übertragung automatisch auch auf dem Zielvolume aktiviert.

Ab ONTAP 9.13.1 wird, wenn die Durchsetzungsoption auf einem SnapMirror Quellvolume aktiviert ist, vom Ziel der logische Speicherplatzverbrauch gemeldet und die Durchsetzung berücksichtigt, was eine bessere Kapazitätsplanung ermöglicht.


NOTE: Wenn eine ONTAP-Version vor ONTAP 9.13.1 verwendet wird, ist zu beachten, dass die Durchsetzungseinstellung zwar auf das SnapMirror Zielvolume übertragen wird, das Zielvolume die Durchsetzung jedoch nicht unterstützt. Daher wird vom Zielvolume die logische Speicherplatzbelegung gemeldet, die Durchsetzung jedoch nicht berücksichtigt.

Weitere Informationen zu link:../volumes/logical-space-reporting-enforcement-concept.html["ONTAP Versionsunterstützung für die Meldung logischer Speicherbereiche"].

.Schritte
Eine oder mehrere der folgenden Optionen können aktiviert werden:

* Logische Speicherplatzberichterstattung für ein Volume aktivieren:
+
`volume modify -vserver _svm_name_ -volume _volume_name_ -size _volume_size_ -is-space-reporting-logical true`

* Logische Speicherplatzerzwingung für ein Volume aktivieren:
+
`volume modify -vserver _svm_name_ -volume _volume_name_ -size _volume_size_ -is-space-enforcement-logical true`

* Logische Speicherplatzberichterstattung und -durchsetzung gemeinsam für ein Volume aktivieren:
+
`volume modify -vserver _svm_name_ -volume _volume_name_ -size _volume_size_ -is-space-reporting-logical true -is-space-enforcement-logical true`

* Logische Speicherplatzberichterstattung oder Durchsetzung für eine neue SVM aktivieren:
+
`+vserver create -vserver _svm_name_ -rootvolume root-_volume_name_ -rootvolume-security-style unix -data-services {desired-data-services} [-is-space-reporting-logical true] [-is-space-enforcement-logical true]+`

* Logische Speicherplatzberichterstattung oder -durchsetzung für eine bestehende SVM aktivieren:
+
`+vserver modify -vserver _svm_name_ {desired-data-services} [-is-space-reporting-logical true] [-is-space-enforcement-logical true]+`


