---
permalink: volumes/enable-inline-data-compaction-fas-systems-task.html 
sidebar: sidebar 
keywords: enable, inline, data compaction, fas systems, hdd aggregate, volume efficiency 
summary: Aktivieren Sie die Inline-Datenkomprimierung auf FAS-Systemen mit Flash Pool Aggregaten oder HDD Aggregaten auf Volume- oder Aggregatebene. 
---
= Inline-Datenkompaktierung für FAS Systeme aktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Inline-Datenkomprimierung auf FAS-Systemen mit Flash Pool (hybrid) Aggregaten oder HDD-Aggregaten auf Volume-Ebene mithilfe des  `volume efficiency` cluster shell Befehls aktivieren. Die Datenkomprimierung ist für auf FAS-Systemen erstellte Volumes standardmäßig deaktiviert. Weitere Informationen zu  `volume efficiency` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+efficiency["ONTAP-Befehlsreferenz"^].

.Über diese Aufgabe
Um die Inline-Datenkomprimierung auf einem Volume zu aktivieren, muss die entsprechende `-space-guarantee` Option auf `none` gesetzt werden. Die Aktivierung der Datenkomprimierung auf einem Volume auf einem HDD-Aggregat verwendet zusätzliche CPU-Ressourcen.

.Schritte
. Wechsel zur erweiterten Berechtigungsstufe:
+
[source, cli]
----
set -privilege advanced
----
+
Weitere Informationen zu  `set` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/set.html["ONTAP-Befehlsreferenz"^].

. Den Status der Datenkomprimierung der Volumes und Aggregate für den gewünschten Knoten prüfen:
+
[source, cli]
----
volume efficiency show -volume <volume_name>
----
+
Weitere Informationen zu  `volume efficiency show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-show.html["ONTAP-Befehlsreferenz"^].

. Datenkompaktierung auf dem Volume aktivieren:
+
[source, cli]
----
volume efficiency modify -volume <volume_name> -data-compaction true
----
+
Weitere Informationen zu  `volume efficiency modify` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-modify.html["ONTAP-Befehlsreferenz"^].

+
[NOTE]
====
Wenn die Datenkomprimierung auf  `false` für ein Aggregat oder ein Volume eingestellt ist, schlägt die Komprimierung fehl. Das Aktivieren der Komprimierung komprimiert keine vorhandenen Daten; nur neue Schreibvorgänge im System werden komprimiert. Der  `volume efficiency start` Befehl enthält weitere Informationen darüber, wie vorhandene Daten komprimiert werden können. Weitere Informationen zu  `volume efficiency start` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-start.html["ONTAP-Befehlsreferenz"^].

====
. Anzeige der Kompaktierungsstatistiken:
+
[source, cli]
----
volume efficiency show -volume <volume_name>
----

