---
permalink: volumes/enable-deduplication-volume-task.html 
sidebar: sidebar 
keywords: enable, deduplication, volume, FlexVol, postprocess, inline 
summary: Aktivieren Sie die Deduplizierung auf einem FlexVol Volume, um eine höhere Speichereffizienz zu erzielen. 
---
= Aktivieren Sie die Deduplizierung auf einem ONTAP Volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Deduplizierung kann für ein FlexVol Volume aktiviert werden, um die Speichereffizienz zu steigern. Die Nachbearbeitungsdeduplizierung kann für alle Volumes und die Inline-Deduplizierung für Volumes aktiviert werden, die sich auf AFF oder Flash Pool Aggregaten befinden.

Wenn Inline-Deduplizierung auf anderen Volume-Typen aktiviert werden soll, siehe die link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_enable_volume_inline_deduplication_on_Non-AFF_(All_Flash_FAS)_aggregates["NetApp Knowledge Base: Aktivierung der Inline-Volume-Deduplizierung auf Nicht-AFF (All Flash FAS) Aggregaten"^].

.Bevor Sie beginnen
Für ein FlexVol Volume muss sichergestellt sein, dass ausreichend freier Speicherplatz für Deduplizierungsmetadaten in Volumes und Aggregaten vorhanden ist. Die Deduplizierungsmetadaten benötigen einen Mindestspeicherplatz im Aggregat. Dieser entspricht 3 % der gesamten physischen Datenmenge aller deduplizierten FlexVol Volumes oder Datenbestandteile innerhalb des Aggregats. Jedes FlexVol Volume oder jeder Datenbestandteil sollte über 4 % des gesamten physischen Datenvolumens an freiem Speicherplatz verfügen, insgesamt also 7 %.

[NOTE]
====
Die Inline-Deduplizierung ist auf AFF Systemen standardmäßig aktiviert.

====
.Auswahlmöglichkeiten
* Mit dem  `volume efficiency on`Befehl lässt sich die Nachbearbeitungsdeduplizierung aktivieren. Weitere Informationen zu  `volume efficiency on` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-on.html["ONTAP-Befehlsreferenz"^].
+
Der folgende Befehl aktiviert die Nachbearbeitungsdeduplizierung auf dem Volume VolA:

+
`volume efficiency on -vserver vs1 -volume VolA`

* Verwenden Sie den  `volume efficiency on` Befehl, gefolgt vom  `volume efficiency modify` Befehl mit der  `-inline-deduplication` Option, die auf  `true` gesetzt ist, um sowohl die Nachbearbeitungsdeduplizierung als auch die Inline-Deduplizierung zu aktivieren. Weitere Informationen zu  `volume efficiency modify` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-modify.html["ONTAP-Befehlsreferenz"^].
+
Die folgenden Befehle aktivieren sowohl die Nachbearbeitungsdeduplizierung als auch die Inline-Deduplizierung auf dem Volume VolA:

+
`volume efficiency on -vserver vs1 -volume VolA`

+
`volume efficiency modify -vserver vs1 -volume VolA -inline-dedupe true`

* Den  `volume efficiency on` Befehl, gefolgt vom  `volume efficiency modify` Befehl, mit der  `-inline-deduplication` Option auf  `true` und der  `-policy` Option auf  `inline-only` verwenden, um nur die Inline-Deduplizierung zu aktivieren.
+
Die folgenden Befehle aktivieren ausschließlich die Inline-Deduplizierung auf dem Volume VolA:

+
`volume efficiency on -vserver vs1 -volume VolA`

+
`volume efficiency modify -vserver vs1 -volume VolA -policy inline-only -inline-dedupe true`



.Nachdem Sie fertig sind
Anhand der Einstellungen zur Volume-Effizienz lässt sich überprüfen, ob die Einstellung geändert wurde:
`volume efficiency show -instance`

Weitere Informationen zu  `volume efficiency show -instance` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-show.html["ONTAP-Befehlsreferenz"^].
