---
permalink: volumes/examples-quota-config-concept.html 
sidebar: sidebar 
keywords: examples, quota, configuration, volume quota policy 
summary: Diese Beispiele helfen Ihnen zu verstehen, wie man Quoten konfiguriert und Quota Reports liest. 
---
= Beispiele für Kontingentkonfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese Beispiele helfen Ihnen zu verstehen, wie man Quoten konfiguriert und Quota Reports liest.

.Zu diesen Beispielen
Nehmen wir für die folgenden Beispiele an, dass Sie ein Speichersystem haben, das eine SVM, `vs1` mit einem Volume, umfasst `vol1`.

. Um mit der Einrichtung von Kontingenten zu beginnen, erstellen Sie eine neue Kontingentrichtlinie für die SVM:
+
[listing]
----
cluster1::>volume quota policy create -vserver vs1 -policy-name quota_policy_vs1_1
----
. Da die Kontingentrichtlinie neu ist, weisen Sie sie der SVM zu:
+
[listing]
----
cluster1::>vserver modify -vserver vs1 -quota-policy quota_policy_vs1_1
----


.Beispiel 1: Standard-Benutzerkontingent
. Sie entscheiden sich für eine harte Grenze von 50MB für jeden Benutzer in `vol1`:
+
[listing]
----
cluster1::>volume quota policy rule create -vserver vs1 -policy-name quota_policy_vs1_1 -volume vol1 -type user -target "" -disk-limit 50MB -qtree ""
----
. Um die neue Regel zu aktivieren, initialisieren Sie Quoten auf dem Volumen:
+
[listing]
----
cluster1::>volume quota on -vserver vs1 -volume vol1 -foreground
----
. Sie können den Quota-Bericht anzeigen:
+
[listing]
----
cluster1::>volume quota report
----


Der daraus resultierende Quotenbericht ähnelt dem folgenden Bericht:

[listing]
----
Vserver: vs1
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1               user    *           0B   50MB       0       -   *
vol1               user    jsmith    49MB   50MB      37       -   *
vol1               user    root        0B      -       1       -
----
Die erste Zeile zeigt das von Ihnen erstellte Standard-Benutzerkontingent, einschließlich der Datenträgerbegrenzung. Wie alle Standardkontingente zeigt dieses standardmäßige Benutzerkontingent keine Informationen über die Festplatten- oder Dateinutzung an. Zusätzlich zu dem erstellten Kontingent werden zwei weitere Quotas angezeigt. Es gibt ein Kontingent für jeden Benutzer, der derzeit über Dateien verfügt `vol1`. Diese zusätzlichen Kontingente sind Benutzerkontingente, die automatisch aus dem Standard-Benutzerkontingent abgeleitet wurden. Das abgeleitete Benutzerkontingent für den Benutzer `jsmith` hat die gleiche Festplattengrenze von 50 MB wie das standardmäßige Benutzerkontingent. Das abgeleitete Benutzerkontingent für den Root-Benutzer ist ein Tracking-Quota (ohne Grenzen).

Wenn ein Benutzer auf dem System (außer dem Root-Benutzer) versucht, eine Aktion auszuführen, die mehr als 50 MB in verwenden würde `vol1` (z. B. Schreiben in eine Datei von einem Editor), schlägt die Aktion fehl.

.Beispiel 2: Explizites Benutzerkontingent, das eine standardmäßige Benutzerquote übergibt
. Wenn Sie `vol1` dem Benutzer mehr Speicherplatz im Volumen bereitstellen müssen `jsmith`, geben Sie den folgenden Befehl ein:
+
[listing]
----
cluster1::>volume quota policy rule create -vserver vs1 -policy-name quota_policy_vs1_1 -volume vol1 -type user -target jsmith -disk-limit 80MB -qtree ""
----
+
Dies ist eine explizite Benutzerquote, da der Benutzer explizit als Ziel der Quota-Regel aufgeführt wird.

+
Dies ist eine Änderung an einem vorhandenen Kontingentlimit, da sich das Festplattenlimit des abgeleiteten Benutzer-Quotas für den Benutzer `jsmith` auf dem Volume ändert. Daher müssen Sie die Quoten auf dem Volume nicht neu initialisieren, um die Änderung zu aktivieren.

. So ändern Sie die Größe von Kontingenten:
+
[listing]
----
cluster1::>volume quota resize -vserver vs1 -volume vol1 -foreground
----
+
Die Quoten bleiben während der Anpassung wirksam, und der Anpassungsprozess ist kurz.



Der daraus resultierende Quotenbericht ähnelt dem folgenden Bericht:

[listing]
----
cluster1::> volume quota report
Vserver: vs1
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1               user    *           0B   50MB       0       -   *
vol1               user    jsmith    50MB   80MB      37       -   jsmith
vol1               user    root        0B      -       1       -
3 entries were displayed.
----
Die zweite Zeile zeigt nun einen Datenträgergrenzwert von `80MB` und einen Quota `jsmith`-Spezifikator von.

Daher `jsmith` kann bis zu 80 MB Speicherplatz auf belegen `vol1`, obwohl alle anderen Benutzer noch auf 50 MB begrenzt sind.

.Beispiel 3: Schwellenwerte
Angenommen, Sie möchten eine Benachrichtigung erhalten, wenn Benutzer innerhalb von 5 MB ihrer Festplattenlimits erreichen.

. Um einen Schwellenwert von 45 MB für alle Benutzer und einen Schwellenwert von 75 MB für zu erstellen `jsmith`, ändern Sie die bestehenden Quota-Regeln:
+
[listing]
----
cluster1::>volume quota policy rule modify -vserver vs1 -policy quota_policy_vs1_1 -volume vol1 -type user -target "" -qtree "" -threshold 45MB
cluster1::>volume quota policy rule modify -vserver vs1 -policy quota_policy_vs1_1 -volume vol1 -type user -target jsmith -qtree "" -threshold 75MB
----
+
Da die Größen der vorhandenen Regeln geändert werden, ändern Sie die Größe der Kontingente auf dem Volume, um die Änderungen zu aktivieren. Sie warten, bis die Größenänderung abgeschlossen ist.

. Um den Kontingentbericht mit den Schwellenwerten anzuzeigen, fügen Sie die hinzu `-thresholds` Parameter für das `volume quota report` Befehl:
+
[listing]
----
cluster1::>volume quota report -thresholds
Vserver: vs1
                                    ----Disk----  ----Files-----
Volume   Tree      Type    ID        Used  Limit   Used    Limit  Quota
                                          (Thold)                 Specifier
-------  --------  ------  -------  -----  -----  ------  ------  ---------
vol1               user    *           0B   50MB       0       -  *
                                           (45MB)
vol1               user    jsmith    59MB   80MB      55       -  jsmith
                                           (75MB)
vol1               user    root        0B      -       1       -
                                           ( -)
3 entries were displayed.
----
+
Die Schwellenwerte werden in Klammern in der Spalte Datenträgerbegrenzung angezeigt.



.Beispiel 4: Quoten auf qtrees
Angenommen, Sie müssen einen Speicherplatz für zwei Projekte partitionieren. Sie können zwei qtrees mit den Namen `proj1` und erstellen, `proj2` um diese Projekte in aufzunehmen `vol1`.

Derzeit können Benutzer genau so viel Speicherplatz auf einem qtree benötigen, wie sie für das gesamte Volume zugeteilt werden (vorausgesetzt, sie haben das Limit des Volumes nicht durch die Nutzung von Speicherplatz im Root-Verzeichnis oder einem anderen qtree überschritten). Darüber hinaus kann jede qtrees das gesamte Volume verbrauchen.

. Wenn Sie sicherstellen möchten, dass weder qtree mehr als 20 GB wächst, können Sie Standard-Tree-Kontingent auf dem Volume erstellen:
+
[listing]
----
cluster1:>>volume quota policy rule create -vserver vs1 -policy-name quota_policy_vs1_1 -volume vol1 -type tree -target "" -disk-limit 20GB
----
+

NOTE: Der richtige Typ ist _Tree_, nicht qtree.

. Da es sich um ein neues Kontingent handelt, können Sie es nicht aktivieren, indem Sie die Größe ändern. Sie initialisieren Quoten auf dem Volumen neu:
+
[listing]
----
cluster1:>>volume quota off -vserver vs1 -volume vol1
cluster1:>>volume quota on -vserver vs1 -volume vol1 -foreground
----


[NOTE]
====
Sie müssen sicherstellen, dass Sie etwa fünf Minuten warten, bevor Sie die Quoten für jedes betroffene Volume reaktivieren, als zu versuchen, sie fast unmittelbar nach der Ausführung des zu aktivieren `volume quota off` Der Befehl kann zu Fehlern führen. Alternativ können Sie die Befehle ausführen, um die Quoten für ein Volume von dem Node, der das jeweilige Volume enthält, neu zu initialisieren.

====
Quoten werden während der Neuinitialisierung nicht durchgesetzt, was länger dauert als der Anpassungsprozess.

Wenn Sie einen Quotenbericht anzeigen, enthält er mehrere neue Zeilen. Einige Zeilen gelten für Tree Quotas und einige Zeilen für abgeleitete Benutzer-Quotas.

Die folgenden neuen Zeilen gelten für die Baumquoten:

[listing]
----

                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
...
vol1               tree    *           0B   20GB       0       -   *
vol1     proj1     tree    1           0B   20GB       1       -   proj1
vol1     proj2     tree    2           0B   20GB       1       -   proj2
...
----
Das von Ihnen erstellte Standardbaumkontingent wird in der ersten neuen Zeile mit einem Sternchen (*) in der Spalte ID angezeigt. Als Reaktion auf das Standard-Tree-Kontingent auf einem Volume erstellt ONTAP automatisch abgeleitete Tree Quotas für jeden qtree im Volume. Diese werden in den Zeilen angezeigt, in denen `proj1` und `proj2` in der `Tree` Spalte angezeigt werden.

Die folgenden neuen Zeilen gelten für abgeleitete Benutzerkontingente:

[listing]
----

                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
...
vol1     proj1     user    *           0B   50MB       0       -
vol1     proj1     user    root        0B      -       1       -
vol1     proj2     user    *           0B   50MB       0       -
vol1     proj2     user    root        0B      -       1       -
...
----
Standard-Benutzerkontingente auf einem Volume werden automatisch für alle qtrees übernommen, die in diesem Volume enthalten sind, sofern die Kontingente für qtrees aktiviert sind. Wenn Sie das erste qtree-Kontingent hinzugefügt haben, haben Sie Quoten auf qtrees aktiviert. Daher wurden für jeden qtree abgeleitete Standard-Benutzerkontingente erstellt. Diese werden in den Zeilen mit einem Sternchen (*) angezeigt.

Da der Root-Benutzer Eigentümer einer Datei ist, wurden für jede der qtrees Standard-Benutzerkontingente erstellt, spezielle Tracking-Kontingente für den Root-Benutzer auf jeder qtrees erstellt. Diese werden in den Zeilen angezeigt, in denen ID root ist.

.Beispiel 5: Benutzerkontingent auf einen qtree
. Sie beschließen, Benutzer auf weniger Platz im `proj1` qtree zu beschränken, als sie im Volume als Ganzes erhalten. Sie möchten verhindern, dass sie mehr als 10 MB im `proj1` qtree verwenden. Daher erstellen Sie ein Standard-Benutzerkontingent für den qtree:
+
[listing]
----
cluster1::>volume quota policy rule create -vserver vs1 -policy-name quota_policy_vs1_1 -volume vol1 -type user -target "" -disk-limit 10MB -qtree proj1
----
+
Dies ist eine Änderung zu einem bestehenden Kontingent, da es das Standard-Benutzerkontingent für den proj1-qtree ändert, der aus dem Standard-Benutzerkontingent auf dem Volume abgeleitet wurde. Daher aktivieren Sie die Änderung durch Ändern der Quoten. Wenn der Größenänderungsprozess abgeschlossen ist, können Sie den Quotenbericht anzeigen.

+
Die folgende neue Zeile erscheint im Kontingentbericht, der die neue explizite Benutzerquote für den qtree zeigt:

+
[listing]
----

                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1     proj1     user    *           0B   10MB       0       -   *
----
+
Allerdings `jsmith` kann der Benutzer nicht mehr Daten in den proj1 qtree schreiben, da die Quote, die Sie zum Überschreiben der Standard-Benutzerquote (um mehr Platz bereitzustellen) erstellt haben, auf dem Volume lag. Wie Sie ein Standard Benutzer-Kontingent auf dem `proj1` qtree hinzugefügt haben, wird dieses Kontingent angewendet und begrenzt alle Benutzerfläche in diesem qtree, einschließlich `jsmith`.

. Um dem Benutzer mehr Speicherplatz `jsmith` zur Verfügung zu stellen, fügen Sie eine explizite Benutzer-Quota-Regel für den qtree mit einer Plattengrenze von 80 MB hinzu, um die standardmäßige Benutzer-Quota-Regel für den qtree außer Kraft zu setzen:
+
[listing]
----
cluster1::>volume quota policy rule create -vserver vs1 -policy-name quota_policy_vs1_1 -volume vol1 -type user -target jsmith -disk-limit 80MB -qtree proj1
----
+
Da es sich hierbei um ein explizites Kontingent handelt, für das bereits ein Standardkontingent existiert, aktivieren Sie die Änderung, indem Sie Quotas ändern. Wenn die Größenänderung abgeschlossen ist, wird ein Kontingentbericht angezeigt.



Die folgende neue Zeile wird im Quotenbericht angezeigt:

[listing]
----

                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1     proj1     user    jsmith    61MB   80MB      57       -   jsmith
----
Der endgültige Quotenbericht ähnelt dem folgenden Bericht:

[listing]
----
cluster1::>volume quota report
Vserver: vs1
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1               tree    *           0B   20GB       0       -   *
vol1               user    *           0B   50MB       0       -   *
vol1               user    jsmith    70MB   80MB      65       -   jsmith
vol1     proj1     tree    1           0B   20GB       1       -   proj1
vol1     proj1     user    *           0B   10MB       0       -   *
vol1     proj1     user    root        0B      -       1       -
vol1     proj2     tree    2           0B   20GB       1       -   proj2
vol1     proj2     user    *           0B   50MB       0       -
vol1     proj2     user    root        0B      -       1       -
vol1               user    root        0B      -       3       -
vol1     proj1     user    jsmith    61MB   80MB      57       -   jsmith
11 entries were displayed.
----
Der Benutzer `jsmith` muss die folgenden Quota-Limits erfüllen, um in eine Datei zu schreiben `proj1`:

. Das Tree-Kontingent für den `proj1` qtree.
. Das Benutzerkontingent auf dem `proj1` qtree.
. Die Benutzerkontingente auf dem Volumen.

