---
permalink: volumes/flexclone-files-luns-efficient-copies-concept.html 
sidebar: sidebar 
keywords: use, flexclone files, flexclone luns, create, efficient, copies, files, luns 
summary: FlexClone Dateien und FlexClone LUNs sind beschreibbare, platzsparende Klone von übergeordneten Dateien und übergeordneten LUNs. 
---
= Übersicht über die Verwendung von FlexClone-Dateien und FlexClone-LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexClone Dateien und FlexClone LUNs sind beschreibbare, platzsparende Klone von übergeordneten Dateien und übergeordneten LUNs und sorgen für eine effiziente Auslastung des physischen Aggregatspeichers. FlexClone Dateien und FlexClone LUNs werden nur für FlexVol Volumes unterstützt.

FlexClone-Dateien und FlexClone-LUNs verwenden 0.4 Prozent ihrer Größe für die Speicherung der Metadaten. Klone nutzen die Datenblöcke ihrer übergeordneten Dateien und übergeordneten LUNs und beanspruchen nur geringen Speicherplatz, bis Clients neue Daten entweder in die übergeordnete Datei, in die übergeordnete Datei oder in die LUN oder in den Klon schreiben.

Clients können alle Datei- und LUN-Vorgänge sowohl für die übergeordneten als auch für die Kloneinheiten durchführen.

Sie können mehrere Methoden verwenden, um FlexClone Dateien und FlexClone LUNs zu löschen.
