---
permalink: volumes/inline-storage-efficiency-enablement-aff-concept.html 
sidebar: sidebar 
keywords: inline, storage, efficiency, enabled, default, aff systems 
summary: Alle Inline-Speichereffizienzfunktionen sind standardmäßig auf allen vorhandenen und neu erstellten Volumes auf allen AFF Systemen aktiviert. 
---
= Bei AFF Systemen ist Inline-Storage-Effizienz standardmäßig aktiviert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage-Effizienzfunktionen sind auf allen neu erstellten Volumes auf AFF Systemen standardmäßig aktiviert. Alle Inline-Speichereffizienzfunktionen sind standardmäßig auf allen vorhandenen und neu erstellten Volumes auf allen AFF Systemen aktiviert.

Zu den Storage-Effizienzfunktionen zählen Inline-Deduplizierung, Inline-übergreifende Volume-Deduplizierung und Inline-Komprimierung. Zudem sind sie auf AFF Systemen standardmäßig aktiviert, wie in der Tabelle dargestellt.

[NOTE]
====
Das Datenkomprimierungsverhalten auf AFF -Volumes ist standardmäßig aktiviert.

====
[cols="4*"]
|===
| Volume-Bedingungen 3+| Speichereffizienzfunktionen standardmäßig aktiviert 


 a| 
 a| 
Inline-Deduplizierung
 a| 
Inline-übergreifende Volume-Deduplizierung
 a| 
Inline-Komprimierung



 a| 
Cluster-Upgrade
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.



 a| 
Wechseln Sie mit ONTAP 7-Mode zu Clustered ONTAP
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.



 a| 
Volume-Verschiebung
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.



 a| 
Volumes mit Thick Provisioning
 a| 
Ja.
 a| 
Nein
 a| 
Ja.



 a| 
Verschlüsselte Volumes
 a| 
Ja.
 a| 
Nein
 a| 
Ja.

|===
Die folgenden Ausnahmen gelten für mindestens eine Inline-Storage-Effizienz-Funktion:

* Nur Lese-Schreib-Volumes unterstützen die Inline-Storage-Effizienzunterstützung standardmäßig.
* Volumes mit Komprimierungseinsparungen werden bei der Aktivierung der Inline-Komprimierung nicht berücksichtigt.
* Volumes mit aktivierter nachgelagerter Deduplizierung werden nicht durch die Aktivierung der Inline-Komprimierung aktiviert.
* Auf Volumes, für die die Volume-Effizienz deaktiviert ist, überschreibt das System die vorhandenen Richtlinieneinstellungen für die Volume-Effizienz und setzt diese so ein, dass nur die Inline-Richtlinie aktiviert wird.

