---
permalink: volumes/logical-space-reporting-enforcement-concept.html 
sidebar: sidebar 
keywords: logical, space, reporting, enforcement, volumes 
summary: Ab ONTAP 9.4 können Sie es zulassen, dass der in einem Volume verwendete logische Speicherplatz und die verbleibende Menge an Speicherplatz für Benutzer angezeigt werden. Ab Version 9.5 können Sie die Menge an logischem Speicherplatz begrenzen, der von Benutzern verbraucht wird. 
---
= Überblick über die Erstellung von Berichten und Erzwingung von logischem Speicherplatz für Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.4 können Sie es zulassen, dass der in einem Volume verwendete logische Speicherplatz und die verbleibende Menge an Speicherplatz für Benutzer angezeigt werden. Ab Version 9.5 können Sie die Menge an logischem Speicherplatz begrenzen, der von Benutzern verbraucht wird.

Die Berichterstellung und Durchsetzung des logischen Speicherplatzes ist standardmäßig deaktiviert.

Die folgenden Volume-Typen unterstützen die Berichterstellung und Durchsetzung des logischen Speicherplatzes.

[cols="3*"]
|===
| Volume-Typ | Werden Speicherplatz-Berichte unterstützt? | Wird die Durchsetzung von Raum unterstützt? 


 a| 
FlexVol Volumes
 a| 
Ja, ab ONTAP 9.4
 a| 
Ja, ab ONTAP 9.5



 a| 
SnapMirror Ziel-Volumes
 a| 
Ja, ab ONTAP 9.8
 a| 
Nein



 a| 
FlexGroup Volumes
 a| 
Ja, ab ONTAP 9.9.1
 a| 
Ja, ab ONTAP 9.9.1



 a| 
FlexCache Volumes
 a| 
Die Ursprungseinstellung wird im Cache verwendet
 a| 
Keine Angabe

|===