---
permalink: volumes/logical-space-reporting-concept.html 
sidebar: sidebar 
keywords: what, logical, space, reporting, shows 
summary: Wenn Sie die Berichterstellung für den logischen Speicherplatz auf einem Volume aktivieren, zeigt das System zusätzlich zum Gesamtspeicherplatz eines Volume den verwendeten logischen und verfügbaren Speicherplatz an. 
---
= Berichterstellung für logischen Speicherplatz
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die Berichterstellung für den logischen Speicherplatz auf einem Volume aktivieren, kann Ihr System neben dem gesamten Speicherplatz in einem Volume die Menge des verwendeten logischen und verfügbaren Speicherplatzes anzeigen. Außerdem können Benutzer unter Linux und Windows Client-Systemen den verwendeten logischen und verfügbaren Speicherplatz anstelle des physisch genutzten und verfügbaren Speicherplatzes sehen.

Definitionen:

* Physischer Speicherplatz bezieht sich auf die physischen Blöcke des verfügbaren oder im Volume genutzten Storage.
* Logischer Speicherplatz bezeichnet den nutzbaren Speicherplatz in einem Volume.
* Der physische Speicherplatz wird verwendet, plus Einsparungen durch konfigurierte Storage-Effizienzfunktionen (wie Deduplizierung und Komprimierung).


Ab ONTAP 9.5 können Sie die Durchsetzung des logischen Speicherplatzes zusammen mit der Speicherplatzberichterstattung aktivieren.

Wenn diese Option aktiviert ist, werden mit dem `volume show` Befehl die folgenden Parameter angezeigt:

[cols="25%,75%"]
|===
| Parameter | Bedeutung 


 a| 
`-logical-used`
 a| 
Zeigt nur Informationen über das Volume oder die Volumes mit der angegebenen logischen Größe an. Dieser Wert schließt den gesamten Platz ein, der durch die Storage-Effizienzfunktionen eingespart wird, sowie den physisch genutzten Speicherplatz. Dies beinhaltet keine Snapshot Reserve, sondern eine Snapshot Verschüttung in Betracht ziehen.



 a| 
`-logical-used-by-afs`
 a| 
Zeigt nur Informationen über das Volume oder die Volumes an, die über die angegebene logische Größe verfügen, die vom aktiven Dateisystem verwendet wird. Dieser Wert unterscheidet sich von dem``-logical-used`` Wert durch die Menge der Snapshot-Verschüttung, die die Snapshot-Reserve überschreitet.



 a| 
`-logical-available`
 a| 
Wenn nur das Reporting des logischen Speicherplatzes aktiviert ist, wird nur der physisch verfügbare Speicherplatz angezeigt. Wenn sowohl die Berichterstellung als auch die Durchsetzung des Speicherplatzes aktiviert sind, wird der derzeit verfügbare freie Speicherplatz angezeigt, sofern der durch die Storage-Effizienzfunktionen eingesparte Speicherplatz in Betracht gezogen wird. Dies beinhaltet nicht die Snapshot Reserve.



 a| 
`-logical-used-percent`
 a| 
Zeigt den Prozentsatz des aktuellen `-logical-used` Werts mit der bereitgestellten Größe ohne Snapshot-Reserve des Volumes an.

Dieser Wert kann größer als 100 % sein, da der `-logical-used-by-afs` Wert die Effizienzeinsparungen im Volume einschließt. Der `-logical-used-by-afs` Wert eines Volumes berücksichtigt keine Snapshot-Verschüttung als belegten Speicherplatz. Der `-physical-used` Wert eines Volumes schließt die ausgelaufene Snapshot-Kapazität als belegten Speicherplatz ein.



 a| 
`-used`
 a| 
Zeigt den von Benutzerdaten und Dateisystem-Metadaten belegten Speicherplatz an. Diese unterscheidet sich von `physical-used` Speicherplatz durch die Summe des Speicherplatzes, der für zukünftige Schreibvorgänge reserviert ist, und des durch aggregierte Storage-Effizienzfunktionen eingesparten Speicherplatzes. Es schließt die ausgelaufene Snapshot-Kapazität ein (die Menge an Speicherplatz, durch die Snapshot Kopien die Snapshot Reserve überschreiten). Die Snapshot Reserve ist nicht enthalten.

|===
Durch das Aktivieren der Berichterstellung für logischen Speicherplatz in der CLI können in System Manager auch die Werte für den belegten logischen Speicherplatz (%) und den logischen Speicherplatz angezeigt werden

Client-Systeme sehen den logischen Speicherplatz, der im folgenden System als „`used`“-Speicherplatz angezeigt wird:

* *Df* Ausgabe auf Linux-Systemen
* Details zum Speicherplatz unter Eigenschaften unter Windows Explorer auf Windows-Systemen.


[NOTE]
====
Wenn die Berichterstellung für logischen Speicherplatz ohne Durchsetzung von logischem Speicherplatz aktiviert ist, kann die insgesamt auf Client-Systemen angezeigte Summe größer als der bereitgestellte Speicherplatz sein.

====