---
permalink: volumes/manage-volume-efficiency-operations-manual-concept.html 
sidebar: sidebar 
keywords: manage, volume, efficiency, operations, manually 
summary: Verwaltung des Ablaufs der Effizienzmaßnahmen für ein Volume durch manuelles Ausführen der Effizienzmaßnahmen. 
---
= ONTAP Volumeneffizienzoperationen manuell verwalten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können steuern, wie die Effizienzoperationen auf einem Volume ausgeführt werden, indem Sie die Effizienzoperationen manuell ausführen.

Sie können auch steuern, wie die Effizienzmaßnahmen basierend auf den folgenden Bedingungen ausgeführt werden:

* Kontrollpunkte verwenden oder nicht
* Effizienzoperationen können entweder auf vorhandenen Daten oder nur auf neuen Daten ausgeführt werden.
* Effizienzmaßnahmen bei Bedarf beenden


Sie können den  `volume efficiency show` Befehl mit  `schedule` als Wert für die  `-fields` Option verwenden, um den den Volumes zugewiesenen Zeitplan anzuzeigen.

Weitere Informationen zu  `volume efficiency show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-show.html["ONTAP-Befehlsreferenz"^].
