---
permalink: volumes/move-between-secondary-adaptive-compression-task.html 
sidebar: sidebar 
keywords: move, secondary compression, adaptive compression 
summary: Sie können je nach Menge des Datenlesens zwischen der sekundären Komprimierung und der adaptiven Komprimierung wechseln. Die adaptive Komprimierung ist vorzuziehen, wenn es im System eine hohe Anzahl zufälliger Lesevorgänge gibt und eine höhere Performance erforderlich ist. Sekundäre Komprimierung ist vorzuziehen, wenn Daten sequenziell geschrieben werden und höhere Komprimierungseinsparungen erforderlich sind. 
---
= Wechseln Sie zwischen sekundärer Komprimierung und anpassungsfähiger Komprimierung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können je nach Menge des Datenlesens zwischen der sekundären Komprimierung und der adaptiven Komprimierung wechseln. Die adaptive Komprimierung ist vorzuziehen, wenn es im System eine hohe Anzahl zufälliger Lesevorgänge gibt und eine höhere Performance erforderlich ist. Sekundäre Komprimierung ist vorzuziehen, wenn Daten sequenziell geschrieben werden und höhere Komprimierungseinsparungen erforderlich sind.

.Über diese Aufgabe
Die Auswahl des Standardkomprimierungstyps erfolgt auf Grundlage Ihrer Aggregate und Plattform.

.Schritte
. Deaktivieren Sie die Datenkomprimierung auf dem Volume:
+
`volume efficiency modify`

+
Mit dem folgenden Befehl wird die Datenkomprimierung auf dem Volume vol1 deaktiviert:

+
`volume efficiency modify -compression false -inline-compression false -volume vol1`

. Ändern Sie die erweiterte Berechtigungsebene:
+
`set -privilege advanced`

. Dekomprimieren der komprimierten Daten:
+
`volume efficiency undo`

+
Mit dem folgenden Befehl werden die komprimierten Daten auf dem Volume vol1 dekomprimiert:

+
`volume efficiency undo -vserver vs1 -volume vol1 -compression true`

+
[NOTE]
====
Sie müssen überprüfen, dass im Volume ausreichend Speicherplatz vorhanden ist, um die dekomprimierten Daten aufzunehmen.

====
. Stellen Sie sicher, dass der Status des Vorgangs inaktiv ist:
+
`volume efficiency show`

+
Mit dem folgenden Befehl wird der Status eines Effizienzvorgangs auf Volume vol1 angezeigt:

+
`volume efficiency show -vserver vs1 -volume vol1`

. Aktivieren Sie die Datenkomprimierung und legen Sie anschließend den Komprimierungstyp fest:
+
`volume efficiency modify`

+
Mit dem folgenden Befehl wird die Datenkomprimierung aktiviert und der Komprimierungstyp als sekundäre Komprimierung auf dem Volume vol1 festgelegt:

+
`volume efficiency modify -vserver vs1 -volume vol1 -compression true -compression-type secondary`

+
[NOTE]
====
Mit diesem Schritt kann nur die sekundäre Komprimierung auf dem Volume aktiviert werden. Die Daten auf dem Volume werden nicht komprimiert.

** Um vorhandene Daten auf AFF Systemen zu komprimieren, müssen Sie den Komprimierungsscanner im Hintergrund ausführen.
** Um vorhandene Daten auf Flash Pool Aggregaten oder HDD-Aggregaten zu komprimieren, müssen Sie die Hintergrund-Komprimierung ausführen.


====
. Ändern Sie diese auf der Administrator-Berechtigungsebene:
+
`set -privilege admin`

. Optional: Inline-Komprimierung aktivieren:
+
`volume efficiency modify`

+
Mit dem folgenden Befehl wird die Inline-Komprimierung auf Volume vol1 aktiviert:

+
`volume efficiency modify -vserver vs1 -volume vol1 -inline-compression true`


