---
permalink: volumes/move-volume-concept.html 
sidebar: sidebar 
keywords: how, move, flexvol, volume, works 
summary: Die Phasen eines FlexVol volume move und den Client-Zugriff während des Prozesses. 
---
= Erfahren Sie mehr über das Verschieben eines ONTAP FlexVol Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Volumes verschieben oder kopieren, um die Kapazitätsauslastung zu optimieren, die Leistung zu verbessern und Service-Level-Agreements zu erfüllen. Das Verständnis, wie das Verschieben eines FlexVol volume funktioniert, hilft dabei zu beurteilen, ob die Verschiebung die Service-Level-Agreements erfüllt und an welcher Stelle im Verschiebungsprozess sich das Volume befindet.

FlexVol volumes werden innerhalb derselben Storage Virtual Machine (SVM) von einem Aggregat oder Knoten zu einem anderen verschoben. Ein Volume-Verschieben unterbricht den Clientzugriff während der Verschiebung nicht.


NOTE: Während der Umstellungsphase eines Volume-Verschiebungsvorgangs können keine FlexClone Dateien oder FlexClone LUNs eines FlexVol Volume erstellt werden.

Das Verschieben eines Volumens erfolgt in mehreren Phasen:

* Ein neues Volume wird auf dem Zielaggregat erstellt.
* Die Daten vom ursprünglichen Volume werden auf das neue Volume kopiert.
+
Während dieser Zeit bleibt das Originalvolumen erhalten und ist für Clients zugänglich.

* Nach Abschluss des Umzugsvorgangs wird der Clientzugriff vorübergehend gesperrt.
+
Während dieser Zeit führt das System eine letzte Replikation vom Quellvolume zum Zielvolume durch, tauscht die Identitäten der Quell- und Zielvolumes und ändert das Zielvolume in das Quellvolume.

* Nach Abschluss des Umzugs leitet das System den Client-Datenverkehr auf das neue Quellvolume und stellt den Client-Zugriff wieder her.


Der Vorgang beeinträchtigt den Clientzugriff nicht, da die Zeit, in der der Clientzugriff gesperrt ist, endet, bevor Clients eine Unterbrechung bemerken und eine Zeitüberschreitung auftritt. Standardmäßig ist der Clientzugriff 30 Sekunden lang gesperrt. Kann der Volume-Verschiebungsvorgang in der Zeit, in der der Zugriff verweigert wird, nicht abgeschlossen werden, bricht das System diese letzte Phase des Volume-Verschiebungsvorgangs ab und gewährt den Clientzugriff. Das System versucht die letzte Phase standardmäßig dreimal. Nach dem dritten Versuch wartet das System eine Stunde, bevor die letzte Phase erneut versucht wird. Das System führt die letzte Phase des Volume-Verschiebungsvorgangs aus, bis der Volume-Verschiebungsvorgang abgeschlossen ist.
