---
permalink: volumes/move-volume-concept.html 
sidebar: sidebar 
keywords: how, move, flexvol, volume, works 
summary: Verstehen Sie die Phasen einer FlexVol volume-Verschiebung und den Client-Zugriff während des Prozesses. 
---
= Verschieben Sie einen Überblick über FlexVol Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Volumes verschieben oder kopieren, um Kapazitäten zu nutzen, die Performance zu verbessern und die Einhaltung von Service Level Agreements zu erfüllen. Wenn Sie wissen, wie das Verschieben eines FlexVol Volumes funktioniert, können Sie feststellen, ob die Verschiebung eines Volumes Service Level Agreements erfüllt und ermitteln, wo sich die Volume-Verschiebung befindet.

FlexVol Volumes werden von einem Aggregat oder Node zu einem anderen innerhalb derselben Storage Virtual Machine (SVM) verschoben. Durch eine Volume-Verschiebung wird der Client-Zugriff während der Verschiebung nicht unterbrochen.


NOTE: In der Umstellungsphase eines Volume-Verschiebevorgangs können keine FlexClone Dateien oder FlexClone LUNs eines FlexVol Volume erstellt werden.

Verschieben eines Volumes erfolgt in mehreren Phasen:

* Ein neues Volume wird auf dem Zielaggregat erstellt.
* Die Daten aus dem ursprünglichen Volume werden auf das neue Volume kopiert.
+
Während dieser Zeit ist das ursprüngliche Volume intakt und für Clients verfügbar.

* Am Ende des Verschiebevorgangs wird der Client-Zugriff vorübergehend gesperrt.
+
Während dieser Zeit führt das System eine endgültige Replikation vom Quell-Volume zum Ziel-Volume durch, tauscht die Identitäten der Quell- und Ziel-Volumes aus und ändert das Ziel-Volume in das Quell-Volume.

* Nach Abschluss der Verschiebung wird der Client-Datenverkehr zum neuen Quell-Volume weitergeleitet und der Client-Zugriff wird fortgesetzt.


Die Verschiebung wird für den Client-Zugriff nicht unterbrochen, da die Zeit, in der der Client-Zugriff gesperrt ist, bevor Clients eine Unterbrechung oder eine Unterbrechung bemerken. Der Client-Zugriff ist standardmäßig für 35 Sekunden gesperrt. Falls der Vorgang zur Verschiebung des Volumes nicht zum Zeitpunkt des Abzugriffs abgeschlossen werden kann, bricht das System diese letzte Phase der Verschiebung des Volumes ab und erlaubt den Client-Zugriff. Das System versucht standardmäßig dreimal die letzte Phase. Nach dem dritten Versuch wartet das System eine Stunde, bevor es erneut versucht wird, die letzte Phasenfolge zu versuchen. Das System führt die letzte Phase der Verschiebung des Volumes aus, bis die Volume-Verschiebung abgeschlossen ist.
