---
permalink: volumes/move-between-secondary-adaptive-compression-task.html 
sidebar: sidebar 
keywords: move, secondary compression, adaptive compression 
summary: Sie können je nach Menge des Datenlesens zwischen der sekundären Komprimierung und der adaptiven Komprimierung wechseln. 
---
= Wechseln Sie zwischen sekundärer Komprimierung und anpassungsfähiger Komprimierung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können je nach Menge des Datenlesens zwischen der sekundären Komprimierung und der adaptiven Komprimierung wechseln. Die adaptive Komprimierung ist vorzuziehen, wenn es im System eine hohe Anzahl zufälliger Lesevorgänge gibt und eine höhere Performance erforderlich ist. Sekundäre Komprimierung ist vorzuziehen, wenn Daten sequenziell geschrieben werden und höhere Komprimierungseinsparungen erforderlich sind.

.Über diese Aufgabe
Die Auswahl des Standardkomprimierungstyps erfolgt auf Grundlage Ihrer Aggregate und Plattform.

.Schritte
. Deaktivieren Sie die Effizienz für das Volume:
+
`volume efficiency off`

+
Beispielsweise wird mit dem folgenden Befehl die Effizienz auf Volume vol1 deaktiviert:

+
`volume efficiency off -vserver vs1 -volume vol1`

. Ändern Sie die erweiterte Berechtigungsebene:
+
`set -privilege advanced`

. Dekomprimieren der komprimierten Daten:
+
`volume efficiency undo`

+
Mit dem folgenden Befehl werden beispielsweise die komprimierten Daten auf Volume vol1 dekomprimiert:

+
`volume efficiency undo -vserver vs1 -volume vol1 -compression true`

+
[NOTE]
====
Sie müssen überprüfen, dass im Volume ausreichend Speicherplatz vorhanden ist, um die dekomprimierten Daten aufzunehmen.

====
. Ändern Sie diese auf der Administrator-Berechtigungsebene:
+
`set -privilege admin`

. Stellen Sie sicher, dass der Status des Vorgangs inaktiv ist:
+
`volume efficiency show`

+
Beispielsweise wird mit dem folgenden Befehl der Status eines Effizienzvorvorgangs für Volume vol1 angezeigt:

+
`volume efficiency show -vserver vs1 -volume vol1`

. Effizienz für das Volume aktivieren:
+
`volume efficiency on` So wird beispielsweise mit dem folgenden Befehl die Effizienz auf Volume vol1 aktiviert:

+
`volume efficiency on -vserver vs1 -volume vol1`

. Aktivieren Sie die Datenkomprimierung und legen Sie anschließend den Komprimierungstyp fest:
+
`volume efficiency modify`

+
Beispielsweise ermöglicht der folgende Befehl die Datenkomprimierung und setzt den Komprimierungstyp als sekundäre Komprimierung auf Volume vol1:

+
`volume efficiency modify -vserver vs1 -volume vol1 -compression true -compression-type secondary`

+
[NOTE]
====
Mit diesem Schritt kann nur die sekundäre Komprimierung auf dem Volume aktiviert werden. Die Daten auf dem Volume werden nicht komprimiert.

** Um vorhandene Daten auf AFF Systemen zu komprimieren, müssen Sie den Komprimierungsscanner im Hintergrund ausführen.
** Um vorhandene Daten auf Flash Pool Aggregaten oder HDD-Aggregaten zu komprimieren, müssen Sie die Hintergrund-Komprimierung ausführen.


====
. Optional: Inline-Komprimierung aktivieren:
+
`volume efficiency modify`

+
Beispielsweise aktiviert der folgende Befehl die Inline-Komprimierung auf Volume vol1:

+
`volume efficiency modify -vserver vs1 -volume vol1 -inline-compression true`


