---
permalink: volumes/move-between-secondary-adaptive-compression-task.html 
sidebar: sidebar 
keywords: move, secondary compression, adaptive compression 
summary: Je nach Anzahl der Datenlesevorgänge kann zwischen sekundärer Komprimierung und adaptiver Komprimierung gewechselt werden. 
---
= Wechseln Sie zwischen ONTAP Sekundärkomprimierung und adaptiver Komprimierung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Je nach Anzahl der Datenlesevorgänge kann zwischen sekundärer Komprimierung und adaptiver Komprimierung gewechselt werden. Adaptive Komprimierung ist vorzuziehen, wenn eine hohe Anzahl zufälliger Lesezugriffe auf das System erfolgt und eine höhere Leistung erforderlich ist. Sekundäre Komprimierung ist vorzuziehen, wenn Daten sequenziell geschrieben werden und ein höheres Komprimierungspotenzial erforderlich ist.

.Über diese Aufgabe
Der Standardkomprimierungstyp wird basierend auf Ihren Aggregaten und Ihrer Plattform ausgewählt.

.Schritte
. Effizienz auf dem Volume deaktivieren:
+
`volume efficiency off`

+
Beispielsweise deaktiviert der folgende Befehl die Effizienz auf dem Volume vol1:

+
`volume efficiency off -vserver vs1 -volume vol1`

. Wechsel zur erweiterten Berechtigungsstufe:
+
`set -privilege advanced`

. Die komprimierten Daten dekomprimieren:
+
`volume efficiency undo`

+
Beispielsweise dekomprimiert der folgende Befehl die komprimierten Daten auf dem Volume vol1:

+
`volume efficiency undo -vserver vs1 -volume vol1 -compression true`

+
[NOTE]
====
Es ist zu überprüfen, ob im Volume ausreichend Speicherplatz für die dekomprimierten Daten vorhanden ist.

====
. Wechseln Sie zur Administrator-Berechtigungsstufe:
+
`set -privilege admin`

. Es sollte überprüft werden, ob der Status des Vorgangs auf „Leerlauf“ steht:
+
`volume efficiency show`

+
Beispielsweise zeigt der folgende Befehl den Status eines Effizienzvorgangs auf dem Volume vol1 an:

+
`volume efficiency show -vserver vs1 -volume vol1`

. Effizienz für das Volume aktivieren:
+
`volume efficiency on`Beispielsweise aktiviert der folgende Befehl die Effizienz auf dem Volume vol1:

+
`volume efficiency on -vserver vs1 -volume vol1`

. Datenkomprimierung aktivieren und anschließend den Komprimierungstyp festlegen:
+
`volume efficiency modify`

+
Beispielsweise aktiviert der folgende Befehl Datenkomprimierung und legt den Komprimierungstyp als sekundäre Komprimierung für das Volume vol1 fest:

+
`volume efficiency modify -vserver vs1 -volume vol1 -compression true -compression-type secondary`

+
[NOTE]
====
Dieser Schritt ermöglicht lediglich die sekundäre Komprimierung des Volumes; die Daten auf dem Volume werden nicht komprimiert.

** Um vorhandene Daten auf AFF Systemen zu komprimieren, ist der Hintergrundkomprimierungsscanner auszuführen.
** Um vorhandene Daten auf Flash Pool Aggregaten oder HDD Aggregaten zu komprimieren, ist die Hintergrundkomprimierung auszuführen.


====
. Optional: Inline-Komprimierung kann aktiviert werden:
+
`volume efficiency modify`

+
Beispielsweise aktiviert der folgende Befehl die Inline-Komprimierung für das Volume vol1:

+
`volume efficiency modify -vserver vs1 -volume vol1 -inline-compression true`


