---
permalink: volumes/move-volume-task.html 
sidebar: sidebar 
keywords: move, volume 
summary: Verschieben Sie ein FlexVol Volume in ein anderes Aggregat, einen anderen Knoten oder beides innerhalb derselben Storage Virtual Machine, um die Speicherkapazität auszugleichen. 
---
= Verschieben eines ONTAP Volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein FlexVol volume innerhalb derselben Storage Virtual Machine (SVM) auf ein anderes Aggregat, einen anderen Knoten oder beides verschieben, um die Kapazitätsauslastung auszugleichen, nachdem festgestellt wurde, dass ein Ungleichgewicht der Kapazitätsauslastung besteht.

.Über diese Aufgabe
Standardmäßig wird der Umstellungsvorgang wiederholt, wenn er nicht innerhalb von 30 Sekunden abgeschlossen werden kann. Das Standardverhalten lässt sich mit den Parametern  `-cutover-window` und  `-cutover-action` anpassen, wobei für beide ein erweiterter Berechtigungslevel erforderlich ist.

Sie müssen Cluster-Administrator sein, um diese Aufgabe ausführen zu können.

.Bevor Sie beginnen
* Wenn ein Volume mit 8K adaptiver Komprimierung auf eine der folgenden Plattformen verschoben wird, sollte link:increase-volume-active-file-system-size.html["die Größe des aktiven Dateisystems des Volumes vergrößern"] vor dem Verschieben des Volumes erfolgen. Die Daten werden auf diesen Plattformen anders komprimiert, sodass Speicherplatz auf Aggregatebene statt auf Volume-Ebene eingespart wird. Aufgrund dieses Unterschieds sollte die Größe des aktiven Dateisystems des Volumes um den Betrag der 8K-Komprimierungseinsparung erhöht werden, um zu verhindern, dass während der Volume-Verschiebung der Speicherplatz ausgeht.
+
** AFF und FAS Plattformen, die dedizierte Offload-Prozessor-Speichereffizienz unterstützen
+
Weitere Informationen zu AFF und FAS Plattformen, die link:../concepts/builtin-storage-efficiency-concept.html["dedizierter Offload-Prozessor Speicher-Effizienz"] unterstützen.

** AFF C-Series Plattformen
+
Siehe link:https://hwu.netapp.com/["Hardware Universe"^] für eine vollständige Liste der C-Series Plattformen.



* Wenn Sie einen Datenschutzspiegel verschieben und die Spiegelungsbeziehung noch nicht initialisiert haben, kann die Spiegelungsbeziehung mit dem  `snapmirror initialize` Befehl initialisiert werden. Weitere Informationen zu  `snapmirror initialize` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["ONTAP-Befehlsreferenz"^].
+
Die Datenschutz-Spiegelbeziehungen müssen initialisiert werden, bevor eines der Volumes verschoben werden kann.



.Schritte
. Ein Aggregat bestimmen, auf das das Volume verschoben werden kann:
+
[source, cli]
----
volume move target-aggr show
----
+
Das ausgewählte Aggregat muss über ausreichend Platz für das Volume verfügen, das heißt, die verfügbare Größe ist größer als das Volume, das verschoben wird.

+
Das folgende Beispiel zeigt, dass das vs2 Volume in jedes der aufgeführten Aggregate verschoben werden kann:

+
[listing]
----
cluster1::> volume move target-aggr show -vserver vs2 -volume user_max
Aggregate Name   Available Size   Storage Type
--------------   --------------   ------------
aggr2            467.9GB          hdd
node12a_aggr3    10.34GB          hdd
node12a_aggr2    10.36GB          hdd
node12a_aggr1    10.36GB          hdd
node12a_aggr4    10.36GB          hdd
5 entries were displayed.
----
+
Weitere Informationen zu  `volume move target-aggr show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-move-target-aggr-show.html["ONTAP-Befehlsreferenz"^].

. Eine Validierungsprüfung stellt sicher, dass das Volume in das vorgesehene Aggregat verschoben werden kann:
+
[source, cli]
----
volume move start -perform-validation-only
----
+
Weitere Informationen zu  `volume move start` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-move-start.html["ONTAP-Befehlsreferenz"^].

. Das Volume verschieben:
+
[source, cli]
----
volume move start
----
+
Der folgende Befehl verschiebt das user_max Volume auf der vs2 SVM auf das node12a_aggr3 Aggregat. Der Verschiebevorgang läuft als Hintergrundprozess.

+
[listing]
----
cluster1::> volume move start -vserver vs2 -volume user_max
-destination-aggregate node12a_aggr3
----
. Status des Volume-Verschiebevorgangs bestimmen:
+
[source, cli]
----
volume move show
----
+
Das folgende Beispiel zeigt den Status einer Volumenverschiebung, die die Replikationsphase abgeschlossen hat und sich in der Umstellungsphase befindet:

+
[listing]
----

cluster1::> volume move show
Vserver   Volume     State    Move Phase  Percent-Complete Time-To-Complete
--------- ---------- -------- ----------  ---------------- ----------------
vs2       user_max   healthy  cutover     -                -
----
+
Der Vorgang zum Verschieben des Volumens ist abgeschlossen, wenn es nicht mehr in der `volume move show` Befehlsausgabe erscheint.

+
Weitere Informationen zu  `volume move show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-move-show.html["ONTAP-Befehlsreferenz"^].

. Optional lassen sich die Komprimierungseinsparungen anzeigen:
+
[source, cli]
----
volume show-footprint -vserver <SVM> -volume <volume_name>
----
+

NOTE: Zusätzliche Einsparungen auf Aggregatebene könnten durch einen Nachbearbeitungs-Konvertierungsscan erzielt werden, der automatisch und kurz nach Abschluss der Volumenverschiebung ausgeführt wird.



.Verwandte Informationen
* link:recommendations-moving-concept.html["Überlegungen und Empfehlungen beim Verschieben von Volumes"]

