---
permalink: volumes/non-space-reserved-luns-thin-provisioned-concept.html 
sidebar: sidebar 
keywords: configuration, settings, non-space-reserved, files, luns, thin-provisioned, volumes 
summary: FlexVol volume- und Datei- oder LUN-Konfigurationskombination erfordert die Vorabzuweisung von Speicherplatz und aktives Speicherplatzmanagement, um Speicherplatzmangel zu verhindern. 
---
= Einstellungen für nicht speicherplatzreservierte Dateien oder LUNs mit Thin-Provisioned ONTAP Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese FlexVol Volume- und Datei- oder LUN-Konfigurationskombination erfordert die geringste Menge an Speicherplatz, die im Voraus zugewiesen werden muss, erfordert jedoch ein aktives Speicherplatzmanagement, um Fehler aufgrund von Speicherplatzmangel zu vermeiden.

Folgende Einstellungen sind erforderlich, um nicht speicherplatzreservierte Dateien oder LUNs in einem Thin-Provisioning Volume zu konfigurieren:

[cols="2*"]
|===
| Volume-Einstellung | Wert 


 a| 
Garantie
 a| 
Keine



 a| 
Teilreserve
 a| 
0



 a| 
Snapshot-Reserve
 a| 
Beliebig



 a| 
Snapshot Autolöschung
 a| 
Optional



 a| 
Automatisches Wachstum
 a| 
Optional

|===
[cols="2*"]
|===
| Datei- oder LUN-Einstellung | Wert 


 a| 
Platzreservierung
 a| 
Deaktiviert

|===


[[additional-considerations]]
== Weitere Überlegungen

Wenn der Speicherplatz auf dem Volume oder Aggregat erschöpft ist, können Schreibvorgänge auf die Datei oder LUN fehlschlagen.

Wenn Sie den freien Speicherplatz sowohl des Volumes als auch des Aggregats nicht aktiv überwachen möchten, sollte Autogrow für das Volume aktiviert werden und die maximale Größe des Volumes auf die Größe des Aggregats festgelegt werden. In dieser Konfiguration ist eine aktive Überwachung des freien Speicherplatzes im Aggregat erforderlich, während der freie Speicherplatz im Volume nicht überwacht werden muss.
