---
permalink: volumes/non-space-reserved-luns-thin-provisioned-concept.html 
sidebar: sidebar 
keywords: configuration, settings, non-space-reserved, files, luns, thin-provisioned, volumes 
summary: Eine Kombination aus FlexVol volume- und Datei- oder LUN-Konfigurationen erfordert die Zuweisung von Storage vorab und das Management von aktivem freiem Speicherplatz, um Speicherplatzmangel zu verhindern. 
---
= Einstellungen für Dateien ohne Speicherplatzreservierung oder LUNs mit Volumes mit Thin Provisioning
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese Kombination aus FlexVol-Volume- und Datei- oder LUN-Konfiguration erfordert die kleinste Storage-Menge im Voraus. Es erfordert jedoch aktives, freies Speicherplatzmanagement, um Fehler aufgrund von mangelndem Speicherplatz zu vermeiden.

Folgende Einstellungen sind erforderlich, um eine Datei oder ein LUN ohne Speicherplatz in einem Volume mit Thin Provisioning zu konfigurieren:

[cols="2*"]
|===
| Lautstärkereinstellung | Wert 


 a| 
Garantie
 a| 
Keine



 a| 
Fraktionale Reserve
 a| 
0



 a| 
Snapshot Reserve
 a| 
Alle



 a| 
Snapshot wird automatisches Löschen erstellt
 a| 
Optional



 a| 
Autogrow
 a| 
Optional

|===
[cols="2*"]
|===
| Datei- oder LUN-Einstellung | Wert 


 a| 
Speicherplatzreservierung
 a| 
Deaktiviert

|===


== Weitere Überlegungen

Wenn der Speicherplatz des Volume oder Aggregats knapp wird, können Schreibvorgänge für die Datei oder LUN ausfallen.

Wenn Sie den freien Speicherplatz nicht sowohl für das Volume als auch für das Aggregat aktiv überwachen möchten, sollten Sie Autogrow für das Volume aktivieren und die maximale Größe für das Volume auf die Größe des Aggregats festlegen. In dieser Konfiguration müssen Sie den freien Speicherplatz des Aggregats aktiv überwachen, den freien Speicherplatz im Volume jedoch nicht überwachen.
