---
permalink: volumes/qtrees-partition-your-volumes-concept.html 
sidebar: sidebar 
keywords: volumes, volume partitioning, qtrees, flexvol volumes, performance, metrics, extended performance monitoring 
summary: Mit Qtrees können Sie FlexVol volumes in kleinere, einzeln verwaltbare Segmente unterteilen. Die durch Qtrees ermöglichte Volume-Partitionierung bietet eine präzisere Kontrolle bei der Speicherverwaltung nach Projekt, Benutzer oder Gruppe. Qtrees ermöglichen eine bessere Verwaltung von Quotas, Sicherheitsstil und CIFS-Oplocks. 
---
= Qtrees und ONTAP FlexVol Volume-Partitionierung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit Qtrees können Sie FlexVol volumes in kleinere, einzeln verwaltbare Segmente unterteilen. Die durch Qtrees ermöglichte Volume-Partitionierung bietet eine präzisere Kontrolle bei der Speicherverwaltung nach Projekt, Benutzer oder Gruppe. Qtrees ermöglichen eine bessere Verwaltung von Quotas, Sicherheitsstil und CIFS-Oplocks.


NOTE: ONTAP erstellt für jedes Volume einen Standard-Qtree mit dem Namen *qtree0*. Werden Daten nicht in einem bestimmten Qtree abgelegt, befinden sie sich in qtree0.



[[general-limitations]]
== Allgemeine Einschränkungen

Vor der Verwendung von Qtrees in einer Produktionsumgebung sollten die Einschränkungen von Qtrees bekannt sein. Außerdem sollten die <<Funktionsweise und Einschränkungen>>Hinweise bei der Nutzung der erweiterten Qtree-Leistungsüberwachungsfunktion beachtet werden.

* Qtree-Namen dürfen maximal 64 Zeichen lang sein.
* Bestimmte Sonderzeichen in den Qtree-Namen, wie Kommas und Leerzeichen, können Probleme mit anderen ONTAP Funktionen verursachen und sollten vermieden werden.
* Verzeichnisse können nicht zwischen verschiedenen Qtrees verschoben werden. Nur Dateien können zwischen Qtrees verschoben werden.
* Wenn Freigaben auf Qtree-Ebene und Volume-Ebene im selben FlexVol Pool oder SCVMM Pool erstellt werden, erscheinen die Qtrees als Verzeichnisse in der FlexVol Freigabe. Es sollte darauf geachtet werden, dass diese nicht versehentlich gelöscht werden.




[[commands-for-managing-and-configuring-qtrees]]
== Befehle zum Verwalten und Konfigurieren von Qtrees

Sie können Qtrees mithilfe der ONTAP CLI verwalten und konfigurieren. Abhängig davon, was Sie tun möchten, sind die folgenden Befehle zur Administration von Qtrees zu verwenden.

[NOTE]
====
Der Befehl  `volume rehost`kann dazu führen, dass andere gleichzeitig ausgeführte administrative Operationen, die auf dasselbe Volume abzielen, fehlschlagen.

====
|===


| Wenn Sie möchten... | Verwenden Sie diesen Befehl... 


 a| 
Einen Qtree erstellen
 a| 
`volume qtree create`



 a| 
Eine gefilterte Liste von Qtrees wird angezeigt
 a| 
`volume qtree show`



 a| 
Einen Qtree löschen
 a| 
`volume qtree delete`


NOTE: Dieser Befehl schlägt fehl, es sei denn, der Qtree ist leer oder das  `-force true` Flag verwendet wird.



 a| 
Ändern der UNIX-Berechtigungen eines Qtrees
 a| 
`volume qtree modify -unix-permissions`



 a| 
Die CIFS-Oplock-Einstellung eines Qtrees ändern
 a| 
`volume qtree oplocks`



 a| 
Die Sicherheitseinstellung eines Qtrees ändern
 a| 
`volume qtree security`



 a| 
Einen Qtree umbenennen
 a| 
`volume qtree rename`



 a| 
Statistiken eines Qtrees anzeigen
 a| 
`volume qtree statistics`



 a| 
Statistiken eines qtree zurücksetzen
 a| 
`volume qtree statistics -reset`

|===


[[extended-qtree-performance-monitoring]]
== Erweiterte Qtree Leistungsüberwachung

Ab ONTAP 9.16.1 kann über die ONTAP REST API auf die erweiterten Qtree-Überwachungsfunktionen zugegriffen werden, die Latenzmetriken und historische Statistiken umfassen.

Die ONTAP REST API umfasst mehrere Endpunkte im Zusammenhang mit qtrees. Vor ONTAP 9.16.1 konnten Kunden Echtzeitstatistiken für qtrees abrufen, darunter IO-Operationen pro Sekunde (IOPs) sowie den Durchsatz für Lese-, Schreib- und andere Operationen.

Die erweiterte Qtree-Leistungsüberwachung, die ab ONTAP 9.16.1 verfügbar ist, bietet die Möglichkeit, Latenzstatistiken in Echtzeit sowie IOPS und Durchsatz für NFSv3, NFSv4.0, NFSv4.1, NFSv4.2, pNFS (technisch ein Teil von NFSv4.1 und NFSv4.2) und CIFS zu überwachen. Es werden außerdem Statistiken gesammelt und archiviert, um die Anzeige historischer Leistungsdaten zu ermöglichen.

Diese erweiterte Überwachung bietet Speicheradministratoren einen tieferen Einblick in die Systemleistung. Diese Daten können verwendet werden, um stark ausgelastete Qtrees, potenzielle Engpässe und andere Bereiche zu identifizieren, wenn an der Verbesserung der Servicequalität gearbeitet wird. Die Möglichkeit, diese Metriken, einschließlich Trends über einen längeren Zeitraum, zu analysieren, ermöglicht fundiertere, datengestützte Entscheidungen.



[[operation-and-limitations]]
=== Funktionsweise und Einschränkungen

Vor der Verwendung der erweiterten qtree Leistungsüberwachungsfunktion in einer Produktionsumgebung sind verschiedene betriebliche Eigenschaften, einschließlich Einschränkungen, zu berücksichtigen.

.Neumontage erforderlich
Nach der Aktivierung der erweiterten qtree-Überwachung muss das betroffene Volume neu eingebunden werden, damit die Funktion aktiviert wird.

.Verfügbarkeit von Statistiken
Nach Aktivierung der erweiterten Leistungsüberwachung sind die statistischen Daten nicht sofort verfügbar. Dies umfasst IOPS, Durchsatz und Latenzstatistiken. Es kann bis zu fünf Minuten dauern, bis diese Daten für einen qtree angezeigt werden.

.Qtrees pro Cluster
Es ist möglich, die erweiterte Leistungsüberwachung für maximal 50.000 Qtrees in einem ONTAP Cluster zu aktivieren.



[[access-extended-metrics-using-the-ontap-rest-api]]
=== Erweiterte Metriken über die ONTAP REST API abrufen

Ab ONTAP 9.16.1 ist der Zugriff auf die erweiterte Qtree-Leistungsüberwachungsfunktion über die ONTAP REST API möglich. Die grundlegenden Funktionen fallen in mehrere Kategorien, wie unten beschrieben.

.Erweiterte Leistungsüberwachung aktivieren und deaktivieren
Sie können die Eigenschaft  `ext_performance_monitoring.enabled` am Endpunkt  `/api/storage/qtrees` aufrufen, um die erweiterte Überwachungsfunktion zu aktivieren oder zu deaktivieren. Die Methoden POST und PATCH stehen zur Verfügung, je nachdem, ob ein neuer Qtree erstellt oder ein vorhandener Qtree konfiguriert wird.

.Globale Überwachungsmetriken und Einstellungen abrufen
Dem  `/api/storage/qtrees` Endpoint wurden mehrere neue globale Eigenschaften hinzugefügt. Diese Felder können mit der GET-Methode abgerufen werden.

.Metriken für einen bestimmten Qtree abrufen
Sie können die GET-Methode am Endpunkt  `/api/storage/qtrees/{volume.uuid}/{id}/metrics` verwenden, um die neuen Statistiken und Metrikeigenschaften für einen bestimmten Qtree, wie er auf einem bestimmten Volume definiert ist, abzurufen.



[[upgrading-and-reverting]]
=== Aktualisierung und Zurücksetzung

Wenn Sie die Funktion in ONTAP 9.16.1 aktivieren, können Sie ohne Einschränkungen auf eine nachfolgende ONTAP-Version aktualisieren. Es sind jedoch zwei Szenarien zu berücksichtigen.

.Upgrade auf 9.16.1 und Umgang mit Clustern mit gemischten Versionen
Die erweiterte Leistungsüberwachungsfunktion kann nicht verwendet werden (d. h.,  `ext_performance_monitoring.enabled` kann nicht auf  `true` gesetzt werden), bis die effektive Clusterversion (ECV) des Clusters 9.16.1 erreicht ist.

.Zurücksetzen von 9.16.1
Wenn bei einem Qtree die Eigenschaft  `ext_performance_monitoring.enabled` auf  `true` gesetzt ist, ist ein Zurücksetzen von 9.16.1 auf 9.15.1 nicht zulässig. Der Rücksetzvorgang wird blockiert. Die empfohlene Vorgehensweise ist,  `ext_performance_monitoring.enabled` auf  `false` für alle Qtrees zu setzen, bevor auf eine frühere ONTAP Version zurückgesetzt wird.



[[learn-more]]
=== Mehr erfahren

Weitere Informationen zur ONTAP REST API, einschließlich  https://docs.netapp.com/us-en/ontap-automation/whats-new.html["Was ist neu bei der ONTAP REST API"^]aus der ONTAP Automation-Dokumentation. In der ONTAP Automation-Dokumentation finden sich ebenfalls Details zur ONTAP REST API https://docs.netapp.com/us-en/ontap-automation/reference/api_reference.html["Qtree Endpunkte"^].
