---
permalink: volumes/qtrees-partition-your-volumes-concept.html 
sidebar: sidebar 
keywords: volumes, volume partitioning, qtrees, flexvol volumes, performance, metrics, extended performance monitoring 
summary: Qtrees ermöglicht Ihnen, FlexVol Volumes in kleinere Segmente zu partitionieren, die individuell gemanagt werden können. Die durch qtrees aktivierte Volume-Partitionierung ermöglicht eine feinere Kontrolle bei der Storage-Administration nach Projekt, Benutzer oder Gruppe. Mit qtrees können Kontingente, Sicherheitsstil und CIFS-Oplocks besser gemanagt werden. 
---
= Qtrees und ONTAP FlexVol volume Partitionierung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Qtrees ermöglicht Ihnen, FlexVol Volumes in kleinere Segmente zu partitionieren, die individuell gemanagt werden können. Die durch qtrees aktivierte Volume-Partitionierung ermöglicht eine feinere Kontrolle bei der Storage-Administration nach Projekt, Benutzer oder Gruppe. Mit qtrees können Kontingente, Sicherheitsstil und CIFS-Oplocks besser gemanagt werden.


NOTE: ONTAP erstellt für jedes Volume mit dem Namen *qtree0* einen Standard-qtree. Wenn Sie keine Daten in einem bestimmten qtree ablegen, wird dieser in qtree0 platziert.



== Allgemeine Einschränkungen

Sie sollten sich der Einschränkungen von qtrees bewusst sein, bevor Sie diese in einer Produktionsumgebung verwenden. Überprüfen Sie auch<<Betrieb und Einschränkungen>>, wann Sie die erweiterte qtree Performance-Überwachungsfunktion verwenden.

* Qtree-Namen dürfen nicht mehr als 64 Zeichen enthalten.
* Bestimmte in den qtree-Namen verwendete Sonderzeichen wie Kommas und Leerzeichen, können mit anderen ONTAP-Funktionen in Verbindung stehen und sollten daher vermieden werden.
* Sie können Verzeichnisse nicht zwischen unterschiedlichen qtrees verschieben. Es können nur Dateien zwischen qtrees verschoben werden.
* Wenn Sie Shares auf qtree- und Volume-Ebene auf demselben FlexVol oder SCVMM Pool erstellen, werden die qtrees als Verzeichnisse auf der FlexVol-Freigabe angezeigt. Sie sollten darauf achten, sie nicht versehentlich zu löschen.




== Befehle zum Verwalten und Konfigurieren von qtrees

Qtrees können über die ONTAP CLI gemanagt und konfiguriert werden. Je nach gewünschtem Vorgang sollten Sie die folgenden Befehle zur Verwaltung von qtrees verwenden.

[NOTE]
====
Der Befehl `volume rehost` kann zum Ausfall anderer gleichzeitiger Administrationsvorgänge mit dem Ziel auf demselben Volume führen.

====
|===


| Ihr Ziel ist | Befehl 


 a| 
Erstellen Sie einen qtree
 a| 
`volume qtree create`



 a| 
Zeigt eine gefilterte Liste von qtrees an
 a| 
`volume qtree show`



 a| 
Löschen Sie einen qtree
 a| 
`volume qtree delete`


NOTE: Dieser Befehl schlägt fehl, es sei denn, der qtree ist leer oder das `-force true` Flag wird verwendet.



 a| 
Ändern Sie die UNIX-Berechtigungen eines qtree
 a| 
`volume qtree modify -unix-permissions`



 a| 
Ändern Sie die CIFS-Oplocks-Einstellung eines qtree
 a| 
`volume qtree oplocks`



 a| 
Ändern Sie die Sicherheitseinstellung eines qtree
 a| 
`volume qtree security`



 a| 
Benennen Sie einen qtree um
 a| 
`volume qtree rename`



 a| 
Zeigen Sie die Statistiken eines qtree an
 a| 
`volume qtree statistics`



 a| 
Zurücksetzen der Statistiken eines qtree
 a| 
`volume qtree statistics -reset`

|===


== Erweitertes qtree Performance-Monitoring

Ab ONTAP 9.16.1 haben Sie mit der ONTAP REST-API Zugriff auf die erweiterten qtree Monitoring-Funktionen, einschließlich Latenzmetriken und historischer Statistiken.

Die ONTAP REST-API enthält mehrere Endpunkte mit qtrees. Vor ONTAP 9.16.1 konnten Kunden auf Echtzeitstatistiken für qtrees zugreifen, einschließlich I/O-Operationen pro Sekunde (IOPS) sowie auf den Durchsatz für Lese-, Schreib- und andere Vorgänge.

Die ab ONTAP 9.16.1 verfügbare erweiterte qtree Performance-Überwachung erlaubt die Überwachung von Echtzeit-Latenzstatistiken sowie von IOPS und Durchsatz für NFSv3, NFSv4.0, NFSv4.1, NFSv4.2, pNFS (technisch ein Bestandteil von NFSv4.1 und NFSv4.2) und CIFS. Außerdem werden Statistiken erfasst und archiviert, um die Anzeige historischer Leistungsdaten zu ermöglichen.

Durch dieses erweiterte Monitoring erhalten Storage-Administratoren einen besseren Einblick in die System-Performance. Mithilfe dieser Daten können Sie stark verwendete qtrees, potenzielle Engpässe und andere Bereiche identifizieren, in denen Ihre Arbeit zur Verbesserung der Servicequalität beitragen. Durch die Möglichkeit, diese Kennzahlen, einschließlich der Trends über einen längeren Zeitraum, zu analysieren, können Sie fundiertere, datengetriebene Entscheidungen treffen.



=== Betrieb und Einschränkungen

Es gibt verschiedene betriebliche Merkmale, einschließlich Einschränkungen. Diese sollten Sie vor Einsatz der erweiterten qtree Performance-Überwachungsfunktion in einer Produktionsumgebung in Betracht ziehen.

.Neueinbindung erforderlich
Nach Aktivierung der erweiterten Überwachung durch qtree müssen Sie das betroffene Volume neu einbinden, um die Funktion zu aktivieren.

.Verfügbarkeit von Statistiken
Nach Aktivierung der erweiterten Leistungsüberwachung stehen die statistischen Daten nicht sofort zur Verfügung. Dies schließt Statistiken zu IOPS, Durchsatz und Latenz ein. Es kann bis zu fünf Minuten dauern, bis diese Daten für einen qtree angezeigt werden.

.Qtrees pro Cluster
Sie können die erweiterte Performance-Überwachung für maximal 50,000 qtrees in einem ONTAP Cluster aktivieren.



=== Zugriff auf erweiterte Metriken mithilfe der ONTAP REST-API

Ab ONTAP 9.16.1 können Sie über die ONTAP REST API auf die erweiterte qtree Performance-Monitoring-Funktion zugreifen. Die grundlegenden Funktionen lassen sich wie unten beschrieben in mehrere Kategorien einteilen.

.Aktivieren und deaktivieren Sie die erweiterte Leistungsüberwachung
Sie können auf die Eigenschaft am Endpunkt `/api/storage/qtrees` zugreifen `ext_performance_monitoring.enabled`, um die erweiterte Überwachungsfunktion zu aktivieren oder zu deaktivieren. Die POST- und PATCH-Methoden sind verfügbar, je nachdem, ob Sie einen neuen qtree erstellen oder einen vorhandenen qtree konfigurieren.

.Rufen Sie die globalen Überwachungsmetriken und -Einstellungen ab
Dem Endpunkt wurden mehrere neue globale Eigenschaften hinzugefügt `/api/storage/qtrees`. Sie können diese Felder mit der GET-Methode abrufen.

.Abrufen von Kennzahlen für einen bestimmten qtree
Sie können die GET-Methode am Endpunkt verwenden `/api/storage/qtrees/{volume.uuid}/{id}/metrics`, um die neuen Statistiken und Kennzahleneigenschaften für einen bestimmten qtree abzurufen, wie er für ein bestimmtes Volume definiert ist.



=== Upgrade und Zurücksetzen

Wenn Sie die Funktion in ONTAP 9.16.1 aktivieren, können Sie ohne Einschränkungen auf eine nachfolgende ONTAP-Version aktualisieren. Es sind jedoch zwei Szenarien zu berücksichtigen.

.Upgrade auf 9.16.1 und Handhabung von Clustern mit gemischten Versionen
Die erweiterte Leistungsüberwachungsfunktion kann nicht verwendet werden (d.h. `ext_performance_monitoring.enabled` kann nicht auf eingestellt `true` werden), bis die effektive Clusterversion (ECV) des Clusters bei 9.16.1 ist.

.Zurück von 9.16.1
Wenn die Eigenschaft einer qtrees `ext_performance_monitoring.enabled` auf festgelegt ist, ist ein Zurücksetzen auf `true` 9.15.1 von 9.16.1 nicht zulässig. Der Rückkehrvorgang ist blockiert. Als Best Practice empfiehlt es sich, die Einstellung `ext_performance_monitoring.enabled` für alle qtrees zu verwenden, bevor auf `false` eine ältere ONTAP Version zurückgesetzt wird.



=== Weitere Informationen .

In der Dokumentation zur ONTAP-Automatisierung finden Sie unter anderem https://docs.netapp.com/us-en/ontap-automation/whats-new.html["Neuerungen bei der ONTAP REST API"^] weitere Informationen zur ONTAP REST-API. In der Dokumentation von ONTAP https://docs.netapp.com/us-en/ontap-automation/reference/api_reference.html["API-Referenz"^] finden Sie weitere Details zu den ONTAP REST API qtree Endpunkten.
