---
permalink: volumes/quotas-multiple-users-concept.html 
sidebar: sidebar 
keywords: how quotas work, with multiple users 
summary: Wenn Sie mehrere Benutzer in das gleiche Kontingentziel setzen, werden die durch dieses Kontingent definierten Kontingentgrenzen nicht auf jeden einzelnen Benutzer angewendet; in diesem Fall werden die Kontingentnutzer von allen Benutzern geteilt, die im Kontingentnutzer aufgelistet sind. 
---
= Wie Kontingente mit mehreren Benutzern funktionieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie mehrere Benutzer in das gleiche Kontingentziel setzen, werden die durch dieses Kontingent definierten Kontingentgrenzen nicht auf jeden einzelnen Benutzer angewendet; in diesem Fall werden die Kontingentnutzer von allen Benutzern geteilt, die im Kontingentnutzer aufgelistet sind.

Im Gegensatz zu den Befehlen zum Verwalten von Objekten wie Volumes und qtrees können Sie kein Kontingentnutzer umbenennen, einschließlich einer Benutzerkontingente. Das bedeutet, dass Sie nach der Definition einer Multi-User-Quote die Benutzer im Kontingentnutzer nicht mehr ändern können, und Sie können keine Benutzer zu einem Ziel hinzufügen oder aus einem Ziel entfernen. Wenn Sie einen Benutzer aus einem Multi-User-Kontingent hinzufügen oder entfernen möchten, muss das Kontingent gelöscht werden, das diesen Benutzer enthält, und eine neue Quota-Regel mit dem Satz von Benutzern im festgelegten Ziel.

[NOTE]
====
Wenn Sie separate Benutzerkontingente zu einem Kontingent für mehrere Benutzer kombinieren, können Sie die Änderung durch Ändern der Größe der Kontingente aktivieren. Wenn Sie jedoch Benutzer von einem Quota-Ziel mit mehreren Benutzern entfernen oder einem Ziel, das bereits mehrere Benutzer hat, Benutzer hinzufügen möchten, müssen Sie Quoten neu initialisieren, bevor die Änderung wirksam wird.

====
Im folgenden Beispiel sind im Quoteneintrag zwei Benutzer aufgeführt. Die beiden Benutzer können bis zu 80 MB Speicherplatz zusammen verwenden. Wenn man 75 MB verwendet, dann kann der andere nur 5 MB verwenden.

[listing]
----

#Quota       target type    disk files thold sdisk sfile
#----------  ----           ---- ----- ----- ----- -----
jsmith,chen  user@/vol/vol1 80M
----