---
permalink: volumes/quotas-activated-concept.html 
sidebar: sidebar 
keywords: quotas, how quotas are activated, quota activation 
summary: Neue Quoten und Änderungen an bestehenden Quoten müssen aktiviert werden, um wirksam zu werden. Die Aktivierung erfolgt auf Lautstärkeebene. Wenn Sie wissen, wie die Quota-Aktivierung funktioniert, können Sie Ihre Kontingente mit weniger Unterbrechungen verwalten. 
---
= Übersicht über die Aktivierung von Quotas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Neue Quoten und Änderungen an bestehenden Quoten müssen aktiviert werden, um wirksam zu werden. Die Aktivierung erfolgt auf Lautstärkeebene. Wenn Sie wissen, wie die Quota-Aktivierung funktioniert, können Sie Ihre Kontingente mit weniger Unterbrechungen verwalten.

Quoten werden entweder durch _Initialisierung_ (Aktivieren) oder durch _Resizing_ aktiviert. Quoten zu deaktivieren und wieder zu aktivieren wird neu initialisiert.

Die Dauer des Aktivierungsprozesses und seine Auswirkungen auf die Quotendurchsetzung sind von der Art der Aktivierung abhängig:

* Der Initialisierungsprozess umfasst zwei Teile: A `quota on` Job und Quota-Scan des gesamten Dateisystems des Volumes Der Scan beginnt nach dem `quota on` Der Job wurde erfolgreich abgeschlossen. Der Kontingentscan kann einige Zeit in Anspruch nehmen; je mehr Dateien auf dem Volume vorliegen, desto länger dauert er. Bis der Scan abgeschlossen ist, ist die Quotenaktivierung nicht abgeschlossen und die Quoten werden nicht durchgesetzt.
* Die Größenänderung erfordert nur a `quota resize` Job: Die Größenänderung dauert weniger Zeit als eine Quota-Initialisierung, da kein Quota-Scan erforderlich ist. Während eines Anpassungsprozesses werden Quotas weiterhin durchgesetzt.


Standardmäßig wird der verwendet `quota on` Und `quota resize` Jobs laufen im Hintergrund, wodurch Sie andere Befehle gleichzeitig verwenden können.

Fehler und Warnungen aus dem Aktivierungsprozess werden an das Event-Management-System gesendet. Wenn Sie den verwenden `-foreground` Parameter mit `volume quota on` Oder `volume quota resize` Befehle: Der Befehl wird erst nach Abschluss des Jobs zurückgegeben. Dies ist hilfreich, wenn Sie ein Skript erneut initialisieren. Um Fehler und Warnungen später anzuzeigen, können Sie den verwenden `volume quota show` Befehl mit dem `-instance` Parameter.

Die Quotenaktivierung bleibt bei Anhalten und Neustarts erhalten. Der Prozess der Kontingentaktivierung hat keine Auswirkung auf die Verfügbarkeit der Storage-Systemdaten.
