---
permalink: volumes/quotas-applied-users-multiple-ids-concept.html 
sidebar: sidebar 
keywords: how, quotas are applied, users, multiple ids 
summary: Ein Benutzer kann durch mehrere IDs repräsentiert werden. Ein einzelnes Benutzerkontingent für einen solchen Benutzer kann festgelegt werden, indem eine Liste von IDs als Kontingentziel angegeben wird. Eine Datei, die einer dieser IDs gehört, unterliegt den Beschränkungen des Benutzerkontingents. 
---
= Erfahren Sie, wie ONTAP Kontingente auf Benutzer mit mehreren IDs angewendet werden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Benutzer kann durch mehrere IDs repräsentiert werden. Ein einzelnes Benutzerkontingent für einen solchen Benutzer kann festgelegt werden, indem eine Liste von IDs als Kontingentziel angegeben wird. Eine Datei, die einer dieser IDs gehört, unterliegt den Beschränkungen des Benutzerkontingents.

Angenommen, ein Benutzer besitzt die UNIX-UID `20` und die Windows-IDs `corp\john_smith` und `engineering\jsmith`. Für diesen Benutzer kann ein Kontingent angegeben werden, bei dem das Kontingentziel eine Liste der UID und der Windows-IDs ist. Wenn dieser Benutzer auf das Speichersystem schreibt, gilt das angegebene Kontingent, unabhängig davon, ob der Schreibvorgang von UID `20`, `corp\john_smith` oder `engineering\jsmith` ausgeht.

Beachten Sie, dass separate Kontingentregeln als separate Ziele betrachtet werden, selbst wenn die IDs demselben Benutzer angehören. Beispielsweise kann für denselben Benutzer ein Kontingent festgelegt werden, das UID `20` auf 1 GB Speicherplatz beschränkt, und ein weiteres Kontingent, das corp\john_smith auf 2 GB Speicherplatz beschränkt, obwohl beide IDs denselben Benutzer repräsentieren. ONTAP wendet Kontingente auf UID `20` und `corp\john_smith` separat an. In diesem Fall werden keine Beschränkungen auf `engineering\jsmith` angewendet, obwohl für die anderen IDs desselben Benutzers Beschränkungen gelten.

.Verwandte Informationen
* link:../volumes/quotas-applied-concept.html["Wie Quoten angewendet werden"]
* link:../volumes/quotas-applied-root-user-concept.html["Wie Kontingente auf den Root-Benutzer angewendet werden"]

