---
permalink: volumes/recommendations-moving-concept.html 
sidebar: sidebar 
keywords: considerations, recommendations, moving volumes, flexclone volume, metroCluster configuration 
summary: Bei der Verschiebung eines Volume müssen Sie auf verschiedene Aspekte achten und entsprechende Empfehlungen aussprechen. Diese richten sich sowohl nach dem Volume, das Sie verschieben, als auch nach der Systemkonfiguration wie MetroCluster. Sie sollten alle relevanten Probleme verstehen, bevor Sie ein Volume verschieben. 
---
= Überlegungen und Empfehlungen beim Verschieben von Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Verschiebung eines Volume müssen Sie auf verschiedene Aspekte achten und entsprechende Empfehlungen aussprechen. Diese richten sich sowohl nach dem Volume, das Sie verschieben, als auch nach der Systemkonfiguration wie MetroCluster. Sie sollten alle relevanten Probleme verstehen, bevor Sie ein Volume verschieben.



== Allgemeine Überlegungen und Empfehlungen

* Wenn Sie die Versionsfamilie für einen Cluster aktualisieren, verschieben Sie ein Volume erst, nachdem Sie alle Nodes im Cluster aktualisiert haben.
+
Diese Empfehlung verhindert, dass Sie versehentlich versuchen, ein Volume von einer neueren Versionsfamilie auf eine ältere Versionsfamilie zu verschieben.

* Das Quell-Volume muss konsistent sein.
* Wenn Sie einer oder mehreren Aggregaten der zugehörigen Storage Virtual Machine (SVM) zugewiesen haben, muss das Zielaggregat eine der zugewiesenen Aggregate sein.
* Sie sollten ein Volume nur auf eine neuere ONTAP-Version verschieben.
* Ein Volume kann nicht in ein oder aus einem übernhast CFO Aggregat verschoben werden.
* Wenn auf einem Volume mit LUNs vor dem Verschieben nicht „NV-Fehler“ aktiviert ist, wird nach dem Verschieben des Volumes die Option „NV-Fehler“ aktiviert.
* Sie können ein Volume von einem Flash Pool Aggregat zu einem anderen Flash Pool Aggregat verschieben.
+
** Die Caching-Richtlinien dieses Volumes werden ebenfalls verschoben.
** Diese Verschiebung kann sich auf die Volume-Performance auswirken.


* Sie können Volumes zwischen einem Flash Pool Aggregat und einem nicht-Flash Pool Aggregat verschieben.
+
** Wenn Sie ein Volume von einem Flash Pool Aggregat zu einem anderen Aggregat ohne Flash Pool verschieben, zeigt ONTAP eine Warnmeldung an, dass die Verschiebung sich möglicherweise auf die Volume Performance auswirken wird und fragt, ob Sie fortfahren möchten.
** Wenn Sie ein Volume von einem nicht-Flash Pool Aggregat zu einem Flash Pool Aggregat verschieben, weist ONTAP die `auto` Caching-Richtlinie zu.


* Volumes verfügen über die Data-at-Rest-Sicherung des Aggregats, auf dem sie sich befinden. Wenn Sie ein Volume von einem Aggregat aus NSE-Laufwerken auf eines ohne diese verschieben, bietet das Volume keine Sicherung der Daten im Ruhezustand mehr.
* Wenn Sie FabricPool -optimierte Volumes von ONTAP 9.13.1 oder früher auf ONTAP 9.15.1 oder höher verschieben, lesen Sie dielink:https://kb.netapp.com/on-prem/ontap/Ontap_OS/FS_Issues/CONTAP-307878["NetApp Knowledge Base: CONTAP-307878 – Unerwarteter Neustart während der optimierten FabricPool -Volume-Verschiebung, wenn der Quell ONTAP kleiner als 9.14.1 und das Ziel größer als 9.14.1 ist"^] .
* Ab ONTAP 9.15.1 kann das Verschieben von Datenträgern von einem A400-System auf ein A70-, A90- oder A1K-System zu erhöhten Leseverzögerungen führen. Einzelheiten und empfohlene Maßnahmen finden Sie unter link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/FS_Issues/CONTAP-556247["NetApp Knowledge Base: CONTAP-556247 – Langsame Komprimierung/Dekomprimierung von Volumes nach der Migration von A400 auf A70, A90 und A1K"^]Die




== Überlegungen und Empfehlungen zu FlexClone Volumes

* FlexClone Volumes können nicht offline sein, wenn sie verschoben werden.
* Sie können FlexClone Volumes von einem Aggregat zu einem anderen Aggregat im selben Node oder zu einem anderen Node in derselben SVM verschieben, ohne den `vol clone split start` Befehl zu starten.
+
Durch Initiieren eines Volume-Verschiebungsvorgangs auf einem FlexClone Volume wird das Klon-Volume während der Verschiebung in ein anderes Aggregat aufgeteilt. Nach Abschluss der Verschiebung des Volume wird das verschobene Volume nicht mehr als ein Klon angezeigt, sondern es erscheint als unabhängiges Volume ohne eine Klonbeziehung zu dem vorherigen übergeordneten Volume.

* FlexClone Volume Snapshots gehen nach der Verschiebung eines Klons nicht verloren.
* Sie können übergeordnete FlexClone Volumes von einem Aggregat zu einem anderen Aggregat verschieben.
+
Wenn Sie ein übergeordnetes FlexClone Volume verschieben, bleibt ein temporäres Volume hinter dem, das als übergeordnetes Volume für alle FlexClone Volumes fungiert. Auf dem temporären Volume sind keine Vorgänge zulässig, ausgenommen sie offline zu schalten oder zu löschen. Nachdem alle FlexClone Volumes geteilt oder zerstört wurden, wird das temporäre Volume automatisch bereinigt.

* Nach dem Verschieben eines Child-Volume von FlexClone ist das Volume kein FlexClone Volume mehr.
* FlexClone Move-Vorgänge schließen sich gegenseitig aus den FlexClone Kopien oder Split-Vorgängen ab.
* Wenn ein Klon-Splitting-Vorgang läuft, kann das Verschieben eines Volumes fehlschlagen.
+
Sie sollten ein Volume nicht verschieben, bis die Klonabtrennung abgeschlossen ist.





== Überlegungen und Empfehlungen zu MetroCluster

* Wenn während einer Verschiebung eines Volumes in einer MetroCluster-Konfiguration ein temporäres Volume auf dem Zielaggregat auf dem Quellcluster erstellt wird, wird ein Datensatz des temporären Volumes erstellt, das dem Volume in der gespiegelten Ressource entspricht, aber nicht assimiliert, wird das Aggregat auch auf dem verbleibenden Cluster erstellt.
* Wenn vor der Umstellung eine MetroCluster-Umschaltung stattfindet, verfügt das Ziel-Volume über einen Datensatz und ist ein temporäres Volume (ein Volume vom Typ TMP).
+
Verschieben eines Jobs startet im verbleibenden Cluster (Disaster Recovery) neu, meldet einen Fehler und bereinigt alle bewegungsbezogenen Elemente einschließlich des temporären Volumes. In jedem Fall, in dem eine Bereinigung nicht korrekt durchgeführt werden kann, wird ein EMS generiert, der den Systemadministrator benachrichtigt, die erforderliche Bereinigung durchzuführen.

* Wenn eine MetroCluster-Umschaltung stattfindet, nachdem die Umstellungsphase gestartet wurde, aber bevor der Ververschiebungsauftrag abgeschlossen wurde (das heißt, die Verschiebung hat eine Phase erreicht, in der das Cluster aktualisiert werden kann, um auf das Zielaggregat zu verweisen), wird der Ververschiebungsauftrag auf dem Survivor (Disaster Recovery) neu gestartet. Cluster wird ausgeführt und wird abgeschlossen.
+
Alle verschiebungsbezogenen Elemente werden einschließlich des temporären Volumens (Originalquelle) bereinigt. In jedem Fall, in dem eine Bereinigung nicht korrekt durchgeführt werden kann, wird ein EMS generiert, der den Systemadministrator benachrichtigt, die erforderliche Bereinigung durchzuführen.

* Es sind weder erzwungene noch nicht erzwungene MetroCluster-Switchbacks zulässig, wenn Volume-Vermittlungsprozesse zum Switch-Standort ausgeführt werden.
+
Switchbacks werden nicht blockiert, wenn Volume-Verschiebungen von lokalen Volumes zum noch aktiven Standort erfolgen.

* Nicht erzwungene MetroCluster-Switchover werden blockiert, aber erzwungene MetroCluster-Switchover werden nicht blockiert, wenn derzeit Volume-Verschiebungen durchgeführt werden.

