---
permalink: volumes/rehost-smb-task.html 
sidebar: sidebar 
keywords: rehost, cifs volumes, smb 
summary: Ein Volume, das Daten über das SMB-Protokoll bereitstellt, kann neu gehostet werden. 
---
= Rehost eines ONTAP SMB-Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Volume, das Daten über das SMB-Protokoll bereitstellt, neu hosten. Damit Clients nach dem Rehosting weiterhin auf die Daten zugreifen können, müssen Richtlinien und die zugehörigen Regeln manuell konfiguriert werden.

.Über diese Aufgabe
* Rehosting ist ein störender Vorgang.
* Falls der Rehosting-Vorgang fehlschlägt, ist es möglicherweise erforderlich, die Volume-Richtlinien und die zugehörigen Regeln auf dem Quellvolume neu zu konfigurieren.
* Wenn sich die Active Directory-Domänen der Quell-SVM und der Ziel-SVM unterscheiden, könnte der Zugriff auf die Objekte auf dem Volume verloren gehen.
* Ab ONTAP 9.8 wird das Rehosting eines Volumes mit NetApp Volume Encryption (NVE) unterstützt. Bei Verwendung eines integrierten Schlüsselmanagers werden die verschlüsselten Metadaten während des Rehosting-Vorgangs geändert. Benutzerdaten werden nicht verändert.
+
Wenn Sie ONTAP 9.8 oder eine frühere Version verwenden, muss das Volume vor der Durchführung des Rehost-Vorgangs entschlüsselt werden.



* Wenn die Quell-SVM lokale Benutzer und Gruppen besitzt, sind die festgelegten Berechtigungen für die Dateien und Verzeichnisse (ACLs) nach der Volume-Rehost-Operation nicht mehr wirksam.
+
Das Gleiche gilt für Audit-ACLs (SACLs)

* Nach dem Rehosting-Vorgang gehen die folgenden Volume-Richtlinien, Richtlinienregeln und Konfigurationen des Quellvolumes verloren und müssen auf dem rehosteten Volume manuell neu konfiguriert werden:
+
** Exportrichtlinien für Volumes und Qtrees
** Antivirus-Richtlinien
** Effizienzrichtlinie
** Richtlinien zur Dienstqualität (QoS)
** Snapshot Richtlinien
** Quotenregeln
** ns-switch und Name-Services-Konfiguration Exportrichtlinie und -regeln
** Benutzer- und Gruppen-IDs




.Bevor Sie beginnen
* Das Volume muss online sein.
* Volume-Management-Operationen wie Volume-Verschiebung oder LUN-Verschiebung dürfen nicht ausgeführt werden.
* Der Datenzugriff auf das Volume, das neu gehostet wird, muss gestoppt werden.
* Die ns-switch- und Name-Services-Konfiguration der Ziel-SVM muss so konfiguriert sein, dass der Datenzugriff auf das Rehosting-Volume unterstützt wird.
* Die Quell-SVM und die Ziel-SVM müssen dieselbe Active Directory und RealmDNS-Domäne haben.
* Die Benutzer-ID und die Gruppen-ID des Volumes müssen entweder in der Ziel-SVM verfügbar sein oder auf dem Hosting-Volume geändert werden.
+

NOTE: Wenn lokale Benutzer und Gruppen konfiguriert sind und sich auf diesem Volume Dateien und Verzeichnisse mit Berechtigungen für diese Benutzer oder Gruppen befinden, sind diese Berechtigungen nicht mehr wirksam.



.Schritte
. Informationen über die CIFS-Freigaben werden erfasst, damit bei einem Fehler beim Volume-Rehosting keine Informationen über die CIFS-Freigaben verloren gehen.
. Das Volume vom übergeordneten Volume trennen:
+
`volume unmount`

. Zur erweiterten Berechtigungsstufe wechseln:
+
`set -privilege advanced`

. Das Volume auf der Ziel-SVM neu hosten:
+
`volume rehost -vserver _source_svm_ -volume _vol_name_ -destination-vserver _destination_svm_`

. Das Volume wird unter dem entsprechenden Verbindungspfad in der Ziel-SVM eingebunden:
+
`volume mount`

. CIFS-Freigaben für das neu gehostete Volume erstellen:
+
`vserver cifs share create`

. Wenn sich die DNS-Domänen zwischen Quell-SVM und Ziel-SVM unterscheiden, sollten neue Benutzer und Gruppen erstellt werden.
. Der CIFS-Client wird mit den neuen Ziel-SVM-LIFs und dem Verbindungspfad zum neu gehosteten Volume aktualisiert.


.Nachdem Sie fertig sind
Die Richtlinien und die zugehörigen Regeln auf dem neu gehosteten Volume müssen manuell neu konfiguriert werden.

https://docs.netapp.com/us-en/ontap-system-manager-classic/smb-config/index.html["SMB-Konfiguration"]

https://docs.netapp.com/us-en/ontap-system-manager-classic/nas-multiprotocol-config/index.html["SMB und NFS Multiprotokollkonfiguration"]
