---
permalink: volumes/rehost-volume-another-svm-task.html 
sidebar: sidebar 
keywords: rehost, volume, from one SVM to another SVM 
summary: 'Mit Volume Rehosting können Sie NAS- oder SAN-Volumes von einer Storage Virtual Machine (SVM, früher als Vserver bezeichnet) einer anderen SVM zuweisen, ohne dass eine SnapMirror Kopie erforderlich ist. Die Verfahren zum Rehosting des Volumes hängen vom Protokolltyp und vom Volume-Typ ab. Volume Rehosting ist ein disruptiver Betrieb für Datenzugriff und Volume Management.' 
---
= Erneutes Hosten eines Volumes von einer SVM zu einer anderen SVM Übersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit Volume Rehosting können Sie NAS- oder SAN-Volumes von einer Storage Virtual Machine (SVM, früher als Vserver bezeichnet) einer anderen SVM zuweisen, ohne dass eine SnapMirror Kopie erforderlich ist. Die Verfahren zum Rehosting des Volumes hängen vom Protokolltyp und vom Volume-Typ ab. Volume Rehosting ist ein disruptiver Betrieb für Datenzugriff und Volume Management.

.Was Sie benötigen
Es müssen mehrere Bedingungen erfüllt sein, bevor Sie ein Volume von einer SVM auf eine andere neu hosten können:

* Das Volume muss sich online sein.
* Protokolle: SAN oder NAS
+
Beim NAS-Protokoll muss das Volume abgehängt werden.

* Wenn sich das Volume in einer SnapMirror Beziehung befindet, muss die Beziehung vor dem erneuten Host des Volumes entweder gelöscht oder beschädigt werden.
+
Sie können die SnapMirror Beziehung neu synchronisieren, nachdem der Datenträger erneut gehostet wird.


