---
permalink: volumes/reinitialize-quotas-after-changes-task.html 
sidebar: sidebar 
keywords: reinitialize, quotas, after making, extensive, changes 
summary: Nachdem Sie umfangreiche Änderungen an bestehenden Quota-Definitionen vorgenommen haben, müssen Sie die Quotas für alle betroffenen Volumes neu initialisieren. 
---
= Quoten nach umfangreichen Änderungen neu initialisieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie umfangreiche Änderungen an bestehenden Quota-Definitionen vorgenommen haben, müssen Sie die Quotas für alle betroffenen Volumes neu initialisieren. Ein Beispiel für diese Art von Änderung ist das Hinzufügen oder Löschen von Quotas für Ziele, die keine erzwungenen Quotas haben.

.Über diese Aufgabe
Sie verfügen über eine Storage Virtual Machine (SVM) mit erzwungenen Kontingenten und Sie möchten Änderungen vornehmen, die eine vollständige Neuinitialisierung der Kontingente erfordern.

.Schritte
. Verwenden Sie den `vserver show` Befehl mit dem `-instance` Parameter, um den Namen der Richtlinie zu bestimmen, die derzeit der SVM zugewiesen ist.
. Ändern Sie die Kontingentregeln, indem Sie eine der folgenden Aktionen ausführen:
+
[cols="2*"]
|===
| Ihr Ziel ist | Dann... 


 a| 
Erstellen neuer Kontingentregeln
 a| 
Verwenden Sie den `volume quota policy rule create` Befehl



 a| 
Ändern Sie die Einstellungen vorhandener Quotenregeln
 a| 
Verwenden Sie den `volume quota policy rule modify` Befehl



 a| 
Vorhandene Kontingentregeln löschen
 a| 
Verwenden Sie den `volume quota policy rule delete` Befehl

|===
.  `volume quota policy rule show`Überprüfen Sie mit dem Befehl, ob die Quota-Regeln ordnungsgemäß konfiguriert sind.
. Initialisieren Sie Quoten für jedes Volumen, wo Sie Quoten geändert haben, indem Sie Quoten deaktivieren und dann Quoten für diese Volumen aktivieren.
+
.. Verwenden Sie den `volume quota off` Befehl für jedes betroffene Volume, um Kontingente für dieses Volume zu deaktivieren.
.. Verwenden Sie den `volume quota on` Befehl für jedes betroffene Volume, um Quoten für dieses Volume zu aktivieren.
+
[NOTE]
====
Sie müssen für jedes betroffene Volume ca. fünf Minuten warten, bevor Sie die Quoten erneut aktivieren. Der Versuch, sie fast unmittelbar nach Ausführung des `volume quota off` Befehls zu aktivieren, kann zu Fehlern führen.

Alternativ können Sie die Befehle ausführen, um die Quoten für ein Volume von dem Node, der das jeweilige Volume enthält, neu zu initialisieren.

====
+
Sie können den Initialisierungsprozess auf eine der folgenden Arten überwachen:

+
*** Wenn Sie den `volume quota on` Befehl verwenden, können Sie den `-foreground` Parameter hinzufügen, um die Quote für den Job im Vordergrund auszuführen. (Der Job wird standardmäßig im Hintergrund ausgeführt.)
+
Wenn der Job im Hintergrund ausgeführt wird, können Sie den Fortschritt mit dem `job show` Befehl überwachen.

*** Sie können den `volume quota show` Befehl verwenden, um den Status der Kontingentinitialisierung zu überwachen.




.  `volume quota show -instance`Überprüfen Sie mit dem Befehl auf Initialisierungsfehler, z. B. Quota-Regeln, die nicht initialisiert werden konnten.
. Verwenden Sie den `volume quota report` Befehl, um einen Quota-Bericht anzuzeigen, damit Sie sicherstellen können, dass die erzwungenen Quotas Ihren Erwartungen entsprechen.

