---
permalink: volumes/resizing-concept.html 
sidebar: sidebar 
keywords: when to, use, resizing 
summary: Die Quota-Größenänderung ist schneller als die Quota-Initialisierung, hat aber Einschränkungen. 
---
= Wissen, wann die Größe verwendet werden soll
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Größenänderung von Quota ist eine nützliche ONTAP-Funktion. Und da die Größenänderung schneller als die Quota-Initialisierung ist, sollten Sie die Größenänderung verwenden, wann immer dies möglich ist. Es gibt jedoch ein paar Einschränkungen, die Sie beachten müssen.

Die Größenänderung funktioniert nur für bestimmte Arten von Quotenänderungen. Sie können die Größe der Kontingente ändern, wenn Sie die folgenden Arten von Änderungen an den Kontingentregeln vornehmen:

* Ändern einer bestehenden Quote
+
Ändern beispielsweise die Grenzen eines vorhandenen Kontingents.

* Hinzufügen einer Quote für ein Kontingentnutzer, für das ein Standardkontingent oder ein Standard-Tracking-Quota vorhanden ist.
* Löschen einer Quote, für die ein Standard-Quota- oder Standard-Tracking-Quota-Eintrag angegeben ist.
* Werden verschiedene Benutzerkontingente zu einem Benutzerkontingent kombiniert.


[NOTE]
====
Nachdem Sie umfangreiche Quotenänderungen vorgenommen haben, sollten Sie eine vollständige Neuinitialisierung durchführen, um sicherzustellen, dass alle Änderungen wirksam werden.

====
[NOTE]
====
Wenn Sie versuchen, die Größe zu ändern und nicht alle Änderungen des Kontingents durch die Größenänderung übernommen werden können, gibt ONTAP eine Warnung aus. Sie können aus dem Kontingentbericht ermitteln, ob Ihr Storage-System die Plattenauslastung für einen bestimmten Benutzer, eine Gruppe oder einen bestimmten qtree verfolgt. Wenn Sie eine Quote im Quota-Bericht sehen, bedeutet dies, dass das Storage-System den Festplattenspeicher und die Anzahl der Dateien im Besitz des Kontingents verfolgt.

====
.Beispiel für Änderungen an Kontingenten, die durch die Anpassung wirksam werden können
Einige Änderungen der Kontingentregel können durch Ändern der Größe wirksam werden. Folgende Kontingente sollten berücksichtigt werden:

[listing]
----

#Quota Target type             disk  files thold sdisk sfile
#------------ ----             ----  ----- ----- ----- -----
*             user@/vol/vol2    50M   15K
*             group@/vol/vol2  750M   85K
*             tree@/vol/vol2      -     -
jdoe          user@/vol/vol2/  100M   75K
kbuck         user@/vol/vol2/  100M   75K
----
Angenommen, Sie nehmen die folgenden Änderungen vor:

* Erhöhen Sie die Anzahl der Dateien für das Standardbenutzerziel.
* Fügen Sie ein neues Benutzerkontingent für einen neuen Benutzer, boris, hinzu, der mehr Datenträgerlimit benötigt als das Standardbenutzerkontingent.
* Löschen Sie den expliziten Quota-Eintrag des kbuck-Benutzers; der neue Benutzer benötigt jetzt nur die standardmäßigen Quota-Limits.


Diese Änderungen führen zu folgenden Quoten:

[listing]
----

#Quota Target type             disk  files thold sdisk sfile
#------------ ----             ----  ----- ----- ----- -----
*             user@/vol/vol2    50M   25K
*             group@/vol/vol2  750M   85K
*             tree@/vol/vol2      -     -
jdoe          user@/vol/vol2/  100M   75K
boris         user@/vol/vol2/  100M   75K
----
Die Größenänderung aktiviert alle Änderungen; eine vollständige Neuinitialisierung der Quote ist nicht erforderlich.
