---
permalink: volumes/resume-efficiency-operation-checkpoint-task.html 
sidebar: sidebar 
keywords: resume, halted, efficiency, operation 
summary: Wenn ein Effizienzvorgang vom System unterbrochen wird, kann der Effizienzvorgang an derselben Stelle fortgesetzt werden. 
---
= Einen angehaltenen ONTAP-Effizienzvorgang fortsetzen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wird ein Effizienzvorgang aufgrund eines Systemstillstands, einer Systemstörung oder eines Neustarts unterbrochen, kann der Effizienzvorgang an derselben Stelle fortgesetzt werden, an der er unterbrochen wurde. Dies trägt dazu bei, Zeit und Ressourcen zu sparen, da der Vorgang nicht von Anfang an neu gestartet werden muss.

.Über diese Aufgabe
Wenn Sie für das Volume nur die Deduplizierung aktiviert haben, wird die Deduplizierung auf die Daten angewendet. Wenn Sie sowohl die Deduplizierung als auch die Datenkomprimierung für ein Volume aktiviert haben, wird zuerst die Datenkomprimierung und anschließend die Deduplizierung ausgeführt.

Die Details des Prüfpunkts für ein Volume lassen sich mit dem  `volume efficiency show` Befehl anzeigen. Weitere Informationen zu  `volume efficiency show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-show.html["ONTAP-Befehlsreferenz"^].

Standardmäßig werden Effizienzoperationen ab einem Checkpoint fortgesetzt. Ist der Checkpoint einer vorherigen Effizienzoperation (der Phase, in der der  `volume efficiency start``-scan-old-data` Befehl ausgeführt wird) jedoch älter als 24 Stunden, wird die Effizienzoperation nicht automatisch ab dem vorherigen Checkpoint fortgesetzt. In diesem Fall beginnt die Effizienzoperation von vorn. Wenn bekannt ist, dass seit dem letzten Scan keine wesentlichen Änderungen am Volume vorgenommen wurden, kann die Fortsetzung ab dem vorherigen Checkpoint mithilfe der  `-use-checkpoint` Option erzwungen werden.

.Schritte
. Verwenden Sie den  `volume efficiency start` Befehl mit der  `-use-checkpoint` Option, um einen Effizienzvorgang fortzusetzen.
+
Der folgende Befehl ermöglicht das Fortsetzen einer Effizienzoperation für neue Daten auf dem Volume VolA:

+
`volume efficiency start -vserver vs1 -volume VolA -use-checkpoint true`

+
Mit dem folgenden Befehl lässt sich eine Effizienzoperation für vorhandene Daten auf dem Volume VolA fortsetzen:

+
`volume efficiency start -vserver vs1 -volume VolA -scan-old-data true -use-checkpoint true`

+
Weitere Informationen zu  `volume efficiency start` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-start.html["ONTAP-Befehlsreferenz"^].


