---
permalink: volumes/resume-efficiency-operation-checkpoint-task.html 
sidebar: sidebar 
keywords: resume, halted, efficiency, operation 
summary: Wenn ein Effizienzvorgang vom System angehalten wird, können Sie den Effizienzvorgang an demselben Punkt fortsetzen. 
---
= Setzen Sie einen angehaltenen Effizienzvorgang fort
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ein Effizienzvorgang aufgrund von Systemstopp, Systemunterbrechung oder Neustart angehalten wird, können Sie den Effizienzvorgang an demselben Punkt fortsetzen, an dem er angehalten wurde. Dies spart Zeit und Ressourcen, da der Vorgang nicht von Anfang an neu gestartet werden muss.

.Über diese Aufgabe
Ist die Deduplizierung nur auf dem Volume aktiviert, wird die Deduplizierung auf den Daten ausgeführt. Wenn sowohl die Deduplizierung als auch die Datenkomprimierung auf einem Volume aktiviert sind, wird zuerst die Datenkomprimierung ausgeführt und anschließend die Deduplizierung.

Sie können die Details des Checkpoint für ein Volume anzeigen, indem Sie den verwenden `volume efficiency show` Befehl.

Standardmäßig werden die Effizienzvorgänge von Checkpoints aus fortgesetzt. Wenn jedoch ein Kontrollpunkt einem vorherigen Effizienzbetrieb entspricht (die Phase, in der das ausgeführt wird `volume efficiency start``-Scan-old-Data` Befehl wird ausgeführt) ist älter als 24 Stunden, dann wird der Effizienzvorgang nicht automatisch vom letzten Checkpoint fortgesetzt. In diesem Fall beginnt der Effizienzbetrieb von Anfang an. Wenn Sie jedoch wissen, dass seit dem letzten Scan keine wesentlichen Änderungen im Volume aufgetreten sind, können Sie die Fortsetzung vom vorherigen Kontrollpunkt durch die erzwingen `-use-checkpoint` Option.

.Schritte
. Verwenden Sie die `volume efficiency start` Befehl mit dem `-use-checkpoint` Option zum Fortsetzen eines Effizienzvorgangs.
+
Mit dem folgenden Befehl können Sie einen Effizienzvorgang für neue Daten auf Volume Vola fortsetzen:

+
`volume efficiency start -vserver vs1 -volume VolA -use-checkpoint true`

+
Mit dem folgenden Befehl können Sie einen Effizienzvorgang für vorhandene Daten auf Volume Vola fortsetzen:

+
`volume efficiency start -vserver vs1 -volume VolA -scan-old-data true -use-checkpoint true`


