---
permalink: volumes/resume-efficiency-operation-checkpoint-task.html 
sidebar: sidebar 
keywords: resume, halted, efficiency, operation 
summary: Wenn ein Effizienzvorgang vom System angehalten wird, können Sie den Effizienzvorgang an demselben Punkt fortsetzen. 
---
= Setzen Sie einen angehaltenen Effizienzvorgang fort
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ein Effizienzvorgang aufgrund von Systemstopp, Systemunterbrechung oder Neustart angehalten wird, können Sie den Effizienzvorgang an demselben Punkt fortsetzen, an dem er angehalten wurde. Dies spart Zeit und Ressourcen, da der Vorgang nicht von Anfang an neu gestartet werden muss.

.Über diese Aufgabe
Ist die Deduplizierung nur auf dem Volume aktiviert, wird die Deduplizierung auf den Daten ausgeführt. Wenn sowohl die Deduplizierung als auch die Datenkomprimierung auf einem Volume aktiviert sind, wird zuerst die Datenkomprimierung ausgeführt und anschließend die Deduplizierung.

Sie können die Details des Kontrollpunkts für ein Volume mit dem `volume efficiency show` Befehl anzeigen. Erfahren Sie mehr über `volume efficiency show` in der link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-show.html["ONTAP-Befehlsreferenz"^].

Standardmäßig werden die Effizienzvorgänge von Checkpoints aus fortgesetzt. Wenn jedoch ein Kontrollpunkt, der einem vorherigen Effizienzvorgang entspricht (die Phase, in der der `volume efficiency start`` Befehl -Scan-old-Data` ausgeführt wird), älter als 24 Stunden ist, wird der Effizienzvorgang nicht automatisch vom vorherigen Kontrollpunkt fortgesetzt. In diesem Fall beginnt der Effizienzbetrieb von Anfang an. Wenn Sie jedoch wissen, dass seit dem letzten Scan keine wesentlichen Änderungen am Volumen aufgetreten sind, können Sie die Fortsetzung vom vorherigen Kontrollpunkt erzwingen, indem Sie die `-use-checkpoint` Option verwenden.

.Schritte
. Verwenden Sie den `volume efficiency start` Befehl mit der `-use-checkpoint` Option, um einen Effizienzvorgang fortzusetzen.
+
Mit dem folgenden Befehl können Sie einen Effizienzvorgang für neue Daten auf Volume Vola fortsetzen:

+
`volume efficiency start -vserver vs1 -volume VolA -use-checkpoint true`

+
Mit dem folgenden Befehl können Sie einen Effizienzvorgang für vorhandene Daten auf Volume Vola fortsetzen:

+
`volume efficiency start -vserver vs1 -volume VolA -scan-old-data true -use-checkpoint true`

+
Erfahren Sie mehr über `volume efficiency start` in der link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-start.html["ONTAP-Befehlsreferenz"^].


