---
permalink: volumes/run-efficiency-operations-manual-task.html 
sidebar: sidebar 
keywords: starting deduplication manually, starting data compression manually, efficiency, run 
summary: Sie können Effizienzvorgänge manuell auf einem Volume ausführen, indem Sie den Befehl „Volume Efficiency Start“ verwenden. 
---
= Führen Sie Effizienzvorgänge manuell aus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Effizienzvorgänge manuell auf einem Volume mit der ausführen `volume efficiency start` Befehl.

.Was Sie benötigen
Abhängig von dem Effizienzvorgang, der manuell ausgeführt werden soll, muss die Deduplizierung oder beide Datenkomprimierung und Deduplizierung auf einem Volume aktiviert sein.

.Über diese Aufgabe
Wenn Deduplizierung und Datenkomprimierung auf einem Volume aktiviert sind, wird die Datenkomprimierung anfänglich durchgeführt - gefolgt von der Deduplizierung.

Die Deduplizierung ist ein Hintergrundprozess, der während der Ausführung Systemressourcen verbraucht. Wenn sich die Daten in einem Volume nicht häufig ändern, sollte die Deduplizierung am besten weniger häufig durchgeführt werden. Mehrere gleichzeitige Deduplizierungsvorgänge auf einem Storage-System führen zu einem höheren Verbrauch von Systemressourcen.

Es können maximal acht gleichzeitige Deduplizierungs- oder Datenkomprimierungsvorgänge pro Node ausgeführt werden. Wenn weitere Effizienzvorgänge geplant werden, werden die Vorgänge in die Warteschlange verschoben.

.Schritt
. Verwenden Sie die `volume efficiency start` Befehl zum Starten des Effizienzvorgangs auf einem Volume.


.Beispiel
Mit dem folgenden Befehl können Sie nur noch Deduplizierung oder Datenkomprimierung manuell starten, gefolgt von Deduplizierung auf dem Volume Vola:

`volume efficiency start -vserver vs1 -volume VolA`
