---
permalink: volumes/run-efficiency-operations-manual-existing-data-task.html 
sidebar: sidebar 
keywords: run, efficiency, operations, manually, existing, data 
summary: Sie können die Effizienzvorgänge manuell für Daten ausführen, die sich in nichttemperatursensiblen Storage-Effizienz-Volumes enthalten haben, bevor Sie die Deduplizierung, Datenkomprimierung oder Data-Compaction mit ONTAP Versionen vor ONTAP 9.8 aktivieren. Diese Vorgänge können Sie mit dem Befehl Volume Efficiency Start -Scan-old-Data ausführen. 
---
= Manuelle Ausführung von Effizienzvorgängen für vorhandene Daten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Effizienzvorgänge manuell für Daten ausführen, die sich in nichttemperatursensiblen Storage-Effizienz-Volumes enthalten haben, bevor Sie die Deduplizierung, Datenkomprimierung oder Data-Compaction mit ONTAP Versionen vor ONTAP 9.8 aktivieren. Sie können diese Vorgänge mit dem ausführen `volume efficiency start -scan-old-data` Befehl.

Der `-compression` Option funktioniert nicht mit `-scan-old-data` Die Volumen der temperaturempfindlichen Storage-Effizienz. Inaktive Datenkomprimierung wird automatisch auf bereits vorhandenen Daten ausgeführt. Auf Volumes mit temperaturempfindlicher Storage-Effizienz werden sie in ONTAP 9.8 und höher ausgeführt.

Wenn die Deduplizierung nur auf einem Volume aktiviert wird, wird die Deduplizierung dann auch für diese Daten ausgeführt. Wenn Sie Deduplizierung, Datenkomprimierung und Data-Compaction auf einem Volume aktivieren, wird zuerst die Datenkomprimierung ausgeführt. Anschließend folgt die Deduplizierung und Data-Compaction.

Wenn Sie für bestehende Daten eine Datenkomprimierung durchführen, werden die Datenblöcke standardmäßig von der Deduplizierung gemeinsam genutzten Datenblöcken und die von Snapshot-Kopien gesperrten Datenblöcke übersprungen. Wenn Kunden die Datenkomprimierung auf gemeinsam genutzten Blöcken ausführen, wird die Optimierung deaktiviert und die Fingerabdruckinformationen werden erfasst und für die erneute Freigabe verwendet. Sie können das Standardverhalten der Datenkomprimierung ändern, wenn Sie vorhandene Daten komprimieren.

Pro Node können maximal acht Deduplizierungsoperationen, Datenkomprimierung oder Data-Compaction ausgeführt werden. Die verbleibenden Vorgänge werden in die Warteschlange verschoben.

[NOTE]
====
Die nachgelagerte Komprimierung wird nicht auf AFF Plattformen ausgeführt. Es wird eine EMS-Nachricht generiert, die Sie darüber informiert, dass dieser Vorgang übersprungen wurde.

====
.Schritt
. Verwenden Sie die `volume efficiency start -scan-old-data` Befehl zum manuellen Ausführen der Deduplizierung, Datenkomprimierung oder Data-Compaction für die vorhandenen Daten
+
Mit dem folgenden Befehl können Sie diese Vorgänge manuell auf den vorhandenen Daten in Volume Vola ausführen:

+
`volume efficiency start -vserver vs1 -volume VolA -scan-old-data true [-compression | -dedupe | -compaction ] true`


