---
permalink: volumes/setup-quotas-svm-task.html 
sidebar: sidebar 
keywords: set up, quotas on svm 
summary: Sie können Quoten auf einer neuen SVM einrichten, um die Ressourcenauslastung zu verwalten und zu überwachen. 
---
= Kontingente auf einer SVM einrichten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Quoten auf einer neuen SVM einrichten, um die Ressourcenauslastung zu verwalten und zu überwachen.

.Über diese Aufgabe
Auf hoher Ebene sind bei der Konfiguration von Quoten mehrere Schritte beteiligt, darunter:

. Eine Quotenrichtlinie erstellen
. Die Quotenregeln zur Richtlinie hinzufügen
. Die Richtlinie der SVM zuweisen
. Die Quoten auf jedem FlexVol volume auf der SVM initialisieren


.Schritte
. Den Befehl  `vserver show -instance` eingeben, um den Namen der Standard-Quota-Richtlinie anzuzeigen, die beim Erstellen der SVM automatisch erstellt wurde.
+
Wurde beim Erstellen der SVM kein Name angegeben, lautet dieser „default“. Mit dem  `vserver quota policy rename` Befehl kann der Standardrichtlinie ein Name zugewiesen werden.

+
[NOTE]
====
Es besteht auch die Möglichkeit, eine neue Richtlinie mit dem  `volume quota policy create` Befehl zu erstellen.

====
. Mit dem  `volume quota policy rule create` Befehl lässt sich für jedes Volume auf der SVM _eine beliebige_ der folgenden Quotenregeln erstellen:
+
** Standard-Kontingentregeln für alle Benutzer
** Explizite Kontingentregeln für bestimmte Benutzer
** Standard-Kontingentregeln für alle Gruppen
** Explizite Quotenregeln für bestimmte Gruppen
** Standardmäßige Kontingentregeln für alle Qtrees
** Explizite Quotenregeln für bestimmte Qtrees


. Mit dem  `volume quota policy rule show` Befehl lässt sich überprüfen, ob die Quotenregeln korrekt konfiguriert sind.
. Wenn Sie an einer neuen Richtlinie arbeiten, kann der  `vserver modify` Befehl verwendet werden, um die neue Richtlinie der SVM zuzuweisen.
. Mit dem  `volume quota on` Befehl werden die Quoten auf jedem Volume der SVM initialisiert.
+
Der Initialisierungsprozess kann auf folgende Weise überwacht werden:

+
** Bei Verwendung des  `volume quota on` Befehls kann der  `-foreground` Parameter hinzugefügt werden, um den Kontingentauftrag im Vordergrund auszuführen. (Standardmäßig wird der Auftrag im Hintergrund ausgeführt.)
+
Wenn der Job im Hintergrund läuft, kann sein Fortschritt mit dem  `job show` Befehl überwacht werden.

** Der  `volume quota show` Befehl kann zur Überwachung des Status der Quota-Initialisierung verwendet werden.


. Mit dem  `volume quota show -instance` Befehl lassen sich Initialisierungsfehler wie Quotenregeln, die nicht initialisiert werden konnten, überprüfen.
. Mit dem  `volume quota report` Befehl lässt sich ein Quotenbericht anzeigen, sodass überprüft werden kann, ob die durchgesetzten Quoten den Erwartungen entsprechen.


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/vserver-show.html["vserver show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/vserver-modify.html["vserver modify"^]
* link:https://docs.netapp.com/us-en/ontap-cli/job-show.html["Job anzeigen"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+quota["Volumenquote"^]

