---
permalink: volumes/snapshot-copies-flexclone-files-luns-concept.html 
sidebar: sidebar 
keywords: how, snapshot copies, work, flexclone files, flexclone luns 
summary: Die Synergie zwischen Snapshots und FlexClone Dateien und FlexClone LUNs sowie bestimmte Einschränkungen werden erläutert. 
---
= Erfahren Sie, wie ONTAP Snapshots mit FlexClone Dateien und FlexClone LUNs funktionieren.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es besteht eine Synergie zwischen Snapshots und den FlexClone Dateien sowie FlexClone LUNs. Bei der Arbeit mit diesen Technologien sind sowohl die Möglichkeiten als auch die jeweiligen Einschränkungen zu berücksichtigen.

.Erstellen von FlexClone-Dateien und LUNs
Sie können eine FlexClone Datei oder FlexClone LUN aus einem vorhandenen Snapshot erstellen. Die Kopie basiert auf den übergeordneten Dateien und LUNs, die in einem FlexVol volume enthalten sind.

.Löschen eines Snapshots
Sie können einen Snapshot, aus dem gerade FlexClone-Dateien oder FlexClone-LUNs erstellt werden, nicht manuell löschen. Der Snapshot bleibt gesperrt, bis der Hintergrundprozess zur Blockfreigabe abgeschlossen ist. Wenn versucht wird, einen gesperrten Snapshot zu löschen, zeigt das System eine Meldung an, die dazu auffordert, den Vorgang nach einer gewissen Zeit erneut zu versuchen. In diesem Fall ist der Löschvorgang weiterhin zu wiederholen. Das Löschen des Snapshots ist möglich, sobald die Blockfreigabe abgeschlossen ist.
