---
permalink: volumes/space-display-quota-report-unix-client-concept.html 
sidebar: sidebar 
keywords: difference, space usage, displayed, quota report, unix client 
summary: Der Wert des belegten Festplattenspeichers, der in einem Kontingentbericht für ein FlexVol Volume oder qtree angezeigt wird, kann sich von dem Wert unterscheiden, der von einem UNIX Client für dasselbe Volume oder denselben qtree angezeigt wird. Der Unterschied bei den Nutzungswerten liegt auf der Differenz zwischen den Methoden, gefolgt vom Quotenbericht und den UNIX Befehlen zur Berechnung der Datenblöcke im Volume oder qtree. 
---
= Die Differenz in der Raumnutzung wird durch einen Quotenbericht und eine Übersicht über den UNIX-Client angezeigt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Wert des belegten Festplattenspeichers, der in einem Kontingentbericht für ein FlexVol Volume oder qtree angezeigt wird, kann sich von dem Wert unterscheiden, der von einem UNIX Client für dasselbe Volume oder denselben qtree angezeigt wird. Der Unterschied bei den Nutzungswerten liegt auf der Differenz zwischen den Methoden, gefolgt vom Quotenbericht und den UNIX Befehlen zur Berechnung der Datenblöcke im Volume oder qtree.

Wenn ein Volume beispielsweise eine Datei enthält, die über leere Datenblöcke verfügt (auf die Daten nicht geschrieben werden), wird im Kontingentbericht für das Volume nicht die leeren Datenblöcke gezählt, während entsprechende Berichte über die Speicherplatznutzung erstellt werden. Wenn jedoch das Volume auf einem UNIX-Client gemountet wird und die Datei als Ausgabe des angezeigt wird `ls` Befehl, die leeren Datenblöcke sind ebenfalls in der Speicherplatznutzung enthalten. Deshalb, das `ls` Der Befehl zeigt eine höhere Dateigröße im Vergleich zur im Kontingentbericht angezeigten Speicherplatznutzung an.

Ebenso können die in einem Quotenbericht dargestellten Werte für die Platznutzung von den Werten abweichen, die als Ergebnis von UNIX-Befehlen wie dargestellt werden `df` Und `du`.
