---
permalink: volumes/space-reserved-luns-thick-provisioned-concept.html 
sidebar: sidebar 
keywords: configuration, settings, space-reserved, files, luns with thick-provisioned volumes 
summary: Die auf Thick Provisioning Volumes basierende Konfiguration bietet Storage-Effizienz und erfordert keine aktive Überwachung des freien Speicherplatzes. 
---
= Konfigurationseinstellungen für platzreservierte Dateien oder LUNs mit Thick Provisioning Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können verschiedene Konfigurationskombinationen für FlexVol volume und Datei- oder LUN-Konfigurationen verwenden. Diese Kombination auf der Basis von Thick Provisioning Volumes ermöglicht die Nutzung von Storage-Effizienztechnologien und erfordert keine aktive Überwachung des freien Speicherplatzes, da vorab ausreichend Speicherplatz zugewiesen wird.

Die folgenden Einstellungen sind erforderlich, um eine speziell für den Speicherplatz reservierte Datei oder ein LUN in einem Volume mit Thick Provisioning zu konfigurieren:

[cols="2*"]
|===
| Lautstärkereinstellung | Wert 


 a| 
Garantie
 a| 
Datenmenge



 a| 
Fraktionale Reserve
 a| 
100



 a| 
Snapshot Reserve
 a| 
Alle



 a| 
Snapshot wird automatisches Löschen erstellt
 a| 
Optional



 a| 
Autogrow
 a| 
Optional; bei Aktivierung muss der freie Speicherplatz des Aggregats aktiv überwacht werden.

|===
[cols="2*"]
|===
| Datei- oder LUN-Einstellung | Wert 


 a| 
Speicherplatzreservierung
 a| 
Aktiviert

|===
.Verwandte Informationen
* link:recommended-volume-lun-config-combinations-concept.html["Überblick über Empfohlene Kombinationen aus Volume- und Datei- oder LUN-Konfiguration"]

