---
permalink: volumes/space-reserved-luns-thick-provisioned-concept.html 
sidebar: sidebar 
keywords: configuration, settings, space-reserved, files, luns with thick-provisioned volumes 
summary: Die auf Thick-Provisioned Volumes basierende Konfiguration bietet Speichereffizienzen und erfordert keine aktive Überwachung des freien Speicherplatzes. 
---
= Konfigurationseinstellungen für speicherplatzreservierte Dateien oder LUNs mit ONTAP Thick-Provisioned-Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es stehen verschiedene Kombinationsmöglichkeiten von FlexVol volume- und Datei- oder LUN-Konfigurationen zur Verfügung. Diese Kombination auf Basis von Thick-Provisioned-Volumes ermöglicht die Nutzung von Speichereffizienztechnologien und erfordert keine aktive Überwachung des freien Speicherplatzes, da ausreichend Speicherplatz im Voraus zugewiesen wird.

Folgende Einstellungen sind erforderlich, um eine speicherplatzreservierte Datei oder LUN in einem Volume mithilfe von Thick Provisioning zu konfigurieren:

[cols="2*"]
|===
| Volume-Einstellung | Wert 


 a| 
Garantie
 a| 
Volumen



 a| 
Teilreserve
 a| 
100



 a| 
Snapshot-Reserve
 a| 
Beliebig



 a| 
Snapshot Autolöschung
 a| 
Optional



 a| 
Automatisches Wachstum
 a| 
Optional; falls aktiviert, muss der freie Speicherplatz des Aggregats aktiv überwacht werden.

|===
[cols="2*"]
|===
| Datei- oder LUN-Einstellung | Wert 


 a| 
Platzreservierung
 a| 
Aktiviert

|===
.Verwandte Informationen
* link:recommended-volume-lun-config-combinations-concept.html["Übersicht empfohlener Volume- und Datei- oder LUN-Konfigurationskombinationen"]

