---
permalink: volumes/specify-unix-users-quotas-concept.html 
sidebar: sidebar 
keywords: specify, unix users, for quotas 
summary: Ein UNIX-Benutzer kann für ein Kontingent in einem von mehreren verschiedenen Formaten angegeben werden. 
---
= UNIX-Benutzer für ONTAP-Kontingente festlegen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein UNIX-Benutzer kann für ein Kontingent in einem von mehreren verschiedenen Formaten angegeben werden.

Die drei verfügbaren Formate bei der Angabe eines UNIX-Benutzers für ein Benutzerkontingent sind die folgenden:

* Der Benutzername (wie jsmith).
+
[NOTE]
====
Sie können keinen UNIX-Benutzernamen zur Angabe eines Benutzerkontingents verwenden, wenn dieser einen Backslash (\) oder ein @-Zeichen enthält. Dies liegt daran, dass ONTAP Namen mit diesen Zeichen als Windows-Namen behandelt.

====
* Die Benutzer-ID oder UID (z. B. 20).
* Der Pfad einer Datei oder eines Verzeichnisses, das diesem Benutzer gehört, sodass die UID der Datei mit der des Benutzers übereinstimmt.
+
[NOTE]
====
Wenn Sie einen Datei- oder Verzeichnisnamen angeben, muss eine Datei oder ein Verzeichnis ausgewählt werden, das so lange besteht, wie das Benutzerkonto auf dem System vorhanden ist.

Die Angabe eines Datei- oder Verzeichnisnamens für die UID bewirkt nicht, dass ONTAP ein Benutzerkontingent auf diese Datei oder dieses Verzeichnis anwendet.

====

