---
permalink: volumes/stop-volume-efficiency-operations-task.html 
sidebar: sidebar 
keywords: stopping deduplication, stopping data compression, volume efficiency operations 
summary: Sie können einen Deduplizierungs- oder nachgelagerten Komprimierungsvorgang anhalten. 
---
= Stoppen Sie die Volume-Effizienz
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen Deduplizierungs- oder nachgelagerten Komprimierungsvorgang anhalten.

.Über diese Aufgabe
Dieser Vorgang verwendet den Befehl `volume efficiency stop`. Dieser Befehl generiert automatisch einen Checkpoint.

.Schritte
. Verwenden Sie die `volume efficiency stop` Befehl zum Anhalten eines aktiven Deduplizierungsvorgangs oder nachgelagerten Komprimierungsvorgangs.
+
Wenn Sie den angeben `-all` Option, aktive und warteschlangenbasierte Effizienzvorgänge werden abgebrochen.



.Beispiele
Mit dem folgenden Befehl wird der Deduplizierungsvorgang oder der nachgelagerte Komprimierungsvorgang angehalten, der derzeit auf Volume Vola aktiv ist:

`volume efficiency stop -vserver vs1 -volume VolA`

Mit dem folgenden Befehl werden sowohl aktive als auch warteschlangenbasierte Deduplizierungs- oder nachgelagerte Komprimierungsvorgänge bei Volume Vola abgebrochen:

`volume efficiency stop -vserver vs1 -volume VolA -all true`
