---
permalink: volumes/track-quotas-concept.html 
sidebar: sidebar 
keywords: how, you, use, tracking, quotas 
summary: Durch das Nachverfolgen von Kontingenten werden Berichte über die Festplatten- und Dateiverwendung generiert und der Ressourcenverbrauch nicht begrenzt. Wenn Sie Kontingente überwachen, ist das Ändern von Quotenwerten weniger Unterbrechungen nötig, da Sie die Größe von Kontingenten anpassen können, anstatt sie aus- und wieder einschalten zu müssen. 
---
= Wie Sie Tracking Quoten verwenden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durch das Nachverfolgen von Kontingenten werden Berichte über die Festplatten- und Dateiverwendung generiert und der Ressourcenverbrauch nicht begrenzt. Wenn Sie Kontingente überwachen, ist das Ändern von Quotenwerten weniger Unterbrechungen nötig, da Sie die Größe von Kontingenten anpassen können, anstatt sie aus- und wieder einschalten zu müssen.

Um ein Tracking-Kontingent zu erstellen, geben Sie die Parameter für die Datenträgerbegrenzung und die Dateibegrenzung aus. Somit überwacht ONTAP die Festplatten- und Dateiverwendung für dieses Ziel (Volume oder qtree), ohne Einschränkungen zu setzen. Die Nachverfolgung der Quoten ist in der Ausgabe von angegeben `show` Befehle und Quota Report mit einem Bindestrich ("-") für alle Grenzwerte.

Sie können auch ein _default Tracking Quota_ angeben, das für alle Instanzen des Ziels gilt. Mithilfe von Standardkontingenten können Sie die Nutzung für alle Instanzen eines Kontingenttyps nachverfolgen (z. B. alle qtrees oder alle Benutzer). Darüber hinaus können Sie die Größe verwenden, anstatt die Neuinitialisierung zu ändern, wenn Quotenänderungen wirksam werden sollen.

In der folgenden Kontingentdatei werden die Kontingente für einen bestimmten Benutzer, eine bestimmte Gruppe und einen bestimmten qtree angezeigt:

[listing]
----

#Quota target   type           disk files thold sdisk sfile
#-----------    ----           ---- ----- ----- ----- -----
kjones          user@/vol/vol1    -  -
eng1            group@/vol/vol1   -  -
proj1           tree@/vol/vol1    -  -
----
Die folgende Kontingentdatei enthält die drei möglichen Standardkontingente (Benutzer, Gruppen und qtrees):

[listing]
----

#Quota target   type           disk  files thold sdisk sfile
#-----------    ----           ----  ----- ----- ----- -----
*               user@/vol/vol1    -   -
*               group@/vol/vol1   -   -
*               tree@/vol/vol1    -   -
----