---
permalink: volumes/track-quotas-concept.html 
sidebar: sidebar 
keywords: how, you, use, tracking, quotas 
summary: Ein Tracking-Kontingent generiert einen Bericht über die Festplatten- und Dateiverwendung, macht das Ändern von Quotenwerten weniger störend und beschränkt die Ressourcennutzung nicht. 
---
= Tracking-Quotas verwenden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Tracking-Kontingent generiert einen Bericht über die Festplatten- und Dateinutzung und beschränkt die Ressourcennutzung nicht. Bei der Verwendung von Quotas ist das Ändern der Quotas weniger störend, da Sie Quotas anpassen können, anstatt sie aus- und wieder einzuschalten.

Um ein Tracking-Kontingent zu erstellen, geben Sie die Parameter für die Datenträgerbegrenzung und die Dateibegrenzung aus. Somit überwacht ONTAP die Festplatten- und Dateiverwendung für dieses Ziel (Volume oder qtree), ohne Einschränkungen zu setzen. Die Nachverfolgung der Quoten ist in der Ausgabe von angegeben `show` Befehle und Quota Report mit einem Bindestrich ("-") für alle Grenzwerte. ONTAP erstellt automatisch Tracking-Quotas, wenn Sie über die System Manager Benutzeroberfläche explizite Quotas (Quotas mit bestimmten Zielen) erstellen. Bei Verwendung der CLI erstellt der Storage-Administrator zusätzlich zu expliziten Quotas Tracking Quotas.

Sie können auch ein _default Tracking Quota_ angeben, das für alle Instanzen des Ziels gilt. Mithilfe von Standardkontingenten können Sie die Nutzung für alle Instanzen eines Kontingenttyps nachverfolgen (z. B. alle qtrees oder alle Benutzer). Darüber hinaus können Sie die Größe verwenden, anstatt die Neuinitialisierung zu ändern, wenn Quotenänderungen wirksam werden sollen.

.Beispiele
Die Ausgabe für eine Tracking-Regel zeigt Tracking-Quoten für einen qtree, Benutzer und Gruppe, wie im folgenden Beispiel für eine Tracking-Regel auf Volume-Ebene dargestellt:

[listing]
----
Vserver: vs0             Policy: default             Volume: fv1

                                      Soft          Soft
                       User    Disk   Disk   Files  Files
Type  Target   Qtree   Mapping Limit  Limit  Limit  Limit  Threshold
----- -------- ------- ------- ------ ------ ------ ------ ---------
tree  ""       ""      -       -      -      -      -      -
user  ""       ""      off     -      -      -      -      -
group ""       ""      -       -      -      -      -      -
----