---
permalink: volumes/tree-quotas-concept.html 
sidebar: sidebar 
keywords: how, tree, quotas, work 
summary: Sie können eine Quote mit einem qtree als Ziel erstellen, um zu begrenzen, wie groß der Ziel-qtree werden kann. Diese Quoten werden auch Tree Quotas genannt. 
---
= Erfahren Sie mehr über ONTAP-Baumquoten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Quote mit einem qtree als Ziel erstellen, um zu begrenzen, wie groß der Ziel-qtree werden kann. Diese Quoten werden auch _Tree Quotas_ genannt.


NOTE: Sie können auch Benutzer- und Gruppenquoten für einen bestimmten qtree erstellen. Darüber hinaus werden Quoten für ein FlexVol Volume manchmal durch die qtrees übernommen, die in diesem Volume enthalten sind.

Wenn Sie ein Kontingent auf einen qtree anwenden, ist das Ergebnis ähnlich wie eine Disk-Partition, außer dass Sie die maximale Größe des qtree jederzeit durch Ändern der Quote ändern können. Beim Anwenden einer Baumquote begrenzt ONTAP unabhängig von ihren Eigentümern den Speicherplatz und die Anzahl der Dateien im qtree. Keine Nutzer, einschließlich Root und Mitglieder der BUILTIN\Administrators-Gruppe, können an den qtree schreiben, wenn der Schreibvorgang dazu führt, dass die Baumquote überschritten wird.

Die Größe des Kontingents ist keine Garantie für eine bestimmte Menge an verfügbarem Speicherplatz. Die Größe des Kontingents kann größer sein als die Menge an freiem Speicherplatz, die dem qtree zur Verfügung steht. Sie können mit dem `volume quota report` Befehl die tatsächliche Menge des verfügbaren Speicherplatzes im qtree bestimmen.

Erfahren Sie mehr über `volume quota report` in der link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-report.html["ONTAP-Befehlsreferenz"^].



== Erfahren Sie, wie ONTAP Benutzer- und Gruppenkontingente mit qtrees funktionieren.

Tree Quotas begrenzen die Gesamtgröße des qtree. Um zu verhindern, dass einzelne Benutzer oder Gruppen den gesamten qtree verbrauchen, geben Sie einen Benutzer- oder Gruppenkontingent für den qtree an.

.Beispiel Benutzerkontingent in einem qtree
[%collapsible]
====
Angenommen, Sie haben die folgenden Quotenregeln:

[listing]
----
cluster1::> volume quota policy rule show -vserver vs0 -volume vol1

Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   ""        ""      off          50MB        -       -        -       45MB
user   jsmith    ""      off          80MB        -       -        -       75MB
----
Sie bemerken, dass ein bestimmter Benutzer, kjones, zu viel Speicherplatz in einem kritischen qtree, proj1, der in vol1 residiert, belegt. Sie können den Speicherplatz dieses Benutzers einschränken, indem Sie die folgende Kontingentregel hinzufügen:

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target "kjones" -qtree "proj1" -disk-limit 20m -threshold 15m

cluster1::> volume quota policy rule show -vserver vs0 -volume vol1

Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   ""        ""      off          50MB        -       -        -       45MB
user   jsmith    ""      off          80MB        -       -        -       75MB
user   kjones    proj1   off          20MB        -       -        -       15MB
----
====


== Erfahren Sie, wie Standard-Baumquoten auf einem ONTAP FlexVol Volume abgeleitete Baumquoten erzeugen

Wenn Sie ein Standard-Baumkontingent auf einem FlexVol-Volumen erstellen, werden automatisch die entsprechenden abgeleiteten Tree Quotas für jeden qtree in diesem Volume erstellt.

Diese abgeleiteten Baumkontingente haben die gleichen Grenzen wie die Standardstrukturkontingente. Wenn keine zusätzlichen Quoten vorhanden sind, haben die Grenzwerte folgende Auswirkungen:

* Benutzer können auf einem qtree so viel Speicherplatz verwenden, wie sie für das gesamte Volume zugeteilt werden (vorausgesetzt, sie überschreiten das Limit für das Volume nicht durch die Nutzung von Speicherplatz im Root-Verzeichnis oder einem anderen qtree).
* Jede qtrees kann entsprechend dem jeweiligen Volume erweitert werden.


Die Existenz einer Standard-Baumquote auf einem Volume wirkt sich weiterhin auf alle neuen qtrees aus, die dem Volume hinzugefügt werden. Jedes Mal, wenn ein neuer qtree erstellt wird, wird auch ein abgeleitetes Baumkontingent erstellt.

Wie alle abgeleiteten Quoten zeigen abgeleitete Baumquoten folgende Verhaltensweisen an:

* Werden nur erstellt, wenn das Ziel noch keine explizite Quote hat.
* Wird in Quotenberichten angezeigt, wird aber nicht angezeigt, wenn Sie Quotenregeln mit dem `volume quota policy rule show` Befehl anzeigen. Erfahren Sie mehr über `volume quota policy rule show` in der link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-policy-rule-show.html["ONTAP-Befehlsreferenz"^].


.Beispiel für abgeleitete Baumkontingente
[%collapsible]
====
Sie haben ein Volumen mit drei qtrees (proj1, proj2 und proj3) und die einzige Baumquote ist ein explizites Kontingent auf dem proj1 qtree, das seine Festplattengröße auf 10 GB begrenzt. Wenn Sie ein Standard-Baumkontingent auf dem Volume erstellen und Quoten für das Volume neu initialisieren, enthält der Quotenbericht jetzt vier Baumkontingente:

[listing]
----
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1     proj1     tree    1           0B   10GB       1       -   proj1
vol1               tree    *           0B   20GB       0       -   *
vol1     proj2     tree    2           0B   20GB       1       -   proj2
vol1     proj3     tree    3           0B   20GB       1       -   proj3
...
----
Die erste Zeile zeigt die ursprüngliche explizite Quote auf dem proj1 qtree. Diese Quote bleibt unverändert.

Die zweite Zeile zeigt das neue Standard-Baumkontingent auf dem Volume. Das Sternchen (*) Quota-Specifizierer zeigt an, dass es sich um ein Standardkontingent handelt. Diese Quote ist das Ergebnis der Kontingentregel, die Sie erstellt haben.

Die letzten beiden Zeilen zeigen neue abgeleitete Baumquoten für die proj2 und proj3 qtrees. ONTAP hat diese Quoten automatisch als Ergebnis des Standard Tree Quotas auf dem Volume erstellt. Diese abgeleiteten Baumkontingente haben das gleiche 20-GB-Datenträgerlimit wie das Standardbaumkontingent auf dem Volumen. ONTAP hat keine abgeleitete Baumquote für den proj1 qtree erzeugt, da der proj1-qtree bereits eine explizite Quote hatte.

====


== Erfahren Sie, wie sich die Standardbenutzerkontingente auf einem ONTAP FlexVol volume auf die Kontingente für Qtrees auswirken.

Wenn ein Standard-Benutzerkontingent für ein FlexVol Volume definiert wird, wird automatisch ein Standard-Benutzerkontingent für jeden qtree erstellt, der von diesem Volume enthalten ist, für den ein explizites oder ein abgeleitetes Baumkontingent besteht.

Ist bereits ein Standard-Benutzerkontingent auf den qtree vorhanden, bleibt er unbeeinflusst, wenn das Standardbenutzerkontingent auf dem Volume erstellt wird.

Die automatisch erstellten Standard-Benutzerkontingente auf den qtrees haben die gleichen Grenzwerte wie das Standardbenutzerkontingent, das Sie für den Datenträger erstellen.

Ein explizites Benutzerkontingent für einen qtree überschreibt (ersetzt die angewendeten Limits) das automatisch erstellte Standard-Benutzerkontingent, auf die gleiche Weise wie es ein Standard-Benutzerkontingent auf den qtree überschreibt, der von einem Administrator erstellt wurde.
