---
permalink: volumes/view-space-savings-flexclone-files-luns-task.html 
sidebar: sidebar 
keywords: view space, view space savings, flexclone files, flexclone luns 
summary: Sie können den Prozentsatz des durch die gemeinsame Nutzung von Blöcken auf einem Volume mit FlexClone-Dateien und FlexClone-LUNs eingesparten Festplattenspeichers anzeigen. Dies könnte im Rahmen der Kapazitätsplanung erfolgen. 
---
= Anzeige der Speicherplatzeinsparungen mit FlexClone Dateien und FlexClone LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Prozentsatz des durch die gemeinsame Nutzung von Blöcken auf einem Volume mit FlexClone-Dateien und FlexClone-LUNs eingesparten Festplattenspeichers anzeigen. Dies könnte im Rahmen der Kapazitätsplanung erfolgen.

.Schritte
. Um die Speicherplatzeinsparung durch FlexClone Dateien und FlexClone LUNs anzuzeigen, geben Sie den folgenden Befehl ein:
+
`df -s volname`

+
`volname` Ist der Name der FlexVol volume.

+
[NOTE]
====
Wenn Sie den `df -s` Befehl auf einer FlexVol volume mit aktivierter Deduplizierung ausführen, lassen sich die Einsparungen sowohl durch die Deduplizierung als auch durch FlexClone-Dateien und LUNs anzeigen.

====


.Beispiel
Das folgende Beispiel zeigt die Speicherplatzeinsparung auf einem FlexClone Volume test1:

[listing]
----
systemA> df -s test1

Filesystem         used   saved   %saved Vserver
/vol/test1/        4828    5744     54%  vs1
----