---
permalink: volumes/view-status-efficiency-operations-task.html 
sidebar: sidebar 
keywords: efficiency, operation, status, view 
summary: Sie können anzeigen, ob die Deduplizierung oder die Datenkomprimierung auf einem Volume aktiviert ist. Mit dem Befehl Volume Efficiency show können Sie auch den Status, den Status, den Status, die Art der Komprimierung und den Fortschritt der Effizienzvorgänge bei einem Volume anzeigen. 
---
= Den Status von Effizienzvorgängen anzeigen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können anzeigen, ob die Deduplizierung oder die Datenkomprimierung auf einem Volume aktiviert ist. Sie können auch den Status, den Zustand, die Art der Komprimierung und den Fortschritt der Effizienzvorgänge auf einem Volume mithilfe von anzeigen `volume efficiency show` Befehl.

.Schritt
. Verwenden Sie die `volume efficiency show` Befehl zum Anzeigen des Status eines Effizienzvorgangs auf einem Volume.
+
Mit dem folgenden Befehl wird der Status eines Effizienzvorgangs auf Volume Vola angezeigt, dem der anpassungsfähige Komprimierungstyp zugewiesen ist:

+
`volume efficiency show -instance -vserver vs1 -volume VolA`

+
Wenn der Effizienzvorgang auf Volume Vola aktiviert ist und der Betrieb im Leerlauf ist, sehen Sie im System-Output Folgendes:

+
[listing]
----
cluster1::> volume efficiency show -vserver vs1 -volume VolA

  Vserver Name: vs1
   Volume Name: VolA
   Volume Path: /vol/VolA
         State: Enabled
        Status: Idle
      Progress: Idle for 00:03:20
----

