---
permalink: encryption-at-rest/assign-authentication-keys-seds-onboard-task.html 
sidebar: sidebar 
keywords: assign, data, authentication, key, fips, drive, sed, onboard, key, management 
summary: Mit dem Befehl Speicherverschlüsselungsdisk modify können Sie einem FIPS-Laufwerk oder einer SED einen Datenauthentifizierungsschlüssel zuweisen. Cluster-Nodes verwenden diesen Schlüssel für den Zugriff auf die Daten auf dem Laufwerk. 
---
= Weisen Sie einem FIPS-Laufwerk oder SED mit der integrierten Schlüsselverwaltung von ONTAP einen Datenauthentifizierungsschlüssel zu
:allow-uri-read: 


[role="lead"]
Mit dem `storage encryption disk modify` Befehl können Sie einem FIPS-Laufwerk oder einer SED einen Datenauthentifizierungsschlüssel zuweisen. Cluster-Nodes verwenden diesen Schlüssel für den Zugriff auf die Daten auf dem Laufwerk.

.Über diese Aufgabe
Ein selbstverschlüsselndes Laufwerk ist nur dann vor unberechtigtem Zugriff geschützt, wenn seine Authentifizierungsschlüssel-ID auf einen nicht standardmäßigen Wert eingestellt ist. Der Hersteller Secure ID (MSID), der die Schlüssel-ID 0x0 hat, ist der Standardvorgabewert für SAS-Laufwerke. Bei NVMe-Laufwerken ist der Standardwert ein Null-Schlüssel, der als leere Schlüssel-ID dargestellt wird. Wenn Sie einem selbstverschlüsselnden Laufwerk die Schlüssel-ID zuweisen, ändert das System seine Authentifizierungsschlüssel-ID in einen nicht standardmäßigen Wert.

.Bevor Sie beginnen
Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.

.Schritte
. Zuweisen eines Datenauthentifizierungsschlüssels zu einem FIPS-Laufwerk oder einer SED:
+
`storage encryption disk modify -disk _disk_ID_ -data-key-id _key_ID_`

+
Erfahren Sie mehr über `storage encryption disk modify` in der link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-modify.html["ONTAP-Befehlsreferenz"^].

+
[NOTE]
====
Sie können den `security key-manager key query -key-type NSE-AK` Befehl verwenden, um Schlüssel-IDs anzuzeigen.

====
+
[listing]
----
cluster1::> storage encryption disk modify -disk 0.10.* -data-key-id <id_value>

Info: Starting modify on 14 disks.
      View the status of the operation by using the
      storage encryption disk show-status command.
----
+
Erfahren Sie mehr über `security key-manager key query` in der link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-query.html["ONTAP-Befehlsreferenz"^].

. Vergewissern Sie sich, dass die Authentifizierungsschlüssel zugewiesen wurden:
+
`storage encryption disk show`

+
Erfahren Sie mehr über `storage encryption disk show` in der link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["ONTAP-Befehlsreferenz"^].

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data <id_value>
0.0.1   data <id_value>
[...]
----


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["Speicherverschlüsselung Datenträger anzeigen"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show-status.html["Speicherverschlüsselung Datenträger Status anzeigen"^]

