---
permalink: encryption-at-rest/backup-key-management-information-manual-task.html 
sidebar: sidebar 
keywords: backing up, onboard key management, okm, onboard key manager, information, manually, backup, passphrase 
summary: Sie sollten die Onboard Key Management-Informationen immer dann an einem sicheren Ort außerhalb des Speichersystems speichern, wenn Sie die Passphrase des Onboard Key Manager konfigurieren. 
---
= ONTAP Onboard-Schlüsselverwaltungsinformationen manuell sichern
:allow-uri-read: 


[role="lead"]
Sie sollten die Onboard Key Management-Informationen immer dann an einem sicheren Ort außerhalb des Speichersystems speichern, wenn Sie die Passphrase des Onboard Key Manager konfigurieren.

.Bevor Sie beginnen
* Sie müssen Cluster-Administrator sein, um diese Aufgabe ausführen zu können.
* Für diese Aufgabe sind erweiterte Berechtigungen erforderlich.


.Über diese Aufgabe
Alle Schlüsselverwaltungsinformationen werden automatisch in der replizierten Datenbank (RDB) des Clusters gesichert. Schlüsselverwaltungsinformationen sollten zusätzlich manuell gesichert werden, um sie im Katastrophenfall verwenden zu können.

.Schritte
. Wechsel zum erweiterten Berechtigungslevel:
+
`set -privilege advanced`

. Die Sicherungsinformationen für die Schlüsselverwaltung des Clusters anzeigen:
+
[cols="40,60"]
|===


| Für diese ONTAP Version... | Verwenden Sie diesen Befehl... 


 a| 
ONTAP 9.6 und höher
 a| 
`security key-manager onboard show-backup`



 a| 
ONTAP 9.5 und früher
 a| 
`security key-manager backup show`

|===
+
Der folgende 9.6-Befehl zeigt die Sicherungsinformationen für die Schlüsselverwaltung für  `cluster1` an:

+
[listing]
----
cluster1::> security key-manager onboard show-backup

     --------------------------BEGIN BACKUP--------------------------
     TmV0QXBwIEtleSBCbG9iAAEAAAAEAAAAcAEAAAAAAADuD+byAAAAACEAAAAAAAAA
     QAAAAAAAAABvOlH0AAAAAMh7qDLRyH1DBz12piVdy9ATSFMT0C0TlYFss4PDjTaV
     dzRYkLd1PhQLxAWJwOIyqSr8qY1SEBgm1IWgE5DLRqkiAAAAAAAAACgAAAAAAAAA
     3WTh7gAAAAAAAAAAAAAAAAIAAAAAAAgAZJEIWvdeHr5RCAvHGclo+wAAAAAAAAAA
     IgAAAAAAAAAoAAAAAAAAAEOTcR0AAAAAAAAAAAAAAAACAAAAAAAJAGr3tJA/LRzU
     QRHwv+1aWvAAAAAAAAAAACQAAAAAAAAAgAAAAAAAAACdhTcvAAAAAJ1PXeBfml4N
     BsSyV1B4jc4A7cvWEFY6lLG6hc6tbKLAHZuvfQ4rIbYAAAAAAAAAAAAAAAAAAAAA
     AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
     AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
     AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
     AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
     AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
     AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
     AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
     AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABOZXRBcHAgS2V5IEJsb2IA
     AQAAAAMAAAAYAQAAAAAAADA5/ccAAAAAIgAAAAAAAAAoAAAAAAAAAEOTcR0AAAAA
     AAAAAAAAAAACAAAAAAAJAGr3tJA/LRzUQRHwv+1aWvAAAAAAAAAAACIAAAAAAAAA
     KAAAAAAAAACI8z/bAAAAAAAAAAAAAAAAAgAAAAAAAQAbxMcI4qiaMS4Uts5tTUnU
     AAAAAAAAAAAkAAAAAAAAAIAAAAAAAAAAqwxTcwAAAACkiwBAI3YeeV3jMFg5Smyj
     LSgoK/qc8FAmMMcrRXY6uriulnL0WPB/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
     AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
     AAAAAAAAAAAAAAAAAAAAAE5ldEFwcCBLZXkgQmxvYgABAAAAAwAAABgBAAAAAAAA
     1cNLLwAAAAAiAAAAAAAAACgAAAAAAAAAQ5NxHQAAAAAAAAAAAAAAAAIAAAAAAAkA
     ave0kD8tHNRBEfC/7Vpa8AAAAAAAAAAAIgAAAAAAAAAoAAAAAAAAAJ4/cQsAAAAA
     AAAAAAAAAAACAAAAAAABAF6JCZch+IF+ZeOutovhv8oAAAAAAAAAACQAAAAAAAAA
     gAAAAAAAAAAN3Zq7AAAAALO7qD20+H8TuGgSauEHoqAyWcLv4uA0m2rrH4nPQM0n
     rDRYRa9SCv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
     AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
     ---------------------------END BACKUP---------------------------
----
. Die Sicherungsdaten sollten an einen sicheren Ort außerhalb des Speichersystems kopiert werden, damit sie im Katastrophenfall zur Verfügung stehen.


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-show-backup.html["security key-manager onboard show-backup"^]
* link:https://docs.netapp.com/us-en/ontap-cli-95/security-key-manager-backup-show.html["security key-manager backup show"^]

