---
permalink: encryption-at-rest/change-key-management-passphrase-task.html 
sidebar: sidebar 
keywords: changing, onboard, key, management, passphrase 
summary: Die Passphrase für die interne Schlüsselverwaltung sollte regelmäßig geändert werden. Die neue Passphrase ist an einem sicheren Ort außerhalb des Speichersystems aufzubewahren. 
---
= Die Passphrase für die ONTAP Onboard-Schlüsselverwaltung ändern
:allow-uri-read: 


[role="lead"]
NetApp empfiehlt, die Passphrase für die integrierte Schlüsselverwaltung regelmäßig zu ändern. Die neue Passphrase muss an einem sicheren Ort außerhalb des Speichersystems aufbewahrt werden.

.Bevor Sie beginnen
* Sie müssen Cluster- oder SVM-Administrator sein, um diese Aufgabe ausführen zu können.
* Für diese Aufgabe sind erweiterte Berechtigungen erforderlich.
* In einer MetroCluster Umgebung wird nach der Aktualisierung der Passphrase auf dem lokalen Cluster die Passphrase-Aktualisierung auf dem Partnercluster synchronisiert.


.Schritte
. Wechsel zum erweiterten Berechtigungslevel:
+
`set -privilege advanced`

. Ändern der Passphrase für die integrierte Schlüsselverwaltung. Der verwendete Befehl hängt von der ONTAP-Version ab, die ausgeführt wird.
+
[role="tabbed-block"]
====
.ONTAP 9.6 und höher
--
`security key-manager onboard update-passphrase`

--
.ONTAP 9.5 und früher
--
`security key-manager update-passphrase`

--
====
. Geben Sie eine Passphrase mit 32 bis 256 Zeichen ein oder für "`cc-mode`" eine Passphrase mit 64 bis 256 Zeichen.
+
Ist die angegebene Passphrase für den "`cc-mode`" kürzer als 64 Zeichen, tritt eine Verzögerung von fünf Sekunden auf, bevor die Passphrase-Aufforderung im Rahmen der Schlüsselmanager-Einrichtung erneut angezeigt wird.

. Bei der Aufforderung zur Passphrase-Bestätigung wird die Passphrase erneut eingegeben.
. Wenn Sie sich in einer MetroCluster Konfiguration befinden, sollte die aktualisierte Passphrase auf dem Partnercluster synchronisiert werden.
+
.. Die Passphrase auf dem Partnercluster wird synchronisiert, indem der richtige Befehl für die jeweilige ONTAP Version ausgewählt wird:
+
[role="tabbed-block"]
====
.ONTAP 9.6 und höher
--
`security key-manager onboard sync`

--
.ONTAP 9.5 und früher
--
*** In ONTAP 9.5 führen Sie Folgendes aus:
+
`security key-manager setup -sync-metrocluster-config`

*** In ONTAP 9.4 und früheren Versionen sollte nach der Aktualisierung der Passphrase auf dem lokalen Cluster 20 Sekunden gewartet werden, bevor der folgende Befehl auf dem Partnercluster ausgeführt wird:
+
`security key-manager setup`



--
====
.. Geben Sie die neue Passphrase ein, wenn Sie dazu aufgefordert werden.
+
Für beide Cluster muss dieselbe Passphrase verwendet werden.





.Nachdem Sie fertig sind
Die Passphrase für die integrierte Schlüsselverwaltung sollte an einem sicheren Ort außerhalb des Speichersystems für die zukünftige Verwendung aufbewahrt werden.

Schlüsselverwaltungsinformationen sollten manuell gesichert werden, sobald die Passphrase für die integrierte Schlüsselverwaltung geändert wird.

.Verwandte Informationen
* link:backup-key-management-information-manual-task.html["Onboard-Schlüsselverwaltungsinformationen manuell sichern"]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-update-passphrase.html["security key-manager onboard update-passphrase"^]

