---
permalink: encryption-at-rest/configure-external-key-management-overview-concept.html 
sidebar: sidebar 
keywords: external key management, kmip, configure 
summary: 'Sie können einen oder mehrere externe Verschlüsselungsmanagementserver verwenden, um die Schlüssel zu sichern, die das Cluster zum Zugriff auf verschlüsselte Daten verwendet. Ein externer Verschlüsselungsmanagement-Server ist ein Drittanbietersystem in Ihrer Storage-Umgebung, der mithilfe des Key Management Interoperability Protocol (KMIP) Schlüssel zu Nodes bereitstellt.' 
---
= Erfahren Sie mehr über die Konfiguration der externen Schlüsselverwaltung mit ONTAP NetApp Volume Encryption
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen oder mehrere externe Schlüsselverwaltungsserver verwenden, um die Schlüssel zu sichern, die der Cluster für den Zugriff auf verschlüsselte Daten verwendet. Ein externer Schlüsselverwaltungsserver ist ein Drittanbietersystem in Ihrer Speicherumgebung, das Schlüssel für Knoten mithilfe des Key Management Interoperability Protocol (KMIP) bereitstellt. Zusätzlich zum Onboard Key Manager unterstützt ONTAP mehrere externe Schlüsselverwaltungsserver.

Ab ONTAP 9.10.1 können Sie Folgendes verwenden: xref:manage-keys-azure-google-task.html[Azure Key Vault oder Google Cloud Key Manager-Dienst] zum Schutz Ihrer NVE-Schlüssel für Daten-SVMs. Ab ONTAP 9.11.1 können Sie mehrere externe Schlüsselmanager in einem Cluster konfigurieren. Sehenxref:configure-cluster-key-server-task.html[Konfigurieren Sie gruppierte Schlüsselserver] . Ab ONTAP 9.12.0 können Sie Folgendes verwenden: link:https://docs.aws.amazon.com/kms/latest/developerguide/overview.html["KMS VON AWS"^] zum Schutz Ihrer NVE-Schlüssel für Daten-SVMs. Ab ONTAP 9.17.1 können Sie OpenStacks verwenden xref:manage-keys-barbican-task.html[Barbican KMS] zum Schutz Ihrer NVE-Schlüssel für Daten-SVMs.
