---
permalink: encryption-at-rest/configure-external-key-management-concept.html 
sidebar: sidebar 
keywords: external key management, kmip, configure 
summary: 'Sie können einen oder mehrere externe Schlüsselverwaltungsserver verwenden, um die Schlüssel zu sichern, die der Cluster für den Zugriff auf verschlüsselte Daten verwendet. Ein externer Schlüsselverwaltungsserver ist ein Drittanbietersystem in Ihrer Speicherumgebung, das Schlüssel an Nodes mithilfe des Key Management Interoperability Protocol (KMIP) bereitstellt.' 
---
= Informationen zur Konfiguration der externen Schlüsselverwaltung in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen oder mehrere externe Schlüsselverwaltungsserver verwenden, um die Schlüssel zu sichern, die der Cluster für den Zugriff auf verschlüsselte Daten verwendet. Ein externer Schlüsselverwaltungsserver ist ein Drittanbietersystem in Ihrer Speicherumgebung, das Schlüssel an Nodes mithilfe des Key Management Interoperability Protocol (KMIP) bereitstellt.

NetApp Volume Encryption (NVE) kann mit dem Onboard Key Manager implementiert werden. In ONTAP 9.3 und höher kann NVE mit externem Key Management (KMIP) und dem Onboard Key Manager implementiert werden. Ab ONTAP 9.11.1 ist die Konfiguration mehrerer externer Schlüsselmanager in einem Cluster möglich. Siehe xref:configure-cluster-key-server-task.html[Clustered Key-Server konfigurieren.]
