---
permalink: encryption-at-rest/data-seds-inaccessible-concept.html 
sidebar: sidebar 
keywords: sanitize, fips, drive, sed, inaccessible, destroy, psid, physical secure ID, nrd plus, emergency, shred,  drive, sed,  encrypt, destroy 
summary: Wenn Sie Daten auf einem FIPS-Laufwerk oder SED dauerhaft unzugänglich machen möchten, aber den nicht genutzten Speicherplatz des Laufwerks für neue Daten verfügbar halten möchten, können Sie die Festplatte bereinigen. Wenn Sie Daten dauerhaft unzugänglich machen und Sie das Laufwerk nicht wiederverwenden müssen, können Sie es zerstören. 
---
= Machen Sie Daten auf einem FIPS-Laufwerk oder SED unzugänglich Übersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Daten auf einem FIPS- oder SED-Laufwerk dauerhaft nicht zugänglich sind, aber den nicht genutzten Speicherplatz des Laufwerks für neue Daten beibehalten werden sollen, kann die Festplatte bereinigen. Wenn Sie Daten dauerhaft unzugänglich machen und Sie das Laufwerk nicht wiederverwenden müssen, können Sie es zerstören.

* Festplattenbereinigung
+
Wenn Sie ein selbstverschlüsselndes Laufwerk desinfizieren, ändert das System den Verschlüsselungsschlüssel in einen neuen zufälligen Wert, setzt den Einschloß-Status auf false zurück und setzt die Schlüssel-ID auf einen Standardwert, entweder die Herstellersichere ID 0x0 (SAS-Laufwerke) oder einen Null-Schlüssel (NVMe-Laufwerke). Dadurch werden die Daten auf der Festplatte nicht mehr zugänglich und können nicht abgerufen werden. Sie können desinfizierte Festplatten als nicht auf Null bereinigte Ersatzfestplatten wiederverwenden.

* Festplatte zerstören
+
Wenn Sie ein FIPS- oder SED-Laufwerk zerstören, setzt das System den Schlüssel für die Festplattenverschlüsselung auf einen unbekannten zufälligen Wert und sperrt die Festplatte unwiderruflich. Dadurch wird die Festplatte permanent nicht nutzbar und die Daten darauf dauerhaft zugänglich gemacht.



Es können einzelne Self-Encrypting Drives oder alle Self-Encrypting Drives eines Node bereinigen oder zerstört werden.



== Ein FIPS-Laufwerk oder SED infizieren

Wenn Daten auf einem FIPS- oder SED-Laufwerk dauerhaft zugänglich gemacht und das Laufwerk für neue Daten verwendet werden soll, können Sie das verwenden `storage encryption disk sanitize` Befehl zum Löschen des Laufwerks.

.Was Sie benötigen
Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.

.Über diese Aufgabe
Wenn Sie ein selbstverschlüsselndes Laufwerk desinfizieren, ändert das System den Verschlüsselungsschlüssel in einen neuen zufälligen Wert, setzt den Einschloß-Status auf false zurück und setzt die Schlüssel-ID auf einen Standardwert, entweder die Herstellersichere ID 0x0 (SAS-Laufwerke) oder einen Null-Schlüssel (NVMe-Laufwerke). Dadurch werden die Daten auf der Festplatte nicht mehr zugänglich und können nicht abgerufen werden. Sie können desinfizierte Festplatten als nicht auf Null bereinigte Ersatzfestplatten wiederverwenden.

.Schritte
. Migrieren Sie alle Daten, die in einem Aggregat auf einer anderen Festplatte aufbewahrt werden müssen.
. Löschen Sie das Aggregat auf dem FIPS-Laufwerk oder der SED, das bereinigt werden soll:
+
`storage aggregate delete -aggregate _aggregate_name_`

+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
[listing]
----
cluster1::> storage aggregate delete -aggregate aggr1
----
. Festplatten-ID für das zu desinfizierte FIPS-Laufwerk oder SED ermitteln:
+
`storage encryption disk show -fields data-key-id,fips-key-id,owner`

+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
0.0.1   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
1.10.2  data F1CB30AFF1CB30B00101000000000000CF0EFD81EA9F6324EA97B369351C56AC
[...]
----
. Wenn ein FIPS-Laufwerk im FIPS-Compliance-Modus ausgeführt wird, legen Sie die FIPS-Authentifizierungsschlüssel-ID für den Node wieder auf den Standard MSID 0x0:
+
`storage encryption disk modify -disk _disk_id_ -fips-key-id 0x0`

+
Sie können das verwenden `security key-manager query` Befehl zum Anzeigen von Schlüssel-IDs.

+
[listing]
----
cluster1::> storage encryption disk modify -disk 1.10.2 -fips-key-id 0x0

Info: Starting modify on 1 disk.
      View the status of the operation by using the
      storage encryption disk show-status command.
----
. Antrieb desinfizieren:
+
`storage encryption disk sanitize -disk _disk_id_`

+
Mit diesem Befehl können Sie nur Hot-Spare- oder defekte Festplatten bereinigen. Um alle Festplatten unabhängig vom Typ zu desinfizieren, verwenden Sie das `-force-all-state` Option. Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
[NOTE]
====
Sie werden aufgefordert, einen Bestätigungsphrase einzugeben, bevor Sie fortfahren. Geben Sie den Ausdruck genau so ein, wie er auf dem Bildschirm angezeigt wird.

====
+
[listing]
----
cluster1::> storage encryption disk sanitize -disk 1.10.2

Warning: This operation will cryptographically sanitize 1 spare or broken self-encrypting disk on 1 node.
         To continue, enter sanitize disk: sanitize disk

Info: Starting sanitize on 1 disk.
      View the status of the operation using the
      storage encryption disk show-status command.
----




== Ein FIPS-Laufwerk oder SED zerstören

Wenn Daten auf einem FIPS- oder SED-Laufwerk dauerhaft zugänglich gemacht werden sollen und Sie das Laufwerk nicht wiederverwenden müssen, können Sie das verwenden `storage encryption disk destroy` Befehl zum Zerstören der Festplatte.

.Was Sie benötigen
Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.

.Über diese Aufgabe
Wenn Sie ein FIPS- oder SED-Laufwerk zerstören, setzt das System den Schlüssel für die Festplattenverschlüsselung auf einen unbekannten zufälligen Wert und sperrt das Laufwerk unwiderruflich. Dadurch wird die Festplatte praktisch nicht nutzbar und die Daten auf ihr dauerhaft zugänglich. Sie können die Festplatte jedoch mithilfe der physischen sicheren ID (PSID) auf dem Etikett des Datenträgers auf die werkseitig konfigurierten Einstellungen zurücksetzen. Weitere Informationen finden Sie unter link:return-self-encrypting-disks-keys-not-available-task.html["Ein FIPS-Laufwerk oder eine SED-Appliance wird zurückgegeben, wenn Authentifizierungsschlüssel verloren gehen"].

[NOTE]
====
Ein FIPS- oder SED-Laufwerk darf nur zerstört werden, wenn Sie über den Non-Returnable Disk Plus-Service (NRD Plus) verfügen. Beim Zerstören einer Festplatte wird die Gewährleistung nicht mehr abgedeckt.

====
.Schritte
. Migrieren Sie alle Daten, die in einem Aggregat auf einer anderen, unterschiedlichen Festplatte aufbewahrt werden müssen.
. Löschen Sie das Aggregat auf dem zu zerstörenden FIPS-Laufwerk oder SED:
+
`storage aggregate delete -aggregate aggregate_name`

+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
[listing]
----
cluster1::> storage aggregate delete -aggregate aggr1
----
. Identifizieren Sie die Festplatten-ID für das zu zerstörenden FIPS-Laufwerk oder die SED:
+
`storage encryption disk show`

+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
0.0.1   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
1.10.2  data F1CB30AFF1CB30B00101000000000000CF0EFD81EA9F6324EA97B369351C56AC
[...]
----
. Zerstören Sie die Festplatte:
+
`storage encryption disk destroy -disk disk_id`

+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
[NOTE]
====
Sie werden aufgefordert, einen Bestätigungsphrase einzugeben, bevor Sie fortfahren. Geben Sie den Ausdruck genau so ein, wie er auf dem Bildschirm angezeigt wird.

====
+
[listing]
----
cluster1::> storage encryption disk destroy -disk 1.10.2

Warning: This operation will cryptographically destroy 1 spare or broken
         self-encrypting disks on 1 node.
         You cannot reuse destroyed disks unless you revert
         them to their original state using the PSID value.
         To continue, enter
          destroy disk
         :destroy disk

Info: Starting destroy on 1 disk.
      View the status of the operation by using the
      "storage encryption disk show-status" command.
----




== Daten werden im Notfall auf einem FIPS-Laufwerk oder SED geschreddert

Im Falle eines Sicherheitsnotfalls können Sie den Zugriff auf ein FIPS-Laufwerk oder eine SED umgehend verhindern, auch wenn dem Storage-System oder dem KMIP-Server keine Stromversorgung zur Verfügung steht.

.Was Sie benötigen
* Wenn Sie einen KMIP-Server ohne Stromversorgung verwenden, muss der KMIP-Server mit einem einfach zerstörten Authentifizierungselement (z. B. eine Smartcard oder ein USB-Laufwerk) konfiguriert werden.
* Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.


.Schritt
. Daten im Notfall auf einem FIPS-Laufwerk oder SED sreddern:
+
|===


| Wenn... 2+| Dann... 


 a| 
Das Storage-System verfügt über einen Stromanstieg, und Sie können das Storage-System normal offline schalten
 a| 
.. Wenn das Storage-System als HA-Paar konfiguriert ist, deaktivieren Sie Takeover.
.. Alle Aggregate offline schalten und löschen.
.. Stellen Sie die Berechtigungsebene auf Erweiteriert: + ein
`set -privilege advanced`
.. Wenn sich das Laufwerk im FIPS-Compliance-Modus befindet, setzen Sie die FIPS-Authentifizierungsschlüssel-ID für den Node wieder auf die Standard-MSID: +
`storage encryption disk modify -disk * -fips-key-id 0x0`
.. Stoppen Sie das Speichersystem.
.. Booten Sie im Wartungsmodus.
.. Desinfizieren oder zerstören Sie die Festplatten:
+
*** Wenn Sie die Daten auf den Datenträgern unzugänglich machen und die Festplatten dennoch wiederverwenden können, desinfizieren Sie die Festplatten: +
`disk encrypt sanitize -all`
*** Wenn Sie die Daten auf den Laufwerken unzugänglich machen möchten und Sie die Festplatten nicht speichern müssen, zerstören Sie die Festplatten: +
`disk encrypt destroy disk_id1 disk_id2 …`


+
[NOTE]
====
Der `disk encrypt sanitize` Und `disk encrypt destroy` Befehle sind nur für den Wartungsmodus reserviert. Diese Befehle müssen auf jedem HA-Node ausgeführt werden und sind nicht für fehlerhafte Festplatten verfügbar.

====
.. Wiederholen Sie diese Schritte für den Partner-Node. Dadurch verlässt das Speichersystem den Status „dauerhaft deaktiviert“, wobei alle Daten gelöscht werden. Um das System erneut zu verwenden, müssen Sie es neu konfigurieren.




 a| 
Dem Storage-System steht Strom zur Verfügung, und Sie müssen die Daten sofort schüttelt haben
 a| 
.. *Wenn Sie die Daten auf den Datenträgern unzugänglich machen und die Festplatten noch wiederverwenden können, desinfizieren Sie die Festplatten:*
.. Wenn das Storage-System als HA-Paar konfiguriert ist, deaktivieren Sie Takeover.
.. Legen Sie die Berechtigungsebene auf erweitert fest:
+
`set -privilege advanced`

.. Wenn sich das Laufwerk im FIPS-Compliance-Modus befindet, legen Sie die FIPS-Authentifizierungsschlüssel-ID für den Node wieder auf die Standard-MSID fest:
+
`storage encryption disk modify -disk * -fips-key-id 0x0`

.. Festplatte bereinigen:
+
`storage encryption disk sanitize -disk * -force-all-states true`


 a| 
.. *Wenn Sie die Daten auf den Datenträgern unzugänglich machen und Sie nicht brauchen, um die Festplatten zu speichern, zerstören Sie die Festplatten:*
.. Wenn das Storage-System als HA-Paar konfiguriert ist, deaktivieren Sie Takeover.
.. Legen Sie die Berechtigungsebene auf erweitert fest:
+
`set -privilege advanced`

.. Zerstören Sie die Festplatten:
`storage encryption disk destroy -disk * -force-all-states true`




 a| 
Das Speichersystem kommt zu einer Panik, sodass das System dauerhaft deaktiviert ist, während alle Daten gelöscht werden. Um das System erneut zu verwenden, müssen Sie es neu konfigurieren.



 a| 
Der KMIP-Server mit Strom ist, nicht jedoch für das Storage-System verfügbar
 a| 
.. Melden Sie sich beim KMIP-Server an.
.. Vernichten Sie alle Schlüssel, die den FIPS-Laufwerken oder SEDs zugeordnet sind, die die Daten enthalten, auf die Sie Zugriff verhindern möchten. Dadurch wird der Zugriff auf die Festplattenverschlüsselung durch das Speichersystem verhindert.




 a| 
Der KMIP-Server oder das Storage-System bieten keine Stromversorgung
 a| 
Zerstören Sie das Authentifizierungselement für den KMIP-Server (z. B. die Smart Card). Dadurch wird der Zugriff auf die Festplattenverschlüsselung durch das Speichersystem verhindert.

|===
+
Eine vollständige Befehlssyntax finden Sie in den man-Pages.


