---
permalink: encryption-at-rest/data-seds-inaccessible-concept.html 
sidebar: sidebar 
keywords: sanitize, fips, drive, sed, inaccessible, destroy, psid, physical secure ID, nrd plus, emergency, shred,  drive, sed,  encrypt, destroy 
summary: Wenn Sie Daten auf einem FIPS-Laufwerk oder einem SED dauerhaft unzugänglich machen möchten, der ungenutzte Speicherplatz jedoch für neue Daten verfügbar bleiben soll, kann das Laufwerk bereinigt werden. Wenn Daten dauerhaft unzugänglich gemacht werden sollen und eine Wiederverwendung des Laufwerks nicht erforderlich ist, kann es zerstört werden. 
---
= Informationen darüber, wie ONTAP Daten auf einem FIPS-Laufwerk oder SED unzugänglich gemacht werden können
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie Daten auf einem FIPS-Laufwerk oder Self-Encrypting Drive dauerhaft unzugänglich machen möchten, der ungenutzte Speicherplatz jedoch für neue Daten verfügbar bleiben soll, kann das Laufwerk bereinigt werden. Wenn Daten dauerhaft unzugänglich gemacht werden sollen und eine Wiederverwendung des Laufwerks nicht erforderlich ist, kann es zerstört werden.

* Datenträgerbereinigung
+
Beim Bereinigen eines Self-Encrypting Drives ändert das System den Verschlüsselungsschlüssel auf einen neuen Zufallswert, setzt den Sperrzustand beim Einschalten auf „false“ und setzt die Schlüssel-ID auf einen Standardwert, entweder die Hersteller Secure ID 0x0 (SAS-Laufwerke) oder einen Null-Schlüssel (NVMe-Laufwerke). Dadurch sind die Daten auf dem Laufwerk unzugänglich und können nicht wiederhergestellt werden. Bereinigte Laufwerke können als nicht mit Nullen überschriebene Ersatzlaufwerke wiederverwendet werden.

* Datenträger zerstören
+
Wenn Sie ein FIPS-Laufwerk oder ein Self-Encrypting Drive zerstören, setzt das System den Festplattenverschlüsselungsschlüssel auf einen unbekannten Zufallswert und sperrt die Festplatte unwiderruflich. Dadurch wird die Festplatte dauerhaft unbrauchbar und die darauf befindlichen Daten sind dauerhaft unzugänglich.



Es besteht die Möglichkeit, einzelne Self-Encrypting Drives zu bereinigen oder zu zerstören oder alle Self-Encrypting Drives eines Knotens zu zerstören.
