---
permalink: encryption-at-rest/delete-encrypted-volume-task.html 
sidebar: sidebar 
keywords: deleting, encrypted, volume 
summary: Mit dem Befehl volume delete lässt sich ein verschlüsseltes Volume löschen. 
---
= Löschen eines verschlüsselten Volumes in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit dem  `volume delete` Befehl lässt sich ein verschlüsseltes Volume löschen.

.Bevor Sie beginnen
* Sie müssen Cluster-Administrator sein, um diese Aufgabe ausführen zu können.
* Das Volume muss offline sein.


.Schritt
. Löschen eines verschlüsselten Volumes:
+
`volume delete -vserver _SVM_name_ -volume _volume_name_`

+
Weitere Informationen zu  `volume delete` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-delete.html["ONTAP-Befehlsreferenz"^].

+
Der folgende Befehl löscht ein verschlüsseltes Volume mit dem Namen  `vol1`:

+
[listing]
----
cluster1::> volume delete -vserver vs1 -volume vol1
----
+
Geben Sie  `yes` ein, wenn Sie zur Bestätigung der Löschung aufgefordert werden.

+
Das System löscht den Verschlüsselungsschlüssel für das Volume nach 24 Stunden.

+
Verwenden Sie  `volume delete` mit der  `-force true` Option, um ein Volume zu löschen und den entsprechenden Verschlüsselungsschlüssel sofort zu zerstören. Dieser Befehl erfordert erweiterte Berechtigungen. Weitere Informationen zu  `volume delete` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-delete.html["ONTAP-Befehlsreferenz"^].



.Nachdem Sie fertig sind
Mit dem  `volume recovery-queue` Befehl kann ein gelöschtes Volume während der Aufbewahrungsfrist nach Ausführung des  `volume delete` Befehls wiederhergestellt werden:

`volume recovery-queue _SVM_name_ -volume _volume_name_`

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_use_the_Volume_Recovery_Queue["Verwendung der Volume Recovery Funktion"^]
