---
permalink: encryption-at-rest/enable-encryption-new-volume-task.html 
sidebar: sidebar 
keywords: encryption, new volume, NAE, NVE, volume create 
summary: Mit dem Befehl volume create lässt sich die Verschlüsselung auf einem neuen Volume aktivieren. 
---
= Verschlüsselung auf einem neuen Volume in ONTAP aktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit dem  `volume create` Befehl lässt sich die Verschlüsselung auf einem neuen Volume aktivieren.

.Über diese Aufgabe
Volumes lassen sich mit NetApp Volume Encryption (NVE) und ab ONTAP 9.6 mit NetApp Aggregate Encryption (NAE) verschlüsseln. Weitere Informationen zu NAE und NVE enthält die xref:configure-netapp-volume-encryption-concept.html[Übersicht zur Volumenverschlüsselung].

Weitere Informationen zu den in diesem Verfahren beschriebenen Befehlen befinden sich in der link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP-Befehlsreferenz"^].

Die Vorgehensweise zum Aktivieren der Verschlüsselung auf einem neuen Volume in ONTAP variiert je nach verwendeter ONTAP-Version und Ihrer spezifischen Konfiguration:

* Ab ONTAP 9.4, wenn beim Einrichten des Onboard Key Managers  `cc-mode` aktiviert wird, werden Volumes, die mit dem  `volume create` Befehl erstellt werden, automatisch verschlüsselt, unabhängig davon, ob  `-encrypt true` angegeben wird.
* In ONTAP 9.6 und früheren Versionen muss  `-encrypt true` mit  `volume create` Befehlen die Verschlüsselung aktiviert werden (sofern  `cc-mode` nicht aktiviert wurde).
* Wenn in ONTAP 9.6 ein NAE-Volume erstellt werden soll, muss NAE auf Aggregatebene aktiviert werden. Weitere Details zu dieser Aufgabe sind unter xref:enable-aggregate-level-encryption-nve-license-task.html[Verschlüsselung auf Aggregatebene mit der VE-Lizenz aktivieren] zu finden.
* Ab ONTAP 9.7 werden neu erstellte Volumes standardmäßig verschlüsselt, wenn die link:../encryption-at-rest/install-license-task.html["VE-Lizenz"] sowie eine integrierte oder externe Schlüsselverwaltung vorhanden sind. Standardmäßig sind neue Volumes, die in einem NAE Aggregat erstellt werden, vom Typ NAE statt NVE.
+
** In ONTAP 9.7 und späteren Versionen, wenn  `-encrypt true` zum  `volume create`-Befehl hinzugefügt wird, um ein Volume in einem NAE-Aggregat zu erstellen, erhält das Volume NVE-Verschlüsselung anstelle von NAE. Alle Volumes in einem NAE-Aggregat müssen entweder mit NVE oder NAE verschlüsselt sein.





NOTE: Klartext-Volumes werden in NAE Aggregaten nicht unterstützt.

.Schritte
. Ein neues Volume erstellen und angeben, ob die Verschlüsselung für das Volume aktiviert ist. Befindet sich das neue Volume in einem NAE Aggregat, ist das Volume standardmäßig ein NAE Volume:
+
[cols="25,75"]
|===


| Zum Erstellen... | Verwenden Sie diesen Befehl... 


 a| 
Ein NAE Volume
 a| 
`volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_`



 a| 
Ein NVE Volume
 a| 
`volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_ -encrypt true` +


NOTE: In ONTAP 9.6 und früher, wo NAE nicht unterstützt wird,  `-encrypt true` gibt an, dass das Volume mit NVE verschlüsselt werden soll. In ONTAP 9.7 und später, wo Volumes in NAE Aggregaten erstellt werden,  `-encrypt true` überschreibt den Standardverschlüsselungstyp von NAE, sodass stattdessen ein NVE Volume erstellt wird.



 a| 
Ein einfaches Text-Volume
 a| 
`volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_ -encrypt false`

|===
+
Weitere Informationen zu  `volume create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["ONTAP-Befehlsreferenz"^].

. Überprüfen, ob Volumes für die Verschlüsselung aktiviert sind:
+
`volume show -is-encrypted true`

+
Weitere Informationen zu  `volume show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-show.html["ONTAP-Befehlsreferenz"^].



.Ergebnis
Wenn ein KMIP-Server zum Speichern der Verschlüsselungsschlüssel für einen Knoten verwendet wird, überträgt ONTAP automatisch einen Verschlüsselungsschlüssel an den Server, wenn ein Volume verschlüsselt wird.
