---
permalink: encryption-at-rest/enable-onboard-key-management-new-nodes-concept.html 
sidebar: sidebar 
keywords: onboard key management, onboard new nodes, okm, encrypt 
summary: Mit dem Onboard Key Manager können Sie die Schlüssel sichern, die der Cluster für den Zugriff auf verschlüsselte Daten verwendet. Der Onboard Key Manager muss auf jedem Cluster aktiviert sein, der auf ein verschlüsseltes Volume oder eine selbstverschlüsselnde Festplatte zugreift. 
---
= Integrierte Schlüsselverwaltung in neu hinzugefügten ONTAP Knoten aktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit dem Onboard Key Manager können Sie die Schlüssel sichern, die der Cluster für den Zugriff auf verschlüsselte Daten verwendet. Der Onboard Key Manager muss auf jedem Cluster aktiviert sein, der auf ein verschlüsseltes Volume oder eine selbstverschlüsselnde Festplatte zugreift.

[NOTE]
====
Für ONTAP 9.6 und höher ist der  `security key-manager onboard sync` Befehl jedes Mal auszuführen, wenn dem Cluster ein Knoten hinzugefügt wird.

Bei ONTAP 9.5 und älteren Versionen muss der  `security key-manager setup` Befehl jedes Mal ausgeführt werden, wenn ein Knoten zum Cluster hinzugefügt wird.

Wenn Sie einen Knoten zu einem Cluster mit integrierter Schlüsselverwaltung hinzufügen, kann dieser Befehl ausgeführt werden, um fehlende Schlüssel zu aktualisieren.

====
Bei einer MetroCluster Konfiguration gelten folgende Richtlinien:

* Ab ONTAP 9.6 muss  `security key-manager onboard enable`zuerst auf dem lokalen Cluster und dann  `security key-manager onboard sync`auf dem Remote-Cluster ausgeführt werden, wobei auf beiden Clustern dieselbe Passphrase verwendet wird.
+
Weitere Informationen zu  `security key-manager onboard enable` und  `security key-manager onboard sync` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+key-manager+onboard["ONTAP-Befehlsreferenz"^].

* In ONTAP 9.5 muss  `security key-manager setup` auf dem lokalen Cluster und  `security key-manager setup -sync-metrocluster-config yes` auf dem Remote-Cluster ausgeführt werden, wobei auf beiden Clustern dieselbe Passphrase verwendet wird.
* Vor ONTAP 9.5 muss  `security key-manager setup` auf dem lokalen Cluster ausgeführt werden, etwa 20 Sekunden gewartet werden und dann  `security key-manager setup` auf dem Remote-Cluster ausgeführt werden, wobei jeweils die gleiche Passphrase verwendet wird.


Standardmäßig ist die Eingabe der Passphrase für den Schlüsselmanager beim Neustart eines Knotens nicht erforderlich. Ab ONTAP 9.4 kann die  `-enable-cc-mode yes` Option verwendet werden, um zu verlangen, dass Benutzer die Passphrase nach einem Neustart eingeben.

Für NVE: Wenn  `-enable-cc-mode yes` gesetzt ist, werden Volumes, die Sie mit den Befehlen  `volume create` und  `volume move start` erstellen, automatisch verschlüsselt. Für  `volume create` muss  `-encrypt true` nicht angegeben werden. Für  `volume move start` muss  `-encrypt-destination true` nicht angegeben werden.

[NOTE]
====
Wenn der Passphrasenversuch fehlschlägt, sollte der Knoten neu gestartet werden. Nach dem Neustart besteht die Möglichkeit, die Passphrase erneut einzugeben.

====
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=cluster+image["Cluster Image-Befehle"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-external-enable.html["security key-manager external enable"^]
* link:https://docs.netapp.com/us-en/ontap-cli//security-key-manager-onboard-enable.html["security key-manager onboard enable"^]

