---
permalink: encryption-at-rest/enable-onboard-key-management-96-later-nse-task.html 
sidebar: sidebar 
keywords: enabling, onboard key management, ontap 9.6, later 
summary: Mit dem integrierten Key Manager werden die Schlüssel gesichert, die das Cluster für den Zugriff auf verschlüsselte Daten verwendet. Sie müssen Onboard Key Manager für jedes Cluster aktivieren, das auf ein verschlüsseltes Volume oder eine selbstverschlüsselnde Festplatte zugreift. 
---
= Ermöglichen Sie integriertes Verschlüsselungsmanagement in ONTAP 9.6 und höher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit dem Onboard Key Manager können Clusterknoten auf einem FIPS-Laufwerk oder SED authentifiziert werden. Der integrierte Onboard Key Manager ist ein Tool, das Authentifizierungsschlüssel für Nodes aus demselben Storage-System wie Ihre Daten bereitstellt. Der Onboard Key Manager ist nach FIPS-140-2 Level 1 zertifiziert.

Mit dem integrierten Key Manager werden die Schlüssel gesichert, die das Cluster für den Zugriff auf verschlüsselte Daten verwendet. Sie müssen Onboard Key Manager für jedes Cluster aktivieren, das auf ein verschlüsseltes Volume oder eine selbstverschlüsselnde Festplatte zugreift.

.Über diese Aufgabe
Sie müssen den `security key-manager onboard enable` Befehl jedes Mal ausführen, wenn Sie dem Cluster einen Node hinzufügen. In MetroCluster-Konfigurationen müssen Sie `security key-manager onboard enable` zuerst auf dem lokalen Cluster ausführen und dann `security key-manager onboard sync` auf dem Remote-Cluster unter Verwendung derselben Passphrase auf beiden ausführen.

Erfahren Sie mehr über `security key-manager onboard enable` und `security key-manager onboard sync` in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+key-manager+onboard["ONTAP-Befehlsreferenz"^].

Standardmäßig müssen Sie beim Neustart eines Node nicht die Passphrase für das Schlüsselmanagement eingeben. Mit Ausnahme von MetroCluster können Sie die `cc-mode-enabled=yes` Option verwenden, um zu verlangen, dass Benutzer die Passphrase nach einem Neustart eingeben.

[NOTE]
====
Wenn der Onboard Key Manager im Common Criteria-Modus aktiviert ist(`cc-mode-enabled=yes`, wird das Systemverhalten wie folgt geändert:

* Das System überwacht bei der Verwendung im Common Criteria-Modus auf aufeinanderfolgende fehlgeschlagene Cluster-Passphrase.
+
Wenn NetApp Storage Encryption (NSE) aktiviert ist und Sie beim Booten nicht die richtige Cluster-Passphrase eingeben, kann sich das System nicht auf seinen Laufwerken authentifizieren und automatisch neu starten. Um dies zu korrigieren, müssen Sie an der Boot-Eingabeaufforderung die richtige Cluster-Passphrase eingeben. Sobald das System gebootet wurde, können bis zu 5 aufeinanderfolgende Versuche unternommen werden, um für jeden Befehl, für den die Cluster-Passphrase als Parameter erforderlich ist, in einem Zeitraum von 24 Stunden korrekt einzugeben. Wenn das Limit erreicht wird (beispielsweise konnten Sie den Cluster-Passphrase 5 Mal hintereinander nicht korrekt eingeben), müssen Sie entweder warten, bis der 24-Stunden-Timeout abgelaufen ist, oder Sie müssen den Node neu booten, um das Limit zurückzusetzen.

* Updates für das System-Image nutzen das Code-Signing-Zertifikat von NetApp RSA-3072 zusammen mit dem von SHA-384 signierten Code, um die Image-Integrität anstelle des üblichen NetApp RSA-2048-Code-Signaturzertifikats und den von SHA-256 signierten Digests zu überprüfen.
+
Der Upgrade-Befehl überprüft, ob der Bildinhalt durch Überprüfen verschiedener digitaler Signaturen nicht verändert oder beschädigt wurde. Der Image-Aktualisierungsprozess wird mit dem nächsten Schritt fortgesetzt, wenn die Validierung erfolgreich ist. Andernfalls schlägt die Image-Aktualisierung fehl. Erfahren Sie mehr über `cluster image` in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=cluster+image["ONTAP-Befehlsreferenz"^].



====

NOTE: Der Onboard Key Manager speichert Schlüssel im volatilen Speicher. Der Inhalt von flüchtigem Speicher wird gelöscht, wenn das System neu gestartet oder angehalten wird. Unter normalen Betriebsbedingungen wird der Inhalt von flüchtigem Speicher innerhalb von 30 s gelöscht, wenn ein System angehalten wird.

.Bevor Sie beginnen
* Wenn Sie NSE mit einem externen KMIP-Server (Key Management) verwenden, müssen Sie die externe Schlüsselmanager-Datenbank gelöscht haben.
+
link:delete-key-management-database-task.html["Umstellung auf integriertes Verschlüsselungsmanagement von externem Verschlüsselungsmanagement"]

* Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.
* Sie müssen die MetroCluster Umgebung konfigurieren, bevor der Onboard Key Manager konfiguriert wird.


.Schritte
. Starten Sie den Key Manager Setup-Befehl:
+
`security key-manager onboard enable -cc-mode-enabled yes|no`

+

NOTE: Legen Sie fest `cc-mode-enabled=yes`, dass Benutzer nach einem Neustart die Passphrase für den Schlüsselmanager eingeben müssen. Die `- cc-mode-enabled` Option wird in MetroCluster-Konfigurationen nicht unterstützt. Der `security key-manager onboard enable` Befehl ersetzt den `security key-manager setup` Befehl.

+
Das folgende Beispiel startet den Befehl zum Einrichten des Schlüsselmanagers in cluster1, ohne dass nach jedem Neustart die Passphrase eingegeben werden muss:

+
[listing]
----
cluster1::> security key-manager onboard enable

Enter the cluster-wide passphrase for onboard key management in Vserver "cluster1"::    <32..256 ASCII characters long text>
Reenter the cluster-wide passphrase:    <32..256 ASCII characters long text>
----
. Geben Sie an der Eingabeaufforderung für die Passphrase eine Passphrase zwischen 32 und 256 Zeichen oder für „`cc-Mode`“ eine Passphrase zwischen 64 und 256 Zeichen ein.
+

NOTE: Wenn die angegebene „`cc-Mode`“-Passphrase weniger als 64 Zeichen beträgt, liegt eine Verzögerung von fünf Sekunden vor, bevor die Eingabeaufforderung für das Setup des Schlüsselmanagers die Passphrase erneut anzeigt.

. Geben Sie die Passphrase erneut an der Eingabeaufforderung zur Bestätigung der Passphrase ein.
. Vergewissern Sie sich, dass die Authentifizierungsschlüssel erstellt wurden:
+
`security key-manager key query -node node`

+

NOTE: Der `security key-manager key query` Befehl ersetzt den `security key-manager query key` Befehl.

+
Im folgenden Beispiel wird überprüft, ob Authentifizierungsschlüssel für erstellt `cluster1` wurden:

+
[listing]
----
cluster1::> security key-manager key query
       Vserver: cluster1
   Key Manager: onboard
          Node: node1

Key Tag                               Key Type  Restored
------------------------------------  --------  --------
node1                                 NSE-AK    yes
    Key ID: <id_value>
node1                                 NSE-AK    yes
    Key ID: <id_value>

       Vserver: cluster1
   Key Manager: onboard
          Node: node2

Key Tag                               Key Type  Restored
------------------------------------  --------  --------
node1                                 NSE-AK    yes
    Key ID: <id_value>
node2                                 NSE-AK    yes
    Key ID: <id_value>
----
+
Erfahren Sie mehr über `security key-manager key query` in der link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-query.html?q=security+key-manager+key+query["ONTAP-Befehlsreferenz"^].



.Nachdem Sie fertig sind
Kopieren Sie die Passphrase zur späteren Verwendung an einen sicheren Ort außerhalb des Storage-Systems.

Alle Informationen zum Verschlüsselungsmanagement werden automatisch in der replizierten Datenbank (RDB) für den Cluster gesichert. Sie sollten die Informationen auch manuell für den Notfall sichern.

.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-setup.html["Einrichtung des Sicherheitsschlüssel-Managers"^]

