---
permalink: encryption-at-rest/enable-root-volume-encryption-task.html 
sidebar: sidebar 
keywords: root, volume, encryption, enabling, node 
summary: Ab ONTAP 9.8 können Sie NetApp Volume Encryption zum Schutz des Root-Volumes des Nodes verwenden. 
---
= Node-Root-Volume-Verschlüsselung aktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.8 können Sie NetApp Volume Encryption zum Schutz des Root-Volumes des Nodes verwenden.

.Was Sie benötigen
* Ihr System muss eine HA-Konfiguration verwenden.
+
Die Root-Volume-Verschlüsselung wird in Konfigurationen mit einem Node nicht unterstützt.

* Das Root-Volume des Nodes muss bereits erstellt werden.
* Ihr System muss über einen integrierten Schlüsselmanager oder einen externen Verschlüsselungsmanagement-Server mit dem Key Management Interoperability Protocol (KMIP) verfügen.


[NOTE]
.Über diese Aufgabe
====
Dieses Verfahren gilt für das Root-Volume des Nodes. Sie gilt nicht für SVM-Root-Volumes. SVM-Root-Volumes können durch Verschlüsselung auf Aggregatebene gesichert werden.

====
Sobald die Verschlüsselung des Root-Volumes beginnt, muss sie abgeschlossen sein. Sie können den Vorgang nicht unterbrechen. Nach Abschluss der Verschlüsselung können Sie dem Root-Volume keinen neuen Schlüssel zuweisen und keine sichere Löschung durchführen.

.Schritte
. Verschlüsseln Sie das Root-Volume:
+
`volume encryption conversion start -vserver SVM_name -volume root_vol_name`

. Überprüfen Sie den Status des Konvertierungsvorgangs:
+
`volume encryption conversion show`

. Nach Abschluss des Konvertierungsvorgangs muss überprüft werden, ob das Volume verschlüsselt ist:
+
`volume show -fields`

+
Das folgende zeigt eine Beispielausgabe für ein verschlüsseltes Volume.

+
[listing]
----
::> volume show -vserver xyz  -volume vol0 -fields is-encrypted
vserver    volume is-encrypted
---------- ------ ------------
xyz        vol0   true
----

