---
permalink: encryption-at-rest/enable-encryption-existing-volume-93-later-task.html 
sidebar: sidebar 
keywords: enabling, encryption, existing, volume encryption conversion start, command 
summary: Ab ONTAP 9.3 kann mit dem Befehl „volume encryption conversion start“ die Verschlüsselung eines vorhandenen Volumes „in place“ aktiviert werden, ohne das volSume an einen anderen Speicherort verschieben zu müssen. 
---
= Aktivieren der Verschlüsselung auf einem vorhandenen Volume mit dem Befehl „volume encryption conversion start“ in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.3 kann mit dem  `volume encryption conversion start` Befehl die Verschlüsselung eines vorhandenen Volumes „an Ort und Stelle“ aktiviert werden, ohne dass das Volume an einen anderen Speicherort verschoben werden muss.

.Über diese Aufgabe
Sobald Sie eine Konvertierung starten, muss diese abgeschlossen werden. Wenn während des Vorgangs Leistungsprobleme auftreten, kann der Vorgang mit dem  `volume encryption conversion pause` Befehl angehalten und mit dem  `volume encryption conversion resume` Befehl fortgesetzt werden.

Ab ONTAP 9.14.1 kann  `volume encryption conversion start` auf einem SVM Root-Volume verwendet werden. Weitere Informationen finden sich unter xref:configure-nve-svm-root-task.html[Konfiguration der NetApp Volume Encryption auf einem SVM Root-Volume].


NOTE: Sie können  `volume encryption conversion start`nicht verwenden, um ein SnapLock-Volumen zu konvertieren.

.Schritte
. Verschlüsselung für ein vorhandenes Volume aktivieren:
+
`volume encryption conversion start -vserver _svm_name_ -volume _volume_name_`

+
Weitere Informationen zu  `volume encryption conversion start` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-encryption-conversion-start.html["ONTAP-Befehlsreferenz"^].

+
Der folgende Befehl aktiviert die Verschlüsselung des vorhandenen Volumes `vol1`:

+
[listing]
----
cluster1::> volume encryption conversion start -vserver vs1 -volume vol1
----
+
Das System erstellt einen Verschlüsselungsschlüssel für das Volume. Die Daten auf dem Volume sind verschlüsselt.

. Status des Konvertierungsvorgangs überprüfen:
+
`volume encryption conversion show`

+
Weitere Informationen zu  `volume encryption conversion show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-encryption-conversion-show.html["ONTAP-Befehlsreferenz"^].

+
Der folgende Befehl zeigt den Status des Konvertierungsvorgangs an:

+
[listing]
----
cluster1::> volume encryption conversion show

Vserver   Volume   Start Time           Status
-------   ------   ------------------   ---------------------------
vs1       vol1     9/18/2017 17:51:41   Phase 2 of 2 is in progress.
----
. Nach Abschluss der Konvertierung kann überprüft werden, ob das Volume für die Verschlüsselung aktiviert ist:
+
`volume show -is-encrypted true`

+
Weitere Informationen zu  `volume show -is-encrypted true` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli//volume-show.html#parameters["ONTAP-Befehlsreferenz"^].

+
Der folgende Befehl zeigt die verschlüsselten Volumes auf  `cluster1` an:

+
[listing]
----
cluster1::> volume show -is-encrypted true

Vserver  Volume  Aggregate  State  Type  Size  Available  Used
-------  ------  ---------  -----  ----  -----  --------- ----
vs1      vol1    aggr2     online    RW  200GB    160.0GB  20%
----


.Ergebnis
Wenn ein KMIP-Server zum Speichern der Verschlüsselungsschlüssel für einen Knoten verwendet wird, überträgt ONTAP automatisch einen Verschlüsselungsschlüssel an den Server, wenn ein Volume verschlüsselt wird.
