---
permalink: encryption-at-rest/install-license-task.html 
sidebar: sidebar 
keywords: install, license, VE license, NVE, encryption, encrypt data 
summary: Eine VE-Lizenz berechtigt Sie zur Nutzung der Funktion auf allen Knoten im Cluster. Sie müssen überprüfen, ob die Lizenz installiert ist, bevor Sie Daten mit NVE verschlüsseln können. 
---
= Installieren der Volume-Verschlüsselungslizenz auf einem ONTAP Cluster
:allow-uri-read: 


[role="lead"]
Eine VE-Lizenz berechtigt Sie zur Nutzung der Funktion auf allen Knoten im Cluster. Diese Lizenz ist erforderlich, bevor Sie Daten mit NVE verschlüsseln können. Es ist im Lieferumfang enthaltenlink:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"].

Vor ONTAP One war die VE-Lizenz im Verschlüsselungspaket enthalten. Das Encryption Bundle wird nicht mehr angeboten, ist aber weiterhin gültig. Obwohl derzeit nicht erforderlich, können Bestandskunden wählenlink:../system-admin/download-nlf-task.html["Upgrade auf ONTAP One"].

.Bevor Sie beginnen
* Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.
* Sie müssen den VE-Lizenzschlüssel von Ihrem Vertriebsmitarbeiter erhalten haben oder ONTAP One installiert haben.


.Schritte
. link:../system-admin/manage-license-task.html["Überprüfen Sie, ob die VE-Lizenz installiert ist"].
+
Der Name des VE-Lizenzpakets lautet `VE`.

. Wenn die Lizenz nicht installiert ist, link:../system-admin/install-license-task.html["Verwenden Sie System Manager oder die ONTAP CLI, um sie zu installieren"].

