---
permalink: encryption-at-rest/install-ssl-certificates-task.html 
sidebar: sidebar 
keywords: install, ssl, certificates, cluster 
summary: Der Cluster und der KMIP-Server verwenden KMIP SSL-Zertifikate, um die Identität des anderen zu überprüfen und eine SSL-Verbindung herzustellen. Vor dem Konfigurieren der SSL-Verbindung mit dem KMIP-Server müssen die KMIP-Client-SSL-Zertifikate für das Cluster und das öffentliche SSL-Zertifikat für die Root-Zertifizierungsstelle des KMIP-Servers installiert werden. 
---
= Installieren Sie SSL-Zertifikate auf dem Cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Cluster und der KMIP-Server verwenden KMIP SSL-Zertifikate, um die Identität des jeweils anderen zu überprüfen und eine SSL-Verbindung herzustellen. Vor dem Konfigurieren der SSL-Verbindung mit dem KMIP-Server müssen die KMIP-Client-SSL-Zertifikate für das Cluster und das öffentliche SSL-Zertifikat für die Root-Zertifizierungsstelle des KMIP-Servers installiert werden.

.Was Sie und#8217;ll benötigen
* Die Zeit muss auf dem Server synchronisiert werden, der die Zertifikate, den KMIP-Server und das Cluster erstellt.
* Sie müssen das öffentliche SSL KMIP-Client-Zertifikat für den Cluster erhalten haben.
* Sie müssen den privaten Schlüssel für das SSL KMIP Client-Zertifikat für das Cluster erhalten haben.
+
Das SSL KMIP-Client-Zertifikat darf nicht durch ein Passwort geschützt sein.

* Sie müssen das öffentliche SSL-Zertifikat für die Root-Zertifizierungsstelle (CA) des KMIP-Servers erhalten haben.


[NOTE]
====
Sie können die Client- und Serverzertifikate vor oder nach der Installation der Zertifikate auf dem Cluster auf dem KMIP-Server installieren.

====
In einem HA-Paar müssen beide Nodes dieselben öffentlichen und privaten KMIP-SSL-Zertifikate verwenden. Wenn Sie mehrere HA-Paare mit demselben KMIP-Server verbinden, müssen alle Nodes der HA-Paare dieselben öffentlichen und privaten KMIP-SSL-Zertifikate verwenden.

.Schritte
. Installieren Sie die SSL KMIP-Client-Zertifikate für das Cluster:
+
`security certificate install -vserver admin_svm_name -type client`

+
Sie werden aufgefordert, die öffentlichen und privaten SSL KMIP-Zertifikate einzugeben.

+
`cluster1::> security certificate install -vserver cluster1 -type client`

. Installieren Sie das öffentliche SSL-Zertifikat für die Root-Zertifizierungsstelle (CA) des KMIP-Servers:
+
`security certificate install -vserver admin_svm_name -type server-ca`

+
`cluster1::> security certificate install -vserver cluster1 -type server-ca`


