---
permalink: encryption-at-rest/luster-version-support-nve-task.html 
sidebar: sidebar 
keywords: determining, whether, cluster, version, supports, nve 
summary: Sie sollten vor der Installation der Lizenz festlegen, ob Ihre Cluster-Version NVE unterstützt. Sie können die Cluster-Version mit dem Befehl Version bestimmen. 
---
= Bestimmen Sie, ob Ihre Cluster-Version NVE unterstützt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten vor der Installation der Lizenz festlegen, ob Ihre Cluster-Version NVE unterstützt. Sie können das verwenden `version` Befehl zum Bestimmen der Cluster-Version.

.Über diese Aufgabe
Die Cluster-Version ist die niedrigste Version von ONTAP, die auf einem beliebigen Node im Cluster ausgeführt wird.

.Schritt
. Bestimmen Sie, ob Ihre Cluster-Version NVE unterstützt:
+
`version -v`

+
NVE wird nicht unterstützt, wenn in der Befehlsausgabe der Text „`1Ono-DARE`“ (für „`no Data at Rest Encryption`“) angezeigt wird oder wenn Sie eine Plattform verwenden, die nicht in aufgeführt ist link:configure-netapp-volume-encryption-concept.html#support-details["Support-Details"].

+
Mit dem folgenden Befehl wird festgelegt, ob NVE unterstützt wird `cluster1`.

+
[listing]
----
cluster1::> version -v
NetApp Release 9.1.0: Tue May 10 19:30:23 UTC 2016 <1Ono-DARE>
----
+
Die Ausgabe von `1Ono-DARE` Gibt an, dass NVE bei Ihrer Cluster-Version nicht unterstützt wird.


