---
permalink: encryption-at-rest/manage-keys-azure-google-task.html 
sidebar: sidebar 
keywords: Azure, AKV, key vault, NVE keys, third-party, GCP, google cloud, Cloud KMS, AWS, amazon 
summary: Nutzen Sie den Azure, Google Cloud oder AWS Schlüsselmanager, um den Schutz Ihrer ONTAP-Schlüssel zu optimieren. 
---
= Verwalten Sie NVE-Schlüssel für ONTAP -Daten-SVMs mit einem Cloud-Anbieter
:allow-uri-read: 


[role="lead"]
Ab ONTAP 9.10.1 können Sie Ihre ONTAP-Verschlüsselungen in einer Cloud-gehosteten Applikation verwenden link:https://docs.microsoft.com/en-us/azure/key-vault/general/basic-concepts["Azure Key Vault (AKV)"^] und link:https://cloud.google.com/kms/docs["Der Verschlüsselungsmanagement-Service (Cloud KMS) der Google Cloud-Plattform"^]schützen. Ab ONTAP 9.12.0 können Sie NVE Schlüssel auch mit schützenlink:https://docs.aws.amazon.com/kms/latest/developerguide/overview.html["KMS VON AWS"^].

AWS KMS, AKV und Cloud KMS können link:configure-netapp-volume-encryption-concept.html["NetApp Volume Encryption (NVE)-Schlüssel"]nur für Daten-SVMs eingesetzt werden.

.Über diese Aufgabe
Das Verschlüsselungsmanagement mit einem Cloud-Provider kann über die CLI oder die ONTAP REST-API aktiviert werden.

Wenn Sie zum Schutz Ihrer Schlüssel einen Cloud-Provider verwenden, beachten Sie, dass standardmäßig eine Daten-SVM-LIF zur Kommunikation mit dem Cloud-Schlüsselmanagement-Endpunkt verwendet wird. Über ein Node-Managementnetzwerk kommunizieren Sie mit den Authentifizierungsservices des Cloud-Providers (login.microsoftonline.com für Azure, oauth2.googleapis.com für Cloud KMS). Wenn das Cluster-Netzwerk nicht ordnungsgemäß konfiguriert ist, verwendet das Cluster den Schlüsselverwaltungsservice nicht ordnungsgemäß.

Wenn Sie einen Cloud-Provider-Managementservice nutzen, sollten Sie sich die folgenden Einschränkungen bewusst sein:

* Das Verschlüsselungsmanagement von Cloud-Providern ist für die NetApp Storage-Verschlüsselung (NSE) und die NetApp Aggregate Encryption (NAE) nicht verfügbar. link:enable-external-key-management-96-later-nve-task.html["Externe KMIPs"] Kann stattdessen verwendet werden.
* Das Verschlüsselungsmanagement bei MetroCluster-Konfigurationen ist nicht für Cloud-Provider verfügbar.
* Das Verschlüsselungsmanagement von Cloud-Providern kann nur auf einer Daten-SVM konfiguriert werden.


.Bevor Sie beginnen
* Sie müssen den KMS auf dem entsprechenden Cloud-Provider konfiguriert haben.
* Die Nodes des ONTAP Clusters müssen NVE unterstützen.
* link:../encryption-at-rest/install-license-task.html["Sie müssen die Lizenzen für Volume Encryption (VE) und Multi-Tenant Encryption Key Management (MTEKM) installiert haben"]. Diese Lizenzen sind in enthaltenlink:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"].
* Sie müssen ein Cluster- oder SVM-Administrator sein.
* Die Daten-SVM darf keine verschlüsselten Volumes enthalten oder einen Schlüsselmanager beschäftigen. Wenn die Daten-SVM verschlüsselte Volumes enthält, müssen Sie sie vor der Konfiguration des KMS migrieren.




== Externes Verschlüsselungsmanagement

Die Aktivierung des externen Schlüsselmanagements hängt von dem jeweiligen Schlüsselmanager ab, den Sie verwenden. Wählen Sie die Registerkarte des entsprechenden Schlüsselmanagers und der entsprechenden Umgebung aus.

[role="tabbed-block"]
====
.AWS
--
.Bevor Sie beginnen
* Sie müssen einen Zuschuss für den AWS-KMS-Schlüssel erstellen, der von der IAM-Rolle zum Managen der Verschlüsselung verwendet wird. Die IAM-Rolle muss eine Richtlinie enthalten, die die folgenden Operationen zulässt:
+
** `DescribeKey`
** `Encrypt`
** `Decrypt` + Weitere Informationen finden Sie in der AWS-Dokumentation für link:https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#grant["Zuschüsse"^].




.Aktivieren Sie AWS KMV auf einer ONTAP SVM
. Bevor Sie beginnen, erhalten Sie sowohl die Zugriffsschlüssel-ID als auch den geheimen Schlüssel von Ihrem AWS KMS.
. Legen Sie die Berechtigungsebene auf erweitert fest:
`set -priv advanced`
. AWS KMS aktivieren:
`security key-manager external aws enable -vserver _svm_name_ -region _AWS_region_ -key-id _key_ID_ -encryption-context _encryption_context_`
. Geben Sie den geheimen Schlüssel ein, wenn Sie dazu aufgefordert werden.
. Überprüfen Sie, ob der AWS-KMS ordnungsgemäß konfiguriert wurde:
`security key-manager external aws show -vserver _svm_name_`
+
Erfahren Sie mehr über `security key-manager external aws` in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+key-manager+external+aws["ONTAP-Befehlsreferenz"^].



--
.Azure
--
.Aktivieren Sie Azure Key Vault auf einer ONTAP SVM
. Bevor Sie beginnen, müssen Sie die entsprechenden Authentifizierungsdaten von Ihrem Azure-Konto beziehen, entweder ein Clientgeheimnis oder ein Zertifikat. Sie müssen außerdem sicherstellen, dass alle Nodes im Cluster sich in einem ordnungsgemäßen Zustand befinden. Sie können dies mit dem Befehl überprüfen `cluster show`. Erfahren Sie mehr über `cluster show` in der link:https://docs.netapp.com/us-en/ontap-cli/cluster-show.html["ONTAP-Befehlsreferenz"^].
. Setzen Sie die privilegierte Ebene auf erweitert
`set -priv advanced`
. Aktivieren Sie AKV auf der SVM
`security key-manager external azure enable -client-id _client_id_ -tenant-id _tenant_id_ -name -key-id _key_id_ -authentication-method {certificate|client-secret}` Wenn Sie dazu aufgefordert werden, geben Sie entweder das Client-Zertifikat oder den Client-Schlüssel aus Ihrem Azure-Konto ein.
. Vergewissern Sie sich, dass AKV korrekt aktiviert
`security key-manager external azure show vserver _svm_name_` ist: Wenn die Service-Erreichbarkeit nicht in Ordnung ist, stellen Sie die Verbindung zum AKV-Schlüsselverwaltungsservice über die Daten-SVM-LIF her.
+
Erfahren Sie mehr über `security key-manager external azure` in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+key-manager+external+azure["ONTAP-Befehlsreferenz"^].



--
.Google Cloud
--
.Aktivieren Sie Cloud-KMS auf einer ONTAP SVM
. Bevor Sie beginnen, erhalten Sie den privaten Schlüssel für die Google Cloud KMS-Kontoschlüsseldatei in einem JSON-Format. Dieser Punkt ist in Ihrem GCP-Konto enthalten. Sie müssen außerdem sicherstellen, dass alle Nodes im Cluster sich in einem ordnungsgemäßen Zustand befinden. Sie können dies mit dem Befehl überprüfen `cluster show`. Erfahren Sie mehr über `cluster show` in der link:https://docs.netapp.com/us-en/ontap-cli/cluster-show.html["ONTAP-Befehlsreferenz"^].
. Privilegierte Ebene auf erweitert setzen:
`set -priv advanced`
. Cloud-KMS auf der SVM aktivieren
`security key-manager external gcp enable -vserver _svm_name_ -project-id _project_id_-key-ring-name _key_ring_name_ -key-ring-location _key_ring_location_ -key-name _key_name_` Wenn Sie dazu aufgefordert werden, geben Sie den Inhalt der JSON-Datei mit dem privaten Schlüssel des Servicekontos ein
. Vergewissern Sie sich, dass Cloud KMS mit den richtigen Parametern konfiguriert ist:
`security key-manager external gcp show vserver _svm_name_` Der Status von `kms_wrapped_key_status` lautet `“UNKNOWN”`, wenn keine verschlüsselten Volumes erstellt wurden. Wenn die Erreichbarkeit des Dienstes nicht in Ordnung ist, stellen Sie die Verbindung zum GCP-Schlüsselverwaltungsservice über die Daten-SVM-LIF her.
+
Erfahren Sie mehr über `security key-manager external gcp` in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+key-manager+external+gcp["ONTAP-Befehlsreferenz"^].



--
====
Wenn bereits ein oder mehrere verschlüsselte Volumes für eine Daten-SVM konfiguriert sind und die entsprechenden NVE Schlüssel vom Onboard-Schlüsselmanager des Admin-SVM gemanagt werden, sollten diese Schlüssel zu dem externen Verschlüsselungsmanagement-Service migriert werden. Dazu führen Sie über die CLI den Befehl aus:
`security key-manager key migrate -from-Vserver _admin_SVM_ -to-Vserver _data_SVM_` Neue verschlüsselte Volumes können erst für die Daten-SVM des Mandanten erstellt werden, wenn alle NVE-Schlüssel der Daten-SVM erfolgreich migriert wurden.

.Verwandte Informationen
* link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-encrypting-volumes.html["Verschlüsseln von Volumes mit NetApp Verschlüsselungslösungen für Cloud Volumes ONTAP"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+key-manager+external+["Sicherheitsschlüsselmanager extern"^]

