---
permalink: encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html 
sidebar: sidebar 
keywords: restoring, onboard, key management encryption 
summary: Gelegentlich müssen Sie einen integrierten Verschlüsselungsschlüssel für das Verschlüsselungsmanagement wiederherstellen. Sobald Sie überprüft haben, ob ein Schlüssel wiederhergestellt werden muss, können Sie den Onboard Key Manager zur Wiederherstellung des Schlüssels einrichten. 
---
= Wiederherstellung der integrierten Verschlüsselungsmanagement-Schlüssel in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gelegentlich müssen Sie möglicherweise einen integrierten Verschlüsselungsschlüssel für die Schlüsselverwaltung wiederherstellen.  Nachdem Sie überprüft haben, dass ein Schlüssel wiederhergestellt werden muss, können Sie den Onboard Key Manager zum Wiederherstellen des Schlüssels einrichten. Das Verfahren zum Wiederherstellen Ihrer Verschlüsselungsschlüssel für die Onboard-Schlüsselverwaltung hängt von Ihrer ONTAP-Version ab.

.Bevor Sie beginnen
* Löschen Sie die externe Schlüsselmanager-Datenbank, wenn Sie NSE mit einem externen KMIP-Server verwenden. Weitere Einzelheiten finden Sie unterlink:delete-key-management-database-task.html["Übergang von der externen Schlüsselverwaltung zur integrierten ONTAP -Schlüsselverwaltung"] .
* Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.



NOTE: Wenn Sie NSE in einem System mit einem Flash Cache Modul verwenden, sollten Sie auch NVE oder NAE aktivieren. NSE verschlüsselt keine Daten im Flash Cache Modul.



== ONTAP 9.6 und höher


IMPORTANT: Wenn Sie ONTAP 9.8 oder höher ausführen und Ihr Stammvolume verschlüsselt ist, befolgen Sie das Verfahren für <<ontap-9-8>>.

. Überprüfen Sie, ob der Schlüssel wiederhergestellt werden muss: +
`security key-manager key query -node _node_`
+
Erfahren Sie mehr über `security key-manager key query` in der link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-query.html["ONTAP-Befehlsreferenz"^].

. Stellen Sie den Schlüssel wieder her: +
`security key-manager onboard sync`
+
Erfahren Sie mehr über `security key-manager onboard sync` in der link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-sync.html["ONTAP-Befehlsreferenz"^].

. Geben Sie an der Eingabeaufforderung für die Passphrase die integrierte Passphrase für das Verschlüsselungsmanagement für das Cluster ein.




== ONTAP 9.8 oder höher mit verschlüsseltem Root-Volume

Wenn Sie ONTAP 9.8 und höher verwenden und Ihr Root-Volume verschlüsselt ist, müssen Sie mit dem Boot-Menü eine integrierte Recovery-Passphrase für das Verschlüsselungsmanagement festlegen. Dieser Vorgang ist auch erforderlich, wenn Sie einen Bootmedienaustausch durchführen.

. Starten Sie den Knoten im Boot-Menü und wählen Sie Option `(10) Set onboard key management recovery secrets`.
. Geben Sie ein, `y` um diese Option zu verwenden.
. Geben Sie an der Eingabeaufforderung die integrierte Passphrase für das Verschlüsselungsmanagement für das Cluster ein.
. Geben Sie an der Eingabeaufforderung die Backup-Schlüsseldaten ein.
+
Nachdem Sie die Daten des Sicherungsschlüssels eingegeben haben, kehrt der Knoten zum Startmenü zurück.

. Wählen Sie im Boot-Menü die Option `(1) Normal Boot`.




== ONTAP 9.5 und frühere Versionen

. Überprüfen Sie, ob der Schlüssel wiederhergestellt werden muss: +
`security key-manager key show`
. Stellen Sie den Schlüssel wieder her: +
`security key-manager setup -node _node_`
+
Erfahren Sie mehr über `security key-manager setup` imlink:https://docs.netapp.com/us-en/ontap-cli-9161/security-key-manager-setup.html["ONTAP-Befehlsreferenz"^] .

. Geben Sie an der Eingabeaufforderung für die Passphrase die integrierte Passphrase für das Verschlüsselungsmanagement für das Cluster ein.

