---
permalink: encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html 
sidebar: sidebar 
keywords: restoring, onboard, key management encryption 
summary: Gelegentlich müssen Sie einen integrierten Verschlüsselungsschlüssel für das Verschlüsselungsmanagement wiederherstellen. Sobald Sie überprüft haben, ob ein Schlüssel wiederhergestellt werden muss, können Sie den Onboard Key Manager zur Wiederherstellung des Schlüssels einrichten. 
---
= Wiederherstellung der integrierten Verschlüsselungsschlüssel für das Verschlüsselungsmanagement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Verfahren zur Wiederherstellung der integrierten Verschlüsselungsschlüssel für das Verschlüsselungsmanagement variiert je nach Ihrer Version von ONTAP.

.Bevor Sie beginnen
* Wenn Sie NSE mit einem externen KMIP-Server (Key Management) verwenden, müssen Sie die externe Schlüsselmanager-Datenbank gelöscht haben. Weitere Informationen finden Sie unter link:delete-key-management-database-task.html["Transition zum Onboard-Verschlüsselungsmanagement von externem Verschlüsselungsmanagement"]
* Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.



NOTE: Wenn Sie NSE in einem System mit einem Flash Cache Modul verwenden, sollten Sie auch NVE oder NAE aktivieren. NSE verschlüsselt keine Daten im Flash Cache Modul.



== ONTAP 9.6 und höher


IMPORTANT: Wenn Sie ONTAP 9.8 oder höher ausführen und Ihr Stammvolume verschlüsselt ist, befolgen Sie das Verfahren für <<ontap-9-8>>.

. Vergewissern Sie sich, dass der Schlüssel wiederhergestellt werden muss: +
`security key-manager key query -node _node_`
. Stellen Sie den Schlüssel wieder her: +
`security key-manager onboard sync`
+
Eine vollständige Befehlssyntax finden Sie in den man-Pages.

+
Mit dem folgenden ONTAP 9.6-Befehl werden die Schlüssel in der Onboard-Schlüsselhierarchie synchronisiert:

+
[listing]
----
cluster1::> security key-manager onboard sync

Enter the cluster-wide passphrase for onboard key management in Vserver "cluster1"::    <32..256 ASCII characters long text>
----
. Geben Sie an der Eingabeaufforderung für die Passphrase die integrierte Passphrase für das Verschlüsselungsmanagement für das Cluster ein.




== ONTAP 9.8 oder höher mit verschlüsseltem Root-Volume

Wenn Sie ONTAP 9.8 und höher verwenden und Ihr Root-Volume verschlüsselt ist, müssen Sie mit dem Boot-Menü eine integrierte Recovery-Passphrase für das Verschlüsselungsmanagement festlegen. Dieser Vorgang ist auch erforderlich, wenn Sie einen Bootmedienaustausch durchführen.

. Starten Sie den Knoten im Startmenü, und wählen Sie Option `(10) Set onboard key management recovery secrets`.
. Eingabe `y` Um diese Option zu verwenden.
. Geben Sie an der Eingabeaufforderung die integrierte Passphrase für das Verschlüsselungsmanagement für das Cluster ein.
. Geben Sie an der Eingabeaufforderung die Backup-Schlüsseldaten ein.
+
Der Node kehrt zum Startmenü zurück.

. Wählen Sie im Startmenü Option `(1) Normal Boot`.




== ONTAP 9.5 und früher

. Vergewissern Sie sich, dass der Schlüssel wiederhergestellt werden muss: +
`security key-manager key show`
. Wenn Sie ONTAP 9.8 und höher verwenden und Ihr Root-Volume verschlüsselt ist, führen Sie folgende Schritte aus:
+
Wenn Sie ONTAP 9.6 oder 9.7 verwenden oder ONTAP 9.8 oder höher verwenden und Ihr Root-Volume nicht verschlüsselt ist, überspringen Sie diesen Schritt.

. Stellen Sie den Schlüssel wieder her: +
`security key-manager setup -node _node_`
+
Eine vollständige Befehlssyntax finden Sie in den man-Pages.

. Geben Sie an der Eingabeaufforderung für die Passphrase die integrierte Passphrase für das Verschlüsselungsmanagement für das Cluster ein.

