---
permalink: encryption-at-rest/return-self-encrypting-disks-keys-not-available-task.html 
sidebar: sidebar 
keywords: returning, fips, drive, sed, service, authentication, keys, lost 
summary: Das System behandelt ein FIPS-Laufwerk oder eine SED als defekt, wenn die Authentifizierungsschlüssel dafür dauerhaft verloren gehen und nicht vom KMIP-Server abgerufen werden können. Obwohl Sie nicht auf die Daten auf der Festplatte zugreifen oder diese wiederherstellen können, können Sie Schritte Unternehmen, um den nicht genutzten Speicherplatz der SED für Daten erneut verfügbar zu machen. 
---
= Geben Sie ein FIPS-Laufwerk oder eine SED an den Dienst zurück, wenn Authentifizierungsschlüssel verloren gehen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das System behandelt ein FIPS-Laufwerk oder eine SED als defekt, wenn die Authentifizierungsschlüssel dafür dauerhaft verloren gehen und nicht vom KMIP-Server abgerufen werden können. Obwohl Sie nicht auf die Daten auf der Festplatte zugreifen oder diese wiederherstellen können, können Sie Schritte Unternehmen, um den nicht genutzten Speicherplatz der SED für Daten erneut verfügbar zu machen.

Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.

Sie sollten diesen Prozess nur verwenden, wenn Sie sicher sind, dass die Authentifizierungsschlüssel für das FIPS-Laufwerk oder die SED dauerhaft verloren gehen und nicht wiederhergestellt werden können.

Wenn die Festplatten partitioniert werden, müssen sie zunächst nicht partitioniert werden, bevor Sie diesen Prozess starten können. Beinhalten:.../_include/undpartition-Disk.adoc[]

.Schritte
. Rückgabe eines FIPS-Laufwerks oder SED an den Dienst:
+
[cols="25,75"]
|===


| Wenn die SEDS... | Verwenden Sie die folgenden Schritte... 


 a| 
Nicht im FIPS-Compliance-Modus oder im FIPS-Compliance-Modus und der FIPS-Schlüssel ist verfügbar
 a| 
.. Legen Sie die Berechtigungsebene auf erweitert fest:
`set -privilege advanced`
.. Setzen Sie den FIPS-Schlüssel auf die Standard-Herstellsichere ID 0x0:
`storage encryption disk modify -fips-key-id 0x0 -disk _disk_id_`
.. Überprüfen Sie, ob der Vorgang erfolgreich war:
`storage encryption disk show-status`Wenn der Vorgang fehlgeschlagen ist, verwenden Sie den PSID-Prozess in diesem Thema.
.. Bereinigen der defekten Scheibe:
`storage encryption disk sanitize -disk _disk_id_`Überprüfen Sie, ob der Vorgang mit dem Befehl erfolgreich war `storage encryption disk show-status` Bevor Sie mit dem nächsten Schritt fortfahren.
.. Entfernen Sie die desinfizierte Festplatte:
`storage disk unfail -spare true -disk _disk_id_`
.. Prüfen Sie, ob die Festplatte einen Eigentümer hat:
`storage disk show -disk _disk_id_`
.. Wenn die Festplatte keinen Eigentümer hat, weisen Sie einen zu, und heben Sie die Ausmusterung der Festplatte erneut auf:
`storage disk assign -owner node -disk _disk_id_`
`storage disk unfail -spare true -disk _disk_id_`
.. Überprüfen Sie, ob die Festplatte nun frei und in einem Aggregat wiederverwendet werden kann:
`storage disk show -disk _disk_id_`




 a| 
Im FIPS-Compliance-Modus ist der FIPS-Schlüssel nicht verfügbar, und SEDs haben eine PSID auf dem Etikett
 a| 
.. Beziehen Sie die PSID des Datenträgers von der Datenträgerbezeichnung.
.. Legen Sie die Berechtigungsebene auf erweitert fest:
`set -privilege advanced`
.. Zurücksetzen der Festplatte auf die werkseitigen Einstellungen:
`storage encryption disk revert-to-original-state -disk _disk_id_ -psid _disk_physical_secure_id_`Überprüfen Sie, ob der Vorgang mit dem Befehl erfolgreich war `storage encryption disk show-status` Bevor Sie mit dem nächsten Schritt fortfahren.
.. Entfernen Sie die desinfizierte Festplatte:
`storage disk unfail -spare true -disk _disk_id_`
.. Prüfen Sie, ob die Festplatte einen Eigentümer hat:
`storage disk show -disk _disk_id_`
.. Wenn die Festplatte keinen Eigentümer hat, weisen Sie einen zu, und heben Sie die Ausmusterung der Festplatte erneut auf:
`storage disk assign -owner node -disk _disk_id_`
`storage disk unfail -spare true -disk _disk_id_`
.. Überprüfen Sie, ob die Festplatte nun frei und in einem Aggregat wiederverwendet werden kann:
`storage disk show -disk _disk_id_`


|===


Eine vollständige Befehlssyntax finden Sie in den man-Pages.
