---
permalink: encryption-at-rest/return-self-encrypting-disks-keys-not-available-task.html 
sidebar: sidebar 
keywords: returning, fips, drive, sed, service, authentication, keys, lost 
summary: Das System behandelt ein FIPS-Laufwerk oder eine SED als defekt, wenn die Authentifizierungsschlüssel dafür dauerhaft verloren gehen und nicht vom KMIP-Server abgerufen werden können. Obwohl Sie nicht auf die Daten auf der Festplatte zugreifen oder diese wiederherstellen können, können Sie Schritte Unternehmen, um den nicht genutzten Speicherplatz der SED für Daten erneut verfügbar zu machen. 
---
= Geben Sie ein FIPS-Laufwerk oder SED wieder in Betrieb, wenn Authentifizierungsschlüssel in ONTAP verloren gehen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das System behandelt ein FIPS-Laufwerk oder eine SED als defekt, wenn die Authentifizierungsschlüssel dafür dauerhaft verloren gehen und nicht vom KMIP-Server abgerufen werden können. Obwohl Sie nicht auf die Daten auf der Festplatte zugreifen oder diese wiederherstellen können, können Sie Schritte Unternehmen, um den nicht genutzten Speicherplatz der SED für Daten erneut verfügbar zu machen.

.Bevor Sie beginnen
Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.

.Über diese Aufgabe
Sie sollten diesen Prozess nur verwenden, wenn Sie sicher sind, dass die Authentifizierungsschlüssel für das FIPS-Laufwerk oder die SED dauerhaft verloren gehen und nicht wiederhergestellt werden können.

Wenn die Festplatten partitioniert werden, müssen sie zunächst nicht partitioniert werden, bevor Sie diesen Prozess starten können.


NOTE: Der Befehl zum Aufheben der Partitionierung einer Festplatte ist nur auf Diagnoseebene verfügbar und sollte nur unter Aufsicht des NetApp Supports ausgeführt werden. **Es wird dringend empfohlen, dass Sie sich an den NetApp -Support wenden, bevor Sie fortfahren.** Sie können sich auch auf dielink:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_unpartition_a_spare_drive_in_ONTAP["NetApp Knowledge Base: So trennen Sie die Partition eines Ersatzlaufwerks in ONTAP"^] .

.Schritte
. Rückgabe eines FIPS-Laufwerks oder SED an den Dienst:
+
[cols="25,75"]
|===


| Wenn die SEDS... | Verwenden Sie die folgenden Schritte... 


 a| 
Nicht im FIPS-Compliance-Modus oder im FIPS-Compliance-Modus und der FIPS-Schlüssel ist verfügbar
 a| 
.. Legen Sie die Berechtigungsebene auf erweitert fest:
`set -privilege advanced`
.. Setzen Sie den FIPS-Schlüssel auf die standardmäßige gesicherte Herstellerkennung 0x0 zurück:
`storage encryption disk modify -fips-key-id 0x0 -disk _disk_id_`
.. Überprüfen Sie, ob
`storage encryption disk show-status` der Vorgang erfolgreich war: Wenn der Vorgang fehlgeschlagen ist, verwenden Sie den PSID-Prozess in diesem Thema.
.. Bereinigen Sie die beschädigte Festplatte:
`storage encryption disk sanitize -disk _disk_id_` Überprüfen Sie mit dem Befehl `storage encryption disk show-status`, ob der Vorgang erfolgreich war, bevor Sie mit dem nächsten Schritt fortfahren.
.. Bereinigte Festplatte aufheben:
`storage disk unfail -spare true -disk _disk_id_`
.. Überprüfen Sie, ob die Festplatte einen Besitzer hat:
`storage disk show -disk _disk_id_` + Wenn die Platte keinen Besitzer hat, weisen Sie einen zu.
`storage disk assign -owner node -disk _disk_id_`
+
... Geben Sie den Knotenpunkt für den Knoten ein, der die Festplatten besitzt, die Sie desinfizieren möchten:
+
`system node run -node _node_name_`

+
Führen Sie den `disk sanitize release` Befehl aus.



.. Verlassen Sie die Nodeshell. Fehler der Festplatte erneut aufheben:
`storage disk unfail -spare true -disk _disk_id_`
.. Überprüfen Sie, ob die Festplatte jetzt als Ersatzlaufwerk verwendet und in einem Aggregat wiederverwendet werden kann:
`storage disk show -disk _disk_id_`




 a| 
Im FIPS-Compliance-Modus ist der FIPS-Schlüssel nicht verfügbar, und SEDs haben eine PSID auf dem Etikett
 a| 
.. Beziehen Sie die PSID des Datenträgers von der Datenträgerbezeichnung.
.. Legen Sie die Berechtigungsebene auf erweitert fest:
`set -privilege advanced`
.. Setzen Sie die Festplatte auf die werkseitig konfigurierten Einstellungen zurück:
`storage encryption disk revert-to-original-state -disk _disk_id_ -psid _disk_physical_secure_id_` Überprüfen Sie `storage encryption disk show-status`, ob der Vorgang mit dem Befehl erfolgreich war, bevor Sie mit dem nächsten Schritt fortfahren.
.. Wenn Sie ONTAP 9.8P5 oder eine frühere Version verwenden, fahren Sie mit dem nächsten Schritt fort. Wenn Sie ONTAP 9.8P6 oder höher ausführen, nehmen Sie den Fehler auf der bereinigten Festplatte zurück.
`storage disk unfail -disk _disk_id_`
.. Überprüfen Sie, ob die Festplatte einen Besitzer hat:
`storage disk show -disk _disk_id_` + Wenn die Platte keinen Besitzer hat, weisen Sie einen zu.
`storage disk assign -owner node -disk _disk_id_`
+
... Geben Sie den Knotenpunkt für den Knoten ein, der die Festplatten besitzt, die Sie desinfizieren möchten:
+
`system node run -node _node_name_`

+
Führen Sie den `disk sanitize release` Befehl aus.



.. Verlassen Sie die Nodeshell.. Fehler der Festplatte erneut aufheben:
`storage disk unfail -spare true -disk _disk_id_`
.. Überprüfen Sie, ob die Festplatte jetzt als Ersatzlaufwerk verwendet und in einem Aggregat wiederverwendet werden kann:
`storage disk show -disk _disk_id_`


|===


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-modify.html["Speicherverschlüsselung Datenträger ändern"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-revert-to-original-state.html["Speicherverschlüsselung Datenträger in den ursprünglichen Zustand zurücksetzen"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-sanitize.html["Speicherverschlüsselung Datenträgerbereinigung"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show-status.html["Speicherverschlüsselung Datenträger Status anzeigen"^]

