---
permalink: encryption-at-rest/return-seds-unprotected-mode-task.html 
sidebar: sidebar 
keywords: returning, fips, drive, unprotected, mode 
summary: Ein FIPS-Laufwerk oder SED ist nur dann vor unberechtigtem Zugriff geschützt, wenn die Authentifizierungsschlüssel-ID für den Knoten auf einen anderen Wert als den Standardwert gesetzt ist. Sie können ein FIPS-Laufwerk oder eine SED in den ungeschützten Modus zurücksenden, indem Sie den Befehl Speicherverschlüsselungsfestplatte ändern verwenden, um die Schlüssel-ID auf den Standardmodus zu setzen. 
---
= Setzen Sie ein FIPS-Laufwerk oder SED in ONTAP in den ungeschützten Modus zurück
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein FIPS-Laufwerk oder SED ist nur dann vor unberechtigtem Zugriff geschützt, wenn die Authentifizierungsschlüssel-ID für den Knoten auf einen anderen Wert als den Standardwert gesetzt ist. Sie können ein FIPS-Laufwerk oder eine SED in den ungeschützten Modus zurücksetzen `storage encryption disk modify`, indem Sie mit dem Befehl die Schlüssel-ID auf den Standardwert setzen. Ein FIPS-Laufwerk oder eine SED im ungeschützten Modus verwendet die standardmäßigen Verschlüsselungsschlüssel, während ein FIPS-Laufwerk oder eine SED im geschützten Modus die angegebenen geheimen Verschlüsselungsschlüssel verwendet. Wenn auf dem Laufwerk verschlüsselte Daten gespeichert sind und das Laufwerk in den ungeschützten Modus zurückgesetzt wird, werden die Daten weiterhin verschlüsselt und nicht offengelegt.


NOTE: Befolgen Sie dieses Verfahren, um sicherzustellen, dass auf alle verschlüsselten Daten nicht mehr zugegriffen werden kann, nachdem das FIPS-Laufwerk oder die SED wieder in den ungeschützten Modus versetzt wurde. Sobald die FIPS- und Datenschlüssel-IDs zurückgesetzt wurden, können vorhandene Daten nicht mehr entschlüsselt werden und sind nicht mehr zugänglich, es sei denn, die ursprünglichen Schlüssel werden wiederhergestellt.

Wenn ein HA-Paar SAS- oder NVMe-Laufwerke (SED, NSE, FIPS) verwendet, müssen Sie diesen Prozess für alle Laufwerke innerhalb des HA-Paars befolgen, bevor das System initialisiert wird (Boot-Optionen 4 oder 9). Andernfalls kann es zu künftigen Datenverlusten kommen, wenn die Laufwerke einer anderen Verwendung zugewiesen werden.

.Bevor Sie beginnen
Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.

.Schritte
. Legen Sie die Berechtigungsebene auf erweitert fest:
+
`set -privilege advanced`

. Wenn ein FIPS-Laufwerk im FIPS-Compliance-Modus ausgeführt wird, legen Sie die FIPS-Authentifizierungsschlüssel-ID für den Node wieder auf den Standard MSID 0x0:
+
`storage encryption disk modify -disk _disk_id_ -fips-key-id 0x0`

+
Sie können den `security key-manager query` Befehl verwenden, um Schlüssel-IDs anzuzeigen.

+
[listing]
----
cluster1::> storage encryption disk modify -disk 2.10.11 -fips-key-id 0x0

Info: Starting modify on 14 disks.
      View the status of the operation by using the
      storage encryption disk show-status command.
----
+
Bestätigen Sie den Vorgang mit dem Befehl:

+
`storage encryption disk show-status`

+
Wiederholen Sie den Befehl „show-status“, bis die Zahlen in „Disks Begun“ und „Disks Done“ gleich sind.

+
[listing]
----
cluster1:: storage encryption disk show-status

            FIPS    Latest   Start               Execution   Disks   Disks Disks
Node        Support Request  Timestamp           Time (sec)  Begun   Done  Successful
-------     ------- -------- ------------------  ---------- ------ ------  ----------
cluster1    true    modify   1/18/2022 15:29:38    3           14     5         5
1 entry was displayed.
----
. Legen Sie die Daten-Authentifizierungsschlüssel-ID für den Knoten wieder auf die Standard-MSID 0x0:
+
`storage encryption disk modify -disk _disk_id_ -data-key-id 0x0`

+
Der Wert von `-data-key-id` sollte auf 0x0 gesetzt werden, unabhängig davon, ob Sie ein SAS- oder NVMe-Laufwerk in den ungeschützten Modus zurückführen.

+
Sie können den `security key-manager query` Befehl verwenden, um Schlüssel-IDs anzuzeigen.

+
[listing]
----
cluster1::> storage encryption disk modify -disk 2.10.11 -data-key-id 0x0

Info: Starting modify on 14 disks.
      View the status of the operation by using the
      storage encryption disk show-status command.
----
+
Bestätigen Sie den Vorgang mit dem Befehl:

+
`storage encryption disk show-status`

+
Wiederholen Sie den Befehl „show-status“, bis die Zahlen gleich sind. Der Vorgang ist abgeschlossen, wenn die Zahlen in „Disks started“ und „Disks done“ gleich sind.





== Wartungsmodus

Ab ONTAP 9.7 können Sie eine FIPS-Festplatte aus dem Wartungsmodus neu Schlüssel aktivieren. Sie sollten den Wartungsmodus nur verwenden, wenn Sie die ONTAP-CLI-Anweisungen im vorherigen Abschnitt nicht verwenden können.

.Schritte
. Legen Sie die FIPS-Authentifizierungsschlüssel-ID für den Knoten wieder auf die Standard-MSID 0x0:
+
`disk encrypt rekey_fips 0x0 _disklist_`

. Legen Sie die Daten-Authentifizierungsschlüssel-ID für den Knoten wieder auf die Standard-MSID 0x0:
+
`disk encrypt rekey 0x0 _disklist_`

. Bestätigen Sie, dass der FIPS-Authentifizierungsschlüssel erfolgreich umcodiert wurde:
+
`disk encrypt show_fips`

. Bestätigung der erfolgreichen Verschlüsselung des Datenauthentifizierungsschlüssels mit:
+
`disk encrypt show`

+
In Ihrer Ausgabe wird wahrscheinlich entweder die Standard-MSID 0x0-Schlüssel-ID oder der 64-stellige Wert des Schlüsselservers angezeigt. Das `Locked?` Feld bezieht sich auf die Datensperrung.



[listing]
----
Disk       FIPS Key ID                 Locked?
---------- --------------------------- -------
0a.01.0    0x0                          Yes
----
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-modify.html["Speicherverschlüsselung Datenträger ändern"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show-status.html["Speicherverschlüsselung Datenträger Status anzeigen"^]

