---
permalink: encryption-at-rest/return-self-encrypting-disks-keys-not-available-task.html 
sidebar: sidebar 
keywords: returning, fips, drive, sed, service, authentication, keys, lost 
summary: Das System behandelt ein FIPS-Laufwerk oder eine SED als defekt, wenn die Authentifizierungsschlüssel dafür dauerhaft verloren gehen und nicht vom KMIP-Server abgerufen werden können. Obwohl auf die Daten auf der Festplatte nicht zugegriffen oder sie wiederhergestellt werden können, besteht die Möglichkeit, den ungenutzten Speicherplatz der SED wieder für Daten verfügbar zu machen. 
---
= Ein FIPS-Laufwerk oder ein SED kann wieder in Betrieb genommen werden, wenn Authentifizierungsschlüssel in ONTAP verloren gegangen sind
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das System behandelt ein FIPS-Laufwerk oder eine SED als defekt, wenn die Authentifizierungsschlüssel dafür dauerhaft verloren gehen und nicht vom KMIP-Server abgerufen werden können. Obwohl auf die Daten auf der Festplatte nicht zugegriffen oder sie wiederhergestellt werden können, besteht die Möglichkeit, den ungenutzten Speicherplatz der SED wieder für Daten verfügbar zu machen.

.Bevor Sie beginnen
Sie müssen Cluster-Administrator sein, um diese Aufgabe ausführen zu können.

.Über diese Aufgabe
Dieses Verfahren sollte nur verwendet werden, wenn Sie sicher sind, dass die Authentifizierungsschlüssel für das FIPS-Laufwerk oder SED dauerhaft verloren sind und nicht wiederhergestellt werden können.

Falls die Festplatten partitioniert sind, müssen sie zuerst entpartitioniert werden, bevor Sie mit diesem Vorgang beginnen können.


NOTE: Der Befehl zum Aufheben der Partitionierung einer Festplatte ist nur auf der Diagnoseebene verfügbar und sollte nur unter Aufsicht des NetApp Supports durchgeführt werden. **Es wird dringend empfohlen, vor dem weiteren Vorgehen den NetApp Support zu kontaktieren.** Es kann auch auf die link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_unpartition_a_spare_drive_in_ONTAP["NetApp Knowledge Base: Wie eine Ersatzfestplatte in ONTAP entpartitioniert wird"^] verwiesen werden.

.Schritte
. Ein FIPS-Laufwerk oder SED wieder in Betrieb nehmen:
+
[cols="25,75"]
|===


| Wenn die SEDS... | Diese Schritte können verwendet werden... 


 a| 
Nicht im FIPS-Konformitätsmodus oder im FIPS-Konformitätsmodus und der FIPS-Schlüssel ist verfügbar
 a| 
.. Die Berechtigungsstufe wird auf „Erweitert“ gesetzt:
`set -privilege advanced`
.. Der FIPS-Schlüssel wird auf die standardmäßige sichere Hersteller-ID 0x0 zurückgesetzt:
`storage encryption disk modify -fips-key-id 0x0 -disk _disk_id_`
.. Es sollte überprüft werden, ob der Vorgang erfolgreich war:
`storage encryption disk show-status` Falls der Vorgang fehlgeschlagen ist, kann der in diesem Thema beschriebene PSID-Prozess verwendet werden.
.. Die defekte Festplatte bereinigen:
`storage encryption disk sanitize -disk _disk_id_` Mit dem Befehl `storage encryption disk show-status` kann überprüft werden, ob der Vorgang erfolgreich war, bevor zum nächsten Schritt übergegangen wird.
.. Die bereinigte Festplatte wiederherstellen:
`storage disk unfail -spare true -disk _disk_id_`
.. Es ist zu prüfen, ob die Festplatte einen Besitzer hat:
`storage disk show -disk _disk_id_` + Falls die Festplatte keinen Besitzer hat, ist einer zuzuweisen.
`storage disk assign -owner node -disk _disk_id_`
+
... Öffnen Sie die Nodeshell für den Node, dem die Festplatten gehören, die Sie bereinigen möchten:
+
`system node run -node _node_name_`

+
Führe den  `disk sanitize release` Befehl aus.



.. Beenden Sie die Nodeshell. Die Festplatte wird erneut in den betriebsbereiten Zustand versetzt:
`storage disk unfail -spare true -disk _disk_id_`
.. Es sollte überprüft werden, dass die Festplatte nun als Ersatzfestplatte verfügbar ist und zur Wiederverwendung in einem Aggregat bereitsteht:
`storage disk show -disk _disk_id_`




 a| 
Im FIPS-Konformitätsmodus ist der FIPS-Schlüssel nicht verfügbar und die SEDs haben eine PSID auf dem Etikett aufgedruckt
 a| 
.. Die PSID der Festplatte lässt sich dem Festplattenetikett entnehmen.
.. Die Berechtigungsstufe wird auf „Erweitert“ gesetzt:
`set -privilege advanced`
.. Setzen Sie die Festplatte auf die werkseitigen Einstellungen zurück:
`storage encryption disk revert-to-original-state -disk _disk_id_ -psid _disk_physical_secure_id_` Mit dem Befehl  `storage encryption disk show-status` lässt sich überprüfen, ob der Vorgang erfolgreich war, bevor zum nächsten Schritt übergegangen wird.
.. Wenn Sie ONTAP 9.8P5 oder früher verwenden, zum nächsten Schritt wechseln. Wenn Sie ONTAP 9.8P6 oder später verwenden, die bereinigte Festplatte wiederherstellen.
`storage disk unfail -disk _disk_id_`
.. Es ist zu prüfen, ob die Festplatte einen Besitzer hat:
`storage disk show -disk _disk_id_` + Falls die Festplatte keinen Besitzer hat, ist einer zuzuweisen.
`storage disk assign -owner node -disk _disk_id_`
+
... Öffnen Sie die Nodeshell für den Node, dem die Festplatten gehören, die Sie bereinigen möchten:
+
`system node run -node _node_name_`

+
Führe den  `disk sanitize release` Befehl aus.



.. Die Nodeshell wird beendet. Die Festplatte wird erneut in den betriebsbereiten Zustand versetzt:
`storage disk unfail -spare true -disk _disk_id_`
.. Es sollte überprüft werden, dass die Festplatte nun als Ersatzfestplatte verfügbar ist und zur Wiederverwendung in einem Aggregat bereitsteht:
`storage disk show -disk _disk_id_`


|===


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-modify.html["Speicherverschlüsselung Festplatte ändern"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-revert-to-original-state.html["Speicherverschlüsselungsfestplatte auf ursprünglichen Zustand zurücksetzen"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-sanitize.html["Speicherverschlüsselung Festplattenbereinigung"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show-status.html["storage encryption disk show-status"^]

