---
permalink: encryption-at-rest/rotate-authentication-keys-nse-task.html 
sidebar: sidebar 
keywords: rotating, authentication, keys, netapp, storage, encryption 
summary: 'Die Authentifizierungsschlüssel können bei Verwendung von NetApp Storage Encryption (NSE) rotiert werden.' 
---
= Authentifizierungsschlüssel für ONTAP NetApp Storage Encryption rotieren
:allow-uri-read: 


[role="lead"]
Die Authentifizierungsschlüssel können bei Verwendung von NetApp Storage Encryption (NSE) rotiert werden.

.Über diese Aufgabe
Die Rotation von Authentifizierungsschlüsseln in einer NSE-Umgebung wird unterstützt, wenn der External Key Manager (KMIP) verwendet wird.


NOTE: Die Rotation von Authentifizierungsschlüsseln in einer NSE-Umgebung wird für Onboard Key Manager (OKM) nicht unterstützt.

.Schritte
. Mit dem  `security key-manager create-key` Befehl werden neue Authentifizierungsschlüssel generiert.
+
Sie müssen neue Authentifizierungsschlüssel generieren, bevor Sie die Authentifizierungsschlüssel ändern können.

. Mit dem  `storage encryption disk modify -disk * -data-key-id`Befehl lassen sich die Authentifizierungsschlüssel ändern.


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-modify.html["Speicherverschlüsselung Festplatte ändern"^]

