---
permalink: encryption-at-rest/rotate-authentication-keys-nse-task.html 
sidebar: sidebar 
keywords: rotating, authentication, keys, netapp, storage, encryption 
summary: 'Sie können die Authentifizierungsschlüssel mit der NetApp Storage Encryption (NSE) drehen.' 
---
= Rotieren Sie die Authentifizierungsschlüssel für ONTAP NetApp Storage Encryption
:allow-uri-read: 


[role="lead"]
Sie können die Authentifizierungsschlüssel mit der NetApp Storage Encryption (NSE) drehen.

.Über diese Aufgabe
Die rotierenden Authentifizierungsschlüssel in einer NSE-Umgebung werden unterstützt, wenn Sie External Key Manager (KMIP) verwenden.


NOTE: Rotierende Authentifizierungsschlüssel in einer NSE-Umgebung werden von Onboard Key Manager (OKM) nicht unterstützt.

.Schritte
.  `security key-manager create-key`Erstellen Sie mit dem Befehl neue Authentifizierungsschlüssel.
+
Sie müssen neue Authentifizierungsschlüssel generieren, bevor Sie die Authentifizierungsschlüssel ändern können.

. Verwenden Sie den `storage encryption disk modify -disk * -data-key-id` Befehl, um die Authentifizierungsschlüssel zu ändern.


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-modify.html["Speicherverschlüsselung Datenträger ändern"^]

