---
permalink: encryption-at-rest/secure-purge-data-encrypted-volume-concept.html 
sidebar: sidebar 
keywords: secure, purge, scrub, data, encrypted, volume, nve, netapp 
summary: 'Ab ONTAP 9.4 kann die Funktion „Secure Purge“ verwendet werden, um Daten auf NVE-fähigen Volumes unterbrechungsfrei zu löschen. Das Löschen von Daten auf einem verschlüsselten Volume stellt sicher, dass diese nicht vom physischen Medium wiederhergestellt werden können, zum Beispiel in Fällen von `spillage,` Datenspuren, die beim Überschreiben von Blöcken zurückgeblieben sind, oder um die Daten eines ausscheidenden Mandanten sicher zu löschen.' 
---
= Informationen zum sicheren Löschen von Daten aus einem verschlüsselten ONTAP Volume
:allow-uri-read: 


[role="lead"]
Ab ONTAP 9.4 kann die Funktion „Secure Purge“ verwendet werden, um Daten auf NVE-fähigen Volumes unterbrechungsfrei zu löschen. Das Löschen von Daten auf einem verschlüsselten Volume stellt sicher, dass diese nicht vom physischen Medium wiederhergestellt werden können, zum Beispiel in Fällen von „Spillage“, bei denen Datenspuren beim Überschreiben von Blöcken zurückgeblieben sein könnten, oder um die Daten eines ausscheidenden Mandanten sicher zu löschen.

Die sichere Löschung funktioniert nur für zuvor gelöschte Dateien auf NVE-fähigen Volumes. Ein unverschlüsseltes Volume kann nicht bereinigt werden. Es sind KMIP-Server zur Bereitstellung der Schlüssel zu verwenden, nicht der integrierte Schlüsselmanager.



[[considerations-for-using-secure-purge]]
== Überlegungen zur Verwendung von Secure Purge

* Volumes, die in einem für NetApp Aggregate Encryption (NAE) aktivierten Aggregat erstellt wurden, unterstützen kein sicheres Löschen.
* Die sichere Löschung funktioniert nur für zuvor gelöschte Dateien auf NVE-fähigen Volumes.
* Ein unverschlüsseltes Volume kann nicht bereinigt werden.
* Es sind KMIP-Server zur Bereitstellung der Schlüssel zu verwenden, nicht der integrierte Schlüsselmanager.


Die Secure Purge Funktion arbeitet je nach Ihrer ONTAP Version unterschiedlich.

[role="tabbed-block"]
====
.ONTAP 9.8 und höher
--
* Secure Purge wird von MetroCluster und FlexGroup unterstützt.
* Wenn das zu löschende Volume die Quelle einer SnapMirror Beziehung ist, muss die SnapMirror Beziehung nicht getrennt werden, um eine sichere Löschung durchzuführen.
* Die Methode zur erneuten Verschlüsselung unterscheidet sich für Volumes mit SnapMirror Datenschutz im Vergleich zu Volumes ohne SnapMirror Datenschutz (DP) oder solchen mit SnapMirror erweiterter Datenschutzfunktion.
+
** Standardmäßig werden Daten auf Volumes, die den SnapMirror Datenschutzmodus (DP) verwenden, mithilfe der Volume Move Re-Verschlüsselungsmethode erneut verschlüsselt.
** Standardmäßig verwenden Volumes, die keinen SnapMirror Datenschutz verwenden, oder Volumes, die den SnapMirror erweiterten Datenschutzmodus (XDP) verwenden, die Methode der direkten Neuverschlüsselung.
** Diese Standardeinstellungen können mit dem  `secure purge re-encryption-method [volume-move|in-place-rekey]` Befehl geändert werden.


* Standardmäßig werden alle Snapshots in FlexVol Volumes während der sicheren Bereinigung automatisch gelöscht. Standardmäßig werden Snapshots in FlexGroup Volumes und Volumes, die SnapMirror Datenschutz verwenden, während der sicheren Bereinigung nicht automatisch gelöscht. Diese Standardeinstellungen können mit dem  `secure purge delete-all-snapshots [true|false]` Befehl geändert werden.


--
.ONTAP 9.7 und früher:
--
* Die sichere Bereinigung unterstützt die folgenden Funktionen nicht:
+
** FlexClone
** SnapVault
** FabricPool


* Wenn das zu löschende Volumen die Quelle einer SnapMirror Beziehung ist, muss die SnapMirror Beziehung getrennt werden, bevor das Volumen gelöscht werden kann.
+
Wenn sich im Volume belegte Snapshots befinden, müssen die Snapshots freigegeben werden, bevor das Volume gelöscht werden kann. Beispielsweise kann es erforderlich sein, ein FlexClone Volume von seinem übergeordneten Volume zu trennen.

* Das erfolgreiche Aufrufen der Funktion „secure-purge“ löst eine Volume-Verschiebung aus, bei der die verbleibenden, nicht gelöschten Daten mit einem neuen Schlüssel neu verschlüsselt werden.
+
Das verschobene Volume verbleibt auf dem aktuellen Aggregat. Der alte Schlüssel wird automatisch gelöscht, wodurch sichergestellt wird, dass gelöschte Daten nicht vom Speichermedium wiederhergestellt werden können.



--
====