---
permalink: encryption-at-rest/transition-external-key-from-onboard-key-task.html 
sidebar: sidebar 
keywords: transitioning, external key management, onboard key management 
summary: Wenn Sie von Onboard-Verschlüsselungsmanagement auf externes Verschlüsselungsmanagement wechseln möchten, müssen Sie die integrierte Verschlüsselungsmanagementkonfiguration löschen, bevor Sie externes Verschlüsselungsmanagement aktivieren können. 
---
= Wechseln Sie zum externen Verschlüsselungsmanagement vom integrierten Verschlüsselungsmanagement in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie von Onboard-Verschlüsselungsmanagement auf externes Verschlüsselungsmanagement wechseln möchten, müssen Sie die integrierte Verschlüsselungsmanagementkonfiguration löschen, bevor Sie externes Verschlüsselungsmanagement aktivieren können.

.Bevor Sie beginnen
* Bei der hardwarebasierten Verschlüsselung müssen die Datenschlüssel aller FIPS-Laufwerke oder SEDs auf den Standardwert zurückgesetzt werden.
+
link:return-seds-unprotected-mode-task.html["Ein FIPS-Laufwerk oder eine SED-Festplatte in den ungeschützten Modus zurückkehren"]

* Bei softwarebasierter Verschlüsselung müssen Sie alle Volumes entschlüsseln.
+
link:unencrypt-volume-data-task.html["Verschlüsselung von Volume-Daten aufheben"]

* Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.


.Schritt
. Löschen der integrierten Verschlüsselungsmanagementkonfiguration für ein Cluster:
+
[cols="35,65"]
|===


| Für diese ONTAP-Version... | Befehl 


 a| 
ONTAP 9.6 und höher
 a| 
`security key-manager onboard disable -vserver SVM`



 a| 
ONTAP 9.5 und frühere Versionen
 a| 
`security key-manager delete-key-database`

|===
+
Erfahren Sie mehr über `security key-manager onboard disable` und `security key-manager delete-key-database` in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+key-manager["ONTAP-Befehlsreferenz"^].


