---
permalink: ndmp/configure-lifs-node-scoped-task.html 
sidebar: sidebar 
keywords: configure, lif 
summary: Es ist erforderlich, eine LIF zu identifizieren, die für die Herstellung einer Datenverbindung und einer Steuerverbindung zwischen dem Node und der Backup-Anwendung verwendet wird. Nach der Identifizierung der LIF sollte überprüft werden, ob die Firewall- und Failover-Richtlinien für die LIF festgelegt sind. 
---
= ONTAP LIFs für knotenbezogenes NDMP konfigurieren
:allow-uri-read: 


[role="lead"]
Es ist erforderlich, eine LIF zu identifizieren, die für die Herstellung einer Datenverbindung und einer Steuerverbindung zwischen dem Node und der Backup-Anwendung verwendet wird. Nach der Identifizierung der LIF sollte überprüft werden, ob die Firewall- und Failover-Richtlinien für die LIF festgelegt sind.


NOTE: Ab ONTAP 9.10.1 sind Firewall-Richtlinien veraltet und vollständig durch LIF-Dienstrichtlinien ersetzt. Weitere Informationen finden sich unter link:../networking/manage_supported_traffic.html["Unterstützten Datenverkehr verwalten"].

[role="tabbed-block"]
====
.ONTAP 9.10.1 oder höher
--
.Schritte
. Die auf den Knoten gehostete Intercluster-LIF wird mit dem  `network interface show` Befehl und dem  `-service-policy` Parameter identifiziert.
+
`network interface show -service-policy default-intercluster`

. Stellen Sie sicher, dass der Intercluster-LIF den  `backup-ndmp-control` Dienst enthält:
+
`network interface service-policy show`

. Stellen Sie sicher, dass die Failover-Richtlinie für die Intercluster-LIFs entsprechend konfiguriert ist:
+
.. Es sollte überprüft werden, ob die Failover-Richtlinie für die Intercluster-LIFs auf  `local-only` gesetzt ist, indem der  `network interface show -failover` Befehl verwendet wird.
+
[listing]
----
cluster1::> network interface show -failover
            Logical          Home              Failover     Failover
Vserver     Interface        Node:Port         Policy       Group
--------    ---------------  ----------------- ------------ --------
cluster1    IC1               cluster1-1:e0a    local-only   Default
                                                    Failover Targets:
                                                    .......
            IC2               cluster1-2:e0b    local-only   Default
                                                    Failover Targets:
                                                    .......
cluster1-1  cluster1-1_mgmt1 cluster1-1:e0m    local-only    Default
                                                    Failover Targets:
                                                    .......
----
.. Wenn die Failover-Richtlinie nicht ordnungsgemäß eingestellt ist, kann die Failover-Richtlinie mit dem  `network interface modify` Befehl und dem  `-failover-policy` Parameter geändert werden.
+
[listing]
----
cluster1::> network interface modify -vserver cluster1 -lif IC1 -failover-policy local-only
----


+
Weitere Informationen zu `network interface show`, `network interface service-policy show` und `network interface modify` in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["ONTAP-Befehlsreferenz"^].



--
.ONTAP 9.9 oder früher
--
.Schritte
. Die auf den Knoten gehostete Intercluster-LIF wird mit dem  `network interface show` Befehl und dem  `-role` Parameter identifiziert.
+
[listing]
----
cluster1::> network interface show -role intercluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster1    IC1        up/up      192.0.2.65/24      cluster1-1    e0a     true
cluster1    IC2        up/up      192.0.2.68/24      cluster1-2    e0b     true
----
. Stellen Sie sicher, dass die Firewall-Richtlinie für NDMP auf den Intercluster-LIFs aktiviert ist:
+
.. Es sollte überprüft werden, ob die Firewall-Richtlinie für NDMP mit dem  `system services firewall policy show` Befehl aktiviert ist.
+
Der folgende Befehl zeigt die Firewall-Richtlinie für die Intercluster LIF an:

+
[listing]
----
cluster1::> system services firewall policy show -policy intercluster

Vserver     Policy       Service    Allowed
-------     ------------ ---------- -------------------
cluster1    intercluster dns        -
                         http       -
                         https      -
                         ndmp       0.0.0.0/0, ::/0
                         ndmps      -
                         ntp        -
                         rsh        -
                         ssh        -
                         telnet     -
9 entries were displayed.
----
.. Falls die Firewall-Richtlinie nicht aktiviert ist, kann die Firewall-Richtlinie mit dem  `system services firewall policy modify` Befehl mit dem  `-service` Parameter aktiviert werden.
+
Der folgende Befehl aktiviert die Firewall-Richtlinie für die Intercluster-LIF:

+
[listing]
----
cluster1::> system services firewall policy modify -vserver cluster1 -policy intercluster -service ndmp 0.0.0.0/0
----


. Stellen Sie sicher, dass die Failover-Richtlinie für die Intercluster-LIFs entsprechend konfiguriert ist:
+
.. Es sollte überprüft werden, ob die Failover-Richtlinie für die Intercluster-LIFs auf  `local-only` gesetzt ist, indem der  `network interface show -failover` Befehl verwendet wird.
+
[listing]
----
cluster1::> network interface show -failover
            Logical          Home              Failover     Failover
Vserver     Interface        Node:Port         Policy       Group
--------    ---------------  ----------------- ------------ --------
cluster1    IC1               cluster1-1:e0a    local-only   Default
                                                    Failover Targets:
                                                    .......
            IC2               cluster1-2:e0b    local-only   Default
                                                    Failover Targets:
                                                    .......
cluster1-1  cluster1-1_mgmt1 cluster1-1:e0m    local-only    Default
                                                    Failover Targets:
                                                    .......
----
.. Wenn die Failover-Richtlinie nicht ordnungsgemäß eingestellt ist, kann die Failover-Richtlinie mit dem  `network interface modify` Befehl und dem  `-failover-policy` Parameter geändert werden.
+
[listing]
----
cluster1::> network interface modify -vserver cluster1 -lif IC1 -failover-policy local-only
----


+
Weitere Informationen zu  `network interface show` und  `network interface modify` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["ONTAP-Befehlsreferenz"^].



--
====