---
permalink: ndmp/enable-tape-reservations-task.html 
sidebar: sidebar 
keywords: enable, tape, reservation 
summary: Sie müssen sicherstellen, dass Bandlaufwerke für Backup-Anwendungen für NDMP-Backup-Vorgänge reserviert sind. 
---
= Aktivieren Sie Tape-Reservierungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen sicherstellen, dass Bandlaufwerke für Backup-Anwendungen für NDMP-Backup-Vorgänge reserviert sind.

.Über diese Aufgabe
Die Reservierungseinstellungen variieren in unterschiedlichen Backup-Anwendungen, und diese Einstellungen müssen mit der Backup-Anwendung und den Nodes oder Servern übereinstimmen, die die gleichen Laufwerke verwenden. Die richtigen Reservierungseinstellungen finden Sie in der Anbieterdokumentation der Backup-Anwendung.

.Schritte
. Aktivieren Sie Reservierungen mit dem `options -option-name tape.reservations -option-value persistent` Befehl.
+
Mit dem folgenden Befehl werden Reservierungen mit dem `persistent` Wert aktiviert:

+
[listing]
----
cluster1::> options -option-name tape.reservations -option-value persistent
2 entries were modified.
----
. Überprüfen Sie mit dem `options tape.reservations` Befehl, ob Reservierungen auf allen Nodes aktiviert sind, und überprüfen Sie dann die Ausgabe.
+
[listing]
----
cluster1::> options tape.reservations

cluster1-1
    tape.reservations                 persistent

cluster1-2
    tape.reservations                 persistent
2 entries were displayed.
----

