---
permalink: ndmp/enable-node-scoped-ndmp-cluster-task.html 
sidebar: sidebar 
keywords: enable, node, scope, ndmp, cluster 
summary: Sie können NDMP mit Node-Umfang konfigurieren, indem Sie auf dem Cluster NDMP mit Node-Umfang und den NDMP-Service auf allen Knoten des Clusters aktivieren. Sie müssen auch den Root-Benutzer für NDMP konfigurieren, wenn Sie den NDMP-Dienst aktivieren. 
---
= Aktivieren Sie NDMP mit Node-Umfang auf dem Cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Backups von Volumes auf einem Node durch die Aktivierung von NDMP mit Node-Umfang, die Einrichtung des Passworts für den Root-Benutzer und die Konfiguration einer logischen Schnittstelle für die Daten- und Kontrollverbindung erstellen.

Sie können NDMP mit Node-Umfang konfigurieren, indem Sie auf dem Cluster NDMP mit Node-Umfang und den NDMP-Service auf allen Knoten des Clusters aktivieren. Außerdem müssen Sie den konfigurieren `root` Benutzer für NDMP wenn Sie den NDMP-Service aktivieren.

.Schritte
. Aktivieren Sie den Node-Scoped NDMP-Modus mit der `system services ndmp` Befehl mit dem `node-scope-mode` Parameter.
+
[listing]
----
cluster1::> system services ndmp node-scope-mode on
NDMP node-scope-mode is enabled.
----
. Aktivieren Sie den NDMP-Service auf allen Nodes im Cluster mithilfe von `system services ndmp on` Befehl.
+
Mit dem Platzhalter „`*`“ wird der NDMP-Service auf allen Nodes gleichzeitig aktiviert.

+
Sie müssen ein Passwort für die Authentifizierung der NDMP-Verbindung durch die Backup-Anwendung angeben.

+
[listing]
----
cluster1::> system services ndmp on -node *

Please enter password:
Confirm password:
2 entries were modified.
----
. Deaktivieren Sie das `-clear-text` Möglichkeit zur sicheren Kommunikation des NDMP-Passworts mithilfe der `system services ndmp modify` Befehl.
+
Verwenden des Platzhalters „`*`" disables the `-clear-text` Auf allen Nodes gleichzeitig möglich.

+
[listing]
----
cluster1::> system services ndmp modify -node * -clear-text false
2 entries were modified.
----
. Vergewissern Sie sich, dass der NDMP-Service aktiviert ist und der `-clear-text` Die Option ist mit der deaktiviert `system services ndmp show` Befehl.
+
[listing]
----
cluster1::> system services ndmp show
Node                  Enabled   Clear text  User Id
--------------------- --------- ----------- ---------
cluster1-1            true      false        root
cluster1-2            true      false        root
2 entries were displayed.
----

