---
permalink: ndmp/index.html 
sidebar: sidebar 
keywords: decide, ndmp, configuration, network, data, management, protocol, backup, back up 
summary: 'Sie können ein ONTAP 9 Cluster schnell so konfigurieren, dass das Network Data Management Protocol (NDMP) verwendet wird, um Daten direkt mithilfe einer Backup-Applikation eines Drittanbieters auf Tape zu sichern.' 
---
= Erfahren Sie mehr über die ONTAP NDMP-Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein ONTAP 9 Cluster schnell so konfigurieren, dass das Network Data Management Protocol (NDMP) verwendet wird, um Daten direkt mithilfe einer Backup-Applikation eines Drittanbieters auf Tape zu sichern.

Wenn die Backup-Anwendung Cluster Aware Backup (CAB) unterstützt, ist eine Konfiguration von NDMP als _SVM-scoped_ oder _node-scoped_ möglich:

* Die SVM-basierte Sicherung auf Cluster- (Admin-SVM-) Ebene ermöglicht das Backup aller Volumes, die auf verschiedenen Knoten des Clusters gehostet werden. SVM-basierter NDMP-Service wird, wo möglich, empfohlen.
* Node-scoped NDMP ermöglicht das Sichern aller auf diesem Knoten gehosteten Volumes.


Wenn die Backup-Anwendung CAB nicht unterstützt, ist node-scope NDMP zu verwenden.

SVM-bezogene und knotenbezogene NDMP schließen sich gegenseitig aus, sie können nicht auf demselben Cluster konfiguriert werden.


NOTE: Node-scoped NDMP ist in ONTAP 9 veraltet.

Weitere Informationen zu link:../tape-backup/cluster-aware-backup-extension-concept.html["Cluster Aware Backup (CAB)"].

Vor der Konfiguration von NDMP ist Folgendes zu überprüfen:

* Sie verwenden eine Backup-Anwendung eines Drittanbieters (auch Data Management Application oder DMA genannt).
* Sie sind ein Cluster-Administrator.
* Tape-Geräte und ein optionaler Medienserver sind installiert.
* Tape-Geräte sind über einen Fibre Channel (FC) Switch oder lokal mit dem Cluster verbunden.
* Mindestens ein Tape-Gerät hat eine logische Einheitennummer (LUN) von 0.

