---
permalink: consistency-groups/configure-hierarchy-task.html 
sidebar: sidebar 
keywords: consistency groups, application protection, parent, child, hierarchy 
summary: Erstellen einer hierarchischen Consistency Group für das Management großer Applikations-Workloads und die Datensicherung 
---
= Konfigurieren Sie eine hierarchische Konsistenzgruppe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Ihr Applikations-Workload aus mehr als einem Teilbereich von Volumes besteht, wobei jede Untergruppe in ihren eigenen zugehörigen Volumes konsistent ist, können Sie mit ONTAP eine hierarchische Konsistenzgruppe erstellen.

Hierarchische Konsistenzgruppen verfügen über ein übergeordnetes Objekt, das bis zu fünf individuelle Konsistenzgruppen umfassen kann. Hierarchische Konsistenzgruppen können unterschiedliche lokale Snapshot-Richtlinien über Konsistenzgruppen oder einzelne Volumes hinweg unterstützen. Wenn Sie eine Remote SM-BC-Richtlinie verwenden, gilt diese für die gesamte hierarchische Consistency Group (übergeordnete und untergeordnete Elemente).

Informationen zu Objektbeschränkungen für Konsistenzgruppen finden Sie unter xref:index.html#consistency-group-object-limits[Objektbeschränkungen für Konsistenzgruppen].



== Erstellen Sie eine hierarchische Konsistenzgruppe mit neuen LUNs

.Schritte
. Wählen Sie *Storage > Consistency Groups* aus.
. Wählen Sie *+Add.* und dann *mit neuen LUNs*.
. Benennen Sie die Konsistenzgruppe. Legen Sie die Anzahl der LUNs und die Kapazität pro LUN fest.
+
.. **Anwendungstyp**: Wenn Sie ONTAP 9.12.1 oder höher verwenden, wählen Sie einen Anwendungstyp aus. Wenn kein Wert ausgewählt ist, wird der Konsistenzgruppe standardmäßig der Typ von **Other** zugewiesen. Erfahren Sie mehr über das Tagging von Konsistenz in xref:index.html#application-and-component-tags[Applikations- und Komponenten-Tags]. Wenn Sie eine SM-BC-Beziehung erstellen möchten, müssen Sie *other* verwenden.


. Wählen Sie das Host-Betriebssystem und das LUN-Format aus. Geben Sie die Informationen zum Host-Initiator ein.
. Um Schutzrichtlinien zu konfigurieren, fügen Sie eine untergeordnete Consistency Group hinzu oder weitere Optionen zu Host-Initiatoren anzeigen, wählen Sie *More options* aus.
. Um eine untergeordnete Konsistenzgruppe hinzuzufügen, wählen Sie *+untergeordnete Konsistenzgruppe hinzufügen* aus.
. Wählen Sie das Performance-Level, die Anzahl der LUNs und die Kapazität pro LUN aus. Legen Sie das Host-Betriebssystem, das LUN-Format fest und wählen Sie eine neue oder vorhandene Host-Initiatorgruppe aus.
. *Optional*: Wählen Sie eine lokale Snapshot Policy.
. Wiederholen Sie dies für bis zu fünf Child-Konsistenzgruppen.
. Wählen Sie *Speichern*.
. Überprüfen Sie, ob die Konsistenzgruppe erstellt wurde, indem Sie zum Hauptmenü der Konsistenzgruppe zurückkehren, wo sie nach Abschluss des ONTAP-Jobs angezeigt wird. Wenn Sie eine Schutzrichtlinie festlegen, achten Sie auf die entsprechende Richtlinie, Remote oder lokal, die einen grünen Schild mit einem Häkchen anzeigen soll.




== Erstellen einer hierarchischen Konsistenzgruppe mit vorhandenen Volumes

.Schritte
. Wählen Sie *Storage > Consistency Groups* aus.
. Wählen Sie *+Add.* und dann *mit vorhandenen Volumes* aus.
. Wählen Sie die Storage-VM aus.
. Wählen Sie die vorhandenen Volumes aus, die einbezogen werden sollen. Nur Volumes, die nicht bereits zu einer Konsistenzgruppe gehören, können ausgewählt werden.
. Um eine untergeordnete Consistency Group hinzuzufügen, wählen Sie *+Child Consistency Group* hinzufügen. Erstellen Sie die erforderlichen Konsistenzgruppen, die automatisch benannt werden.
+
.. **Komponententyp**: Wenn Sie ONTAP 9.12.1 oder höher verwenden, wählen Sie einen Komponententyp von „Daten“, „Logs“ oder „Sonstige“ aus. Wenn kein Wert ausgewählt ist, wird der Konsistenzgruppe standardmäßig der Typ von **Other** zugewiesen. Erfahren Sie mehr über das Tagging von Konsistenz in xref:index.html#application-and-component-tags[Applikations- und Komponenten-Tags]. Wenn Sie eine SM-BC-Beziehung erstellen möchten, müssen Sie *other* verwenden.


. Weisen Sie jeder Konsistenzgruppe vorhandene Volumes zu.
+
.. *Optional*: Wählen Sie eine lokale Snapshot Policy.


. Wiederholen Sie dies für bis zu fünf Child-Konsistenzgruppen.
. Wählen Sie *Speichern*.
. Überprüfen Sie, ob die Konsistenzgruppe erstellt wurde, indem Sie zum Hauptmenü der Konsistenzgruppe zurückkehren, wo sie nach Abschluss des ONTAP-Jobs angezeigt wird. Wenn Sie eine Schutzrichtlinie ausgewählt haben, bestätigen Sie, dass sie richtig eingestellt wurde, indem Sie Ihre Konsistenzgruppe im Menü auswählen. Wenn Sie eine Schutzrichtlinie festlegen, achten Sie auf die entsprechende Richtlinie, Remote oder lokal, die einen grünen Schild mit einem Häkchen anzeigen soll.

