---
permalink: consistency-groups/limits.html 
sidebar: sidebar 
keywords: consistency groups, object limits 
summary: Bei der Planung von Konsistenzgruppen gibt es Objektbegrenzungen, die Sie beachten sollten. 
---
= Einschränkungen für Konsistenzgruppen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Berücksichtigen Sie beim Planen und Verwalten von Konsistenzgruppen Objektbeschränkungen im Umfang des Clusters und der übergeordneten oder untergeordneten Konsistenzgruppe.



== Erzwungene Grenzwerte

In der folgenden Tabelle werden die Grenzwerte für Konsistenzgruppen aufgeführt. Für Konsistenzgruppen, die SnapMirror Active Sync verwenden, gelten gesonderte Einschränkungen. Weitere Informationen finden Sie unter link:../snapmirror-active-sync/limits-reference.html["Einschränkungen bei der aktiven SnapMirror Synchronisierung"].

|===


| Grenze | Umfang | Minimum | Maximal 


| Anzahl der Konsistenzgruppen | Cluster | 0 | Entspricht der maximalen Volume-Anzahl im Cluster* 


| Anzahl der übergeordneten Konsistenzgruppen | Cluster | 0 | Die maximale Anzahl der Volumes im Cluster entspricht 


| Anzahl der einzelnen und übergeordneten Konsistenzgruppen | Cluster | 0 | Die maximale Anzahl der Volumes im Cluster entspricht 


| Anzahl der Volumes in einer Konsistenzgruppe | Eine Konsistenzgruppe | 1 Lautstärke | 80 Bände 


| Anzahl von Volumes in einer Konsistenzgruppe mit SnapMirror asynchron | Eine Konsistenzgruppe | 1 Lautstärke  a| 
* Ab ONTAP 9.15.1: 80 Bände
* In ONTAP 9.13.1 und 9.14.1: 16 Bände




| Anzahl der Volumes im untergeordneten Element einer übergeordneten Konsistenzgruppe | Übergeordnete Konsistenzgruppe | 1 Lautstärke | 80 Bände 


| Anzahl der Volumes in einer untergeordneten Konsistenzgruppe | Untergeordnete Konsistenzgruppe | 1 Lautstärke | 80 Bände 


| Anzahl der untergeordneten Konsistenzgruppen in einer übergeordneten Konsistenzgruppe | Übergeordnete Konsistenzgruppe | 1 Konsistenzgruppe | 5 Konsistenzgruppen 


| Anzahl der SVM-Disaster-Recovery-Beziehungen mit einer Konsistenzgruppe (verfügbar ab ONTAP 9.14.1) | Cluster | 0 | 32 
|===
{Asterisk} Es können maximal 50 Konsistenzgruppen, die mit asynchronem SnapMirror aktiviert sind, auf einem Cluster gehostet werden.



== Nicht erzwungene Grenzwerte

Der unterstützte Mindestzeitplan für Konsistenzgruppen beträgt 30 Minuten. Dies basiert auf link:https://www.netapp.com/media/12385-tr4571.pdf["Testen für FlexGroup Volumes"^], die dieselbe Snapshot Infrastruktur wie Konsistenzgruppen verwenden.
