---
sidebar: sidebar 
permalink: concept_quotas_overview.html 
keywords: netapp, ontap, quotas, quota, managing, resources, qtree, qtrees, disk space, hard quota, soft quota 
summary: Quotas ermöglichen es, den von einem Benutzer, einer Gruppe oder einem Qtree verwendeten Speicherplatz und die Anzahl der Dateien einzuschränken oder zu verfolgen. Quotas werden auf ein bestimmtes Volume oder einen bestimmten Qtree angewendet. 
---
= Ressourcen mithilfe von Kontingenten mit ONTAP System Manager verwalten
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ab ONTAP 9.7 ist es möglich, Nutzungskontingente mit System Manager zu konfigurieren und zu verwalten.

Wenn Sie die ONTAP CLI zum Konfigurieren und Verwalten von Nutzungskontingenten verwenden, siehe link:./volumes/index.html["Logische Speicherverwaltung"].

Wenn Sie den älteren OnCommand System Manager für ONTAP 9.7 und frühere Versionen zur Konfiguration und Verwaltung von Nutzungskontingenten verwenden, finden Sie im Folgenden Informationen zu Ihrer Version:

* link:http://docs.netapp.com/us-en/ontap-system-manager-classic/online-help-96-97/index.html["ONTAP 9.7 und 9.6 Dokumentation"^]
* link:https://mysupport.netapp.com/documentation/docweb/index.html?productID=62686&language=en-US["ONTAP 9.5 Dokumentation"^]
* link:https://mysupport.netapp.com/documentation/docweb/index.html?productID=62594&language=en-US["ONTAP 9.4 Dokumentation"^]
* link:https://mysupport.netapp.com/documentation/docweb/index.html?productID=62579&language=en-US["ONTAP 9.3 Dokumentation"^]




[[quota-overview]]
== Quotenübersicht

Quotas ermöglichen es, den von einem Benutzer, einer Gruppe oder einem Qtree verwendeten Speicherplatz und die Anzahl der Dateien einzuschränken oder zu verfolgen. Quotas werden auf ein bestimmtes Volume oder einen bestimmten Qtree angewendet.

Mithilfe von Quoten lässt sich die Ressourcennutzung in Volumes verfolgen und begrenzen, und es erfolgt eine Benachrichtigung, wenn die Ressourcennutzung bestimmte Werte erreicht.

Quoten können weich oder hart sein. Weiche Quoten veranlassen ONTAP, eine Benachrichtigung zu senden, wenn festgelegte Grenzwerte überschritten werden, und harte Quoten verhindern, dass ein Schreibvorgang erfolgreich ist, wenn festgelegte Grenzwerte überschritten werden.
