---
sidebar: sidebar 
permalink: concept_rest_overview.html 
keywords: netapp, ontap, rest, rest api, rest api log, api log, rest overview 
summary: Das REST-API-Protokoll erfasst die API-Aufrufe, die der System Manager an ONTAP sendet. Das Protokoll ermöglicht ein Verständnis der Art und Reihenfolge der API-Aufrufe, die für verschiedene ONTAP Verwaltungsaufgaben erforderlich sind. 
---
= REST API-Verwaltung mit System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Das REST-API-Protokoll erfasst die API-Aufrufe, die der System Manager an ONTAP sendet. Das Protokoll ermöglicht ein Verständnis der Art und Reihenfolge der Aufrufe, die für die Durchführung der verschiedenen ONTAP administrativen Aufgaben erforderlich sind.



[[how-system-manager-uses-the-rest-api-and-api-log]]
== Wie System Manager die REST API und das API-Protokoll verwendet

Es gibt mehrere Möglichkeiten, wie der System Manager REST-API-Aufrufe an ONTAP sendet.



[[when-does-system-manager-issue-api-calls]]
=== Wann sendet der System Manager API-Aufrufe?

Hier sind die wichtigsten Beispiele dafür, wann der System Manager ONTAP REST API-Aufrufe ausführt.



==== Automatische Seitenaktualisierung

System Manager gibt im Hintergrund automatisch API-Aufrufe aus, um die angezeigten Informationen, wie auf der Dashboard-Seite, zu aktualisieren.



==== Anzeigeaktion des Benutzers

Beim Anzeigen einer bestimmten Speicherressource oder einer Sammlung von Ressourcen über die System Manager Benutzeroberfläche werden ein oder mehrere API-Aufrufe ausgelöst.



==== Aktualisierungsaktion des Benutzers

Ein API-Aufruf wird ausgelöst, wenn Sie eine ONTAP-Ressource über die System Manager-Benutzeroberfläche hinzufügen, ändern oder löschen.



[[reissuing-an-api-call]]
=== Erneutes Auslösen eines API-Aufrufs

Sie können einen API-Aufruf auch manuell erneut auslösen, indem Sie auf einen Protokolleintrag klicken. Dadurch wird die unformatierte JSON-Ausgabe des Aufrufs angezeigt.



[[more-information]]
== Weitere Informationen

* link:https://docs.netapp.com/us-en/ontap-automation/["ONTAP 9 Automatisierungsdokumente"^]

