---
sidebar: sidebar 
permalink: concept_metrocluster_manage_nodes.html 
keywords: system manager, manage, metrocluster, clusters, nodes, mcc, HA, config, peering, peers, pairing, pairs 
summary: Ab ONTAP 9.8 können Sie MetroCluster Vorgänge mit System Manager managen. 
---
= Überblick über das Management der MetroCluster Site mit System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ab ONTAP 9.8 können Sie System Manager als vereinfachte Benutzeroberfläche zum Management einer Konfiguration einer MetroCluster Einrichtung verwenden.

Eine MetroCluster Konfiguration ermöglicht es zwei Clustern, Daten aufeinander zu spiegeln, wenn ein Cluster ausfällt, gehen die Daten nicht verloren.

In der Regel richtet ein Unternehmen die Cluster an zwei verschiedenen geografischen Standorten ein. Ein Administrator an jedem Standort richtet ein Cluster ein und konfiguriert es. Anschließend kann ein Administrator das Peering zwischen den Clustern einrichten, um Daten gemeinsam zu nutzen.

Das Unternehmen kann auch einen ONTAP Mediator an einem dritten Standort installieren. Der ONTAP Mediator Service überwacht den Status jedes Clusters. Wenn eines der Cluster erkennt, dass es nicht mit dem Partner-Cluster kommunizieren kann, fragt es den Monitor ab, um zu ermitteln, ob der Fehler ein Problem mit dem Cluster-System oder mit der Netzwerkverbindung ist.

Wenn das Problem mit der Netzwerkverbindung besteht, führt der Systemadministrator Fehlerbehebungsmethoden durch, um den Fehler zu beheben und die Verbindung wiederherzustellen. Wenn das Partner-Cluster ausfällt, initiiert das andere Cluster einen Switchover-Prozess, um den Daten-I/O für beide Cluster zu steuern.

Sie können auch eine Umschaltung durchführen, um eines der Cluster-Systeme für eine geplante Wartung herunterzufahren. Das Partner-Cluster übernimmt alle Daten-I/O-Vorgänge für beide Cluster, bis Sie das Cluster hochfahren, für das Sie Wartungsarbeiten durchgeführt und einen Switchback-Vorgang durchführen.

Sie können folgende Vorgänge verwalten:

* link:task_metrocluster_setup.html["Richten Sie eine IP MetroCluster-Site ein"]
* link:task_metrocluster_peering.html["IP-MetroCluster-Peering einrichten"]
* link:task_metrocluster_configure.html["Konfigurieren Sie einen IP MetroCluster-Standort"]
* link:task_metrocluster_switchover_switchback.html["IP MetroCluster-Umschaltung und zurückwechseln"]
* link:task_metrocluster_troubleshooting.html["Fehlerbehebung mit IP MetroCluster-Konfigurationen"]
* link:task_metrocluster_ANDU_upgrade.html["Aktualisieren Sie ONTAP auf MetroCluster Clustern"]

