---
sidebar: sidebar 
permalink: metrocluster-setup-l3-task.html 
keywords: metrocluster, layer 3, edit, gateway, netmask, net mask, configuration, configure 
summary: Ab ONTAP 9.10.1 können Sie die IP-Adresse und -Maske sowie das Gateway einer MetroCluster IP-Schnittstelle ändern. 
---
= Adresse, Netmask und Gateway in einer MetroCluster-IP ändern
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ab ONTAP 9.10.1 können Sie die folgenden Eigenschaften einer MetroCluster IP-Schnittstelle ändern: IP-Adresse und -Maske sowie Gateway. Sie können jede beliebige Kombination von Parametern zum Aktualisieren verwenden.

Möglicherweise müssen Sie diese Eigenschaften aktualisieren, z. B. wenn eine doppelte IP-Adresse erkannt wird oder wenn ein Gateway aufgrund von Änderungen der Routerkonfiguration im Fall eines Layer 3-Netzwerks geändert werden muss. Sie können jeweils nur eine Schnittstelle ändern. Es wird eine Verkehrsunterbrechung auf dieser Schnittstelle geben, bis die anderen Schnittstellen aktualisiert und Verbindungen wiederhergestellt sind.


NOTE: Sie müssen die Änderungen an jedem Port vornehmen. Auf ähnliche Weise müssen Netzwerk-Switches auch ihre Konfiguration aktualisieren. Wenn das Gateway beispielsweise aktualisiert wird, wird idealerweise auf beiden Knoten eines HA-Paares geändert, da sie identisch sind. Außerdem muss der mit diesen Nodes verbundene Switch auch sein Gateway aktualisieren.

.Schritt
Aktualisieren Sie die IP-Adresse, die Netmask und das Gateway für jeden Node und jede Schnittstelle.
