---
sidebar: sidebar 
permalink: sysmgr-integration-bluexp-concept.html 
keywords: netapp, ontap, system manager, experience, integrate, integration, bluexp, hybrid, cloud, dashboard, multicloud 
summary: Ab ONTAP 9.12.1 ist der System Manager vollständig in BlueXP integriert. Mit BlueXP können Sie Ihre Hybrid-Multi-Cloud-Infrastruktur über eine einzige Kontrollebene managen und gleichzeitig das vertraute System Manager Dashboard nutzen. 
---
= System Manager Integration in BlueXP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ab ONTAP 9.12.1 ist der System Manager vollständig in BlueXP integriert. Mit BlueXP können Sie Ihre Hybrid-Multi-Cloud-Infrastruktur über eine einzige Kontrollebene managen und gleichzeitig das vertraute System Manager Dashboard nutzen.



== Überblick über die Integration

Wenn Sie auf System Manager auf einem lokalen ONTAP-Cluster mit ONTAP 9.12.1 oder höher mit Verbindung zum BlueXP-Dienst zugreifen, werden Sie aufgefordert, den Cluster direkt von BlueXP zu verwalten. Von BlueXP haben Sie Zugriff auf die System Manager-Schnittstelle, die Sie gewohnt sind, sowie auf BlueXP-Funktionalität.

Mit BlueXP können Sie Cloud-Storage erstellen und verwalten (z. B. Cloud Volumes ONTAP), Datenservices von NetApp (beispielsweise Cloud-Backups) sowie zahlreiche lokale und Edge-Storage-Geräte steuern.



== Verwalten Sie Ihre ONTAP Cluster über BlueXP

Wenn Sie bereit sind, Ihre ONTAP Cluster von BlueXP zu verwalten, können Sie den Link folgen, der angezeigt wird, wenn Sie versuchen, auf System Manager zugreifen, oder Sie können direkt zu BlueXP gehen. Der direkte Weg zu BlueXP bietet einen Vorteil, wenn Sie die Datendienste von BlueXP nutzen möchten, um Daten zu sichern, zu scannen und zu kategorisieren, und vieles mehr.



=== Verwenden Sie den Link vom System Manager

Wenn Sie über Ihren Webbrowser eine Verbindung zur Cluster-Managementoberfläche herstellen, werden Sie aufgefordert, den Cluster mit System Manager in BlueXP oder die Version von System Manager zu managen, die mit Ihrem ONTAP System installiert ist.

So verwenden Sie System Manager in BlueXP:

.Schritte
. Öffnen Sie einen Webbrowser, und geben Sie die IP-Adresse der Cluster-Managementoberfläche ein.
+
Wenn der Cluster über eine Verbindung zu BlueXP verfügt, wird eine Anmeldeaufforderung angezeigt.

. Klicken Sie auf *Weiter zu BlueXP*, um dem Link zu BlueXP zu folgen.
+

NOTE: Wenn Ihre Systemeinstellungen externe Netzwerke blockiert haben, können Sie nicht auf BlueXP zugreifen.  Um mit BlueXP auf System Manager zuzugreifen, müssen Sie sicherstellen, dass Ihr System auf die Adresse „`cloudmanager.cloud.netapp.com`"“ zugreifen kann.  Andernfalls können Sie an der Eingabeaufforderung die Version von System Manager verwenden, die mit dem ONTAP System installiert ist.

. Wählen Sie auf der BlueXP Login-Seite die Option *mit den Anmeldedaten der NetApp Support Site* anmelden* und geben Sie Ihre Zugangsdaten ein.
+
Wenn Sie bereits BlueXP verwendet haben und einen Login mit einer E-Mail und einem Passwort, dann müssen Sie die Login-Option stattdessen fortsetzen.

+
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html["Erfahren Sie mehr über die Anmeldung bei BlueXP"^].

. Wenn Sie dazu aufgefordert werden, geben Sie einen Namen für Ihr neues BlueXP-Konto ein.
+
In den meisten Fällen erstellt BlueXP automatisch ein Konto für Sie basierend auf Daten aus Ihrem Cluster.

. Geben Sie die Cluster-Administrator-Anmeldedaten für das Cluster ein.


.Ergebnis
System Manager wird angezeigt, und Sie können den Cluster jetzt über BlueXP verwalten.



=== Ermitteln Sie Ihre Cluster direkt von BlueXP

BlueXP bietet zwei Möglichkeiten, Cluster zu erkennen und zu verwalten:

* Direkte Bestandsaufnahme für das Management über System Manager
+
Dies ist die gleiche Erkennungsoption, die im vorherigen Abschnitt beschrieben wird, mit der Sie den Anweisungen folgen.

* Erkennung über einen Konnektor
+
Der Connector ist eine in Ihrer Umgebung installierte Software, mit der Sie über System Manager auf Managementfunktionen zugreifen können. Außerdem können Sie auf Cloud-Services von BlueXP zugreifen, die Funktionen wie Datenreplizierung, Backup und Recovery, Datenklassifizierung, Daten-Tiering und vieles mehr bieten.



Wechseln Sie zum https://docs.netapp.com/us-en/cloud-manager-family/index.html["BlueXP-Dokumentation"^] Um mehr über diese Optionen zur Bestandsaufnahme und Verwaltung zu erfahren.



== Erfahren Sie mehr über BlueXP

* https://docs.netapp.com/us-en/cloud-manager-family/concept-overview.html["BlueXP im Überblick"^]
* https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/index.html["Management Ihrer NetApp AFF und FAS Systeme über BlueXP"^]

