---
sidebar: sidebar 
permalink: task_dp_configure_storage_vm_dr.html 
keywords: netapp, ontap, system manager, VM, storage, destination, source, source storage VM, disaster, protection, protection relationship, relationship, relationships, recovery 
summary: Mit System Manager können Sie eine Disaster Recovery-Beziehung für Storage VMs erstellen, um eine Storage-VM-Konfiguration auf eine andere zu replizieren. Bei einem Notfall am primären Standort können Sie die Ziel-Storage VM schnell aktivieren. 
---
= Disaster Recovery für Storage-VMs konfigurieren
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mit System Manager können Sie eine Storage VM Disaster Recovery-Beziehung (Storage VM DR) erstellen, um eine Storage-VM-Konfiguration auf eine andere zu replizieren. Bei einem Notfall am primären Standort können Sie die Ziel-Storage VM schnell aktivieren.

Führen Sie dieses Verfahren vom Ziel aus. Wenn Sie eine neue Schutzrichtlinie erstellen müssen, z. B. wenn Ihre Quell-Storage-VM SMB konfiguriert ist, sollten Sie die Richtlinie mit System Manager erstellen und im Fenster *Schutzrichtlinie hinzufügen* die Option *Identity Preserve* auswählen.
Weitere Details finden Sie unter link:task_dp_create_custom_data_protection_policies.html#["Erstellen benutzerdefinierter Datensicherungsrichtlinien"].

.Schritte
. Klicken Sie auf dem Ziel-Cluster auf *Schutz > Beziehungen*.
. Klicken Sie unter *Relationships* auf Protect und wählen Sie *Storage VMs (DR)* aus.
. Wählen Sie eine Schutzrichtlinie aus. Wenn Sie eine benutzerdefinierte Schutzrichtlinie erstellt haben, wählen Sie diese aus, und wählen Sie dann das Quellcluster und die Storage VM aus, die repliziert werden sollen. Sie können auch eine neue Ziel-Storage-VM erstellen, indem Sie einen neuen Namen für die Storage VM eingeben.
. Klicken Sie Auf *Speichern*.

