---
sidebar: sidebar 
permalink: task_metrocluster_setup.html 
keywords: system manager, metrocluster, set up, setup, start, initialize, cluster, config, nodes 
summary: Ab ONTAP 9.8 können Sie mit System Manager eine IP-Konfiguration eines MetroCluster Standorts einrichten. 
---
= Richten Sie eine IP MetroCluster-Site ein
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Ab ONTAP 9.8 können Sie mit System Manager eine IP-Konfiguration eines MetroCluster Standorts einrichten.

Ein MetroCluster-Standort besteht aus zwei Clustern. In der Regel befinden sich die Cluster an verschiedenen geografischen Standorten.

.Bevor Sie beginnen
* Das System sollte bereits installiert und entsprechend dem verkabelt sein https://["Installations- und Setup-Anleitung"^] Das kam mit dem System.
* Clusternetzwerkschnittstellen sollten auf jedem Knoten eines jeden Clusters für die Kommunikation innerhalb des Clusters konfiguriert werden.




== Weisen Sie eine Node-Management-IP-Adresse zu



=== Windows System

Sie sollten Ihren Windows-Computer mit dem Subnetz verbinden, mit dem die Controller verbunden sind. Sie weist Ihrem System automatisch eine Node-Management-IP-Adresse zu.

.Schritte
. Öffnen Sie vom Windows-System aus das Laufwerk *Network*, um die Knoten zu erkennen.
. Doppelklicken Sie auf den Node, um den Cluster-Setup-Assistenten zu starten.




=== Andere Systeme

Sie sollten die Node-Management-IP-Adresse für einen der Nodes im Cluster konfigurieren. Sie können diese Node-Management-IP-Adresse verwenden, um den Setup-Assistenten für das Cluster zu starten.

Siehe link:./software_setup/task_create_the_cluster_on_the_first_node.html["Erstellen des Clusters auf dem ersten Node"] Informationen über das Zuweisen einer Node-Management-IP-Adresse.



== Initialisieren und konfigurieren Sie den Cluster

Sie initialisieren den Cluster, indem Sie ein Administratorpasswort für das Cluster festlegen und die Cluster-Management- und Node-Managementnetzwerke einrichten. Sie können auch Dienste wie einen DNS-Server konfigurieren, um Hostnamen aufzulösen und einen NTP-Server, um Zeit zu synchronisieren.

.Schritte
. Geben Sie in einem Webbrowser die IP-Adresse für die Node-Verwaltung ein, die Sie konfiguriert haben: "https://[]
+
System Manager erkennt die im Cluster verbliebenen Nodes automatisch.

. Führen Sie im Fenster *Storage System initialisieren* folgende Schritte durch:
+
.. Geben Sie die Netzwerkkonfigurationsdaten des Cluster-Managements ein.
.. Geben Sie die Node-Management-IP-Adressen für alle Nodes ein.
.. Geben Sie DNS-Details (Domain Name Server) an.
.. Aktivieren Sie im Abschnitt *andere* das Kontrollkästchen *Zeitdienst verwenden (NTP)*, um die Zeitserver hinzuzufügen.




Wenn Sie auf *Absenden* klicken, warten Sie, bis der Cluster erstellt und konfiguriert wurde. Anschließend erfolgt ein Validierungsprozess.

.Nächste Schritte
Nachdem beide Cluster eingerichtet, initialisiert und konfiguriert wurden, führen Sie das folgende Verfahren aus:

* link:task_metrocluster_peering.html["IP-MetroCluster-Peering einrichten"]




== Konfigurieren Sie ONTAP auf einem neuen Cluster-Video

video::PiX41bospbQ[youtube,width=848,height=480]