---
sidebar: sidebar 
permalink: task_nas_file_system_analytics_view.html 
keywords: explorer, file system analytics, inactive data, capacity analytics, active data, historical data 
summary: Nachdem Sie die Dateisystemanalyse aktiviert haben, können Sie im Explorer-Bildschirm Kapazitätsanalysen anzeigen, inaktive Datenperioden festlegen und andere Daten zu Ihren Dateisystemen durchsuchen. 
---
= Zeigen Sie die Dateisystemaktivität in ONTAP an
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nachdem die Dateisystemanalyse (FSA) aktiviert ist, können Sie den Inhalt des Stammverzeichnisses eines ausgewählten Volumes anzeigen, sortiert nach dem in den einzelnen Unterstrukturen verwendeten Speicherplatz.

Wählen Sie ein beliebiges Dateisystemobjekt aus, um das Dateisystem zu durchsuchen und detaillierte Informationen zu jedem Objekt in einem Verzeichnis anzuzeigen. Informationen zu Verzeichnissen können auch grafisch dargestellt werden. Im Laufe der Zeit werden für jede Unterstruktur historische Daten angezeigt. Der verwendete Platz wird nicht sortiert, wenn mehr als 3000 Verzeichnisse vorhanden sind.



== Explorer

Der Bildschirm File System Analytics *Explorer* besteht aus drei Bereichen:

* Strukturansicht von Verzeichnissen und Unterverzeichnissen; erweiterbare Liste mit Namen, Größe, Änderungsverlauf und Zugriffsverlauf.
* Dateien: Name, Größe und Zugriffszeit für das in der Verzeichnisliste ausgewählte Objekt.
* Aktiver und inaktiver Datenvergleich für das in der Verzeichnisliste ausgewählte Objekt.
+
Ab ONTAP 9.9 können Sie den Bereich für die Meldung anpassen. Der Standardwert ist ein Jahr. Auf der Grundlage dieser Anpassungen können Sie Korrekturmaßnahmen vornehmen, z. B. Volumes verschieben und die Tiering-Richtlinie ändern.



Die Zugriffszeit wird standardmäßig angezeigt. Wenn jedoch der Standardwert des Volumes von der CLI geändert wurde (durch Einstellung der `-atime-update` Option auf `false` mit dem `volume modify` Befehl), wird nur die zuletzt geänderte Zeit angezeigt. Beispiel:

* Die Baumansicht zeigt nicht die *Zugriffshistorie* an.
* Die Ansicht der Dateien wird geändert.
* Die aktive/inaktive Datenansicht basiert auf der geänderten Zeit (`mtime`).


Mithilfe dieser Anzeigen können Sie Folgendes überprüfen:

* Speicherorte von Dateisystemen, die den meisten Speicherplatz belegen
* Detaillierte Informationen zu einer Verzeichnisstruktur, einschließlich der Anzahl von Dateien und Unterverzeichnissen innerhalb von Verzeichnissen und Unterverzeichnissen
* Dateisystemstandorte, die alte Daten enthalten (z. B. Scratch-, Temp- oder Log-Bäume)


Beachten Sie bei der Interpretation der FSA-Ausgabe folgende Punkte:

* FSA zeigt an, wo und wann Ihre Daten in Gebrauch sind, nicht wie viele Daten verarbeitet werden. Ein großer Speicherverbrauch von kürzlich aufgerufenen oder geänderten Dateien bedeutet beispielsweise nicht unbedingt, dass die Verarbeitungslasten des Systems sehr hoch sind.
* Die Art und Weise, wie die Registerkarte *Volume Explorer* den Platzbedarf für FSA berechnet, kann von anderen Tools abweichen. Insbesondere könnten erhebliche Unterschiede zum Verbrauch im *Volume Overview* bestehen, wenn für das Volume Storage-Effizienzfunktionen aktiviert sind. Dies liegt daran, dass die Registerkarte *Volume Explorer* keine Effizienzeinsparungen enthält.
* Aufgrund von Platzbeschränkungen in der Verzeichnisanzeige ist es nicht möglich, eine Verzeichnistiefe von mehr als 8 Ebenen in der _Listenansicht_ anzuzeigen. Um Verzeichnisse anzuzeigen, die mehr als 8 Ebenen tief sind, müssen Sie zu _Graphical View_ wechseln, das gewünschte Verzeichnis suchen und dann zurück zu _List View_ wechseln. Dadurch wird zusätzlicher Bildschirmbereich im Display angezeigt.


.Schritte
. Anzeigen des Root-Verzeichnis-Inhalts eines ausgewählten Volumes:
+
[cols="2"]
|===
| In ONTAP 9.8 und 9.9.1 | Ab ONTAP 9.10.1 


| Klicken Sie auf *Storage > Volumes*, wählen Sie das gewünschte Volumen aus und klicken Sie dann auf *Explorer*. | Wählen Sie *Storage > Volumes*, wählen Sie das gewünschte Volumen aus. Wählen Sie im Menü für einzelne Volumes die Option *Dateisystem > Explorer* aus. 
|===

