---
sidebar: sidebar 
permalink: task_admin_monitor_risks.html 
keywords: system manager, monitor, risk, risks, suggestion, suggestions, mitigate, digital advisor, active iq, category, categories, mitigation, impact, impacts, corrections, corrective action, corrective actions, acknowledge risk, dismiss, undismiss, restore, unacknowledge 
summary: Mit System Manager und ONTAP 9.10.0 oder höher lassen sich die von Digital Advisor gemeldeten Risiken überwachen. 
---
= Risiken im ONTAP System Manager überwachen
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ab ONTAP 9.10.0 können Sie mit System Manager die von Active IQ Digital Advisor (auch bekannt als Digital Advisor) gemeldeten Risiken überwachen. Ab ONTAP 9.10.1 können Sie mit System Manager auch die Risiken bestätigen.

NetApp Digital Advisor meldet Möglichkeiten zur Risikoreduzierung sowie zur Verbesserung der Leistung und Effizienz Ihrer Speicherumgebung. Mit System Manager können Sie sich über von Digital Advisor gemeldete Risiken informieren und erhalten verwertbare Informationen, die bei der Verwaltung des Speichers unterstützen und eine höhere Verfügbarkeit, verbesserte Sicherheit sowie bessere Speicherleistung ermöglichen.



[[link-to-your-digital-advisor-account]]
[[link_active_iq]]
== Link zu Ihrem Digital Advisor Konto

Um Informationen über Risiken von Digital Advisor zu erhalten, sollte zunächst über den System Manager eine Verbindung zum Digital Advisor-Konto hergestellt werden.

.Schritte
. Im System Manager auf *Cluster > Einstellungen* klicken.
. Unter *Active IQ Registration* auf *Registrieren* klicken.
. Geben Sie Ihre Zugangsdaten für Digital Advisor ein.
. Nachdem Ihre Anmeldeinformationen authentifiziert wurden, auf *Bestätigen, um Active IQ mit System Manager zu verknüpfen* klicken.




[[view-the-number-of-risks]]
== Anzahl der Risiken anzeigen

Ab ONTAP 9.10.0 ist im Dashboard des System Managers die Anzahl der von Digital Advisor gemeldeten Risiken sichtbar.

.Bevor Sie beginnen
Es ist erforderlich, eine Verbindung vom System Manager zu Ihrem Digital Advisor Konto herzustellen. Weitere Informationen unter <<link_active_iq,Link zu Ihrem Digital Advisor Konto>>.

.Schritte
. Im System Manager auf *Dashboard* klicken.
. Im Abschnitt *Gesundheit* wird die Anzahl der gemeldeten Risiken angezeigt.
+

NOTE: Detailliertere Informationen zu jedem Risiko erhalten Sie durch Anklicken der Meldung mit der Anzahl der Risiken. Siehe <<view_risk_details,Details zu den Risiken>>.





[[view-details-of-risks]]
[[view_risk_details]]
== Details zu den Risiken

Ab ONTAP 9.10.0 kann im System Manager angezeigt werden, wie die von Digital Advisor gemeldeten Risiken nach Wirkungsbereichen kategorisiert sind. Es werden außerdem detaillierte Informationen zu jedem gemeldeten Risiko, dessen potenziellen Auswirkungen auf Ihr System und den möglichen Korrekturmaßnahmen angezeigt.

.Bevor Sie beginnen
Es ist erforderlich, eine Verbindung vom System Manager zu Ihrem Digital Advisor Konto herzustellen. Weitere Informationen unter <<link_active_iq,Link zu Ihrem Digital Advisor Konto>>.

.Schritte
. Wählen Sie *Events > All Events* aus.
. Im Abschnitt *Übersicht* kann unter *Active IQ Suggestions* die Anzahl der Risiken in jeder Wirkungsbereichskategorie angezeigt werden. Die Risikokategorien umfassen:
+
** Leistung und Effizienz
** Verfügbarkeit & Schutz
** Kapazität
** Konfiguration
** Sicherheit


. Klicken Sie auf die Registerkarte *Active IQ Suggestions*, um Informationen zu jedem Risiko anzuzeigen, einschließlich der folgenden:
+
** Auswirkungen auf Ihr System
** Risikokategorie
** Betroffene Knoten
** Art der erforderlichen Minderungsmaßnahmen
** Korrekturmaßnahmen, die Sie ergreifen können






[[acknowledge-risks]]
== Risiken anerkennen

Ab ONTAP 9.10.1 kann der System Manager verwendet werden, um alle offenen Risiken zu bestätigen.

.Schritte
. Im System Manager wird die Liste der Risiken angezeigt, indem die Prozedur in <<view_risk_details,Details zu den Risiken>> ausgeführt wird.
. Klicken Sie auf den Risikonamen eines offenen Risikos, das Sie bestätigen möchten.
. Informationen in die folgenden Felder eingeben:
+
** Erinnerung (Datum)
** Rechtfertigung
** Kommentare


. Auf *Bestätigen* klicken.
+

NOTE: Nachdem Sie ein Risiko bestätigt haben, dauert es einige Minuten, bis die Änderung in der Liste der Digital Advisor Vorschläge angezeigt wird.





[[unacknowledge-risks]]
== Risiken nicht anerkennen

Ab ONTAP 9.10.1 ist es möglich, mit System Manager jedes zuvor bestätigte Risiko zu widerrufen.

.Schritte
. Im System Manager wird die Liste der Risiken angezeigt, indem die Prozedur in <<view_risk_details,Details zu den Risiken>> ausgeführt wird.
. Klicken Sie auf den Risikonamen eines bestätigten Risikos, dessen Bestätigung Sie widerrufen möchten.
. Informationen in die folgenden Felder eingeben:
+
** Rechtfertigung
** Kommentare


. Klicken Sie auf *Bestätigung widerrufen*.
+

NOTE: Nachdem Sie ein Risiko als nicht mehr bestätigt haben, dauert es einige Minuten, bis die Änderung in der Liste der Digital Advisor Vorschläge angezeigt wird.


