---
sidebar: sidebar 
permalink: task_nas_flexcache.html 
keywords: flexcache, flexcache volume, offload traffic, work load, workload, access speed 
summary: FlexCache Volumes beschleunigen den Zugriff auf Daten oder verlagern den Datenverkehr von Volumes, auf die stark zugegriffen wird. FlexCache Volumes eignen sich ideal für leseintensive Workloads, insbesondere wenn Clients wiederholt auf dieselben Daten zugreifen müssen. 
---
= Verbessern Sie mit FlexCache die Performance für mehrere Clients
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
FlexCache Volumes beschleunigen den Zugriff auf Daten oder verlagern den Datenverkehr von Volumes, auf die stark zugegriffen wird. FlexCache Volumes eignen sich ideal für leseintensive Workloads, insbesondere wenn Clients wiederholt auf dieselben Daten zugreifen müssen.

Die Themen in diesem Abschnitt zeigen Ihnen, wie Sie FlexCache Volumes mit System Manager in ONTAP 9.7 und neueren Versionen verwalten.Wenn Sie den klassischen System Manager verwenden (nur in ONTAP 9.7 und älter verfügbar), sehen Sie dieses Thema:

* https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/task_creating_flexcache_volumes.html["FlexCache Volumes erstellen"^]


Das FlexCache Volume kann sich auf demselben Cluster wie oder in einem anderen Cluster befinden als das des Remote Volume. Wenn sich das Remote-Volume auf einem anderen Cluster befindet, müssen Sie bereits die Cluster und Storage VMs Peering durchgeführt haben.


NOTE: Wenn ein HA-Paar nutzt link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html["Verschlüsselung von SAS- oder NVMe-Laufwerken (SED, NSE, FIPS)"], Sie müssen die Anweisungen im Thema folgen link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/return-seds-unprotected-mode-task.html["Ein FIPS-Laufwerk oder eine SED-Festplatte in den ungeschützten Modus zurückkehren"] Für alle Laufwerke innerhalb des HA-Paars vor der Initialisierung des Systems (Boot-Optionen 4 oder 9). Andernfalls kann es zu künftigen Datenverlusten kommen, wenn die Laufwerke einer anderen Verwendung zugewiesen werden.

.Schritte
. Klicken Sie Auf *Storage > Volumes*.
. Klicken Sie Auf *Hinzufügen*.
. Klicken Sie auf *Weitere Optionen* und wählen Sie dann *als Cache für ein Remote-Volume hinzufügen*.
+
.. Wenn Sie ONTAP 9.8 oder höher verwenden und QoS deaktivieren oder eine benutzerdefinierte QoS-Richtlinie auswählen möchten, klicken Sie auf *Mehr Optionen* und wählen Sie dann unter *Speicher und Optimierung* die Option *Performance Service Level*.




Für neue Datenanfragen fordert das FlexCache Volume die Daten vom Remote-Volume an und speichert sie. Alle nachfolgenden Leseanforderungen für die Daten werden dann direkt über das FlexCache Volume bedient.



== Videos



=== So kann FlexCache die WAN-Latenz verringern und die Lesezeiten für globale Daten verkürzen

video::rbbH0l74RWc[youtube,width=848,height=480]


=== Erfahren Sie mehr über die Performance-Vorteile von ONTAP FlexCache!

video::bWi1-8Ydkpg[youtube,width=848,height=480]