---
permalink: element-replication/create-replication-relationship-task.html 
sidebar: sidebar 
keywords: create, relationship, element, source, ontap, destination 
summary: Mithilfe von SnapMirror werden Snapshot Kopien eines Element Volume in ein ONTAP Zielsystem repliziert. Bei einem Ausfall am Element Standort können Sie Clients über das ONTAP System Daten bereitstellen und das Element Quell-Volume nach Wiederherstellung des Service erneut aktivieren. 
---
= Erstellen einer Beziehung von einer Element Quelle zu einem ONTAP Ziel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Beziehung zwischen dem Quell-Volume im primären Storage und dem Ziel-Volume im sekundären Storage wird als „_Data Protection Relationship_“ bezeichnet. Mit dem `snapmirror create` Befehl können Sie eine Datensicherungsbeziehung von einer Element Quelle zu einem ONTAP Ziel oder von einer ONTAP Quelle zu einem Element Ziel erstellen.

Mithilfe von SnapMirror werden Snapshot Kopien eines Element Volume in ein ONTAP Zielsystem repliziert. Bei einem Ausfall am Element Standort können Sie Clients über das ONTAP System Daten bereitstellen und das Element Quell-Volume nach Wiederherstellung des Service erneut aktivieren.

.Bevor Sie beginnen
* Der Element-Node, der das zu replizierende Volume enthält, muss ONTAP zugänglich gemacht werden.
* Das Element Volume muss für die SnapMirror Replizierung aktiviert worden sein.
* Wenn Sie die Richtlinie „`mmirror-Vault`“ verwenden, muss ein SnapMirror Label konfiguriert worden sein, damit die Element Snapshot Kopien repliziert werden können.
+
[NOTE]
====
Diese Aufgabe kann nur in der Web-Benutzeroberfläche der Element Software ausgeführt werden. Weitere Informationen finden Sie im https://docs.netapp.com/us-en/element-software/index.html["Dokumentation des Elements"].

====


.Über diese Aufgabe
Sie müssen den Quellpfad des Elements im Formular angeben `<hostip:>/lun/<name>`, wobei „`lun`“ die tatsächliche Zeichenfolge „`lun`“ ist und `name` der Name des Element-Volumes ist.

Ein Element Volume ist in etwa dem einer ONTAP LUN entsprechenden Modus. SnapMirror erstellt eine LUN mit dem Namen des Element-Volume, wenn eine Datensicherungsbeziehung zwischen Element Software und ONTAP initialisiert wird. SnapMirror repliziert Daten in eine vorhandene LUN, wenn die LUN die Anforderungen für die Replizierung von Element Software zu ONTAP erfüllt.

Replikationsregeln:

* Ein ONTAP Volume kann nur Daten aus einem Element Volume enthalten.
* Es können keine Daten von einem ONTAP Volume auf mehrere Element Volumes repliziert werden.


Ab ONTAP 9.3 und älteren Versionen kann ein Ziel-Volume bis zu 251 Snapshot Kopien enthalten. Ab ONTAP 9.4 kann ein Ziel-Volume bis zu 1019 Snapshot Kopien enthalten.

.Schritt
. Erstellen Sie vom Ziel-Cluster eine Replizierungsbeziehung von einer Elementquelle zu einem ONTAP Ziel:
+
`snapmirror create -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume> -type XDP -schedule schedule -policy <policy>`

+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
Im folgenden Beispiel wird eine SnapMirror DR-Beziehung mithilfe der Standardrichtlinie erstellt `MirrorLatest`:

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorLatest
----
+
Im folgenden Beispiel wird mithilfe der Standardrichtlinie eine einheitliche Replizierungsbeziehung erstellt `MirrorAndVault`:

+
[listing]
----
cluster_dst:> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorAndVault
----
+
Im folgenden Beispiel wird mithilfe der `Unified7year` Richtlinie eine einheitliche Replizierungsbeziehung erstellt:

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy Unified7year
----
+
Im folgenden Beispiel wird mithilfe der benutzerdefinierten `my_unified` Richtlinie eine einheitliche Replizierungsbeziehung erstellt:

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy my_unified
----


.Nachdem Sie fertig sind
 `snapmirror show`Überprüfen Sie mit dem Befehl, ob die SnapMirror Beziehung erstellt wurde. Eine vollständige Befehlssyntax finden Sie in der man-Page.
