---
permalink: tape-backup/access-event-log-files-backup-restore-operations-task.html 
sidebar: sidebar 
keywords: access, event, log, files, rdfile, nodeshell, tap, backup, monitor, restore, operations 
summary: Sie können die Ereignisprotokolldateien für Bandsicherung und Wiederherstellungsvorgänge im Verzeichnis /etc/log/ mit dem Befehl rdfile im nodeshell aufrufen. Sie können diese Ereignisprotokolldateien anzeigen, um Tape-Backup- und Restore-Vorgänge zu überwachen. 
---
= Greifen Sie auf die Ereignis-Log-Dateien zu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können auf die Ereignisprotokolldateien für Bandsicherungs- und Wiederherstellungsvorgänge in zugreifen `/etc/log/` Verzeichnis mit verwenden `rdfile` Befehl im nodeshell. Sie können diese Ereignisprotokolldateien anzeigen, um Tape-Backup- und Restore-Vorgänge zu überwachen.

.Über diese Aufgabe
Mit zusätzlichen Konfigurationen, wie z. B. eine Zugriffskontroll-Rolle mit Zugriff auf das `spi` Webdienst oder ein mit dem eingerichtet Benutzerkonto `http` Zugriffsmethode Sie können auch einen Webbrowser verwenden, um auf diese Protokolldateien zuzugreifen.

.Schritte
. Geben Sie den folgenden Befehl ein, um auf den nodeshell zuzugreifen:
+
`*node run -node _node_name_*`

+
`node_name` Ist der Name des Node.

. Geben Sie den folgenden Befehl ein, um auf die Ereignisprotokolldateien für Backup- und Restore-Vorgänge auf Band zuzugreifen:
+
`*rdfile /etc/log/backup*`



.Verwandte Informationen
link:../system-admin/index.html["Systemadministration"]
