---
permalink: tape-backup/access-event-log-files-backup-restore-operations-task.html 
sidebar: sidebar 
keywords: access, event, log, files, rdfile, nodeshell, tap, backup, monitor, restore, operations 
summary: Sie können auf die Ereignisprotokolldateien für Tape-Backup und Wiederherstellungsvorgänge im Verzeichnis /etc/log/ mit dem Befehl rdfile in der Nodeshell zugreifen. Diese Ereignisprotokolldateien können zur Überwachung von Tape-Backup- und Wiederherstellungsvorgängen eingesehen werden. 
---
= Zugriff auf die ONTAP Ereignisprotokolldateien für Tape-Backup und Restore-Vorgänge
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können auf die Ereignisprotokolldateien für Tape-Backup- und Wiederherstellungsvorgänge im `/etc/log/` Verzeichnis zugreifen, indem Sie den `rdfile` Befehl an der Nodeshell verwenden. Diese Ereignisprotokolldateien können zur Überwachung von Tape-Backup- und Wiederherstellungsvorgängen eingesehen werden.

.Über diese Aufgabe
Mit zusätzlichen Konfigurationen, wie beispielsweise einer Zugriffskontrollrolle mit Zugriff auf den  `spi` Webdienst oder einem Benutzerkonto, das mit der  `http` Zugriffsmethode eingerichtet wurde, ist auch der Zugriff auf diese Protokolldateien über einen Webbrowser möglich.

.Schritte
. Um auf die Nodeshell zuzugreifen, ist folgender Befehl einzugeben:
+
`*node run -node _node_name_*`

+
`node_name` ist der Name des Knotens.

. Um auf die Ereignisprotokolldateien für Tape-Backup und Wiederherstellungsvorgänge zuzugreifen, ist folgender Befehl einzugeben:
+
`*rdfile /etc/log/backup*`



.Verwandte Informationen
link:../system-admin/index.html["Systemadministration"]
