---
permalink: tape-backup/assign-tape-aliases-task.html 
sidebar: sidebar 
keywords: assign, tape, aliases, device, identification, drive, medium, changer, logical, names, backup 
summary: Zur einfachen Geräteidentifizierung kann einem Tape-Laufwerk oder Medienwechsler ein Tape-Alias zugewiesen werden. Aliase stellen eine Entsprechung zwischen den logischen Namen der Backup-Geräte und einem dauerhaft zugewiesenen Namen für das Tape-Laufwerk oder den Medienwechsler her. 
---
= Tape-Aliase einem Tape-Laufwerk oder Medienwechsler für ONTAP Tape-Backup zuweisen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zur einfachen Geräteidentifizierung kann einem Tape-Laufwerk oder Medienwechsler ein Tape-Alias zugewiesen werden. Aliase stellen eine Entsprechung zwischen den logischen Namen der Backup-Geräte und einem dauerhaft zugewiesenen Namen für das Tape-Laufwerk oder den Medienwechsler her.

.Schritte
. Einem Tape-Laufwerk oder einem Medium-Changer kann ein Alias mit dem  `storage tape alias set` Befehl zugewiesen werden.
+
Weitere Informationen zu  `storage tape alias set` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-alias-set.html["ONTAP-Befehlsreferenz"^].

+
Sie können die Seriennummerninformationen (SN) der Tape-Laufwerke mit dem  `system node hardware tape drive show` Befehl und die Informationen zu Tape-Bibliotheken mit den  `system node hardware tape library show` Befehlen anzeigen.

+
Der folgende Befehl weist einem Tape-Laufwerk mit der Seriennummer SN[123456]L4, das an den Knoten cluster1-01 angeschlossen ist, einen Aliasnamen zu:

+
[listing]
----
cluster-01::> storage tape alias set  -node cluster-01 -name st3 -mapping SN[123456]L4
----
+
Der folgende Befehl weist einem Medienwechsler mit der Seriennummer SN[65432], der an den Knoten cluster1-01 angeschlossen ist, einen Aliasnamen zu:

+
[listing]
----
cluster-01::> storage tape alias set  -node cluster-01 -name mc1 -mapping SN[65432]
----


.Verwandte Informationen
* xref:assign-tape-aliases-concept.adoc[Was Tape-Aliasing ist]
* xref:remove-tape-aliases-task.adoc[Entfernen von Tape-Aliasen]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-alias-set.html["Storage-Tape-Alias-Set"^]

