---
permalink: tape-backup/assign-tape-aliases-task.html 
sidebar: sidebar 
keywords: assign, tape, aliases, device, identification, drive, medium, changer, logical, names, backup 
summary: Zur einfachen Geräteerkennung können Sie einem Bandlaufwerk oder einem Mittelwechsler Bandaliase zuweisen. Aliase stellen eine Korrespondenz zwischen den logischen Namen von Sicherungsgeräten und einem Namen dar, der permanent dem Bandlaufwerk oder dem Mittelwechsler zugewiesen ist. 
---
= Weisen Sie in ONTAP Tape-Aliase zu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zur einfachen Geräteerkennung können Sie einem Bandlaufwerk oder einem Mittelwechsler Bandaliase zuweisen. Aliase stellen eine Korrespondenz zwischen den logischen Namen von Sicherungsgeräten und einem Namen dar, der permanent dem Bandlaufwerk oder dem Mittelwechsler zugewiesen ist.

.Schritte
. Weisen Sie einem Bandlaufwerk oder einem Medienwechsler mit dem `storage tape alias set` Befehl einen Alias zu.
+
Erfahren Sie mehr über `storage tape alias set` in der link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-alias-set.html["ONTAP-Befehlsreferenz"^].

+
Sie können die SN-Informationen über die Bandlaufwerke mit dem `system node hardware tape drive show` Befehl und über Bandbibliotheken mit den `system node hardware tape library show` Befehlen anzeigen.

+
Mit dem folgenden Befehl wird ein Alias-Name auf ein Bandlaufwerk mit der Seriennummer SN[123456]L4 festgelegt, das an den Knoten angeschlossen ist, cluster1-01:

+
[listing]
----
cluster-01::> storage tape alias set  -node cluster-01 -name st3 -mapping SN[123456]L4
----
+
Mit dem folgenden Befehl wird ein Alias-Name auf einen Medienwechsler mit der Seriennummer SN[65432], die an den Knoten angeschlossen ist, cluster1-01:

+
[listing]
----
cluster-01::> storage tape alias set  -node cluster-01 -name mc1 -mapping SN[65432]
----


.Verwandte Informationen
xref:assign-tape-aliases-concept.adoc[Verwenden Sie das Tape-Aliasing]

xref:remove-tape-aliases-task.adoc[Entfernen von Bandaliasen]
