---
permalink: tape-backup/availability-volumes-tapes-backup-restore-lif-reference.html 
sidebar: sidebar 
keywords: lif, availability, volumes, tape, devices, backup, restore, types, cab, extension, application 
summary: 'Sie können eine Backup-Applikation konfigurieren, um eine NDMP-Steuerverbindung auf einem der LIF-Typen in einem Cluster herzustellen. Im NDMP-Modus mit Storage Virtual Machine (SVM) können Sie die Verfügbarkeit von Volumes und Tape-Geräten für Backup- und Restore-Vorgänge bestimmen, abhängig von diesen LIF-Typen und dem Status der CAB-Erweiterung.' 
---
= Verfügbarkeit von Volumes und Tape-Geräten für Backup und Restore bei unterschiedlichen LIF-Typen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Backup-Applikation konfigurieren, um eine NDMP-Steuerverbindung auf einem der LIF-Typen in einem Cluster herzustellen. Im NDMP-Modus mit Storage Virtual Machine (SVM) können Sie die Verfügbarkeit von Volumes und Tape-Geräten für Backup- und Restore-Vorgänge bestimmen, abhängig von diesen LIF-Typen und dem Status der CAB-Erweiterung.

In der folgenden Tabelle sind die Verfügbarkeit von Volumes und Bandgeräten für NDMP Control Connection LIF-Typen und der Status der CAB-Erweiterung aufgeführt:



== Verfügbarkeit von Volumes und Bandgeräten, wenn CAB-Erweiterung von der Backup-Anwendung nicht unterstützt wird

|===
| NDMP-Steuerverbindung – LIF-Typ | Volumes verfügbar für Backup und Restore | Bandgeräte für Backup oder Restore verfügbar 


 a| 
Node-Management-LIF
 a| 
Alle Volumes werden von einem Node gehostet
 a| 
Mit dem Node, der die Node-Management-LIF hostet, verbundene Tape-Geräte



 a| 
Data LIF
 a| 
Nur Volumes, die zu der SVM gehören, die von einem Node gehostet wird, der die Daten-LIF hostet
 a| 
Keine



 a| 
Cluster-Management-LIF
 a| 
Alle Volumes werden von einem Node gehostet, der die LIF zum Cluster-Management hostet
 a| 
Keine



 a| 
Intercluster LIF
 a| 
Alle Volumes werden von einem Node gehostet, der die Intercluster LIF hostet
 a| 
Mit dem Node, der die Intercluster-LIF hostet, verbundene Bandgeräte

|===


== Verfügbarkeit von Volumes und Bandgeräten, wenn die CAB-Erweiterung von der Backup-Anwendung unterstützt wird

|===
| NDMP-Steuerverbindung – LIF-Typ | Volumes verfügbar für Backup und Restore | Bandgeräte für Backup oder Restore verfügbar 


 a| 
Node-Management-LIF
 a| 
Alle Volumes werden von einem Node gehostet
 a| 
Mit dem Node, der die Node-Management-LIF hostet, verbundene Tape-Geräte



 a| 
Data LIF
 a| 
Alle Volumes, die zu der SVM gehören, die die Daten-LIF hostet
 a| 
Keine



 a| 
Cluster-Management-LIF
 a| 
Alle Volumes im Cluster
 a| 
Alle Bandgeräte im Cluster



 a| 
Intercluster LIF
 a| 
Alle Volumes im Cluster
 a| 
Alle Bandgeräte im Cluster

|===