---
permalink: tape-backup/availability-volumes-tapes-backup-restore-lif-reference.html 
sidebar: sidebar 
keywords: lif, availability, volumes, tape, devices, backup, restore, types, cab, extension, application 
summary: Sie können eine Backup-Anwendung so konfigurieren, dass sie eine NDMP-Steuerungsverbindung auf jedem LIF-Typ in einem Cluster herstellt. Im NDMP-Modus mit Bezug zur Storage Virtual Machine können Sie die Verfügbarkeit von Volumes und Tape-Geräten für Backup- und Restore-Vorgänge in Abhängigkeit von diesen LIF-Typen und dem Status der CAB-Erweiterung ermitteln. 
---
= Verfügbarkeit von ONTAP Volumes und Tape-Geräten für Backup und Wiederherstellung auf verschiedenen LIF-Typen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Backup-Anwendung so konfigurieren, dass sie eine NDMP-Steuerungsverbindung auf jedem LIF-Typ in einem Cluster herstellt. Im NDMP-Modus mit Storage Virtual Machine (SVM)-Bezug lässt sich die Verfügbarkeit von Volumes und Tape-Geräten für Backup- und Restore-Vorgänge abhängig von diesen LIF-Typen und dem Status der CAB-Erweiterung bestimmen.

Die folgenden Tabellen zeigen die Verfügbarkeit von Volumes und Tape-Geräten für NDMP-Steuerungsverbindungs-LIF-Typen und den Status der CAB-Erweiterung:



[[availability-of-volumes-and-tape-devices-when-cab-extension-is-not-supported-by-the-backup-application]]
== Verfügbarkeit von Volumes und Tape-Geräten, wenn die CAB-Erweiterung von der Backup-Anwendung nicht unterstützt wird

|===
| NDMP-Steuerverbindung LIF-Typ | Verfügbare Volumes für Backup oder Restore | Tape-Geräte für Backup oder Wiederherstellung verfügbar 


 a| 
Node-Management-LIF
 a| 
Alle von einem Knoten gehosteten Volumes
 a| 
Tape-Geräte, die mit dem Knoten verbunden sind, auf dem die Node-Management-LIF gehostet wird



 a| 
Data LIF
 a| 
Nur Volumes, die zu der SVM gehören, die von einem Knoten gehostet wird, der die Daten-LIF hostet
 a| 
Keine



 a| 
Cluster-Management LIF
 a| 
Alle Volumes, die von einem Knoten gehostet werden, der das Cluster-Management-LIF hostet
 a| 
Keine



 a| 
Intercluster-LIF
 a| 
Alle Volumes, die von einem Knoten gehostet werden, der das Intercluster-LIF hostet
 a| 
Tape-Geräte, die mit dem Knoten verbunden sind, der das Intercluster-LIF hostet

|===


[[availability-of-volumes-and-tape-devices-when-cab-extension-is-supported-by-the-backup-application]]
== Verfügbarkeit von Volumes und Tape-Geräten, wenn die CAB-Erweiterung von der Backup-Anwendung unterstützt wird

|===
| NDMP-Steuerverbindung LIF-Typ | Verfügbare Volumes für Backup oder Restore | Tape-Geräte für Backup oder Wiederherstellung verfügbar 


 a| 
Node-Management-LIF
 a| 
Alle von einem Knoten gehosteten Volumes
 a| 
Tape-Geräte, die mit dem Knoten verbunden sind, auf dem die Node-Management-LIF gehostet wird



 a| 
Data LIF
 a| 
Alle Volumes, die zu der SVM gehören, die die Daten-LIF hostet
 a| 
Keine



 a| 
Cluster-Management LIF
 a| 
Alle Volumes im Cluster
 a| 
Alle Tape-Geräte im Cluster



 a| 
Intercluster-LIF
 a| 
Alle Volumes im Cluster
 a| 
Alle Tape-Geräte im Cluster

|===