---
permalink: tape-backup/commands-manage-drives-media-changers-reference.html 
sidebar: sidebar 
keywords: manage, tape, drive, media, changer, operation, cluster, cartridge, position, online, offline, reset, clear 
summary: Es gibt Befehle zur Anzeige von Informationen über Bandlaufwerke und Medienwechsler in einem Cluster, um ein Bandlaufwerk online zu schalten und offline zu schalten, die Position der Bandlaufwerkkassette zu ändern, den Aliasnamen des Bandlaufwerks einzustellen und zu löschen und ein Bandlaufwerk zurückzusetzen. Sie können auch Statistiken zu Bandlaufwerken anzeigen und zurücksetzen. 
---
= Befehle für die Verwaltung von Bandlaufwerken, Medienwechslern und Bandlaufwerken in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es gibt Befehle zur Anzeige von Informationen über Bandlaufwerke und Medienwechsler in einem Cluster, um ein Bandlaufwerk online zu schalten und offline zu schalten, die Position der Bandlaufwerkkassette zu ändern, den Aliasnamen des Bandlaufwerks einzustellen und zu löschen und ein Bandlaufwerk zurückzusetzen. Sie können auch Statistiken zu Bandlaufwerken anzeigen und zurücksetzen.

|===
| Ihr Ziel ist | Befehl 


 a| 
Bringen Sie ein Bandlaufwerk online
 a| 
`storage tape online`



 a| 
Löschen Sie einen Alias-Namen für Bandlaufwerk oder Medienwechsler
 a| 
`storage tape alias clear`



 a| 
Aktivieren oder deaktivieren Sie einen Bandlaufvorgang für ein Bandlaufwerk
 a| 
`storage tape trace`



 a| 
Ändern Sie die Position der Bandlaufwerk-Patrone
 a| 
`storage tape position`



 a| 
Setzen Sie ein Bandlaufwerk zurück
 a| 
`storage tape reset`

[NOTE]
====
Dieser Befehl ist nur auf der erweiterten Berechtigungsebene verfügbar.

====


 a| 
Legen Sie einen Alias-Namen für Bandlaufwerk oder Medienwechsler fest
 a| 
`storage tape alias set`



 a| 
Versetzen Sie ein Bandlaufwerk in den Offline-Modus
 a| 
`storage tape offline`



 a| 
Hier finden Sie Informationen zu allen Bandlaufwerken und Medienwechslern
 a| 
`storage tape show`



 a| 
Zeigen Sie Informationen über Bandlaufwerke an, die mit dem Cluster verbunden sind
 a| 
* `storage tape show-tape-drive`
* `system node hardware tape drive show`




 a| 
Zeigen Sie Informationen über an den Cluster angeschlossene Medienwechsler an
 a| 
`storage tape show-media-changer`



 a| 
Zeigen Sie Fehlerinformationen zu Bandlaufwerken an, die mit dem Cluster verbunden sind
 a| 
`storage tape show-errors`



 a| 
Zeigen Sie alle für ONTAP geeigneten und unterstützten Bandlaufwerke an, die mit jedem Node im Cluster verbunden sind
 a| 
`storage tape show-supported-status`



 a| 
Zeigen Sie Aliase aller Bandlaufwerke und Medienwechsler an, die mit jedem Knoten im Cluster verbunden sind
 a| 
`storage tape alias show`



 a| 
Setzen Sie den Statistikwert eines Bandlaufwerks auf Null zurück
 a| 
`storage stats tape zero` `tape_name`

Sie müssen diesen Befehl in der nodeshell verwenden.



 a| 
View Tape-Laufwerke, die von ONTAP unterstützt werden
 a| 
`storage show tape supported [-v]`

Sie müssen diesen Befehl in der nodeshell verwenden. Sie können die `-v` Option verwenden, um weitere Details zu den einzelnen Bandlaufwerken anzuzeigen.



 a| 
Zeigen Sie Statistiken zu Bandgeräten an, um die Bandleistung zu verstehen und das Nutzungsmuster zu überprüfen
 a| 
`storage stats tape` `tape_name`

Sie müssen diesen Befehl in der nodeshell verwenden.

|===
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+tape["Speicherband"^]

