---
permalink: tape-backup/commands-manage-node-scoped-ndmp-reference.html 
sidebar: sidebar 
keywords: command, manage, node, scoped, ndmp, mode 
summary: Sie können NDMP-Befehle des Systemservices verwenden, um NDMP auf Node-Ebene zu verwalten. Einige dieser Befehle sind veraltet und werden in einer zukünftigen größeren Version entfernt. 
---
= Befehle für die Verwaltung des NDMP-Modus mit Node-Umfang
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können `system services ndmp` NDMP mit diesen Befehlen auf Node-Ebene verwalten. Einige dieser Befehle sind veraltet und werden in einer zukünftigen größeren Version entfernt.

Sie können die folgenden NDMP-Befehle nur auf der erweiterten Berechtigungsebene verwenden:

* `system services ndmp service terminate`
* `system services ndmp service start`
* `system services ndmp service stop`
* `system services ndmp log start`
* `system services ndmp log stop`


|===
| Ihr Ziel ist | Befehl 


 a| 
Aktivieren des NDMP-Service
 a| 
`system services ndmp on`*



 a| 
Deaktivieren des NDMP-Dienstes
 a| 
`system services ndmp off`*



 a| 
Zeigt die NDMP-Konfiguration an
 a| 
`system services ndmp show`*



 a| 
NDMP-Konfiguration ändern
 a| 
`system services ndmp modify`*



 a| 
Zeigt die Standard-NDMP-Version an
 a| 
`system services ndmp version`*



 a| 
Zeigt die Konfiguration des NDMP-Dienstes an
 a| 
`system services ndmp service show`



 a| 
Konfiguration des NDMP-Dienstes ändern
 a| 
`system services ndmp service modify`



 a| 
Zeigt alle NDMP-Sitzungen an
 a| 
`system services ndmp status`



 a| 
Anzeigen detaillierter Informationen zu allen NDMP-Sitzungen
 a| 
`system services ndmp probe`



 a| 
Beenden Sie die angegebene NDMP-Sitzung
 a| 
`system services ndmp kill`



 a| 
Beenden Sie alle NDMP-Sitzungen
 a| 
`system services ndmp kill-all`



 a| 
Ändern Sie das NDMP-Passwort
 a| 
`system services ndmp password`*



 a| 
Aktivieren des NDMP-Modus mit Node-Umfang
 a| 
`system services ndmp node-scope-mode on`*



 a| 
Deaktivieren Sie den NDMP-Modus mit Node-Umfang
 a| 
`system services ndmp node-scope-mode off`*



 a| 
Zeigen den Status des NDMP-Modus mit Node-Umfang an
 a| 
`system services ndmp node-scope-mode status`*



 a| 
Alle NDMP-Sitzungen mit Nachdruck beenden
 a| 
`system services ndmp service terminate`



 a| 
Starten Sie den NDMP-Service-Daemon
 a| 
`system services ndmp service start`



 a| 
Beenden Sie den NDMP-Service-Daemon
 a| 
`system services ndmp service stop`



 a| 
Starten Sie die Protokollierung für die angegebene NDMP-Sitzung
 a| 
`system services ndmp log start`*



 a| 
Beenden der Protokollierung für die angegebene NDMP-Sitzung
 a| 
`system services ndmp log stop`*

|===
* Diese Befehle sind veraltet und werden in einer zukünftigen größeren Version entfernt.


Weitere Informationen zu diesen `system services ndmp` Befehlen finden Sie in den man-Pages für die Befehle.
