---
permalink: tape-backup/could-not-initialize-media-reference.html 
sidebar: sidebar 
keywords: initiate, media, error, corrective, action, fix, problem, tape, drive, corrupt, damaged, backup, active, io, thread 
summary: Die Medien konnten nicht initialisiert werden. 
---
= Medien konnten nicht initialisiert werden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
* *Nachricht*
+
`Could not initialize media`

* *Ursache*
+
Dieser Fehler kann aus einem der folgenden Gründe auftreten:

+
** Das für das Backup verwendete Tape-Laufwerk ist beschädigt oder defekt.
** Das Band enthält nicht die vollständige Sicherung oder ist beschädigt.
** Die maximale Anzahl aktiver lokaler Tape-E/A-Threads ist derzeit belegt.
+
Es sind maximal 16 aktive lokale Tape-Laufwerke möglich.



* *Korrekturmaßnahme*
+
** Wenn das Tape-Laufwerk defekt oder beschädigt ist, sollte der Vorgang mit einem gültigen Tape-Laufwerk wiederholt werden.
** Wenn das Band nicht die vollständige Sicherung enthält oder beschädigt ist, kann die Wiederherstellung nicht durchgeführt werden.
** Falls keine Bandressourcen verfügbar sind, sollte abgewartet werden, bis einige Sicherungs- oder Wiederherstellungsaufträge abgeschlossen sind, und anschließend kann der Vorgang erneut versucht werden.



