---
permalink: tape-backup/delete-restartable-contexts-task.html 
sidebar: sidebar 
keywords: delete, restartable, contents, backup, context 
summary: Wenn Sie ein Backup starten möchten, anstatt einen Kontext neu zu starten, können Sie den Kontext löschen. 
---
= Löschen von neu startbaren Kontexten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ein Backup starten möchten, anstatt einen Kontext neu zu starten, können Sie den Kontext löschen.

.Über diese Aufgabe
Sie können mit dem `vserver services ndmp restartable-backup delete` Befehl einen neu startbaren Kontext löschen, indem Sie den SVM-Namen und die Kontext-ID angeben.

.Schritte
. Löschen eines neu startbaren Kontexts:
+
`*vserver services ndmp restartable-backup delete -vserver _vserver-name_ -context-id _context_identifier_*`.

+
[listing]
----
cluster::> vserver services ndmpd restartable-backup show
Vserver     Context Identifier                   Is Cleanup Pending?
----------- ------------------------------------ -------------------
vserver1    330e6739-0179-11e6-a299-005056bb4bc9 false
vserver1    481025c1-0179-11e6-a299-005056bb4bc9 false
vserver2    5cf10132-0179-11e6-a299-005056bb4bc9 false
3 entries were displayed.

cluster::>
cluster::> vserver services ndmp restartable-backup delete -vserver vserver1 -context-id 481025c1-0179-11e6-a299-005056bb4bc9

cluster::> vserver services ndmpd restartable-backup show
Vserver     Context Identifier                   Is Cleanup Pending?
----------- ------------------------------------ -------------------
vserver1    330e6739-0179-11e6-a299-005056bb4bc9 false
vserver2    5cf10132-0179-11e6-a299-005056bb4bc9 false
3 entries were displayed.

cluster::>"
----

