---
permalink: tape-backup/dump-backup-concept.html 
sidebar: sidebar 
keywords: dump, backup, qtree, file, system, data 
summary: Ein Dump Backup schreibt mithilfe eines vordefinierten Prozesses Daten des Dateisystems von der Festplatte auf das Band. Sie können ein Backup eines Volumes, eines qtree oder Subbaums erstellen, der weder ein gesamtes Volume noch ein ganzer qtree ist. 
---
= So funktioniert ein Dump-Backup mit ONTAP NDMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Dump Backup schreibt mithilfe eines vordefinierten Prozesses Daten des Dateisystems von der Festplatte auf das Band. Sie können ein Backup eines Volumes, eines qtree oder Subbaums erstellen, der weder ein gesamtes Volume noch ein ganzer qtree ist.

In der folgenden Tabelle wird der Vorgang beschrieben, den ONTAP zum Backup des Objekts verwendet, das vom Dump-Pfad angegeben wird:

[cols="1,4"]
|===
| Stufe | Aktion 


 a| 
1
 a| 
Bei weniger als vollständigen Volume oder vollständigen qtree Backups durchläuft ONTAP Verzeichnisse, um die zu sichernden Dateien zu identifizieren. Wenn Sie ein ganzes Volume oder einen gesamten qtree sichern, kombiniert ONTAP diese Phase mit Phase 2.



 a| 
2
 a| 
Bei einem vollständigen Volume oder vollständigen qtree-Backup identifiziert ONTAP die Verzeichnisse in den Volumes oder in den zu sichernden qtrees.



 a| 
3
 a| 
ONTAP schreibt die Verzeichnisse auf Band.



 a| 
4
 a| 
ONTAP schreibt die Dateien auf das Band.



 a| 
5
 a| 
ONTAP schreibt die ACL-Informationen (falls zutreffend) auf Tapes.

|===
Das Dump Backup verwendet einen Snapshot Ihrer Daten für das Backup. Daher müssen Sie das Volume vor dem Start des Backups nicht offline schalten.

Der Dump Backup benennt jeden Snapshot, den er erstellt als `snapshot_for_backup.n`, wobei `n` eine Ganzzahl ist, die bei 0 beginnt. Jedes Mal, wenn das Dump-Backup einen Snapshot erstellt, wird die Ganzzahl um 1 erhöht. Die Ganzzahl wird nach dem Neustart des Speichersystems auf 0 zurückgesetzt. Nach Abschluss des Sicherungsvorgangs löscht die Dump-Engine diesen Snapshot.

Wenn ONTAP mehrere Dump-Backups gleichzeitig durchführt, erstellt die Dump-Engine mehrere Snapshots. Wenn ONTAP beispielsweise zwei Dump-Backups gleichzeitig ausführt, finden Sie die folgenden Snapshots in den Volumes, von denen Daten gesichert werden: `snapshot_for_backup.0` Und `snapshot_for_backup.1`.

[NOTE]
====
Wenn Sie ein Backup von einem Snapshot erstellen, erstellt die Dump-Engine keinen zusätzlichen Snapshot.

====


== Arten von Daten, die die Dump-Engine sichert

Die Dump-Engine ermöglicht es Ihnen, Daten-Backups auf Tape zu erstellen, um sie vor Ausfällen oder Controller-Unterbrechungen zu schützen. Zusätzlich zum Backup von Datenobjekten wie Dateien, Verzeichnisse, qtrees oder ganzen Volumes kann die Dump-Engine viele Arten von Informationen zu jeder Datei sichern. Wenn Sie wissen, welche Daten von der Dump-Engine gesichert werden können und welche Einschränkungen berücksichtigt werden müssen, können Sie Ihren Ansatz für die Disaster Recovery planen.

Zusätzlich zum Sichern von Daten in Dateien kann die Dump-Engine die folgenden Informationen über jede Datei sichern, falls zutreffend:

* UNIX GID, Besitzer-UID und Dateiberechtigungen
* Zugriff, Erstellung und Änderung für UNIX-Systeme
* Dateityp
* Dateigröße
* DOS-Name, DOS-Attribute und Erstellungszeit
* Zugriffssteuerungslisten (ACLs) mit 1,024 Einträgen (Aces)
* Qtree Informationen
* Verbindungspfade


Verbindungspfade werden als symbolische Links gesichert.

* Klone zu LUNs und LUNs
+
Sie können ein vollständiges LUN-Objekt sichern. Sie können jedoch keine einzelne Datei innerhalb des LUN-Objekts sichern. Auf ähnliche Weise können Sie ein gesamtes LUN-Objekt, jedoch keine einzelne Datei in der LUN wiederherstellen.

+
[NOTE]
====
Die Dump-Engine sichert LUN-Klone als unabhängige LUNs.

====
* VM-bezogene Dateien
+
Das Backup von VM-ausgerichteten Dateien wird in Versionen vor Data ONTAP 8.1 nicht unterstützt.



[NOTE]
====
Wenn ein Snapshot-gesicherter LUN-Klon von Data ONTAP 7-Mode auf ONTAP migriert wird, ist dies eine inkonsistente LUN. Die Dump-Engine führt nicht zu einem Backup inkonsistenter LUNs.

====
Wenn Sie Daten auf einem Volume wiederherstellen, sind die Client-I/O-Vorgänge auf die wiederherzustellenden LUNs beschränkt. Die LUN-Einschränkung wird nur entfernt, wenn der Dump-Wiederherstellungsvorgang abgeschlossen ist. Ebenso beschränkt sich der Client-I/O während einer Wiederherstellung einzelner Dateien oder LUNs auf die wiederherzustellenden Dateien und LUNs. Diese Einschränkung wird nur entfernt, wenn die einzelne Datei oder die LUN-Wiederherstellung abgeschlossen ist. Wenn auf einem Volume, auf dem eine Dump-Wiederherstellung oder eine einzelne SnapMirror-Datei oder eine LUN-Wiederherstellung durchgeführt wird, ein Dump-Backup durchgeführt wird, werden die Dateien oder LUNs, die eine Client-I/O-Einschränkung aufweisen, nicht in das Backup einbezogen. Diese Dateien oder LUNs sind in einem nachfolgenden Backup-Vorgang enthalten, wenn die Client-I/O-Einschränkung entfernt wird.

[NOTE]
====
Eine LUN, die auf Data ONTAP 8.3 ausgeführt wird und auf Tape gesichert wird, kann nur in 8.3 oder späteren Versionen wiederhergestellt werden, und nicht in einer früheren Version. Wenn die LUN auf eine frühere Version wiederhergestellt wird, wird die LUN als Datei wiederhergestellt.

====
Wenn Sie ein sekundäres SnapVault Volume oder ein Ziel-SnapMirror Volume auf Band sichern, werden nur die Daten auf dem Volume gesichert. Die zugehörigen Metadaten werden nicht gesichert. Wenn Sie also versuchen, das Volume wiederherzustellen, werden nur die Daten auf diesem Volume wiederhergestellt. Informationen über die Volume SnapMirror-Beziehungen sind im Backup nicht verfügbar und werden daher nicht wiederhergestellt.

Wenn Sie eine Datei abladen, die nur Windows NT Berechtigungen hat und sie auf einen UNIX-Stil qtree oder Volume wiederherstellen, erhält die Datei die standardmäßigen UNIX Berechtigungen für diesen qtree oder Volume.

Wenn Sie eine Datei abspeichern, die nur UNIX Berechtigungen hat und sie auf einen NTFS-Stil qtree oder Volume wiederherstellen, erhält die Datei die standardmäßigen Windows Berechtigungen für diesen qtree oder Volume.

Bei anderen Dumps und Wiederherstellungen werden die Berechtigungen beibehalten.

Sie können neben den Dateien, die an VMs ausgerichtet `vm-align-sector` sind, auch Backups erstellen. Weitere Informationen zu VM-ausgerichteten Dateien finden Sie unter link:../volumes/index.html["Logisches Storage-Management"].
