---
permalink: tape-backup/dump-snapmirror-single-file-lun-restore-concept.html 
sidebar: sidebar 
keywords: dump, works, snapmirror, single, file, lun, restore, operation 
summary: Bevor Sie Dump-Backup oder -Restore-Vorgänge auf einem Volume ausführen, auf das eine einzelne Datei oder LUN mithilfe der SnapMirror Technologie wiederhergestellt wird, müssen Sie verstehen, wie Dump-Vorgänge mit einer einzelnen Datei oder einer LUN-Wiederherstellung funktionieren. 
---
= Wie Dump funktioniert mit SnapMirror Single File- oder LUN-Wiederherstellung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie Dump-Backup oder -Restore-Vorgänge auf einem Volume ausführen, auf das eine einzelne Datei oder LUN mithilfe der SnapMirror Technologie wiederhergestellt wird, müssen Sie verstehen, wie Dump-Vorgänge mit einer einzelnen Datei oder einer LUN-Wiederherstellung funktionieren.

Bei einer einzelnen SnapMirror Datei oder einem LUN-Restore sind die Client-I/O-Vorgänge auf die Datei oder das wiederherzustellende LUN beschränkt. Sobald die Wiederherstellung einer einzelnen Datei oder eines LUN abgeschlossen ist, wird die I/O-Einschränkung für die Datei oder LUN entfernt. Wenn ein Dump-Backup auf einem Volume ausgeführt wird, auf das eine einzelne Datei oder eine LUN wiederhergestellt wird, dann ist die Datei oder die LUN, die die Client-I/O-Einschränkung aufweist, nicht in das Dump-Backup enthalten. Bei einem nachfolgenden Backup-Vorgang wird diese Datei oder dieses LUN nach dem Entfernen der I/O-Einschränkung auf Tape gesichert.

Sie können keine Dump-Wiederherstellung und keine SnapMirror-Wiederherstellung gleichzeitig auf demselben Volume durchführen.
