---
permalink: tape-backup/dump-events-concept.html 
sidebar: sidebar 
keywords: dump, event, field, information, parenthesis, type 
summary: Das Ereignisfeld für ein Dump-Ereignis enthält einen Ereignistyp, gefolgt von ereignisspezifischen Informationen in Klammern. 
---
= Was sind Dump-Ereignisse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Ereignisfeld für ein Dump-Ereignis enthält einen Ereignistyp, gefolgt von ereignisspezifischen Informationen in Klammern.

In der folgenden Tabelle werden die Ereignisse, ihre Beschreibungen und verwandte Ereignisinformationen beschrieben, die für einen Dump-Vorgang aufgezeichnet werden können:

|===
| Ereignis | Beschreibung | Ereignisinformationen 


 a| 
Starten
 a| 
NDMP Dump wird gestartet
 a| 
Dump-Ebene und die Art von Dump



 a| 
Beenden
 a| 
Speicherabbilder erfolgreich abgeschlossen
 a| 
Menge der verarbeiteten Daten



 a| 
Abbrechen
 a| 
Der Vorgang wird abgebrochen
 a| 
Menge der verarbeiteten Daten



 a| 
Optionen
 a| 
Die angegebenen Optionen sind aufgelistet
 a| 
Alle Optionen und die zugehörigen Werte, einschließlich NDMP-Optionen



 a| 
Tape_öffnen
 a| 
Das Band ist für Lese-/Schreibzugriff geöffnet
 a| 
Der neue Name des Bandgeräts



 a| 
Tape_close
 a| 
Das Band ist für Lese-/Schreibzugriff geschlossen
 a| 
Der Name des Bandgeräts



 a| 
Phasenänderung
 a| 
Ein Dump wird in eine neue Verarbeitungsphase eingegeben
 a| 
Der neue Phasenname



 a| 
Fehler
 a| 
In einem Dump ist ein unerwartetes Ereignis aufgetreten
 a| 
Fehlermeldung



 a| 
Snapshot
 a| 
Eine Snapshot Kopie wird erstellt oder gefunden
 a| 
Der Name und die Uhrzeit der Snapshot Kopie



 a| 
Base_dump
 a| 
Ein Base Dump-Eintrag in der internen Metadatei wurde gefunden
 a| 
Level und Zeit des Basis-Dump (nur für inkrementelle Dumps)

|===