---
permalink: tape-backup/dump-snapmirror-single-file-lun-restore-concept.html 
sidebar: sidebar 
keywords: dump, works, snapmirror, single, file, lun, restore, operation 
summary: Bevor mit Hilfe der SnapMirror Technologie Dump-Backup- oder Wiederherstellungsvorgänge auf einem Volume durchgeführt werden, auf dem eine einzelne Datei oder LUN wiederhergestellt wird, ist es wichtig zu verstehen, wie Dump-Vorgänge mit einer einzelnen Datei- oder LUN-Wiederherstellung zusammenwirken. 
---
= Funktionsweise von Dump bei einer ONTAP SnapMirror Wiederherstellung einer einzelnen Datei oder LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor mit Hilfe der SnapMirror Technologie Dump-Backup- oder Wiederherstellungsvorgänge auf einem Volume durchgeführt werden, auf dem eine einzelne Datei oder LUN wiederhergestellt wird, ist es wichtig zu verstehen, wie Dump-Vorgänge mit einer einzelnen Datei- oder LUN-Wiederherstellung zusammenwirken.

Während einer SnapMirror Wiederherstellung einer einzelnen Datei oder LUN wird die Client-E/A für die wiederherzustellende Datei oder LUN eingeschränkt. Wenn die Wiederherstellung einer einzelnen Datei oder LUN abgeschlossen ist, wird die E/A-Einschränkung für die Datei oder LUN aufgehoben. Wenn ein Dump-Backup auf einem Volume durchgeführt wird, auf das eine einzelne Datei oder LUN wiederhergestellt wurde, ist die Datei oder LUN mit Client-E/A-Einschränkung nicht im Dump-Backup enthalten. Bei einem nachfolgenden Backup wird diese Datei oder LUN nach Aufhebung der E/A-Einschränkung auf Band gesichert.

Es ist nicht möglich, auf demselben Volume gleichzeitig eine Dump-Wiederherstellung und eine SnapMirror Einzeldatei- oder LUN-Wiederherstellung durchzuführen.
