---
permalink: tape-backup/dump-volume-move-concept.html 
sidebar: sidebar 
keywords: dump, works, volume, move, tape, backup, restore, storage, system 
summary: Tape-Backup- und Restore-Vorgänge sowie Volume-Verschiebung können parallel ausgeführt werden, bis die letzte Umstellungsphase vom Storage-System versucht wird. Nach dieser Phase sind neue Backup- und Restore-Vorgänge auf Tape auf dem zu verschiebenden Volume nicht zulässig. Die aktuellen Vorgänge werden jedoch bis zum Abschluss fortgesetzt. 
---
= Wie Dump funktioniert mit Volume-Verschiebung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tape-Backup- und Restore-Vorgänge sowie Volume-Verschiebung können parallel ausgeführt werden, bis die letzte Umstellungsphase vom Storage-System versucht wird. Nach dieser Phase sind neue Backup- und Restore-Vorgänge auf Tape auf dem zu verschiebenden Volume nicht zulässig. Die aktuellen Vorgänge werden jedoch bis zum Abschluss fortgesetzt.

In der folgenden Tabelle wird das Verhalten von Tape-Backup- und Restore-Vorgängen nach dem Verschieben eines Volumes beschrieben:

|===
| Wenn Sie Tape-Backup- und Restore-Vorgänge im ausführen... | Dann... 


 a| 
Der NDMP-Modus im Umfang der Storage Virtual Machine (SVM) wird bereitgestellt, wenn die CAB-Erweiterung von der Backup-Applikation unterstützt wird
 a| 
Sie können weiterhin inkrementelle Backup- und Restore-Vorgänge auf Lese-/Schreib- und schreibgeschützten Volumes durchführen, ohne die Backup-Richtlinien neu zu konfigurieren.



 a| 
SVM-Scoped NDMP-Modus, wenn CAB-Erweiterung nicht von der Backup-Applikation unterstützt wird
 a| 
Sie können weiterhin inkrementelle Tape-Backups und Restore-Vorgänge bei Lese-/Schreib- und schreibgeschützten Volumes durchführen, wenn Sie die in der Backup-Richtlinie konfigurierte LIF auf den Node migrieren, der das Zielaggregat hostet. Andernfalls müssen Sie nach der Verschiebung eines Volumes ein Basis-Backup durchführen, bevor Sie den inkrementellen Backup-Vorgang durchführen.

|===
[NOTE]
====
Wenn das Volume, das zu einer anderen SVM auf dem Ziel-Node gehört, denselben Namen wie das verschobene Volume hat, können Sie bei der Verschiebung keine inkrementellen Backup-Vorgänge durchführen.

====