---
permalink: tape-backup/dump-backup-restore-operations-mcc-config-concept.html 
sidebar: sidebar 
keywords: dump, backup, restore, opartion, metrocluster, configuration, switchback, switchover 
summary: Bevor Sie Dump-Backup und Restore-Vorgänge in einer MetroCluster Konfiguration durchführen, ist es wichtig zu verstehen, wie sich Dump-Vorgänge auswirken, wenn ein Switchover oder Switchback erfolgt. 
---
= Wie sich Dump-Backup- und Restore-Vorgänge in ONTAP MetroCluster Konfigurationen auswirken
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie Dump-Backup und Restore-Vorgänge in einer MetroCluster Konfiguration durchführen, ist es wichtig zu verstehen, wie sich Dump-Vorgänge auswirken, wenn ein Switchover oder Switchback erfolgt.



[[dump-backup-or-restore-operation-followed-by-switchover]]
== Dump-Backup oder Wiederherstellungsvorgang, gefolgt von Switchover

Betrachten Sie zwei Cluster: Cluster 1 und Cluster 2. Während einer Dump-Backup- oder Wiederherstellungsoperation auf Cluster 1, wenn ein Switchover von Cluster 1 zu Cluster 2 eingeleitet wird, tritt Folgendes ein:

* Ist der Wert der  `override-vetoes` Option  `false`, wird der Switchover abgebrochen und der Backup- oder Recovery-Vorgang fortgesetzt.
* Wenn der Wert der Option  `true` ist, wird der Dump-Backup- oder Wiederherstellungsvorgang abgebrochen und die Umschaltung fortgesetzt.




[[dump-backup-or-restore-operation-followed-by-switchback]]
== Dump-Backup oder Wiederherstellungsvorgang, gefolgt von Switchback

Es wird ein Switchover von Cluster 1 zu Cluster 2 durchgeführt und ein Dump-Backup- oder Wiederherstellungsvorgang auf Cluster 2 initiiert. Der Dump-Vorgang sichert oder stellt ein Volume wieder her, das sich auf Cluster 2 befindet. Zu diesem Zeitpunkt, wenn ein Switchback von Cluster 2 zu Cluster 1 eingeleitet wird, tritt Folgendes ein:

* Wenn der Wert der  `override-vetoes` Option  `false` ist, wird der Switchback abgebrochen und der Backup- oder Restore-Vorgang fortgesetzt.
* Wenn der Wert der Option  `true` ist, wird der Sicherungs- oder Wiederherstellungsvorgang abgebrochen und der Switchback fortgesetzt.




[[dump-backup-or-restore-operation-initiated-during-a-switchover-or-switchback]]
== Sicherungs- oder Wiederherstellungsoperation per Dump, die während eines Switchover oder Switchback initiiert wurde

Während eines Switchover von Cluster 1 zu Cluster 2 schlägt ein Dump-Backup- oder Wiederherstellungsvorgang auf Cluster 1 fehl, und der Switchover wird fortgesetzt.

Wenn während eines Switchback von Cluster 2 zu Cluster 1 ein Dump-Backup oder Wiederherstellungsvorgang von Cluster 2 aus initiiert wird, schlägt der Backup- oder Wiederherstellungsvorgang fehl und der Switchback wird fortgesetzt.
