---
permalink: tape-backup/enable-reservations-task.html 
sidebar: sidebar 
keywords: enable, disable, tape, reservation, turn, on 
summary: Sie können steuern, wie ONTAP die Reservierung von Bandgeräten verwaltet, indem Sie die Option Tape.reservations verwenden. Standardmäßig ist die Tape-Reservierung deaktiviert. 
---
= Aktivieren oder Deaktivieren von Bandreservierungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können steuern, wie ONTAP Reservierungen für Bandgeräte mit dem verwaltet `tape.reservations` Option. Standardmäßig ist die Tape-Reservierung deaktiviert.

Die Aktivierung der Option zur Bandreservierung kann Probleme verursachen, wenn Bandlaufwerke, Mittelwechsler, Brücken oder Bibliotheken nicht ordnungsgemäß funktionieren. Wenn Bandbefehle melden, dass das Gerät reserviert ist, wenn keine anderen Speichersysteme das Gerät verwenden, sollte diese Option deaktiviert werden.

.Schritte
. Um entweder den SCSI-Reserve-/Release-Mechanismus oder SCSI Persistent Reservationsor zum Deaktivieren von Bandreservierungen zu verwenden, geben Sie folgenden Befehl in der clustershell ein:
+
`*options -option-name tape.reservations -option-value {scsi | persistent | off}*`

+
`scsi` Wählt den SCSI-Reserve-/Freigabemechanismus aus.

+
`persistent` Wählt persistente SCSI-Reservierungen aus.

+
`off` Deaktiviert Bandreservierungen.



xref:tape-reservations-concept.adoc[Welche Tape-Reservierungen sind]
