---
permalink: tape-backup/event-logging-concept.html 
sidebar: sidebar 
keywords: monitor, tape, backup, restore, operations, flexvol, volumes 
summary: Sie können die Ereignisprotokolldateien anzeigen, um die Tape-Backup- und Restore-Vorgänge zu überwachen. ONTAP protokolliert automatisch erhebliche Backup- und Restore-Ereignisse sowie die Zeit, zu der sie in einer Protokolldatei mit dem Namen Backup im Verzeichnis /etc/log/ des Controllers auftreten. Standardmäßig ist die Ereignisprotokollierung auf ein festgelegt. 
---
= Überwachung von Tape-Backup- und Restore-Vorgängen für FlexVol Volumes – Übersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Ereignisprotokolldateien anzeigen, um die Tape-Backup- und Restore-Vorgänge zu überwachen. ONTAP protokolliert wichtige Backup- und Restore-Ereignisse automatisch sowie die Zeit, zu der sie in einer Protokolldatei mit dem Namen auftreten `backup` In den Controllern `/etc/log/` Verzeichnis. Standardmäßig ist die Ereignisprotokollierung auf festgelegt `on`.

Die Ereignisprotokolldateien können aus folgenden Gründen angezeigt werden:

* Überprüfung, ob ein nächtliches Backup erfolgreich war
* Sammeln von Statistiken zu Backup-Vorgängen
* Zur Verwendung der Informationen in früheren Ereignisprotokolldateien, um bei der Diagnose von Problemen mit Backup- und Restore-Vorgängen zu helfen


Einmal wöchentlich werden die Ereignisprotokolldateien gedreht. Der `/etc/log/backup` Datei wird in umbenannt `/etc/log/backup.0`, Das `/etc/log/backup.0` Datei wird in umbenannt `/etc/log/backup.1`, Und so weiter. Das System speichert die Protokolldateien bis zu sechs Wochen lang, sodass Sie bis zu sieben Nachrichtendateien haben können (`/etc/log/backup.[0-5]` Und den Strom `/etc/log/backup` Datei).
