---
permalink: tape-backup/index.html 
sidebar: sidebar 
keywords: tape, backup, flexvol, volumes, overview, ndmp, network, data, management, protocol, sump, smtape 
summary: ONTAP unterstützt Tape-Backup und -Wiederherstellung über das Network Data Management Protocol. 
---
= Informationen zum Tape-Backup von ONTAP FlexVol Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP unterstützt Tape-Backup und Wiederherstellung über das Network Data Management Protocol (NDMP). NDMP ermöglicht die Sicherung von Daten in Speichersystemen direkt auf Band, was zu einer effizienten Nutzung der Bandbreite führt. ONTAP unterstützt sowohl Dump- als auch SMTape-Engines für Tape-Backup.

Ein Dump- oder SMTape-Backup oder eine Wiederherstellung kann mithilfe von NDMP-kompatiblen Backup-Anwendungen durchgeführt werden. Es wird nur NDMP Version 4 unterstützt.



[[tape-backup-using-dump]]
== Tape-Backup mit Dump

Dump ist eine Snapshot-basierte Datensicherung, bei der Ihre Dateisystemdaten auf Band gesichert werden. Die ONTAP Dump-Engine sichert Dateien, Verzeichnisse und die zugehörige Zugriffssteuerungsliste (ACL) auf Band. Es ist möglich, ein gesamtes Volume, einen gesamten Qtree oder einen Teilbaum zu sichern, der kein gesamtes Volume oder kein gesamter Qtree ist. Dump unterstützt Baseline-, Differenzial- und inkrementelle Backups.



[[tape-backup-using-smtape]]
== Tape-Backup mit SMTape

SMTape ist eine Snapshot-basierte Disaster-Recovery-Lösung von ONTAP, die Datenblöcke auf Band sichert. Mit SMTape lassen sich Volume-Backups auf Tape durchführen. Ein Backup auf Qtree- oder Subtree-Ebene ist jedoch nicht möglich. SMTape unterstützt Baseline-, Differenzial- und inkrementelle Backups.

Ab ONTAP 9.13.1 wird Tape-Backup mit SMTape unterstützt xref:../snapmirror-active-sync/interoperability-reference.html[SnapMirror Active Sync].
