---
permalink: tape-backup/manage-svm-scoped-ndmp-mode-concept.html 
sidebar: sidebar 
keywords: manage, svm, scope, ndmp, flexvol, volumes, vserver, modify 
summary: Sie können NDMP auf Basis pro SVM mit den NDMP-Optionen und -Befehlen verwalten. Sie können die NDMP-Optionen mit dem vserver Services ndmp modify-Befehl ändern. Im SVM-Scoped NDMP-Modus ist die Benutzerauthentifizierung in den rollenbasierten Zugriffssteuerungsmechanismus integriert. 
---
= Überblick über das Managen des SVM-Scoped NDMP-Modus für FlexVol Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können NDMP auf Basis pro SVM mit den NDMP-Optionen und -Befehlen verwalten. Sie können die NDMP-Optionen mit dem `vserver services ndmp modify` Befehl ändern. Im SVM-Scoped NDMP-Modus ist die Benutzerauthentifizierung in den rollenbasierten Zugriffssteuerungsmechanismus integriert.

Sie können NDMP in der Liste zulässige oder unzulässige Protokolle mit dem `vserver modify` Befehl hinzufügen. Standardmäßig befindet sich NDMP in der Liste der zugelassenen Protokolle. Wenn der Liste der nicht zulässigen Protokolle NDMP hinzugefügt wird, können NDMP-Sitzungen nicht erstellt werden.

Sie können den LIF-Typ steuern, auf dem eine NDMP-Datenverbindung hergestellt wird `-preferred-interface-role`, indem Sie die Option verwenden. Während einer NDMP-Datenverbindung wählt NDMP eine IP-Adresse aus, die zum von dieser Option angegebenen LIF-Typ gehört. Wenn die IP-Adressen keiner dieser LIF-Typen angehören, kann die NDMP-Datenverbindung nicht hergestellt werden. Weitere Informationen zu dieser `-preferred-interface-role` Option finden Sie in den man-Pages.

Weitere Informationen zu dem `vserver services ndmp modify` Befehl finden Sie in den man-Pages.

.Verwandte Informationen
xref:commands-manage-svm-scoped-ndmp-reference.adoc[Befehle für die Verwaltung des SVM-Scoped NDMP-Modus]

xref:cluster-aware-backup-extension-concept.adoc[Was ist Cluster-bewusste Backup-Erweiterung]

xref:svm-scoped-ndmp-mode-concept.adoc[Welcher SVM-Scoped NDMP-Modus ist]

link:../system-admin/index.html["Systemadministration"]
