---
permalink: tape-backup/ndmp-modes-concept.html 
sidebar: sidebar 
keywords: ndmp, mode, operation, backup, restore, node, level, svm 
summary: 'Sie können Tape-Backup- und -Restore-Vorgänge entweder auf Node-Ebene oder auf SVM-Ebene (Storage Virtual Machine) durchführen. Damit diese Vorgänge auf SVM-Ebene erfolgreich durchgeführt werden können, muss der NDMP-Service auf der SVM aktiviert sein.' 
---
= Allgemeines zum NDMP-Modus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Tape-Backup- und -Restore-Vorgänge entweder auf Node-Ebene oder auf SVM-Ebene (Storage Virtual Machine) durchführen. Damit diese Vorgänge auf SVM-Ebene erfolgreich durchgeführt werden können, muss der NDMP-Service auf der SVM aktiviert sein.

Wenn Sie ein Upgrade von Data ONTAP 8.2 auf Data ONTAP 8.3 durchführen, wird der in 8.2 verwendete NDMP-Betriebsmodus nach dem Upgrade von 8.2 auf 8.3 weiterhin beibehalten.

Bei der Installation eines neuen Clusters mit Data ONTAP 8.2 oder neuer befindet sich NDMP standardmäßig im NDMP-Modus mit SVM-Umfang. Zur Durchführung von Tape-Backup- und Restore-Vorgängen im NDMP-Modus mit Node-Umfang müssen Sie explizit den NDMP-Modus mit Node-Umfang aktivieren.

.Verwandte Informationen
xref:commands-manage-node-scoped-ndmp-reference.adoc[Befehle für die Verwaltung des NDMP-Modus mit Node-Umfang]

xref:manage-node-scoped-ndmp-mode-concept.adoc[Verwalten des NDMP-Modus mit Node-Umfang für FlexVol Volumes]

xref:manage-svm-scoped-ndmp-mode-concept.adoc[Verwalten des SVM-Scoped NDMP-Modus für FlexVol Volumes]
