---
permalink: tape-backup/ndmp-management-concept.html 
sidebar: sidebar 
keywords: understand, ndmp, flexvol, volume, network, data, management, protocol, storage, devices, systems, tape, library 
summary: 'Das Network Data Management Protocol (NDMP) ist ein standardisiertes Protokoll für die Kontrolle von Backup, Recovery und anderen Arten des Datentransfers zwischen primären und sekundären Storage-Geräten, wie z. B. Storage-Systemen und Tape Libraries.' 
---
= Über NDMP für FlexVol Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Network Data Management Protocol (NDMP) ist ein standardisiertes Protokoll für die Kontrolle von Backup, Recovery und anderen Arten des Datentransfers zwischen primären und sekundären Storage-Geräten, wie z. B. Storage-Systemen und Tape Libraries.

Durch Aktivierung der NDMP-Unterstützung auf einem Storage-System ermöglichen Sie, dass das Storage-System mit NDMP-fähigen, über das Netzwerk angeschlossenen Backup-Applikationen (auch _Data Management Applications_ oder _DMAs_), Datenservern und Bandservern, die an Backup- oder Recovery-Vorgängen beteiligt sind, kommunizieren kann. Die gesamte Netzwerkkommunikation erfolgt über ein TCPIP- oder TCP/IPv6-Netzwerk. NDMP bietet darüber hinaus eine Low-Level-Kontrolle von Bandlaufwerken und Mediumchanger.

Sie können die Durchführung von Prozessen zur Tape-Sicherung und -Wiederherstellung entweder im NDMP-Modus mit Node-Umfang oder im NDMP-Modus mit dem Umfang von Storage Virtual Machines (SVM) durchführen.

Beachten Sie jedoch bei der Verwendung von NDMP, der Liste der Umgebungsvariablen und den unterstützten NDMP Tape-Backup-Topologien. Sie können auch die erweiterte DAR-Funktion aktivieren oder deaktivieren. ONTAP unterstützt die beiden von unterstützten Authentifizierungsmethoden zur Authentifizierung des NDMP-Zugriffs auf ein Storage-System: Klartext und Herausforderung.

xref:environment-variables-supported-concept.adoc[Von ONTAP unterstützte Umgebungsvariablen]
