---
permalink: tape-backup/options-ndmpcopy-command-reference.html 
sidebar: sidebar 
keywords: ndmpcopy, command, tranfer, data, nodeshell 
summary: Sie sollten die verfügbaren Optionen für den NDMPcopy Befehl verstehen, um Daten erfolgreich zu übertragen. 
---
= Optionen für den Befehl ndmpcopy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten die verfügbaren Optionen für den `ndmpcopy` nodeshell-Befehl verstehen, um Daten erfolgreich zu übertragen.

In der folgenden Tabelle sind die verfügbaren Optionen aufgeführt. Erfahren Sie mehr über die in diesem Verfahren beschriebenen Befehle im link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP-Befehlsreferenz"^].

|===
| Option | Beschreibung 


 a| 
`-sa` `username`:[`password`]
 a| 
Mit dieser Option werden der Benutzername und das Passwort für die Quellauthentifizierung für die Verbindung zum Quell-Speichersystem festgelegt. Diese Option ist obligatorisch.

Für einen Benutzer ohne Administratorberechtigung müssen Sie das vom System generierte NDMP-spezifische Passwort des Benutzers angeben. Das vom System generierte Passwort ist sowohl für Admin- als auch für nicht-Admin-Benutzer erforderlich.



 a| 
`-da` `username`:[`password`]
 a| 
Mit dieser Option werden der Benutzername und das Passwort für die Zielauthentifizierung für die Verbindung zum Zielspeichersystem festgelegt. Diese Option ist obligatorisch.



 a| 
`-st` {`md5`|`text`}
 a| 
Diese Option legt den Quellauthentifizierungstyp fest, der bei der Verbindung mit dem Quellspeichersystem verwendet werden soll.Dies ist eine obligatorische Option und daher sollte der Benutzer entweder die `text` `md5` Option oder angeben.



 a| 
`-dt` {`md5`|`text`}
 a| 
Mit dieser Option wird der Zielauthentifizierungstyp festgelegt, der bei der Verbindung mit dem Ziel-Speichersystem verwendet wird.



 a| 
`-l`
 a| 
Mit dieser Option wird die für die Übertragung verwendete Dump `0` `1` `9` `0` `1` `9`-Ebene auf den angegebenen Wert von Level gesetzt.gültige Werte sind, , bis , wobei eine vollständige Übertragung angezeigt wird und bis eine inkrementelle Übertragung angibt. Der Standardwert ist `0`.



 a| 
`-d`
 a| 
Diese Option ermöglicht die Erstellung von NDMPcopy Debug-Protokollmeldungen. Die NDMPcopy Debug-Log-Dateien befinden sich im `/mroot/etc/log` Root-Volume. Die Namen der NDMPcopy-Debug-Log-Dateien liegen im `ndmpcopy.yyyymmdd` Format vor.



 a| 
`-f`
 a| 
Diese Option aktiviert den erzwungenen Modus. In diesem Modus können Systemdateien im `/etc` Stammverzeichnis des 7-Mode Volumes überschrieben werden.



 a| 
`-h`
 a| 
Mit dieser Option wird die Hilfemeldung gedruckt.



 a| 
`-p`
 a| 
Bei dieser Option werden Sie aufgefordert, das Kennwort für die Quell- und Zielautorisierung einzugeben. Dieses Kennwort setzt das für die `-sa` `-da` Optionen und angegebene Kennwort außer Kraft.

[NOTE]
====
Sie können diese Option nur verwenden, wenn der Befehl in einer interaktiven Konsole ausgeführt wird.

====


 a| 
`-exclude`
 a| 
Diese Option schließt angegebene Dateien oder Verzeichnisse aus dem für die Datenübertragung angegebenen Pfad aus. Der Wert kann eine kommagetrennte Liste von Verzeichnis- oder Dateinamen wie `*.pst` oder sein `*.txt`.

|===