---
permalink: tape-backup/physical-path-names-concept.html 
sidebar: sidebar 
keywords: physical, path, names, ppn, numerical, address, tape, drive, electrical 
summary: 'PPPNs (Physical Path Names) sind die numerischen Adresssequenzen, die ONTAP Bandlaufwerken und Bandbibliotheken basierend auf dem SCSI-2/3-Adapter oder Switch (bestimmte Position) zuweisen, die sie mit dem Speichersystem verbunden sind. PPNS werden auch als elektrische Namen bezeichnet.' 
---
= Welche physischen Pfadnamen sind
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
PPPNs (Physical Path Names) sind die numerischen Adresssequenzen, die ONTAP Bandlaufwerken und Bandbibliotheken basierend auf dem SCSI-2/3-Adapter oder Switch (bestimmte Position) zuweisen, die sie mit dem Speichersystem verbunden sind. PPNS werden auch als elektrische Namen bezeichnet.

PPNS von direkt angeschlossenen Geräten verwenden das folgende Format: `host_adapter`. `device_id_lun`

[NOTE]
====
Der LUN-Wert wird nur für Band- und Mittelwechsler angezeigt, deren LUN-Werte nicht null sind. Das heißt, wenn der LUN-Wert null ist `lun` Ein Teil des PPN wird nicht angezeigt.

====
Der PPN 8.6 zeigt beispielsweise an, dass die Host-Adapternummer 8, die Geräte-ID 6 und die Nummer der logischen Einheit (LUN) 0 ist.

SAS Tape-Geräte sind ebenfalls Direct-Attached-Geräte. Beispiel: Der PPN 5c.4 zeigt an, dass in einem Speichersystem der SAS-HBA in Steckplatz 5 angeschlossen ist, das SAS-Band mit Port C des SAS-HBA verbunden ist und die Geräte-ID 4 lautet.

PPNS von Fibre Channel-Switch-Attached-Geräten verwenden das folgende Format: `switch:port_id`. `device_id_lun`

Zum Beispiel zeigt der PPN MY_SWITCH:5.3L2 an, dass das Bandlaufwerk, das an Port 5 eines Switch namens MY_SWITCH angeschlossen ist, mit der Geräte-ID 3 gesetzt ist und die LUN 2 hat.

Die LUN (Logical Unit Number) wird durch das Laufwerk bestimmt. Fibre Channel, SCSI-Bandlaufwerke und Bibliotheken sowie Festplatten verfügen über PPNs.

PPNS von Bandlaufwerken und Bibliotheken ändern sich nicht, es sei denn, der Name des Switches ändert sich, das Bandlaufwerk oder die Bandbibliothek bewegt sich oder das Bandlaufwerk oder die Bandbibliothek wird neu konfiguriert. PPNS bleibt nach Neustart unverändert. Wenn zum Beispiel ein Bandlaufwerk namens MY_SWITCH:5.3L2 entfernt wird und ein neues Bandlaufwerk mit der gleichen Geräte-ID und LUN an Port 5 des Switch MY_SWITCH angeschlossen ist, würde das neue Bandlaufwerk über MY_SWITCH:5.3L2 zugänglich sein.
