---
permalink: tape-backup/restart-dump-backup-concept.html 
sidebar: sidebar 
keywords: restart, dump, backup, internal, external, tape, write, errors, power, outages, accidental, user, interruptions, internal, inconsistency 
summary: Ein Dump-Backup wird manchmal aufgrund interner oder externer Fehler, wie Tape-Schreibfehlern, Stromausfällen, versehentlichen Benutzerunterbrechungen oder interner Inkonsistenz im Speichersystem, nicht abgeschlossen. Schlägt das Backup aus einem dieser Gründe fehl, besteht die Möglichkeit, es neu zu starten. 
---
= Zeitpunkt für den Neustart eines ONTAP Dump-Backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Dump-Backup wird manchmal aufgrund interner oder externer Fehler, wie Tape-Schreibfehlern, Stromausfällen, versehentlichen Benutzerunterbrechungen oder interner Inkonsistenz im Speichersystem, nicht abgeschlossen. Schlägt das Backup aus einem dieser Gründe fehl, besteht die Möglichkeit, es neu zu starten.

Sie können eine Datensicherung unterbrechen und neu starten, um Phasen hoher Auslastung des Speichersystems oder die Belegung anderer begrenzter Ressourcen auf dem Speichersystem, wie zum Beispiel eines Tape-Laufwerks, zu vermeiden. Eine längere Datensicherung kann unterbrochen und später neu gestartet werden, wenn eine dringendere Wiederherstellung (oder Datensicherung) dasselbe Tape-Laufwerk benötigt. Wiederaufnehmbare Datensicherungen bleiben auch nach einem Neustart erhalten. Eine abgebrochene Datensicherung auf Band kann nur dann neu gestartet werden, wenn die folgenden Bedingungen erfüllt sind:

* Das abgebrochene Backup befindet sich in Phase IV.
* Alle zugehörigen Snapshots, die durch den Löschbefehl gesperrt wurden, sind verfügbar.
* Der Dateiversionsverlauf muss aktiviert sein.


Wird ein solcher Löschbefehl abgebrochen und in einem wiederaufnehmbaren Zustand belassen, werden die zugehörigen Snapshots gesperrt. Diese Snapshots werden freigegeben, nachdem der Sicherungskontext gelöscht wurde. Die Liste der Sicherungskontexte kann mit dem  `vserver services ndmp restartable backup show` Befehl angezeigt werden.

[listing]
----
cluster::> vserver services ndmpd restartable-backup show
Vserver     Context Identifier                   Is Cleanup Pending?
----------- ------------------------------------ -------------------
vserver1 330e6739-0179-11e6-a299-005056bb4bc9 false
vserver1 481025c1-0179-11e6-a299-005056bb4bc9 false
vserver2 5cf10132-0179-11e6-a299-005056bb4bc9 false
3 entries were displayed.

cluster::> vserver services ndmpd restartable-backup show -vserver vserver1 -context-id 330e6739-0179-11e6-a299-005056bb4bc9

                       Vserver: vserver1
            Context Identifier: 330e6739-0179-11e6-a299-005056bb4bc9
                   Volume Name: /vserver1/vol1
           Is Cleanup Pending?: false
            Backup Engine Type: dump
Is Snapshot Auto-created?: true
                     Dump Path: /vol/vol1
   Incremental Backup Level ID: 0
                     Dump Name: /vserver1/vol1
     Context Last Updated Time: 1460624875
               Has Offset Map?: true
                 Offset Verify: true
       Is Context Restartable?: true
              Is Context Busy?: false
                  Restart Pass: 4
              Status of Backup: 2
            Snapshot Name: snapshot_for_backup.1
          State of the Context: 7

cluster::>"
----