---
permalink: tape-backup/scalability-limits-dump-backup-restore-sessions-concept.html 
sidebar: sidebar 
keywords: scalability, limites, dump, backup, restore, sessions, maximum, memory, capacities, storage, system 
summary: Sie müssen die maximale Anzahl von Dump Backup- und Restore-Sessions kennen, die gleichzeitig auf Speichersystemen mit unterschiedlichen Systemspeicherkapazitäten ausgeführt werden können. Diese maximale Zahl hängt vom Systemspeicher eines Storage-Systems ab. 
---
= Skalierbarkeitsgrenzen für Dump Backup und Restore-Sessions
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die maximale Anzahl von Dump Backup- und Restore-Sessions kennen, die gleichzeitig auf Speichersystemen mit unterschiedlichen Systemspeicherkapazitäten ausgeführt werden können. Diese maximale Zahl hängt vom Systemspeicher eines Storage-Systems ab.

Die in der folgenden Tabelle aufgeführten Grenzwerte gelten für die Dump- oder Wiederherstellungs-Engine. Die in den Skalierbarkeitslimits für NDMP-Sitzungen genannten Grenzwerte gelten für den NDMP-Server, die höher sind als die Engine-Limits.

|===
| Systemspeicher eines Storage-Systems | Gesamtzahl der Backup- und Restore-Sessions für Dump 


 a| 
Weniger als 16 GB
 a| 
4



 a| 
Größer oder gleich 16 GB, aber kleiner als 24 GB
 a| 
16



 a| 
Größer oder gleich 24 GB
 a| 
32

|===
[NOTE]
====
Wenn Sie verwenden `ndmpcopy` Befehl zum Kopieren von Daten in Storage-Systemen werden zwei NDMP-Sitzungen eingerichtet, eine für Dump-Backup und die andere für Dump-Wiederherstellung.

====
Sie können den Systemspeicher Ihres Storage-Systems mit dem abrufen `sysconfig -a` Befehl (verfügbar über die nodeshell). Weitere Informationen über diese Verwendung dieses Befehls finden Sie in den man-Pages.

xref:scalability-limits-ndmp-sessions-reference.adoc[Obergrenzen für Skalierbarkeit bei NDMP-Sitzungen]
