---
permalink: tape-backup/scalability-limits-smtape-sessions-reference.html 
sidebar: sidebar 
keywords: scalability, limits, smtap, backup, restore, session, ndmp, cli, tape, seeding, system, memory 
summary: 'Bei Backup- und Restore-Vorgängen mit SMTape über NDMP oder CLI (Tape Seeding) müssen Sie jedoch die maximale Anzahl von SMTape Backup- und Restore-Sessions kennen, die gleichzeitig auf Storage-Systemen mit unterschiedlichen Systemspeicherkapazitäten ausgeführt werden können. Diese maximale Zahl hängt vom Systemspeicher eines Storage-Systems ab.' 
---
= Skalierbarkeitsbeschränkungen für SMTape Backup- und Restore-Sitzungen in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei Backup- und Restore-Vorgängen mit SMTape über NDMP oder CLI (Tape Seeding) müssen Sie jedoch die maximale Anzahl von SMTape Backup- und Restore-Sessions kennen, die gleichzeitig auf Storage-Systemen mit unterschiedlichen Systemspeicherkapazitäten ausgeführt werden können. Diese maximale Zahl hängt vom Systemspeicher eines Storage-Systems ab.

[NOTE]
====
Einschränkungen bei SMTape-Backup- und Restore-Sessions unterscheiden sich von Einschränkungen durch NDMP-Sitzungsgrenzen und Einschränkungen bei Dump-Sitzungen.

====
|===
| Systemarbeitsspeicher des Storage-Systems | Gesamtzahl der SMTape Backup- und Restore-Sessions 


 a| 
Weniger als 16 GB
 a| 
6



 a| 
Größer oder gleich 16 GB, aber kleiner als 24 GB
 a| 
16



 a| 
Größer oder gleich 24 GB
 a| 
32

|===
Sie können den Systemspeicher Ihres Speichersystems mit dem `sysconfig -a` Befehl (verfügbar über die nodeshell) abrufen. Erfahren Sie mehr über `sysconfig -a` in der link:https://docs.netapp.com/us-en/ontap-cli/system-node-run.html["ONTAP-Befehlsreferenz"^].

.Verwandte Informationen
xref:scalability-limits-ndmp-sessions-reference.adoc[Obergrenzen für Skalierbarkeit bei NDMP-Sitzungen]

xref:scalability-limits-dump-backup-restore-sessions-concept.adoc[Skalierbarkeitsgrenzen für Dump Backup und Restore-Sessions]
