---
permalink: tape-backup/serial-numbers-concept.html 
sidebar: sidebar 
keywords: serial, numbers, sn, tape, drive, medium, changer, wwn 
summary: 'Eine Seriennummer (SN) ist eine eindeutige Kennung für ein Bandlaufwerk oder einen Mittelwechsler. ONTAP generiert basierend auf SN anstelle des WWN Aliase.' 
---
= Um welche Seriennummern handelt es sich
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Eine Seriennummer (SN) ist eine eindeutige Kennung für ein Bandlaufwerk oder einen Mittelwechsler. ONTAP generiert basierend auf SN anstelle des WWN Aliase.

Da die SN eine eindeutige Kennung für ein Bandlaufwerk oder einen Mittelwechsler ist, bleibt der Alias gleich, unabhängig von den mehreren Verbindungspfaden zum Bandlaufwerk oder zum Mittelwechsler. So können Storage-Systeme dasselbe Bandlaufwerk oder denselben Mediumwechsler in einer Bandbibliothek nachverfolgen.

Die SN eines Bandlaufwerks oder eines Mittelwechsels ändert sich nicht, auch wenn Sie den Fibre-Channel-Switch umbenennen, an den das Bandlaufwerk oder der Mittelwechsler angeschlossen ist. Wenn Sie jedoch in einer Bandbibliothek ein vorhandenes Bandlaufwerk durch ein neues ersetzen, generiert ONTAP neue Aliase, da sich die SN des Bandlaufwerks ändert. Wenn Sie ein vorhandenes Bandlaufwerk zu einem neuen Steckplatz in einer Bandbibliothek verschieben oder die LUN des Bandlaufwerks neu zuordnen, generiert ONTAP einen neuen Alias für das Bandlaufwerk.

[NOTE]
====
Sie müssen die Backupanwendungen mit den neu erstellten Aliase aktualisieren.

====
Die SN eines Bandgeräts verwendet das folgende Format: `SN[xxxxxxxxxx]L[X]`

`x` Ist ein alphanumerisches Zeichen und L``X`` Ist die LUN des Bandgeräts. Wenn die LUN 0 ist, lautet L``X`` Ein Teil der Zeichenfolge wird nicht angezeigt.

Jede SN besteht aus bis zu 32 Zeichen; das Format für die SN ist nicht Groß-/Kleinschreibung.
