---
permalink: tape-backup/smtape-engine-concept.html 
sidebar: sidebar 
keywords: smtape, disaster, recovery, solution, blocks, data, tape, qtree, subtree, volume, license, baseline, differential, incremental, backup 
summary: SMTape ist eine Disaster Recovery-Lösung von ONTAP, die Datenblöcke auf Tape sichert. Mit SMTape können Volume-Backups auf Tapes durchgeführt werden. Sie können jedoch keine Sicherung auf qtree- oder Subbaum-Ebene durchführen. SMTape unterstützt Basis-, Differenzial- und inkrementelle Backups. SMTape benötigt keine Lizenz. 
---
= Über SMTape Engine für FlexVol Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMTape ist eine Disaster Recovery-Lösung von ONTAP, die Datenblöcke auf Tape sichert. Mit SMTape können Volume-Backups auf Tapes durchgeführt werden. Sie können jedoch keine Sicherung auf qtree- oder Subbaum-Ebene durchführen. SMTape unterstützt Basis-, Differenzial- und inkrementelle Backups. SMTape benötigt keine Lizenz.

Sie können eine Backup- und Restore-Operation mit SMTape über eine NDMP-kompatible Backup-Applikation durchführen. Sie können SMTape auswählen, um Backup- und Restore-Vorgänge nur im NDMP-Modus mit dem Umfang der Storage Virtual Machine (SVM) durchzuführen.

[NOTE]
====
Der Reversionsvorgang wird nicht unterstützt, wenn eine SMTape-Backup- oder Wiederherstellungssitzung läuft. Sie müssen warten, bis die Sitzung beendet ist, oder Sie müssen die NDMP-Sitzung abbrechen.

====
Mit SMTape können Sie bis zu 255 Snapshot Kopien erstellen. Für nachfolgende Baseline-, inkrementelle oder differenzielle Backups müssen ältere gesicherte Snapshot Kopien gelöscht werden.

Vor einer Basis-Wiederherstellung muss das Volume, auf dem Daten wiederhergestellt werden, vom Typ sein `DP` und dieses Volume muss sich im eingeschränkten Zustand befinden. Nach einem erfolgreichen Restore wird dieses Volume automatisch online geschaltet. Sie können nachfolgende inkrementelle oder differenzielle Wiederherstellungen auf diesem Volume in der Reihenfolge durchführen, in der die Backups durchgeführt wurden.
