---
permalink: tape-backup/smtape-capabilities-concept.html 
sidebar: sidebar 
keywords: smtap, capabilities, snapshot, copy, preservation, deduplication, compression, restored, volume, backup, restore 
summary: SMTape-Funktionen wie Backup von Snapshots, inkrementelle und differenzielle Backups, Erhalt von Deduplizierungs- und Komprimierungsfunktionen auf wiederhergestellten Volumes und Tape-Seeding helfen Ihnen bei der Optimierung Ihrer Tape-Backup- und -Restore-Vorgänge. 
---
= SMTape Funktionen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMTape-Funktionen wie Backup von Snapshots, inkrementelle und differenzielle Backups, Erhalt von Deduplizierungs- und Komprimierungsfunktionen auf wiederhergestellten Volumes und Tape-Seeding helfen Ihnen bei der Optimierung Ihrer Tape-Backup- und -Restore-Vorgänge.

SMTape bietet die folgenden Funktionen:

* Bietet eine Disaster Recovery-Lösung
* Ermöglicht inkrementelle und differenzielle Backups
* Sichert Snapshots
* Ermöglicht Backups und Restores deduplizierter Volumes und erhält die Deduplizierung auf den wiederhergestellten Volumes aufrecht
* Sichert komprimierte Volumes und erhält die Komprimierung auf den wiederhergestellten Volumes aufrecht
* Ermöglicht das Tape Seeding


SMTape unterstützt den Blockierfaktor in Vielfachen von 4 KB im Bereich von 4 KB bis 256 KB.

[NOTE]
====
Sie können Daten auf Volumes wiederherstellen, die nur in bis zu zwei aufeinanderfolgenden ONTAP Versionen erstellt wurden.

====