---
permalink: tape-backup/smtape-storage-failover-arl-concept.html 
sidebar: sidebar 
keywords: smtape, storage, failover, arl, operation, aggregate, relocation 
summary: 'Bevor Sie SMTape Backup- oder Restore-Vorgänge durchführen, sollten Sie verstehen, wie diese Vorgänge mit Storage Failover (Übernahme und Rückgabe) oder ARL (Aggregate Relocation) funktionieren. Die Option -override-vetoes bestimmt das Verhalten der SMTape Engine während eines Storage-Failovers oder eines ARL-Betriebs.' 
---
= Funktionsweise von SMTape mit Storage-Failover und ARL-Betrieb
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie SMTape Backup- oder Restore-Vorgänge durchführen, sollten Sie verstehen, wie diese Vorgänge mit Storage Failover (Übernahme und Rückgabe) oder ARL (Aggregate Relocation) funktionieren. Der `-override-vetoes` Die Option bestimmt das Verhalten der SMTape Engine während eines Storage Failover oder eines ARL-Betriebs.

Wenn ein Backup- oder Wiederherstellungsvorgang mit SMTape ausgeführt wird, und `-override-vetoes` Die Option ist auf festgelegt `false`, Ein durch den Benutzer initiiertes Storage Failover oder ARL-Vorgang wird angehalten und der Backup- oder Wiederherstellungsvorgang abgeschlossen. Wenn die Backup-Applikation CAB-Erweiterung unterstützt, können Sie mit inkrementellen Backup- und Restore-Vorgängen bei SMTape fortfahren, ohne Backup-Richtlinien neu zu konfigurieren. Wenn der jedoch `–override-vetoes` Die Option ist auf festgelegt `true`, Dann wird das Storage-Failover oder der ARL-Vorgang fortgesetzt und der SMTape-Backup- oder Restore-Vorgang wird abgebrochen.

.Verwandte Informationen
link:../networking/index.html["Netzwerkmanagement"]

https://["Hochverfügbarkeit"]
