---
permalink: tape-backup/snapshot-copies-during-smtape-backup-concept.html 
sidebar: sidebar 
keywords: snapshot, copy, smtape, backup, baseline, incremental, snapmirror 
summary: Es ist wichtig zu verstehen, wie Snapshots bei einer SMTape Basissicherung und einer inkrementellen Sicherung verwendet werden. Es sind außerdem einige Aspekte zu berücksichtigen, wenn eine Sicherung mit SMTape durchgeführt wird. 
---
= Informationen zur Verwendung von ONTAP Snapshots während des SMTape-Backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es ist wichtig zu verstehen, wie Snapshots bei einer SMTape Basissicherung und einer inkrementellen Sicherung verwendet werden. Es sind außerdem einige Aspekte zu berücksichtigen, wenn eine Sicherung mit SMTape durchgeführt wird.



[[baseline-backup]]
== Basissicherung

Beim Erstellen einer Basissicherung kann der Name des auf Tape zu sichernden Snapshots angegeben werden. Wird kein Snapshot angegeben, wird abhängig vom Zugriffstyp des Volumes (lesen/schreiben oder Nur-Lesezugriff) entweder automatisch ein Snapshot erstellt oder vorhandene Snapshots werden verwendet. Wird ein Snapshot für das Backup angegeben, werden alle Snapshots, die älter als der angegebene Snapshot sind, ebenfalls auf Tape gesichert.

Wenn Sie keinen Snapshot für das Backup angeben, tritt Folgendes ein:

* Für ein lesen/schreiben Volume wird automatisch ein Snapshot erstellt.
+
Der neu erstellte Snapshot und alle älteren Snapshots werden auf Tape gesichert.

* Bei einem schreibgeschützten Volume werden alle Snapshots, einschließlich des neuesten Snapshots, auf Tape-Backup gesichert.
+
Alle nach dem Start der Datensicherung erstellten Snapshots werden nicht gesichert.





[[incremental-backup]]
== Inkrementelle Datensicherung

Für SMTape inkrementelle oder differenzielle Backup-Operationen erstellen und verwalten die NDMP-konformen Backup-Anwendungen die Snapshots.

Sie müssen bei der Durchführung eines inkrementellen Backup-Vorgangs immer einen Snapshot angeben. Für einen erfolgreichen inkrementellen Backup-Vorgang muss sich der während des vorherigen Backup-Vorgangs (Baseline oder inkrementell) gesicherte Snapshot auf dem Volume befinden, von dem das Backup durchgeführt wird. Um sicherzustellen, dass Sie diesen gesicherten Snapshot verwenden, muss die auf diesem Volume zugewiesene Snapshot-Richtlinie bei der Konfiguration der Backup-Richtlinie berücksichtigt werden.



[[considerations-on-smtape-backups-on-snapmirror-destinations]]
== Überlegungen zu SMTape Backups auf SnapMirror Zielen

* Eine Spiegelbeziehung zum Datenschutz erstellt temporäre Snapshots auf dem Zielvolume für die Replikation.
+
Diese Snapshots sollten nicht für SMTape Backup verwendet werden.

* Wenn während eines SMTape-Backup-Vorgangs auf demselben Volume eine SnapMirror-Aktualisierung auf einem Zielvolume in einer Data-Protection-Spiegelbeziehung erfolgt, darf der von SMTape gesicherte Snapshot auf dem Quellvolume nicht gelöscht werden.
+
Während des Sicherungsvorgangs sperrt SMTape den Snapshot auf dem Zielvolume, und wenn der entsprechende Snapshot auf dem Quellvolume gelöscht wird, schlägt der nachfolgende SnapMirror-Updatevorgang fehl.

* Diese Snapshots sollten nicht bei inkrementellen Backups verwendet werden.

