---
permalink: tape-backup/supported-ndmp-authentication-methods-concept.html 
sidebar: sidebar 
keywords: ndmp, authentication, method, requests, plaintext, challenge 
summary: 'Sie können ein Authentifizierungsverfahren für NDMP-Verbindungsanfragen festlegen. ONTAP unterstützt zwei Methoden zur Authentifizierung des NDMP-Zugriffs auf ein Speichersystem: Klartext und Challenge.' 
---
= ONTAP unterstützte NDMP-Authentifizierungsverfahren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Authentifizierungsverfahren für NDMP-Verbindungsanfragen festlegen. ONTAP unterstützt zwei Methoden zur Authentifizierung des NDMP-Zugriffs auf ein Speichersystem: Klartext und Challenge.

Im knotenbezogenen NDMP-Modus sind sowohl Challenge als auch Klartext standardmäßig aktiviert. Challenge kann jedoch nicht deaktiviert werden. Klartext kann aktiviert und deaktiviert werden. Im Klartext-Authentifizierungsverfahren wird das Anmeldekennwort als Klartext übertragen.

Im Storage Virtual Machine (SVM)-bezogenen NDMP-Modus ist das Authentifizierungsverfahren standardmäßig Challenge. Im Gegensatz zum node-bezogenen NDMP-Modus können in diesem Modus sowohl Klartext- als auch Challenge-Authentifizierungsverfahren aktiviert und deaktiviert werden.

.Verwandte Informationen
xref:user-authentication-node-scoped-ndmp-mode-concept.adoc[Benutzerauthentifizierung im knotenbezogenen NDMP-Modus]

xref:user-authentication-svm-scoped-ndmp-mode-concept.adoc[Benutzerauthentifizierung im SVM-bezogenen NDMP-Modus]
