---
permalink: tape-backup/tape-seeding-concept.html 
sidebar: sidebar 
keywords: tape, seeding, smtape, functionality, destination, flexvol, data, protection, mirror 
summary: Bei der Tape Seeding handelt es sich um eine SMTape-Funktionalität, mit der Sie ein FlexVol Ziel-Volume in einer Datensicherungs-Spiegelbeziehung initialisieren können. 
---
= Was ist das Tape-Seeding
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Tape Seeding handelt es sich um eine SMTape-Funktionalität, mit der Sie ein FlexVol Ziel-Volume in einer Datensicherungs-Spiegelbeziehung initialisieren können.

Mit Tape Seeding können Sie eine Datensicherungs-Spiegelbeziehung zwischen einem Quellsystem und einem Zielsystem über eine Verbindung mit niedriger Bandbreite herstellen.

Eine inkrementelle Spiegelung von Snapshot Kopien vom Quell- zum Zielsystem ist über eine Verbindung mit niedriger Bandbreite realisierbar. Eine erste Spiegelung der Basis-Snapshot-Kopie dauert jedoch sehr lange über eine Verbindung mit einer niedrigen Bandbreite. In solchen Fällen können Sie ein SMTape Backup des Quell-Volume auf ein Tape durchführen und die Tapes zur Übertragung der ersten Basis-Snapshot Kopie an das Ziel verwenden. Anschließend können Sie über die Verbindung mit niedriger Bandbreite inkrementelle SnapMirror Updates auf das Zielsystem einrichten.
