---
permalink: tape-backup/tape-devices-concept.html 
sidebar: sidebar 
keywords: tape, device, representation, combination, rewind, type, compression, capability, drive 
summary: Ein Tape-Gerät ist eine Darstellung eines Tape-Laufwerks. Es ist eine spezifische Kombination aus Rückspultyp und Kompressionsfähigkeit eines Tape-Laufwerks. 
---
= Informationen zu ONTAP Tape-Geräten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Tape-Gerät ist eine Darstellung eines Tape-Laufwerks. Es ist eine spezifische Kombination aus Rückspultyp und Kompressionsfähigkeit eines Tape-Laufwerks.

Ein Tape-Gerät wird für jede Kombination aus Rückspultyp und Komprimierungsfähigkeit erstellt. Daher kann ein Tape-Laufwerk oder eine Tape-Bibliothek mehrere zugeordnete Tape-Geräte haben. Ein Tape-Gerät muss angegeben werden, um Bänder zu verschieben, zu beschreiben oder zu lesen.

Wenn ein Tape-Laufwerk oder eine Tape-Bibliothek in ein Speichersystem installiert wird, erstellt ONTAP Tape-Geräte, die dem Tape-Laufwerk oder der Tape-Bibliothek zugeordnet sind.

ONTAP erkennt Tape-Laufwerke und Tape-Bibliotheken und weist ihnen logische Nummern und Tape-Geräte zu. ONTAP erkennt die Fibre Channel-, SAS- und parallelen SCSI Tape-Laufwerke und Tape-Bibliotheken, wenn sie an die Schnittstellen-Ports angeschlossen sind. ONTAP erkennt diese Laufwerke, wenn deren Schnittstellen aktiviert sind.
