---
permalink: tape-backup/tape-device-name-format-concept.html 
sidebar: sidebar 
keywords: tape, device, name, format, rewind, type, alias, compression 
summary: Jedes Bandgerät verfügt über einen zugeordneten Namen, der in einem definierten Format angezeigt wird. Das Format enthält Informationen zum Gerätetyp, zum Rückwind, zum Alias und zum Kompressionstyp. 
---
= Format für Bandgerätenamen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Jedes Bandgerät verfügt über einen zugeordneten Namen, der in einem definierten Format angezeigt wird. Das Format enthält Informationen zum Gerätetyp, zum Rückwind, zum Alias und zum Kompressionstyp.

Das Format eines Bandgerätnamens lautet wie folgt:

`rewind_type` `st` `alias_number` `compression_type`

`rewind_type` Ist der Rücklauf-Typ.

In der folgenden Liste werden die verschiedenen Werte für den Rückwind beschrieben:

* *R*
+
ONTAP windet das Band erneut, nachdem die Tape-Datei geschrieben wurde.

* *Nr*
+
ONTAP fillaesst das Tape nach dem Schreiben der Tape-Datei nicht mehr zurück. Sie müssen diesen Rewind-Typ verwenden, wenn Sie mehrere Banddateien auf demselben Band schreiben möchten.

* *Ur*
+
Dies ist die Art des erneuten Entlads/Neueinzuspulen. Wenn Sie diesen Rückwind-Typ verwenden, entlädt die Bandbibliothek das Band, wenn es das Ende einer Banddatei erreicht, und lädt dann das nächste Band, falls vorhanden.

+
Sie dürfen diesen Rückwind nur unter folgenden Umständen verwenden:

+
** Das mit diesem Gerät verbundene Bandlaufwerk befindet sich in einer Bandbibliothek oder befindet sich im Bibliotheksmodus.
** Das mit diesem Gerät verbundene Bandlaufwerk ist an ein Speichersystem angeschlossen.
** In der für dieses Bandlaufwerk definierten Library-Bandsequenz sind ausreichend Bänder für den Vorgang verfügbar, den Sie gerade durchführen.




[NOTE]
====
Wenn Sie ein Band mit einem Rückspulen-Gerät aufnehmen, müssen Sie das Band vor dem Lesen zurückspulen.

====
`st` Ist die Standardbezeichnung für ein Bandlaufwerk.

`alias_number` Ist der Alias, den ONTAP dem Bandlaufwerk zuweist. Wenn ONTAP ein neues Bandlaufwerk erkennt, weist ONTAP dem Bandlaufwerk einen Alias zu.

`compression_type` Ist ein laufwerksspezifischer Code für die Dichte der Daten auf dem Band und den Typ der Komprimierung.

Die folgende Liste beschreibt die verschiedenen Werte für `compression_type`:

* *A*
+
Höchste Komprimierung

* *H*
+
Hohe Komprimierung

* *M*
+
Mittlere Komprimierung

* *L*
+
Niedrige Komprimierung



.Beispiele
`nrst0a` Gibt ein Gerät ohne Rücklauf auf Bandlaufwerk 0 mit der höchsten Komprimierung an.

.Beispiel für eine Liste mit Bandgeräten
Das folgende Beispiel zeigt die Bandgeräte, die mit HP Ultrium 2-SCSI verbunden sind:

[listing]
----

           Tape drive (fc202_6:2.126L1)  HP      Ultrium 2-SCSI
    rst0l  -  rewind device,        format is: HP (200GB)
    nrst0l -  no rewind device,     format is: HP (200GB)
    urst0l -  unload/reload device, format is: HP (200GB)
    rst0m  -  rewind device,        format is: HP (200GB)
    nrst0m -  no rewind device,     format is: HP (200GB)
    urst0m -  unload/reload device, format is: HP (200GB)
    rst0h  -  rewind device,        format is: HP (200GB)
    nrst0h -  no rewind device,     format is: HP (200GB)
    urst0h -  unload/reload device, format is: HP (200GB)
    rst0a  -  rewind device,        format is: HP (400GB w/comp)
    nrst0a -  no rewind device,     format is: HP (400GB w/comp)
    urst0a -  unload/reload device, format is: HP (400GB w/comp)
----
In der folgenden Liste werden die Abkürzungen im vorhergehenden Beispiel beschrieben:

* GB--GB; dies ist die Kapazität des Bandes.
* w/Kompr. Mit Komprimierung; dieser zeigt die Tape-Kapazität mit Komprimierung an.

