---
permalink: tape-backup/tape-device-name-format-concept.html 
sidebar: sidebar 
keywords: tape, device, name, format, rewind, type, alias, compression 
summary: Jedes Tape-Gerät hat einen zugehörigen Namen, der in einem definierten Format erscheint. Das Format enthält Informationen über den Gerätetyp, den Rückspultyp, den Alias und den Komprimierungstyp. 
---
= Format eines ONTAP Tape-Gerät Namens
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Jedes Tape-Gerät hat einen zugehörigen Namen, der in einem definierten Format erscheint. Das Format enthält Informationen über den Gerätetyp, den Rückspultyp, den Alias und den Komprimierungstyp.

Das Format eines Tape-Gerät-Namens ist wie folgt:

`rewind_type` `st` `alias_number` `compression_type`

`rewind_type` ist vom Typ „Zurückspulen“.

Die folgende Liste beschreibt die verschiedenen Rückspultyp-Werte:

* *r*
+
ONTAP spult das Band zurück, nachdem das Schreiben der Banddatei abgeschlossen ist.

* *nr*
+
ONTAP spult das Band nach dem Beschreiben der Banddatei nicht zurück. Diese Rückspulart muss verwendet werden, wenn mehrere Banddateien auf dasselbe Band geschrieben werden sollen.

* *ur*
+
Dies ist der Rückspultyp „Entladen/Laden“. Bei diesem Rückspultyp entlädt die Tape-Bibliothek das Band, sobald das Ende einer Banddatei erreicht ist, und lädt anschließend das nächste Band, sofern eines vorhanden ist.

+
Diese Rückspulart darf nur unter folgenden Umständen verwendet werden:

+
** Das mit diesem Gerät verbundene Tape-Laufwerk befindet sich in einer Tape-Bibliothek oder in einem Medienwechsler, der sich im Bibliotheksmodus befindet.
** Das mit diesem Gerät verbundene Tape-Laufwerk ist an ein Speichersystem angeschlossen.
** Für den von Ihnen durchgeführten Vorgang sind ausreichend Tapes in der für dieses Tape-Laufwerk definierten Tape-Bibliothekssequenz verfügbar.




[NOTE]
====
Wenn ein Tape mit einem No-Rewind-Gerät beschrieben wird, muss das Tape vor dem Auslesen zurückgespult werden.

====
`st` ist die Standardbezeichnung für ein Tape-Laufwerk.

`alias_number` ist der Alias, den ONTAP dem Tape-Laufwerk zuweist. Wenn ONTAP ein neues Tape-Laufwerk erkennt, weist ONTAP dem Tape-Laufwerk einen Alias zu.

`compression_type` ist ein laufwerkspezifischer Code für die Datendichte auf dem Band und die Art der Komprimierung.

Die folgende Liste beschreibt die verschiedenen Werte für  `compression_type`:

* *a*
+
Höchste Kompression

* *h*
+
Hohe Kompression

* *m*
+
Mittlere Kompression

* *l*
+
Niedrige Kompression



.Beispiele
`nrst0a`Gibt ein No-Rewind-Gerät auf Tape-Laufwerk 0 mit der höchsten Komprimierung an.

.Beispiel einer Auflistung von Tape-Geräten
Das folgende Beispiel zeigt die mit HP Ultrium 2-SCSI verbundenen Tape-Geräte:

[listing]
----

           Tape drive (fc202_6:2.126L1)  HP      Ultrium 2-SCSI
    rst0l  -  rewind device,        format is: HP (200GB)
    nrst0l -  no rewind device,     format is: HP (200GB)
    urst0l -  unload/reload device, format is: HP (200GB)
    rst0m  -  rewind device,        format is: HP (200GB)
    nrst0m -  no rewind device,     format is: HP (200GB)
    urst0m -  unload/reload device, format is: HP (200GB)
    rst0h  -  rewind device,        format is: HP (200GB)
    nrst0h -  no rewind device,     format is: HP (200GB)
    urst0h -  unload/reload device, format is: HP (200GB)
    rst0a  -  rewind device,        format is: HP (400GB w/comp)
    nrst0a -  no rewind device,     format is: HP (400GB w/comp)
    urst0a -  unload/reload device, format is: HP (400GB w/comp)
----
Die folgende Liste beschreibt die Abkürzungen im vorhergehenden Beispiel:

* GB – Gigabyte; dies ist die Kapazität des Tape.
* w/comp, mit Kompression; dies zeigt die Bandkapazität mit Kompression.

