---
permalink: tape-backup/tape-reservations-concept.html 
sidebar: sidebar 
keywords: tape, reservation, drive, medium, changer, bridge, libraries, scsi, persistent, reserve, release 
summary: Mehrere Speichersysteme können den Zugriff auf Bandlaufwerke, mittlere Wechsler, Brücken oder Bandbibliotheken gemeinsam nutzen. Durch die Reservierung von Bandgeräten wird sichergestellt, dass zu einem bestimmten Zeitpunkt nur ein Speichersystem auf ein Gerät zugreift, indem entweder der SCSI-Reserve-/Freigabemechanismus oder SCSI Persistent Reservations für alle Bandlaufwerke, Mittelwechsler, Brücken und Bandbibliotheken ermöglicht wird. 
---
= Welche Tape-Reservierungen sind
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mehrere Speichersysteme können den Zugriff auf Bandlaufwerke, mittlere Wechsler, Brücken oder Bandbibliotheken gemeinsam nutzen. Durch die Reservierung von Bandgeräten wird sichergestellt, dass zu einem bestimmten Zeitpunkt nur ein Speichersystem auf ein Gerät zugreift, indem entweder der SCSI-Reserve-/Freigabemechanismus oder SCSI Persistent Reservations für alle Bandlaufwerke, Mittelwechsler, Brücken und Bandbibliotheken ermöglicht wird.

[NOTE]
====
Alle Systeme, die Geräte in einer Bibliothek gemeinsam nutzen, unabhängig davon, ob Switches beteiligt sind oder nicht, müssen dieselbe Reservierungsmethode verwenden.

====
Der SCSI-Reserve-/Freigabemechanismus für die Reservierung von Geräten funktioniert unter normalen Bedingungen gut. Während der Recovery-Verfahren bei Schnittstellenfehlern können jedoch Reservierungen verloren gehen. In diesem Fall können andere Initiatoren als der reservierte Eigentümer auf das Gerät zugreifen.

Reservierungen, die mit SCSI Persistent Reservations vorgenommen werden, werden nicht durch Fehler-Recovery-Mechanismen wie Loop-Reset oder Ziel-Reset beeinflusst; jedoch implementieren nicht alle Geräte SCSI Persistent Reservations richtig.
