---
permalink: tape-backup/tape-reservations-concept.html 
sidebar: sidebar 
keywords: tape, reservation, drive, medium, changer, bridge, libraries, scsi, persistent, reserve, release 
summary: Mehrere Speichersysteme können gemeinsam auf Tape-Laufwerke, Medienwechsler, Bridges oder Tape-Bibliotheken zugreifen. Tape-Reservierungen gewährleisten, dass jeweils nur ein Speichersystem auf ein Gerät zugreift, indem entweder der SCSI Reserve/Release-Mechanismus oder SCSI Persistent Reservations für alle Tape-Laufwerke, Medienwechsler, Bridges und Tape-Bibliotheken aktiviert werden. 
---
= Informationen zu ONTAP Tape-Reservierungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mehrere Speichersysteme können gemeinsam auf Tape-Laufwerke, Medienwechsler, Bridges oder Tape-Bibliotheken zugreifen. Tape-Reservierungen gewährleisten, dass jeweils nur ein Speichersystem auf ein Gerät zugreift, indem entweder der SCSI Reserve/Release-Mechanismus oder SCSI Persistent Reservations für alle Tape-Laufwerke, Medienwechsler, Bridges und Tape-Bibliotheken aktiviert werden.

[NOTE]
====
Alle Systeme, die Geräte in einer Bibliothek gemeinsam nutzen, unabhängig davon, ob Switches beteiligt sind oder nicht, müssen die gleiche Reservierungsmethode verwenden.

====
Der SCSI Reserve/Release-Mechanismus zur Reservierung von Geräten funktioniert unter normalen Bedingungen einwandfrei. Während Fehlerbehebungsverfahren an der Schnittstelle können Reservierungen jedoch verloren gehen. Falls dies geschieht, können Initiatoren, die nicht der reservierende Eigentümer sind, auf das Gerät zugreifen.

Reservierungen, die mit SCSI Persistent Reservations vorgenommen werden, sind von Fehlerkorrekturmechanismen wie Loop Reset oder Target Reset nicht betroffen, allerdings implementieren nicht alle Geräte SCSI Persistent Reservations korrekt.
