---
permalink: tape-backup/use-cases-choosing-tape-backup-method-concept.html 
sidebar: sidebar 
keywords: cases, choose, tape, backup, engine, smtape, dump, restore 
summary: 'ONTAP unterstützt zwei Backup Engines: SMTape und Dump. Sie sollten die Anwendungsfälle für SMTape und Dump Backup-Engines kennen, um Sie bei der Auswahl der Backup Engine zu unterstützen, die Tape-Backup- und Restore-Vorgänge durchgeführt werden soll.' 
---
= Anwendungsfälle für ONTAP SMTape und Dump-Backup-Engines
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP unterstützt zwei Backup Engines: SMTape und Dump. Sie sollten die Anwendungsfälle für SMTape und Dump Backup-Engines kennen, um Sie bei der Auswahl der Backup Engine zu unterstützen, die Tape-Backup- und Restore-Vorgänge durchgeführt werden soll.

Dump kann in den folgenden Fällen verwendet werden:

* Direct Access Recovery (DAR) von Dateien und Verzeichnissen
* Sicherung einer Untergruppe von Unterverzeichnissen oder Dateien in einem bestimmten Pfad
* Ausschließen von bestimmten Dateien und Verzeichnissen während der Backups
* Langfristige Backup-Aufbewahrung


SMTape kann in den folgenden Fällen eingesetzt werden:

* Disaster Recovery-Lösung
* Beibehalten der Deduplizierungseinsparungen und der Deduplizierungseinstellungen auf den gesicherten Daten während einer Wiederherstellung
* Backup großer Volumes

