---
permalink: software_setup/concept_decide_whether_to_use_ontap_cli.html 
sidebar: sidebar 
keywords: ontap, software, setup, deciding, decide, if, whether, use, cli, cluster, System Manager, IPv6, HA, root volumes, FlexArray 
summary: 'Wenn es bei Ihrer Konfiguration möglich ist, empfiehlt NetApp zum Einrichten neuer Cluster die Verwendung von System Manager. Wenn Ihre Version von System Manager die Ersteinrichtung von Clustern für Ihre Konfiguration nicht unterstützt oder Sie ein IPv6-Netzwerk einrichten müssen, sollten Sie die ONTAP-Befehlszeilenschnittstelle (CLI) verwenden.' 
---
= Konfigurieren Sie ONTAP in einer neuen Cluster-Übersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn es bei Ihrer Konfiguration möglich ist, empfiehlt NetApp zum Einrichten neuer Cluster die Verwendung von System Manager. Wenn Ihre Version von System Manager die Ersteinrichtung von Clustern für Ihre Konfiguration nicht unterstützt oder Sie ein IPv6-Netzwerk einrichten müssen, sollten Sie die ONTAP-Befehlszeilenschnittstelle (CLI) verwenden.

Ab ONTAP 9.13.1 können Sie auf den A800 und FAS8700 Plattformen neue Cluster über die ONTAP CLI in reinen IPv6-Netzwerkumgebungen erstellen und konfigurieren. Wenn Sie IPv6 in ONTAP 9.13.0 und früher oder auf anderen Plattformen in ONTAP 9.13.1 und höher verwenden müssen, müssen Sie neue Cluster mit IPv4 und dann erstellen link:convert-ipv4-to-ipv6-task.html["Konvertieren in IPv6"].

Wenn Sie eine FlexArray auf nicht-NetApp Festplatten konfigurieren, müssen Sie die ONTAP CLI verwenden, um Root-Volumes auf den Array-LUNs zu konfigurieren, und dann den Cluster-Setup-Assistenten verwenden, um den Cluster einzurichten. Weitere Informationen finden Sie im link:https://docs.netapp.com/us-en/ontap-flexarray/install/concept_flexarray_virtualization_technology_overview_using_array_luns_for_storage.html["Installation und Anforderungen der FlexArray Virtualisierung"] Dokumentation.
