---
permalink: software_setup/gather_cluster_setup_information.html 
sidebar: sidebar 
keywords: ontap, software, setup, deciding, decide, if, whether, use, cli, cluster, System Manager, IPv6, HA, root volumes 
summary: Software-Setup 
---
= Sammeln von Informationen zur Einrichtung eines ONTAP-Clusters
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie mit dem Cluster-Setup beginnen, sollten Sie die Informationen zusammentragen, die Sie zum Abschließen des Cluster-Setups benötigen, z. B. den Port der Cluster-Managementoberfläche und die IP-Adresse. Hier finden Sie alle relevanten Informationen in den Worksheets zum Cluster Setup. Mithilfe des Cluster-Setup-Arbeitsblatts können Sie die Werte aufzeichnen, die Sie während des Cluster-Setups benötigen. Wenn ein Standardwert angegeben ist, können Sie diesen Wert verwenden oder Ihren eigenen Wert eingeben.

.Über diese Aufgabe
Dieses Verfahren gilt für FAS-, AFF- und ASA-Systeme. Wenn Sie ein ASA r2-System (ASA A1K, ASA A90, ASA A70, ASA A50, ASA A30, ASA A20 oder ASA C30) haben, folgen Sie link:https://docs.netapp.com/us-en/asa-r2/install-setup/initialize-ontap-cluster.html["Diesen Schritten ausführen"^] um einen ONTAP-Cluster einzurichten. ASA r2 Systeme bieten eine vereinfachte ONTAP-Erfahrung speziell für reine SAN-Kunden.



== Systemstandard

Die Systemvoreinstellungen sind die Standardwerte für das private Clusternetzwerk. Am besten verwenden Sie diese Standardwerte. Wenn sie jedoch Ihren Anforderungen nicht entsprechen, können Sie die Tabelle verwenden, um Ihre eigenen Werte zu erfassen.


NOTE: Bei Clustern, die für Netzwerk-Switches konfiguriert sind, muss jeder Cluster-Switch die MTU-Größe von 9000 verwenden.

[cols="2*"]
|===
| Arten von Informationen | Ihre Werte 


| Private Cluster-Netzwerk-Ports |  


| Cluster-Netzwerk-Netmask |  


| IP-Adressen der Cluster-Schnittstelle (für jeden Cluster-Netzwerkport auf jedem Node) die IP-Adressen für jeden Node müssen sich im gleichen Subnetz befinden. |  
|===


== Cluster-Informationen

[cols="2*"]
|===
| Arten von Informationen | Ihre Werte 


| Cluster-Name der Name muss mit einem Buchstaben beginnen und darf nicht mehr als 44 Zeichen lang sein. Der Name kann die folgenden Sonderzeichen enthalten: 
`.` `-` `_` |  
|===


== Mit Lizenzschlüssel

Auf der NetApp Support Site finden Sie Lizenzschlüssel für Ihre Standard- oder Add-on-Software-Bestellungen unter *Mein Support* > *Software-Lizenzen*.

[cols="2*"]
|===
| Arten von Informationen | Ihre Werte 


| Mit Lizenzschlüssel |  
|===


== Admin-Storage Virtual Machine (SVM)

[cols="2*"]
|===
| Arten von Informationen | Ihre Werte 


 a| 
Passwort für den Cluster-Administrator

Das Passwort für das Administratorkonto, das das Cluster erfordert, bevor dem Cluster-Administrator Zugriff auf die Konsole oder über ein sicheres Protokoll gewährt wird.


NOTE: Aus Sicherheitsgründen wird die Erfassung von Passwörtern in diesem Arbeitsblatt nicht empfohlen.

Die Standardregeln für Passwörter lauten wie folgt:

* Ein Passwort muss mindestens acht Zeichen lang sein.
* Ein Kennwort muss mindestens einen Buchstaben und eine Ziffer enthalten.

 a| 



 a| 
Port für die Cluster-Managementoberfläche

Der physische Port, der mit dem Datennetzwerk verbunden ist und dem Cluster-Administrator das Cluster-Management ermöglicht.
 a| 



 a| 
Die IP-Adresse der Cluster-Managementoberfläche

Eine eindeutige IPv4- oder IPv6-Adresse für die Cluster-Managementoberfläche. Der Cluster-Administrator verwendet diese Adresse, um auf die Admin-SVM zuzugreifen und den Cluster zu managen. In der Regel sollte sich diese Adresse im Datennetzwerk befinden.

Sie können diese IP-Adresse vom Administrator beziehen, der für das Zuweisen von IP-Adressen in Ihrem Unternehmen verantwortlich ist.

Beispiel: 192.0.2.66
 a| 



 a| 
Cluster-Managementoberfläche Netmask (IPv4)

Die Subnetzmaske, die den Bereich gültiger IPv4-Adressen im Cluster-Managementnetzwerk definiert.

Beispiel: 255.255.255.0
 a| 



 a| 
Cluster-Managementoberfläche Netzmaskenlänge (IPv6)

Wenn die Cluster-Managementoberfläche eine IPv6-Adresse verwendet, stellt dieser Wert die Präfixlänge dar, die den Bereich gültiger IPv6-Adressen im Cluster-Managementnetzwerk definiert.

Beispiel: 64
 a| 



 a| 
Standard-Gateway für die Cluster-Managementoberfläche

Die IP-Adresse für den Router im Cluster-Managementnetzwerk.
 a| 



 a| 
DNS-Domain-Name

Der Name der DNS-Domäne Ihres Netzwerks.

Der Domain-Name muss aus alphanumerischen Zeichen bestehen. Um mehrere DNS-Domain-Namen einzugeben, trennen Sie jeden Namen durch Komma oder Leerzeichen.
 a| 



 a| 
IP-Adressen des Nameserver

Die IP-Adressen der DNS-Namensserver. Trennen Sie jede Adresse mit einem Komma oder einem Leerzeichen.
 a| 

|===


== Node-Informationen (für jeden Node im Cluster)

[cols="2*"]
|===
| Arten von Informationen | Ihre Werte 


 a| 
Physischer Standort des Controllers (optional)

Eine Beschreibung des physischen Standorts des Controllers. Verwenden Sie eine Beschreibung, die bestimmt, wo dieser Knoten im Cluster gefunden werden soll (z. B. „`Lab 5, Row 7, Rack B`“).
 a| 



 a| 
Port für die Node-Managementoberfläche

Der physische Port, der mit dem Node-Managementnetzwerk verbunden ist und dem Clusteradministrator das Verwalten des Node ermöglicht.
 a| 



 a| 
IP-Adresse für die Node-Managementoberfläche

Eine eindeutige IPv4- oder IPv6-Adresse für die Node-Managementoberfläche im Managementnetzwerk. Wenn Sie den Port der Node-Managementoberfläche als Datenport definiert haben, sollte diese IP-Adresse eine eindeutige IP-Adresse im Datennetzwerk sein.

Sie können diese IP-Adresse vom Administrator beziehen, der für das Zuweisen von IP-Adressen in Ihrem Unternehmen verantwortlich ist.

Beispiel: 192.0.2.66
 a| 



 a| 
Node-Managementoberfläche Netmask (IPv4)

Die Subnetzmaske, die den Bereich gültiger IP-Adressen im Node-Managementnetzwerk definiert.

Wenn Sie den Port der Node-Managementoberfläche als Daten-Port definiert haben, sollte die Netmask die Subnetzmaske für das Datennetzwerk sein.

Beispiel: 255.255.255.0
 a| 



 a| 
Netmask-Länge der Node-Managementoberfläche (IPv6)

Wenn die Node-Managementoberfläche eine IPv6-Adresse verwendet, stellt dieser Wert die Präfixlänge dar, die den Bereich gültiger IPv6-Adressen im Node-Managementnetzwerk definiert.

Beispiel: 64
 a| 



 a| 
Standard-Gateway für die Node-Managementoberfläche

Die IP-Adresse für den Router im Node-Managementnetzwerk.
 a| 

|===


== Informationen zum NTP-Server

[cols="2*"]
|===
| Arten von Informationen | Ihre Werte 


 a| 
NTP-Serveradressen

Die IP-Adressen der NTP-Server (Network Time Protocol) an Ihrem Standort. Diese Server werden verwendet, um die Zeit über das Cluster hinweg zu synchronisieren.
 a| 

|===