---
sidebar: sidebar 
permalink: software_setup/setup-cluster.html 
keywords: install, installing, cluster, set up, setup, configure, disk, data ports, guided setup, local tiers, aggregate, vserver, volume, configuring ONTAP on a new cluster, configuring a new cluster, assign a node-management IP address, node, DNS server, host name, hostname, NTP server, synchronize time, create a local tier, configure protocol, SSD, provision storage, add LUN, add volume, add namespace, volume, vserver, configure ONTAP on a new cluster, configuration 
summary: System Manager bietet einen einfachen und unkomplizierten Workflow für die Einrichtung des Clusters und die Konfiguration des Speichers. 
---
= Ein ONTAP Cluster erstellen und Knoten beitreten
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp empfiehlt, neue Cluster mit dem System Manager zu erstellen. Der System Manager bietet einen einfachen und unkomplizierten Workflow für die Cluster-Einrichtung. Die Verwendung der ONTAP Befehlszeilenschnittstelle (CLI) ist nur erforderlich, wenn Sie ONTAP 9.7 oder älter in einer MetroCluster-Konfiguration ausführen oder einen reinen IPv6-Cluster auf unterstützten Systemen konfigurieren müssen.

.Über diese Aufgabe
Dieses Verfahren gilt für link:https://docs.netapp.com/us-en/ontap-systems-family/index.html["AFF, ASA, FAS"^] und link:https://docs.netapp.com/us-en/ontap-afx/index.html["AFX-Systeme"^]. Bei einem ASA r2 System (ASA A1K, ASA A90, ASA A70, ASA A50, ASA A30, ASA A20 oder ASA C30) ist link:https://docs.netapp.com/us-en/asa-r2/install-setup/initialize-ontap-cluster.html["diese Schritte"^] zu folgen, um mithilfe des System Manager ein ONTAP Cluster einzurichten. ASA r2 Systeme bieten eine vereinfachte ONTAP Erfahrung speziell für ausschließlich SAN-basierte Kunden.

Die Zuweisung von IPv6-Adressen zu Management-LIFs während der Cluster-Einrichtung wird auf den folgenden Systemen und ONTAP Versionen unterstützt.

[cols="2"]
|===
| ONTAP Version | Unterstützte Systeme 


| 9.17.1 und später  a| 
* AFF C60
* AFF C30
* AFF A50
* AFF A30
* AFF A20


Ihre BMC Version muss 19.3 oder höher sein, um die IPv6-Adresszuweisung während der Cluster-Einrichtung zu unterstützen.



| ONTAP 9.13.1 und höher  a| 
* AFF A800
* FAS8700


|===
Sie müssen die Clusterkonfiguration mit der ONTAP CLI durchführen, um den unterstützten Systemen IPv6-Adressen zuzuweisen. Wenn die Zuweisung von IPv6-Adressen während der Clusterkonfiguration auf Ihrem System und Ihrer ONTAP Version nicht unterstützt wird, sollten Sie den System Manager verwenden, um Ihren Cluster mit IPv4-Adressen zu erstellen und dann link:convert-ipv4-to-ipv6-task.html["In IPv6 konvertieren"] Adressen nach Abschluss der Clusterkonfiguration zuzuweisen.


NOTE: System Manager unterstützt keine Bereitstellungen, die IPv6-Netzwerkfunktionen in ONTAP 9.6 und früher erfordern.

.Bevor Sie beginnen
* Sie sollten Ihr neues Speichersystem gemäß der Installations- und Einrichtungsanweisungen für Ihr Systemmodell installiert, verkabelt und eingeschaltet haben.
+
Siehe link:https://docs.netapp.com/us-en/ontap-systems/index.html["ONTAP Hardware-Systemdokumentation"^].

* Falls Cluster-Switches Teil der Systeminstallation sind, überprüfen Sie die Verkabelungs- und Konfigurationshinweise Ihres Cluster-Switch-Modells für die Cluster-Ports Ihrer neuen Speichersysteme. Siehe link:https://docs.netapp.com/us-en/ontap-systems-switches/index.html["Switch-Dokumentation für ONTAP Hardware-Systeme"^].
+
.. Wählen Sie die *Cluster Switches* oder *Shared Switches* in der Kachel *Unterstützte Switches* aus.
.. Wählen Sie die *Install*-Dokumentation für Ihr Switch-Modell aus.
.. Suchen Sie nach dem Thema *Review cabling and configuration considerations* und überprüfen Sie es für Ihr Speichersystem.


* link:gather_cluster_setup_information.html["Die benötigten Informationen zusammenstellen"]um die Cluster-Einrichtung abzuschließen.
* Für die Kommunikation innerhalb des Clusters sollten auf jedem Knoten des Clusters Cluster-Netzwerkschnittstellen konfiguriert werden.
* Wenn Sie die CLI zur Konfiguration von IPv6 verwenden, sollte IPv6 auf dem Base Management Controller (BMC) konfiguriert werden, sodass per SSH auf das System zugegriffen werden kann.


.Schritte
[role="tabbed-block"]
====
.System Manager
--
. Eine Node-Management-IP-Adresse zuweisen
+
** Windows Computer
+
... Den Windows-Computer mit demselben Subnetz wie die Controller verbinden.
+
Dadurch wird Ihrem System automatisch eine Node-Management-IP-Adresse zugewiesen.

... Das *Netzlaufwerk* öffnen, um die Knoten zu ermitteln.
... Wählen Sie den Knoten aus, um den Cluster-Setup-Assistenten zu starten.


** Nicht-Windows Computer
+
... Alle Knoten, die dem Cluster hinzugefügt werden, einschalten.
+
Dies ist erforderlich, um die Erkennung für Ihre Clusterkonfiguration zu aktivieren.

... Stellen Sie eine Verbindung zur Konsole des ersten Knotens her.
+
Der Knoten wird hochgefahren, anschließend startet der Cluster Setup-Assistent auf der Konsole.

+
[listing]
----
Welcome to the cluster setup wizard....
----
... Die AutoSupport-Aussage wird bestätigt.
+
[listing]
----
Type yes to confirm and continue {yes}: yes
----
+
AutoSupport ist standardmäßig aktiviert.

... Auf dem Bildschirm werden Anweisungen angezeigt, um dem Knoten eine Management-IP-Adresse zuzuweisen.
... In einem Webbrowser die konfigurierte Node-Management-IP-Adresse eingeben: "https://node-management-IP"[].
+
Der System Manager erkennt automatisch die restlichen Knoten im Cluster.





. Unter *Speichersystem initialisieren* den Clusternamen und das Administratorpasswort eingeben.
. Unter *Netzwerk* die Cluster-Management-IP-Adresse, die Subnetzmaske und das Gateway eingeben.
. Wenn der Domain Name Service zur Auflösung von Hostnamen verwendet werden soll, ist *Domain Name Service (DNS) verwenden* auszuwählen; anschließend sind die DNS-Serverinformationen einzugeben.
. Wenn das Network Time Protocol (NTP) zur Synchronisierung der Zeiten im Cluster verwendet werden soll, unter *Andere* die Option *Zeitdienste (NTP) verwenden* auswählen und anschließend die NTP-Serverinformationen eingeben.
. Wählen Sie *Absenden*.


--
.ONTAP CLI
--
. Alle Knoten, die dem Cluster hinzugefügt werden, einschalten.
+
Dies ist erforderlich, um die Erkennung für Ihre Clusterkonfiguration zu aktivieren.

. Stellen Sie eine Verbindung zur Konsole des ersten Knotens her.
+
Der Knoten wird hochgefahren, anschließend startet der Cluster Setup-Assistent auf der Konsole.

+
[listing]
----
Welcome to the cluster setup wizard....
----
. Die AutoSupport-Aussage wird bestätigt.
+
[listing]
----
Type yes to confirm and continue {yes}: yes
----
+
AutoSupport ist standardmäßig aktiviert.

. Auf dem Bildschirm werden Anweisungen angezeigt, um dem Knoten eine Management-IP-Adresse zuzuweisen.
. *Eingabetaste* drücken, um fortzufahren.
+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
----
. Neuen Cluster erstellen:
+
.. Eingeben `create`
.. Die Systemvorgaben können übernommen oder eigene Werte eingegeben werden.
.. Nach Abschluss der Einrichtung im Cluster anmelden und überprüfen, ob der Cluster aktiv ist und der erste Knoten fehlerfrei funktioniert: `cluster show`
+
Das folgende Beispiel zeigt einen Cluster, in dem der erste Knoten (cluster1-01) fehlerfrei und zur Teilnahme berechtigt ist:

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
cluster1-01           true    true
----
+
Bei Bedarf kann mit dem  `cluster setup` Befehl auf den Cluster Setup-Assistenten zugegriffen und alle Werte geändert werden, die für die Admin- oder Node-SVM eingegeben wurden.



. Einen Knoten zum Cluster hinzufügen:
+
Sie können jeweils einen Knoten zum Cluster hinzufügen. Der Beitrittsvorgang muss für jeden Knoten abgeschlossen sein, und der Knoten muss Teil des Clusters sein, bevor der nächste Knoten hinzugefügt werden kann.

+
.. Melden Sie sich an dem Knoten an, dem Sie im Cluster beitreten möchten.
+
Der Cluster Setup-Assistent startet auf der Konsole.

+
[listing]
----
Welcome to the cluster setup wizard....
----
.. Die AutoSupport-Aussage wird bestätigt.
+

NOTE: AutoSupport ist standardmäßig aktiviert.



+
[listing]
----
Type yes to confirm and continue {yes}: yes
----
+
.. Folgen Sie den Anweisungen auf dem Bildschirm, um dem Knoten eine IP-Adresse zuzuweisen.
.. *Eingabetaste* drücken, um fortzufahren.
+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
----
.. Eingeben `join`
.. Befolgen Sie die Anweisungen auf dem Bildschirm, um den Knoten einzurichten und dem Cluster beizutreten.
.. Nach Abschluss der Einrichtung sollte überprüft werden, ob der Knoten fehlerfrei funktioniert und zur Teilnahme am Cluster berechtigt ist: `cluster show`
+
Das folgende Beispiel zeigt einen Cluster, nachdem der zweite Knoten (cluster1-02) dem Cluster beigetreten ist:

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
cluster1-01           true    true
cluster1-02           true    true
----


. Schritt 7 wird für jeden verbleibenden Knoten wiederholt, um ihn beizutreten.


--
====
.Was kommt als Nächstes
* Falls erforderlich, link:convert-ipv4-to-ipv6-task.html["Umstellung von IPv4 auf IPv6"].
* link:task_check_cluster_with_config_advisor.html["Active IQ Config Advisor kann zur Validierung Ihrer Konfiguration und zur Überprüfung auf häufige Konfigurationsfehler verwendet werden."].

