---
permalink: software_setup/task_synchronize_the_system_time_across_the_cluster.html 
sidebar: sidebar 
keywords: ontap, software, setup, synchronize, system, time, across, cluster 
summary: Die Synchronisierung der Zeit stellt sicher, dass jeder Knoten im Cluster die gleiche Zeit hat und verhindert CIFS- und Kerberos-Ausfälle. 
---
= Synchronisierung der Systemzeit in einem ONTAP Cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Synchronisierung der Zeit stellt sicher, dass jeder Knoten im Cluster die gleiche Zeit hat und verhindert CIFS- und Kerberos-Ausfälle.

An Ihrem Standort sollte ein Network Time Protocol (NTP)-Server eingerichtet werden. Ab ONTAP 9.5 ist die Einrichtung Ihres NTP-Servers mit symmetrischer Authentifizierung möglich. Weitere Informationen finden sich in der Dokumentation zu link:../system-admin/manage-cluster-time-concept.html["Verwaltung der Clusterzeit (nur für Clusteradministratoren)"].

Die Zeit im gesamten Cluster wird synchronisiert, indem der Cluster mit einem oder mehreren NTP-Servern verknüpft wird.

. Es sollte überprüft werden, ob die Systemzeit und die Zeitzone für jeden Knoten korrekt eingestellt sind:
+
[source, cli]
----
cluster date show
----
+
Alle Knoten im Cluster sollten auf dieselbe Zeitzone eingestellt sein.

+
Dieses Beispiel zeigt das Datum und die Zeitzone für jeden Knoten im Cluster.

+
[listing]
----
cluster1::> cluster date show
Node         Date                Time zone
------------ ------------------- -----------------
cluster1-01  01/06/2015 09:35:15 America/New_York
cluster1-02  01/06/2015 09:35:15 America/New_York
cluster1-03  01/06/2015 09:35:15 America/New_York
cluster1-04  01/06/2015 09:35:15 America/New_York
4 entries were displayed.
----
. Das Datum oder die Zeitzone für alle Knoten ändern:
+
[source, cli]
----
cluster date modify
----
+
Dieses Beispiel ändert die Zeitzone für den Cluster auf GMT:

+
[listing]
----
cluster1::> cluster date modify -timezone GMT
----
. Den Cluster mit Ihrem NTP-Server verknüpfen:
+
Zum Einrichten Ihres NTP-Servers ohne symmetrische Authentifizierung ist folgender Befehl einzugeben:

+
[source, cli]
----
cluster time-service ntp server create -server <server_name>
----
+
Um Ihren NTP-Server mit symmetrischer Authentifizierung einzurichten, den folgenden Befehl eingeben:

+
[source, cli]
----
cluster time-service ntp server create -server <server_ip_address> -key-id <key_id>
----
+

NOTE: Die symmetrische Authentifizierung ist ab ONTAP 9.5 verfügbar. In ONTAP 9.4 oder früher ist sie nicht verfügbar.

+
Dieses Beispiel setzt voraus, dass DNS für den Cluster konfiguriert wurde. Wenn DNS nicht konfiguriert wurde, ist die IP-Adresse des NTP-Servers anzugeben:

+
[listing]
----
cluster1::> cluster time-service ntp server create -server ntp1.example.com
----
. Es sollte überprüft werden, ob der Cluster mit einem NTP-Server verbunden ist:
+
[source, cli]
----
cluster time-service ntp server show
----
+
Dieses Beispiel zeigt, dass der Cluster mit dem NTP-Server ntp1.example.com verknüpft ist.

+
[listing]
----
cluster1::> cluster time-service ntp server show
Server               Version
-------------------- -----------
ntp1.example.com     auto
----




[[commands-for-managing-symmetric-authentication-on-ntp-servers]]
== Befehle zur Verwaltung der symmetrischen Authentifizierung auf NTP-Servern

Ab ONTAP 9.5 wird das Network Time Protocol (NTP) Version 3 unterstützt. NTPv3 beinhaltet eine symmetrische Authentifizierung mit SHA-1-Schlüsseln, was die Netzwerksicherheit erhöht.

[cols="2*"]
|===
| Dazu ... | Verwenden Sie diesen Befehl... 


 a| 
Konfiguration eines NTP-Servers ohne symmetrische Authentifizierung
 a| 
[source, cli]
----
cluster time-service ntp server create -server server_name
----


 a| 
Einen NTP-Server mit symmetrischer Authentifizierung konfigurieren
 a| 
[source, cli]
----
cluster time-service ntp server create -server server_ip_address -key-id key_id
----


 a| 
Symmetrische Authentifizierung für einen vorhandenen NTP-Server aktivieren

Ein bestehender NTP-Server kann durch Hinzufügen der erforderlichen Schlüssel-ID so geändert werden, dass die Authentifizierung aktiviert wird.
 a| 
[source, cli]
----
cluster time-service ntp server modify -server server_name -key-id key_id
----


 a| 
Einen gemeinsamen NTP-Schlüssel konfigurieren
 a| 
[source, cli]
----
cluster time-service ntp key create -id shared_key_id -type shared_key_type -value shared_key_value
----
*Hinweis:* Gemeinsame Schlüssel werden über eine ID referenziert. Die ID, ihr Typ und ihr Wert müssen sowohl auf dem Knoten als auch auf dem NTP Server identisch sein.



 a| 
Einen NTP-Server mit einer unbekannten Schlüssel-ID konfigurieren
 a| 
[source, cli]
----
cluster time-service ntp server create -server server_name -key-id key_id
----


 a| 
Ein Server mit einer Schlüssel-ID, die auf dem NTP-Server nicht konfiguriert ist, wird konfiguriert.
 a| 
[source, cli]
----
cluster time-service ntp server create -server server_name -key-id key_id
----
*Hinweis:* Die Schlüssel-ID, der Typ und der Wert müssen mit der auf dem NTP-Server konfigurierten Schlüssel-ID, dem Typ und dem Wert identisch sein.



 a| 
Symmetrische Authentifizierung deaktivieren
 a| 
[source, cli]
----
cluster time-service ntp server modify -server server_name -authentication disabled
----
|===
.Verwandte Informationen
* link:../system-admin/index.html["Systemadministration"]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=cluster+time-service+ntp["Cluster Zeitdienst NTP"^]

