---
permalink: software_setup/task_check_cluster_with_config_advisor.html 
sidebar: sidebar 
keywords: ontap, software, setup, check, cluster, digital advisor, active iq, config, advisor 
summary: Nachdem Sie alle Nodes dem neuen Cluster hinzugefügt haben, sollten Sie Active IQ Config Advisor ausführen, um die Konfiguration zu validieren und auf häufige Konfigurationsfehler zu überprüfen. 
---
= Überprüfen Sie Ihren Cluster mit Digital Advisor Config Advisor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie alle Nodes dem neuen Cluster hinzugefügt haben, sollten Sie Active IQ Config Advisor ausführen, um die Konfiguration zu validieren und auf häufige Konfigurationsfehler zu überprüfen.

Config Advisor ist eine webbasierte Anwendung, die Sie auf Ihrem Laptop, Ihrer virtuellen Maschine oder einem Server installieren und auf Windows-, Linux- und Mac-Plattformen einsetzbar ist.

Config Advisor führt eine Reihe von Befehlen aus, um die Installation zu validieren und den Gesamtstatus der Konfiguration, einschließlich des Clusters und der Storage Switches, zu überprüfen.

. Laden Sie Active IQ Config Advisor herunter und installieren Sie es.
+
link:https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^]

. Starten Sie Digital Advisor, und richten Sie eine Passphrase ein, wenn Sie dazu aufgefordert werden.
. Überprüfen Sie Ihre Einstellungen und klicken Sie auf *Speichern*.
. Klicken Sie auf der Seite *Ziele* auf *Validierung nach der ONTAP-Bereitstellung*.
. Wählen Sie entweder den Modus „Assistent“ oder „Experte“.
+
Wenn Sie den Modus „Assistent“ wählen, werden die angeschlossenen Switches automatisch erkannt.

. Geben Sie die Cluster-Anmeldedaten ein.
. (Optional) Klicken Sie Auf *Formular Validieren*.
. Um mit dem Sammeln von Daten zu beginnen, klicken Sie auf *Speichern & Bewerten*.
. Nach Abschluss der Datenerfassung können Sie unter *Job Monitor > Aktionen* die erfassten Daten anzeigen, indem Sie auf das Symbol *Datenansicht* klicken und die Ergebnisse anzeigen, indem Sie auf das Symbol *Ergebnisse* klicken.
. Lösung der von Config Advisor identifizierten Probleme

