---
sidebar: sidebar 
permalink: high-availability/ha_automatic_giveback_commands.html 
keywords: ontap, high, availability, ha, pair, automatic, giveback, commands 
summary: Befehle für das automatische Giveback 
---
= Befehle für das automatische Giveback
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Standardmäßig gibt der Partner-Node bei Übernahme automatisch Storage zurück, wenn der Offline-Node wieder in den Online-Modus versetzt wird, sodass die Hochverfügbarkeitspaarbeziehung wiederhergestellt wird. In den meisten Fällen ist dies das gewünschte Verhalten. Wenn Sie das automatische Giveback deaktivieren müssen - zum Beispiel, wenn Sie die Ursache der Übernahme vor der Rückgabe untersuchen wollen - müssen Sie sich über die Interaktion der nicht-Standardeinstellungen im Klaren sein.

|===


| Ihr Ziel ist | Befehl 


 a| 
Aktivieren Sie das automatische Giveback. So tritt das Giveback ein, sobald der überneitge Knoten gebootet wurde, erreicht den Status Warten auf GiveBack und die Verzögerung vor Ablauf der automatischen GiveBack-Periode.

Die Standardeinstellung lautet true.
 a| 
`storage failover modify ‑node _nodename_ ‑auto‑giveback true`



 a| 
Deaktivieren Sie das automatische Giveback. Die Standardeinstellung lautet true.

*Hinweis:* diesen Parameter auf false zu setzen, deaktiviert das automatische Giveback nach Übernahme in Panik nicht; automatisches Giveback nach Übernahme in Panik muss durch Setzen des deaktiviert werden `‑auto‑giveback‑after‑panic` Parameter auf FALSE.
 a| 
`storage failover modify ‑node _nodename_ ‑auto‑giveback false`



 a| 
Deaktivieren Sie das automatische Giveback nach dem Übernehmen in Panik (diese Einstellung ist standardmäßig aktiviert).
 a| 
`storage failover modify ‑node _nodename_ ‑auto‑giveback‑after‑panic false`



 a| 
Automatische Rückübertragung für eine bestimmte Anzahl von Sekunden verzögern (Standardeinstellung ist 600). Diese Option bestimmt die Mindestzeit, die ein Node vor dem automatischen Giveback verbleibt.
 a| 
`storage failover modify ‑node _nodename_ ‑delay‑seconds _seconds_`

|===


== Änderungen des Befehls zum Storage Failover wirken sich auf die automatische Rückgabe aus

Der Betrieb der automatischen Rückgabe hängt davon ab, wie Sie die Parameter des Änderungsbefehls für das Storage Failover konfigurieren.

In der folgenden Tabelle sind die Standardeinstellungen für das aufgeführt `storage failover modify` Befehlsparameter, die auf Takeover-Ereignisse angewendet werden und nicht durch einen Panikzustand verursacht wurden.

|===


| Parameter | Standardeinstellung 


 a| 
`-auto-giveback _true_ | _false_`
 a| 
`_true_`



 a| 
`-delay-seconds _integer_ (seconds)`
 a| 
600



 a| 
`-onreboot _true_ | _false_`
 a| 
`_true_`

|===
In der folgenden Tabelle wird beschrieben, wie die Kombinationen des beschrieben werden `-onreboot` Und `-auto-giveback` Parameter wirken sich auf die automatische Rückgabe von Takeover-Ereignissen aus, die nicht durch Panikzustand verursacht wurden.

|===


| `storage failover modify` Verwendete Parameter | Ursache des Übernahmens | Findet ein automatisches Giveback statt? 


 a| 
`-onreboot _true_`

`-auto-giveback _true_`
| Befehl „neu booten“ | Ja. 


| Stoppen Sie den Befehl, oder schalten Sie den Vorgang aus und wieder ein, der vom Service Processor ausgegeben wird | Ja. 


 a| 
`-onreboot _true_`

`-auto-giveback _false_`
| Befehl „neu booten“ | Ja. 


| Stoppen Sie den Befehl, oder schalten Sie den Vorgang aus und wieder ein, der vom Service Processor ausgegeben wird | Nein 


 a| 
`-onreboot _false_`

`-auto-giveback _true_`
| Befehl „neu booten“ | K. A. in diesem Fall erfolgt Übernahme nicht 


| Stoppen Sie den Befehl, oder schalten Sie den Vorgang aus und wieder ein, der vom Service Processor ausgegeben wird | Ja. 


 a| 
`-onreboot _false_`

`-auto-giveback _false_`
| Befehl „neu booten“ | Nein 


| Stoppen Sie den Befehl, oder schalten Sie den Vorgang aus und wieder ein, der vom Service Processor ausgegeben wird | Nein 
|===
Der `-auto-giveback` Parameter steuert die Rückübertragung nach Panik und allen anderen automatischen Takovern. Wenn der `-onreboot` Parameter ist auf festgelegt `true` Darüber hinaus wird ein Takeover aufgrund eines Neustarts durchgeführt – dann wird das automatische Giveback immer durchgeführt, unabhängig davon, ob der `-auto-giveback` Parameter ist auf festgelegt `true`.

Der `-onreboot` Der Parameter gilt für Neustart und Stopp-Befehle, die von ONTAP ausgegeben werden. Wenn der `-onreboot` Parameter ist auf false gesetzt, eine Übernahme findet nicht im Fall eines Node-Neubootens statt. Daher kann ein automatisches Giveback nicht auftreten, unabhängig davon, ob der `-auto-giveback` Parameter ist auf „true“ gesetzt. Eine Client-Störung tritt auf.



== Die Auswirkungen der automatischen Giveback-Parameterkombinationen, die für Panikfälle gelten.

In der folgenden Tabelle sind die aufgeführt `storage failover modify` Befehlsparameter, die für Panikfälle gelten:

|===


| Parameter | Standardeinstellung 


 a| 
`-onpanic _true | false_`
 a| 
`_true_`



 a| 
`-auto-giveback-after-panic _true | false_`

(Berechtigung: Erweitert)
 a| 
`_true_`



 a| 
`-auto-giveback _true | false_`
 a| 
`_true_`

|===
In der folgenden Tabelle wird beschrieben, wie die Parameterkombinationen des beschrieben werden `storage failover modify` Befehl beeinflusst die automatische Rückgabe in Panikfällen.

[cols="60,40"]
|===


| `storage failover` Verwendete Parameter | Findet nach einem Panikzustand die automatische Rückgabe statt? 


| `-onpanic true`
`-auto-giveback true`
`-auto-giveback-after-panic true` | Ja. 


| `-onpanic true`
`-auto-giveback true`
`-auto-giveback-after-panic false` | Ja. 


| `-onpanic true`
`-auto-giveback false`
`-auto-giveback-after-panic true` | Ja. 


| `-onpanic true`
`-auto-giveback false`
`-auto-giveback-after-panic false` | Nein 


| `-onpanic false`Wenn `-onpanic` Ist auf festgelegt `false`, Übernahme/Rückgabe geschieht nicht, unabhängig vom eingestellten Wert `-auto-giveback` Oder `-auto-giveback-after-panic` | Nein 
|===

NOTE: Ein Takeover kann auf einen Fehler führen, der nicht mit einem Panikzustand verbunden ist. Ein _Failure_ ist aufgetreten, wenn die Kommunikation zwischen einem Knoten und seinem Partner verloren geht, auch als _Heartbeat Loss_ bezeichnet wird. Wenn ein Takeover aufgrund eines Ausfalls auftritt, wird das Giveback vom gesteuert `-onfailure` Parameter anstelle des `-auto-giveback-after-panic parameter`.


NOTE: Bei einer Panik eines Node wird ein Panikpaket an seinen Partner-Node gesendet. Wenn das Panikpaket aus irgendeinem Grund nicht vom Partner-Node empfangen wird, kann der Panikzustand als Fehler interpretiert werden. Ohne Eingang des Panikpakets weiß der Partner-Node nur, dass die Kommunikation verloren gegangen ist und weiß nicht, dass ein Panikzustand aufgetreten ist. In diesem Fall verarbeitet der Partner-Knoten den Verlust der Kommunikation als Ausfall statt eines Panikzustands und Giveback wird vom gesteuert `-onfailure` Parameter (und nicht mit dem `-auto-giveback-after-panic parameter`).

Für Details zu allen `storage failover modify` Parameter, siehe link:https://docs.netapp.com/us-en/ontap-cli-9141/storage-failover-modify.html["Handbuch für ONTAP-Seiten"].
