---
sidebar: sidebar 
permalink: high-availability/ha_monitor_an_ha_pair_overview.html 
keywords: ontap, high availability, ha, pair, monitor, hwassist 
summary: Sie können ONTAP Befehle verwenden, um den Status des HA Paars zu überwachen. 
---
= ONTAP Befehle zur Überwachung eines HA-Paares
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können ONTAP Befehle verwenden, um den Status des HA Paars zu überwachen. Wenn eine Übernahme erfolgt, lässt sich auch die Ursache der Übernahme feststellen.

|===


| Wenn Sie überprüfen möchten | Verwenden Sie diesen Befehl 


| Ob ein Failover aktiviert ist oder bereits stattgefunden hat oder Gründe, warum ein Failover derzeit nicht möglich ist | `storage failover show` 


| Die Knoten, auf denen die Einstellung „Storage Failover HA-Modus“ aktiviert ist, werden angezeigt. Der Wert muss auf „ha“ gesetzt werden, damit der Knoten an einer Storage Failover (HA-Paar) Konfiguration teilnimmt. | `storage failover show -fields mode` 


| Ob Hardware-unterstützte Übernahme aktiviert ist | `storage failover hwassist show` 


| Die Historie der Hardware-unterstützt Übernahmeereignisse, die aufgetreten sind | `storage failover hwassist stats show` 


| Der Fortschritt einer Übernahmeoperation, während die Aggregate des Partners auf den Knoten übertragen werden, der die Übernahme durchführt | `storage failover show‑takeover` 


| Der Fortschritt einer Rückgabeoperation bei der Rückgabe von Aggregaten an den Partnerknoten | `storage failover show‑giveback` 


| Ob ein Aggregat während einer Übernahme oder Rückgabe seinen Home-Status hat | `aggregate show ‑fields home‑id,owner‑id,home‑name,owner‑name,is‑home` 


| Ob Cluster HA aktiviert ist (gilt nur für Cluster mit zwei Knoten) | `cluster ha show` 


| Der HA-Zustand der Komponenten eines HA-Paares (auf Systemen, die den HA-Zustand verwenden) | `ha‑config show`Dies ist ein Befehl im Wartungsmodus. 
|===


[[node-states-displayed-by-storage-failover-show-type-commands]]
== Von den Befehlen „storage failover show-type“ angezeigte Knotenzustände

Die folgende Liste beschreibt die Knotenzustände, die der  `storage failover show` Befehl anzeigt.

|===


| Knotenstatus | Beschreibung 


 a| 
Verbindung zu partner_name hergestellt, automatische Übernahme deaktiviert.
 a| 
Die HA-Verbindung ist aktiv und kann Daten an den Partnerknoten übertragen. Die automatische Übernahme des Partnerknotens ist deaktiviert.



 a| 
Warten auf partner_name, Rückgabe der Partner-Ersatzfestplatten ausstehend.
 a| 
Der lokale Knoten kann keine Informationen mit dem Partnerknoten über die HA-Verbindung austauschen. Die Rückgabe der SFO Aggregate an den Partner ist abgeschlossen, aber die Ersatzfestplatten des Partners sind weiterhin im Besitz des lokalen Knotens.

* Der  `storage failover show-giveback`Befehl liefert weitere Informationen.




 a| 
Warten auf partner_name. Warten auf Synchronisierung der Partnersperre.
 a| 
Der lokale Knoten kann über die HA Interconnect keine Informationen mit dem Partnerknoten austauschen und wartet auf die Partner-Sperrsynchronisierung.



 a| 
Warten auf partner_name. Warten auf die Verfügbarkeit der Clusteranwendungen auf dem lokalen Node.
 a| 
Der lokale Knoten kann über die HA Interconnect keine Informationen mit dem Partnerknoten austauschen und wartet darauf, dass die Clusteranwendungen online gehen.



 a| 
Übernahme geplant. Der Zielknoten verlagert seine SFO-Aggregate zur Vorbereitung der Übernahme.
 a| 
Die Übernahmeverarbeitung wurde gestartet. Der Zielknoten verlegt die Eigentumsrechte an seinen SFO-Aggregaten im Vorfeld der Übernahme.



 a| 
Übernahme geplant. Der Zielknoten hat seine SFO-Aggregate zur Vorbereitung der Übernahme verlegt.
 a| 
Die Übernahmeverarbeitung wurde gestartet. Der Zielknoten hat die Eigentumsverhältnisse seiner SFO-Aggregate im Vorfeld der Übernahme verlagert.



 a| 
Übernahme geplant. Warten auf Deaktivierung von Hintergrund-Firmware-Updates auf dem lokalen Knoten. Ein Firmware-Update wird derzeit auf dem Node durchgeführt.
 a| 
Die Übernahmeverarbeitung wurde gestartet. Das System wartet darauf, dass die Hintergrund-Firmware-Aktualisierungsvorgänge auf dem lokalen Knoten abgeschlossen werden.



 a| 
Verlagerung der SFO Aggregate zum übernehmenden Node in Vorbereitung auf die Übernahme.
 a| 
Der lokale Knoten verlagert die Eigentumsrechte an seinen SFO Aggregaten auf den übernehmenden Knoten im Vorfeld der Übernahme.



 a| 
SFO Aggregate wurden auf den übernehmenden Node verschoben. Warten darauf, dass der übernehmende Node übernimmt.
 a| 
Die Übertragung der Eigentumsrechte an den SFO Aggregaten vom lokalen Knoten auf den übernehmenden Knoten ist abgeschlossen. Das System wartet auf die Übernahme durch den übernehmenden Knoten.



 a| 
SFO Aggregate werden zu partner_name verschoben. Warten auf die Deaktivierung von Hintergrund-Firmware-Updates auf dem lokalen Knoten. Ein Firmware-Update wird derzeit auf dem Node durchgeführt.
 a| 
Die Übertragung der Zuständigkeit für SFO Aggregate vom lokalen Knoten auf den übernehmenden Knoten ist im Gange. Das System wartet darauf, dass die Hintergrund-Firmware-Aktualisierungsvorgänge auf dem lokalen Knoten abgeschlossen werden.



 a| 
SFO Aggregate werden zu partner_name verschoben. Es wird darauf gewartet, die Hintergrund-Firmware-Updates für Festplatten auf partner_name zu deaktivieren. Ein Firmware-Update wird derzeit auf dem Node durchgeführt.
 a| 
Die Übertragung der Zuständigkeit für SFO Aggregate vom lokalen Knoten auf den übernehmenden Knoten ist im Gange. Das System wartet auf den Abschluss von Hintergrund-Firmware-Aktualisierungsvorgängen auf dem Partnerknoten.



 a| 
Verbindung zu partner_name hergestellt. Vorheriger Übernahmeversuch wurde abgebrochen, da reason. Der lokale Node besitzt einige SFO Aggregate des Partners. Eine erneute Übernahme des Partners mit dem  `‑bypass-optimization` Parameter auf true übernimmt die verbleibenden Aggregate, alternativ gibt eine Rückgabe des Partners die verlagerten Aggregate zurück.
 a| 
Die HA-Verbindung ist aktiv und kann Daten an den Partnerknoten übertragen. Der vorherige Übernahmeversuch wurde aufgrund des unter „Grund“ angezeigten Grundes abgebrochen. Der lokale Knoten besitzt einige SFO Aggregate seines Partners.

* Entweder eine erneute Übernahme des Partnerknotens durchführen, wobei der Parameter „-bypass-optimization“ auf „true“ gesetzt wird, um die verbleibenden SFO-Aggregate zu übernehmen, oder eine Rückgabe des Partners durchführen, um die verschobenen Aggregate zurückzugeben.




 a| 
Verbindung zu partner_name hergestellt. Der vorherige Übernahmeversuch wurde abgebrochen. Der lokale Node besitzt einige SFO Aggregate des Partners. Eine erneute Übernahme des Partners mit dem  `‑bypass-optimization` Parameter auf true übernimmt die verbleibenden Aggregate, alternativ gibt eine Rückgabe des Partners die verlagerten Aggregate zurück.
 a| 
Die HA-Verbindung ist aktiv und kann Daten an den Partnerknoten übertragen. Der vorherige Übernahmeversuch wurde abgebrochen. Der lokale Knoten besitzt einige SFO Aggregate seines Partners.

* Entweder eine erneute Übernahme des Partnerknotens durchführen, wobei der Parameter „-bypass-optimization“ auf „true“ gesetzt wird, um die verbleibenden SFO-Aggregate zu übernehmen, oder eine Rückgabe des Partners durchführen, um die verschobenen Aggregate zurückzugeben.




 a| 
Warten auf partner_name. Vorheriger Übernahmeversuch wurde abgebrochen, da reason. Der lokale Node besitzt einige SFO Aggregate des Partners. Eine erneute Übernahme des Partners mit dem Parameter „‑bypass-optimization“ auf „true“ übernimmt die verbleibenden Aggregate, alternativ gibt ein Giveback des Partners die verlagerten Aggregate zurück.
 a| 
Der lokale Knoten kann keine Informationen mit dem Partnerknoten über die HA-Verbindung austauschen. Der vorherige Übernahmeversuch wurde aufgrund des unter „Grund“ angezeigten Grundes abgebrochen. Der lokale Knoten besitzt einige SFO Aggregate seines Partners.

* Entweder eine erneute Übernahme des Partnerknotens durchführen, wobei der Parameter „-bypass-optimization“ auf „true“ gesetzt wird, um die verbleibenden SFO-Aggregate zu übernehmen, oder eine Rückgabe des Partners durchführen, um die verschobenen Aggregate zurückzugeben.




 a| 
Warten auf partner_name. Der vorherige Übernahmeversuch wurde abgebrochen. Der lokale Node besitzt einige SFO Aggregate des Partners. Eine erneute Übernahme des Partners mit dem Parameter „‑bypass-optimization“ auf „true“ übernimmt die verbleibenden Aggregate, alternativ gibt ein Giveback des Partners die verlagerten Aggregate zurück.
 a| 
Der lokale Knoten kann keine Informationen mit dem Partnerknoten über die HA-Verbindung austauschen. Der vorherige Übernahmeversuch wurde abgebrochen. Der lokale Knoten besitzt einige SFO Aggregate seines Partners.

* Entweder eine erneute Übernahme des Partnerknotens durchführen, wobei der Parameter „-bypass-optimization“ auf „true“ gesetzt wird, um die verbleibenden SFO-Aggregate zu übernehmen, oder eine Rückgabe des Partners durchführen, um die verschobenen Aggregate zurückzugeben.




 a| 
Verbindung zu partner_name hergestellt. Der vorherige Übernahmeversuch wurde abgebrochen, da die Deaktivierung der Hintergrund-Disk-Firmware-Aktualisierung (BDFU) auf dem lokalen Node fehlgeschlagen ist.
 a| 
Die HA-Verbindung ist aktiv und kann Daten an den Partnerknoten übertragen. Der vorherige Übernahmeversuch wurde abgebrochen, da das Hintergrund-Firmware-Update der Festplatte auf dem lokalen Knoten nicht deaktiviert war.



 a| 
Verbindung zu partner_name hergestellt. Vorheriger Übernahmeversuch wurde abgebrochen, da reason.
 a| 
Die HA-Verbindung ist aktiv und kann Daten an den Partnerknoten übertragen. Der vorherige Übernahmeversuch wurde aufgrund des unter „Grund“ angezeigten Grundes abgebrochen.



 a| 
Warten auf partner_name. Vorheriger Übernahmeversuch wurde abgebrochen, da reason.
 a| 
Der lokale Knoten kann keine Informationen mit dem Partnerknoten über die HA-Verbindung austauschen. Der vorherige Übernahmeversuch wurde aufgrund des unter „Grund“ angezeigten Grundes abgebrochen.



 a| 
Verbindung zu partner_name hergestellt. Der vorherige Übernahmeversuch von partner_name wurde abgebrochen, weil reason.
 a| 
Die HA-Verbindung ist aktiv und kann Daten an den Partnerknoten übertragen. Der vorherige Übernahmeversuch durch den Partnerknoten wurde aufgrund des unter „Grund“ angezeigten Grundes abgebrochen.



 a| 
Verbindung zu partner_name hergestellt. Vorheriger Übernahmeversuch von partner_name wurde abgebrochen.
 a| 
Die HA-Verbindung ist aktiv und kann Daten an den Partnerknoten übertragen. Der vorherige Übernahmeversuch des Partnerknotens wurde abgebrochen.



 a| 
Warten auf partner_name. Der vorherige Übernahmeversuch von partner_name wurde abgebrochen, weil reason.
 a| 
Der lokale Knoten kann keine Informationen mit dem Partnerknoten über die HA-Verbindung austauschen. Der vorherige Übernahmeversuch durch den Partnerknoten wurde aufgrund des unter „Grund“ angezeigten Grundes abgebrochen.



 a| 
Der vorherige Rückgabevorgang ist im Modul: Modulname fehlgeschlagen. Die automatische Rückgabe wird in number of seconds Sekunden eingeleitet.
 a| 
Der vorherige Rückgabeversuch ist im Modul module_name fehlgeschlagen. Die automatische Rückgabe wird in number of seconds Sekunden eingeleitet.

* Der  `storage failover show-giveback`Befehl liefert weitere Informationen.




 a| 
Node besitzt die Aggregate des Partners im Rahmen des unterbrechungsfreien Controller-Upgrade-Verfahrens.
 a| 
Der Knoten besitzt die Aggregate seines Partners aufgrund des derzeit laufenden nicht unterbrechenden Controller Upgrade Verfahrens.



 a| 
Verbindung zu partner_name hergestellt. Der Knoten besitzt Aggregate, die zu einem anderen Knoten im Cluster gehören.
 a| 
Die HA-Verbindung ist aktiv und kann Daten an den Partnerknoten übertragen. Der Knoten besitzt Aggregate, die zu einem anderen Knoten im Cluster gehören.



 a| 
Verbindung zu partner_name hergestellt. Warten auf Synchronisierung der Partnersperre.
 a| 
Die HA-Verbindung ist aktiv und kann Daten an den Partnerknoten übertragen. Das System wartet auf den Abschluss der Partner-Lock-Synchronisierung.



 a| 
Verbindung zu partner_name hergestellt. Warten auf die Verfügbarkeit der Clusteranwendungen auf dem lokalen Node.
 a| 
Die HA-Verbindung ist aktiv und kann Daten an den Partnerknoten übertragen. Das System wartet darauf, dass die Clusteranwendungen auf dem lokalen Knoten online sind.



 a| 
Im Nicht-HA-Modus ist ein Neustart erforderlich, um den gesamten NVRAM zu nutzen.
 a| 
Storage-Failover ist nicht möglich. Die HA-Mode-Option ist auf non_ha konfiguriert.

* Der Knoten muss neu gestartet werden, damit der gesamte NVRAM genutzt werden kann.




 a| 
Nicht-HA-Modus. Der Node muss neu gestartet werden, um HA zu aktivieren.
 a| 
Storage-Failover ist nicht möglich.

* Der Knoten muss neu gestartet werden, um die HA-Funktionalität zu aktivieren.




 a| 
Nicht-HA-Modus.
 a| 
Storage-Failover ist nicht möglich. Die HA-Mode-Option ist auf non_ha konfiguriert.

* Sie müssen den  `storage failover modify ‑mode ha ‑node nodename` Befehl auf beiden Nodes im HA-Paar ausführen und anschließend die Nodes neu starten, um die HA-Fähigkeit zu aktivieren.


|===
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP-Befehlsreferenz"^]
* link:https://docs.netapp.com/us-en/ontap-cli/cluster-ha-show.html["cluster ha show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+failover+hwassist["Storage Failover Hardware-unterstützt"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-failover-modify.html["storage failover modify"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-failover-show.html["storage failover show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-failover-show-giveback.html["storage failover show-giveback"^]

