---
sidebar: sidebar 
permalink: high-availability/index.html 
keywords: high availability, ha, overview 
summary: Übernahme ist der Prozess, in dem ein Node die Kontrolle über den Storage seines Partners übernimmt. GiveBack ist der Prozess, in dem die Speicherung an den Partner zurückgeschickt wird. 
---
= Erfahren Sie mehr über die HA-Paarverwaltung in ONTAP-Clustern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cluster-Nodes werden in HA-Paaren konfiguriert, um Fehlertoleranz und unterbrechungsfreien Betrieb zu gewährleisten. Wenn ein Node ausfällt oder Sie einen Node zur routinemäßigen Wartung herunterfahren müssen, kann sein Partner seinen Storage übernehmen und weiterhin Daten darauf bereitstellen. Der Partner gibt Storage zurück, wenn der Node wieder in den Online-Modus versetzt wird.

Die HA-Paar-Controller-Konfiguration besteht aus einem Paar übereinstimmenden FAS/AFF Storage-Controllern (lokaler Node und Partner-Node). Jeder dieser Nodes ist mit den Festplatten-Shelfs der anderen verbunden. Wenn auf einem Node in einem HA-Paar ein Fehler auftritt und die Verarbeitung der Daten angehalten wird, erkennt der Partner den Status „ausgefallen“ und übernimmt die gesamte Verarbeitung der Daten von diesem Controller.

_Übernahme_ ist der Prozess, in dem ein Node die Kontrolle über den Storage seines Partners übernimmt.

_GiveBack_ ist der Prozess, in dem die Speicherung an den Partner zurückgeschickt wird.

Standardmäßig werden Übernahmen automatisch in einer der folgenden Situationen durchgeführt:

* Ein Software- oder Systemfehler tritt auf einem Node auf, der zu einem Panikzustand führt. Die HA-Paar-Controller führen automatisch einen Failover auf den Partner-Node durch. Nachdem der Partner den Panikzustand wiederhergestellt und hochgefahren hat, führt der Node automatisch ein Giveback durch und stellt den normalen Betrieb des Partners wieder her.
* Auf einem Node tritt ein Systemfehler auf, und der Node kann nicht neu gebootet werden. Wenn ein Node beispielsweise aufgrund eines Stromausfalls ausfällt, führen die HA-Paar-Controller automatisch einen Failover auf seinen Partner-Node aus und stellen Daten vom verbleibenden Storage Controller bereit.



NOTE: Sollte auch der Storage für einen Node zur gleichen Zeit an Strom verlieren, ist ein Standard-Takeover nicht möglich.

* Heartbeat-Meldungen werden nicht vom Partner des Node empfangen. Das könnte passieren, wenn der Partner einen Hardware- oder Softwarefehler (z. B. ein Interconnect-Fehler) hat, der nicht zu einem Panik- oder Systemfehler geführt hat, aber dennoch daran gehindert wird, ihn korrekt zu funktionieren.
* Sie beenden einen der Nodes, ohne den `-f` `-inhibit-takeover true` Parameter oder zu verwenden.



NOTE: In einem Cluster mit zwei Nodes und aktiviertem Cluster HA `‑inhibit‑takeover true` bewirkt das Anhalten oder Neubooten eines Node mit dem Parameter, dass beide Nodes nicht mehr Daten bereitstellen, es sei denn, Sie deaktivieren zuerst Cluster HA und weisen dann Epsilon dem Node zu, der online bleiben soll.

* Sie booten einen der Nodes ohne Verwendung des `‑inhibit‑takeover true` Parameters neu. (Der `‑onboot` Parameter des `storage failover` Befehls ist standardmäßig aktiviert.)
* Das Remote-Management-Gerät (Service Processor) erkennt den Ausfall des Partner-Node. Dies gilt nicht, wenn Sie die Hardware-gestützte Übernahme deaktivieren.


Sie können Takeovers auch manuell mit dem `storage failover takeover` Befehl starten.



== Verbesserungen bei der Cluster-Ausfallsicherheit und Diagnose

Ab ONTAP 9.9 verbessern die folgenden Ergänzungen die Clusterbedienung:

* *Port-Überwachung und -Vermeidung*: In zwei-Knoten-Cluster-Konfigurationen ohne Switches vermeidet das System Ports, die einen vollständigen Paketverlust (Verbindungsverlust) aufweisen. Ab ONTAP 9.8.1 war diese Funktionalität nur in geschalteten Konfigurationen verfügbar.
* *Automatisches Knoten-Failover*: Wenn ein Knoten keine Daten über sein Cluster-Netzwerk bereitstellen kann, sollte dieser Knoten keine Festplatten besitzen. Stattdessen sollte sein HA-Partner übernehmen, wenn der Partner gesund ist.
* *Befehle zur Analyse von Verbindungsproblemen*: Verwenden Sie den folgenden Befehl, um anzuzeigen, welche Cluster-Pfade Paketverlust haben: `network interface check cluster-connectivity show`
+
Erfahren Sie mehr über `network interface check cluster-connectivity show` in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-check-cluster-connectivity-show.html["ONTAP-Befehlsreferenz"^].


