---
sidebar: sidebar 
permalink: high-availability/index.html 
keywords: high availability, ha, overview 
summary: Übernahme ist der Vorgang, bei dem ein Node die Kontrolle über den Storage seines Partners übernimmt. Rückgabe ist der Vorgang, bei dem der Storage an den Partner zurückgegeben wird. 
---
= Informationen zur Verwaltung von HA-Paaren in ONTAP Clustern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Clusterknoten sind in Hochverfügbarkeitspaaren (HA-Paaren) konfiguriert, um Fehlertoleranz und unterbrechungsfreie Vorgänge zu ermöglichen. Fällt ein Knoten aus oder muss ein Knoten für routinemäßige Wartungsarbeiten heruntergefahren werden, kann der Partner dessen Speicher übernehmen und weiterhin Daten daraus bereitstellen. Der Partner gibt den Speicher zurück, wenn der Knoten wieder online ist.

Die HA-Paar-Controller-Konfiguration besteht aus einem Paar übereinstimmender Speichercontroller (lokaler Node und Partner-Node). Jeder dieser Nodes ist mit den Festplatten-Shelfs des jeweils anderen verbunden. Wenn ein Node in einem HA-Paar einen Fehler feststellt und die Datenverarbeitung stoppt, erkennt der Partner den Ausfallstatus des Partners und übernimmt die gesamte Datenverarbeitung von diesem Controller.

Die Übernahme ist der Prozess, bei dem ein Node die Kontrolle über den Storage seines Partners übernimmt.

_Giveback_ ist der Prozess, bei dem der Speicher an den Partner zurückgegeben wird.

Standardmäßig erfolgen Übernahmen automatisch in einer der folgenden Situationen:

* Auf einem Node tritt ein Software- oder Systemausfall auf, der zu einem Panic führt. Die HA Pair Controller übernehmen automatisch auf ihren Partner-Node. Nachdem sich der Partner vom Panic erholt und hochgefahren ist, führt der Node automatisch ein Giveback durch und versetzt den Partner wieder in den Normalbetrieb.
* Ein Systemausfall tritt auf einem Node auf, und der Node kann nicht neu gestartet werden. Beispielsweise übernehmen bei einem Ausfall eines Node aufgrund eines Stromausfalls die HA Pair Controller automatisch auf den Partner-Node und stellen Daten vom verbleibenden Storage Controller bereit.



NOTE: Wenn der Speicher eines Knotens gleichzeitig ebenfalls die Stromversorgung verliert, ist eine Standardübernahme nicht möglich.

* Heartbeat-Nachrichten werden vom Partner des Knotens nicht empfangen. Dies kann auftreten, wenn der Partner einen Hardware- oder Softwarefehler (zum Beispiel einen Interconnect-Fehler) hatte, der zwar keinen Panikzustand auslöste, aber dennoch die korrekte Funktion verhinderte.
* Sie halten einen der Knoten an, ohne den  `-f` oder  `-inhibit-takeover true` Parameter zu verwenden.



NOTE: In einem Zwei-Node-Cluster mit aktiviertem Cluster HA führt das Anhalten oder Neustarten eines Knotens mithilfe des  `‑inhibit‑takeover true` Parameters dazu, dass beide Knoten keine Daten mehr liefern, es sei denn, zuerst wird Cluster HA deaktiviert und dann dem Knoten, der online bleiben soll, epsilon zugewiesen.

* Sie starten einen der Knoten neu, ohne den `‑inhibit‑takeover true` Parameter zu verwenden. (Der `‑onboot` Parameter des `storage failover` Befehls ist standardmäßig aktiviert.)
* Das Fernverwaltungsgerät (Service Processor) erkennt einen Ausfall des Partnerknotens. Dies ist nicht zutreffend, wenn Hardware-unterstützt Takeover deaktiviert ist.


Übernahmen können auch manuell mit dem  `storage failover takeover` Befehl initiiert werden.

Ab ONTAP 9.18.1 kann die verschlüsselte Kommunikation zwischen HA-Paar-Nodes konfiguriert werden. Weitere Informationen finden sich unter link:ha-pair-encryption.html["Verschlüsselung für ONTAP HA Datenverkehr konfigurieren"].



[[cluster-resiliency-and-diagnostic-improvements]]
== Resilienz von Clustern und diagnostische Verbesserungen

Ab ONTAP 9.9.1 verbessern die folgenden Erweiterungen hinsichtlich Ausfallsicherheit und Diagnose den Clusterbetrieb:

* *Portüberwachung und -vermeidung*: In Zwei-Knoten Cluster ohne Switches vermeidet das System Ports, bei denen es zu vollständigem Paketverlust (Verbindungsverlust) kommt. In ONTAP 9.8 und früher war diese Funktionalität nur in Konfigurationen mit Switches verfügbar.
* *Automatisches Node-Failover*: Kann ein Node keine Daten über sein Cluster-Netzwerk bereitstellen, sollte dieser Node keine Festplatten besitzen. Stattdessen sollte der HA-Partner übernehmen, sofern dieser funktionsfähig ist.
* *Befehle zur Analyse von Verbindungsproblemen*: Mit dem folgenden Befehl wird angezeigt, bei welchen Clusterpfaden Paketverluste auftreten: `network interface check cluster-connectivity show`
+
Weitere Informationen zu  `network interface check cluster-connectivity show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-check-cluster-connectivity-show.html["ONTAP-Befehlsreferenz"^].


