---
permalink: nas-audit/additional-information-reference.html 
sidebar: sidebar 
keywords: additional information 
summary: Nachdem Sie den SMB-Clientzugriff erfolgreich getestet haben, können Sie eine erweiterte SMB-Konfiguration vornehmen oder SAN-Zugriff hinzufügen. Nachdem Sie den NFS-Clientzugriff erfolgreich getestet haben, können Sie eine erweiterte NFS-Konfiguration vornehmen oder SAN-Zugriff hinzufügen. Wenn der Protokollzugriff abgeschlossen ist, sollte das Root-Volume der SVM geschützt werden. 
---
= Wo weitere Informationen zu ONTAP SVMs zu finden sind
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie den SMB-Clientzugriff erfolgreich getestet haben, können Sie eine erweiterte SMB-Konfiguration vornehmen oder SAN-Zugriff hinzufügen. Nachdem Sie den NFS-Clientzugriff erfolgreich getestet haben, können Sie eine erweiterte NFS-Konfiguration vornehmen oder SAN-Zugriff hinzufügen. Wenn der Protokollzugriff abgeschlossen ist, sollte das Root-Volume der SVM geschützt werden.



[[smb-configuration]]
== SMB-Konfiguration

Der SMB-Zugriff lässt sich zusätzlich wie folgt konfigurieren:

* link:../smb-admin/index.html["SMB Management"]
+
Es wird erläutert, wie der Dateizugriff mithilfe des SMB-Protokolls konfiguriert und verwaltet werden kann.

* https://www.netapp.com/pdf.html?item=/media/16326-tr-4191.pdf["NetApp Technischer Bericht 4191: Best Practices-Leitfaden für Clustered Data ONTAP 8.2 Windows-Dateidienste"^]
+
Bietet einen kurzen Überblick über die SMB-Implementierung und andere Windows File Services-Funktionen mit Empfehlungen und grundlegenden Informationen zur Fehlerbehebung für ONTAP.

* https://www.netapp.com/pdf.html?item=/media/19673-tr-3740.pdf["NetApp Technical Report 3740: SMB 2 Next-Generation CIFS-Protokoll in Data ONTAP"^]
+
Beschreibt die Funktionen von SMB 2, Konfigurationsdetails und die Implementierung in ONTAP.





[[nfs-configuration]]
== NFS-Konfiguration

Der NFS-Zugriff lässt sich zusätzlich wie folgt konfigurieren:

* link:../nfs-admin/index.html["NFS Management"]
+
Es wird erläutert, wie der Dateizugriff mithilfe des NFS-Protokolls konfiguriert und verwaltet werden kann.

* https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["NetApp Technischer Bericht 4067: NFS Best Practices-Leitfaden und Implementierungsleitfaden"^]
+
Dient als Betriebsanleitung für NFSv3 und NFSv4 und bietet einen Überblick über das ONTAP Betriebssystem mit Schwerpunkt auf NFSv4.

* https://www.netapp.com/pdf.html?item=/media/16328-tr-4668.pdf["NetApp Technischer Bericht 4668: Name Services Best Practices-Leitfaden"^]
+
Bietet eine umfassende Liste bewährter Verfahren, Beschränkungen, Empfehlungen und Überlegungen bei der Konfiguration von LDAP, NIS, DNS sowie lokalen Benutzer- und Gruppendateien für Authentifizierungszwecke.

* https://www.netapp.com/pdf.html?item=/media/19384-tr-4616.pdf["NetApp Technical Report 4616: NFS Kerberos in ONTAP mit Microsoft Active Directory"^]
* https://www.netapp.com/pdf.html?item=/media/19423-tr-4835.pdf["NetApp Technischer Bericht 4835: Konfiguration von LDAP in ONTAP"^]
* https://www.netapp.com/pdf.html?item=/media/16398-tr-3580.pdf["NetApp Technical Report 3580: NFSv4-Erweiterungen und Best Practices-Leitfaden Data ONTAP Implementierung"^]
+
Beschreibt die Best Practices, die bei der Implementierung von NFSv4-Komponenten auf AIX-, Linux- oder Solaris-Clients, die an Systeme mit ONTAP angeschlossen sind, beachtet werden sollten.





[[root-volume-protection]]
== Root Volume-Schutz

Nach der Konfiguration der Protokolle auf der SVM sollte sichergestellt werden, dass das Root-Volume geschützt ist:

* link:../data-protection/index.html["Datenschutz"]
+
Beschreibt, wie ein Load-Sharing-Mirror zum Schutz des SVM-Root-Volumes erstellt wird, was eine NetApp Best Practice für NAS-fähige SVMs ist. Beschreibt außerdem, wie eine schnelle Wiederherstellung nach Volume-Ausfällen oder -Verlusten durch das Hochstufen des SVM-Root-Volumes von einem Load-Sharing-Mirror erfolgen kann.


