---
permalink: nas-audit/audit-symlinks-hard-links-concept.html 
sidebar: sidebar 
keywords: considerations, audit, symlinks, hard links 
summary: Bei der Überprüfung von Symlinks und Hardlinks sind bestimmte Aspekte zu berücksichtigen. 
---
= Informationen zur ONTAP-Prüfung von symbolischen Links und Hardlinks
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Überprüfung von Symlinks und Hardlinks sind bestimmte Aspekte zu berücksichtigen.

Ein Prüfprotokoll enthält Informationen über das geprüfte Objekt, einschließlich des Pfads zu dem geprüften Objekt, der im `ObjectName` Tag angegeben ist. Es ist zu beachten, wie Pfade für symbolische Links und Hardlinks im `ObjectName` Tag erfasst werden.



[[symlinks]]
== Symlinks

Ein symbolischer Link ist eine Datei mit einem separaten Inode, der einen Zeiger auf den Speicherort eines Zielobjekts, des sogenannten Targets, enthält. Beim Zugriff auf ein Objekt über einen symbolischen Link interpretiert ONTAP diesen automatisch und folgt dem tatsächlichen kanonischen, protokollunabhängigen Pfad zum Zielobjekt im Volume.

Im folgenden Beispielausgabe gibt es zwei Symlinks, die beide auf eine Datei mit dem Namen `target.txt` zeigen. Einer der Symlinks ist ein relativer Symlink und einer ist ein absoluter Symlink. Wenn einer der Symlinks geprüft wird, enthält das  `ObjectName`-Tag im Revisionsereignis den Pfad zur Datei `target.txt`:

[listing]
----
[root@host1 audit]# ls -l
total 0
lrwxrwxrwx 1 user1 group1 37 Apr  2 10:09 softlink_fullpath.txt -> /data/audit/target.txt
lrwxrwxrwx 1 user1 group1 10 Apr  2 09:54 softlink.txt -> target.txt
-rwxrwxrwx 1 user1 group1 16 Apr  2 10:05 target.txt
----


[[hard-links]]
== Harte Links

Ein Hardlink ist ein Verzeichniseintrag, der einen Namen mit einer vorhandenen Datei im Dateisystem verknüpft. Der Hardlink verweist auf den Inode-Standort der Originaldatei. Ähnlich wie ONTAP symbolische Links interpretiert, interpretiert ONTAP auch den Hardlink und folgt dem tatsächlichen kanonischen Pfad zum Zielobjekt im Volume. Wenn der Zugriff auf ein Hardlink-Objekt protokolliert wird, zeichnet das Protokollereignis diesen absoluten kanonischen Pfad im  `ObjectName` Tag auf, anstatt des Hardlink-Pfads.
