---
permalink: nas-audit/commands-modify-fpolicy-config-reference.html 
sidebar: sidebar 
keywords: commands, modify, fpolicy, configurations 
summary: Sie können FPolicy externe Engines, Ereignisse, Scopes und Richtlinien ändern. 
---
= Befehle zum Ändern von FPolicy-Konfigurationen in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können FPolicy-Konfigurationen ändern, indem Sie die Elemente ändern, aus denen die Konfiguration besteht. Sie können externe Engines, FPolicy-Ereignisse, FPolicy Scopes, persistente FPolicy-Speicher und FPolicy-Richtlinien ändern. Sie können FPolicy auch aktivieren oder deaktivieren. Wenn Sie die FPolicy deaktivieren, wird die Dateiüberwachung für diese Richtlinie eingestellt.

Sie sollten eine FPolicy-Richtlinie deaktivieren, bevor Sie die Konfiguration ändern.

[cols="35,65"]
|===


| Sie möchten Folgendes ändern: | Befehl 


 a| 
Externe Motoren
 a| 
`vserver fpolicy policy external-engine modify`



 a| 
Veranstaltungen
 a| 
`vserver fpolicy policy event modify`



 a| 
Bereich
 a| 
`vserver fpolicy policy scope modify`



 a| 
Persistenter Speicher
 a| 
`vserver fpolicy persistent-store modify`



 a| 
Richtlinien
 a| 
`vserver fpolicy policy modify`

|===
Erfahren Sie mehr über `vserver fpolicy policy` in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+fpolicy+policy["ONTAP-Befehlsreferenz"^].
