---
permalink: nas-audit/configure-auditing-unix-security-files-directories-task.html 
sidebar: sidebar 
keywords: configure, audit, unix security style files, directories 
summary: Sie konfigurieren Audit für Dateien und Verzeichnisse im UNIX-Sicherheitsstil durch Hinzufügen von Audit ACLs zu NFSv4.x ACLs. So können Sie bestimmte NFS-Datei- und Verzeichniszugriffe zu Sicherheitszwecken überwachen. 
---
= Konfigurieren Sie die Überwachung von UNIX-Sicherheitsdateien und -Verzeichnissen in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie konfigurieren Audit für Dateien und Verzeichnisse im UNIX-Sicherheitsstil durch Hinzufügen von Audit ACLs zu NFSv4.x ACLs. So können Sie bestimmte NFS-Datei- und Verzeichniszugriffe zu Sicherheitszwecken überwachen.

.Über diese Aufgabe
Für NFSv4.x sind Ermessenswert- und SystemAsse in derselben ACL gespeichert. Sie werden nicht in separaten DACLs und SACLs gespeichert. Daher müssen Sie beim Hinzufügen von Audit Aces zu einer vorhandenen ACL Vorsicht walten lassen, um zu vermeiden, dass eine vorhandene ACL überschrieben und verloren geht. Die Reihenfolge, in der Sie die Audit Aces zu einer bestehenden ACL hinzufügen, ist nicht von Bedeutung.

.Schritte
. Rufen Sie die vorhandene ACL für die Datei oder `nfs4_getfacl` das Verzeichnis mit dem Befehl oder einem entsprechenden Befehl ab.
+
Erfahren Sie mehr über das Bearbeiten von ACLs im link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP-Befehlsreferenz"^].

. Fügen Sie die gewünschten Audit Aces hinzu.
. Wenden Sie die aktualisierte ACL mit dem `nfs4_setfacl` Befehl oder dem entsprechenden Befehl auf die Datei oder das Verzeichnis an.

