---
permalink: nas-audit/configure-fpolicy-ssl-connections-concept.html 
sidebar: sidebar 
keywords: additional information, configure, fpolicy, external engines, ssl authenticated, connections 
summary: Einige zusätzliche Informationen sind erforderlich, wenn die externe FPolicy Engine für die Verwendung von SSL bei der Verbindung mit FPolicy Servern konfiguriert werden soll. 
---
= Zusätzliche Informationen zur Konfiguration von ONTAP FPolicy externen Engines zur Verwendung von SSL-authentifizierten Verbindungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Einige zusätzliche Informationen sind erforderlich, wenn die externe FPolicy Engine für die Verwendung von SSL bei der Verbindung mit FPolicy Servern konfiguriert werden soll.



[[ssl-server-authentication]]
== SSL-Serverauthentifizierung

Wenn Sie die externe FPolicy Engine für die SSL-Serverauthentifizierung konfigurieren, muss vor der Erstellung der externen Engine das öffentliche Zertifikat der Zertifizierungsstelle (CA), die das FPolicy Serverzertifikat signiert hat, installiert werden.



[[mutual-authentication]]
== Gegenseitige Authentifizierung

Wenn externe FPolicy Engines so konfiguriert werden, dass sie bei der Verbindung von Storage Virtual Machine (SVM) Daten-LIFs mit externen FPolicy Servern die gegenseitige SSL Authentifizierung verwenden, muss vor der Erstellung der externen Engine das öffentliche Zertifikat der CA, die das FPolicy Serverzertifikat signiert hat, zusammen mit dem öffentlichen Zertifikat und der Schlüsseldatei für die Authentifizierung der SVM installiert werden. Dieses Zertifikat darf nicht gelöscht werden, solange FPolicy Richtlinien das installierte Zertifikat verwenden.

Wird das Zertifikat gelöscht, während FPolicy es für die gegenseitige Authentifizierung bei der Verbindung zu einem externen FPolicy Server verwendet, kann eine deaktivierte FPolicy Richtlinie, die dieses Zertifikat nutzt, nicht wieder aktiviert werden. Die FPolicy Richtlinie kann in diesem Fall auch dann nicht reaktiviert werden, wenn ein neues Zertifikat mit denselben Einstellungen erstellt und auf der SVM installiert wird.

Wenn das Zertifikat gelöscht wurde, ist ein neues Zertifikat zu installieren, neue FPolicy externe Engines zu erstellen, die das neue Zertifikat verwenden, und die neuen externen Engines der FPolicy Richtlinie zuzuordnen, die durch Ändern der FPolicy Richtlinie wieder aktiviert werden soll.



[[install-certificates-for-ssl]]
== Zertifikate für SSL installieren

Das öffentliche Zertifikat der Zertifizierungsstelle, das zum Signieren des FPolicy Serverzertifikats verwendet wird, wird mit dem `security certificate install` Befehl und dem `-type` Parameter, der auf `client-ca` gesetzt ist, installiert. Der für die Authentifizierung der SVM erforderliche private Schlüssel und das öffentliche Zertifikat werden mit dem `security certificate install` Befehl und dem `-type` Parameter, der auf `server` gesetzt ist, installiert.

.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-install.html["Sicherheitszertifikat installieren"^]

