---
permalink: nas-audit/connect-external-fpolicy-servers-task.html 
sidebar: sidebar 
keywords: connect, external fpolicy servers 
summary: Um die Dateiverarbeitung zu aktivieren, kann es erforderlich sein, manuell eine Verbindung zu einem externen FPolicy Server herzustellen, falls die Verbindung zuvor getrennt wurde. Eine Verbindung wird getrennt, nachdem die Server-Zeitüberschreitung erreicht wurde oder aufgrund eines Fehlers. Alternativ kann der Administrator eine Verbindung auch manuell beenden. 
---
= Verbindung zu externen FPolicy Servern in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um die Dateiverarbeitung zu aktivieren, kann es erforderlich sein, manuell eine Verbindung zu einem externen FPolicy Server herzustellen, falls die Verbindung zuvor getrennt wurde. Eine Verbindung wird getrennt, nachdem die Server-Zeitüberschreitung erreicht wurde oder aufgrund eines Fehlers. Alternativ kann der Administrator eine Verbindung auch manuell beenden.

.Über diese Aufgabe
Tritt ein schwerwiegender Fehler auf, kann die Verbindung zum FPolicy Server unterbrochen werden. Nachdem das Problem, das den schwerwiegenden Fehler verursacht hat, behoben wurde, ist eine manuelle Wiederherstellung der Verbindung zum FPolicy Server erforderlich.

.Schritte
. Mit dem  `vserver fpolicy engine-connect` Befehl wird eine Verbindung zum externen FPolicy Server hergestellt.
+
Weitere Informationen zu  `vserver fpolicy engine-connect` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-fpolicy-engine-connect.html["ONTAP-Befehlsreferenz"^].

. Es kann mit dem  `vserver fpolicy show-engine` Befehl überprüft werden, ob der externe FPolicy Server verbunden ist.
+
Weitere Informationen zu  `vserver fpolicy show-engine` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-fpolicy-show-engine.html["ONTAP-Befehlsreferenz"^].


