---
permalink: nas-audit/create-security-traces-concept.html 
sidebar: sidebar 
keywords: considerations, create, security traces 
summary: 'Bei der Erstellung von Sicherheitspuren auf Storage Virtual Machines (SVMs) sollten Sie mehrere Überlegungen in Hinterkopf behalten. Zum Beispiel müssen Sie wissen, auf welchen Protokollen Sie einen Trace erstellen können, welche Sicherheitsstile unterstützt werden und wie viele aktive Traces maximal sind.' 
---
= Überlegungen zum Erstellen von Sicherheitstraces auf ONTAP SVMs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Erstellung von Sicherheitspuren auf Storage Virtual Machines (SVMs) sollten Sie mehrere Überlegungen in Hinterkopf behalten. Zum Beispiel müssen Sie wissen, auf welchen Protokollen Sie einen Trace erstellen können, welche Sicherheitsstile unterstützt werden und wie viele aktive Traces maximal sind.

* Sie können nur Sicherheitspuren auf SVMs erstellen.
* Jeder Eintrag von Security Trace-Filtern ist SVM-spezifisch.
+
Sie müssen die SVM angeben, auf der Sie den Trace ausführen möchten.

* Sie können Filter für die Berechtigungs-Verfolgung von SMB- und NFS-Anfragen hinzufügen.
* Sie müssen den SMB- oder NFS-Server auf der SVM einrichten, auf der Sie Trace-Filter erstellen möchten.
* Sie können Sicherheitspuren für Dateien und Ordner auf NTFS, UNIX und gemischten Volumes und qtrees im Sicherheitsstil erstellen.
* Sie können maximal 10 Filter für die Ablaufverfolgung von Berechtigungen pro SVM hinzufügen.
* Sie müssen beim Erstellen oder Ändern eines Filters eine Filterindex-Nummer angeben.
+
Filter werden in der Reihenfolge der Indexnummer berücksichtigt. Die Kriterien in einem Filter mit einer höheren Indexnummer werden vor den Kriterien mit einer niedrigeren Indexnummer berücksichtigt. Wenn die zurückverfolgende Anfrage mit den Kriterien mehrerer aktivierter Filter übereinstimmt, wird nur der Filter mit der höchsten Indexnummer ausgelöst.

* Nachdem Sie einen Sicherheits-Trace-Filter erstellt und aktiviert haben, müssen Sie einige Datei- oder Ordneranforderungen auf einem Client-System durchführen, um Aktivitäten zu generieren, die der Trace-Filter im Trace-Ergebnisprotokoll erfassen und anmelden kann.
* Sie sollten Filter für Berechtigungs-Tracing hinzufügen, um die Überprüfung des Dateizugriffs oder die Fehlerbehebung zu prüfen.
+
Das Hinzufügen von Berechtigungs-Tracing-Filtern hat eine geringe Auswirkung auf die Controller-Leistung.

+
Wenn Sie mit Überprüfungs- oder Fehlerbehebungsaktivitäten fertig sind, sollten Sie alle Filter für die Berechtigungsprüfung deaktivieren oder entfernen. Darüber hinaus sollten die von Ihnen ausgewählten Filterkriterien so spezifisch wie möglich sein, damit ONTAP keine große Anzahl von Trace-Ergebnissen an das Protokoll sendet.


