---
permalink: nas-audit/create-fpolicy-event-task.html 
sidebar: sidebar 
keywords: creating, fpolicy event 
summary: Wenn Sie eine FPolicy-Konfiguration erstellen, müssen Sie ein FPolicy-Ereignis erstellen. Sie verknüpfen das Ereignis mit der FPolicy, wenn es erstellt wird. Ein Ereignis definiert, welches Protokoll überwacht werden soll und welche Dateizugriffsereignisse überwacht und gefiltert werden müssen. 
---
= Erstellen Sie das FPolicy-Ereignis
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie eine FPolicy-Konfiguration erstellen, müssen Sie ein FPolicy-Ereignis erstellen. Sie verknüpfen das Ereignis mit der FPolicy, wenn es erstellt wird. Ein Ereignis definiert, welches Protokoll überwacht werden soll und welche Dateizugriffsereignisse überwacht und gefiltert werden müssen.

.Bevor Sie beginnen
Füllen Sie das FPolicy Event-Arbeitsblatt aus.

.Schritte
. Erstellen Sie das FPolicy-Ereignis mit `vserver fpolicy policy event create` Befehl.
+
`vserver fpolicy policy event create -vserver-name vs1.example.com -event-name event1 -protocol cifs -file-operations open,close,read,write`

. Überprüfen Sie die FPolicy-Event-Konfiguration mit `vserver fpolicy policy event show` Befehl.
+
`vserver fpolicy policy event show -vserver vs1.example.com`

+
[listing]
----

                  Event               File                    Is Volume
Vserver           Name      Protocols Operations    Filters   Operation
---------------   --------- --------- ------------- --------- ------------
vs1.example.com   event1    cifs      open, close,  -         false
                                      read, write
----

