---
permalink: nas-audit/display-fpolicy-passthrough-read-connection-task.html 
sidebar: sidebar 
keywords: display, information, fpolicy, passthrough-read, connection status 
summary: 'Sie können Informationen über den FPolicy Passthrough-Read-Verbindungsstatus zu externen FPolicy Servern (FPolicy-Server) für das Cluster oder für eine angegebene Storage Virtual Machine (SVM) anzeigen. Diese Informationen können Ihnen dabei helfen zu bestimmen, welche FPolicy-Server über Pass-Read-Datenverbindungen verfügen und für welche FPolicy-Server die Passthrough-Read-Verbindung getrennt haben.' 
---
= Zeigen Sie Informationen zum Verbindungsstatus der FPolicy-Durchleseverbindung an
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Informationen über den FPolicy Passthrough-Read-Verbindungsstatus zu externen FPolicy Servern (FPolicy-Server) für das Cluster oder für eine angegebene Storage Virtual Machine (SVM) anzeigen. Diese Informationen können Ihnen dabei helfen zu bestimmen, welche FPolicy-Server über Pass-Read-Datenverbindungen verfügen und für welche FPolicy-Server die Passthrough-Read-Verbindung getrennt haben.

Wenn Sie keinen Parameter angeben, werden mit dem Befehl die folgenden Informationen angezeigt:

* SVM-Name
* FPolicy-Name
* Node-Name
* FPolicy-Server-IP-Adresse
* FPolicy-Verbindungsstatus beim Passthrough-Lesen


Zusätzlich zum Anzeigen von Informationen über FPolicy-Verbindungen auf dem Cluster oder einer bestimmten SVM können Sie mit Befehlsparametern die Ausgabe des Befehls um andere Kriterien filtern.

Sie können den angeben `-instance` Parameter zum Anzeigen detaillierter Informationen zu aufgeführten Richtlinien Alternativ können Sie den verwenden `-fields` Parameter, um nur die angegebenen Felder in der Befehlsausgabe anzuzeigen. Sie können eingeben `?` Nach dem `-fields` Parameter, um herauszufinden, welche Felder Sie verwenden können.

.Schritt
. Zeigen Sie gefilterte Informationen zum Verbindungsstatus zwischen dem Knoten und dem FPolicy-Server mithilfe des entsprechenden Befehls an:
+
[cols="35,65"]
|===


| Wenn Sie Informationen zum Verbindungsstatus anzeigen möchten über... | Geben Sie den Befehl ein... 


 a| 
FPolicy-Verbindungsstatus für Passthrough-Lesevorgang für das Cluster
 a| 
`vserver fpolicy show-passthrough-read-connection`



 a| 
FPolicy-Verbindungsstatus für Passthrough-Leseverbindungen für eine angegebene SVM
 a| 
`vserver fpolicy show-passthrough-read-connection -vserver vserver_name`



 a| 
FPolicy-Verbindungsstatus für eine bestimmte Richtlinie zum Passthrough-Lesen
 a| 
`vserver fpolicy show-passthrough-read-connection -policy-name policy_name`



 a| 
Detaillierter Verbindungsstatus von FPolicy über Durchleseverbindungen für eine bestimmte Richtlinie
 a| 
`vserver fpolicy show-passthrough-read-connection -policy-name policy_name -instance`



 a| 
FPolicy Passthrough-read Verbindungsstatus für den von Ihnen angegebenen Status
 a| 
`vserver fpolicy show-passthrough-read-connection -policy-name policy_name -server-status status` Für den Serverstatus kann einer der folgenden Werte angezeigt werden:

** `connected`
** `disconnected`


|===


Mit dem folgenden Befehl werden Informationen zu Passthrough-Read-Verbindungen von allen FPolicy-Servern im Cluster angezeigt:

[listing]
----
cluster1::> vserver fpolicy show-passthrough-read-connection
                                            FPolicy           Server
Vserver          Policy Name   Node         Server            Status
---------------  ------------- ------------ ----------------- --------------
vs2.example.com  pol_cifs_2    FPolicy-01   2.2.2.2           disconnected
vs1.example.com  pol_cifs_1    FPolicy-01   1.1.1.1           connected
----
Mit dem folgenden Befehl werden ausführliche Informationen zu PassThrough-Read-Verbindungen von FPolicy-Servern angezeigt, die in der Richtlinie „`pol_cifs_1`“ konfiguriert sind:

[listing]
----
cluster1::> vserver fpolicy show-passthrough-read-connection -policy-name pol_cifs_1 -instance

                                             Node: FPolicy-01
                                          Vserver: vs1.example.com
                                           Policy: pol_cifs_1
                                           Server: 1.1.1.1
                Session ID of the Control Channel: 8cef052e-2502-11e3-88d4-123478563412
                                    Server Status: connected
      Time Passthrough Read Channel was Connected: 9/24/2013 10:17:45
   Time Passthrough Read Channel was Disconnected: -
Reason for Passthrough Read Channel Disconnection: none
----