---
permalink: nas-audit/display-audit-config-task.html 
sidebar: sidebar 
keywords: display, information, audit configurations 
summary: Sie können Informationen zu Überwachungskonfigurationen anzeigen. Diese Informationen unterstützen Sie bei der Ermittlung der gewünschten Konfiguration für die jeweilige SVM. Mit den angezeigten Informationen können Sie auch überprüfen, ob eine Überwachungskonfiguration aktiviert ist. 
---
= Zeigt Informationen zu Überwachungskonfigurationen an
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Informationen zu Überwachungskonfigurationen anzeigen. Diese Informationen unterstützen Sie bei der Ermittlung der gewünschten Konfiguration für die jeweilige SVM. Mit den angezeigten Informationen können Sie auch überprüfen, ob eine Überwachungskonfiguration aktiviert ist.

Sie können ausführliche Informationen zum Auditing von Konfigurationen auf allen SVMs anzeigen oder Sie können durch Angabe optionaler Parameter anpassen, welche Informationen in der Ausgabe angezeigt werden. Wenn Sie keinen der optionalen Parameter angeben, wird Folgendes angezeigt:

* SVM-Name, auf den die Audit-Konfiguration zutrifft
* Der Prüfstatus, der sein kann `true` Oder `false`
+
Wenn der Prüfstatus lautet `true`, Prüfung ist aktiviert. Wenn der Prüfstatus lautet `false`, Prüfung ist deaktiviert.

* Die Kategorien der zu prüfenden Ereignisse
* Das Format des Prüfprotokolls
* Das Zielverzeichnis, in dem das Audit-Subsystem konsolidierte und konvertierte Audit-Protokolle speichert


.Schritt
. Zeigen Sie Informationen über die Überwachungskonfiguration mithilfe des an `vserver audit show` Befehl.
+
Weitere Informationen zur Verwendung des Befehls finden Sie in den man-Pages.



Im folgenden Beispiel wird eine Zusammenfassung der Audit-Konfiguration für alle SVMs angezeigt:

[listing]
----
cluster1::> vserver audit show

 Vserver     State  Event Types Log Format Target Directory
 ----------- ------ ----------- ---------- --------------------
 vs1         false  file-ops    evtx       /audit_log
----
Im folgenden Beispiel werden alle Audit-Konfigurationsinformationen für alle SVMs in Listenform angezeigt:

[listing]
----
cluster1::> vserver audit show -instance

                             Vserver: vs1
                      Auditing state: true
                Log Destination Path: /audit_log
       Categories of Events to Audit: file-ops
                          Log Format: evtx
                 Log File Size Limit: 100MB
        Log Rotation Schedule: Month: -
  Log Rotation Schedule: Day of Week: -
          Log Rotation Schedule: Day: -
         Log Rotation Schedule: Hour: -
       Log Rotation Schedule: Minute: -
                  Rotation Schedules: -
            Log Files Rotation Limit: 0
----