---
permalink: nas-audit/display-security-trace-results-task.html 
sidebar: sidebar 
keywords: display, security trace results 
summary: Sie können die Ergebnisse der Sicherheitsverfolgung anzeigen, die für Dateivorgänge generiert wurden, die den Sicherheitsverfolgungsfiltern entsprechen. Die Ergebnisse können zur Validierung Ihrer Dateizugriffssicherheitskonfiguration oder zur Fehlerbehebung bei SMB- und NFS-Dateizugriffsproblemen verwendet werden. 
---
= Anzeige der Sicherheitsverfolgungsergebnisse in ONTAP SVMs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Ergebnisse der Sicherheitsverfolgung anzeigen, die für Dateivorgänge generiert wurden, die den Sicherheitsverfolgungsfiltern entsprechen. Die Ergebnisse können zur Validierung Ihrer Dateizugriffssicherheitskonfiguration oder zur Fehlerbehebung bei SMB- und NFS-Dateizugriffsproblemen verwendet werden.

.Bevor Sie beginnen
Ein aktivierter Sicherheitstrace-Filter muss vorhanden sein und es müssen Vorgänge von einem SMB- oder NFS-Client durchgeführt worden sein, der dem Sicherheitstrace-Filter entspricht, um Sicherheitstrace-Ergebnisse zu generieren.

.Über diese Aufgabe
Sie können eine Zusammenfassung aller Sicherheitstrace-Ergebnisse anzeigen oder die angezeigten Informationen durch Angabe optionaler Parameter anpassen. Dies kann hilfreich sein, wenn die Sicherheitstrace-Ergebnisse eine große Anzahl von Datensätzen enthalten.

Wenn Sie keinen der optionalen Parameter angeben, wird Folgendes angezeigt:

* Name der Storage Virtual Machine (SVM)
* Knotenname
* Sicherheits-Trace-Indexnummer
* Sicherheitsstil
* Pfad
* Grund
* Benutzername
+
Der Benutzername wird abhängig von der Konfiguration des Trace-Filters angezeigt:

+
[cols="40,60"]
|===


| Wenn der Filter konfiguriert ist... | Dann... 


 a| 
Mit einem UNIX-Benutzernamen
 a| 
Das Ergebnis der Sicherheitsüberwachung zeigt den UNIX-Benutzernamen an.



 a| 
Mit einem Windows-Benutzernamen
 a| 
Das Ergebnis der Sicherheitsüberwachung zeigt den Windows-Benutzernamen an.



 a| 
Ohne Benutzernamen
 a| 
Das Ergebnis der Sicherheitsüberwachung zeigt den Windows-Benutzernamen an.

|===


Sie können die Ausgabe mithilfe optionaler Parameter anpassen. Zu den optionalen Parametern, mit denen Sie die in der Befehlsausgabe zurückgegebenen Ergebnisse eingrenzen können, gehören unter anderem die folgenden:

[cols="35,65"]
|===


| Optionaler Parameter | Beschreibung 


 a| 
`-fields` `field_name`, ...
 a| 
Zeigt die Ausgabe in den von Ihnen ausgewählten Feldern an. Sie können diesen Parameter entweder allein oder in Kombination mit anderen optionalen Parametern verwenden.



 a| 
`-instance`
 a| 
Zeigt detaillierte Informationen zu Security Trace-Ereignissen an. Mit diesem Parameter und weiteren optionalen Parametern werden detaillierte Informationen zu bestimmten Filterergebnissen angezeigt.



 a| 
`-node` `node_name`
 a| 
Zeigt nur Informationen zu Ereignissen auf dem angegebenen Knoten an.



 a| 
`-vserver` `vserver_name`
 a| 
Zeigt nur Informationen über Ereignisse auf der angegebenen SVM an.



 a| 
`-index` `integer`
 a| 
Zeigt Informationen zu den Ereignissen an, die durch den Filter entsprechend der angegebenen Indexnummer aufgetreten sind.



 a| 
`-client-ip` `IP_address`
 a| 
Zeigt Informationen zu den Ereignissen, die infolge des Dateizugriffs von der angegebenen Client-IP-Adresse aufgetreten sind.



 a| 
`-path` `path`
 a| 
Zeigt Informationen zu den Ereignissen an, die infolge des Dateizugriffs auf den angegebenen Pfad aufgetreten sind.



 a| 
`-user-name` `user_name`
 a| 
Zeigt Informationen zu den Ereignissen an, die infolge des Dateizugriffs durch den angegebenen Windows- oder UNIX-Benutzer aufgetreten sind.



 a| 
`-security-style` `security_style`
 a| 
Zeigt Informationen über die Ereignisse an, die auf Dateisystemen mit dem angegebenen Sicherheitsstil aufgetreten sind.

|===
Weitere Informationen zu anderen optionalen Parametern finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP-Befehlsreferenz"^].

.Schritt
. Sicherheits-Trace-Filter-Ergebnisse werden mit dem  `vserver security trace trace-result show` Befehl angezeigt.
+
`vserver security trace trace-result show -user-name domain\user`

+
[listing]
----
Vserver: vs1

Node     Index   Filter Details         Reason
-------- ------- ---------------------  -----------------------------
node1    3       User:domain\user       Access denied by explicit ACE
                 Security Style:mixed
                 Path:/dir1/dir2/

node1    5       User:domain\user       Access denied by explicit ACE
                 Security Style:unix
                 Path:/dir1/
----

