---
permalink: nas-audit/enable-fpolicy-policy-task.html 
sidebar: sidebar 
keywords: enable, fpolicy policy 
summary: Nachdem Sie eine FPolicy-Konfiguration durchlaufen haben, aktivieren Sie die FPolicy. Durch das Aktivieren der Richtlinie wird die Priorität festgelegt und die Dateizugriffsüberwachung für die Richtlinie gestartet. 
---
= Aktivieren Sie ONTAP FPolicy-Richtlinien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie eine FPolicy-Konfiguration durchlaufen haben, aktivieren Sie die FPolicy. Durch das Aktivieren der Richtlinie wird die Priorität festgelegt und die Dateizugriffsüberwachung für die Richtlinie gestartet.

.Bevor Sie beginnen
Die FPolicy muss mit einer zugeordneten externen Engine existieren (wenn die Richtlinie zur Verwendung externer FPolicy-Server konfiguriert ist) und über mindestens ein damit verbundener FPolicy-Ereignis verfügen. Der Richtlinienumfang von FPolicy muss vorhanden sein und der FPolicy zugewiesen werden.

.Über diese Aufgabe
Die Priorität wird verwendet, wenn mehrere Richtlinien auf der Storage Virtual Machine (SVM) aktiviert sind und mehr als eine Richtlinie dasselbe Ereignis für den Dateizugriff abonniert hat. Richtlinien, die die native Engine-Konfiguration verwenden, haben für jede andere Engine eine höhere Priorität als Richtlinien, unabhängig von der ihnen bei der Aktivierung der Richtlinie zugewiesenen Sequenznummer.

[NOTE]
====
Eine Richtlinie kann auf der Admin-SVM nicht aktiviert werden.

====
.Schritte
. Aktivieren Sie die FPolicy-Richtlinie mit dem `vserver fpolicy enable` Befehl.
+
`vserver fpolicy enable -vserver-name vs1.example.com -policy-name policy1 -sequence-number 1`

. Überprüfen Sie mit dem `vserver fpolicy show` Befehl, ob die FPolicy-Richtlinie aktiviert ist.
+
`vserver fpolicy show -vserver vs1.example.com`

+
[listing]
----

                                   Sequence
Vserver          Policy Name         Number  Status   Engine
---------------  ----------------- --------  -------- ---------
vs1.example.com  policy1                  1  on       engine1
----

