---
permalink: nas-audit/file-directory-access-events-audited-reference.html 
sidebar: sidebar 
keywords: nfs file, directory access events, audited 
summary: ONTAP kann bestimmte NFS-Datei- und Verzeichniszugriffsereignisse protokollieren. Es ist hilfreich zu wissen, welche Zugriffsereignisse protokolliert werden können, wenn die Ergebnisse der konvertierten Audit-Ereignisprotokolle interpretiert werden. 
---
= Informationen zur ONTAP Überwachung von NFS-Datei- und Verzeichniszugriffsereignissen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP kann bestimmte NFS-Datei- und Verzeichniszugriffsereignisse protokollieren. Es ist hilfreich zu wissen, welche Zugriffsereignisse protokolliert werden können, wenn die Ergebnisse der konvertierten Audit-Ereignisprotokolle interpretiert werden.

Sie können die folgenden NFS-Datei- und Verzeichniszugriffsereignisse prüfen:

* LESEN
* OFFEN
* SCHLIESSEN
* READDIR
* SCHREIBEN
* SETATTR
* ERSTELLEN
* Link
* OPENATTR
* ENTFERNEN
* GETATTR
* VERIFIZIEREN
* NVERIFY
* UMBENENNEN


Um NFS RENAME-Ereignisse zuverlässig zu protokollieren, sollten Überwachungs-ACEs auf Verzeichnisse anstatt auf Dateien festgelegt werden, da die Dateiberechtigungen bei einer RENAME-Operation nicht überprüft werden, wenn die Verzeichnisberechtigungen ausreichend sind.
