---
permalink: nas-audit/fpolicy-external-engine-config-worksheet-reference.html 
sidebar: sidebar 
keywords: complete, fpolicy, external engine, configuration, worksheet 
summary: Mit diesem Arbeitsblatt können Sie die Werte aufzeichnen, die Sie während der Konfiguration der externen FPolicy Engine benötigen. Wenn ein Parameterwert erforderlich ist, müssen Sie vor der Konfiguration der externen Engine festlegen, welchen Wert für diese Parameter verwendet werden soll. 
---
= Vollständige Arbeitsblätter zur Konfiguration der externen ONTAP FPolicy-Engine
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit diesem Arbeitsblatt können Sie die Werte aufzeichnen, die Sie während der Konfiguration der externen FPolicy Engine benötigen. Wenn ein Parameterwert erforderlich ist, müssen Sie vor der Konfiguration der externen Engine festlegen, welchen Wert für diese Parameter verwendet werden soll.



== Informationen für eine grundlegende externe Engine-Konfiguration

Sie sollten aufzeichnen, ob Sie die einzelnen Parametereinstellungen in die externe Engine-Konfiguration aufnehmen möchten, und dann den Wert für die Parameter notieren, die Sie einbeziehen möchten.

[cols="40,20,20,20"]
|===


| Informationstyp | Erforderlich | Einschließlich | Ihre Werte 


 a| 
Name der Storage Virtual Machine (SVM
 a| 
Ja.
 a| 
Ja.
 a| 



 a| 
Motorname
 a| 
Ja.
 a| 
Ja.
 a| 



 a| 
Primäre FPolicy-Server
 a| 
Ja.
 a| 
Ja.
 a| 



 a| 
Port-Nummer
 a| 
Ja.
 a| 
Ja.
 a| 



 a| 
Sekundäre FPolicy Server
 a| 
Nein
 a| 
 a| 



 a| 
Externer Motortyp
 a| 
Nein
 a| 
 a| 



 a| 
SSL-Option zur Kommunikation mit externem FPolicy-Server
 a| 
Ja.
 a| 
Ja.
 a| 



 a| 
FQDN des Zertifikats oder benutzerdefinierter allgemeiner Name
 a| 
Nein
 a| 
 a| 



 a| 
Seriennummer des Zertifikats
 a| 
Nein
 a| 
 a| 



 a| 
Zertifizierungsstelle
 a| 
Nein
 a| 
 a| 

|===


== Informationen für erweiterte externe Motorparameter

Um eine externe Engine mit erweiterten Parametern zu konfigurieren, müssen Sie den Konfigurationsbefehl im erweiterten Berechtigungsmodus eingeben.

[cols="40,20,20,20"]
|===


| Informationstyp | Erforderlich | Einschließlich | Ihre Werte 


 a| 
Zeitüberschreitung beim Abbrechen einer Anfrage
 a| 
Nein
 a| 
 a| 



 a| 
Timeout beim Abbrechen einer Anfrage
 a| 
Nein
 a| 
 a| 



 a| 
Intervall für das Senden von Statusanforderungen
 a| 
Nein
 a| 
 a| 



 a| 
Maximale offene Anfragen auf dem FPolicy-Server
 a| 
Nein
 a| 
 a| 



 a| 
Timeout zum Trennen eines nicht ansprechenden FPolicy-Servers
 a| 
Nein
 a| 
 a| 



 a| 
Intervall für das Senden von Keep-Alive-Nachrichten an den FPolicy-Server
 a| 
Nein
 a| 
 a| 



 a| 
Maximale Anzahl von Verbindungsversuchen
 a| 
Nein
 a| 
 a| 



 a| 
Empfangspuffgröße
 a| 
Nein
 a| 
 a| 



 a| 
Puffergröße senden
 a| 
Nein
 a| 
 a| 



 a| 
Zeitüberschreitung beim Spülen einer Sitzungs-ID während der erneuten Verbindung
 a| 
Nein
 a| 
 a| 

|===