---
permalink: nas-audit/fpolicy-scope-worksheet-reference.html 
sidebar: sidebar 
keywords: complete, fpolicy, scope, worksheet 
summary: Mit diesem Arbeitsblatt können Sie die Werte aufzeichnen, die Sie während der Konfiguration des FPolicy Scope benötigen. Wenn ein Parameterwert erforderlich ist, müssen Sie vor der Konfiguration des FPolicy-Umfangs festlegen, welchen Wert für diese Parameter verwendet werden soll. 
---
= Vollständige Arbeitsblätter zum ONTAP FPolicy-Bereich
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit diesem Arbeitsblatt können Sie die Werte aufzeichnen, die Sie während der Konfiguration des FPolicy Scope benötigen. Wenn ein Parameterwert erforderlich ist, müssen Sie vor der Konfiguration des FPolicy-Umfangs festlegen, welchen Wert für diese Parameter verwendet werden soll.

Sie sollten aufzeichnen, ob die einzelnen Parameter in die FPolicy Scope-Konfiguration einbezogen werden sollen, und dann den Wert für die Parameter notieren, die Sie einbeziehen möchten.

[cols="40,20,20,20"]
|===


| Informationstyp | Erforderlich | Einschließlich | Ihre Werte 


 a| 
Name der Storage Virtual Machine (SVM
 a| 
Ja.
 a| 
Ja.
 a| 



 a| 
Name der Richtlinie
 a| 
Ja.
 a| 
Ja.
 a| 



 a| 
Einzuschließen von Freigaben
 a| 
Nein
 a| 
 a| 



 a| 
Auszuschließende Freigaben
 a| 
Nein
 a| 
 a| 



 a| 
Volumes die einbezogen werden sollen
 a| 
Nein
 a| 
 a| 



 a| 
Auszuschließende Volumes
 a| 
Nein
 a| 
 a| 



 a| 
Richtlinien exportieren, die einbezogen werden sollen
 a| 
Nein
 a| 
 a| 



 a| 
Auszuschließende Richtlinien exportieren
 a| 
Nein
 a| 
 a| 



 a| 
Einzuschließen von Dateierweiterungen
 a| 
Nein
 a| 
 a| 



 a| 
Auszuschließende Dateierweiterung
 a| 
Nein
 a| 
 a| 



 a| 
Ist die Dateierweiterung für das Verzeichnis aktiviert?
 a| 
Nein
 a| 
 a| 

|===