---
permalink: nas-audit/index.html 
sidebar: sidebar 
keywords: file, access, auditing, audit, smb, cifs, nfs, fpolicy, udit, nas, events, svms 
summary: Zudem können die mit ONTAP verfügbaren Auditing-Funktionen für Dateizugriffe über SMB und NFS verwendet werden, beispielsweise von nativen Audits und Dateirichtlinien-Management über FPolicy. 
---
= SMB- und NFS-Auditing und Sicherheits-Tracing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zudem können die mit ONTAP verfügbaren Auditing-Funktionen für Dateizugriffe über SMB und NFS verwendet werden, beispielsweise von nativen Audits und Dateirichtlinien-Management über FPolicy.

Unter den folgenden Umständen sollten Audits für SMB- und NFS-Dateizugriffe entworfen und implementiert werden:

* Der grundlegende Dateizugriff über SMB und NFS wurde konfiguriert.
* Sie möchten eine Überwachungskonfiguration mit einer der folgenden Methoden erstellen und verwalten:
+
** Native ONTAP Funktionalität
** Externe FPolicy Server






== Prüfung von NAS-Ereignissen auf SVMs

Das Auditing von NAS-Ereignissen ist eine Sicherheitsmaßnahme, mit der Sie bestimmte SMB- und NFS-Ereignisse auf Storage Virtual Machines (SVMs) nachverfolgen und protokollieren können. So können Sie potenzielle Sicherheitsprobleme verfolgen und Sicherheitsverletzungen nachweisen. Außerdem können Sie zentrale Active Directory-Zugriffsrichtlinien erstellen und prüfen, um zu sehen, welche Ergebnisse diese implementieren würden.



=== SMB-Ereignisse

Sie können die folgenden Ereignisse prüfen:

* SMB-Datei- und Ordnerzugriff
+
SMB-Datei- und Ordnerzugriffe auf Objekte prüfen, die in FlexVol Volumes gespeichert sind, die zu prüfenden SVMs gehören.

* SMB-Anmeldung und -Abmeldung
+
Sie können SMB-Anmeldeereignisse und Abmeldeereignisse für SMB-Server auf SVMs prüfen.

* Staging von zentralen Zugriffsrichtlinien
+
Sie können den effektiven Zugriff auf Objekte auf SMB-Servern anhand von Berechtigungen überprüfen, die anhand vorgeschlagener, zentraler Zugriffsrichtlinien angewendet werden. Das Auditing durch die Durchführung von zentralen Zugriffsrichtlinien ermöglicht es Ihnen, die Auswirkungen zentraler Zugriffsrichtlinien zu sehen, bevor sie bereitgestellt werden.

+
Das Auditing von zentralen Zugriffsrichtlinien-Staging wird über Active Directory GPOs eingerichtet. Die SVM-Auditing-Konfiguration muss jedoch für das Auditing von Staging von zentralen Zugriffsrichtlinien konfiguriert werden.

+
Obwohl Sie die zentrale Zugriffsrichtlinien-Staging in der Überwachungskonfiguration aktivieren können, ohne die dynamische Zugriffskontrolle auf dem SMB-Server zu aktivieren, werden zentrale Zugriffsrichtlinien-Staging-Ereignisse nur erzeugt, wenn Dynamic Access Control aktiviert ist. Die dynamische Zugriffskontrolle wird über eine SMB-Serveroption aktiviert. Sie ist standardmäßig nicht aktiviert.





=== NFS-Ereignisse

Sie können Datei- und Verzeichnisereignisse prüfen, indem Sie die NFSv4-ACL auf Objekten verwenden, die auf SVMs gespeichert sind.
