---
permalink: nas-audit/interpret-security-trace-results-concept.html 
sidebar: sidebar 
keywords: interpret, security trace, results 
summary: Die Ergebnisse von Sicherheitspuren geben den Grund an, warum eine Anfrage zugelassen oder abgelehnt wurde. Die Ausgabe zeigt das Ergebnis als eine Kombination aus dem Grund für das Zulassen oder Ablehnen des Zugriffs und dem Ort innerhalb des Zugriffspunts an, auf dem der Zugriff erlaubt oder verweigert wird. Anhand der Ergebnisse können Sie bestimmen, warum Aktionen zulässig sind oder nicht. 
---
= Die Ergebnisse der Sicherheitsverfolgung interpretieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Ergebnisse von Sicherheitspuren geben den Grund an, warum eine Anfrage zugelassen oder abgelehnt wurde. Die Ausgabe zeigt das Ergebnis als eine Kombination aus dem Grund für das Zulassen oder Ablehnen des Zugriffs und dem Ort innerhalb des Zugriffspunts an, auf dem der Zugriff erlaubt oder verweigert wird. Anhand der Ergebnisse können Sie bestimmen, warum Aktionen zulässig sind oder nicht.



== Informationen zu den Listen der Ergebnistypen und Filterdetails finden

Sie finden die Listen der Ergebnistypen und Filterdetails, die in die Security-Trace-Ergebnisse in den man-Pages für den `vserver security trace trace-result show` Befehl aufgenommen werden können.

.Beispiel für die Ausgabe aus dem `Reason` Feld in einem `Allow` Ergebnistyp
Im Folgenden finden Sie ein Beispiel für die Ausgabe aus dem `Reason` Feld, das im Protokoll der Trace-Ergebnisse in einem `Allow` Ergebnistyp angezeigt wird:

[listing]
----
Access is allowed because SMB implicit permission grants requested
access while opening existing file or directory.
----
[listing]
----
Access is allowed because NFS implicit permission grants requested
access while opening existing file or directory.
----
.Beispiel für die Ausgabe aus dem `Reason` Feld in einem `Allow` Ergebnistyp
Im Folgenden finden Sie ein Beispiel für die Ausgabe aus dem `Reason` Feld, das im Protokoll der Trace-Ergebnisse in einem `Deny` Ergebnistyp angezeigt wird:

[listing]
----
Access is denied. The requested permissions are not granted by the
ACE while checking for child-delete access on the parent.
----
.Beispiel für eine Ausgabe aus dem `Filter details` Feld
Im Folgenden finden Sie ein Beispiel für die Ausgabe aus dem `Filter details` Feld im Protokoll der Trace-Ergebnisse, in dem der effektive Sicherheitsstil des Dateisystems aufgeführt ist, das Dateien und Ordner enthält, die den Filterkriterien entsprechen:

[listing]
----
Security Style: MIXED and ACL
----