---
permalink: nas-audit/manage-audit-policy-change-event-concept.html 
sidebar: sidebar 
keywords: manage, audit-policy-change, event 
summary: 'Wenn ein Ereignis für die Änderung von Audit-Richtlinien für eine Storage Virtual Machine (SVM) konfiguriert und ein Audit aktiviert ist, werden Audit-Ereignisse generiert. Die Ereignisse für die Änderung von Audit-Richtlinien werden generiert, wenn eine Audit-Richtlinie mithilfe von Befehlen zum vserver-Audit geändert wird.' 
---
= Management von Änderungs- und Audit-Richtlinien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ein Ereignis für die Änderung von Audit-Richtlinien für eine Storage Virtual Machine (SVM) konfiguriert und ein Audit aktiviert ist, werden Audit-Ereignisse generiert. Die Ereignisse `vserver audit` zur Änderung der Überwachungsrichtlinie werden generiert, wenn eine Überwachungsrichtlinie mit verwandten Befehlen geändert wird.

Das Ereignis „Audit-Policy-change“ mit der Ereignis Event-id 4719 wird immer dann generiert, wenn eine Audit-Richtlinie deaktiviert, aktiviert oder geändert wird. Außerdem wird festgestellt, wann ein Benutzer versucht, die Prüfung für die Tracks zu deaktivieren. Er ist standardmäßig konfiguriert und erfordert zum Deaktivieren Diagnoseberechtigung.

Im folgenden Beispiel wird ein Änderungsereignis für die Audit-Richtlinie mit der generierten ID 4719 angezeigt, wenn ein Audit deaktiviert ist:

[listing]
----
netapp-clus1::*> vserver audit disable -vserver vserver_1
- System
  - Provider
   [ Name]  NetApp-Security-Auditing
   [ Guid]  {3CB2A168-FE19-4A4E-BDAD-DCF422F13473}
   EventID 4719
   EventName Audit Disabled
   ...
   ...
  SubjectUserName admin
  SubjectUserSid 65533-1001
  SubjectDomainName ~
  SubjectIP console
  SubjectPort
----