---
permalink: nas-audit/manage-file-share-event-concept.html 
sidebar: sidebar 
keywords: manage, file-share, event 
summary: 'Wenn ein Dateifreigabe-Ereignis für eine Storage Virtual Machine (SVM) konfiguriert ist und ein Audit aktiviert ist, werden Audit-Ereignisse generiert. Die Dateifreigabe-Ereignisse werden generiert, wenn die CIFS-Netzwerkfreigabe mithilfe von vserver cifs Share-Befehlen geändert wird.' 
---
= Verwalten von ONTAP-Ereignissen mit Dateifreigabe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ein Dateifreigabe-Ereignis für eine Storage Virtual Machine (SVM) konfiguriert ist und ein Audit aktiviert ist, werden Audit-Ereignisse generiert. Die Dateifreigabeereignisse werden generiert, wenn die SMB-Netzwerkfreigabe mit `vserver cifs share` verwandten Befehlen geändert wird.

Die Dateifreigabe-Ereignisse mit den Ereignis-ids 5142, 5143 und 5144 werden generiert, wenn eine SMB-Netzwerkfreigabe für die SVM hinzugefügt, geändert oder gelöscht wird. Die Konfiguration der SMB-Netzwerkfreigabe wird über die `cifs share access control create|modify|delete` Befehle geändert.

Im folgenden Beispiel wird ein Dateifreigabe-Ereignis mit der ID 5143 erzeugt, wenn ein Freigabetobjekt namens 'Audit_dest' erstellt wird:

[listing]
----
netapp-clus1::*> cifs share create -share-name audit_dest -path /audit_dest
- System
  - Provider
   [ Name]  NetApp-Security-Auditing
   [ Guid]  {3CB2A168-FE19-4A4E-BDAD-DCF422F13473}
   EventID 5142
   EventName Share Object Added
   ...
   ...
  ShareName audit_dest
  SharePath /audit_dest
  ShareProperties oplocks;browsable;changenotify;show-previous-versions;
  SD O:BAG:S-1-5-21-2447422786-1297661003-4197201688-513D:(A;;FA;;;WD)
----