---
permalink: nas-audit/manage-authorization-policy-change-event-concept.html 
sidebar: sidebar 
keywords: manage, authorization-policy-change, event 
summary: 'Wenn ein Ereignis zur Änderung von Autorisierungsrichtlinien für eine Storage Virtual Machine (SVM) konfiguriert ist und ein Audit aktiviert ist, werden Audit-Ereignisse generiert.' 
---
= Verwaltung von ONTAP-Ereignissen, die sich auf Autorisierungsrichtlinie ändern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ein Ereignis zur Änderung von Autorisierungsrichtlinien für eine Storage Virtual Machine (SVM) konfiguriert ist und ein Audit aktiviert ist, werden Audit-Ereignisse generiert.

Die Ereignisse mit den Ereignis-ids 4704 und 4705 werden generiert, sobald die Autorisierungsrechte für einen SMB-Benutzer und eine SMB-Gruppe erteilt oder widerrufen werden. Die Autorisierungs-Policy-change-Ereignisse werden erzeugt, wenn die Autorisierungsrechte über `vserver cifs users-and-groups privilege` verwandte Befehle zugewiesen oder aufgehoben werden.

Im folgenden Beispiel wird ein Ereignis für die Autorisierungsrichtlinie mit der generierten ID 4704 angezeigt, wenn die Autorisierungsrechte für eine SMB-Benutzergruppe zugewiesen sind:

[listing]
----
netapp-clus1::*> vserver cifs users-and-groups privilege add-privilege -user-or-group-name testcifslocalgroup -privileges *
- System
  - Provider
   [ Name]  NetApp-Security-Auditing
   [ Guid]  {3CB2A168-FE19-4A4E-BDAD-DCF422F13473}
   EventID 4704
   EventName User Right Assigned
   ...
   ...
  TargetUserOrGroupName testcifslocalgroup
  TargetUserOrGroupDomainName NETAPP-CLUS1
  TargetUserOrGroupSid S-1-5-21-2447422786-1297661003-4197201688-1004;
  PrivilegeList SeTcbPrivilege;SeBackupPrivilege;SeRestorePrivilege;SeTakeOwnershipPrivilege;SeSecurityPrivilege;SeChangeNotifyPrivilege;
  TargetType CIFS
----