---
permalink: nas-audit/manual-rotate-audit-event-logs-task.html 
sidebar: sidebar 
keywords: manually, rotate, audit event logs 
summary: 'Bevor Sie die Protokolle der Audit-Ereignisse anzeigen können, müssen die Protokolle in benutzerlesbare Formate konvertiert werden. Wenn Sie die Ereignisprotokolle für eine bestimmte Storage Virtual Machine (SVM) anzeigen möchten, bevor ONTAP das Protokoll automatisch rotiert, können Sie die Überwachungsprotokolle auf einer SVM manuell drehen.' 
---
= Drehen Sie die Überwachungsprotokolle manuell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie die Protokolle der Audit-Ereignisse anzeigen können, müssen die Protokolle in benutzerlesbare Formate konvertiert werden. Wenn Sie die Ereignisprotokolle für eine bestimmte Storage Virtual Machine (SVM) anzeigen möchten, bevor ONTAP das Protokoll automatisch rotiert, können Sie die Überwachungsprotokolle auf einer SVM manuell drehen.

.Schritt
. Drehen Sie die Überwachungsprotokolle mit dem `vserver audit rotate-log` Befehl.
+
`vserver audit rotate-log -vserver vs1`

+
Das Revisionsprotokoll wird im SVM-Audit-Ereignisprotokoll mit dem von der Audit-Konfiguration angegebenen Format gespeichert (`XML` Oder `EVTX`), und kann mit der entsprechenden Anwendung angezeigt werden.


