---
permalink: nas-audit/process-when-reverting-concept.html 
sidebar: sidebar 
keywords: process, revert, cluster 
summary: 'Wenn Sie den Cluster zurücksetzen möchten, sollten Sie auf den ONTAP für den Umkehrprozess achten, wenn es im Cluster Audit-fähige Storage Virtual Machines (SVMs) gibt. Sie müssen bestimmte Aktionen durchführen, bevor Sie den Wechsel rückgängig machen.' 
---
= Auswirkungen des Zurücks des Clusters benennen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie den Cluster zurücksetzen möchten, sollten Sie auf den ONTAP für den Umkehrprozess achten, wenn es im Cluster Audit-fähige Storage Virtual Machines (SVMs) gibt. Sie müssen bestimmte Aktionen durchführen, bevor Sie den Wechsel rückgängig machen.



== Zurücksetzen auf eine Version von ONTAP, die keine Unterstützung für das Auditing von SMB-Anmeldeereignissen und Abmeldungs-Ereignissen sowie von Staging-Ereignissen für zentrale Zugriffsrichtlinien bietet

Clustered Data ONTAP 8.3 unterstützt das Auditing von SMB-Anmeldeereignissen und Abmeldung sowie von zentralen Zugriffs-Policy-Staging-Ereignissen. Wenn Sie zurück zu einer Version von ONTAP wechseln, die diese Ereignistypen nicht unterstützt, und Sie verfügen über Auditing-Konfigurationen, die diese Ereignistypen überwachen, müssen Sie vor dem Zurücksetzen die Prüfungskonfiguration für diese revisionssigemeinsam verwendeten SVMs ändern. Sie müssen die Konfiguration so ändern, dass nur Datei-op-Ereignisse überprüft werden.
