---
permalink: nas-audit/supported-file-operation-filter-fpolicy-smb-concept.html 
sidebar: sidebar 
keywords: list, supported file operation, filter combinations, fpolicy, monitor, smb 
summary: Wenn Sie Ihr FPolicy-Ereignis konfigurieren, müssen Sie beachten, dass nur bestimmte Kombinationen von Dateioperationen und Filtern zur Überwachung von SMB-Dateizugriffsvorgängen unterstützt werden. 
---
= Unterstützte Dateioperationen und Filterkombinationen ONTAP FPolicy-Monitore für SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie Ihr FPolicy-Ereignis konfigurieren, müssen Sie beachten, dass nur bestimmte Kombinationen von Dateioperationen und Filtern zur Überwachung von SMB-Dateizugriffsvorgängen unterstützt werden.

Die folgende Tabelle enthält eine Liste der unterstützten Dateivorgänge und Filterkombinationen für die FPolicy-Überwachung von SMB-Dateizugriffsereignissen:

[cols="30,70"]
|===


| Unterstützte Dateivorgänge | Unterstützte Filter 


 a| 
Schließen
 a| 
Monitor-ads, Offline-Bit, Close-with-Modifizierung, Close-ohne-Änderung, Close-with-Read, Exclude-Verzeichnis



 a| 
Erstellen
 a| 
Monitor-ADS, Offline-Bit



 a| 
Create_dir
 a| 
Derzeit wird kein Filter für diesen Dateivorgang unterstützt.



 a| 
Löschen
 a| 
Monitor-ADS, Offline-Bit



 a| 
Delete_dir
 a| 
Derzeit wird kein Filter für diesen Dateivorgang unterstützt.



 a| 
Getattr
 a| 
Offline-Bit, exclude-dir



 a| 
Offen
 a| 
Monitor-ads, Offline-Bit, open-with-delete-Intent, open-with-write-Intent, exclude-dir



 a| 
Lesen
 a| 
Monitor-ADS, Offline-Bit, First-Read



 a| 
Schreiben
 a| 
Monitor-ads, Offline-Bit, First-Write, Write-with-size-Change



 a| 
Umbenennen
 a| 
Monitor-ADS, Offline-Bit



 a| 
Umbenennen_dir
 a| 
Derzeit wird kein Filter für diesen Dateivorgang unterstützt.



 a| 
Sollwert
 a| 
Monitor-ads, offline-bit, setattr_with_owner_change, setattr_with_Group_change, setattr_with_Mode_change, Setattr_with_sacl_change, setattr_with_dacl_change, setattr_with_modify_time_change, setattr_with_Access_time_change, setattr_with_creation_time_change, Setattr_with_size_change, setattr_with_allokation_size_change, exclude_Directory

|===
Ab ONTAP 9.13.1 können Benutzer Benachrichtigungen für fehlgeschlagene Dateivorgänge erhalten, da sie keine Berechtigungen haben. Die Liste der unterstützten Zugriffsverweigerung Dateioperationen und Filterkombinationen für das FPolicy Monitoring von SMB-Dateizugriffsereignissen ist in der folgenden Tabelle aufgeführt:

[cols="30,70"]
|===


| Unterstützter Zugriff verweigert Dateivorgang | Unterstützte Filter 


 a| 
Offen
 a| 
NA

|===