---
permalink: nas-audit/two-parts-fpolicy-solution-concept.html 
sidebar: sidebar 
keywords: two parts, fpolicy, solution 
summary: Es gibt zwei Teile zu einer FPolicy Lösung. Das ONTAP FPolicy Framework managt Aktivitäten auf dem Cluster und sendet Benachrichtigungen an externe FPolicy Server. Externe FPolicy Server verarbeiten Benachrichtigungen, die von ONTAP FPolicy gesendet werden. 
---
= Was die beiden Teile der FPolicy Lösung sind
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FPolicy ist ein Benachrichtigungs-Framework für den Dateizugriff, mit dem Ereignisse für den Dateizugriff auf Storage Virtual Machines (SVMs) über Partnerlösungen überwacht und gemanagt werden können. Partnerlösungen unterstützen Sie bei der Bewältigung verschiedener Anwendungsfälle wie Daten-Governance und Compliance, Ransomware-Schutz und Datenmobilität.

Zu den Partnerlösungen zählen sowohl von NetApp unterstützte Lösungen von Drittanbietern als auch NetApp Produkte Workload Security und Cloud Data Sense.

Es gibt zwei Teile zu einer FPolicy Lösung. Das ONTAP FPolicy Framework verwaltet Aktivitäten im Cluster und sendet Benachrichtigungen an die Partnerapplikation (auch externe FPolicy Server genannt). Externe FPolicy Server verarbeiten Benachrichtigungen, die von ONTAP FPolicy gesendet werden, um Kundennutzungsfälle zu erfüllen.

Das ONTAP Framework erstellt und pflegt die FPolicy Konfiguration, überwacht Dateiereignisse und sendet Benachrichtigungen an externe FPolicy Server. ONTAP FPolicy bietet die Infrastruktur für die Kommunikation zwischen externen FPolicy Servern und Storage Virtual Machine (SVM) Nodes.

Das FPolicy-Framework stellt eine Verbindung zu externen FPolicy-Servern her und sendet Benachrichtigungen für bestimmte Dateisystemereignisse an die FPolicy-Server, wenn diese Ereignisse als Folge des Client-Zugriffs auftreten. Die externen FPolicy Server verarbeiten die Benachrichtigungen und senden Antworten zurück auf den Knoten. Was als Folge der Benachrichtigungsverarbeitung geschieht, hängt von der Anwendung ab und ob die Kommunikation zwischen Knoten und externen Servern asynchron oder synchron ist.
