---
permalink: nas-audit/two-parts-fpolicy-solution-concept.html 
sidebar: sidebar 
keywords: two parts, fpolicy, solution 
summary: Eine FPolicy Lösung besteht aus zwei Komponenten. Das ONTAP FPolicy Framework verwaltet Aktivitäten im Cluster und sendet Benachrichtigungen an externe FPolicy Server. Externe FPolicy Server verarbeiten die von ONTAP FPolicy gesendeten Benachrichtigungen. 
---
= Informationen zu ONTAP FPolicy Lösungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FPolicy ist ein Dateizugriff Benachrichtigungs-Framework, das zur Überwachung und Verwaltung von Dateizugriffsereignissen auf Storage Virtual Machines (SVMs) mithilfe von Partnerlösungen verwendet wird. Partnerlösungen ermöglichen die Umsetzung verschiedener Anwendungsfälle wie Data Governance und Compliance, Ransomware-Schutz und Datenmobilität.

Zu den Partnerlösungen gehören sowohl von NetApp unterstützte Drittanbieterlösungen als auch die NetApp Produkte Workload Security und NetApp Data Classification.

Eine FPolicy Lösung besteht aus zwei Komponenten. Das ONTAP FPolicy Framework verwaltet Aktivitäten im Cluster und sendet Benachrichtigungen an Partner Application (auch External FPolicy Servers genannt). External FPolicy Servers verarbeiten die von ONTAP FPolicy gesendeten Benachrichtigungen, um die Anwendungsfälle der Kunden zu erfüllen.

Das ONTAP Framework erstellt und verwaltet die FPolicy Konfiguration, überwacht Dateiereignisse und sendet Benachrichtigungen an externe FPolicy Server. ONTAP FPolicy stellt die Infrastruktur bereit, die die Kommunikation zwischen externen FPolicy Servern und Storage Virtual Machine (SVM) Knoten ermöglicht.

Das FPolicy Framework verbindet sich mit externen FPolicy Servern und sendet Benachrichtigungen über bestimmte Dateisystemereignisse an die FPolicy Server, wenn diese Ereignisse durch Clientzugriffe ausgelöst werden. Die externen FPolicy Server verarbeiten die Benachrichtigungen und senden Antworten an den Knoten zurück. Was infolge der Benachrichtigungsverarbeitung geschieht, hängt von der Anwendung und davon ab, ob die Kommunikation zwischen dem Knoten und den externen Servern asynchron oder synchron ist.
