---
permalink: nas-audit/view-audit-event-logs-concept.html 
sidebar: sidebar 
keywords: view, audit event logs 
summary: Mithilfe von Revisionsprotokollen für Ereignisse kann festgestellt werden, ob die Dateisicherheit ausreichend ist und ob unberechtigte Zugriffsversuche auf Dateien und Ordner erfolgt sind. Sie können Revisionsprotokolle für Ereignisse, die im EVTX- oder XML-Dateiformat gespeichert sind, anzeigen und verarbeiten. 
---
= ONTAP Revisionsprotokolle für Ereignisse anzeigen und verarbeiten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mithilfe von Revisionsprotokollen für Ereignisse kann festgestellt werden, ob die Dateisicherheit ausreichend ist und ob unberechtigte Zugriffsversuche auf Dateien und Ordner erfolgt sind. Revisionsprotokolle für Ereignisse, die im  `EVTX`- oder  `XML`-Dateiformat gespeichert sind, können angezeigt und verarbeitet werden.

* `EVTX` Dateiformat
+
Sie können die konvertierten  `EVTX`Revisionsprotokolle als gespeicherte Dateien mit Microsoft Event Viewer öffnen.

+
Es gibt zwei Optionen, die Sie beim Anzeigen von Ereignisprotokollen mit der Ereignisanzeige verwenden können:

+
** Gesamtansicht
+
Für den Ereignisdatensatz werden Informationen angezeigt, die für alle Ereignisse gelten. In dieser Version von ONTAP werden die ereignisspezifischen Daten für den Ereignisdatensatz nicht angezeigt. In der Detailansicht lassen sich ereignisspezifische Daten anzeigen.

** Detailansicht
+
Es stehen eine benutzerfreundliche Ansicht und eine XML-Ansicht zur Verfügung. Die benutzerfreundliche Ansicht und die XML-Ansicht zeigen sowohl die für alle Ereignisse gemeinsamen Informationen als auch die ereignisspezifischen Daten des Ereignisdatensatzes an.



* `XML` Dateiformat
+
Sie können Audit-Ereignisprotokolle  `XML` in Drittanbieteranwendungen anzeigen und verarbeiten, die das  `XML` Dateiformat unterstützen. XML-Anzeigetools können verwendet werden, um die Audit-Protokolle anzuzeigen, sofern Sie über das XML-Schema und Informationen zu den Definitionen der XML-Felder verfügen. Weitere Informationen zum XML-Schema und zu den Definitionen finden Sie in der  https://library.netapp.com/ecm/ecm_get_file/ECMLP2875022["ONTAP Revisionsprotokoll-Schema-Referenz"^].





[[how-active-audit-logs-are-viewed-using-event-viewer]]
== Wie aktive Revisionsprotokolle mit der Ereignisanzeige angezeigt werden

Wenn der Revisionsprotokoll-Konsolidierungsprozess auf dem Cluster ausgeführt wird, fügt der Konsolidierungsprozess neue Einträge an die aktive Revisionsprotokolldatei für audit-aktivierte Storage Virtual Machines (SVMs) an. Auf dieses aktive Revisionsprotokoll kann über eine SMB-Freigabe in der Microsoft Event Viewer zugegriffen und es geöffnet werden.

Zusätzlich zur Anzeige vorhandener Revisionsprotokolle bietet die Ereignisanzeige eine Aktualisierungsoption, mit der der Inhalt im Konsolenfenster aktualisiert werden kann. Ob die neu hinzugefügten Protokolle in der Ereignisanzeige sichtbar sind, hängt davon ab, ob Oplocks für die Freigabe aktiviert sind, die für den Zugriff auf das aktive Revisionsprotokoll verwendet wird.

[cols="30,70"]
|===


| Oplocks Einstellung für die Freigabe | Verhalten 


 a| 
Aktiviert
 a| 
Die Ereignisanzeige öffnet das Protokoll, das die bis zu diesem Zeitpunkt gespeicherten Ereignisse enthält. Der Aktualisierungsvorgang aktualisiert das Protokoll nicht mit neuen Ereignissen, die vom Konsolidierungsprozess hinzugefügt wurden.



 a| 
Deaktiviert
 a| 
Die Ereignisanzeige öffnet das Protokoll, das die bis zu diesem Zeitpunkt gespeicherten Ereignisse enthält. Der Aktualisierungsvorgang aktualisiert das Protokoll mit den vom Konsolidierungsprozess hinzugefügten neuen Ereignissen.

|===
[NOTE]
====
Diese Informationen gelten nur für  `EVTX`Ereignisprotokolle.  `XML`Ereignisprotokolle können über SMB in einem Browser oder über NFS mit einem beliebigen XML-Editor oder Viewer angezeigt werden.

====