---
permalink: san-config/fc-switch-config-best-practices-concept.html 
sidebar: sidebar 
keywords: fc, switch, configuration, best, practices 
summary: Für eine optimale Leistung sind bei der Konfiguration Ihres FC Switch bestimmte Best Practices zu berücksichtigen. 
---
= Bewährte Verfahren zur Konfiguration von FC Switches mit ONTAP Systemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für eine optimale Leistung sind bei der Konfiguration Ihres FC Switch bestimmte Best Practices zu berücksichtigen.

Eine feste Verbindungsgeschwindigkeit ist die beste Vorgehensweise für FC Switch-Konfigurationen, insbesondere für große Fabrics, da sie die beste Leistung bei Fabric-Neuaufbauten bietet und erheblich Zeit sparen kann. Obwohl die automatische Aushandlung die größte Flexibilität bietet, funktioniert die FC Switch-Konfiguration nicht immer wie erwartet und verlängert die gesamte Fabric-Aufbausequenz.

Alle mit dem Fabric verbundenen Switches müssen N_Port ID Virtualisierung (NPIV) unterstützen und NPIV muss aktiviert sein. ONTAP verwendet NPIV, um FC-Ziele für ein Fabric bereitzustellen.

Einzelheiten zu den unterstützten Umgebungen sind in der  https://mysupport.netapp.com/matrix["NetApp Interoperabilitätsmatrix-Tool"^] zu finden.

Best Practices zu FC und iSCSI sind unter  https://www.netapp.com/pdf.html?item=/media/10680-tr4080.pdf["NetApp Technischer Bericht 4080: Bewährte Verfahren für moderne SAN"^] zu finden.
