---
permalink: san-config/fc-target-port-config-recommendations-concept.html 
sidebar: sidebar 
keywords: fc, target, port, configuration, recommendations 
summary: Für optimale Leistung und höchste Verfügbarkeit wird die empfohlene FC-Zielportkonfiguration empfohlen. 
---
= Unterstützte FC-Zielportgeschwindigkeiten für Ihr ONTAP System ermitteln
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FC-Zielports können für das FC-NVMe-Protokoll genauso konfiguriert und verwendet werden wie für das FC-Protokoll.

Für optimale Leistung und höchste Verfügbarkeit wird die empfohlene Zielportkonfiguration, die in  https://hwu.netapp.com["NetApp Hardware Universe"^] für Ihr spezifisches ONTAP System aufgeführt ist, verwendet.

Jeder Onboard FC Port und jeder Erweiterungsadapter Port kann individuell für unterschiedliche, unterstützte Geschwindigkeiten konfiguriert werden. Die unterstützten Geschwindigkeiten variieren je nach ONTAP System und HBAs. Alle von einem Host verwendeten Zielports sollten auf dieselbe Geschwindigkeit eingestellt sein.

Es empfiehlt sich, für alle Ihre Initiator-, Switch- und Zielports eine einheitliche Geschwindigkeit zu konfigurieren. Wenn die Geschwindigkeiten von Port und Initiator unterschiedlich sind und keine gemeinsame Geschwindigkeit ausgehandelt werden kann, kann keine Sitzung hergestellt werden. Die Verwendung der automatischen Aushandlung zur Festlegung der Portgeschwindigkeit wird nicht empfohlen. Die automatische Aushandlung kann den Sitzungsaufbau und die Wiederherstellung nach einer Unterbrechung verlangsamen.

Die unterstützten Geschwindigkeiten sind im NetApp Hardware Universe unter *Unterstützte Adapterkarten* für jedes ONTAP System aufgeführt.

.Schritte
. Zu link:https://hwu.netapp.com["NetApp Hardware Universe"^] wechseln.
. *Produkte* auswählen.
. Unter *Plattformen* den Systemtyp auswählen.
. Wählen Sie Ihr spezifisches System und anschließend Ihre ONTAP Version.
. *Ergebnisse anzeigen* auswählen und dann *Unterstützte Adapterkarten* auswählen.
+
FC-Adapterkarten sind unter *Category* als „Block Access (Target)“ aufgeführt, und die unterstützten Geschwindigkeiten sind unter *Supported Protocol(s)* aufgeführt.


