---
permalink: san-config/fc-target-port-supported-speeds-reference.html 
sidebar: sidebar 
keywords: fc, target, port, supported, speeds 
summary: FC-Ziel-Ports können für die Ausführung mit unterschiedlichen Geschwindigkeiten konfiguriert werden. Sie sollten die Geschwindigkeit des Zielports so einstellen, dass sie mit der Geschwindigkeit des Geräts übereinstimmt, mit dem das Gerät verbunden wird. Alle von einem bestimmten Host verwendeten Ziel-Ports sollten auf dieselbe Geschwindigkeit eingestellt sein. 
---
= Unterstützte Geschwindigkeiten für FC-Zielport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FC-Ziel-Ports können für die Ausführung mit unterschiedlichen Geschwindigkeiten konfiguriert werden. Sie sollten die Geschwindigkeit des Zielports so einstellen, dass sie mit der Geschwindigkeit des Geräts übereinstimmt, mit dem das Gerät verbunden wird. Alle von einem bestimmten Host verwendeten Ziel-Ports sollten auf dieselbe Geschwindigkeit eingestellt sein.

FC-Ziel-Ports können für FC-NVMe-Konfigurationen genau auf die gleiche Weise verwendet werden wie für FC-Konfigurationen.

Sie sollten die Geschwindigkeit des Zielports so einstellen, dass sie mit der Geschwindigkeit des Geräts übereinstimmt, zu dem eine Verbindung hergestellt wird, anstatt die Autonegotiation zu verwenden. Ein Port, der auf die Autonegotiation festgelegt ist, kann nach einer Übernahme/Rückgabe oder einer anderen Unterbrechung länger dauern, bis die Verbindung wiederhergestellt ist.

Die integrierten Ports und Erweiterungsadapter können mit folgenden Geschwindigkeiten konfiguriert werden: Jeder Controller und jeder Erweiterungs-Adapter-Port kann je nach Bedarf individuell für unterschiedliche Geschwindigkeiten konfiguriert werden.

[cols="4*"]
|===
| 4-GB-Ports | 8-GB-Ports | 16-GB-Ports | 32-GB-Ports 


 a| 
* 4 Gb
* 2 Gb
* 1 Gb

 a| 
* 8 Gb
* 4 Gb
* 2 Gb

 a| 
* 16 Gb
* 8 Gb
* 4 Gb

 a| 
* 32 Gb
* 16 Gb
* 8 Gb


|===
[NOTE]
====
UTA2-Ports können bei Bedarf einen 8-GB-SFP+-Adapter verwenden, um Geschwindigkeiten von 8, 4 und 2 GB zu unterstützen.

====