---
permalink: san-config/index.html 
sidebar: sidebar 
keywords: san, configure, configuration, fc, iscsi, nvme, host, fcoe, topology, topologies, connect, connecting, limits 
summary: Unterstützte FC-NVMe-, FC-, iSCSI- und FCoE-Topologien zur Verbindung von Host-Computern mit Nodes sowie unterstützte Grenzwerte für SAN-Komponenten. 
---
= Erfahren Sie mehr über die ONTAP-SAN-Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Storage Area Network (SAN) besteht aus einer Storage-Lösung, die über ein SAN-Transportprotokoll wie iSCSI oder FC mit Hosts verbunden ist. Sie können Ihr SAN so konfigurieren, dass Ihre Speicherlösung über einen oder mehrere Switches mit Ihren Hosts verbunden wird. Wenn Sie iSCSI verwenden, können Sie Ihr SAN auch so konfigurieren, dass Ihre Speicherlösung ohne einen Switch direkt an Ihren Host angeschlossen wird.

In einem SAN können mehrere Hosts mit verschiedenen Betriebssystemen, wie Windows, Linux oder UNIX, gleichzeitig auf die Storage-Lösung zugreifen. Mit link:../san-admin/selective-lun-map-concept.html["Selektive LUN-Zuordnung"] und können link:../san-admin/create-port-sets-binding-igroups-task.html["Portsätze"]Sie den Datenzugriff zwischen den Hosts und dem Speicher einschränken.

Bei iSCSI wird die Netzwerktopologie zwischen der Speicherlösung und den Hosts als Netzwerk bezeichnet. Bei FC, FC/NVMe und FCoE wird die Netzwerktopologie zwischen der Storage-Lösung und den Hosts als Fabric bezeichnet. Um Redundanz zu schaffen, die Sie vor dem Verlust des Datenzugriffs schützt, sollten Sie Ihr SAN mit HA-Paaren in einer Multi-Netzwerk- oder Multi-Fabric-Konfiguration einrichten. Konfigurationen mit einzelnen Knoten oder einzelnen Netzwerken/Fabrics sind nicht vollständig redundant und daher nicht empfohlen.

Nachdem Ihr SAN konfiguriert ist, können Sie link:../san-admin/provision-storage.html["Bereitstellen von Storage für iSCSI oder FC"], oder Sie können link:../san-admin/create-nvme-namespace-subsystem-task.html["Storage für FC/NVMe bereitstellen"]. Anschließend können Sie eine Verbindung zu Ihren Hosts herstellen, um mit der Datenpflege zu beginnen.

Die Unterstützung der SAN-Protokolle variiert abhängig von Ihrer Version von ONTAP, Ihrer Plattform und Ihrer Konfiguration. Weitere Informationen zu Ihrer spezifischen Konfiguration finden Sie im link:https://imt.netapp.com/matrix/["NetApp Interoperabilitäts-Matrix-Tool"^].

.Verwandte Informationen
* link:../san-admin/index.html["ÜBERSICHT ÜBER DIE SAN-Administration"]
* link:../nvme/support-limitations.html["Konfiguration, Support und Einschränkungen von NVMe"]

