---
permalink: san-config/set-queue-depth-task.html 
sidebar: sidebar 
keywords: calculate, queue depth 
summary: Möglicherweise müssen Sie die FC-Warteschlangentiefe auf dem Host anpassen, um die Höchstwerte für ITNs pro Knoten und FC-Port-Fan-in zu erreichen. Die maximale Anzahl an LUNs und die Anzahl der HBAs, die eine Verbindung zu einem FC-Port herstellen können, werden durch die verfügbare Warteschlangentiefe auf den FC-Ziel-Ports begrenzt. 
---
= Ändern Sie die Warteschlangentiefe für ONTAP-SAN-Hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie die Warteschlangentiefe auf Ihrem Host ändern, um die maximalen Werte für ITNs pro Knoten und FC-Port-Fan-in zu erreichen.



== AIX-Hosts

Sie können die Warteschlangentiefe auf AIX-Hosts mit dem `chdev` Befehl ändern. Mit dem `chdev` Befehl genommene Änderungen werden auch nach einem Neustart fortgeführt.

Beispiele:

* Um die Warteschlangentiefe für das hdisk7-Gerät zu ändern, verwenden Sie den folgenden Befehl:
+
`chdev -l hdisk7 -a queue_depth=32`

* Verwenden Sie den folgenden Befehl, um die Warteschlangentiefe für den FCS0-HBA zu ändern:
+
`chdev -l fcs0 -a num_cmd_elems=128`

+
Der Standardwert für `num_cmd_elems` ist 200. Der maximale Wert ist 2.048.

+
[NOTE]
====
Unter Umständen muss der HBA in den Offline-Modus versetzt werden, um `num_cmd_elems` ihn zu ändern und ihn dann mithilfe der `rmdev -l fcs0 -R` `makdev -l fcs0 -P` Befehle und wieder in den Online-Modus zu versetzen.

====




== HP-UX-Hosts erhältlich

Sie können die LUN- oder Gerätewarteschlangentiefe auf HP-UX-Hosts mit dem Kernel-Parameter ändern `scsi_max_qdepth`. Sie können die HBA-Warteschlangentiefe mit dem Kernel-Parameter ändern `max_fcp_reqs`.

* Der Standardwert für `scsi_max_qdepth` ist 8. Der maximale Wert ist 255.
+
`scsi_max_qdepth` Kann auf einem laufenden System mit der `-u` Option des `kmtune` Befehls dynamisch geändert werden. Die Änderung wird für alle Geräte im System wirksam. Verwenden Sie beispielsweise den folgenden Befehl, um die LUN-Warteschlangentiefe auf 64 zu erhöhen:

+
`kmtune -u -s scsi_max_qdepth=64`

+
Mit dem `scsictl` Befehl kann die Warteschlangentiefe für einzelne Gerätedateien geändert werden. Änderungen mit dem `scsictl` Befehl gehen beim Neubooten des Systems nicht verloren. Um die Warteschlangentiefe für eine bestimmte Gerätedatei anzuzeigen und zu ändern, führen Sie den folgenden Befehl aus:

+
`scsictl -a /dev/rdsk/c2t2d0`

+
`scsictl -m queue_depth=16 /dev/rdsk/c2t2d0`

* Der Standardwert für `max_fcp_reqs` ist 512. Der maximale Wert ist 1024.
+
Der Kernel muss neu aufgebaut werden und das System muss neu gestartet werden, damit `max_fcp_reqs` die Änderungen wirksam werden. Verwenden Sie zum Ändern der HBA-Warteschlangentiefe in 256 beispielsweise den folgenden Befehl:

+
`kmtune -u -s max_fcp_reqs=256`





== Solaris-Hosts

Sie können die LUN- und HBA-Warteschlangentiefe für Ihre Solaris-Hosts einstellen.

* Für LUN-Warteschlangentiefe: Die Anzahl der auf einem Host verwendeten LUNs muss mit dem pro-LUN-Gashebel (lun-Queue-Tiefe) kleiner oder gleich dem Wert für die tgt-queue-Tiefe auf dem Host sein.
* Für Warteschlangentiefe in einem Sun Stack: Die nativen Treiber erlauben keine `max_throttle` Einstellungen pro LUN oder pro Ziel auf HBA-Ebene. Die empfohlene Methode zum Festlegen des `max_throttle` Werts für native Treiber ist auf der Ebene pro Device (VID_PID) in den `/kernel/drv/sd.conf` `/kernel/drv/ssd.conf` Dateien und. Das Host-Dienstprogramm setzt diesen Wert auf 64 für MPxIO-Konfigurationen und 8 für Veritas DMP-Konfigurationen.


.Schritte
. `# cd/kernel/drv`
. `# vi lpfc.conf`
. Suchen nach `/tft-queue (/tgt-queue)`
+
`tgt-queue-depth=32`

+
[NOTE]
====
Der Standardwert ist bei der Installation auf 32 gesetzt.

====
. Legen Sie den gewünschten Wert basierend auf der Konfiguration Ihrer Umgebung fest.
. Speichern Sie die Datei.
. Starten Sie den Host mit dem `+sync; sync; sync; reboot -- -r+` Befehl neu.




== VMware Hosts für einen QLogic HBA

Verwenden Sie den `esxcfg-module` Befehl, um die Einstellungen für die HBA-Zeitüberschreitung zu ändern.  `esx.conf`Eine manuelle Aktualisierung der Datei wird nicht empfohlen.

.Schritte
. Melden Sie sich als Root-Benutzer an der Service-Konsole an.
.  `#vmkload_mod -l`Überprüfen Sie mit dem Befehl, welches Qlogic HBA-Modul aktuell geladen ist.
. Führen Sie für eine einzelne Instanz eines Qlogic HBA den folgenden Befehl aus:
+
`#esxcfg-module -s ql2xmaxqdepth=64 qla2300_707`

+
[NOTE]
====
Dieses Beispiel verwendet das Modul qla2300_707. Verwenden Sie das entsprechende Modul basierend auf der Ausgabe von `vmkload_mod -l`.

====
. Speichern Sie Ihre Änderungen mit dem folgenden Befehl:
+
`#/usr/sbin/esxcfg-boot -b`

. Starten Sie den Server mit folgendem Befehl neu:
+
`#reboot`

. Bestätigen Sie die Änderungen mit folgenden Befehlen:
+
.. `#esxcfg-module -g qla2300_707`
.. `qla2300_707 enabled = 1 options = 'ql2xmaxqdepth=64'`






== VMware-Hosts für einen Emulex HBA

Verwenden Sie den `esxcfg-module` Befehl, um die Einstellungen für die HBA-Zeitüberschreitung zu ändern.  `esx.conf`Eine manuelle Aktualisierung der Datei wird nicht empfohlen.

.Schritte
. Melden Sie sich als Root-Benutzer an der Service-Konsole an.
.  `#vmkload_mod -l grep lpfc`Überprüfen Sie mit dem Befehl, welcher Emulex HBA aktuell geladen ist.
. Geben Sie für eine einzelne Instanz eines Emulex HBA den folgenden Befehl ein:
+
`#esxcfg-module -s lpfc0_lun_queue_depth=16 lpfcdd_7xx`

+
[NOTE]
====
Je nach HBA-Modell kann das Modul entweder lpfcdd_7xx oder lpfcdd_732 sein. Der obige Befehl verwendet das lpfcdd_7xx-Modul. Sie sollten das entsprechende Modul basierend auf dem Ergebnis von verwenden `vmkload_mod -l`.

====
+
Durch Ausführen dieses Befehls wird die LUN-Warteschlangentiefe auf 16 für den HBA festgelegt, der von lpfc0 dargestellt wird.

. Führen Sie für mehrere Instanzen eines Emulex HBA den folgenden Befehl aus:
+
`a esxcfg-module -s "lpfc0_lun_queue_depth=16 lpfc1_lun_queue_depth=16" lpfcdd_7xx`

+
Die LUN-Warteschlangentiefe für lpfc0 und die LUN-Warteschlangentiefe für lpfc1 ist auf 16 festgelegt.

. Geben Sie den folgenden Befehl ein:
+
`#esxcfg-boot -b`

. Starten Sie mit `#reboot`.




== Windows Hosts für einen Emulex HBA

Auf Windows-Hosts können Sie das `LPUTILNT` Dienstprogramm verwenden, um die Warteschlangentiefe für Emulex-HBAs zu aktualisieren.

.Schritte
. Führen Sie das `LPUTILNT` Dienstprogramm aus `C:\WINNT\system32`, das sich im Verzeichnis befindet.
. Wählen Sie im Menü auf der rechten Seite die Option *Drive Parameters* aus.
. Scrollen Sie nach unten und doppelklicken Sie auf *QueueDepth*.
+
[NOTE]
====
Wenn Sie *QueueDepth* größer als 150 einstellen, muss auch der folgende Wert für die Windows-Registrierung entsprechend erhöht werden:

`HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\lpxnds\Parameters\Device\NumberOfRequests`

====




== Windows Hosts für einen Qlogic HBA

Auf Windows-Hosts können Sie die und das `SANsurfer` HBA-Manager-Dienstprogramm verwenden, um die Warteschlangentiefen für Qlogic HBAs zu aktualisieren.

.Schritte
. Führen Sie das `SANsurfer` HBA-Manager-Dienstprogramm aus.
. Klicken Sie auf *HBA-Port* > *Einstellungen*.
. Klicken Sie im Listenfeld auf *Erweiterte HBA-Porteinstellungen*.
. Aktualisieren Sie den `Execution Throttle` Parameter.




== Linux Hosts für Emulex HBA

Sie können die Warteschlangentiefe eines Emulex HBA auf einem Linux-Host aktualisieren. Damit die Updates bei einem Neustart erhalten bleiben, müssen Sie dann ein neues RAM-Laufwerk-Image erstellen und den Host neu starten.

.Schritte
. Geben Sie die zu ändernden Warteschlangentiefe an:
+
`modinfo lpfc|grep queue_depth`

+
Die Liste der Parameter für die Warteschlangentiefe mit ihrer Beschreibung wird angezeigt. Je nach Betriebssystemversion können Sie einen oder mehrere der folgenden Parameter für die Warteschlangentiefe ändern:

+
** `lpfc_lun_queue_depth`: Maximale Anzahl von FC-Befehlen, die in eine bestimmte LUN (uint) eingereiht werden können
** `lpfc_hba_queue_depth`: Maximale Anzahl von FC-Befehlen, die in eine Warteschlange für einen lpfc HBA (uint) gestellt werden können
** `lpfc_tgt_queue_depth`: Maximale Anzahl von FC-Befehlen, die in einen bestimmten Zielport (uint) eingereiht werden können
+
Der `lpfc_tgt_queue_depth` Parameter gilt nur für Red hat Enterprise Linux 7.x-Systeme, SUSE Linux Enterprise Server 11 SP4-Systeme und 12.x-Systeme.



. Aktualisieren Sie die Warteschlangentiefe, indem Sie der `/etc/modprobe.conf` Datei für ein Red hat Enterprise Linux 5.x-System und der `/etc/modprobe.d/scsi.conf` Datei für ein Red hat Enterprise Linux 6.x- oder 7.x-System oder einem SUSE Linux Enterprise Server 11.x- oder 12.x-System die Warteschlangentiefe hinzufügen.
+
Abhängig von Ihrer Betriebssystemversion können Sie einen oder mehrere der folgenden Befehle hinzufügen:

+
** `options lpfc lpfc_hba_queue_depth=new_queue_depth`
** `options lpfc lpfc_lun_queue_depth=new_queue_depth`
** `options lpfc_tgt_queue_depth=new_queue_depth`


. Erstellen Sie ein neues RAM-Laufwerk-Image, und starten Sie dann den Host neu, damit die Updates bei einem Neustart erhalten bleiben.
+
Weitere Informationen finden Sie im link:../system-admin/index.html["Systemadministration"] für Ihre Version des Linux-Betriebssystems.

. Vergewissern Sie sich, dass die Werte für die Warteschlangentiefe für jeden Parameter aktualisiert werden, den Sie geändert haben:
+


+
[listing]
----
root@localhost ~]#cat /sys/class/scsi_host/host5/lpfc_lun_queue_depth
      30
----
+
Der aktuelle Wert der Warteschlangentiefe wird angezeigt.





== Linux Hosts für QLogic HBA

Sie können die Tiefe der Gerätewarteschlange eines QLogic-Treibers auf einem Linux-Host aktualisieren. Damit die Updates bei einem Neustart erhalten bleiben, müssen Sie dann ein neues RAM-Laufwerk-Image erstellen und den Host neu starten. Mithilfe der QLogic HBA Management-GUI oder der Befehlszeilenschnittstelle (CLI) lässt sich die QLogic HBA-Warteschlangentiefe ändern.

Diese Aufgabe zeigt, wie die QLogic HBA CLI zum Ändern der QLogic HBA-Warteschlangentiefe verwendet wird

.Schritte
. Geben Sie den Parameter für die Warteschlangentiefe des Geräts an, der geändert werden soll:
+
`modinfo qla2xxx | grep ql2xmaxqdepth`

+
Sie können nur den `ql2xmaxqdepth` Parameter „Warteschlangentiefe“ ändern, der die maximale Warteschlangentiefe angibt, die für jede LUN festgelegt werden kann. Der Standardwert ist 64 für RHEL 7.5 und höher. Der Standardwert ist 32 für RHEL 7.4 und früher.

+
[listing]
----
root@localhost ~]# modinfo qla2xxx|grep ql2xmaxqdepth
parm:       ql2xmaxqdepth:Maximum queue depth to set for each LUN. Default is 64. (int)
----
. Wert für die Tiefe der Gerätewarteschlange aktualisieren:
+
** Wenn Sie die Änderungen persistent machen möchten, führen Sie die folgenden Schritte aus:
+
... Aktualisieren Sie die Warteschlangentiefe, indem Sie der `/etc/modprobe.conf` Datei für ein Red hat Enterprise Linux 5.x-System und der `/etc/modprobe.d/scsi.conf` Datei für ein Red hat Enterprise Linux 6.x- oder 7.x-System oder einem SUSE Linux Enterprise Server 11.x- oder 12.x-System den Parameter Warteschlangentiefe hinzufügen: `options qla2xxx ql2xmaxqdepth=new_queue_depth`
... Erstellen Sie ein neues RAM-Laufwerk-Image, und starten Sie dann den Host neu, damit die Updates bei einem Neustart erhalten bleiben.
+
Weitere Informationen finden Sie im link:../system-admin/index.html["Systemadministration"] für Ihre Version des Linux-Betriebssystems.



** Wenn Sie den Parameter nur für die aktuelle Sitzung ändern möchten, führen Sie den folgenden Befehl aus:
+
`echo new_queue_depth > /sys/module/qla2xxx/parameters/ql2xmaxqdepth`

+
Im folgenden Beispiel wird die Warteschlangentiefe auf 128 gesetzt.

+
[listing]
----
echo 128 > /sys/module/qla2xxx/parameters/ql2xmaxqdepth
----


. Überprüfen Sie, ob die Werte für die Warteschlangentiefe aktualisiert wurden:
+
`cat /sys/module/qla2xxx/parameters/ql2xmaxqdepth`

+
Der aktuelle Wert der Warteschlangentiefe wird angezeigt.

. Ändern Sie die Warteschlangentiefe von QLogic HBA, indem Sie den Firmware-Parameter `Execution Throttle` aus dem QLogic HBA BIOS aktualisieren.
+
.. Melden Sie sich bei der QLogic HBA Management CLI an:
+
`/opt/QLogic_Corporation/QConvergeConsoleCLI/qaucli`

.. Wählen Sie im Hauptmenü die `Adapter Configuration` Option aus.
+
[listing]
----
[root@localhost ~]# /opt/QLogic_Corporation/QConvergeConsoleCLI/qaucli
Using config file: /opt/QLogic_Corporation/QConvergeConsoleCLI/qaucli.cfg
Installation directory: /opt/QLogic_Corporation/QConvergeConsoleCLI
Working dir: /root

QConvergeConsole

        CLI - Version 2.2.0 (Build 15)

    Main Menu

    1:  Adapter Information
    **2:  Adapter Configuration**
    3:  Adapter Updates
    4:  Adapter Diagnostics
    5:  Monitoring
    6:  FabricCache CLI
    7:  Refresh
    8:  Help
    9:  Exit


        Please Enter Selection: 2
----
.. Wählen Sie in der Liste der Adapterkonfigurationsparameter die `HBA Parameters` Option aus.
+
[listing]
----
1:  Adapter Alias
    2:  Adapter Port Alias
    **3:  HBA Parameters**
    4:  Persistent Names (udev)
    5:  Boot Devices Configuration
    6:  Virtual Ports (NPIV)
    7:  Target Link Speed (iiDMA)
    8:  Export (Save) Configuration
    9:  Generate Reports
   10:  Personality
   11:  FEC
(p or 0: Previous Menu; m or 98: Main Menu; ex or 99: Quit)
        Please Enter Selection: 3
----
.. Wählen Sie aus der Liste der HBA-Ports den erforderlichen HBA-Port aus.
+
[listing]
----
Fibre Channel Adapter Configuration

    HBA Model QLE2562 SN: BFD1524C78510
      1: Port   1: WWPN: 21-00-00-24-FF-8D-98-E0 Online
      2: Port   2: WWPN: 21-00-00-24-FF-8D-98-E1 Online
    HBA Model QLE2672 SN: RFE1241G81915
      3: Port   1: WWPN: 21-00-00-0E-1E-09-B7-62 Online
      4: Port   2: WWPN: 21-00-00-0E-1E-09-B7-63 Online


        (p or 0: Previous Menu; m or 98: Main Menu; ex or 99: Quit)
        Please Enter Selection: 1
----
+
Die Details des HBA-Ports werden angezeigt.

.. Wählen Sie im Menü HBA-Parameter die `Display HBA Parameters` Option aus `Execution Throttle`, um den aktuellen Wert der Option anzuzeigen.
+
Der Standardwert der `Execution Throttle` Option ist 65535.

+
[listing]
----
HBA Parameters Menu

=======================================================
HBA           : 2 Port: 1
SN            : BFD1524C78510
HBA Model     : QLE2562
HBA Desc.     : QLE2562 PCI Express to 8Gb FC Dual Channel
FW Version    : 8.01.02
WWPN          : 21-00-00-24-FF-8D-98-E0
WWNN          : 20-00-00-24-FF-8D-98-E0
Link          : Online
=======================================================

    1:  Display HBA Parameters
    2:  Configure HBA Parameters
    3:  Restore Defaults


        (p or 0: Previous Menu; m or 98: Main Menu; x or 99: Quit)
        Please Enter Selection: 1
--------------------------------------------------------------------------------
HBA Instance 2: QLE2562 Port 1 WWPN 21-00-00-24-FF-8D-98-E0 PortID 03-07-00
Link: Online
--------------------------------------------------------------------------------
Connection Options             : 2 - Loop Preferred, Otherwise Point-to-Point
Data Rate                      : Auto
Frame Size                     : 2048
Hard Loop ID                   : 0
Loop Reset Delay (seconds)     : 5
Enable Host HBA BIOS           : Enabled
Enable Hard Loop ID            : Disabled
Enable FC Tape Support         : Enabled
Operation Mode                 : 0 - Interrupt for every I/O completion
Interrupt Delay Timer (100us)  : 0
**Execution Throttle             : 65535**
Login Retry Count              : 8
Port Down Retry Count          : 30
Enable LIP Full Login          : Enabled
Link Down Timeout (seconds)    : 30
Enable Target Reset            : Enabled
LUNs Per Target                : 128
Out Of Order Frame Assembly    : Disabled
Enable LR Ext. Credits         : Disabled
Enable Fabric Assigned WWN     : N/A

Press <Enter> to continue:
----
.. Drücken Sie *Enter*, um fortzufahren.
.. Wählen Sie im Menü HBA-Parameter die `Configure HBA Parameters` Option zum Ändern der HBA-Parameter aus.
.. Wählen Sie im Menü Parameter konfigurieren die `Execute Throttle` Option aus, und aktualisieren Sie den Wert dieses Parameters.
+
[listing]
----
Configure Parameters Menu

=======================================================
HBA           : 2 Port: 1
SN            : BFD1524C78510
HBA Model     : QLE2562
HBA Desc.     : QLE2562 PCI Express to 8Gb FC Dual Channel
FW Version    : 8.01.02
WWPN          : 21-00-00-24-FF-8D-98-E0
WWNN          : 20-00-00-24-FF-8D-98-E0
Link          : Online
=======================================================

    1:  Connection Options
    2:  Data Rate
    3:  Frame Size
    4:  Enable HBA Hard Loop ID
    5:  Hard Loop ID
    6:  Loop Reset Delay (seconds)
    7:  Enable BIOS
    8:  Enable Fibre Channel Tape Support
    9:  Operation Mode
   10:  Interrupt Delay Timer (100 microseconds)
   11:  Execution Throttle
   12:  Login Retry Count
   13:  Port Down Retry Count
   14:  Enable LIP Full Login
   15:  Link Down Timeout (seconds)
   16:  Enable Target Reset
   17:  LUNs per Target
   18:  Enable Receive Out Of Order Frame
   19:  Enable LR Ext. Credits
   20:  Commit Changes
   21:  Abort Changes


        (p or 0: Previous Menu; m or 98: Main Menu; x or 99: Quit)
        Please Enter Selection: 11
Enter Execution Throttle [1-65535] [65535]: 65500
----
.. Drücken Sie *Enter*, um fortzufahren.
.. Wählen Sie im Menü Parameter konfigurieren die `Commit Changes` Option aus, um die Änderungen zu speichern.
.. Verlassen Sie das Menü.



