---
permalink: san-config/supported-fc-ports-concept.html 
sidebar: sidebar 
keywords: supported, fc, ports 
summary: Die Anzahl der für FC konfigurierten integrierten FC-Ports und CNA-/UTA2-Ports variiert basierend auf dem Modell des Controllers. FC-Ports sind auch über unterstützte FC-Zielerweiterungsadapter oder zusätzliche UTA2-Karten verfügbar, die mit FC SFP+ Adaptern konfiguriert sind. 
---
= Unterstützte FC-Ports
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Anzahl der für FC konfigurierten integrierten FC-Ports und CNA-/UTA2-Ports variiert basierend auf dem Modell des Controllers. FC-Ports sind auch über unterstützte FC-Zielerweiterungsadapter oder zusätzliche UTA2-Karten verfügbar, die mit FC SFP+ Adaptern konfiguriert sind.



== Onboard FC-, UTA- und UTA2-Ports

* Die Onboard-Ports können individuell als Ziel- oder Initiator-FC-Ports konfiguriert werden.
* Die Anzahl der integrierten FC-Ports variiert je nach Controller-Modell.
+
Der https://hwu.netapp.com["NetApp Hardware Universe"^] Enthält eine vollständige Liste der integrierten FC-Ports auf jedem Controller-Modell.

* FC-Ports sind nur auf FAS2240 Systemen über den X1150A-R6 Erweiterungsadapter verfügbar.
+
FAS2220 und FAS2520 unterstützen keine FC-Unterstützung.





== FC-Ports für den Zielerweiterungsadapter

* Die verfügbaren Zielerweiterungsadapter variieren je nach Controller-Modell.
+
Der https://hwu.netapp.com["NetApp Hardware Universe"^] Enthält eine vollständige Liste der Adapter zur Zielerweiterung für jedes Controller-Modell.

* Die Ports auf einigen FC-Erweiterungsadaptern werden werkseitig als Initiatoren oder Ziele konfiguriert und können nicht geändert werden.
+
Andere können wie die integrierten FC-Ports individuell als Ziel- oder Initiator-FC-Ports konfiguriert werden. Eine vollständige Liste finden Sie in https://hwu.netapp.com["NetApp Hardware Universe"^].


