---
permalink: upgrade/arp-warning-clear.html 
sidebar: sidebar 
keywords: ontap, upgrade, ransomware, protection, security, arp 
summary: Vor dem Upgrade von ONTAP auf alle Warnungen über ungewöhnliche Aktivitäten in ARP reagieren. 
---
= Aktivitätswarnungen im Autonomous Ransomware Protection (ARP) sollten vor einem ONTAP Upgrade behoben werden.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie auf ONTAP 9.16.1 oder höher aktualisieren, sollte auf alle Warnungen zu ungewöhnlichen Aktivitäten reagiert werden, die von Autonomous Ransomware Protection (ARP) gemeldet werden. In ONTAP 9.16.1 wurde ARP auf ein maschinelles Lern-/künstliche Intelligenz (KI)-basiertes Modell umgestellt. Aufgrund dieser Änderung gehen alle ungelösten aktiven Warnungen der bestehenden ARP in ONTAP 9.15.1 oder früher nach dem Upgrade verloren.

.Schritte
. Auf alle von link:../anti-ransomware/respond-abnormal-task.html["ARP"] gemeldeten Warnungen zu ungewöhnlichen Aktivitäten reagieren und mögliche Probleme beheben.
. Die Behebung dieser Probleme sollte vor dem Upgrade bestätigt werden, indem *Aktualisieren und verdächtige Dateitypen löschen* ausgewählt wird, um die Entscheidung zu protokollieren und die normale ARP-Überwachung fortzusetzen.

