---
permalink: upgrade/arp-warning-clear.html 
sidebar: sidebar 
keywords: ontap, upgrade, ransomware, protection, security, arp 
summary: Konfigurieren Sie vor dem Upgrade von ONTAP LDAP-Clients mithilfe von SSLv3 für die sichere Kommunikation mit LDAP-Servern zur Verwendung von TLS. SSL ist nach dem Upgrade nicht verfügbar. 
---
= Reaktion auf Warnungen vor auffälligen Aktivitäten in Autonomous Ransomware Protection (ARP)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie ein Upgrade auf ONTAP 9.16.1 oder höher durchführen, sollten Sie auf abnormale Aktivitätswarnungen reagieren, die von Autonomous Ransomware Protection (ARP) gemeldet werden. In ONTAP 9.16.1 wechselte ARP zu einem auf Machine Learning/künstlicher Intelligenz (KI) basierenden Modell. Aufgrund dieser Änderung gehen alle ungelösten aktiven Warnungen des bestehenden ARP in ONTAP 9.15.1 oder früher nach dem Upgrade verloren.

.Schritte
. Reagieren Sie auf abnormale Aktivitätswarnungen, die von gemeldet link:../anti-ransomware/respond-abnormal-task.html["ARP"]wurden, und beheben Sie mögliche Probleme.
. Bestätigen Sie die Behebung dieser Probleme, bevor Sie das Upgrade durchführen, indem Sie *Update and Clear Suspect File Types* auswählen, um Ihre Entscheidung zu erfassen und die normale ARP-Überwachung fortzusetzen.

