---
permalink: upgrade/choose-target-version.html 
sidebar: sidebar 
keywords: upgrade, ontap, choose target release, target release 
summary: Wählen Sie Ihr Ziel-ONTAP Upgrade-Release basierend auf NetApp Empfehlungen, Ihren Bedarf für bestimmte Funktionen oder die empfohlene Mindestversion für die Performance aus. 
---
= Wählen Sie die gewünschte ONTAP-Version für ein Upgrade aus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wählen Sie Ihre gewünschte ONTAP Upgrade-Version basierend auf Empfehlungen von NetApp, Ihren Bedarf für bestimmte Funktionen oder Ihre Notwendigkeit, die Mindestversion zu haben, um Ihre Performance-Anforderungen zu erfüllen.

* Upgrade auf die neueste verfügbare Version (empfohlen)
+
NetApp empfiehlt, dass Sie Ihre ONTAP-Software auf die neueste Patch-Version der neuesten nummerierten ONTAP-Version aktualisieren.  Wenn dies nicht möglich ist, weil die neueste Version mit der Nummer nicht von den Speichersystemen im Cluster unterstützt wird, sollten Sie ein Upgrade auf die neueste Version mit der Nummer durchführen, die unterstützt wird.

* Verfügbare Funktionen
+
Wenn Sie ein Upgrade auf die minimale ONTAP-Version durchführen möchten, die für die Unterstützung einer bestimmten Funktion erforderlich ist, finden Sie unter link:https://www.netapp.com/media/15984-ontap-release-recommendation-guide.pdf["ONTAP Release-Empfehlungen"^] Um die ONTAP-Version zu ermitteln, sollten Sie auf aktualisieren.

* Empfohlene Mindestversion
+
Wenn Sie das Upgrade auf die empfohlene Mindestversion für den Cluster beschränken möchten, finden Sie Informationen unter link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU2["Empfohlene Mindestversionen für ONTAP"^] Um die ONTAP-Version zu ermitteln, sollten Sie auf aktualisieren.


