---
permalink: upgrade/concept_when_you_need_to_update_the_disk_qualification_package.html 
sidebar: sidebar 
keywords: upgrade, ontap, dqp, disk, qualification, package 
summary: 'Nach dem Upgrade von ONTAP, dem Hinzufügen eines neuen Laufwerkstyps oder einer neuen Laufwerkgröße oder dem Aktualisieren der Festplatten-Firmware sollten Sie auch das ONTAP-DQP-Paket (Disk Qualification Package) aktualisieren.' 
---
= Aktualisieren Sie das Disk Qualification Package
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach dem Upgrade der ONTAP-Software sollten Sie das ONTAP-DQP-Paket (Disk Qualification Package) herunterladen und installieren. Das DQP wird im Rahmen eines ONTAP-Upgrades nicht aktualisiert.

Der DQP enthält die richtigen Parameter für die ONTAP-Interaktion mit allen neu qualifizierten Laufwerken. Wenn Ihre DQP-Version keine Informationen für ein neu qualifiziertes Laufwerk enthält, verfügt ONTAP nicht über die Informationen zur ordnungsgemäßen Konfiguration des Laufwerks.

Es empfiehlt sich, den DQP vierteljährlich zu aktualisieren. Sie sollten den DQP auch aus den folgenden Gründen aktualisieren:

* Immer, wenn Sie einem Node im Cluster einen neuen Laufwerkstyp oder eine neue Laufwerksgröße hinzufügen
+
Wenn Sie beispielsweise bereits über 1-TB-Laufwerke verfügen und 2-TB-Laufwerke hinzufügen, müssen Sie nach dem aktuellen DQP-Update suchen.

* Jedes Mal, wenn Sie die Festplatten-Firmware aktualisieren
* Immer wenn neuere Festplatten-Firmware oder DQP-Dateien verfügbar sind


.Verwandte Informationen
* https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware/download/DISKQUAL/ALL/qual_devices.zip["NetApp Downloads: Disk Qualification Package"^]
* https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp Downloads: Festplatten-Firmware"^]

