---
permalink: upgrade/concept_upgrade_requirements_for_metrocluster_configurations.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, requirements, metrocluster, mcc, general, normal, operations, switchover 
summary: Wenn Sie ein Upgrade einer MetroCluster Konfiguration durchführen müssen, sollten Sie sich einige wichtige Anforderungen bewusst sein. 
---
= Upgrade-Anforderungen für MetroCluster Konfigurationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Beim Upgrade einer MetroCluster-Konfiguration sollten Sie auf einige wichtige Anforderungen achten.



== Erforderliche Methoden für größere Upgrades und Patch-Upgrades von MetroCluster-Konfigurationen

Unabhängig von der verwendeten Version von ONTAP können Patch-Upgrades auf MetroCluster-Konfigurationen mit dem automatischen ANDU-Verfahren (Non-Disruptive Upgrade) durchgeführt werden.

Solange Sie ONTAP 9.3 oder höher verwenden, können Sie größere Upgrades auf MetroCluster Konfigurationen mit dem Verfahren für automatische unterbrechungsfreie Upgrades (ANDU) durchführen. Auf Clustern mit ONTAP 9.2 oder einer älteren Version müssen größere Upgrades für MetroCluster-Konfigurationen mit dem für MetroCluster-Konfigurationen spezifischen NDU-Verfahren durchgeführt werden.



== Allgemeine Anforderungen

* Beide Cluster müssen dieselbe Version von ONTAP ausführen.
+
Sie können die ONTAP-Version mit dem Versionsbefehl überprüfen.

* Wenn Sie ein großes Upgrade durchführen, muss sich die MetroCluster-Konfiguration im normalen Modus befinden.
* Wenn Sie ein Patch-Upgrade durchführen, kann sich die MetroCluster-Konfiguration entweder im normalen Modus oder im Umschaltmodus befinden.
* Bei allen Konfigurationen mit Ausnahme von Clustern mit zwei Nodes können beide Cluster unterbrechungsfrei gleichzeitig aktualisiert werden.
+
Bei einem unterbrechungsfreien Upgrade von 2-Node-Clustern müssen die Cluster jeweils einen Node pro Cluster aktualisiert werden.

* Die Aggregate auf beiden Clustern dürfen den RAID-Status nicht neu synchronisieren.
+
Während der MetroCluster-Reparatur werden die gespiegelten Aggregate erneut synchronisiert. Sie können überprüfen, ob die MetroCluster Konfiguration diesen Status aufweist, indem Sie die verwenden `storage aggregate plex show -in-progress true` Befehl. Wenn Aggregate synchronisiert werden, sollten Sie erst nach Abschluss der Resynchronisierung ein Upgrade durchführen.

* Ausgehandelte Switchover-Operationen werden während des Upgrades fehlschlagen.
+
Zur Vermeidung von Problemen bei Upgrade- oder Umrüstung von Vorgängen sollte bei einem Upgrade oder Wechsel nicht eine ungeplante Umschaltung durchgeführt werden, es sei denn, alle Nodes auf beiden Clustern führen dieselbe Version von ONTAP aus.





== Konfigurationsanforderungen für den normalen Betrieb

* Die Quell-SVM LIFs müssen auf ihren Home-Nodes aktiv sein und sich befinden.
+
Daten-LIFs für die Ziel-SVMs müssen nicht auf ihren Home-Nodes up-to-the-Ziel-SVMs vorhanden sein.

* Alle Aggregate am lokalen Standort müssen online sein.
* Alle Root- und Daten-Volumes der SVMs des lokalen Clusters müssen online sein.




== Konfigurationsanforderungen für die Umschaltung

* Alle LIFs müssen sich auf ihren Home-Nodes befinden und sich dort befinden.
* Mit Ausnahme der Root-Aggregate am DR-Standort müssen alle Aggregate online sein.
+
Root-Aggregate sind während bestimmter Phasen der Umschaltung offline.

* Alle Volumes müssen online sein.


.Verwandte Informationen
link:task_verifying_the_networking_and_storage_status_for_metrocluster_cluster_is_ready.html["Überprüfen des Netzwerk- und Storage-Status für MetroCluster Konfigurationen"]
