---
permalink: upgrade/concept_when_you_need_to_update_the_disk_qualification_package.html 
sidebar: sidebar 
keywords: upgrade, ontap, dqp, disk, qualification, package 
summary: 'Das Disk Qualification Package (DQP) bietet vollständige Unterstützung für neu qualifizierte Laufwerke. Bevor Sie die Laufwerk-Firmware aktualisieren oder einem Cluster neue Laufwerktypen oder -Größen hinzufügen, müssen Sie das DQP aktualisieren. Eine Best Practice besteht darin, auch das DQP regelmäßig zu aktualisieren, z. B. jedes Quartal oder halbjährlich.' 
---
= Wenn Sie das Disk Qualification Package aktualisieren müssen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Disk Qualification Package (DQP) bietet vollständige Unterstützung für neu qualifizierte Laufwerke.

ONTAP behandelt Festplatten anders als normalerweise erwartet, beispielsweise weist ONTAP unterschiedliche Sektorgrößen zu als die vom Hersteller angegebenen. Das DQP enthält die richtigen Parameter für ONTAP für alle neu qualifizierten Laufwerke. Wenn Sie daher eine ONTAP-Version mit einem DQP verwenden, das keine Informationen für ein neu qualifiziertes Laufwerk enthält, verfügt ONTAP nicht über die Informationen, die für die ordnungsgemäße Konfiguration des Laufwerks erforderlich sind.

Sie müssen das DQP in den folgenden Situationen herunterladen und installieren. Eine Best Practice besteht darin, auch das DQP regelmäßig zu aktualisieren, z. B. jedes Quartal oder halbjährlich.

* Jedes Mal, wenn Sie ein Upgrade auf eine neue Version von ONTAP durchführen.
+
Das DQP wird im Rahmen eines ONTAP-Upgrades nicht aktualisiert.

* Immer wenn Sie dem Node einen neuen Laufwerkstyp oder eine neue Größe hinzufügen
+
Wenn Sie beispielsweise bereits über 1-TB-Laufwerke verfügen und 2-TB-Laufwerke hinzufügen, müssen Sie nach dem aktuellen DQP-Update suchen.

* Jedes Mal, wenn Sie die Festplatten-Firmware aktualisieren
* Immer wenn neuere Festplatten-Firmware oder DQP-Dateien verfügbar sind


.Verwandte Informationen
https://["NetApp Downloads: Disk Qualification Package"^]

https://["NetApp Downloads: Festplatten-Firmware"]
