---
permalink: upgrade/concept_upgrade_requirements_for_metrocluster_configurations.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, requirements, metrocluster, configuration, mcc, general, normal, operations, switchover 
summary: Bevor Sie Ihre ONTAP Software in einer MetroCluster Konfiguration aktualisieren, müssen Ihre Cluster bestimmte Anforderungen erfüllen. 
---
= ONTAP Upgrade-Anforderungen für MetroCluster Konfigurationen prüfen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie Ihre ONTAP Software in einer MetroCluster Konfiguration aktualisieren, müssen Ihre Cluster bestimmte Anforderungen erfüllen.

* Beide Cluster müssen mit derselben Version von ONTAP ausgeführt werden.
+
Die ONTAP Version lässt sich mit dem Befehl version überprüfen.

* Bei einem größeren ONTAP Upgrade muss sich die MetroCluster Konfiguration im Normalmodus befinden.
* Bei einem Patch-ONTAP-Upgrade kann sich die MetroCluster Konfiguration entweder im Normalmodus oder im Switchover-Modus befinden.
* Bei allen Konfigurationen außer Zwei-Knoten-Clustern ist ein unterbrechungsfreies Upgrade beider Cluster gleichzeitig möglich.
+
Für ein unterbrechungsfreies Upgrade in Zwei-Knoten-Clustern müssen die Cluster jeweils Knoten für Knoten aktualisiert werden.

* Die Aggregate in beiden Clustern dürfen sich nicht im RAID-Resynchronisierungsstatus befinden.
+
Während der MetroCluster-Heilung werden die gespiegelten Aggregate resynchronisiert. Ob sich die MetroCluster Konfiguration in diesem Zustand befindet, lässt sich mit dem  `storage aggregate plex show -in-progress true` Befehl überprüfen. Werden Aggregate synchronisiert, sollte ein Upgrade erst nach Abschluss der Resynchronisierung erfolgen.

+
Weitere Informationen zu  `storage aggregate plex show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-plex-show.html["ONTAP-Befehlsreferenz"^].

* Die ausgehandelten Umschaltungsvorgänge schlagen während des laufenden Upgrades fehl.
+
Um Probleme bei Upgrade- oder Rücksetzvorgängen zu vermeiden, darf während eines Upgrade- oder Rücksetzvorgangs kein ungeplanter Switchover durchgeführt werden, es sei denn, auf allen Knoten beider Cluster läuft die gleiche Version von ONTAP.





[[configuration-requirements-for-metrocluster-normal-operation]]
== Konfigurationsanforderungen für den normalen Betrieb von MetroCluster

* Die Quell-SVM-LIFs müssen aktiv sein und sich auf ihren Home-Nodes befinden.
+
Die Daten-LIFs für die Ziel-SVMs müssen weder aktiv sein noch sich auf ihren Heimatknoten befinden.

* Alle Aggregate am lokalen Standort müssen online sein.
* Alle Root- und Datenvolumes, die den SVMs des lokalen Clusters gehören, müssen online sein.




[[configuration-requirements-for-metrocluster-switchover]]
== Konfigurationsanforderungen für MetroCluster Switchover

* Alle LIFs müssen aktiv sein und sich auf ihren Home-Nodes befinden.
* Alle Aggregate müssen online sein, mit Ausnahme der Root Aggregate am DR-Standort.
+
Die Root-Aggregate am DR-Standort sind während bestimmter Phasen des Switchover offline.

* Alle Volumes müssen online sein.


.Verwandte Informationen
link:task_verifying_the_networking_and_storage_status_for_metrocluster_cluster_is_ready.html["Überprüfung des Netzwerk- und Speicherstatus für MetroCluster Konfigurationen"]
