---
permalink: upgrade/concept_how_firmware_is_updated_during_upgrade.html 
sidebar: sidebar 
keywords: ontap, upgrade, how, firmware, updated, during 
summary: Da das Upgrade von ONTAP auch ein Upgrade Ihrer Firmware umfasst, müssen Sie die Firmware nicht manuell aktualisieren. 
---
= Aktualisierung der Firmware während des ONTAP Upgrades
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Da das Upgrade von ONTAP auch ein Upgrade Ihrer Firmware umfasst, müssen Sie die Firmware nicht manuell aktualisieren. Wenn Sie ein ONTAP-Upgrade durchführen, wird die Firmware für das im ONTAP Upgrade-Paket enthaltene Cluster auf das Boot-Gerät jedes Node kopiert und die neue Firmware wird automatisch installiert.

Die Firmware für die folgenden Komponenten wird automatisch aktualisiert, wenn die Version im Cluster älter als die im ONTAP-Upgrade-Paket enthaltene Firmware ist:

* BIOS/LOADER
* Service-Prozessor (SP) oder Baseboard-Management-Controller (BMC)
* Storage Shelf
* Festplatte
* Flash Cache


Auf Wunsch können Sie auch die Firmware manuell zwischen ONTAP-Aktualisierungen aktualisieren.
