---
permalink: upgrade/concept_mixed_version_requirements.html 
sidebar: sidebar 
keywords: ontap, upgrade, mixed, version, clusters, mixed-version nodes, requirements 
summary: Ein ONTAP Cluster mit gemischten Versionen besteht aus Nodes, auf denen zwei verschiedene wichtige ONTAP Versionen ausgeführt werden, z. B. ONTAP 9.8 und 9.12.1. ONTAP-Cluster mit gemischter Version werden nur in bestimmten Szenarien unterstützt. 
---
= Überprüfen Sie die Kompatibilität der ONTAP-Versionen für Cluster mit gemischten Versionen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In einem ONTAP Cluster mit gemischten Versionen laufen auf den Nodes kurze Zeit zwei verschiedene wichtige ONTAP-Versionen. Beispielsweise ist ein Cluster mit Nodes mit ONTAP 9.8 und 9.12.1 oder ONTAP 9.9.1 und 9.13.1 ein Cluster mit gemischten Versionen. Cluster mit Nodes, die innerhalb derselben Version unterschiedliche Patch-Level ausführen, wie ONTAP 9.9.1P1 und 9.9.1P5, sind keine Cluster mit gemischten Versionen.


NOTE: Cluster mit gemischten Versionen werden für Cloud Volumes ONTAP nicht unterstützt.

NetApp unterstützt ONTAP Cluster gemischter Versionen für begrenzte Zeit und in bestimmten Szenarien.

Im Folgenden finden Sie die häufigsten Szenarien, in denen ein ONTAP-Cluster einen gemischten Versionsstatus aufweist:

* ONTAP Software-Upgrades in großen Clustern
+
Das Upgrade aller Nodes in einem großen Cluster kann mehrere Tage oder Wochen dauern. Das Cluster wechselt in einen Zustand mit gemischter Version, bis alle Nodes aktualisiert werden.

* ONTAP Software-Upgrades sind erforderlich, wenn einem Cluster neue Nodes hinzugefügt werden sollen
+
Sie können dem Cluster entweder neue Nodes hinzufügen, um die Kapazität zu erweitern, oder während des kompletten Austauschen der Controller neue Nodes hinzufügen. In beiden Fällen müssen Sie unter Umständen den Status gemischter Versionen eingeben, um Ihre Daten von bestehenden Controllern zu den neuen Nodes in Ihrem neuen System zu migrieren.



Für einen optimalen Cluster-Betrieb sollte die Zeitspanne, während der sich das Cluster in einem Zustand gemischter Versionen befindet, so kurz wie möglich sein. Die maximale Dauer, die ein Cluster für eine Unterstützung in einem gemischten Versionsstatus zur Verfügung stellt, hängt von der niedrigsten ONTAP-Version im Cluster ab.

[cols="2"]
|===
| Wenn die niedrigste Version von ONTAP, die im Cluster mit gemischten Versionen läuft, ist... | Dann können Sie in einem gemischten Version Zustand bleiben für ein Maximum von... 


| ONTAP 9.8 oder höher | 90 Tage 


| ONTAP 9.7 oder früher | 7 Tage 
|===
Während sich das Cluster in einem Zustand mit gemischten Versionen befindet, sollten Sie keine Befehle eingeben, die den Cluster-Betrieb oder die Konfiguration verändern, außer diejenigen, die für das Upgrade oder die Datenmigration erforderlich sind. Beispielsweise sollten Aktivitäten wie (aber nicht beschränkt auf) LIF-Migration, geplante Storage-Failover-Vorgänge oder die Erstellung oder Löschung umfangreicher Objekte erst nach Abschluss des Upgrades und der Datenmigration durchgeführt werden.



== Cluster mit gemischten Versionen werden von ONTAP Software-Upgrades unterstützt

Sie können mit jeder beliebigen unterstützten ONTAP-Version einen gemischten Versionsstatus eingeben, der ein direktes Upgrade von Ihrer niedrigsten aktuellen Version ermöglicht. Wenn Sie beispielsweise ONTAP 9.11.1 ausführen, können Sie den Status einer gemischten Version mit Nodes eingeben, auf denen ONTAP 9.15.1 ausgeführt wird. Sie können keinen gemischten Versionsstatus mit Nodes aufrufen, die ONTAP 9.11.1 und ONTAP 9.16.1 ausführen. ONTAP 9.16.1 wird für direkte Upgrades von ONTAP 9.11.1 nicht unterstützt.


NOTE: ONTAP Patch (P)-Release-Versionen haben keinen Einfluss auf die Kompatibilität von Clustern mit gemischten Versionen. Wenn Sie beispielsweise ONTAP 9.11.1P6 verwenden, ist Ihre aktuelle ONTAP Version für die Kompatibilität von Clustern mit gemischten Versionen ONTAP 9.11.1. Oder: Wenn Sie ONTAP 9.12.1 verwenden und auf ONTAP 9.15.1P2 aktualisieren möchten, ist Ihre Ziel ONTAP Version für die Kompatibilität von Clustern mit gemischten Versionen ONTAP 9.15.1.

Um ein Upgrade auf eine ONTAP-Version durchzuführen, die für ein direktes Upgrade von Ihrer aktuellen Version nicht unterstützt wird, müssen Sie ein mehrstufiges Upgrade durchführen. Bei einem mehrstufigen Upgrade geben Sie zuerst einen gemischten Versionsstatus mit der höchsten Version ein, die für ein direktes Upgrade von Ihrer aktuellen Version unterstützt wird. Sie führen dieses Upgrade durch und führen dann ein separates Upgrade auf Ihre Zielversion durch. Wenn die niedrigste aktuelle Version beispielsweise ONTAP 9.10.1 ist und Sie ein Upgrade auf ONTAP 9.16.1 durchführen möchten, geben Sie zuerst einen gemischten Versionsstatus ein, um alle Nodes auf ONTAP 9.14.1 zu aktualisieren. Anschließend führen Sie ein separates Upgrade von ONTAP 9.14.1 auf ONTAP 9.16.1 durch. Erfahren Sie mehr über link:concept_upgrade_paths.html#types-of-upgrade-paths["Mehrstufige Upgrades"] und link:concept_upgrade_paths.html#supported-upgrade-paths["Unterstützte Upgrade-Pfade"].

Ein Cluster mit gemischten Versionen kann nur zwei wichtige ONTAP-Versionen enthalten. Sie können beispielsweise ein Cluster mit gemischten Versionen und Nodes mit ONTAP 9.13.1 und 9.15.1 oder mit Nodes mit ONTAP 9.13.1 und 9.16.1 verwenden. Sie können kein Cluster mit gemischten Versionen und Nodes mit ONTAP 9.13.1, 9.15.1 und 9.16.1 verwenden.

[cols="25,25,50"]
|===
| Wenn Ihre aktuelle ONTAP Version… ist | Die ONTAP Zielversion lautet… | Der Status der gemischten Version für das Upgrade ist… 


| 9.17.1 | 9.18.1 | Unterstützt 


.2+| 9.16.1 | 9.18.1 | Unterstützt 


| 9.17.1 | Unterstützt 


.3+| 9.15.1 | 9.18.1 | Unterstützt 


| 9.17.1 | Unterstützt 


| 9.16.1 | Unterstützt 


.4+| 9.14.1 | 9.18.1 | Unterstützt 


| 9.17.1 | Unterstützt 


| 9.16.1 | Unterstützt 


| 9.15.1 | Unterstützt 


.5+| 9.13.1 | 9.18.1 | Nicht unterstützt 


| 9.17.1 | Unterstützt 


| 9.16.1 | Unterstützt 


| 9.15.1 | Unterstützt 


| 9.14.1 | Unterstützt 


.5+| 9.12.1 | 9.17.1 oder später | Nicht unterstützt 


| 9.16.1 | Unterstützt 


| 9.15.1 | Unterstützt 


| 9.14.1 | Unterstützt 


| 9.13.1 | Unterstützt 


.5+| 9.11.1 | 9.16.1 oder höher  a| 
Nicht unterstützt



| 9.15.1 | Unterstützt 


| 9.14.1 | Unterstützt 


| 9.13.1 | Unterstützt 


| 9.12.1 | Unterstützt 


.5+| 9.10.1 | 9.15.1 oder höher  a| 
Nicht unterstützt



| 9.14.1 | Unterstützt 


| 9.13.1 | Unterstützt 


| 9.12.1 | Unterstützt 


| 9.11.1 | Unterstützt 


.5+| 9.9.1 | 9.14.1 oder später  a| 
Nicht unterstützt



| 9.13.1 | Unterstützt 


| 9.12.1 | Unterstützt 


| 9.11.1 | Unterstützt 


| 9.10.1 | Unterstützt 


.5+| 9,8 | 9.13.1 oder später  a| 
Nicht unterstützt



| 9.12.1 | Unterstützt 


| 9.11.1 | Unterstützt 


| 9.10.1  a| 
Unterstützt



| 9.9.1 | Unterstützt 
|===


== Hinzufügen neuer Nodes zu einem ONTAP Cluster

Wenn Sie dem Cluster neue Nodes hinzufügen möchten und für diese Nodes eine Mindestversion von ONTAP erforderlich ist, die später ist als die Version, die derzeit im Cluster ausgeführt wird, müssen Sie vor dem Hinzufügen der neuen Nodes alle unterstützten Software-Upgrades auf den vorhandenen Nodes im Cluster durchführen. Idealerweise aktualisieren Sie alle vorhandenen Nodes auf die Mindestversion von ONTAP, die von den Nodes benötigt wird, die Sie dem Cluster hinzufügen möchten. Ist dies jedoch nicht möglich, da einige Ihrer vorhandenen Nodes die neuere Version von ONTAP nicht unterstützen, müssen Sie im Rahmen des Upgrades für einen begrenzten Zeitraum einen gemischten Versionsstatus eingeben.

.Schritte
. link:concept_upgrade_methods.html["Upgrade"] Die Knoten, die die von Ihren neuen Controllern benötigte minimale ONTAP Version nicht unterstützen, werden auf die höchste von ihnen unterstützte ONTAP Version aktualisiert.
+
Wenn Sie beispielsweise ein FAS8080 mit ONTAP 9.5 betreiben und eine neue C-Series-Plattform mit ONTAP 9.12.1 hinzufügen, sollten Sie Ihr FAS8080 auf ONTAP 9.8 aktualisieren (das ist die höchste ONTAP Version, die es unterstützt).

. link:../system-admin/add-nodes-cluster-concept.html["Fügen Sie die neuen Nodes dem Cluster hinzu"^].
. link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-create-aggregate-move-volumes.html["Migrieren der Daten"^] Von den Nodes, die aus dem Cluster entfernt werden, zu den neu hinzugefügten Nodes.
. link:../system-admin/remove-nodes-cluster-concept.html["Entfernen Sie die nicht unterstützten Nodes aus dem Cluster"^].
. link:concept_upgrade_methods.html["Upgrade"] den Cluster auf die gleiche ONTAP Version und den gleichen Patch-Level umzustellen, die auf den neuen Knoten ausgeführt werden, oder auf die link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU2["Neueste empfohlene Patch-Version"^] für die ONTAP -Version, die auf den neuen Knoten läuft.
. Überprüfen Sie, ob auf allen Knoten die gleiche ONTAP Version ausgeführt wird.
+
.. Zeigen Sie die auf dem Cluster ausgeführte ONTAP Version an:
+
[source, cli]
----
version
----
.. Zeigen Sie die ONTAP Version an, die auf jedem Knoten des Clusters ausgeführt wird:
+
[source, cli]
----
version *
----


+
Wenn es einen Unterschied zwischen der in der Ausgabe gemeldeten ONTAP Version für die `version *` (Cluster) und `version` (Einzelknoten)-Befehle, aktualisieren Sie alle Knoten auf dieselbe ONTAP und Patch-Version, indem Sie Folgendes ausführen: link:concept_upgrade_methods.html["Cluster-Image-Aktualisierung"]Die



Weitere Informationen zur Datenmigration finden Sie unter:

* link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-create-aggregate-move-volumes.html["Erstellung eines Aggregats und Verschiebung von Volumes zu den neuen Nodes"^]
* link:https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_linux_iscsi_hosts_from_mcc_fc_to_mcc_ip_nodes.html#setting-up-new-iscsi-connections["Einrichten neuer iSCSI-Verbindungen für SAN-Volume-Verschiebungen"^]
* link:../encryption-at-rest/encrypt-existing-volume-task.html["Verschieben von Volumes mit Verschlüsselung"^]

