---
permalink: upgrade/concept_how_firmware_is_updated_during_upgrade.html 
sidebar: sidebar 
keywords: ontap, upgrade, how, firmware, updated, during 
summary: Sie müssen Ihre Firmware vor einem ONTAP-Upgrade nicht aktualisieren.  Die Firmware für das Cluster ist im ONTAP Upgrade-Paket enthalten und wird im Rahmen des Upgrade-Prozesses installiert. 
---
= Booten Sie den SP oder BMC neu, um das Firmware-Update während eines ONTAP Upgrades vorzubereiten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor einem ONTAP-Upgrade müssen Sie Ihre Firmware nicht manuell aktualisieren. Die Firmware für das Cluster ist im ONTAP Upgrade-Paket enthalten und wird auf das Boot-Gerät jedes Node kopiert. Die neue Firmware wird dann im Rahmen des Upgrades installiert.

Die Firmware für die folgenden Komponenten wird automatisch aktualisiert, wenn die Version im Cluster älter als die im ONTAP-Upgrade-Paket enthaltene Firmware ist:

* BIOS/LOADER
* Service-Prozessor (SP) oder Baseboard-Management-Controller (BMC)
* Storage Shelf
* Festplatte
* Flash Cache


Um sich auf ein reibungsloses Update vorzubereiten, sollten Sie den SP oder BMC neu starten, bevor das Upgrade beginnt.

.Schritt
. Starten Sie vor dem Upgrade den SP oder BMC neu:
+
[source, cli]
----
system service-processor reboot-sp -node node_name
----
+
Starten Sie jeweils nur einen SP oder BMC neu.  Warten Sie, bis der neu gestartete SP oder BMC vollständig wiederverwendet wird, bevor Sie den nächsten neu starten.



Das können Sie auch link:../update/firmware-task.html["Aktualisieren Sie die Firmware manuell"] Zwischen ONTAP-Upgrades.  Wenn Sie Active IQ haben, können Sie dies link:https://activeiq.netapp.com/system-firmware/["Zeigen Sie die Liste der derzeit in Ihrem ONTAP-Image enthaltenen Firmware-Versionen an"^].

Aktualisierte Firmware-Versionen sind wie folgt verfügbar:

* link:https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["System-Firmware (BIOS, BMC, SP)"^]
* link:https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Platten-Shelf Firmware"^]
* link:https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Festplatten- und Flash Cache Firmware"^]

