---
permalink: upgrade/considerations-for-s3-snapmirror-concept.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, considerations, s3, snapmirror, license 
summary: Wenn Sie S3 SnapMirror verwenden, sollten Sie vor dem Upgrade von ONTAP Ihre Lizenzen überprüfen 
---
= Überprüfen Sie die Lizenzierung für S3 SnapMirror Konfigurationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie vor dem Upgrade von ONTAP S3 SnapMirror verwenden und ein Upgrade auf ONTAP 9.12.1 oder höher durchführen, sollten Sie überprüfen, ob Sie über die richtigen SnapMirror Lizenzen verfügen.

Nach dem Upgrade von ONTAP können Lizenzierungsänderungen, die zwischen ONTAP 9.11.1 und älteren Versionen sowie ONTAP 9.12.1 und höher vorgenommen wurden, zu einem Fehlschlagen von S3 SnapMirror Beziehungen führen.



== ONTAP 9.11.1 und früher

* Bei der Replizierung zu einem von NetApp gehosteten Ziel-Bucket (ONTAP S3 oder StorageGRID) prüft S3 SnapMirror die synchrone Lizenz, die vor der Einführung der Software Suite im Datensicherungspaket enthalten ist. link:../system-admin/manage-licenses-concept.html["ONTAP One"]
* Bei der Replizierung zu einem nicht von NetApp stammenden Ziel-Bucket prüft S3 SnapMirror SnapMirror die im Hybrid-Cloud-Bundle enthaltene Lizenz, die vor der Einführung der Software Suite zur Verfügung stand link:../system-admin/manage-licenses-concept.html["ONTAP One"] .




== ONTAP 9.12.1 und höher

* Bei der Replizierung zu einem von NetApp gehosteten Ziel-Bucket (ONTAP S3 oder StorageGRID) prüft S3 SnapMirror die im Datensicherungs-Bundle enthaltene S3-Lizenz, die vor der Einführung der Software Suite zur Verfügung stand link:../system-admin/manage-licenses-concept.html["ONTAP One"] .
* Bei der Replizierung zu einem nicht von NetApp stammenden Ziel-Bucket überprüft S3 SnapMirror die externe S3-SnapMirror Lizenz, die im Hybrid-Cloud-Bundle enthalten war, das vor der Einführung der Software Suite und der verfügbar war link:../system-admin/manage-licenses-concept.html["ONTAP One"] link:../data-protection/install-snapmirror-cloud-license-task.html["ONTAP One Kompatibilitätspaket"].




== Bestehende S3 SnapMirror Beziehungen

Bestehende S3 SnapMirror Beziehungen sollten nach einem Upgrade von ONTAP 9.11.1 oder einer älteren Version auf ONTAP 9.12.1 oder höher weiterhin funktionieren, selbst wenn das Cluster nicht über die neue Lizenzierung verfügt.

Die Erstellung neuer S3 SnapMirror Beziehungen schlägt fehl, wenn auf dem Cluster nicht die richtige Lizenz installiert ist.
