---
permalink: upgrade/considerations-for-s3-snapmirror-concept.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, considerations, s3, snapmirror, license 
summary: Wenn Sie SnapMirror S3 verwenden, sollten Sie Ihre Lizenzen vor dem Upgrade von ONTAP überprüfen 
---
= Überprüfen Sie die Lizenzierung für SnapMirror S3 Konfigurationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie vor dem Upgrade von ONTAP SnapMirror S3 verwenden und ein Upgrade auf ONTAP 9.12.1 oder höher durchführen, sollten Sie überprüfen, ob Sie über die richtigen SnapMirror-Lizenzen verfügen.

Nach dem Upgrade von ONTAP können Lizenzierungsänderungen, die zwischen ONTAP 9.11.1 und früher und ONTAP 9.12.1 und höher vorgenommen wurden, dazu führen, dass SnapMirror S3-Beziehungen fehlschlagen.



== ONTAP 9.11.1 und früher

* Bei der Replizierung zu einem von NetApp gehosteten Ziel-Bucket (ONTAP S3 oder StorageGRID) prüft SnapMirror S3 vor der Einführung der link:../system-admin/manage-licenses-concept.html["ONTAP One"]Software-Suite die im Datensicherungspaket enthaltene synchrone SnapMirror Lizenz.
* Bei der Replizierung zu einem nicht-NetApp-Ziel-Bucket prüft SnapMirror S3 die SnapMirror-Cloud-Lizenz, die im Hybrid-Cloud-Bundle enthalten war, das vor der Einführung der link:../system-admin/manage-licenses-concept.html["ONTAP One"] Software-Suite zur Verfügung stand.




== ONTAP 9.12.1 und höher

* Bei der Replizierung zu einem von NetApp gehosteten Ziel-Bucket (ONTAP S3 oder StorageGRID) prüft SnapMirror S3 die im Datensicherungspaket enthaltene SnapMirror S3-Lizenz, die vor der Einführung der link:../system-admin/manage-licenses-concept.html["ONTAP One"] Softwaresuite zur Verfügung stand.
* Bei der Replizierung zu einem nicht-NetApp-Ziel-Bucket überprüft SnapMirror S3 die externe SnapMirror S3-Lizenz, die im Hybrid-Cloud-Bundle enthalten war, das vor der Einführung link:../system-admin/manage-licenses-concept.html["ONTAP One"]der Software-Suite und der verfügbar warlink:../data-protection/install-snapmirror-cloud-license-task.html["ONTAP One Kompatibilitätspaket"].




== Vorhandene SnapMirror S3 Beziehungen

Bestehende SnapMirror S3 Beziehungen sollten nach einem Upgrade von ONTAP 9.11.1 oder einer älteren Version auf ONTAP 9.12.1 oder höher weiterhin funktionieren, selbst wenn das Cluster nicht über die neue Lizenzierung verfügt.

Das Erstellen neuer SnapMirror S3-Beziehungen schlägt fehl, wenn auf dem Cluster nicht die richtige Lizenz installiert ist.
