---
permalink: upgrade/how-long-upgrade-will-take.html 
sidebar: sidebar 
keywords: ontap, upgrade, plan, planning, upgrade advisor, advisor, active iq, create an upgrade plan, estimate upgrade, 
summary: Planen Sie mindestens 30 Minuten für vorbereitende Schritte, 60 Minuten für ein Upgrade jedes HA-Paars und mindestens 30 Minuten für die Schritte nach dem Upgrade ein 
---
= Bestimmen Sie, wie lange ein ONTAP Upgrade dauert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten mindestens 30 Minuten einplanen, um die vorbereitenden Schritte für ein ONTAP Upgrade durchzuführen, 60 Minuten für jedes HA-Paar und mindestens 30 Minuten für das Abschließen der Schritte nach dem Upgrade.


NOTE: Wenn Sie NetApp Verschlüsselung mit einem externen Verschlüsselungsmanagement-Server und dem Key Management Interoperability Protocol (KMIP) verwenden, sollten Sie davon ausgehen, dass das Upgrade für jedes HA-Paar länger als eine Stunde ist.

Diese Richtlinien für die Upgrade-Dauer basieren auf typischen Konfigurationen und Workloads. Anhand dieser Richtlinien können Sie die Dauer für ein unterbrechungsfreies Upgrade in Ihrer Umgebung abschätzen. Die tatsächliche Dauer Ihres Upgrade-Prozesses hängt von Ihrer individuellen Umgebung und der Anzahl der Nodes ab.
