---
permalink: upgrade/index.html 
sidebar: sidebar 
keywords: upgrade, ontap 
summary: ONTAP Upgrade-Verfahren 
---
= Upgrade ONTAP – Übersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Der link:concept_upgrade_methods.html["Methode, die Sie zum Upgrade verwenden"] Ihre ONTAP Software ist von Ihrer Konfiguration abhängig. Wenn dieser von Ihrer Konfiguration unterstützt wird, sollten Sie ein automatisiertes unterbrechungsfreies Upgrade (ANDU) mit System Manager durchführen.

Wenn Sie eine aktive haben link:https://www.netapp.com/us/services/support-edge.aspx["SupportEdge"] Vertrag für link:https://aiq.netapp.com/["Active IQ Digitalberater"], Bevor Sie Ihr Upgrade beginnen, sollten Sie Upgrade Advisor in Active IQ Digital Advisor starten, um Ihnen bei der Planung Ihres Upgrades zu helfen.

Die in diesem Abschnitt beschriebenen Verfahren führen Sie durch die Schritte, die vor und nach dem Upgrade ausgeführt werden sollten, einschließlich der zu lesenden Ressourcen und der erforderlichen Überprüfungen vor und nach dem Upgrade.
