---
permalink: upgrade/prepare.html 
sidebar: sidebar 
keywords: upgrade, ontap, prepare, digital advisor, preparation, before you upgrade, plan, upgrade overview, upgrade summary 
summary: Durch die Vorbereitung auf ein ONTAP Upgrade können Sie Upgrade-Risiken oder -Blockers identifizieren und minimieren und besondere Überlegungen einbeziehen, die für Ihre Konfiguration gelten. 
---
= Vorbereitung auf ein ONTAP Software-Upgrade ohne Upgrade Advisor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durch die ordnungsgemäße Vorbereitung auf ein ONTAP Software-Upgrade können Sie potenzielle Upgrade-Risiken oder -Blockierungen erkennen und minimieren, bevor Sie mit dem Upgrade-Prozess beginnen. Während der Upgrade-Vorbereitung können Sie auch alle besonderen Überlegungen identifizieren, die Sie vor dem Upgrade berücksichtigen müssen. Wenn beispielsweise der SSL-FIPS-Modus auf Ihrem Cluster aktiviert ist und die Administratorkonten öffentliche SSH-Schlüssel zur Authentifizierung verwenden, müssen Sie überprüfen, ob der Host-Schlüsselalgorithmus in Ihrer ONTAP-Zielversion unterstützt wird.

Wenn Sie einen aktiven SupportEdge-Vertrag für haben link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["Digital Advisor"^], link:create-upgrade-plan.html["Planen Sie Ihr Upgrade mit Upgrade Advisor"]. Wenn Sie keinen Zugriff auf den digitalen Berater von Active IQ haben (auch als digitaler Berater bekannt), sollten Sie Folgendes tun, um ein ONTAP-Upgrade vorzubereiten.

. link:choose-target-version.html["Wählen Sie die gewünschte ONTAP Version aus"].
. Lesen Sie die Abschnitte _Upgrade Cautions_ und _Bekannte Probleme und Einschränkungen_ im Link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508 [ONTAP 9 Versionshinweise] für Ihre Zielversion.
+
Hinweise zu Upgrades beschreiben potenzielle Probleme, die Sie vor dem Upgrade beachten sollten. Bekannte Probleme und Einschränkungen beschreiben potenziell unerwartetes Systemverhalten, das nach dem Upgrade auftreten könnte.

+
Sie müssen sich mit Ihrem NetApp Konto anmelden oder ein Konto erstellen, um auf die Versionshinweise zuzugreifen.

. link:confirm-configuration.html["Bestätigen Sie den ONTAP-Support für Ihre Hardwarekonfiguration"].
+
Die Hardwareplattform, Cluster-Management-Switches und MetroCluster IP-Switches müssen die Zielversion unterstützen. Wenn Ihr Cluster für SAN konfiguriert ist, muss die SAN-Konfiguration vollständig unterstützt werden.

. link:task_check_for_common_configuration_errors_using_config_advisor.html["Verwenden Sie Active IQ Config Advisor, um zu überprüfen, ob keine allgemeinen Konfigurationsfehler vorliegen."]
. Lesen Sie den unterstützten ONTAPlink:concept_upgrade_paths.html#supported-upgrade-paths["Upgrade-Pfade"], um festzustellen, ob Sie ein direktes Upgrade durchführen können oder ob das Upgrade schrittweise abgeschlossen werden muss.
. link:task_verifying_the_lif_failover_configuration.html["Überprüfen Sie Ihre LIF Failover-Konfiguration"].
+
Bevor Sie ein Upgrade durchführen, müssen Sie überprüfen, ob die Failover-Richtlinien und Failover-Gruppen des Clusters korrekt konfiguriert sind.

. link:concept_verify_svm_routing.html["Überprüfen Sie die SVM-Routing-Konfiguration"].
. link:special-considerations.html["Überprüfen Sie besondere Überlegungen"] Für Ihr Cluster.
+
Wenn bestimmte Konfigurationen im Cluster vorhanden sind, müssen Sie vor dem Start eines ONTAP-Softwareupgrades bestimmte Aktionen durchführen.

. link:reboot-sp-bmc.html["Starten Sie den SP oder BMC neu"].

