---
permalink: upgrade/reboot-sp-bmc.html 
sidebar: sidebar 
keywords: ontap, upgrade, how, firmware, updated, during, digital advisor 
summary: Sie müssen Ihre Firmware vor einem ONTAP Upgrade nicht aktualisieren. Die Firmware für Ihr Cluster ist im ONTAP Upgrade Paket enthalten und wird im Rahmen des Upgrade Prozesses installiert. 
---
= SP oder BMC neu starten, um die Firmware-Aktualisierung während eines ONTAP Upgrades vorzubereiten.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor einem ONTAP Upgrade ist keine manuelle Firmware-Aktualisierung erforderlich. Die Firmware für Ihren Cluster ist im ONTAP Upgrade Paket enthalten und wird auf das Boot-Gerät jedes Knotens kopiert. Die neue Firmware wird anschließend im Rahmen des Upgrade-Prozesses installiert.

Die Firmware der folgenden Komponenten wird automatisch aktualisiert, wenn die Version in Ihrem Cluster älter ist als die Firmware, die im ONTAP Upgrade-Paket enthalten ist:

* BIOS/LOADER
* Service Processor (SP) oder Baseboard Management Controller (BMC)
* Storage Shelf
* Festplatte
* Flash Cache


Zur Vorbereitung eines reibungslosen Updates empfiehlt es sich, den SP oder BMC vor Beginn des Upgrades neu zu starten.

Ein Neustart kann mit der ONTAP CLI, dem SP oder dem BMC durchgeführt werden.

[role="tabbed-block"]
====
.CLI
--
. SP oder BMC neu starten:
+
[source, cli]
----
system service-processor reboot-sp -node <node_name>
----


--
.SP
--
. Starten Sie die SP neu:
+
[source, cli]
----
sp reboot
----


--
.BMC
--
. Starten Sie die BMC neu:
+
[source, cli]
----
bmc reboot
----


--
====
Nur jeweils einen SP oder BMC neu starten. Warten, bis der neu gestartete SP oder BMC vollständig neu gestartet wurde, bevor der nächste neu gestartet wird.

Das ist auch link:../update/firmware-task.html["Firmware manuell aktualisieren"] zwischen ONTAP Upgrades möglich. Wenn Sie Digital Advisor haben, kann link:https://activeiq.netapp.com/system-firmware/["Die Liste der Firmware-Versionen, die derzeit in Ihrem ONTAP Image enthalten sind, wird angezeigt."^].

Aktualisierte Firmware-Versionen sind wie folgt verfügbar:

* link:https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["Systemfirmware (BIOS, BMC, SP)"^]
* link:https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Shelf Firmware"^]
* link:https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Festplatten- und Flash Cache-Firmware"^]

