---
permalink: upgrade/remove-ems-lif-service-task.html 
sidebar: sidebar 
keywords: ontap, upgrade, after, post, ems, event, management, system, lifs, messages, not, delivered 
summary: Nach dem Upgrade von ONTAP 9.7 oder früher auf 9.8 oder später kann es erforderlich sein, bei Verwendung von EMS den EMS LIF-Service aus bestimmten Netzwerkservice-Richtlinien zu entfernen. 
---
= Nach einem ONTAP Upgrade den EMS LIF Netzwerkservice aus den Netzwerkdienstrichtlinien entfernen.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie vor dem Upgrade von ONTAP 9.7 oder früher auf ONTAP 9.8 oder später Event Management System (EMS)-Nachrichten eingerichtet haben, werden Ihre EMS-Nachrichten nach dem Upgrade möglicherweise nicht zugestellt.

Während des Upgrades `management-ems`, das der EMS-LIF-Dienst ist, wird dieser allen bestehenden Dienstrichtlinien in den administrativen SVMs hinzugefügt. Dadurch können EMS-Meldungen von jedem der den Dienstrichtlinien zugeordneten LIFs gesendet werden. Wenn der ausgewählte LIF keine Erreichbarkeit zum Ziel der Ereignisbenachrichtigung hat, wird die Nachricht nicht zugestellt.

Um dies zu verhindern, sollte nach dem Upgrade der EMS LIF Dienst aus den Netzwerkservice-Richtlinien entfernt werden, die keine Erreichbarkeit zum Ziel bieten.

link:../networking/lifs_and_service_policies96.html#service-policies-for-system-svms["Weitere Informationen zu ONTAP LIFs und Servicerichtlinien"].

.Schritte
. Die LIFs und die zugehörigen Netzwerkservice-Richtlinien, über die EMS-Nachrichten gesendet werden können, lassen sich identifizieren:
+
[source, cli]
----
network interface show -fields service-policy -services management-ems
----
+
[listing]
----
vserver        lif            service-policy
-------------- ------------   ------------------
cluster-1      cluster_mgmt   default-management
cluster-1      node1-mgmt     default-management
cluster-1      node2-mgmt     default-management
cluster-1      inter_cluster  default-intercluster
4 entries were displayed.
----
. Jede LIF auf Konnektivität zum EMS-Ziel überprüfen:
+
[source, cli]
----
network ping -lif <lif_name> -vserver <svm_name> -destination <destination_address>
----
+
Dies ist auf jedem Knoten auszuführen.

+
.Beispiele
[listing]
----
cluster-1::> network ping -lif node1-mgmt -vserver cluster-1 -destination 10.10.10.10
10.10.10.10 is alive

cluster-1::> network ping -lif inter_cluster -vserver cluster-1 -destination 10.10.10.10
no answer from 10.10.10.10
----
. Erweiterte Berechtigungsstufe eingeben:
+
[source, cli]
----
set advanced
----
. Für die LIFs, die keine Erreichbarkeit haben, den  `management-ems`LIF-Service aus den entsprechenden Service-Richtlinien entfernen:
+
[source, cli]
----
network interface service-policy remove-service -vserver <svm_name> -policy <service_policy_name> -service management-ems
----
+
Weitere Informationen zu  `network interface service-policy remove-service` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-service-policy-remove-service.html["ONTAP-Befehlsreferenz"^].

. Es sollte sichergestellt sein, dass die management-ems LIF nun nur noch mit den LIFs verknüpft ist, die die Erreichbarkeit des EMS-Ziels bereitstellen:
+
[source, cli]
----
network interface show -fields service-policy -services management-ems
----

