---
sidebar: sidebar 
permalink: upgrade/resume-upgrade-after-andu-error.html 
keywords: netapp, ontap, automate, automatic, automated, upgrade, nondisruptive, nondisruptively, non-disruptive update, nondisruptive upgrade, upgrade a cluster, shift workload between clusters, hardware platform, configuration, software image, update, update ONTAP, update software, ndu 
summary: Sie können die ONTAP Version auf Ihrem Cluster unterbrechungsfrei aktualisieren. 
---
= Setzen Sie das ONTAP-Softwareupgrade nach einem Fehler im automatischen Upgradeprozess fort
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn ein automatisiertes ONTAP-Softwareupgrade aufgrund eines Fehlers angehalten wird, sollten Sie den Fehler beheben und dann mit dem Upgrade fortfahren.  Nachdem der Fehler behoben ist, können Sie den automatischen Aktualisierungsprozess fortsetzen oder den Aktualisierungsprozess manuell abschließen. Wenn Sie mit dem automatischen Upgrade fortfahren möchten, führen Sie keine der Aktualisierungsschritte manuell aus.

.Schritte
[role="tabbed-block"]
====
.System Manager
--
. Führen Sie je nach der verwendeten ONTAP-Version einen der folgenden Schritte aus:
+
|===


| Wenn Sie laufen... | Dann... 


 a| 
ONTAP 9.8 oder höher
 a| 
Klicken Sie Auf *Cluster* > *Übersicht*



 a| 
ONTAP 9.7, 9.6 oder 9.5
 a| 
Klicken Sie Auf *Konfiguration* > *Cluster* > *Update*.



 a| 
ONTAP 9.4 oder früher
 a| 
** Klicken Sie Auf *Konfiguration* > *Cluster Update*.
** Klicken Sie in der rechten Ecke des Fensters *Übersicht* auf die drei blauen vertikalen Punkte und wählen Sie *ONTAP-Aktualisierung*.


|===
. Fahren Sie mit dem automatischen Upgrade fort, oder brechen Sie es ab, und fahren Sie manuell fort.
+
|===


| Ihr Ziel ist | Dann... 


 a| 
Automatisches Upgrade fortsetzen
 a| 
Klicken Sie Auf *Fortsetzen*.



 a| 
Brechen Sie das automatische Upgrade ab, und fahren Sie manuell fort
 a| 
Klicken Sie Auf *Abbrechen*.

|===


--
.CLI
--
. Aktualisierungsfehler anzeigen:
+
[source, cli]
----
cluster image show-update-progress
----
. Beheben Sie den Fehler.
. Aktualisierung fortsetzen:
+
|===


| Ihr Ziel ist | Geben Sie den folgenden Befehl ein... 


 a| 
Automatisches Upgrade fortsetzen
 a| 
[source, cli]
----
cluster image resume-update
----


 a| 
Brechen Sie das automatische Upgrade ab, und fahren Sie manuell fort
 a| 
[source, cli]
----
cluster image cancel-update
----
|===


--
====
.Nachdem Sie fertig sind
link:task_what_to_do_after_upgrade.html["Prüfungen nach dem Upgrade durchführen"].
