---
permalink: upgrade/snapmirror-cascade-relationship-blocked.html 
sidebar: sidebar 
keywords: ontap, upgrade, 9.9.1. 9.10.1, update, cascade, LTR, long term retention, snapshots, considerations, secondary storage 
summary: Wenn auf Ihrem Cluster eine SnapMirror Kaskadenbeziehung konfiguriert ist, kann es erforderlich sein, Langzeitaufbewahrungs-Snapshots zu deaktivieren, bevor ein Upgrade durchgeführt wird. 
---
= Langzeit-Snapshots sollten vor dem ONTAP Upgrade deaktiviert werden.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In einer Beziehung von kaskadierten Volumes werden Langzeitaufbewahrungs-Snapshots nur auf dem finalen SnapMirror Ziel-Volume der Kaskade in allen Versionen von ONTAP 9 unterstützt. Die Aktivierung von Langzeitaufbewahrungs-Snapshots auf einem beliebigen Zwischen-Volume in der Kaskade führt zu fehlenden Backups und Snapshots.

Weitere Informationen zu link:../data-protection/long-term-retention-snapshots-concept.html["Langzeitaufbewahrungs-Snapshots"].

Wenn eine nicht unterstützte Konfiguration vorliegt, bei der Langzeit-Snapshots auf einem mittleren Volume einer Kaskade aktiviert wurden, sollte der technische Support kontaktiert und der Link https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/Cascading_a_volume_with_Long-Term_Retention_(long-termretention)_snapshots_enabled_is_not_supported[NetApp Knowledge Base: Cascading a volume with Long-Term Retention (LTR) snapshots enabled is not supported^] als Referenz angegeben werden, um Unterstützung zu erhalten.

Die folgenden ONTAP Versionen erlauben es nicht, Langzeit-Snapshots auf einem beliebigen Volume in einer Kaskade zu aktivieren, außer auf dem endgültigen SnapMirror Zielvolume.

* 9.15.1 und später
* 9.14.1P2 und P4 bis P14
* 9.13.1P9 bis P17
* 9.12.1 P12 bis P19
* 9.11.1P15 bis P20
* 9.10.1P18 bis P20
* 9.9.1P20


Bevor von einer ONTAP Version, die das Aktivieren von Langzeitaufbewahrungs-Snapshots auf mittleren Volumes einer Kaskade ermöglicht, auf eine ONTAP Version aktualisiert wird, die dies blockiert, ist es erforderlich, die Langzeitaufbewahrungs-Snapshots zu deaktivieren, um verpasste Backups und Snapshots zu vermeiden.

In den folgenden Szenarien ist eine Aktion erforderlich:

* Langzeit-Snapshots werden auf dem „B“-Volume in einer „A > B > C“ SnapMirror Kaskade oder auf einem anderen mittleren SnapMirror Zielvolume in Ihrer größeren Kaskade konfiguriert.
* Langzeitaufbewahrungs-Snapshots werden durch einen Zeitplan definiert, der auf eine SnapMirror Richtlinienregel angewendet wird. Diese Regel repliziert keine Snapshots vom Quellvolume, sondern erstellt sie direkt auf dem Zielvolume.
+

NOTE: Weitere Informationen zu Zeitplänen und SnapMirror-Richtlinien finden sich im link:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/How_does_the_schedule_parameter_in_an_ONTAP_9_SnapMirror_policy_rule_work["NetApp Knowledge Base: Wie funktioniert der Parameter "schedule" in einer ONTAP 9 SnapMirror-Richtlinienregel?"^].



.Schritte
. Die Regel zur langfristigen Aufbewahrung aus der SnapMirror Richtlinie für das mittlere Volume der Kaskade entfernen:
+
[listing]
----
Secondary::> snapmirror policy remove-rule -vserver <> -policy <> -snapmirror-label <>
----
+
Weitere Informationen zu  `snapmirror policy remove-rule` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-remove-rule.html["ONTAP-Befehlsreferenz"^].

. Die Regel für das SnapMirror Label ohne den langfristigen Aufbewahrungsplan erneut hinzufügen:
+
[listing]
----
Secondary::> snapmirror policy add-rule -vserver <> -policy <> -snapmirror-label <> -keep <>
----
+

NOTE: Das Entfernen von Snapshots zur Langzeitaufbewahrung aus den SnapMirror-Richtlinienregeln bedeutet, dass SnapMirror die Snapshots mit dem angegebenen Label vom Quell-Volume abruft. Es kann außerdem erforderlich sein, einen Zeitplan in der Snapshot-Richtlinie des Quell-Volumes hinzuzufügen oder zu ändern, um korrekt gekennzeichnete Snapshots zu erstellen.

+
Weitere Informationen zu  `snapmirror policy add-rule` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-add-rule.html["ONTAP-Befehlsreferenz"^].

. Gegebenenfalls kann ein Zeitplan in der Snapshot-Richtlinie des Quellvolumes geändert oder erstellt werden, damit Snapshots mit einer SnapMirror Bezeichnung erstellt werden können:
+
[listing]
----
Primary::> volume snapshot policy modify-schedule -vserver <> -policy <> -schedule <> -snapmirror-label <>
----
+
[listing]
----
Primary::> volume snapshot policy add-schedule -vserver <> -policy <> -schedule <> -snapmirror-label <> -count <>
----



NOTE: Langzeitaufbewahrungs-Snapshots können weiterhin auf dem endgültigen SnapMirror Zielvolume innerhalb einer SnapMirror Kaskadenkonfiguration aktiviert werden.
