---
permalink: upgrade/task_preparing_to_upgrade_nodes_using_netapp_storage_encryption_with_external_key_management_servers.html 
sidebar: sidebar 
keywords: ontap, upgrade, prepare, preparing, nodes, netapp, storage, encryption, nse, external, key management, servers 
summary: 'Wenn Sie NetApp Storage Encryption \(NSE\) auf ONTAP 9.2 oder einer älteren Version verwenden und ein Upgrade auf ONTAP 9.3 oder höher durchführen, müssen Sie vor dem Upgrade alle vorhandenen externen Verschlüsselungsmanagement \(KMIP\)-Serververbindungen über die Befehlszeilenschnittstelle \(CLI\) löschen.' 
---
= Löschen Sie vor dem Upgrade vorhandene Verbindungen für den externen Verschlüsselungsmanagement-Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie vor dem Upgrade von ONTAP ONTAP 9.2 oder eine frühere Version mit NetApp Storage Encryption (NSE) ausführen und ein Upgrade auf ONTAP 9.3 oder höher durchführen, müssen Sie alle vorhandenen Verbindungen des externen KMIP-Servers (Key Management) über die Befehlszeilenschnittstelle (CLI) löschen.

.Schritte
. Stellen Sie sicher, dass die NSE-Laufwerke entsperrt, geöffnet und auf die Standard-ID für die Herstellung 0x0: Eingestellt sind.
+
[source, cli]
----
storage encryption disk show -disk*
----
. Wechseln Sie in den erweiterten Berechtigungsmodus:
+
[source, cli]
----
set -privilege advanced
----
. Verwenden Sie die Standard-Manufaktur Secure ID 0x0, um den FIPS-Schlüssel den Self-Encrypting Disks (SEDs) zuzuweisen:
+
[source, cli]
----
storage encryption disk modify -fips-key-id 0x0 -disk *
----
. Vergewissern Sie sich, dass alle Festplatten den FIPS-Schlüssel zugewiesen haben:
+
[source, cli]
----
storage encryption disk show-status
----
. Überprüfen Sie, ob der *Modus* für alle Festplatten auf Daten eingestellt ist
+
[source, cli]
----
storage encryption disk show
----
. Zeigen Sie die konfigurierten KMIP-Server an:
+
[source, cli]
----
security key-manager show
----
. Löschen Sie die konfigurierten KMIP-Server:
+
[source, cli]
----
security key-manager delete -address kmip_ip_address
----
. Löschen Sie die Konfiguration des externen Schlüsselmanagers:
+
[source, cli]
----
security key-manager delete-kmip-config
----
+

NOTE: In diesem Schritt werden die NSE-Zertifikate nicht entfernt.



.Wie es weiter geht
Nach Abschluss des Upgrades müssen Sie die KMIP-Serververbindungen neu konfigurieren.

.Verwandte Informationen
xref:task_reconfiguring_kmip_servers_connections_after_upgrading_to_ontap_9_3_or_later.adoc[Neukonfigurieren von KMIP-Serververbindungen nach dem Upgrade auf ONTAP 9.3 oder höher]
