---
permalink: upgrade/task_updating_an_ontap_cluster_disruptively.html 
sidebar: sidebar 
keywords: ontap, upgrade, disruptively 
summary: Wenn Sie Ihren Cluster für ein Upgrade auf eine neue ONTAP Version offline nehmen können, kann die disruptive Upgrade-Methode verwendet werden. 
---
= Manuelles, unterbrechendes ONTAP Upgrade über die CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie Ihren Cluster für ein Upgrade auf eine neue ONTAP Version offline nehmen können, kann die disruptive Upgrade-Methode verwendet werden. Diese Methode umfasst mehrere Schritte: Deaktivieren des Storage Failover für jedes HA-Paar, Neustart jedes Knotens im Cluster und anschließendes erneutes Aktivieren des Storage Failover.

* Sie müssen link:download-software-image.html["herunterladen"] und link:install-software-manual-upgrade.html["installieren"] das Software-Image verwenden.
* Wenn Sie in einer SAN-Umgebung arbeiten, müssen alle SAN Clients heruntergefahren oder angehalten werden, bis das Upgrade abgeschlossen ist.
+
Wenn SAN-Clients vor einem unterbrechenden Upgrade nicht heruntergefahren oder angehalten werden, treten Fehler in den Client-Dateisystemen und Anwendungen auf, die nach Abschluss des Upgrades eine manuelle Wiederherstellung erfordern können.



Bei einem Upgrade mit Unterbrechung ist eine Ausfallzeit erforderlich, da die Speicherausfallsicherung für jedes HA-Paar deaktiviert ist und jeder Node aktualisiert wird. Wenn die Speicherausfallsicherung deaktiviert ist, verhält sich jeder Node wie ein Einzel-Node-Cluster, das heißt, die mit dem Node verbundenen Systemdienste werden für die Dauer des Systemneustarts unterbrochen.

.Schritte
. Die Berechtigungsstufe wird von admin auf advanced geändert, wobei bei entsprechender Aufforderung *y* eingegeben wird, um fortzufahren:
+
[source, cli]
----
set -privilege advanced
----
+
Die erweiterte Eingabeaufforderung (`*>`) erscheint.

. Das neue ONTAP Software-Image als Standard-Image festlegen:
+
[source, cli]
----
system image modify {-node * -iscurrent false} -isdefault true
----
+
Dieser Befehl verwendet eine erweiterte Abfrage, um das Ziel ONTAP Software-Image (das als alternatives Image installiert ist) so zu ändern, dass es für jeden Knoten zum Standard-Image wird.

. Es sollte überprüft werden, ob das neue ONTAP Software-Image als Standard-Image festgelegt ist:
+
[source, cli]
----
system image show
----
+
Im folgenden Beispiel ist Bild 2 die neue ONTAP Version und als Standardbild auf beiden Knoten festgelegt:

+
[listing]
----
cluster1::*> system image show
                 Is      Is                Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------- -------------------
node0
         image1  false   true    X.X.X     MM/DD/YYYY TIME
         image2  true    false   Y.Y.Y     MM/DD/YYYY TIME
node1
         image1  false   true    X.X.X     MM/DD/YYYY TIME
         image2  true    false   Y.Y.Y     MM/DD/YYYY TIME
4 entries were displayed.
----
. Einer der folgenden Schritte kann durchgeführt werden:
+
[cols="2*"]
|===
| Wenn der Cluster aus ... besteht | Folgendes ist zu tun... 


 a| 
Ein Knoten
 a| 
Fahren Sie mit dem nächsten Schritt fort.



 a| 
Zwei Knoten
 a| 
.. Cluster-Hochverfügbarkeit deaktivieren:
+
[source, cli]
----
cluster ha modify -configured false
----
+
Geben Sie  `y` ein, um fortzufahren, wenn Sie dazu aufgefordert werden.

.. Storage-Failover für das HA-Paar deaktivieren:
+
[source, cli]
----
storage failover modify -node * -enabled false
----




 a| 
Mehr als zwei Knoten
 a| 
Storage-Failover für jedes HA-Paar im Cluster deaktivieren:

[source, cli]
----
storage failover modify -node * -enabled false
----
|===
. Einen Node im Cluster neu starten:
+
[source, cli]
----
system node reboot -node nodename -ignore-quorum-warnings
----
+

IMPORTANT: Nicht mehr als ein Node darf gleichzeitig neu gestartet werden.

+
Der Knoten startet das neue ONTAP Image. Die ONTAP Anmeldeaufforderung erscheint und zeigt damit an, dass der Neustartvorgang abgeschlossen ist.

. Nachdem der Knoten oder die Knotengruppe mit dem neuen ONTAP Image neu gestartet wurde, ist die Berechtigungsstufe auf „Erweitert“ zu setzen:
+
[source, cli]
----
set -privilege advanced
----
+
*y* eingeben, wenn zur Fortsetzung aufgefordert wird

. Bestätigen Sie, dass die neue Software ausgeführt wird:
+
[source, cli]
----
system node image show
----
+
Im folgenden Beispiel ist image1 die neue ONTAP Version und als aktuelle Version auf node0 festgelegt:

+
[listing]
----
cluster1::*> system node image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    X.X.X       MM/DD/YYYY TIME
         image2  false   false   Y.Y.Y      MM/DD/YYYY TIME
node1
         image1  true    false   X.X.X      MM/DD/YYYY TIME
         image2  false   true    Y.Y.Y      MM/DD/YYYY TIME
4 entries were displayed.
----
. Es sollte überprüft werden, ob das Upgrade erfolgreich abgeschlossen wurde:
+
.. Stellen Sie die Berechtigungsstufe auf „Erweitert“ ein:
+
[source, cli]
----
set -privilege advanced
----
.. Es sollte überprüft werden, ob der Upgrade-Status für jeden Node abgeschlossen ist:
+
[source, cli]
----
system node upgrade-revert show -node nodename
----
+
Der Status sollte als abgeschlossen angezeigt werden.

+
Wenn der Status nicht vollständig ist, link:http://mysupport.netapp.com/["Den NetApp Support kontaktieren"^] sofort.

.. Zurück zur Administrator-Privilegstufe:
+
[source, cli]
----
set -privilege admin
----


. Schritte 5 bis 8 sind für jeden weiteren Node zu wiederholen.
. Besteht der Cluster aus zwei oder mehr Knoten, wird das Storage-Failover für jedes HA-Paar im Cluster aktiviert:
+
[source, cli]
----
storage failover modify -node * -enabled true
----
. Besteht der Cluster nur aus zwei Knoten, kann die Cluster-High Availability aktiviert werden:
+
[source, cli]
----
cluster ha modify -configured true
----


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/storage-failover-modify.html["storage failover modify"^]

