---
permalink: upgrade/task-prep-node-upgrade-nse-with-ext-kmip-servers.html 
sidebar: sidebar 
keywords: ontap, upgrade, prepare, preparing, nodes, netapp, storage, encryption, nse, external, key management, servers 
summary: Wenn Sie die NetApp-Speicherverschlüsselung unter ONTAP 9.2 oder früher verwenden und ein Upgrade auf 9.3 oder höher durchführen, löschen Sie die Verbindungen des externen Schlüsselverwaltungsservers, bevor Sie ein Upgrade durchführen. 
---
= Löschen Sie vorhandene externe Verbindungen des Schlüsselverwaltungsservers, bevor Sie ein Upgrade von ONTAP durchführen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie vor dem Upgrade von ONTAP ONTAP 9.2 oder eine frühere Version mit NetApp Storage Encryption (NSE) ausführen und ein Upgrade auf ONTAP 9.3 oder höher durchführen, müssen Sie alle vorhandenen Verbindungen des externen KMIP-Servers (Key Management) über die Befehlszeilenschnittstelle (CLI) löschen.

.Schritte
. Stellen Sie sicher, dass die NSE-Laufwerke entsperrt, geöffnet und auf die Standard-ID für die Herstellung 0x0: Eingestellt sind.
+
[source, cli]
----
storage encryption disk show -disk *
----
. Wechseln Sie in den erweiterten Berechtigungsmodus:
+
[source, cli]
----
set -privilege advanced
----
. Verwenden Sie die Standard-Manufaktur Secure ID 0x0, um den FIPS-Schlüssel den Self-Encrypting Disks (SEDs) zuzuweisen:
+
[source, cli]
----
storage encryption disk modify -fips-key-id 0x0 -disk *
----
. Vergewissern Sie sich, dass alle Festplatten den FIPS-Schlüssel zugewiesen haben:
+
[source, cli]
----
storage encryption disk show-status
----
. Überprüfen Sie, ob der *Modus* für alle Festplatten auf Daten eingestellt ist
+
[source, cli]
----
storage encryption disk show
----
. Zeigen Sie die konfigurierten KMIP-Server an:
+
[source, cli]
----
security key-manager show
----
. Löschen Sie die konfigurierten KMIP-Server:
+
[source, cli]
----
security key-manager delete -address <kmip_ip_address>
----
. Löschen Sie die Konfiguration des externen Schlüsselmanagers:
+
[source, cli]
----
security key-manager delete-kmip-config
----
+

NOTE: In diesem Schritt werden die NSE-Zertifikate nicht entfernt.



.Wie es weiter geht
Nachdem die Aktualisierung abgeschlossen ist, müssen Sie xref:task_reconfiguring_kmip_servers_connections_after_upgrading_to_ontap_9_3_or_later.adoc[Konfigurieren Sie die KMIP-Serververbindungen neu].
