---
permalink: upgrade/task_verifying_the_san_configuration_after_an_upgrade.html 
sidebar: sidebar 
keywords: ontap, upgrade, post, after, san, verify 
summary: Überprüfen Sie nach einem ONTAP Upgrade in einer SAN-Umgebung, ob jeder Initiator, der vor dem Upgrade mit einer LIF verbunden war, erfolgreich mit der LIF verbunden wurde 
---
= Überprüfen Sie die SAN-Konfiguration nach einem Upgrade
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach einem ONTAP Upgrade sollten Sie in einer SAN-Umgebung überprüfen, ob jeder Initiator, der mit einer LIF verbunden war, vor dem Upgrade erfolgreich mit der LIF verbunden wurde.

. Vergewissern Sie sich, dass jeder Initiator mit dem richtigen LIF verbunden ist.
+
Sie sollten die Liste der Initiatoren mit der Liste vergleichen, die Sie während der Upgrade-Vorbereitung erstellt haben. Wenn Sie ONTAP 9.11.1 oder höher verwenden, zeigen Sie den Verbindungsstatus mit System Manager an, da die Anzeige dort wesentlich klarer ist als die CLI.

+
[role="tabbed-block"]
====
.System Manager
--
.. Klicken Sie in System Manager auf *Hosts > SAN-Initiatorgruppen*.
+
Die Seite zeigt eine Liste der Initiatorgruppen an. Wenn die Liste groß ist, können Sie weitere Seiten der Liste anzeigen, indem Sie auf die Seitenzahlen unten rechts auf der Seite klicken.

+
In den Spalten werden verschiedene Informationen zu den Initiatorgruppen angezeigt. Ab 9.11.1 wird auch der Verbindungsstatus der Initiatorgruppe angezeigt. Bewegen Sie den Mauszeiger über Statuswarnungen, um Details anzuzeigen.



--
.CLI
--
** Liste der iSCSI-Initiatoren:
+
[source, cli]
----
iscsi initiator show -fields igroup,initiator-name,tpgroup
----
** Liste FC-Initiatoren:
+
[source, cli]
----
fcp initiator show -fields igroup,wwpn,lif
----


--
====

