---
permalink: upgrade/task_download_and_install_ontap_software_image.html 
sidebar: sidebar 
keywords: ontap, software, image, download, downloading, install, installing 
summary: 'Die ONTAP Software muss zuerst von der NetApp Support Site heruntergeladen werden. Anschließend kann sie entweder mithilfe des automatischen unterbrechungsfreien Upgrades (ANDU) oder manueller Upgrades installiert werden.' 
---
= Laden Sie das ONTAP Software-Image herunter und installieren Sie es
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die ONTAP Software muss zuerst von der NetApp Support Site heruntergeladen werden. Anschließend kann sie entweder mithilfe des automatischen unterbrechungsfreien Upgrades (ANDU) oder manueller Upgrades installiert werden.



== Laden Sie das Software-Image herunter

Je nach ONTAP Version können Sie das ONTAP Software Image von der NetApp Support Site an einen der folgenden Stellen kopieren: Einen HTTP-, HTTPS- oder FTP-Server im Netzwerk oder einen lokalen Ordner.

Sie sollten folgende wichtige Informationen beachten:

* Software-Images sind für Plattformmodelle spezifisch.
+
Sie müssen das richtige Image für Ihr Cluster erhalten. Software-Images, Informationen zu Firmware-Versionen und die neueste Firmware für Ihr Plattformmodell finden Sie auf der NetApp Support Site.

* Software-Images enthalten die neueste Version der System-Firmware, die verfügbar war, wenn eine bestimmte Version von ONTAP veröffentlicht wurde.
* Wenn Sie ein System mit NetApp Volume Encryption auf ONTAP 9.5 oder höher aktualisieren, müssen Sie das ONTAP Software-Image für Länder herunterladen, für die keine Beschränkungen bestehen. Dazu gehören auch NetApp Volume Encryption.
+
Wenn Sie zum Upgrade eines Systems mit NetApp Volume Encryption das ONTAP Software-Image für eingeschränkte Länder verwenden, kommt es zu einer Systempanik, während der Zugriff auf die Volumes verloren geht.

* Wenn Sie ein Upgrade von ONTAP 9.5 auf 9.9 durchführen, müssen Sie das Software-Image für ONTAP 9.7 und 9.9 kopieren.
* Wenn Sie ein Upgrade von ONTAP 9.3 auf 9.7 durchführen, müssen Sie das Software-Image für ONTAP 9.5 und 9.7 kopieren.


.Schritte
. Suchen Sie die Ziel-ONTAP-Software im link:http://mysupport.netapp.com/NOW/cgi-bin/software["Software-Downloads"] Der NetApp Support Site.
. Kopieren Sie das Software-Image (z. B. 97_q_image.tgz) an den entsprechenden Speicherort.
+
Je nach Ihrer ONTAP-Version ist der Speicherort ein Verzeichnis mit einem HTTP-, HTTPS- oder FTP-Server, von dem das Image an das lokale System oder einen lokalen Ordner auf dem Speichersystem bereitgestellt wird.

+
[cols="2"]
|===
| Sie können das Bild an diesen Speicherort kopieren... | ONTAP Versionen, wenn Sie diese ausführen... 


| Ein HTTP- oder FTP-Server | ONTAP 9.0 und höher 


| Ein lokaler Ordner | ONTAP 9.4 und höher 


| Auf dem lokalen System muss ein HTTPS-Server und das CA-Zertifikat des Servers installiert sein. | ONTAP 9.6 und höher 
|===




== Installieren Sie das Software-Image

Sie müssen das Ziel-Software-Image auf den Nodes des Clusters installieren.

* Wenn Sie ein System mit NetApp Volume Encryption auf ONTAP 9.5 oder höher aktualisieren, müssen Sie das ONTAP Software-Image für Länder ohne Beschränkungen heruntergeladen haben, darunter NetApp Volume Encryption.
+
Wenn Sie zum Upgrade eines Systems mit NetApp Volume Encryption das ONTAP Software-Image für eingeschränkte Länder verwenden, kommt es zu einer Systempanik, während der Zugriff auf die Volumes verloren geht.

* Wenn Sie ein Upgrade von ONTAP 9.5 direkt auf 9.9 durchführen, müssen Sie das Software-Image für ONTAP 9.7 und 9.9 herunterladen. Wenn Sie ein Upgrade von ONTAP 9.3 direkt auf 9.7 durchführen, müssen Sie das Software-Image für ONTAP 9.5 und 9.7 herunterladen.
+
Bei der automatischen Aktualisierung werden beide Bilder im Hintergrund verwendet, um das Upgrade abzuschließen.





=== Für automatisches, unterbrechungsfreies Upgrade (ANDU)

. Prüfen Sie das Image-Repository und löschen Sie alle vorherigen Bilder.
+
`cluster image package show-repository`

+
[listing]
----
cluster image package show-repository\
<<name_of_vsim|There are no packages in the repository.\r\n
----
. Laden Sie das Bild herunter.
+
`cluster image package get -url url_to_image_on_nss`

+
`cluster image package get -url http://10.60.132.98/x/eng/rlse/DOT/9.7P13X2/promo/9.7P13X2/x86_64.optimize/image.tgz`

. Überprüfen Sie, ob das Paket heruntergeladen wurde.
+
`cluster image package show-repository`

+
.Beispiel
[listing]
----
cluster image package show-repository -fields download-ver\
<<name_of_vsim| download-verX;X\r\n
<<name_of_vsim| Downloaded VersionX;X\r\n
<<name_of_vsim| ONTAP 9.10.1.X;X\r\n
----




=== Bei manuellen Upgrades

. Stellen Sie die Berechtigungsebene auf Erweitert ein, und geben Sie bei Aufforderung * y* ein, um fortzufahren: `set -privilege advanced`
+
Die erweiterte Eingabeaufforderung (`*>`Erscheint.

. Laden Sie das Bild herunter.
+
.. Wenn Sie ein Cluster ohne MetroCluster oder eine MetroCluster Konfiguration mit zwei Nodes aktualisieren, laden Sie das Image mit dem folgenden Befehl herunter:
+
`system node image update -node * -package _location_ -replace-package true -setdefault true -background true`

+
_Location_ kann ein Webserver oder ein lokaler Ordner sein, abhängig von der ONTAP-Version. Siehe `system node image update` Man-Page für Details.

+
Mit diesem Befehl wird das Software-Image gleichzeitig auf allen Nodes heruntergeladen und installiert. Geben Sie das nicht an, um das Image auf jedem Knoten einzeln herunterzuladen und zu installieren `-background` Parameter.

.. Wenn Sie eine MetroCluster Konfiguration mit vier oder acht Nodes aktualisieren, müssen Sie auf beiden Clustern den folgenden Befehl ausgeben:
+
`system node image update -node * -package location -replace-package true -background true -setdefault false`

+
Dieser Befehl verwendet eine erweiterte Abfrage, um das Ziel-Software-Image zu ändern, das als alternatives Image auf jedem Node installiert wird.



. Eingabe `y` Fortfahren, wenn Sie dazu aufgefordert werden.
. Vergewissern Sie sich, dass das Software-Image auf jedem Node heruntergeladen und installiert ist.
+
`system node image show-update-progress -node *`

+
Mit diesem Befehl wird der aktuelle Status des Downloads und der Installation des Software-Images angezeigt. Sie sollten diesen Befehl weiter ausführen, bis alle Knoten einen *Run Status* von *Exited* und einen *Exit Status* von *Erfolg* melden.

+
Der Befehl zum Aktualisieren des System-Node-Images kann fehlschlagen und zeigt Fehler- oder Warnmeldungen an. Nach Beheben von Fehlern oder Warnungen können Sie den Befehl erneut ausführen.

+
In diesem Beispiel wird ein Cluster mit zwei Nodes angezeigt, in dem das Software-Image auf beiden Nodes heruntergeladen und erfolgreich installiert wird:

+
[listing]
----
cluster1::*> system node image show-update-progress -node *
There is no update/install in progress
Status of most recent operation:
        Run Status:     Exited
        Exit Status:    Success
        Phase:          Run Script
        Exit Message:   After a clean shutdown, image2 will be set as the default boot image on node0.
There is no update/install in progress
Status of most recent operation:
        Run Status:     Exited
        Exit Status:    Success
        Phase:          Run Script
        Exit Message:   After a clean shutdown, image2 will be set as the default boot image on node1.
2 entries were acted on.
----

