---
permalink: upgrade/task_verify_cluster_after_upgrade.html 
sidebar: sidebar 
keywords: ontap, upgrade, upgrade, verify, status, health, post, after 
summary: Überprüfen Sie nach dem Upgrade von ONTAP die Clusterversion, den Clusterstatus und den Storage-Zustand.  Vergewissern Sie sich bei MetroCluster FC-Konfigurationen, dass die automatische ungeplante Umschaltung aktiviert ist. 
---
= Überprüfen Sie den Cluster nach dem ONTAP Upgrade
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Überprüfen Sie nach dem Upgrade von ONTAP die Clusterversion, den Clusterstatus und den Storage-Zustand.  Überprüfen Sie bei MetroCluster FC-Konfigurationen auch, ob das Cluster für die automatische ungeplante Umschaltung aktiviert ist.



== Überprüfen der Cluster-Version

Nachdem alle HA-Paare aktualisiert wurden, müssen Sie mit dem Befehl Version überprüfen, ob auf allen Nodes das Ziel-Release ausgeführt wird.

Die Cluster-Version ist die niedrigste Version von ONTAP, die auf einem beliebigen Node im Cluster ausgeführt wird. Wenn die Cluster-Version nicht die ONTAP-Zielversion ist, können Sie ein Cluster-Upgrade durchführen.

. Vergewissern Sie sich, dass die Cluster-Version die ONTAP-Zielversion ist:
+
[source, cli]
----
version
----
. Wenn die Cluster-Version nicht das Ziel-ONTAP-Release ist, sollten Sie den Upgrade-Status aller Nodes überprüfen:
+
[source, cli]
----
system node upgrade-revert show
----




== Überprüfen des Cluster-Systemzustands

Nach dem Upgrade eines Clusters sollten Sie überprüfen, ob die Nodes ordnungsgemäß sind und berechtigt sind, am Cluster teilzunehmen, und dass sich das Cluster in einem Quorum befindet.

. Vergewissern Sie sich, dass die Nodes im Cluster online sind und am Cluster teilnehmen können:
+
[source, cli]
----
cluster show
----
+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
node0                 true    true
node1                 true    true
----
+
Wenn ein Knoten fehlerhaft oder nicht geeignet ist, überprüfen Sie die EMS-Protokolle auf Fehler und ergreifen Sie Korrekturmaßnahmen.

. Legen Sie die Berechtigungsebene auf erweitert fest:
+
[source, cli]
----
set -privilege advanced
----
. Überprüfen Sie die Konfigurationsdetails für jeden RDB-Prozess.
+
** Die Epochen der relationalen Datenbank und Datenbank-Epochen sollten für jeden Node übereinstimmen.
** Der Quorum-Master pro Ring sollte für alle Knoten gleich sein.
+
Beachten Sie, dass für jeden Ring möglicherweise ein anderer Quorum-Master vorhanden ist.

+
|===


| So zeigen Sie diesen RDB-Prozess an: | Diesen Befehl eingeben... 


 a| 
Managementapplikation
 a| 
`cluster ring show -unitname mgmt`



 a| 
Volume-Standortdatenbank
 a| 
`cluster ring show -unitname vldb`



 a| 
Virtual Interface Manager
 a| 
`cluster ring show -unitname vifmgr`



 a| 
SAN Management-Daemon
 a| 
`cluster ring show -unitname bcomd`

|===
+
Dieses Beispiel zeigt den Datenbankprozess für den Speicherort des Volumes:



+
[listing]
----
cluster1::*> cluster ring show -unitname vldb
Node      UnitName Epoch    DB Epoch DB Trnxs Master    Online
--------- -------- -------- -------- -------- --------- ---------
node0     vldb     154      154      14847    node0     master
node1     vldb     154      154      14847    node0     secondary
node2     vldb     154      154      14847    node0     secondary
node3     vldb     154      154      14847    node0     secondary
4 entries were displayed.
----
. Wenn Sie in einer SAN-Umgebung arbeiten, vergewissern Sie sich, dass sich jeder Knoten in einem SAN-Quorum befindet:
+
[source, cli]
----
cluster kernel-service show
----
+
[listing]
----
cluster1::*> cluster kernel-service show
Master            Cluster           Quorum        Availability  Operational
Node              Node              Status        Status        Status
----------------- ----------------- ------------- ------------- -------------
cluster1-01       cluster1-01       in-quorum     true          operational
                  cluster1-02       in-quorum     true          operational
2 entries were displayed.
----


.Verwandte Informationen
link:../system-admin/index.html["Systemadministration"]



== Überprüfen, ob die automatische ungeplante Umschaltung aktiviert ist (nur MetroCluster FC-Konfigurationen)

Wenn sich Ihr Cluster in einer MetroCluster FC-Konfiguration befindet, sollten Sie nach dem Upgrade von ONTAP überprüfen, ob die automatische ungeplante Umschaltung aktiviert ist.

Wenn Sie eine MetroCluster IP-Konfiguration verwenden, überspringen Sie diesen Vorgang.

.Schritte
. Prüfen, ob die automatische ungeplante Umschaltung aktiviert ist:
+
[source, cli]
----
metrocluster show
----
+
Wenn die automatische ungeplante Umschaltung aktiviert ist, wird die folgende Anweisung in der Befehlsausgabe angezeigt:

+
[listing]
----
AUSO Failure Domain  auso-on-cluster-disaster
----
. Wenn die Anweisung nicht angezeigt wird, aktivieren Sie eine automatische ungeplante Umschaltung:
+
[source, cli]
----
metrocluster modify -auto-switchover-failure-domain auso-on-cluster-disaster
----
. Vergewissern Sie sich, dass eine automatische ungeplante Umschaltung aktiviert wurde:
+
[source, cli]
----
metrocluster show
----


.Verwandte Informationen
link:../disks-aggregates/index.html["Festplatten- und Aggregatmanagement"]
