---
permalink: upgrade/task_verifying_the_san_configuration.html 
sidebar: sidebar 
keywords: ontap, upgrade, verify, verifying, san, configuration 
summary: Bevor Sie ein Upgrade eines SAN-Clusters durchführen, sollten Sie überprüfen, ob jeder Host mit der richtigen Anzahl an direkten und indirekten Pfaden konfiguriert ist und dass jeder Host mit den richtigen LIFs verbunden ist. 
---
= Überprüfen Sie vor einem ONTAP-Upgrade die SAN-Hostkonfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Beim Upgrade von ONTAP in einer SAN-Umgebung ändert sich, welche Pfade direkt sind. Bevor Sie ein Upgrade eines SAN-Clusters durchführen, sollten Sie überprüfen, ob jeder Host mit der richtigen Anzahl an direkten und indirekten Pfaden konfiguriert ist und dass jeder Host mit den richtigen LIFs verbunden ist.

.Schritte
. Überprüfen Sie bei jedem Host, ob eine ausreichende Anzahl direkter und indirekter Pfade konfiguriert ist und jeder Pfad aktiv ist.
+
Jeder Host muss über einen Pfad zu jedem Node im Cluster verfügen.

. Vergewissern Sie sich, dass jeder Host auf jedem Node mit einer logischen Schnittstelle verbunden ist.
+
Nach dem Upgrade sollten Sie die Liste der Initiatoren zum Vergleich aufzeichnen. Wenn Sie ONTAP 9.11.1 oder höher verwenden, zeigen Sie den Verbindungsstatus mit System Manager an, da die Anzeige dort wesentlich klarer ist als die CLI.

+
[role="tabbed-block"]
====
.System Manager
--
.. Klicken Sie in System Manager auf *Hosts > SAN-Initiatorgruppen*.
+
Die Seite zeigt eine Liste der Initiatorgruppen an. Wenn die Liste groß ist, können Sie weitere Seiten der Liste anzeigen, indem Sie auf die Seitenzahlen unten rechts auf der Seite klicken.

+
In den Spalten werden verschiedene Informationen zu den Initiatorgruppen angezeigt. Ab 9.11.1 wird auch der Verbindungsstatus der Initiatorgruppe angezeigt. Bewegen Sie den Mauszeiger über Statuswarnungen, um Details anzuzeigen.



--
.CLI
--
** Liste der iSCSI-Initiatoren:
+
[source, cli]
----
iscsi initiator show -fields igroup,initiator-name,tpgroup
----
** Liste FC-Initiatoren:
+
[source, cli]
----
fcp initiator show -fields igroup,wwpn,lif
----


--
====

