---
permalink: upgrade/task_reconfiguring_kmip_servers_connections_after_upgrading_to_ontap_9_3_or_later.html 
sidebar: sidebar 
keywords: ontap, upgrade, reconfigure, reconfiguring, kmip, server, connections, 9.3, later 
summary: 'Nach einem Upgrade auf ONTAP 9.3 oder höher müssen Sie die Verbindungen des externen KMIP-Servers (Key Management) neu konfigurieren.' 
---
= Nach einem Upgrade von ONTAP 9.2 oder einer älteren Version werden KMIP-Serververbindungen neu konfiguriert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach dem Upgrade von ONTAP 9.2 oder einer älteren Version auf ONTAP 9.3 oder höher müssen Sie alle externen KMIP-Serververbindungen (Key Management) neu konfigurieren.

.Schritte
. Konfiguration der Schlüsselmanager-Konnektivität:
+
[source, cli]
----
security key-manager setup
----
. Fügen Sie Ihre KMIP-Server hinzu:
+
[source, cli]
----
security key-manager add -address <key_management_server_ip_address>
----
. Vergewissern Sie sich, dass KMIP-Server verbunden sind:
+
[source, cli]
----
security key-manager show -status
----
. Abfrage der Schlüsselserver:
+
[source, cli]
----
security key-manager query
----
. Neuen Authentifizierungsschlüssel und neue Passphrase erstellen:
+
[source, cli]
----
security key-manager create-key -prompt-for-key true
----
+
Die Passphrase muss mindestens 32 Zeichen lang sein.

. Abfrage des neuen Authentifizierungsschlüssels:
+
[source, cli]
----
security key-manager query
----
. Weisen Sie Ihren Self-Encrypting Disks (SEDs) den neuen Authentifizierungsschlüssel zu:
+
[source, cli]
----
storage encryption disk modify -disk <disk_ID> -data-key-id <key_ID>
----
+

NOTE: Stellen Sie sicher, dass Sie den neuen Authentifizierungsschlüssel aus Ihrer Abfrage verwenden.

. Weisen Sie den SEDs bei Bedarf einen FIPS-Schlüssel zu:
+
[source, cli]
----
storage encryption disk modify -disk <disk_id> -fips-key-id <fips_authentication_key_id>
----
+
Wenn Sie in Ihrer Sicherheitseinrichtung unterschiedliche Schlüssel für die Datenauthentifizierung und die FIPS 140-2-Authentifizierung verwenden müssen, sollten Sie jeweils einen separaten Schlüssel erstellen. Falls dies nicht der Fall ist, können Sie denselben Authentifizierungsschlüssel für die FIPS-Compliance verwenden, den Sie für den Datenzugriff verwenden.



.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-setup.html["Einrichtung des Sicherheitsschlüssel-Managers"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-modify.html["Speicherverschlüsselung Datenträger ändern"^]

