---
permalink: upgrade/task_setting_the_desired_nt_acl_permissions_display_level_for_nfs_clients.html 
sidebar: sidebar 
keywords: ontap, upgrade, setting, set, desired, nt, acl, permissions, display, level, nfs, clients 
summary: Nach dem Upgrade von ONTAP 8.3 hat sich die standardmäßige Verarbeitung für die Anzeige von NT ACL-Berechtigungen für NFS-Clients geändert. Sie sollten die Einstellung überprüfen und bei Bedarf auf die gewünschte Einstellung für Ihre Umgebung ändern. Diese Aufgabe gilt nicht, wenn Sie ein Upgrade von ONTAP 8.3.1 oder höher durchführen. 
---
= Legen Sie die Anzeigeebene für die gewünschten NT ACL-Berechtigungen für NFS-Clients fest
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach dem Upgrade von ONTAP 8.3 hat sich die standardmäßige Verarbeitung für die Anzeige von NT ACL-Berechtigungen für NFS-Clients geändert. Sie sollten die Einstellung überprüfen und bei Bedarf auf die gewünschte Einstellung für Ihre Umgebung ändern. Diese Aufgabe gilt nicht, wenn Sie ein Upgrade von ONTAP 8.3.1 oder höher durchführen.

In Multi-Protokoll-Umgebungen zeigt ONTAP den NFS-Clients die Berechtigungen von NTFS-Dateien und -Verzeichnissen basierend auf dem Zugriff an, den jeder Benutzer durch die NT ACL gewährt hat. In ONTAP 8.3 wird ONTAP standardmäßig für NFS-Clients die Berechtigung basierend auf dem maximalen Zugriff angezeigt, der von der NT-ACL gewährt wurde. Nach der Aktualisierung ändert sich die Standardeinstellung, um Berechtigungen basierend auf dem von der NT-ACL gewährten Mindestzugriff anzuzeigen. Diese Änderung bezieht sich auf neue und vorhandene Storage Virtual Machines (SVMs).

. Legen Sie die Berechtigungsebene auf erweitert fest: `set -privilege advanced`
. Überprüfen Sie die Einstellung für die Anzeige von NT ACL-Berechtigungen für NFS-Clients: `vserver nfs show -vserver vserver_name -fields ntacl-display-permissive-perms`
+
Nach dem Upgrade von 8.3 ist der Wert für diesen neuen Parameter deaktiviert, was bedeutet, dass ONTAP die Mindestberechtigungen anzeigt.

. Wenn Sie die maximalen Berechtigungen anzeigen möchten, ändern Sie die Einstellung nach Bedarf individuell für jede SVM: `vserver nfs modify -vserver vserver_name -ntacl-display-permissive-perms enabled`
. Vergewissern Sie sich, dass die Änderung wirksam wurde: `vserver nfs show -vserver vserver_name -fields ntacl-display-permissive-perms`
. Zurück zur Administratorberechtigungsebene: `set -privilege admin`

