---
permalink: upgrade/task_check_for_common_configuration_errors_using_config_advisor.html 
sidebar: sidebar 
keywords: upgrade, common, configuration, errors, check, config, advisor, before upgrade, before upgrading 
summary: Bevor ONTAP aktualisiert wird, empfiehlt sich die Verwendung des Active IQ Config Advisor Tools, um auf häufige Konfigurationsfehler zu prüfen. 
---
= Häufige Konfigurationsfehler vor einem Upgrade von ONTAP mit Active IQ Config Advisor erkennen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie ONTAP aktualisieren, kann mit dem Active IQ Config Advisor Tool auf häufige Konfigurationsfehler geprüft werden.

Active IQ Config Advisor ist ein Konfigurationsvalidierungstool für NetApp Systeme. Es kann sowohl an sicheren als auch an ungesicherten Standorten zur Datenerfassung und Systemanalyse eingesetzt werden.


NOTE: Der Support für Active IQ Config Advisor ist eingeschränkt und nur online verfügbar.

.Schritte
. Melden Sie sich bei der link:https://mysupport.netapp.com/site/global/["NetApp Support Site"^] Website an und wählen Sie anschließend *TOOLS* > *Tools*.
. Unter *Active IQ Config Advisor* auf  https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["App herunterladen"^] klicken.
. Active IQ Config Advisor kann heruntergeladen, installiert und ausgeführt werden.
. Nach dem Ausführen von Active IQ Config Advisor die Ausgabe des Tools prüfen und die bereitgestellten Empfehlungen berücksichtigen, um etwaige vom Tool festgestellte Probleme zu adressieren.

