---
permalink: upgrade/task_verifying_the_networking_and_storage_status_for_metrocluster_post_upgrade.html 
sidebar: sidebar 
keywords: ontap, post, after, upgrade, verify, networking, storage, status, metrocluster, mcc 
summary: Nachdem Sie in einer MetroCluster Konfiguration ein Update durchgeführt haben, überprüfen Sie den Status der LIFs, Aggregate und Volumes für jedes Cluster. 
---
= Nach einem ONTAP Upgrade überprüfen Sie den Netzwerk- und Storage-Status für MetroCluster Konfigurationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie ein ONTAP Cluster in einer MetroCluster Konfiguration aktualisiert haben, sollten Sie den Status der LIFs, Aggregate und Volumes für jedes Cluster überprüfen.

. Überprüfen Sie den LIF-Status:
+
[source, cli]
----
network interface show
----
+
Im normalen Betrieb müssen LIFs für Quell-SVMs einen Administratorstatus von „up“ aufweisen und sich auf ihren Home-Nodes befinden. LIFs für Ziel-SVMs müssen nicht auf ihren Home-Nodes up-to-located sein. Durch die Umschaltung verfügen alle LIFs über einen Administratorstatus von oben, müssen sich aber nicht auf ihren Home-Nodes befinden.

+
[listing]
----
cluster1::> network interface show
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            cluster1-a1_clus1
                         up/up    192.0.2.1/24       cluster1-01
                                                                   e2a     true
            cluster1-a1_clus2
                         up/up    192.0.2.2/24       cluster1-01
                                                                   e2b     true


cluster1-01
            clus_mgmt    up/up    198.51.100.1/24    cluster1-01
                                                                   e3a     true
            cluster1-a1_inet4_intercluster1
                         up/up    198.51.100.2/24    cluster1-01
                                                                   e3c     true
            ...

27 entries were displayed.
----
. Überprüfen Sie den Status der Aggregate:
+
[source, cli]
----
storage aggregate show -state !online
----
+
Mit diesem Befehl werden alle Aggregate angezeigt, die _Not_ online sind. Im normalen Betrieb müssen alle Aggregate am lokalen Standort online sein. Wenn die MetroCluster-Konfiguration jedoch um den Switch geht, können Root-Aggregate am Disaster-Recovery-Standort offline sein.

+
Dieses Beispiel zeigt ein Cluster im normalen Betrieb:

+
[listing]
----
cluster1::> storage aggregate show -state !online
There are no entries matching your query.
----
+
Dieses Beispiel zeigt ein Cluster in Switchover, in dem die Root-Aggregate am Disaster-Recovery-Standort offline sind:

+
[listing]
----
cluster1::> storage aggregate show -state !online
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
aggr0_b1
                0B        0B    0% offline      0 cluster2-01      raid_dp,
                                                                   mirror
                                                                   degraded
aggr0_b2
                0B        0B    0% offline      0 cluster2-02      raid_dp,
                                                                   mirror
                                                                   degraded
2 entries were displayed.
----
. Überprüfen Sie den Status der Volumes:
+
[source, cli]
----
volume show -state !online
----
+
Dieser Befehl zeigt alle Volumes an, die _Not_ online sind.

+
Wenn die MetroCluster-Konfiguration sich im normalen Betrieb befindet (sie befindet sich nicht im Switchover-Status), sollte die Ausgabe alle Volumes anzeigen, die zu den sekundären SVMs des Clusters gehören (diejenigen mit dem SVM-Namen, angehängt mit „-mc“).

+
Diese Volumes sind nur bei einem Switchover online verfügbar.

+
Dieses Beispiel zeigt einen Cluster im normalen Betrieb, bei dem die Volumes am Disaster-Recovery-Standort nicht online sind.

+
[listing]
----
cluster1::> volume show -state !online
  (volume show)
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vs2-mc    vol1         aggr1_b1     -          RW            -          -     -
vs2-mc    root_vs2     aggr0_b1     -          RW            -          -     -
vs2-mc    vol2         aggr1_b1     -          RW            -          -     -
vs2-mc    vol3         aggr1_b1     -          RW            -          -     -
vs2-mc    vol4         aggr1_b1     -          RW            -          -     -
5 entries were displayed.
----
. Vergewissern Sie sich, dass es keine inkonsistenten Volumes gibt:
+
[source, cli]
----
volume show -is-inconsistent true
----
+
Lesen Sie den Artikel link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Volume_Showing_WAFL_Inconsistent["Volume zeigt WAFL inkonsistent an"]der Knowledge Base, wie Sie die inkonsistenten Volumes bewältigen können.


