---
permalink: upgrade/task-change-svm-42v-xattrs-option.html 
sidebar: sidebar 
keywords: ontap, upgrade, svm, xattr, nfsv4.2 
summary: Bevor Sie ONTAP 9.12.1 und höher aktualisieren, stellen Sie sicher, dass Sie einen expliziten Wert für eine erweiterte Attributoption NFSv4.2 angeben, um NFS-Antwortfehler zu vermeiden. 
---
= Weisen Sie der Option v4.2-xattrs vor einem ONTAP-Upgrade einen expliziten Wert zu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie über einen NFSv4.2-Client verfügen, müssen Sie vor dem Upgrade von bestimmten Releases und Patches von ONTAP 9.12.1 und höher einen expliziten Wert für die erweiterte Attributoption NFSv4.2 angeben, um NFS-Antwortfehler nach dem Upgrade zu vermeiden.

Wenn der `v4.2-xattrs` Option vor dem ONTAP-Upgrade auf betroffene Versionen nie explizit ein Wert zugewiesen wird, werden NFSv4.2-Clients nicht darüber informiert, dass sich die Option Erweiterte Attribute des Servers geändert hat. Dies führt zu NFS-Antwortfehlern bei bestimmten `xattrs` Anrufen aufgrund von Client- und Serverabweichungen.

.Bevor Sie beginnen
Sie müssen einen expliziten Wert für die erweiterte Attributoption NFSv4.2 zuweisen, wenn Folgendes zutrifft:

* Sie verwenden NFSv4.2 mit einer SVM, die mit ONTAP 9.11.1 oder einer älteren Version erstellt wurde
* Sie führen ein ONTAP-Upgrade für eine der folgenden betroffenen Versionen und Patches durch:
+
** 9.12.1RC1 bis 9.12.1P11
** 9.13.1RC1 bis 9.13.1P8
** 9.14.1RC1 bis 9.14.1P1




.Über diese Aufgabe
Sie müssen ONTAP 9.12.1 oder höher ausführen, um den Wert mit dem in diesem Verfahren beschriebenen Befehl festzulegen.

Wenn `v4.2-xattrs` bereits auf festgelegt ist `enabled`, sollte es immer noch explizit auf zukünftige Unterbrechungen gesetzt werden `enabled`. Wenn Sie auf deaktiviert gesetzt `v4.2-xattrs` haben, können NFSv4.2-Clients bis zum erneuten Mounten oder der Einstellung der Option auf `enabled` „Ungültige Argumente“ Antworten erhalten `v4.2-xattrs`.

.Schritte
* Weisen Sie der Option einen expliziten Wert zu `v4.2-xattrs`:
+
[source, cli]
----
nfs modify -v4.2-xattrs <enabled/disabled> -vserver <vserver_name>
----


.Verwandte Informationen
https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-Issues/CONTAP-120160["NFS v4.2-xattrs-Feld wird nach Upgrades gespiegelt"^]
