---
permalink: upgrade/task_plan_without_upgrade_advisor.html 
sidebar: sidebar 
keywords: ontap, upgrade, plan, planning, upgrade, manually, manual 
summary: Als Best Practice-Methode empfiehlt es sich, Upgrade Advisor in Active IQ zu verwenden, um Ihr Upgrade zu planen. Wenn Sie keinen aktiven SupportEdge Vertrag für Active IQ besitzen, sollten Sie die erforderlichen Vorabprüfungen durchführen und Ihren eigenen Upgrade-Plan erstellen. 
---
= Planen Sie Ihr Upgrade ohne Upgrade Advisor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Als Best Practice-Methode empfiehlt es sich, Upgrade Advisor in zu verwenden link:https://aiq.netapp.com/["Active IQ"^] Um Ihr Upgrade zu planen. Wenn Sie keine aktive haben link:https://www.netapp.com/us/services/support-edge.aspx["SupportEdge"] Vertrag für Active IQ, führen Sie die erforderlichen Überprüfungen vor dem Upgrade durch und erstellen Sie Ihren eigenen Upgrade-Plan.



== Wie lange dauert mein Upgrade?

Sie sollten mindestens 30 Minuten lang planen, um die vorbereitenden Schritte abzuschließen, 60 Minuten zum Upgrade jedes HA-Paares und mindestens 30 Minuten, um die Schritte nach dem Upgrade abzuschließen.


NOTE: Wenn Sie NetApp Verschlüsselung mit einem externen Verschlüsselungsmanagement-Server und dem Key Management Interoperability Protocol (KMIP) verwenden, sollten Sie davon ausgehen, dass das Upgrade für jedes HA-Paar länger als eine Stunde ist.

Unsere Richtlinien für die Upgrade-Dauer basieren auf typischen Konfigurationen und Workloads. Anhand dieser Richtlinien können Sie die Dauer für ein unterbrechungsfreies Upgrade in Ihrer Umgebung abschätzen. Die tatsächliche Dauer Ihres Upgrade-Prozesses hängt jedoch von Ihrer individuellen Umgebung und der Anzahl der Nodes ab.
