---
permalink: performance-admin/active-iq-digital-advisor-view-performance-concept.html 
sidebar: sidebar 
keywords: use, active iq digital advisor, view, system, performance 
summary: Bei jedem ONTAP System, das AutoSupport Telemetrie an NetApp sendet, können Sie umfassende Performance- und Kapazitätsdaten anzeigen.Active IQ zeigt die System-Performance über einen längeren Zeitraum an, als Sie im System Manager sehen können. 
---
= Verwenden Sie Active IQ Digital Advisor, um die Systemleistung anzuzeigen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei jedem ONTAP System, das AutoSupport Telemetrie an NetApp sendet, können Sie umfassende Daten zu Performance und Kapazität einsehen. Active IQ zeigt die System-Performance über einen längeren Zeitraum an, als Sie in System Manager sehen können.

Sie können Diagramme der CPU-Auslastung, Latenz, IOPS, IOPS nach Protokoll und Netzwerkdurchsatz anzeigen. Sie können diese Daten auch als .csv-Format für die Analyse in anderen Werkzeugen herunterladen.

Neben diesen Performance-Daten zeigt Active IQ Ihnen Storage-Effizienz je Workload und vergleicht diese Effizienz mit der erwarteten Effizienz für jenen Workload-Typ. Sie können Kapazitätstrends anzeigen und eine Schätzung der Menge an zusätzlichem Storage anzeigen, die Sie möglicherweise zu einem bestimmten Zeitpunkt hinzufügen müssen.

[NOTE]
====
* Storage-Effizienz ist auf der linken Seite des Haupt-Dashboards auf Kunden-, Cluster- und Node-Ebene verfügbar.
* Die Performance ist auf Cluster- und Node-Ebene auf der linken Seite des Haupt-Dashboards verfügbar.


====
.Verwandte Informationen
* https://["Active IQ Digital Advisor Dokumentation"]
* https://["Active IQ Digital Advisor – Video-Playlist"]
* https://["Active IQ Web Portal"]

