---
permalink: performance-admin/adaptive-policy-template-task.html 
sidebar: sidebar 
keywords: qos, throughput floor, throughput ceiling, adaptive policy group template 
summary: Durchsatzminimum und Durchsatzmaximum auf SVM-Ebene mithilfe einer adaptiven Richtliniengruppenvorlage festlegen. 
---
= Eine adaptive Richtliniengruppenvorlage in ONTAP festlegen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.13.1 lassen sich Durchsatzunter- und -obergrenzen auf SVM-Ebene mithilfe einer adaptiven Richtliniengruppenvorlage festlegen.

.Über diese Aufgabe
* Die Vorlage für adaptive Richtliniengruppen ist eine Standardrichtlinie `apg1`. Die Richtlinie kann jederzeit geändert werden. Sie kann nur mit der CLI oder der ONTAP REST API festgelegt werden und kann nur auf bestehende SVMs angewendet werden.
* Die Vorlage für die adaptive Richtliniengruppe wirkt sich nur auf Volumes aus, die nach der Festlegung der Richtlinie auf der SVM erstellt oder dorthin migriert wurden. Vorhandene Volumes auf der SVM behalten ihren bisherigen Status.
+
Wenn Sie die Vorlage für adaptive Richtliniengruppen deaktivieren, behalten die Volumes auf der SVM ihre bestehenden Richtlinien. Nur Volumes, die anschließend auf der SVM erstellt oder auf die SVM migriert werden, sind von der Deaktivierung betroffen.

* Eine adaptive Richtliniengruppenvorlage kann auf einer SVM mit einer QoS-Richtliniengruppe nicht festgelegt werden.
* Adaptive Richtliniengruppenvorlagen sind für AFF Plattformen konzipiert. Eine adaptive Richtliniengruppenvorlage kann auch auf anderen Plattformen festgelegt werden, jedoch wird die Richtlinie möglicherweise keinen Mindestdurchsatz erzwingen. Ebenso kann eine adaptive Richtliniengruppenvorlage zu einer SVM in einem FabricPool Aggregat oder in einem Aggregat hinzugefügt werden, das keinen Mindestdurchsatz unterstützt; der Mindestdurchsatz wird jedoch nicht erzwungen.
* Wenn sich die SVM in einer MetroCluster Konfiguration oder einer SnapMirror Beziehung befindet, wird die Vorlage der adaptiven Richtliniengruppe auf die gespiegelte SVM angewendet.


.Schritte
. Die SVM wird so angepasst, dass die Vorlage für die adaptive Richtliniengruppe angewendet wird:
`vserver modify -qos-adaptive-policy-group-template apg1`
. Es wird bestätigt, dass die Richtlinie festgelegt wurde:
`vserver show -fields qos-adaptive-policy-group`

