---
permalink: performance-admin/check-fc-adapter-port-speed-task.html 
sidebar: sidebar 
keywords: check, fc, adapter, port, speed 
summary: Die Zielportgeschwindigkeit des Adapters sollte der Geschwindigkeit des Geräts, mit dem er verbunden ist, entsprechen, um die Leistung zu optimieren. Wenn der Port auf automatische Aushandlung eingestellt ist, kann es nach einer Übernahme und Rückgabe oder einer anderen Unterbrechung länger dauern, bis die Verbindung wiederhergestellt ist. 
---
= Die Portgeschwindigkeit des ONTAP FC-Adapters prüfen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Zielportgeschwindigkeit des Adapters sollte der Geschwindigkeit des Geräts, mit dem er verbunden ist, entsprechen, um die Leistung zu optimieren. Wenn der Port auf automatische Aushandlung eingestellt ist, kann es nach einer Übernahme und Rückgabe oder einer anderen Unterbrechung länger dauern, bis die Verbindung wiederhergestellt ist.

.Bevor Sie beginnen
Alle LIFs, die diesen Adapter als ihren Home-Port verwenden, müssen offline sein.

.Schritte
. Den Adapter offline schalten:
+
`network fcp adapter modify -node _nodename_ -adapter _adapter_ -state _down_`

+
Weitere Informationen zu  `network fcp adapter modify` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-fcp-adapter-modify.html["ONTAP-Befehlsreferenz"^].

. Die maximale Geschwindigkeit des Portadapters prüfen:
+
`fcp adapter show -instance`

+
Weitere Informationen zu  `fcp adapter show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-fcp-adapter-show.html["ONTAP-Befehlsreferenz"^].

. Die Portgeschwindigkeit kann bei Bedarf geändert werden:
+
`network fcp adapter modify -node _nodename_ -adapter _adapter_ -speed {1|2|4|8|10|16|auto}`

. Den Adapter online schalten:
+
`network fcp adapter modify -node _nodename_ -adapter _adapter_ -state up`

. Alle LIFs auf dem Adapter online schalten:
+
`network interface modify -vserver * -lif * { -home-node node1 -home-port e0c } -status-admin up`

+
Weitere Informationen zu  `network interface modify` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html["ONTAP-Befehlsreferenz"^].



.Beispiel
Das folgende Beispiel ändert die Portgeschwindigkeit des Adapters `0d` auf `node1` 2 Gbit/s:

[listing]
----
cluster1::> network fcp adapter modify -node node1 -adapter 0d -speed 2
----