---
permalink: performance-admin/enable-disable-throughput-floors-v2-task.html 
sidebar: sidebar 
keywords: enable, disable, throughput, floors v2 
summary: Auf AFF können Sie Durchsatzböden v2 aktivieren oder deaktivieren. Die Standardeinstellung ist aktiviert. Bei aktivierten Etagen v2 können Durchsatzböden eingehalten werden, wenn Controller stark genutzt werden, um Kosten für eine höhere Latenz bei anderen Workloads zu senken. Floors v2 gilt sowohl für QoS als auch für Adaptive QoS. 
---
= Aktivieren oder Deaktivieren von Durchsatzböden v2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf AFF können Sie Durchsatzböden v2 aktivieren oder deaktivieren. Die Standardeinstellung ist aktiviert. Bei aktivierten Etagen v2 können Durchsatzböden eingehalten werden, wenn Controller stark genutzt werden, um Kosten für eine höhere Latenz bei anderen Workloads zu senken. Floors v2 gilt sowohl für QoS als auch für Adaptive QoS.

.Schritte
. Ändern Sie die erweiterte Berechtigungsebene:
+
`set -privilege advanced`

. Geben Sie einen der folgenden Befehle ein:
+
|===
| Ihr Ziel ist | Verwenden Sie den folgenden Befehl: 


 a| 
Deaktivieren Sie die Etagen v2
 a| 
`qos settings throughput-floors-v2 -enable false`



 a| 
Ebenen v2 aktivieren
 a| 
`qos settings throughput-floors-v2 -enable true`

|===
+
[NOTE]
====
Um Durchsatzböden v2 in einem MetroCluster Cluster zu deaktivieren, müssen Sie die ausführen

`qos settings throughput-floors-v2 -enable false`

Befehl auf Quell- und Ziel-Clustern.

====
+
[listing]
----
cluster1::*> qos settings throughput-floors-v2 -enable false
----
+
Erfahren Sie mehr über `qos settings throughput-floors-v2` in der link:https://docs.netapp.com/us-en/ontap-cli/qos-settings-throughput-floors-v2.html["ONTAP-Befehlsreferenz"^].


