---
permalink: performance-admin/identify-performance-issues-unified-manager-task.html 
sidebar: sidebar 
keywords: identify, performance, issues, active iq unified manager 
summary: Tritt ein Performance-Ereignis auf, können Sie die Ursache im Active IQ Unified Manager ermitteln und andere Tools zur Behebung verwenden. Möglicherweise erhalten Sie eine E-Mail-Benachrichtigung über ein Ereignis oder bemerken das Ereignis während der täglichen Überwachung. 
---
= Leistungsprobleme im ONTAP Active IQ Unified Manager identifizieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tritt ein Performance-Ereignis auf, können Sie die Ursache im Active IQ Unified Manager ermitteln und andere Tools zur Behebung verwenden. Möglicherweise erhalten Sie eine E-Mail-Benachrichtigung über ein Ereignis oder bemerken das Ereignis während der täglichen Überwachung.

.Schritte
. Klicken Sie auf den Link in der E-Mail-Benachrichtigung, der Sie direkt zu dem Speicherobjekt mit einem Leistungsereignis führt.
+
|===


| Wenn Sie... | Dann... 


 a| 
Eine E-Mail-Benachrichtigung über ein Ereignis erhalten
 a| 
Über den Link erfolgt eine direkte Weiterleitung zur Seite mit den Veranstaltungsdetails.



 a| 
Das Ereignis fällt bei der Analyse der Seite „Ereignisinventar“ auf.
 a| 
Das Ereignis kann ausgewählt werden, um direkt zur Seite mit den Ereignisdetails zu gelangen.

|===
. Wenn das Ereignis einen systemdefinierten Schwellenwert überschritten hat, können die in der Benutzeroberfläche vorgeschlagenen Maßnahmen zur Fehlerbehebung genutzt werden.
. Wenn das Ereignis einen vom Benutzer festgelegten Schwellenwert überschritten hat, sollte das Ereignis analysiert werden, um zu bestimmen, ob Maßnahmen erforderlich sind.
. Wenn das Problem weiterhin besteht, sind die folgenden Einstellungen zu überprüfen:
+
** Protokolleinstellungen auf dem Speichersystem
** Netzwerkeinstellungen auf beliebigen Ethernet- oder Fabric-Switches
** Netzwerkeinstellungen auf dem Speichersystem
** Festplattenlayout und Aggregatmetriken des Speichersystems


. Sollte das Problem weiterhin bestehen, wenden Sie sich an den technischen Support, um Unterstützung zu erhalten.

