---
permalink: performance-admin/index.html 
sidebar: sidebar 
keywords: performance, manage, management, monitor, monitoring, issues 
summary: Sie können grundlegende Aufgaben zur Performance-Überwachung und -Verwaltung einrichten und gängige Performance-Probleme ermitteln und beheben. 
---
= Erfahren Sie mehr über die Leistungsüberwachung und -verwaltung von ONTAP Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können grundlegende Aufgaben zur Performance-Überwachung und -Verwaltung einrichten und gängige Performance-Probleme ermitteln und beheben.

Diese Verfahren können Sie zur Überwachung und Verwaltung der Cluster-Performance verwenden, wenn sich folgende Annahmen auf Ihre Situation beziehen:

* Sie möchten Best Practices verwenden und nicht alle verfügbaren Optionen erkunden.
* Mit Active IQ Unified Manager (ehemals OnCommand Unified Manager) möchten Sie neben der Befehlszeilenschnittstelle von ONTAP den Systemstatus und die Cluster Performance überwachen und Root-Cause-Analysen durchführen.
* Sie verwenden die ONTAP-Befehlszeilenschnittstelle, um Storage Quality of Service (QoS) zu konfigurieren. QoS ist außerdem über die folgenden Optionen verfügbar:
+
** System Manager
** ONTAP REST API
** ONTAP Tools für VMware vSphere
** NetApp-Service-Level-Manager (NSLM)
** OnCommand Workflow Automation (WFA)


* Sie möchten Active IQ Unified Manager mithilfe einer virtuellen Appliance installieren, anstatt eine Linux- oder Windows-basierte Installation durchzuführen.
* Sie sind bereit, eine statische Konfiguration anstelle von DHCP zu verwenden, um die Software zu installieren.
* Sie können auf der erweiterten Berechtigungsebene auf ONTAP-Befehle zugreifen.
* Sie sind ein Cluster-Administrator mit der Rolle „admin“.


.Verwandte Informationen
Wenn diese Annahmen für Ihre Situation nicht richtig sind, sollten Sie die folgenden Ressourcen sehen:

* http://docs.netapp.com/ocum-98/topic/com.netapp.doc.onc-um-isg/home.html["Installation von Active IQ Unified Manager 9.8"]
* link:../system-admin/index.html["Systemadministration"]

