---
permalink: performance-admin/policy-group-assignment-restrictions.html 
sidebar: sidebar 
keywords: use, adaptive, qos, policy, groups 
summary: Mithilfe einer adaptiven QoS-Richtliniengruppe lässt sich eine Durchsatzobergrenze oder -untergrenze automatisch an die Volumengröße anpassen, wobei das Verhältnis von IOPS zu TB oder GB erhalten bleibt, wenn sich die Größe des Volumens ändert. Das stellt einen entscheidenden Vorteil dar, wenn Hunderte oder Tausende von Workloads in einer großen Umgebung verwaltet werden. 
---
= Einschränkungen bei der Zuweisung von QoS-Richtliniengruppen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.18.1 können verschachtelte QoS-Richtlinien verwendet werden, die die Zuweisung von Richtliniengruppen sowohl zum übergeordneten Objekt, wie einer SVM, als auch zu dessen untergeordnetem Objekt, wie einem Volume, ermöglichen. In einer mandantenfähigen Umgebung ermöglichen verschachtelte QoS-Richtlinien Administratoren, die QoS-Grenzwerte auf SVMs unter den Volumes und Qtrees innerhalb der SVM aufzuteilen und die Möglichkeit zu bieten, Speicherressourcen über verschiedene Rechenumgebungen hinweg auszugleichen, während gleichzeitig die Priorisierung geschäftskritischer Workloads ermöglicht wird.

Verschachtelte QoS-Richtlinien werden für die folgenden Objektpaare unterstützt:

* SVMs und FlexVol oder FlexGroup Volumes, die von der SVM enthalten sind.
* FlexVol oder FlexGroup Volumes und qtrees innerhalb der Volumes.


Bei verschachtelten QoS-Richtlinien gilt die restriktivste anwendbare Richtlinie.

Die folgende Tabelle listet die Einschränkungen auf.

|===
| Wenn Sie die... | Dann kann die Richtlinie keiner Richtliniengruppe zugewiesen werden... 


 a| 
SVM zu einer Richtliniengruppe
 a| 
Alle von der SVM enthaltenen Speicherobjekte.


NOTE: Wenn Sie ONTAP 9.18.1 verwenden, können FlexVol- und FlexGroup-Volumes, die in SVMs enthalten sind, einer Richtliniengruppe zugewiesen werden.



 a| 
Volumen zu einer Richtliniengruppe
 a| 
Die SVM, die das Volume oder untergeordnete LUNs enthält.


NOTE: Wenn Sie ONTAP 9.18.1 oder höher verwenden, kann die SVM, die das Volume enthält, einer Richtliniengruppe zugewiesen werden. Zusätzlich können Qtrees in FlexVol- oder FlexGroup-Volumes zugewiesen werden.



 a| 
LUN zu einer Richtliniengruppe
 a| 
Das Volume oder SVM, das die LUNs enthält



 a| 
Datei einer Richtliniengruppe zuordnen
 a| 
Das Volume oder die SVM, die die Datei enthält

|===