---
permalink: performance-admin/set-throughput-floor-qos-task.html 
sidebar: sidebar 
keywords: setting, throughput, floor, qos 
summary: 'Im Feld „Mindestdurchsatz“ für eine Richtliniengruppe wird eine Durchsatzfläche für Storage-Objekt-Workloads definiert (QoS Min.). Sie können die Richtliniengruppe anwenden, wenn Sie das Speicherobjekt erstellen oder ändern. Ab ONTAP 9.8 können Sie die Durchsatzfläche in IOPS oder MB/s oder IOPS und MB/s angeben.' 
---
= Durchsatzboden festlegen mit QoS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `min-throughput` Feld für eine Richtliniengruppe zur Definition einer Durchsatzfläche für Storage-Objekt-Workloads (QoS Min.) Sie können die Richtliniengruppe anwenden, wenn Sie das Speicherobjekt erstellen oder ändern. Ab ONTAP 9.8 können Sie die Durchsatzfläche in IOPS oder MB/s oder IOPS und MB/s angeben.

.Bevor Sie beginnen
* Sie müssen ONTAP 9.2 oder höher ausführen. Durchsatzböden sind ab ONTAP 9.2 verfügbar.
* Zum Erstellen einer Richtliniengruppe müssen Sie ein Cluster-Administrator sein.
* Ab ONTAP 9.13.1 lassen sich Durchsatzraten auf SVM-Ebene mithilfe eines erzwingen xref:adaptive-policy-template-task.html[Vorlage für adaptive Richtliniengruppen]. Sie können keine Vorlage für adaptive Richtliniengruppen auf einer SVM mit einer QoS-Richtliniengruppe festlegen.


.Über diese Aufgabe
* Ab ONTAP 9.4 können Sie mithilfe einer Richtliniengruppe ohne Shared_ QoS festlegen, dass die definierte Durchsatzfläche auf jeden Workload der Mitglieder einzeln angewendet wird. Dies ist die einzige Bedingung, bei der eine Richtliniengruppe für eine Durchsatzboden auf mehrere Workloads angewendet werden kann.
+
Einstellen `-is-shared=false` Für das `qos policy-group create` Befehl zum Festlegen einer nicht freigegebenen Richtliniengruppe.

* Der Durchsatz für einen Workload könnte unter die angegebene Etage fallen, wenn auf dem Node oder Aggregat keine Performance-Kapazität (Reserve) vorhanden ist.
* Ein Storage-Objekt, das einem QoS-Limit unterliegt, muss von der SVM, der die Richtliniengruppe angehört, enthalten sein. Mehrere Richtliniengruppen können derselben SVM angehören.
* Es handelt sich um eine Best Practice bei QoS, eine Richtliniengruppe auf denselben Storage-Typ anzuwenden.
* Eine Richtliniengruppe mit Durchsatzboden kann nicht auf eine SVM angewendet werden.


.Schritte
. Prüfen Sie, ob auf dem Node oder Aggregat eine ausreichende Performance-Kapazität verfügbar ist, wie in beschrieben link:identify-remaining-performance-capacity-task.html["Identifizierung der verbleibenden Performance-Kapazität"].
. Erstellen einer Richtliniengruppe:
+
`qos policy-group create -policy group _policy_group_ -vserver _SVM_ -min-throughput _qos_target_ -is-shared true|false`

+
Eine vollständige Befehlssyntax finden Sie in der man Page für Ihr ONTAP Release. Sie können das verwenden `qos policy-group modify` Befehl zum Anpassen der Durchsatzböden.

+
Mit dem folgenden Befehl wird die gemeinsam genutzte Richtliniengruppe erstellt `pg-vs2` Bei einem Mindestdurchsatz von 1,000 IOPS:

+
[listing]
----
cluster1::> qos policy-group create -policy group pg-vs2 -vserver vs2 -min-throughput 1000iops -is-shared true
----
+
Mit dem folgenden Befehl wird die nicht gemeinsam genutzte Richtliniengruppe erstellt `pg-vs4` Ohne Durchsatzbegrenzung:

+
[listing]
----
cluster1::> qos policy-group create -policy group pg-vs4 -vserver vs4 -is-shared false
----
. Anwenden einer Richtliniengruppe auf ein Volume oder eine LUN:
+
`_storage_object_ create -vserver _SVM_ -qos-policy-group _policy_group_`

+
Eine vollständige Befehlssyntax finden Sie in den man-Pages. Sie können das verwenden `_storage_object_modify` Befehl zum Anwenden einer anderen Richtliniengruppe auf das Speicherobjekt.

+
Der folgende Befehl wendet die Richtliniengruppe an `pg-app2` Auf das Volume `app2`:

+
[listing]
----
cluster1::> volume create -vserver vs2 -volume app2 -aggregate aggr1 -qos-policy-group pg-app2
----
. Überwachung der Richtliniengruppenleistung:
+
`qos statistics performance show`

+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
[NOTE]
====
Monitoring der Performance über das Cluster Verwenden Sie kein Tool auf dem Host, um die Leistung zu überwachen.

====
+
Mit dem folgenden Befehl wird die Performance der Richtliniengruppe angezeigt:

+
[listing]
----
cluster1::> qos statistics performance show
Policy Group           IOPS      Throughput   Latency
-------------------- -------- --------------- ----------
-total-                 12316       47.76MB/s  1264.00us
pg_app2                  7216       28.19MB/s   420.00us
_System-Best-Effort        62       13.36KB/s     4.13ms
_System-Background         30           0KB/s        0ms
----
. Monitoring der Workload-Performance:
+
`qos statistics workload performance show`

+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
[NOTE]
====
Monitoring der Performance über das Cluster Verwenden Sie kein Tool auf dem Host, um die Leistung zu überwachen.

====
+
Mit dem folgenden Befehl wird die Workload-Performance angezeigt:

+
[listing]
----
cluster1::> qos statistics workload performance show
Workload          ID     IOPS      Throughput    Latency
--------------- ------ -------- ---------------- ----------
-total-              -    12320        47.84MB/s  1215.00us
app2-wid7967      7967     7219        28.20MB/s   319.00us
vs1-wid12279     12279     5026        19.63MB/s     2.52ms
_USERSPACE_APPS     14       55        10.92KB/s   236.00us
_Scan_Backgro..   5688       20            0KB/s        0ms
----
+
[NOTE]
====
Sie können das verwenden `qos statistics workload latency show` Befehl zum Anzeigen detaillierter Latenzstatistiken für QoS-Workloads

====

