---
permalink: performance-admin/worksheet-reference.html 
sidebar: sidebar 
keywords: active iq unified manager, worksheet 
summary: Vor Installation, Konfiguration und Verbindung von Active IQ Unified Manager sollten spezifische Informationen zur Systemumgebung sofort verfügbar sein. Sie können die Informationen im Arbeitsblatt aufzeichnen. 
---
= Active IQ Unified Manager-Arbeitsblatt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor Installation, Konfiguration und Verbindung von Active IQ Unified Manager sollten spezifische Informationen zur Systemumgebung sofort verfügbar sein. Sie können die Informationen im Arbeitsblatt aufzeichnen.



== Informationen zur Installation von Unified Manager

|===


| Virtual Machine, auf der Software bereitgestellt wird | Ihr Wert 


 a| 
IP-Adresse des ESXi-Servers
 a| 



 a| 
Vollständig qualifizierter Domain-Name des Hosts
 a| 



 a| 
Host-IP-Adresse
 a| 



 a| 
Netzwerkmaske
 a| 



 a| 
Gateway-IP-Adresse
 a| 



 a| 
Primäre DNS-Adresse
 a| 



 a| 
Sekundäre DNS-Adresse
 a| 



 a| 
Domänen durchsuchen
 a| 



 a| 
Wartungs-Benutzername
 a| 



 a| 
Wartungs-Benutzer-Passwort
 a| 

|===


== Informationen zur Unified Manager-Konfiguration

|===


| Einstellung | Ihr Wert 


 a| 
Wartungs-Benutzer-E-Mail-Adresse
 a| 



 a| 
NTP-Server
 a| 



 a| 
Hostname oder IP-Adresse des SMTP-Servers
 a| 



 a| 
SMTP-Benutzername
 a| 



 a| 
SMTP-Passwort
 a| 



 a| 
SMTP-Standardport
 a| 
25 (Standardwert)



 a| 
E-Mail, von der aus Benachrichtigungen gesendet werden
 a| 



 a| 
LDAP Bind Distinguished Name
 a| 



 a| 
LDAP-Bindekennwort
 a| 



 a| 
Name des Active Directory-Administrators
 a| 



 a| 
Active Directory-Kennwort
 a| 



 a| 
Authentifizierungsserverbasis mit Distinguished Name
 a| 



 a| 
Hostname oder IP-Adresse des Authentifizierungsservers
 a| 

|===


== Cluster-Informationen

Erfassen Sie die folgenden Informationen für jedes Cluster auf Unified Manager.

|===


| Cluster 1 von N | Ihr Wert 


 a| 
Host-Name oder Cluster-Management-IP-Adresse
 a| 



 a| 
Benutzername des ONTAP-Administrators

[NOTE]
====
Dem Administrator muss die Rolle „admin“ zugewiesen worden sein.

==== a| 



 a| 
ONTAP-Administratorpasswort
 a| 



 a| 
Protokoll (HTTP oder HTTPS)
 a| 

|===
link:../authentication/index.html["Administratorauthentifizierung und RBAC"]
