---
permalink: performance-config/configure-alert-settings-task.html 
sidebar: sidebar 
keywords: configure, alert, settings, 
summary: Sie können festlegen, welche Ereignisse aus Active IQ Unified Manager-Trigger-Warnmeldungen, die E-Mail-Empfänger für diese Meldungen und die Häufigkeit der Meldungen betreffen. 
---
= Konfigurieren Sie die Einstellungen für Warnmeldungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können festlegen, welche Ereignisse aus Active IQ Unified Manager-Trigger-Warnmeldungen, die E-Mail-Empfänger für diese Meldungen und die Häufigkeit der Meldungen betreffen.

Sie müssen über die Anwendungsadministratorrolle verfügen.

Sie können eindeutige Alarmeinstellungen für die folgenden Arten von Performance-Ereignissen konfigurieren:

* Kritische Ereignisse, die durch Verstöße gegen benutzerdefinierte Schwellenwerte ausgelöst werden
* Warnereignisse, die durch Verstöße gegen benutzerdefinierte Schwellenwerte, systemdefinierte Schwellenwerte oder dynamische Schwellenwerte ausgelöst werden


Standardmäßig werden E-Mail-Alarme für alle neuen Ereignisse an Unified Manager Admin-Benutzer gesendet. Sie können E-Mail-Benachrichtigungen an andere Benutzer senden, indem Sie die E-Mail-Adressen dieser Benutzer hinzufügen.

[NOTE]
====
Um das Senden von Warnmeldungen für bestimmte Ereignistypen zu deaktivieren, müssen Sie alle Kontrollkästchen in einer Ereigniskategorie löschen. Durch diese Aktion werden Ereignisse nicht in der Benutzeroberfläche angezeigt.

====
.Schritte
. Wählen Sie im linken Navigationsbereich *Storage-Management* > *Alarm-Setup* aus.
+
Die Seite „Alarm-Setup“ wird angezeigt.

. Klicken Sie auf *Hinzufügen* und konfigurieren Sie die entsprechenden Einstellungen für jeden Ereignistypen.
+
Um E-Mail-Benachrichtigungen an mehrere Benutzer zu senden, geben Sie ein Komma zwischen den einzelnen E-Mail-Adressen ein.

. Klicken Sie Auf *Speichern*.

