---
permalink: peering/remove-snapmirror-encryption-existing-relationship-task.html 
sidebar: sidebar 
keywords: remove, cluster, peering, encryption, existing, peer, relationship 
summary: Die Cluster-Peering-Verschlüsselung wird standardmäßig für alle in ONTAP 9.6 oder höher erstellten Peer-Beziehungen aktiviert. Wenn Sie keine Verschlüsselung für Cluster-übergreifende Peering-Kommunikation verwenden möchten, können Sie diese deaktivieren. 
---
= Entfernen Sie die Cluster-Peering-Verschlüsselung von einer vorhandenen Peer-Beziehung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Cluster-Peering-Verschlüsselung wird standardmäßig für alle in ONTAP 9.6 oder höher erstellten Peer-Beziehungen aktiviert. Wenn Sie keine Verschlüsselung für Cluster-übergreifende Peering-Kommunikation verwenden möchten, können Sie diese deaktivieren.

.Schritte
. Ändern Sie auf dem Zielcluster die Kommunikation mit dem Quellcluster, um die Verwendung der Cluster-Peering-Verschlüsselung einzustellen:
+
** Geben Sie Folgendes ein, um die Verschlüsselung zu entfernen, aber die Authentifizierung beizubehalten:
+
[source, cli]
----
cluster peer modify <source_cluster> -auth-status-admin use-authentication -encryption-protocol-proposed none
----
** So entfernen Sie Verschlüsselung und Authentifizierung:
+
... Ändern Sie die Cluster-Peering-Richtlinie, um nicht authentifizierten Zugriff zu ermöglichen:
+
[source, cli]
----
cluster peer policy modify -is-unauthenticated-access-permitted true
----
... Verschlüsselung und Authentifizierungszugriff ändern:
+
[source, cli]
----
cluster peer modify <source_cluster> -auth-status no-authentication
----




. Wenn Sie dazu aufgefordert werden, geben Sie die Passphrase ein.
. Bestätigen Sie die Passphrase, indem Sie sie erneut eingeben.
. Deaktivieren Sie auf dem Quellcluster die Verschlüsselung für die Kommunikation mit dem Ziel-Cluster:
+
** Geben Sie Folgendes ein, um die Verschlüsselung zu entfernen, aber die Authentifizierung beizubehalten:
+
[source, cli]
----
cluster peer modify <destination_cluster> -auth-status-admin use-authentication -encryption-protocol-proposed none
----
** So entfernen Sie Verschlüsselung und Authentifizierung:
+
... Ändern Sie die Cluster-Peering-Richtlinie, um nicht authentifizierten Zugriff zu ermöglichen:
+
[source, cli]
----
cluster peer policy modify -is-unauthenticated-access-permitted true
----
... Verschlüsselung und Authentifizierungszugriff ändern:
+
[source, cli]
----
cluster peer modify <destination_cluster> -auth-status no-authentication
----




. Wenn Sie dazu aufgefordert werden, geben Sie dieselbe Passphrase ein, die Sie auf dem Ziel-Cluster verwendet haben, und geben Sie sie erneut ein.

