---
permalink: peering/shared-dedicated-ports-intercluster-concept.html 
sidebar: sidebar 
keywords: use, shared, dedicated, ports, network, bandwidth, replication, interval, availability 
summary: Sie können dedizierte Ports für die Cluster-übergreifende Kommunikation verwenden oder vom Datennetzwerk verwendete Ports freigeben. Bei der Entscheidung, ob Ports gemeinsam genutzt werden sollen, müssen Sie die Netzwerkbandbreite, das Replikationsintervall und die Portverfügbarkeit berücksichtigen. 
---
= Verwenden Sie gemeinsam genutzte oder dedizierte ONTAP-Ports
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können dedizierte Ports für die Cluster-übergreifende Kommunikation verwenden oder vom Datennetzwerk verwendete Ports freigeben. Bei der Entscheidung, ob Ports gemeinsam genutzt werden sollen, müssen Sie die Netzwerkbandbreite, das Replikationsintervall und die Portverfügbarkeit berücksichtigen.

[NOTE]
====
Sie können Ports für einen Peering Cluster gemeinsam nutzen, während Sie auf dem anderen dedizierte Ports verwenden.

====


== Netzwerkbandbreite

Wenn Sie ein High-Speed-Netzwerk wie 10 GbE haben, verfügen Sie möglicherweise über ausreichend lokale LAN-Bandbreite, um eine Replikation mit denselben 10 GbE-Ports durchzuführen, die für den Datenzugriff verwendet werden.

Selbst dann sollten Sie Ihre verfügbare WAN-Bandbreite mit Ihrer LAN-Bandbreite vergleichen. Wenn die verfügbare WAN-Bandbreite deutlich weniger als 10 GbE beträgt, müssen Sie möglicherweise dedizierte Ports verwenden.

[TIP]
====
Eine Ausnahme von dieser Regel besteht unter Umständen darin, dass alle oder viele Nodes im Cluster Daten replizieren. In diesem Fall wird die Bandbreitenauslastung normalerweise über verschiedene Nodes verteilt.

====
Wenn Sie keine dedizierten Ports verwenden, sollte die MTU-Größe (Maximum Transmission Unit) des Replikationsnetzwerks in der Regel mit der MTU-Größe des Datennetzwerks übereinstimmen.



== Replikationsintervall

Wenn die Replizierung in Zeiten geringerer Auslastung stattfindet, sollten Sie in der Lage sein, Daten-Ports für die Replizierung zu nutzen, auch ohne eine 10-GbE-LAN-Verbindung.

Wenn die Replizierung während der normalen Geschäftszeiten stattfindet, müssen Sie die Menge der zu replizierenden Daten berücksichtigen und entscheiden, ob es so viel Bandbreite erfordert, dass es Konflikte mit den Datenprotokolle verursachen kann. Wenn die Netzwerkauslastung durch Datenprotokolle (SMB, NFS, iSCSI) über 50 % liegt, sollten dedizierte Ports für die Kommunikation zwischen Clustern verwendet werden. Damit wird bei einem Node-Failover die Performance nicht beeinträchtigt.



== Port-Verfügbarkeit

Wenn Sie feststellen, dass der Replizierungsverkehr den Datenverkehr beeinträchtigt, können Sie LIFs zwischen Clustern auf jeden anderen Cluster-fähigen, gemeinsam genutzten Port desselben Nodes migrieren.

Sie können auch VLAN-Ports für die Replikation zuweisen. Die Bandbreite des Ports wird von allen VLANs und dem Basis-Port gemeinsam genutzt.
