---
permalink: san-admin/change-uta2-port-cna-mode-fc-task.html 
sidebar: sidebar 
keywords: change, uta2, port, cna mode, fc mode 
summary: 'Sie sollten den UTA2-Port vom Converged Network Adapter (CNA)-Modus in den Fibre Channel (FC)-Modus ändern, um den FC-Initiator und den FC-Zielmodus zu unterstützen. Sie sollten die Persönlichkeit vom CNA-Modus in den FC-Modus ändern, wenn Sie das physische Medium ändern müssen, das den Port mit seinem Netzwerk verbindet.' 
---
= Ändern Sie den UTA2-Port vom CNA-Modus in den FC-Modus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten den UTA2-Port vom Converged Network Adapter (CNA)-Modus in den Fibre Channel (FC)-Modus ändern, um den FC-Initiator und den FC-Zielmodus zu unterstützen. Sie sollten die Persönlichkeit vom CNA-Modus in den FC-Modus ändern, wenn Sie das physische Medium ändern müssen, das den Port mit seinem Netzwerk verbindet.

.Schritte
. Versetzen Sie den Adapter in den Offline-Modus:
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -status-admin down`

. Ändern des Portmodus:
+
`ucadmin modify -node _node_name_ -adapter _adapter_name_ -mode fcp`

. Booten Sie den Node neu, und versetzen Sie den Adapter dann in den Online-Modus:
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -status-admin up`

. Benachrichtigen Sie den Administrator oder VIF-Manager, dass er den Port löschen oder entfernen soll, falls zutreffend:
+
** Wenn der Port als Home Port einer logischen Schnittstelle verwendet wird, ist ein Mitglied einer Interface Group (ifgrp), oder Hosts VLANs, dann sollte ein Administrator Folgendes tun:
+
... Verschieben Sie die LIFs, entfernen Sie den Port aus dem ifgrp oder löschen Sie die VLANs.
... Löschen Sie den Port manuell, indem Sie den `network port delete` Befehl ausführen.
+
Wenn der `network port delete` Befehl fehlschlägt, sollte der Admin die Fehler beheben und dann den Befehl erneut ausführen.

+
Erfahren Sie mehr über `network port delete` in der link:https://docs.netapp.com/us-en/ontap-cli/network-port-delete.html["ONTAP-Befehlsreferenz"^].



** Wenn der Port nicht als Home-Port einer LIF verwendet wird, kein Mitglied eines ifgrp ist und keine VLANs hostet, dann sollte der VIF-Manager den Port zum Zeitpunkt des Neustarts aus seinen Datensätzen entfernen.
+
Wenn der VIF-Manager den Port nicht entfernt, muss der Administrator ihn nach dem Neubooten mit dem `network port delete` Befehl manuell entfernen.



+
[listing]
----
net-f8040-34::> network port show

    Node: net-f8040-34-01
                                                      Speed(Mbps) Health
    Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
    --------- ------------ ---------------- ---- ---- ----------- --------
    ...
    e0i       Default      Default          down 1500  auto/10    -
    e0f       Default      Default          down 1500  auto/10    -
    ...

    net-f8040-34::> ucadmin show
                              Current  Current    Pending  Pending    Admin
    Node            Adapter   Mode     Type       Mode     Type       Status
    ------------    -------   -------  ---------  -------  ---------  -----------
    net-f8040-34-01   0e       cna      target     -        -          offline
    net-f8040-34-01   0f       cna      target     -        -          offline
    ...

    net-f8040-34::> network interface create -vs net-f8040-34 -lif m -role
node-mgmt-home-node net-f8040-34-01 -home-port e0e -address 10.1.1.1
-netmask 255.255.255.0


    net-f8040-34::> network interface show -fields home-port, curr-port

    vserver lif                   home-port curr-port
    ------- --------------------- --------- ---------
    Cluster net-f8040-34-01_clus1 e0a       e0a
    Cluster net-f8040-34-01_clus2 e0b       e0b
    Cluster net-f8040-34-01_clus3 e0c       e0c
    Cluster net-f8040-34-01_clus4 e0d       e0d
    net-f8040-34
            cluster_mgmt          e0M       e0M
    net-f8040-34
            m                     e0e       e0i
    net-f8040-34
            net-f8040-34-01_mgmt1 e0M       e0M
    7 entries were displayed.

    net-f8040-34::> ucadmin modify local 0e fc

    Warning: Mode on adapter 0e and also adapter 0f will be changed to fc.
    Do you want to continue? {y|n}: y
    Any changes will take effect after rebooting the system. Use the
"system node reboot" command to reboot.

    net-f8040-34::> reboot local
      (system node reboot)

    Warning: Are you sure you want to reboot node "net-f8040-34-01"?
    {y|n}: y
----
. Vergewissern Sie sich, dass das richtige SFP+ installiert ist:
+
`network fcp adapter show -instance -node -adapter`

+
Für CNA sollten Sie einen 10-GB-Ethernet SFP verwenden. Vor dem Ändern der Konfiguration auf dem Node sollten Sie für FC entweder einen 8-Gbit-SFP oder einen 16-Gbit-SFP verwenden.

+
Erfahren Sie mehr über `network fcp adapter show` in der link:https://docs.netapp.com/us-en/ontap-cli/network-fcp-adapter-show.html["ONTAP-Befehlsreferenz"^].



.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["Netzwerkschnittstelle"^]

