---
permalink: san-admin/commands-manage-fc-adapters-reference.html 
sidebar: sidebar 
keywords: commands, managing, fc, adapters 
summary: Sie können FC-Befehle verwenden, um FC-Zieladapter, FC-Initiatoradapter und Onboard FC-Adapter Ihres Speicherkontrollers zu verwalten. Dieselben Befehle werden zur Verwaltung von FC-Adaptern für das FC-Protokoll und das FC-NVMe-Protokoll verwendet. 
---
= Befehle zur Verwaltung von FC-Adaptern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können FC-Befehle verwenden, um FC-Zieladapter, FC-Initiatoradapter und Onboard FC-Adapter Ihres Speicherkontrollers zu verwalten. Dieselben Befehle werden zur Verwaltung von FC-Adaptern für das FC-Protokoll und das FC-NVMe-Protokoll verwendet.

Die Befehle des FC-Initiator-Adapters funktionieren nur auf Knotenebene. Der  `run -node _node_name_` Befehl muss verwendet werden, bevor die Befehle des FC-Initiator-Adapters verwendet werden können.



[[commands-for-managing-fc-target-adapters]]
== Befehle zur Verwaltung von FC Zieladaptern

[cols="2*"]
|===
| Wenn Sie möchten... | Verwenden Sie diesen Befehl... 


 a| 
FC-Adapterinformationen auf einem Node anzeigen
 a| 
`network fcp adapter show`



 a| 
FC Zieladapter-Parameter ändern
 a| 
`network fcp adapter modify`



 a| 
FC-Protokoll-Verkehrsinformationen
 a| 
`run -node _node_name_ sysstat -f`



 a| 
Anzeigen, wie lange das FC-Protokoll bereits läuft
 a| 
`run -node _node_name_ uptime`



 a| 
Konfiguration und Status des Grafikadapters
 a| 
`run -node _node_name_ sysconfig -v _adapter_`



 a| 
Es wird geprüft, welche Erweiterungskarten installiert sind und ob Konfigurationsfehler vorliegen.
 a| 
`run -node _node_name_ sysconfig -ac`



 a| 
Eine Manpage für einen Befehl anzeigen
 a| 
`man <command_name>`

|===


[[commands-for-managing-fc-initiator-adapters]]
== Befehle zur Verwaltung von FC Initiatoradaptern

[cols="2*"]
|===
| Wenn Sie möchten... | Verwenden Sie diesen Befehl... 


 a| 
Informationen für alle Initiatoren und ihre Adapter in einem Knoten anzeigen
 a| 
`run -node _node_name_ storage show adapter`



 a| 
Konfiguration und Status des Grafikadapters
 a| 
`run -node _node_name_ sysconfig -v _adapter_`



 a| 
Es wird geprüft, welche Erweiterungskarten installiert sind und ob Konfigurationsfehler vorliegen.
 a| 
`run -node _node_name_ sysconfig -ac`

|===


[[commands-for-managing-onboard-fc-adapters]]
== Befehle zur Verwaltung der Onboard-FC-Adapter

[cols="2*"]
|===
| Wenn Sie möchten... | Verwenden Sie diesen Befehl... 


 a| 
Status der integrierten FC-Ports anzeigen
 a| 
`run -node _node_name_ system hardware unified-connect show`

|===
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+fcp+adapter["Netzwerk FCP Adapter"^]

