---
permalink: san-admin/configure-backup-vaults-san-environment-concept.html 
sidebar: sidebar 
keywords: configure, using, snapvault, backups, san, environment 
summary: Die Konfiguration und der Einsatz von SnapVault in einer SAN-Umgebung sind ähnlich der Konfiguration und dem Einsatz in einer NAS-Umgebung. Die Wiederherstellung von LUNs in einer SAN-Umgebung erfordert jedoch einige spezielle Verfahren. 
---
= Konfiguration und Verwendung von SnapVault Backups in einer Übersicht über die SAN-Umgebung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Konfiguration und der Einsatz von SnapVault in einer SAN-Umgebung sind ähnlich der Konfiguration und dem Einsatz in einer NAS-Umgebung. Die Wiederherstellung von LUNs in einer SAN-Umgebung erfordert jedoch einige spezielle Verfahren.

SnapVault Backups enthalten einen Satz schreibgeschützter Kopien eines Quell-Volumes. In einer SAN-Umgebung sichern Sie immer ganze Volumes auf dem sekundären SnapVault Volume, nicht auf individuellen LUNs.

Das Verfahren zum Erstellen und Initialisieren der SnapVault-Beziehung zwischen einem primären Volume mit LUNs und einem sekundären Volume, das als SnapVault Backup fungiert, ist identisch mit dem Verfahren, das mit FlexVol Volumes für Dateiprotokolle verwendet wird. Dieses Verfahren wird ausführlich in beschriebenlink:../data-protection/index.html["Datensicherung"].

Es ist wichtig, dass die gesicherten LUNs einen konsistenten Zustand aufweisen, bevor die Snapshots erstellt und auf das sekundäre SnapVault Volume kopiert werden. Die Automatisierung der Snapshot-Erstellung mit SnapCenter stellt sicher, dass gesicherte LUNs vollständig und von der ursprünglichen Applikation nutzbar sind.

Es gibt drei grundlegende Möglichkeiten für die Wiederherstellung von LUNs aus einem sekundären SnapVault-Volume:

* Eine LUN kann direkt vom sekundären SnapVault Volume zugeordnet werden und einen Host mit der LUN verbinden, um auf die Inhalte der LUN zuzugreifen.
+
Die LUN ist schreibgeschützt, und Sie können nur dem letzten Snapshot im SnapVault-Backup zuordnen. Persistente Reservierungen und andere LUN-Metadaten gehen verloren. Bei Bedarf können Sie den LUN-Inhalt mit einem Kopierprogramm auf dem Host zurück auf die ursprüngliche LUN kopieren, sofern der Zugriff weiterhin möglich ist.

+
Die LUN verfügt über eine andere Seriennummer als die Quell-LUN.

* Sie können jeden Snapshot im sekundären SnapVault-Volume auf ein neues Lese-/Schreibvolume klonen.
+
Anschließend können Sie jede der LUNs im Volume zuordnen und einen Host mit der LUN verbinden, um auf die Inhalte der LUN zuzugreifen. Bei Bedarf können Sie den LUN-Inhalt mit einem Kopierprogramm auf dem Host zurück auf die ursprüngliche LUN kopieren, sofern der Zugriff weiterhin möglich ist.

* Sie können das gesamte Volume, das die LUN enthält, von jedem beliebigen Snapshot im sekundären SnapVault-Volume wiederherstellen.
+
Beim Wiederherstellen des gesamten Volume werden alle LUNs und alle Dateien im Volume ersetzt. Alle neuen LUNs, die seit der Snapshot-Erstellung erstellt wurden, gehen verloren.

+
Die LUNs behalten ihre Zuordnung, Seriennummern, UUIDs und ihre persistenten Reservierungen bei.


