---
permalink: san-admin/configure-return-fqdn-host-iscsi-discovery-task.html 
sidebar: sidebar 
keywords: configure, iscsi, lifs, return, fqdn, host, sendtargets discovery operation 
summary: 'Ab ONTAP 9 können iSCSI-LIFs so konfiguriert werden, dass ein vollständig qualifizierter Domain-Name (FQDN) zurückgegeben wird, wenn ein Host-Betriebssystem einen iSCSI-SendTargets-Ermittlungsvorgang sendet. Die Rückgabe eines FQDN ist nützlich, wenn zwischen dem Host-Betriebssystem und dem Speicherdienst ein NAT-Gerät (Network Address Translation) vorhanden ist.' 
---
= Konfigurieren Sie iSCSI-LIFs, um FQDN an den Host-iSCSI SendTargets Discovery-Vorgang zurückzugeben
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9 können iSCSI-LIFs so konfiguriert werden, dass ein vollständig qualifizierter Domain-Name (FQDN) zurückgegeben wird, wenn ein Host-Betriebssystem einen iSCSI-SendTargets-Ermittlungsvorgang sendet. Die Rückgabe eines FQDN ist nützlich, wenn zwischen dem Host-Betriebssystem und dem Speicherdienst ein NAT-Gerät (Network Address Translation) vorhanden ist.

.Über diese Aufgabe
IP-Adressen auf einer Seite des NAT-Geräts sind auf der anderen Seite bedeutungslos, aber FQDNs können auf beiden Seiten Bedeutung haben.

[NOTE]
====
Die Interoperabilitätsgrenze für den FQDN-Wert beträgt 128 Zeichen auf allen Hostbetriebssystemen.

====
.Schritte
. Ändern Sie die Berechtigungseinstellung in erweitert:
+
`set -privilege advanced`

. Konfigurieren Sie iSCSI-LIFs für die Rückgabe von FQDN:
+
`vserver iscsi interface modify -vserver _SVM_name_ -lif _iscsi_LIF_name_ -sendtargets_fqdn FQDN`

+
Im folgenden Beispiel sind die iSCSI-LIFs so konfiguriert, dass sie den FQDN storagehost-005.example.com zurückgeben.

+
`vserver iscsi interface modify -vserver vs1 -lif vs1_iscsi1 -sendtargets-fqdn storagehost-005.example.com`

. Vergewissern Sie sich, dass sendtargets der FQDN ist:
+
`vserver iscsi interface show -vserver _SVM_name_ -fields sendtargets-fqdn`

+
In diesem Beispiel wird storagehost-005.example.com im Ausgabfeld sendtargets-fqdn angezeigt.

+
[listing]
----
cluster::vserver*> vserver iscsi interface show -vserver vs1 -fields sendtargets-fqdn
vserver lif        sendtargets-fqdn
------- ---------- ---------------------------
vs1     vs1_iscsi1 storagehost-005.example.com
vs1     vs1_iscsi2 storagehost-006.example.com
----


.Verwandte Informationen
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9-Befehle"^]
