---
permalink: san-admin/configure-switches-fcoe-task.html 
sidebar: sidebar 
keywords: configure, switches, fcoe 
summary: Sie müssen Ihre Switches für FCoE konfigurieren, bevor Ihr FC-Service über die vorhandene Ethernet-Infrastruktur ausgeführt werden kann. 
---
= Konfigurieren Sie Switches für FCoE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen Ihre Switches für FCoE konfigurieren, bevor Ihr FC-Service über die vorhandene Ethernet-Infrastruktur ausgeführt werden kann.

.Was Sie benötigen
* Ihre SAN-Konfiguration muss unterstützt werden.
+
Weitere Informationen zu unterstützten Konfigurationen finden Sie im https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^].

* Auf Ihrem Storage-System muss ein Unified Target Adapter (UTA) installiert sein.
+
Wenn Sie eine UTA2 verwenden, muss er auf festgelegt sein `cna` Modus.

* Ein konvergierter Netzwerkadapter (CNA) muss auf Ihrem Host installiert sein.


.Schritte
. Nutzen Sie die Switch-Dokumentation, um die Switches für FCoE zu konfigurieren.
. Überprüfen Sie, ob die DCB-Einstellungen für jeden Knoten im Cluster korrekt konfiguriert wurden.
+
[source, cli]
----
run -node node1 -command dcb show
----
+
DCB-Einstellungen werden auf dem Switch konfiguriert. Wenn die Einstellungen nicht korrekt sind, konsultieren Sie die Switch-Dokumentation.

. Überprüfen Sie, ob die FCoE-Anmeldung funktioniert, wenn der FC-Zielport-Online-Status lautet `true`.
+
[source, cli]
----
fcp adapter show -fields node,adapter,status,state,speed,fabric-established,physical-protocol
----
+
Wenn der Online-Status des FC-Zielports lautet `false`, Konsultieren Sie Ihre Switch-Dokumentation.



.Verwandte Informationen
* https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^]
* http://www.netapp.com/us/media/tr-3800.pdf["Technischer Bericht von NetApp 3800: End-to-End-Implementierungsleitfaden für Fibre Channel over Ethernet (FCoE"^]
* http://www.cisco.com/en/US/products/ps5989/products_installation_and_configuration_guides_list.html["Konfigurationsleitfäden für Cisco MDS 9000 NX-OS und SAN-OS Software"]
* http://www.brocade.com/products/all/index.page["Brocade Produkte"]

