---
permalink: san-admin/configure-volume-provisioning-options-task.html 
sidebar: sidebar 
keywords: configure, volume, provisioning, options 
summary: Sie können ein Volume für Thin Provisioning, Thick Provisioning oder Semi-Thick Provisioning konfigurieren. 
---
= Optionen für die Volumenbereitstellung konfigurieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Volume für Thin Provisioning, Thick Provisioning oder Semi-Thick Provisioning konfigurieren.

.Über diese Aufgabe
Das Setzen der `-space-slo` Option auf `thick` stellt Folgendes sicher:

* Das gesamte Volume ist im Aggregat vorab zugewiesen. Es ist nicht möglich, den  `volume create`- oder  `volume modify`-Befehl zu verwenden, um die  `-space-guarantee`-Option des Volumes zu konfigurieren.
* Der für Überschreibungen benötigte Speicherplatz ist zu 100 % reserviert. Der  `volume modify` Befehl kann nicht verwendet werden, um die  `-fractional-reserve` Option des Volumes zu konfigurieren.


Das Setzen der `-space-slo` Option auf `semi-thick` stellt Folgendes sicher:

* Das gesamte Volume ist im Aggregat vorab zugewiesen. Es ist nicht möglich, den  `volume create`- oder  `volume modify`-Befehl zu verwenden, um die  `-space-guarantee`-Option des Volumes zu konfigurieren.
* Es ist kein Speicherplatz für Überschreibungen reserviert. Mit dem  `volume modify` Befehl lässt sich die  `-fractional-reserve` Option des Volumes konfigurieren.
* Die automatische Löschung von Snapshots ist aktiviert.


.Schritt
. Optionen zur Volumenbereitstellung konfigurieren:
+
`volume create -vserver _vserver_name_ -volume _volume_name_ -aggregate _aggregate_name_ -space-slo none|thick|semi-thick -space-guarantee none|volume`

+
Die  `-space-guarantee` Option ist standardmäßig  `none` für AFF Systeme und für nicht-AFF DP-Volumes aktiviert. Andernfalls ist sie standardmäßig  `volume`. Für bestehende FlexVol Volumes kann der  `volume modify` Befehl zur Konfiguration der Bereitstellungsoptionen verwendet werden.

+
Der folgende Befehl konfiguriert vol1 auf SVM vs1 für Thin Provisioning:

+
[listing]
----
cluster1::> volume create –vserver vs1 -volume vol1 -space-guarantee none
----
+
Der folgende Befehl konfiguriert vol1 auf SVM vs1 für Thick Provisioning:

+
[listing]
----
cluster1::> volume create –vserver vs1 -volume vol1 -space-slo thick
----
+
Der folgende Befehl konfiguriert vol1 auf SVM vs1 für Semi-Thick Provisioning:

+
[listing]
----
cluster1::> volume create –vserver vs1 -volume vol1 -space-slo semi-thick
----

