---
permalink: san-admin/copy-luns-concept.html 
sidebar: sidebar 
keywords: considerations, copying, luns, before 
summary: Vor dem Kopieren einer LUN sollten Sie bestimmte Dinge beachten. 
---
= Was muss vor dem Kopieren von LUNs wissen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor dem Kopieren einer LUN sollten Sie bestimmte Dinge beachten.

Cluster-Administratoren können eine LUN mithilfe der in Storage Virtual Machines (SVMs) innerhalb des Clusters kopieren `lun copy` Befehl. Cluster-Administratoren müssen die Storage Virtual Machine (SVM)-Peering-Beziehung mithilfe des herstellen `vserver peer create` Befehl, bevor ein LUN-Kopiervorgang zwischen den SVMs ausgeführt wird Für einen SIS-Klon muss im Quell-Volume genügend Platz vorhanden sein.

LUNs in Snapshot Kopien können als Quell-LUNs für die verwendet werden `lun copy` Befehl. Wenn Sie eine LUN mit dem kopieren `lun copy` Befehl, die LUN-Kopie steht sofort für Lese- und Schreibzugriff zur Verfügung. Die Quell-LUN wird durch die Erstellung einer LUN-Kopie nicht geändert. Sowohl die Quell-LUN als auch die LUN-Kopie sind als eindeutige LUNs mit unterschiedlichen LUN-Seriennummern vorhanden. Änderungen an der Quell-LUN werden nicht in der LUN-Kopie widergespiegelt und Änderungen, die an der LUN-Kopie vorgenommen werden, werden nicht in der Quell-LUN wiedergegeben. Die LUN-Zuordnung der Quell-LUN wird nicht auf die neue LUN kopiert. Die LUN Kopie muss zugeordnet werden.

Die Datensicherung durch Snapshot-Kopien findet auf Volume-Ebene statt. Wenn Sie eine LUN auf ein anderes Volume als das Volume der Quell-LUN kopieren, fällt die Ziel-LUN unter das Datensicherungsschema des Ziel-Volume. Wenn für das Ziel-Volume keine Snapshot Kopien eingerichtet wurden, werden keine Snapshot Kopien von der LUN-Kopie erstellt.

Das Kopieren von LUNs ist ein unterbrechungsfreier Vorgang.

Sie können die folgenden LUNs-Typen nicht kopieren:

* Eine LUN, die aus einer Datei erstellt wurde
* Eine LUN im Status „NV-Fehler“
* Eine LUN, die sich in einer Load-Sharing-Beziehung befindet
* Eine Protokoll-Endpunktklasse LUN

