---
permalink: san-admin/data-protection-methods-reference.html 
sidebar: sidebar 
keywords: data, protection, methods, san, environments, snapmirror business continuity, smbc, snapshot copy, mirror, update, flexclone luns, license required, snapvault, backups, snapdrive, windows, unix 
summary: Sie können Ihre Daten schützen, indem Sie Kopien davon erstellen, sodass sie bei versehentlichem Löschen, Applikationsabstürzen, Datenbeschädigung oder Ausfällen für eine Wiederherstellung verfügbar sind. Je nach Datensicherungs- und Backup-Anforderungen bietet ONTAP verschiedene Methoden zum Schutz Ihrer Daten. 
---
= Datensicherungs-Methoden in SAN-Umgebungen im Überblick
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Ihre Daten schützen, indem Sie Kopien davon erstellen, sodass sie bei versehentlichem Löschen, Applikationsabstürzen, Datenbeschädigung oder Ausfällen für eine Wiederherstellung verfügbar sind. Je nach Datensicherungs- und Backup-Anforderungen bietet ONTAP verschiedene Methoden zum Schutz Ihrer Daten.



== SnapMirror Business Continuity (SM-BC)

Ab ONTAP 9.9 ist diese allgemeine Verfügbarkeit mit Zero Recovery Time Objective (RTO von Null) oder transparentem Applikations-Failover (TAF) möglich und ermöglicht ein automatisches Failover geschäftskritischer Applikationen in SAN-Umgebungen. SM-BC erfordert die Installation von ONTAP Mediator 1.2 in einer Konfiguration mit zwei AFF Clustern oder zwei All SAN Array (ASA) Clustern.

https://docs.netapp.com/us-en/ontap/smbc["NetApp Dokumentation: SnapMirror Business Continuity"]



== Snapshot Kopie

Ermöglicht Ihnen das manuelle oder automatische Erstellen, Planen und Pflegen mehrerer Backups Ihrer LUNs. Snapshot Kopien belegen nur eine minimale Menge an zusätzlichem Volume-Speicherplatz und liegen keine Performance-Kosten vor. Wenn Ihre LUN-Daten versehentlich geändert oder gelöscht werden, können diese Daten aus einer der neuesten Snapshot Kopien einfach und schnell wiederhergestellt werden.



== FlexClone LUNs (FlexClone Lizenz erforderlich)

Erstellung zeitpunktgenauer, beschreibbarer Kopien einer anderen LUN in einem aktiven Volume oder in einer Snapshot Kopie Ein Klon und sein übergeordnetes Objekt können unabhängig voneinander geändert werden, ohne dass sich gegenseitig beeinträchtigen.



== SnapRestore (Lizenz erforderlich)

Snapshot Kopien auf einem gesamten Volume ermöglichen eine schnelle, platzsparende Datenwiederherstellung nach Bedarf. Mit SnapRestore können Sie eine LUN auf einen früheren Zustand wiederherstellen, ohne das Storage-System neu zu booten.



== Datensicherung Spiegelungskopien (SnapMirror Lizenz erforderlich)

Bietet asynchrone Disaster Recovery, da Sie die Möglichkeit haben, regelmäßig Snapshot-Kopien von Daten auf Ihrem Volume zu erstellen, diese Snapshot-Kopien über ein lokales oder Wide Area Network zu einem Partner-Volume zu kopieren, normalerweise in einem anderen Cluster. Diese Snapshot Kopien bleiben erhalten. Die gespiegelte Kopie auf dem Partner-Volume sorgt für eine rasche Verfügbarkeit und Wiederherstellung der Daten aus dem Zeitpunkt der letzten Snapshot Kopie, sofern die Daten auf dem Quell-Volume beschädigt oder verloren sind.



== SnapVault Backups (SnapMirror Lizenz erforderlich)

Ermöglicht eine effiziente und langfristige Aufbewahrung von Backups. Mithilfe von SnapVault Beziehungen können Sie ausgewählte Snapshot Kopien von Volumes auf einem Ziel-Volume sichern und die Backups beibehalten.

Falls Sie Tape-Backups und Archivierungsvorgänge durchführen, können Sie sie auch für die Daten ausführen, die bereits auf dem sekundären SnapVault Volume gesichert sind.



== SnapDrive für Windows oder UNIX (SnapDrive-Lizenz erforderlich)

Konfiguration des Zugriffs auf LUNs, Management von LUNs und Management von Snapshot Kopien des Storage-Systems direkt von einem Windows oder UNIX Host aus



== Natives Tape-Backup und -Recovery

Die meisten vorhandenen Bandlaufwerke werden in ONTAP unterstützt und ebenfalls eine Methode für Tape-Anbieter, um neue Geräte dynamisch zu unterstützen. ONTAP unterstützt außerdem das Remote Magnetic Tape (RMT)-Protokoll und ermöglicht so Backup und Recovery für jedes fähige System.

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30050["NetApp Dokumentation: SnapDrive für UNIX"]

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30049["NetApp Dokumentation: SnapDrive für Windows (aktuelle Versionen)"]

link:../tape-backup/index.html["Datensicherung mithilfe von Tape Backup"]
