---
permalink: san-admin/delete-iscsi-service-svm-task.html 
sidebar: sidebar 
keywords: delete, iscsi, service, svm 
summary: 'Sie können einen iSCSI-Service für eine Storage Virtual Machine (SVM) löschen, wenn dieser nicht mehr benötigt wird.' 
---
= Löschen eines iSCSI-Dienstes für eine SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen iSCSI-Service für eine Storage Virtual Machine (SVM) löschen, wenn dieser nicht mehr benötigt wird.

.Was Sie benötigen
Der Administrationsstatus des iSCSI-Dienstes muss sich im Status „`down`“ befinden, bevor Sie einen iSCSI-Dienst löschen können. Sie können den Administrationsstatus mit der nach unten verschieben `vserver iscsi modify` Befehl.

.Schritte
. Verwenden Sie die `vserver iscsi modify` Befehl zum Beenden der I/O-Vorgänge auf der LUN.
+
`vserver iscsi modify -vserver vs1 -status-admin down`

. Verwenden Sie die `vserver iscsi delete` Befehl zum Entfernen des iscsi-Service von der SVM.
+
`vserver iscsi delete -vserver vs_1`

. Verwenden Sie die `vserver iscsi show command` Um zu überprüfen, ob Sie den iSCSI-Service von der SVM gelöscht haben.
+
`vserver iscsi show -vserver vs1`


