---
permalink: san-admin/delete-iscsi-service-svm-task.html 
sidebar: sidebar 
keywords: delete, iscsi, service, svm 
summary: Sie können einen iSCSI-Service für eine Storage Virtual Machine löschen, wenn er nicht mehr benötigt wird. 
---
= Löschen eines iSCSI-Service für eine SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein iSCSI-Service für eine Storage Virtual Machine (SVM) kann gelöscht werden, wenn er nicht mehr benötigt wird.

.Bevor Sie beginnen
Der Administrationsstatus des iSCSI-Service muss sich im Zustand „down“ befinden, bevor ein iSCSI-Service gelöscht werden kann. Der Administrationsstatus kann mit dem  `vserver iscsi modify` Befehl auf „down“ gesetzt werden.

.Schritte
. Der  `vserver iscsi modify`-Befehl kann verwendet werden, um die I/O zur LUN zu stoppen.
+
`vserver iscsi modify -vserver vs1 -status-admin down`

. Mit dem  `vserver iscsi delete`Befehl lässt sich der iSCSI-Service aus der SVM entfernen.
+
`vserver iscsi delete -vserver vs_1`

. Verwenden Sie den  `vserver iscsi show command`, um zu überprüfen, ob der iSCSI-Service von der SVM gelöscht wurde.
+
`vserver iscsi show -vserver vs1`


