---
permalink: san-admin/enable-space-allocation-scsi-thin-provisioned-luns-task.html 
sidebar: sidebar 
keywords: enable, space, allocation, scsi, thinly, provisioned luns 
summary: Wenn Sie die Option für die Speicherplatzzuweisung auf aktiviert setzen, benachrichtigt ONTAP den Host, wenn der Speicherplatz des Volume erschöpft ist, und die LUN im Volume kann keine Schreibvorgänge akzeptieren. Mit dieser Option kann ONTAP auch automatisch Speicherplatz freigeben, wenn der Host Daten löscht. 
---
= Aktivieren Sie die Speicherplatzzuweisung für Thin Provisioning LUNs von SCSI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die einstellen `space-allocation` Option auf `enabled`, ONTAP benachrichtigt den Host, wenn der Speicherplatz des Volume knapp ist, und die LUN im Volume kann Schreibvorgänge nicht akzeptieren. Mit dieser Option kann ONTAP auch automatisch Speicherplatz freigeben, wenn der Host Daten löscht.

.Über diese Aufgabe
Der `space-allocation` Die Option ist auf festgelegt `disabled` Standardmäßig müssen Sie die LUN in den Offline-Modus versetzen, um die Speicherplatzzuweisung zu aktivieren. Nachdem Sie die Speicherplatzzuweisung aktiviert haben, müssen Sie eine Ermittlung auf dem Host durchführen, bevor der Host erkennt, dass die Speicherplatzzuweisung aktiviert wurde.

.Schritte
. Versetzen Sie die LUN in den Offline-Modus.
+
[source, cli]
----
lun modify -vserver vserver_name -volume volume_name -lun lun_name -state offline
----
. Speicherplatzzuweisung aktivieren:
+
[source, cli]
----
lun modify -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -space-allocation enabled
----
. Vergewissern Sie sich, dass die Speicherplatzzuweisung aktiviert ist:
+
[source, cli]
----
lun show -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -fields space-allocation
----
. Versetzen Sie die LUN in den Online-Modus:
+
[source, cli]
----
lun modify -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -state online
----
. Auf dem Host, scannen Sie alle Festplatten neu, um sicherzustellen, dass die Änderung an `-space-allocation` Die Option wurde ordnungsgemäß erkannt.

