---
permalink: san-admin/flexclone-luns-protect-your-data-concept.html 
sidebar: sidebar 
keywords: use, flexclone, luns, protect, your, data 
summary: Eine FlexClone LUN ist eine zeitpunktgenau beschreibbare Kopie einer anderen LUN in einem aktiven Volume oder in einem Snapshot. Die Kopie und die übergeordnete LUN können unabhängig voneinander geändert werden, ohne sich gegenseitig zu beeinflussen. 
---
= Schutz Ihrer Daten mit ONTAP FlexClone LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Eine FlexClone LUN ist eine zeitpunktgenau beschreibbare Kopie einer anderen LUN in einem aktiven Volume oder in einem Snapshot. Die Kopie und die übergeordnete LUN können unabhängig voneinander geändert werden, ohne sich gegenseitig zu beeinflussen.

Mit FlexClone LUNs können mehrere lesen/schreiben-Kopien einer LUN erstellt werden.

.Gründe für die Erstellung von FlexClone LUNs
* Eine temporäre Kopie einer LUN für Testzwecke wird benötigt.
* Eine Kopie Ihrer Daten muss für zusätzliche Benutzer verfügbar sein, ohne dass ihnen Zugriff auf die Produktionsdaten gewährt wird.
* Es soll ein Klon einer Datenbank für Manipulations- und Projektionsvorgänge erstellt werden, wobei die Originaldaten in unveränderter Form erhalten bleiben.
* Sie möchten auf eine bestimmte Teilmenge der Daten einer LUN zugreifen (ein bestimmtes logisches Volume oder Dateisystem in einer Volume-Gruppe oder eine bestimmte Datei oder Dateigruppe in einem Dateisystem) und diese auf die ursprüngliche LUN kopieren, ohne die übrigen Daten in der ursprünglichen LUN wiederherzustellen. Dies funktioniert auf Betriebssystemen, die das gleichzeitige Einbinden einer LUN und eines Klons der LUN unterstützen.
* Sie benötigen mehrere SAN Boot Hosts mit demselben Betriebssystem.


Eine FlexClone LUN teilt sich zunächst den Speicherplatz mit ihrer übergeordneten LUN. Standardmäßig erbt die FlexClone LUN das Attribut „reservierter Speicherplatz“ der übergeordneten LUN. Wenn die übergeordnete LUN beispielsweise keinen reservierten Speicherplatz hat, ist die FlexClone LUN standardmäßig ebenfalls ohne reservierten Speicherplatz. Es ist jedoch möglich, eine FlexClone LUN ohne reservierten Speicherplatz aus einer übergeordneten LUN mit reserviertem Speicherplatz zu erstellen.

Beim Klonen einer LUN findet die Blockfreigabe im Hintergrund statt und Sie können erst dann einen Volume-Snapshot erstellen, wenn die Blockfreigabe abgeschlossen ist.

Das Volume muss so konfiguriert werden, dass die automatische Löschfunktion für FlexClone LUNs mit dem  `volume snapshot autodelete modify` Befehl aktiviert wird. Andernfalls, wenn FlexClone LUNs automatisch gelöscht werden sollen, das Volume jedoch nicht für die automatische Löschung von FlexClone LUNs konfiguriert ist, werden keine FlexClone LUNs gelöscht.

Wenn eine FlexClone LUN erstellt wird, ist die automatische Löschfunktion für die FlexClone LUN standardmäßig deaktiviert. Sie muss für jede FlexClone LUN manuell aktiviert werden, bevor diese FlexClone LUN automatisch gelöscht werden kann. Bei Verwendung von semi-thick Volume-Provisioning und dem Wunsch nach der durch diese Option bereitgestellten „best effort“-Schreibgarantie müssen _alle_ FlexClone LUNs für die automatische Löschung verfügbar gemacht werden.

[NOTE]
====
Wenn eine FlexClone LUN aus einem Snapshot erstellt wird, wird die LUN automatisch mithilfe eines platzsparenden Hintergrundprozesses vom Snapshot getrennt, sodass die LUN nicht weiterhin vom Snapshot abhängig ist oder zusätzlichen Speicherplatz belegt. Wenn diese Hintergrundtrennung noch nicht abgeschlossen ist und dieser Snapshot automatisch gelöscht wird, wird diese FlexClone LUN gelöscht, selbst wenn die FlexClone Auto-Delete-Funktion für diese FlexClone LUN deaktiviert wurde. Nach Abschluss der Hintergrundtrennung wird die FlexClone LUN nicht gelöscht, selbst wenn dieser Snapshot gelöscht wird.

====
.Verwandte Informationen
* link:../volumes/create-flexclone-file-flexclone-lun-task.html["Eine FlexClone LUN erstellen"]
* link:../volumes/configure-flexvol-delete-flexclone-files-luns-task.html["Ein FlexVol volume kann so konfiguriert werden, dass FlexClone LUNs automatisch gelöscht werden"]
* link:../volumes/prevent-flexclone-file-lun-automatic-deleted-task.html["Verhindern, dass eine FlexClone LUN automatisch gelöscht wird"]

