---
permalink: san-admin/get-details-iscsi-session-error-recoveries-task.html 
sidebar: sidebar 
keywords: get, more, details, iscsi, session, error, recoveries 
summary: Wenn Sie die Recovery-Ebene für iSCSI-Sitzungsfehler erhöhen, erhalten Sie detailliertere Informationen über die Wiederherstellung von iSCSI-Fehlern. Die Verwendung eines höheren Fehlerwiederherstellungsniveaus kann zu einer geringfügigen Reduzierung der iSCSI-Sitzungsleistung führen. 
---
= Weitere Details bei der Wiederherstellung von iSCSI-Sitzungsfehlern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die Recovery-Ebene für iSCSI-Sitzungsfehler erhöhen, erhalten Sie detailliertere Informationen über die Wiederherstellung von iSCSI-Fehlern. Die Verwendung eines höheren Fehlerwiederherstellungsniveaus kann zu einer geringfügigen Reduzierung der iSCSI-Sitzungsleistung führen.

.Über diese Aufgabe
Standardmäßig ist ONTAP so konfiguriert, dass für iSCSI-Sitzungen die Fehlerwiederherstellungsstufe 0 verwendet wird. Wenn Sie einen Initiator verwenden, der für die Fehlerwiederherstellungsstufe 1 oder 2 qualifiziert wurde, können Sie wählen, die Fehlerwiederherstellungsstufe zu erhöhen. Der geänderte Wiederherstellungslevel für Sitzungsfehler betrifft nur die neu erstellten Sitzungen und wirkt sich nicht auf vorhandene Sitzungen aus.

Ab ONTAP 9.4 beginnt der `max-error-recovery-level` Die Option wird in nicht unterstützt `iscsi show` Und `iscsi modify` Befehle.

.Schritte
. Erweiterten Modus aufrufen:
+
`set -privilege advanced`

. Überprüfen Sie die aktuelle Einstellung mit dem `iscsi show` Befehl.
+
`iscsi show -vserver vs3 -fields max-error-recovery-level`

+
[listing]
----
vserver max-error-recovery-level
------- ------------------------
vs3     0
----
. Ändern Sie die Fehlerwiederherstellungsebene mit `iscsi modify` Befehl.
+
`iscsi modify -vserver vs3 -max-error-recovery-level 2`


