---
permalink: san-admin/host-side-management-concept.html 
sidebar: sidebar 
keywords: understand, host-side, space, management 
summary: In einer Thin-Provisioning-Umgebung schließt das hostseitige Speicherplatzmanagement den Prozess der Verwaltung des im Host-Dateisystem freigegebenen Speicherplatzes vom Speichersystem ab. 
---
= SAN Host-seitiges Speicherplatzmanagement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In einer Thin-Provisioning-Umgebung schließt das hostseitige Speicherplatzmanagement den Prozess der Verwaltung des im Host-Dateisystem freigegebenen Speicherplatzes vom Speichersystem ab.

Das Dateisystem eines Hosts enthält Metadaten, die festlegen, welche Blöcke für neue Daten verfügbar sind und welche Blöcke gültige Daten enthalten, die nicht überschrieben werden dürfen. Diese Metadaten werden in der LUN oder im Namensraum gespeichert. Wenn eine Datei im Dateisystem des Hosts gelöscht wird, werden die Metadaten des Dateisystems aktualisiert, um die Blöcke dieser Datei als freien Speicherplatz zu markieren. Der gesamte freie Speicherplatz des Dateisystems wird dann neu berechnet, sodass die neu freigegebenen Blöcke einbezogen werden. Für das Speichersystem unterscheiden sich diese Metadatenaktualisierungen nicht von anderen Schreibvorgängen des Hosts. Daher ist dem Speichersystem nicht bekannt, dass Löschungen erfolgt sind.

Dies führt zu einer Diskrepanz zwischen dem vom Host und dem vom zugrunde liegenden Speichersystem gemeldeten freien Speicherplatz. Beispielsweise weist das Speichersystem Ihrem Host eine neu bereitgestellte 200-GB-LUN zu. Sowohl der Host als auch das Speichersystem melden 200 GB freien Speicherplatz. Anschließend schreibt der Host 100 GB Daten. Zu diesem Zeitpunkt melden sowohl der Host als auch das Speichersystem 100 GB belegten und 100 GB ungenutzten Speicherplatz.

Dann werden 50 GB Daten von Ihrem Host gelöscht. Zu diesem Zeitpunkt meldet Ihr Host 50 GB belegten und 150 GB ungenutzten Speicherplatz. Ihr Speichersystem meldet jedoch 100 GB belegten und 100 GB ungenutzten Speicherplatz.

Das Host-seitige Speicherplatzmanagement nutzt verschiedene Methoden, um die Speicherdifferenz zwischen Host und Speichersystem auszugleichen.



[[simplified-host-management-with-snapcenter]]
== Vereinfachte Hostverwaltung mit SnapCenter

Mit der SnapCenter software lassen sich einige Verwaltungs- und Datenschutzaufgaben im Zusammenhang mit iSCSI- und FC-Speicher vereinfachen. SnapCenter ist ein optionales Verwaltungspaket für Windows- und UNIX-Hosts.

Mit der SnapCenter Software lassen sich virtuelle Festplatten aus Speicherpools einfach erstellen, die auf mehrere Speichersysteme verteilt werden können. Zudem werden Aufgaben zur Speicherbereitstellung automatisiert und der Prozess zur Erstellung von Snapshots und Klonen aus Snapshots, die mit den Hostdaten konsistent sind, vereinfacht.

In der NetApp Produktdokumentation sind weitere Informationen zu  https://docs.netapp.com/us-en/snapcenter/index.html["SnapCenter"] zu finden.

.Verwandte Links
link:enable-space-allocation-scsi-thin-provisioned-luns-task.html["ONTAP Speicherplatzzuweisung für SAN-Protokolle aktivieren"]
