---
permalink: san-admin/host-side-management-concept.html 
sidebar: sidebar 
keywords: understand, host-side, space, management 
summary: In einer durch Thin Provisioning bereitgestellten Umgebung rundet das Platzmanagement auf der Host-Seite den Prozess des Speicherplatzmanagements auf dem Storage-System ab, das im Host-Filesystem freigegeben wurde. 
---
= SAN-Host-seitiges Speicherplatzmanagement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In einer durch Thin Provisioning bereitgestellten Umgebung rundet das Platzmanagement auf der Host-Seite den Prozess des Speicherplatzmanagements auf dem Storage-System ab, das im Host-Filesystem freigegeben wurde.

Ein Host-Filesystem enthält Metadaten, um zu verfolgen, welche Blöcke zum Speichern neuer Daten verfügbar sind und welche Blöcke gültige Daten enthalten, die nicht überschrieben werden dürfen. Diese Metadaten werden innerhalb der LUN gespeichert. Wenn eine Datei im Host-Filesystem gelöscht wird, werden die Metadaten des Filesystems aktualisiert, um die Blöcke dieser Datei als freien Speicherplatz zu markieren. Der gesamte freie Speicherplatz des Filesystems wird dann neu berechnet, um die neu freigegebenen Blöcke einzubeziehen. Für das Speichersystem werden diese Metadatenaktualisierungen nicht von anderen Schreibvorgängen angezeigt, die vom Host ausgeführt werden. Daher ist im Storage-System keine Löschung aufgetreten.

Dadurch entsteht eine Diskrepanz zwischen der Menge an freiem Speicherplatz, die vom Host gemeldet wird, und der Menge an freiem Speicherplatz, die vom zugrunde liegenden Storage-System gemeldet wird. Nehmen wir beispielsweise an, dass Ihrem Host durch Ihr Storage-System eine neu bereitgestellte 200-GB-LUN zugewiesen ist. Sowohl der Host als auch das Speichersystem berichten von 200 GB freiem Speicherplatz. Ihr Host schreibt dann 100 GB Daten. An diesem Punkt berichten sowohl der Host als auch das Speichersystem von 100 GB belegten Speicherplatz und 100 GB nicht genutztem Speicherplatz.

Dann löschen Sie 50 GB Daten von Ihrem Host. An dieser Stelle meldet Ihr Host 50 GB verbrauchten Speicherplatz und 150 GB nicht genutzten Speicherplatz. Ihr Speichersystem wird jedoch 100 GB verwendeten Speicherplatzes und 100 GB nicht genutzten Speicherplatz melden.

Das Host-seitige Speicherplatzmanagement verwendet verschiedene Methoden, um den Speicherplatzunterschied zwischen dem Host und dem Storage-System abzugleichen.



== Vereinfachtes Host-Management mit SnapCenter

Mit SnapCenter können Sie einige Management- und Datensicherungsaufgaben von iSCSI- und FC-Storage vereinfachen. SnapCenter ist ein optionales Management-Paket für Windows- und UNIX-Hosts.

Mit SnapCenter lassen sich mühelos virtuelle Festplatten aus Storage-Pools erstellen, die auf verschiedene Storage-Systeme verteilt werden können. Die Storage-Provisionierung wird automatisiert und die Erstellung von Snapshot Kopien und Klonen von Snapshot Kopien, die mit Host-Daten konsistent sind, wird vereinfacht.

Weitere Informationen finden Sie in der NetApp Produktdokumentation zu https://docs.netapp.com/us-en/snapcenter/index.html["SnapCenter"].

.Weiterführende Links
link:enable-space-allocation-scsi-thin-provisioned-luns-task.html["Aktivieren Sie die Speicherplatzzuweisung für Thin Provisioning LUNs von SCSI"]
