---
permalink: san-admin/igroups-concept.html 
sidebar: sidebar 
keywords: understand, igroups 
summary: Initiatorgruppen sind Tabellen mit WWPNs von FC-Protokoll-Hosts oder iSCSI-Hostknotennamen. Es besteht die Möglichkeit, igroups zu definieren und sie LUNs zuzuordnen, um zu steuern, welche Initiatoren Zugriff auf LUNs erhalten. 
---
= Erfahren Sie mehr über ONTAP SAN igroups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Initiatorgruppen (igroups) sind Tabellen mit WWPNs von FC-Protokoll-Hosts oder iSCSI-Hostknotennamen. Es besteht die Möglichkeit, igroups zu definieren und sie LUNs zuzuordnen, um zu steuern, welche Initiatoren Zugriff auf LUNs erhalten.

Im Normalfall sollten alle Initiator-Ports oder Softwareinitiatoren eines Hosts Zugriff auf eine LUN haben. Wenn Multipathing-Software verwendet wird oder Hosts in einem Cluster betrieben werden, benötigt jeder Initiator-Port oder Softwareinitiator jedes Cluster-Hosts redundante Pfade zur selben LUN.

Es ist möglich, igroups zu erstellen, die festlegen, welche Initiatoren Zugriff auf die LUNs haben, entweder vor oder nach der Erstellung der LUNs, jedoch müssen igroups erstellt werden, bevor eine LUN einer Initiatorgruppe zugeordnet werden kann.

Initiatorgruppen können mehrere Initiatoren haben, und mehrere Initiatorgruppen können denselben Initiator haben. Es ist jedoch nicht möglich, eine LUN mehreren Initiatorgruppen mit demselben Initiator zuzuordnen. Ein Initiator darf nicht Mitglied von Initiatorgruppen mit unterschiedlichen ostypes sein.



[[example-of-how-igroups-give-lun-access]]
== Beispiel dafür, wie igroups den Zugriff auf LUNs ermöglichen

Sie können mehrere igroups erstellen, um festzulegen, welche LUNs Ihren Hosts zur Verfügung stehen. Wenn beispielsweise ein Host-Cluster vorhanden ist, kann mit igroups sichergestellt werden, dass bestimmte LUNs nur für einen Host im Cluster oder für alle Hosts im Cluster sichtbar sind.

Die folgende Tabelle veranschaulicht, wie vier Initiatorgruppen den Zugriff auf die LUNs für vier verschiedene Hosts ermöglichen, die auf das Speichersystem zugreifen. Die Cluster-Hosts (Host3 und Host4) sind beide Mitglieder derselben Initiatorgruppe (group3) und können auf die LUNs zugreifen, die dieser Initiatorgruppe zugeordnet sind. Die Initiatorgruppe group4 enthält die WWPNs von Host4, um lokale Informationen zu speichern, die für den Partner nicht sichtbar sein sollen.

[cols="4*"]
|===
| Hosts mit HBA WWPNs, IQNs oder EUIs | igroups | WWPNs, IQNs, EUIs wurden zu Initiatorgruppen hinzugefügt | LUNs, die Initiatorgruppen zugeordnet sind 


 a| 
Host1, Single-Path (iSCSI Softwareinitiator)

iqn.1991-05.com.microsoft:host1
 a| 
group1
 a| 
iqn.1991-05.com.microsoft:host1
 a| 
`/vol/vol2/lun1`



 a| 
Host2, Multipath (zwei HBAs)

10:00:00:00:c9:2b:6b:3c

10:00:00:00:c9:2b:02:3c
 a| 
group2
 a| 
10:00:00:00:c9:2b:6b:3c

10:00:00:00:c9:2b:02:3c
 a| 
`/vol/vol2/lun2`



 a| 
Host3, Multipath, in einem Cluster mit Host 4

10:00:00:00:c9:2b:32:1b

10:00:00:00:c9:2b:41:02
 a| 
group3
 a| 
10:00:00:00:c9:2b:32:1b

10:00:00:00:c9:2b:41:02

10:00:00:00:c9:2b:51:2c

10:00:00:00:c9:2b:47:a2
 a| 
`/vol/vol2/qtree1/lun3`



 a| 
Host4, Multipath, Clustered (für Host3 nicht sichtbar)

10:00:00:00:c9:2b:51:2c

10:00:00:00:c9:2b:47:a2
 a| 
group4
 a| 
10:00:00:00:c9:2b:51:2c

10:00:00:00:c9:2b:47:a2
 a| 
`/vol/vol2/qtree2/lun4` `/vol/vol2/qtree1/lun5`

|===