---
permalink: san-admin/iscsi-service-management-system-interfaces-concept.html 
sidebar: sidebar 
keywords: iscsi, service, management 
summary: 'Sie können die Verfügbarkeit des iSCSI-Dienstes auf den logischen iSCSI-Schnittstellen der Storage Virtual Machine (SVM) über die vserver iscsi-Schnittstelle aktivieren oder vserver iscsi-Schnittstelle deaktivieren Befehle verwalten.' 
---
= ISCSI-Service-Management
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Verfügbarkeit des iSCSI-Dienstes auf den logischen iSCSI-Schnittstellen der SVM (Storage Virtual Machine) mit den `vserver iscsi interface enable` `vserver iscsi interface disable` Befehlen oder managen.

Standardmäßig ist der iSCSI-Service auf allen logischen iSCSI-Schnittstellen aktiviert.



== Wie iSCSI auf dem Host implementiert wird

ISCSI kann auf dem Host mithilfe von Hardware oder Software implementiert werden.

Sie können iSCSI auf eine der folgenden Arten implementieren:

* Mit Initiator-Software, die die Standard-Ethernet-Schnittstellen des Hosts verwendet.
* Über einen iSCSI-Host Bus Adapter (HBA): Ein iSCSI-HBA erscheint dem Host-Betriebssystem als SCSI-Festplattenadapter mit lokalen Festplatten.
* Verwendung eines Adapters für die TCP Offload Engine (TOE), der die TCP/IP-Verarbeitung entlastet.
+
Die iSCSI-Protokollverarbeitung wird weiterhin von der Host-Software durchgeführt.


