---
permalink: san-admin/iscsi-interface-access-management-concept.html 
sidebar: sidebar 
keywords: How, using, iscsi, interface, access, lists, limit, initiator, interfaces, increase, performance, security 
summary: ISCSI-Schnittstellenzugriffslisten können verwendet werden, um die Anzahl der LIFs in einer SVM zu begrenzen, auf die ein Initiator zugreifen kann, wodurch Leistung und Sicherheit erhöht werden. 
---
= Wie die Verwendung von iSCSI-Schnittstellenzugriffslisten zur Einschränkung von Initiator-Schnittstellen die Leistung und Sicherheit steigern kann
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ISCSI-Schnittstellenzugriffslisten können verwendet werden, um die Anzahl der LIFs in einer SVM zu begrenzen, auf die ein Initiator zugreifen kann, wodurch Leistung und Sicherheit erhöht werden.

Wenn ein Initiator eine Erkennungssitzung mit einem iSCSI  `SendTargets` Befehl startet, erhält er die IP-Adressen, die der LIF (Netzwerkschnittstelle) zugeordnet sind und sich in der Zugriffsliste befindet. Standardmäßig haben alle Initiatoren Zugriff auf alle iSCSI LIFs in der SVM. Mit der Zugriffsliste kann die Anzahl der LIFs in der SVM, auf die ein Initiator Zugriff hat, eingeschränkt werden.
