---
permalink: san-admin/lifs-cluster-concept.html 
sidebar: sidebar 
keywords: considerations, lifs, cluster, san environments 
summary: Sie müssen bestimmte LIF-Überlegungen in einer SAN-Umgebung beachten. 
---
= Überlegungen zu LIFs in Cluster-SAN-Umgebungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen bestimmte LIF-Überlegungen in einer SAN-Umgebung beachten.

* Initiatoren müssen Multipath I/O (MPIO) und ALUA (Asymmetric Logical Unit Access) für die Failover-Funktion von Clustern in einer SAN-iSCSI- oder FC-Umgebung verwenden, da SAN keinen automatischen Failover für LIFs unterstützt.
* Auf jedem Node, der eine zugeordnete LUN hostet, und dem HA-Partner des Node muss mindestens eine SAN-LIF des entsprechenden Protokolls konfiguriert werden.
+
Sie können zwei LIFs pro Node konfigurieren, eine für jede Fabric, die bei FC verwendet wird, und Ethernet-Netzwerke für iSCSI trennen.

* Einige Optionen gelten nicht für iSCSI oder FC.
+
Beispielsweise können Sie keine IP-Adressen mit FC verwenden.


