---
permalink: san-admin/lun-san-environments-concept.html 
sidebar: sidebar 
keywords: lun, guidelines, assigning, assign, ids, mapping, map, igroups 
summary: Bevor Sie mit dem Einrichten Ihrer LUNs auf dem Cluster beginnen, müssen Sie die LUN-Richtlinien prüfen. 
---
= Was muss ich wissen, bevor Sie eine LUN erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== Warum die tatsächlichen LUN-Größen geringfügig variieren

Sie sollten Folgendes bezüglich der Größe Ihrer LUNs kennen.

* Wenn Sie eine LUN erstellen, kann die tatsächliche Größe der LUN abhängig vom OS-Typ der LUN geringfügig variieren. Der LUN-OS-Typ kann nach dem Erstellen der LUN nicht geändert werden.
* Wenn Sie eine LUN mit der maximalen LUN-Größe erstellen, beachten Sie, dass die tatsächliche Größe der LUN ein wenig geringer sein kann. ONTAP rundet das Limit auf etwas weniger ab.
* Die Metadaten für jede LUN benötigen ca. 64 KB Speicherplatz im Aggregat, das enthalten ist. Wenn Sie eine LUN erstellen, müssen Sie sicherstellen, dass das zugehörige Aggregat über ausreichend Platz für die Metadaten der LUN verfügt. Wenn das Aggregat nicht genügend Speicherplatz für die Metadaten der LUN enthält, können einige Hosts möglicherweise nicht auf die LUN zugreifen.




== Richtlinien für das Zuweisen von LUN-IDs

In der Regel beginnt die Standard-LUN-ID mit 0 und wird jeder zusätzlichen zugeordneten LUN in Schritten von 1 zugewiesen. Der Host ordnet die LUN-ID dem Standort- und Pfadnamen der LUN zu. Der Bereich gültiger LUN-ID-Nummern hängt vom Host ab. Ausführliche Informationen finden Sie in der Dokumentation Ihrer Host Utilities.



== Richtlinien zum Zuordnen von LUNs zu Initiatorgruppen

* Sie können eine LUN nur einmal einer Initiatorgruppe zuordnen.
* Als Best Practice sollten Sie eine LUN über die Initiatorgruppe nur einem bestimmten Initiator zuordnen.
* Sie können einen einzelnen Initiator mehreren Initiatorgruppen hinzufügen, der Initiator kann jedoch nur einer LUN zugeordnet werden.
* Sie können nicht dieselbe LUN-ID für zwei LUNs verwenden, die derselben Initiatorgruppe zugeordnet sind.
* Sie sollten denselben Protokolltyp für Initiatorgruppen und Port-Sets verwenden.

