---
permalink: san-admin/map-nvme-namespace-subsystem-task.html 
sidebar: sidebar 
keywords: map, nvme, namespace, subsystem 
summary: Bei der Verwendung von NVMe müssen Sie einen Namespace zu einem Subsystem zuordnen. 
---
= Zuordnen eines NVMe Namespace zu einem Subsystem
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dieses Verfahren ordnet einen vorhandenen NVMe Namespace über die ONTAP-CLI einem vorhandenen NVMe-Subsystem zu.

Der Namespace und das Subsystem sollten bereits erstellt werden. Wenn Sie einen Namespace und ein Subsystem erstellen müssen, lesen Sie link:create-nvme-namespace-subsystem-task.html["NVMe-Storage wird bereitgestellt"].

.Schritte
. Beziehen Sie das NQN vom Host.
. Fügen Sie den Host-NQN zum Subsystem hinzu:
+
`vserver nvme subsystem host add -vserver _SVM_name_ -subsystem _subsystem_name_ -host-nqn _Host_NQN_:subsystem._subsystem_name_`

. Den Namespace dem Subsystem zuordnen:
+
`vserver nvme subsystem map add -vserver _SVM_name_ -subsystem _subsystem_name_ -path _path_`

+
Ein Namespace kann nur einem einzelnen Subsystem zugeordnet werden.

. Vergewissern Sie sich, dass der Namespace dem Subsystem zugeordnet ist:
+
`vserver nvme namespace show -vserver _SVM_name_ -instance`

+
Das Subsystem sollte als aufgeführt werden `Attached subsystem`.


