---
permalink: san-admin/modify-slm-reporting-nodes-task.html 
sidebar: sidebar 
keywords: modify, slm, reporting-nodes, list 
summary: 'Wenn Sie eine LUN oder ein Volume mit LUNs auf ein anderes HA-Paar (High Availability) innerhalb desselben Clusters verschieben, sollten Sie die Liste mit Berichterstellungknoten für Selective LUN Map (SLM) ändern, bevor Sie die Verschiebung initiieren, um sicherzustellen, dass aktive, optimierte LUN-Pfade beibehalten werden.' 
---
= Ändern Sie die Liste der SLM-Reporting-Nodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie eine LUN oder ein Volume mit LUNs auf ein anderes HA-Paar (High Availability) innerhalb desselben Clusters verschieben, sollten Sie die Liste mit Berichterstellungknoten für Selective LUN Map (SLM) ändern, bevor Sie die Verschiebung initiieren, um sicherzustellen, dass aktive, optimierte LUN-Pfade beibehalten werden.

.Schritte
. Fügen Sie den Ziel-Node und seinen Partner-Node zur Liste der Reporting-Nodes des Aggregats oder Volumes hinzu:
+
`lun mapping add-reporting-nodes -vserver _vserver_name_ -path _lun_path_ -igroup _igroup_name_ [-destination-aggregate _aggregate_name_|-destination-volume _volume_name_]`

+
Wenn Sie eine konsistente Namenskonvention haben, können Sie mehrere LUN-Zuordnungen gleichzeitig ändern, indem Sie verwenden `*-igroup*` Statt `igroup`.

. Prüfen Sie den Host erneut, um die neu hinzugefügten Pfade zu finden.
. Wenn Ihr Betriebssystem benötigt wird, fügen Sie die neuen Pfade zu Ihrer Multipath-Netzwerk-I/O (MPIO)-Konfiguration hinzu.
. Führen Sie den Befehl für den Vorgang der erforderlichen Verschiebung aus, und warten Sie, bis der Vorgang abgeschlossen ist.
. Vergewissern Sie sich, dass die I/O-Verarbeitung über den aktiv/optimierten Pfad erfolgt:
+
`lun mapping show -fields reporting-nodes`

. Entfernen Sie den vorherigen LUN-Eigentümer und seinen Partner-Node aus der Liste der Reporting-Nodes:
+
`lun mapping remove-reporting-nodes -vserver _vserver_name_ -path _lun_path_ -igroup _igroup_name_ -remote-nodes`

. Vergewissern Sie sich, dass die LUN aus der vorhandenen LUN-Zuordnung entfernt wurde:
+
`lun mapping show -fields reporting-nodes`

. Entfernen Sie alle veralteten Geräteeinträge für das Host-Betriebssystem.
. Ändern Sie gegebenenfalls alle Multipathing-Konfigurationsdateien.
. Der Host wird erneut gescannt, um das Entfernen alter Pfade zu überprüfen. + Informationen zu bestimmten Schritten finden Sie in Ihrer Host-Dokumentation, um Ihre Hosts erneut zu scannen.

