---
permalink: san-admin/move-san-lifs-task.html 
sidebar: sidebar 
keywords: move, san, lifs 
summary: Wenn ein Knoten offline genommen werden muss, können Sie eine SAN-LIF verschieben, um deren Konfigurationsinformationen, wie z. B. die WWPN, zu erhalten und eine Neuzonierung der Switch-Fabric zu vermeiden. 
---
= Verschieben Sie eine ONTAP SAN LIF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ein Knoten offline genommen werden muss, können Sie eine SAN LIF verschieben, um deren Konfigurationsinformationen, wie z. B. die WWPN, zu erhalten. Das Verschieben einer LIF erfordert weder eine Neuzonierung Ihres FC-Fabric noch die Erstellung neuer iSCSI-Sitzungen zwischen Cluster-Hosts und der Ziel-Schnittstelle. Sie können SAN LIFs auf jeden beliebigen Knoten im Cluster verschieben, jedoch nicht zwischen Storage Virtual Machines (SVMs).

Sie können eine LIF verschieben, um die folgenden Aktionen unterbrechungsfrei durchzuführen:

* Ersetzen Sie ein HA-Paar eines Clusters durch ein aktualisiertes HA-Paar auf eine Weise, die für Hosts, die auf LUN- oder Namespace-Daten zugreifen, transparent ist
* Aktualisieren einer Zielschnittstellenkarte
* Verschieben Sie die Ressourcen einer Storage Virtual Machine (SVM) von einem Node-Satz in einem Cluster zu einer anderen Gruppe von Nodes im Cluster


Sie können ein SAN LIF nicht mit dem  `network interface move` Befehl verschieben. Um ein SAN LIF zu verschieben, müssen Sie es offline nehmen, auf einen neuen Home-Node oder Port verschieben und dann wieder online schalten. Da ein SAN LIF vor der Verschiebung offline genommen werden muss, muss der Host-Datenverkehr auf Host-Multipathing-Software zurückgreifen, um unterbrechungsfreien Zugriff auf die LUN zu gewährleisten, sodass keine E/A-Unterbrechung auftritt.

.Bevor Sie beginnen
Wenn die LIF Mitglied eines Port-Satzes ist, muss die LIF aus dem Portsatz entfernt worden sein, bevor die LIF zu einem anderen Node verschoben werden kann.

.Über diese Aufgabe
Der Ziel-Node und der physische Port für eine LIF, die Sie verschieben möchten, müssen sich in derselben FC-Fabric oder einem Ethernet-Netzwerk befinden. Wenn Sie ein LIF auf ein anderes Fabric verschieben, das nicht richtig begrenzt wurde, oder wenn Sie ein LIF in ein Ethernet-Netzwerk verschieben, das keine Verbindung zwischen iSCSI-Initiator und Ziel hat, ist die LUN nicht zugänglich, wenn Sie sie wieder in den Online-Modus versetzen.

.Schritte
. Anzeigen des Administrations- und Betriebsstatus der LIF:
+
[source, cli]
----
network interface show -vserver <SVM_name>
----
+
Erfahren Sie mehr über `network interface show` in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["ONTAP-Befehlsreferenz"^].

. Ändern Sie den Status der LIF in `down` (offline):
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <LIF_name> -status-admin down
----
+
Erfahren Sie mehr über `network interface modify` in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html["ONTAP-Befehlsreferenz"^].

. Weisen Sie der LIF einen neuen Node und neuen Port zu:
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <LIF_name> -home-node <node_name> -home-port <port_name>
----
. Ändern Sie den Status des LIF in `up` (online):
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <LIF_name> -status-admin up
----
. Überprüfen Sie Ihre Änderungen:
+
[source, cli]
----
network interface show -vserver <SVM_name>
----

