---
permalink: san-admin/prevent-loss-connectivity-x1133a-r6-adapter-concept.html 
sidebar: sidebar 
keywords: how to, prevent, loss of connectivity, using, x1133a-r6 adapter 
summary: Ein Verbindungsverlust während eines Portausfalls lässt sich verhindern, wenn das System mit redundanten Pfaden zu separaten X1133A-R6 HBAs konfiguriert ist. 
---
= Verlust der Konnektivität bei Verwendung des X1133A-R6 Adapters verhindern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Verbindungsverlust während eines Portausfalls lässt sich verhindern, wenn das System mit redundanten Pfaden zu separaten X1133A-R6 HBAs konfiguriert ist.

Der X1133A-R6 HBA ist ein 4-Port 16-Gb-FC-Adapter, bestehend aus zwei 2-Port-Paaren. Der X1133A-R6 Adapter kann im Target-Modus oder Initiator-Modus konfiguriert werden. Jedes 2-Port-Paar wird von einem einzelnen ASIC unterstützt (zum Beispiel Port 1 und Port 2 auf ASIC 1 sowie Port 3 und Port 4 auf ASIC 2). Beide Ports eines einzelnen ASIC müssen im selben Modus betrieben werden, entweder im Target-Modus oder im Initiator-Modus. Tritt ein Fehler bei dem ASIC auf, der ein Paar unterstützt, gehen beide Ports des Paares offline.

Um diesen Verbindungsverlust zu verhindern, wird das System mit redundanten Pfaden zu separaten X1133A-R6 HBAs oder mit redundanten Pfaden zu Ports, die von verschiedenen ASICs auf dem HBA unterstützt werden, konfiguriert.
