---
permalink: san-admin/restore-all-luns-volume-snapshot-copy-task.html 
sidebar: sidebar 
keywords: restore, all, luns in a volume, from, snapshot copy 
summary: Sie können den Wiederherstellungsbefehl für Volume Snapshot verwenden, um alle LUNs in einem angegebenen Volume aus einem Snapshot wiederherzustellen. 
---
= Stellen Sie alle LUNs in einem Volume aus einem Snapshot wieder her
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit dem Befehl können Sie `volume snapshot restore` alle LUNs in einem angegebenen Volume aus einem Snapshot wiederherstellen.

.Schritte
. Beenden Sie vom Host den gesamten Host-Zugriff auf die LUNs.
+
Die Verwendung von SnapRestore ohne die Unterbrechung des gesamten Host-Zugriffs auf LUNs im Volume kann zu Datenbeschädigungen und Systemfehlern führen.

. Heben Sie die Bereitstellung der LUNs auf diesem Host auf, damit der Host nicht auf die LUNs zugreifen kann.
. LUNs-Zuordnung aufheben:
+
`lun mapping delete -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -igroup _igroup_name_`

. Bestimmen Sie den Snapshot, auf dem Sie Ihr Volume wiederherstellen möchten:
+
`volume snapshot show -vserver _vserver_name_ -volume _volume_name_`

. Ändern Sie Ihre Berechtigungseinstellung in erweitert:
+
`set -privilege advanced`

. Wiederherstellen von Daten:
+
`volume snapshot restore -vserver _vserver_name_ -volume _volume_name_ -snapshot _snapshot_name_`

. Befolgen Sie die Anweisungen auf dem Bildschirm.
. LUNs neu zuordnen:
+
`lun mapping create -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -igroup _igroup_name_`

. Vergewissern Sie sich, dass Ihre LUNs online sind:
+
`lun show -vserver _vserver_name_ -path _lun_path_ -fields state`

. Wenn Ihre LUNs nicht online sind, bringen Sie sie in den Online-Modus:
+
`lun modify -vserver _vserver_name_ -path _lun_path_ -state online`

. Ändern Sie Ihre Berechtigungseinstellung in admin:
+
`set -privilege admin`

. Mounten Sie die LUNs vom Host neu.
. Starten Sie den Zugriff auf Ihre LUNs vom Host aus neu.

