---
permalink: san-admin/restore-all-luns-volume-snapshot-copy-task.html 
sidebar: sidebar 
keywords: restore, all, luns in a volume, from, snapshot copy 
summary: Sie können den Wiederherstellungsbefehl für Volume Snapshot verwenden, um alle LUNs in einem angegebenen Volume aus einem Snapshot wiederherzustellen. 
---
= Stellen Sie alle LUNs in einem Volume aus einem ONTAP-Snapshot wieder her
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit dem Befehl können Sie `volume snapshot restore` alle LUNs in einem angegebenen Volume aus einem Snapshot wiederherstellen.

.Schritte
. Beenden Sie vom Host den gesamten Host-Zugriff auf die LUNs.
+
Die Verwendung von SnapRestore ohne die Unterbrechung des gesamten Host-Zugriffs auf LUNs im Volume kann zu Datenbeschädigungen und Systemfehlern führen.

. Heben Sie die Bereitstellung der LUNs auf diesem Host auf, damit der Host nicht auf die LUNs zugreifen kann.
. LUNs-Zuordnung aufheben:
+
[source, cli]
----
lun mapping delete -vserver <SVM_name> -volume <volume_name> -lun <lun_name> -igroup <igroup_name>
----
. Bestimmen Sie den Snapshot, auf dem Sie Ihr Volume wiederherstellen möchten:
+
[source, cli]
----
volume snapshot show -vserver <SVM_name> -volume <volume_name>

----
. Ändern Sie Ihre Berechtigungseinstellung in erweitert:
+
[source, cli]
----
set -privilege advanced
----
. Wiederherstellen von Daten:
+
[source, cli]
----
volume snapshot restore -vserver <SVM_name> -volume <volume_name> -snapshot <snapshot_name>
----
. Befolgen Sie die Anweisungen auf dem Bildschirm.
. LUNs neu zuordnen:
+
[source, cli]
----
lun mapping create -vserver <SVM_name> -volume <volume_name> -lun <lun_name> -igroup <igroup_name>
----
. Vergewissern Sie sich, dass Ihre LUNs online sind:
+
[source, cli]
----
lun show -vserver <SVM_name> -path <lun_path> -fields state
----
. Wenn Ihre LUNs nicht online sind, bringen Sie sie in den Online-Modus:
+
[source, cli]
----
lun modify -vserver <SVM_name> -path <lun_path> -state online
----
. Ändern Sie Ihre Berechtigungseinstellung in admin:
+
[source, cli]
----
set -privilege admin
----
. Mounten Sie die LUNs vom Host neu.
. Starten Sie den Zugriff auf Ihre LUNs vom Host aus neu.

