---
permalink: san-admin/san-provisioning-nvme-concept.html 
sidebar: sidebar 
keywords: san, provisioning, nvme 
summary: Ab ONTAP 9.4 wird NVMe FC in SAN-Umgebungen unterstützt. NVMe FC ermöglicht es Speicheradministratoren, Namespaces und Subsysteme bereitzustellen und anschließend die Namespaces Subsystemen zuzuordnen, ähnlich wie LUNs für FC und iSCSI bereitgestellt und Initiatorgruppen zugeordnet werden. 
---
= SAN-Bereitstellung mit NVMe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.4 wird NVMe/FC in SAN-Umgebungen unterstützt. NVMe/FC ermöglicht Speicheradministratoren die Bereitstellung von Namespaces und Subsystemen sowie die Zuordnung der Namespaces zu Subsystemen, ähnlich wie LUNs für FC und iSCSI bereitgestellt und Initiatorgruppen zugeordnet werden.

Ein NVMe-Namensraum ist eine Menge nichtflüchtigen Speichers, die in logische Blöcke formatiert werden kann. Namensräume entsprechen den LUNs der FC- und iSCSI-Protokolle, und ein NVMe-Subsystem ist analog zu einer Initiatorgruppe. Ein NVMe-Subsystem kann mit Initiatoren verknüpft werden, sodass die Namensräume innerhalb des Subsystems von den zugehörigen Initiatoren genutzt werden können.

[NOTE]
====
Obwohl NVMe-Namespaces in ihrer Funktion analog sind, werden nicht alle von LUNs unterstützten Funktionen unterstützt.

====
Ab ONTAP 9.5 ist eine Lizenz erforderlich, um den hostseitigen Datenzugriff mit NVMe zu unterstützen. Wenn NVMe in ONTAP 9.4 aktiviert ist, wird nach dem Upgrade auf ONTAP 9.5 eine 90-tägige Kulanzfrist gewährt, um die Lizenz zu erwerben. Wenn Sie link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"]haben, ist die NVMe-Lizenz enthalten. Die Lizenz kann mit dem folgenden Befehl aktiviert werden:

`system license add -license-code _NVMe_license_key_`

.Verwandte Informationen
https://www.netapp.com/pdf.html?item=/media/10681-tr4684.pdf["NetApp Technical Report 4684: Implementierung und Konfiguration moderner SANs mit NVMe/FC"^]
