---
permalink: san-admin/set-fractional-reserve-concept.html 
sidebar: sidebar 
keywords: considerations, setting, fractional, reserve 
summary: Die fraktionale Reserve, die auch LUN Überschreibungsreserve genannt wird, ermöglicht es Ihnen, Überschreibungsreserve für platzsparende LUNs und Dateien in einem FlexVol Volume auszuschalten. So können Sie Ihre Storage-Auslastung maximieren, aber wenn Ihre Umgebung durch mangelnde Schreibzugriffe beeinträchtigt ist, müssen Sie die Anforderungen dieser Konfiguration kennen und verstehen, die diese Konfiguration mit sich bringt. 
---
= Überlegungen bei der Festlegung der fraktionalen Reserve
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die fraktionale Reserve, auch _LUN Overwrite Reserve_ genannt, ermöglicht Ihnen die Abschaltung der Überschreibungsreserve für platzsparende LUNs und Dateien in einem FlexVol Volume. So können Sie Ihre Storage-Auslastung maximieren, aber wenn Ihre Umgebung durch mangelnde Schreibzugriffe beeinträchtigt ist, müssen Sie die Anforderungen dieser Konfiguration kennen und verstehen, die diese Konfiguration mit sich bringt.

Die Einstellung für die fraktionale Reserve wird als Prozentsatz angegeben; die einzigen gültigen Werte sind `0` und `100` Prozent. Die Einstellung der fraktionalen Reserve ist ein Attribut des Volume.

Wenn Sie die fraktionale Reserve einstellen, um `0` Ihre Storage-Auslastung zu erhöhen. Bei einer Applikation, die auf Daten im Volume zugreift, kann es jedoch zu einem Datenausfall kommen, wenn der Speicherplatz auf `volume`dem Volume nicht mehr voll ist, selbst wenn die Volume-Garantie auf festgelegt ist. Durch ordnungsgemäße Volume-Konfiguration und Nutzung können Sie jedoch die Wahrscheinlichkeit eines Schreibversagens minimieren. ONTAP bietet eine „`Best Effort`“-Schreibgarantie für Volumes mit einer fraktionalen Reserve `0`, die auf „ all“ der folgenden Anforderungen gesetzt wurde:

* Die Deduplizierung wird nicht verwendet
* Die Komprimierung wird nicht verwendet
* Die Unterdateien von FlexClone werden nicht verwendet
* Alle FlexClone Dateien und FlexClone LUNs sind zum automatischen Löschen aktiviert
+
Dies ist nicht die Standardeinstellung. Sie müssen das automatische Löschen entweder während der Erstellung oder durch Ändern der FlexClone Datei oder der FlexClone LUN nach der Erstellung aktivieren.

* ODX und FlexClone Copy Offload werden derzeit nicht genutzt
* Volume-Garantie wird auf festgelegt `volume`
* Die Speicherplatzreservierung für Datei oder LUN ist `enabled`
* Die Volume Snapshot Reserve wurde auf festgelegt `0`
* Volume Snapshot automatische Löschung ist `enabled` mit einem Commitment-Level von `destroy`, eine Destroy-Liste von `lun_clone,vol_clone,cifs_share,file_clone,sfsr`, und ein Trigger von `volume`
+
Diese Einstellung stellt zudem sicher, dass FlexClone Dateien und FlexClone LUNs im Bedarfsfall gelöscht werden.



Beachten Sie, dass bei einer hohen Änderungsrate in seltenen Fällen das automatische Löschen von Snapshots zurückfallen kann, was dazu führt, dass der Speicherplatz auf dem Volume nicht mehr zur Verfügung steht, selbst wenn alle oben genannten erforderlichen Konfigurationseinstellungen verwendet werden.

Optional können Sie auch die Volume Autogrow Funktion verwenden, um die Wahrscheinlichkeit zu verringern, dass Volume Snapshots automatisch gelöscht werden müssen. Wenn Sie die Autogrow-Funktion aktivieren, müssen Sie den freien Speicherplatz im zugehörigen Aggregat überwachen. Wenn das Aggregat voll genug wird, dass das Volumen daran gehindert wird zu wachsen, werden wahrscheinlich mehr Snapshots gelöscht werden, da der freie Platz im Volumen erschöpft ist.

Wenn Sie nicht alle oben genannten Konfigurationsanforderungen erfüllen können und Sie sicherstellen müssen, dass dem Volume nicht der Platz knapp wird, müssen Sie die fraktionale Reserve des Volume auf einstellen `100`. Dies erfordert vorab mehr freien Speicherplatz, garantiert jedoch, dass Datenänderungen auch dann erfolgreich ausgeführt werden, wenn die oben aufgeführten Technologien eingesetzt werden.

Der Standardwert und die zulässigen Werte für die Einstellung der fraktionalen Reserve hängen von der Garantie des Volume ab:

[cols="3*"]
|===
| Volume-Garantie | Standardmäßige fraktionale Reserve | Zulässige Werte 


 a| 
Datenmenge
 a| 
100
 a| 
0, 100



 a| 
Keine
 a| 
0
 a| 
0, 100

|===