---
permalink: san-admin/storage-virtualization-vmware-copy-offload-concept.html 
sidebar: sidebar 
keywords: storage, virtualization, vmware, microsoft, copy, offload, advantages, virtualized, san 
summary: Kopierauslagerungsoperationen von VMware und Microsoft zur Steigerung der Performance und des Netzwerkdurchsatzes Sie müssen Ihr System so konfigurieren, dass es die Anforderungen der Betriebssystemumgebungen von VMware und Windows erfüllt, damit die jeweiligen Funktionen zur Offload von Kopien genutzt werden können. 
---
= Überblick: Storage-Virtualisierung mit VMware und Microsoft Copy-Offload
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Kopierauslagerungsoperationen von VMware und Microsoft zur Steigerung der Performance und des Netzwerkdurchsatzes Sie müssen Ihr System so konfigurieren, dass es die Anforderungen der Betriebssystemumgebungen von VMware und Windows erfüllt, damit die jeweiligen Funktionen zur Offload von Kopien genutzt werden können.

Bei der Nutzung von VMware und Microsoft Copy-Offload in virtualisierten Umgebungen müssen Ihre LUNs aufeinander abgestimmt werden. Nicht ausgerichtete LUNs können die Performance beeinträchtigen.



== Vorteile der Nutzung einer virtualisierten SAN-Umgebung

Wenn Sie eine virtualisierte Umgebung mithilfe von Storage Virtual Machines (SVMs) und LIFs erstellen, können Sie Ihre SAN-Umgebung auf alle Nodes im Cluster erweitern.

* Dezentrales Management
+
Sie können sich bei jedem Node in der SVM anmelden, um alle Nodes in einem Cluster zu verwalten.

* Verbesserter Datenzugriff
+
Mit MPIO und ALUA haben Sie Zugriff auf Ihre Daten über alle aktiven iSCSI oder FC LIFs für die SVM.

* Kontrollierter LUN-Zugriff
+
Wenn Sie SLM und Portsätze verwenden, können Sie die Anzahl der LIFs begrenzen, die ein Initiator zum Zugriff auf LUNs verwenden kann.


