---
permalink: smb-config/assess-networking-requirements-task.html 
sidebar: sidebar 
keywords: provide, smb, storage, client, verify, network, configure, provision, requirement, assess, assess networking requirements 
summary: Bevor Sie Clients SMB Storage zur Verfügung stellen, müssen Sie überprüfen, ob das Netzwerk ordnungsgemäß konfiguriert ist, um die SMB-Bereitstellungsanforderungen zu erfüllen. 
---
= Netzwerkanforderungen bewerten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie Clients SMB Storage zur Verfügung stellen, müssen Sie überprüfen, ob das Netzwerk ordnungsgemäß konfiguriert ist, um die SMB-Bereitstellungsanforderungen zu erfüllen.

.Bevor Sie beginnen
Die folgenden Cluster-Netzwerkobjekte müssen konfiguriert werden:

* Physische und logische Ports
* Broadcast-Domänen
* Subnetze (falls erforderlich)
* IPspaces (nach Bedarf zusätzlich zum Standard-IPspace)
* Failover-Gruppen (falls erforderlich, zusätzlich zur Standard-Failover-Gruppe für jede Broadcast-Domäne)
* Externe Firewalls


.Schritte
. Anzeigen der verfügbaren physischen und virtuellen Ports: `network port show`
+
** Wenn möglich, sollten Sie den Port mit der höchsten Geschwindigkeit für das Datennetzwerk verwenden.
** Für optimale Performance müssen alle Komponenten im Datennetzwerk dieselbe MTU-Einstellung aufweisen.


. Wenn Sie planen, einen Subnetznamen zu verwenden, um die IP-Adresse und den Netzwerkmaskenwert für eine LIF zuzuweisen, überprüfen Sie, ob das Subnetz existiert und über ausreichende Adressen verfügbar ist: `network subnet show`
+
Subnetze enthalten einen Pool mit IP-Adressen, die zum selben Layer-3-Subnetz gehören. Subnetze werden mithilfe des erstellt `network subnet create` Befehl.

. Verfügbare IPspaces anzeigen: `network ipspace show`
+
Sie können den Standard-IPspace oder einen benutzerdefinierten IPspace verwenden.

. Wenn Sie IPv6-Adressen verwenden möchten, überprüfen Sie, ob IPv6 auf dem Cluster aktiviert ist: `network options ipv6 show`
+
Bei Bedarf können Sie IPv6 mithilfe des aktivieren `network options ipv6 modify` Befehl.


