---
permalink: smb-config/configure-client-access-shared-storage-concept.html 
sidebar: sidebar 
keywords: smb, client, access, storage, svm, create, volume, qtree, container, modify, share, file, permission, test, configure smb client access to shared storage 
summary: Um SMB-Clients Zugriff auf gemeinsam genutzten Speicher auf einer SVM bereitzustellen, muss ein Volume oder ein Qtree als Speichercontainer erstellt und anschließend eine Freigabe für diesen Container erstellt oder geändert werden. Anschließend können Freigabe- und Dateiberechtigungen konfiguriert und der Zugriff von Clientsystemen getestet werden. 
---
= Konfiguration des SMB-Clientzugriffs auf gemeinsam genutzten ONTAP Speicher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um SMB-Clients Zugriff auf gemeinsam genutzten Speicher auf einer SVM bereitzustellen, muss ein Volume oder ein Qtree als Speichercontainer erstellt und anschließend eine Freigabe für diesen Container erstellt oder geändert werden. Anschließend können Freigabe- und Dateiberechtigungen konfiguriert und der Zugriff von Clientsystemen getestet werden.

.Bevor Sie beginnen
* SMB muss auf der SVM vollständig eingerichtet sein.
* Alle Aktualisierungen Ihrer Namensdienstkonfiguration müssen vollständig abgeschlossen sein.
* Jegliche Ergänzungen oder Änderungen an einer Active Directory Domänen- oder Arbeitsgruppenkonfiguration müssen vollständig abgeschlossen sein.

