---
permalink: smb-config/configure-time-services-task.html 
sidebar: sidebar 
keywords: creating, create, smb, server, active, domain, controller, ensure, cluster, time, match, configure time services 
summary: Bevor Sie einen SMB-Server in einem Active Domain-Controller erstellen, müssen Sie sicherstellen, dass die Clusterzeit und die Zeit auf den Domänencontrollern der Domäne, zu der der SMB-Server gehört, innerhalb von fünf Minuten übereinstimmen. 
---
= Konfiguration der ONTAP Time Services für SMB-Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie einen SMB-Server in einem Active Domain-Controller erstellen, müssen Sie sicherstellen, dass die Clusterzeit und die Zeit auf den Domänencontrollern der Domäne, zu der der SMB-Server gehört, innerhalb von fünf Minuten übereinstimmen.

.Über diese Aufgabe
Sie sollten die Cluster-NTP-Dienste so konfigurieren, dass sie für die Synchronisierung dieselben NTP-Server verwenden, die auch die Active Directory-Domäne nutzt.

Ab ONTAP 9.5 können Sie Ihren NTP-Server mit symmetrischer Authentifizierung einrichten.

.Schritte
. Konfigurieren Sie Zeitdienste mit dem `cluster time-service ntp server create` Befehl.
+
** Geben Sie den folgenden Befehl ein, um Time Services ohne symmetrische Authentifizierung zu konfigurieren: `cluster time-service ntp server create -server server_ip_address`
** Geben Sie den folgenden Befehl ein, um Zeitdienste mit symmetrischer Authentifizierung zu konfigurieren: `cluster time-service ntp server create -server server_ip_address -key-id key_id`
`cluster time-service ntp server create -server 10.10.10.1` `cluster time-service ntp server create -server 10.10.10.2`


. Überprüfen Sie mit dem `cluster time-service ntp server show` Befehl, ob die Zeitdienste ordnungsgemäß eingerichtet wurden.
+
`cluster time-service ntp server show`

+
[listing]
----

Server                         Version
------------------------------ -------
10.10.10.1                     auto
10.10.10.2                     auto
----


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=cluster+time-service+ntp["Cluster Time Service ntp"^]

