---
permalink: smb-config/configure-dns-host-name-resolution-task.html 
sidebar: sidebar 
keywords: vserver, name-service, service, dns, command, enable, svm, host-name, resolution, host, name, resolve, external, enable dns for host-name resolution 
summary: 'Der Befehl `vserver services name-service dns` kann verwendet werden, um DNS auf einer SVM zu aktivieren und so zu konfigurieren, dass DNS für die Hostnamenauflösung verwendet wird. Hostnamen werden mithilfe externer DNS-Server aufgelöst.' 
---
= DNS für die ONTAP SMB-Hostnamensauflösung aktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den  `vserver services name-service dns` Befehl verwenden, um DNS auf einer SVM zu aktivieren und sie so zu konfigurieren, dass sie DNS für die Hostnamensauflösung verwendet. Hostnamen werden mithilfe externer DNS-Server aufgelöst. Weitere Informationen zu  `vserver services name-service dns` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+services+name-service+dns["ONTAP-Befehlsreferenz"^].

.Bevor Sie beginnen
Für die Auflösung von Hostnamen muss ein standortweiter DNS-Server verfügbar sein.

Es empfiehlt sich, mehr als einen DNS-Server zu konfigurieren, um einen Single Point of Failure zu vermeiden. Der  `vserver services name-service dns create` Befehl gibt eine Warnung aus, wenn nur ein DNS-Servername eingegeben wird. Weitere Informationen zu  `vserver services name-service dns create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-services-name-service-dns-create.html["ONTAP-Befehlsreferenz"^].

.Über diese Aufgabe
Weitere Informationen zu link:../networking/configure_dynamic_dns_services.html["Konfiguration von dynamischem DNS auf der SVM"].

.Schritte
. DNS auf der SVM aktivieren: `vserver services name-service dns create -vserver vserver_name -domains domain_name -name-servers ip_addresses -state enabled`
+
Der folgende Befehl aktiviert externe DNS-Server auf der SVM vs1:

+
[listing]
----
vserver services name-service dns create -vserver vs1.example.com -domains example.com -name-servers 192.0.2.201,192.0.2.202 -state enabled
----
+
[NOTE]
====
Der  `vserver services name-service dns create` Befehl führt eine automatische Konfigurationsprüfung durch und gibt eine Fehlermeldung aus, wenn ONTAP den Nameserver nicht erreichen kann.

====
. Die DNS-Domänenkonfigurationen werden mit dem  `vserver services name-service dns show` Befehl angezeigt.
+
Der folgende Befehl zeigt die DNS-Konfigurationen für alle SVMs im Cluster an:

+
[listing]
----
vserver services name-service dns show
                                             Name
Vserver           State     Domains             Servers
----------------- --------- ------------------- -------------
cluster1          enabled   example.com         192.0.2.201,
                                                192.0.2.202
vs1.example.com   enabled   example.com         192.0.2.201,
                                                192.0.2.202
----
+
Der folgende Befehl zeigt detaillierte DNS-Konfigurationsinformationen für SVM vs1 an:

+
[listing]
----
vserver services name-service dns show -vserver vs1.example.com
               Vserver: vs1.example.com
               Domains: example.com
          Name Servers: 192.0.2.201, 192.0.2.202
    Enable/Disable DNS: enabled
        Timeout (secs): 2
      Maximum Attempts: 1
----
. Der Status der Nameserver kann mit dem  `vserver services name-service dns check` Befehl validiert werden.
+
[listing]
----
vserver services name-service dns check -vserver vs1.example.com

Vserver           Name Server     Status       Status Details
----------------  -------------   ----------   --------------------------
vs1.example.com   10.0.0.50         up         Response time (msec): 2
vs1.example.com   10.0.0.51         up         Response time (msec): 2
----

