---
permalink: smb-config/create-share-task.html 
sidebar: sidebar 
keywords: create, smb, share, data, server, client, properties, home, directory, designate, designating, customize, configure, configuring, optional, setting, create an smb share 
summary: Sie müssen eine SMB-Freigabe erstellen, bevor Sie Daten von einem SMB-Server für SMB-Clients freigeben können. Wenn Sie eine Freigabe erstellen, können Sie Freigabegenschaften festlegen, wie z. B. die Freigabe als Home-Verzeichnis zu bezeichnen. Sie können die Freigabe auch anpassen, indem Sie optionale Einstellungen konfigurieren. 
---
= Erstellen Sie eine SMB-Freigabe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen eine SMB-Freigabe erstellen, bevor Sie Daten von einem SMB-Server für SMB-Clients freigeben können. Wenn Sie eine Freigabe erstellen, können Sie Freigabegenschaften festlegen, wie z. B. die Freigabe als Home-Verzeichnis zu bezeichnen. Sie können die Freigabe auch anpassen, indem Sie optionale Einstellungen konfigurieren.

.Bevor Sie beginnen
Der Verzeichnispfad für Volume oder qtree muss im SVM-Namespace vorhanden sein, bevor die Freigabe erstellt wird.

.Über diese Aufgabe
Wenn Sie eine Freigabe erstellen, lautet die Standard-Freigabe-ACL (Standard-Freigabeberechtigungen) `Everyone / Full Control` . Nachdem Sie den Zugriff auf die Freigabe getestet haben, sollten Sie die Standard-Share-ACL entfernen und sie durch eine sicherere Alternative ersetzen.

.Schritte
. Erstellen Sie bei Bedarf die Verzeichnispfadstruktur für die Freigabe.
+
Der `vserver cifs share create` Befehl überprüft den in der `-path` Option während der Erstellung von Freigaben angegebenen Pfad. Wenn der angegebene Pfad nicht vorhanden ist, schlägt der Befehl fehl.

. Mit der angegebenen SVM verbundene SMB-Freigabe erstellen: `+vserver cifs share create -vserver vserver_name -share-name share_name -path path [-share-properties share_properties,...] [other_attributes] [-comment text]+`
. Überprüfen Sie, ob die Freigabe erstellt wurde:``vserver cifs share show -share-name share_name``


.Beispiele
Mit dem folgenden Befehl wird eine SMB-Freigabe namens „`SHARE1`“ auf SVM erstellt `vs1.example.com`. Sein Verzeichnispfad ist `/users`, und er wird mit Standardeigenschaften erstellt.

[listing]
----
cluster1::> vserver cifs share create -vserver vs1.example.com -share-name SHARE1 -path /users

cluster1::> vserver cifs share show -share-name SHARE1

Vserver          Share    Path     Properties Comment  ACL
---------------  -------- -------- ---------- -------- -----------
vs1.example.com  SHARE1   /users   oplocks    -        Everyone / Full Control
                                   browsable
                                   changenotify
                                   show-previous-versions
----