---
permalink: smb-config/create-local-user-accounts-task.html 
sidebar: sidebar 
keywords: create, local, user, account, authorize, access, data, contain, svm, sb, connection, local, user, authentication, create local user accounts 
summary: Sie können ein lokales Benutzerkonto erstellen, das zur Autorisierung des Zugriffs auf die im SVM enthaltenen Daten über eine SMB-Verbindung verwendet werden kann. Sie können lokale Benutzerkonten auch für die Authentifizierung beim Erstellen einer SMB-Sitzung verwenden. 
---
= Lokale ONTAP SMB-Benutzerkonten erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein lokales Benutzerkonto erstellen, das zur Autorisierung des Zugriffs auf die im SVM enthaltenen Daten über eine SMB-Verbindung verwendet werden kann. Sie können lokale Benutzerkonten auch für die Authentifizierung beim Erstellen einer SMB-Sitzung verwenden.

.Über diese Aufgabe
Die Funktionalität für lokale Benutzer ist bei der Erstellung der SVM standardmäßig aktiviert.

Wenn ein lokales Benutzerkonto erstellt wird, müssen ein Benutzername und die SVM angegeben werden, mit der das Konto verknüpft wird.

Weitere Informationen zu `vserver cifs users-and-groups local-user` und optionalen Parametern sowie Namensanforderungen finden Sie in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs+users-and-groups+local-user["ONTAP-Befehlsreferenz"^].

.Schritte
. Lokalen Benutzer anlegen: `vserver cifs users-and-groups local-user create -vserver _vserver_name_ -user-name _user_name_ _optional_parameters_`
+
Folgende optionale Parameter könnten nützlich sein:

+
** `-full-name`
+
Der vollständige Name des Benutzers.

** `-description`
+
Eine Beschreibung für den lokalen Benutzer.

** `-is-account-disabled {true|false}`
+
Gibt an, ob das Benutzerkonto aktiviert oder deaktiviert ist. Wenn dieser Parameter nicht angegeben wird, ist das Benutzerkonto standardmäßig aktiviert.



+
Der Befehl fordert zur Eingabe des Passworts des lokalen Benutzers auf.

. Ein Passwort für den lokalen Benutzer eingeben und anschließend das Passwort bestätigen.
. Es wird überprüft, ob der Benutzer erfolgreich erstellt wurde: `vserver cifs users-and-groups local-user show -vserver _vserver_name_`


.Beispiel
Das folgende Beispiel erstellt einen lokalen Benutzer "`SMB_SERVER01\sue`" mit dem vollständigen Namen "`Sue Chang`", der mit SVM vs1.example.com verknüpft ist:

[listing]
----
cluster1::> vserver cifs users-and-groups local-user create -vserver vs1.example.com ‑user-name SMB_SERVER01\sue -full-name "Sue Chang"

Enter the password:
Confirm the password:

cluster1::> vserver cifs users-and-groups local-user show
Vserver  User Name                  Full Name  Description
-------- -------------------------- ---------- -------------
vs1      SMB_SERVER01\Administrator            Built-in administrator account
vs1      SMB_SERVER01\sue            Sue Chang
----