---
permalink: smb-config/create-local-groups-task.html 
sidebar: sidebar 
keywords: create, local, group, authorize, authorizing, access, data, associate, svm, smb, connection, assign, privilege, define, right, capabilities, capability, member, create local groups 
summary: Lokale Gruppen können zur Autorisierung des Zugriffs auf Daten, die der SVM zugeordnet sind, über eine SMB-Verbindung erstellt werden. Sie können auch Berechtigungen zuweisen, die definieren, welche Benutzerrechte oder Funktionen ein Mitglied der Gruppe hat. 
---
= Erstellen von lokalen Gruppen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lokale Gruppen können zur Autorisierung des Zugriffs auf Daten, die der SVM zugeordnet sind, über eine SMB-Verbindung erstellt werden. Sie können auch Berechtigungen zuweisen, die definieren, welche Benutzerrechte oder Funktionen ein Mitglied der Gruppe hat.

.Über diese Aufgabe
Bei der Erstellung der SVM ist die Funktion der lokalen Gruppe standardmäßig aktiviert.

Beim Erstellen einer lokalen Gruppe müssen Sie einen Namen für die Gruppe angeben. Sie müssen die SVM angeben, der die Gruppe zugeordnet werden soll. Sie können einen Gruppennamen mit oder ohne lokalen Domänennamen angeben und optional eine Beschreibung für die lokale Gruppe angeben. Sie können einer anderen lokalen Gruppe keine lokale Gruppe hinzufügen.

Der `vserver cifs users-and-groups local-group` Handbuch-Seiten enthalten Details zu optionalen Parametern und Benennungsanforderungen.

.Schritte
. Erstellen Sie die lokale Gruppe: `vserver cifs users-and-groups local-group create -vserver vserver_name -group-name group_name`
+
Der folgende optionale Parameter könnte hilfreich sein:

+
** `-description`
+
Eine Beschreibung für die lokale Gruppe.



. Vergewissern Sie sich, dass die Gruppe erfolgreich erstellt wurde: `vserver cifs users-and-groups local-group show -vserver vserver_name`


.Beispiel
Im folgenden Beispiel wird eine lokale Gruppe „`SMB_SERVER01\Engineering`“ erstellt, die zu SVM vs1 gehört:

[listing]
----
cluster1::> vserver cifs users-and-groups local-group create -vserver vs1.example.com -group-name SMB_SERVER01\engineering

cluster1::> vserver cifs users-and-groups local-group show -vserver vs1.example.com
Vserver          Group Name                   Description
---------------- ---------------------------- ----------------------------
vs1.example.com  BUILTIN\Administrators       Built-in Administrators group
vs1.example.com  BUILTIN\Backup Operators     Backup Operators group
vs1.example.com  BUILTIN\Power Users          Restricted administrative privileges
vs1.example.com  BUILTIN\Users                All users
vs1.example.com  SMB_SERVER01\engineering
vs1.example.com  SMB_SERVER01\sales
----
.Nachdem Sie fertig sind
Sie müssen der neuen Gruppe Mitglieder hinzufügen.
