---
permalink: smb-config/create-svms-data-access-task.html 
sidebar: sidebar 
keywords: svm, cluster, data, access, smb, client, create, create an svm 
summary: Wenn nicht bereits mindestens eine SVM in einem Cluster vorhanden ist, um den Datenzugriff für SMB-Clients zu ermöglichen, muss eine SVM erstellt werden. 
---
= Erstellen einer SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn nicht bereits mindestens eine SVM in einem Cluster vorhanden ist, um den Datenzugriff für SMB-Clients zu ermöglichen, muss eine SVM erstellt werden.

.Schritte
. SVM erstellen: `vserver create -vserver vserver_name -rootvolume root_volume_name -aggregate aggregate_name -rootvolume-security-style ntfs -language C.UTF-8 -ipspace ipspace_name`
+
** Verwenden Sie die NTFS-Einstellung für das `-rootvolume-security-style` Option.
** Verwenden Sie die Standard-C.UTF-8 `-language` Option.
** Der `ipspace` Die Einstellung ist optional.


. Konfiguration und Status der neu erstellten SVM überprüfen: `vserver show -vserver vserver_name`
+
Der `Allowed Protocols` Feld muss CIFS enthalten. Sie können diese Liste später bearbeiten.

+
Der `Vserver Operational State` Das Feld muss angezeigt werden `running` Bundesland. Wenn der angezeigt wird `initializing` Zustand: Einiger Zwischenvorgang wie z. B. die Erstellung des Root-Volumes ist fehlgeschlagen. Außerdem müssen Sie die SVM löschen und erneut erstellen.



.Beispiele
Mit dem folgenden Befehl wird eine SVM für den Datenzugriff im IPspace ipspace A erstellt:

[listing]
----
cluster1::> vserver create -vserver vs1.example.com -rootvolume root_vs1 -aggregate aggr1
-rootvolume-security-style ntfs -language C.UTF-8 -ipspace ipspaceA

[Job 2059] Job succeeded:
Vserver creation completed
----
Der folgende Befehl zeigt, dass eine SVM mit einem Root-Volume von 1 GB erstellt wurde und dass sie automatisch gestartet wurde und sich in befindet `running` Bundesland. Das Root-Volume verfügt über eine standardmäßige Exportrichtlinie, die keine Regeln enthält, sodass das Root-Volume bei der Erstellung nicht exportiert wird.

[listing]
----
cluster1::> vserver show -vserver vs1.example.com
                                    Vserver: vs1.example.com
                               Vserver Type: data
                            Vserver Subtype: default
                               Vserver UUID: b8375669-19b0-11e5-b9d1-00a0983d9736
                                Root Volume: root_vs1
                                  Aggregate: aggr1
                                 NIS Domain: -
                 Root Volume Security Style: ntfs
                                LDAP Client: -
               Default Volume Language Code: C.UTF-8
                            Snapshot Policy: default
                                    Comment:
                               Quota Policy: default
                List of Aggregates Assigned: -
 Limit on Maximum Number of Volumes allowed: unlimited
                        Vserver Admin State: running
                  Vserver Operational State: running
   Vserver Operational State Stopped Reason: -
                          Allowed Protocols: nfs, cifs, fcp, iscsi, ndmp
                       Disallowed Protocols: -
                           QoS Policy Group: -
                                Config Lock: false
                               IPspace Name: ipspaceA
----