---
permalink: smb-config/verify-client-access-task.html 
sidebar: sidebar 
keywords: verify, configure, smb, correct, access, writing, write, data, share, server, name, netbios, alias, verify smb client access 
summary: Sie sollten überprüfen, ob SMB korrekt konfiguriert ist, indem Sie auf die Freigabe zugreifen und Daten darauf schreiben. Der Zugriff sollte sowohl mit dem SMB-Servernamen als auch mit allen NetBIOS-Aliasen getestet werden. 
---
= Überprüfung des ONTAP SMB-Clientzugriffs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten überprüfen, ob SMB korrekt konfiguriert ist, indem Sie auf die Freigabe zugreifen und Daten darauf schreiben. Der Zugriff sollte sowohl mit dem SMB-Servernamen als auch mit allen NetBIOS-Aliasen getestet werden.

.Schritte
. Melden Sie sich an einem Windows Client an.
. Testzugriff mit dem SMB-Servernamen:
+
.. Im Windows Explorer ein Laufwerk im folgenden Format mit der Freigabe verbinden: `\⁠\\SMB_Server_Name\Share_Name`
+
Falls die Zuordnung fehlschlägt, ist es möglich, dass die DNS-Zuordnung noch nicht im gesamten Netzwerk wirksam geworden ist. Der Zugriff sollte zu einem späteren Zeitpunkt mit dem SMB-Servernamen getestet werden.

+
Wenn der SMB-Server vs1.example.com heißt und die Freigabe SHARE1, ist Folgendes einzugeben: `\⁠\vs0.example.com\SHARE1`

.. Auf dem neu erstellten Laufwerk eine Testdatei erstellen und anschließend wieder löschen.


+
Sie haben den Schreibzugriff auf die Freigabe mithilfe des SMB-Servernamens überprüft.

. Schritt 2 ist für alle NetBIOS Aliase zu wiederholen.

