---
permalink: smb-config/worksheet-reference.html 
sidebar: sidebar 
keywords: smb, configuration, worksheet, enable, collect, require, information, access, client, worksheet, gather, cifs, worksheet for gathering SMB configuration information 
summary: Über das SMB-Konfigurationsarbeitsblatt können Sie die erforderlichen Informationen für die Einrichtung des SMB-Zugriffs für Clients sammeln. 
---
= Arbeitsblatt zum Sammeln von SMB-Konfigurationsinformationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Über das SMB-Konfigurationsarbeitsblatt können Sie die erforderlichen Informationen für die Einrichtung des SMB-Zugriffs für Clients sammeln.

Je nach Ihrer Entscheidung über den Speicherort sollten Sie einen oder beide Abschnitte des Arbeitsblatts ausfüllen:

* Wenn Sie SMB-Zugriff auf eine SVM konfigurieren, sollten Sie beide Abschnitte abschließen.
+
xref:configure-access-svm-task.adoc[Konfigurieren des SMB-Zugriffs auf eine SVM]

+
xref:configure-client-access-shared-storage-concept.adoc[Konfigurieren des SMB-Client-Zugriffs auf gemeinsam genutzten Storage]

* Wenn Sie einer SMB-fähigen SVM Storage-Kapazität hinzufügen, sollten Sie nur den zweiten Abschnitt ausfüllen.
+
xref:configure-client-access-shared-storage-concept.adoc[Konfigurieren des SMB-Client-Zugriffs auf gemeinsam genutzten Storage]



Die Befehlsman-Pages enthalten Details zu den Parametern.



== Konfigurieren des SMB-Zugriffs auf eine SVM

*Parameter zum Erstellen einer SVM*

Sie geben diese Werte mit an `vserver create` Befehl, wenn Sie eine neue SVM erstellen möchten.

|===
| Feld | Beschreibung | Ihr Wert 


 a| 
`-vserver`
 a| 
Einen Namen, den Sie für die neue SVM angeben, der entweder ein vollständig qualifizierter Domain-Name (FQDN) ist, oder der einer anderen Konvention folgt, die eindeutige SVM-Namen in einem Cluster durchsetzt.
 a| 



 a| 
`-aggregate`
 a| 
Der Name eines Aggregats im Cluster mit ausreichend Speicherplatz für neue SMB-Storage-Kapazität.
 a| 



 a| 
`-rootvolume`
 a| 
Ein eindeutiger Name für das SVM-Root-Volume.
 a| 



 a| 
`-rootvolume-security-style`
 a| 
Verwenden Sie den NTFS-Sicherheitsstil für die SVM.
 a| 
`ntfs`



 a| 
`-language`
 a| 
Verwenden Sie die Standardeinstellung für die Sprache in diesem Workflow.
 a| 
`C.UTF-8`



 a| 
`ipspace`
 a| 
Optional: IPspaces sind unterschiedliche IP-Adressbereiche, in denen SVMs sich befinden.
 a| 

|===
*Parameter zur Erstellung eines LIF*

Sie geben diese Werte mit an `network interface create` Befehl, wenn Sie LIFs erstellen.

|===
| Feld | Beschreibung | Ihr Wert 


 a| 
`-lif`
 a| 
Einen Namen, den Sie für das neue LIF angeben.
 a| 



 a| 
`-role`
 a| 
Verwenden Sie die LIF-Rolle der Daten in diesem Workflow.
 a| 
`data`



 a| 
`-data-protocol`
 a| 
Verwenden Sie in diesem Workflow nur das SMB-Protokoll.
 a| 
`cifs`



 a| 
`-home-node`
 a| 
Der Node, zu dem das LIF zurückgibt, wenn das `network interface revert` Befehl wird auf dem LIF ausgeführt.
 a| 



 a| 
`-home-port`
 a| 
Der Port oder die Schnittstellengruppe, zu dem das LIF zurückgibt, wenn das `network interface revert` Befehl wird auf dem LIF ausgeführt.
 a| 



 a| 
`-address`
 a| 
Die IPv4- oder IPv6-Adresse auf dem Cluster, die für den Datenzugriff durch die neue LIF verwendet wird.
 a| 



 a| 
`-netmask`
 a| 
Netzwerkmaske und Gateway für LIF.
 a| 



 a| 
`-subnet`
 a| 
Ein Pool mit IP-Adressen. Verwendet statt `-address` Und `-netmask` So weisen Sie Adressen und Netmasken automatisch zu.
 a| 



 a| 
`-firewall-policy`
 a| 
Verwenden Sie in diesem Workflow die standardmäßige Richtlinie für die Daten-Firewall.
 a| 
`data`



 a| 
`-auto-revert`
 a| 
Optional: Gibt an, ob eine Daten-LIF automatisch auf ihren Home-Node beim Start oder unter anderen Umständen zurückgesetzt wird. Die Standardeinstellung ist `false`.
 a| 

|===
*Parameter für DNS Host Name Auflösung*

Sie geben diese Werte mit an `vserver services name-service dns create` Befehl, wenn Sie DNS konfigurieren.

|===
| Feld | Beschreibung | Ihr Wert 


 a| 
`-domains`
 a| 
Bis zu fünf DNS-Domain-Namen
 a| 



 a| 
`-name-servers`
 a| 
Bis zu drei IP-Adressen für jeden DNS-Namenserver.
 a| 

|===


== Einrichten eines SMB-Servers in einer Active Directory-Domäne

*Parameter für die Konfiguration des Zeitdienstes*

Sie geben diese Werte mit an `cluster time-service ntp server create` Befehl, wenn Sie Zeitdienste konfigurieren.

|===
| Feld | Beschreibung | Ihr Wert 


 a| 
`-server`
 a| 
Der Hostname oder die IP-Adresse des NTP-Servers für die Active Directory-Domäne.
 a| 

|===
*Parameter zum Erstellen eines SMB-Servers in einer Active Directory-Domäne*

Sie geben diese Werte mit an `vserver cifs create` Befehl, wenn Sie einen neuen SMB-Server erstellen und Domäneninformationen angeben.

|===
| Feld | Beschreibung | Ihr Wert 


 a| 
`-vserver`
 a| 
Der Name der SVM, auf der der SMB-Server erstellt werden soll.
 a| 



 a| 
`-cifs-server`
 a| 
Der Name des SMB-Servers (bis zu 15 Zeichen).
 a| 



 a| 
`-domain`
 a| 
Der vollständig qualifizierte Domänenname (FQDN) der Active Directory-Domäne, der mit dem SMB-Server verknüpft werden soll.
 a| 



 a| 
`-ou`
 a| 
Optional: Die Organisationseinheit innerhalb der Active Directory-Domäne, die mit dem SMB-Server verknüpft werden soll. Standardmäßig ist dieser Parameter auf CN=Computer eingestellt.
 a| 



 a| 
`-netbios-aliases`
 a| 
Optional: Eine Liste von NetBIOS-Aliasen, bei denen es sich um alternative Namen zum SMB-Servernamen handelt.
 a| 



 a| 
`-comment`
 a| 
Optional: Ein Textkommentar für den Server. Windows-Clients können diese SMB-Serverbeschreibung beim Durchsuchen von Servern im Netzwerk sehen.
 a| 

|===


== Einrichten eines SMB-Servers in einer Arbeitsgruppe

*Parameter zum Erstellen eines SMB-Servers in einer Arbeitsgruppe*

Sie geben diese Werte mit an `vserver cifs create` Befehl, wenn Sie einen neuen SMB-Server erstellen und unterstützte SMB-Versionen angeben.

|===
| Feld | Beschreibung | Ihr Wert 


 a| 
`-vserver`
 a| 
Der Name der SVM, auf der der SMB-Server erstellt werden soll.
 a| 



 a| 
`-cifs-server`
 a| 
Der Name des SMB-Servers (bis zu 15 Zeichen).
 a| 



 a| 
`-workgroup`
 a| 
Der Name der Arbeitsgruppe (bis zu 15 Zeichen).
 a| 



 a| 
`-comment`
 a| 
Optional: Ein Textkommentar für den Server. Windows-Clients können diese SMB-Serverbeschreibung beim Durchsuchen von Servern im Netzwerk sehen.
 a| 

|===
*Parameter zum Erstellen von lokalen Benutzern*

Diese Werte geben Sie an, wenn Sie lokale Benutzer mithilfe der erstellen `vserver cifs users-and-groups local-user create` Befehl. Sie sind für SMB-Server in Arbeitsgruppen und optional in AD-Domänen erforderlich.

|===
| Feld | Beschreibung | Ihr Wert 


 a| 
`-vserver`
 a| 
Der Name der SVM, auf der der lokale Benutzer erstellt werden soll.
 a| 



 a| 
`-user-name`
 a| 
Der Name des lokalen Benutzers (bis zu 20 Zeichen).
 a| 



 a| 
`-full-name`
 a| 
Optional: Der vollständige Name des Benutzers. Wenn der vollständige Name ein Leerzeichen enthält, setzen Sie den vollständigen Namen in doppelte Anführungszeichen.
 a| 



 a| 
`-description`
 a| 
Optional: Eine Beschreibung für den lokalen Benutzer. Wenn die Beschreibung ein Leerzeichen enthält, setzen Sie den Parameter in Anführungszeichen.
 a| 



 a| 
`-is-account-disabled`
 a| 
Optional: Gibt an, ob das Benutzerkonto aktiviert oder deaktiviert ist. Wenn dieser Parameter nicht angegeben wird, ist die Standardeinstellung, das Benutzerkonto zu aktivieren.
 a| 

|===
*Parameter zum Erstellen von lokalen Gruppen*

Diese Werte geben Sie an, wenn Sie lokale Gruppen mithilfe der erstellen `vserver cifs users-and-groups local-group create` Befehl. Sie sind optional für SMB Server in AD-Domänen und Arbeitsgruppen.

|===
| Feld | Beschreibung | Ihr Wert 


 a| 
`-vserver`
 a| 
Der Name der SVM, auf der die lokale Gruppe erstellt werden soll.
 a| 



 a| 
`-group-name`
 a| 
Der Name der lokalen Gruppe (bis zu 256 Zeichen).
 a| 



 a| 
`-description`
 a| 
Optional: Eine Beschreibung für die lokale Gruppe. Wenn die Beschreibung ein Leerzeichen enthält, setzen Sie den Parameter in Anführungszeichen.
 a| 

|===


== Hinzufügen von Storage-Kapazität zu einer SMB-fähigen SVM

*Parameter für die Erstellung eines Volumens*

Sie geben diese Werte mit an `volume create` Befehl, wenn Sie ein Volume anstelle eines qtree erstellen.

|===
| Feld | Beschreibung | Ihr Wert 


 a| 
`-vserver`
 a| 
Der Name einer neuen oder vorhandenen SVM, die das neue Volume hosten wird.
 a| 



 a| 
`-volume`
 a| 
Ein eindeutiger beschreibende Name, den Sie für das neue Volume angeben.
 a| 



 a| 
`-aggregate`
 a| 
Der Name eines Aggregats im Cluster mit ausreichend Platz für das neue SMB Volume.
 a| 



 a| 
`-size`
 a| 
Eine Ganzzahl, die Sie für die Größe des neuen Datenträgers festlegen.
 a| 



 a| 
`-security-style`
 a| 
Verwenden Sie den NTFS-Sicherheitsstil für diesen Workflow.
 a| 
`ntfs`



 a| 
`-junction-path`
 a| 
Ort unter root (/), wo das neue Volume gemountet werden soll.
 a| 

|===
*Parameter zur Erstellung eines qtree*

Sie geben diese Werte mit an `volume qtree create` Befehl, wenn Sie einen qtree anstelle eines Volumes erstellen.

|===
| Feld | Beschreibung | Ihr Wert 


 a| 
`-vserver`
 a| 
Der Name der SVM, auf der sich das Volume mit dem qtree befindet.
 a| 



 a| 
`-volume`
 a| 
Der Name des Volume, das den neuen qtree enthalten soll.
 a| 



 a| 
`-qtree`
 a| 
Einen eindeutigen beschreibenden Namen, den Sie für den neuen qtree bereitstellen, mindestens 64 Zeichen.
 a| 



 a| 
`-qtree-path`
 a| 
Das Argument qtree-Pfad im Format `/vol/volume_name/qtree_name\>` Kann angegeben werden anstelle des Volume und des qtree als separate Argumente.
 a| 

|===
*Parameter zum Erstellen von SMB-Shares*

Sie geben diese Werte mit an `vserver cifs share create` Befehl.

|===
| Feld | Beschreibung | Ihr Wert 


 a| 
`-vserver`
 a| 
Der Name der SVM, auf der die SMB-Freigabe erstellt werden soll.
 a| 



 a| 
`-share-name`
 a| 
Der Name der zu erstellenden SMB-Freigabe (bis zu 256 Zeichen).
 a| 



 a| 
`-path`
 a| 
Der Name des Pfads zur SMB-Freigabe (bis zu 256 Zeichen). Dieser Pfad muss in einem Volume vorhanden sein, bevor die Freigabe erstellt wird.
 a| 



 a| 
`-share-properties`
 a| 
Optional: Eine Liste der Freigabegenschaften. Die Standardeinstellungen sind `oplocks`, `browsable`, `changenotify`, und `show-previous-versions`.
 a| 



 a| 
`-comment`
 a| 
Optional: Ein Textkommentar für den Server (bis zu 256 Zeichen). Windows-Clients können diese SMB-Share-Beschreibung beim Durchsuchen im Netzwerk sehen.
 a| 

|===
*Parameter zum Erstellen von SMB-Share-Zugriffssteuerungslisten (ACLs)*

Sie geben diese Werte mit an `vserver cifs share access-control create` Befehl.

|===
| Feld | Beschreibung | Ihr Wert 


 a| 
`-vserver`
 a| 
Der Name der SVM, auf der die SMB-ACL erstellt werden soll.
 a| 



 a| 
`-share`
 a| 
Der Name der SMB-Freigabe, auf der erstellt werden soll.
 a| 



 a| 
`-user-group-type`
 a| 
Der Typ des Benutzers oder der Gruppe, der zur ACL der Freigabe hinzugefügt werden soll. Der Standardtyp ist `windows`
 a| 
`windows`



 a| 
`-user-or-group`
 a| 
Der Benutzer oder die Gruppe, der zur ACL der Freigabe hinzugefügt werden soll. Wenn Sie den Benutzernamen angeben, müssen Sie die Domäne des Benutzers im Format „`domain\username`“ angeben.
 a| 



 a| 
`-permission`
 a| 
Gibt die Berechtigungen für den Benutzer oder die Gruppe an.
 a| 
`[ No_access | Read | Change | Full_Control ]`

|===