---
permalink: disks-aggregates/add-capacity-local-tier-overview-task.html 
sidebar: sidebar 
keywords: local tier, aggregate, add, create 
summary: Mithilfe verschiedener Methoden folgen Sie einem bestimmten Workflow, um die Kapazität hinzuzufügen 
---
= Hinzufügen von Kapazität (Festplatten) zu einer lokalen Tier (Aggregat)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mithilfe verschiedener Methoden folgen Sie einem bestimmten Workflow, um die Kapazität hinzuzufügen.

* link:aggregate-expansion-workflow-concept.html["Workflow zur Erweiterung der Kapazität einer lokalen Tier (Aggregat)"]
* link:methods-create-space-aggregate-concept.html["Methoden zur Erstellung von Speicherplatz in einer lokalen Tier (Aggregat)"]


Festplatten können einer lokalen Ebene hinzugefügt und zu einem Node oder Shelf hinzugefügt werden.

Bei Bedarf können Sie falsch ausgerichtete Ersatzpartitionen korrigieren.

* link:add-disks-local-tier-aggr-task.html["Hinzufügen von Festplatten zu einer lokalen Tier (Aggregat)"]
* link:add-disks-node-task.html["Fügen Sie Laufwerke zu einem Node oder Shelf hinzu"]
* link:correct-misaligned-spare-partitions-task.html["Falsch ausgerichtete Ersatzpartitionen korrigieren"]

