---
permalink: disks-aggregates/assign-aggregates-svms-task.html 
sidebar: sidebar 
keywords: assign, aggregate, local tier, svm, storage vm, vserver 
summary: 'Wenn Sie einer Storage Virtual Machine (Storage VM oder SVM, früher bekannt als Vserver) ein oder mehrere lokale Tiers zuweisen, können Sie nur diese lokalen Tiers verwenden, um Volumes für diese SVM aufzunehmen. Ein' 
---
= ONTAP lokale Tiers Storage-VMs (SVMs) zuweisen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie einer Storage Virtual Machine (Storage VM oder SVM, früher bekannt als Vserver) eine oder mehrere lokale Ebenen zuweisen, können nur diese lokalen Ebenen Volumes für diese Storage VM (SVM) enthalten.


NOTE: Vor ONTAP 9.7 verwendet System Manager den Begriff _aggregate_, um eine _lokale Ebene_ zu beschreiben. Unabhängig von der ONTAP Version verwendet die ONTAP CLI den Begriff _aggregate_. Weitere Informationen zu lokalen Ebenen finden sich unter link:../disks-aggregates/index.html["Festplatten und lokale Ebenen"].

.Bevor Sie beginnen
Die Storage-VM und die lokalen Ebenen, die Sie dieser Storage-VM zuweisen möchten, müssen bereits existieren.

.Über diese Aufgabe
Durch die Zuweisung lokaler Speicherebenen zu Ihren Storage-VMs bleiben die Storage-VMs voneinander isoliert, was insbesondere in einer Mandantenfähigkeit Umgebung wichtig ist.

.Schritte
. Die Liste der lokalen Ebenen, die dem SVM bereits zugewiesen sind, kann überprüft werden:
+
`vserver show -fields aggr-list`

+
Die dem SVM aktuell zugewiesenen lokalen Ebenen werden angezeigt. Falls keine lokalen Ebenen zugewiesen sind,  `-`wird angezeigt.

. Je nach Bedarf zugewiesene lokale Ebenen hinzufügen oder entfernen:
+
|===


| Wenn Sie möchten... | Verwenden Sie diesen Befehl... 


 a| 
Zusätzliche lokale Ebenen zuweisen
 a| 
`vserver add-aggregates`



 a| 
Lokale Ebenen aufheben
 a| 
`vserver remove-aggregates`

|===
+
Die aufgelisteten lokalen Ebenen werden der SVM zugewiesen oder von ihr entfernt. Wenn die SVM bereits Volumes enthält, die ein Aggregat verwenden, das der SVM nicht zugewiesen ist, wird eine Warnmeldung angezeigt, aber der Befehl wird erfolgreich abgeschlossen. Alle lokalen Ebenen, die der SVM bereits zugewiesen waren und im Befehl nicht genannt wurden, bleiben unberührt.



.Beispiel
Im folgenden Beispiel sind die lokalen Ebenen aggr1 und aggr2 der SVM svm1 zugewiesen:

`vserver add-aggregates -vserver svm1 -aggregates aggr1,aggr2`
