---
permalink: disks-aggregates/commands-manage-ssd-storage-pools-reference.html 
sidebar: sidebar 
keywords: commands, manage, ssd, storage, pools 
summary: 'ONTAP stellt den Befehl `storage pool` zur Verwaltung von SSD-Speicherpools zur Verfügung.' 
---
= ONTAP Befehle zur Verwaltung von SSD-Speicherpools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP stellt den  `storage pool` Befehl zur Verwaltung von SSD-Speicherpools bereit.

|===


| Wenn Sie möchten... | Verwenden Sie diesen Befehl... 


 a| 
Anzeigen, wie viel Speicherplatz ein Speicherpool welcher lokalen Ebene bereitstellt
 a| 
`storage pool show-aggregate`



 a| 
Anzeigen, wie viel Cache zur Gesamt-Cache-Kapazität für beide RAID-Typen hinzugefügt würde (Datengröße der Zuordnungseinheit)
 a| 
`storage pool show -instance`



 a| 
Die Datenträger in einem Speicherpool anzeigen
 a| 
`storage pool show-disks`



 a| 
Nicht zugewiesene Zuordnungseinheiten für einen Speicherpool anzeigen
 a| 
`storage pool show-available-capacity`



 a| 
Die Eigentumsrechte an einer oder mehreren Zuordnungseinheiten eines Storage Pools von einem HA-Partner auf den anderen übertragen
 a| 
`storage pool reassign`

|===
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/storage-pool-reassign.html["Speicherpool neu zuweisen"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-pool-show.html["storage pool show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-pool-show-aggregate.html["storage pool show-aggregate"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-pool-show-available-capacity.html["storage pool show-available-capacity"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-pool-show-disks.html["storage pool show-disks"^]

