---
permalink: disks-aggregates/commands-aggregate-relocation-reference.html 
sidebar: sidebar 
keywords: commands, aggregate, relocation 
summary: Es gibt spezielle ONTAP-Befehle für den Umzug der lokalen Tier-Eigentumsrechte innerhalb eines HA-Paars. 
---
= Befehle für die lokale Tier-Verschiebung in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es gibt spezielle ONTAP-Befehle für den Umzug der lokalen Tier-Eigentumsrechte innerhalb eines HA-Paars.


NOTE: Vor ONTAP 9.7 verwendet System Manager den Begriff „_Aggregate_“, um eine „_Local Tier_“ zu beschreiben. Unabhängig von Ihrer ONTAP-Version verwendet die ONTAP CLI den Begriff _Aggregate_. Weitere Informationen zu lokalen Ebenen finden Sie unter link:../disks-aggregates/index.html["Festplatten und lokale Tiers"].

|===


| Ihr Ziel ist | Befehl 


 a| 
Starten Sie den Prozess für die Verlagerung der lokalen Ebene
 a| 
`storage aggregate relocation start`



 a| 
Überwachen Sie den Prozess für die Verlagerung der lokalen Ebene
 a| 
`storage aggregate relocation show`

|===
.Verwandte Informationen
* link:../concepts/manual-pages.html["ONTAP-Befehlsreferenz"]

