---
permalink: disks-aggregates/commands-display-storage-shelves-reference.html 
sidebar: sidebar 
keywords: commands, display, information, storage, shelves 
summary: Mit dem Befehl „Storage Shelf show“ werden Konfigurations- und Fehlerinformationen für Ihre Festplatten-Shelfs angezeigt. 
---
= ONTAP-Befehle zum Anzeigen von Informationen über Storage-Shelfs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie verwenden den `storage shelf show` Befehl, um Konfigurations- und Fehlerinformationen für Ihre Platten-Shelfs anzuzeigen.

|===
| Sie möchten Folgendes anzeigen: | Befehl 


 a| 
Allgemeine Informationen zur Shelf-Konfiguration und zum Hardware-Status
 a| 
`storage shelf show`



 a| 
Detaillierte Informationen zu einem bestimmten Shelf, einschließlich Stack-ID
 a| 
`storage shelf show -shelf`



 a| 
Ungelöst, kundenverwertbare, Shelf-Fehler
 a| 
`storage shelf show -errors`



 a| 
Einschubinformationen
 a| 
`storage shelf show -bay`



 a| 
Informationen zur Konnektivität
 a| 
`storage shelf show -connectivity`



 a| 
Informationen zur Kühlung, einschließlich Temperatursensoren und Kühllüfter
 a| 
`storage shelf show -cooling`



 a| 
Informationen zu I/O-Modulen
 a| 
`storage shelf show -module`



 a| 
Portinformationen
 a| 
`storage shelf show -port`



 a| 
Informationen zur Stromversorgung, einschließlich Netzteilen (Netzteile), Stromsensoren und Spannungssensoren
 a| 
`storage shelf show -power`

|===
.Verwandte Informationen
* https://docs.netapp.com/us-en/ontap-cli["ONTAP-Befehlsreferenz"^]

