---
permalink: disks-aggregates/commands-display-space-usage-reference.html 
sidebar: sidebar 
keywords: commands, display, space usage, information 
summary: Mit den Befehlen storage aggregate und volume lässt sich erkennen, wie der Speicherplatz in Ihren lokalen Ebenen und Volumes sowie deren Snapshots genutzt wird. 
---
= ONTAP Befehle zur Anzeige von Informationen zur Speicherplatznutzung
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie verwenden die  `storage aggregate`- und  `volume`-Befehle, um anzuzeigen, wie der Speicherplatz in Ihren lokalen Tiers und Volumes sowie deren Snapshots genutzt wird.


NOTE: Vor ONTAP 9.7 verwendet System Manager den Begriff _aggregate_, um eine _lokale Ebene_ zu beschreiben. Unabhängig von der ONTAP Version verwendet die ONTAP CLI den Begriff _aggregate_. Weitere Informationen zu lokalen Ebenen finden sich unter link:../disks-aggregates/index.html["Festplatten und lokale Ebenen"].

|===


| Informationen über ... werden angezeigt. | Verwenden Sie diesen Befehl... 


 a| 
Lokale Ebene, einschließlich Details zu belegten und verfügbaren Speicherplatz-Prozentsätzen, Größe der Snapshot-Reserve und weiteren Informationen zur Speicherplatznutzung
 a| 
`storage aggregate show`

`storage aggregate show-space -fields snap-size-total,used-including-snapshot-reserve`



 a| 
Wie Festplatten und RAID-Gruppen in einer lokalen Ebene verwendet werden und der RAID-Status
 a| 
`storage aggregate show-status`



 a| 
Die Menge an Speicherplatz, die freigegeben würde, wenn ein bestimmter Snapshot gelöscht wird
 a| 
`volume snapshot compute-reclaimable`



 a| 
Der von einem Volume belegte Speicherplatz
 a| 
`volume show -fields size,used,available,percent-used`

`volume show-space`



 a| 
Der von einem Volumen in der übergeordneten lokalen Ebene belegte Speicherplatz
 a| 
`volume show-footprint`

|===
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show.html["storage aggregate show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-space.html["storage aggregate show-space"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-status.html["storage aggregate show-status"^]

