---
permalink: disks-aggregates/commands-manage-disks-reference.html 
sidebar: sidebar 
keywords: commands, manage, disks 
summary: Sie können die Befehle Speicher Festplatte und Storage-Aggregat verwenden, um Ihre Festplatten zu verwalten. 
---
= Befehle zum Verwalten von Festplatten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `storage disk` Und `storage aggregate` Befehle zum Verwalten Ihrer Festplatten.

|===


| Ihr Ziel ist | Befehl 


 a| 
Zeigt eine Liste der Ersatzfestplatten, einschließlich partitionierter Festplatten, nach Eigentümer an
 a| 
`storage aggregate show-spare-disks`



 a| 
Zeigen Sie den Festplatten-RAID-Typ, die aktuelle Auslastung und die RAID-Gruppe nach Aggregat an
 a| 
`storage aggregate show-status`



 a| 
Anzeige des RAID-Typs, der aktuellen Auslastung, der Aggregat- und RAID-Gruppe, einschließlich Spares, Für physische Festplatten
 a| 
`storage disk show -raid`



 a| 
Zeigt eine Liste der ausgefallenen Festplatten an
 a| 
`storage disk show -broken`



 a| 
Zeigt den Namen des Pre-Cluster-Laufwerks (Nodescope) für eine Festplatte an
 a| 
`storage disk show -primary-paths` (Erweitert)



 a| 
Leuchten Sie die LED für eine bestimmte Festplatte oder ein bestimmtes Shelf aus
 a| 
`storage disk set-led`



 a| 
Zeigen Sie den Prüfsummentyp für eine bestimmte Festplatte an
 a| 
`storage disk show -fields checksum-compatibility`



 a| 
Zeigen Sie den Prüfsummentyp für alle Spare-Festplatten an
 a| 
`storage disk show -fields checksum-compatibility -container-type spare`



 a| 
Zeigt Informationen zur Festplattenkonnektivität und Platzierung an
 a| 
`storage disk show -fields disk,primary-port,secondary-name,secondary-port,shelf,bay`



 a| 
Zeigt die vor-Cluster-Festplattennamen für bestimmte Festplatten an
 a| 
`storage disk show -disk diskname -fields diskpathnames`



 a| 
Zeigt die Liste der Festplatten im Maintenance Center an
 a| 
`storage disk show -maintenance`



 a| 
Zeigt die SSD-Verschleiß an
 a| 
`storage disk show -ssd-wear`



 a| 
Heben Sie die Partitionierung eines freigegebenen Laufwerks auf
 a| 
`storage disk unpartition` (Auf Diagnoseebene verfügbar)



 a| 
Löschen aller nicht auf Daten gelöschten Festplatten
 a| 
`storage disk zerospares`



 a| 
Beenden Sie die fortlaufende Bereinigung auf einer oder mehreren angegebenen Festplatten
 a| 
`system node run -node nodename -command disk sanitize`



 a| 
Zeigt Informationen zur Speicherverschlüsselungsfestplatte an
 a| 
`storage encryption disk show`



 a| 
Abrufen der Authentifizierungsschlüssel von allen verknüpften Verschlüsselungsmanagementservern
 a| 
`security key-manager restore`

|===
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9-Befehle"^]
