---
permalink: disks-aggregates/configure-auto-assignment-disk-ownership-task.html 
sidebar: sidebar 
keywords: change, modify, automatic, assignment, disk ownership 
summary: Mit dem Befehl „Ändern der Speicherplattenoption“ können Sie eine nicht-Standardrichtlinie für die automatische Zuweisung des Festplattenbesitzes auswählen oder die automatische Zuweisung des Festplattenbesitzes deaktivieren. 
---
= Ändern Sie die Einstellungen für die automatische Zuweisung des Festplattenbesitzes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `storage disk option modify` Befehl zum Auswählen einer nicht standardmäßigen Richtlinie für die automatische Zuweisung des Festplattenbesitzes oder zum Deaktivieren der automatischen Zuweisung des Festplattenbesitzes.

Erfahren Sie mehr über link:disk-autoassignment-policy-concept.html["Automatische Zuweisung der Festplatteneigentümer"].

.Schritte
. Ändern der automatischen Festplattenzuordnung:
+
.. Wenn Sie eine nicht-Standardrichtlinie auswählen möchten, geben Sie Folgendes ein:
+
`storage disk option modify -autoassign-policy _autoassign_policy_ -node _node_name_`

+
*** Nutzung `stack` Als der `_autoassign_policy_` Zum Konfigurieren der automatischen Eigentümerschaft auf Stack- oder Loop-Ebene.
*** Nutzung `shelf` Als der `_autoassign_policy_` Um die automatische Nutzung auf Shelf-Ebene zu konfigurieren.
*** Nutzung `bay` Als der `_autoassign_policy_` So konfigurieren Sie die automatische Eigentümerschaft auf der Einschubebene.


.. Wenn Sie die automatische Zuweisung des Festplattenbesitzes deaktivieren möchten, geben Sie Folgendes ein:
+
`storage disk option modify -autoassign off -node _node_name_`



. Überprüfen Sie die Einstellungen für die automatische Zuordnung der Festplatten:
+
`storage disk option show`

+
[listing]
----
cluster1::> storage disk option show

Node           BKg. FW. Upd.  Auto Copy     Auto Assign    Auto
                                                           Assign Policy
-------------  -------------  ------------  -------------  --------
cluster1-1     on             on            on             default
cluster1-2     on             on            on             default
----

