---
permalink: disks-aggregates/configure-auto-assignment-disk-ownership-task.html 
sidebar: sidebar 
keywords: change, modify, automatic, assignment, disk ownership 
summary: Sie können den Befehl storage disk option modify verwenden, um eine andere Richtlinie als die Standardrichtlinie für die automatische Zuweisung des Festplattenbesitzes auszuwählen oder die automatische Zuweisung des Festplattenbesitzes zu deaktivieren. 
---
= Einstellungen für die automatische Zuweisung der ONTAP Festplattenzugehörigkeit ändern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den  `storage disk option modify`Befehl verwenden, um eine nicht standardmäßige Richtlinie für die automatische Zuweisung des Festplattenbesitzes auszuwählen oder die automatische Zuweisung des Festplattenbesitzes zu deaktivieren.

Informationen dazu link:disk-autoassignment-policy-concept.html["automatische Zuweisung des Festplattenbesitzes"].

.Über diese Aufgabe
Wenn ein HA-Paar ausschließlich aus DS460C Shelves besteht, ist die standardmäßige automatische Zuweisungsrichtlinie „half-drawer“. Ein Wechsel zu einer nicht standardmäßigen Richtlinie (bay, shelf, stack) ist nicht möglich.

.Schritte
. Automatische Datenträgerzuordnung ändern:
+
.. Wenn Sie eine vom Standard abweichende Richtlinie auswählen möchten, geben Sie Folgendes ein:
+
`storage disk option modify -autoassign-policy _autoassign_policy_ -node _node_name_`

+
*** Verwenden Sie  `stack` als  `_autoassign_policy_` zur Konfiguration der automatischen Besitzverwaltung auf Stack- oder Schleifenebene.
*** Verwenden Sie  `shelf` als  `_autoassign_policy_` zur Konfiguration der automatischen Eigentümerschaft auf Shelf-Ebene.
*** Verwenden Sie  `bay` als  `_autoassign_policy_` zur Konfiguration der automatischen Eigentümerschaft auf Einschubebene.


.. Wenn die automatische Zuweisung des Datenträgerbesitzes deaktiviert werden soll, ist folgender Befehl einzugeben:
+
`storage disk option modify -autoassign off -node _node_name_`



. Die Einstellungen für die automatische Datenträgerzuordnung überprüfen:
+
`storage disk option show`

+
[listing]
----
cluster1::> storage disk option show

Node           BKg. FW. Upd.  Auto Copy     Auto Assign    Auto
                                                           Assign Policy
-------------  -------------  ------------  -------------  --------
cluster1-1     on             on            on             default
cluster1-2     on             on            on             default
----


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-option-modify.html["Storage Disk Option ändern"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-option-show.html["storage disk option show"^]

