---
permalink: disks-aggregates/convert-raid-tec-dp-task.html 
sidebar: sidebar 
keywords: convert, raid-tec, raid-dp, raid policy 
summary: 'Wenn Sie die Größe Ihrer lokalen Ebene (Aggregat) verringern und keine dreifache Parität mehr benötigen, können Sie Ihre RAID-Richtlinie von RAID-TEC in RAID-DP konvertieren und die Anzahl der für RAID-Parität erforderlichen Festplatten reduzieren.' 
---
= Konvertierung von RAID-TEC zu RAID-DP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die Größe Ihrer lokalen Ebene (Aggregat) verringern und keine dreifache Parität mehr benötigen, können Sie Ihre RAID-Richtlinie von RAID-TEC in RAID-DP konvertieren und die Anzahl der für RAID-Parität erforderlichen Festplatten reduzieren.

.Was Sie benötigen
Die maximale RAID-Gruppengröße für RAID-TEC ist größer als die maximale RAID-Gruppen-Größe für RAID-DP. Wenn die größte RAID-TEC-Gruppengröße nicht innerhalb der RAID-DP Grenzen liegt, können Sie nicht zu RAID-DP konvertieren.

.Schritte
. Vergewissern Sie sich, dass das Aggregat online ist und mindestens sechs Festplatten hat:
+
`storage aggregate show-status -aggregate _aggregate_name_`

. Konvertieren Sie das Aggregat von RAID-TEC zu RAID-DP:
+
`storage aggregate modify -aggregate _aggregate_name_ -raidtype raid_dp`

. Überprüfen Sie, ob die Aggregat-RAID-Richtlinie RAID-DP ist:
+
`storage aggregate show _aggregate_name_`


