---
permalink: disks-aggregates/convert-raid-dp-tec-task.html 
sidebar: sidebar 
keywords: convert, raid-dp, raid-tec, raid policy 
summary: Wenn Sie zusätzlichen Schutz durch Triple-Parity wünschen, können Sie von RAID-DP zu RAID-TEC konvertieren. RAID-TEC wird empfohlen, wenn die Größe der in Ihrem lokalen Tier verwendeten Festplatten größer als 4 TiB ist. 
---
= Konvertieren Sie von ONTAP RAID-DP zu RAID-TEC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie zusätzlichen Schutz durch Triple-Parity wünschen, können Sie von RAID-DP zu RAID-TEC konvertieren. RAID-TEC wird empfohlen, wenn die Größe der in Ihrem lokalen Tier verwendeten Festplatten größer als 4 TiB ist.


NOTE: Vor ONTAP 9.7 verwendet System Manager den Begriff „_Aggregate_“, um eine „_Local Tier_“ zu beschreiben. Unabhängig von Ihrer ONTAP-Version verwendet die ONTAP CLI den Begriff _Aggregate_. Weitere Informationen zu lokalen Ebenen finden Sie unter link:../disks-aggregates/index.html["Festplatten und lokale Tiers"].

.Bevor Sie beginnen
Der zu konvertierende lokale Tier muss mindestens sieben Festplatten haben.

.Über diese Aufgabe
* Die lokalen Festplatten-Tiers können von RAID-DP zu RAID-TEC konvertiert werden. Dies umfasst Festplatten-Tiers in lokalen Flash Pool Tiers.


.Vorgehensweise für Flashpools/Hybridaggregate, bei denen -disktype verwendet werden muss, um den jeweiligen Festplattentyp zu ändern
[-T, -disktype {ATA | BSAS | FCAL | FSAS | LUN | MSATA | SAS | SSD | VMDISK | SSD-NVM | SSD-CAP | SSD-ZNS | VMLUN | VMLUN-SSD}] - Datenträgertyp

Dieser Parameter legt den Festplattentyp der zu ändernden RAID-Gruppen fest. Im Fall von Flash Pool gibt er entweder die HDD-Ebene oder die SSD-Ebene an. Wenn die HDD-Ebene aus mehr als einem Festplattentyp besteht, führt die Angabe eines der verwendeten Festplattentypen dazu, dass diese Ebene geändert wird. Wenn der aktuelle Aggregat-RAID-Typ mixed_raid_type ist, ist dieser Parameter obligatorisch.

.Schritte
. Überprüfen Sie, ob die lokale Tier online ist und mindestens sechs Festplatten hat:
+
`storage aggregate show-status -aggregate _aggregate_name_`

. Konvertieren Sie den lokalen Tier von RAID-DP zu RAID-TEC:
+
`storage aggregate modify -aggregate _aggregate_name_ -raidtype raid_tec`

. Vergewissern Sie sich, dass die RAID-Richtlinie der lokalen Ebene RAID-TEC lautet:
+
`storage aggregate show _aggregate_name_`



.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-modify.html["Speicheraggregat ändern"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-status.html["Speicheraggregat-Status anzeigen"^]

