---
permalink: disks-aggregates/correct-misaligned-spare-partitions-task.html 
sidebar: sidebar 
keywords: correct, misaligned, partition, disk 
summary: Beim Hinzufügen partitionierter Festplatten zu einer lokalen Ebene muss für jeden Node eine Festplatte mit sowohl der Root- als auch der Datenpartition als Ersatzfestplatte verfügbar sein. Wenn dies nicht der Fall ist und ein Node eine Störung aufweist, kann ONTAP den Core nicht auf die Ersatzdatenpartition schreiben. 
---
= Falsch ausgerichtete ONTAP Ersatzpartitionen korrigieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Beim Hinzufügen partitionierter Festplatten zu einer lokalen Ebene muss für jeden Node eine Festplatte mit sowohl der Root- als auch der Datenpartition als Ersatzfestplatte verfügbar sein. Wenn dies nicht der Fall ist und ein Node eine Störung aufweist, kann ONTAP den Core nicht auf die Ersatzdatenpartition schreiben.


NOTE: Vor ONTAP 9.7 verwendet System Manager den Begriff _aggregate_, um eine _lokale Ebene_ zu beschreiben. Unabhängig von der ONTAP Version verwendet die ONTAP CLI den Begriff _aggregate_. Weitere Informationen zu lokalen Ebenen finden sich unter link:../disks-aggregates/index.html["Festplatten und lokale Ebenen"].

.Bevor Sie beginnen
Sowohl eine Ersatzdatenpartition als auch eine Ersatzstammpartition müssen sich auf demselben Festplattentyp befinden, der demselben Node gehört.

.Schritte
. Mit der CLI werden die Ersatzpartitionen für den Node angezeigt:
+
`storage aggregate show-spare-disks -original-owner _node_name_`

+
Notieren Sie, welche Festplatte eine Ersatzdatenpartition (spare_data) und welche Festplatte eine Ersatzrootpartition (spare_root) hat. Die Ersatzpartition zeigt einen Wert ungleich null in der  `Local Data Usable`- oder  `Local Root Usable`-Spalte an.

. Die Festplatte mit der Ersatzdatenpartition durch die Festplatte mit der Ersatz-Root-Partition ersetzen:
+
`storage disk replace -disk _spare_data_ -replacement _spare_root_ -action start`

+
Sie können die Daten in beide Richtungen kopieren; das Kopieren der Stammpartition benötigt jedoch weniger Zeit.

. Den Fortschritt des Festplattenaustauschs überwachen:
+
`storage aggregate show-status -aggregate _aggr_name_`

. Nachdem der Austauschvorgang abgeschlossen ist, werden die Ersatzfestplatten erneut angezeigt, um zu bestätigen, dass eine vollständige Ersatzfestplatte vorhanden ist:
+
`storage aggregate show-spare-disks -original-owner _node_name_`

+
Eine Ersatzfestplatte mit nutzbarem Speicherplatz sollte sowohl unter „`Local Data Usable`“ als auch unter  `Local Root Usable` angezeigt werden.



.Beispiel
Sie zeigen Ihre Ersatzpartitionen für Node c1-01 an und sehen, dass Ihre Ersatzpartitionen nicht ausgerichtet sind:

[listing]
----
c1::> storage aggregate show-spare-disks -original-owner c1-01

Original Owner: c1-01
 Pool0
  Shared HDD Spares
                              Local    Local
                               Data     Root  Physical
 Disk    Type   RPM Checksum Usable   Usable      Size
 ------- ----- ---- -------- ------- ------- --------
 1.0.1   BSAS  7200 block    753.8GB     0B   828.0GB
 1.0.10  BSAS  7200 block         0B 73.89GB  828.0GB
----
Der Festplattenaustausch wird gestartet:

[listing]
----
c1::> storage disk replace -disk 1.0.1 -replacement 1.0.10 -action start
----
Während Sie auf den Abschluss des Austauschvorgangs warten, wird der Fortschritt des Vorgangs angezeigt:

[listing]
----
c1::> storage aggregate show-status -aggregate aggr0_1

Owner Node: c1-01
 Aggregate: aggr0_1 (online, raid_dp) (block checksums)
  Plex: /aggr0_1/plex0 (online, normal, active, pool0)
   RAID Group /aggr0_1/plex0/rg0 (normal, block checksums)
                                    Usable Physical
 Position Disk    Pool Type   RPM     Size     Size Status
 -------- ------- ---- ---- ----- -------- -------- ----------
 shared   1.0.1    0   BSAS  7200  73.89GB  828.0GB (replacing,copy in progress)
 shared   1.0.10   0   BSAS  7200  73.89GB  828.0GB (copy 63% completed)
 shared   1.0.0    0   BSAS  7200  73.89GB  828.0GB (normal)
 shared   1.0.11   0   BSAS  7200  73.89GB  828.0GB (normal)
 shared   1.0.6    0   BSAS  7200  73.89GB  828.0GB (normal)
 shared   1.0.5    0   BSAS  7200  73.89GB  828.0GB (normal)
----
Nach Abschluss des Austauschvorgangs sollte eine vollständige Ersatzfestplatte vorhanden sein:

[listing]
----
ie2220::> storage aggregate show-spare-disks -original-owner c1-01

Original Owner: c1-01
 Pool0
  Shared HDD Spares
                             Local    Local
                              Data     Root  Physical
 Disk   Type   RPM Checksum Usable   Usable      Size
 ------ ----- ---- -------- -------- ------- --------
 1.0.1  BSAS  7200 block    753.8GB  73.89GB  828.0GB
----
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+aggregate+show["storage aggregate show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-replace.html["Speicherfestplatte ersetzen"^]

