---
permalink: disks-aggregates/create-ssd-storage-pool-task.html 
sidebar: sidebar 
keywords: create, provision, ssd, storage, flash, pool, add, cache, local tier, aggregate 
summary: 'Sie können SSD-Storage-Pools (Solid State Drive) erstellen, um SSD-Cache für zwei bis vier lokale Flash Pool Tiers (Aggregate) bereitzustellen.' 
---
= Fügen Sie einem lokalen Tier (Aggregat) Cache hinzu, indem Sie einen SSD Storage-Pool erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Cache bereitstellen, indem Sie eine vorhandene lokale Ebene (Aggregat) in eine lokale Flash Pool Ebene (Aggregat) konvertieren, indem Sie Solid State-Laufwerke (SSDs) hinzufügen.

Sie können SSD-Storage-Pools (Solid State Drive) erstellen, um SSD-Cache für zwei bis vier lokale Flash Pool Tiers (Aggregate) bereitzustellen. Mit Flash Pool Aggregaten können Sie Flash als hochperformanten Cache für Ihre Arbeitsdaten implementieren und gleichzeitig kostengünstige Festplatten für seltener verwendete Daten verwenden.

.Über diese Aufgabe
* Beim Erstellen oder Hinzufügen von Datenträgern zu einem Speicherpool müssen Sie eine Festplattenliste angeben.
+
Speicherpools unterstützen keine `diskcount` Parameter.

* Die im Speicherpool verwendeten SSDs sollten die gleiche Größe haben.


[role="tabbed-block"]
====
.System Manager
--
.Verwenden von System Manager zum Hinzufügen eines SSD-Caches (ONTAP 9.12.1 und höher)
[%collapsible%open]
=====
Ab ONTAP 9.12.1 können Sie mit System Manager einen SSD-Cache hinzufügen.


NOTE: Storage-Pool-Optionen stehen auf AFF Systemen nicht zur Verfügung.

.Schritte
. Klicken Sie auf *Cluster > Disks* und dann auf *ein-/Ausblenden*.
. Wählen Sie *Typ* aus, und stellen Sie sicher, dass auf dem Cluster ErsatzSSD vorhanden ist.
. Klicken Sie auf *Storage > Tiers* und klicken Sie auf *Storage Pool hinzufügen*.
. Wählen Sie den Festplattentyp aus.
. Geben Sie eine Festplattengröße ein.
. Wählen Sie die Anzahl der Festplatten aus, die dem Speicherpool hinzugefügt werden sollen.
. Überprüfen Sie die geschätzte Cache-Größe.


=====
.Verwenden Sie System Manager zum Hinzufügen eines SSD-Caches (nur ONTAP 9.7)
[%collapsible%open]
=====

NOTE: Verwenden Sie das CLI-Verfahren, wenn Sie eine ONTAP-Version höher als ONTAP 9.7 oder früher als ONTAP 9.12.1 verwenden.

.Schritte
. Klicken Sie auf *(Zurück zur klassischen Version)*.
. Klicken Sie Auf *Storage > Aggregate & Disks > Aggregate*.
. Wählen Sie die lokale Ebene (Aggregat) aus und klicken Sie dann auf *Aktionen > Cache hinzufügen*.
. Wählen Sie die Cache-Quelle als „Storage Pools“ oder „Dedicated SSDs“ aus.
. Klicken Sie auf * (zum neuen Erlebnis wechseln)*.
. Klicken Sie auf *Storage > Tiers*, um die Größe des neuen Aggregats zu überprüfen.


=====
--
.CLI
--
*Verwenden Sie die CLI, um einen SSD-Speicherpool zu erstellen*

.Schritte
. Bestimmen Sie die Namen der verfügbaren Spare-SSDs:
+
`storage aggregate show-spare-disks -disk-type SSD`

+
Die in einem Storage-Pool verwendeten SSDs können einem Node eines HA-Paars zugewiesen werden.

. Erstellen Sie den Speicherpool:
+
`storage pool create -storage-pool _sp_name_ -disk-list _disk1_,_disk2_,...`

. *Optional:* Überprüfung des neu erstellten Speicherpools:
+
`storage pool show -storage-pool _sp_name_`



--
====
Nachdem die SSDs in den Storage-Pool gelegt wurden, werden sie nicht mehr als Spares auf dem Cluster angezeigt, obwohl der vom Speicherpool bereitgestellte Storage noch keinen Flash Pool Caches zugewiesen wurde. Sie können einer RAID-Gruppe keine SSDs als separate Laufwerke hinzufügen. Ihr Storage kann nur mithilfe der Zuweisungseinheiten des Storage-Pools bereitgestellt werden, zu denen sie gehören.
