---
permalink: disks-aggregates/delete-local-tier-task.html 
sidebar: sidebar 
keywords: delete, local tier, aggregate, remove 
summary: Sie können eine lokale Ebene löschen, wenn keine Volumes auf der lokalen Ebene vorhanden sind. 
---
= Löschen Sie eine lokale ONTAP-Tier
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine lokale Ebene löschen, wenn keine Volumes auf der lokalen Ebene vorhanden sind.


NOTE: Vor ONTAP 9.7 verwendet System Manager den Begriff „_Aggregate_“, um eine „_Local Tier_“ zu beschreiben. Unabhängig von Ihrer ONTAP-Version verwendet die ONTAP CLI den Begriff _Aggregate_. Weitere Informationen zu lokalen Ebenen finden Sie unter link:../disks-aggregates/index.html["Festplatten und lokale Tiers"].

Mit dem `storage aggregate delete` Befehl wird eine lokale Speicherebene gelöscht. Der Befehl schlägt fehl, wenn auf der lokalen Ebene Volumes vorhanden sind. Wenn der lokalen Tier ein Objektspeicher angehängt ist, löscht der Befehl zusätzlich zum Löschen des lokalen Objekts auch die Objekte im Objektspeicher. Es werden keine Änderungen an der Konfiguration des Objektspeichers als Teil dieses Befehls vorgenommen.

Im folgenden Beispiel wird eine lokale Ebene namens „`aggr1`“ gelöscht:

....
> storage aggregate delete -aggregate aggr1
....
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-delete.html["Speicheraggregat löschen"^]

