---
permalink: disks-aggregates/determine-space-usage-aggregate-concept.html 
sidebar: sidebar 
keywords: space, usage, aggregate, local tier, volume 
summary: 'Sie können sehen, wie viel Speicherplatz von allen Volumes in einer oder mehreren lokalen Ebenen (Aggregate) verwendet wird, damit Sie Maßnahmen ergreifen können, um mehr Speicherplatz freizugeben.' 
---
= Bestimmen der Speicherplatznutzung in einer lokalen Tier (Aggregat)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können sehen, wie viel Speicherplatz von allen Volumes in einer oder mehreren lokalen Ebenen (Aggregate) verwendet wird, damit Sie Maßnahmen ergreifen können, um mehr Speicherplatz freizugeben.

Mit dem können Sie die Speicherplatznutzung aller Volumes in einem oder mehreren Aggregaten anzeigen `aggregate show-space` Befehl. Dies hilft Ihnen zu sehen, welche Volumes den meisten Speicherplatz in ihren enthaltenen Aggregaten verbrauchen, sodass Sie Maßnahmen ergreifen können, um mehr Speicherplatz freizugeben.

Der verwendete Speicherplatz in einem Aggregat wird direkt von dem Platz beeinflusst, der in den in ihm enthaltenen FlexVol-Volumes genutzt wird. Maßnahmen, die zum Erhöhen des Speicherplatzes in einem Volume benötigt werden, beeinflussen auch den Speicherplatz im Aggregat.

Die folgenden Zeilen sind in enthalten `aggregate show-space` Befehlsausgabe:

* *Volumen-Footprints*
+
Die Summe aller Volume-Footprints innerhalb des Aggregats. Es schließt den gesamten Speicherplatz ein, der von allen Daten und Metadaten aller Volumes des zugehörigen Aggregats verwendet oder reserviert wird.

* *Aggregierte Metadaten*
+
Die vom Aggregat benötigten Gesamt-Filesystem-Metadaten, wie z. B. Zuordnung von Bitmaps und Inode-Dateien.

* *Snapshot Reserve*
+
Die Menge an Speicherplatz, der für aggregierte Snapshot Kopien reserviert ist, basierend auf der Volume-Größe. Sie wird als genutzter Speicherplatz betrachtet und steht nicht für das Volume oder Aggregat von Daten oder Metadaten zur Verfügung.

* *Snapshot Reserve Nicht Nutzbar*
+
Die Menge an Speicherplatz, die ursprünglich für die Snapshot Reserve des Aggregats zugewiesen war, ist nicht für Snapshot Kopien des Aggregats verfügbar, da sie von den Volumes verwendet wird, die mit dem Aggregat verbunden sind. Die Snapshot-Reserve ist nur für Aggregate mit einer nicht null beträgt.

* *Insgesamt Verwendet*
+
Die Summe des gesamten Speicherplatzes, der im Aggregat verwendet oder reserviert ist, durch Volumes, Metadaten oder Snapshot Kopien.

* *Gesamt Physisch Genutzt*
+
Der Speicherplatz, der aktuell für Daten verwendet wird (und nicht für zukünftige Verwendung reserviert), Umfasst den von Aggregat-Snapshot-Kopien verwendeten Speicherplatz.



Das folgende Beispiel zeigt die `aggregate show-space` Befehlsausgabe für ein Aggregat, dessen Snapshot-Reserve 5% ist. Wenn die Snapshot Reserve 0 war, wird die Zeile nicht angezeigt.

....
cluster1::> storage aggregate show-space

						Aggregate : wqa_gx106_aggr1

      Feature                                   Used      Used%
      --------------------------------    ----------     ------
      Volume Footprints                      101.0MB         0%
      Aggregate Metadata                       300KB         0%
      Snapshot Reserve                        5.98GB         5%

      Total Used                              6.07GB         5%
      Total Physical Used                    34.82KB         0%
....