---
permalink: disks-aggregates/determine-modify-caching-policy-flash-pool-task.html 
sidebar: sidebar 
keywords: modify, cache, policy, flash pool, aggregate, local tier 
summary: Sie können Volumes in Flash Pool lokalen Tiers Cache-Aufbewahrungsrichtlinien zuweisen, um festzulegen, wie lange die Volume-Daten im Flash Pool Cache verbleiben. In manchen Fällen hat die Änderung der Cache-Aufbewahrungsrichtlinie jedoch keinen Einfluss auf die Verweildauer der Volume-Daten im Cache. 
---
= Es sollte geprüft werden, ob die ONTAP Caching-Richtlinie der lokalen Flash Pool Tiers angepasst werden muss.
:allow-uri-read: 


[role="lead"]
Sie können Volumes in Flash Pool lokalen Tiers Cache-Aufbewahrungsrichtlinien zuweisen, um festzulegen, wie lange die Volume-Daten im Flash Pool Cache verbleiben. In manchen Fällen hat die Änderung der Cache-Aufbewahrungsrichtlinie jedoch keinen Einfluss darauf, wie lange die Daten des Volumes im Cache verbleiben.

.Über diese Aufgabe
Wenn Ihre Daten eine der folgenden Bedingungen erfüllen, könnte eine Änderung Ihrer Cache-Retention-Policy keine Auswirkungen haben:

* Ihre Arbeitslast ist sequenziell.
* Ihre Arbeitslast liest die im Solid State Drive (SSD) zwischengespeicherten zufälligen Blöcke nicht erneut.
* Die Cache-Größe des Volumes ist zu klein.


.Schritte
Die folgenden Schritte prüfen, ob die Daten die erforderlichen Bedingungen erfüllen. Die Aufgabe muss über die Befehlszeilenschnittstelle (CLI) im erweiterten Berechtigungsmodus ausgeführt werden.

. Die CLI kann verwendet werden, um das Workload-Volumen anzuzeigen:
+
`statistics start -object workload_volume`

. Das Auslastungsmuster des Volumens bestimmen:
+
`statistics show -object workload_volume -instance _volume-workload_ -counter sequential_reads`

. Die Trefferquote des Volumens bestimmen:
+
`statistics show -object wafl_hya_vvol -instance _volume_ -counter read_ops_replaced_percent|wc_write_blks_overwritten_percent`

. Bestimmen Sie die  `Cacheable Read` und  `Project Cache Alloc` des Volumens:
+
`system node run -node node_name wafl awa start _aggr_name_`

. AWA-Zusammenfassung anzeigen:
+
`system node run -node node_name wafl awa print _aggr_name_`

. Die Trefferquote des Volumes kann mit der  `Cacheable Read` verglichen werden.
+
Wenn die Trefferquote des Volumes größer als der `Cacheable Read` ist, liest Ihre Arbeitslast keine zufälligen, auf den SSDs zwischengespeicherten Blöcke erneut.

. Die aktuelle Cache-Größe des Volumes im Vergleich zur  `Project Cache Alloc`.
+
Wenn die aktuelle Cache-Größe des Volumes größer als die  `Project Cache Alloc` ist, ist die Größe Ihres Volume-Caches zu klein.



.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/statistics-show.html["Statistiken zeigen"^]
* link:https://docs.netapp.com/us-en/ontap-cli/statistics-start.html["Statistiken Start"^]

