---
permalink: disks-aggregates/determine-space-usage-aggregate-concept.html 
sidebar: sidebar 
keywords: space, usage, aggregate, local tier, volume 
summary: 'Sie können anzeigen, wie viel Speicherplatz von allen Volumes in einem oder mehreren lokalen Tiers (Aggregate) verwendet wird, sodass Sie Aktionen durchführen können, um mehr Speicherplatz freizugeben.' 
---
= Bestimmen der Speicherplatznutzung in einer lokalen Tier (Aggregat)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können anzeigen, wie viel Speicherplatz von allen Volumes in einem oder mehreren lokalen Tiers (Aggregate) verwendet wird, sodass Sie Aktionen durchführen können, um mehr Speicherplatz freizugeben.

WAFL reserviert einen Prozentsatz des gesamten Festplattenspeichers für Metadaten und Performance auf Aggregatebene. Der Platz, der zur Erhaltung der Volumes im Aggregat verwendet wird, stammt aus der WAFL Reserve und kann nicht geändert werden.

In Aggregaten, die kleiner als 30 TB sind, reserviert WAFL 10 % des gesamten Festplattenspeichers für Metadaten und Performance auf Aggregatebene.

Ab ONTAP 9.12.1 wird bei Aggregaten, die 30 TB oder größer sind, die Menge des reservierten Festplattenspeichers für Metadaten und Performance auf Aggregatebene reduziert. Dies führt zu 5 % mehr nutzbarem Speicherplatz in Aggregaten. Die Verfügbarkeit dieser Speicherersparnis ist abhängig von Ihrer Plattform und Version von ONTAP.

[cols="30,30,40"]
|===
| Speicherplatz, der von ONTAP in Aggregaten für 30 TB oder mehr reserviert wird | Gilt für Plattformen | In ONTAP-Versionen 


| 5 % erreicht | Alle AFF und FAS Plattformen | ONTAP 9.14.1 und höher 


| 5 % erreicht | AFF Plattformen und FAS500f Plattformen entwickelt | ONTAP 9.12.1 und höher 


| 10 % erreicht | Alle Plattformen | ONTAP 9.11.1 und höher 
|===
Mit dem `aggregate show-space` Befehl können Sie die Speicherplatznutzung nach allen Volumes in einem oder mehreren Aggregaten anzeigen. Dies hilft Ihnen zu sehen, welche Volumes den meisten Speicherplatz in ihren enthaltenen Aggregaten verbrauchen, sodass Sie Maßnahmen ergreifen können, um mehr Speicherplatz freizugeben.

Der verwendete Speicherplatz in einem Aggregat wird direkt von dem Platz beeinflusst, der in den in ihm enthaltenen FlexVol-Volumes genutzt wird. Maßnahmen, die zum Erhöhen des Speicherplatzes in einem Volume benötigt werden, beeinflussen auch den Speicherplatz im Aggregat.


NOTE: Ab ONTAP 9.15.1 sind zwei neue Metadatenzähler verfügbar. Zusammen mit Änderungen an mehreren vorhandenen Zählern erhalten Sie eine klarere Übersicht über die Menge der zugewiesenen Benutzerdaten. Weitere Informationen finden Sie unter link:../volumes/determine-space-usage-volume-aggregate-concept.html["Bestimmen Sie die Speicherplatznutzung in einem Volume oder Aggregat"] .

Die `aggregate show-space` Befehlsausgabe enthält die folgenden Zeilen:

* *Volumen-Footprints*
+
Die Summe aller Volume-Footprints innerhalb des Aggregats. Es schließt den gesamten Speicherplatz ein, der von allen Daten und Metadaten aller Volumes des zugehörigen Aggregats verwendet oder reserviert wird.

* *Aggregierte Metadaten*
+
Die vom Aggregat benötigten Gesamt-Filesystem-Metadaten, wie z. B. Zuordnung von Bitmaps und Inode-Dateien.

* *Snapshot Reserve*
+
Die Menge an Speicherplatz, die für Aggregat-Snapshots reserviert ist, basierend auf der Volume-Größe. Sie wird als genutzter Speicherplatz betrachtet und steht nicht für das Volume oder Aggregat von Daten oder Metadaten zur Verfügung.

* *Snapshot Reserve Nicht Nutzbar*
+
Die ursprünglich für die Aggregat-Snapshot-Reserve zugewiesene Speichermenge, die für Aggregat-Snapshots nicht verfügbar ist, da sie von Volumes verwendet wird, die dem Aggregat zugeordnet sind. Kann nur bei Aggregaten mit einer nicht-Null-Aggregat-Snapshot-Reserve auftreten.

* *Insgesamt Verwendet*
+
Die Summe des gesamten im Aggregat genutzten oder reservierten Speicherplatzes durch Volumes, Metadaten oder Snapshots.

* *Gesamt Physisch Genutzt*
+
Der Speicherplatz, der aktuell für Daten verwendet wird (und nicht für zukünftige Verwendung reserviert), Umfasst den von Snapshot-Aggregaten verwendeten Speicherplatz.



Das folgende Beispiel zeigt die `aggregate show-space` Befehlsausgabe für ein Aggregat, dessen Snapshot-Reserve 5 % beträgt. Wenn die Snapshot-Reserve 0 war, wird die Zeile nicht angezeigt.

....
cluster1::> storage aggregate show-space

						Aggregate : wqa_gx106_aggr1

      Feature                                   Used      Used%
      --------------------------------    ----------     ------
      Volume Footprints                      101.0MB         0%
      Aggregate Metadata                       300KB         0%
      Snapshot Reserve                        5.98GB         5%

      Total Used                              6.07GB         5%
      Total Physical Used                    34.82KB         0%
....
.Verwandte Informationen
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Space_Usage["Knowledge Base-Artikel: Raumnutzung"^]
* link:https://www.netapp.com/blog/free-up-storage-capacity-upgrade-ontap/["Setzen Sie beim Upgrade auf ONTAP 9.12.1 auf bis zu 5 % Storage-Kapazität frei"^]

