---
permalink: disks-aggregates/determine-impact-cache-size-adding-ssds-task.html 
sidebar: sidebar 
keywords: determine, impact, cache, size, ssds, storage pool 
summary: 'Wenn das Hinzufügen von SSDs zu einem Speicherpool dazu führt, dass das Cache-Limit Ihres Plattformmodells überschritten wird, weist ONTAP die neu hinzugefügte Kapazität keinem lokalen Flash Pool Tier (Aggregate) zu. Dies kann dazu führen, dass einige oder alle der neu hinzugefügten Kapazitäten nicht zur Verwendung zur Verfügung stehen.' 
---
= Bestimmen Sie die Auswirkung auf die Cache-Größe, wenn Sie SSDs zu einem SSD Storage-Pool hinzufügen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn beim Hinzufügen von SSDs zu einem Storage-Pool das Cache-Limit Ihres Plattformmodells überschritten wird, weist ONTAP die neu hinzugefügte Kapazität keinem lokalen Flash Pool Tier (Aggregate) zu. Dies kann dazu führen, dass einige oder alle der neu hinzugefügten Kapazitäten nicht zur Verwendung zur Verfügung stehen.

.Über diese Aufgabe
Wenn Sie einem SSD Storage-Pool SSDs hinzufügen, in dem bereits zugewiesene Zuweisungseinheiten den lokalen Flash Pool Tiers (Aggregate) sind, erhöhen Sie die Cache-Größe jeder dieser lokalen Tiers und den gesamten Cache im System. Wenn keine der Zuweisungseinheiten des Speicherpools zugewiesen wurden, hat das Hinzufügen von SSDs zu diesem Speicherpool keinen Einfluss auf die Größe des SSD-Caches, bis eine oder mehrere Zuweisungseinheiten einem Cache zugewiesen sind.

.Schritte
. Legen Sie die nutzbare Größe der SSDs fest, die Sie dem Storage-Pool hinzufügen:
+
`storage disk show _disk_name_ -fields usable-size`

. Legen Sie fest, wie viele Zuweisungseinheiten für den Speicherpool nicht zugewiesen bleiben:
+
`storage pool show-available-capacity _sp_name_`

+
Alle nicht zugewiesenen Zuweisungseinheiten im Speicherpool werden angezeigt.

. Berechnen Sie die Menge des Cache, der durch Anwendung der folgenden Formel hinzugefügt wird:
+
( 4 -- Anzahl nicht zugewiesener Zuweisungseinheiten) × 25% × nutzbare Größe × Anzahl SSDs


