---
permalink: disks-aggregates/disk-partition-ownership-overview-concept.html 
sidebar: sidebar 
keywords: disk, partition, ownership, overview 
summary: Sie können die Eigentumsrechte von Festplatten und Partitionen verwalten. 
---
= Eigentum von Festplatten und Partitionen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Sie können die Eigentumsrechte von Festplatten und Partitionen verwalten.

Sie können die folgenden Aufgaben ausführen:

* *link:display-partition-ownership-task.html["Anzeige der Disk- und Partitionseigentümer"]*
+
Sie können den Festplattenbesitzer anzeigen, um festzulegen, welcher Node den Speicher steuert. Sie können auch die Partitionseigentümer auf Systemen anzeigen, die freigegebene Festplatten verwenden.

* *link:manual-assign-ownership-partitioned-disks-task.html["Weisen Sie eigenhändisch partitionierte Festplatten zu"]*
+
Sie können die Eigentumsrechte der Container-Festplatte oder der Partitionen manuell oder durch die automatische Zuweisung einstellen - genau wie bei nicht partitionierten Laufwerken.

* *link:configure-auto-assignment-disk-ownership-task.html["Konfigurieren Sie die automatische Zuweisung der Festplatteneigentümer"]*
+
Sie können ONTAP so konfigurieren, dass die Festplatteneigentümer gemäß einem Stack, Shelf oder Schacht einer Festplatte automatisch zugewiesen werden.

* *link:remove-failed-disk-task.html["Entfernen einer fehlerhaften Festplatte"]*
+
Eine Festplatte, die komplett ausgefallen ist, wird von ONTAP nicht mehr als nutzbare Festplatte betrachtet, und Sie können die Festplatte sofort vom Shelf trennen.

* *link:remove-ownership-disk-task.html["Entfernen Sie den Besitz von einer Festplatte"]*
+
ONTAP schreibt die Festplattenbesitzer-Informationen auf die Festplatte. Bevor Sie eine Spare-Festplatte oder ihr Shelf von einem Node entfernen, sollten Sie die Besitzinformationen entfernen, damit sie ordnungsgemäß in einen anderen Node integriert werden können.


