---
permalink: disks-aggregates/disk-autoassignment-policy-concept.html 
sidebar: sidebar 
keywords: disk, auto-assign, spare, policy, automatic, assignment, disk ownership 
summary: Standardmäßig ist die automatische Zuweisung nicht eigener Festplatten aktiviert. Die automatischen Festplattenzuordnungen werden 10 Minuten nach der Systeminitialisierung und alle fünf Minuten während des normalen Systembetriebs ausgeführt. 
---
= Allgemeines zur automatischen Zuweisung der Festplatteneigentümer
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Standardmäßig ist die automatische Zuweisung nicht eigener Festplatten aktiviert. Die automatischen Festplattenzuordnungen werden 10 Minuten nach der Systeminitialisierung und alle fünf Minuten während des normalen Systembetriebs ausgeführt.

Wenn Sie einem System neue Festplatten hinzufügen – zum Beispiel beim Austausch ausgefallener Festplatten, beim Antworten auf eine Meldung mit niedrigen Ersatzteilen oder beim Hinzufügen von Kapazität – weist die standardmäßige Richtlinie zur automatischen Zuweisung einem Node die Eigentumsrechte an der Festplatte zu. Sie können die automatische Zuweisung deaktivieren oder eine andere Richtlinie für die automatische Zuweisung mit der auswählen `storage disk option modify` Befehl.

Die standardmäßige Richtlinie für eine automatische Zuweisung basiert auf plattformspezifischen Merkmalen. Sie verwendet jedoch eine der folgenden Methoden, um den Festplattenbesitzer zuzuweisen:

|===


| Zuweisungsmethode | Auswirkung auf Knotenzuweisungen | Plattformen 


 a| 
bucht
 a| 
Gerade nummerierte Schächte werden Node A und ungerade nummerierte Schächte Node B. zugewiesen
 a| 
Einstiegssysteme in einer HA-Konfiguration mit einem einzelnen gemeinsam genutzten Shelf



 a| 
Shelf
 a| 
Alle Festplatten im Shelf sind Node A zugewiesen
 a| 
Einstiegssysteme in einer HA-Konfiguration mit einem Stack aus zwei oder mehr Shelfs und MetroCluster Konfigurationen mit einem Stack pro Node, zwei oder mehr Shelfs.



 a| 
Geteiltes Shelf
 a| 
Die Festplatten auf der linken Seite des Shelf sind dem Node A und auf der rechten Seite dem Node B. zugewiesen Neue Systeme werden teilweise mit Festplatten ausgeliefert, die von der Shelf-Kante in Richtung Mitte aufgefüllt werden.
 a| 
AFF C190 Systeme und einige MetroCluster Konfigurationen.



 a| 
Stapel
 a| 
Alle Festplatten im Stack sind Node A zugewiesen
 a| 
Eigenständige Systeme der Einstiegsklasse und alle anderen Konfigurationen.

|===
Wenn die Standardzuordnungsmethode in Ihrer Umgebung nicht wünschenswert ist, können Sie über die die Methode für Schacht, Shelf oder Stack-Zuweisung angeben `-autoassign-policy` Parameter für das `storage disk option modify` Befehl. Beachten Sie folgende Regeln:

* Wenn Sie versuchen, den zu verwenden `bay autoassign-policy` Bei einer Plattform ohne Einstiegssegment schlägt es fehl.
* Es gibt keine entsprechende, nicht standardmäßige Richtlinie für die Angabe der Split-Shelf-Methode.


Sie können die Festplattenzuordnung auch manuell über verwalten `storage disk assign` Befehl.

* Wenn Sie die automatische Zuweisung deaktivieren, stehen neue Festplatten erst als Spares zur Verfügung, wenn sie einem Node mit dem zugewiesen sind `storage disk assign` Befehl.
* Wenn Festplatten automatisch zugewiesen werden sollen und Sie über mehrere Stacks oder Shelfs verfügen müssen, die unterschiedliche Eigentumsrechte verfügen müssen, muss jeweils eine Festplatte manuell jedem Stack oder Shelf zugewiesen werden. Damit die automatische Eigentumszuweisung auf jedem Stack oder Shelf funktioniert.
* Wenn die automatische Zuweisung aktiviert ist und Sie einem Knoten, der in der aktiven Richtlinie nicht angegeben ist, manuell ein einzelnes Laufwerk zuweisen, wird die automatische Zuweisung nicht mehr ausgeführt und es wird eine EMS-Meldung angezeigt.


Weitere Informationen zu link:manual-assign-ownership-partitioned-disks-task.html["Manuelles Zuweisen der Festplatteneigentümer"].

Mit dem können Sie die aktuellen Einstellungen für die automatische Zuweisung anzeigen `storage disk option show` Befehl.
