---
permalink: disks-aggregates/manage-local-tiers-overview-concept.html 
sidebar: sidebar 
keywords: local tier, aggregate, prepare, add, create, disks, RAID, delete, manage local tier, manage aggregate 
summary: 'Sie können mit System Manager oder der CLI lokale Tiers hinzufügen, deren Nutzung managen und Kapazität (Festplatten) hinzufügen.' 
---
= Erfahren Sie mehr über lokales Tier-Management von ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit System Manager oder der ONTAP-CLI können Sie lokale Tiers hinzufügen, deren Nutzung managen und diese um Kapazität (Festplatten) erweitern.


NOTE: Vor ONTAP 9.7 verwendet System Manager den Begriff „_Aggregate_“, um eine „_Local Tier_“ zu beschreiben. Unabhängig von Ihrer ONTAP-Version verwendet die ONTAP CLI den Begriff _Aggregate_. Weitere Informationen zu lokalen Ebenen finden Sie unter link:../disks-aggregates/index.html["Festplatten und lokale Tiers"].

Sie können die folgenden Aufgaben ausführen:

* link:add-local-tier-overview-task.html["Fügen Sie eine lokale Ebene hinzu (erstellen)"]
+
Um eine lokale Ebene hinzuzufügen, folgen Sie einem bestimmten Workflow. Sie bestimmen die Anzahl der Festplatten oder Festplattenpartitionen, die für die lokale Ebene benötigt werden, und legen fest, welche Methode zur Erstellung der lokalen Ebene verwendet werden soll. Sie können lokale Tiers automatisch hinzufügen, indem Sie ONTAP die Konfiguration zuweisen lassen. Alternativ können Sie die Konfiguration manuell angeben.

* link:manage-use-local-tiers-overview-task.html["Verwalten Sie die Verwendung lokaler Tiers"]
+
Für vorhandene lokale Tiers können Sie sie umbenennen, ihre Medienkosten festlegen oder Informationen zu Laufwerken und RAID-Gruppen ermitteln. Sie können die RAID-Konfiguration einer lokalen Ebene ändern und Storage VMs (SVMs) lokale Tiers zuweisen. Sie können die RAID-Konfiguration einer lokalen Ebene ändern und Storage VMs (SVMs) lokale Tiers zuweisen. Sie können festlegen, welche Volumes auf einer lokalen Ebene residieren und wie viel Speicherplatz sie auf einer lokalen Ebene nutzen. Sie können steuern, wie viel Speicherplatz diese Volumes verwenden können. Sie können die Eigentümerschaft der lokalen Ebene mit einem HA-Paar verschieben. Sie können auch eine lokale Ebene löschen.

* link:add-capacity-local-tier-overview-task.html["Hinzufügen von Kapazität (Festplatten) zu einer lokalen Ebene"]
+
Mithilfe verschiedener Methoden folgen Sie einem bestimmten Workflow, um die Kapazität hinzuzufügen. Festplatten können einer lokalen Ebene hinzugefügt und zu einem Node oder Shelf hinzugefügt werden. Bei Bedarf können Sie falsch ausgerichtete Ersatzpartitionen korrigieren.


