---
permalink: disks-aggregates/manual-assign-disks-ownership-manage-task.html 
sidebar: sidebar 
keywords: manual, assign, disk, ownership 
summary: 'Die Festplatten müssen einem Node gehören, bevor sie in einer lokalen Tier (Aggregat) verwendet werden können. Wenn Ihr Cluster nicht für die Verwendung der automatischen Festplattenzuordnungszuweisung konfiguriert ist, müssen Sie die Eigentümerschaft manuell zuweisen. Sie können die Eigentumsrechte einer Festplatte, die in einer lokalen Ebene verwendet wird, nicht neu zuweisen.' 
---
= Manuelles Zuweisen der Festplatteneigentümer
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Festplatten müssen einem Node gehören, bevor sie in einer lokalen Tier (Aggregat) verwendet werden können.

Wenn Ihr Cluster nicht für die Verwendung der automatischen Festplattenzuordnungszuweisung konfiguriert ist, müssen Sie die Eigentümerschaft manuell zuweisen.

Sie können die Eigentumsrechte einer Festplatte, die in einer lokalen Ebene verwendet wird, nicht neu zuweisen.

.Schritte
. Zeigen Sie über die CLI alle Festplatten ohne Besitzer an:
+
`storage disk show -container-type unassigned`

. Weisen Sie jede Festplatte zu:
+
`storage disk assign -disk _disk_name_ -owner _owner_name_`

+
Sie können das Platzhalterzeichen verwenden, um mehr als eine Festplatte gleichzeitig zuzuweisen. Wenn Sie eine Ersatzfestplatte neu zuweisen, die bereits einem anderen Node gehört, müssen Sie die Option „`-Force`“ verwenden.


