---
permalink: disks-aggregates/modify-caching-policies-flash-pool-aggregates-task.html 
sidebar: sidebar 
keywords: modify, cache, policy, flash pool, aggregate, local tier 
summary: Sie sollten die Caching-Richtlinie nur dann ändern, wenn eine andere Caching-Richtlinie für eine bessere Performance zu erwarten ist. Sie können die Caching-Richtlinie eines Volumes auf einer lokalen Flash Pool Tier ändern. 
---
= Caching-Richtlinien der lokalen Flash Pool Tiers in ONTAP ändern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten die Caching-Richtlinie nur dann ändern, wenn eine andere Caching-Richtlinie für eine bessere Performance zu erwarten ist. Sie können die Caching-Richtlinie eines Volumes auf einer lokalen Flash Pool Tier ändern.

.Bevor Sie beginnen
Sie müssen festlegen, ob Sie Ihre Caching-Richtlinie ändern möchten.

.Über diese Aufgabe
In den meisten Fällen ist die standardmäßige Caching-Richtlinie von `auto` die beste Caching-Richtlinie, die Sie verwenden können. Die Caching-Richtlinie sollte nur geändert werden, wenn eine andere Richtlinie eine bessere Performance für Ihren Workload bietet. Die Konfiguration einer falschen Caching-Richtlinie kann die Volume Performance erheblich beeinträchtigen. Die Performance kann sich im Laufe der Zeit allmählich erhöhen. Beim Ändern von Caching-Richtlinien sollten Sie Vorsicht walten lassen. Wenn Sie Performance-Probleme bei einem Volume haben, für das die Caching-Richtlinie geändert wurde, sollten Sie die Caching-Richtlinie an zurücksenden `auto`.

.Schritt
. Verwenden Sie die CLI, um die Caching-Richtlinie des Volume zu ändern:
+
`volume modify -volume _volume_name_ -caching-policy _policy_name_`



.Beispiel
Im folgenden Beispiel wird die Caching-Richtlinie eines Volumes mit dem Namen der Richtlinie `none` geändert `vol2`:

`volume modify -volume vol2 -caching-policy none`
