---
permalink: disks-aggregates/raid-protection-levels-disks-concept.html 
sidebar: sidebar 
keywords: raid, protection, level, spare, disk, failure, parity, local tier, aggregate 
summary: 'ONTAP unterstützt drei Stufen des RAID-Schutzes für lokale Tiers (Aggregate). Die Stufe des RAID-Schutzes bestimmt die Anzahl der für die Datenwiederherstellung im Falle eines Festplattenfehlenes verfügbaren Parity-Festplatten.' 
---
= RAID-Schutzlevel für Festplatten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP unterstützt drei Stufen des RAID-Schutzes für lokale Tiers (Aggregate). Die Stufe des RAID-Schutzes bestimmt die Anzahl der für die Datenwiederherstellung im Falle eines Festplattenfehlenes verfügbaren Parity-Festplatten.

Wenn in der RAID-Gruppe ein Ausfall einer Datenfestplatte ausfällt, kann ONTAP die ausgefallene Festplatte durch eine Ersatzfestplatte ersetzen und über Paritätsdaten die Daten der ausgefallenen Festplatte wiederherstellen.

* *RAID4*
+
Durch den RAID4-Schutz kann ONTAP die Daten von einer ausgefallenen Festplatte innerhalb der RAID-Gruppe mit einer Ersatzfestplatte ersetzen und rekonstruieren.

* *RAID-DP*
+
Dank RAID-DP-Schutz kann ONTAP bis zu zwei Ersatzfestplatten benötigen, um die Daten von bis zu zwei gleichzeitigen ausgefallenen Festplatten innerhalb der RAID-Gruppe zu ersetzen und zu rekonstruieren.

* *RAID-TEC*
+
Mit RAID-TEC-Schutz kann ONTAP bis zu drei freie Festplatten einsetzen, um die Daten von bis zu drei gleichzeitig ausgefallenen Festplatten innerhalb der RAID-Gruppe zu ersetzen und zu rekonstruieren.



.Verwandte Informationen
http://["Technischer Bericht 3437 von NetApp zur Ausfallsicherheit von Storage-Subsystemen"^]
