---
permalink: disks-aggregates/root-data-partitioning-management-concept.html 
sidebar: sidebar 
keywords: additional, root-data, partitioning, management, options 
summary: Über das Bootmenü ist eine Option zur Root-Datenpartitionierung verfügbar, die zusätzliche Verwaltungsfunktionen für Festplatten bietet, die für die Root-Datenpartitionierung konfiguriert sind. 
---
= Zusätzliche ONTAP Root Data Partitionierungsverwaltungsoptionen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Über das Bootmenü ist eine Option zur Root-Datenpartitionierung verfügbar, die zusätzliche Verwaltungsfunktionen für Festplatten bietet, die für die Root-Datenpartitionierung konfiguriert sind.

Die folgenden Verwaltungsfunktionen sind unter der Boot Menu Option 9 verfügbar.

* *Alle Festplatten entpartitionieren und deren Eigentümerinformationen entfernen*
+
Diese Option ist nützlich, wenn Ihr System für die Root-Daten-Partitionierung konfiguriert ist und mit einer anderen Konfiguration neu initialisiert werden muss.

* *Bereinigung der Konfiguration und Initialisierung des Knotens mit partitionierten Festplatten*
+
Diese Option ist für Folgendes nützlich:

+
** Ihr System ist nicht für die Root-Datenpartitionierung konfiguriert und es besteht der Wunsch, es für die Root-Datenpartitionierung zu konfigurieren.
** Ihr System ist für die Root-Datenpartitionierung falsch konfiguriert und muss korrigiert werden
** Sie besitzen eine AFF Plattform oder eine FAS Plattform mit ausschließlich SSDs, die für die vorherige Version der Root-Datenpartitionierung konfiguriert ist, und möchten diese auf die neuere Version der Root-Datenpartitionierung aktualisieren, um eine höhere Speichereffizienz zu erzielen.


* *Bereinigung der Konfiguration und Initialisierung des Knotens mit vollständigen Festplatten*
+
Diese Option ist nützlich, wenn Sie Folgendes benötigen:

+
** Vorhandene Partitionen entpartitionieren
** Lokalen Festplattenbesitz entfernen
** Das System mit vollständigen Festplatten unter Verwendung von RAID-DP neu initialisieren



