---
permalink: disks-aggregates/sanitization-tips-concept.html 
sidebar: sidebar 
keywords: disk, disk sanitization, local tier, aggregate, sensitive data, sanitize 
summary: Wenn Sie lokale Tiers erstellen oder sichern, um Daten zu enthalten, die möglicherweise bereinigt werden müssen, können Sie durch das Befolgen einiger einfacher Richtlinien die Zeit für die Datendesinfektionszeit verkürzen. 
---
= Tipps zum Erstellen und Sichern von lokalen ONTAP-Tiers mit zu bereinigenden Daten
:allow-uri-read: 


[role="lead"]
Wenn Sie lokale Tiers erstellen oder sichern, um Daten zu enthalten, die möglicherweise bereinigt werden müssen, können Sie durch das Befolgen einiger einfacher Richtlinien die Zeit für die Datendesinfektionszeit verkürzen.

* Stellen Sie sicher, dass die lokalen Tiers mit vertraulichen Daten nicht größer sind, als sie sein müssen.
+
Wenn sie größer als nötig sind, erfordert die Bereinigung mehr Zeit, Speicherplatz und Bandbreite.

* Wenn Sie lokale Tiers mit vertraulichen Daten sichern, vermeiden Sie Backups in lokaler Ebene, die auch große Mengen nicht-sensibler Daten enthalten.
+
Dies verringert die Ressourcen, die zum Verschieben nicht sensibler Daten vor der Bereinigung vertraulicher Daten erforderlich sind.


