---
permalink: disks-aggregates/set-cache-data-retention-policy-flash-pool-task.html 
sidebar: sidebar 
keywords: set, cache-retention policy, flash pool 
summary: Sie können Volumes in lokalen Flash Pool Tiers Richtlinien zur Cache-Aufbewahrung zuweisen. Daten in Volumes mit hoher Cache-Aufbewahrungsrichtlinie bleiben länger im Cache und Daten in Volumes mit einer geringen Cache-Aufbewahrungsrichtlinie werden schneller entfernt. Dies steigert die Performance Ihrer kritischen Workloads, indem Informationen mit hoher Priorität über einen längeren Zeitraum schneller zugänglich gemacht werden. 
---
= Legen Sie die Richtlinie für die Cache-Aufbewahrung für lokale Flash Pool Tiers in ONTAP fest
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Volumes in lokalen Flash Pool Tiers Richtlinien zur Cache-Aufbewahrung zuweisen. Daten in Volumes mit hoher Cache-Aufbewahrungsrichtlinie bleiben länger im Cache und Daten in Volumes mit einer geringen Cache-Aufbewahrungsrichtlinie werden schneller entfernt. Dies steigert die Performance Ihrer kritischen Workloads, indem Informationen mit hoher Priorität über einen längeren Zeitraum schneller zugänglich gemacht werden.

.Bevor Sie beginnen
Sie sollten wissen, ob Ihr System irgendwelche Bedingungen hat, die verhindern könnten, dass die Richtlinie zur Cache-Aufbewahrung Auswirkungen auf die Aufbewahrungsdauer Ihrer Daten im Cache hat.

.Schritte
Verwenden Sie die CLI im erweiterten Berechtigungsmodus, um die folgenden Schritte auszuführen:

. Ändern Sie die Berechtigungseinstellung in erweitert:
+
`set -privilege advanced`

. Überprüfen Sie die Cache-Aufbewahrungsrichtlinie des Volumes:
+
Standardmäßig lautet die Aufbewahrungsrichtlinie für den Cache „`normal`“.

. Legen Sie die Cache-Aufbewahrungsrichtlinie fest:
+
`volume modify -volume volume_name -vserver vserver_name -caching-policy policy_name`

. Überprüfen Sie, ob die Cache-Aufbewahrungsrichtlinie des Volumes in die von Ihnen ausgewählte Option geändert wurde.
. Die Berechtigungsebene wird an den Administrator zurückgegeben:
+
`set -privilege admin`


