---
permalink: disks-aggregates/set-cache-data-retention-policy-flash-pool-task.html 
sidebar: sidebar 
keywords: set, cache-retention policy, flash pool 
summary: 'Sie können Volumes in lokalen Flash Pool Tiers (Aggregate) Richtlinien zur Cache-Aufbewahrung zuweisen. Daten in Volumes mit hoher Cache-Aufbewahrungsrichtlinie bleiben länger im Cache und Daten in Volumes mit einer geringen Cache-Aufbewahrungsrichtlinie werden schneller entfernt. Dies steigert die Performance Ihrer kritischen Workloads, indem Informationen mit hoher Priorität über einen längeren Zeitraum schneller zugänglich gemacht werden.' 
---
= Festlegen der Cache-Aufbewahrungsrichtlinie für lokale Flash Pool Tiers (Aggregate)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Volumes in lokalen Flash Pool Tiers (Aggregate) Richtlinien zur Cache-Aufbewahrung zuweisen. Daten in Volumes mit hoher Cache-Aufbewahrungsrichtlinie bleiben länger im Cache und Daten in Volumes mit einer geringen Cache-Aufbewahrungsrichtlinie werden schneller entfernt. Dies steigert die Performance Ihrer kritischen Workloads, indem Informationen mit hoher Priorität über einen längeren Zeitraum schneller zugänglich gemacht werden.

.Was Sie benötigen
Sie sollten wissen, ob Ihr System irgendwelche Bedingungen hat, die verhindern könnten, dass die Richtlinie zur Cache-Aufbewahrung Auswirkungen auf die Aufbewahrungsdauer Ihrer Daten im Cache hat.

.Schritte
Verwenden Sie die CLI im erweiterten Berechtigungsmodus, um die folgenden Schritte auszuführen:

. Ändern Sie die Berechtigungseinstellung in erweitert:
+
`set -privilege advanced`

. Überprüfen Sie die Cache-Aufbewahrungsrichtlinie des Volumes:
+
Standardmäßig lautet die Aufbewahrungsrichtlinie für den Cache „`normal`“.

. Legen Sie die Cache-Aufbewahrungsrichtlinie fest:
+
|===


| ONTAP-Version | Befehl 


 a| 
ONTAP 9.0, 9.1
 a| 
`priority hybrid-cache set volume_name read-cache=read_cache_value write-cache=write_cache_value cache-retention-priority=cache_retention_policy`

Legen Sie `cache_retention_policy` `high` den Wert auf fest, wenn Daten länger im Cache verbleiben sollen. Stellen Sie `cache_retention_policy` `low` für Daten, die Sie früher aus dem Cache entfernen möchten, auf ein.



 a| 
ONTAP 9.2 oder höher
 a| 
`volume modify -volume volume_name -vserver vserver_name -caching-policy policy_name.`

|===
. Überprüfen Sie, ob die Cache-Aufbewahrungsrichtlinie des Volumes in die von Ihnen ausgewählte Option geändert wurde.
. Die Berechtigungsebene wird an den Administrator zurückgegeben:
+
`set -privilege admin`


