---
permalink: flexgroup/convert-flexvol-svm-dr-relationship-task.html 
sidebar: sidebar 
keywords: convert, flexvol, flexgroup, svm-dr 
summary: Ab ONTAP 9.10.1 ist es möglich, ein FlexVol Volume in ein FlexGroup Volume auf einer SVM-DR-Quelle zu konvertieren. 
---
= ONTAP FlexVol Volumes in FlexGroup Volumes innerhalb einer SVM-DR Beziehung konvertieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.10.1 ist es möglich, ein FlexVol Volume in ein FlexGroup Volume auf einer SVM-DR-Quelle zu konvertieren.

.Bevor Sie beginnen
* Das FlexVol Volume, das konvertiert wird, muss online sein.
* Die Vorgänge und Konfigurationen auf dem FlexVol volume müssen mit dem Konvertierungsprozess kompatibel sein.
+
Eine Fehlermeldung wird generiert, wenn das FlexVol Volume eine Inkompatibilität aufweist, und die Volume-Konvertierung wird abgebrochen. Korrekturmaßnahmen können ergriffen und die Konvertierung erneut versucht werden. Weitere Einzelheiten finden sich unter link:convert-flexvol-concept.html["Überlegungen zur Umwandlung von FlexVol Volumes in FlexGroup Volumes"]



.Schritte
. Anmeldung im erweiterten Berechtigungsmodus: `set -privilege advanced`
. Vom Ziel aus die SVM-DR Beziehung aktualisieren:
+
[source, cli]
----
snapmirror update -destination-path <destination_svm_name>: -source-path <source_svm_name>:
----
+
[NOTE]
====
Nach dem SVM-Namen in der  `-destination-path` Option muss ein Doppelpunkt (:) eingegeben werden.

====
. Stellen Sie sicher, dass sich die SVM-DR-Beziehung im SnapMirrored-Status befindet und nicht getrennt wurde:
+
[source, cli]
----
snapmirror show
----
. Von der Ziel-SVM aus prüfen, ob das FlexVol Volume für die Konvertierung bereit ist:
+
[source, cli]
----
volume conversion start -vserver <svm_name> -volume <vol_name> -check-only true
----
+
Falls dieser Befehl andere Fehler als „Dies ist ein Ziel-SVMDR-Volume“ erzeugt, besteht die Möglichkeit, die entsprechende Korrekturmaßnahme zu ergreifen, den Befehl erneut auszuführen und die Konvertierung fortzusetzen.

. Vom Ziel aus die Übertragungen in der SVM-DR Beziehung deaktivieren:
+
[source, cli]
----
snapmirror quiesce -destination-path <dest_svm>:
----
+
[NOTE]
====
Nach dem SVM-Namen in der  `-destination-path` Option muss ein Doppelpunkt (:) eingegeben werden.

====
. Vom Quell-Cluster aus die Konvertierung starten:
+
[source, cli]
----
volume conversion start -vserver <svm_name> -volume <vol_name>
----
. Es sollte überprüft werden, ob die Konvertierung erfolgreich war:
+
[source, cli]
----
volume show <vol_name> -fields volume-style-extended,state
----
+
[listing]
----
cluster-1::*> volume show my_volume -fields volume-style-extended,state

vserver  volume     state    volume-style-extended
-------  ---------  ------   ---------------------
vs0      my_volume  online   flexgroup
----
. Vom Ziel-Cluster die Übertragungen für die Beziehung fortsetzen:
+
[source, cli]
----
snapmirror resume -destination-path <dest_svm>:
----
+
[NOTE]
====
Nach dem SVM-Namen in der  `-destination-path` Option muss ein Doppelpunkt (:) eingegeben werden.

====
. Vom Ziel-Cluster aus ein Update durchführen, um die Konvertierung auf das Ziel zu übertragen:
+
[source, cli]
----
snapmirror update -destination-path <dest_svm>:
----
+
[NOTE]
====
Nach dem SVM-Namen in der  `-destination-path` Option muss ein Doppelpunkt (:) eingegeben werden.

====
. Stellen Sie sicher, dass sich die SVM-DR-Beziehung im SnapMirrored-Status befindet und nicht getrennt wurde:
+
[source, cli]
----
snapmirror show
----
. Sicherstellen, dass die Konvertierung auf dem Zielsystem erfolgte:
+
[source, cli]
----
volume show <vol_name> -fields volume-style-extended,state
----
+
[listing]
----
cluster-2::*> volume show my_volume -fields volume-style-extended,state

vserver  volume     state   volume-style-extended
-------  -------    ------  ---------------------
vs0_dst  my_volume  online  flexgroup
----


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resume.html["snapmirror resume"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["snapmirror quiesce"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["snapmirror show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["SnapMirror update"^]

