---
permalink: flexgroup/convert-flexvol-snapmirror-relationship-task.html 
sidebar: sidebar 
keywords: convert, flexvol, volume, snapmirror, relation, flexgroup 
summary: Um eine FlexVol Volume SnapMirror Beziehung in eine FlexGroup Volume SnapMirror Beziehung in ONTAP zu konvertieren, muss zuerst das Ziel-FlexVol Volume und anschließend das Quell-FlexVol Volume konvertiert werden. 
---
= ONTAP FlexVol volume SnapMirror Beziehungen in ONTAP FlexGroup volume SnapMirror Beziehungen konvertieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um eine FlexVol Volume SnapMirror Beziehung in eine FlexGroup Volume SnapMirror Beziehung in ONTAP zu konvertieren, muss zuerst das Ziel-FlexVol Volume und anschließend das Quell-FlexVol Volume konvertiert werden.

.Über diese Aufgabe
* Das Mischen von FlexGroups mit FlexVol Volumes in SnapMirror/SnapVault Beziehungen wird über den Konvertierungsprozess hinaus nicht unterstützt.
* Die FlexGroup Konvertierung wird nur für SnapMirror asynchrone Beziehungen unterstützt.
* Die Konvertierung von FlexGroup wird in SnapMirror Cloud-Beziehungen nicht unterstützt.
* Die Umrechnungszeit hängt von mehreren Variablen ab. Zu diesen Variablen gehören unter anderem:
+
** CPU des Controllers
** CPU-Auslastung durch andere Anwendungen
** Datenmenge im ersten Snapshot
** Netzwerkbandbreite
** Von anderen Anwendungen genutzte Bandbreite




.Bevor Sie beginnen
* Das FlexVol Volume, das konvertiert wird, muss online sein.
* Das FlexVol Volume in der SnapMirror Beziehung darf nicht das Quell-Volume für mehrere SnapMirror Beziehungen sein.
+
Ab ONTAP 9.9.1 werden Fanout-SnapMirror-Beziehungen für FlexGroup Volumes unterstützt. Weitere Informationen finden sich unter link:../flexgroup/create-snapmirror-cascade-fanout-reference.html#considerations-for-creating-cascading-relationships["Überlegungen zur Erstellung von SnapMirror Kaskaden- und Fächerbeziehungen für FlexGroup Volumes"].

* Die Vorgänge und Konfigurationen auf dem FlexVol volume müssen mit dem Konvertierungsprozess kompatibel sein.
+
Eine Fehlermeldung wird generiert, wenn das FlexVol Volume eine Inkompatibilität aufweist und die Volume-Konvertierung abgebrochen wird. Korrekturmaßnahmen können ergriffen und die Konvertierung erneut versucht werden.



.Schritte
. Es sollte überprüft werden, ob die SnapMirror Beziehung intakt ist:
+
[source, cli]
----
snapmirror show
----
+
Nur Spiegelungsbeziehungen vom Typ XDP können konvertiert werden.

+
Beispiel:

+
[listing]
----
cluster2::> snapmirror show
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs0:src_dpv DP   vs2:dst_dpv  Snapmirrored
                                      Idle           -         true    -
vs0:src_xdp XDP  vs2:dst_xdp  Snapmirrored
                                      Idle           -         true    -
----
. Es sollte überprüft werden, ob das Quellvolume für die Konvertierung kompatibel ist:
+
.. Melden Sie sich im erweiterten Berechtigungsmodus an:
+
[source, cli]
----
set -privilege advanced
----
.. Der Konvertierungsprozess kann überprüft werden:
+
[source, cli]
----
volume conversion start -vserver <src_svm_name> -volume <src_vol> -check-only true
----
+
Beispiel:

+
[listing]
----
volume conversion start -vserver vs1 -volume src_vol -check-only true
----
+
Alle Fehler müssen behoben werden, bevor das Volume konvertiert wird.



. Das Ziel-FlexVol Volume in ein FlexGroup Volume konvertieren.
+
.. Die FlexVol SnapMirror Beziehung in den Ruhezustand versetzen:
+
[source, cli]
----
snapmirror quiesce -destination-path <dest_svm:dest_volume>
----
+
Beispiel:

+
[listing]
----
cluster2::> snapmirror quiesce -destination-path vs2:dst_xdp
----
.. Konvertierung starten:
+
[source, cli]
----
volume conversion start -vserver <dest_svm> -volume <dest_volume>
----
+
Beispiel:

+
[listing]
----
cluster-1::> volume conversion start -vserver vs2 -volume dst_xdp

Warning: After the volume is converted to a FlexGroup, it will not be possible
to change it back to a flexible volume.
Do you want to continue? {y|n}: y

[Job 510] Job succeeded: SnapMirror destination volume "dst_xdp" has been successfully converted to a FlexGroup volume.
You must now convert the relationship's source volume, "vs0:src_xdp", to a FlexGroup.
Then, re-establish the SnapMirror relationship using the "snapmirror resync" command.
----


. Das Quellvolume FlexVol in ein FlexGroup Volume konvertieren: `
+
[source, cli]
----
volume conversion start -vserver <src_svm_name> -volume <src_vol_name>
----
+
Beispiel:

+
[listing]
----
cluster-1::> volume conversion start -vserver vs0 -volume src_xdp

Warning: Converting flexible volume "src_xdp" in Vserver "vs0" to a FlexGroup
         will cause the state of all Snapshot copies from the volume to be set
         to "pre-conversion". Pre-conversion snapshots cannot be
         restored.
Do you want to continue? {y|n}: y
[Job 57] Job succeeded: success
----
. Beziehung neu synchronisieren:
+
[source, cli]
----
snapmirror resync -destination-path dest_svm_name:dest_volume
----
+
Beispiel:

+
[listing]
----
cluster2::> snapmirror resync -destination-path vs2:dst_xdp
----


.Nachdem Sie fertig sind
Es ist sicherzustellen, dass wenn das Quell-FlexGroup Volume um weitere Bestandteile erweitert wird, auch das Zielvolumen entsprechend erweitert wird.

.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["snapmirror quiesce"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["SnapMirror Resynchronisierung"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["snapmirror show"^]

