---
permalink: flexgroup/create-unified-data-protection-relationship-task.html 
sidebar: sidebar 
keywords: create, unified, data, protection, relationship, flexgroup, volume, snap shot, snapshot, policy, policies, mirrorandvault, mirror-vault, mirrorallsnapshot, back up, backup, snapvault, snap vault 
summary: Ab ONTAP 9.3 ist es möglich, SnapMirror unified Data Protection-Beziehungen zu erstellen und zu konfigurieren, sodass Notfallwiederherstellung und Archivierung auf demselben Ziel-Volume eingerichtet werden können. 
---
= Einheitliche Datenschutzbeziehungen für ONTAP FlexGroup Volumes erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.3 ist es möglich, SnapMirror unified Data Protection-Beziehungen zu erstellen und zu konfigurieren, sodass Notfallwiederherstellung und Archivierung auf demselben Ziel-Volume eingerichtet werden können.

.Bevor Sie beginnen
Es sind die Überlegungen zur Schaffung einheitlicher Datenschutzbeziehungen für FlexGroup Volumes zu beachten.

link:snapvault-backup-concept.html["Überlegungen zur Erstellung einer SnapVault Backup-Beziehung und einer einheitlichen Datensicherungsbeziehung für FlexGroup Volumes"]

.Schritte
. Ein Ziel-FlexGroup-Volume vom Typ  `DP` erstellen, das die gleiche Anzahl an Bestandteilen wie das Quell-FlexGroup-Volume aufweist:
+
.. Im Quell-Cluster die Anzahl der Bestandteile im Quell-FlexGroup-Volume ermitteln: `volume show -volume volume_name* -is-constituent true`
+
[listing]
----
cluster1::> volume show  -volume srcFG* -is-constituent true
Vserver   Volume         Aggregate    State      Type       Size  Available  Used%
--------- ------------   ------------ ---------- ---- ----------  ---------- -----
vss       srcFG          -            online     RW         400TB   172.86GB  56%
vss       srcFG__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vss       srcFG__0002    aggr1        online     RW         25TB    10.86TB   56%
vss       srcFG__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vss       srcFG__0004    aggr1        online     RW         25TB    10.73TB   57%
vss       srcFG__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vss       srcFG__0006    aggr1        online     RW         25TB    10.64TB   57%
vss       srcFG__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----
.. Vom Ziel-Cluster aus ein Ziel-FlexGroup Volume vom Typ  `DP` mit der gleichen Anzahl an Bestandteilen wie das Quell-FlexGroup Volume erstellen.
+
[listing]
----
cluster2::> volume create -vserver vsd -aggr-list aggr1,aggr2 -aggr-list-multiplier 8 -size 400TB -type DP dstFG

Warning: The FlexGroup volume "dstFG" will be created with the following number of constituents of size 25TB: 16.
Do you want to continue? {y|n}: y
[Job 766] Job succeeded: Successful
----
.. Vom Ziel-Cluster aus die Anzahl der Bestandteile im Ziel-FlexGroup Volume überprüfen: `volume show -volume volume_name* -is-constituent true`
+
[listing]
----
cluster2::> volume show  -volume dstFG* -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vsd       dstFG          -            online     RW         400TB   172.86GB  56%
vsd       dstFG__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vsd       dstFG__0002    aggr1        online     RW         25TB    10.86TB   56%
vsd       dstFG__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vsd       dstFG__0004    aggr1        online     RW         25TB    10.73TB   57%
vsd       dstFG__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vsd       dstFG__0006    aggr1        online     RW         25TB    10.64TB   57%
vsd       dstFG__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----


. Einen Arbeitsplan erstellen: `job schedule cron create -name job_name -month month -dayofweek day_of_week -day day_of_month -hour hour -minute minute`
+
Für die  `-month`,  `-dayofweek` und  `-hour` Optionen kann  `all` angegeben werden, um den Job jeden Monat, jeden Wochentag bzw. jede Stunde auszuführen.

+
Das folgende Beispiel erstellt einen Jobplan mit dem Namen  `my_weekly`, der samstags um 3:00 Uhr morgens ausgeführt wird:

+
[listing]
----
cluster1::> job schedule cron create -name my_weekly -dayofweek "Saturday" -hour 3 -minute 0
----
. Eine benutzerdefinierte Richtlinie vom Typ  `mirror-vault` erstellen und anschließend eine Regel für die Spiegel- und Tresorrichtlinie definieren:
+
.. Eine benutzerdefinierte Richtlinie vom Typ  `mirror-vault` für die einheitliche Datenschutzbeziehung erstellen: `snapmirror policy create -vserver svm_name -policy policy_name -type mirror-vault`
.. Eine Regel für die Mirror und Vault Richtlinie definiert, welche Snapshots während Initialisierungs- und Aktualisierungsvorgängen übertragen werden: `snapmirror policy add-rule -vserver svm_name -policy policy_for_rule - snapmirror-label snapmirror-label -keep retention_count -schedule schedule`


+
Wenn Sie keine benutzerdefinierte Richtlinie angeben, wird die  `MirrorAndVault`Richtlinie für einheitliche Datenschutzbeziehungen verwendet.

. Eine einheitliche Datenschutzbeziehung erstellen: `snapmirror create -source-path src_svm:src_flexgroup -destination-path dest_svm:dest_flexgroup -type XDP -schedule schedule_name -policy MirrorAndVault`
+
In ONTAP 9.4 und früher, wenn die Richtlinie nicht mit dem `snapmirror create` Befehl angegeben wird, wird standardmäßig die `MirrorAllSnapshots` Richtlinie verwendet. In ONTAP 9.5, wenn die Richtlinie nicht mit dem `snapmirror create` Befehl angegeben wird, wird standardmäßig die `MirrorAndVault` Richtlinie verwendet.

+
[listing]
----
cluster2::> snapmirror create -source-path vss:srcFG -destination-path vsd:dstFG -type XDP -schedule Daily -policy MirrorAndVault
----
+
Weitere Informationen zu  `snapmirror create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["ONTAP-Befehlsreferenz"^].

. Vom Ziel-Cluster aus wird die einheitliche Datensicherungsbeziehung durch einen Basistransfer initialisiert: `snapmirror initialize -destination-path dest_svm:dest_flexgroup`
+
[listing]
----
cluster2::> snapmirror initialize -destination-path vsd:dstFG
Operation is queued: snapmirror initialize of destination "vsd:dstFG".
----


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["snapmirror create"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["snapmirror initialize"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-add-rule.html["snapmirror policy add-rule"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-create.html["snapmirror policy create"^]

