---
permalink: flexgroup/create-snapmirror-relationship-task.html 
sidebar: sidebar 
keywords: create, snapmirror, relationship, flexgroup, volume, snap mirror, flex group, peered svm, replicate, replicating, disaster 
summary: Eine SnapMirror Beziehung zwischen Quell-FlexGroup Volume und Ziel-FlexGroup Volume auf einer gepeerten SVM ermöglicht die Replikation von Daten für die Notfallwiederherstellung. 
---
= Erstellung von SnapMirror Beziehungen für ONTAP FlexGroup Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es kann eine SnapMirror Beziehung zwischen dem Quell-FlexGroup Volume und dem Ziel-FlexGroup Volume auf einer verbundenen SVM erstellt werden, um Daten für die Notfallwiederherstellung zu replizieren. Die Spiegelkopien des FlexGroup Volumes können zur Wiederherstellung von Daten im Katastrophenfall verwendet werden.

.Bevor Sie beginnen
Die Cluster-Peering Beziehung und die SVM-Peering Beziehung müssen erstellt worden sein.

link:../peering/index.html["Cluster- und SVM-Peering"]

.Über diese Aufgabe
* Ab ONTAP 9.9.1 kann die ONTAP CLI verwendet werden, um SnapMirror Kaskaden- und Fanout-Beziehungen für FlexGroup Volumes zu erstellen. Weitere Details finden sich unter link:create-snapmirror-cascade-fanout-reference.html["Überlegungen zur Erstellung von SnapMirror Kaskaden- und Fächerbeziehungen für FlexGroup Volumes"].
* Sowohl Intercluster-SnapMirror Beziehungen als auch Intracluster-SnapMirror Beziehungen können für FlexGroup Volumes erstellt werden.
* Ab ONTAP 9.3 können FlexGroup Volumes, die sich in einer SnapMirror Beziehung befinden, erweitert werden.
+
Wenn eine Version von ONTAP vor ONTAP 9.3 verwendet wird, sollten FlexGroup Volumes nach dem Herstellen einer SnapMirror Beziehung nicht erweitert werden; die Kapazität von FlexGroup Volumes kann jedoch nach dem Herstellen einer SnapMirror Beziehung erhöht werden. Wenn das Quell FlexGroup Volume nach dem Aufheben der SnapMirror Beziehung in Versionen vor ONTAP 9.3 erweitert wird, ist ein Basistransfer auf das Ziel FlexGroup Volume erforderlich.



.Schritte
. Ein Ziel-FlexGroup-Volume vom Typ  `DP` erstellen, das die gleiche Anzahl an Bestandteilen wie das Quell-FlexGroup-Volume aufweist:
+
.. Im Quell-Cluster die Anzahl der Bestandteile im Quell-FlexGroup-Volume ermitteln: `volume show -volume volume_name* -is-constituent true`
+
[listing]
----
cluster1::> volume show  -volume srcFG* -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vss       srcFG          -            online     RW         400TB   172.86GB  56%
vss       srcFG__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vss       srcFG__0002    aggr1        online     RW         25TB    10.86TB   56%
vss       srcFG__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vss       srcFG__0004    aggr1        online     RW         25TB    10.73TB   57%
vss       srcFG__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vss       srcFG__0006    aggr1        online     RW         25TB    10.64TB   57%
vss       srcFG__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----
.. Vom Ziel-Cluster aus ein Ziel-FlexGroup Volume vom Typ  `DP` mit der gleichen Anzahl an Bestandteilen wie das Quell-FlexGroup Volume erstellen.
+
[listing]
----
cluster2::> volume create -vserver vsd -aggr-list aggr1,aggr2 -aggr-list-multiplier 8 -size 400TB -type DP dstFG

Warning: The FlexGroup volume "dstFG" will be created with the following number of constituents of size 25TB: 16.
Do you want to continue? {y|n}: y
[Job 766] Job succeeded: Successful
----
.. Vom Ziel-Cluster aus die Anzahl der Bestandteile im Ziel-FlexGroup Volume überprüfen: `volume show -volume volume_name* -is-constituent true`
+
[listing]
----
cluster2::> volume show  -volume dstFG* -is-constituent true
Vserver   Volume        Aggregate    State      Type       Size  Available  Used%
--------- ------------  ------------ ---------- ---- ----------  ---------- -----
vsd       dstFG          -            online     DP         400TB   172.86GB  56%
vsd       dstFG__0001    Aggr_cmode   online     DP         25GB    10.86TB   56%
vsd       dstFG__0002    aggr1        online     DP         25TB    10.86TB   56%
vsd       dstFG__0003    Aggr_cmode   online     DP         25TB    10.72TB   57%
vsd       dstFG__0004    aggr1        online     DP         25TB    10.73TB   57%
vsd       dstFG__0005    Aggr_cmode   online     DP         25TB    10.67TB   57%
vsd       dstFG__0006    aggr1        online     DP         25TB    10.64TB   57%
vsd       dstFG__0007    Aggr_cmode   online     DP         25TB    10.63TB   57%
...
----


. Einen Arbeitsplan erstellen: `job schedule cron create -name job_name -month month -dayofweek day_of_week -day day_of_month -hour hour -minute minute`
+
Für die  `-month`,  `-dayofweek` und  `-hour` Optionen kann  `all` angegeben werden, um den Job jeden Monat, jeden Wochentag bzw. jede Stunde auszuführen.

+
Das folgende Beispiel erstellt einen Jobplan mit dem Namen  `my_weekly`, der samstags um 3:00 Uhr morgens ausgeführt wird:

+
[listing]
----
cluster1::> job schedule cron create -name my_weekly -dayofweek "Saturday" -hour 3 -minute 0
----
. Eine benutzerdefinierte Richtlinie vom Typ  `async-mirror` für die SnapMirror Beziehung erstellen: `snapmirror policy create -vserver SVM -policy snapmirror_policy -type async-mirror`
+
Wenn Sie keine benutzerdefinierte Richtlinie erstellen, sollte die  `MirrorAllSnapshots` Richtlinie für SnapMirror Beziehungen angegeben werden.

. Vom Ziel-Cluster aus eine SnapMirror Beziehung zwischen dem Quell-FlexGroup Volume und dem Ziel-FlexGroup Volume erstellen: `snapmirror create -source-path src_svm:src_flexgroup -destination-path dest_svm:dest_flexgroup -type XDP -policy snapmirror_policy -schedule sched_name`
+
SnapMirror Beziehungen für FlexGroup Volumes müssen vom Typ  `XDP` sein.

+
Wenn Sie für die SnapMirror Beziehung des FlexGroup Volumes einen Drosselungswert festlegen, verwendet jede Komponente denselben Drosselungswert. Der Drosselungswert wird nicht auf die einzelnen Komponenten aufgeteilt.

+
[NOTE]
====
Sie können keine SnapMirror Bezeichnungen von Snapshots für FlexGroup Volumes verwenden.

====
+
In ONTAP 9.4 und früher, wenn die Richtlinie nicht mit dem `snapmirror create` Befehl angegeben wird, wird standardmäßig die `MirrorAllSnapshots` Richtlinie verwendet. In ONTAP 9.5, wenn die Richtlinie nicht mit dem `snapmirror create` Befehl angegeben wird, wird standardmäßig die `MirrorAndVault` Richtlinie verwendet.

+
[listing]
----
cluster2::> snapmirror create -source-path vss:srcFG -destination-path vsd:dstFG -type XDP -policy MirrorAllSnapshots -schedule hourly
Operation succeeded: snapmirror create for the relationship with destination "vsd:dstFG".
----
. Vom Ziel-Cluster aus wird die SnapMirror Beziehung durch einen Basistransfer initialisiert: `snapmirror initialize -destination-path dest_svm:dest_flexgroup`
+
Nach Abschluss des Basistransfers wird das Ziel-FlexGroup-Volume regelmäßig entsprechend dem Zeitplan der SnapMirror Beziehung aktualisiert.

+
[listing]
----
cluster2::> snapmirror initialize -destination-path vsd:dstFG
Operation is queued: snapmirror initialize of destination "vsd:dstFG".
----
+
[NOTE]
====
Wenn eine SnapMirror Beziehung zwischen FlexGroup Volumes besteht, wobei das Quell-Cluster ONTAP 9.3 und das Ziel-Cluster ONTAP 9.2 oder älter ausführt, und wenn im Quell-FlexGroup Volume Qtrees erstellt werden, schlagen die SnapMirror Aktualisierungen fehl. Zur Behebung dieser Situation sind alle nicht standardmäßigen Qtrees im FlexGroup Volume zu löschen, die Qtree-Funktionalität im FlexGroup Volume zu deaktivieren und anschließend alle Snapshots zu löschen, bei denen die Qtree-Funktionalität aktiviert ist.

====


.Nachdem Sie fertig sind
Die Ziel-SVM wird für den Datenzugriff eingerichtet, indem die erforderlichen Konfigurationen wie LIFs und Exportrichtlinien festgelegt werden.

.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["snapmirror create"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["snapmirror initialize"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-create.html["snapmirror policy create"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["SnapMirror update"^]

