---
permalink: flexgroup/create-snapvault-relationship-task.html 
sidebar: sidebar 
keywords: create, snapvault, relationship, flexgroup, volumes 
summary: Sie können eine SnapVault Beziehung konfigurieren und der Beziehung eine SnapVault Richtlinie zuweisen, um ein SnapVault Backup zu erstellen. 
---
= SnapVault Beziehung für FlexGroup Volumes erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine SnapVault Beziehung konfigurieren und der Beziehung eine SnapVault Richtlinie zuweisen, um ein SnapVault Backup zu erstellen.

Sie müssen sich bei der Erstellung einer SnapVault Beziehung für FlexGroup Volumes bewusst sein.

.Schritte
. Erstellung eines FlexGroup Ziel-Volume des Typs `DP` Dies verfügt über die gleiche Anzahl von Komponenten wie das FlexGroup Quell-Volume:
+
.. Bestimmen Sie aus dem Quellcluster die Anzahl der Komponenten im Quell-FlexGroup Volume: `volume show -volume volume_name* -is-constituent true`
+
[listing]
----
cluster1::> volume show  -volume src* -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vss       src          -            online     RW         400TB   172.86GB  56%
vss       src__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vss       src__0002    aggr1        online     RW         25TB    10.86TB   56%
vss       src__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vss       src__0004    aggr1        online     RW         25TB    10.73TB   57%
vss       src__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vss       src__0006    aggr1        online     RW         25TB    10.64TB   57%
vss       src__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----
.. Erstellen Sie aus dem Ziel-Cluster ein FlexGroup Ziel-Volume vom Typ `DP` Wählen Sie für das FlexGroup Quell-Volume die gleiche Anzahl von Komponenten aus.
+
[listing]
----
cluster2::> volume create -vserver vsd -aggr-list aggr1,aggr2 -aggr-list-multiplier 8 -size 400TB -type DP dst

Warning: The FlexGroup volume "dst" will be created with the following number of constituents of size 25TB: 16.
Do you want to continue? {y|n}: y
[Job 766] Job succeeded: Successful
----
.. Überprüfen Sie aus dem Ziel-Cluster die Anzahl der Komponenten im FlexGroup Ziel-Volume: `volume show -volume volume_name* -is-constituent true`
+
[listing]
----
cluster2::> volume show  -volume dst* -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vsd       dst          -            online     RW         400TB   172.86GB  56%
vsd       dst__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vsd       dst__0002    aggr1        online     RW         25TB    10.86TB   56%
vsd       dst__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vsd       dst__0004    aggr1        online     RW         25TB    10.73TB   57%
vsd       dst__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vsd       dst__0006    aggr1        online     RW         25TB    10.64TB   57%
vsd       dst__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----


. Job-Zeitplan erstellen: `job schedule cron create -name job_name -month month -dayofweek day_of_week -day day_of_month -hour hour -minute minute`
+
Für `-month`, `-dayofweek`, und `-hour`, Sie können angeben `all` Zum Ausführen des Jobs jeden Monat, Wochentag und Stunde.

+
Im folgenden Beispiel wird ein Job-Zeitplan mit dem Namen erstellt `my_weekly` Das läuft samstags um 3:00 Uhr:

+
[listing]
----
cluster1::> job schedule cron create -name my_weekly -dayofweek "Saturday" -hour 3 -minute 0
----
. Erstellen Sie eine SnapVault-Richtlinie, und definieren Sie dann eine Regel für die SnapVault-Richtlinie:
+
.. Erstellen Sie eine benutzerdefinierte Typrichtlinie `vault` Für die SnapVault Beziehung: `snapmirror policy create -vserver svm_name -policy policy_name -type vault`
.. Definieren einer Regel für die SnapVault-Richtlinie, die bestimmt, welche Snapshot-Kopien während der Initialisierung und Aktualisierung übertragen werden: `snapmirror policy add-rule -vserver svm_name -policy policy_for_rule - snapmirror-label snapmirror-label -keep retention_count -schedule schedule`


+
Wenn Sie keine benutzerdefinierte Richtlinie erstellen, sollten Sie die angeben `XDPDefault` Richtlinie für SnapVault-Beziehungen.

. SnapVault Beziehung erstellen: `snapmirror create -source-path src_svm:src_flexgroup -destination-path dest_svm:dest_flexgroup -type XDP -schedule schedule_name -policy XDPDefault`
+
Wenn die Richtlinie in ONTAP 9.4 und früheren Versionen nicht mit angegeben wurde `snapmirror create` Befehl, das `MirrorAllSnapshots` Richtlinie wird standardmäßig verwendet. Wenn in ONTAP 9.5 die Richtlinie nicht mit dem angegeben ist `snapmirror create` Befehl, das `MirrorAndVault` Richtlinie wird standardmäßig verwendet.

+
[listing]
----
cluster2::> snapmirror create -source-path vss:srcFG -destination-path vsd:dstFG -type XDP -schedule Daily -policy XDPDefault
----
. Initialisieren Sie die SnapVault-Beziehung vom Ziel-Cluster, indem Sie einen Basistransfer durchführen: `snapmirror initialize -destination-path dest_svm:dest_flexgroup`
+
[listing]
----
cluster2::> snapmirror initialize -destination-path vsd:dst
Operation is queued: snapmirror initialize of destination "vsd:dst".
----

