---
permalink: flexgroup/increase-capacity-task.html 
sidebar: sidebar 
keywords: increase, size, flexgroup, volume, flex group 
summary: Die Größe des FlexGroup Volumens kann erhöht werden, indem mehr Kapazität zu den bestehenden Bestandteilen des Volumens hinzugefügt oder das FlexGroup Volumen durch neue Mitgliedsvolumina erweitert wird. 
---
= Die Größe von ONTAP FlexGroup Volumes erhöhen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Größe eines FlexGroup Volumes kann entweder durch Hinzufügen von mehr Kapazität zu allen bestehenden Mitgliedsvolumes (Bestandteilen) des FlexGroup Volumes oder durch Erweiterung des FlexGroup Volumes mit neuen Mitgliedsvolumes erhöht werden. Ein FlexGroup Volume kann nicht mehr als 200 Mitgliedsvolumes haben.

Sie können bei Bedarf auch die Größe eines einzelnen Volumens innerhalb eines FlexGroup Volumens erhöhen.

.Bevor Sie beginnen
In den Aggregaten muss ausreichend Platz vorhanden sein.

.Über diese Aufgabe
Wenn mehr Speicherplatz benötigt wird, kann die Gesamtgröße des FlexGroup Volumes erhöht werden. Die Vergrößerung eines FlexGroup Volumes passt die vorhandenen Teilvolumes des FlexGroup Volumes an.

Wenn Sie die Performance verbessern möchten, kann das FlexGroup Volume erweitert werden. Eine Erweiterung eines FlexGroup Volumes und das Hinzufügen neuer Mitgliedsvolumes kann in folgenden Situationen sinnvoll sein:

* Dem Cluster wurden neue Knoten hinzugefügt.
* Neue lokale Ebenen (Aggregate) wurden auf den bestehenden Knoten erstellt.
* Die vorhandenen Mitgliedsvolumes des FlexGroup Volumes haben die maximale FlexVol Größe für die Hardware erreicht (100TB oder 300TB, wenn link:../volumes/enable-large-vol-file-support-task.html["Unterstützung großer Volumen"] aktiviert wurde), und daher kann das FlexGroup Volume nicht vergrößert werden, ohne zusätzliche Mitgliedsvolumes hinzuzufügen.


[NOTE]
====
Wenn ein FlexGroup Volume so geändert wird, dass es mehr Mitglieder enthält, gelten zuvor erstellte Snapshots als „partiell“ und sind für Clients nur über das  `.snapshot` Verzeichnis oder die Registerkarte *Vorherige Versionen* verfügbar.

Wird ein Snapshot als „partiell“ eingestuft, kann er nicht für SnapRestore Operationen verwendet werden. Partielle Snapshots können jedoch genutzt werden, um einzelne Dateien aus  `.snapshot` Verzeichnissen oder der Registerkarte „Vorherige Versionen“ wiederherzustellen.

====
In Versionen vor ONTAP 9.3 sollten FlexGroup Volumes nach dem Einrichten einer SnapMirror Beziehung nicht erweitert werden. Wenn das Quell-FlexGroup Volume nach dem Aufheben der SnapMirror Beziehung in Versionen vor ONTAP 9.3 erweitert wird, ist ein Basistransfer auf das Ziel-FlexGroup Volume erneut erforderlich. Ab ONTAP 9.3 können FlexGroup Volumes, die sich in einer SnapMirror Beziehung befinden, erweitert werden.

.Schritte
. Die Größe des FlexGroup Volumes kann durch Erhöhung der Kapazität oder Leistung des FlexGroup Volumes nach Bedarf vergrößert werden:
+
|===


| Wenn Sie die... erhöhen möchten | Fahren Sie dann wie folgt fort... 


 a| 
Kapazität des FlexGroup Volumens
 a| 
Alle Mitgliedsvolumes des FlexGroup Volumes in der Größe anpassen:

`volume modify -vserver <svm_name> -volume <fg_name> -size <new_size>`



 a| 
Leistung für das FlexGroup volume
 a| 
Erweitern Sie das FlexGroup Volume durch das Hinzufügen neuer Mitgliedsvolumes (Bestandteile):

`+volume expand -vserver vserver_name -volume fg_name -aggr-list aggregate name,... [-aggr-list-multiplier constituents_per_aggr]+`

Der Standardwert des  `-aggr-list-multiplier` Parameters ist 1.

Bei der Erweiterung eines FlexGroup Volumes mit link:../fabricpool/index.html["FabricPool"] müssen alle lokalen Ebenen (Aggregate) an dieselbe Cloud-Ebene angehängt werden.

|===


Sofern die bestehenden Aggregate (lokale Ebenen) oder Mitgliedsvolumes ihre maximale Kapazität (100/300TB oder zwei Milliarden Dateien pro Volume) noch nicht erreicht haben, ist es vorzuziehen, die Gesamtgröße des FlexGroup Volumes zu erhöhen, anstatt zusätzliche Mitgliedsvolumes hinzuzufügen.

Die Volumenerweiterung sollte nur verwendet werden, wenn eine Erhöhung der vorhandenen Volumengröße oder der Dateianzahl nicht möglich ist oder wenn die FlexGroup über neue Hardware erweitert wird. Allen Knoten sollte die gleiche Anzahl an Mitgliedsvolumes hinzugefügt werden, um eine konsistente Leistung sicherzustellen. Beispielsweise führt das Hinzufügen von zwei Mitgliedsvolumes pro Knoten zu einem vorhandenen FlexGroup volume mit acht Mitgliedsvolumes und vier Mitgliedsvolumes pro Knoten zu insgesamt zwölf Mitgliedsvolumes, also sechs Mitgliedsvolumes pro Knoten.

Beim Hinzufügen neuer Mitglieder zu neuen Knoten sollte die Anzahl der Mitgliedsvolumes pro Knoten möglichst gleich bleiben wie bei den bestehenden Knoten. Wenn beispielsweise ein bestehendes FlexGroup Volume 8 Mitgliedsvolumes mit jeweils vier Mitgliedsvolumes pro Knoten umfasst, und das FlexGroup Volume auf den neuen Knoten erweitert wird, sollten vier weitere Mitgliedsvolumes hinzugefügt werden, sodass ein FlexGroup Volume mit insgesamt 12 Mitgliedsvolumes entsteht.

Das Hinzufügen neuer Mitglieder zu einem FlexGroup volume ändert die Aufnahmeheuristiken, um die neuen, leeren Mitgliedsvolumes zu bevorzugen, und kann die Gesamtleistung des Systems bei der Aufnahme neuer Daten beeinträchtigen, bis die neuen Mitgliedsvolumes mit den bereits vorhandenen Mitgliedsvolumes im Gleichgewicht sind.

.Beispiele
*Beispiel für die Erhöhung der Kapazität der bestehenden Mitgliedsvolumina*

Das folgende Beispiel zeigt, wie 20 TB Speicherplatz zu einem FlexGroup Volume volX hinzugefügt werden:

[listing]
----
cluster1::> volume modify -vserver svm1 -volume volX -size +20TB
----
Wenn das FlexGroup volume 16 Mitgliedsvolumes hat, wird der Speicherplatz jedes Mitgliedsvolumes um 1,25 TB erhöht.

*Beispiel für die Verbesserung der Performance durch Hinzufügen neuer Mitgliedsvolumes*

Das folgende Beispiel zeigt, wie vier zusätzliche Mitgliedsvolumes zu dem FlexGroup volume hinzugefügt werden, jeweils zwei zu jeder der zugrunde liegenden lokalen Ebenen (Aggregaten)  `fg1`:

[listing]
----
cluster1::> volume expand -vserver svm1 -volume fg1 -aggr-list aggr1,aggr2 -aggr-list-multiplier 2
----
Die Größe der neuen Mitgliedsvolumes entspricht der der bestehenden Mitgliedsvolumes.

.Die Größe eines einzelnen Volumes erhöhen
Wenn Sie die Größe eines einzelnen Mitgliedsvolumes in einem FlexGroup Volume erhöhen möchten, kann der  `volume resize` Befehl verwendet werden.

.Schritt
. Die Größe eines einzelnen FlexGroup Member-Volumes erhöhen:
+
`volume size -volume <volume_name> -vserver <svm1> -new-size <new_size>`

+
Das folgende Beispiel erhöht die Größe des FlexGroup Mitgliedsvolumes FG_0003 auf 3,7GB:

+
[listing]
----
volume size -volume FG__0003 -vserver svm1 -new-size 3.7GB
vol size: Volume "svm1:FG__0003" size set to 3.70g.
----

