---
permalink: flexgroup/increase-capacity-task.html 
sidebar: sidebar 
keywords: increase, size, flexgroup, volume, flex group 
summary: Ein FlexGroup Volume lässt sich vergrößern, indem entweder die vorhandenen Komponenten des FlexGroup Volume um mehr Kapazität erweitert oder das FlexGroup Volume um neue Mitglied-Volumes erweitert wird. 
---
= Vergrößern Sie ONTAP FlexGroup Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein FlexGroup Volume kann vergrößert werden, indem entweder mehr Kapazität zu den vorhandenen Mitglieds-Volumes (Komponenten) des FlexGroup Volume hinzugefügt oder das FlexGroup Volume um neue Mitglied-Volumes erweitert wird. Ein FlexGroup-Volume darf nicht mehr als 200 Mitglieds-Volumes enthalten.

.Bevor Sie beginnen
In den Aggregaten muss ausreichend Platz vorhanden sein.

.Über diese Aufgabe
Falls Sie mehr Speicherplatz hinzufügen möchten, können Sie die kollektive Größe des FlexGroup Volume erhöhen. Wenn Sie die Größe eines FlexGroup Volumes erhöhen, werden die vorhandenen Mitglied-Volumes des FlexGroup Volume angepasst.

Wenn Sie die Performance verbessern möchten, können Sie das FlexGroup Volume erweitern. In den folgenden Situationen können Sie ein FlexGroup-Volume erweitern und neue Member-Volumes hinzufügen:

* Dem Cluster wurden neue Nodes hinzugefügt.
* Auf den vorhandenen Nodes wurden neue lokale Tiers (Aggregate) erstellt.
* Die bestehenden Mitglied-Volumes des FlexGroup Volume haben die maximale FlexVol-Größe für die Hardware erreicht (100 TB oder 300 TB, falls link:../volumes/enable-large-vol-file-support-task.html["Unterstützung für große Volumes"]aktiviert). Daher kann die Größe des FlexGroup Volume nicht ohne Hinzufügen weiterer Mitglied-Volumes geändert werden.


In Versionen vor ONTAP 9.3 sollten FlexGroup Volumes nicht erweitert werden, nachdem eine SnapMirror Beziehung hergestellt wurde. Wenn Sie das FlexGroup-Quell-Volume erweitern, nachdem Sie die SnapMirror Beziehung in Versionen vor ONTAP 9.3 unterbrochen haben, müssen Sie erneut einen Basistransfer zum Ziel-FlexGroup-Volume durchführen. Ab ONTAP 9.3 können Sie die FlexGroup Volumes in einer SnapMirror Beziehung erweitern.

.Schritt
. Vergrößern Sie das FlexGroup Volume, indem Sie bei Bedarf die Kapazität oder Performance des FlexGroup Volume erhöhen:
+
|===


| Wenn Sie die... | Dann tun Sie das... 


 a| 
Kapazität des FlexGroup Volume
 a| 
Redimensionierung der Member Volumes des FlexGroup Volume:

`volume modify -vserver vserver_name -volume fg_name -size new_size`



 a| 
Performance für das FlexGroup Volume zu steigern
 a| 
Erweitern Sie das FlexGroup Volume durch Hinzufügen neuer Member Volumes (Komponenten):

`+volume expand -vserver vserver_name -volume fg_name -aggr-list aggregate name,... [-aggr-list-multiplier constituents_per_aggr]+`

Der Standardwert des `-aggr-list-multiplier` Parameters ist 1.

Bei der Erweiterung eines FlexGroup Volumes mit link:../fabricpool/index.html["FabricPool"]müssen alle lokalen Tiers (Aggregate) an denselben Cloud-Tier angebunden werden.

|===


Wenn bestehende Aggregate (lokale Tiers) oder Mitglied-Volumes ihre maximale Kapazität nicht erreicht haben (100 TB oder zwei Milliarden Dateien jeweils), ist es vorzuziehen, die Gesamtgröße des FlexGroup Volumes zu erhöhen, anstatt zusätzliche Mitglied-Volumes hinzuzufügen.

Verwenden Sie die Volume-Erweiterung nur, wenn Sie keine Möglichkeit haben, die vorhandene Volume-Größe oder die Anzahl der Dateien zu erhöhen, oder wenn die FlexGroup auf neue Hardware erweitert wird. Um eine konsistente Leistung zu gewährleisten, muss allen Knoten die gleiche Anzahl an Mitgliedsvolumes hinzugefügt werden. Wenn ein vorhandenes FlexGroup-Volume beispielsweise 8 Mitglied-Volumes mit vier Mitglied-Volumes pro Node enthält, führt das Hinzufügen von zwei Mitgliedern pro Node zu 12 Mitglied-Volumes, sechs Mitglied-Volumes pro Node.

Wenn Sie neue Mitglieder zu neuen Nodes hinzufügen, versuchen Sie, eine konsistente Anzahl von Mitglieds-Volumes pro Node wie in den vorhandenen Nodes beizubehalten. Wenn ein vorhandenes FlexGroup-Volume beispielsweise 8 Member Volumes mit vier Member Volumes pro Node enthält, müssen bei Erweiterung der FlexGroup-Volumes auf den neuen Node vier Member Volumes hinzugefügt werden, was zu einem FlexGroup-Volume mit 12 Mitgliedern führt.

Das Hinzufügen neuer Mitglieder zu einem FlexGroup-Volume ändert die Ingest Heuristics, um die neuen, leeren Mitgliedervolumes zu bevorzugen und kann die Gesamtsystemleistung für neue Dateneinspeisung beeinflussen, bis die neuen Mitgliedervolumes mit bereits vorhandenen Mitgliedervolumes ausgeglichen werden.

.Beispiele
*Beispiel für die Erhöhung der Kapazität der bestehenden Mitgliedervolumes*

Das folgende Beispiel zeigt, wie man einem FlexGroup-Volume Volx 20 TB Speicherplatz hinzufügt:

[listing]
----
cluster1::> volume modify -vserver svm1 -volume volX -size +20TB
----
Wenn das FlexGroup-Volume 16 Mitglied-Volumes enthält, wird der Speicherplatz jedes Mitglieds-Volumes um 1.25 TB erhöht.

*Beispiel für die Verbesserung der Performance durch Hinzufügen neuer Mitgliedervolumes*

Im folgenden Beispiel wird gezeigt, wie vier zusätzliche Mitglied-Volumes hinzugefügt werden, zwei zu jedem der zugrunde liegenden lokalen Tiers (Aggregate) zum FlexGroup-Volume fg1:

[listing]
----
cluster1::> volume expand -vserver svm1 -volume fg1 -aggr-list aggr1,aggr2 -aggr-list-multiplier 2
----
Die Größe der neuen Mitgliedervolumes entspricht der der vorhandenen Mitgliedervolumes.
