---
permalink: flexgroup/monitor-snapmirror-data-transfers-task.html 
sidebar: sidebar 
keywords: monitor, snapmirror, data, transfer, flexgroup, volumes 
summary: Sie sollten regelmäßig den Status der FlexGroup Volume SnapMirror Beziehungen überwachen, um zu überprüfen, ob das Ziel-FlexGroup-Volume gemäß dem angegebenen Zeitplan regelmäßig aktualisiert wird. 
---
= Monitoring der SnapMirror Datentransfers für FlexGroup Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten regelmäßig den Status der FlexGroup Volume SnapMirror Beziehungen überwachen, um zu überprüfen, ob das Ziel-FlexGroup-Volume gemäß dem angegebenen Zeitplan regelmäßig aktualisiert wird.

.Über diese Aufgabe
Sie müssen diese Aufgabe vom Ziel-Cluster aus ausführen.

.Schritte
. SnapMirror Beziehungsstatus aller FlexGroup Volume-Beziehungen anzeigen: `snapmirror show -relationship-group-type flexgroup`
+
[listing]
----
cluster2::> snapmirror show -relationship-group-type flexgroup
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vss:s       XDP  vsd:d        Snapmirrored
                                      Idle           -         true    -
vss:s2      XDP  vsd:d2       Uninitialized
                                      Idle           -         true    -
2 entries were displayed.
----
. Sehen Sie sich den SnapMirror Beziehungsstatus für jede Komponente im FlexGroup Volume an: `snapmirror show -expand`
+
[listing]
----
cluster2::> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vss:s       XDP  vsd:d        Snapmirrored
                                      Idle           -         true    -
vss:s__0001 XDP  vsd:d__0001  Snapmirrored
                                      Idle           -         true    -
vss:s__0002 XDP  vsd:d__0002  Snapmirrored
                                      Idle           -         true    -
vss:s__0003 XDP  vsd:d__0003  Snapmirrored
                                      Idle           -         true    -
vss:s__0004 XDP  vsd:d__0004  Snapmirrored
                                      Idle           -         true    -
vss:s__0005 XDP  vsd:d__0005  Snapmirrored
                                      Idle           -         true    -
vss:s__0006 XDP  vsd:d__0006  Snapmirrored
                                      Idle           -         true    -
vss:s__0007 XDP  vsd:d__0007  Snapmirrored
                                      Idle           -         true    -
vss:s__0008 XDP  vsd:d__0008  Snapmirrored
                                      Idle           -         true    -
...
----
. Wenn die SnapMirror Übertragung fehlschlägt, identifizieren Sie die FlexGroup Volume-Komponente, für die der Transfer fehlgeschlagen ist, und geben Sie den Grund für die Fehlermeldung an: `snapmirror show -fields last-transfer-error -expand`
+
[listing]
----
cluster2::> snapmirror show -fields last-transfer-error -expand
source-path destination-path last-transfer-error
----------- ---------------- -----------------------------------------------
vss:s       vsd:d            Group Update failed (Failed to complete update operation on one or more item relationships.)
vss:s__0001 vsd:d__0001      -
vss:s__0002 vsd:d__0002      -
vss:s__0003 vsd:d__0003      Failed to get information for source volume "vss:s__0003" for setup of transfer. (Failed to get volume attributes for e2de028c-8049-11e6-96ea-005056851ca2:s__0003. (Volume is offline))
vss:s__0004 vsd:d__0004      -
vss:s__0005 vsd:d__0005      -
vss:s__0006 vsd:d__0006      -
vss:s__0007 vsd:d__0007      -
vss:s__0008 vsd:d__0008      -
9 entries were displayed.
----
+
Nach der Behebung des Problems müssen Sie den SnapMirror Vorgang erneut ausführen.


