---
permalink: flexgroup/provision-automatically-task.html 
sidebar: sidebar 
keywords: provision, flexgroup, volume, automatic, create, flex group, aggregate, space 
summary: 'Beim Erstellen eines FlexGroup Volumes können Sie festlegen, dass ONTAP das FlexGroup Volume durch automatische Auswahl der lokalen Ebenen (Aggregate) bereitstellt. Die Auswahl der lokalen Ebenen erfolgt auf Basis bewährter Verfahren für optimale Leistung.' 
---
= Automatische Bereitstellung eines ONTAP FlexGroup Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Beim Erstellen eines FlexGroup Volumes kann ONTAP das FlexGroup Volume automatisch bereitstellen, indem die zugrunde liegenden lokalen Tiers (Aggregate) ausgewählt werden. Lokale Tiers werden auf Grundlage von Best Practices für optimale Leistung und Kapazität ausgewählt.

.Bevor Sie beginnen
Jeder Knoten im Cluster muss mindestens eine lokale Ebene haben.

[NOTE]
====
Beim Erstellen eines FlexGroup Volumes, das inaktive Daten auf eine andere Ebene verschiebt, muss jeder Knoten mindestens eine lokale Ebene mit aktiviertem FabricPool haben.

====
.Über diese Aufgabe
ONTAP wählt auf jedem Knoten zwei lokale Speicherebenen mit dem größten verfügbaren Speicherplatz aus, um das FlexGroup volume zu erstellen. Wenn zwei lokale Speicherebenen nicht verfügbar sind, wählt ONTAP pro Knoten eine lokale Speicherebene aus, um das FlexGroup volume zu erstellen.

Ab ONTAP 9.15.1 wird bei der automatischen Bereitstellung eines FlexGroup Volumes Balanced Placement (BP) von ONTAP verwendet, um die lokalen Tiers und das Layout der FlexGroup Mitglieds- (Konstituenten-) Volumes auszuwählen. Ein Aspekt von BP ist, wie die Überbereitstellung lokaler Tiers beim Erstellen von FlexGroup Volumes mit „Keine Garantie“ (thin-provisioned) begrenzt wird. Die Größe des gesamten FlexGroup Volumes ist durch den freien Speicherplatz auf dem lokalen Tier begrenzt, wobei dieses Limit höher ist als bei FlexGroup Volumes mit „Volume-Garantie“ (thick-provisioned). Wenn ein FlexGroup Volume mithilfe von REST-APIs oder  `auto-provision-as` mit der ONTAP CLI erstellt wird, kann die Bereitstellung aufgrund dieses Limits wegen unzureichenden Speicherplatzes fehlschlagen. Dies kann vermieden werden, indem kleinere FlexGroup Volumes erstellt oder link:create-task.html["Erstellung eines FlexGroup Volume und manuelle Auswahl der lokalen Tiers"] der  `aggr-list` Parameter verwendet wird.

.Schritte
. Das FlexGroup Volume bereitstellen:
+
`volume create -vserver svm_name -volume fg_vol_name –auto-provision-as flexgroup -size fg_size [–encrypt true] [-qos-policy-group qos_policy_group_name] [-support-tiering true] [-granular-data advanced]`

+
Ab ONTAP 9.16.1 kann link:enable-adv-capacity-flexgroup-task.html["fortschrittlicher Kapazitätsausgleich"] (`-granular-data advanced` in der CLI aktiviert werden, um Daten über mehrere FlexGroup Member-Volumes zu schreiben, wenn Dateien größer als 10 GB sind.

+
Ab ONTAP 9.5 können FlexGroup Volumes auf lokalen Tiers mit aktiviertem FabricPool erstellt werden. Um ein FlexGroup Volume auf lokalen Tiers mit aktiviertem FabricPool automatisch bereitzustellen, muss der  `-support-tiering` Parameter auf  `true` gesetzt werden. Die Volume-Garantie muss für FabricPool immer auf  `none` gesetzt werden. Es kann außerdem die Tiering-Policy und die minimale Tiering-Abkühlperiode für das FlexGroup Volume angegeben werden.

+
link:../disks-aggregates/index.html["Festplatten- und Aggregatverwaltung"]

+
Sie können eine Durchsatzobergrenze (QoS Max) für FlexGroup Volumes festlegen. Dies begrenzt die Leistungsressourcen, die das FlexGroup Volume nutzen kann. Ab ONTAP 9.4 können Durchsatzuntergrenzen (QoS Min) und adaptives QoS für FlexGroup Volumes festgelegt werden.

+
link:../performance-admin/index.html["Leistungsmanagement"]

+
Sie können den  `-encrypt` Parameter auf  `true` setzen, wenn Sie die Verschlüsselung auf dem FlexGroup volume aktivieren möchten. Für das Erstellen eines verschlüsselten Volumes müssen die Volume Encryption-Lizenz und der Key Manager installiert sein.

+

NOTE: Die Verschlüsselung auf FlexGroup Volumes muss zum Zeitpunkt der Erstellung aktiviert werden. Die Verschlüsselung kann auf bestehenden FlexGroup Volumes nicht aktiviert werden.

+
link:../encryption-at-rest/index.html["Verschlüsselung von Daten im Ruhezustand"]

+
Der  `size` Parameter gibt die Größe des FlexGroup Volumes in KB, MB, GB, TB oder PB an.

+
Das folgende Beispiel zeigt, wie ein FlexGroup volume mit einer Größe von 400 TB bereitgestellt wird:

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
Das folgende Beispiel zeigt, wie eine QoS-Richtliniengruppe für die Durchsatzbegrenzung erstellt wird und wie sie auf ein FlexGroup volume angewendet wird:

+
[listing]
----
cluster1::> qos policy-group create -policy group pg-vs1 -vserver vs1 -max-throughput 5000iops
----
+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -qos-policy-group pg-vs1
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
Das folgende Beispiel zeigt, wie ein FlexGroup volume mit einer Größe von 400 TB auf lokalen Ebenen mit aktivierter FabricPool Option bereitgestellt wird:

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -support-tiering true -tiering-policy auto
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
Das FlexGroup volume wird mit acht Mitgliedsvolumes auf jedem Knoten im Cluster erstellt. Die Mitgliedsvolumes werden gleichmäßig auf die beiden größten lokalen Tiers auf jedem Knoten verteilt.

+
Standardmäßig wird das FlexGroup Volume mit der  `volume` Speicherplatzzusage erstellt, außer auf AFF Systemen. Für AFF Systeme wird das FlexGroup Volume standardmäßig mit der  `none` Speicherplatzzusage erstellt.

. Das FlexGroup Volume mit einem Verbindungspfad einbinden:
+
`volume mount -vserver vserver_name -volume vol_name -junction-path junction_path`

+
[listing]
----
cluster1::> volume mount -vserver vs0 -volume fg2 -junction-path /fg2
----


.Nachdem Sie fertig sind
Das FlexGroup Volume sollte vom Client aus eingebunden werden.

Wenn ONTAP 9.6 oder eine frühere Version verwendet wird und die Storage Virtual Machine (SVM) sowohl NFSv3 als auch NFSv4 konfiguriert hat, kann das Einbinden des FlexGroup Volumes vom Client fehlschlagen. In solchen Fällen muss die NFS-Version beim Einbinden des FlexGroup Volumes vom Client explizit angegeben werden.

[listing]
----
# mount -t nfs -o vers=3 192.53.19.64:/fg2 /mnt/fg2
# ls /mnt/fg2
file1  file2
----
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/qos-policy-group-create.html["qos policy-group create"^]

