---
permalink: flexgroup/provision-automatically-task.html 
sidebar: sidebar 
keywords: provision, flexgroup, volume, automatic, create, flex group, aggregate, space 
summary: 'Wenn Sie ein FlexGroup Volume erstellen, können Sie ONTAP das FlexGroup Volume bereitstellen lassen, indem Sie automatisch die lokalen Tiers (Aggregate) auswählen. Die Auswahl der lokalen Stufen erfolgt anhand der Best Practices für eine optimale Leistung.' 
---
= Automatische Bereitstellung eines ONTAP FlexGroup Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Erstellung eines FlexGroup Volume besteht die Wahl zwischen der automatischen Bereitstellung des FlexGroup Volume durch ONTAP durch Auswahl der zugrunde liegenden lokalen Tiers (Aggregate). Die Auswahl der lokalen Tiers erfolgt anhand der Best Practices für optimale Performance und Kapazität.

.Bevor Sie beginnen
Jeder Node im Cluster muss über mindestens eine lokale Tier verfügen.

[NOTE]
====
Wenn ein FlexGroup-Volume erstellt wird, auf dem inaktive Daten verschoben werden, muss für jeden Node mindestens eine lokale Tier mit aktiviertem FabricPool vorhanden sein.

====
.Über diese Aufgabe
ONTAP wählt zwei lokale Tiers mit der größten Menge an nutzbarem Speicherplatz auf jedem Node aus, um das FlexGroup Volume zu erstellen. Wenn nicht zwei lokale Tiers verfügbar sind, wählt ONTAP eine lokale Tier pro Node aus, um das FlexGroup Volume zu erstellen.

Ab ONTAP 9.15.1 verwendet ONTAP bei der automatischen Bereitstellung eines FlexGroup Volume die optimierte Platzierung (BP) zur Auswahl der lokalen Tiers und des Layouts der FlexGroup Member (konstituierenden) Volumes. Ein Aspekt von BP ist, wie es die Überdimensionierung lokaler Tiers beim Erstellen von „keinen“ garantierten (Thin-Provisioning) FlexGroup-Volumes beschränkt. Die Größe des gesamten FlexGroup-Volumes wird durch den freien Speicherplatz auf der lokalen Tier begrenzt, obwohl das Limit höher ist als bei mit „Volume“ garantierten (Thick Provisioning) FlexGroup-Volumes. Wenn Sie ein FlexGroup-Volume mit REST-APIs oder mit der ONTAP-CLI erstellen `auto-provision-as` , kann die Bereitstellung aufgrund dieser Beschränkung fehlschlagen, weil der Speicherplatz nicht ausreicht. Dies kann durch das Erstellen kleinerer FlexGroup Volumes oder mit dem Parameter vermieden link:create-task.html["Erstellen eines FlexGroup-Volumes und manuelle Auswahl der lokalen Tiers"] `aggr-list` werden.

.Schritte
. Bereitstellen des FlexGroup Volume:
+
`volume create -vserver svm_name -volume fg_vol_name –auto-provision-as flexgroup -size fg_size [–encrypt true] [-qos-policy-group qos_policy_group_name] [-support-tiering true] [-granular-data advanced]`

+
Ab ONTAP 9.16.1 können Sie  (`-granular-data advanced`in der CLI aktivierenlink:../enable-adv-capacity-flexgroup-task.html["Erweiterter Kapazitätsausgleich"]), um Daten über mehrere FlexGroup Member Volumes zu schreiben, wenn Dateien größer als 10 GB sind.

+
Ab ONTAP 9.5 können Sie FlexGroup Volumes auf lokalen Tiers mit aktivierter FabricPool erstellen. Um ein FlexGroup-Volume automatisch auf lokalen Tiers mit aktiviertem FabricPool bereitzustellen, müssen Sie den Parameter auf `true` einstellen `-support-tiering`.  `none`Für FabricPool muss die Volumengarantie immer auf festgelegt sein. Sie können auch die Tiering-Richtlinie und den minimalen Kühlzeitraum für das FlexGroup Volume festlegen.

+
link:../disks-aggregates/index.html["Festplatten- und Aggregatmanagement"]

+
Sie können eine Durchsatzobergrenze (max. QoS) für FlexGroup Volumes angeben. Dies schränkt die Performance-Ressourcen ein, die das FlexGroup Volume verbrauchen kann. Ab ONTAP 9.4 können Sie Durchsatzböden (QoS Min.) und anpassungsfähige QoS für FlexGroup Volumes festlegen.

+
link:../performance-admin/index.html["Performance Management"]

+
Sie können den Parameter auf festlegen `-encrypt`, wenn Sie die Verschlüsselung auf `true` dem FlexGroup Volume aktivieren möchten. Zum Erstellen eines verschlüsselten Volumes müssen Sie die Lizenz für die Volume-Verschlüsselung und den Schlüsselmanager installiert haben.

+

NOTE: Sie müssen die Verschlüsselung auf FlexGroup Volumes während der Erstellung aktivieren. Sie können die Verschlüsselung auf vorhandenen FlexGroup Volumes nicht aktivieren.

+
link:../encryption-at-rest/index.html["Verschlüsselung von Daten im Ruhezustand"]

+
Der `size` Parameter gibt die Größe des FlexGroup-Volumes in KB, MB, GB, TB oder PB an.

+
Im folgenden Beispiel wird gezeigt, wie ein FlexGroup Volume mit einer Größe von 400 TB bereitgestellt wird:

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
Das folgende Beispiel zeigt, wie eine QoS-Richtliniengruppe für eine Durchsatzobergrenze erstellt und wie sie auf ein FlexGroup Volume angewendet wird:

+
[listing]
----
cluster1::> qos policy-group create -policy group pg-vs1 -vserver vs1 -max-throughput 5000iops
----
+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -qos-policy-group pg-vs1
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
Im folgenden Beispiel wird gezeigt, wie ein FlexGroup Volume mit der Größe 400 TB auf lokalen Tiers mit aktiviertem FabricPool bereitgestellt wird:

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -support-tiering true -tiering-policy auto
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
Das FlexGroup Volume wird mit acht Member Volumes auf jedem Node im Cluster erstellt. Die Mitgliedervolumes werden gleichmäßig auf die beiden größten lokalen Tiers auf jedem Node verteilt.

+
Standardmäßig wird das FlexGroup Volume mit der `volume` Einstellung für Speicherplatzzusagen erstellt, ausgenommen bei AFF Systemen. Bei AFF Systemen wird das FlexGroup-Volume standardmäßig mit der `none` Platzgarantie erstellt.

. Mounten Sie das FlexGroup Volume mit einem Verbindungspfad:
+
`volume mount -vserver vserver_name -volume vol_name -junction-path junction_path`

+
[listing]
----
cluster1::> volume mount -vserver vs0 -volume fg2 -junction-path /fg2
----


.Nachdem Sie fertig sind
Sie sollten das FlexGroup-Volume vom Client mounten.

Wenn Sie ONTAP 9.6 oder früher ausführen und wenn die Storage Virtual Machine (SVM) sowohl NFSv3 als auch NFSv4 konfiguriert ist, kann das Mounten des FlexGroup Volumes vom Client fehlschlagen. In diesen Fällen müssen Sie beim Mounten des FlexGroup-Volume vom Client explizit die NFS-Version angeben.

[listing]
----
# mount -t nfs -o vers=3 192.53.19.64:/fg2 /mnt/fg2
# ls /mnt/fg2
file1  file2
----