---
permalink: flexgroup/reactivate-original-source-after-disaster-task.html 
sidebar: sidebar 
keywords: reactivate, original, source, flexgroup, volume, disaster 
summary: Wenn das FlexGroup Volume wieder verfügbar ist, kann das ursprüngliche Quell- und das ursprüngliche Ziel-FlexGroup Volume erneut synchronisiert werden. Alle neuen Daten auf dem Ziel-FlexGroup Volume gehen verloren. 
---
= Das ursprüngliche ONTAP FlexGroup Quellvolume nach einem Desaster wieder aktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn das FlexGroup Volume wieder verfügbar ist, kann das ursprüngliche Quell- und das ursprüngliche Ziel-FlexGroup Volume erneut synchronisiert werden. Alle neuen Daten auf dem Ziel-FlexGroup Volume gehen verloren.

.Über diese Aufgabe
Alle aktiven Kontingentregeln auf dem Ziel-Volume werden deaktiviert und die Kontingentregeln werden vor der Resynchronisierung gelöscht.

Sie können die  `volume quota policy rule create`- und  `volume quota modify`-Befehle verwenden, um Kontingentregeln nach Abschluss der Resynchronisierung zu erstellen und zu reaktivieren.

.Schritte
. Vom Ziel-Cluster aus die FlexGroup Volume SnapMirror Beziehung neu synchronisieren: `snapmirror resync -destination-path dst_svm:dest_flexgroup`
. Status der SnapMirror Beziehung anzeigen: `snapmirror show -expand`
+
[listing]
----
cluster2::> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vss:s       XDP  vsd:dst        Snapmirrored
                                      Idle           -         true    -
vss:s__0001 XDP  vsd:dst__0001  Snapmirrored
                                      Idle           -         true    -
vss:s__0002 XDP  vsd:dst__0002  Snapmirrored
                                      Idle           -         true    -
vss:s__0003 XDP  vsd:dst__0003  Snapmirrored
                                      Idle           -         true    -
vss:s__0004 XDP  vsd:dst__0004  Snapmirrored
                                      Idle           -         true    -
vss:s__0005 XDP  vsd:dst__0005  Snapmirrored
                                      Idle           -         true    -
vss:s__0006 XDP  vsd:dst__0006  Snapmirrored
                                      Idle           -         true    -
vss:s__0007 XDP  vsd:dst__0007  Snapmirrored
                                      Idle           -         true    -
vss:s__0008 XDP  vsd:dst__0008  Snapmirrored
                                      Idle           -         true    -
...
----
+
Der SnapMirror Beziehungsstatus jedes Bestandteils ist `Snapmirrored`.



.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["SnapMirror Resynchronisierung"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["snapmirror show"^]

