---
permalink: flexgroup/reverse-snapmirror-relationship-task.html 
sidebar: sidebar 
keywords: reverse, snapmirror, relation, flexgroup, volume, disaster, recovery 
summary: Wenn ein Ausfall das FlexGroup Volume des Quell-SnapMirror Beziehung deaktiviert, kann das Ziel-FlexGroup Volume zur Datenbereitstellung verwendet werden, während das Quell-FlexGroup Volume repariert oder ersetzt wird. Nachdem das Quell-FlexGroup Volume wieder online ist, kann das ursprüngliche Quell-FlexGroup Volume als schreibgeschütztes Ziel festgelegt und die SnapMirror Beziehung umgekehrt werden. 
---
= Umgekehrte SnapMirror Beziehungen zwischen ONTAP FlexGroup Volumes während der Notfallwiederherstellung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ein Ausfall das FlexGroup Volume des Quell-SnapMirror Beziehung deaktiviert, kann das Ziel-FlexGroup Volume zur Datenbereitstellung verwendet werden, während das Quell-FlexGroup Volume repariert oder ersetzt wird. Nachdem das Quell-FlexGroup Volume wieder online ist, kann das ursprüngliche Quell-FlexGroup Volume als schreibgeschütztes Ziel festgelegt und die SnapMirror Beziehung umgekehrt werden.

.Über diese Aufgabe
Alle aktiven Kontingentregeln auf dem Ziel-Volume werden deaktiviert und die Kontingentregeln werden vor der Resynchronisierung gelöscht.

Sie können die  `volume quota policy rule create`- und  `volume quota modify`-Befehle verwenden, um Kontingentregeln nach Abschluss der Resynchronisierung zu erstellen und zu reaktivieren.

.Schritte
. Auf dem ursprünglichen Ziel-FlexGroup-Volume die Datensicherungsspiegelbeziehung zwischen dem Quell-FlexGroup-Volume und dem Ziel-FlexGroup-Volume entfernen: `snapmirror delete -destination-path svm_name:volume_name`
+
[listing]
----
cluster2::> snapmirror delete -destination-path vsd:dst
----
. Entfernen Sie auf dem ursprünglichen Quell-FlexGroup-Volume die Beziehungsinformationen vom Quell-FlexGroup-Volume: `snapmirror release -destination-path svm_name:volume_name -relationship-info-only`
+
Nach dem Löschen einer SnapMirror Beziehung müssen die Beziehungsinformationen aus dem Quell-FlexGroup Volume entfernt werden, bevor ein Resynchronisierungsvorgang versucht wird.

+
[listing]
----
cluster1::> snapmirror release -destination-path vsd:dst -relationship-info-only true
----
. Auf dem neuen Ziel-FlexGroup Volume die Spiegelbeziehung erstellen: `snapmirror create -source-path src_svm_name:volume_name -destination-path dst_svm_name:volume_name -type XDP -policy MirrorAllSnapshots`
+
[listing]
----
cluster1::> snapmirror create -source-path vsd:dst -destination-path vss:src -type XDP -policy MirrorAllSnapshots
----
+
Weitere Informationen zu  `snapmirror create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["ONTAP-Befehlsreferenz"^].

. Auf dem neuen Ziel-FlexGroup-Volume die Quell-FlexGroup neu synchronisieren: `snapmirror resync -source-path svm_name:volume_name`
+
[listing]
----
cluster1::> snapmirror resync -source-path vsd:dst
----
. Überwachung der SnapMirror Transfers: `snapmirror show -expand`
+
[listing]
----
cluster2::> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vsd:dst       XDP  vss:src        Snapmirrored
                                      Idle           -         true    -
vss:dst__0001 XDP  vss:src__0001  Snapmirrored
                                      Idle           -         true    -
vsd:dst__0002 XDP  vss:src__0002  Snapmirrored
                                      Idle           -         true    -
vsd:dst__0003 XDP  vss:src__0003  Snapmirrored
                                      Idle           -         true    -
vsd:dst__0004 XDP  vss:src__0004  Snapmirrored
                                      Idle           -         true    -
vsd:dst__0005 XDP  vss:src__0005  Snapmirrored
                                      Idle           -         true    -
vsd:dst__0006 XDP  vss:src__0006  Snapmirrored
                                      Idle           -         true    -
vsd:dst__0007 XDP  vss:src__0007  Snapmirrored
                                      Idle           -         true    -
vsd:dst__0008 XDP  vss:src__0008  Snapmirrored
                                      Idle           -         true    -
...
----
+
Der SnapMirror Beziehungsstatus jedes Bestandteils wird als  `Snapmirrored` angezeigt, was darauf hindeutet, dass die Resynchronisierung erfolgreich war.



.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["snapmirror create"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["snapmirror delete"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["SnapMirror Release"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["SnapMirror Resynchronisierung"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["snapmirror show"^]

