---
permalink: flexgroup/shrink-flexgroup-volume-task.html 
sidebar: sidebar 
keywords: reduce, size, flexgroup, volume, flex group, resize, shrink, shrinking, autosize 
summary: Ab ONTAP 9.6 können Sie die Größe eines FlexGroup-Volumes auf einen Wert skalieren, der unter der aktuellen Größe liegt, um den ungenutzten Speicherplatz aus dem Volume freizugeben. Bei der Verkleinerung eines FlexGroup Volumes wird ONTAP automatisch alle FlexGroup Komponenten neu dimensionieren. 
---
= Verkleinerung eines FlexGroup Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.6 können Sie die Größe eines FlexGroup-Volumes auf einen Wert skalieren, der unter der aktuellen Größe liegt, um den ungenutzten Speicherplatz aus dem Volume freizugeben. Bei der Verkleinerung eines FlexGroup Volumes wird ONTAP automatisch alle FlexGroup Komponenten neu dimensionieren.

.Schritt
. Überprüfen Sie die aktuelle FlexGroup-Volume-Größe: 'Volume size -vserver_vserver_Name_ -Volume _fg_Name_'
. Reduzierung der Größe des FlexGroup Volumes: `volume size -vserver _vserver_name_ -volume _fg_name_ _new_size_`
+
Wenn Sie die neue Größe angeben, können Sie entweder einen niedrigeren Wert als die aktuelle Größe oder einen negativen Wert mit dem Minuszeichen (-) angeben, um das die aktuelle Größe des FlexGroup-Volumes reduziert wird.

+
[NOTE]
====
Wenn das automatische Verkleinern für das Volume aktiviert ist (`volume autosize` Befehl). Die minimale Autosize wird auf die neue Größe des Volume festgelegt.

====
+
Im folgenden Beispiel wird die aktuelle Volume-Größe für das FlexGroup Volume mit dem Namen Volx angezeigt und die Größe des Volume auf 10 TB angepasst:

+
[listing]
----
cluster1::> volume size -vserver svm1 -volume volX
(volume size)
vol size: FlexGroup volume 'svm1:volX' has size 15TB.

cluster1::> volume size -vserver svm1 -volume volX 10TB
(volume size)
vol size: FlexGroup volume 'svm1:volX' size set to 10TB.
----
+
Im folgenden Beispiel wird die aktuelle Volume-Größe für das FlexGroup Volume mit dem Namen Volx angezeigt und die Größe des Volumes um 5 TB reduziert:

+
[listing]
----
cluster1::> volume size -vserver svm1 -volume volX
(volume size)
vol size: FlexGroup volume 'svm1:volX' has size 15TB.

cluster1::> volume size -vserver svm1 -volume volX -5TB
(volume size)
vol size: FlexGroup volume 'svm1:volX' size set to 10TB.
----

