---
permalink: flexgroup/shrink-flexgroup-volume-task.html 
sidebar: sidebar 
keywords: reduce, size, flexgroup, volume, flex group, resize, shrink, shrinking, autosize 
summary: Ab ONTAP 9.6 können Sie die Größe eines FlexGroup-Volumes auf einen Wert skalieren, der unter der aktuellen Größe liegt, um den ungenutzten Speicherplatz aus dem Volume freizugeben. Bei der Verkleinerung eines FlexGroup Volumes wird ONTAP automatisch alle FlexGroup Komponenten neu dimensionieren. 
---
= Verkleinerung eines FlexGroup Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.6 können Sie die Größe eines FlexGroup-Volumes auf einen Wert skalieren, der unter der aktuellen Größe liegt, um den ungenutzten Speicherplatz aus dem Volume freizugeben. Bei der Verkleinerung eines FlexGroup Volumes wird ONTAP automatisch alle FlexGroup Komponenten neu dimensionieren.

.Schritt
. Reduzierung der Größe des FlexGroup Volumes: `volume size -vserver vserver_name -volume fg_name -size new_size`
+
`new_size` Ist die Größe des FlexGroup Volume. Sie können entweder einen niedrigeren Wert als die aktuelle Größe angeben oder einen negativen Wert angeben, um den die aktuelle Größe des FlexGroup Volume verringert wird.

+
[NOTE]
====
Wenn das automatische Verkleinern für das Volume aktiviert ist (`volume autosize` Befehl). Die minimale Autosize wird auf die neue Größe des Volume festgelegt.

====
+
[listing]
----
cluster1::> volume size -vserver svm1 -volume volX -size 10TB
----
+
[listing]
----
cluster1::> volume size -vserver svm1 -volume volX -size -5TB
----

