---
permalink: flexcache-writeback/flexcache-write-back-overview.html 
sidebar: sidebar 
keywords: tr-4743, flexcache writeback, flexcache write-back, overview, technical report, netapp tr, ontap tr 
summary: Eingeführt in ONTAP 9.15.1, ist FlexCache Write-Back ein alternativer Betriebsmodus für das Schreiben in einem Cache. 
---
= Erfahren Sie mehr über ONTAP FlexCache Write-Back
:allow-uri-read: 


[role="lead"]
Eingeführt in ONTAP 9.15.1, ist FlexCache Write-Back ein alternativer Betriebsmodus für das Schreiben in einem Cache. Write-Back ermöglicht es, dass der Schreibvorgang im Cache auf einem stabilen Speicher gesichert und dem Client bestätigt wird, ohne darauf zu warten, dass die Daten den Ursprung erreichen. Die Daten werden asynchron an den Ursprung zurückgeschrieben. Das Ergebnis ist ein global verteiltes Dateisystem, das Schreibvorgänge mit nahezu lokaler Geschwindigkeit für bestimmte Arbeitslasten und Umgebungen ermöglicht und erhebliche Leistungsverbesserungen bietet.


NOTE: ONTAP 9.12.1 führte eine Write-Back-Funktion als öffentliche Vorschau ein. Diese wird als Write-Back Version 1 (wbv1) bezeichnet und sollte nicht mit der Write-Back-Funktion in ONTAP 9.15.1 verwechselt werden, die als Write-Back Version 2 (wbv2) bezeichnet wird.



[[write-back-vs-write-around]]
== Write-back vs Write-around

Seit FlexCache in ONTAP 9.5 eingeführt wurde, ist es ein les- und beschreibbarer Cache; jedoch arbeitete es im Write-Around-Betriebsmodus. Schreibvorgänge im Cache wurden an den Ursprung gesendet, um dort im permanenten Speicher gesichert zu werden. Nachdem der Ursprung den Schreibvorgang erfolgreich im permanenten Speicher gesichert hatte, bestätigte er den Schreibvorgang an den Cache. Der Cache bestätigte den Schreibvorgang anschließend an den Client. Dadurch verursachte jeder Schreibvorgang den Nachteil, das Netzwerk zwischen Cache und Ursprung zu durchlaufen. FlexCache Write-Back ändert dies.


NOTE: Nach dem Upgrade auf ONTAP 9.15.1 ist es möglich, einen herkömmlichen Write-Around-Cache in einen Write-Back-Cache zu konvertieren und bei Bedarf wieder zurück in einen Write-Around-Cache. Dies kann jedoch das Lesen von Diagnoseprotokollen erschweren, falls ein Problem auftritt.

|===
|  | Write-around | Write-Back 


| ONTAP Version | 9.6+ | 9.15.1+ 


| Anwendungsfall | Leseintensive Arbeitslast | Schreibintensive Arbeitslast 


| Daten festgeschrieben am | Herkunft | Cache 


| Kundenerlebnis | WAN-ähnlich | LAN-ähnlich 


| Grenzen | 100 pro Herkunft | 10 pro Herkunft 


| https://en.wikipedia.org/wiki/CAP_theorem["CAP-Theorem"^] | Verfügbar und partitionstolerant | Verfügbar und konsistent 
|===


[[flexcache-write-back-terminology]]
== FlexCache Write-Back-Terminologie

Wichtige Konzepte und Begriffe im Zusammenhang mit FlexCache Write-Back.

[cols="12%,88%"]
|===
| Begriff | Definition 


| [[dirty-data]]*schmutzige Daten* | Daten, die im Cache zur dauerhaften Speicherung hinterlegt wurden, aber noch nicht an den Ursprung übertragen wurden. 


| *Exklusive Sperrdelegierung (XLD)* | Eine Sperrberechtigung auf Protokollebene, die einem Cache pro Datei gewährt wird. Diese Berechtigung ermöglicht dem Cache, exklusive Schreibsperren an Clients zu vergeben, ohne den Ursprung zu kontaktieren. 


| *Gemeinsame Sperrdelegierung (SLD)* | Eine Sperrberechtigung auf Protokollebene, die einem Cache pro Datei gewährt wird. Diese Berechtigung ermöglicht dem Cache, gemeinsame Lesesperren an Clients zu vergeben, ohne den Ursprung zu kontaktieren. 


| *Write-back* | Ein Betriebsmodus von FlexCache, bei dem Schreibvorgänge in einem Cache auf dem stabilen Speicher dieses Caches festgeschrieben und dem Client sofort bestätigt werden. Die Daten werden asynchron an den Ursprung zurückgeschrieben. 


| *Write-around* | Ein Betriebsmodus von FlexCache, bei dem Schreibvorgänge in einen Cache an den Ursprung weitergeleitet werden, um dort dauerhaft gespeichert zu werden. Nach der Speicherung bestätigt der Ursprung den Schreibvorgang gegenüber dem Cache, und der Cache bestätigt den Schreibvorgang gegenüber dem Client. 


| *System zur Erfassung schmutziger Daten (DDRS)* | Ein proprietärer Mechanismus, der die schmutzigen Daten in einem Write-Back-fähigen Cache dateiweise verfolgt. 


| *Herkunft* | Ein FlexGroup oder FlexVol, das die Quelldaten für alle FlexCache Cache-Volumes enthält. Es ist die zentrale Datenquelle, steuert die Sperrung und gewährleistet 100% Datenkonsistenz, Aktualität und Kohärenz. 


| *Cache* | Ein FlexGroup, das ein spärlich belegtes Cache-Volume des FlexCache Ursprungs ist. 
|===


[[consistent-current-and-coherent]]
=== Konsistent, aktuell und kohärent

FlexCache ist NetApps Lösung, um die richtigen Daten jederzeit und überall bereitzustellen. FlexCache ist zu 100 % konsistent, aktuell und kohärent – und das zu 100 % der Zeit:

* *Konsistent:* Die Daten sind überall dort gleich, wo auf sie zugegriffen wird.
* *Aktuell:* Die Daten sind immer auf dem neuesten Stand.
* *Kohärent:* Die Daten sind korrekt/nicht beschädigt.

