---
sidebar: sidebar 
permalink: smbc/considerations-limits.html 
keywords: SM-BC, SMBC, restrictions, consistency group, endpoint limits, solaris, aix, hp-ux, fanout, snampmirror active sync 
summary: Bei der Verwendung der SnapMirror Business Continuity-Lösung gibt es einige zusätzliche Einschränkungen. 
---
= Objektbeschränkungen für SnapMirror Business Continuity
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Beachten Sie bei der Vorbereitung der Verwendung und Verwaltung von SnapMirror Business Continuity die folgenden Einschränkungen.



== Konsistenzgruppen in einem Cluster

Die Einschränkungen der Konsistenzgruppen für ein Cluster mit SM-BC werden auf Basis von Beziehungen berechnet und hängen von der verwendeten ONTAP Version ab. Einschränkungen sind plattformunabhängig.

|===
| ONTAP-Version | Maximale Anzahl von Beziehungen 


| ONTAP 9.8-9.9.1 | 5 


| ONTAP 9.10.1 | 20 


| ONTAP 9.11.1 und höher | 50 
|===


== Volumes pro Konsistenzgruppe

Die maximale Anzahl von Volumes pro Konsistenzgruppe mit SM-BC ist plattformunabhängig.

|===
| ONTAP-Version | Maximale Anzahl von Volumes, die in einer Konsistenzgruppenbeziehung unterstützt werden 


| ONTAP 9.8-9.9.1 | 12 


| ONTAP 9.10.1 und höher | 16 
|===


== Volumes

Volumengrenzen in SM-BC werden auf der Grundlage der Anzahl der Endpunkte berechnet, nicht anhand der Anzahl der Beziehungen. Eine Konsistenzgruppe mit 12 Volumes steuert 12 Endpunkte auf dem primären und dem sekundären Cluster bei. Sowohl SM-BC als auch SnapMirror Synchronous Beziehungen tragen zur Gesamtzahl der Endpunkte bei.

Die maximale Anzahl der Endpunkte pro Plattform ist in der folgenden Tabelle enthalten.

|===
| S. Nein | Plattform 3+| Endpunkte pro HA für SM-BC 3+| Sync insgesamt und SM-BC Endpunkte pro HA 


|  |  | ONTAP 9.8-9.9.1 | ONTAP 9.10.1 | ONTAP 9.11.1 und höher | ONTAP 9.8-9.9.1 | ONTAP 9.10.1 | ONTAP 9.11.1 und höher 


| 1 | AFF | 60 | 200 | 400 | 80 | 200 | 400 


| 2 | ASA | 60 | 200 | 400 | 80 | 200 | 400 
|===


== SAN-Objektbeschränkungen

Die EINSCHRÄNKUNGEN FÜR SAN-Objekte sind in der folgenden Tabelle enthalten. Die Grenzen gelten unabhängig von der Plattform.

|===
| Objekt in einer SM-BC-Beziehung | Zählen 


| LUNs pro Volume | 256 


| LUN-Zuordnungen pro Node | 2048 


| LUN-Zuordnungen pro Cluster | 4096 


| LIFs pro SVM (mit mindestens einem Volume in einer SM-BC-Beziehung) | 256 


| Inter-Cluster-LIFs pro Node | 4 


| Inter-Cluster LIFs pro Cluster | 8 
|===
.Verwandte Informationen
* link:https://hwu.netapp.com/["Hardware Universe"^]
* link:../consistency-groups/limits.html["Einschränkungen für Konsistenzgruppen"^]

