---
sidebar: sidebar 
permalink: smbc/smbc_troubleshoot_sm_delete_fails_in_takeover_state.html 
keywords: troubleshooting, SM-BC, SMBC, SnapMirror, delete, takeover, consistency group 
summary: 'Wenn ONTAP 9.9.1 auf einem Cluster installiert ist, führen Sie die aus `snapmirror delete` Befehl schlägt fehl, wenn eine SM-BC Konsistenzgruppenbeziehung sich im Übernahmemodus befindet.' 
---
= Das Löschen von SnapMirror schlägt im Takover-Status fehl
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Wenn ONTAP 9.9.1 auf einem Cluster installiert ist, führen Sie die aus `snapmirror delete` Befehl schlägt fehl, wenn eine SM-BC Konsistenzgruppenbeziehung sich im Übernahmemodus befindet.

....
C2_cluster::> snapmirror delete  vs1:/cg/dd

Error: command failed: RPC: Couldn't make connection
....
Wenn sich die Knoten in einer SM-BC Beziehung im Übernahmemodus befinden, führen Sie die SnapMirror Lösch- und Freigabeoperation durch und die Option „-Force“ ist auf „true“ gesetzt.

....
C2_cluster::> snapmirror delete  vs1:/cg/dd -force true

Warning: The relationship between source "vs0:/cg/ss" and destination
         "vs1:/cg/dd" will be deleted, however the items of the destination
         Consistency Group might not be made writable, deletable, or modifiable
         after the operation. Manual recovery might be required.
Do you want to continue? {y|n}: y
Operation succeeded: snapmirror delete for the relationship with destination "vs1:/cg/dd".
....