---
sidebar: sidebar 
permalink: smbc/smbc_plan_ontap_access_options.html 
keywords: SM-BC, SMBC, access options, CLI, command line interface, System Manager, REST API 
summary: Bei der Konfiguration der ONTAP-Nodes, die an einer SM-BC-Implementierung beteiligt sind, stehen Ihnen verschiedene Zugriffsoptionen zur Verfügung. 
---
= ONTAP-Zugriffsoptionen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Bei der Konfiguration der ONTAP-Nodes, die an einer SM-BC-Implementierung beteiligt sind, stehen Ihnen verschiedene Zugriffsoptionen zur Verfügung. Wählen Sie die Option aus, die am besten zu Ihrer spezifischen Umgebung und Ihren Bereitstellungszielen passt.


NOTE: In allen Fällen müssen Sie sich mit dem Administratorkonto mit einem gültigen Passwort anmelden.

Befehlszeilenschnittstelle:: Die textbasierte Befehlszeilenschnittstelle ist über die ONTAP-Management-Shell verfügbar. Sie können über Secure Shell (SSH) auf die CLI zugreifen.
System Manager:: Sie können eine Verbindung zum System Manager über einen modernen Webbrowser herstellen. Die Web-GUI bietet eine intuitive und benutzerfreundliche Oberfläche für den Zugriff auf die Business Continuity-Funktionen von SnapMirror. Weitere Informationen zur Verwendung von System Manager finden Sie unter https://["Dokumentation von System Manager"^].
REST API:: Die ONTAP REST API ist externen Clients zugänglich und bietet eine weitere Option beim Herstellen einer Verbindung zum ONTAP. Sie können über jede gängige Programmiersprache oder ein Tool, das REST-Webservices unterstützt, auf die API zugreifen. Beliebte Optionen sind:
+
--
* Python (einschließlich ONTAP Python Client Library)
* Java
* Curl


--


Die Verwendung einer Programmiersprache oder Skriptsprache bietet die Möglichkeit, die Implementierung und das Management von SnapMirror Business Continuity-Implementierungen zu automatisieren. Weitere Informationen finden Sie auf der ONTAP Online-Dokumentationsseite Ihres ONTAP Storage-Systems.
