---
sidebar: sidebar 
permalink: smbc/smbc_admin_upgrade_and_revert_considerations.html 
keywords: upgrade, revert, snapmirror active sync 
summary: Das Aktualisieren oder Zurücksetzen von ONTAP hat Auswirkungen auf Ihre SM-BC-Beziehung, insbesondere beim Wechsel zu ONTAP 9.8 oder höher oder 9.7 und früher. 
---
= Aktualisieren und Zurücksetzen von ONTAP mit SM-BC
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror Business Continuity (SM-BC) wird ab ONTAP 9.8 unterstützt. Das Aktualisieren und Zurücksetzen des ONTAP-Clusters hat Auswirkungen auf die SM-BC Beziehungen, abhängig von der ONTAP-Version, auf die Sie aktualisieren oder zurücksetzen.



== Upgrade von ONTAP

Bevor Sie SM-BC konfigurieren und verwenden können, müssen Sie alle Nodes auf den Quell- und Ziel-Clustern auf ONTAP 9.8 oder höher aktualisieren.
link:link:../upgrade/index.html["Software-Upgrades auf ONTAP Clustern"]


NOTE: Der `snapmirror quiesce` Und `snampirror resume` Befehle werden mit SM-BC nicht unterstützt.

Wenn Sie Cluster von 9.8 oder 9.9.1 auf 9.10.1 aktualisieren, erstellt ONTAP neue Konsistenzgruppen auf Quelle und Ziel für SM-BC-Beziehungen. Diese können in System Manager unter der Option **Consistency Groups** oder über die ONTAP REST API mit dem Endpunkt Consistency Groups verwaltet werden.



== Kehren Sie von ONTAP 9.10.1 zu ONTAP 9.9.1 zurück

Um Beziehungen von 9.10.1 auf 9.9 zurückzusetzen, müssen SM-BC-Beziehungen gelöscht werden, gefolgt von der Konsistenzgruppeinstanz 9.10.1. Konsistenzgruppen mit einer aktiven SM-BC-Beziehung können nicht gelöscht werden. Alle FlexVol-Volumes, die auf 9.10.1 aktualisiert wurden, die zuvor mit einem anderen intelligenten Container oder einer Enterprise-Applikation in 9.9.1 oder früher verbunden waren, werden nicht mehr wieder zugeordnet. Durch das Löschen von Konsistenzgruppen werden die zusammengehörigen Volumes oder granularen Volume-Snapshots nicht gelöscht. Siehe link:../consistency-groups/delete-task.html["Löschen einer Konsistenzgruppe"] Weitere Informationen zu dieser Aufgabe finden Sie in ONTAP 9.10.1 und höher.



== Kehren Sie von ONTAP 9.8 zu ONTAP 9.7 zurück


NOTE: SM-BC wird nicht mit gemischten ONTAP 9.7 und ONTAP 9.8 Clustern unterstützt.

Wenn Sie von ONTAP 9.8 auf ONTAP 9.7 zurücksetzen, müssen Sie Folgendes beachten:

* Wenn der Cluster-Host ein SM-BC Ziel ist, kann das Zurücksetzen auf ONTAP 9.7 nicht zulässig, bis die Beziehung unterbrochen und gelöscht wird.
* Wenn der Cluster eine SM-BC Quelle hostet, ist das Zurücksetzen auf ONTAP 9.7 erst zulässig, wenn die Beziehung freigegeben ist.
* Alle benutzerdefinierten SM-BC SnapMirror-Richtlinien, die vom Benutzer erstellt wurden, müssen gelöscht werden, bevor Sie auf ONTAP 9.7 zurücksetzen.


Informationen zur Erfüllung dieser Anforderungen finden Sie unter link:smbc_admin_removing_an_smbc_configuration.html["Entfernen Sie eine SM-BC-Konfiguration"].

.Schritte
. Führen Sie einen Rückkehrcheck von einem der Cluster in der SM-BC Beziehung durch:
+
`cluster::*> system node revert-to -version 9.7 -check-only`

+
Beispiel:

+
....
cluster::*> system node revert-to -version 9.7 -check-only
Error: command failed: The revert check phase failed. The following issues must be resolved before revert can be completed. Bring the data LIFs down on running vservers. Command to list the running vservers: vserver show -admin-state running Command to list the data LIFs that are up: network interface show -role data -status-admin up Command to bring all data LIFs down: network interface modify {-role data} -status-admin down
Disable snapshot policies.
    Command to list snapshot policies: "snapshot policy show".
    Command to disable snapshot policies: "snapshot policy modify -vserver
   * -enabled false"

   Break off the initialized online data-protection (DP) volumes and delete
   Uninitialized online data-protection (DP) volumes present on the local
   node.
    Command to list all online data-protection volumes on the local node:
   volume show -type DP -state online -node <local-node-name>
    Before breaking off the initialized online data-protection volumes,
   quiesce and abort transfers on associated SnapMirror relationships and
   wait for the Relationship Status to be Quiesced.
    Command to quiesce a SnapMirror relationship: snapmirror quiesce
    Command to abort transfers on a SnapMirror relationship: snapmirror
   abort
    Command to see if the Relationship Status of a SnapMirror relationship
   is Quiesced: snapmirror show
    Command to break off a data-protection volume: snapmirror break
    Command to break off a data-protection volume which is the destination
   of a SnapMirror relationship with a policy of type "vault": snapmirror
   break -delete-snapshots
    Uninitialized data-protection volumes are reported by the "snapmirror
   break" command when applied on a DP volume.
    Command to delete volume: volume delete

   Delete current version snapshots in advanced privilege level.
    Command to list snapshots: "snapshot show -fs-version 9.8"
    Command to delete snapshots: "snapshot prepare-for-revert -node
   <nodename>"

   Delete all user-created policies of the type active-strict-sync-mirror
   and active-sync-mirror.
   The command to see all active-strict-sync-mirror and active-sync-mirror
   type policies is:
    snapmirror policy show -type
   active-strict-sync-mirror,active-sync-mirror
   The command to delete a policy is :
    snapmirror policy delete -vserver <SVM-name> -policy <policy-name>
....


Informationen zum Zurücksetzen von Clustern finden Sie unter link:../revert/index.html["ONTAP zurücksetzen"].
