---
sidebar: sidebar 
permalink: smbc/smbc_install_creating_a_consistency_group_relationship.html 
keywords: SM-BC, SMBC, consistency group, create, constituent 
summary: Sie müssen eine SnapMirror Konsistenzgruppe erstellen, durch die auch die Beziehung der synchronen Konsistenzgruppen hergestellt wird. 
---
= Erstellen einer Konsistenzgruppenbeziehung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie müssen eine SM-BC Konsistenzgruppe erstellen, durch die auch die synchrone Konsistenzgruppe Beziehung hergestellt wird.


NOTE: Dieser Workflow gilt für Benutzer in ONTAP 9.8 und 9.9.1. Wenn Sie diese ONTAP CLI-Befehle ab ONTAP 9.10.1 verwenden, funktionieren sie weiterhin für die Erstellung einer Konsistenzgruppe. Es wird jedoch empfohlen, Konsistenzgruppen mit System Manager oder der ONTAP REST API zu verwalten.

Es gelten die folgenden Voraussetzungen und Einschränkungen:

* Sie müssen ein Cluster- oder Storage-VM-Administrator sein
* Sie benötigen eine SnapMirror Synchronous-Lizenz
* Die Ziel-Volumes müssen vom Typ DP sein
* Die primäre und die sekundäre Storage VM müssen eine Peered-Beziehung sein
* Alle zusammengehörigen Volumes einer Konsistenzgruppe müssen sich in einer einzelnen Storage VM befinden
* Sie können keine SM-BC-Konsistenzgruppenbeziehungen über ASA Cluster und nicht-ASA Cluster hinweg einrichten
* Der Name der Konsistenzgruppe muss eindeutig sein


Sie müssen die Konsistenzgruppenbeziehung vom Ziel-Cluster erstellen. Mit dem können bis zu 12 Komponenten zugeordnet werden `cg-item-mappings` Parameter auf dem `snapmirror create` Befehl.

.Schritte
. Erstellen einer Konsistenzgruppe und einer Beziehung zwischen den einzelnen Bestandteile. Dieses Beispiel erstellt zwei Konsistenzgruppen: cg_src mit konstituierenden Volumes vol1 und vol2, und cg_dist mit konstituierenden Volumes vol1_dr und vol2_dr.
+
`destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol_src1:@vol_dst1,vol_src2:@vol_dst2 -policy AutomatedFailOver`


