---
sidebar: sidebar 
permalink: smbc/smbc_troubleshoot_planned_failover_unsuccessful.html 
keywords: troubleshooting, SM-BC, SMBC, SnapMirror, failover, planned failover, common Snapshot copy 
summary: 'Nach Ausführung des `snapmirror failover start` Befehl, die Ausgabe für das `snapmirror failover show` Befehl zeigt eine Meldung an, dass ein unterbrechungsfreier Vorgang ausgeführt wird.' 
---
= Ein geplantes Failover war nicht erfolgreich
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


.Problem:
[role="lead"]
Nach Ausführung des `snapmirror failover start` Befehl, die Ausgabe für das `snapmirror failover show` Befehl zeigt eine Meldung an, dass ein unterbrechungsfreier Vorgang ausgeführt wird.

....
Cluster1::> snapmirror failover show
Source Destination Error
Path Path Type Status start-time end-time Reason
-------- ----------- -------- --------- ---------- ---------- ----------
vs1:/cg/cg vs0:/cg/cg planned failed 10/1/2020 10/1/2020 SnapMirror Failover cannot start because a volume move is running. Retry the command once volume move has finished.
                                                          08:35:04 08:35:04
....
.Ursache:
Geplante Failovers können nicht beginnen, wenn ein unterbrechungsfreier Betrieb einschließlich Volume-Verschiebung, Aggregatverschiebung und Storage Failover läuft.

.Lösung:
Warten Sie, bis der unterbrechungsfreie Betrieb abgeschlossen ist, und versuchen Sie es erneut.
