---
sidebar: sidebar 
permalink: smbc/smbc_admin_performing_a_planned_failover.html 
keywords: SM-BC, SMBC, testing failover, planned failover, maintenance, Mediator, quorum 
summary: Sie können ein geplantes Failover durchführen, um die Disaster-Recovery-Konfiguration zu testen oder um Wartungsarbeiten am primären Cluster durchzuführen. 
---
= Führen Sie ein geplantes Failover durch
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können ein geplantes Failover durchführen, um die Disaster-Recovery-Konfiguration zu testen oder um Wartungsarbeiten am primären Cluster durchzuführen.

.Bevor Sie beginnen
* Die Beziehung muss synchron sein
* Unterbrechungsfreier Betrieb darf nicht ausgeführt werden
* Der ONTAP Mediator muss konfiguriert, verbunden und in Quorum sein


Der Administrator des sekundären Clusters initiiert einen geplanten Failover. Der Vorgang erfordert das Umschalten der primären und sekundären Rollen, damit das sekundäre Cluster vom primären Standort übernommen wird. Das neue primäre Cluster kann dann ohne Unterbrechung der Client-Prozesse mit der lokalen Verarbeitung von ein- und Ausgabeanfragen beginnen.

.Schritte
. Starten Sie den Failover-Vorgang:
+
`destination::>snapmirror failover start -destination-path   vs1_dst:/cg/cg_dst`

. Überwachen Sie den Status des Failover:
+
`destination::>snapmirror failover show`

. Wenn der Failover-Vorgang abgeschlossen ist, können Sie den Status der synchronen SnapMirror Schutzbeziehung vom Ziel aus überwachen:
+
`destination::>snapmirror show`


