---
permalink: s3-audit/create-enable-config-task.html 
sidebar: sidebar 
keywords: consistency groups, consistency group, application protection, parent, child, configure 
summary: Zur Implementierung von S3 Auditing wird zunächst eine persistente Objektspeicher Auditing-Konfiguration auf einer S3-fähigen SVM erstellt und anschließend die Konfiguration aktiviert. 
---
= Erstellen und Aktivieren einer ONTAP S3 Überwachungskonfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zur Implementierung von S3 Auditing wird zunächst eine persistente Objektspeicher Auditing-Konfiguration auf einer S3-fähigen SVM erstellt und anschließend die Konfiguration aktiviert.

.Bevor Sie beginnen
* Sie verfügen über eine S3-fähige SVM.
* Bestätigen Sie, dass ausreichend Speicherplatz für Staging-Volumes in der lokalen Tier vorhanden ist.


.Über diese Aufgabe
Für jede SVM, die S3-Buckets enthält, die Sie überwachen möchten, ist eine Überwachungskonfiguration erforderlich. Die S3-Überwachung kann auf neuen oder bestehenden S3-Servern aktiviert werden. Überwachungskonfigurationen bleiben in einer S3-Umgebung erhalten, bis sie mit dem Befehl *vserver object-store-server audit delete* entfernt werden.

Die S3-Audit-Konfiguration gilt für alle Buckets in der SVM, die für die Überwachung ausgewählt werden. Eine SVM mit aktivierter Überwachung kann sowohl überwachte als auch nicht überwachte Buckets enthalten.

Es wird empfohlen, die S3-Überwachung für die automatische Protokollrotation zu konfigurieren, die anhand der Protokollgröße oder eines Zeitplans erfolgt. Wenn die automatische Protokollrotation nicht konfiguriert wird, werden standardmäßig alle Protokolldateien beibehalten. Die S3-Protokolldateien können auch manuell mit dem Befehl *vserver object-store-server audit rotate-log* rotiert werden.

Wenn die SVM eine SVM Disaster Recovery-Quelle ist, kann sich der Zielpfad nicht auf dem Root-Volume befinden.

.Schritte
. Die Überwachungskonfiguration ermöglicht das Rotieren von Überwachungsprotokollen basierend auf der Protokollgröße oder einem Zeitplan.
+
[cols="2,4"]
|===
| Wenn Sie die Revisionsprotokolle rotieren möchten... | Eingeben... 


| Loggröße | `vserver object-store-server audit create -vserver _svm_name_ -destination _path_ [[-events] {data{vbar}management}, ...] {[-rotate-limit _integer_] {vbar} [-retention-duration [_integer_d] [_integer_h][_integer_m][_integers_]]} [-rotate-size {_integer_[KB{vbar}MB{vbar}GB{vbar}TB{vbar}PB]}]` 


| Ein Zeitplan  a| 
`vserver object-store-server audit create -vserver _svm_name_ -destination path [[-events] {data{vbar}management}, ...] {[-rotate-limit _integer_] {vbar} [-retention-duration [_integerd_][_integerh_] [_integerm_][_integers_]] } [-rotate-schedule-month _chron_month_] [-rotate-schedule-dayofweek _chron_dayofweek_] [-rotate-schedule-day _chron_dayofmonth_] [-rotate-schedule-hour _chron_hour_] -rotate-schedule-minute _chron_minute_`

Der  `-rotate-schedule-minute`Parameter ist erforderlich, wenn eine zeitbasierte Revisionsprotokollrotation konfiguriert wird.

|===
. S3-Überwachung aktivieren:
+
`vserver object-store-server audit enable -vserver _svm_name_`



.Beispiele
Das folgende Beispiel erstellt eine Überwachungskonfiguration, die alle S3-Ereignisse (Standard) mithilfe einer größenbasierten Rotation überwacht. Die Protokolle werden im Verzeichnis /audit_log gespeichert. Die maximale Protokolldateigröße beträgt 200 MB. Die Protokolle werden rotiert, sobald sie 200 MB groß sind.

`cluster1::> vserver audit create -vserver vs1 -destination /audit_log -rotate-size 200MB`

Das folgende Beispiel erstellt eine Überwachungskonfiguration, die alle S3-Ereignisse (Standard) mithilfe einer größenbasierten Rotation überwacht. Die maximale Protokolldateigröße beträgt 100 MB (Standard), und die Protokolle werden 5 Tage lang aufbewahrt, bevor sie gelöscht werden.

`cluster1::> vserver audit create -vserver vs1 -destination /audit_log -retention-duration 5d0h0m`

Das folgende Beispiel erstellt eine Audit-Konfiguration, die S3-Management-Ereignisse und Ereignisse der zentralen Zugriffsrichtlinien-Staging mithilfe zeitbasierter Rotation auditiert. Die Audit-Protokolle werden monatlich um 12:30 Uhr an allen Wochentagen rotiert. Das Protokoll-Rotationslimit beträgt 5.

`cluster1::> vserver audit create -vserver vs1 -destination /audit_log -events management -rotate-schedule-month all -rotate-schedule-dayofweek all -rotate-schedule-hour 12 -rotate-schedule-minute 30 -rotate-limit 5`
