---
permalink: s3-audit/modify-config-task.html 
sidebar: sidebar 
keywords: s3 audit, modify 
summary: Sie können die Revisionsparameter einzelner Buckets oder die Revisionskonfiguration aller zur Revision ausgewählten Buckets im SVM anpassen. 
---
= Ändern einer ONTAP S3 Überwachungskonfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Revisionsparameter einzelner Buckets oder die Revisionskonfiguration aller zur Revision ausgewählten Buckets im SVM anpassen.

[cols="2,4"]
|===
| Wenn Sie die Revisionsprotokollkonfiguration für... anpassen möchten | Eingeben... 


| Einzelne Buckets | `vserver object-store-server audit event-selector modify -vserver _svm_name_ [-bucket _bucket_name_] [_parameters to modify_]` 


| Alle Buckets in der SVM  a| 
`vserver object-store-server audit modify -vserver _svm_name_ [_parameters to modify_]`

|===
.Beispiele
Das folgende Beispiel ändert eine einzelne Bucket-Audit-Konfiguration, um nur Schreibzugriffsereignisse zu protokollieren:

[listing]
----
cluster1::> vserver object-store-server audit event-selector modify -vserver vs1 -bucket test-bucket -access write-only
----
Das folgende Beispiel ändert die Revisionsprotokollkonfiguration aller Buckets in der SVM, um die Protokollgrößenbeschränkung auf 10 MB zu ändern und 3 Protokolldateien vor der Rotation aufzubewahren.

[listing]
----
cluster1::> vserver object-store-server audit modify -vserver vs1 -rotate-size 10MB -rotate-limit 3
----