---
permalink: s3-audit/select-buckets-task.html 
sidebar: sidebar 
keywords: s3 audit, select, buckets 
summary: Es ist anzugeben, welche Buckets in einer Audit-aktivierten SVM überwacht werden. 
---
= Buckets für ONTAP S3-Auditing auswählen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es ist anzugeben, welche Buckets in einer Audit-aktivierten SVM überwacht werden.

.Bevor Sie beginnen
* Sie haben eine SVM für die S3-Überwachung aktiviert.


.Über diese Aufgabe
S3-Audit-Konfigurationen werden pro SVM aktiviert, jedoch müssen Sie in den SVMs die Buckets auswählen, die für das Audit aktiviert sind. Wenn Buckets zur SVM hinzugefügt werden und diese neuen Buckets auditiert werden sollen, müssen sie mit diesem Verfahren ausgewählt werden. Es können auch nicht auditierte Buckets in einer SVM für S3-Auditing aktiviert sein.

Die Überwachungskonfigurationen bleiben für Buckets bestehen, bis sie durch den  `vserver object-store-server audit event-selector delete` Befehl entfernt werden.

.Schritte
. Wählen Sie einen Bucket für die S3-Überwachung aus:
+
[source, cli]
----
vserver object-store-server audit event-selector create -vserver <svm_name> -bucket <bucket_name> [[-access] {read-only|write-only|all}] [[-permission] {allow-only|deny-only|all}]
----
+
** `-access`: Gibt die Art des zu überwachenden Ereigniszugriffs an: `read-only`, `write-only` oder `all` (Standardwert ist `all`).
** `-permission`: Gibt den Typ der zu überwachenden Ereignisberechtigung an: `allow-only`, `deny-only` oder `all` (Standardwert ist `all`).




.Beispiel
Das folgende Beispiel erstellt eine Bucket-Audit-Konfiguration, die nur zulässige Ereignisse mit Lesezugriff protokolliert:

`cluster1::> vserver object-store-server audit event-selector create -vserver vs1 -bucket test-bucket -access read-only -permission allow-only`
