---
permalink: abac/abac-overview.html 
sidebar: sidebar 
keywords: technical report, tr, abac, attribute, access control, attribute based, nfs, security labels, xattrs, nfs 4.2, nist, abac compliant, data management, role-based access control, rbac, policy enforcement point, pep, policy decision point, pdp 
summary: 'ONTAP kann bei Konfiguration mit NFS 4.2-Sicherheitslabels und erweiterten Attributen (XATTRS) in eine Role-Based Access Control (RBAC) und eine attributbasierte Zugriffskontroll- und Zugriffskontrollsoftware (ABAC) integriert werden, die eine NIST ABAC-konforme Datenmanagement-Lösung ist.' 
---
= Attributbasierte Zugriffssteuerung mit ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können erweiterte RBAC mit Attributen und attributbasierter Zugriffssteuerung (Attribute Based Access Control, ABAC) mithilfe von ONTAP implementieren. ONTAP bietet verschiedene Ansätze, mit denen ein Kunde ABAC auf Dateiebene realisieren kann, einschließlich der Bezeichnung NFS 4.2 und XATTRS mit NFS und SMB/CIFS.

Attributbasierte Zugriffskontrolle (ABAC) ist eine ausgefeilte Methode zur Verwaltung von Zugriffsrechten, die Benutzerattribute, Ressourcenattribute und Umgebungsbedingungen berücksichtigt. Das National Institute of Standards and Technology (NIST) hat einen Standard für ABAC entwickelt, der ein Framework für seine sichere und konsistente Implementierung bietet.

Ab ONTAP 9.12.1 können Sie ONTAP mit NFSv4.2 Security Labels und Extended Attributes (XATTRS) so konfigurieren, dass es mit einer rollenbasierten Zugriffskontrolle (RBAC) und einer attributbasierten Zugriffskontrolle (ABAC)-Identität integriert werden kann. Durch diese Integration kann ONTAP eine als NIST ABAC-konforme Datenmanagement-Lösung kategorisierte Zugriffskontroll-Software nutzen. Sie bietet einen robusten und fortschrittlichen Ansatz für das Management von Zugriffsrechten in komplexen Umgebungen, einschließlich Policy Enforcement Point (PEP), einem Policy Decision Point (PDP) und Richtlinien, die Attribute berücksichtigen, die mit dem Benutzer, der Ressource und der Umgebung verknüpft sind.

Die Integration von NetApp ONTAP mit erweiterten Attributen (XATTRS) und der attributbasierten Zugriffskontrollsoftware (ABAC) entspricht den Richtlinien der NIST-Sonderveröffentlichung 800-162, um die Einhaltung der NIST-Standards für die ABAC-Implementierung sicherzustellen. Die Verwendung von NFS 4.2 Security Labels und XATTRS ermöglicht die Zuordnung von benutzerdefinierten Attributen mit Dateien und erfüllt damit die Anforderung des NIST ABAC Standards zur Berücksichtigung von Ressourcenattributen bei Entscheidungen zur Zugriffskontrolle. PEP und PDP der ABAC-Software entsprechen den Anforderungen des NIST ABAC-Standards für diese Komponenten im Zutrittskontrollprozess. Die Fähigkeit, komplexe Richtlinien zu definieren, die mehrere Attribute und Bedingungen berücksichtigen, entspricht den Anforderungen des NIST ABAC-Standards für richtlinienbasierte Zugriffssteuerung.

.Verwandte Informationen
* link:../abac/abac-approaches.html["Ansätze für ABAC mit ONTAP"]
* link:https://www.netapp.com/media/10720-tr-4067.pdf["NFS in NetApp ONTAP: Best Practice und Implementierungsleitfaden"^]
* Anforderung von Kommentaren (RFC)
+
** RFC 2203: RPCSEC_GSS-Protokollspezifikation
** RFC 3530: Network File System (NFS) Version 4 Protocol



