---
sidebar: sidebar 
permalink: s3-snapmirror/requirements-cloud-targets-concept.html 
keywords: requirements for cloud target relationships 
summary: Stellen Sie sicher, dass Ihre Quell- und Zielumgebungen die Anforderungen für die SnapMirror S3-Backup-Sicherung auf Cloud-Ziele erfüllen. 
---
= Anforderungen für Cloud-Zielbeziehungen
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Stellen Sie sicher, dass Ihre Quell- und Zielumgebungen die Anforderungen für die SnapMirror S3-Backup-Sicherung auf Cloud-Ziele erfüllen.

Um auf den Daten-Bucket zuzugreifen, müssen Sie über gültige Kontoanmeldeinformationen beim Objektspeicher-Provider verfügen.

Auf dem Cluster sollten Intercluster-Netzwerkschnittstellen und ein IPspace konfiguriert werden, bevor das Cluster eine Verbindung zu einem Cloud-Objektspeicher herstellen kann. Sie sollten auf jedem Node Cluster-Netzwerkschnittstellen erstellen, um Daten nahtlos vom lokalen Storage in den Cloud-Objektspeicher zu übertragen.

Für StorageGRID-Ziele müssen Sie die folgenden Informationen kennen:

* Servername, ausgedrückt als vollständig qualifizierter Domain-Name (FQDN) oder IP-Adresse
* Bucket-Name: Der Bucket muss bereits vorhanden sein
* Zugriffsschlüssel
* Geheimer Schlüssel


Darüber hinaus muss das CA-Zertifikat, das zum Signieren des StorageGRID-Serverzertifikats verwendet wird `security certificate install command`, auf der Admin-Storage-VM des ONTAP S3-Clusters mithilfe der installiert werden. Weitere Informationen finden Sie unterlink:../fabricpool/install-ca-certificate-storagegrid-task.html["Installieren eines CA-Zertifikats"], wenn Sie StorageGRID verwenden.

Für AWS S3 Ziele sind die folgenden Informationen erforderlich:

* Servername, ausgedrückt als vollständig qualifizierter Domain-Name (FQDN) oder IP-Adresse
* Bucket-Name: Der Bucket muss bereits vorhanden sein
* Zugriffsschlüssel
* Geheimer Schlüssel


Der DNS-Server für die Admin-Speicher-VM des ONTAP-Clusters muss in der Lage sein, FQDNs (sofern verwendet) in IP-Adressen aufzulösen.
