---
permalink: nvme/change-host-priority-nvme-task.html 
sidebar: sidebar 
keywords: manage, nvme, host, priority, regular, high priority, allocate more input and output, allocate, higher, input and output, queue counts, queue-depths, queue, depth 
summary: Ab ONTAP 9.14.1 kann das NVM-Subsystem so konfiguriert werden, dass die Ressourcenzuweisung für bestimmte Hosts priorisiert wird. 
---
= NVMe Host-Priorität ändern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.14.1 kann das NVMe-Subsystem so konfiguriert werden, dass die Ressourcenzuweisung für bestimmte Hosts priorisiert wird. Standardmäßig wird einem Host, der dem Subsystem hinzugefügt wird, eine reguläre Priorität zugewiesen. Hosts mit hoher Priorität werden größere I/O-Warteschlangenzahlen und Warteschlangentiefen zugewiesen.

Die Standardpriorität kann über die ONTAP command line interface (CLI) manuell von Normal auf Hoch geändert werden. Um die einem Host zugewiesene Priorität zu ändern, ist es erforderlich, den Host aus dem Subsystem zu entfernen und anschließend wieder hinzuzufügen.

.Schritte
. Es sollte überprüft werden, ob die Hostpriorität auf „regulär“ gesetzt ist:
+
[source, cli]
----
vserver nvme show-host-priority
----
+
Weitere Informationen zu  `vserver nvme show-host-priority` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-show-host-priority.html["ONTAP-Befehlsreferenz"^].

. Den Host aus dem Subsystem entfernen:
+
[source, cli]
----
vserver nvme subsystem host remove –vserver <svm_name> -subsystem <subsystem> -host-nqn <host_nqn>
----
+
Weitere Informationen zu  `vserver nvme subsystem host remove` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-subsystem-host-remove.html["ONTAP-Befehlsreferenz"^].

. Es sollte überprüft werden, ob der Host aus dem Subsystem entfernt wurde:
+
[source, cli]
----
vserver nvme subsystem host show
----
+
Weitere Informationen zu  `vserver nvme subsystem host show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-subsystem-host-show.html["ONTAP-Befehlsreferenz"^].

. Den Host mit hoher Priorität wieder dem Subsystem hinzufügen:
+
[source, cli]
----
vserver nvme subsystem host add -vserver <SVM_name> -subsystem <subsystem_name> -host-nqn <Host_NQN_:subsystem._subsystem_name> -priority high
----
+
Weitere Informationen zu  `vserver nvme subsystem host add` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-subsystem-host-add.html["ONTAP-Befehlsreferenz"^].


