---
permalink: nvme/disable-secure-authentication-nvme-task.html 
sidebar: sidebar 
keywords: manage, nvme, secure, authentication, tcp, dh-hmac-hcap, chap, disable, in-band, in band 
summary: Wenn Sie das NVMe-Protokoll ausführen und eine sichere Authentifizierung mit DH-HMAC-CHAP eingerichtet haben, können Sie es jederzeit deaktivieren. 
---
= In-Band-Authentifizierung über NVMe deaktiviert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die bandinterne Authentifizierung über NVMe mit DH-HMAC-CHAP konfiguriert haben, können Sie diese jederzeit deaktivieren.

Wenn Sie von ONTAP 9.12.1 oder höher auf ONTAP 9.12.0 oder früher zurücksetzen, müssen Sie die bandinterne Authentifizierung vor dem Zurücksetzen deaktivieren. Wenn die bandinterne Authentifizierung mit DH-HMAC-CHAP nicht deaktiviert ist, schlägt die Wiederherstellung fehl.

.Schritte
. Entfernen Sie den Host aus dem Subsystem, um die DH-HMAC-CHAP-Authentifizierung zu deaktivieren:
+
[source, cli]
----
vserver nvme subsystem host remove -vserver <svm_name> -subsystem <subsystem> -host-nqn <host_nqn>
----
. Vergewissern Sie sich, dass das DH-HMAC-CHAP-Authentifizierungsprotokoll vom Host entfernt wird:
+
[source, cli]
----
vserver nvme subsystem host show
----
. Fügen Sie den Host ohne Authentifizierung wieder zum Subsystem hinzu:
+
[source, cli]
----
vserver nvme subsystem host add vserver <svm_name> -subsystem <subsystem> -host-nqn <host_nqn>
----

