---
permalink: nvme/support-limitations.html 
sidebar: sidebar 
keywords: nvme, namespaces, considerations, provisioning 
summary: Die NVMe-Unterstützung variiert je nach Ihrer ONTAP Version, Ihrer Plattform und Ihrer Konfiguration. 
---
= NVMe Konfiguration, Unterstützung und Einschränkungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.4 ist das link:../san-admin/manage-nvme-concept.html["Non-Volatile Memory Express (NVMe)"] Protokoll für SAN-Umgebungen verfügbar. FC-NVMe verwendet dieselbe physische Konfiguration und dasselbe Zoning-Verfahren wie herkömmliche FC-Netzwerke, ermöglicht jedoch eine höhere Bandbreite, gesteigerte IOPs und geringere Latenz als FC-SCSI.

NVMe-Unterstützung und Einschränkungen variieren je nach Ihrer Version von ONTAP, Ihrer Plattform und Ihrer Konfiguration. Details zu Ihrer spezifischen Konfiguration sind in der link:https://imt.netapp.com/matrix/["NetApp Interoperabilitätsmatrix-Tool"^] zu finden. Informationen zu den unterstützten Grenzwerten finden sich unter link:https://hwu.netapp.com/["Hardware Universe"^].


NOTE: Die maximale Anzahl an Knoten pro Cluster ist im Hardware Universe unter *Unterstützte Plattformmischung* verfügbar.



[[configuration]]
== Konfiguration

* Die NVMe Konfiguration kann mit einem einzelnen Fabric oder mit mehreren Fabrics eingerichtet werden.
* Für jede SVM, die SAN unterstützt, sollte eine Management-LIF konfiguriert werden.
* Die Verwendung heterogener FC-Switch-Fabrics wird nicht unterstützt, außer bei eingebetteten Blade-Switches.
+
Spezifische Ausnahmen sind auf der link:https://mysupport.netapp.com/matrix["NetApp Interoperabilitätsmatrix-Tool"^] aufgeführt.

* Kaskadierte, partielle, vollständige, Core-Edge- und Director-Fabrics sind branchenübliche Methoden zur Verbindung von FC-Switches mit einem Fabric und werden alle unterstützt.
+
Ein Fabric kann aus einem oder mehreren Switches bestehen, und die Storage-Controller können mit mehreren Switches verbunden sein.





[[features]]
== Features

Die folgenden NVMe-Funktionen werden abhängig von Ihrer ONTAP-Version unterstützt.

[cols="2*"]
|===


| Beginnend mit ONTAP... | NVMe unterstützt 


| 9.17.1  a| 
* SnapMirror active sync NVMe/FC- und NVMe/TCP-Hostzugriff für VMware Workloads.




| 9.15.1  a| 
* Vier-Knoten MetroCluster IP-Konfigurationen auf NVMe/TCP




| 9.14.1  a| 
* Festlegung der Hostpriorität auf Subsystemebene (Host-Level-QoS)




| 9.12.1  a| 
* Vier-Knoten MetroCluster IP-Konfigurationen auf NVMe/FC
* MetroCluster Konfigurationen werden für Frontend-NVMe-Netzwerke vor ONTAP 9.12.1 nicht unterstützt.
* MetroCluster Konfigurationen werden auf NVMe/TCP nicht unterstützt.




| 9.10.1 | xref:../nvme/resize-namespace-task.html[Ändern der Größe eines Namensraums] 


| 9.9.1  a| 
* Koexistenz von Namensräumen und LUNs auf demselben Volume




| 9,8  a| 
* Protokollkoexistenz
+
Die Protokolle SCSI, NAS und NVMe können auf derselben virtuellen Speichermaschine (SVM) existieren. Wenn die gleichzeitige Nutzung mehrerer Protokolle vom Host-Betriebssystem nicht unterstützt wird, sollten Sie für jedes vom Host unterstützte Protokoll eine separate SVM konfigurieren.

+
Vor ONTAP 9.8 konnte NVMe das einzige Protokoll auf der SVM sein.





| 9,6  a| 
* 512-Byte-Blöcke und 4096-Byte-Blöcke für Namensräume
+
4096 ist der Standardwert. 512 sollte nur verwendet werden, wenn das Host-Betriebssystem keine 4096-Byte-Blöcke unterstützt.

* Volume Move mit zugeordneten Namespaces




| 9,5  a| 
* Multipath HA Pair Failover/Giveback


|===


[[protocols]]
== Protokolle

Die folgenden NVMe-Protokolle werden unterstützt.

[cols="3*"]
|===


| Protokoll | Beginnend mit ONTAP... | Erlaubt durch... 


| TCP | 9.10.1 | Standard 


| FC | 9,4 | Standard 
|===
Ab ONTAP 9.8 ist es möglich, die Protokolle SCSI, NAS und NVMe auf derselben Storage Virtual Machine (SVM) zu konfigurieren. In ONTAP 9.7 und früher kann NVMe das einzige Protokoll auf der SVM sein.



[[namespaces]]
== Namensräume

Beim Arbeiten mit NVMe Namespaces ist Folgendes zu beachten:

* Für ONTAP 9.15.1 und frühere Versionen unterstützt ONTAP den NVMe DataSet Management-Befehl (deallocate) mit NVMe zur Speicherplatzzurückgewinnung nicht.
* Sie können SnapRestore nicht verwenden, um einen Namespace von einer LUN wiederherzustellen oder umgekehrt.
* Die Speicherplatzzusage für Namensräume entspricht der Speicherplatzzusage des übergeordneten Volumes.
* Bei einem Volume-Übergang von Data ONTAP, das im 7-Mode betrieben wird, kann kein Namespace erstellt werden.
* Namensräume unterstützen Folgendes nicht:
+
** Umbenennung
** Inter-Volume-Verschiebung
** Inter-Volume-Kopie
** Kopie auf Anfrage






[[additional-limitations]]
== Weitere Einschränkungen

.Die folgenden ONTAP Funktionen werden von NVMe Konfigurationen nicht unterstützt:
* persistente Reservierungen


.Das Folgende gilt nur für Knoten, auf denen ONTAP 9.4 ausgeführt wird:
* NVMe LIFs und Namespaces müssen auf demselben Knoten gehostet werden.
* Der NVMe Service muss erstellt werden, bevor die NVMe LIF erstellt wird.


.Verwandte Informationen
link:https://www.netapp.com/pdf.html?item=/media/10680-tr4080.pdf["Bewährte Verfahren für moderne SAN"^]
