= 
:allow-uri-read: 


. Verwenden Sie den  `system license show` Befehl, um zu überprüfen, ob Sie eine Lizenz für FC oder iSCSI besitzen. Weitere Informationen zu  `system license show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/system-license-show.html["ONTAP-Befehlsreferenz"^].
+
`system license show`

+
[listing]
----

Package           Type    Description           Expiration
 ----------------- ------- --------------------- --------------------
 Base              site    Cluster Base License  -
 NFS               site    NFS License           -
 CIFS              site    CIFS License          -
 iSCSI             site    iSCSI License         -
 FCP               site    FCP License           -
----
. Falls Sie keine Lizenz für FC oder iSCSI besitzen, kann der  `license add` Befehl verwendet werden. Weitere Informationen zu  `license add` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=license+add["ONTAP-Befehlsreferenz"^].
+
`license add -license-code _your_license_code_`

. Der Protokolldienst wird auf der SVM aktiviert:
+
*Für iSCSI:* `vserver iscsi create -vserver _vserver_name_ -target-alias _vserver_name_`

+
Weitere Informationen zu  `vserver iscsi create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-iscsi-create.html["ONTAP-Befehlsreferenz"^].

+
*Für FC:* `vserver fcp create -vserver _vserver_name_ -status-admin up`

+
Weitere Informationen zu  `vserver fcp create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-fcp-create.html["ONTAP-Befehlsreferenz"^].

. Zwei LIFs für die SVMs auf jedem Knoten erstellen:
+
`network interface create -vserver _vserver_name_ -lif _lif_name_ -role data -data-protocol iscsi|fc -home-node _node_name_ -home-port _port_name_ -address _ip_address_ -netmask netmask`

+
NetApp unterstützt mindestens ein iSCSI- oder FC-LIF pro Knoten für jede SVM, die Daten bereitstellt. Für Redundanz sind jedoch zwei LIFs pro Knoten erforderlich. Weitere Informationen zu  `network interface create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-create.html["ONTAP-Befehlsreferenz"^].

. Es wird überprüft, ob Ihre LIFs erstellt wurden und ob ihr Betriebsstatus  `online` ist:
+
`network interface show -vserver _vserver_name_ _lif_name_`

+
Weitere Informationen zu  `network interface show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["ONTAP-Befehlsreferenz"^].

. LUNs erstellen:
+
`lun create -vserver vserver_name -volume _volume_name_ -lun _lun_name_ -size _lun_size_ -ostype linux -space-reserve enabled|disabled`

+
Ihr LUN Name darf maximal 255 Zeichen lang sein und keine Leerzeichen enthalten. Weitere Informationen zu  `lun create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/lun-create.html["ONTAP-Befehlsreferenz"^].

+

NOTE: Die NVFAIL Option wird automatisch aktiviert, wenn eine LUN in einem Volume erstellt wird.

. Erstellen Sie Ihre Initiatorgruppen:
+
`igroup create -vserver _vserver_name_ -igroup _igroup_name_ -protocol fcp|iscsi|mixed -ostype linux -initiator _initiator_name_`

+
Weitere Informationen zu  `igroup create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=igroup+create["ONTAP-Befehlsreferenz"^].

. Ordnen Sie Ihre LUNs Initiatorgruppen zu:
+
`lun mapping create -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -igroup _igroup_name_`

+
Weitere Informationen zu  `lun mapping create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/lun-mapping-create.html["ONTAP-Befehlsreferenz"^].

. Es sollte überprüft werden, ob die LUNs korrekt konfiguriert sind:
+
`lun show -vserver _vserver_name_`

+
Weitere Informationen zu  `lun show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/lun-show.html["ONTAP-Befehlsreferenz"^].

. link:../san-admin/create-port-sets-binding-igroups-task.html["Einen Portsatz erstellen und an eine Initiatorgruppe binden"] (optional).
. In der Dokumentation Ihres Hostsystems finden Sie die Schritte zur Aktivierung des Blockzugriffs auf Ihren jeweiligen Hosts.
. Mit den Host-Dienstprogrammen lässt sich die FC- oder iSCSI-Zuordnung abschließen und die LUNs auf dem Host erkennen.

