= 
:allow-uri-read: 


[role="lead"]
Es gibt vier verschiedene Sicherheitsarten: UNIX, NTFS, gemischt und vereinheitlicht. Jeder Sicherheitsstil hat unterschiedliche Auswirkungen auf den Umgang mit Berechtigungen für Daten. Sie müssen die verschiedenen Effekte verstehen, um sicherzustellen, dass Sie den entsprechenden Sicherheitsstil für Ihre Zwecke auswählen.

Es ist wichtig zu verstehen, dass Sicherheitsstile nicht bestimmen, welche Client-Typen auf Daten zugreifen können oder nicht. Sicherheitsstile bestimmen nur die Art der Berechtigungen, die ONTAP zur Kontrolle des Datenzugriffs verwendet, und welche Clienttypen diese Berechtigungen ändern können.

Wenn ein Volume beispielsweise UNIX-Sicherheitsstil verwendet, können SMB-Clients aufgrund der Multiprotokollart von ONTAP weiterhin auf Daten zugreifen (sofern sie sich ordnungsgemäß authentifizieren und autorisieren). ONTAP verwendet jedoch UNIX-Berechtigungen, die nur UNIX-Clients mit nativen Tools ändern können.

[cols="5*"]
|===
| Sicherheitsstil | Clients, die Berechtigungen ändern können | Berechtigungen, die Clients verwenden können | Dadurch effektiver Sicherheitsstil | Clients, die auf Dateien zugreifen können 


.2+| Unix .2+| NFS | Bits im NFSv3 Modus .2+| Unix .9+| NFS und SMB 


| NFSv4.x ACLs 


| NTFS | SMB | NTFS-ACLs | NTFS 


.3+| Gemischt .3+| NFS oder SMB | Bits im NFSv3 Modus .2+| UNIX 


| NFSv4.ACLs 


| NTFS-ACLs | NTFS 


.3+| Unified (nur für Infinite Volumes, in ONTAP 9.4 und älteren Versionen.) .3+| NFS oder SMB | Bits im NFSv3 Modus .2+| Unix 


| NFSv4.1 ACLs 


| NTFS-ACLs | NTFS 
|===
FlexVol Volumes unterstützen UNIX, NTFS und verschiedene Sicherheitsstile. Wenn der Sicherheitsstil gemischt oder vereinheitlicht ist, hängen die effektiven Berechtigungen vom Clienttyp ab, der die Berechtigungen zuletzt geändert hat, da Benutzer den Sicherheitsstil auf individueller Basis festlegen. Wenn der letzte Client, der die Berechtigungen geändert hat, ein NFSv3-Client war, sind die Berechtigungen UNIX NFSv3-Modus-Bits. Wenn der letzte Client ein NFSv4-Client war, sind die Berechtigungen NFSv4 ACLs. Wenn der letzte Client ein SMB-Client war, sind die Berechtigungen Windows NTFS ACLs.

Der Unified Security-Stil ist nur mit Infinite Volumes verfügbar, die in ONTAP 9.5 und neueren Versionen nicht mehr unterstützt werden. Weitere Informationen finden Sie unter xref:../flexgroup/index.html[Das Management von FlexGroup Volumes – Überblick].

Ab ONTAP 9.2 `show-effective-permissions` `vserver security file-directory` können Sie mit dem Parameter des Befehls effektive Berechtigungen anzeigen, die einem Windows- oder UNIX-Benutzer auf dem angegebenen Datei- oder Ordnerpfad gewährt wurden. Darüber hinaus `-share-name` können Sie mit dem optionalen Parameter die effektive Freigabeberechtigung anzeigen.

[NOTE]
====
ONTAP legt zunächst einige Standarddateiberechtigungen fest. Standardmäßig ist der effektive Sicherheitsstil auf allen Daten in UNIX-, gemischten und Unified Security-Volumes UNIX und der effektive Berechtigungstyp UNIX Mode Bits (0755, sofern nicht anders angegeben), bis er von einem Client gemäß dem Standardsicherheitsstil konfiguriert wird. Standardmäßig ist der effektive Sicherheitsstil auf allen Daten in NTFS-Sicherheitsstil-Volumes NTFS und hat eine ACL, die allen die vollständige Kontrolle erlaubt.

====