---
sidebar: sidebar 
permalink: networking/add_or_remove_ports_from_a_broadcast_domain97.html 
keywords: adding, add, create, creating, remove, removing, delete, deleting, port, broadcast, domain, reachability, repair, physical, switch, configuration, manually add or remove ports from a broadcast domain, network port broadcast-domain add-ports, network port broadcast-domain remove-ports, examples of adding and removing ports, move, moving, broadcast, domain, ipspace, remove ports from a broadcast domain, broadcast-domain remove-ports 
summary: Das manuelle Hinzufügen und Entfernen von Ports aus Broadcast-Domänen ist nicht erforderlich oder wird empfohlen 
---
= Hinzufügen oder Entfernen von Ports aus einer Broadcast-Domäne (ONTAP 9.7 und früher)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können Netzwerkports beim Erzeugen einer Broadcast-Domäne hinzufügen oder Ports zu einer bereits vorhandenen Broadcast-Domäne hinzufügen oder aus dieser entfernen. Damit können Sie alle Ports im Cluster effizient nutzen.

Wenn sich die Ports, die Sie der neuen Broadcast-Domäne hinzufügen möchten, bereits in einer anderen Broadcast-Domäne befinden, müssen Sie die Ports aus dieser Broadcast-Domäne entfernen, bevor Sie sie der neuen Broadcast-Domäne zuordnen.


NOTE: Diese Aufgabe ist relevant für ONTAP 9.0 - 9.7, nicht für ONTAP 9.8.

.Bevor Sie beginnen
* Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.
* Ports, die einer Broadcast-Domäne hinzugefügt werden sollen, dürfen nicht einer anderen Broadcast-Domäne angehören.
* Ports, die bereits zu einer Schnittstellengruppe gehören, können nicht einzeln einer Broadcast-Domäne hinzugefügt werden.


.Über diese Aufgabe
Folgende Regeln gelten beim Hinzufügen und Entfernen von Netzwerkports:

|===


| Wenn Ports hinzugefügt werden... | Wenn Ports entfernt... 


| Bei den Ports kann es sich um Netzwerkports, VLANs oder Interface Groups (iffrps) handeln. | K. A. 


| Die Ports werden der systemdefinierten Failover-Gruppe der Broadcast-Domäne hinzugefügt. | Die Ports werden von allen Failover-Gruppen in der Broadcast-Domäne entfernt. 


| Die MTU der Ports wird auf den in der Broadcast-Domäne festgelegten MTU-Wert aktualisiert. | Die MTU der Ports bleibt unverändert. 


| Der IPspace der Ports wird auf den IPspace-Wert der Broadcast-Domain aktualisiert. | Die Ports werden in den IP-Bereich 'Default' ohne Broadcast-Domain-Attribut verschoben. 
|===

NOTE: Wenn Sie den letzten Mitgliedsport einer Schnittstellengruppe mithilfe der entfernen `network port ifgrp remove-port` Der Befehl bewirkt, dass der Port der Schnittstellengruppe aus der Broadcast-Domäne entfernt wird, da in einer Broadcast-Domäne kein leerer Port für Schnittstellengruppen zulässig ist.

.Schritte
. Zeigen Sie die Ports an, die einer Broadcast-Domäne derzeit zugewiesen oder nicht zugewiesen werden. Verwenden Sie dazu das `network port show` Befehl.
. Hinzufügen oder Entfernen von Netzwerk-Ports aus der Broadcast-Domäne:
+
[cols="40,60"]
|===


| Ihr Ziel ist | Verwenden... 


 a| 
Fügen Sie Ports zu einer Broadcast-Domäne hinzu
 a| 
`network port broadcast-domain add-ports`



 a| 
Entfernen Sie Ports aus einer Broadcast-Domäne
 a| 
`network port broadcast-domain remove-ports`

|===
. Überprüfen Sie, ob die Ports der Broadcast-Domäne hinzugefügt oder entfernt wurden:
+
`network port show`



Weitere Informationen zu diesen Befehlen finden Sie unter http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9-Befehle"^].



== Beispiele für das Hinzufügen und Entfernen von Ports

Mit dem folgenden Befehl wird Port e0g am Node Cluster-1-01 und Port e0g am Node Cluster-1-02 zur Broadcast-Domäne bcast1 im Standard-IPspace hinzugefügt:

`cluster-1::> network port broadcast-domain add-ports -broadcast-domain bcast1 -ports cluster-1-01:e0g,cluster1-02:e0g`

Mit dem folgenden Befehl werden zwei Cluster-Ports zum Broadcast Domain Cluster im Cluster IPspace hinzugefügt:

`cluster-1::> network port broadcast-domain add-ports -broadcast-domain Cluster -ports cluster-2-03:e0f,cluster2-04:e0f -ipspace Cluster`

Mit dem folgenden Befehl wird Port e0e auf Node cluster1-01 aus Broadcast-Domäne bcast1 im Standard-IPspace entfernt:

`cluster-1::> network port broadcast-domain remove-ports -broadcast-domain bcast1 -ports cluster-1-01:e0e`
