---
sidebar: sidebar 
permalink: networking/change_the_mtu_value_for_ports_in_a_broadcast_domain.html 
keywords: modify, modifying, mtu, mtu_value, change, changing, broadcast, domain, ports, port, change the mtu value for ports in a broadcast domain 
summary: Ändern Sie den MTU-Wert für eine Broadcast-Domäne, um diesen Wert für alle Ports in der Broadcast-Domäne zu ändern. 
---
= Den MTU-Wert für Ports in einer ONTAP Broadcast-Domäne ändern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können den MTU-Wert für eine Broadcast-Domäne ändern, um den MTU-Wert für alle Ports in dieser Broadcast-Domäne zu ändern. Dies kann erfolgen, um Topologieänderungen zu unterstützen, die im Netzwerk vorgenommen wurden.


NOTE: Die Vorgehensweise zum Ändern des MTU-Werts für Broadcast-Domänenports unterscheidet sich in ONTAP 9.7 und früheren Versionen. Falls eine Änderung des MTU-Werts für Broadcast-Domänenports in einem Netzwerk mit ONTAP 9.7 oder einer früheren Version erforderlich ist, siehe link:https://docs.netapp.com/us-en/ontap-system-manager-classic/networking-bd/change_the_mtu_value_for_ports_in_a_broadcast_domain97.html["Den MTU-Wert für Ports in einer Broadcast-Domäne (ONTAP 9.7 und früher) ändern"^].

[role="tabbed-block"]
====
.System Manager
--
Ab ONTAP 9.12.0 können Sie den System Manager verwenden, um den MTU-Wert für eine Broadcast-Domäne zu ändern und so den MTU-Wert für alle Ports in dieser Broadcast-Domäne zu ändern.

.Schritte
. Wählen Sie *Network > Broadcast Domains*.
. Wählen Sie im Abschnitt *Broadcast Domains* den Namen der Broadcast Domain aus, für die Sie den MTU-Wert ändern möchten.
. Es erscheint eine Bestätigungsabfrage, ob Sie den MTU-Wert für alle Ports in der Broadcast-Domäne ändern möchten. Klicken Sie auf *Yes*, um die Änderung durchzuführen.
. Passen Sie den MTU-Wert nach Bedarf an und speichern Sie Ihre Änderungen.
+
Das System wendet den neuen MTU-Wert auf alle Ports in der Broadcast-Domäne an, was zu einer kurzen Unterbrechung des Datenverkehrs über diese Ports führt.



--
.CLI
--
.Bevor Sie beginnen
Der MTU-Wert muss mit dem Wert aller Geräte übereinstimmen, die mit diesem Layer-2-Netzwerk verbunden sind, mit Ausnahme des e0M Ports, der den Management-Datenverkehr verarbeitet.

.Über diese Aufgabe
Die Änderung des MTU-Werts führt zu einer kurzen Unterbrechung des Datenverkehrs über die betroffenen Ports. Das System zeigt eine Eingabeaufforderung an, die Sie mit *y* bestätigen müssen, um die MTU-Änderung durchzuführen.

.Schritt
Den MTU-Wert für alle Ports in einer Broadcast-Domäne ändern:

[listing]
----
network port broadcast-domain modify -broadcast-domain <broadcast_domain_name> -mtu <mtu_value> [-ipspace <ipspace_name>]
----
Wo:

* `broadcast_domain` ist der Name der Broadcast-Domäne.
* `mtu` ist die MTU-Größe für IP-Pakete; 1500 und 9000 sind typische Werte.
* `ipspace` ist der Name des IPspace, in dem sich diese Broadcast-Domäne befindet. Der „Default“ IPspace wird verwendet, sofern Sie für diese Option keinen Wert angeben.
+
Der folgende Befehl ändert die MTU auf 9000 für alle Ports in der Broadcast-Domäne bcast1:

+
[listing]
----
network port broadcast-domain modify -broadcast-domain <Default-1> -mtu < 9000 >
Warning: Changing broadcast domain settings will cause a momentary data-serving interruption.
Do you want to continue? {y|n}: <y>
----


--
====
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/network-port-broadcast-domain-modify.html["network port Broadcast-Domäne ändern"^]

