---
sidebar: sidebar 
permalink: networking/commands_for_managing_firewall_service_and_policies.html 
keywords: manage, managing, firewall, fire, wall, service, policy, policies, commands for managing firewall service and policies, system services firewall, system services firewall policy, network interface modify, system services firewall modify, system services firewall show, system services firewall policy create, network interface modify -lif lifname -firewall-policy, system services firewall policy modify, system services firewall policy show, system services firewall policy clone, system services firewall policy delete 
summary: Verwalten des Firewallservice 
---
= Befehle zum Management von Firewallservice und -Richtlinien
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können den `system services firewall` Firewall-Service mit den Befehlen managen, die `system services firewall policy` Befehle zum Verwalten von Firewallrichtlinien und den `network interface modify` Befehl zum Verwalten von Firewalleinstellungen für LIFs.

|===


| Ihr Ziel ist | Befehl 


 a| 
Aktivieren oder Deaktivieren des Firewallservice
 a| 
`system services firewall modify`



 a| 
Zeigt die aktuelle Konfiguration für den Firewallservice an
 a| 
`system services firewall show`



 a| 
Erstellen Sie eine Firewallrichtlinie oder fügen Sie einen Service zu einer vorhandenen Firewallrichtlinie hinzu
 a| 
`system services firewall policy create`



 a| 
Wenden Sie eine Firewallrichtlinie auf ein LIF an
 a| 
`network interface modify -lif lifname -firewall-policy`



 a| 
Ändern Sie die IP-Adressen und Netmasks, die einer Firewallrichtlinie zugeordnet sind
 a| 
`system services firewall policy modify`



 a| 
Zeigt Informationen zu Firewallrichtlinien an
 a| 
`system services firewall policy show`



 a| 
Erstellen Sie eine neue Firewallrichtlinie als exakte Kopie einer vorhandenen Richtlinie
 a| 
`system services firewall policy clone`



 a| 
Löschen Sie eine Firewallrichtlinie, die von keinem LIF verwendet wird
 a| 
`system services firewall policy delete`

|===
Weitere Informationen finden Sie `system services firewall` `system services firewall policy` `network interface modify` in den man-Pages für die Befehle , und in link:http://docs.netapp.com/us-en/ontap-cli["Die ONTAP 9-Befehlsreferenz"^].
