---
sidebar: sidebar 
permalink: networking/commands_for_managing_failover_groups_and_policies.html 
keywords: manage, managing, failover, fail, over, group, policy, policies, groups, commands for managing failover groups and policies, network interface failover-groups, network interface modify, network interface failover-groups add-targets, network interface failover-groups remove-targets, network interface failover-groups modify, network interface modify -failover-group -failover-policy, network interface failover-groups show, rename, delete 
summary: Failover-Gruppen verwalten. 
---
= ONTAP Befehle zur Verwaltung von Failover-Gruppen und Richtlinien
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können die  `network interface failover-groups` Befehle zur Verwaltung von Failover-Gruppen verwenden. Der  `network interface modify` Befehl dient zur Verwaltung der Failover-Gruppen und Failover-Richtlinien, die auf eine LIF angewendet werden.

|===


| Wenn Sie möchten... | Verwenden Sie diesen Befehl... 


 a| 
Netzwerk-Ports zu einer Failover-Gruppe hinzufügen
 a| 
`network interface failover-groups add-targets`



 a| 
Netzwerkports aus einer Failover-Gruppe entfernen
 a| 
`network interface failover-groups remove-targets`



 a| 
Netzwerkports in einer Failover-Gruppe ändern
 a| 
`network interface failover-groups modify`



 a| 
Aktuelle Failover-Gruppen werden angezeigt
 a| 
`network interface failover-groups show`



 a| 
Failover auf einem LIF konfigurieren
 a| 
`network interface modify -failover-group -failover-policy`



 a| 
Die Failover-Gruppe und die Failover-Richtlinie, die von jedem LIF verwendet werden, anzeigen
 a| 
`network interface show -fields failover-group, failover-policy`



 a| 
Umbenennen einer Failover-Gruppe
 a| 
`network interface failover-groups rename`



 a| 
Eine Failover-Gruppe löschen
 a| 
`network interface failover-groups delete`

|===

NOTE: Das Ändern einer Failover-Gruppe, sodass sie für keinen LIF im Cluster ein gültiges Failover-Ziel bereitstellt, kann zu einem Ausfall führen, wenn ein LIF versucht, ein Failover durchzuführen.

.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["Netzwerkschnittstelle"^]

