---
sidebar: sidebar 
permalink: networking/commands_for_managing_snmp.html 
keywords: snmp, traps, traphosts, trap, traphost, manage, managing, users, user, configure, configuring, modify, modifying, set, setting, event, command, system snmp, security, options -option-name snmp.enable -option-value on, options -option-name snmp.enable -option-value off, commands for managing snmp, commands for managing snmp v1, v2c, and v3 users, commands for providing contact and location information, commands for managing SNMP communities, command for displaying snmp option values, commands for managing snmp traps and traphosts, commands for managing events related to snmp traps, system snmp, security login create, security snmpusers and security login show -application snmp, security login create, security login delete, security snmpusers and security login show -application snmp, security login modify, system snmp contact, system snmp location, system snmp community add, system snmp community delete, system snmp community show, system snmp show 
summary: SNMP, SNMP-Benutzer, Traps, Trap-Ereignisse und Trap-Hosts verwalten. 
---
= ONTAP Befehle zur Verwaltung von SNMP, Traps und Traphosts
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die  `system snmp` Befehle können zur Verwaltung von SNMP, Traps und Traphosts verwendet werden. Die  `security` Befehle können zur Verwaltung von SNMP Benutzern pro SVM verwendet werden. Die  `event` Befehle können zur Verwaltung von Ereignissen im Zusammenhang mit SNMP Traps verwendet werden.



[[commands-for-configuring-snmp]]
== Befehle zur Konfiguration von SNMP

|===


| Wenn Sie möchten... | Verwenden Sie diesen Befehl... 


 a| 
SNMP auf dem Cluster aktivieren
 a| 
`options -option-name snmp.enable -option-value on`

Der SNMP-Dienst muss in der Management-Firewall-Richtlinie (mgmt) zugelassen sein. Ob SNMP zugelassen ist, lässt sich mit dem Befehl `system services firewall policy show` überprüfen.



 a| 
SNMP auf dem Cluster deaktivieren
 a| 
`options -option-name snmp.enable -option-value off`

|===


[[commands-for-managing-snmp-v1-v2c-and-v3-users]]
== Befehle zur Verwaltung von SNMP v1, v2c und v3 Benutzern

|===


| Wenn Sie möchten... | Verwenden Sie diesen Befehl... 


 a| 
SNMP-Benutzer konfigurieren
 a| 
`security login create`



 a| 
SNMP-Benutzer anzeigen
 a| 
`security snmpusers` und `security login show -application snmp`



 a| 
SNMP-Benutzer löschen
 a| 
`security login delete`



 a| 
Den Namen der Zugriffskontrollrolle einer Anmeldemethode für SNMP-Benutzer ändern
 a| 
`security login modify`

|===


[[commands-for-providing-contact-and-location-information]]
== Befehle zur Bereitstellung von Kontakt- und Standortinformationen

|===


| Wenn Sie möchten... | Verwenden Sie diesen Befehl... 


 a| 
Kontaktdaten des Clusters anzeigen oder ändern
 a| 
`system snmp contact`



 a| 
Standortdetails des Clusters anzeigen oder ändern
 a| 
`system snmp location`

|===


[[commands-for-managing-snmp-communities]]
== Befehle zur Verwaltung von SNMP-Communities

|===


| Wenn Sie möchten... | Verwenden Sie diesen Befehl... 


 a| 
Eine schreibgeschützte (ro) Community für eine SVM oder für alle SVMs im Cluster hinzufügen
 a| 
`system snmp community add`



 a| 
Eine Community oder alle Communities löschen
 a| 
`system snmp community delete`



 a| 
Anzeige der Liste aller Communities
 a| 
`system snmp community show`

|===
Da SVMs nicht Teil des SNMP-Standards sind, müssen Abfragen von Daten-LIFs die NetApp Root-OID (1.3.6.1.4.1.789) enthalten, zum Beispiel  `snmpwalk -v 2c -c snmpNFS 10.238.19.14 1.3.6.1.4.1.789`.



[[command-for-displaying-snmp-option-values]]
== Befehl zum Anzeigen von SNMP Optionswerten

|===


| Wenn Sie möchten... | Verwenden Sie diesen Befehl... 


 a| 
Zeigt die aktuellen Werte aller SNMP-Optionen an, einschließlich Cluster-Kontakt, Kontaktstandort, ob der Cluster für das Senden von Traps konfiguriert ist, die Liste der Traphosts sowie die Liste der Communities und des Zugriffskontrolltyps.
 a| 
`system snmp show`

|===


[[commands-for-managing-snmp-traps-and-traphosts]]
== Befehle zur Verwaltung von SNMP-Traps und Traphosts

|===


| Wenn Sie möchten... | Verwenden Sie diesen Befehl... 


 a| 
SNMP-Traps, die vom Cluster gesendet werden, aktivieren
 a| 
`system snmp init -init 1`



 a| 
SNMP-Traps, die vom Cluster gesendet werden, deaktivieren
 a| 
`system snmp init -init 0`



 a| 
Einen Traphost hinzufügen, der SNMP-Benachrichtigungen für bestimmte Ereignisse im Cluster empfängt
 a| 
`system snmp traphost add`



 a| 
Einen Traphost löschen
 a| 
`system snmp traphost delete`



 a| 
Anzeige der Liste der Traphosts
 a| 
`system snmp traphost show`

|===


[[commands-for-managing-events-related-to-snmp-traps]]
== Befehle zur Verwaltung von Ereignissen im Zusammenhang mit SNMP-Traps

|===


| Wenn Sie möchten... | Verwenden Sie diesen Befehl... 


 a| 
Zeigt die Ereignisse an, für die SNMP Traps (integriert) generiert werden
 a| 
`event route show`

Der  `-snmp-support true`Parameter zeigt nur SNMP-bezogene Ereignisse an.

Mit dem  `instance -messagename <message>` Parameter wird eine detaillierte Beschreibung angezeigt, warum ein Ereignis aufgetreten sein könnte, sowie eine mögliche Korrekturmaßnahme.

Das Routing einzelner SNMP-Trap-Ereignisse zu bestimmten Traphost-Zielen wird nicht unterstützt. Alle SNMP-Trap-Ereignisse werden an alle Traphost-Ziele gesendet.



 a| 
Eine Liste der SNMP-Trap-Verlaufsdatensätze wird angezeigt, also Ereignisbenachrichtigungen, die an SNMP-Traps gesendet wurden.
 a| 
`event snmphistory show`



 a| 
Löschen eines SNMP Trap Verlaufseintrags
 a| 
`event snmphistory delete`

|===
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+snmp["system snmp"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-snmpusers.html["security snmpusers"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security["Sicherheit"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=event["Ereignis"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+login["Security Login"^]

