---
sidebar: sidebar 
permalink: networking/commands_for_managing_failover_groups_and_policies.html 
keywords: manage, managing, failover, fail, over, group, policy, policies, groups, commands for managing failover groups and policies, network interface failover-groups, network interface modify, network interface failover-groups add-targets, network interface failover-groups remove-targets, network interface failover-groups modify, network interface modify -failover-group -failover-policy, network interface failover-groups show, rename, delete 
summary: Management von Failover-Gruppen 
---
= ONTAP-Befehle zum Managen von Failover-Gruppen und Richtlinien
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können die `network interface failover-groups` Befehle zum Verwalten von Failover-Gruppen verwenden. Sie verwenden den `network interface modify` Befehl zum Managen der Failover-Gruppen und Failover-Richtlinien, die auf eine LIF angewendet werden.

|===


| Ihr Ziel ist | Befehl 


 a| 
Fügen Sie Netzwerkports zu einer Failover-Gruppe hinzu
 a| 
`network interface failover-groups add-targets`



 a| 
Entfernen Sie Netzwerkanschlüsse aus einer Failover-Gruppe
 a| 
`network interface failover-groups remove-targets`



 a| 
Ändern Sie Netzwerkports in einer Failover-Gruppe
 a| 
`network interface failover-groups modify`



 a| 
Zeigt die aktuellen Failover-Gruppen an
 a| 
`network interface failover-groups show`



 a| 
Konfigurieren Sie den Failover auf einem LIF
 a| 
`network interface modify -failover-group -failover-policy`



 a| 
Zeigen Sie die Failover-Gruppe und die Failover-Richtlinie an, die von den einzelnen LIFs verwendet werden
 a| 
`network interface show -fields failover-group, failover-policy`



 a| 
Benennen Sie eine Failover-Gruppe um
 a| 
`network interface failover-groups rename`



 a| 
Löschen einer Failover-Gruppe
 a| 
`network interface failover-groups delete`

|===

NOTE: Das Ändern einer Failover-Gruppe, sodass sie kein gültiges Failover-Ziel für eine LIF im Cluster bietet, kann zu einem Ausfall führen, wenn ein LIF einen Failover versucht.

.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["Netzwerkschnittstelle"^]

