---
sidebar: sidebar 
permalink: networking/configure_network_security_using_federal_information_processing_standards_fips.html 
keywords: fips 140-2, compliant, ssl, connections, tlsv1.2, tlsv1.1, tlsv1, enable fips, disable fips, compliance status, SSL 
summary: Federal Information Processing Standards 140-2-konform für alle SSL-Verbindungen. 
---
= ONTAP Netzwerksicherheit mit FIPS für alle SSL-Verbindungen konfigurieren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP erfüllt die Anforderungen des Federal Information Processing Standards (FIPS) 140-2 für alle SSL-Verbindungen. Es besteht die Möglichkeit, den SSL FIPS-Modus zu aktivieren oder zu deaktivieren, SSL-Protokolle global festzulegen und schwache Verschlüsselungsverfahren innerhalb von ONTAP zu deaktivieren.

Standardmäßig ist SSL auf ONTAP so konfiguriert, dass die FIPS-Konformität deaktiviert ist und die folgenden TLS-Protokolle aktiviert sind:

* TLSv1.3 (beginnend mit ONTAP 9.11.1)
* TLSv1.2


In früheren ONTAP Versionen waren die folgenden TLS-Protokolle standardmäßig aktiviert:

* TLSv1.1 (standardmäßig deaktiviert ab ONTAP 9.12.1)
* TLSv1 (ab ONTAP 9.8 standardmäßig deaktiviert)


Wenn der SSL-FIPS-Modus aktiviert ist, verwendet die SSL-Kommunikation von ONTAP zu externen Client- oder Serverkomponenten außerhalb von ONTAP FIPS-konforme Verschlüsselung für SSL.

Wenn Administratorkonten mit einem öffentlichen SSH-Schlüssel auf SVMs zugreifen sollen, muss sichergestellt werden, dass der Host-Algorithmus unterstützt wird, bevor der SSL FIPS-Modus aktiviert wird.

*Hinweis:* Die Unterstützung für Host-Key-Algorithmen hat sich in ONTAP 9.11.1 und späteren Versionen geändert.

[cols="30,30,30"]
|===


| ONTAP Release | Unterstützte Schlüsseltypen | Nicht unterstützte Schlüsseltypen 


 a| 
9.11.1 und später
 a| 
ecdsa-sha2-nistp256
 a| 
rsa-sha2-512 + rsa-sha2-256 + ssh-ed25519 + ssh-dss + ssh-rsa



 a| 
9.10.1 und früher
 a| 
ecdsa-sha2-nistp256 + ssh-ed25519
 a| 
ssh-dss + ssh-rsa

|===
Sie müssen bestehende SSH-Public-Key-Konten so umkonfigurieren, dass sie einen unterstützten Schlüsseltyp verwenden, bevor Sie FIPS aktivieren, oder die Administratorauthentifizierung schlägt fehl.

Weitere Informationen finden sich unter link:../authentication/enable-ssh-public-key-accounts-task.html["SSH-Konten mit öffentlichen Schlüsseln aktivieren"].

ONTAP 9.18.1 führt die Unterstützung für die Post-Quanten-Kryptografiealgorithmen ML-KEM, ML-DSA und SLH-DSA für SSL ein und bietet damit eine zusätzliche Sicherheitsebene gegen potenzielle zukünftige Quantencomputerangriffe. Diese Algorithmen sind nur verfügbar, wenn <<FIPS deaktivieren,FIPS ist deaktiviert>>. Post-Quanten-Kryptografiealgorithmen werden ausgehandelt, wenn FIPS deaktiviert ist und der Peer sie unterstützt.



[[enable-fips]]
== FIPS aktivieren

Es wird empfohlen, dass alle sicheren Benutzer ihre Sicherheitskonfiguration unmittelbar nach der Systeminstallation oder -aktualisierung anpassen. Wenn der SSL-FIPS-Modus aktiviert ist, verwendet die SSL-Kommunikation von ONTAP zu externen Client- oder Serverkomponenten außerhalb von ONTAP FIPS-konforme Verschlüsselung für SSL.


NOTE: Wenn FIPS aktiviert ist, kann kein Zertifikat mit einer RSA-Schlüssellänge von 4096 installiert oder erstellt werden.

.Schritte
. Wechsel zum erweiterten Berechtigungslevel:
+
`set -privilege advanced`

. FIPS aktivieren:
+
`security config modify * -is-fips-enabled true`

. Wenn Sie zur Fortsetzung aufgefordert werden, geben Sie Folgendes ein: `y`
. Ab ONTAP 9.9.1 ist kein Neustart mehr erforderlich. Wenn Sie ONTAP 9.8 oder früher verwenden, starten Sie jeden Knoten im Cluster einzeln manuell neu.


.Beispiel
Wenn Sie ONTAP 9.9.1 oder eine neuere Version verwenden, wird Ihnen diese Warnmeldung nicht angezeigt.

....
security config modify -is-fips-enabled true

Warning: This command will enable FIPS compliance and can potentially cause some non-compliant components to fail. MetroCluster and Vserver DR require FIPS to be enabled on both sites in order to be compatible.
Do you want to continue? {y|n}: y

Warning: When this command completes, reboot all nodes in the cluster. This is necessary to prevent components from failing due to an inconsistent security configuration state in the cluster. To avoid a service outage, reboot one node at a time and wait for it to completely initialize before rebooting the next node. Run "security config status show" command to monitor the reboot status.
Do you want to continue? {y|n}: y
....
Weitere Informationen zu  `security config modify` und zur Konfiguration des SSL FIPS-Modus finden Sie in der link:https://docs.netapp.com/us-en/ontap-cli/security-config-modify.html["ONTAP-Befehlsreferenz"^].



[[disable-fips]]
== FIPS deaktivieren

Ab ONTAP 9.18.1 unterstützt SSL in ONTAP die Post-Quanten-Computing-Kryptografie-Algorithmen ML-KEM, ML-DSA und SLH-DSA. Diese Algorithmen sind nur verfügbar, wenn FIPS deaktiviert ist und der Peer sie unterstützt.

.Schritte
. Wechsel zum erweiterten Berechtigungslevel:
+
`set -privilege advanced`

. FIPS wird deaktiviert durch Eingabe von:
+
`security config modify -is-fips-enabled false -interface SSL`

. Wenn Sie zur Fortsetzung aufgefordert werden,  `y` eingeben.
. Ab ONTAP 9.9.1 ist kein Neustart mehr erforderlich. Wenn ONTAP 9.8 oder eine frühere Version verwendet wird, ist ein manueller Neustart jedes Knotens im Cluster erforderlich.


Wenn Sie das SSLv3-Protokoll verwenden müssen, müssen Sie FIPS mit dem oben beschriebenen Verfahren deaktivieren. SSLv3 kann nur aktiviert werden, wenn FIPS deaktiviert ist.

Sie können SSLv3 mit dem folgenden Befehl aktivieren. Wenn Sie ONTAP 9.9.1 oder später verwenden, wird keine Warnmeldung angezeigt.

....
security config modify -supported-protocols SSLv3

Warning: Enabling the SSLv3 protocol may reduce the security of the interface, and is not recommended.
Do you want to continue? {y|n}: y

Warning: When this command completes, reboot all nodes in the cluster. This is necessary to prevent components from failing due to an inconsistent security configuration state in the cluster. To avoid a service outage, reboot one node at a time and wait for it to completely initialize before rebooting the next node. Run "security config status show" command to monitor the reboot status.
Do you want to continue? {y|n}: y
....


[[view-fips-compliance-status]]
== FIPS-Konformitätsstatus anzeigen

Es ist ersichtlich, ob der gesamte Cluster mit den aktuellen Sicherheitskonfigurationseinstellungen arbeitet.

.Schritte
. Wenn Sie ONTAP 9.8 oder früher verwenden, starten Sie jeden Knoten im Cluster einzeln manuell neu.
. Aktueller Compliance-Status:
+
`security config show`

+
....
cluster1::> security config show
Cluster    Supported
FIPS Mode  Protocols Supported Cipher Suites
---------- --------- ----------------------------------------------------------
false      TLSv1.3,  TLS_RSA_WITH_AES_128_CCM, TLS_RSA_WITH_AES_128_CCM_8,
           TLSv1.2   TLS_RSA_WITH_AES_128_GCM_SHA256,
                     TLS_RSA_WITH_AES_128_CBC_SHA,
                     TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_256_CCM,
                     TLS_RSA_WITH_AES_256_CCM_8,
                     ...
....
+
Weitere Informationen zu  `security config show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/security-config-show.html["ONTAP-Befehlsreferenz"^].



.Verwandte Informationen
* link:https://csrc.nist.gov/pubs/fips/203/final["FIPS 203: Standard für einen Modul-Gitter-basierten Schlüsselkapselungsmechanismus (ML-KEM)"^]
* link:https://csrc.nist.gov/pubs/fips/204/final["FIPS 204: Modulgitter-basierter digitaler Signaturstandard (ML-DSA)"^]
* link:https://csrc.nist.gov/pubs/fips/205/final["FIPS 205: Stateless Hash-Based Digital Signature Standard (SLH-DSA)"^]
* link:../networking/configure-tls-offload.html["TLS-Hardware-Offload konfigurieren"]

