---
sidebar: sidebar 
permalink: networking/configure_network_security_using_federal_information_processing_standards_fips.html 
keywords: fips 140-2, compliant, ssl, connections, tlsv1.2, tlsv1.1, tlsv1, enable fips, disable fips, compliance status, SSL 
summary: 'Die Federal Information Processing Standards (FIPS) 140-2 erfüllen alle SSL-Verbindungen' 
---
= Konfigurieren Sie die ONTAP-Netzwerksicherheit mit FIPS für alle SSL-Verbindungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP erfüllt die Anforderungen des Federal Information Processing Standards (FIPS) 140-2 für alle SSL-Verbindungen.  Sie können den SSL-FIPS-Modus ein- und ausschalten, SSL-Protokolle global festlegen und alle schwachen Verschlüsselungsverfahren innerhalb von ONTAP deaktivieren.

Bei SSL auf ONTAP ist die FIPS-Compliance standardmäßig deaktiviert und die folgenden TLS-Protokolle aktiviert:

* TLSv1.3 (ab ONTAP 9.11.1)
* TLSv1.2


In früheren ONTAP-Versionen waren standardmäßig die folgenden TLS-Protokolle aktiviert:

* TLSv1.1 (standardmäßig deaktiviert ab ONTAP 9.12.1)
* TLSv1 (standardmäßig deaktiviert, beginnend mit ONTAP 9.8)


Wenn der SSL-FIPS-Modus aktiviert ist, wird die SSL-Kommunikation von ONTAP mit externen Client- oder Serverkomponenten außerhalb von ONTAP FIPS-konforme Crypto for SSL verwendet.

Wenn Administratorkonten auf SVMs mit einem öffentlichen SSH-Schlüssel zugreifen möchten, müssen Sie vor Aktivierung des SSL-FIPS-Modus sicherstellen, dass der Host Key-Algorithmus unterstützt wird.

*Hinweis:* die Unterstützung des Host Key Algorithmus hat sich in ONTAP 9.11.1 und späteren Versionen geändert.

[cols="30,30,30"]
|===


| Version von ONTAP | Unterstützte Schlüsseltypen | Nicht unterstützte Schlüsseltypen 


 a| 
9.11.1 und höher
 a| 
ecdsa-sha2-nistp256
 a| 
rsa-sha2-512 + rsa-sha2-256 + ssh-ed25519 + ssh-dss + ssh-rsa



 a| 
9.10.1 und früher
 a| 
ecdsa-sha2-nistp256 + ssh-ed25519
 a| 
ssh-dss + SSH-rsa

|===
Bestehende öffentliche SSH-Konten ohne die unterstützten Schlüsselalgorithmen müssen vor der Aktivierung von FIPS mit einem unterstützten Schlüsseltyp neu konfiguriert werden oder die Administratorauthentifizierung schlägt fehl.

Weitere Informationen finden Sie unter link:../authentication/enable-ssh-public-key-accounts-task.html["Aktivieren Sie SSH-Konten für öffentliche Schlüssel"].

ONTAP 9.18.1 führt die Unterstützung für die Post-Quantum-Computing-Kryptographiealgorithmen ML-KEM, ML-DSA und SLH-DSA für SSL ein und bietet damit eine zusätzliche Sicherheitsebene gegen potenzielle zukünftige Quantencomputerangriffe.  Diese Algorithmen sind nur verfügbar, wenn<<FIPS deaktivieren,FIPS ist deaktiviert>> Die  Post-Quanten-Kryptographiealgorithmen werden ausgehandelt, wenn FIPS deaktiviert ist und der Peer sie unterstützt.



== Aktivieren Sie FIPS

Es wird empfohlen, dass alle sicheren Benutzer ihre Sicherheitskonfiguration unmittelbar nach der Installation oder Aktualisierung des Systems anpassen. Wenn der SSL-FIPS-Modus aktiviert ist, wird die SSL-Kommunikation von ONTAP mit externen Client- oder Serverkomponenten außerhalb von ONTAP FIPS-konforme Crypto for SSL verwendet.


NOTE: Wenn FIPS aktiviert ist, können Sie kein Zertifikat mit einer RSA-Schlüssellänge von 4096 installieren oder erstellen.

.Schritte
. Ändern Sie die erweiterte Berechtigungsebene:
+
`set -privilege advanced`

. FIPS aktivieren:
+
`security config modify * -is-fips-enabled true`

. Wenn Sie dazu aufgefordert werden, fortzufahren, geben Sie ein `y`
. Ab ONTAP 9.9.1 ist kein Neustart erforderlich.  Wenn Sie ONTAP 9.8 oder früher ausführen, starten Sie jeden Knoten im Cluster einzeln manuell neu.


.Beispiel
Wenn ONTAP 9.9.1 oder höher ausgeführt wird, wird die Warnmeldung nicht angezeigt.

....
security config modify -is-fips-enabled true

Warning: This command will enable FIPS compliance and can potentially cause some non-compliant components to fail. MetroCluster and Vserver DR require FIPS to be enabled on both sites in order to be compatible.
Do you want to continue? {y|n}: y

Warning: When this command completes, reboot all nodes in the cluster. This is necessary to prevent components from failing due to an inconsistent security configuration state in the cluster. To avoid a service outage, reboot one node at a time and wait for it to completely initialize before rebooting the next node. Run "security config status show" command to monitor the reboot status.
Do you want to continue? {y|n}: y
....
Weitere Informationen zur `security config modify` Konfiguration des SSL-FIPS-Modus finden Sie in link:https://docs.netapp.com/us-en/ontap-cli/security-config-modify.html["ONTAP-Befehlsreferenz"^].



== FIPS deaktivieren

Ab ONTAP 9.18.1 unterstützt SSL in ONTAP die Post-Quantum-Computing-Kryptographiealgorithmen ML-KEM, ML-DSA und SLH-DSA.  Diese Algorithmen sind nur verfügbar, wenn FIPS deaktiviert ist und der Peer sie unterstützt.

.Schritte
. Ändern Sie die erweiterte Berechtigungsebene:
+
`set -privilege advanced`

. Deaktivieren Sie FIPS, indem Sie Folgendes eingeben:
+
`security config modify -is-fips-enabled false`

. Wenn Sie aufgefordert werden, fortzufahren, geben `y`Sie .
. Ab ONTAP 9.9.1 ist kein Neustart erforderlich.  Wenn Sie ONTAP 9.8 oder früher ausführen, starten Sie jeden Knoten im Cluster manuell neu.


Wenn Sie das SSLv3-Protokoll verwenden müssen, müssen Sie FIPS mit dem oben beschriebenen Verfahren deaktivieren.  SSLv3 kann nur aktiviert werden, wenn FIPS deaktiviert ist.

Sie können SSLv3 mit folgendem Befehl aktivieren.  Wenn Sie ONTAP 9.9.1 oder eine neuere Version verwenden, wird Ihnen diese Warnmeldung nicht angezeigt.

....
security config modify -supported-protocols SSLv3

Warning: Enabling the SSLv3 protocol may reduce the security of the interface, and is not recommended.
Do you want to continue? {y|n}: y

Warning: When this command completes, reboot all nodes in the cluster. This is necessary to prevent components from failing due to an inconsistent security configuration state in the cluster. To avoid a service outage, reboot one node at a time and wait for it to completely initialize before rebooting the next node. Run "security config status show" command to monitor the reboot status.
Do you want to continue? {y|n}: y
....


== Den FIPS-Compliance-Status anzeigen

Sie sehen, ob im gesamten Cluster die aktuellen Sicherheitseinstellungen ausgeführt werden.

.Schritte
. Wenn Sie ONTAP 9.8 oder früher ausführen, starten Sie jeden Knoten im Cluster einzeln manuell neu.
. Den aktuellen Compliance-Status anzeigen:
+
`security config show`

+
....
cluster1::> security config show
Cluster    Supported
FIPS Mode  Protocols Supported Cipher Suites
---------- --------- ----------------------------------------------------------
false      TLSv1.3,  TLS_RSA_WITH_AES_128_CCM, TLS_RSA_WITH_AES_128_CCM_8,
           TLSv1.2   TLS_RSA_WITH_AES_128_GCM_SHA256,
                     TLS_RSA_WITH_AES_128_CBC_SHA,
                     TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_256_CCM,
                     TLS_RSA_WITH_AES_256_CCM_8,
                     ...
....
+
Erfahren Sie mehr über `security config show` in der link:https://docs.netapp.com/us-en/ontap-cli/security-config-show.html["ONTAP-Befehlsreferenz"^].



.Verwandte Informationen
* link:https://csrc.nist.gov/pubs/fips/203/final["FIPS 203: Standard für einen modulgitterbasierten Schlüsselkapselungsmechanismus (ML-KEM)"^]
* link:https://csrc.nist.gov/pubs/fips/204/final["FIPS 204: Modulgitterbasierter digitaler Signaturstandard (ML-DSA)"^]
* link:https://csrc.nist.gov/pubs/fips/205/final["FIPS 205: Stateless Hash-Based Digital Signature Standard (SLH-DSA)"^]

