---
sidebar: sidebar 
permalink: networking/configure_qos_marking_cluster_administrators_only_overview.html 
keywords: quality, service, qos, marking, network, traffic, DSCP, IP, IPspace, protocol, NFS, SMB, iSCSI, SnapMirror, NDMP, FTP, HTTP, HTTPS, SSH, Telnet, SNMP 
summary: Mit der QoS-Kennzeichnung können Sie verschiedene Datenverkehrstypen basierend auf den Netzwerkbedingungen priorisieren, um die Netzwerkressourcen effektiv zu nutzen. 
---
= Erfahren Sie mehr über ONTAP-Netzwerk Quality of Service (QoS)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mithilfe der Markierung für die Netzwerkqualität (Quality of Service, QoS) können Sie verschiedene Datenverkehrstypen basierend auf den Netzwerkbedingungen priorisieren, um die Netzwerkressourcen effektiv zu nutzen. Sie können den differenzierten Service Code Point (DSCP)-Wert der ausgehenden IP-Pakete für die unterstützten Traffic-Typen pro IPspace festlegen.



== DSCP-Kennzeichnung für UC-Konformität

Sie können die Markierung des differenzierten Dienstcodepunktes (DSCP) für ausgehenden (ausgehenden) IP-Paketverkehr für ein bestimmtes Protokoll mit einem Standard- oder vom Benutzer bereitgestellten DSCP-Code aktivieren. Die DSCP-Kennzeichnung ist ein Mechanismus zur Klassifizierung und Verwaltung des Netzwerkdatenverkehrs und ist eine Komponente der Unified Capability (UC)-Compliance.

Die DSCP-Markierung (auch bekannt als _QoS-Markierung_ oder _Quality of Service-Markierung_) wird durch die Bereitstellung eines IPspace-, Protokoll- und DSCP-Wertes aktiviert. Die Protokolle, auf die DSCP-Kennzeichnung angewendet werden kann, sind NFS, SMB, iSCSI, SnapMirror, NDMP, FTP, HTTP/HTTPS, SSH, Telnet und SNMP

Wenn Sie keinen DSCP-Wert angeben, wenn Sie die DSCP-Markierung für ein bestimmtes Protokoll aktivieren, wird ein Standardwert verwendet:

* Der Standardwert für Datenprotokolle/Datenverkehr ist 0x0A (10).
* Der Standardwert für Steuerungsprotokolle/-Verkehr ist 0x30 (48).

