---
sidebar: sidebar 
permalink: networking/configure_failover_groups_and_policies_for_lifs_overview.html 
keywords: lif, failover, fail, over, target, automatic, automatically, port, link, failure, group, broadcast, domain, lif failover is the automatic migration of a lif to a different network port in response to a link failure, configure failover groups and policies for lifs overview, network interface show -failover 
summary: LIF-Failover ist die automatische Migration eines LIF auf einen anderen Netzwerkport als Reaktion auf einen Linkausfall. 
---
= Informationen zum LIF-Failover in ONTAP Netzwerken
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
LIF-Failover bezeichnet die automatische Migration eines LIF auf einen anderen Netzwerkport als Reaktion auf einen Verbindungsfehler am aktuellen Port des LIF. Dies ist eine Schlüsselkomponente für die Hochverfügbarkeit der Verbindungen zu SVMs. Die Konfiguration des LIF-Failover umfasst das Erstellen einer Failover-Gruppe, das Anpassen des LIF an die Verwendung der Failover-Gruppe und das Festlegen einer Failover-Richtlinie.

LIF-Failover mithilfe von Failover-Gruppen wird für SAN-Protokoll-LIFs nicht unterstützt. Informationen dazu link:../san-admin/multipath-automatic-lif-failover-support.html["SAN-Multipath- und automatische LIF-Failover-Unterstützung"].

Eine Failover-Gruppe enthält eine Reihe von Netzwerkports (physische Ports, VLANs und Schnittstellengruppen) von einem oder mehreren Knoten in einem ONTAP Cluster. Die Netzwerkports, die in der Failover-Gruppe vorhanden sind, definieren die für die LIF verfügbaren Failover-Ziele. Einer Failover-Gruppe können Cluster-Management-LIFs, Knoten-Management-LIFs, Intercluster-LIFs und NAS-Daten-LIFs zugewiesen werden.


IMPORTANT: Wenn eine LIF ohne gültiges Failover-Ziel konfiguriert ist, tritt ein Ausfall auf, wenn die LIF versucht, ein Failover durchzuführen. Mit dem  `network interface show -failover` Befehl lässt sich die Failover-Konfiguration überprüfen. Weitere Informationen zu  `network interface show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["ONTAP-Befehlsreferenz"^].

Wenn eine Broadcast-Domäne erstellt wird, wird automatisch eine gleichnamige Failover-Gruppe angelegt, die dieselben Netzwerkports enthält. Diese Failover-Gruppe wird vom System automatisch verwaltet, das heißt, wenn Ports zur Broadcast-Domäne hinzugefügt oder daraus entfernt werden, werden sie auch automatisch zu dieser Failover-Gruppe hinzugefügt oder daraus entfernt. Dies stellt eine effiziente Lösung für Administratoren dar, die ihre Failover-Gruppen nicht selbst verwalten möchten.

Ab ONTAP 9.19.1 erweitert die systemdefinierte Failover-Gruppenrichtlinie von ONTAP die Failover-Ziele für NAS-Daten-LIFs dynamisch, sodass potenziell alle verfügbaren Ports in der Broadcast-Domäne auf jedem verfügbaren Knoten im Cluster einbezogen werden können. Sie können die systemdefinierte Richtlinie auf jede Failover-Gruppe anwenden. Vor ONTAP 9.19.1 konnten LIFs mit dieser Richtlinie nur auf einen anderen Knoten im Cluster ausweichen; wenn dieser Knoten nicht im Quorum war, fand kein Failover statt, selbst wenn andere Knoten verfügbar waren.

.Verwandte Informationen
Informationen dazu link:https://docs.netapp.com/us-en/asa-r2/administer/manage-client-vm-access.html#create-a-lif-network-interface["automatisches LIF-Failover auf ASA r2-Systemen"^].
