---
sidebar: sidebar 
permalink: networking/configure-backend-encryption.html 
keywords: cluster network, encryption, TLS, data-in-flight, backend network 
summary: Konfigurieren Sie die Cluster-NetzwerkverschlĂĽsselungseinstellungen. 
---
= Konfigurieren der ONTAP Backend-Cluster-NetzwerkverschlĂĽsselung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.18.1 kĂ¶nnen Sie die Transport Layer Security (TLS)-VerschlĂĽsselung fĂĽr Daten wĂ¤hrend der Ăśbertragung im Backend-Cluster-Netzwerk konfigurieren.  Diese VerschlĂĽsselung schĂĽtzt Kundendaten, die in ONTAP gespeichert sind, wĂ¤hrend der Ăśbertragung zwischen ONTAP Knoten im Backend-Clusternetzwerk.

.Ăśber diese Aufgabe
* Die Backend-Cluster-NetzwerkverschlĂĽsselung ist standardmĂ¤Ăźig deaktiviert.
* Wenn die VerschlĂĽsselung des Backend-Cluster-Netzwerks aktiviert ist, werden alle in ONTAP gespeicherten Kundendaten bei der Ăśbertragung zwischen ONTAP Knoten im Backend-Cluster-Netzwerk verschlĂĽsselt.  Bestimmte Netzwerkdaten im Cluster, wie z. B. Daten des Kontrollpfads, sind nicht verschlĂĽsselt.
* StandardmĂ¤Ăźig verwendet die Backend-Cluster-NetzwerkverschlĂĽsselung automatisch generierte Zertifikate fĂĽr jeden Knoten im Cluster.  Du kannst<<Cluster-NetzwerkverschlĂĽsselungszertifikate verwalten>> Auf jedem Knoten soll ein benutzerdefiniertes Zertifikat verwendet werden.


.Bevor Sie beginnen
* Sie mĂĽssen ONTAP Administrator sein. `admin` Berechtigungsstufe zum AusfĂĽhren der folgenden Aufgaben.
* Auf allen Knoten im Cluster muss ONTAP 9.18.1 oder hĂ¶her ausgefĂĽhrt werden, um die Backend-Cluster-NetzwerkverschlĂĽsselung zu aktivieren.




== VerschlĂĽsselung fĂĽr die Cluster-Netzwerkkommunikation aktivieren oder deaktivieren

.Schritte
. Den aktuellen VerschlĂĽsselungsstatus des Clusternetzwerks anzeigen:
+
[source, cli]
----
security cluster-network show
----
+
Dieser Befehl zeigt den aktuellen Status der Cluster-NetzwerkverschlĂĽsselung an:

+
[source]
----
Cluster-1::*> security cluster-network show

Enabled: true

Mode: tls

Status: READY
----
. Aktivieren oder Deaktivieren der TLS-Backend-Cluster-NetzwerkverschlĂĽsselung:
+
[source, cli]
----
security cluster-network modify -enabled <true|false>
----
+
Dieser Befehl aktiviert oder deaktiviert die verschlĂĽsselte Kommunikation fĂĽr Kundendaten, die sich wĂ¤hrend der Ăśbertragung im Backend-Cluster-Netzwerk befinden.





== Cluster-NetzwerkverschlĂĽsselungszertifikate verwalten

. Aktuelle Informationen zum Cluster-NetzwerkverschlĂĽsselungszertifikat anzeigen:
+
[source, cli]
----
security cluster-network certificate show
----
+
Dieser Befehl zeigt die aktuellen Informationen zum Cluster-NetzwerkverschlĂĽsselungszertifikat an:

+
[source]
----
security cluster-network certificate show
Node                  Certificate Name                      CA
--------------------- -----------------------------------   --------------
node1                 -                                     Cluster-1_Root_CA
node2                 -                                     Cluster-1_Root_CA
node3                 google_issued_cert1                   Google_CA1
node4                 google_issued_cert2                   Google_CA1
----
+
FĂĽr jeden Knoten im Cluster werden die Zertifikats- und Zertifizierungsstellennamen (CA-Namen) angezeigt.

. Ă„ndern des Clusternetzwerk-VerschlĂĽsselungszertifikats fĂĽr einen Knoten:
+
[source, cli]
----
security cluster-network certificate modify -node <node_name> -name <certificate_name>
----
+
Dieser Befehl Ă¤ndert das Clusternetzwerk-VerschlĂĽsselungszertifikat fĂĽr einen bestimmten Knoten.  Das Zertifikat muss vor AusfĂĽhrung dieses Befehls installiert und von einer installierten Zertifizierungsstelle signiert werden.  Weitere Informationen zur Zertifikatsverwaltung finden Sie unterlink:../authentication/manage-certificates-sm-task.html["Managen Sie ONTAP Zertifikate mit System Manager"] Die  Wenn `-name` Wenn kein Zertifikat angegeben ist, wird das automatisch generierte Standardzertifikat verwendet.


