---
sidebar: sidebar 
permalink: networking/configure_network_ports_cluster_administrators_only_overview.html 
keywords: introducing, introduction, overview, network, port, port type, type, physical, interface group, vlan, vip, virtual, naming, convention, configure network ports overview, introducing physical and virtual network ports 
summary: Einführung physischer und virtueller Netzwerk-Ports. 
---
= Erfahren Sie mehr über ONTAP Netzwerkportkonfiguration
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ports sind entweder physische Ports (NICs) oder virtualisierte Ports, wie Schnittstellengruppen oder VLANs.

Virtuelle lokale Netzwerke (VLANs) und Schnittstellengruppen bilden die virtuellen Ports. Schnittstellengruppen behandeln mehrere physische Ports als einen einzigen Port, während VLANs einen physischen Port in mehrere separate logische Ports unterteilen.

* Physische Ports: LIFs können direkt auf physischen Ports konfiguriert werden.
* Schnittstellengruppe: Ein Portaggregat, das zwei oder mehr physische Ports umfasst, die als ein einziger Trunk-Port fungieren. Eine Schnittstellengruppe kann im Einzelmodus, im Mehrmodus oder im Dynamischen Multimode sein.
* VLAN: Ein logischer Port, der VLAN-getaggten (IEEE 802.1Q-Standard) Datenverkehr empfängt und sendet. Zu den Eigenschaften eines VLAN-Ports gehört die VLAN-ID für den Port. Die zugrunde liegenden physischen Ports oder Schnittstellengruppen-Ports gelten als VLAN-Trunk-Ports, und die angeschlossenen Switch-Ports müssen so konfiguriert sein, dass sie die VLAN-IDs trunkieren.
+
Die zugrunde liegenden physischen Ports oder Schnittstellengruppen-Ports für einen VLAN-Port können weiterhin LIFs hosten, die ungetaggten Datenverkehr senden und empfangen.

* Virtueller IP-Port (VIP-Port): Ein logischer Port, der als Heimatport für eine VIP-LIF verwendet wird. VIP-Ports werden automatisch vom System erstellt und unterstützen nur eine begrenzte Anzahl von Operationen. VIP-Ports werden ab ONTAP 9.5 unterstützt.


Die Namenskonvention für Ports lautet _enumberletter_:

* Der erste Buchstabe beschreibt den Porttyp. „e“ steht für Ethernet.
* Das zweite Zeichen kennzeichnet den nummerierten Steckplatz, in dem sich der Portadapter befindet.
* Das dritte Zeichen gibt die Position des Ports an einem Mehrport-Adapter an. „a“ steht für den ersten Port, „b“ für den zweiten Port und so weiter.


Beispielsweise  `e0b`zeigt dies an, dass ein Ethernet-Port der zweite Port auf dem Motherboard des Knotens ist.

VLANs müssen mit der Syntax  `port_name-vlan-id` benannt werden.

`port_name` gibt den physischen Port oder die Schnittstellengruppe an.

`vlan-id` gibt die VLAN-Kennung im Netzwerk an. Zum Beispiel,  `e1c-80` ist ein gültiger VLAN-Name.
