---
sidebar: sidebar 
permalink: networking/configure_traphosts_to_receive_snmp_notifications.html 
keywords: configure, configuration, configuring, setup, setting, set, up, traphosts, trap, host, receive, snmp, notifications, configure traphosts to receive snmp notifications. system snmp traphost add 
summary: Konfigurieren Sie den SNMP-Manager für den Empfang von Trap-Benachrichtigungen 
---
= Konfigurieren Sie traphosts für den Empfang von SNMP-Benachrichtigungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können traphost (SNMP Manager) so konfigurieren, dass Benachrichtigungen (SNMP Trap PDUs) empfangen werden, wenn SNMP Traps im Cluster generiert werden. Sie können entweder den Hostnamen oder die IP-Adresse (IPv4 oder IPv6) des SNMP traphost angeben.

.Bevor Sie beginnen
* SNMP- und SNMP-Traps müssen auf dem Cluster aktiviert sein.



NOTE: SNMP- und SNMP-Traps sind standardmäßig aktiviert.

* Für das Auflösen der traphost-Namen muss auf dem Cluster DNS konfiguriert sein.
* IPv6 muss auf dem Cluster aktiviert sein, um SNMP-Traphosts mithilfe von IPv6-Adressen zu konfigurieren.
* Für ONTAP 9.1 und neuere Versionen müssen Sie beim Erstellen von Traphosts die Authentifizierung eines vordefinierten Benutzer-basierten Sicherheitsmodells (USM) und der Privatsphäre-Anmeldeinformationen angegeben haben.


Hinzufügen eines SNMP traphost:

....
system snmp traphost add
....

NOTE: Traps können nur gesendet werden, wenn mindestens eine SNMP Management Station als traphost angegeben ist.

Mit dem folgenden Befehl wird ein neuer SNMPv3 traphost mit dem Namen yyy.example.com mit einem bekannten USM-Benutzer hinzugefügt:

....
system snmp traphost add -peer-address yyy.example.com -usm-username MyUsmUser
....
Mit dem folgenden Befehl wird ein traphost unter Verwendung der IPv6-Adresse des Hosts hinzugefügt:

....
system snmp traphost add -peer-address 2001:0db8:1:1:209:6bff:feae:6d67
....