---
permalink: networking/configure-ports-uta-x1143a-r6.html 
sidebar: sidebar 
keywords: configure, ports 
summary: 'Um den Unified Target Adapter (X1143A-R6) zu konfigurieren, müssen die beiden benachbarten Ports auf demselben Chip im selben Personality-Modus konfiguriert werden.' 
---
= Konfigurieren Sie die UTA X1143A-R6-Ports für das ONTAP-Netzwerk
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Standardmäßig ist der X1143A-R6 Unified Target Adapter im FC Target-Modus konfiguriert. Sie können seine Ports jedoch entweder als 10-Gbit-Ethernet- und FCoE-Ports (CNA) oder als 16-Gbit-FC-Initiator oder als Ziel-Ports konfigurieren. Dazu sind andere SFP+-Adapter erforderlich.

Bei Konfiguration für Ethernet und FCoE unterstützen X1143A-R6 Adapter gleichzeitigen NIC- und FCoE-Zielverkehr auf demselben 10-GBE-Port. Bei Konfiguration für FC kann jedes Paar mit zwei Ports, das denselben ASIC verwendet, individuell für das FC-Ziel oder den FC-Initiator-Modus konfiguriert werden. Das bedeutet, dass ein einzelner X1143A-R6 Adapter einen FC-Zielmodus auf einem Paar mit zwei Ports und einen FC-Initiator-Modus auf einem anderen Paar mit zwei Ports unterstützen kann. Die mit demselben ASIC verbundenen Port-Paare müssen im gleichen Modus konfiguriert werden.

Im FC-Modus verhält sich der X1143A-R6 Adapter wie jedes vorhandene FC-Gerät mit Geschwindigkeiten von bis zu 16 Gbit/s. Im CNA-Modus können Sie den X1143A-R6-Adapter für den gleichzeitigen NIC- und FCoE-Datenverkehr verwenden, der denselben 10-GbE-Port nutzt. Der CNA-Modus unterstützt für die FCoE-Funktion nur den FC-Zielmodus.

Um den Unified Target Adapter (X1143A-R6) zu konfigurieren, müssen die beiden benachbarten Ports auf demselben Chip im selben Personality-Modus konfiguriert werden.

.Schritte
. Überprüfen Sie die Portkonfiguration:
+
[source, cli]
----
system hardware unified-connect show
----
. Konfigurieren Sie die Ports nach Bedarf für Fibre Channel (FC) oder Converged Network Adapter (CNA):
+
[source, cli]
----
system node hardware unified-connect modify -node <node_name> -adapter <adapter_name> -mode {fcp|cna}
----
. Schließen Sie die entsprechenden Kabel für FC- oder 10-Gbit-Ethernet an.
. Vergewissern Sie sich, dass das richtige SFP+ installiert ist:
+
[source, cli]
----
network fcp adapter show -instance -node -adapter
----
+
Für CNA sollten Sie einen 10-GB-Ethernet SFP verwenden. Für FC sollten Sie basierend auf der FC-Fabric, mit der verbunden ist, entweder einen 8-Gbit-SFP oder einen 16-Gbit-SFP verwenden.


