---
sidebar: sidebar 
permalink: networking/create_ipspaces.html 
keywords: create, creation, creating, add, adding, ipspace, create ipspaces, ipspace create, ipspace show, create ipspaces, ipspace create, broadcast-domain move 
summary: Erstellen von IPspaces für jede SVM in einem Cluster 
---
= Erstellen von IPspaces
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
IPspaces können verwendet werden, um für jede SVM in einem Cluster einen eigenen IP-Adressbereich zu erstellen. So können Clients in administrativ getrennten Netzwerkdomänen unter Verwendung überlappender IP-Adressbereiche aus demselben IP-Adressbereich des Subnetzes auf Cluster-Daten zugreifen.

.Bevor Sie beginnen
Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.

.Schritt
Erstellen Sie einen IPspace.

`network ipspace create -ipspace ipspace1`

`network ipspace show`

....
IPspace             Vserver List          Broadcast Domains
------------------- --------------------- ----------------------------
Cluster             Cluster               Cluster
Default             Cluster1              Default
ipspace1            ipspace1              -
....
Der IPspace wird zusammen mit der System-SVM für den IPspace erstellt. Die SVM des Systems führt den Management-Datenverkehr durch.
