---
sidebar: sidebar 
permalink: networking/create_a_dns_load_balancing_zone.html 
keywords: create, creation, creating, add, adding, dns, naming, name, service, load, balancing, balance, zone, lif, create a dns load balancing zone, improve lif performance 
summary: Erstellen Sie eine DNS-Lastausgleichzone, um die LIF-Performance zu verbessern 
---
= Erstellen Sie eine DNS-Lastausgleichzone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können eine DNS-Lastausgleichzone erstellen, um die dynamische Auswahl einer logischen Schnittstelle gemäß der Last, d. h. der Anzahl der Clients, die auf einem LIF gemountet sind, zu vereinfachen. Sie können eine Load Balancing-Zone erstellen, während Sie eine Daten-LIF erstellen.

.Bevor Sie beginnen
Der DNS-Forwarder auf dem standortweiten DNS-Server muss so konfiguriert sein, dass alle Anfragen für die Lastausgleichszone an die konfigurierten LIFs weitergehen.

Der Knowledgebase-Artikel link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_set_up_DNS_load_balancing_in_clustered_Data_ONTAP["So richten Sie den DNS-Lastenausgleich im Cluster-Modus ein"^] Auf der NetApp Support Site finden Sie weitere Informationen zum Konfigurieren des DNS-Lastausgleichs mithilfe von Conditional Forwarding.

.Über diese Aufgabe
* Jede logische Datenschnittstelle kann auf DNS-Abfragen für einen DNS-Namen für den Lastenausgleichsbereich reagieren.
* Eine DNS-Load-Balancing-Zone muss einen eindeutigen Namen im Cluster haben, und der Zonenname muss die folgenden Anforderungen erfüllen:
+
** Er darf maximal 256 Zeichen lang sein.
** Es sollte mindestens einen Zeitraum enthalten.
** Das erste und das letzte Zeichen dürfen kein Punkt oder ein anderes Sonderzeichen sein.
** Es dürfen keine Leerzeichen zwischen Zeichen enthalten.
** Jede Beschriftung im DNS-Namen darf 63 Zeichen nicht überschreiten.
+
Eine Bezeichnung ist der Text, der vor oder nach dem Zeitraum erscheint. Beispielsweise verfügt die DNS-Zone mit dem Namen storage.company.com über drei Bezeichnungen.





.Schritt
Verwenden Sie die `network interface create` Befehl mit dem `dns-zone` Option zum Erstellen einer DNS-Lastausgleichzone.

Wenn die Lastausgleichzone bereits vorhanden ist, wird ihr das LIF hinzugefügt. Weitere Informationen zum Befehl finden Sie im https://docs.netapp.com/us-en/ontap-cli["Befehlsreferenz für ONTAP"^].

Das folgende Beispiel zeigt, wie eine DNS-Load-Balancing-Zone mit dem Namen storage.company.com beim Erstellen des LIF erstellt wird `lif1`:

....
network interface create -vserver vs0 -lif lif1 -home-node node1
-home-port e0c -address 192.0.2.129 -netmask 255.255.255.128 -dns-zone storage.company.com
....