---
sidebar: sidebar 
permalink: networking/delete_a_lif.html 
keywords: remove a lif, destroy a lif, delete, deleting, remove, removing, logical, interface, lif 
summary: Löschen Sie eine Netzwerkschnittstelle, LIF, die nicht mehr benötigt wird. 
---
= ONTAP LIFs löschen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können eine logische Schnittstelle (LIF) löschen, die nicht mehr benötigt wird.

.Bevor Sie beginnen
Die zu löschenden LIFs dürfen nicht in Gebrauch sein.

.Schritte
. Die LIFs, die gelöscht werden sollen, werden mit dem folgenden Befehl als administrativ inaktiv markiert:
+
....
network interface modify -vserver vserver_name -lif lif_name -status-admin down
....
. Mit dem  `network interface delete` Befehl lässt sich eine oder alle LIFs löschen:
+
[cols="30,70"]
|===


| Wenn Sie löschen möchten... | Den Befehl ... eingeben. 


 a| 
Ein spezifisches LIF
 a| 
`network interface delete -vserver vserver_name -lif lif_name`



 a| 
Alle LIFs
 a| 
`network interface delete -vserver vserver_name -lif *`

|===
+
Weitere Informationen zu  `network interface delete` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-delete.html["ONTAP-Befehlsreferenz"^].

+
Der folgende Befehl löscht die LIF mgmtlif2:

+
....
network interface delete -vserver vs1 -lif mgmtlif2
....
. Mit dem  `network interface show` Befehl lässt sich bestätigen, dass die LIF gelöscht wurde.
+
Weitere Informationen zu  `network interface show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["ONTAP-Befehlsreferenz"^].


