---
sidebar: sidebar 
permalink: networking/display_lif_failover_targets.html 
keywords: display, view, show, lif, logical, interface, failover, fail, over, target, display lif failover targets, verify the failover policy and failover group configuration for a lif, network interface show 
summary: Überprüfen Sie die Failover-Richtlinie und die Failover-Gruppe für einen LIF. 
---
= ONTAP LIF-Failover-Ziele anzeigen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie überprüfen, ob die Failover-Richtlinien und die Failover-Gruppen eines LIF korrekt konfiguriert sind. Zur Vermeidung von Fehlkonfigurationen der Failover-Regeln besteht die Möglichkeit, die Failover-Ziele für ein einzelnes LIF oder für alle LIFs anzuzeigen.

.Über diese Aufgabe
Die Anzeige der LIF-Failover-Ziele ermöglicht die Überprüfung folgender Punkte:

* Ob die LIFs mit der richtigen Failover-Gruppe und Failover-Richtlinie konfiguriert sind
* Ob die resultierende Liste der Failover-Zielports für jedes LIF geeignet ist
* Ob das Failover-Ziel einer Daten-LIF kein Management-Port (e0M) ist


.Schritt
Die Failover-Ziele eines LIF werden mit der  `failover` Option des  `network interface show` Befehls angezeigt.

Der folgende Befehl zeigt Informationen zu den Failover-Zielen für alle LIFs in einem Zwei-Node-Cluster an. Die  `Failover` `Targets` Zeile zeigt die (priorisierte) Liste der Node-Port-Kombinationen für ein bestimmtes LIF.

....
network interface show -failover
         Logical       Home                  Failover        Failover
Vserver  Interface     Node:Port             Policy          Group
-------- ------------- --------------------- --------------- ---------
Cluster
         node1_clus1   node1:e0a             local-only      Cluster
                       Failover Targets: node1:e0a,
                                         node1:e0b
         node1_clus2   node1:e0b             local-only      Cluster
                       Failover Targets: node1:e0b,
                                         node1:e0a
         node2_clus1   node2:e0a             local-only      Cluster
                       Failover Targets: node2:e0a,
                                         node2:e0b
         node2_clus2   node2:e0b             local-only      Cluster
                       Failover Targets: node2:e0b,
                                         node2:e0a
cluster1
         cluster_mgmt  node1:e0c             broadcast-domain-wide
                                                             Default
                       Failover Targets: node1:e0c,
                                         node1:e0d,
                                         node2:e0c,
                                         node2:e0d
         node1_mgmt1   node1:e0c             local-only      Default
                       Failover Targets: node1:e0c,
                                         node1:e0d
         node2_mgmt1   node2:e0c             local-only      Default
                       Failover Targets: node2:e0c,
                                         node2:e0d
vs1
         data1         node1:e0e             system-defined  bcast1
                       Failover Targets: node1:e0e,
                                         node1:e0f,
                                         node2:e0e,
                                         node2:e0f
....
Weitere Informationen zu  `network interface show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["ONTAP-Befehlsreferenz"^].
