---
sidebar: sidebar 
permalink: networking/display_ipspaces.html 
keywords: display, view, show, ipspace, display ipspaces, list the ipspaces and view ipspace information for the cluster 
summary: Die IPspaces auflisten und IPspace-Informationen für das Cluster anzeigen. 
---
= IPspaces im ONTAP Netzwerk anzeigen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können die Liste der in einem Cluster vorhandenen IPspaces anzeigen und die Storage Virtual Machines (SVMs), Broadcast-Domänen und Ports einsehen, die jedem IPspace zugewiesen sind.

.Schritt
Die IPspaces und SVMs in einem Cluster werden angezeigt:

....
network ipspace show [-ipspace ipspace_name]
....
Der folgende Befehl zeigt alle IPspaces, SVMs und Broadcast-Domänen im Cluster an:

....
network ipspace show
IPspace        Vserver List             Broadcast Domains
-------------  -----------------------  -------------------
Cluster
               Cluster                  Cluster
Default
               vs1, cluster-1            Default
ipspace1
               vs3, vs4, ipspace1       bcast1
....
Der folgende Befehl zeigt die Nodes und Ports an, die Teil des IPspace ipspace1 sind:

....
network ipspace show -ipspace ipspace1
IPspace name: ipspace1
Ports: cluster-1-01:e0c, cluster-1-01:e0d, cluster-1-01:e0e, cluster-1-02:e0c, cluster-1-02:e0d, cluster-1-02:e0e
Broadcast Domains: Default-1
Vservers: vs3, vs4, ipspace1
....
Weitere Informationen zu  `network ipspace show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-ipspace-show.html["ONTAP-Befehlsreferenz"^].
