---
sidebar: sidebar 
permalink: networking/display_interface_group_information_cluster_administrators_only.html 
keywords: display, view, show, interface, group, information, display interface group information, verify interface group configuration, network port ifgrp show 
summary: Überprüfen Sie die Konfiguration der Schnittstellengruppe. 
---
= Informationen zur ONTAP Schnittstellengruppe anzeigen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Informationen über eine Schnittstellengruppe können angezeigt werden, um deren Konfiguration zu ermitteln.

.Über diese Aufgabe
Folgende Informationen werden angezeigt:

* Knoten, auf dem sich die Schnittstellengruppe befindet
* Liste der Netzwerkports, die in der Schnittstellengruppe enthalten sind
* Name der Schnittstellengruppe
* Verteilungsfunktion (MAC, IP, Port oder sequenziell)
* Media Access Control (MAC)-Adresse der Schnittstellengruppe
* Status der Port-Aktivität, das heißt, ob alle aggregierten Ports aktiv sind (volle Teilnahme), ob einige aktiv sind (teilweise Teilnahme) oder ob keiner aktiv ist


.Schritt
Informationen zu Schnittstellengruppen werden mit dem  `network port ifgrp show` Befehl angezeigt.

Detaillierte Informationen zu jedem Node werden durch Angabe des  `-instance` Parameters angezeigt. Spezifische Informationen werden durch Angabe von Feldnamen mit dem  `-fields` Parameter angezeigt.

Der folgende Befehl zeigt Informationen zu allen Schnittstellengruppen im Cluster an:

....
network port ifgrp show
         Port     Distribution                    Active
Node     IfGrp    Function     MAC Address        Ports   Ports
-------- -------- ------------ -----------------  ------- --------
cluster-1-01
         a0a      ip           02:a0:98:06:10:b2  full    e7a, e7b
cluster-1-02
         a0a      sequential   02:a0:98:06:10:ca  full    e7a, e7b
cluster-1-03
         a0a      port         02:a0:98:08:5b:66  full    e7a, e7b
cluster-1-04
         a0a      mac          02:a0:98:08:61:4e  full    e7a, e7b
....
Der folgende Befehl zeigt detaillierte Informationen zur Schnittstellengruppe für einen einzelnen Knoten an:

....
network port ifgrp show -instance -node cluster-1-01

                 Node: cluster-1-01
 Interface Group Name: a0a
Distribution Function: ip
        Create Policy: multimode
          MAC Address: 02:a0:98:06:10:b2
   Port Participation: full
        Network Ports: e7a, e7b
             Up Ports: e7a, e7b
           Down Ports: -
....
Weitere Informationen zu  `network port ifgrp show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-port-ifgrp-show.html["ONTAP-Befehlsreferenz"^].
