---
sidebar: sidebar 
permalink: networking/display_network_connectivity_with_neighbor_discovery_protocols.html 
keywords: display, view, show, network, connectivity, neighbor, discovery, protocol, ndp, cdp, cisco, link, layer, lldp, display network connectivity with neighbor discovery protocols, use neighbor discovery protocols to view network connectivity between a pair of physical or virtual systems and their network interfaces, use cdp to detect network connectivity, considerations for using cdp, enable or disable cdp, view cdp neighbor information, example of showing and clearing statistics, use lldp to detect network connectivity, enable or disable lldp, view lldp neighbor information, adjust the interval for transmitting lldp advertisements 
summary: Verwenden Sie Neighbor-Discovery-Protokolle, um die Netzwerkverbindungen zwischen einem Paar physischer oder virtueller Systeme und deren Netzwerkschnittstellen anzuzeigen. 
---
= ONTAP Netzwerkverbindungen mit Nachbarerkennungsprotokollen anzeigen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In einem Rechenzentrum können Nachbarerkennungsprotokolle verwendet werden, um die Netzwerkverbindungen zwischen einem Paar physischer oder virtueller Systeme und deren Netzwerkschnittstellen anzuzeigen. ONTAP unterstützt zwei Nachbarerkennungsprotokolle: Cisco Discovery Protocol (CDP) und Link Layer Discovery Protocol (LLDP).

Neighbor Discovery Protocols ermöglichen die automatische Erkennung und Anzeige von Informationen über direkt verbundene, protokollfähige Geräte in einem Netzwerk. Jedes Gerät gibt Identifikations-, Funktions- und Verbindungsinformationen bekannt. Diese Informationen werden in Ethernet-Frames an eine Multicast-MAC-Adresse übertragen und von allen benachbarten, protokollfähigen Geräten empfangen.

Damit zwei Geräte Nachbarn werden können, muss auf jedem ein Protokoll aktiviert und korrekt konfiguriert sein. Die Erkennungsprotokollfunktion ist auf direkt verbundene Netzwerke beschränkt. Nachbarn können protokollfähige Geräte wie Switches, Router, Bridges usw. sein. ONTAP unterstützt zwei Nachbarerkennungsprotokolle, die einzeln oder gemeinsam verwendet werden können.

*Cisco Discovery Protocol (CDP)*

CDP ist ein proprietäres Link-Layer-Protokoll, das von Cisco Systems entwickelt wurde. Es ist in ONTAP für Cluster-Ports standardmäßig aktiviert, muss aber für Daten-Ports explizit aktiviert werden.

*Link Layer Discovery Protocol (LLDP)*

LLDP ist ein herstellerneutrales Protokoll, das im Standarddokument IEEE 802.1AB spezifiziert ist. Es muss für alle Ports explizit aktiviert werden.
