---
sidebar: sidebar 
permalink: networking/display_dns_host_table_entries_cluster_administrators_only.html 
keywords: display, view, show, dns, host, names, alias, display dns host table entries, view the host and alias names and the mapped ip addresses for all svms in a cluster, vserver services name-service dns 
summary: Zeigen Sie die Host- und Aliasnamen sowie die zugeordneten IP-Adressen aller SVMs in einem Cluster an. 
---
= ONTAP DNS-Hosttabelleneinträge
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die DNS-Hosttabelleneinträge ordnen Hostnamen IP-Adressen zu. Die Hostnamen, Aliasnamen und die zugehörigen IP-Adressen, denen sie zugeordnet sind, können für alle SVMs in einem Cluster angezeigt werden.

.Schritt
Die Hostnameneinträge für alle SVMs werden mit dem Befehl vserver services name-service dns hosts show angezeigt.

Das folgende Beispiel zeigt die Einträge der Hosttabelle:

....
vserver services name-service dns hosts show
Vserver    Address        Hostname        Aliases
---------- -------------- --------------- ---------------------
cluster-1
           10.72.219.36   lnx219-36       -
vs1
           10.72.219.37   lnx219-37       lnx219-37.example.com
....
Sie können den  `vserver services name-service dns` Befehl verwenden, um DNS auf einer SVM zu aktivieren und sie so zu konfigurieren, dass sie DNS für die Hostnamensauflösung verwendet. Hostnamen werden mithilfe externer DNS-Server aufgelöst.
