---
sidebar: sidebar 
permalink: networking/display_broadcast_domains.html 
keywords: display, view, show, broadcast, domain, display broadcast domains, view a list of broadcast domains within each ipspace in a cluster 
summary: Zeigen Sie eine Liste der Broadcast-Domänen innerhalb jedes IPspaces in einem Cluster an 
---
= Anzeigen von ONTAP Broadcast-Domänen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können die Liste der Broadcast-Domänen innerhalb jedes IPspaces in einem Cluster anzeigen. In der Ausgabe werden außerdem die Portliste und der MTU-Wert für jede Broadcast-Domäne angezeigt.


NOTE: Das Verfahren zur Anzeige von Broadcast-Domänen unterscheidet sich in ONTAP 9.7 und früheren Versionen. Wenn Sie Broadcast-Domänen in einem Netzwerk anzeigen müssen, auf dem ONTAP 9.7 und früher ausgeführt wird, finden Sie weitere Informationen unter link:https://docs.netapp.com/us-en/ontap-system-manager-classic/networking-bd/display_broadcast_domains97.html["Broadcast-Domänen anzeigen (ONTAP 9.7 oder früher)"^].

.Schritt
Zeigen Sie die Broadcast-Domänen und die zugehörigen Ports im Cluster an:

....
network port broadcast-domain show
....
Mit dem folgenden Befehl werden alle Broadcast-Domänen und die zugehörigen Ports im Cluster angezeigt:

....
network port broadcast-domain show
IPspace Broadcast                                Update
Name    Domain Name  MTU   Port List             Status Details
------- ----------- -----  --------------------- --------------
Cluster Cluster      9000
                           cluster-1-01:e0a       complete
                           cluster-1-01:e0b       complete
                           cluster-1-02:e0a       complete
                           cluster-1-02:e0b       complete
Default Default      1500
                           cluster-1-01:e0c       complete
                           cluster-1-01:e0d       complete
                           cluster-1-02:e0c       complete
                           cluster-1-02:e0d       complete
        Default-1    1500
                           cluster-1-01:e0e       complete
                           cluster-1-01:e0f       complete
                           cluster-1-01:e0g       complete
                           cluster-1-02:e0e       complete
                           cluster-1-02:e0f       complete
                           cluster-1-02:e0g       complete
....
Mit dem folgenden Befehl werden die Ports in der Standard-1 Broadcast-Domäne angezeigt, die einen Aktualisierungsstatus aufweisen, was darauf hinweist, dass der Port nicht ordnungsgemäß aktualisiert werden konnte:

....
network port broadcast-domain show -broadcast-domain Default-1 -port-update-status error

IPspace Broadcast                                Update
Name    Domain Name  MTU   Port List             Status Details
------- ----------- -----  --------------------- --------------
Default Default-1   1500
                           cluster-1-02:e0g       error
....
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/network-port-broadcast-domain-show.html["Netzwerk-Port Broadcast-Domain anzeigen"^]

