---
sidebar: sidebar 
permalink: networking/dscp_marking_for_uc_compliance.html 
keywords: enable, enabling, dscp, qos, marking, quality of service, differentiated services code point, egress, ip packet, traffic, performance, uc, compliance, unified capability, dscp marking for uc compliance, enable dscp marking on outgoing ip packet traffic 
summary: Aktivieren Sie die DSCP-Markierung beim ausgehenden IP-Paketverkehr 
---
= DSCP-Kennzeichnung für UC-Compliance
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Markierung des differenzierten Dienstcodepunktes (DSCP) für ausgehenden (ausgehenden) IP-Paketverkehr für ein bestimmtes Protokoll mit einem Standard- oder vom Benutzer bereitgestellten DSCP-Code aktivieren. Die DSCP-Kennzeichnung ist ein Mechanismus zur Klassifizierung und Verwaltung des Netzwerkdatenverkehrs und ist eine Komponente der Unified Capability (UC)-Compliance.

Die DSCP-Markierung (auch bekannt als _QoS-Markierung_ oder _Quality of Service-Markierung_) wird durch die Bereitstellung eines IPspace-, Protokoll- und DSCP-Wertes aktiviert. Die Protokolle, auf die DSCP-Kennzeichnung angewendet werden kann, sind NFS, SMB, iSCSI, SnapMirror, NDMP, FTP, HTTP/HTTPS, SSH, Telnet und SNMP

Wenn Sie keinen DSCP-Wert angeben, wenn Sie die DSCP-Markierung für ein bestimmtes Protokoll aktivieren, wird ein Standardwert verwendet:

* Der Standardwert für Datenprotokolle/Datenverkehr ist 0x0A (10).
* Der Standardwert für Steuerungsprotokolle/-Verkehr ist 0x30 (48).

