---
sidebar: sidebar 
permalink: networking/enable_multipath_routing.html 
keywords: enable, multipath, routing, load balance, available routes, network, traffic, outgoing traffic, ECMP routing, multipath routing, network options, advanced privilege level, cluster, nodes, metrics 
summary: Aktivieren Sie Multipath-Routing, um Lastausgleich zu ermöglichen und alle verfügbaren Routen zu nutzen. 
---
= Multipath-Routing für das ONTAP Netzwerk aktivieren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Wenn mehrere Routen dieselbe Metrik für ein Ziel aufweisen, wird nur eine dieser Routen für ausgehenden Datenverkehr ausgewählt. Dadurch bleiben andere Routen für ausgehenden Datenverkehr ungenutzt. Multipath Routing kann aktiviert werden, um den Lastausgleich proportional zu den Metriken auf alle verfügbaren Routen zu ermöglichen, während ECMP Routing den Lastausgleich auf verfügbare Routen mit derselben Metrik durchführt.

.Schritte
. Anmeldung auf der erweiterten Berechtigungsebene:
+
`set -privilege advanced`

. Multipath-Routing aktivieren:
+
`network options multipath-routing modify -is-enabled true`

+
Multipath Routing ist für alle Knoten im Cluster aktiviert.

+
....
network options multipath-routing modify -is-enabled true
....
+
Weitere Informationen zu  `network options multipath-routing modify` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-options-multipath-routing-modify.html["ONTAP-Befehlsreferenz"^].


