---
sidebar: sidebar 
permalink: networking/lifs_and_service_policies96.html 
keywords: service policies for system svms, lif service policies, lif, logical, interface, service, policy, policies, lifs and service policies in ontap 9.6 and later, assign service policies to lifs to specify the supported traffic, service policies for system svms, service policies for data svms, data-core service 
summary: Weisen Sie LIFs Service-Richtlinien zu, um den unterstützten Datenverkehr festzulegen. 
---
= Informationen zu ONTAP LIFs und Servicerichtlinien
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können LIFs Dienstrichtlinien (anstelle von LIF-Rollen oder Firewall-Richtlinien) zuweisen, die den für die LIFs unterstützten Datenverkehr festlegen. Dienstrichtlinien definieren eine Sammlung von Netzwerkdiensten, die von einem LIF unterstützt werden. ONTAP bietet eine Reihe integrierter Dienstrichtlinien, die einem LIF zugeordnet werden können.


NOTE: Die Methode zur Verwaltung des Netzwerkverkehrs unterscheidet sich in ONTAP 9.7 und früheren Versionen. Wenn der Datenverkehr in einem Netzwerk mit ONTAP 9.7 oder einer früheren Version verwaltet werden muss, siehe link:https://docs.netapp.com/us-en/ontap-system-manager-classic/networking/lif_roles95.html["LIF-Rollen (ONTAP 9.5 und früher)"^].


IMPORTANT: FCP- und NVMe/FCP-Protokolle erfordern derzeit keine Service-Policy.

Sie können Servicerichtlinien und deren Details mit folgendem Befehl anzeigen:
`network interface service-policy show`

Weitere Informationen zu  `network interface service-policy show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-service-policy-show.html["ONTAP-Befehlsreferenz"^].

Features, die nicht an einen bestimmten Dienst gebunden sind, verwenden ein systemdefiniertes Verhalten, um LIFs für ausgehende Verbindungen auszuwählen.


NOTE: Anwendungen auf einem LIF mit leerer Service-Richtlinie könnten sich unerwartet verhalten.



[[service-policies-for-system-svms]]
== Servicerichtlinien für System SVMs

Die administrative SVM und jede System-SVM enthalten Dienstrichtlinien, die für LIFs in dieser SVM verwendet werden können, einschließlich Management- und Intercluster-LIFs. Diese Richtlinien werden vom System automatisch erstellt, wenn ein IPspace erstellt wird.

Die folgende Tabelle listet die integrierten Richtlinien für LIFs in System-SVMs ab ONTAP 9.12.1 auf. Für andere Versionen lassen sich die Dienstrichtlinien und deren Details mit dem folgenden Befehl anzeigen:

`network interface service-policy show`

[cols="20,20,20,40"]
|===


| Richtlinie | Inklusive Leistungen | Gleichwertige Rolle | Beschreibung 


 a| 
default-intercluster
 a| 
intercluster-core, management-https
 a| 
Intercluster
 a| 
Wird von LIFs verwendet, die Intercluster-Datenverkehr transportieren. Hinweis: Der Dienst intercluster-core ist ab ONTAP 9.5 unter dem Namen net-intercluster service policy verfügbar.



 a| 
Standardroutenankündigung
 a| 
Management BGP
 a| 
-
 a| 
Wird von LIFs verwendet, die BGP-Peer-Verbindungen übertragen Hinweis: Verfügbar ab ONTAP 9.5 unter dem Namen net-route-announce service policy.



 a| 
Standard-Management
 a| 
management-core, management-https, management-http, management-ssh, management-autosupport, management-ems, management-dns-client, management-ad-client, management-ldap-client, management-nis-client, management-ntp-client, management-log-forwarding
 a| 
node-mgmt oder cluster-mgmt
 a| 
Mit dieser systemweiten Managementrichtlinie lassen sich Knoten- und Cluster-Management-LIFs erstellen, die einer System-SVM zugeordnet sind. Diese LIFs können für ausgehende Verbindungen zu DNS-, AD-, LDAP- oder NIS-Servern sowie für zusätzliche Verbindungen genutzt werden, um Anwendungen zu unterstützen, die im Auftrag des gesamten Systems ausgeführt werden. Ab ONTAP 9.12.1 kann der  `management-log-forwarding`Service verwendet werden, um zu steuern, welche LIFs zur Weiterleitung von Revisionsprotokollen an einen Remote-Syslog-Server genutzt werden.

|===
Die folgende Tabelle listet die Dienste auf, die LIFs auf einer System SVM ab ONTAP 9.11.1 nutzen können:

[cols="25,25,50"]
|===


| Service | Failover-Beschränkungen | Beschreibung 


 a| 
Intercluster Core
 a| 
nur Heimknoten
 a| 
Kerndienste zwischen Clustern



 a| 
Management Core
 a| 
-
 a| 
Kernmanagement Services



 a| 
management-ssh
 a| 
-
 a| 
Dienste für den SSH-Managementzugriff



 a| 
Management-http
 a| 
-
 a| 
Dienste für den HTTP-Managementzugriff



 a| 
management-https
 a| 
-
 a| 
Dienste für den HTTPS-Managementzugriff



 a| 
Management AutoSupport
 a| 
-
 a| 
Services im Zusammenhang mit dem Senden von AutoSupport-Nutzdaten



 a| 
Management BGP
 a| 
nur Home-Port
 a| 
Dienste im Zusammenhang mit BGP-Peer-Interaktionen



 a| 
Backup NDMP-Steuerung
 a| 
-
 a| 
Services für NDMP-Backup-Steuerungen



 a| 
Management EMS
 a| 
-
 a| 
Dienste für den Zugriff auf Management-Messaging



 a| 
Management NTP-Client
 a| 
-
 a| 
Eingeführt in ONTAP 9.10.1. Dienste für den NTP-Clientzugriff.



 a| 
Management NTP-Server
 a| 
-
 a| 
Eingeführt in ONTAP 9.10.1. Dienste für den Zugriff auf die NTP-Server-Managementoberfläche



 a| 
Management Portmap
 a| 
-
 a| 
Services für die Portmap-Verwaltung



 a| 
Management RSH-Server
 a| 
-
 a| 
Dienste für die rsh-Serververwaltung



 a| 
Management SNMP-Server
 a| 
-
 a| 
Dienste für die SNMP-Serververwaltung



 a| 
Management Telnet-Server
 a| 
-
 a| 
Dienste für die Telnet Serververwaltung



 a| 
Managementlog-Weiterleitung
 a| 
-
 a| 
Eingeführt in ONTAP 9.12.1. Dienste für die Weiterleitung von Revisionsprotokollen

|===


[[service-policies-for-data-svms]]
== Servicerichtlinien für Daten-SVMs

Alle Daten-SVMs enthalten Service-Richtlinien, die von LIFs in dieser SVM verwendet werden können.

Die folgende Tabelle listet die integrierten Richtlinien für LIFs in Daten-SVMs ab ONTAP 9.11.1 auf. Für andere Versionen lassen sich die Dienstrichtlinien und deren Details mit dem folgenden Befehl anzeigen:

`network interface service-policy show`

[cols="20,20,20,40"]
|===


| Richtlinie | Inklusive Leistungen | Äquivalentes Datenprotokoll | Beschreibung 


 a| 
Standard-Management
 a| 
data-core, management-https, management-http, management-ssh, management-dns-client, management-ad-client, management-ldap-client, management-nis-client
 a| 
keine
 a| 
Diese SVM-bezogene Verwaltungsrichtlinie dient zum Erstellen von SVM-Management-LIFs, die einer Daten-SVM zugeordnet sind. Diese LIFs können verwendet werden, um SVM-Administratoren Zugriff per SSH oder HTTPS zu ermöglichen. Bei Bedarf können diese LIFs für ausgehende Verbindungen zu externen DNS-, AD-, LDAP- oder NIS-Servern genutzt werden.



 a| 
Standard-Datenblöcke
 a| 
data-core, data-iscsi
 a| 
iSCSI
 a| 
Wird von LIFs verwendet, die blockorientierten SAN-Datenverkehr übertragen. Ab ONTAP 9.10.1 ist die Richtlinie „default-data-blocks“ veraltet. Stattdessen sollte die Dienstrichtlinie „default-data-iscsi“ verwendet werden.



 a| 
Standarddatendateien
 a| 
data-core, data-fpolicy-client, data-dns-server, data-flexcache, data-cifs, data-nfs, management-dns-client, management-ad-client, management-ldap-client, management-nis-client
 a| 
nfs, cifs, fcache
 a| 
Die Standard-data-files-Richtlinie dient zur Erstellung von NAS-LIFs, die dateibasierte Datenprotokolle unterstützen. Manchmal ist in der SVM nur ein LIF vorhanden, daher ermöglicht diese Richtlinie die Nutzung des LIFs für ausgehende Verbindungen zu einem externen DNS-, AD-, LDAP- oder NIS-Server. Diese Dienste können aus dieser Richtlinie entfernt werden, wenn bevorzugt wird, dass diese Verbindungen ausschließlich Management-LIFs nutzen.



 a| 
Standarddaten iSCSI
 a| 
data-core, data-iscsi
 a| 
iSCSI
 a| 
Wird von LIFs verwendet, die iSCSI-Datenverkehr übertragen.



 a| 
Standarddaten NVMe-TCP
 a| 
data-core, data-nvme-tcp
 a| 
nvme-tcp
 a| 
Wird von LIFs verwendet, die NVMe/TCP-Datenverkehr übertragen.

|===
Die folgende Tabelle listet die Dienste auf, die auf einer Daten-SVM verwendet werden können, sowie alle Einschränkungen, die jeder Dienst der Failover-Richtlinie eines LIF auferlegt, beginnend mit ONTAP 9.11.1:

[cols="25,25,50"]
|===


| Service | Ausfallbeschränkungen | Beschreibung 


 a| 
management-ssh
 a| 
-
 a| 
Dienste für den SSH-Managementzugriff



 a| 
Management-http
 a| 
-
 a| 
Eingeführt in ONTAP 9.10.1 Dienste für den HTTP-Verwaltungszugriff



 a| 
management-https
 a| 
-
 a| 
Dienste für den HTTPS-Managementzugriff



 a| 
Management Portmap
 a| 
-
 a| 
Dienste für den Portmap-Management-Zugriff



 a| 
Management SNMP-Server
 a| 
-
 a| 
Eingeführt in ONTAP 9.10.1 Dienste für den SNMP-Serververwaltungszugriff



 a| 
Datenkern
 a| 
-
 a| 
Kerndatendienste



 a| 
data-nfs
 a| 
-
 a| 
NFS Datendienst



 a| 
data-cifs
 a| 
-
 a| 
CIFS Datendienst



 a| 
Daten FlexCache
 a| 
-
 a| 
FlexCache Datendienst



 a| 
data-iscsi
 a| 
home-port-only für AFF/FAS; sfo-partner-only für ASA
 a| 
iSCSI Datendienst



 a| 
Backup NDMP-Steuerung
 a| 
-
 a| 
Eingeführt in ONTAP 9.10.1 Backup NDMP steuert den Datendienst



 a| 
data-dns-server
 a| 
-
 a| 
Eingeführt in ONTAP 9.10.1 DNS Server Datendienst



 a| 
data-fpolicy-client
 a| 
-
 a| 
Datendienst für Dateiprüfungsrichtlinien



 a| 
data-nvme-tcp
 a| 
nur Home-Port
 a| 
Eingeführt in ONTAP 9.10.1 NVMe TCP Datendienst



 a| 
data-s3-server
 a| 
-
 a| 
Simple Storage Service (S3) Server-Datendienst

|===
Es ist wichtig zu wissen, wie die Service-Richtlinien den LIFs in Daten-SVMs zugewiesen werden:

* Wenn eine Daten-SVM mit einer Liste von Datendiensten erstellt wird, werden die integrierten Dienstrichtlinien "default-data-files" und "default-data-blocks" in dieser SVM unter Verwendung der angegebenen Dienste erstellt.
* Wird eine Daten-SVM erstellt, ohne eine Liste von Datendiensten anzugeben, werden die integrierten Dienstrichtlinien „default-data-files“ und „default-data-blocks“ in dieser SVM anhand einer Standardliste von Datendiensten erstellt.
+
Die Standardliste der Datendienste umfasst die iSCSI-, NFS-, NVMe-, SMB- und FlexCache-Dienste.

* Wenn ein LIF mit einer Liste von Datenprotokollen erstellt wird, wird dem LIF eine Dienstrichtlinie zugewiesen, die den angegebenen Datenprotokollen entspricht.
* Falls keine entsprechende Servicerichtlinie existiert, wird eine benutzerdefinierte Servicerichtlinie erstellt.
* Wenn eine LIF ohne Dienstrichtlinie oder Liste von Datenprotokollen erstellt wird, wird der LIF standardmäßig die default-data-files Dienstrichtlinie zugewiesen.




[[data-core-service]]
== Daten-Core-Service

Der Data-Core-Service ermöglicht es Komponenten, die zuvor LIFs mit der Datenrolle verwendet haben, auf Clustern, die auf die Verwaltung von LIFs mithilfe von Service-Richtlinien anstelle von LIF-Rollen (die in ONTAP 9.6 als veraltet gelten) umgestellt wurden, wie erwartet zu funktionieren.

Die Angabe von data-core als Dienst öffnet keine Ports in der Firewall, der Dienst sollte jedoch in jeder Service-Richtlinie in einer Daten-SVM enthalten sein. Beispielsweise enthält die Service-Richtlinie default-data-files standardmäßig die folgenden Dienste:

* Datenkern
* data-nfs
* data-cifs
* Daten FlexCache


Der Datenkerndienst sollte in die Richtlinie aufgenommen werden, um sicherzustellen, dass alle Anwendungen, die LIF verwenden, wie erwartet funktionieren, aber die anderen drei Dienste können, falls gewünscht, entfernt werden.



[[client-side-lif-service]]
== Client-seitiger LIF-Dienst

Ab ONTAP 9.10.1 stellt ONTAP Client-seitig LIF-Dienste für mehrere Anwendungen bereit. Diese Dienste ermöglichen die Steuerung, welche LIFs für ausgehende Verbindungen im Namen der jeweiligen Anwendung verwendet werden.

Die folgenden neuen Dienste geben Administratoren die Kontrolle darüber, welche LIFs als Quelladressen für bestimmte Anwendungen verwendet werden.

[cols="25,25,50"]
|===


| Service | SVM-Beschränkungen | Beschreibung 


 a| 
Management-AD-Client
 a| 
-
 a| 
Ab ONTAP 9.11.1 stellt ONTAP einen Active Directory Client-Dienst für ausgehende Verbindungen zu einem externen AD-Server bereit.



| Management-DNS-Client  a| 
-
 a| 
Ab ONTAP 9.11.1 stellt ONTAP einen DNS-Client-Dienst für ausgehende Verbindungen zu einem externen DNS-Server bereit.



| Management LDAP-Client  a| 
-
 a| 
Ab ONTAP 9.11.1 stellt ONTAP einen LDAP-Client-Dienst für ausgehende Verbindungen zu einem externen LDAP-Server bereit.



| Management-NIS-Client  a| 
-
 a| 
Ab ONTAP 9.11.1 stellt ONTAP einen NIS-Client-Dienst für ausgehende Verbindungen zu einem externen NIS-Server bereit.



 a| 
Management NTP-Client
 a| 
nur systemintern
 a| 
Ab ONTAP 9.10.1 stellt ONTAP einen NTP-Client-Dienst für ausgehende Verbindungen zu einem externen NTP-Server bereit.



 a| 
data-fpolicy-client
 a| 
nur Daten
 a| 
Ab ONTAP 9.8 stellt ONTAP einen Client-Service für ausgehende FPolicy-Verbindungen bereit.

|===
Jeder der neuen Dienste ist automatisch in einigen der integrierten Dienstrichtlinien enthalten, aber Administratoren können sie aus den integrierten Richtlinien entfernen oder zu benutzerdefinierten Richtlinien hinzufügen, um zu steuern, welche LIFs für ausgehende Verbindungen im Namen der einzelnen Anwendungen verwendet werden.

.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/network-interface-service-policy-show.html["network interface service-policy show"^]

