---
sidebar: sidebar 
permalink: networking/merge_broadcast_domains.html 
keywords: merge, combine, broadcast, domain, reachability, merge broadcast domains, merge the ports from one broadcast domain into an existing broadcast domain 
summary: Verbinden Sie die Ports aus einer Broadcast-Domäne mit einer vorhandenen Broadcast-Domäne 
---
= Broadcast-Domänen zusammenführen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn sich die Erreichbarkeit des Netzwerkports geändert hat, entweder durch die physische Netzwerkkonnektivität oder durch die Switch-Konfiguration und zwei Gruppen von Netzwerkports, die zuvor in mehreren Broadcast-Domänen konfiguriert waren, nun alle über eine gemeinsame Erreichbarkeit verfügen, kann das Zusammenführen zweier Broadcast-Domänen verwendet werden, um die ONTAP-Konfiguration mit der physischen Netzwerktopologie zu synchronisieren.

Um festzustellen, ob mehrere Broadcast-Domänen zu einem Satz Erreichbarkeit gehören, verwenden Sie den Befehl „Network Port Reachability show -Details“ und achten Sie darauf, welche Ports, die in einer anderen Broadcast-Domäne konfiguriert sind, tatsächlich eine Verbindung miteinander haben („unerwartete Ports“). In der Regel definiert die Liste der unerwarteten Ports den Satz von Ports, die in die Broadcast-Domäne zusammengeführt werden sollen, nachdem Sie überprüft haben, ob die physische Konfiguration und die Switch-Konfiguration korrekt sind.

Die Ports aus einer Broadcast-Domäne in eine vorhandene Broadcast-Domäne zusammenführen:

....
network port broadcast-domain merge -ipspace <ipspace_name> -broadcast-domain <broadcast_domain_name> -into-broadcast-domain <broadcast_domain_name>
....
* `ipspace_name` Ist der Name des ipspace, in dem sich die Broadcast-Domänen befinden.
* `-broadcast-domain` Ist der Name der Broadcast-Domain, die zusammengeführt wird.
* `-into-broadcast-domain` Ist der Name der Broadcast-Domain, die zusätzliche Ports erhält.

