---
sidebar: sidebar 
permalink: networking/modify_mtu_setting_for_interface_group_ports.html 
keywords: modify, modifying, change, changing, mtu, modify mtu setting for interface group ports, modify the mtu of the broadcast domain 
summary: Ändern Sie die MTU der Broadcast-Domain 
---
= MTU-Einstellung für Schnittstellengruppen-Ports ändern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Um die MTU-Einstellung für Schnittstellengruppen zu ändern, müssen Sie die MTU der Broadcast-Domäne ändern.

Die VLAN-MTU-Größe sollte mit der MTU der Broadcast-Domäne der zugrunde liegenden Schnittstellengruppen und physischen Ports übereinstimmen. Wenn für ein VLAN eine andere VLAN-Einstellung erforderlich ist, darf diese die von der zugrunde liegenden Broadcast-Domäne angegebene Größe nicht überschreiten.

.Schritte
. Ändern Sie die Einstellungen für die Broadcast-Domäne:
+
`broadcast-domain modify -broadcast-domain _broadcast_domain_name_ -mtu _mtu_setting_`

+
Die folgende Warnmeldung wird angezeigt:

+
....
Warning: Changing broadcast domain settings will cause a momentary data-serving interruption.
Do you want to continue? {y|n}: y
....
. Geben Sie y ein, um fortzufahren.
. Überprüfen Sie, ob die MTU-Einstellung korrekt geändert wurde:
+
`network port show`



....
network port show
(network port show)
Node: vsim-01
                                                              Ignore
                                         Speed(Mbps) Health   Health
Port IPspace Broadcast Domain  Link  MTU Admin/Oper  Status   Status
---- ------- ----------------  ---- ---- ----------- -------- ------
a0a  Default Default-1         up   1300 auto/1000   healthy  false
e0a  Default Default-1         up   1300 auto/1000   healthy  false
e0b  Default Default           up   1500 auto/1000   healthy  false
e0c  Default Default           up   1500 auto/1000   healthy  false
e0d  Default Default           up   1500 auto/1000   healthy  false
5 entries were displayed.
....