---
sidebar: sidebar 
permalink: networking/move_broadcast_domains.html 
keywords: move, moving, broadcast, domain, ipspace, move broadcast domains into ipspaces, move the system created broadcast domains into the ipspaces you created 
summary: Verschieben Sie die vom System erstellten Broadcast-Domänen in die von Ihnen erstellten IPspaces 
---
= Broadcast-Domänen in IPspaces verschieben (ONTAP 9.8 und höher)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Verschieben Sie die Broadcast-Domänen, die das System auf Basis der Reachability von Ebene 2 erstellt hat, in die von Ihnen erstellten IPspaces.

Bevor Sie die Broadcast-Domäne verschieben, müssen Sie die Erreichbarkeit der Ports in Ihren Broadcast-Domänen überprüfen.

Durch das automatische Scannen von Ports kann bestimmt werden, welche Ports sich gegenseitig erreichen und in derselben Broadcast-Domäne platzieren können, aber dieser Scan kann den entsprechenden IPspace nicht ermitteln. Wenn die Broadcast-Domäne in einem nicht standardmäßigen IPspace gehört, müssen Sie sie manuell verschieben, indem Sie die Schritte in diesem Abschnitt verwenden.

.Bevor Sie beginnen
Broadcast-Domänen werden automatisch als Teil der Cluster-Erstellung und dem Beitritt konfiguriert. ONTAP definiert die Broadcast-Domäne „Standard“ als Satz von Ports mit Layer-2-Konnektivität zum Home Port der Managementoberfläche auf dem ersten im Cluster erstellten Node. Andere Broadcast-Domänen werden, falls erforderlich, erstellt und werden mit *Default-1*, *Default-2* usw. bezeichnet.

Wenn ein Knoten einem vorhandenen Cluster beitreten wird, werden ihre Netzwerkports basierend auf der Reachability der Ebene 2 automatisch zu bestehenden Broadcast-Domänen verbunden. Wenn sie nicht auf eine vorhandene Broadcast-Domäne hin- und wieder verfügbar sind, werden die Ports in eine oder mehrere neue Broadcast-Domänen platziert.

.Über diese Aufgabe
* Ports mit Cluster-LIFs werden automatisch im IPspace „Cluster“ platziert.
* Ports, die auf den Home Port der Node-Management-LIF zugreifen können, werden in der Broadcast-Domäne „Standard“ platziert.
* Andere Broadcast-Domänen werden von ONTAP automatisch als Teil der Cluster-Erstellung oder dem Cluster-Vorgang hinzugefügt.
* Wenn Sie VLANs und Schnittstellengruppen hinzufügen, werden sie ca. eine Minute nach der Erstellung automatisch in die entsprechende Broadcast-Domäne platziert.


.Schritte
. Überprüfen Sie die Erreichbarkeit der Ports in Ihren Broadcast-Domänen. ONTAP überwacht automatisch die Reachabilität der Ebene 2. Mit dem folgenden Befehl können Sie überprüfen, ob jeder Port einer Broadcast-Domäne hinzugefügt wurde und auf „ok“-Erreichbarkeit verfügt.
+
`network port reachability show -detail`

. Bei Bedarf Broadcast-Domänen in andere IPspaces verschieben:
+
`network port broadcast-domain move`

+
Beispiel: Wenn Sie eine Broadcast-Domäne von „Standard“ auf „ips1“ verschieben möchten:

+
`network port broadcast-domain move -ipspace Default -broadcast-domain Default -to-ipspace ips1`


