---
sidebar: sidebar 
permalink: networking/removing_a_nic_from_the_node.html 
keywords: delete, deleting, remove, removing, nic, network, interface, card, slot, maintenance, faulty, error, bad, failed, fail, node, remove a faulty NIC from its slot or move the NIC to another slot for maintenance purposes, removing a nic from the node on ontap 9.8 or later, controller-replacement, network displaced-vlans, displaced-vlans show, displaced-vlans restore, 
summary: 'ONTAP 9.8 und höher: Entfernen Sie eine defekte Netzwerkkarte aus ihrem Steckplatz oder versetzen Sie die Netzwerkkarte zu Wartungszwecken in einen anderen Steckplatz.' 
---
= Netzwerkkarten aus ONTAP Clusterknoten entfernen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie eine defekte Netzwerkkarte aus ihrem Steckplatz entfernen oder die Netzwerkkarte zu Wartungszwecken in einen anderen Steckplatz umstecken.


NOTE: Die Vorgehensweise zum Entfernen einer Netzwerkkarte (NIC) unterscheidet sich in ONTAP 9.7 und früheren Versionen. Für das Entfernen einer Netzwerkkarte von einem ONTAP Clusterknoten mit ONTAP 9.7 oder einer früheren Version ist die entsprechende Vorgehensweise unter link:https://docs.netapp.com/us-en/ontap-system-manager-classic/networking/remove_a_nic_from_the_node_97.html["Entfernen einer Netzwerkkarte aus dem Knoten (ONTAP 9.7 oder früher)"^] zu beachten.

.Schritte
. Den Knoten ausschalten.
. Die Netzwerkkarte wird physisch aus ihrem Steckplatz entfernt.
. Den Knoten einschalten.
. Überprüfen, ob der Port gelöscht wurde:
+
....
network port show
....
+

NOTE: ONTAP entfernt den Port automatisch aus allen Schnittstellengruppen. Wenn der Port das einzige Mitglied einer Schnittstellengruppe war, wird die Schnittstellengruppe gelöscht. Weitere Informationen zu  `network port show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html["ONTAP-Befehlsreferenz"^].

. Falls für den Port VLANs konfiguriert waren, werden diese verschoben. Die verschobenen VLANs lassen sich mit folgendem Befehl anzeigen:
+
....
cluster controller-replacement network displaced-vlans show
....
+

NOTE: Die  `displaced-interface show`,  `displaced-vlans show` und  `displaced-vlans restore` Befehle sind einzigartig und benötigen nicht den vollqualifizierten Befehlsnamen, der mit  `cluster controller-replacement network` beginnt.

. Diese VLANs werden gelöscht, können aber mit folgendem Befehl wiederhergestellt werden:
+
....
displaced-vlans restore
....
. Falls für den Port LIFs konfiguriert waren, wählt ONTAP automatisch neue Home-Ports für diese LIFs auf einem anderen Port in derselben Broadcast-Domäne. Wird kein geeigneter Home-Port auf demselben Filer gefunden, gelten diese LIFs als verschoben. Verschobene LIFs lassen sich mit folgendem Befehl anzeigen:
+
`displaced-interface show`

. Wird dem Broadcast-Bereich auf demselben Knoten ein neuer Port hinzugefügt, werden die Home-Ports der LIFs automatisch wiederhergestellt. Alternativ lässt sich der Home-Port mit dem  `network interface modify -home-port -home-node or use the displaced- interface restore` Befehl festlegen.


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/cluster-controller-replacement-network-displaced-interface-delete.html["Cluster Controller-Ersatznetzwerk verschobene Schnittstelle löschen"^]
* link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html["Netzwerkschnittstelle ändern"^]

