---
sidebar: sidebar 
permalink: networking/remove_a_nic_from_the_node_97.html 
keywords: delete, deleting, remove, removing, nic, network, interface, card, slot, maintenance, faulty, error, bad, failed, fail, node, removing a nic from the node on ontap 9.7 or earlier, network port delete, network port show, remove a faulty nic from its slot or move the nic to another slot for maintenance purposes 
summary: Entfernen Sie bei ONTAP 9.7 und einer älteren Version eine fehlerhafte NIC aus ihrem Steckplatz, oder verschieben Sie die NIC zu Wartungszwecken in einen anderen Steckplatz 
---
= Entfernen einer NIC aus dem Knoten (ONTAP 9.7 oder früher)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dieses Thema bezieht sich auf ONTAP 9.7 oder früher. Sie müssen möglicherweise eine fehlerhafte NIC aus ihrem Steckplatz entfernen oder die NIC zu Wartungszwecken in einen anderen Steckplatz verschieben.

.Bevor Sie beginnen
* Alle auf den NIC-Ports gehosteten LIFs müssen migriert oder gelöscht wurden.
* Bei den NIC-Ports kann es sich nicht um die Home-Ports beliebiger LIFs befinden.
* Sie müssen über erweiterte Berechtigungen verfügen, um die Ports von einer NIC löschen zu können.


.Schritte
. Löschen Sie die Ports aus der NIC:
+
`network port delete`

. Überprüfen Sie, ob die Ports gelöscht wurden:
+
`network port show`

. Wiederholen Sie Schritt 1, wenn in der Ausgabe des Befehls „Network Port show“ der gelöschte Port angezeigt wird.

