---
sidebar: sidebar 
permalink: networking/remove_ports_from_a_broadcast_domain.html 
keywords: move, moving, broadcast, domain, ipspace, remove ports from a broadcast domain, broadcast-domain remove-ports 
summary: Entfernen Sie Ports aus einer Broadcast-Domäne 
---
= Entfernen Sie Ports aus einer Broadcast-Domäne
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn sich die Ports, die Sie der neuen Broadcast-Domäne hinzufügen möchten, bereits in einer anderen Broadcast-Domäne befinden, müssen Sie die Ports aus dieser Broadcast-Domäne entfernen, bevor Sie sie der neuen Broadcast-Domäne zuordnen.


NOTE: Diese Aufgabe ist relevant für ONTAP 9.0 - 9.7, nicht für ONTAP 9.8.

Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.

.Schritte
. Entfernen Sie die Ports aus der Broadcast-Domäne, indem Sie Folgendes angeben:
+
** IP-Bereich, `Default` In der folgenden Probe.
** Broadcast-Domäne `Default` In der folgenden Probe.
** Ports unter Verwendung der Node- und Port-Syntax, `node1:e0d,node1:e0e,node2:e0d,node2:e0e` In der folgenden Probe.
+
[listing]
----
network port broadcast-domain remove-ports -ipspace Default -broadcast-domain Default -ports node1:e0d,node1:e0e,node2:e0d,node2:e0e
----


. Vergewissern Sie sich, dass die Ports aus der Broadcast-Domäne entfernt wurden:
+
`network port show`


