---
sidebar: sidebar 
permalink: networking/split_broadcast_domains.html 
keywords: split, broadcast, domain, separate, splitting, separating, reachability, port, split a broadcast domain to synchronize the ontap configuration with the physical network topology, unreachable ports, broadcast-domain split, split broadcast domains 
summary: Teilen Sie eine Broadcast-Domäne auf, um die ONTAP 9.8 und spätere Konfiguration mit der physischen Netzwerktopologie zu synchronisieren. 
---
= Aufteilung von ONTAP Broadcast-Domänen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Wenn sich die Erreichbarkeit von Netzwerkports geändert hat, sei es durch physische Netzwerkverbindungen oder durch eine Switch-Konfiguration, und eine Gruppe von Netzwerkports, die zuvor in einer einzigen Broadcast-Domäne konfiguriert war, in zwei verschiedene Erreichbarkeitsgruppen aufgeteilt wurde, kann eine Broadcast-Domäne aufgeteilt werden, um die ONTAP Konfiguration mit der physischen Netzwerktopologie zu synchronisieren.


NOTE: Die Vorgehensweise zum Aufteilen von Broadcast-Domänen unterscheidet sich in ONTAP 9.7 und früheren Versionen. Wenn Broadcast-Domänen in einem Netzwerk mit ONTAP 9.7 oder einer früheren Version aufgeteilt werden müssen, siehe link:https://docs.netapp.com/us-en/ontap-system-manager-classic/networking-bd/split_broadcast_domains97.html["Aufgeteilte Broadcast-Domänen (ONTAP 9.7 oder früher)"^].

Um festzustellen, ob eine Broadcast-Domäne eines Netzwerkports in mehr als eine Erreichbarkeitsgruppe unterteilt ist, kann der  `network port reachability show -details` Befehl verwendet werden. Dabei ist darauf zu achten, welche Ports keine Verbindung zueinander haben („Nicht erreichbare Ports“). In der Regel definiert die Liste der nicht erreichbaren Ports die Gruppe von Ports, die nach Überprüfung der korrekten physischen und Switch-Konfiguration in eine weitere Broadcast-Domäne aufgeteilt werden sollte. Weitere Informationen zu  `network port reachability show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-port-reachability-show.html["ONTAP-Befehlsreferenz"^].

.Schritt
Eine Broadcast-Domäne in zwei Broadcast-Domänen aufteilen:

....
network port broadcast-domain split -ipspace <ipspace_name> -broadcast-domain <broadcast_domain_name> -new-broadcast-domain <broadcast_domain_name> -ports <node:port,node:port>
....
* `ipspace_name` ist der Name des IP-Adressraums, in dem sich die Broadcast-Domäne befindet.
* -`broadcast-domain` ist der Name der Broadcast-Domain, die aufgeteilt wird.
* -`new-broadcast-domain` ist der Name der neuen Broadcast-Domain, die erstellt wird.
* -`ports` ist der Node-Name und der Port, die der neuen Broadcast-Domäne hinzugefügt werden.


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/network-port-broadcast-domain-split.html["Broadcast-Domänenaufteilung des Netzwerkports"^]

