---
sidebar: sidebar 
permalink: networking/task_testing_snmp_polling.html 
keywords: configure, snmp, verify, poll, cluster, test, test snmp poll 
summary: Nach der Konfiguration von SNMP sollte überprüft werden, ob der Cluster abgefragt werden kann. 
---
= SNMP-Abfrage in einem ONTAP Cluster überprüfen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach der Konfiguration von SNMP sollte überprüft werden, ob der Cluster abgefragt werden kann.

.Über diese Aufgabe
Um einen Cluster abzufragen, müssen Sie einen Drittanbieterbefehl wie  `snmpwalk` verwenden.

.Schritte
. Ein SNMP-Befehl kann gesendet werden, um den Cluster von einem anderen Cluster aus abzufragen.
+
Für Systeme mit SNMPv1 kann der CLI-Befehl  `snmpwalk -v version -c community_stringip_address_or_host_name system` verwendet werden, um den Inhalt der MIB (Management Information Base) zu ermitteln.

+
In diesem Beispiel lautet die IP-Adresse des Cluster-Management-LIF, das Sie abfragen, 10.11.12.123. Der Befehl zeigt die angeforderten Informationen aus der MIB an:

+
[listing]
----
C:\Windows\System32>snmpwalk -v 1 -c public 10.11.12.123 system

SNMPv1-MIB::sysDescr.0 = STRING: NetApp Release 8.3.0
            Cluster-Mode: Tue Apr 22 16:24:48 EDT 2014
SNMPv1-MIB::sysObjectID.0 = OID: SNMPv1-SMI::enterprises.789.2.5
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (162644448) 18 days, 19:47:24.48
SNMPv1-MIB::sysContact.0 = STRING:
SNMPv1-MIB::sysName.0 = STRING: systemname.testlabs.com
SNMPv1-MIB::sysLocation.0 = STRING: Floor 2 Row B Cab 2
SNMPv1-MIB::sysServices.0 = INTEGER: 72
----
+
Für Systeme mit SNMPv2c kann der CLI-Befehl  `snmpwalk -v version -c community_stringip_address_or_host_name system` verwendet werden, um den Inhalt der MIB (Management Information Base) zu ermitteln.

+
In diesem Beispiel lautet die IP-Adresse des Cluster-Management-LIF, das Sie abfragen, 10.11.12.123. Der Befehl zeigt die angeforderten Informationen aus der MIB an:

+
[listing]
----
C:\Windows\System32>snmpwalk -v 2c -c public 10.11.12.123 system

SNMPv2-MIB::sysDescr.0 = STRING: NetApp Release 8.3.0
            Cluster-Mode: Tue Apr 22 16:24:48 EDT 2014
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.789.2.5
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (162635772) 18 days, 19:45:57.72
SNMPv2-MIB::sysContact.0 = STRING:
SNMPv2-MIB::sysName.0 = STRING: systemname.testlabs.com
SNMPv2-MIB::sysLocation.0 = STRING: Floor 2 Row B Cab 2
SNMPv2-MIB::sysServices.0 = INTEGER: 72
----
+
Für Systeme mit SNMPv3 kann der CLI-Befehl  `snmpwalk -v 3 -a MD5 or SHA -l authnopriv -u username -A passwordip_address_or_host_name system` verwendet werden, um den Inhalt der MIB (Management Information Base) zu ermitteln.

+
In diesem Beispiel lautet die IP-Adresse des Cluster-Management-LIF, das Sie abfragen, 10.11.12.123. Der Befehl zeigt die angeforderten Informationen aus der MIB an:

+
[listing]
----
C:\Windows\System32>snmpwalk -v 3 -a MD5 -l authnopriv -u snmpv3
       -A password123 10.11.12.123 system

SNMPv3-MIB::sysDescr.0 = STRING: NetApp Release 8.3.0
       Cluster-Mode: Tue Apr 22 16:24:48 EDT 2014
SNMPv3-MIB::sysObjectID.0 = OID: SNMPv3-SMI::enterprises.789.2.5
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (162666569) 18 days, 19:51:05.69
SNMPv3-MIB::sysContact.0 = STRING:
SNMPv3-MIB::sysName.0 = STRING: systemname.testlabs.com
SNMPv3-MIB::sysLocation.0 = STRING: Floor 2 Row B Cab 2
SNMPv3-MIB::sysServices.0 = INTEGER: 72
----

