---
sidebar: sidebar 
permalink: networking/use_cdp_to_detect_network_connectivity.html 
keywords: display, view, show, network, connectivity, neighbor, discovery, protocol, cdp, use cdp to detect network connectivity, considerations for using cdp, enable or disable cdp, view cdp neighbor information, example of showing and clearing statistics, cisco 
summary: In einem Rechenzentrum können Nachbarerkennungsprotokolle verwendet werden, um die Netzwerkverbindungen zwischen einem Paar physischer oder virtueller Systeme und deren Netzwerkschnittstellen anzuzeigen. ONTAP unterstützt zwei Neighbor-Discovery-Protokolle, Cisco Discovery Protocol und Link Layer Discovery Protocol. 
---
= CDP kann zur Erkennung der ONTAP-Netzwerkverbindung verwendet werden.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die Verwendung von CDP zur Erkennung von Netzwerkverbindungen umfasst die Prüfung der Bereitstellungsaspekte, die Aktivierung an Datenports, die Anzeige benachbarter Geräte und die gegebenenfalls erforderliche Anpassung der CDP-Konfigurationswerte. CDP ist standardmäßig an Clusterports aktiviert.

CDP muss außerdem auf allen Ethernet Switches und Routern aktiviert sein, bevor Informationen über benachbarte Geräte angezeigt werden können.

.Verwandte Informationen
link:../system-admin/index.html["Systemadministration"]



[[considerations-for-using-cdp]]
== Überlegungen zur Verwendung von CDP

Standardmäßig senden CDP-kompatible Geräte CDPv2-Ankündigungen. CDP-kompatible Geräte senden CDPv1-Ankündigungen nur, wenn sie CDPv1-Ankündigungen empfangen. ONTAP unterstützt nur CDPv1. Daher senden benachbarte CDP-kompatible Geräte CDPv1-Ankündigungen zurück, wenn ein ONTAP Node CDPv1-Ankündigungen sendet.

Vor der Aktivierung von CDP auf einem Node sind die folgenden Informationen zu berücksichtigen:

* CDP wird für alle Ports unterstützt.
* CDP-Anzeigen werden von Ports im aktiven Zustand gesendet und empfangen.
* CDP muss sowohl auf dem sendenden als auch auf dem empfangenden Gerät aktiviert sein, damit CDP-Anzeigen gesendet und empfangen werden können.
* CDP-Anzeigen werden in regelmäßigen Abständen gesendet, und das Zeitintervall kann konfiguriert werden.
* Wenn die IP-Adressen für eine LIF geändert werden, sendet der Node die aktualisierten Informationen in der nächsten CDP-Ankündigung.
* ONTAP 9.10.1 und früher:
+
** CDP ist auf Cluster-Ports immer aktiviert.
** CDP ist standardmäßig auf allen Nicht-Cluster-Ports deaktiviert.


* ONTAP 9.11.1 und höher:
+
** CDP ist auf Cluster- und Speicher-Ports immer aktiviert.
** CDP ist standardmäßig auf allen Nicht-Cluster- und Nicht-Speicher-Ports deaktiviert.





NOTE: Manchmal werden die CDP-Informationen auf der Empfängerseite (z. B. einem Ethernet-Switch) nicht aktualisiert, wenn LIFs auf dem Knoten geändert werden. Tritt ein solches Problem auf, kann die Netzwerkschnittstelle des Knotens zunächst in den Status "down" und anschließend in den Status "up" versetzt werden.

* Nur IPv4-Adressen werden in CDP-Anzeigen bekanntgegeben.
* Für physische Netzwerk-Ports mit VLANs werden alle auf den VLANs dieses Ports konfigurierten LIFs bekanntgegeben.
* Für physische Ports, die Teil einer Schnittstellengruppe sind, werden alle auf dieser Schnittstellengruppe konfigurierten IP-Adressen auf jedem physischen Port bekanntgegeben.
* Für eine Schnittstellengruppe, die VLANs hostet, werden alle auf der Schnittstellengruppe und den VLANs konfigurierten LIFs auf jedem der Netzwerkports angekündigt.
* Da CDP-Pakete auf maximal 1500 Bytes beschränkt sind, kann auf Ports, die mit einer großen Anzahl von LIFs konfiguriert sind, nur eine Teilmenge dieser IP-Adressen auf dem benachbarten Switch gemeldet werden.




[[enable-or-disable-cdp]]
== CDP aktivieren oder deaktivieren

Um CDP-kompatible Nachbargeräte zu erkennen und ihnen Werbung zu senden, muss CDP auf jedem Knoten des Clusters aktiviert sein.

In ONTAP 9.10.1 und früher ist CDP standardmäßig auf allen Cluster-Ports eines Knotens aktiviert und auf allen Nicht-Cluster-Ports eines Knotens deaktiviert.

In ONTAP 9.11.1 und später ist CDP standardmäßig auf allen Cluster- und Speicher-Ports eines Knotens aktiviert und auf allen Nicht-Cluster- und Nicht-Speicher-Ports eines Knotens deaktiviert.

.Über diese Aufgabe
Die  `cdpd.enable`Option steuert, ob CDP an den Ports eines Knotens aktiviert oder deaktiviert ist:

* Bei ONTAP 9.10.1 und früher wird CDP auf Nicht-Cluster-Ports aktiviert.
* Ab ONTAP 9.11.1 wird CDP auf Nicht-Cluster- und Nicht-Storage-Ports aktiviert.
* Bei ONTAP 9.10.1 und früher deaktiviert „off“ CDP auf Nicht-Cluster-Ports; CDP kann auf Cluster-Ports nicht deaktiviert werden.
* Für ONTAP 9.11.1 und höher deaktiviert „off“ CDP auf Nicht-Cluster- und Nicht-Speicher-Ports; auf Cluster-Ports kann CDP nicht deaktiviert werden.


Wenn CDP an einem Port deaktiviert ist, der mit einem CDP-kompatiblen Gerät verbunden ist, könnte der Netzwerkverkehr möglicherweise nicht optimiert sein.

.Schritte
. Die aktuelle CDP-Einstellung für einen Knoten oder für alle Knoten in einem Cluster anzeigen:
+
[cols="30,70"]
|===


| Die CDP-Einstellung von ... kann angezeigt werden... | Eingeben... 


 a| 
Ein Knoten
 a| 
`run - node <node_name> options cdpd.enable`



 a| 
Alle Knoten in einem Cluster
 a| 
`options cdpd.enable`

|===
. CDP auf allen Ports eines Knotens oder auf allen Ports aller Knoten in einem Cluster aktivieren oder deaktivieren:
+
[cols="30,70"]
|===


| CDP kann auf ... aktiviert oder deaktiviert werden. | Eingeben... 


 a| 
Ein Knoten
 a| 
`run -node node_name options cdpd.enable {on or off}`



 a| 
Alle Knoten in einem Cluster
 a| 
`options cdpd.enable {on or off}`

|===




[[view-cdp-neighbor-information]]
== CDP-Nachbarinformationen anzeigen

Sie können Informationen über die benachbarten Geräte anzeigen, die mit jedem Port der Knoten Ihres Clusters verbunden sind, vorausgesetzt, der Port ist mit einem CDP-kompatiblen Gerät verbunden. Mit dem  `network device-discovery show -protocol cdp` Befehl lassen sich Nachbarinformationen anzeigen. Weitere Informationen zu  `network device-discovery show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-device-discovery-show.html["ONTAP-Befehlsreferenz"^].

.Über diese Aufgabe
In ONTAP 9.10.1 und früher, da CDP für Cluster-Ports immer aktiviert ist, werden die CDP-Nachbarinformationen für diese Ports immer angezeigt. CDP muss auf Nicht-Cluster-Ports aktiviert sein, damit die Nachbarinformationen für diese Ports angezeigt werden.

In ONTAP 9.11.1 und höher ist CDP für Cluster- und Speicherports immer aktiviert, daher werden die CDP-Nachbarinformationen für diese Ports stets angezeigt. CDP muss auf Nicht-Cluster- und Nicht-Speicherports aktiviert sein, damit die Nachbarinformationen für diese Ports angezeigt werden.

.Schritt
Informationen über alle CDP-kompatiblen Geräte, die mit den Ports eines Knotens im Cluster verbunden sind, werden angezeigt:

....
network device-discovery show -node node -protocol cdp
....
Der folgende Befehl zeigt die Nachbarn, die mit den Ports des Knotens sti2650-212 verbunden sind:

....
network device-discovery show -node sti2650-212 -protocol cdp
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
sti2650-212/cdp
            e0M    RTP-LF810-510K37.gdl.eng.netapp.com(SAL1942R8JS)
                                             Ethernet1/14      N9K-C93120TX
            e0a    CS:RTP-CS01-510K35        0/8               CN1610
            e0b    CS:RTP-CS01-510K36        0/8               CN1610
            e0c    RTP-LF350-510K34.gdl.eng.netapp.com(FDO21521S76)
                                             Ethernet1/21      N9K-C93180YC-FX
            e0d    RTP-LF349-510K33.gdl.eng.netapp.com(FDO21521S4T)
                                             Ethernet1/22      N9K-C93180YC-FX
            e0e    RTP-LF349-510K33.gdl.eng.netapp.com(FDO21521S4T)
                                             Ethernet1/23      N9K-C93180YC-FX
            e0f    RTP-LF349-510K33.gdl.eng.netapp.com(FDO21521S4T)
                                             Ethernet1/24      N9K-C93180YC-FX
....
Die Ausgabe listet die Cisco Geräte auf, die mit jedem Port des angegebenen Knotens verbunden sind.



[[configure-the-hold-time-for-cdp-messages]]
== Die Haltezeit für CDP-Nachrichten konfigurieren

Die Haltezeit ist der Zeitraum, für den CDP-Ankündigungen im Cache benachbarter CDP-kompatibler Geräte gespeichert werden. Die Haltezeit wird in jedem CDPv1-Paket angekündigt und aktualisiert, wenn ein Knoten ein CDPv1-Paket empfängt.

* Der Wert der  `cdpd.holdtime` Option sollte auf beiden Knoten eines HA-Paares auf den gleichen Wert eingestellt werden.
* Der Standardwert für die Haltezeit beträgt 180 Sekunden, es können jedoch Werte zwischen 10 Sekunden und 255 Sekunden eingegeben werden.
* Wird eine IP-Adresse vor Ablauf der Aufbewahrungsfrist entfernt, werden die CDP-Informationen bis zum Ablauf der Aufbewahrungsfrist zwischengespeichert.


.Schritte
. Die aktuelle CDP-Haltezeit für einen Knoten oder für alle Knoten in einem Cluster anzeigen:
+
[cols="30,70"]
|===


| Die Wartezeit kann angezeigt werden... | Eingeben... 


 a| 
Ein Knoten
 a| 
`run -node node_name options cdpd.holdtime`



 a| 
Alle Knoten in einem Cluster
 a| 
`options cdpd.holdtime`

|===
. Die CDP-Haltezeit auf allen Ports eines Knotens oder auf allen Ports aller Knoten in einem Cluster konfigurieren:
+
[cols="30,70"]
|===


| Die Haltezeit kann eingestellt werden... | Eingeben... 


 a| 
Ein Knoten
 a| 
`run -node node_name options cdpd.holdtime holdtime`



 a| 
Alle Knoten in einem Cluster
 a| 
`options cdpd.holdtime holdtime`

|===




[[set-the-interval-for-sending-cdp-advertisements]]
== Das Intervall für das Senden von CDP-Anzeigen festlegen

CDP-Ankündigungen werden in regelmäßigen Abständen an CDP-Nachbarn gesendet. Das Intervall für das Senden von CDP-Ankündigungen kann je nach Netzwerkverkehr und Änderungen in der Netzwerktopologie erhöht oder verringert werden.

* Der Wert der  `cdpd.interval` Option sollte auf beiden Knoten eines HA-Paares auf den gleichen Wert eingestellt werden.
* Das Standardintervall beträgt 60 Sekunden, aber es kann ein Wert zwischen 5 und 900 Sekunden eingegeben werden.


.Schritte
. Das aktuelle CDP-Werbezeitintervall für einen Knoten oder für alle Knoten in einem Cluster anzeigen:
+
[cols="30,70"]
|===


| Das Intervall für ... kann angezeigt werden. | Eingeben... 


 a| 
Ein Knoten
 a| 
`run -node node_name options cdpd.interval`



 a| 
Alle Knoten in einem Cluster
 a| 
`options cdpd.interval`

|===
. Das Intervall für das Senden von CDP-Ankündigungen für alle Ports eines Knotens oder für alle Ports aller Knoten in einem Cluster konfigurieren:
+
[cols="30,70"]
|===


| Das Intervall für ... festlegen | Eingeben... 


 a| 
Ein Knoten
 a| 
`run -node node_name options cdpd.interval interval`



 a| 
Alle Knoten in einem Cluster
 a| 
`options cdpd.interval interval`

|===




[[view-or-clear-cdp-statistics]]
== CDP-Statistiken anzeigen oder löschen

Sie können die CDP-Statistiken für die Cluster- und Nicht-Cluster-Ports auf jedem Knoten einsehen, um potenzielle Netzwerkverbindungsprobleme zu erkennen. Die CDP-Statistiken sind seit ihrer letzten Löschung kumulativ.

.Über diese Aufgabe
In ONTAP 9.10.1 und früher, da CDP für Ports immer aktiviert ist, werden CDP-Statistiken für den Datenverkehr auf diesen Ports immer angezeigt. CDP muss auf Ports aktiviert sein, damit Statistiken für diese Ports angezeigt werden.

In ONTAP 9.11.1 und höher ist CDP für Cluster- und Speicherports immer aktiviert, daher werden CDP-Statistiken für den Datenverkehr auf diesen Ports stets angezeigt. CDP muss auf Nicht-Cluster- oder Nicht-Speicherports aktiviert sein, damit Statistiken für diese Ports angezeigt werden.

.Schritt
Aktuelle CDP-Statistiken für alle Ports eines Knotens anzeigen oder löschen:

[cols="30,70"]
|===


| Wenn Sie möchten... | Eingeben... 


 a| 
CDP-Statistiken anzeigen
 a| 
`run -node node_name cdpd show-stats`



 a| 
CDP-Statistiken löschen
 a| 
`run -node node_name cdpd zero-stats`

|===


[[example-of-showing-and-clearing-statistics]]
=== Beispiel für das Anzeigen und Löschen von Statistiken

Der folgende Befehl zeigt die CDP-Statistiken an, bevor sie gelöscht werden. Die Ausgabe zeigt die Gesamtzahl der Pakete, die seit dem letzten Löschen der Statistiken gesendet und empfangen wurden.

....
run -node node1 cdpd show-stats

RECEIVE
 Packets:         9116  | Csum Errors:       0  | Unsupported Vers:  4561
 Invalid length:     0  | Malformed:         0  | Mem alloc fails:      0
 Missing TLVs:       0  | Cache overflow:    0  | Other errors:         0

TRANSMIT
 Packets:         4557  | Xmit fails:        0  | No hostname:          0
 Packet truncated:   0  | Mem alloc fails:   0  | Other errors:         0

OTHER
 Init failures:      0
....
Der folgende Befehl löscht die CDP Statistiken:

....
run -node node1 cdpd zero-stats
....
....
run -node node1 cdpd show-stats

RECEIVE
 Packets:            0  | Csum Errors:       0  | Unsupported Vers:     0
 Invalid length:     0  | Malformed:         0  | Mem alloc fails:      0
 Missing TLVs:       0  | Cache overflow:    0  | Other errors:         0

TRANSMIT
 Packets:            0  | Xmit fails:        0  | No hostname:          0
 Packet truncated:   0  | Mem alloc fails:   0  | Other errors:         0

OTHER
 Init failures:      0
....
Nachdem die Statistiken gelöscht wurden, beginnen sie nach dem Senden oder Empfangen der nächsten CDP-Werbung wieder zu zählen.



[[connecting-to-ethernet-switches-that-do-not-support-cdp]]
== Verbindung mit Ethernet-Switches, die CDP nicht unterstützen

Einige Switches verschiedener Hersteller unterstützen CDP nicht. Siehe die link:https://kb.netapp.com/onprem/ontap/da/NAS/ONTAP_device_discovery_shows_nodes_instead_of_the_switch["NetApp Knowledge Base: ONTAP Geräteerkennung zeigt Knoten anstelle des Switches an"^] für weitere Details.

Es gibt zwei Möglichkeiten, dieses Problem zu lösen:

* CDP deaktivieren und LLDP aktivieren, sofern unterstützt. Weitere Einzelheiten sind unter link:use_lldp_to_detect_network_connectivity.html["LLDP zur Erkennung der Netzwerkverbindung verwenden"] zu finden.
* Ein MAC-Adress-Paketfilter auf den Switches wird konfiguriert, sodass CDP-Ankündigungen verworfen werden.

