---
sidebar: sidebar 
permalink: networking/view_network_information_overview.html 
keywords: overview, introduction, introducing, view, show, display, network, information, ports, LIFs, routes, failover rules, failover groups, firewall rules, DNS, NIS, connections, view network information overview, network information, export, CSV, system manager, cli 
summary: Informationen zu Ports, LIFs, Routen, Failover-Regeln, Failover-Gruppen, Firewall-Regeln, DNS, NIS und Verbindungen anzeigen und herunterladen. 
---
= ONTAP Netzwerkinformationen anzeigen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Über die CLI können Sie Informationen zu Ports, LIFs, Routen, Failover-Regeln, Failover-Gruppen, Firewall-Regeln, DNS, NIS und Verbindungen anzeigen. Ab ONTAP 9.8 ist es außerdem möglich, die im System Manager angezeigten Daten zu Ihrem Netzwerk herunterzuladen.

Diese Informationen können in Situationen wie der Neukonfiguration von Netzwerkeinstellungen oder bei der Fehlerbehebung im Cluster nützlich sein.

Wenn Sie Cluster-Administrator sind, können Sie alle verfügbaren Netzwerkinformationen anzeigen. Wenn Sie SVM-Administrator sind, können Sie nur die Informationen zu Ihren zugewiesenen SVMs anzeigen.

Im System Manager kann bei der Anzeige von Informationen in einer _Listenansicht_ auf *Herunterladen* geklickt werden, und die angezeigte Objektliste wird heruntergeladen.

* Die Liste wird im Format für durch Kommas getrennte Werte (CSV) heruntergeladen.
* Nur die Daten in den sichtbaren Spalten werden heruntergeladen.
* Der CSV-Dateiname ist mit dem Objektnamen und einem Zeitstempel formatiert.

