---
sidebar: sidebar 
permalink: networking/what_mibs_are.html 
keywords: 'introducing, introduction, overview, mib, management information base, text, structure, netapp.mib, what mibs are, introducing management information bases (mibs), snmp objects and traps, object identifiers, oids, traps.dat' 
summary: 'Einführung in Management Information Bases (MIBs)' 
---
= Was sind MIBs
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Eine MIB (Management Information Base) ist eine Textdatei, die SNMP-Objekte und Traps beschreibt.

MIBs beschreiben die Struktur der Managementdaten des Storage-Systems und verwenden einen hierarchischen Namespace mit Objekt-IDs (OIDs). Jede OID identifiziert eine Variable, die über SNMP gelesen werden kann.

Da MIBs keine Konfigurationsdateien sind und ONTAP diese Dateien nicht liest, wird die SNMP-Funktionalität von MIBs nicht beeinflusst. ONTAP bietet die folgende MIB-Datei:

* Eine individuelle NetApp MIB (`netapp.mib`)


ONTAP unterstützt IPv6 (RFC 2465), TCP (RFC 4022), UDP (RFC 4113) und ICMP (RFC 2466) MIBs, die sowohl IPv4- als auch IPv6-Daten enthalten, werden unterstützt.

ONTAP bietet außerdem eine kurze Querverweis zwischen Objekt-IDs (OIDs) und Objektkurznamen in `traps.dat` Datei:


NOTE: Die neuesten Versionen der Dateien ONTAP MIBs und `traps.dat `stehen auf der NetApp Support-Website zur Verfügung. Allerdings entsprechen die Versionen dieser Dateien auf der Support-Website nicht unbedingt den SNMP-Fähigkeiten Ihrer ONTAP-Version. Diese Dateien werden bereitgestellt, um Ihnen zu helfen, SNMP-Funktionen in der neuesten ONTAP-Version zu bewerten.
