---
permalink: concepts/administrator-authentication-rbac-concept.html 
sidebar: sidebar 
keywords: administrator authentication, rbac 
summary: 'Administratoren verwenden lokale oder Remote-Anmeldekonten, um sich am Cluster und an der SVM zu authentifizieren. Role-Based Access Control (RBAC) legt fest, auf welche Befehle ein Administrator Zugriff hat.' 
---
= Administratorauthentifizierung und RBAC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Administratoren verwenden lokale oder Remote-Anmeldekonten, um sich am Cluster und an der SVM zu authentifizieren. Role-Based Access Control (RBAC) legt fest, auf welche Befehle ein Administrator Zugriff hat.



[[authentication]]
== Authentifizierung

Es können lokale oder Remote-Cluster- und SVM-Administratorkonten erstellt werden:

* Bei einem lokalen Konto befinden sich die Kontoinformationen, der öffentliche Schlüssel oder das Sicherheitszertifikat auf dem Speichersystem.
* Bei einem Remote-Konto werden die Kontoinformationen auf einem Active Directory Domänencontroller, einem LDAP Server oder einem NIS Server gespeichert.


Mit Ausnahme von DNS verwendet ONTAP dieselben Namensdienste zur Authentifizierung von Administratorkonten wie zur Authentifizierung von Clients.



[[rbac]]
== RBAC

Die einem Administrator zugewiesene Rolle bestimmt, auf welche Befehle der Administrator Zugriff hat. Die Rolle wird zugewiesen, wenn das Konto für den Administrator erstellt wird. Es kann bei Bedarf eine andere Rolle zugewiesen oder benutzerdefinierte Rollen definiert werden.
