---
sidebar: sidebar 
permalink: concepts/capacity-measurements-in-sm-concept.html 
keywords: capacity, measurement, physical, logical, storage, used storage, local tier capacity, aggregate capacity, block, capacity concern, add capacity, volume, used capacity, available capacity, total capacity, inactive capacity, static insights, dynamic insights, snapshot copy, snapshot copies, inactive data, overprovision, overflows, snapshot copy policy, snapshot copy reserves, reserves, policy, top volumes 
summary: Die Systemkapazität kann als physischer oder logischer Speicherplatz gemessen werden. In neueren Versionen von System Manager werden Messungen physischer und logischer Kapazitäten verwendet. 
---
= Kapazitätsmessungen in System Manager
:allow-uri-read: 


[role="lead"]
Die Systemkapazität kann als physischer oder logischer Speicherplatz gemessen werden. In neueren Versionen von System Manager werden Messungen physischer und logischer Kapazitäten verwendet.

Die Unterschiede zwischen den beiden Messungen werden in den folgenden Beschreibungen erläutert:

* *Physische Kapazität*: Physischer Platz bezieht sich auf die physischen Speicherblöcke, die im Volume oder der lokalen Ebene verwendet werden. Der Wert der verwendeten physischen Kapazität ist normalerweise kleiner als der Wert der logischen genutzten Kapazität, aufgrund der Reduzierung von Daten durch Storage-Effizienzfunktionen (wie Deduplizierung und Komprimierung).
* *Logische Kapazität*: Logischer Raum bezieht sich auf den nutzbaren Speicherplatz (die logischen Blöcke) in einem Volume oder einem lokalen Tier. Logischer Speicherplatz bezeichnet die Art und Weise, wie theoretischer Speicherplatz verwendet werden kann, ohne dabei die Folgen der Deduplizierung oder Komprimierung berücksichtigen zu müssen. Der Wert des logischen Speicherplatzes ergibt sich aus der Menge des verwendeten physischen Speicherplatzes plus den Einsparungen durch konfigurierte Storage-Effizienzfunktionen (z. B. Deduplizierung und Komprimierung). Diese Messung erscheint oft größer als die physisch genutzte Kapazität, da sie Snapshot-Kopien, Klone und andere Komponenten umfasst. Außerdem werden die Datenkomprimierung und andere Platzeinsparungen nicht berücksichtigt. Somit kann die logische Gesamtkapazität über dem bereitgestellten Speicherplatz liegen.



NOTE: In System Manager werden Kapazitätsdarstellungen nicht auf die Root Storage Tier (Aggregat)-Kapazitäten angerechnet.

<<measurements-used-cap>>
<<cap-measurement-terms>>
<<cap-measurement-units>>

.Weitere Informationen
Überwachen Sie die Kapazität eines Clusters, lokaler Tiers und Volumes in System Manager. Siehe link:../task_admin_monitor_capacity_in_sm.html["Überwachung der Kapazität in System Manager"].



== Messungen der genutzten Kapazität

Maße der genutzten Kapazität werden abhängig von der verwendeten Version von System Manager unterschiedlich angezeigt, wie in der folgenden Tabelle erläutert:

[cols="30,30,40"]
|===


| Version von System Manager | Laufzeit für Kapazität genutzt | Art der genannten Kapazität 


 a| 
9.5 und 9.6 (Klassische Ansicht)
 a| 
Verwendet
 a| 
Physischer Speicherplatz belegt



 a| 
9.7 und 9.8
 a| 
Verwendet
 a| 
Genutzter logischer Speicherplatz (wenn Storage-Effizienz-Einstellungen aktiviert wurden)



 a| 
9.9.1 und höher
 a| 
Logisch Verwendet
 a| 
Genutzter logischer Speicherplatz (wenn Storage-Effizienz-Einstellungen aktiviert wurden)

|===


== Begriffe zur Kapazitätsmessung

Bei der Beschreibung der Kapazität werden die folgenden Begriffe verwendet:

* *Verfügbar*: Die Menge des physischen Speicherplatzes, der in einer lokalen Ebene zur Bereitstellung von Volumes verfügbar ist.
* *Kundendaten*: Die Menge des von Client-Daten verwendeten Speicherplatzes (entweder physisch oder logisch).
* * Engagement*: Die Menge der für eine lokale Ebene zugesagt Kapazität.
* *Datenreduzierung*:
+
** *Insgesamt*: Das Verhältnis des gesamten logischen verbrauchten Raums im Vergleich zum physischen genutzten Raum.
** *Ohne Snapshot Kopien und Klone*: Das Verhältnis des logischen Speicherplatzes, der nur von Client-Daten verwendet wird, im Vergleich zu dem physischen Speicherplatz, der nur von Client-Daten verwendet wird.


* *Logisch genutzt*: Der Platz, der bisher genutzt wird, ohne den Platz zu berücksichtigen, der durch Storage-Effizienzfunktionen eingespart wird.
* *Logisch genutzter %*: Der Prozentsatz der aktuell genutzten logischen Kapazität im Vergleich zur bereitgestellten Größe, ausgenommen Snapshot Reserven. Dieser Wert kann größer als 100 % sein, da dazu auch Effizienzeinsparungen im Volume zählen.
* *Physisch genutzt*: Die Menge an Kapazität, die in den physischen Blöcken eines Volumes oder lokalen Tiers verwendet wird.
* *Physisch genutzter %*: Der Prozentsatz der in den physischen Blöcken eines Volumes verwendeten Kapazität im Vergleich zur bereitgestellten Größe.
* *Reserviert*: Die Menge an Speicherplatz, der für bereits bereitgestellte Volumes in einem lokalen Tier reserviert ist.
* *Genutzt und reserviert*: Die Summe des physischen und reservierten Speicherplatzes.




== Kapazitätsmesseinheiten

System Manager berechnet die Storage-Kapazität auf der Basis von Binäreinheiten von 1024 (2^10^) Byte. In ONTAP 9.10.0 und früher wurden diese Einheiten in System Manager als KB, MB, GB, TB und PB angezeigt. Ab ONTAP 9.10.1 werden sie im System Manager als KiB, MiB, gib, tib und PiB angezeigt.


NOTE: Die in System Manager für den Durchsatz verwendeten Einheiten liegen bei allen ONTAP-Versionen weiterhin bei KB/s, MB/s, GB/s, TB/s und PB/s.

[cols="20,20,30,30"]
|===


| In System Manager für ONTAP 9.10.0 und früher angezeigte Kapazitätseinheit | Im System Manager für ONTAP 9.10.1 und höher wird die Kapazitätseinheit angezeigt | Berechnung | Wert in Byte 


 a| 
KB
 a| 
KiB
 a| 
1024
 a| 
1024 Byte



 a| 
MB
 a| 
MIB
 a| 
1024 * 1024
 a| 
1,048,576 Byte



 a| 
GB
 a| 
Gib
 a| 
1024 * 1024 * 1024
 a| 
1,073,741,824 Byte



 a| 
TB
 a| 
TIB
 a| 
1024 * 1024 * 1024 * 1024
 a| 
1,099,511,627,776 Byte



 a| 
PB
 a| 
PIB
 a| 
1024 * 1024 * 1024 * 1024 * 1024
 a| 
1,125,898,010,834,824 Byte

|===
.Weitere Informationen:
link:../volumes/logical-space-reporting-enforcement-concept.html["Berichterstellung und Durchsetzung von logischem Speicherplatz für Volumes"]
