---
permalink: concepts/client-protocols-concept.html 
sidebar: sidebar 
keywords: client protocols 
summary: ONTAP unterstützt alle wichtigen branchenüblichen Client-Protokolle, einschließlich NFS, SMB, FC, FCoE, iSCSI, NVMe und S3. 
---
= Clientprotokolle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP unterstützt alle wichtigen branchenüblichen Client-Protokolle: NFS, SMB, FC, FCoE, iSCSI, NVMe und S3.



[[nfs]]
== NFS

NFS ist das traditionelle Protokoll für den Dateizugriff für UNIX- und LINUX-Systeme. Clients können auf Dateien in ONTAP-Volumes über die folgenden Protokolle zugreifen.

* NFSv3
* NFSv4
* NFSv4.2
* NFSv4.1
* pNFS


Der Dateizugriff kann mithilfe von UNIX-Berechtigungen, NTFS-Berechtigungen oder einer Mischung aus beidem gesteuert werden.

Clients können mit sowohl NFS- als auch SMB-Protokollen auf dieselben Dateien zugreifen.



[[smb]]
== SMB

SMB ist das traditionelle Protokoll für den Dateizugriff auf Windows-Systemen. Clients können auf Dateien in ONTAP-Volumes mithilfe der Protokolle SMB 2.0, SMB 2.1, SMB 3.0 und SMB 3.1.1 zugreifen. Wie bei NFS wird eine Mischung von Berechtigungsstilen unterstützt.

SMB 1.0 ist verfügbar, aber in ONTAP 9.3 und späteren Versionen standardmäßig deaktiviert.



[[fc]]
== FC

Fibre Channel ist das ursprüngliche netzwerkbasierte Blockprotokoll. Anstelle von Dateien stellt ein Blockprotokoll einem Client eine komplette virtuelle Festplatte zur Verfügung. Das traditionelle FC-Protokoll verwendet ein dediziertes FC-Netzwerk mit speziellen FC-Switches und erfordert, dass der Client-Computer über FC-Netzwerkschnittstellen verfügt.

Eine LUN repräsentiert die virtuelle Festplatte, und eine oder mehrere LUNs werden in einem ONTAP Volume gespeichert. Auf dieselbe LUN kann über die Protokolle FC, FCoE und iSCSI zugegriffen werden, jedoch können mehrere Clients nur dann auf dieselbe LUN zugreifen, wenn sie Teil eines Clusters sind, der Schreibkonflikte verhindert.



[[fcoe]]
== FCoE

FCoE ist im Grunde dasselbe Protokoll wie FC, verwendet aber anstelle des herkömmlichen FC-Transports ein Ethernet-Netzwerk in Rechenzentrumsqualität. Der Client benötigt weiterhin eine FCoE-spezifische Netzwerkschnittstelle.



[[iscsi]]
== iSCSI

iSCSI ist ein Blockprotokoll, das in Standard-Ethernet-Netzwerken ausgeführt werden kann. Die meisten Client-Betriebssysteme bieten einen Softwareinitiator, der über einen Standard-Ethernet-Port läuft. iSCSI ist eine gute Wahl, wenn ein Blockprotokoll für eine bestimmte Anwendung benötigt wird, aber kein dediziertes FC-Netzwerk zur Verfügung steht.



[[nvmefc-and-nvmetcp]]
== NVMe/FC und NVMe/TCP

Das neueste Blockprotokoll, NVMe, wurde speziell für die Verwendung mit Flash-basiertem Speicher entwickelt. Es bietet skalierbare Sitzungen, eine deutliche Reduzierung der Latenz und eine Erhöhung der Parallelität, wodurch es sich besonders für mit niedriger Latenz und hohem Durchsatz verbundene Anwendungen wie In-Memory-Datenbanken und Analysen eignet.

Im Gegensatz zu FC und iSCSI verwendet NVMe keine LUNs. Stattdessen nutzt es Namensräume, die in einem ONTAP Volume gespeichert werden. Auf NVMe Namensräume kann nur über das NVMe Protokoll zugegriffen werden.



[[s3]]
== S3

Ab ONTAP 9.8 ist es möglich, einen ONTAP Simple Storage Service (S3) Server in einem ONTAP Cluster zu aktivieren, sodass Daten im Objektspeicher mithilfe von S3 Buckets bereitgestellt werden können.

ONTAP unterstützt zwei lokale Anwendungsfallszenarien für die Bereitstellung von S3-Objektspeicher:

* FabricPool Tier zu einem Bucket auf einem lokalen Cluster (Tier zu einem lokalen Bucket) oder einem Remote-Cluster (Cloud-Tier).
* Zugriff einer S3-Client-App auf einen Bucket im lokalen Cluster oder in einem Remote-Cluster.


[NOTE]
====
ONTAP S3 ist geeignet, wenn S3-Funktionen auf bestehenden Clustern ohne zusätzliche Hardware und Verwaltung gewünscht werden. Für Bereitstellungen mit mehr als 300 TB bleibt die NetApp StorageGRID Software weiterhin die NetApp Flaggschifflösung für Objektspeicher. Weitere Informationen https://docs.netapp.com/us-en/storagegrid-family/["StorageGRID"^].

====