---
permalink: concepts/cloud-backup-support-traditional-backups-concept.html 
sidebar: sidebar 
keywords: cloud backup, support, traditional backups 
summary: Neben SnapMirror und SnapVault Datensicherungsbeziehungen, die Disk-to-Disk nur für ONTAP 9.7 und frühere Versionen waren, gibt es nun mehrere Backup-Lösungen, die eine kostengünstigere Alternative für die langfristige Datenaufbewahrung bieten. 
---
= Cloud-Backup und Unterstützung für herkömmliche Backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Neben SnapMirror und SnapVault Datensicherungsbeziehungen, die Disk-to-Disk nur für ONTAP 9.7 und frühere Versionen waren, gibt es nun mehrere Backup-Lösungen, die eine kostengünstigere Alternative für die langfristige Datenaufbewahrung bieten.

Zahlreiche Datensicherungsapplikationen von Drittanbietern bieten herkömmliche Backups von von von von ONTAP gemanagten Daten. Veeam, Veritas und CommVault bieten u. a. integriertes Backup für ONTAP Systeme.

Ab ONTAP 9.8 bietet die SnapMirror Cloud asynchrone Replizierung von Snapshot Kopien von ONTAP Instanzen in Objekt-Storage-Endpunkte. Für SnapMirror Cloud Replication ist eine lizenzierte Applikation zur Orchestrierung und zum Management von Datensicherungs-Workflows erforderlich. SnapMirror Cloud-Beziehungen werden von ONTAP Systemen für die Auswahl von Objekt-Storage-Zielen in On-Premises- und Public-Cloud-Umgebungen unterstützt – einschließlich AWS S3, Google Cloud Storage-Plattform oder Microsoft Azure Blob Storage – wodurch sich die Effizienz mit Backup-Software der Anbieter erhöht. Kontaktieren Sie Ihren NetApp Ansprechpartner, um eine Liste der unterstützten zertifizierten Applikationen und Objekt-Storage-Anbieter zu erhalten.

Wenn Sie an einer Cloud-nativen Datensicherung interessiert sind, können Sie mit BlueXP SnapMirror oder SnapVault Beziehungen zwischen lokalen Volumes und Cloud Volumes ONTAP Instanzen in der Public Cloud konfigurieren.

BlueXP bietet zudem Backups von Cloud Volumes ONTAP-Instanzen mithilfe eines Software-as-a-Service-Modells (SaaS). Benutzer können mithilfe von BlueXP  Backup und Recovery ihre Cloud Volumes ONTAP Instanzen auf S3 und S3-konformen Public-Cloud-Objektspeicher sichern.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP-Dokumentation"^]

link:https://docs.netapp.com/us-en/bluexp-family/index.html["BlueXP-Dokumentation"^]

link:https://bluexp.netapp.com/["NetApp BlueXP"^]
