---
permalink: concepts/cluster-svm-administrators-concept.html 
sidebar: sidebar 
keywords: cluster, svm administration 
summary: Ein Clusteradministrator greift auf die Admin-SVM für das Cluster zu. Die Admin-SVM und ein Cluster-Administrator mit dem reservierten Namen-Administrator werden bei der Einrichtung des Clusters automatisch erstellt. 
---
= Administration von Clustern und SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein_Cluster-Administrator_ greift auf die Admin-SVM für das Cluster zu.  `admin`Beim Einrichten des Clusters werden automatisch die Admin-SVM und ein Cluster-Administrator mit dem reservierten Namen erstellt.

Ein Cluster-Administrator mit der Standardrolle `admin` kann den gesamten Cluster und seine Ressourcen verwalten. Der Cluster-Administrator kann bei Bedarf weitere Cluster-Administratoren mit unterschiedlichen Rollen erstellen.

Ein _SVM-Administrator_ greift auf eine Daten-SVM zu. Je nach Bedarf erstellt der Cluster-Administrator Daten-SVMs und SVM-Administratoren.

SVM-Administratoren wird die `vsadmin` Rolle standardmäßig zugewiesen. Der Cluster-Administrator kann je nach Bedarf SVM-Administratoren verschiedene Rollen zuweisen.

|===


 a| 
*_Role-Based Access Control (RBAC)_*

Die einem Administrator zugewiesene _Rolle_ bestimmt die Befehle, auf die der Administrator Zugriff hat. Sie weisen die Rolle beim Erstellen des Kontos für den Administrator zu. Sie können je nach Bedarf eine andere Rolle zuweisen oder benutzerdefinierte Rollen definieren.

|===