---
permalink: concepts/fabricpool-concept.html 
sidebar: sidebar 
keywords: storagegrid, storage grid, fabricpool, cloud tier, local tier, aggregate 
summary: Viele NetApp Kunden verfügen über große Mengen gespeicherter Daten, auf die selten zugegriffen wird. Das nennen wir kalte Daten. Kunden haben auch Daten, auf die häufig zugegriffen wird, die wir heiße Daten nennen. Idealerweise befindet sich die heiße Daten auf dem schnellsten Speicher, um die beste Performance zu erzielen. Kalte Daten können auf langsameren Speicher verschoben werden, solange sie bei Bedarf sofort verfügbar sind. Erfahren Sie, wie Sie erkennen, welche Teile Ihrer Daten heiß und welche kalt sind. 
---
= FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Viele NetApp Kunden verfügen über große Mengen gespeicherter Daten, auf die selten zugegriffen wird. Diese Daten werden als _kalte_ Daten bezeichnet. Kunden besitzen außerdem Daten, auf die häufig zugegriffen wird, die als _heiße_ Daten bezeichnet werden. Idealerweise befindet sich die heiße Daten auf dem schnellsten Speicher, um die beste Performance zu erzielen. Kalte Daten können auf langsameren Speicher verschoben werden, solange sie bei Bedarf sofort verfügbar sind. Doch wie lässt sich feststellen, welche Teile Ihrer Daten heiß und welche kalt sind?

FabricPool ist eine ONTAP Funktion, die Daten basierend auf Zugriffsmustern automatisch zwischen einer leistungsstarken lokalen Ebene und einer Cloud-Ebene verschiebt. Tiering gibt teuren lokalen Speicher für häufig genutzte Daten frei, während selten genutzte Daten aus kostengünstigem Objektspeicher in der Cloud jederzeit verfügbar bleiben. FabricPool überwacht kontinuierlich den Datenzugriff und verschiebt Daten zwischen den Ebenen, um beste Leistung und maximale Einsparungen zu erzielen.

Die Nutzung von FabricPool zum Tiering kalter Daten in die Cloud ist eine der einfachsten Möglichkeiten, Cloud-Effizienz zu erzielen und eine Hybrid Cloud Konfiguration zu erstellen. FabricPool arbeitet auf der Speicherblockebene und funktioniert daher sowohl mit Datei- als auch mit LUN-Daten.

Aber FabricPool dient nicht nur dazu, lokale Daten in die Cloud auszulagern. Viele Kunden nutzen FabricPool in Cloud Volumes ONTAP, um kalte Daten aus teureren Cloud-Speichern in kostengünstigeren Objektspeicher innerhalb des Cloud-Anbieters zu verschieben. Ab ONTAP 9.8 lassen sich Analysen zu FabricPool-fähigen Volumes mit link:../concept_nas_file_system_analytics_overview.html["Dateisystemanalyse"] oder link:../volumes/enable-temperature-sensitive-efficiency-concept.html["temperaturabhängige Speichereffizienz"] erfassen.

Die Anwendungen, die die Daten nutzen, sind sich nicht bewusst, dass Daten gestuft werden, daher sind keine Änderungen an Ihren Anwendungen erforderlich. Die Tiering-Funktion ist vollautomatisch, sodass keine laufende Administration erforderlich ist.

Sie können selten genutzte Daten im Objektspeicher eines der großen Cloud-Anbieter ablegen. Oder NetApp StorageGRID wählen, um Ihre selten genutzten Daten in Ihrer eigenen privaten Cloud zu speichern und so höchste Leistung und vollständige Kontrolle über Ihre Daten zu erhalten.

.Verwandte Informationen
link:../concept_cloud_overview.html["FabricPool System Manager-Dokumentation"]

https://www.youtube.com/playlist?list=PLdXI3bZJEw7mcD3RnEcdqZckqKkttoUpS["FabricPool Playlist auf NetApp TechComm TV"^]
