---
permalink: concepts/insights-system-optimization-concept.html 
sidebar: sidebar 
keywords: system manager, optimize, optimise, optimization, optimisation, insight, cluster, system, analysis, analyze, perform, performing, performance, capacity, local tier, storage tier, telnet, remote shell, rsh, autosupport, auto support, auto-support, insecure protocol, nonsecure, login banner, log in banner, ssh, secure shell, cbc cipher, ntp server, admin user, administrative, user, best practice, practise, fabricpool, fabric pool, physical capacity, aggregate, cloud, snapshot, directories, directory, file, remote access, transport protocol, https, http, autogrow, auto grow, auto-grow, shrink, reduce, reduction, dismiss, undismiss, explore, fix, remove, replace, analytic, security, compliance, secure, comply, volume, applications, reclaim, space, full, provisioning, provisioned cluster, serial, port, node, global fips 140-2 
summary: Ab ONTAP 9.11.1 zeigt System Manager Erkenntnisse an, die Ihnen bei der Optimierung der Performance und Sicherheit Ihres Systems helfen. 
---
= Einblicke in System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Ab ONTAP 9.11.1 zeigt System Manager _Insights_ an, die Sie bei der Optimierung der Performance und Sicherheit Ihres Systems unterstützen.


NOTE: Informationen zum Anzeigen, Anpassen und Reagieren auf Erkenntnisse finden Sie unter link:../insights-system-optimization-task.html["Einblicke zur Optimierung Ihres Systems"]



== Kapazitätseinblicke

System Manager kann als Reaktion auf die Kapazitätsbedingungen in Ihrem System die folgenden Einblicke anzeigen:

[cols="15,15,20,50"]
|===


| Insight | Schweregrad | Zustand | Korrekturen 


 a| 
Lokale Ebenen haben keinen Platz
 a| 
Risiken beheben
 a| 
Eine oder mehrere lokale Ebenen sind zu mehr als 95 % voll und wachsen schnell. Bestehende Workloads können sich möglicherweise nicht vergrößern oder in extremen Fällen kann es vorkommen, dass die Menge an Speicherplatz ausbleibt oder ausfällt.
 a| 
*Empfohlener Fix*: Führen Sie eine der folgenden Optionen aus.

* Löschen Sie die Warteschlange für die Volume-Wiederherstellung.
* Aktivieren Sie Thin Provisioning auf Thick Provisioning Volumes, um die Freigabe von Storage-Kapazität zu ermöglichen.
* Verschieben Sie Volumes auf eine andere lokale Ebene.
* Nicht benötigte Snapshot Kopien werden gelöscht.
* Löschen Sie nicht benötigte Verzeichnisse oder Dateien in den Volumes.
* Aktivieren Sie Fabric Pool für das Tiering der Daten in die Cloud.




 a| 
Applikationen fehlt Speicherplatz
 a| 
Erfordert Aufmerksamkeit
 a| 
Ein oder mehrere Volumes sind zu mehr als 95 % voll, haben aber keine Autogrow aktiviert.
 a| 
*Empfohlen*: Aktivieren Sie Autogrow bis zu 150% der aktuellen Kapazität.

*Andere Optionen*:

* Durch Löschen von Snapshot Kopien wird Speicherplatz zurückgewonnen.
* Größe der Volumes ändern.
* Verzeichnisse oder Dateien löschen.




 a| 
Die Kapazität des FlexGroup Volume ist nicht ausgeglichen
 a| 
Optimieren Sie den Storage
 a| 
Die Größe der zusammengehörigen Volumes eines oder mehrerer FlexGroup Volumes ist im Laufe der Zeit ungleichmäßig gewachsen, was zu einem Ungleichgewicht bei der Kapazitätsauslastung führte.  Wenn die einzelnen Volumes voll werden, können Fehler beim Schreiben auftreten.
 a| 
*Empfohlen*: Balancieren Sie die FlexGroup-Volumes aus.



 a| 
Die Kapazität der Storage-VMs geht zu knapp
 a| 
Optimieren Sie den Storage
 a| 
Eine oder mehrere Storage-VMs nähern sich der maximalen Kapazität.  Sie können nicht mehr Platz für neue oder bestehende Volumes bereitstellen, wenn die Storage-VMs die maximale Kapazität erreichen.
 a| 
*Empfohlen*: Wenn möglich, erhöhen Sie die maximale Kapazitätsgrenze der Speicher-VM.

|===


== Sicherheitseinblicke

System Manager kann die folgenden Einblicke als Reaktion auf Umstände anzeigen, die die Sicherheit Ihrer Daten oder Ihres Systems gefährden könnten.

[cols="15,15,20,50"]
|===


| Insight | Schweregrad | Zustand | Korrekturen 


 a| 
Lernmodus für Ransomware noch immer sehr einfach
 a| 
Erfordert Aufmerksamkeit
 a| 
Ein oder mehrere Volumes befinden sich seit 90 Tagen im Lernmodus zum Schutz vor Ransomware.
 a| 
*Empfohlen*: Aktivieren Sie den Anti-Ransomware-aktiven Modus für diese Volumes.



 a| 
Das automatische Löschen von Snapshot Kopien ist auf Volumes aktiviert
 a| 
Erfordert Aufmerksamkeit
 a| 
Das automatische Löschen von Snapshots ist auf einem oder mehreren Volumes aktiviert.
 a| 
*Empfohlen*: Deaktivieren Sie das automatische Löschen von Snapshot Kopien. Andernfalls ist im Fall eines Ransomware-Angriffs möglicherweise keine Datenwiederherstellung für diese Volumes möglich.



 a| 
Volumes verfügen nicht über Snapshot-Richtlinien
 a| 
Erfordert Aufmerksamkeit
 a| 
An ein oder mehrere Volumes ist keine angemessene Snapshot-Richtlinie gebunden.
 a| 
*Empfohlen*: Hängen Sie eine Snapshot-Richtlinie an Volumes an, die keine haben. Andernfalls ist im Fall eines Ransomware-Angriffs möglicherweise keine Datenwiederherstellung für diese Volumes möglich.



 a| 
Native FPolicy ist nicht konfiguriert
 a| 
Best Practices in sich
 a| 
Native FPolicy wird nicht auf einer oder mehreren NAS-Storage-VMs konfiguriert.
 a| 
*Empfohlen*: *WICHTIG*: Das Blockieren von Erweiterungen kann zu unerwarteten Ergebnissen führen. Ab 9.11.1 können Sie nativen FPolicy für Storage-VMs aktivieren. Dabei werden mehr als 3000 Dateierweiterungen blockiert, von denen bekannt ist, dass sie für Ransomware-Angriffe verwendet werden. link:../insights-configure-native-fpolicy-task.html["Konfigurieren Sie nativen FPolicy"] In NAS-Speicher-VMs, um die Dateierweiterungen zu steuern, die auf Volumes in Ihrer Umgebung geschrieben werden dürfen oder dürfen.



 a| 
Telnet ist aktiviert
 a| 
Best Practices in sich
 a| 
Secure Shell (SSH) sollte für einen sicheren Remote-Zugriff verwendet werden.
 a| 
*Empfohlen*: Telnet deaktivieren und SSH für sicheren Remote-Zugriff verwenden.



 a| 
Es sind zu wenige NTP-Server konfiguriert
 a| 
Best Practices in sich
 a| 
Die Anzahl der für NTP konfigurierten Server ist kleiner als 3.
 a| 
*Empfohlen*: Mindestens drei NTP-Server mit dem Cluster verknüpfen.  Andernfalls können Probleme bei der Synchronisierung der Cluster-Zeit auftreten.



 a| 
Remote Shell (RSH) ist aktiviert
 a| 
Best Practices in sich
 a| 
Secure Shell (SSH) sollte für einen sicheren Remote-Zugriff verwendet werden.
 a| 
*Empfohlen*: Deaktivieren Sie RSH und verwenden Sie SSH für sicheren Remote-Zugriff.



 a| 
Anmeldebanner ist nicht konfiguriert
 a| 
Best Practices in sich
 a| 
Anmeldemeldungen sind weder für das Cluster, für die Storage-VM noch für beides konfiguriert.
 a| 
*Empfohlen*: Richten Sie die Anmeldebanner für den Cluster und die Speicher-VM ein und aktivieren Sie deren Nutzung.



 a| 
AutoSupport verwendet ein nicht sicheres Protokoll
 a| 
Best Practices in sich
 a| 
AutoSupport ist nicht für die Kommunikation über HTTPS konfiguriert.
 a| 
*Empfohlen*: Es wird dringend empfohlen, HTTPS als Standard-Transportprotokoll zu verwenden, um AutoSupport-Nachrichten an den technischen Support zu senden.



 a| 
Der Standard-Admin-Benutzer ist nicht gesperrt
 a| 
Best Practices in sich
 a| 
Niemand hat sich mit einem Standard-Administratorkonto (admin oder diag) angemeldet, und diese Konten sind nicht gesperrt.
 a| 
*Empfohlen*: Sperren Sie standardmäßige Administratorkonten, wenn sie nicht verwendet werden.



 a| 
Secure Shell (SSH) verwendet unsichere Chiffren
 a| 
Best Practices in sich
 a| 
Die aktuelle Konfiguration verwendet nicht sichere CBC-Chiffren.
 a| 
*Empfohlen*: Sie sollten nur sichere Chiffren auf Ihrem Webserver zulassen, um die sichere Kommunikation mit Ihren Besuchern zu schützen. Entfernen Sie Chiffren mit Namen, die „cbc“ enthalten, z. B. „ais128-cbc“, „aes192-cbc“, „aes256-cbc“ und „3des-cbc“.



 a| 
Die globale FIPS 140-2-2-Compliance ist deaktiviert
 a| 
Best Practices in sich
 a| 
Die globale FIPS 140-2-2-Compliance ist auf dem Cluster deaktiviert.
 a| 
*Empfohlen*: Aus Sicherheitsgründen sollten Sie die globale FIPS 140-2-konforme Kryptographie aktivieren, um sicherzustellen, dass ONTAP sicher mit externen Clients oder Server-Clients kommunizieren kann.



 a| 
Volumes werden nicht auf Ransomware-Angriffe überwacht
 a| 
Erfordert Aufmerksamkeit
 a| 
Anti-Ransomware ist auf einem oder mehreren Volumes deaktiviert.
 a| 
*Empfohlen*: Aktivieren Sie Anti-Ransomware auf den Volumes. Andernfalls bemerken Sie möglicherweise nicht, wann Volumen bedroht werden oder angegriffen werden.



 a| 
Storage VMs sind nicht für den Schutz vor Ransomware konfiguriert
 a| 
Best Practices in sich
 a| 
Eine oder mehrere Storage-VMs sind nicht für den Schutz vor Ransomware konfiguriert.
 a| 
*Empfohlen*: Aktivieren Sie Anti-Ransomware auf den Storage-VMs. Andernfalls werden Sie möglicherweise nicht bemerken, wenn Storage-VMs bedroht sind oder angegriffen werden.

|===


== Konfigurationseinblicke

System Manager kann die folgenden Einblicke als Antwort auf Bedenken hinsichtlich der Konfiguration Ihres Systems anzeigen.

[cols="15,15,20,50"]
|===


| Insight | Schweregrad | Zustand | Korrekturen 


 a| 
Das Cluster ist nicht für Benachrichtigungen konfiguriert
 a| 
Best Practices in sich
 a| 
E-Mail, Webhooks oder ein SNMP traphost ist nicht so konfiguriert, dass Sie Benachrichtigungen über Probleme mit dem Cluster erhalten.
 a| 
*Empfohlen*: Konfigurieren Sie Benachrichtigungen für den Cluster.



 a| 
Das Cluster ist nicht für automatische Updates konfiguriert.
 a| 
Best Practices in sich
 a| 
Das Cluster wurde nicht so konfiguriert, dass es automatische Updates für die neuesten verfügbaren Dateien zur Festplattenqualifizierung, Festplatten-Firmware, Shelf-Firmware und SP/BMC-Firmware empfängt.
 a| 
*Empfohlen*: Aktivieren Sie diese Funktion.



 a| 
Cluster-Firmware ist nicht auf dem neuesten Stand
 a| 
Best Practices in sich
 a| 
Ihr System verfügt nicht über das neueste Firmware-Update, das Verbesserungen, Sicherheitspatches oder neue Funktionen zur Sicherung des Clusters für eine bessere Performance bieten könnte.
 a| 
*Empfohlen*: Aktualisieren Sie die ONTAP-Firmware.

|===