---
permalink: concepts/introducing-ontap-interfaces-concept.html 
sidebar: sidebar 
keywords: ontap interfaces, interfaces, system manager, bluexp, cli, rest api, ontapi 
summary: Die ONTAP Datenmanagement-Software bietet viele Schnittstellen zum Management von ONTAP geschützten Daten. 
---
= ONTAP-Benutzeroberflächen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die ONTAP Datenmanagement-Software verfügt über mehrere Schnittstellen, mit denen Sie die ONTAP Cluster managen können. Diese Schnittstellenoptionen bieten unterschiedliche Ebenen von Zugriff und Funktionalität und ermöglichen es Ihnen, Ihre ONTAP Cluster je nach Umgebungsebene flexibel zu managen.

Über jede dieser Schnittstellen können Sie Ihre ONTAP Cluster verwalten und Datenmanagement-Vorgänge durchführen



== ONTAP System Manager

Bei ONTAP System Manager handelt es sich um eine webbasierte Benutzeroberfläche, die das Cluster einfach und intuitiv gestaltet. Sie können allgemeine Vorgänge wie Storage-Konfiguration, Datensicherung sowie Einrichtung und Management des Netzwerks verwalten. System Manager bietet darüber hinaus Monitoring und Einblicke in Risiko- und Cluster-Performance, damit Sie auf Cluster-Probleme reagieren und Probleme frühzeitig erkennen können. link:../concept_administration_overview.html["Weitere Informationen ."].

Die Benutzeroberfläche von ONTAP System Manager wurde in ONTAP 9.7 neu gestaltet, um die Benutzerfreundlichkeit zu verbessern und intuitiver zu gestalten. Die Verfahren in dieser Dokumentation beschreiben die neu gestaltete System Manager Oberfläche, die mit jeder ONTAP Version noch mehr Optionen bietet.


NOTE: Die ältere System Manager Oberfläche wird in der ONTAP Dokumentation als System Manager Classic bezeichnet. Die letzte ONTAP Version, in der die klassische Benutzeroberfläche von System Manager verfügbar ist, ist ONTAP 9.7.



== BlueXP

Ab ONTAP 9.12.1 können Sie die webbasierte BlueXP Schnittstelle nutzen, um Ihre Hybrid-Multi-Cloud-Infrastruktur von einer zentralen Kontrollebene zu managen, während Sie weiterhin das vertraute Dashboard von System Manager nutzen. Mit BlueXP können Sie Cloud-Storage erstellen und verwalten (z. B. Cloud Volumes ONTAP), NetApp Datenservices nutzen (z. B. Cloud Backup) und zahlreiche lokale und Edge-Storage-Geräte kontrollieren. Wenn Sie lokale ONTAP Systeme zu BlueXP hinzufügen, können Sie Ihre gesamten Storage- und Datenressourcen über eine einzige Schnittstelle managen. https://docs.netapp.com/us-en/bluexp-family/["Weitere Informationen ."^].



== ONTAP Befehlszeilenschnittstelle

Der link:../system-admin/index.html["ONTAP Befehlszeilenschnittstelle (CLI)"] Ist eine textbasierte Schnittstelle, die Ihnen die Interaktion mit einem Cluster, Node, SVM und mehr ermöglicht link:../concepts/manual-pages.html["Befehle"]. CLI-Befehle sind auf Basis von verfügbar link:../system-admin/cluster-svm-administrators-concept.html["Rollentyp"]. Sie können über SSH oder eine Konsolenverbindung mit einem Node im Cluster auf die ONTAP-CLI zugreifen.



== ONTAP REST API

Ab ONTAP 9.6 haben Sie Zugriff auf eine RESTful API, mit der Sie Cluster-Vorgänge programmgesteuert managen und automatisieren können. Verwenden der API zur Durchführung verschiedener administrativer ONTAP-Aufgaben, wie das Erstellen und Managen von Volumes, Snapshots und Aggregaten sowie das Monitoring der Cluster-Performance. Sie können über ein Utility wie Curl oder eine beliebige Programmiersprache, die einen REST-Client unterstützt, wie Python, PowerShell und Java, direkt auf die ONTAP REST-API zugreifen. https://docs.netapp.com/us-en/ontap-automation/get-started/ontap_automation_options.html["Weitere Informationen ."^].


NOTE: ONTAPI ist eine proprietäre ONTAP API vor der ONTAP REST API. Die ONTAPI Schnittstelle wird in zukünftigen Versionen von ONTAP deaktiviert. Wenn Sie ONTAPI verwenden, sollten Sie Ihre planen https://docs.netapp.com/us-en/ontap-automation/migrate/ontapi_disablement.html["Migration zur ONTAP-REST-API"^].



== NetApp Toolkits und Frameworks

NetApp bietet Client-Toolkits für spezifische Entwicklungssprachen und -Umgebungen, die die ONTAP-REST-API abstrahieren und die Erstellung von Automatisierungscode vereinfachen.
https://docs.netapp.com/us-en/ontap-automation/get-started/ontap_automation_options.html#client-software-toolkits["Weitere Informationen ."^].

Zusätzlich zu diesen Toolkits können Sie Automatisierungscode mithilfe von Frameworks erstellen und bereitstellen. https://docs.netapp.com/us-en/ontap-automation/get-started/ontap_automation_options.html#automation-frameworks["Weitere Informationen ."^].
