---
permalink: concepts/storage-efficiency-overview.html 
sidebar: sidebar 
keywords: storage efficiency, storage efficiencies, storage efficiency technologies, space utliziation, space savings, optimizing, space optimization, minimizing, wasted space, reducing, footprint, thin provisioning, deduplication, zero block, zero-block, inline, deduplication, backgroud deduplication, postprocessing, post-processing, compression, compaction, flex-clone technologies 
summary: 'Storage-Effizienz beschreibt, wie effizient ein Storage-System verfügbaren Speicherplatz nutzt: Es optimiert die Storage-Ressourcen, minimiert die Verschwendung und reduziert den physischen Platzbedarf geschriebener Daten.' 
---
= Überblick über die ONTAP Storage-Effizienz
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage-Effizienz beschreibt, wie effizient ein Storage-System verfügbaren Speicherplatz nutzt: Es optimiert die Storage-Ressourcen, minimiert die Verschwendung und reduziert den physischen Platzbedarf geschriebener Daten. Dank der höheren Storage-Effizienz können Sie die maximale Datenmenge auf kleinstmöglichem Raum zu den geringstmöglichen Kosten speichern. Durch den Einsatz von Storage-Effizienztechnologien, die doppelte Datenblöcke und mit Nullen gefüllte Datenblöcke erkennen und beseitigen, wird beispielsweise der physische Storage-Bedarf insgesamt verringert und die Gesamtkosten gesenkt.

ONTAP bietet eine Vielzahl von Storage-Effizienztechnologien, mit denen sich die Menge an physischer Hardware oder Cloud Storage verringert, die von Ihren Daten belegt wird. Darüber hinaus führt dies zu deutlichen Verbesserungen der System-Performance, z. B. schnelleren Lesevorgängen von Daten, schnelleren Datenkopien und schnellerer VM-Bereitstellung.

.ONTAP Storage-Effizienz-Technologien bieten folgende Vorteile:
* *Thin Provisioning*
+
xref:thin-provisioning-concept.html[Thin Provisioning] Ermöglicht Ihnen die Zuweisung von Storage in einem Volume oder LUN nach Bedarf, anstatt es vorab zu reservieren.  So wird die Menge an physischem Storage verringert, da Sie in der Lage sind, Ihre Volumes oder LUNs aufgrund potenzieller Auslastung zu viel zuzuweisen, ohne Speicherplatz zu reservieren, der derzeit nicht verwendet wird.

* *Deduplizierung*
+
xref:deduplication-concept.html[Deduplizierung] Reduziert den Bedarf an physischem Storage für ein Volume auf dreierlei Weise.

+
** *Zero Block Deduplication*
+
Die Zero-Block-Deduplizierung erkennt und eliminiert Datenblöcke, die mit allen Nullen gefüllt sind, und aktualisiert nur Metadaten. Dann werden 100 % des in der Regel von 0-Blöcken genutzten Speicherplatzes eingespart.  Die Zero-Block-Deduplizierung ist auf allen deduplizierten Volumes standardmäßig aktiviert.

** *Inline-Deduplizierung*
+
Die Inline-Deduplizierung erkennt doppelte Datenblöcke und ersetzt sie durch Verweise auf einen eindeutigen, gemeinsam genutzten Block, bevor Daten auf die Festplatte geschrieben werden. Die Inline-Deduplizierung beschleunigt die VM-Bereitstellung um 20 % bis 30 %.  Abhängig von Ihrer Version von ONTAP und der Plattform ist die Inline-Deduplizierung auf Volume- oder Aggregatebene verfügbar.  Bei AFF- und ASA-Systemen ist sie standardmäßig aktiviert. Sie müssen die Inline-Deduplizierung auf FAS Systemen manuell aktivieren.

** *Deduplizierung im Hintergrund*
+
Hintergrund-Deduplizierung erkennt ebenfalls doppelte Datenblöcke und ersetzt sie durch Verweise auf einen eindeutigen, gemeinsam genutzten Block, erhöht jedoch die Storage-Effizienz noch weiter, nachdem die Daten auf die Festplatte geschrieben wurden.  Sie können eine Hintergrunddeduplizierung so einrichten, dass sie ausgeführt wird, wenn bestimmte Kriterien für Ihr Storage-System erfüllt sind. Beispielsweise können Sie die Hintergrund-Deduplizierung aktivieren, wenn Ihr Volume eine Auslastung von 10 % erreicht.  Sie können auch die Hintergrund-Deduplizierung manuell auslösen oder sie für einen spezifischen Zeitplan festlegen. Bei AFF- und ASA-Systemen ist sie standardmäßig aktiviert. Sie müssen die Hintergrund-Deduplizierung auf FAS Systemen manuell aktivieren.



+
Die Deduplizierung wird innerhalb von Volumes und über Volumes innerhalb eines Aggregats hinweg unterstützt.  Lesezugriffe auf deduplizierte Daten verursachen in der Regel keine Performance-Kosten.

* *Komprimierung*
+
xref:compression-concept.html[Komprimierung] Reduziert den erforderlichen physischen Storage für ein Volume, indem Datenblöcke in Komprimierungsgruppen zusammengefasst werden, von denen jeder als einzelner Block gespeichert wird. Wenn eine Lese- oder Überschreibanforderung eingeht, wird nur eine kleine Gruppe von Blöcken gelesen, nicht die gesamte Datei. Dieser Prozess optimiert die Lese- und Überschreibleistung und ermöglicht eine größere Skalierbarkeit der Größe der komprimierten Dateien.

+
Die Komprimierung kann inline oder nachgelagerte erfolgen.  Die Inline-Komprimierung bietet unmittelbare Platzeinsparungen, indem Daten im Speicher komprimiert werden, bevor sie auf die Festplatte geschrieben werden. Bei der nachgelagerten Komprimierung werden die Blöcke zunächst unkomprimiert auf die Festplatte geschrieben, später werden die Daten zu einem geplanten Zeitpunkt komprimiert. Sie müssen die Komprimierung manuell aktivieren.

* *Verdichtung*
+
Data-Compaction reduziert den Bedarf an physischem Storage für ein Volume, indem Datenblöcke, die in 4-KB-Blöcken gespeichert sind, jedoch eine Größe von weniger als 4 KB aufweisen, in einem einzelnen Block zusammengefasst werden. Die Data-Compaction findet statt, während sich Daten noch im Speicher befinden, sodass auf den Festplatten nie unnötiger Speicherplatz verbraucht wird.  Bei AFF- und ASA-Systemen ist sie standardmäßig aktiviert. Sie müssen die Data-Compaction auf FAS Systemen manuell aktivieren.

* *FlexClone Volumen, Dateien und LUNs*
+
xref:flexclone-volumes-files-luns-concept.html[FlexClone Technologie] Mit Snapshot Metadaten lassen sich beschreibbare, zeitpunktgenaue Kopien von Volumes, Dateien oder LUNs erstellen. Kopien nutzen Datenblöcke gemeinsam mit den Eltern. Somit wird kein Storage belegt, außer was für Metadaten erforderlich ist, bis Änderungen in eine Kopie oder deren übergeordnete Kopie geschrieben werden.  Wird eine Änderung geschrieben, wird nur das Delta gespeichert.

+
Wo herkömmliche Datensatzkopien in Minuten oder gar Stunden erstellt werden können, ermöglicht die FlexClone Technologie nahezu sofortiges Kopieren selbst der größten Datensätze.



Sie können die Vorteile dieser Technologien im täglichen Betrieb mit minimalem Aufwand nutzen.  Angenommen, Sie müssen 5,000 Benutzern Speicherplatz für Home Directories bereitstellen, und Sie schätzen, dass der maximale Speicherplatz für jeden Benutzer 1 GB beträgt. Sie könnten ein Aggregat von 5 TB im Voraus reservieren, um den potenziellen Gesamtspeicherbedarf zu decken.  Sie wissen aber auch, dass der Kapazitätsbedarf für Home Directorys zwischen Ihrem Unternehmen stark variiert.  Anstatt 5 TB Gesamtspeicherplatz für Ihr Unternehmen zu reservieren, können Sie ein Aggregat von 2 TB erstellen.  Dann können Sie Thin Provisioning verwenden, um jedem Benutzer 1 GB Storage zuzuweisen, aber den Storage nur wie benötigt zuzuweisen.  Sie können das Aggregat im Laufe der Zeit aktiv überwachen und die tatsächliche physische Größe bei Bedarf erhöhen.

Nehmen Sie in einem anderen Beispiel an, Sie verwenden eine Virtual Desktop Infrastructure (VDI) mit einer großen Menge an doppelten Daten auf Ihren virtuellen Desktops. Deduplizierung reduziert Ihre Storage-Nutzung, indem doppelte Datenblöcke im gesamten VDI automatisch eliminiert und diese durch einen Zeiger auf den ursprünglichen Block ersetzt werden. Andere ONTAP Storage-Effizienztechnologien wie Komprimierung lassen sich auch im Hintergrund ausführen, ohne dass Sie eingreifen müssen.

Die ONTAP Technologie zur Festplattenpartitionierung sorgt für Steigerung der Storage-Effizienz.  Die RAID DP-Technologie schützt ohne Performance-Beeinträchtigung oder Overhead durch Festplattenspiegelung vor doppeltem Festplattenausfall. Die erweiterte SSD-Partitionierung mit ONTAP 9 erhöht die nutzbare Kapazität um fast 20 %.

NetApp bietet dieselben Storage-Effizienzfunktionen wie On-Premises-ONTAP in der Cloud. Wenn Sie Daten von lokalen ONTAP-Systemen in die Cloud migrieren, bleibt die vorhandene Storage-Effizienz erhalten. Angenommen, Sie haben eine SQL-Datenbank mit geschäftskritischen Daten, die Sie von einem On-Premises-System in die Cloud verschieben möchten.  Mit der Datenreplizierung in BlueXP können Sie Ihre Daten migrieren und im Rahmen des Migrationsprozesses Ihre aktuellen lokalen Richtlinien für Snapshot Kopien in der Cloud aktivieren.

* *Temperaturempfindliche Lagereffizienz*
+
ONTAP bietet link:https://docs.netapp.com/us-en/ontap/volumes/enable-temperature-sensitive-efficiency-concept.html["Temperaturempfindliche Lagereffizienz"] Bietet Vorteile, indem bewertet wird, wie oft auf die Daten auf das Volume zugegriffen wird, und diese Frequenz dem Grad der Komprimierung zugeordnet wird, der auf diese Daten angewendet wird. Bei selten abgerufenen „kalten“ Daten werden größere Datenblöcke komprimiert. Bei häufig abgerufenen Daten, die häufiger überschrieben werden, werden kleinere Datenblöcke komprimiert, was den Prozess effizienter macht.



Temperaturempfindliche Storage-Effizienz (TSSE) wird seit ONTAP 9.8 eingeführt und wird automatisch auf neu erstellten AFF Volumes mit Thin Provisioning aktiviert.
