---
permalink: concepts/storage-efficiency-overview.html 
sidebar: sidebar 
keywords: storage efficiency, storage efficiencies, storage efficiency technologies, space utilization, space savings, optimizing, space optimization, minimizing, wasted space, reducing, footprint, thin provisioning, deduplication, zero block, zero-block, inline, deduplication, background deduplication, postprocessing, post-processing, compression, compaction, flex-clone technologies 
summary: Speichereffizienz ist das Maß dafür, wie effektiv ein Speichersystem den verfügbaren Speicherplatz nutzt, indem Speicherressourcen optimiert, verschwendeter Speicherplatz minimiert und der physische Platzbedarf der geschriebenen Daten reduziert wird. 
---
= ONTAP Speichereffizienz im Überblick
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Speichereffizienz ist das Maß dafür, wie effektiv ein Speichersystem den verfügbaren Speicherplatz nutzt, indem Speicherressourcen optimiert, verschwendeter Speicherplatz minimiert und der physische Platzbedarf der geschriebenen Daten reduziert wird. Eine höhere Speichereffizienz ermöglicht es, die maximale Datenmenge auf kleinstem Raum zu den geringstmöglichen Kosten zu speichern. Beispielsweise verringert die Nutzung speichereffizienter Technologien, die doppelte Datenblöcke und mit Nullen gefüllte Datenblöcke erkennen und eliminieren, die insgesamt benötigte physische Speichermenge und reduziert die Gesamtkosten.

ONTAP bietet eine breite Palette von Speichereffizienztechnologien, die den Bedarf an physischer Hardware oder Cloud-Speicher für Ihre Daten reduzieren und gleichzeitig deutliche Verbesserungen der Systemleistung ermöglichen, darunter schnellere Lesevorgänge von Daten, schnellere Kopien von Datensätzen und eine schnellere VM-Bereitstellung.

.Zu den ONTAP Speichereffizienztechnologien zählen:
* *Thin Provisioning*
+
xref:thin-provisioning-concept.html[Thin Provisioning] ermöglicht die bedarfsgerechte Zuweisung von Speicherplatz in einem Volume oder einer LUN, anstatt diesen im Voraus zu reservieren. Dadurch wird die Menge an physischem Speicher reduziert, da Volumes oder LUNs auf Basis des potenziellen Bedarfs überbelegt werden können, ohne aktuell ungenutzten Speicherplatz zu reservieren.

* *Deduplizierung*
+
xref:deduplication-concept.html[Deduplizierung] reduziert den für ein Volumen benötigten physischen Speicherplatz auf drei verschiedene Arten.

+
** *Zero-Block-Deduplizierung*
+
Die Zero-Block-Deduplizierung erkennt und entfernt Datenblöcke, die ausschließlich mit Nullen gefüllt sind, und aktualisiert nur die Metadaten. 100 % des Speicherplatzes, der normalerweise von Zero-Blöcken belegt wird, wird dadurch eingespart. Die Zero-Block-Deduplizierung ist standardmäßig auf allen deduplizierten Volumes aktiviert.

** *Inline Deduplizierung*
+
Die Inline-Deduplizierung erkennt doppelte Datenblöcke und ersetzt sie durch Verweise auf einen eindeutigen, gemeinsam genutzten Block, bevor die Daten auf die Festplatte geschrieben werden. Die Inline-Deduplizierung beschleunigt die VM-Bereitstellung um 20 % bis 30 %. Abhängig von Ihrer ONTAP Version und Ihrer Plattform ist die Inline-Deduplizierung auf Volume- oder Aggregatebene verfügbar. Sie ist auf AFF und ASA Systemen standardmäßig aktiviert. Auf FAS Systemen muss die Inline-Deduplizierung manuell aktiviert werden.

** *Hintergrund-Deduplizierung*
+
Die Hintergrunddeduplizierung erkennt ebenfalls doppelte Datenblöcke und ersetzt sie durch Verweise auf einen eindeutigen, gemeinsam genutzten Block, verbessert jedoch die Speichereffizienz zusätzlich, indem dies nach dem Schreiben der Daten auf die Festplatte erfolgt. Die Hintergrunddeduplizierung kann so eingerichtet werden, dass sie ausgeführt wird, wenn bestimmte Kriterien auf Ihrem Speichersystem erfüllt sind. Beispielsweise kann die Hintergrunddeduplizierung aktiviert werden, wenn Ihr Volume eine Auslastung von 10 % erreicht. Die Hintergrunddeduplizierung kann auch manuell ausgelöst oder so eingestellt werden, dass sie nach einem bestimmten Zeitplan ausgeführt wird. Sie ist auf AFF und ASA Systemen standardmäßig aktiviert. Auf FAS Systemen muss die Hintergrunddeduplizierung manuell aktiviert werden.



+
Die Deduplizierung wird innerhalb von Volumes und zwischen Volumes innerhalb eines Aggregats unterstützt. Lesevorgänge deduplizierter Daten verursachen in der Regel keine Leistungseinbußen.

* *Kompression*
+
xref:compression-concept.html[Komprimierung]Der benötigte physische Speicherplatz für ein Volume wird reduziert, indem Datenblöcke in Komprimierungsgruppen zusammengefasst werden, von denen jede als einzelner Block gespeichert wird. Bei einer Lese- oder Überschreibanforderung wird nur eine kleine Gruppe von Blöcken gelesen, nicht die gesamte Datei. Dieser Prozess optimiert die Lese- und Überschreibleistung und ermöglicht eine größere Skalierbarkeit bei der Größe der komprimierten Dateien.

+
Die Komprimierung kann inline oder nachträglich erfolgen. Inline-Komprimierung spart sofort Speicherplatz, indem Daten im Arbeitsspeicher komprimiert werden, bevor sie auf die Festplatte geschrieben werden. Bei der nachträglichen Komprimierung werden die Blöcke zunächst unkomprimiert auf die Festplatte geschrieben und dann zu einem festgelegten Zeitpunkt komprimiert. Sie ist auf AFA-Systemen standardmäßig aktiviert. Auf allen anderen Systemen muss die Komprimierung manuell aktiviert werden.

* *Verdichtung*
+
Die Komprimierung reduziert den benötigten physischen Speicherplatz eines Volumes, indem Datenblöcke, die in 4-KB-Blöcken gespeichert sind, aber kleiner als 4 KB sind, zu einem einzigen Block zusammengefasst werden. Die Komprimierung erfolgt im Arbeitsspeicher, sodass kein unnötiger Speicherplatz auf den Festplatten belegt wird. Sie ist auf AFF und ASA Systemen standardmäßig aktiviert. Auf FAS Systemen muss die Komprimierung manuell aktiviert werden.

* *FlexClone Volumes, Dateien und LUNs*
+
xref:flexclone-volumes-files-luns-concept.html[FlexClone Technologie] nutzt Snapshot-Metadaten, um beschreibbare, zeitpunktgenaue Kopien eines Volumes, einer Datei oder einer LUN zu erstellen. Kopien teilen sich Datenblöcke mit ihren übergeordneten Objekten und belegen keinen Speicherplatz außer dem für Metadaten erforderlichen, bis Änderungen an einer Kopie oder ihrem übergeordneten Objekt geschrieben werden. Wenn eine Änderung geschrieben wird, wird nur das Delta gespeichert.

+
Während das Erstellen herkömmlicher Datensatzkopien Minuten oder sogar Stunden dauern kann, ermöglicht die FlexClone Technologie das nahezu sofortige Kopieren selbst größter Datensätze.

* *Temperaturabhängige Speichereffizienz*
+
ONTAP bietet link:../volumes/enable-temperature-sensitive-efficiency-concept.html["temperaturabhängige Speichereffizienz"] Vorteile, indem bewertet wird, wie häufig auf die Daten Ihres Volumes zugegriffen wird, und diese Häufigkeit mit dem Grad der auf diese Daten angewendeten Komprimierung abgeglichen wird. Für selten abgerufene Daten werden größere Datenblöcke komprimiert. Für häufig abgerufene und häufiger überschriebene Daten werden kleinere Datenblöcke komprimiert, wodurch der Prozess effizienter wird.

+
Die in ONTAP 9.8 eingeführte temperaturabhängige Speichereffizienz (TSSE) wird automatisch für neu erstellte, dünn bereitgestellte AFF Volumes aktiviert. Sie ist nicht aktiviert für link:builtin-storage-efficiency-concept.html["AFF A70, AFF A90 und AFF A1K Plattformen"]Volumes, die in ONTAP 9.15.1 eingeführt wurden und einen Hardware-Offload-Prozessor verwenden.




NOTE: TSSE wird nur auf Thick Provisioned Volumes nicht unterstützt.

* *Speichereffizienz durch CPU oder dedizierten Offload-Prozessor*
+
Ab ONTAP 9.15.1 ist link:builtin-storage-efficiency-concept.html["Speichereffizienz der CPU oder eines dedizierten Offload-Prozessors"] auf bestimmten AFF und FAS Plattformen automatisch aktiviert und erfordert keine Konfiguration. Diese Plattformen nutzen keine temperaturabhängige Speichereffizienz. Die Komprimierung beginnt, ohne dass auf das Abkühlen der Daten gewartet wird, und erfolgt entweder durch die Haupt-CPU oder einen dedizierten Offload-Prozessor. Diese Plattformen verwenden außerdem die sequenzielle Packung angrenzender physischer Blöcke, um die Speichereffizienz für komprimierte Daten weiter zu verbessern.



Die Vorteile dieser Technologien lassen sich mit minimalem Aufwand in den täglichen Betrieb integrieren. Beispielsweise kann angenommen werden, dass 5.000 Benutzer Speicherplatz für Home-Verzeichnisse benötigen und der maximale Speicherbedarf pro Benutzer auf 1 GB geschätzt wird. Ein 5-TB-Datenaggregat könnte im Voraus reserviert werden, um den potenziellen Gesamtbedarf an Speicherplatz zu decken. Es ist jedoch auch bekannt, dass die Kapazitätsanforderungen für Home-Verzeichnisse innerhalb der Organisation stark variieren. Anstatt 5 TB Gesamtspeicherplatz für die Organisation zu reservieren, kann ein 2-TB-Datenaggregat erstellt werden. Mit Thin Provisioning lässt sich dann jedem Benutzer nominell 1 GB Speicherplatz zuweisen, wobei der Speicher tatsächlich nur bei Bedarf bereitgestellt wird. Das Datenaggregat kann im Zeitverlauf aktiv überwacht und die tatsächliche physische Größe bei Bedarf erhöht werden.

In einem weiteren Beispiel wird eine Virtual Desktop Infrastructure (VDI) mit einer großen Menge an doppelten Daten unter den virtuellen Desktops angenommen. Die Deduplizierung reduziert den Speicherbedarf, indem doppelte Datenblöcke in der VDI automatisch entfernt und durch einen Verweis auf den Originalblock ersetzt werden. Weitere ONTAP Speicher-Effizienztechnologien, wie etwa die Komprimierung, können ebenfalls im Hintergrund ohne Ihr Zutun ausgeführt werden.

ONTAP Festplattenpartitionierungstechnologie sorgt zudem für eine höhere Speichereffizienz. RAID DP Technologie schützt vor doppeltem Festplattenausfall, ohne die Leistung zu beeinträchtigen oder zusätzlichen Aufwand durch Festplattenspiegelung zu verursachen. Fortschrittliche SSD-Partitionierung mit ONTAP 9 erhöht die nutzbare Kapazität um fast 20 %.

NetApp bietet dieselben Speichereffizienzfunktionen wie bei On-Premises ONTAP in der Cloud. Bei der Migration von Daten von On-Premises ONTAP in die Cloud bleibt die bestehende Speichereffizienz erhalten. Beispielsweise kann eine SQL-Datenbank mit geschäftskritischen Daten von einem On-Premises-System in die Cloud verschoben werden. Datenreplizierung in der NetApp Console kann für die Migration der Daten genutzt werden, und im Rahmen des Migrationsprozesses lässt sich die aktuelle On-Premises-Richtlinie für Snapshots in der Cloud aktivieren.
