---
sidebar: sidebar 
permalink: concepts/sysmgr-integration-bluexp-concept.html 
keywords: netapp, ontap, system manager, experience, integrate, integration, bluexp, hybrid, cloud, dashboard, multicloud 
summary: Sie können ONTAP 9.10.1 und spätere Versionen mit dem System Manager in BlueXP verwalten. Diese Integration ermöglicht Ihnen die effiziente Überwachung Ihrer hybriden Multicloud-Infrastruktur mithilfe einer einheitlichen Steuerungsebene und behält dabei die vertraute Benutzeroberfläche des System Managers bei. 
---
= Integrieren Sie ONTAP System Manager mit BlueXP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können ONTAP 9.10.1 und spätere Versionen mit dem System Manager in BlueXP verwalten. Diese Integration ermöglicht Ihnen die effiziente Überwachung Ihrer hybriden Multicloud-Infrastruktur mithilfe einer einheitlichen Steuerungsebene und behält dabei die vertraute Benutzeroberfläche des System Managers bei.

Mit BlueXP können Sie Cloud-Speicher erstellen und verwalten (z. B. Cloud Volumes ONTAP), NetApp-Datendienste verwenden (z. B. Cloud Backup) und viele lokale und Edge-Speichergeräte steuern.

BlueXP bietet zwei Möglichkeiten, Cluster zu erkennen und zu verwalten:

* Direkte Erkennung für die Verwaltung über System Manager (ONTAP 9.12.1 und höher)
* Erkennung über einen Konnektor


Der Connector ist eine in Ihrer Umgebung installierte Software. Sie ermöglicht Ihnen den Zugriff auf Verwaltungsfunktionen über den System Manager und auf BlueXP-Cloud-Dienste mit Funktionen wie Datenreplikation, Backup und Wiederherstellung, Datenklassifizierung, Daten-Tiering und mehr.

Erfahren Sie mehr über link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html["ONTAP-Cluster-Management vor Ort mit BlueXP"^].

.Schritte
. Melden Sie sich bei BlueXP an.
+
.. Wenn Sie über einen BlueXP-Login verfügen, verwenden Sie diesen.
.. Wenn Sie dies zum ersten Mal tun, wählen Sie „Mit Ihren Anmeldeinformationen für die NetApp-Support-Site anmelden“ und geben Sie Ihre Anmeldeinformationen auf der BlueXP-Anmeldeseite ein.


. Entdecken Sie Ihren lokalen Cluster in BlueXP mithilfe eines Connectors oder direkter Erkennung. Weitere Informationen finden Sie unter: https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html[Erkennung lokaler ONTAP-Cluster^].
+
.. Erfahren Sie, wie man link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-direct.html["Verwalten von Clustern, die direkt erkannt wurden"^].
.. Erfahren Sie, wie man link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-connector.html["Verwalten von Clustern, die mit einem Connector erkannt wurden"^].


. Verwalten Sie Ihren lokalen Cluster mit System Manager. Wählen Sie auf der Arbeitsumgebungsseite den Cluster aus und klicken Sie in der Liste „Dienste“ auf „System Manager“.
+
.. Erfahren Sie mehr über link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-direct.html["Verwalten von Clustern, die direkt erkannt wurden"^].
.. Erfahren Sie, wie man link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-connector.html["Verwalten von Clustern, die mit einem Connector erkannt wurden"^].






== BlueXP und ONTAP 9.12.1

Hinweis: Wenn Sie ONTAP 9.12.1 verwenden, wird eine Meldung angezeigt, die Sie auffordert, BlueXP auszuprobieren.

+ Wenn der Cluster über eine Verbindung zu BlueXP verfügt, wird eine Anmeldeaufforderung angezeigt.

. Klicken Sie auf *Weiter zu BlueXP*, um dem Link zu BlueXP zu folgen.
+

NOTE: Wenn Ihre Systemeinstellungen externe Netzwerke blockiert haben, können Sie nicht auf BlueXP zugreifen. Um mit BlueXP auf System Manager zuzugreifen, müssen Sie sicherstellen, dass Ihr System auf die Adresse „`cloudmanager.cloud.netapp.com`"“ zugreifen kann. Andernfalls können Sie an der Eingabeaufforderung die Version von System Manager verwenden, die mit dem ONTAP System installiert ist.

. Wählen Sie auf der BlueXP Login-Seite die Option *mit den Anmeldedaten der NetApp Support Site* anmelden* und geben Sie Ihre Zugangsdaten ein.
+
Wenn Sie BlueXP bereits verwendet haben und über einen Login mit E-Mail und Passwort verfügen, müssen Sie stattdessen weiterhin diese Login-Option verwenden.

+
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html["Erfahren Sie mehr über die Anmeldung bei BlueXP"^].

. Geben Sie bei entsprechender Aufforderung einen Namen für Ihr neues BlueXP-Konto ein.
+
In den meisten Fällen erstellt BlueXP automatisch ein Konto für Sie basierend auf Daten aus Ihrem Cluster.

. Geben Sie die Cluster-Administrator-Anmeldedaten für das Cluster ein.


.Ergebnis
System Manager wird angezeigt, und Sie können den Cluster jetzt über BlueXP verwalten.



== Erfahren Sie mehr über BlueXP

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["BlueXP im Überblick"^]
* https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/index.html["Management Ihrer NetApp AFF und FAS Systeme über BlueXP"^]

