---
permalink: nfs-rdma/configure-nics-task.html 
sidebar: sidebar 
keywords: networking, NICs, NFS over RDMA, NVIDIA, NFS, system manager, ports, ethernet ports 
summary: In diesem Artikel werden sowohl die Konfigurationsprozesse für das Client-System als auch die Storage-Plattform sowie die Anforderungen für NICs zur Verwendung von NFS über RDMA in ONTAP erläutert. 
---
= Konfigurieren Sie NICs für NFS über RDMA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS über RDMA erfordert die NIC-Konfiguration sowohl für das Client-System als auch für die Storage-Plattform.



== Konfiguration der Storage-Plattform

Auf dem Server muss ein X1148 RDMA-Adapter installiert sein. Wenn Sie eine HA-Konfiguration verwenden, müssen Sie über einen entsprechenden X1148-Adapter auf dem Failover-Partner verfügen, damit RDMA-Service auch während des Failover fortgesetzt werden kann. Der NIC muss ROCE-fähig sein.

Ab ONTAP 9.10.1 können Sie sich mit dem Befehl eine Liste der RDMA-Offload-Protokolle anzeigen lassen:
`network port show -rdma-protocols roce`



== Client-System-Konfiguration

Clients müssen Mellanox RDMA-fähige NIC-Karten verwenden (z. B. X1148) und Mellanox OFED-Netzwerksoftware. Die Mellanox-Dokumentation enthält weitere Informationen zu unterstützten Modellen und Versionen. Obwohl Client und Server direkt verbunden werden können, wird die Verwendung von Switches aufgrund einer verbesserten Failover-Performance mit einem Switch empfohlen.

Der Client, der Server und alle Switches sowie alle Ports auf den Switches müssen mithilfe von Jumbo Frames konfiguriert werden. Achten Sie außerdem darauf, dass die Prioritätssteuerung bei allen Switches wirksam ist.

Sobald diese Konfiguration bestätigt ist, können Sie NFS mounten.

[role="tabbed-block"]
====
.System Manager
--
Sie müssen ONTAP 9.12.1 oder höher verwenden, um Netzwerkschnittstellen mit NFS über RDMA mit System Manager zu konfigurieren.

.Schritte
. Prüfung, ob RDMA unterstützt wird. Navigieren Sie zu *Netzwerk > Ethernet-Ports* und wählen Sie den entsprechenden Knoten in der Gruppenansicht aus. Wenn Sie den Knoten erweitern, sehen Sie sich das Feld *RDMA-Protokolle* für einen bestimmten Port an: Der Wert *RoCE* bezeichnet RDMA wird unterstützt; ein Dash (*-*) zeigt an, dass er nicht unterstützt wird.
. Um ein VLAN hinzuzufügen, wählen Sie *+ VLAN* aus. Wählen Sie den entsprechenden Knoten aus. Im Dropdown-Menü *Port* werden in den verfügbaren Ports der Text *RoCE aktiviert* angezeigt, wenn sie RDMA unterstützen; kein Text wird angezeigt, wenn sie RDMA nicht unterstützen.
. Folgen Sie dem Workflow in xref:../task_nas_enable_linux_nfs.html[Aktivieren Sie NAS-Storage für Linux-Server mithilfe von NFS] So konfigurieren Sie einen neuen NFS-Server:
+
Beim Hinzufügen von Netzwerkschnittstellen haben Sie die Möglichkeit, *RoCE-Ports verwenden* auszuwählen. Wählen Sie diese Option für alle Netzwerkschnittstellen aus, für die NFS über RDMA verwendet werden soll.



--
.CLI
--
. Überprüfen Sie, ob der RDMA-Zugriff auf dem NFS-Server mit dem Befehl aktiviert ist:
+
`vserver nfs show-vserver _SVM_name_`

+
Standardmäßig ist `-rdma` Sollte aktiviert sein. Wenn das nicht der Fall ist, aktivieren Sie RDMA-Zugriff auf dem NFS-Server:

+
`vserver nfs modify -vserver _SVM_name_ -rdma enabled`

. Client über NFSv4.0 über RDMA mounten:
+
.. Die Eingabe für den Proto-Parameter hängt von der Server-IP-Protokollversion ab. Wenn es sich um IPv4 handelt, verwenden Sie `proto=rdma`. Wenn es sich um IPv6 handelt, verwenden Sie `proto=rdma6`.
.. Geben Sie den NFS-Ziel-Port als an `port=20049` Anstelle des Standardanschlusses 2049:
+
`mount -o vers=4,minorversion=0,proto=rdma,port=20049 _Server_IP_address_:/_volume_path_ _mount_point_`



. *OPTIONAL*: Wenn Sie die Bereitstellung des Clients aufheben müssen, führen Sie den Befehl aus `unmount _mount_path_`


--
====
.Weitere Informationen
* xref:../nfs-config/create-server-task.html[Erstellen Sie einen NFS-Server]
* xref:../task_nas_enable_linux_nfs.html[Aktivieren Sie NAS-Storage für Linux-Server mithilfe von NFS]

