---
permalink: nfs-rdma/index.html 
sidebar: sidebar 
keywords: NFS over RDMA, GPU, NVIDIA GDX 
summary: NFS over RDMA verwendet RDMA-fähige Adapter, wodurch Daten direkt zwischen Speicher und Arbeitsspeicher des Hostsystems kopiert werden können, ohne dass es zu CPU-Unterbrechungen und zusätzlichem Aufwand kommt. 
---
= Informationen zu NFS über RDMA in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS over RDMA verwendet RDMA-fähige Netzwerkadapter, sodass Daten direkt zwischen dem Speicher des Speichersystems und dem Speicher des Hostsystems kopiert werden können, wodurch CPU-Unterbrechungen und Overhead umgangen werden.

NFS over RDMA Konfigurationen sind für Kunden mit latenzsensitiven oder mit einer hohen Bandbreite Workloads wie Machine Learning und Analytics konzipiert. ONTAP NFS over RDMA kann für alle NFS basierten Workloads verwendet werden. Darüber hinaus hat NVIDIA NFS over RDMA erweitert, um GPU Direct Storage (GDS) zu ermöglichen. GDS beschleunigt GPU-fähige Workloads zusätzlich, indem CPU und Hauptspeicher vollständig umgangen werden und RDMA verwendet wird, um Daten direkt zwischen dem Speichersystem und dem GPU-Speicher zu übertragen.

Ab ONTAP 9.10.1 werden NFS over RDMA Konfigurationen für das NFSv4.0 Protokoll unterstützt. Nachfolgende ONTAP Versionen führten die Unterstützung für weitere NFS Versionen ein.

.Anforderungen
* Stellen Sie sicher, dass die richtige Version von ONTAP für die gewünschte NFS-Version verwendet wird.
+
[cols="2"]
|===
| NFS Version | ONTAP-Unterstützung 


| NFSv4.0 | ONTAP 9.10.1 und höher 


| NFSv4.1 | ONTAP 9.14.1 und höher 


| NFSv3 | ONTAP 9.15.1 und höher 
|===
+
** Ab ONTAP 9.12.1 kann NFS über RDMA mit System Manager konfiguriert werden. In ONTAP 9.10.1 und 9.11.1 ist die Konfiguration von NFS über RDMA mit der CLI erforderlich.


* Beide Knoten im Hochverfügbarkeitspaar (HA) müssen die gleiche Version haben.
* Speichersystemcontroller müssen RDMA unterstützen:
+
[cols="2"]
|===
| Beginnend mit ONTAP... | Die folgenden Controller unterstützen RDMA... 


| 9.10.1 und später  a| 
** AFF A400
** AFF A700
** AFF A800




| ONTAP 9.14.1 und höher  a| 
** AFF C-Series
** AFF A900




| ONTAP 9.15.1 und höher  a| 
** AFF A1K
** AFF A90
** AFF A70




| ONTAP 9.16.1 und höher  a| 
** AFF A50
** AFF A30
** AFF A20


|===
* Data LIFs müssen so konfiguriert sein, dass sie RDMA unterstützen.
* Informationen zur Unterstützung von Ziel-RNICs finden sich in der  https://hwu.netapp.com/["NetApp Hardware Universe"^].
* Informationen zu unterstützten Client-Betriebssystemen für NFS über RDMA sind in der  https://imt.netapp.com/matrix/["NetApp Interoperabilitätsmatrix (IMT)"^] zu finden. Für RoCE v2 unterstützte RNICs wird auf die jeweilige RNIC-Herstellerdokumentation verwiesen.



NOTE: Schnittstellengruppen werden bei NFS über RDMA nicht unterstützt.

.Nächste Schritte
* xref:./configure-nics-task.adoc[Netzwerkkarten für NFS über RDMA konfigurieren]
* xref:./configure-lifs-task.adoc[LIFs für NFS über RDMA konfigurieren]
* xref:./configure-nfs-task.adoc[NFS-Einstellungen für NFS über RDMA]


.Verwandte Informationen
* link:../concepts/rdma-concept.html["RDMA"]
* xref:../nfs-trunking/index.html[NFS Trunking Übersicht]
* https://datatracker.ietf.org/doc/html/rfc7530["RFC 7530: NFS Version 4 Protokoll"^]
* https://datatracker.ietf.org/doc/html/rfc8166["RFC 8166: Remote Direct Memory Access Transport für Remote Procedure Call Version 1"^]
* https://datatracker.ietf.org/doc/html/rfc8167["RFC 8167: Bidirektionaler Remote Procedure Call über RPC-over-RDMA Transports"^]
* https://datatracker.ietf.org/doc/html/rfc8267["RFC 8267: NFS-Upper-Layer-Bindung an RPC-over-RDMA Version 1"^]

