---
permalink: nfs-rdma/index.html 
sidebar: sidebar 
keywords: NFS over RDMA, GPU, NVIDIA GDX 
summary: NFS über RDMA-Adapter können direkt zwischen dem Speicher des Storage-Systems und dem Arbeitsspeicher des Host-Systems kopiert werden, wodurch CPU-Unterbrechungen und Overhead vermieden werden. 
---
= NFS über RDMA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS über RDMA-Adapter können direkt zwischen dem Speicher des Storage-Systems und dem Arbeitsspeicher des Host-Systems kopiert werden, wodurch CPU-Unterbrechungen und Overhead vermieden werden.

NFS-über-RDMA-Konfigurationen wurden für Kunden mit latenzempfindlichen Workloads mit hoher Bandbreite wie Machine Learning und Analytics entwickelt. NVIDIA hat NFS über RDMA erweitert, um GPU Direct Storage (GDS) zu unterstützen. GDS beschleunigt GPU-fähige Workloads noch weiter, da CPU und Hauptspeicher vollständig umgangen werden. Dazu wird RDMA verwendet, um Daten direkt zwischen dem Storage-System und dem GPU-Speicher zu übertragen.

NFS über RDMA wird ab ONTAP 9.10.1 unterstützt. NFS-over-RDMA-Konfigurationen werden für das NFSv4.0-Protokoll nur unterstützt, wenn dieser mit dem Mellanox CX-5 oder CX-6 Adapter verwendet wird. Dies unterstützt RDMA über Version 2 des RoCE-Protokolls. GDS wird nur mit NVIDIA Tesla- und Ampere-GPUs mit Mellanox NIC-Karten und MOFED-Software unterstützt. Die Unterstützung von NFS über RDMA ist nur für den lokalen Datenverkehr auf Nodes beschränkt. Standard-FlexVols oder FlexGroups, bei denen alle Komponenten auf demselben Node unterstützt werden und auf sie über eine LIF im selben Node zugegriffen werden muss. NFS-Mount-Größen über 64 KB führen zu instabiler Performance mit NFS-über RDMA-Konfigurationen.

.Anforderungen
* Storagesysteme müssen mit ONTAP 9.10.1 betrieben werden.
+
** Sie können NFS über RDMA mit System Manager ab ONTAP 9.12.1 konfigurieren. In ONTAP 9.10.1 und 9.11.1 müssen Sie NFS über RDMA mit der CLI konfigurieren.


* Beide Nodes im HA-Paar müssen die gleiche Version sein.
* Storage-System-Controller müssen über RDMA-Unterstützung verfügen (derzeit A400, A700 und A800).
* Storage Appliance konfiguriert mit RDMA-unterstützter Hardware (z. B. Mellanox CX-5 oder CX-6).
* Daten-LIFs müssen für die Unterstützung von RDMA konfiguriert sein.
* Clients müssen Mellanox RDMA-fähige NIC-Karten und die Mellanox OFED-Netzwerksoftware (MOFED) verwenden.


.Nächste Schritte
* xref:./configure-nics-task.adoc[Konfigurieren Sie NICs für NFS über RDMA]
* xref:./configure-lifs-task.adoc[Konfigurieren Sie LIFs für NFS über RDMA]
* xref:./configure-nfs-task.adoc[NFS-Einstellungen für NFS über RDMA]


.Weitere Informationen
* link:../concepts/rdma-concept["RDMA"]
* link:https://datatracker.ietf.org/doc/html/rfc7530["RFC 7530: NFS Version 4 Protocol"]
* link:https://datatracker.ietf.org/doc/html/rfc8166["RFC 8166: Remote Direct Memory Access Transport for Remote Procedure Call Version 1"]
* link:https://datatracker.ietf.org/doc/html/rfc8167["RFC 8167: Bidirektionaler Remote Procedure Call auf RPC-over-RDMA-Transports"]
* link:https://datatracker.ietf.org/doc/html/rfc8267["RFC 8267: NFS Upper-Layer Bindung an RPC-over-RDMA Version 1"]

