---
permalink: error-messages/configure-ems-events-send-email-task.html 
sidebar: sidebar 
keywords: configuring, important, ems, events, send, email, notifications 
summary: Um E-Mail-Benachrichtigungen über die wichtigsten Ereignisse zu erhalten, muss das EMS so konfiguriert werden, dass E-Mail-Nachrichten für Ereignisse gesendet werden, die auf wichtige Aktivitäten hinweisen. 
---
= Wichtige ONTAP EMS Ereignisse für den Versand von E-Mail-Benachrichtigungen konfigurieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um E-Mail-Benachrichtigungen über die wichtigsten Ereignisse zu erhalten, muss das EMS so konfiguriert werden, dass E-Mail-Nachrichten für Ereignisse gesendet werden, die auf wichtige Aktivitäten hinweisen.

.Bevor Sie beginnen
DNS muss auf dem Cluster konfiguriert sein, um die E-Mail-Adressen aufzulösen.

.Über diese Aufgabe
Diese Aufgabe kann jederzeit während des Betriebs des Clusters durch Eingabe der Befehle in der ONTAP Befehlszeile ausgeführt werden.

.Schritte
. Die SMTP-Mailservereinstellungen für Ereignisse konfigurieren:
+
`event config modify -mail-server mailhost.your_domain -mail-from cluster_admin@your_domain`

+
Weitere Informationen zu  `event config modify` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/event-config-modify.html["ONTAP-Befehlsreferenz"^].

. Ein E-Mail-Ziel für Ereignisbenachrichtigungen erstellen:
+
`event notification destination create -name storage-admins -email your_email@your_domain`

+
Weitere Informationen zu  `event notification destination create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/event-notification-destination-create.html["ONTAP-Befehlsreferenz"^].

. Die wichtigen Ereignisse konfigurieren, für die E-Mail-Benachrichtigungen gesendet werden:
+
`event notification create -filter-name important-events -destinations storage-admins`

+
Weitere Informationen zu  `event notification create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/event-notification-create.html["ONTAP-Befehlsreferenz"^].


