---
permalink: error-messages/configure-snmp-traphosts-event-notifications-task.html 
sidebar: sidebar 
keywords: configuring, snmp, traphosts, receive, event notifications 
summary: Um Ereignisbenachrichtigungen auf einem SNMP-Traphost zu erhalten, ist die Konfiguration eines Traphosts erforderlich. 
---
= ONTAP SNMP Traphosts für den Empfang von Ereignisbenachrichtigungen konfigurieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um Ereignisbenachrichtigungen auf einem SNMP-Traphost zu erhalten, ist die Konfiguration eines Traphosts erforderlich.

.Bevor Sie beginnen
* SNMP und SNMP Traps müssen auf dem Cluster aktiviert sein.
+
[NOTE]
====
SNMP und SNMP Traps sind standardmäßig aktiviert.

====
* DNS muss auf dem Cluster konfiguriert sein, um die Traphost-Namen aufzulösen.


.Über diese Aufgabe
Wenn noch kein SNMP Traphost konfiguriert ist, um Ereignisbenachrichtigungen (SNMP Traps) zu empfangen, muss einer hinzugefügt werden.

Diese Aufgabe kann jederzeit während des Betriebs des Clusters durch Eingabe der Befehle in der ONTAP Befehlszeile ausgeführt werden.

.Schritt
. Falls in Ihrer Umgebung noch kein SNMP Traphost für den Empfang von Ereignisbenachrichtigungen konfiguriert ist, sollte einer hinzugefügt werden:
+
`system snmp traphost add -peer-address _snmp_traphost_name_`

+
Alle Ereignisbenachrichtigungen, die von SNMP standardmäßig unterstützt werden, werden an den SNMP traphost weitergeleitet.


