---
permalink: error-messages/index.html 
sidebar: sidebar 
keywords: ems, configuration, event, management, system, events, notifications 
summary: 'Sie können ONTAP schnell so konfigurieren, dass wichtige EMS-Ereignisbenachrichtigungen (Event Management System) direkt an eine E-Mail-Adresse, einen Syslog-Server oder einen SNMP (Simple Management Network Protocol) traphost gesendet werden, damit Sie sofort über Systemprobleme informiert werden, die eine sofortige Behebung erfordern.' 
---
= EMS-Konfigurationsübersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ONTAP 9 schnell konfigurieren, um wichtige EMS-Ereignisbenachrichtigungen (Event Management System) direkt an eine E-Mail-Adresse, einen Syslog-Server, ein Simple Management Network Protocol (SNMP) traphost oder EINEN REST-API-Server zu senden, sodass Sie sofort über Systemprobleme informiert werden, bei denen eine sofortige Aufmerksamkeit erforderlich ist.

Um die wichtigsten Aktivitäten in Ihrem System zu überwachen, müssen Sie die wichtigen EMS-Ereignisse überwachen.

Da wichtige Ereignisbenachrichtigungen standardmäßig nicht aktiviert sind, müssen Sie das EMS so konfigurieren, dass Benachrichtigungen entweder an eine E-Mail-Adresse, einen Syslog-Server, einen SNMP traphost oder REST API-Server gesendet werden.

Konfigurieren Sie EMS-Ereignisbenachrichtigungen für wichtige Ereignisse, wenn Folgendes zutrifft:

* Sie implementieren eines der folgenden Szenarien:
+
** Sie einrichten ein neues System mit ONTAP 9, das nicht über EMS konfiguriert ist.
** Sie haben ein System, auf dem ONTAP 9 ausgeführt wird und das über kein EMS konfiguriert ist.
** Sie aktualisieren gerade auf ONTAP 9, das nicht über EMS konfiguriert ist.
** Sie haben gerade den Übergang von Data ONTAP im 7-Mode zu ONTAP 9 abgeschlossen.


* Sie möchten Best Practices verwenden und nicht alle verfügbaren Optionen erkunden.
* Sie wollen nicht viel konzeptuellen Hintergrund lesen.


Den EMS-Veranstaltungskatalog finden Sie unter Weitere Ressourcen auf dieser Seite: link:https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["ONTAP 9 Produktbibliothek"^]. Siehe xref:convert-ems-routing-to-notifications-task.html[Konvertieren Sie das Routing für ältere Ereignisse in Ereignisbenachrichtigungen] Weitere Informationen zur Durchführung der Benachrichtigungsbasierten Modellkonvertierung. Sie können auch auf die verweisen link:https://docs.netapp.com/us-en/ontap-ems-9121/["EMS-Referenz"^].
