---
permalink: error-messages/index.html 
sidebar: sidebar 
keywords: ems, configuration, event, management, system, events, notifications 
summary: 'Sie können ONTAP schnell so konfigurieren, dass wichtige EMS-Ereignisbenachrichtigungen (Event Management System) direkt an eine E-Mail-Adresse, einen Syslog-Server oder einen SNMP (Simple Management Network Protocol) traphost gesendet werden, damit Sie sofort über Systemprobleme informiert werden, die eine sofortige Behebung erfordern.' 
---
= EMS-Konfigurationsübersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ONTAP 9 so konfigurieren, dass wichtige EMS (Event Management System)-Ereignisbenachrichtigungen direkt an eine E-Mail-Adresse, Syslog-Server, Simple Management Network Protocol (SNMP) traphost oder Webhook-Anwendung gesendet werden, sodass Sie sofort über Systemprobleme benachrichtigt werden, die eine sofortige Aufmerksamkeit erfordern.

Da wichtige Ereignisbenachrichtigungen standardmäßig nicht aktiviert sind, müssen Sie das EMS so konfigurieren, dass Benachrichtigungen entweder an eine E-Mail-Adresse, einen Syslog-Server, eine SNMP traphost- oder Webhook-Anwendung gesendet werden.

Überprüfen Sie die Release-spezifischen Versionen der link:https://docs.netapp.com/us-en/ontap-ems-9131/["ONTAP 9 EMS-Referenz"^].

Wenn Ihre EMS-Ereigniszuordnung veraltete ONTAP-Befehlssätze verwendet (z. B. Ereignisziel, Ereignisroute), wird empfohlen, dass Sie Ihre Zuordnung aktualisieren. link:../error-messages/convert-ems-routing-to-notifications-task.html["Erfahren Sie, wie Sie Ihre EMS-Zuordnung von veralteten ONTAP-Befehlen aktualisieren können"].
