---
permalink: nfs-admin/break-locks-task.html 
sidebar: sidebar 
keywords: breaking, locks 
summary: Wenn Dateisperren den Zugriff von Clients auf Dateien verhindern, können Informationen über die aktuell bestehenden Sperren angezeigt und anschließend bestimmte Sperren aufgehoben werden. Beispiele für Szenarien, in denen das Aufheben von Sperren erforderlich sein kann, sind das Debuggen von Anwendungen. 
---
= Aufheben von Dateisperren für ONTAP NFS SVMs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Dateisperren den Zugriff von Clients auf Dateien verhindern, können Informationen über die aktuell bestehenden Sperren angezeigt und anschließend bestimmte Sperren aufgehoben werden. Beispiele für Szenarien, in denen das Aufheben von Sperren erforderlich sein kann, sind das Debuggen von Anwendungen.

.Über diese Aufgabe
Der  `vserver locks break`Befehl ist nur auf der erweiterten Berechtigungsstufe und höher verfügbar. Weitere Informationen zu  `vserver locks break` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-locks-break.html["ONTAP-Befehlsreferenz"^].

.Schritte
. Um die Informationen zu finden, die Sie zum Aufheben einer Sperre benötigen, verwenden Sie den  `vserver locks show` Befehl.
+
Weitere Informationen zu  `vserver locks show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-locks-show.html["ONTAP-Befehlsreferenz"^].

. Stellen Sie die Berechtigungsstufe auf „Erweitert“ ein:
+
`set -privilege advanced`

. Führen Sie eine der folgenden Aktionen aus:
+
[cols="35,65"]
|===


| Wenn ein Schloss durch Angabe von... aufgehoben werden soll | Geben Sie den Befehl ein... 


 a| 
Der SVM Name, der Volumenname, der LIF Name und der Dateipfad
 a| 
`vserver locks break -vserver vserver_name -volume volume_name -path path -lif lif`



 a| 
Die Lock-ID
 a| 
`vserver locks break -lockid UUID`

|===
. Zurück zur Administrator-Privilegstufe:
+
`set -privilege admin`


