---
permalink: nfs-admin/case-sensitivity-file-directory-multiprotocol-concept.html 
sidebar: sidebar 
keywords: case sensitivity, file, directory, name, multiprotocol, environment 
summary: Datei- und Verzeichnisnamen werden bei NFS-Clients Groß-/Kleinschreibung berücksichtigt, und die Groß-/Kleinschreibung wird nicht berücksichtigt. Sie müssen die Auswirkungen in einer Multi-Protokoll-Umgebung und die Aktionen verstehen, die Sie bei der Angabe des Pfads beim Erstellen von SMB-Freigaben und beim Zugriff auf Daten innerhalb der Freigaben ergreifen müssen. 
---
= Groß-/Kleinschreibung von Datei- und Verzeichnisnamen in einer Multi-Protokoll-Umgebung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Datei- und Verzeichnisnamen werden bei NFS-Clients Groß-/Kleinschreibung berücksichtigt, und die Groß-/Kleinschreibung wird nicht berücksichtigt. Sie müssen die Auswirkungen in einer Multi-Protokoll-Umgebung und die Aktionen verstehen, die Sie bei der Angabe des Pfads beim Erstellen von SMB-Freigaben und beim Zugriff auf Daten innerhalb der Freigaben ergreifen müssen.

Wenn ein SMB-Client ein Verzeichnis mit dem Namen erstellt `testdir`, Sowohl SMB- als auch NFS-Clients zeigen den Dateinamen als an `testdir`. Wenn jedoch ein SMB-Benutzer später versucht, einen Verzeichnisnamen zu erstellen `TESTDIR`, Der Name ist nicht zulässig, da, für den SMB-Client, dieser Name derzeit existiert. Wenn ein NFS-Benutzer später ein Verzeichnis mit dem Namen erstellt `TESTDIR`, NFS- und SMB-Clients zeigen den Verzeichnisnamen anders an, wie folgt:

* Auf NFS-Clients werden beispielsweise beide Verzeichnisnamen angezeigt, wie sie erstellt wurden `testdir` Und `TESTDIR`, Weil Verzeichnisnamen die Groß-/Kleinschreibung beachten.
* SMB-Clients verwenden die 8.3 Namen, um zwischen den beiden Verzeichnissen zu unterscheiden. Ein Verzeichnis hat den Basisdateinamen. Zusätzlichen Verzeichnissen wird ein Dateiname von 8.3 zugewiesen.
+
** Auf SMB-Clients wird angezeigt `testdir` Und `TESTDI~1`.
** ONTAP erstellt das `TESTDI~1` Verzeichnisname zur Unterscheidung der beiden Verzeichnisse.
+
In diesem Fall müssen Sie den Namen 8.3 verwenden, wenn Sie einen Freigabepfad angeben, während Sie eine Freigabe auf einer Storage Virtual Machine (SVM) erstellen oder ändern.





Gleiches gilt für Dateien, wenn ein SMB-Client erstellt wird `test.txt`, Sowohl SMB- als auch NFS-Clients zeigen den Dateinamen als an `text.txt`. Wenn jedoch ein SMB-Benutzer später versucht, es zu erstellen `Test.txt`, Der Name ist nicht zulässig, da, für den SMB-Client, dieser Name derzeit existiert. Wenn ein NFS-Benutzer später eine Datei mit dem Namen erstellt `Test.txt`, NFS- und SMB-Clients zeigen den Dateinamen anders an, wie folgt:

* Auf NFS-Clients werden beide Dateinamen angezeigt, während sie erstellt wurden. `test.txt` Und `Test.txt`, Weil Dateinamen Groß- und Kleinschreibung beachten.
* SMB-Clients verwenden die 8.3 Namen, um zwischen den beiden Dateien zu unterscheiden. Eine Datei hat den Basisdateinamen. Zusätzlichen Dateien wird ein Dateiname von 8.3 zugewiesen.
+
** Auf SMB-Clients wird angezeigt `test.txt` Und `TEST~1.TXT`.
** ONTAP erstellt das `TEST~1.TXT` Dateiname zur Unterscheidung der beiden Dateien.




[NOTE]
====
Wenn Sie die Zeichenzuordnung über die CIFS-Befehle zur Character Mapping von Vserver aktiviert oder geändert haben, wird bei einer Windows Lookup im Normalfall die Groß-/Kleinschreibung nicht berücksichtigt.

====