---
permalink: nfs-admin/commands-manage-name-service-cache-reference.html 
sidebar: sidebar 
keywords: command, managing, name, service, cache 
summary: 'Sie können den Name-Service-Cache verwalten, indem Sie den Wert für Live (TTL) ändern. Der TTL-Wert bestimmt, wie lange Name-Service-Informationen im Cache persistent sind.' 
---
= Befehle zum Verwalten von Name Service Cache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Name-Service-Cache verwalten, indem Sie den Wert für Live (TTL) ändern. Der TTL-Wert bestimmt, wie lange Name-Service-Informationen im Cache persistent sind.

[cols="35,65"]
|===


| Wenn Sie den TTL-Wert ändern möchten für... | Befehl 


 a| 
UNIX-Benutzer
 a| 
`vserver services name-service cache unix-user settings`



 a| 
UNIX-Gruppen
 a| 
`vserver services name-service cache unix-group settings`



 a| 
UNIX-Netzwerkgruppen
 a| 
`vserver services name-service cache netgroups settings`



 a| 
Hosts
 a| 
`vserver services name-service cache hosts settings`



 a| 
Gruppenmitgliedschaft
 a| 
`vserver services name-service cache group-membership settings`

|===
.Verwandte Informationen
link:../concepts/manual-pages.html["Befehlsreferenz für ONTAP"]
