---
permalink: nfs-admin/commands-manage-nis-domain-config-reference.html 
sidebar: sidebar 
keywords: command, manage, nis, domain, configuration 
summary: Es gibt bestimmte ONTAP Befehle zum Verwalten von NIS Domain-Konfigurationen. 
---
= ONTAP-Befehle zum Verwalten von NFS-NIS-Domänenkonfigurationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es gibt bestimmte ONTAP Befehle zum Verwalten von NIS Domain-Konfigurationen.

[cols="35,65"]
|===


| Ihr Ziel ist | Befehl 


 a| 
Erstellen Sie eine NIS-Domänenkonfiguration
 a| 
`vserver services name-service nis-domain create`



 a| 
Anzeige der NIS-Domänenkonfigurationen
 a| 
`vserver services name-service nis-domain show`



 a| 
Anzeige des Bindungsstatus einer NIS-Domain-Konfiguration
 a| 
`vserver services name-service nis-domain show-bound`



 a| 
Zeigt die NIS-Statistiken an
 a| 
`vserver services name-service nis-domain show-statistics` Verfügbar auf der erweiterten Berechtigungsebene und höher.



 a| 
Löschen Sie NIS-Statistiken
 a| 
`vserver services name-service nis-domain clear-statistics` Verfügbar auf der erweiterten Berechtigungsebene und höher.



 a| 
Ändern Sie eine NIS-Domänenkonfiguration
 a| 
`vserver services name-service nis-domain modify`



 a| 
Löschen Sie eine NIS-Domänenkonfiguration
 a| 
`vserver services name-service nis-domain delete`



 a| 
Aktivieren Sie das Caching für Netzgruppensuche nach Host
 a| 
`vserver services name-service nis-domain netgroup-database config modify` Verfügbar auf der erweiterten Berechtigungsebene und höher.

|===
Erfahren Sie mehr über `vserver services name-service nis-domain` in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+services+name-service+nis-domain["ONTAP-Befehlsreferenz"^].
