---
permalink: nfs-admin/configure-security-styles-qtrees-task.html 
sidebar: sidebar 
keywords: configure, security, style, qtree 
summary: Sie konfigurieren den Sicherheitsstil des qtree Volume, um die Art der Berechtigungen zu bestimmen, die für Daten in qtrees verwendet werden. 
---
= Security Styles auf qtrees konfigurieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie konfigurieren den Sicherheitsstil des qtree Volume, um die Art der Berechtigungen zu bestimmen, die für Daten in qtrees verwendet werden.

.Schritte
. Führen Sie eine der folgenden Aktionen aus:
+
[cols="30,70"]
|===


| Wenn der qtree... | Verwenden Sie den Befehl... 


 a| 
Ist noch nicht vorhanden
 a| 
`volume qtree create` Und nehmen Sie die auf `-security-style` Parameter, um den Sicherheitsstil anzugeben.



 a| 
Ist bereits vorhanden
 a| 
`volume qtree modify` Und nehmen Sie die auf `-security-style` Parameter, um den Sicherheitsstil anzugeben.

|===
+
Die möglichen Optionen für den qtree-Sicherheitsstil sind `unix`, `ntfs`, Oder `mixed`.

+
Wenn Sie beim Erstellen eines qtree keinen Sicherheitsstil angeben, wird der Standardsicherheitsstil festgelegt `mixed`.

+
Weitere Informationen zum `volume qtree create` Oder `volume qtree modify` Befehle, siehe link:../volumes/index.html["Logisches Storage-Management"].

. Geben Sie zum Anzeigen der Konfiguration, einschließlich des Sicherheitsstils des erstellten qtree, den folgenden Befehl ein: `volume qtree show -qtree _qtree_name_ -instance`

