---
permalink: nfs-admin/control-nfs-requests-nonreserved-ports-task.html 
sidebar: sidebar 
keywords: control, nfs, request, nonreserved, port 
summary: Sie können NFS-Mount-Anfragen von nicht reservierten Ports ablehnen, indem Sie die Option -mount-rootonly aktivieren. Um alle NFS-Anfragen von nicht reservierten Ports abzulehnen, kann die Option -nfs-rootonly aktiviert werden. 
---
= NFS-Anfragen von nicht reservierten Ports für ONTAP SVMs steuern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können NFS-Mount-Anfragen von nicht reservierten Ports ablehnen, indem Sie die `-mount-rootonly` Option aktivieren. Um alle NFS-Anfragen von nicht reservierten Ports abzulehnen, kann die `-nfs-rootonly` Option aktiviert werden.

.Über diese Aufgabe
Standardmäßig ist die Option `-mount-rootonly`  `enabled`.

Standardmäßig ist die Option `-nfs-rootonly`  `disabled`.

Diese Optionen gelten nicht für die NULL-Prozedur.

.Schritt
. Führen Sie eine der folgenden Aktionen aus:
+
[cols="35,65"]
|===


| Wenn Sie möchten... | Geben Sie den Befehl ein... 


 a| 
NFS Mount-Anfragen von nicht reservierten Ports zulassen
 a| 
`vserver nfs modify -vserver vserver_name -mount-rootonly disabled`



 a| 
NFS Mount-Anfragen von nicht reservierten Ports ablehnen
 a| 
`vserver nfs modify -vserver vserver_name -mount-rootonly enabled`



 a| 
Alle NFS-Anfragen von nicht reservierten Ports zulassen
 a| 
`vserver nfs modify -vserver vserver_name -nfs-rootonly disabled`



 a| 
Alle NFS-Anfragen von nicht reservierten Ports ablehnen
 a| 
`vserver nfs modify -vserver vserver_name -nfs-rootonly enabled`

|===

