---
permalink: nfs-admin/control-root-user-access-ntfs-security-data-task.html 
sidebar: sidebar 
keywords: control, root, user, access, ntfs, security, style, data 
summary: 'Sie können ONTAP so konfigurieren, dass NFS-Clients Zugriff auf NTFS-Sicherheitsdaten und NTFS-Clients auf die Daten im NFS-Sicherheitsstil erhalten. Wenn Sie den NTFS-Sicherheitsstil bei einem NFS-Datenspeicher verwenden, müssen Sie entscheiden, wie der Root-Benutzer den Zugriff behandelt und die SVM (Storage Virtual Machine) entsprechend konfiguriert.' 
---
= Kontrolle des Root-Benutzerzugriffs auf NTFS-Sicherheitsdaten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ONTAP so konfigurieren, dass NFS-Clients Zugriff auf NTFS-Sicherheitsdaten und NTFS-Clients auf die Daten im NFS-Sicherheitsstil erhalten. Wenn Sie den NTFS-Sicherheitsstil bei einem NFS-Datenspeicher verwenden, müssen Sie entscheiden, wie der Root-Benutzer den Zugriff behandelt und die SVM (Storage Virtual Machine) entsprechend konfiguriert.

Wenn ein Root-Benutzer auf NTFS-Sicherheitsdaten zugreift, haben Sie zwei Optionen:

* Ordnen Sie den Root-Benutzer wie jeder andere NFS-Benutzer einem Windows-Benutzer zu und verwalten Sie den Zugriff nach NTFS ACLs.
* Ignorieren Sie NTFS ACLs und bieten Sie vollständigen Zugriff auf das Root.


.Schritte
. Legen Sie die Berechtigungsebene auf erweitert fest:
+
`set -privilege advanced`

. Führen Sie die gewünschte Aktion aus:
+
[cols="35,65"]
|===


| Wenn der Root-Benutzer... | Geben Sie den Befehl ein... 


 a| 
Werden einem Windows-Benutzer zugeordnet
 a| 
`vserver nfs modify -vserver vserver_name -ignore-nt-acl-for-root disabled`



 a| 
Umgehen Sie die NT-ACL-Prüfung
 a| 
`vserver nfs modify -vserver vserver_name -ignore-nt-acl-for-root enabled`

|===
+
Dieser Parameter ist standardmäßig deaktiviert.

+
Wenn dieser Parameter aktiviert ist, aber keine Namenszuweisung für den Root-Benutzer vorhanden ist, verwendet ONTAP für die Prüfung eine standardmäßige SMB-Administratoranmeldungs-Berechtigung.

. Zurück zur Administratorberechtigungsebene:
+
`set -privilege admin`


