---
permalink: nfs-admin/create-volumes-without-specifying-junction-task.html 
sidebar: sidebar 
keywords: create, data, volume, specify, junction, point 
summary: Sie können ein Daten-Volume erstellen, ohne einen Verbindungspunkt anzugeben. Das resultierende Volume wird nicht automatisch gemountet und steht für den NAS-Zugriff nicht zur Verfügung. Sie müssen das Volume mounten, bevor Sie SMB-Freigaben oder NFS-Exporte für dieses Volume konfigurieren können. 
---
= Erstellung von Daten-Volumes ohne Angabe von Verbindungspunkten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Daten-Volume erstellen, ohne einen Verbindungspunkt anzugeben. Das resultierende Volume wird nicht automatisch gemountet und steht für den NAS-Zugriff nicht zur Verfügung. Sie müssen das Volume mounten, bevor Sie SMB-Freigaben oder NFS-Exporte für dieses Volume konfigurieren können.

.Bevor Sie beginnen
* Das Aggregat, in dem Sie das Volume erstellen möchten, muss bereits vorhanden sein.
* Ab ONTAP 9.13.1 können Sie Volumes mit aktivierten Kapazitätsanalysen und Aktivitätsverfolgung erstellen. Um die Kapazitäts- oder Aktivitätsverfolgung zu aktivieren, geben Sie das ein `volume create` Befehl mit `-analytics-state` Oder `-activity-tracking-state` Auf einstellen `on`.
+
Weitere Informationen zur Kapazitätsanalyse und Aktivitätsverfolgung finden Sie unter xref:../task_nas_file_system_analytics_enable.html[Dateisystemanalyse Aktivieren].



.Schritte
. Um das Volume ohne Verbindungspunkt zu erstellen, verwenden Sie folgenden Befehl:
+
`volume create -vserver vserver_name -volume volume_name -aggregate aggregate_name -size {integer[KB|MB|GB|TB|PB]} -security-style {ntfs|unix|mixed}`

+
Die Angabe eines Volume-Sicherheitsstils ist optional. Wenn Sie keinen Sicherheitsstil angeben, erstellt ONTAP das Volume mit dem gleichen Sicherheitstyp, der auf das Root-Volume der SVM (Storage Virtual Machine) angewendet wird. Der Sicherheitsstil des Root-Volumes ist jedoch möglicherweise nicht der Sicherheitsstil, den Sie auf das Datenvolumen anwenden möchten. Es wird empfohlen, beim Erstellen des Volumes den Sicherheitsstil festzulegen, um Probleme mit dem Dateizugriff zu minimieren, die sich nur schwer beheben lassen.

+
Es gibt viele optionale Parameter, mit denen Sie ein Daten-Volume anpassen können. Weitere Informationen dazu finden Sie auf den man-Pages für die `volume create` Befehl.

. Vergewissern Sie sich, dass das Volume ohne Verbindungspunkt erstellt wurde:
+
`volume show -vserver vserver_name -volume volume_name -junction`



.Beispiel
Im folgenden Beispiel wird ein Volume mit dem Namen „`sales`“ auf der SVM vs1 erstellt, das nicht an einem Verbindungspunkt gemountet ist:

[listing]
----
cluster1::> volume create -vserver vs1 -volume sales -aggregate aggr3 -size 20GB
[Job 3406] Job succeeded: Successful

cluster1::> volume show -vserver vs1 -junction
                     Junction                 Junction
Vserver   Volume     Active   Junction Path   Path Source
--------- ---------- -------- --------------- -----------
vs1       data       true     /data           RW_volume
vs1       home4      true     /eng/home       RW_volume
vs1       vs1_root   -        /               -
vs1       sales      -        -               -
----