---
permalink: nfs-admin/decide-security-style-svm-flexvol-concept.html 
sidebar: sidebar 
keywords: decide, security, style, svm 
summary: Zur Unterstützung bei der Entscheidung, welchen Sicherheitsstil Sie für ein Volume verwenden, sind zwei Faktoren zu berücksichtigen. Der wichtigste Faktor ist die Art des Administrators, der das Dateisystem verwaltet. Der zweite Faktor ist die Art des Benutzers oder Dienstes, der auf die Daten auf dem Volume zugreift. 
---
= Festlegung des zu verwendenden Sicherheitsstils auf ONTAP NAS SVMs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zur Unterstützung bei der Entscheidung, welchen Sicherheitsstil Sie für ein Volume verwenden, sind zwei Faktoren zu berücksichtigen. Der wichtigste Faktor ist die Art des Administrators, der das Dateisystem verwaltet. Der zweite Faktor ist die Art des Benutzers oder Dienstes, der auf die Daten auf dem Volume zugreift.

Bei der Konfiguration des Sicherheitsstils eines Volumes sollten die Anforderungen Ihrer Umgebung berücksichtigt werden, um den optimalen Sicherheitsstil auszuwählen und Probleme bei der Berechtigungsverwaltung zu vermeiden. Die folgenden Überlegungen können bei der Entscheidung helfen:

[cols="20,80"]
|===


| Sicherheitsstil | Wählen Sie aus, ob... 


 a| 
UNIX
 a| 
* Das Dateisystem wird von einem UNIX-Administrator verwaltet.
* Die Mehrheit der Nutzer sind NFS-Clients.
* Eine Anwendung, die auf die Daten zugreift, verwendet einen UNIX-Benutzer als Dienstkonto.




 a| 
NTFS
 a| 
* Das Dateisystem wird von einem Windows-Administrator verwaltet.
* Die Mehrheit der Nutzer sind SMB-Clients.
* Eine Anwendung, die auf die Daten zugreift, verwendet einen Windows-Benutzer als Dienstkonto.




 a| 
Gemischt
 a| 
* Das Dateisystem wird sowohl von UNIX- als auch von Windows-Administratoren verwaltet, und die Benutzer bestehen sowohl aus NFS- als auch aus SMB-Clients.


|===