---
permalink: nfs-admin/default-export-policy-svms-concept.html 
sidebar: sidebar 
keywords: default, export, policy, svm 
summary: Jede SVM verfügt über eine standardmäßige Exportrichtlinie ohne Regeln. Eine Exportrichtlinie mit Regeln muss vorhanden sein, bevor Clients auf Daten in der SVM zugreifen können. Jedes in der SVM enthaltene FlexVol volume muss einer Exportrichtlinie zugeordnet sein. 
---
= Standard-Exportrichtlinien für ONTAP NFS SVMs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Jede SVM verfügt über eine standardmäßige Exportrichtlinie ohne Regeln. Eine Exportrichtlinie mit Regeln muss vorhanden sein, bevor Clients auf Daten in der SVM zugreifen können. Jedes in der SVM enthaltene FlexVol volume muss einer Exportrichtlinie zugeordnet sein.

Beim Erstellen einer SVM erstellt das Speichersystem automatisch eine Standardexportrichtlinie namens  `default` für das Root-Volume der SVM. Es müssen eine oder mehrere Regeln für die Standard-Exportregel erstellt werden, bevor Clients auf Daten auf der SVM zugreifen können. Alternativ kann eine benutzerdefinierte Exportrichtlinie mit Regeln erstellt werden. Die Standardexportrichtlinie kann geändert und umbenannt werden, aber sie kann nicht gelöscht werden.

Wenn Sie ein FlexVol volume in der zugehörigen SVM erstellen, erstellt das Speichersystem das volume und ordnet das volume der Standardexportrichtlinie für das Root-Volume der SVM zu. Standardmäßig ist jedes in der SVM erstellte volume der Standardexportrichtlinie für das Root-Volume zugeordnet. Die Standardexportrichtlinie kann für alle in der SVM enthaltenen volumes verwendet werden, alternativ kann für jedes volume eine eigene Exportrichtlinie erstellt werden. Mehrere volumes können derselben Exportrichtlinie zugeordnet werden.
