---
permalink: nfs-admin/display-volume-mount-junction-point-task.html 
sidebar: sidebar 
keywords: display, volume, mount, junction, point, information 
summary: 'Sie können Informationen zu gemounteten Volumes für Storage Virtual Machines (SVMs) und den Verbindungspunkten für die Volumes anzeigen. Sie können auch festlegen, welche Volumes nicht an einem Verbindungspunkt angehängt sind. Anhand dieser Informationen können Sie Ihren SVM-Namespace verstehen und managen.' 
---
= Anzeige von Informationen zu Volume Mount und Verbindungspunktpunkten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Informationen zu gemounteten Volumes für Storage Virtual Machines (SVMs) und den Verbindungspunkten für die Volumes anzeigen. Sie können auch festlegen, welche Volumes nicht an einem Verbindungspunkt angehängt sind. Anhand dieser Informationen können Sie Ihren SVM-Namespace verstehen und managen.

.Schritt
. Führen Sie die gewünschte Aktion aus:
+
[cols="35,65"]
|===


| Sie möchten Folgendes anzeigen: | Geben Sie den Befehl ein... 


 a| 
Zusammenfassende Informationen über gemountete und abgehängt Volumes auf der SVM
 a| 
`volume show -vserver _vserver_name_ -junction`



 a| 
Detaillierte Informationen zu gemounteten und abgehängt Volumes auf der SVM
 a| 
`volume show -vserver _vserver_name_ -volume _volume_name_ -instance`



 a| 
Spezifische Informationen über gemountete und abgehängt Volumes auf der SVM
 a| 
.. Bei Bedarf können Sie gültige Felder für das anzeigen `-fields` Parameter mit dem folgenden Befehl:
`volume show -fields ?`
.. Zeigen Sie die gewünschten Informationen mit dem an `-fields` Parameter:
`volume show -vserver _vserver_name_ -fields _fieldname_,...`


|===


Im folgenden Beispiel werden eine Zusammenfassung der gemounteten und nicht abgehängt Volumes auf SVM vs1 angezeigt:

[listing]
----
cluster1::> volume show -vserver vs1 -junction
                     Junction                 Junction
Vserver   Volume     Active   Junction Path   Path Source
--------- ---------- -------- --------------- -----------
vs1       data       true     /data           RW_volume
vs1       home4      true     /eng/home       RW_volume
vs1       vs1_root   -        /               -
vs1       sales      true     /sales          RW_volume
----
Im folgenden Beispiel werden Informationen zu den angegebenen Feldern für Volumes in SVM vs2 angezeigt:

[listing]
----
cluster1::> volume show -vserver vs2 -fields vserver,volume,aggregate,size,state,type,security-style,junction-path,junction-parent,node
vserver volume   aggregate size state  type security-style junction-path junction-parent node
------- ------   --------- ---- ------ ---- -------------- ------------- --------------- -----
vs2     data1    aggr3     2GB  online RW   unix           -             -               node3
vs2     data2    aggr3     1GB  online RW   ntfs           /data2        vs2_root        node3
vs2     data2_1  aggr3     8GB  online RW   ntfs           /data2/d2_1   data2           node3
vs2     data2_2  aggr3     8GB  online RW   ntfs           /data2/d2_2   data2           node3
vs2     pubs     aggr1     1GB  online RW   unix           /publications vs2_root        node1
vs2     images   aggr3     2TB  online RW   ntfs           /images       vs2_root        node3
vs2     logs     aggr1     1GB  online RW   unix           /logs         vs2_root        node1
vs2     vs2_root aggr3     1GB  online RW   ntfs           /             -               node3
----