---
permalink: nfs-admin/display-ldap-statistics-task.html 
sidebar: sidebar 
keywords: display, ldap, statistics 
summary: 'Ab ONTAP 9.2 können Sie LDAP-Statistiken für Storage Virtual Machines (SVMs) auf einem Storage-System anzeigen, um die Performance zu überwachen und Probleme zu diagnostizieren.' 
---
= Zeigt LDAP-Statistiken an
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.2 können Sie LDAP-Statistiken für Storage Virtual Machines (SVMs) auf einem Storage-System anzeigen, um die Performance zu überwachen und Probleme zu diagnostizieren.

.Was Sie benötigen
* Sie müssen einen LDAP-Client auf der SVM konfiguriert haben.
* Sie müssen LDAP-Objekte identifiziert haben, von denen Sie Daten anzeigen können.


.Schritt
. Performance-Daten für Zählerobjekte anzeigen:
+
`statistics show`



.Beispiele
Das folgende Beispiel zeigt die Performance-Daten für das Objekt `secd_external_service_op`:

[listing]
----
cluster::*> statistics show -vserver vserverName -object secd_external_service_op -instance “vserverName:LDAP (NIS & Name Mapping):GetUserInfoFromName:1.1.1.1”

Object: secd_external_service_op
Instance: vserverName:LDAP (NIS & Name Mapping):GetUserInfoFromName:1.1.1.1
Start-time: 4/13/2016 22:15:38
End-time: 4/13/2016 22:15:38
Scope: vserverName
Counter                            Value
-------------------------------- --------------------------------
instance_name                      vserverName:LDAP (NIS & Name
                                   Mapping):GetUserInfoFromName:
                                   1.1.1.1
last_modified_time                 1460610787
node_name                          nodeName
num_not_found_responses            1
num_request_failures               1
num_requests_sent                  1
num_responses_received             1
num_successful_responses           0
num_timeouts                       0
operation                          GetUserInfoFromName
process_name                       secd
request_latency                    52131us
----