---
permalink: nfs-admin/enable-disable-nfsv4-acls-task.html 
sidebar: sidebar 
keywords: enable, disable, nfsv4, acls 
summary: Um NFSv4-ACLs zu aktivieren oder zu deaktivieren, können Sie die Optionen -v4.0-acl und -v4.1-acl ändern. Diese Optionen sind standardmäßig deaktiviert. 
---
= Aktivieren oder Deaktivieren von NFSv4-ACLs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um NFSv4-ACLs zu aktivieren oder `-v4.0-acl` `-v4.1-acl` zu deaktivieren, können Sie die Optionen und ändern. Diese Optionen sind standardmäßig deaktiviert.

.Über diese Aufgabe
Die `-v4.0-acl` `-v4.1-acl` Option oder steuert die Einstellung und Anzeige von NFSv4-ACLs; sie kontrolliert nicht die Durchsetzung dieser ACLs zur Zugriffsprüfung.

.Schritt
. Führen Sie eine der folgenden Aktionen aus:
+
[cols="30,70"]
|===


| Ihr Ziel ist | Dann... 


 a| 
Aktivieren Sie NFSv4.0 ACLs
 a| 
Geben Sie den folgenden Befehl ein:

`vserver nfs modify -vserver vserver_name -v4.0-acl enabled`



 a| 
Deaktivieren Sie NFSv4.0 ACLs
 a| 
Geben Sie den folgenden Befehl ein:

`vserver nfs modify -vserver vserver_name -v4.0-acl disabled`



 a| 
Aktivieren Sie NFSv4.1 ACLs
 a| 
Geben Sie den folgenden Befehl ein:

`vserver nfs modify -vserver vserver_name -v4.1-acl enabled`



 a| 
Deaktivieren Sie NFSv4.1 ACLs
 a| 
Geben Sie den folgenden Befehl ein:

`vserver nfs modify -vserver vserver_name -v4.1-acl disabled`

|===

