---
permalink: nfs-admin/enable-access-windows-nfs-clients-task.html 
sidebar: sidebar 
keywords: enable, access, windows, nfs, clients 
summary: ONTAP unterstützt Dateizugriff von Windows NFSv3 Clients. Das bedeutet, dass Clients mit Windows Betriebssystemen, die NFSv3 unterstützen, auf Dateien in NFSv3 Exporten des Clusters zugreifen können. Um diese Funktion erfolgreich zu nutzen, müssen Sie die Storage Virtual Machine korrekt konfigurieren und sich bestimmter Anforderungen und Einschränkungen bewusst sein. 
---
= Zugriff für Windows NFS-Clients auf ONTAP SVMs ermöglichen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP unterstützt Dateizugriff von Windows NFSv3 Clients. Das bedeutet, dass Clients mit Windows Betriebssystemen, die NFSv3 unterstützen, auf Dateien in NFSv3 Exporten des Clusters zugreifen können. Um diese Funktion erfolgreich zu nutzen, ist eine korrekte Konfiguration der Storage Virtual Machine (SVM) erforderlich und bestimmte Anforderungen sowie Einschränkungen sind zu berücksichtigen.

.Über diese Aufgabe
Standardmäßig ist die Unterstützung für Windows NFSv3 Client deaktiviert.

.Bevor Sie beginnen
NFSv3 muss auf der SVM aktiviert sein.

.Schritte
. Windows NFSv3 Client-Unterstützung aktivieren:
+
`vserver nfs modify -vserver _svm_name_ -v3-ms-dos-client enabled -mount-rootonly disabled`

. Auf allen SVMs, die Windows NFSv3-Clients unterstützen, die Parameter  `-enable-ejukebox` und  `-v3-connection-drop` deaktivieren:
+
`vserver nfs modify -vserver vserver_name -enable-ejukebox false -v3-connection-drop disabled`

+
Windows NFSv3 Clients können jetzt Exporte auf dem Speichersystem einbinden.

. Es wird sichergestellt, dass jeder Windows NFSv3 Client feste Mounts verwendet, indem die  `-o mtype=hard` Option angegeben wird.
+
Dies ist erforderlich, um zuverlässige Mounts sicherzustellen.

+
`mount -o mtype=hard \\10.53.33.10\vol\vol1 z:\`


