---
permalink: nfs-admin/enable-disable-nfsv4-read-file-delegations-task.html 
sidebar: sidebar 
keywords: enable, disable, nfsv4, read, file, delegation 
summary: Um die NFSv4-Delegation für Lesedateien zu aktivieren oder zu deaktivieren, können Sie die Option -v4.0-read-Delegationen oder -v4.1-read-Delegationen ändern. Durch die Aktivierung von Read-File-Delegationen können Sie einen Großteil des Nachrichtenaufwands für das Öffnen und Schließen von Dateien beseitigen. 
---
= Aktivieren oder deaktivieren Sie NFSv4-Lesedatei-Delegationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um NFSv4-Delegationen für Lesedateien zu aktivieren oder zu deaktivieren, können Sie die ändern ``-v4.0-read-delegation``Oder Option. Durch die Aktivierung von Read-File-Delegationen können Sie einen Großteil des Nachrichtenaufwands für das Öffnen und Schließen von Dateien beseitigen.

.Über diese Aufgabe
Standardmäßig sind Lesedatei-Delegationen deaktiviert.

Der Nachteil bei der Aktivierung der Lesedatei-Delegationen besteht darin, dass der Server und seine Clients die Delegationen wiederherstellen müssen, nachdem der Server neu gestartet oder neu gestartet wurde, ein Client neu gestartet oder neu gestartet wurde oder eine Netzwerkpartition stattfindet.

.Schritt
. Führen Sie eine der folgenden Aktionen aus:
+
[cols="35,65"]
|===


| Ihr Ziel ist | Dann... 


 a| 
Aktivieren Sie die NFSv4-Delegation für Lesedateien
 a| 
Geben Sie den folgenden Befehl ein:

`vserver nfs modify -vserver vserver_name -v4.0-read-delegation enabled`



 a| 
Aktivieren der NFSv4.1-Dateidelegationen
 a| 
Geben Sie den folgenden Befehl ein:

+
`vserver nfs modify -vserver vserver_name -v4.1-read-delegation enabled`



 a| 
Deaktivieren Sie NFSv4-Lesedatei-Delegationen
 a| 
Geben Sie den folgenden Befehl ein:

`vserver nfs modify -vserver vserver_name -v4.0-read-delegation disabled`



 a| 
Deaktivieren Sie NFSv4.1 „Read File Delegationen“
 a| 
Geben Sie den folgenden Befehl ein:

`vserver nfs modify -vserver vserver_name -v4.1-read-delegation disabled`

|===


.Ergebnis
Die Optionen für die Dateidelegation werden wirksam, sobald sie geändert wurden. Es ist nicht erforderlich, NFS neu zu starten oder neu zu starten.
