---
permalink: nfs-admin/export-policies-client-access-volumes-concept.html 
sidebar: sidebar 
keywords: export, policies, control, client, access, volume, qtrees 
summary: Exportrichtlinien enthalten eine oder mehrere Exportregeln, die jede Clientzugriffsanfrage verarbeiten. Das Ergebnis des Prozesses bestimmt, ob dem Client der Zugriff verweigert oder gewährt wird und auf welcher Zugriffsebene. Auf der Storage Virtual Machine muss eine Exportrichtlinie mit Exportregeln vorhanden sein, damit Clients auf Daten zugreifen können. 
---
= Wie Exportrichtlinien den Clientzugriff auf ONTAP NFS-Volumes oder Qtrees steuern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Exportrichtlinien enthalten eine oder mehrere Exportregeln, die jede Clientzugriffsanfrage verarbeiten. Das Ergebnis des Prozesses bestimmt, ob dem Client der Zugriff verweigert oder gewährt wird und auf welcher Zugriffsebene. Eine Exportrichtlinie mit Exportregeln muss auf der Storage Virtual Machine (SVM) vorhanden sein, damit Clients auf Daten zugreifen können.

Jedem Volume oder Qtree wird genau eine Exportregel zugeordnet, um den Clientzugriff auf das Volume oder den Qtree zu konfigurieren. Die SVM kann mehrere Exportregeln enthalten. Dadurch ist Folgendes für SVMs mit mehreren Volumes oder Qtrees möglich:

* Jedem Volume oder Qtree der SVM können unterschiedliche Exportrichtlinien zugewiesen werden, sodass die Zugriffskontrolle für einzelne Clients auf jedes Volume oder jeden Qtree in der SVM individuell erfolgt.
* Dieselbe Exportregel kann mehreren Volumes oder Qtrees der SVM zugewiesen werden, sodass identische Clientzugriffskontrolle möglich ist, ohne für jedes Volume oder jeden Qtree eine neue Exportregel erstellen zu müssen.


Wenn ein Client eine Zugriffsanfrage stellt, die durch die geltende Exportregel nicht zulässig ist, schlägt die Anfrage mit einer Permission-denied-Meldung fehl. Wenn ein Client keiner Regel in der Exportregel entspricht, wird der Zugriff verweigert. Ist eine Exportregel leer, werden alle Zugriffe implizit verweigert.

Eine Exportregel kann auf einem System mit ONTAP dynamisch geändert werden.
