---
permalink: nfs-admin/how-name-mappings-used-concept.html 
sidebar: sidebar 
keywords: configure, name, mapping 
summary: ONTAP verwendet Namenszuordnung, um SMB-Identitäten UNIX-Identitäten, Kerberos-Identitäten UNIX-Identitäten und UNIX-Identitäten SMB-Identitäten zuzuordnen. Diese Informationen werden benötigt, um Benutzeranmeldeinformationen zu erhalten und den korrekten Dateizugriff bereitzustellen, unabhängig davon, ob die Verbindung von einem NFS-Client oder einem SMB-Client erfolgt. 
---
= Informationen zur Namenszuordnungskonfiguration für ONTAP NAS SVMs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP verwendet Namenszuordnung, um SMB-Identitäten UNIX-Identitäten, Kerberos-Identitäten UNIX-Identitäten und UNIX-Identitäten SMB-Identitäten zuzuordnen. Diese Informationen werden benötigt, um Benutzeranmeldeinformationen zu erhalten und den korrekten Dateizugriff bereitzustellen, unabhängig davon, ob die Verbindung von einem NFS-Client oder einem SMB-Client erfolgt.

Es gibt zwei Ausnahmen, bei denen Sie keine Namenszuordnung verwenden müssen:

* Sie konfigurieren eine reine UNIX-Umgebung und planen nicht, SMB-Zugriff oder den NTFS-Sicherheitsstil auf Volumes zu verwenden.
* Stattdessen wird der Standardbenutzer konfiguriert.
+
In diesem Szenario ist keine Namenszuordnung erforderlich, da statt der Zuordnung jeder einzelnen Client-Anmeldeinformation alle Client-Anmeldeinformationen demselben Standardbenutzer zugeordnet werden.



Beachten Sie, dass die Namenszuordnung nur für Benutzer und nicht für Gruppen verwendet werden kann.

Sie können jedoch eine Gruppe einzelner Benutzer einem bestimmten Benutzer zuordnen. Beispielsweise können alle AD-Benutzer, deren Name mit dem Wort SALES beginnt oder endet, einem bestimmten UNIX-Benutzer und der Benutzer-UID dieses Benutzers zugeordnet werden.
