---
permalink: nfs-admin/ldap-signing-sealing-concept.html 
sidebar: sidebar 
keywords: ldap, sign, seal, concept 
summary: Ab ONTAP 9 können Sie die Signierung und Versiegelung konfigurieren, um die LDAP-Sitzungssicherheit bei Abfragen an einen Active Directory-Server zu aktivieren. Sie müssen die NFS-Server-Sicherheitseinstellungen auf der Storage Virtual Machine so konfigurieren, dass sie mit denen des LDAP-Servers übereinstimmen. 
---
= Informationen zur LDAP-Signierung und -Versiegelung für ONTAP NFS SVMs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9 können Sie die Signierung und Versiegelung konfigurieren, um die LDAP-Sitzungssicherheit bei Abfragen an einen Active Directory (AD)-Server zu aktivieren. Die NFS-Server-Sicherheitseinstellungen auf der Storage Virtual Machine (SVM) müssen so konfiguriert werden, dass sie mit denen des LDAP-Servers übereinstimmen.

Signieren bestätigt die Integrität der LDAP-Nutzlastdaten mithilfe einer geheimen Schlüsseltechnologie. Versiegeln verschlüsselt die LDAP-Nutzlastdaten, um die Übertragung sensibler Informationen im Klartext zu vermeiden. Eine Option für den _LDAP Security Level_ gibt an, ob der LDAP-Datenverkehr signiert, signiert und versiegelt oder keines von beidem sein muss. Der Standardwert ist `none`. test

Die LDAP-Signierung und -Versiegelung des SMB-Datenverkehrs ist auf der SVM mit der  `-session-security-for-ad-ldap` Option zum  `vserver cifs security modify` Befehl aktiviert.
