---
permalink: nfs-admin/limits-local-unix-users-groups--concept.html 
sidebar: sidebar 
keywords: limit, local, unix, user, group, member 
summary: ONTAP führte Beschränkungen für die maximale Anzahl von UNIX-Benutzern und UNIX-Gruppen im Cluster sowie Befehle zur Verwaltung dieser Beschränkungen ein. Diese Beschränkungen können dazu beitragen, Leistungsprobleme zu vermeiden, indem sie verhindern, dass Administratoren zu viele lokale UNIX-Benutzer und UNIX-Gruppen im Cluster erstellen. 
---
= Grenzwerte für lokale UNIX-Benutzer, Gruppen und Gruppenmitglieder für ONTAP NFS SVMs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP führte Beschränkungen für die maximale Anzahl von UNIX-Benutzern und UNIX-Gruppen im Cluster sowie Befehle zur Verwaltung dieser Beschränkungen ein. Diese Beschränkungen können dazu beitragen, Leistungsprobleme zu vermeiden, indem sie verhindern, dass Administratoren zu viele lokale UNIX-Benutzer und UNIX-Gruppen im Cluster erstellen.

Die Gesamtzahl lokaler UNIX-Benutzergruppen und ihrer Mitglieder ist begrenzt. Für lokale UNIX-Benutzer gilt eine separate Begrenzung. Die Begrenzungen gelten clusterweit. Jede dieser neuen Begrenzungen ist auf einen Standardwert festgelegt, der bis zu einem vordefinierten endgültigen Limit angepasst werden kann.

[cols="3*"]
|===
| Datenbank | Standardlimit | endgültiges Limit 


 a| 
Lokale UNIX-Benutzer
 a| 
32.768
 a| 
65.536



 a| 
Lokale UNIX-Gruppen und Gruppenmitglieder
 a| 
32.768
 a| 
65.536

|===