---
permalink: nfs-admin/limitations-support-nfsv4-concept.html 
sidebar: sidebar 
keywords: limitation, ontap, support, nfsv4 
summary: Es gibt einige Einschränkungen bei der ONTAP Unterstützung für NFSv4. 
---
= Informationen zu den ONTAP-Unterstützungsbeschränkungen für NFSv4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es gibt einige Einschränkungen bei der ONTAP Unterstützung für NFSv4.

* Die Delegierungsfunktion wird nicht von allen Clienttypen unterstützt.
* In ONTAP 9.4 und früheren Versionen werden Namen mit Nicht-ASCII-Zeichen auf anderen Volumes als UTF8-Volumes vom Speichersystem abgelehnt.
+
In ONTAP 9.5 und späteren Versionen unterliegen Volumes, die mit der Spracheinstellung utf8mb4 erstellt und mit NFS v4 gemountet wurden, dieser Einschränkung nicht mehr.

* Alle Dateihandles sind persistent; der Server vergibt keine flüchtigen Dateihandles.
* Migration und Replikation werden nicht unterstützt.
* NFSv4-Clients werden mit schreibgeschützten Load-Sharing-Mirroring-Servern nicht unterstützt.
+
ONTAP leitet NFSv4-Clients zur Quelle des Load-Sharing Mirror weiter, um direkten Lese- und Schreibzugriff zu ermöglichen.

* Benannte Attribute werden nicht unterstützt.
* Alle empfohlenen Attribute werden unterstützt, mit Ausnahme der folgenden:
+
** `archive`
** `hidden`
** `homogeneous`
** `mimetype`
** `quota_avail_hard`
** `quota_avail_soft`
** `quota_used`
** `system`
** `time_backup`
+

NOTE: Obwohl es die  `quota*`Attribute nicht unterstützt, unterstützt ONTAP Benutzer- und Gruppenquoten über das RQUOTA Sideband-Protokoll.




