---
permalink: nfs-admin/manage-nfsv4-storepool-controls-task.html 
sidebar: sidebar 
keywords: enable, disable, nfsv4, storepool, controls, limit, client, resource, blocked 
summary: Ab ONTAP 9.13 können Administratoren ihre NFS-Server so konfigurieren, dass sie NFS-Clients Ressourcen verweigern, sobald sie die Ressourcengrenzen des jeweiligen Storepools erreicht haben. 
---
= ONTAP NFSv4 Storepool-Limits verwalten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.13 können Administratoren ihre NFSv4 Server so konfigurieren, dass sie NFSv4 Clients Ressourcen verweigern, sobald die Ressourcenlimits des jeweiligen Storepool erreicht sind. Wenn Clients zu viele NFSv4 Storepool-Ressourcen verbrauchen, kann dies dazu führen, dass andere NFSv4 Clients aufgrund fehlender NFSv4 Storepool-Ressourcen blockiert werden.

Durch Aktivierung dieser Funktion können Kunden außerdem den aktiven storepool-Ressourcenverbrauch jedes einzelnen Clients einsehen. Dies erleichtert die Identifizierung von Clients, die Systemressourcen erschöpfen, und macht es möglich, Ressourcenlimits pro Client festzulegen.



[[view-storepool-resources-consumed]]
== Verbrauchte Storepool-Ressourcen anzeigen

Der  `vserver nfs storepool show` Befehl zeigt die Anzahl der verbrauchten Storepool-Ressourcen an. Ein Storepool ist ein Pool von Ressourcen, der von NFSv4-Clients verwendet wird.

.Schritt
. Als Administrator kann der  `vserver nfs storepool show` Befehl ausgeführt werden, um die Storepool-Informationen der NFSv4-Clients anzuzeigen.


.Beispiel
Dieses Beispiel zeigt die Speicherpoolinformationen von NFSv4-Clients an.

[listing]
----
cluster1::*> vserver nfs storepool show

Node: node1

Vserver: vs1

Data-Ip: 10.0.1.1

Client-Ip Protocol IsTrunked OwnerCount OpenCount DelegCount LockCount

-------------- --------- --------- ---------- ---------- ---------- ---------

10.0.2.1          nfs4.1     true    2 1 0 4

10.0.2.2          nfs4.2     true    2 1 0 4

2 entries were displayed.
----


[[enable-or-disable-storepool-limit-controls]]
== Aktivieren oder Deaktivieren der Storepool-Limitsteuerung

Administratoren können die folgenden Befehle verwenden, um die Speicherpool-Limitsteuerung zu aktivieren oder zu deaktivieren.

.Schritt
. Als Administrator kann eine der folgenden Aktionen ausgeführt werden:
+
[cols="2*"]
|===
| Wenn Sie möchten... | Führen Sie den folgenden Befehl aus... 


 a| 
Steuerungen für Speicherpool-Limits aktivieren
 a| 
`vserver nfs storepool config modify -limit-enforce enabled`



 a| 
Steuerung für Speicherpool-Limits deaktivieren
 a| 
`vserver nfs storepool config modify -limit-enforce disabled`

|===




[[view-a-list-of-blocked-clients]]
== Liste blockierter Clients

Wenn die Speicherpoolbegrenzung aktiviert ist, können Administratoren sehen, welche Clients blockiert wurden, sobald sie ihren Ressourcenschwellenwert pro Client erreicht haben. Administratoren können den folgenden Befehl verwenden, um zu sehen, welche Clients als blockierte Clients markiert wurden.

.Schritte
. Mit dem  `vserver nfs storepool blocked-client show` Befehl wird die Liste der blockierten NFSv4-Clients angezeigt.




[[remove-a-client-from-the-blocked-client-list]]
== Einen Client aus der Liste der blockierten Clients entfernen

Clients, die ihr Client-Limit erreichen, werden getrennt und dem Block-Client-Cache hinzugefügt. Administratoren können den folgenden Befehl verwenden, um den Client aus dem Block-Client-Cache zu entfernen. Dadurch kann der Client eine Verbindung zum ONTAP NFSV4 Server herstellen.

.Schritte
. Mit dem  `vserver nfs storepool blocked-client flush -client-ip <ip address>` Befehl lässt sich der blockierte Client-Cache des Storepools leeren.
. Mit dem  `vserver nfs storepool blocked-client show` Befehl lässt sich überprüfen, ob der Client aus dem Block Client Cache entfernt wurde.


.Beispiel
Dieses Beispiel zeigt einen blockierten Client mit der IP-Adresse "10.2.1.1", der von allen Knoten entfernt wird.

[listing]
----
cluster1::*>vserver nfs storepool blocked-client flush -client-ip 10.2.1.1

cluster1::*>vserver nfs storepool blocked-client show

Node: node1

Client IP
----------
10.1.1.1

1 entries were displayed.
----