---
permalink: nfs-admin/modify-credential-cache-time-to-live-reference.html 
sidebar: sidebar 
keywords: reason, modify, nfs, credential, cache, time, live 
summary: Es gibt verschiedene Szenarien, in denen die Änderung der Gültigkeitsdauer des NFS-Anmeldeinformationscaches zur Problemlösung beitragen kann. Es ist wichtig, diese Szenarien sowie die Konsequenzen solcher Änderungen zu kennen. 
---
= Gründe für die Änderung der Gültigkeitsdauer des NFS-Anmeldeinformationscache für ONTAP SVMs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP verwendet einen Berechtigungs-Cache, um die für die Benutzerauthentifizierung beim Zugriff auf NFS-Exporte benötigten Informationen zu speichern, um einen schnelleren Zugriff und eine bessere Performance zu ermöglichen. Die Dauer der Speicherung der Informationen im Berechtigungs-Cache kann konfiguriert werden, um sie an die jeweilige Umgebung anzupassen.

Es gibt verschiedene Szenarien, in denen die Änderung der Time-to-Live (TTL) des NFS-Credential-Cache zur Problemlösung beitragen kann. Es ist wichtig, diese Szenarien sowie die Konsequenzen solcher Änderungen zu kennen.



[[reasons]]
== Gründe

Eine Änderung der Standard-TTL ist unter folgenden Umständen in Betracht zu ziehen:

[cols="2*"]
|===
| Problem | Abhilfemaßnahme 


 a| 
Die Nameserver in Ihrer Umgebung verzeichnen eine Leistungseinbuße aufgrund einer hohen Anzahl von Anfragen von ONTAP.
 a| 
Die Gültigkeitsdauer (TTL) für zwischengespeicherte positive und negative Anmeldeinformationen kann erhöht werden, wodurch die Anzahl der Anfragen von ONTAP an die Nameserver verringert wird.



 a| 
Der Name-Server-Administrator nahm Änderungen vor, um NFS-Benutzern, denen zuvor der Zugriff verweigert wurde, den Zugriff zu ermöglichen.
 a| 
Die TTL für zwischengespeicherte negative Anmeldeinformationen kann verringert werden, um die Zeit zu verkürzen, die NFS-Benutzer warten müssen, bis ONTAP neue Anmeldeinformationen von externen Nameservern anfordert, damit sie Zugriff erhalten.



 a| 
Der Name-Server-Administrator hat Änderungen vorgenommen, um NFS-Benutzern, denen zuvor der Zugriff erlaubt war, den Zugriff zu verweigern.
 a| 
Die Gültigkeitsdauer (TTL) für zwischengespeicherte positive Anmeldeinformationen wird reduziert, wodurch sich die Zeit verkürzt, bevor ONTAP neue Anmeldeinformationen von externen Nameservern anfordert, sodass NFS-Benutzern nun der Zugriff verweigert wird.

|===


[[consequences]]
== Konsequenzen

Sie können die Speicherdauer für positive und negative Anmeldeinformationen individuell anpassen. Allerdings sollten sowohl die Vorteile als auch die Nachteile dieser Vorgehensweise berücksichtigt werden.

[cols="3*"]
|===
| Wenn Sie... | Der Vorteil ist... | Der Nachteil ist... 


 a| 
Die Zeit für den positiven Anmeldeinformationscache erhöhen
 a| 
ONTAP sendet Anfragen nach Anmeldeinformationen seltener an die Name-Server, was die Last auf die Name-Server verringert.
 a| 
Es dauert länger, NFS-Benutzern den Zugriff zu verweigern, denen dieser zuvor erlaubt war, jetzt aber nicht mehr.



 a| 
Die Zeit für den positiven Anmeldeinformationscache verringern
 a| 
Es dauert weniger lang, NFS-Benutzern den Zugriff zu verweigern, denen dieser zuvor erlaubt war, jetzt aber nicht mehr.
 a| 
ONTAP sendet Anfragen nach Anmeldeinformationen häufiger an die Name-Server, was die Last auf die Name-Server erhöht.



 a| 
Die Cache-Zeit für negative Anmeldeinformationen erhöhen
 a| 
ONTAP sendet Anfragen nach Anmeldeinformationen seltener an die Name-Server, was die Last auf die Name-Server verringert.
 a| 
Es dauert länger, NFS-Benutzern Zugriff zu gewähren, die zuvor keinen Zugriff hatten, nun aber Zugriff erhalten.



 a| 
Die Zeit für den negativen Anmeldeinformationscache verringern
 a| 
Es nimmt weniger Zeit in Anspruch, NFS-Benutzern Zugriff zu gewähren, denen zuvor kein Zugriff erlaubt war, die nun aber Zugriff erhalten.
 a| 
ONTAP sendet Anfragen nach Anmeldeinformationen häufiger an die Name-Server, was die Last auf die Name-Server erhöht.

|===