---
permalink: nfs-admin/modify-ports-used-nfsv3-services-task.html 
sidebar: sidebar 
keywords: modify, port, nfsv3, service 
summary: Der NFS-Server des Speichersystems nutzt Dienste wie mount daemon und Network Lock Manager, um über bestimmte Standard-Netzwerkports mit NFS-Clients zu kommunizieren. In den meisten NFS-Umgebungen funktionieren die Standard-Netzwerkports korrekt und müssen nicht geändert werden, aber wenn in Ihrer NFSv3-Umgebung andere NFS-Netzwerkports verwendet werden sollen, ist dies möglich. 
---
= Ändern der für NFSv3-Services verwendeten Ports für ONTAP SVMs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der NFS-Server des Speichersystems nutzt Dienste wie mount daemon und Network Lock Manager, um über bestimmte Standard-Netzwerkports mit NFS-Clients zu kommunizieren. In den meisten NFS-Umgebungen funktionieren die Standard-Netzwerkports korrekt und müssen nicht geändert werden, aber wenn in Ihrer NFSv3-Umgebung andere NFS-Netzwerkports verwendet werden sollen, ist dies möglich.

.Bevor Sie beginnen
Das Ändern der NFS-Ports auf dem Speichersystem erfordert, dass alle NFS-Clients die Verbindung zum System erneut herstellen. Es empfiehlt sich, diese Information den Benutzern im Voraus mitzuteilen.

.Über diese Aufgabe
Sie können die Ports festlegen, die vom NFS-Mount-Daemon, dem Network Lock Manager, dem Network Status Monitor und dem NFS-Quota-Daemon-Dienst für jede Storage Virtual Machine (SVM) verwendet werden. Die Änderung der Portnummer wirkt sich auf NAS-Clients aus, die über TCP und UDP auf Daten zugreifen.

Die Ports für NFSv4 und NFSv4.1 können nicht geändert werden.

.Schritte
. Stellen Sie die Berechtigungsstufe auf „Erweitert“ ein:
+
`set -privilege advanced`

. Zugriff auf NFS deaktivieren:
+
`vserver nfs modify -vserver vserver_name -access false`

. Den NFS-Port für den jeweiligen NFS-Service festlegen:
+
`vserver nfs modify -vserver vserver_namenfs_port_parameterport_number`

+
[cols="3*"]
|===
| NFS-Portparameter | Beschreibung | Standardport 


 a| 
`-mountd-port`
 a| 
NFS Mount-Daemon
 a| 
635



 a| 
`-nlm-port`
 a| 
Network Lock Manager
 a| 
4045



 a| 
`-nsm-port`
 a| 
Network Status Monitor
 a| 
4046



 a| 
`-rquotad-port`
 a| 
NFS Quota-Daemon
 a| 
4049

|===
+
Neben dem Standardport ist der zulässige Portbereich 1024 bis 65535. Jeder NFS-Service muss einen eindeutigen Port verwenden.

. Zugriff auf NFS aktivieren:
+
`vserver nfs modify -vserver vserver_name -access true`

. Mit dem  `network connections listening show`Befehl lässt sich überprüfen, ob sich die Portnummer geändert hat.
+
Weitere Informationen zu  `network connections listening show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-connections-listening-show.html["ONTAP-Befehlsreferenz"^].

. Zurück zur Administrator-Privilegstufe:
+
`set -privilege admin`



.Beispiel
Die folgenden Befehle legen den NFS-Mount-Daemon-Port auf 1113 auf der SVM mit dem Namen vs1 fest:

....
vs1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use
         them only when directed to do so by NetApp personnel.
Do you want to continue? {y|n}: y

vs1::*> vserver nfs modify -vserver vs1 -access false

vs1::*> vserver nfs modify -vserver vs1 -mountd-port 1113

vs1::*> vserver nfs modify -vserver vs1 -access true

vs1::*> network connections listening show
Vserver Name     Interface Name:Local Port        Protocol/Service
---------------- -------------------------------  ----------------
Node: cluster1-01
Cluster          cluster1-01_clus_1:7700          TCP/ctlopcp
vs1              data1:4046                       TCP/sm
vs1              data1:4046                       UDP/sm
vs1              data1:4045                       TCP/nlm-v4
vs1              data1:4045                       UDP/nlm-v4
vs1              data1:1113                       TCP/mount
vs1              data1:1113                       UDP/mount
...
vs1::*> set -privilege admin
....