---
permalink: nfs-admin/nfs-client-authentication-concept.html 
sidebar: sidebar 
keywords: ontap, nfs, client, authentication 
summary: NFS-Clients müssen ordnungsgemäß authentifiziert werden, bevor sie auf Daten auf der SVM zugreifen können. ONTAP authentifiziert die Clients, indem ihre UNIX-Anmeldeinformationen auf die von Ihnen konfigurierten Namensdienste überprüft werden. 
---
= Erfahren Sie mehr über die ONTAP-Authentifizierung für NAS-Clients
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS-Clients müssen ordnungsgemäß authentifiziert werden, bevor sie auf Daten auf der SVM zugreifen können. ONTAP authentifiziert die Clients, indem ihre UNIX-Anmeldeinformationen auf die von Ihnen konfigurierten Namensdienste überprüft werden.

Wenn ein NFS-Client eine Verbindung zur SVM herstellt, erhält ONTAP die UNIX-Anmeldedaten für den Benutzer, indem er abhängig von der Name-Services-Konfiguration der SVM andere Name-Services überprüft. ONTAP kann die Anmeldedaten für lokale UNIX Accounts, NIS-Domänen und LDAP-Domänen prüfen. Mindestens einer von ihnen muss so konfiguriert werden, dass ONTAP den Benutzer erfolgreich authentifizieren kann. Sie können mehrere Namensdienste und die Reihenfolge angeben, in der ONTAP sie durchsucht.

In einer reinen NFS-Umgebung mit UNIX-Volume-Sicherheitsstil genügt diese Konfiguration zur Authentifizierung und Bereitstellung des richtigen Dateizugriffs für einen Benutzer, der sich von einem NFS-Client aus verbinden lässt.

Bei Verwendung von Sicherheitsstilen für gemischte, NTFS- oder einheitliche Volumes muss ONTAP einen SMB-Benutzernamen für den UNIX-Benutzer zur Authentifizierung mit einem Windows Domain Controller erhalten. Dies kann entweder durch die Zuordnung einzelner Benutzer mithilfe lokaler UNIX-Konten oder LDAP-Domänen oder durch die Verwendung eines standardmäßigen SMB-Benutzers erfolgen. Sie können festlegen, nach welchen Namens-Services ONTAP in welcher Reihenfolge gesucht wird, oder einen standardmäßigen SMB-Benutzer angeben.
