---
permalink: nfs-admin/nfsv4-referrals-concept.html 
sidebar: sidebar 
keywords: nfsv4, referral, work 
summary: Wenn Sie NFSv4-Weiterleitungen aktivieren, stellt ONTAP Intra-SVM-Weiterleitungen für NFSv4-Clients bereit. Eine Intra-SVM-Weiterleitung bedeutet, dass ein Clusterknoten, der die NFSv4-Anfrage empfängt, den NFSv4-Client an eine andere logische Schnittstelle auf der Storage Virtual Machine verweist. 
---
= Informationen zu NFSv4-Verweisen für ONTAP SVMs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn NFSv4-Weiterleitungen aktiviert sind, stellt ONTAP „Intra-SVM“-Weiterleitungen für NFSv4-Clients bereit. Eine Intra-SVM-Weiterleitung liegt vor, wenn ein Cluster-Knoten, der die NFSv4-Anfrage empfängt, den NFSv4-Client an eine andere logische Schnittstelle (LIF) auf der Storage Virtual Machine (SVM) verweist.

Der NFSv4-Client sollte ab diesem Zeitpunkt auf den Pfad zugreifen, der die Weiterleitung am Ziel-LIF erhalten hat. Der ursprüngliche Cluster-Node stellt eine solche Weiterleitung bereit, wenn festgestellt wird, dass im SVM ein LIF existiert, das auf dem Cluster-Node residiert, auf dem sich das Daten-Volume befindet. Dadurch wird den Clients ein schnellerer Zugriff auf die Daten ermöglicht und zusätzliche Cluster-Kommunikation vermieden.
