---
permalink: nfs-admin/ontap-export-policy-caches-concept.html 
sidebar: sidebar 
keywords: ontap, use, export, policy, cache 
summary: Um die Systemleistung zu verbessern, verwendet ONTAP lokale Caches zum Speichern von Informationen wie Hostnamen und Netzgruppen. Dadurch kann ONTAP Exportrichtlinienregeln schneller verarbeiten, als wenn die Informationen von externen Quellen abgerufen würden. Das Verständnis, was die Caches sind und was sie tun, kann bei der Fehlerbehebung von Clientzugriffsproblemen helfen. 
---
= Informationen zu ONTAP NFS Export-Policy-Caches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um die Systemleistung zu verbessern, verwendet ONTAP lokale Caches zum Speichern von Informationen wie Hostnamen und Netzgruppen. Dadurch kann ONTAP Exportrichtlinienregeln schneller verarbeiten, als wenn die Informationen von externen Quellen abgerufen würden. Das Verständnis, was die Caches sind und was sie tun, kann bei der Fehlerbehebung von Clientzugriffsproblemen helfen.

Sie konfigurieren Exportrichtlinien, um den Clientzugriff auf NFS-Exporte zu steuern. Jede Exportrichtlinie enthält Regeln, und jede Regel enthält Parameter, um die Regel mit den Clients abzugleichen, die Zugriff anfordern. Einige dieser Parameter erfordern, dass ONTAP eine externe Quelle wie DNS- oder NIS-Server kontaktiert, um Objekte wie Domänennamen, Hostnamen oder Netzgruppen aufzulösen.

Diese Kommunikation mit externen Quellen benötigt nur wenig Zeit. Zur Steigerung der Performance verkürzt ONTAP die Zeit, die für die Auflösung von Exportrichtlinienregelobjekten benötigt wird, indem Informationen lokal auf jedem Node in mehreren Caches gespeichert werden.

[cols="2*"]
|===
| Cache Name | Art der gespeicherten Informationen 


 a| 
Zugang
 a| 
Zuordnungen von Clients zu entsprechenden Exportrichtlinien



 a| 
Name
 a| 
Zuordnung von UNIX-Benutzernamen zu entsprechenden UNIX-Benutzer-IDs



 a| 
ID
 a| 
Zuordnungen von UNIX-Benutzerkennungen zu entsprechenden UNIX-Benutzerkennungen und erweiterten UNIX-Gruppenkennungen



 a| 
Host
 a| 
Zuordnung von Hostnamen zu entsprechenden IP-Adressen



 a| 
Netgroup
 a| 
Zuordnungen von Netzgruppen zu den entsprechenden IP-Adressen der Mitglieder



 a| 
Showmount
 a| 
Liste der aus dem SVM-Namensraum exportierten Verzeichnisse

|===
Wenn Sie die Informationen auf den externen Name Servern in Ihrer Umgebung ändern, nachdem ONTAP diese abgerufen und lokal gespeichert hat, könnten die Caches nun veraltete Informationen enthalten. Obwohl ONTAP die Caches nach bestimmten Zeiträumen automatisch aktualisiert, haben die verschiedenen Caches unterschiedliche Ablauf- und Aktualisierungszeiten sowie Algorithmen.

Ein weiterer möglicher Grund für veraltete Cache-Informationen ist, wenn ONTAP versucht, zwischengespeicherte Informationen zu aktualisieren, dabei jedoch bei der Kommunikation mit den Nameservern ein Fehler auftritt. Tritt dies auf, verwendet ONTAP weiterhin die aktuell im lokalen Cache gespeicherten Informationen, um Störungen für die Clients zu vermeiden.

Daher kann es vorkommen, dass Clientzugriffsanfragen, die erfolgreich sein sollten, fehlschlagen, und Clientzugriffsanfragen, die fehlschlagen sollten, erfolgreich sind. Einige der Export-Policy-Caches können bei der Fehlerbehebung solcher Clientzugriffsprobleme eingesehen und manuell geleert werden.
