---
permalink: nfs-admin/ontap-differs-windows-locks-share-path-concept.html 
sidebar: sidebar 
keywords: ontap, windows, handle, locks, share, path, component 
summary: Im Gegensatz zu Windows sperrt ONTAP nicht die einzelnen Komponenten des Pfades zu einer geöffneten Datei, solange die Datei geöffnet ist. Dieses Verhalten betrifft auch SMB-Freigabepfade. 
---
= Unterschiede zwischen ONTAP NFS und Windows bei der Handhabung von Sperren auf Freigabepfadkomponenten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Gegensatz zu Windows sperrt ONTAP nicht die einzelnen Komponenten des Pfades zu einer geöffneten Datei, solange die Datei geöffnet ist. Dieses Verhalten betrifft auch SMB-Freigabepfade.

Da ONTAP die einzelnen Pfadkomponenten nicht sperrt, ist es möglich, eine Pfadkomponente oberhalb der geöffneten Datei oder Freigabe umzubenennen, was bei bestimmten Anwendungen zu Problemen führen oder den Freigabepfad in der SMB-Konfiguration ungültig machen kann. Dies kann dazu führen, dass die Freigabe nicht zugänglich ist.

Um Probleme zu vermeiden, die durch das Umbenennen von Pfadkomponenten entstehen, lassen sich Sicherheitseinstellungen der Windows Access Control List (ACL) anwenden, die verhindern, dass Benutzer oder Anwendungen kritische Verzeichnisse umbenennen.

Weitere Informationen zu link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_prevent_directories_from_being_renamed_while_clients_are_accessing_them["Wie verhindert werden kann, dass Verzeichnisse umbenannt werden, während Clients darauf zugreifen"^].
