---
permalink: nfs-admin/ontap-support-nfsv42-concept.html 
sidebar: sidebar 
keywords: ontap, support, nfsv4.2 
summary: Ab ONTAP 9.8 wird das NFSv4.2 Protokoll unterstützt, um den Zugriff für NFSv4.2 Clients zu ermöglichen. 
---
= ONTAP unterstützt NFSv4.2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.8 wird das NFSv4.2 Protokoll unterstützt, um den Zugriff für NFSv4.2 Clients zu ermöglichen.

Standardmäßig ist NFSv4.2 in ONTAP 9.9.1 und höher aktiviert. In ONTAP 9.8 können Sie v4.2 aktivieren, indem Sie die angeben `-v4.1` Option und Einstellung auf `enabled` Beim Erstellen eines NFS-Servers auf der Storage Virtual Machine (SVM) Durch die Aktivierung von NFSv4.1 können Clients auch die NFSv4.1 Funktionen verwenden, während sie als v4.2 gemountet werden.

Die folgenden NFSv4.2 optionalen Funktionen werden unterstützt:

* Ab ONTAP 9.9 wird NFS mit der Bezeichnung NFS obligatorischer Zugriffssteuerung (MAC) unterstützt, wenn NFSv4.2 aktiviert ist.
* Weitere NFSv4.2 optionale Funktionen werden später in einer ONTAP Version hinzugefügt.




== Aktivieren Sie die NFS v4.2-Sicherheitsetiketten

Ab ONTAP 9.9 können NFS-Sicherheitslabels aktiviert werden. Sie sind standardmäßig deaktiviert.

Bei NFS v4.2-Sicherheitsetiketten sind ONTAP-NFS-Server der MAC-Adresse (Pflichtzugriff) bewusst und speichern und abrufen von Clients gesendete sec_Label-Attribute.

Weitere Informationen finden Sie unter https://tools.ietf.org/html/rfc7204["RFC7240"]

[NOTE]
====
NFS v4.2-Sicherheitsetiketten werden derzeit nicht für NDMP-Dump-Vorgänge unterstützt. Wenn auf Dateien oder Verzeichnissen Sicherheitsetiketten gefunden werden, schlägt der Dump fehl.

====
.Schritte
. Ändern Sie die Berechtigungseinstellung in erweitert:
+
``set -privilege advanced``

. Sicherheitsetiketten aktivieren:
+
``vserver nfs modify -vserver svm_name -v4.2-seclabel enabled``


