---
permalink: nfs-admin/ontap-name-services-concept.html 
sidebar: sidebar 
keywords: ontap, name, service 
summary: ONTAP bezieht Informationen zu Benutzern und Clients mithilfe von Name Services. ONTAP verwendet diese Informationen, um Benutzer zu authentifizieren, die auf Daten auf dem Storage-System zugreifen, und um Benutzeranmeldeinformationen in einer heterogenen Umgebung zuzuordnen. 
---
= Verwendung von Name Services durch ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP bezieht Informationen zu Benutzern und Clients mithilfe von Name Services. ONTAP verwendet diese Informationen, um Benutzer zu authentifizieren, die auf Daten auf dem Storage-System zugreifen, und um Benutzeranmeldeinformationen in einer heterogenen Umgebung zuzuordnen.

Wenn Sie das Speichersystem konfigurieren, müssen Sie angeben, welche Namensdienste ONTAP zum Abrufen von Benutzeranmeldeinformationen zur Authentifizierung verwenden soll. ONTAP unterstützt folgende Namensdienste:

* Lokale Benutzer (Datei)
* Externe NIS-Domänen (NIS)
* Externe LDAP-Domänen (LDAP)


Sie verwenden die `vserver services name-service ns-switch` Befehlsfamilie, um SVMs mit den Quellen zu konfigurieren, um nach Netzwerkinformationen und der Reihenfolge zu suchen, in der sie durchsucht werden sollen. Diese Befehle bieten die gleiche Funktionalität wie die `/etc/nsswitch.conf` Datei auf UNIX-Systemen.

Wenn ein NFS-Client eine Verbindung zur SVM herstellt, überprüft ONTAP die angegebenen Namensservices, um die UNIX-Anmeldedaten für den Benutzer abzurufen. Wenn Namensdienste richtig konfiguriert sind und ONTAP die UNIX-Anmeldedaten erhalten kann, authentifiziert ONTAP den Benutzer erfolgreich.

In einer Umgebung mit unterschiedlichen Sicherheitsstilen muss ONTAP möglicherweise Benutzeranmeldeinformationen zuordnen. Sie müssen Name-Services entsprechend für Ihre Umgebung konfigurieren, damit ONTAP die Benutzeranmeldeinformationen ordnungsgemäß zuordnen kann.

ONTAP verwendet außerdem Namensdienste für die Authentifizierung von SVM-Administratorkonten. Dies müssen Sie beachten, wenn Sie den Namespace-Switch konfigurieren oder ändern, um zu vermeiden, dass die Authentifizierung für SVM-Administratorkonten versehentlich deaktiviert wird. Weitere Informationen zu Benutzern der SVM-Administration finden Sie unter link:../authentication/index.html["Administratorauthentifizierung und RBAC"].
