---
permalink: nfs-admin/ontap-support-nfsv41-concept.html 
sidebar: sidebar 
keywords: ontap, support, nfsv4.1 
summary: Ab ONTAP 9.8 ist nconnect standardmäßig verfügbar, wenn NFSv4.1 aktiviert ist. 
---
= ONTAP Unterstützung für NFSv4.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.8 ist nconnect standardmäßig verfügbar, wenn NFSv4.1 aktiviert ist.

Bei früheren NFS-Client-Implementierungen wird nur eine einzige TCP-Verbindung mit einem Mount verwendet. Im ONTAP kann eine einzelne TCP-Verbindung zu einem Engpass mit einer höheren IOPS werden. Ein nconnect-fähiger Client kann jedoch mehrere TCP-Verbindungen (bis zu 16) haben, die einem einzelnen NFS-Mount zugeordnet sind. Dieser NFS-Client vergrößert Dateivorgänge auf mehrere TCP-Verbindungen nach Round Robin-Verfahren und erzielt so einen höheren Durchsatz aus der verfügbaren Netzwerkbandbreite. Nconnect wird nur für NFSv3- und NFSv4.1-Mounts empfohlen.

Überprüfen Sie in der Dokumentation des NFS-Clients, ob nconnect in Ihrer Client-Version unterstützt wird.

NFSv4.1 ist standardmäßig in ONTAP 9.9.1 und höher aktiviert. In früheren Versionen können Sie die Aktivierung durch Angabe des aktivieren `-v4.1` Option und Einstellung auf `enabled` Beim Erstellen eines NFS-Servers auf der Storage Virtual Machine (SVM)

ONTAP unterstützt keine Delegationen auf Verzeichnis- und Dateiebene in NFSv4.1.
