---
permalink: nfs-admin/optimize-access-cache-performance-task.html 
sidebar: sidebar 
keywords: optimize, access, cache, performance 
summary: Sie können verschiedene Parameter konfigurieren, um den Zugriffscache zu optimieren und das richtige Gleichgewicht zwischen Leistung und Aktualität der im Zugriffscache gespeicherten Informationen zu finden. 
---
= Optimierung der Zugriffscache-Performance für ONTAP NFS SVMs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können verschiedene Parameter konfigurieren, um den Zugriffscache zu optimieren und das richtige Gleichgewicht zwischen Leistung und Aktualität der im Zugriffscache gespeicherten Informationen zu finden.

.Über diese Aufgabe
Bei der Konfiguration der Aktualisierungsintervalle für den Zugriffscache ist Folgendes zu beachten:

* Höhere Werte bedeuten, dass Einträge länger im Zugriffscache verbleiben.
+
Der Vorteil liegt in der besseren Performance, da ONTAP weniger Ressourcen für die Aktualisierung der Zugriffscache-Einträge aufwendet. Der Nachteil besteht darin, dass es länger dauert, veraltete Zugriffscache-Einträge zu aktualisieren, wenn sich Exportrichtlinienregeln ändern. Dadurch kann es vorkommen, dass Clients, die Zugriff erhalten sollten, abgelehnt werden und Clients, die abgelehnt werden sollten, Zugriff erhalten.

* Niedrigere Werte bedeuten, dass ONTAP die Zugriffscache-Einträge häufiger aktualisiert.
+
Der Vorteil besteht darin, dass die Einträge aktueller sind und Clients mit höherer Wahrscheinlichkeit korrekt Zugriff gewährt oder verweigert wird. Der Nachteil ist eine geringere Leistung, da ONTAP mehr Ressourcen für die Aktualisierung der Zugriffscache-Einträge aufwendet.



.Schritte
. Stellen Sie die Berechtigungsstufe auf „Erweitert“ ein:
+
`set -privilege advanced`

. Die gewünschte Aktion ausführen:
+
[cols="2*"]
|===
| Um die... | Eingeben... 


 a| 
Aktualisierungszeitraum für positive Einträge
 a| 
`vserver export-policy access-cache config modify-all-vservers -refresh-period-positive timeout_value`



 a| 
Aktualisierungszeitraum für negative Einträge
 a| 
`vserver export-policy access-cache config modify-all-vservers -refresh-period-negative timeout_value`



 a| 
Timeout-Zeitraum für alte Einträge
 a| 
`vserver export-policy access-cache config modify-all-vservers -harvest-timeout timeout_value`

|===
. Die neuen Parametereinstellungen werden überprüft:
+
`vserver export-policy access-cache config show-all-vservers`

. Zurück zur Administrator-Privilegstufe:
+
`set -privilege admin`


