---
permalink: nfs-admin/remove-export-policy-qtree-task.html 
sidebar: sidebar 
keywords: remove, export, policy, qtree 
summary: Wenn Sie sich entscheiden, dass einer bestimmten Exportrichtlinie einem qtree nicht mehr zugewiesen wird, können Sie die Exportrichtlinie entfernen, indem Sie den qtree ändern, um die Exportrichtlinie des enthaltenden Volumes stattdessen zu übernehmen. Dazu können Sie den Befehl Volume qtree modify mit dem Parameter -Export-Policy und einem leeren Namespace verwenden. 
---
= Entfernen Sie eine Exportrichtlinie von einem qtree
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie sich entscheiden, dass einer bestimmten Exportrichtlinie einem qtree nicht mehr zugewiesen wird, können Sie die Exportrichtlinie entfernen, indem Sie den qtree ändern, um die Exportrichtlinie des enthaltenden Volumes stattdessen zu übernehmen. Dazu verwenden Sie den `volume qtree modify` Befehl mit dem `-export-policy` Parameter und einen leeren Namensstring ("").

.Schritte
. Geben Sie den folgenden Befehl ein, um eine Exportrichtlinie von einem qtree zu entfernen:
+
`volume qtree modify -vserver vserver_name -qtree-path /vol/volume_name/qtree_name -export-policy ""`

. Vergewissern Sie sich, dass der qtree entsprechend geändert wurde:
+
`volume qtree show -qtree qtree_name -fields export-policy`


