---
permalink: nfs-admin/smb-access-nfs-clients-concept.html 
sidebar: sidebar 
keywords: ontap, grant, smb, file, access, nfs, client 
summary: ONTAP verwendet die Sicherheitssemantik des Windows NT-Dateisystems, um zu ermitteln, ob ein UNIX-Benutzer auf einem NFS-Client Zugriff auf eine Datei mit NTFS-Berechtigungen hat. 
---
= ONTAP SMB Dateizugriff von NFS-Clients ermöglichen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP verwendet die Sicherheitssemantik des Windows NT File System (NTFS), um festzustellen, ob ein UNIX-Benutzer auf einem NFS-Client Zugriff auf eine Datei mit NTFS-Berechtigungen hat.

ONTAP wandelt dazu die UNIX-Benutzerkennung (UID) des Benutzers in eine SMB-Anmeldeinformation um und verwendet anschließend diese SMB-Anmeldeinformation, um zu überprüfen, ob der Benutzer Zugriffsrechte auf die Datei hat. Eine SMB-Anmeldeinformation besteht aus einer primären Sicherheitskennung (SID), üblicherweise dem Windows-Benutzernamen, und einer oder mehreren Gruppen-SIDs, die den Windows-Gruppen entsprechen, denen der Benutzer angehört.

Die Zeit, die ONTAP für die Umwandlung der UNIX-UID in eine SMB-Anmeldeinformation benötigt, kann von einigen Dutzend bis zu mehreren Hundert Millisekunden betragen, da der Prozess die Kontaktaufnahme mit einem Domänencontroller erfordert. ONTAP ordnet die UID der SMB-Anmeldeinformation zu und trägt die Zuordnung in einen Anmeldeinformationscache ein, um die durch die Umwandlung verursachte Überprüfungszeit zu verkürzen.
