---
permalink: nfs-admin/specify-nfsv4-locking-lease-period-task.html 
sidebar: sidebar 
keywords: specify, nfsv4, lock, lease, period 
summary: Um die Sperrdauer für NFSv4 festzulegen, können Sie die Option -v4-lease-seconds anpassen. Kürzere Lease-Zeiträume beschleunigen die Serverwiederherstellung, während längere Lease-Zeiträume für Server mit einer sehr großen Anzahl von Clients vorteilhaft sind. 
---
= Die Sperrfrist für NFSv4-Locking bei ONTAP SVMs angeben
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um den Sperr-Lease-Zeitraum für NFSv4 festzulegen (das heißt, den Zeitraum, in dem ONTAP einem Client unwiderruflich eine Sperre gewährt), kann die  `-v4-lease-seconds` Option angepasst werden. Kürzere Lease-Zeiträume beschleunigen die Serverwiederherstellung, während längere Lease-Zeiträume für Server mit einer sehr großen Anzahl von Clients vorteilhaft sind.

.Über diese Aufgabe
Standardmäßig ist diese Option auf  `30` eingestellt. Der Mindestwert für diese Option ist  `10`. Der Höchstwert für diese Option ist die Sperrfrist, die mit der  `locking.lease_seconds` Option festgelegt werden kann.

.Schritte
. Stellen Sie die Berechtigungsstufe auf „Erweitert“ ein:
+
`set -privilege advanced`

. Führen Sie den folgenden Befehl aus:
+
`vserver nfs modify -vserver vserver_name -v4-lease-seconds number_of_seconds`

. Zurück zur Administrator-Privilegstufe:
+
`set -privilege admin`


