---
permalink: nfs-admin/support-vmware-vstorage-over-nfs-concept.html 
sidebar: sidebar 
keywords: support, vmware, vStorage, nfs 
summary: 'ONTAP unterstützt bestimmte VMware vStorage APIs zur Array Integration (VAAI) Funktionen in einer NFS Umgebung.' 
---
= Support für VMware vStorage via NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP unterstützt bestimmte VMware vStorage APIs zur Array Integration (VAAI) Funktionen in einer NFS Umgebung.



== Unterstützte Funktionen

Folgende Funktionen werden unterstützt:

* Copy-Offload
+
Ermöglicht es einem ESXi Host, Virtual Machines oder Virtual Machine Disks (VMDKs) direkt zwischen dem Quell- und Zielspeicherort zu kopieren, ohne den Host zu involvieren. Dies spart ESXi Host-CPU-Zyklen und Netzwerkbandbreite. Der Copy-Offload behält die Platzeffizienz bei, wenn das Quell-Volume nur wenige Ressourcen beansprucht.

* Speicherplatzreservierung
+
Garantiert Speicherplatz für eine VMDK-Datei, indem Speicherplatz dafür reserviert wird.





== Einschränkungen

VMware vStorage via NFS weist folgende Einschränkungen auf:

* Offload-Vorgänge für Kopien können in den folgenden Szenarien fehlschlagen:
+
** Während der Ausführung von Wafliron auf dem Quell- oder Ziel-Volume, da es das Volume vorübergehend offline nimmt
** Während Sie das Quell- oder Ziel-Volume verschieben
** Während Sie die Quell- oder Ziel-LIF verschieben
** Während der Durchführung von Takeover- oder Giveback-Vorgängen
** Während Switchover- oder Switchback-Vorgänge durchgeführt werden


* Serverseitige Kopien können aufgrund von Formatunterschieden bei Datei-Handle im folgenden Szenario fehlschlagen:
+
Sie versuchen, Daten von SVMs zu kopieren, die derzeit oder zuvor qtrees in SVMs exportiert hatten, die in noch nie qtrees exportiert hatten. Um diese Einschränkung zu umgehen, können Sie mindestens einen qtree auf der Ziel-SVM exportieren.



https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/What_VAAI_offloaded_operations_are_supported_by_Data_ONTAP%3F["Welche VAAI Offloaded Operationen werden von Data ONTAP unterstützt?"]
