---
sidebar: sidebar 
permalink: anti-ransomware/modify-snapshot-options-arpai.html 
keywords: ARP AI, arpai, snapshot settings, retention, arw snap, autonomous ransomware protection AI, ONTAP 9.17.1, SAN snapshot parameters, machine learning ransomware 
summary: Die Erstellungs- und Aufbewahrungseinstellungen für ARP/AI Snapshots, die automatisch als Reaktion auf potenzielle Ransomware-Bedrohungen generiert werden, können angepasst werden. 
---
= Einstellungen für automatisch generierte ONTAP ARP/AI Snapshots anpassen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.16.1 kann über die CLI die Aufbewahrungseinstellung für Autonomous Ransomware Protection with AI (ARP/AI) Snapshots gesteuert werden, die automatisch als Reaktion auf vermutete Ransomware-Angriffe generiert werden.


NOTE: Wenn Sie ONTAP 9.15.1 oder eine frühere Version verwenden, siehe link:modify-snapshot-options-arp.html["Einstellungen für automatisch generierte ARP Snapshots anpassen"].

.Bevor Sie beginnen
Die ARP/AI-Snapshot-Optionen können nur auf einer link:../system-admin/types-svms-concept.html["Node SVM"] und nicht auf anderen SVM-Typen geändert werden.

.Schritte
. Alle aktuellen ARP/AI Snapshot-Einstellungen anzeigen:
+
[source, cli]
----
options -option-name arw*
----
. Ausgewählte aktuelle ARP/AI Snapshot-Einstellungen:
+
[source, cli]
----
options -option-name <arw_setting_name>
----
. ARP/AI Snapshot-Einstellungen ändern:
+
[source, cli]
----
options -option-name <arw_setting_name> -option-value <arw_setting_value>
----
+
Die folgenden Einstellungen lassen sich ändern (ONTAP 9.16.1 und höher):

+
[cols="1,3,1"]
|===
| Einstellung | Beschreibung | Unterstützte Versionen mit ARP/AI 


| `arw.snap.max.count`  a| 
Legt die maximale Anzahl von ARP/AI-Snapshots fest, die zu einem bestimmten Zeitpunkt in einem Volume vorhanden sein können. Ältere Kopien werden gelöscht, um sicherzustellen, dass die Gesamtzahl der ARP/AI-Snapshots innerhalb dieses Grenzwerts bleibt.
 a| 
ONTAP 9.16.1 und höher



| `arw.snap.create.interval.hours`  a| 
Gibt das Intervall _in Stunden_ zwischen ARP/AI Snapshots an. Ein neuer ARP/AI Snapshot wird erstellt, wenn ein datenentropiebasierter Angriff vermutet wird und der zuletzt erstellte Snapshot älter als das angegebene Intervall ist.
 a| 
ONTAP 9.16.1 und höher



| `arw.snap.normal.retain.interval.hours`  a| 
Gibt die Dauer _in Stunden_ an, für die ein ARP/AI Snapshot aufbewahrt wird. Wenn ein ARP/AI Snapshot den Aufbewahrungsschwellenwert erreicht, wird er gelöscht.
 a| 
ONTAP 9.16.1 (deprecated in 9.17.1 und höher)



| `arw.snap.max.retain.interval.days`  a| 
Gibt die maximale Aufbewahrungsdauer _in Tagen_ eines ARP/AI-Snapshots an. Alle ARP/AI-Snapshots, die älter als diese Dauer sind, werden gelöscht, wenn kein Angriff auf das Volume gemeldet wird.


NOTE: Das maximale Aufbewahrungsintervall wird ignoriert, wenn ARP/AI eine Bedrohung erkennt. Der als Reaktion auf die Bedrohung erstellte ARP/AI-Snapshot wird so lange aufbewahrt, bis Sie auf die Bedrohung reagieren. Wenn Sie eine Bedrohung als Fehlalarm markieren, wird der durch  `arw.snap.retain.hours.after.clear.suspect.false.alert` festgelegte Aufbewahrungstimer auf die ARP/AI-Snapshots angewendet. Nach Ablauf dieses Timers gelten wieder die Standardeinstellungen für die Aufbewahrung.
 a| 
ONTAP 9.16.1 (deprecated in 9.17.1 und höher)



| `arw.snap.create.interval.hours.post.max.count`  a| 
Legt das Intervall _in Stunden_ zwischen ARP/AI-Snapshots fest, wenn das Volume bereits die maximale Anzahl an ARP/AI-Snapshots enthält. Wenn die maximale Anzahl erreicht ist, wird ein ARP/AI-Snapshot gelöscht, um Platz für eine neue Kopie zu schaffen. Mit dieser Option lässt sich die Erstellungsgeschwindigkeit reduzieren, sodass ältere Kopien erhalten bleiben.
 a| 
ONTAP 9.16.1 (deprecated in 9.17.1 und höher)



| `arw.snap.new.extns.interval.hours`  a| 
Gibt das Intervall _in Stunden_ zwischen ARP/AI-Snapshots an, die erstellt werden, wenn eine neue Dateierweiterung erkannt wird. Ein neuer ARP/AI-Snapshot wird erstellt, wenn eine neue Dateierweiterung erkannt wird und der vorherige entsprechende Snapshot älter als das angegebene Intervall ist. Diese Option besteht unabhängig von  `arw.snap.create.interval.hours`, die das Intervall für entropiebasierte Snapshots angibt.
 a| 
ONTAP 9.16.1 (deprecated in 9.17.1 und höher)



| `arw.snap.low.encryption.retain.duration.hours`  a| 
Legt die Aufbewahrungsdauer _in Stunden_ für ARP/AI Snapshots fest, die während Perioden geringer Verschlüsselungsaktivität erstellt wurden.
 a| 
ONTAP 9.17.1 und höher



| `arw.snap.retain.hours.after.clear.suspect.false.alert`  a| 
Gibt das Intervall _in Stunden_ an, in dem ein ARP/AI-Snapshot vorsorglich aufbewahrt wird, nachdem ein Angriffsereignis vom Administrator als Fehlalarm markiert wurde.
 a| 
ONTAP 9.16.1 und höher



| `arw.snap.retain.hours.after.clear.suspect.real.attack`  a| 
Gibt das Intervall _in Stunden_ an, in dem ein ARP/AI-Snapshot vorsorglich aufbewahrt wird, nachdem ein Angriffsereignis vom Administrator als echter Angriff markiert wurde.
 a| 
ONTAP 9.16.1 und höher



| `arw.snap.surge.interval.days`  a| 
Legt das Intervall _in Tagen_ zwischen ARP/AI-Snapshots fest, die als Reaktion auf IO-Spitzen erstellt werden. Diese Option legt außerdem die Aufbewahrungsdauer _in Tagen_ für einen ARP/AI-Surge-Snapshot fest.
 a| 
ONTAP 9.16.1 und höher



| `arw.high.encryption.alert.enabled`  a| 
Aktiviert Warnmeldungen bei hohem Verschlüsselungsgrad. Wenn auf  `on` (Standardeinstellung) gesetzt, sendet ONTAP eine Warnmeldung, wenn der Prozentsatz der Verschlüsselung den in  `arw.high.encryption.percentage.threshold` angegebenen Schwellenwert überschreitet.
 a| 
ONTAP 9.17.1 und höher



| `arw.high.encryption.percentage.threshold`  a| 
Legt den maximalen Prozentsatz der Verschlüsselung für ein Volume fest. Wenn der Prozentsatz der Verschlüsselung diesen Schwellenwert überschreitet, behandelt ONTAP die Erhöhung als Angriff und erstellt einen ARP/AI-Snapshot.  `arw.high.encryption.alert.enabled` muss auf  `on` gesetzt werden, damit diese Option wirksam wird.
 a| 
ONTAP 9.17.1 und höher



| `arw.snap.high.encryption.retain.duration.hours`  a| 
Gibt das Aufbewahrungsintervall _in Stunden_ für Snapshots an, die während eines Ereignisses mit hohem Verschlüsselungsschwellenwert erstellt wurden.
 a| 
ONTAP 9.17.1 und höher

|===
. Wenn Sie ARP/AI in einer SAN-Umgebung verwenden, können Sie auch die folgenden Einstellungen für den Evaluierungszeitraum ändern:
+
[cols="1,3,1"]
|===
| Einstellung | Beschreibung | Unterstützte Versionen 


| `arw.block_device.auto.learn.threshold.min_value`  a| 
Legt den minimalen Verschlüsselungsschwellenwert in Prozent während der automatischen Lernphase der Evaluierung für Blockgeräte fest.
 a| 
ONTAP 9.17.1 und höher



| `arw.block_device.auto.learn.threshold.max_value`  a| 
Legt den maximalen Verschlüsselungsschwellenwert in Prozent während der automatischen Lernphase der Evaluierung für Blockgeräte fest.
 a| 
ONTAP 9.17.1 und höher



| `arw.block_device.evaluation.phase.min_hours`  a| 
Gibt das Mindestintervall _in Stunden_ an, das die Auswertungsphase durchlaufen muss, bevor der Verschlüsselungsschwellenwert festgelegt wird.
 a| 
ONTAP 9.17.1 und höher



| `arw.block_device.evaluation.phase.max_hours`  a| 
Gibt das maximale Intervall _in Stunden_ an, das die Auswertungsphase durchlaufen muss, bevor der Verschlüsselungsschwellenwert festgelegt wird.
 a| 
ONTAP 9.17.1 und höher



| `arw.block_device.evaluation.phase.min_data_ingest_size_GB`  a| 
Gibt die Mindestmenge an Daten _in GB_ an, die während der Auswertungsphase erfasst werden muss, bevor der Verschlüsselungsschwellenwert festgelegt wird.
 a| 
ONTAP 9.17.1 und höher



| `arw.block_device.evaluation.phase.alert.enabled`  a| 
Gibt an, ob Warnmeldungen für die Auswertungsphase von ARP/AI auf Blockgeräten aktiviert sind. Standardwert ist  `True`.
 a| 
ONTAP 9.17.1 und höher



| `arw.block_device.evaluation.phase.alert.threshold`  a| 
Legt den Schwellenwert in Prozent während der Auswertungsphase von ARP/AI auf Blockgeräten fest. Wenn der Prozentsatz der Verschlüsselung diesen Schwellenwert überschreitet, wird eine Warnung ausgelöst.
 a| 
ONTAP 9.17.1 und höher

|===


.Verwandte Informationen
* link:learn-about-arpai.html#arp-ai-snapshots["Bedrohungsanalyse und ARP/AI Snapshots"]
* link:entropy-eval-period-arpai.html["ARP/AI Entropieauswertungszeitraum für SAN Volumes"]

