---
sidebar: sidebar 
permalink: anti-ransomware/pause-task.html 
keywords: anti-ransomware, ransomware, pause, autonomous, protection, arp 
summary: Wenn Sie ungewöhnliche Workload-Ereignisse erwarten, können Sie die Analyse des autonomen Ransomware-Schutzes jederzeit vorübergehend unterbrechen und fortsetzen. 
---
= Unterbrechen Sie den autonomen Ransomware-Schutz, um Workload-Ereignisse aus der Analyse auszuschließen
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie ungewöhnliche Workload-Ereignisse erwarten, können Sie die ARP-Analyse (Autonomous Ransomware Protection, Autonomous Ransomware Protection) jederzeit unterbrechen und wieder aufnehmen.

Ab ONTAP 9.13.1 können Sie die Multi-Admin-Verifizierung (MAV) aktivieren, sodass mindestens zwei authentifizierte Benutzeradministratoren zum Anhalten des ARP erforderlich sind. link:../multi-admin-verify/enable-disable-task.html["Weitere Informationen ."^].

.Über diese Aufgabe
Während einer ARP-Pause werden keine Ereignisse protokolliert oder sind Maßnahmen bei neuen Schreibvorgängen. Die Analyse wird jedoch für frühere Protokolle im Hintergrund fortgesetzt.


NOTE: Verwenden Sie die ARP-Deaktivierungsfunktion nicht, um die Analyse anzuhalten. Dadurch wird ARP auf dem Volume deaktiviert, und alle vorhandenen Informationen rund um das gelernte Workload-Verhalten sind verloren. Dies würde einen Neustart des Lernzeitraums erfordern.

.Schritte
Sie können System Manager oder die ONTAP-CLI verwenden, um ARP anzuhalten.

[role="tabbed-block"]
====
.System Manager
--
. Wählen Sie *Speicher > Volumes* und wählen Sie dann das Volume aus, auf dem Sie ARP anhalten möchten.
. Wählen Sie auf der Registerkarte **Sicherheit** der Volumes-Übersicht *Anti-Ransomware anhalten* im Feld *Anti-Ransomware* aus.
+

NOTE: Wenn Sie ab ONTAP 9.13.1 MAV zum Schutz Ihrer ARP-Einstellungen verwenden, werden Sie durch den Pause-Vorgang aufgefordert, die Genehmigung eines oder mehrerer zusätzlicher Administratoren einzuholen. link:../multi-admin-verify/request-operation-task.html["Die Genehmigung muss von allen Administratoren eingeholt werden"] Der MAV-Genehmigungsgruppe zugeordnet oder der Vorgang schlägt fehl.



--
.CLI
--
. ARP auf einem Volume anhalten:
+
`security anti-ransomware volume pause -vserver _svm_name_ -volume _vol_name_`

. Um die Verarbeitung fortzusetzen, verwenden Sie den `resume` Befehl:
+
`security anti-ransomware volume resume -vserver _svm_name_ -volume _vol_name_`

. *Wenn Sie MAV (verfügbar mit ARP ab ONTAP 9.13.1) zum Schutz Ihrer ARP-Einstellungen verwenden,* fordert Sie der Pausenvorgang auf, die Genehmigung eines oder mehrerer zusätzlicher Administratoren einzuholen. Die Genehmigung muss von allen Administratoren, die mit der MAV-Genehmigungsgruppe verknüpft sind, eingeholt werden. Andernfalls schlägt der Vorgang fehl.
+
Wenn Sie MAV verwenden und für einen erwarteten Pausenbetrieb zusätzliche Genehmigungen erforderlich sind, führt jeder Genehmiger der MAV-Gruppe Folgendes durch:

+
.. Anfrage anzeigen:
+
`security multi-admin-verify request show`

.. Genehmigen Sie die Anforderung:
+
`security multi-admin-verify request approve -index[_number returned from show request_]`

+
Die Antwort für den letzten Gruppengenehmiger zeigt an, dass das Volume geändert wurde und der Status von ARP angehalten wurde.

+
Wenn Sie MAV verwenden und ein Genehmiger der MAV-Gruppe sind, können Sie eine Anforderung für einen Pause-Vorgang ablehnen:

+
`security multi-admin-verify request veto -index[_number returned from show request_]`





--
====