---
sidebar: sidebar 
permalink: anti-ransomware/recover-data-task.html 
keywords: Restore data after an attack, anti-ransomware backup, restore data from snapshot copies, potential ransomware attack, ransomware attack, recovery snapshot copies are deleted, recover deleted snapshot copies, autonomous, ransomware, protection, arp 
summary: Snapshot-Kopien namens Anti_Ransomware_Backup werden erstellt, wenn das Ransomware-Konzept einen potenziellen Angriff erkennt. Daten können von diesen Ransomware-Kopien oder anderen Snapshot Kopien wiederhergestellt werden. 
---
= Wiederherstellung von Daten nach einem Ransomware-Angriff
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Snapshot-Kopien mit dem Namen „Anti_Ransomware_Backup“ werden erstellt, wenn Autonomous Ransomware Protection (ARP) einen potenziellen Angriff erkennt. Sie können Daten aus diesen ARP Kopien oder anderen Snapshot Kopien wiederherstellen.


NOTE: Falls ein Ransomware-Angriff stattfindet, ist der Artikel der Knowledge Base zu entnehmen link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Ransomware_prevention_and_recovery_in_ONTAP["Vorbeugung und Wiederherstellung von Ransomware in ONTAP"^] Weitere Informationen zur Wiederherstellung und Risikominimierung.

.Was Sie benötigen
* ARP aktiviert
* Berichte zu potenziellen Ransomware-Angriffen


.Schritte
[role="tabbed-block"]
====
.System Manager
--
. Zeigen Sie die Snapshot Kopien in Volumes an, die in einem potenziellen Angriff identifiziert wurden: Klicken Sie auf *Storage > Volumes*, wählen Sie das Volume aus und klicken Sie dann auf die Registerkarte Snapshot Kopien.
. Stellen Sie die gewünschten Kopien gemäß folgenden Anweisungen wieder her:link:../task_dp_recover_snapshot.html["Wiederherstellung aus Snapshot-Kopien"]


--
.CLI
--
. Zeigen Sie die Snapshot-Kopien in Volumes an, die bei einem potenziellen Angriff identifiziert wurden:
`volume snapshot show -vserver _svm_name_ -volume _vol_name_`
. Stellen Sie die gewünschten Kopien gemäß folgenden Anweisungen wieder her:link:../data-protection/restore-contents-volume-snapshot-task.html["Wiederherstellen von Dateien aus Snapshot-Kopien"]


--
====