---
sidebar: sidebar 
permalink: snapmirror-active-sync/aufo-site-b-troubleshoot-task.html 
keywords: SM-BC, SMBC, troubleshooting, automatic unplanned failover, aufo, failover, Mediator, Cloud Mediator, quorum, snapmirror active sync 
summary: Ein Ausfall an Standort A löst keinen ungeplanten ONTAP Cluster-Failover an Standort B aus. 
---
= Automatisches ungeplantes Failover wird an Standort B nicht ausgelöst.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die folgenden Informationen gelten, wenn ein Ausfall an Standort A keinen ungeplanten Failover an Standort B auslöst.

.Problem:
Ein Ausfall an Standort A löst keinen ungeplanten Failover an Standort B aus.

.Mögliche Ursache Nr. 1:
Der ONTAP Mediator oder der ONTAP Cloud Mediator ist nicht konfiguriert. Um festzustellen, ob dies die Ursache ist, kann der  `snapmirror mediator show` Befehl auf dem Cluster von Standort B ausgeführt werden.

....
Cluster2::> snapmirror mediator show
This table is currently empty.
....
Dieses Beispiel zeigt, dass der Mediator auf Standort B nicht konfiguriert ist.

.Lösung:
Es muss sichergestellt sein, dass der Mediator auf beiden Clustern konfiguriert ist, der Status auf „Verbunden“ steht und das Quorum auf „True“ gesetzt ist.

.Mögliche Ursache Nr. 2:
SnapMirror Konsistenzgruppe ist nicht synchron. Zur Feststellung, ob dies die Ursache ist, kann das Ereignisprotokoll eingesehen werden, um zu prüfen, ob die Konsistenzgruppe zum Zeitpunkt des Ausfalls von Site A synchron war.

....
cluster::> event log show -event *out.of.sync*

Time                Node             Severity      Event
------------------- ---------------- ------------- ---------------------------
10/1/2020 23:26:12  sti42-vsim-ucs511w ERROR       sms.status.out.of.sync: Source volume "vs0:zrto_cg_556844_511u_RW1" and destination volume "vs1:zrto_cg_556881_511w_DP1" with relationship UUID "55ab7942-03e5-11eb-ba5a-005056a7dc14" is in "out-of-sync" status due to the following reason: "Transfer failed."
....
.Lösung:
Die folgenden Schritte sind erforderlich, um ein erzwungenes Failover auf Standort B durchzuführen.

. Alle LUNs, die zur Konsistenzgruppe gehören, vom Standort B unzuordnen.
. Die SnapMirror Konsistenzgruppenbeziehung wird mit der  `force` Option gelöscht.
. Den  `snapmirror break` Befehl auf den Konsistenzgruppen-Bestandteilen ausführen, um Volumes von DP auf R/W zu konvertieren und I/O von Site B zu ermöglichen.
. Die Knoten von Standort A werden gestartet, um eine Zero-RTO-Beziehung von Standort B zu Standort A zu erstellen.
. Die Konsistenzgruppe wird mit  `relationship-info-only` auf Standort A freigegeben, um einen gemeinsamen Snapshot beizubehalten und die zugehörigen LUNs der Konsistenzgruppe zu entkoppeln.
. Die Volumes am Standort A werden von R/W auf DP konvertiert, indem auf Volume-Ebene eine Beziehung mithilfe der Sync-Richtlinie oder der Async-Richtlinie eingerichtet wird.
. Den Befehl  `snapmirror resync` ausgeben, um die Beziehungen zu synchronisieren.
. Die SnapMirror Beziehungen mit der Sync-Richtlinie auf Standort A löschen.
. Die SnapMirror Beziehungen mit Sync-Richtlinie werden mithilfe von  `relationship-info-only true` auf Standort B freigegeben.
. Eine Konsistenzgruppen-Beziehung von Standort B zu Standort A erstellen.
. Eine Konsistenzgruppe-Resynchronisierung von Standort A aus durchführen und anschließend überprüfen, ob die Konsistenzgruppe synchron ist.
. Die Host-LUN-I/O-Pfade werden erneut gescannt, um alle Pfade zu den LUNs wiederherzustellen.


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-break.html["snapmirror break"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-mediator-show.html["snapmirror mediator show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["SnapMirror Resynchronisierung"^]

