---
sidebar: sidebar 
permalink: snapmirror-active-sync/cloud-mediator-requirements-concept.html 
keywords: SM-BC, SMBC, ONTAP, Cloud Mediator, prerequisites, requirements, configuration, firewall, latency, proxy, certificate, snapmirror active sync 
summary: Sie müssen bestimmte Anforderungen erfüllen, bevor Sie ONTAP Cloud Mediator installieren. 
---
= Vorbereiten der Konfiguration von ONTAP Cloud Mediator
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Bevor Sie link:cloud-mediator-config-task.html["ONTAP Cloud Mediator konfigurieren"] müssen Sie sicherstellen, dass die Voraussetzungen erfüllt sind.



[[firewall-requirements]]
== Anforderungen an die Firewall

Die Firewall-Einstellung auf dem Domänencontroller muss HTTPS-Verkehr zulassen  `api.bluexp.netapp.com` aus beiden Clustern.



[[proxy-server-requirements]]
== Proxyserver-Anforderungen

Wenn Sie Proxyserver für SnapMirror Active Sync verwenden, stellen Sie sicher, dass die Proxyserver erstellt wurden und Sie über die folgenden Proxyserverinformationen verfügen:

* HTTPS-Proxy-IP
* Port
* Benutzername
* Passwort




[[latency]]
== Latenz

Die empfohlene Ping-Latenz zwischen dem NetApp Console-Cloud-Server und den SnapMirror Active Sync-Cluster-Peers beträgt weniger als 200 ms.



[[root-ca-certificates]]
== Stammzertifizierungsstellenzertifikate

.Überprüfen des Clusters auf Zertifikate
ONTAP wird mit vorinstallierten bekannten Root-CA-Zertifikaten geliefert, sodass Sie in den meisten Fällen das Root-CA-Zertifikat des NetApp Console-Servers nicht installieren müssen. Bevor Sie mit der Konfiguration des ONTAP Cloud Mediators beginnen, können Sie den Cluster überprüfen, um sicherzustellen, dass die Zertifikate vorhanden sind:

Beispiel:

[listing]
----
C1_cluster% openssl s_client -showcerts -connect api.bluexp.netapp.com:443 -servername api.bluexp.netapp.com | egrep "s:|i:"

depth=4 C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services
verify error:num=19:self-signed certificate in certificate chain
verify return:1
depth=4 C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services
verify return:1
depth=3 C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust RSA Certification Authority
verify return:1
depth=2 C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication Root R46
verify return:1
depth=1 C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication CA OV R36
verify return:1
depth=0 C=US, ST=California, O=NetApp, Inc., CN=cloud.netapp.com
verify return:1
 0 s:C=US, ST=California, O=NetApp, Inc., CN=cloud.netapp.com
   i:C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication CA OV R36
 1 s:C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication CA OV R36
   i:C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication Root R46
 2 s:C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication Root R46
   i:C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust RSA Certification Authority
 3 s:C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust RSA Certification Authority
   i:C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services
 4 s:C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services
   i:C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services

C1_cluster::> security certificate show -common-name Sectigo*|USERTrust*|AAA*
Vserver    Serial Number   Certificate Name                       Type
---------- --------------- -------------------------------------- ------------
C1_sti245-vsim-ocvs024k_1775534714 42F2CCDA1B6937445F15FE752810B8F4 SectigoPublicServerAuthenticationRootE46 server-ca
    Certificate Authority: Sectigo Public Server Authentication Root E46
          Expiration Date: Wed Mar 21 19:59:59 2046

C1_sti245-vsim-ocvs024k_1775534714 758DFD8BAE7C0700FAA925A7E1C7AD14 SectigoPublicServerAuthenticationRootR46 server-ca
    Certificate Authority: Sectigo Public Server Authentication Root R46
          Expiration Date: Wed Mar 21 19:59:59 2046

C1_sti245-vsim-ocvs024k_1775534714 5C8B99C55A94C5D27156DECD8980CC26 USERTrustECCCertificationAuthority server-ca
    Certificate Authority: USERTrust ECC Certification Authority
          Expiration Date: Mon Jan 18 18:59:59 2038

C1_sti245-vsim-ocvs024k_1775534714 01FD6D30FCA3CA51A81BBC640E35032D USERTrustRSACertificationAuthority server-ca
    Certificate Authority: USERTrust RSA Certification Authority
          Expiration Date: Mon Jan 18 18:59:59 2038

----
.Proxyserver auf installierte Zertifikate prüfen
Wenn Sie einen Proxy verwenden, um eine Verbindung zum ONTAP Cloud Mediator-Dienst in der NetApp Konsole herzustellen, stellen Sie sicher, dass die Stamm-CA-Zertifikate des Proxyservers in ONTAP installiert sind:

Beispiel:

[listing]
----
C1_cluster% openssl s_client -showcerts -proxy <ip:port> -connect api.bluexp.netapp.com:443 -servername api.bluexp.netapp.com |egrep "s:|i:"
----
.Laden Sie das CA-Zertifikat herunter:
Bei Bedarf können Sie die Root-CA-Zertifikate von der Website der Zertifizierungsstelle herunterladen und auf den Clustern installieren.

Beispiel:

[listing]
----
C1_cluster::> security certificate install -type server-ca -vserver C1_cluster

C2_cluster::> security certificate install -type server-ca -vserver C2_cluster
----