---
sidebar: sidebar 
permalink: snapmirror-active-sync/cluster-config-task.html 
keywords: SM-BC, SMBC, cluster, peering, ONTAP, Mediator, ONTAP Cloud Mediator, initialize, snapmirror active sync 
summary: Wenn Sie ONTAP Mediator oder ONTAP Cloud Mediator mit SnapMirror Active Sync verwenden, müssen Sie zunächst sicherstellen, dass der Cluster richtig konfiguriert ist. 
---
= Konfigurieren Sie ONTAP -Cluster für SnapMirror Active Sync
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror Active Sync verwendet Peering-Cluster, um Ihre Daten im Falle eines Failovers zu schützen. Bevor Sie ONTAP Mediator oder ONTAP Cloud Mediator für SnapMirror Active Sync konfigurieren, müssen Sie zunächst sicherstellen, dass der Cluster korrekt konfiguriert ist.

.Bevor Sie beginnen
Bevor Sie ONTAP Mediator oder ONTAP Cloud Mediator konfigurieren, sollten Sie Folgendes bestätigen:

. Zwischen den Clustern besteht eine Cluster-Peering-Beziehung.
+

NOTE: Der standardmäßige IPspace wird von der aktiven SnapMirror Synchronisierung für Cluster-Peer-Beziehungen benötigt. Ein benutzerdefinierter IPspace wird nicht unterstützt.

+
link:../peering/create-cluster-relationship-93-later-task.html["Erstellen einer Cluster-Peer-Beziehung"]

. Die SVMs werden auf jedem Cluster erstellt.
+
link:../smb-config/create-svms-data-access-task.html["Erstellen einer SVM"]

. Zwischen den SVMs auf jedem Cluster besteht eine Peer-Beziehung.
+
link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["Erstellen einer SVM-Peering-Beziehung"]

. Die Volumes sind für Ihre LUNs vorhanden.
+
link:../smb-config/create-volume-task.html["Erstellen eines Volumes"]

. Auf jedem Knoten im Cluster wird mindestens ein SAN LIF erstellt.
+
link:../san-admin/manage-lifs-all-san-protocols-concept.html["Überlegungen zu LIFs in einer Cluster-SAN-Umgebung"]

+
link:../networking/create_a_lif.html["Erstellen einer LIF"]

. Die erforderlichen LUNs werden erstellt und einer Igroup zugeordnet, die zum Zuordnen von LUNs zum Initiator auf dem Anwendungshost verwendet wird.
+
link:../san-admin/provision-storage.html["LUNs erstellen und Initiatorgruppen zuordnen"]

. Der Anwendungshost wird erneut gescannt, um neue LUNs zu erkennen.

