---
sidebar: sidebar 
permalink: snapmirror-active-sync/delete-fails-takeover-task.html 
keywords: troubleshooting, SM-BC, SMBC, SnapMirror, delete, takeover, consistency group, snapmirror active sync 
summary: 'Wenn ONTAP 9.9.1 auf einem Cluster installiert ist, führt die Ausführung des  `snapmirror delete` Der Befehl schlägt fehl, wenn sich eine SnapMirror Active Sync Consistency Group-Beziehung im Übernahmestatus befindet.' 
---
= Das Löschen von SnapMirror schlägt im Takover-Status fehl
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Verwenden Sie die folgenden Informationen, wenn die  `snapmirror delete` Der Befehl schlägt fehl, wenn sich eine SnapMirror Active Sync Consistency Group-Beziehung im Übernahmestatus befindet.

.Problem:
Wenn ONTAP 9.9.1 auf einem Cluster installiert ist, führt die Ausführung des  `snapmirror delete` Der Befehl schlägt fehl, wenn sich eine SnapMirror Active Sync Consistency Group-Beziehung im Übernahmestatus befindet.

....
C2_cluster::> snapmirror delete  vs1:/cg/dd

Error: command failed: RPC: Couldn't make connection
....
.Nutzen
Wenn sich die Knoten in einer SnapMirror-Active-Sync-Beziehung im Übernahmezustand befinden, führen Sie den SnapMirror-Lösch- und Freigabevorgang mit der Option „-force“ auf „true“ aus.

....
C2_cluster::> snapmirror delete  vs1:/cg/dd -force true

Warning: The relationship between source "vs0:/cg/ss" and destination
         "vs1:/cg/dd" will be deleted, however the items of the destination
         Consistency Group might not be made writable, deletable, or modifiable
         after the operation. Manual recovery might be required.
Do you want to continue? {y|n}: y
Operation succeeded: snapmirror delete for the relationship with destination "vs1:/cg/dd".
....
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["snapmirror löschen"^]

