---
sidebar: sidebar 
permalink: snapmirror-active-sync/delete-fails-takeover-task.html 
keywords: troubleshooting, SM-BC, SMBC, SnapMirror, delete, takeover, consistency group, snapmirror active sync 
summary: 'Wenn ONTAP 9.9.1 auf einem Cluster installiert ist, schlägt die Ausführung des  `snapmirror delete` Befehls fehl, wenn sich eine SnapMirror Aktiv Sync Konsistenzgruppenbeziehung im Übernahmezustand befindet.' 
---
= ONTAP SnapMirror Löschvorgang schlägt im Übernahmezustand fehl
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die folgenden Informationen sind relevant, wenn der  `snapmirror delete` Befehl fehlschlägt, wenn sich eine SnapMirror active sync Konsistenzgruppe Beziehung im Übernahmezustand befindet.

.Problem:
Wenn ONTAP 9.9.1 auf einem Cluster installiert ist, schlägt die Ausführung des  `snapmirror delete` Befehls fehl, wenn sich eine SnapMirror Aktiv Sync Konsistenzgruppenbeziehung im Übernahmezustand befindet.

....
C2_cluster::> snapmirror delete  vs1:/cg/dd

Error: command failed: RPC: Couldn't make connection
....
.Lösung
Wenn sich die Knoten in einer SnapMirror Aktiv Sync-Beziehung im Übernahmezustand befinden, ist der SnapMirror Lösch- und Freigabevorgang mit der Option "-force" auf true auszuführen.

....
C2_cluster::> snapmirror delete  vs1:/cg/dd -force true

Warning: The relationship between source "vs0:/cg/ss" and destination
         "vs1:/cg/dd" will be deleted, however the items of the destination
         Consistency Group might not be made writable, deletable, or modifiable
         after the operation. Manual recovery might be required.
Do you want to continue? {y|n}: y
Operation succeeded: snapmirror delete for the relationship with destination "vs1:/cg/dd".
....
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["snapmirror delete"^]

