---
sidebar: sidebar 
permalink: snapmirror-active-sync/index.html 
keywords: SM-BC, SMBC, failover, terms, benefits, snapmirror active sync, TR-4878 
summary: Verwenden Sie SnapMirror Active Sync, um Applikationen mit LUNs zu schützen und Applikationen für transparentes Failover zu ermöglichen, sodass für Business Continuity im Falle eines Notfalls gesorgt ist. 
---
= Erfahren Sie mehr über ONTAP SnapMirror Active Sync
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror Active Sync, auch bekannt als SnapMirror Business Continuity (SM-BC), ermöglicht die Weiterfunktion von Geschäftsdiensten im Falle eines vollständigen Site-Ausfalls.  Diese Technologie ermöglicht ein nahtloses Failover von Anwendungen auf eine sekundäre Kopie ohne manuelle Eingriffe oder benutzerdefinierte Skripts.

NetApp SnapMirror Active Sync (SM-as) ist als granularerer, kostengünstigerer und benutzerfreundlicherer Schutz auf Anwendungsebene mit automatischem Failover konzipiert.  SnapMirror Active Sync ermöglicht die Aufrechterhaltung des Betriebs unternehmenskritischer Dienste, selbst bei einem vollständigen Site-Ausfall.  Mit SnapMirror Active Sync können Sie jetzt mehrere Volumes einer Anwendung synchron zwischen Sites an geografisch verteilten Standorten replizieren (indem Sie sie einer Konsistenzgruppe hinzufügen).  Sie können im Falle einer Störung der primären Kopie automatisch ein Failover auf die sekundäre Kopie durchführen und so die Geschäftskontinuität für Tier-1-Anwendungen gewährleisten.

In einigen Ländern schreiben die Vorschriften für Finanzinstitute vor, dass Unternehmen regelmäßig von ihren sekundären Rechenzentren aus bedient werden können.  SnapMirror Active Sync ermöglicht mit seinen Hochverfügbarkeitsclustern diese Rechenzentrumsumschaltungen zur Gewährleistung der Geschäftskontinuität.

SnapMirror Active Sync ist ab ONTAP 9.9.1 verfügbar und wird auf AFF und All-Flash SAN Array (ASA)-Clustern unterstützt.  Der primäre und der sekundäre Cluster müssen vom gleichen Typ sein: entweder ASA, ASA r2 oder AFF.  SnapMirror Active Sync schützt Anwendungen mit iSCSI- oder FCP-LUNs oder NVMe-Namespaces.

SnapMirror Active Sync unterstützt sowohl symmetrische als auch asymmetrische Konfigurationen.  Die Unterstützung für symmetrisches Aktiv/Aktiv wurde in ONTAP 9.15.1 eingeführt.  Durch die symmetrische Aktiv/Aktiv-Konfiguration können beide Kopien einer geschützten LUN Lese- und Schreib-E/A-Vorgänge mit bidirektionaler synchroner Replikation durchführen, sodass jede LUN-Kopie lokale E/A-Anforderungen erfüllen kann.


NOTE: Ab Juli 2024 wurden die Inhalte aus zuvor als PDFs veröffentlichten technischen Berichten in die ONTAP Produktdokumentation integriert. Die Dokumentation zur aktiven Synchronisierung von ONTAP SnapMirror enthält nun Inhalte aus _TR-4878: SnapMirror Active Sync_.



== Vorteile

SnapMirror Active Sync bietet folgende Vorteile:

* Kontinuierliche Verfügbarkeit für geschäftskritische Applikationen:
* Fähigkeit, kritische Applikationen abwechselnd von primären und sekundären Standorten zu hosten
* Vereinfachtes Applikationsmanagement durch Consistency Groups für eine abhängige Konsistenz der Schreibreihenfolge
* Die Fähigkeit, ein Failover für jede Anwendung zu testen.
* Sofortige Erstellung von gespiegelten Klonen ohne Beeinträchtigung der Applikationsverfügbarkeit
* Bereitstellung geschützter und nicht geschützter Workloads im selben ONTAP-Cluster.
* LUN, NVMe-Namespace, NVMe-Subsystem oder Speichereinheitenidentität bleiben gleich, sodass die Anwendung sie als gemeinsam genutztes virtuelles Gerät betrachtet.
* Sekundäre Cluster können mit der Flexibilität wiederverwendet werden, um sofort Klone für die Anwendungsnutzung für Entwicklungs- und Testzwecke sowie für UAT- oder Reporting-Zwecke zu erstellen, ohne die Applikations-Performance oder -Verfügbarkeit zu beeinträchtigen.


SnapMirror Active Sync ermöglicht Ihnen den Schutz Ihrer Daten-LUNs oder NVMe-Namespaces. Dadurch wird ein transparentes Failover von Anwendungen zur Gewährleistung der Geschäftskontinuität im Notfall ermöglicht. Weitere Informationen finden Sie unter link:use-cases-concept.html["Anwendungsfälle"] .



== Schlüsselkonzepte

SnapMirror Active Sync verwendet Konsistenzgruppen, um sicherzustellen, dass Ihre Daten repliziert werden.  SnapMirror Active Sync verwendet den ONTAP Mediator oder, ab ONTAP 9.17.1, den Cloud Mediator für automatisiertes Failover und stellt so sicher, dass die Daten im Katastrophenfall bereitgestellt werden. Bei der Planung Ihrer SnapMirror Active Sync-Bereitstellung ist es wichtig, die wesentlichen Konzepte und die Architektur von SnapMirror Active Sync zu verstehen.

.Asymmetrie und Symmetrie
In symmetrischen Aktiv/Aktiv-Konfigurationen können beide Standorte für aktive E/A auf den lokalen Speicher zugreifen. Symmetrisches Aktiv/Aktiv ist für Clusteranwendungen wie VMware vMSC, Windows Failover Cluster mit SQL und Oracle RAC optimiert.

In asymmetrischen Aktiv/Aktiv-Konfigurationen werden Daten auf der sekundären Site an eine LUN, einen Namespace oder eine Speichereinheit weitergeleitet.

Weitere Informationen finden Sie unter xref:architecture-concept.html[Architektur der aktiven Synchronisierung von SnapMirror].

.Konsistenzgruppe
Für AFF und ASA -Systeme ist ein link:../consistency-groups/index.html["Konsistenzgruppe"] ist eine Sammlung von FlexVol -Volumes, die eine Konsistenzgarantie für die Anwendungs-Workload bieten, die zur Gewährleistung der Geschäftskontinuität geschützt werden muss. In ASA R2-Systemen ist eine Konsistenzgruppe eine Sammlung von Speichereinheiten.

Der Zweck einer Konsistenzgruppe besteht darin, gleichzeitig Snapshots von Volumes oder Speichereinheiten zu erstellen und so absturzkonsistente Kopien der Sammlung zu einem bestimmten Zeitpunkt sicherzustellen. Eine Konsistenzgruppe stellt sicher, dass alle Volumes eines Datensatzes stillgelegt und zum exakt gleichen Zeitpunkt erneut gesichert werden. Dies ermöglicht einen datenkonsistenten Wiederherstellungspunkt für alle Volumes oder Speichereinheiten, die den Datensatz unterstützen. Eine Konsistenzgruppe gewährleistet dadurch die abhängige Konsistenz der Schreibreihenfolge. Wenn Sie Anwendungen zur Geschäftskontinuität schützen möchten, muss die Gruppe der dieser Anwendung zugehörigen Volumes oder Speichereinheiten einer Konsistenzgruppe hinzugefügt werden, um eine Datenschutzbeziehung zwischen einer Quell- und einer Zielkonsistenzgruppe herzustellen. Die Quell- und Zielkonsistenzgruppe müssen dieselbe Anzahl und denselben Typ von Volumes enthalten.

.Konstitutive
Ein einzelnes Volume, LUN oder NVMe-Namespace (ab ONTAP 9.17.1), das Teil der Konsistenzgruppe ist, die in der SnapMirror Active Sync-Beziehung geschützt ist.

.ONTAP Mediator
Der link:../mediator/index.html["ONTAP Mediator"] empfängt Zustandsinformationen zu verbundenen ONTAP Clustern und -Knoten, koordiniert die Zusammenarbeit und ermittelt, ob jeder Knoten/Cluster fehlerfrei und betriebsbereit ist. ONTAP Mediator liefert Zustandsinformationen zu:

* Peer ONTAP Cluster
* Peer ONTAP Cluster Nodes
* Konsistenzgruppen (zur Definition der Failover-Einheiten in einer SnapMirror Active Sync Beziehung), für jede Konsistenzgruppe sind die folgenden Informationen angegeben:
+
** Replikationsstatus: Nicht initialisiert, synchron oder nicht synchronisiert
** Welcher Cluster hostet die primäre Kopie
** Operationskontext (wird für geplanten Failover verwendet)




Mit diesen ONTAP Mediator-Integritätsinformationen können Cluster zwischen verschiedenen Arten von Ausfällen unterscheiden und bestimmen, ob ein automatisiertes Failover durchgeführt werden soll. ONTAP Mediator ist eine der drei Parteien des SnapMirror Active Sync Quorums zusammen mit beiden ONTAP Clustern (primär und sekundär). Um einen Konsens zu erreichen, müssen mindestens zwei Parteien im Quorum einer bestimmten Operation zustimmen.


NOTE: Ab ONTAP 9.15.1 zeigt System Manager den Status der aktiven SnapMirror Synchronisierungsbeziehung von einem der beiden Cluster an. Sie können den Status des ONTAP Mediators auch von einem der Cluster aus im System Manager überwachen. In früheren Versionen von ONTAP zeigt System Manager den Status der aktiven SnapMirror Synchronisierungsbeziehungen vom Quell-Cluster an.

.ONTAP Cloud Mediator
ONTAP Cloud Mediator ist ab ONTAP 9.17.1 verfügbar. ONTAP Cloud Mediator bietet dieselben Dienste wie ONTAP Mediator, außer dass es mithilfe der NetApp Konsole in der Cloud gehostet wird.

.Geplantes Failover
Ein manueller Vorgang zum Ändern der Rollen von Kopien in einer aktiven SnapMirror Synchronisierungsbeziehung. Die primären Standorte werden zum sekundären Standort und der sekundäre zum primären Standort.

.Automatisches ungeplantes Failover (AUFO)
Ein automatischer Vorgang zum Durchführen eines Failovers der Spiegelkopie. Der Vorgang erfordert Unterstützung durch den ONTAP Mediator, um festzustellen, dass die primäre Kopie nicht verfügbar ist.

.Primary-First und Primary Bias
Die aktive Synchronisierung von SnapMirror nutzt ein Prinzip der primären Priorität, das der primären Kopie vorgibt, um I/O-Anfragen bei einer Netzwerkpartition zu bedienen.

Primär-Bias ist eine spezielle Quorum-Implementierung, die die Verfügbarkeit eines durch SnapMirror aktiv synchron geschützten Datensatzes verbessert. Wenn die primäre Kopie verfügbar ist, tritt Primary-Bias in Kraft, wenn der ONTAP Mediator nicht von beiden Clustern aus erreichbar ist.

Primary-First- und Primary-Bias werden ab ONTAP 9.15.1 in SnapMirror Active Sync unterstützt. Primäre Kopien werden in System Manager festgelegt und mit der REST-API und CLI ausgegeben.

.Out-of-Sync (OOS)
Wenn die Anwendungs-I/O nicht auf das sekundäre Speichersystem repliziert wird, wird es als **nicht synchron** gemeldet. Ein Status „nicht synchron“ bedeutet, dass die sekundären Volumes nicht mit dem primären Volume (Quelle) synchronisiert werden und dass die SnapMirror Replizierung nicht stattfindet.

Wenn der Spiegelzustand `Snapmirrored` , dies zeigt an, dass eine SnapMirror -Beziehung hergestellt wurde und die Datenübertragung abgeschlossen ist, was bedeutet, dass das Zielvolume mit dem Quellvolume auf dem neuesten Stand ist.

Die aktive Synchronisierung von SnapMirror unterstützt die automatische Neusynchronisierung, sodass Kopien in den InSync Status zurückkehren können.

Ab ONTAP 9.15.1 unterstützt SnapMirror Active Sync link:interoperability-reference.html#fan-out-configurations["Automatische Neukonfiguration in Fan-out-Konfigurationen"].

.Einheitliche und uneinheitliche Konfiguration
* **Uniform Host Access** bedeutet, dass Hosts von beiden Standorten mit allen Pfaden zu Storage Clustern auf beiden Standorten verbunden sind. Standortübergreifende Pfade sind über Entfernungen verteilt.
* **Uneinheitlicher Hostzugriff** bedeutet, dass Hosts an jedem Standort nur mit dem Cluster am selben Standort verbunden sind. Standortübergreifende Pfade und gestreckte Pfade sind nicht miteinander verbunden.



NOTE: Jeder SnapMirror Active Sync Bereitstellung wird ein einheitlicher Host-Zugriff unterstützt. Ein nicht einheitlicher Host-Zugriff wird nur für symmetrische aktiv/aktiv-Implementierungen unterstützt.

.Kein RPO
RPO steht für das Recovery Point Objective. Dies ist die Menge an Datenverlusten, die in einem bestimmten Zeitraum als akzeptabel erachtet werden. Ein RPO von null bedeutet, dass kein Datenverlust akzeptabel ist.

.Kein RTO
RTO steht für die Recovery Time Objective. Diese Zeitdauer wird für eine Applikation nach einem Ausfall, Ausfall oder anderen Datenverlusten für die unterbrechungsfreie Wiederherstellung des normalen Betriebs erachtet. Kein RTO bedeutet, dass keine Ausfallzeiten akzeptabel sind.



== SnapMirror Active Sync-Konfigurationsunterstützung durch ONTAP -Version

Die Unterstützung für SnapMirror Active Sync variiert je nach Ihrer ONTAP-Version:

[cols="4*"]
|===


| ONTAP-Version | Unterstützte Cluster | Unterstützte Protokolle | Unterstützte Konfigurationen 


| 9.17.1 und höher  a| 
* AFF
* ASA
* C-Serie
* ASA r2

 a| 
* ISCSI
* FC
* NVMe für VMware-Workloads

 a| 
* Asymmetrisch aktiv/aktiv



NOTE: Asymmetrisches Aktiv/Aktiv unterstützt ASA r2 und NVMe nicht. Weitere Informationen zur NVMe-Unterstützung finden Sie unter link:../nvme/support-limitations.html["Konfiguration, Support und Einschränkungen von NVMe"] .

* Symmetrische aktiv/aktiv-Lösung




| 9.16.1 und höher  a| 
* AFF
* ASA
* C-Serie
* ASA r2

 a| 
* ISCSI
* FC

 a| 
* Asymmetrisch aktiv/aktiv
* Symmetrische Aktiv/Aktiv-Konfigurationen unterstützen 4-Knoten-Cluster in ONTAP 9.16.1 und höher.  Für ASA r2 werden nur 2-Knoten-Cluster unterstützt.




| 9.15.1 und höher  a| 
* AFF
* ASA
* C-Serie

 a| 
* ISCSI
* FC

 a| 
* Asymmetrisch aktiv/aktiv
* Symmetrische Aktiv/Aktiv-Konfigurationen unterstützen 2-Knoten-Cluster in ONTAP 9.15.1. 4-Knoten-Cluster werden in ONTAP 9.16.1 und höher unterstützt.




| 9.9.1 und höher  a| 
* AFF
* ASA
* C-Serie

 a| 
* ISCSI
* FC

 a| 
Asymmetrisch aktiv/aktiv

|===
Primäre und sekundäre Cluster müssen vom gleichen Typ sein: entweder link:../san-admin/learn-about-asa.html["ASA"] , link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2"^] oder AFF.
