---
sidebar: sidebar 
permalink: snapmirror-active-sync/index.html 
keywords: SM-BC, SMBC, failover, terms, benefits, snapmirror active sync, TR-4878 
summary: Mit SnapMirror active sync lassen sich Anwendungen mit LUNs schützen, sodass Anwendungen transparent auf einen anderen Standort umschalten können und die Geschäftskontinuität im Katastrophenfall gewährleistet ist. 
---
= Informationen zu ONTAP SnapMirror Active Sync
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror active sync (vor ONTAP 9.15.1 als SnapMirror Business Continuity bezeichnet) ermöglicht die Fortführung von Geschäftsservices im Falle eines vollständigen Standortausfalls. Diese Technologie ermöglicht Anwendungen, nahtlos auf eine sekundäre Kopie umzuschalten, ohne manuelle Eingriffe oder benutzerdefinierte Skripte.

SnapMirror active sync (SM-as) ist als granularerer, kostengünstigerer und benutzerfreundlicherer Anwendungsschutz auf Applikationsebene mit automatischem Failover konzipiert. Mit SnapMirror active sync können mehrere Volumes einer Anwendung synchron zwischen Standorten an geografisch verteilten Orten repliziert werden. Im Falle einer Störung des primären Systems kann automatisch auf die sekundäre Kopie umgeschaltet werden, wodurch die Geschäftskontinuität für Tier-1-Anwendungen ermöglicht wird.

Die Vorschriften für Finanzinstitute in einigen Ländern verpflichten Unternehmen, regelmäßig über ihre sekundären Rechenzentren erreichbar zu sein. SnapMirror active sync ermöglicht mit seinen hochverfügbaren Clustern diese Rechenzentrumswechsel zur Sicherstellung der Geschäftskontinuität.

Ab ONTAP 9.9.1 wird SnapMirror active sync auf AFF und ASA Clustern unterstützt. Das primäre und das sekundäre Cluster müssen vom gleichen Typ sein: entweder AFF, ASA oder ASA r2. SnapMirror active sync schützt Anwendungen mit iSCSI- oder FCP-LUNs oder NVMe-Namespaces.

SnapMirror active sync für SAN-Workloads unterstützt sowohl symmetrische als auch asymmetrische Konfiguration. ONTAP 9.9.1 und höher umfasst die Unterstützung für asymmetrische Konfiguration. Die Unterstützung für symmetrische Aktiv/Aktiv-Konfiguration wurde in ONTAP 9.15.1 eingeführt. Die symmetrische Aktiv/Aktiv-Konfiguration ermöglicht es beiden Kopien einer geschützten LUN, Lese- und Schreib-I/O-Operationen mit bidirektionaler synchroner Replizierung durchzuführen, sodass jede LUN-Kopie lokale I/O-Anforderungen bedienen kann.

Ab ONTAP 9.19.1 unterstützt SnapMirror Active Sync NAS-Workloads auf SVM-Ebene mit NFS (v3 und v4) sowie SMB (2.x oder höher) auf AFF Clustern (nur 2-Node) oder AFX Clustern (nur 4-Node) und ermöglicht Lese-/Schreibzugriff ausschließlich auf dem primären System. Die sekundäre SVM und die darin enthaltenen Volumes sind nicht über NAS-Protokolle zugänglich, jedoch können die sekundären Volumes in eine andere SVM geklont werden, um Zugriff darauf zu ermöglichen.


NOTE: Ab Juli 2024 wurden Inhalte aus zuvor als PDFs veröffentlichten technischen Berichten in die ONTAP Produktdokumentation integriert. Die ONTAP SnapMirror active sync Dokumentation enthält nun Inhalte aus _TR-4878: SnapMirror active sync_.



[[benefits]]
== Vorteile

SnapMirror active sync bietet folgende Vorteile:

* Kontinuierliche Verfügbarkeit für geschäftskritische Anwendungen.
* Fähigkeit, geschäftskritische Anwendungen abwechselnd von primären und sekundären Standorten aus zu hosten.
* Vereinfachtes Anwendungsmanagement mit Konsistenzgruppen für abhängige Schreibreihenfolgekonsistenz.
* Die Möglichkeit, das Failover für jede Anwendung zu testen.
* Sofortige Erstellung von Spiegelklonen ohne Beeinträchtigung der Anwendungsverfügbarkeit.
* Die Möglichkeit, geschützte und ungeschützte Workloads im selben ONTAP Cluster bereitzustellen.
* Die LUN-, NVMe-Namespace-, NVMe-Subsystem- oder Speichereinheitsidentität für SAN-Konfigurationen und die Volumenidentität für NAS-Konfigurationen bleiben gleich, sodass die Anwendung sie als ein gemeinsam genutztes virtuelles Gerät erkennt.
* Die Möglichkeit, sekundäre Cluster flexibel wiederzuverwenden, um sofortige Klone für die Anwendungsnutzung zu erstellen, beispielsweise für Entwicklungs-, Test-, UAT- oder Berichtszwecke, ohne die Anwendungsleistung oder Verfügbarkeit zu beeinträchtigen.


SnapMirror active sync ermöglicht den Schutz Ihrer Daten-LUNs oder NVMe-Namespaces in SAN-Konfigurationen sowie Volumes in NAS-Konfigurationen, wodurch Anwendungen im Falle einer Katastrophe transparent auf ein anderes System umschalten können, um die Geschäftskontinuität sicherzustellen. Weitere Informationen finden sich unter link:use-cases-concept.html["Anwendungsfälle"].



[[key-concepts]]
== Schlüsselkonzepte

SnapMirror active sync verwendet Konsistenzgruppen in SAN-Konfigurationen und SVMs in NAS-Konfigurationen, um die Replizierung Ihrer Daten sicherzustellen. SnapMirror active sync verwendet den ONTAP Mediator oder, beginnend mit ONTAP 9.17.1, den Cloud Mediator für automatisches Failover, wodurch sichergestellt wird, dass die Daten im Katastrophenfall bereitgestellt werden. Bei der Planung Ihrer SnapMirror active sync-Bereitstellung ist es wichtig, die grundlegenden Konzepte von SnapMirror active sync und dessen Architektur zu verstehen.

.Asymmetrie und Symmetrie
In symmetrischen Aktiv/Aktiv-SAN-Clusterkonfigurationen können beide Standorte für aktive E/A auf den lokalen Speicher zugreifen. Symmetrische Aktiv/Aktiv-Konfigurationen sind für Clusteranwendungen wie VMware vMSC, Windows Failover Cluster mit SQL und Oracle RAC optimiert.

In asymmetrischen Aktiv/Aktiv SAN-Konfigurationen werden Daten am sekundären Standort an eine LUN, einen Namespace oder eine Speichereinheit weitergeleitet.

Weitere Informationen finden sich unter xref:architecture-concept.html[SnapMirror Active Sync-Architektur].

In NAS-Konfigurationen gibt es keinen Proxy und die sekundäre SVM ist inaktiv, aber die Volumes können auf eine andere SVM geklont werden, um Zugriff darauf bereitzustellen.

.Konsistenzgruppe (nur SAN)
Für AFF und ASA Systeme ist eine link:../consistency-groups/index.html["Konsistenzgruppe"]Konsistenzgruppe eine Sammlung von FlexVol Volumes, die eine Konsistenzgarantie für die Anwendungs-Workload bieten, die zum Schutz der Geschäftskontinuität erforderlich ist. In ASA r2 Systemen ist eine Konsistenzgruppe eine Sammlung von Speichereinheiten.

Der Zweck einer Konsistenzgruppe besteht darin, gleichzeitig Snapshot-Kopien einer Sammlung von Volumes oder Speichereinheiten zu erstellen und so absturzkonsistente Kopien der Sammlung zu einem bestimmten Zeitpunkt zu gewährleisten. Eine Konsistenzgruppe stellt sicher, dass alle Volumes eines Datasets in den Ruhezustand versetzt und dann exakt zum selben Zeitpunkt gesichert werden. Dies bietet einen datenkonsistenten Wiederherstellungspunkt über alle Volumes oder Speichereinheiten hinweg, die das Dataset unterstützen. Eine Konsistenzgruppe stellt dabei die Konsistenz der abhängigen Schreibreihenfolge sicher. Soll Anwendungen für die Geschäftskontinuität Schutz geboten werden, muss die Gruppe der dieser Anwendung entsprechenden Volumes oder Speichereinheiten einer Konsistenzgruppe hinzugefügt werden, sodass eine Datensicherungsbeziehung zwischen einer Quell- und einer Ziel-Konsistenzgruppe besteht. Die Quell- und die Ziel-Konsistenzgruppe müssen die gleiche Anzahl und den gleichen Typ von Volumes enthalten.

.SVM- und FlexVol-Unterstützung (SnapMirror active sync für NAS)
In ONTAP 9.19.1 unterstützt SnapMirror active sync für NAS den Schutz von SVMs, die FlexVol Volumes enthalten. Konsistenzgruppen oder FlexGroup Volumes innerhalb einer SVM werden von SnapMirror active sync in NAS-Konfigurationen nicht unterstützt.

.Bestandteil
In einer SAN-Konfiguration ist ein Bestandteil ein einzelnes Volume, eine LUN oder ein NVMe-Namespace (beginnend mit ONTAP 9.17.1), das Teil der Konsistenzgruppe ist, die in der SnapMirror active sync-Beziehung geschützt ist.

In einer NAS-Konfiguration ist ein Bestandteil ein Volume, und die enthaltende SVM ist die Entität, die in der SnapMirror active sync-Beziehung geschützt wird.

.ONTAP Mediator
Der link:../mediator/index.html["ONTAP Mediator"] empfängt Statusinformationen über verbundene ONTAP Cluster und Knoten, koordiniert zwischen beiden und ermittelt, ob jeder Knoten bzw. Cluster betriebsbereit ist. ONTAP Mediator liefert Statusinformationen über:

* Peer ONTAP Cluster
* Peer ONTAP Clusterknoten
* Failover-Einheiten (die Konsistenzgruppen in einer SnapMirror Aktiv/Synchronisierung-für-SAN-Beziehung und SVMs in einer SnapMirror Aktiv/Synchronisierung-für-NAS-Beziehung entsprechen); für jede Failover-Einheit sind die folgenden Informationen angegeben:
+
** Replikationsstatus: Nicht initialisiert, Synchron, oder Nicht synchron
** Welcher Cluster hostet die primäre Kopie
** Betriebskontext (wird für geplanten Failover verwendet)




Mit diesen ONTAP Mediator-Gesundheitsinformationen können Cluster zwischen verschiedenen Fehlertypen unterscheiden und feststellen, ob ein automatisches Failover durchgeführt werden soll. ONTAP Mediator ist neben beiden ONTAP Clustern (primär und sekundär) eine der drei Parteien im SnapMirror Aktiv-Sync-Quorum. Um einen Konsens zu erreichen, müssen mindestens zwei Parteien im Quorum einer bestimmten Operation zustimmen.


NOTE: Ab ONTAP 9.15.1 zeigt der System Manager den Status Ihrer SnapMirror Active Sync-Beziehung von beiden Clustern aus an. Auch der Status des ONTAP Mediators kann im System Manager von beiden Clustern aus überwacht werden. In früheren Versionen von ONTAP zeigt System Manager den Status von SnapMirror Aktiv/Aktiv-Synchronisierungsbeziehungen vom Quell-Cluster an.

.ONTAP Cloud Mediator
ONTAP Cloud Mediator ist ab ONTAP 9.17.1 verfügbar. ONTAP Cloud Mediator bietet die gleichen Dienste wie ONTAP Mediator, wird jedoch in der Cloud über die NetApp Console gehostet.

.Geplantes Failover
Ein manueller Vorgang zum Ändern der Rollen von Kopien in einer SnapMirror Aktiv/Aktiv-Synchronisierungsbeziehung. Der primäre Standort wird zum sekundären und der sekundäre zum primären.

.Automatisches ungeplantes Failover (AUFO)
Ein automatischer Vorgang zur Durchführung eines Failovers auf die Spiegelkopie. Der Vorgang erfordert die Unterstützung des ONTAP Mediators, um zu erkennen, dass die primäre Kopie nicht verfügbar ist.

.Primärwahl und Primär-Bias
SnapMirror active sync verwendet das Prinzip „Primär zuerst“, das der primären Kopie Vorrang bei der Bedienung von E/A-Vorgängen im Falle einer Netzwerkpartition einräumt.

Primär-Bias ist eine spezielle Quorum-Implementierung, die die Verfügbarkeit eines durch SnapMirror active sync geschützten Datensatzes verbessert. Wenn die primäre Kopie verfügbar ist, tritt Primär-Bias in Kraft, wenn der ONTAP Mediator von beiden Clustern aus nicht erreichbar ist.

Primary-first und Primary Bias werden in SnapMirror Aktiv/Sync SAN-Konfigurationen ab ONTAP 9.11.1 unterstützt. Primäre Kopien werden im System Manager festgelegt und mit der REST API und CLI ausgegeben.

.Nicht synchronisiert (OOS)
Wenn die Anwendungs-E/A nicht auf das sekundäre Speichersystem repliziert wird, wird dies als **nicht synchron** gemeldet. Ein „nicht synchron“-Status bedeutet, dass die sekundären Volumes nicht mit dem primären (Quell-)Volume synchronisiert sind und dass die SnapMirror Replizierung nicht erfolgt.

Wenn der Spiegelungsstatus  `Snapmirrored` ist, bedeutet dies, dass eine SnapMirror Beziehung hergestellt wurde und der Datentransfer abgeschlossen ist, das heißt, das Zielvolume ist auf dem neuesten Stand mit dem Quellvolume.

SnapMirror active sync unterstützt die automatische Resynchronisierung, sodass Kopien wieder in den InSync-Zustand versetzt werden können.

Ab ONTAP 9.15.1 unterstützt SnapMirror Active Sync link:interoperability-reference.html#fan-out-configurations["automatische Rekonfiguration in Fan-Out Konfigurationen"].

.Uniforme und nicht-uniforme Konfiguration
* **Einheitlicher Hostzugriff** bedeutet, dass Hosts beider Standorte mit allen Pfaden zu den Speicherclustern beider Standorte verbunden sind. Standortübergreifende Pfade werden über Entfernungen hinweg genutzt. Einheitlicher Hostzugriff gilt nur für SAN Konfigurationen.
* **Nicht-uniformer Hostzugriff** bedeutet, dass Hosts von jedem Standort nur mit dem Cluster am selben Standort verbunden sind. Standortübergreifende Pfade und gestreckte Pfade sind nicht verbunden.



NOTE: Einheitlicher Hostzugriff wird für jede SnapMirror active sync-Bereitstellung unterstützt, nicht-einheitlicher Hostzugriff wird nur für symmetrische Aktiv/Aktiv-Bereitstellungen unterstützt.

.Zero RPO
RPO steht für Recovery Point Objective, also das Maß an Datenverlust, das innerhalb eines bestimmten Zeitraums als akzeptabel gilt. Ein RPO von Null bedeutet, dass kein Datenverlust akzeptabel ist.

.Zero RTO
RTO steht für Recovery Time Objective, also das Wiederherstellungszeitziel, und bezeichnet die Zeitspanne, die als akzeptabel gilt, damit eine Anwendung nach einem Ausfall, Fehler oder einem anderen Datenverlustereignis unterbrechungsfrei wieder zum Normalbetrieb zurückkehrt. Zero RTO bedeutet, dass keinerlei Ausfallzeit akzeptabel ist.



[[snapmirror-active-sync-configuration-support-by-ontap-version]]
== SnapMirror Aktiv/Aktiv-Synchronisierungs-Konfigurationsunterstützung nach ONTAP Version

Die von SnapMirror active sync unterstützten Clustertypen, Protokolle und Konfigurationen variieren je nach Ihrer ONTAP Version. Die Tabelle zeigt die ONTAP Version, in der die Aktualisierungen hinzugefügt wurden, sowie die Konfigurationen, die diese Aktualisierungen unterstützen.

[cols="2*"]
|===
| ONTAP Version | Fügt Unterstützung für 


| 9.19.1 und später  a| 
* NFS
* SMB


NAS-Protokolle werden auf diesen Clustertypen unterstützt:

* AFF
* AFX




| 9.17.1 und später  a| 
* NVMe für VMware Host-Workloads




| 9.16.1 und später  a| 
* ASA r2, 2-Node Cluster
* Symmetrische Aktiv/Aktiv 4-Knoten zu 4-Knoten AFF oder ASA Cluster
+
Symmetrische Aktiv/Aktiv Konfigurationen unterstützen in ONTAP 9.16.1 und späteren Versionen neben 2-Knoten-zu-2-Knoten-Clustern auch 4-Knoten-zu-4-Knoten-Cluster.

+
Für ASA r2 werden nur 2-Node-zu-2-Node-Cluster unterstützt.





| 9.15.1 und später  a| 
Der folgende Konfigurationstyp:

* Symmetrisch Aktiv/Aktiv
+
Symmetrische Aktiv/Aktiv Konfigurationen unterstützen 2-Node-Cluster in ONTAP 9.15.1.





| 9.9.1 und später  a| 
* AFF
* ASA (nur C-Serie)


Protokolle:

* iSCSI
* FC


Konfigurationstypen:

* Asymmetrisch Aktiv/Aktiv


|===
Primäre und sekundäre Cluster müssen vom gleichen Typ sein: entweder link:../san-admin/learn-about-asa.html["ASA"], link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2"^] oder AFF.

Weitere Konfigurationsinformationen sind verfügbar unter:

* link:prerequisites-reference.html["SnapMirror Active Sync-Voraussetzungen"]
* link:limits-reference.html["SnapMirror Active Sync-Objektbeschränkungen"]

