---
sidebar: sidebar 
permalink: snapmirror-active-sync/monitor-task.html 
keywords: SM-BC, SMBC, monitoring, Mediator status, EMS, errors, planned failover status, automatic unplanned failover status, , snapmirror active sync 
summary: Es gibt mehrere SnapMirror Active Sync-Komponenten und -Vorgänge, die überwacht werden können. 
---
= ONTAP SnapMirror Active Sync-Vorgänge überwachen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können die folgenden SnapMirror active sync-Vorgänge überwachen, um den Zustand Ihrer SnapMirror active sync-Konfiguration sicherzustellen:

* ONTAP Mediator
* Geplante Failover-Vorgänge
* Automatische ungeplante Failover Operationen
* SnapMirror Active Sync-Verfügbarkeit



NOTE: Ab ONTAP 9.15.1 zeigt der System Manager den Status Ihrer SnapMirror Active Sync-Beziehung von beiden Clustern aus an. Auch der Status des ONTAP Mediators kann im System Manager von beiden Clustern aus überwacht werden.



[[ontap-mediator]]
== ONTAP Mediator

Während des normalen Betriebs sollte der ONTAP Mediator den Status „Verbunden“ aufweisen. Befindet er sich in einem anderen Status, kann dies auf eine Fehlerbedingung hinweisen. Die link:https://docs.netapp.com/us-en/ontap-ems-9131/sm-mediator-events.html["Meldungen des Event Management System (EMS)"^] kann überprüft werden, um den Fehler und geeignete Korrekturmaßnahmen zu bestimmen.



[[planned-failover-operations]]
== Geplante Failover-Vorgänge

Status und Fortschritt eines geplanten Failover-Vorgangs lassen sich mit dem  `snapmirror failover show` Befehl überwachen. Beispielsweise in einer SAN-Konfiguration:

....
ClusterB::> snapmirror failover start -destination-path vs1:/cg/dcg1
....
Sobald der Failover-Vorgang abgeschlossen ist, kann der SnapMirror-Schutzstatus vom neuen Ziel-Cluster aus überwacht werden. Beispiel:

....
ClusterA::> snapmirror show
....
In der link:https://docs.netapp.com/us-en/ontap-ems-9131/smbc-pfo-events.html["EMS-Referenz"^] finden sich Informationen zu Ereignismeldungen und Korrekturmaßnahmen.



[[automatic-unplanned-failover-operations]]
== Automatische ungeplante Failover Operationen

Während eines ungeplanten automatischen Failovers kann der Status des Vorgangs mit dem  `snapmirror failover show` Befehl überwacht werden.

....
ClusterB::> snapmirror failover show -instance
Start Time: 9/23/2020 22:03:29
         Source Path: vs1:/cg/scg3
    Destination Path: vs3:/cg/dcg3
     Failover Status: completed
        Error Reason:
            End Time: 9/23/2020 22:03:30
Primary Data Cluster: cluster-2
Last Progress Update: -
       Failover Type: unplanned
  Error Reason codes: -
....
In der link:https://docs.netapp.com/us-en/ontap-ems-9131/smbc-aufo-events.html["EMS-Referenz"^] finden sich Informationen zu Ereignismeldungen und Korrekturmaßnahmen.



[[snapmirror-active-sync-availability]]
== SnapMirror Active Sync-Verfügbarkeit

Die Verfügbarkeit der SnapMirror active sync-Beziehung lässt sich mithilfe einer Reihe von Befehlen entweder auf dem primären Cluster, dem sekundären Cluster oder auf beiden prüfen.

Zu den verwendeten Befehlen gehören der  `snapmirror mediator show` Befehl auf dem primären und sekundären Cluster, um den Verbindungs- und Quorumstatus zu überprüfen, der  `snapmirror show` Befehl und der  `volume show` Befehl. Beispiel:

....
SMBC_A::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.236.172.86    SMBC_B           connected         true

SMBC_B::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.236.172.86    SMBC_A           connected         true

SMBC_B::*> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs0:/cg/cg1 XDP  vs1:/cg/cg1_dp Snapmirrored Insync -         true    -
vs0:vol1    XDP  vs1:vol1_dp  Snapmirrored Insync   -         true    -
2 entries were displayed.

SMBC_A::*> volume show -fields is-smbc-master,smbc-consensus,is-smbc-failover-capable -volume vol1
vserver volume is-smbc-master is-smbc-failover-capable smbc-consensus
------- ------ -------------- ------------------------ --------------
vs0     vol1   true           false                    Consensus

SMBC_B::*> volume show -fields is-smbc-master,smbc-consensus,is-smbc-failover-capable -volume vol1_dp
vserver volume  is-smbc-master is-smbc-failover-capable smbc-consensus
------- ------- -------------- ------------------------ --------------
vs1     vol1_dp false          true                     No-consensus
....
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-failover-show.html["snapmirror failover show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-failover-start.html["SnapMirror Failover Start"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-mediator-show.html["snapmirror mediator show"^]

