---
sidebar: sidebar 
permalink: snapmirror-active-sync/monitor-task.html 
keywords: SM-BC, SMBC, monitoring, Mediator status, EMS, errors, planned failover status, automatic unplanned failover status, , snapmirror active sync 
summary: Es gibt mehrere SnapMirror Komponenten und Vorgänge für die aktive Synchronisierung, die Sie überwachen können. 
---
= Monitoring der aktiven SnapMirror Synchronisierungsvorgänge
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können die folgenden aktiven SnapMirror Synchronisierungsvorgänge überwachen, um den Zustand Ihrer SnapMirror Active Sync Konfiguration sicherzustellen:

* ONTAP Mediator
* Geplante Failover-Vorgänge
* Automatische ungeplante Failover-Vorgänge
* Verfügbarkeit der aktiven Synchronisierung von SnapMirror



NOTE: Ab ONTAP 9.15.1 zeigt System Manager den Status der SnapMirror Active Sync Beziehung von einem der Cluster aus an. Sie können den Status des ONTAP Mediators auch von einem der Cluster aus im System Manager überwachen.



== ONTAP Mediator

Während des normalen Betriebs sollte der ONTAP-Mediatorstatus verbunden sein. Wenn es sich in einem anderen Zustand befindet, kann dies auf einen Fehlerzustand hinweisen. Sie können die überprüfen link:https://docs.netapp.com/us-en/ontap-ems-9131/sm-mediator-events.html["EMS-Meldungen (Event Management System"^] Zur Bestimmung des Fehlers und der entsprechenden Korrekturmaßnahmen.



== Geplante Failover-Vorgänge

Mit dem können Sie den Status und den Status eines geplanten Failover-Vorgangs überwachen `snapmirror failover show` Befehl. Beispiel:

....
ClusterB::> snapmirror failover start -destination-path vs1:/cg/dcg1
....
Sobald der Failover-Vorgang abgeschlossen ist, können Sie den SnapMirror Sicherungsstatus vom neuen Ziel-Cluster aus überwachen. Beispiel:

....
ClusterA::> snapmirror show
....
Siehe link:https://docs.netapp.com/us-en/ontap-ems-9131/smbc-pfo-events.html["EMS-Referenz"^] Um Informationen zu Ereignismeldungen und Korrekturmaßnahmen zu erhalten.



== Automatische ungeplante Failover-Vorgänge

Während eines ungeplanten automatischen Failover können Sie mithilfe von den den den Status des Vorgangs überwachen `snapmirror failover show` Befehl.

....
ClusterB::> snapmirror failover show -instance
Start Time: 9/23/2020 22:03:29
         Source Path: vs1:/cg/scg3
    Destination Path: vs3:/cg/dcg3
     Failover Status: completed
        Error Reason:
            End Time: 9/23/2020 22:03:30
Primary Data Cluster: cluster-2
Last Progress Update: -
       Failover Type: unplanned
  Error Reason codes: -
....
Siehe link:https://docs.netapp.com/us-en/ontap-ems-9131/smbc-aufo-events.html["EMS-Referenz"^] Um Informationen zu Ereignismeldungen und zu Korrekturmaßnahmen zu erhalten.



== Verfügbarkeit der aktiven Synchronisierung von SnapMirror

Sie können die Verfügbarkeit der aktiven SnapMirror Synchronisierungsbeziehung mit einer Reihe von Befehlen überprüfen, entweder auf dem primären Cluster, dem sekundären Cluster oder beidem.

Die Befehle, die Sie verwenden, enthalten `snapmirror mediator show` Befehl für das primäre und das sekundäre Cluster, um den Status der Verbindung und des Quorum zu überprüfen, der `snapmirror show` Befehl, und das `volume show` Befehl. Beispiel:

....
SMBC_A::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.236.172.86    SMBC_B           connected         true

SMBC_B::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.236.172.86    SMBC_A           connected         true

SMBC_B::*> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs0:/cg/cg1 XDP  vs1:/cg/cg1_dp Snapmirrored Insync -         true    -
vs0:vol1    XDP  vs1:vol1_dp  Snapmirrored Insync   -         true    -
2 entries were displayed.

SMBC_A::*> volume show -fields is-smbc-master,smbc-consensus,is-smbc-failover-capable -volume vol1
vserver volume is-smbc-master is-smbc-failover-capable smbc-consensus
------- ------ -------------- ------------------------ --------------
vs0     vol1   true           false                    Consensus

SMBC_B::*> volume show -fields is-smbc-master,smbc-consensus,is-smbc-failover-capable -volume vol1_dp
vserver volume  is-smbc-master is-smbc-failover-capable smbc-consensus
------- ------- -------------- ------------------------ --------------
vs1     vol1_dp false          true                     No-consensus
....