---
sidebar: sidebar 
permalink: snapmirror-active-sync/network-port-requirements.html 
keywords: SM-BC, SMBC, SM-AS, restrictions, firewall, network ports, snapmirror active sync 
summary: ONTAP SnapMirror active sync Netzwerkanschlussanforderungen 
---
= Anforderungen an den Netzwerkanschluss
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror active sync-Replikation hat mehrere Netzwerkport-Anforderungen.

Beispielsweise muss jeder an der Replikation beteiligte Knoten den Zustand seiner Partnerknoten überwachen, die Replikationsaktivität steuern und die Daten selbst replizieren. Darüber hinaus muss der ONTAP Mediator bzw. ONTAP Cloud Mediator mit allen Knoten kommunizieren, um Quorumdienste bereitzustellen und beim Failover zu unterstützen. Alle diese Funktionen haben unterschiedliche Anforderungen an Endpunkte und Ports.

In den meisten Fällen wird die SnapMirror Active Sync-Replikation in einem internen Netzwerk ohne Port- oder zielbasierte Einschränkungen betrieben. Wenn der IP-Verkehr durch Firewalls, Router, Netzwerktopologie oder andere Mechanismen eingeschränkt wird, sollten die folgenden Konnektivitätsanforderungen überprüft werden.



== Kommunikation zwischen Knoten über Intercluster-/Peer-Verbindungen

|===
| Port | Quelle | Richtung | Ziel | Zweck 


| 3260/tcp | Intercluster-LIFs | beide | Intercluster-LIFs | LUN-Konsens 


 a| 
11104/tcp + 11105/tcp
| Intercluster-LIFs | beide | Intercluster-LIFs  a| 
Kommunikation zwischen Clustern

SnapMirror Datentransfer



| 443/tcp (HTTPS) | Intercluster-LIFs | beide | Intercluster-LIFs | Intercluster-Management 


| 10000/tcp  a| 
Cluster-Management-LIFs + Knoten-Management-LIFs
| beide | optional | Kommunikation mit Active IQ Unified Manager 
|===


== Kommunikation zwischen Mediator und Clusterknoten

|===
| Port | Quelle | Richtung | Ziel | Zweck 


| 22/tcp (SSH) | Management-Host(s) | Eingehend | ONTAP Mediator | ONTAP Mediator-Management 


| 31784/tcp (HTTPS) | Cluster-Management-LIFs | Eingehend | Web-Server ONTAP Mediator | REST API 


| 31784/tcp | Node-Management-LIFs | Eingehend | Web-Server ONTAP Mediator | Quorum-Dienst 
|===