---
sidebar: sidebar 
permalink: snapmirror-active-sync/volume-move-stuck-task.html 
keywords: SM-BC, SMBC, volume move, troubleshooting, primary down, snapmirror active sync 
summary: Es besteht die Möglichkeit, den Zero-RTO-SnapMirror synchronen Schutz zu entfernen und die SnapMirror Aktiv Sync-Beziehungskonfiguration zu löschen. 
---
= Die Volume-Verschiebungsoperation bleibt hängen, wenn der ONTAP Primärserver ausgefallen ist.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die folgenden Informationen sind relevant, wenn ein Volume-Verschiebungsvorgang im Status „Cutover Deferred“ auf unbestimmte Zeit festhängt, weil der primäre Standort in einer SnapMirror active sync Beziehung ausgefallen ist.

.Problem:
Ein Volume-Verschiebungsvorgang bleibt im Status „Aufgeschobene Umschaltung“ dauerhaft hängen, wenn der primäre Standort in einer SnapMirror active sync Beziehung ausgefallen ist. Wenn der primäre Standort ausgefallen ist, führt der sekundäre Standort ein automatisches ungeplantes Failover (AUFO) durch. Wenn ein Volume-Verschiebungsvorgang in Bearbeitung ist, wenn das AUFO ausgelöst wird, bleibt der Volume-Verschiebungsvorgang hängen.

.Lösung:
Die festhängende Volume-Verschiebungsinstanz wird abgebrochen und der Volume-Verschiebungsvorgang neu gestartet.
