---
sidebar: sidebar 
permalink: snapmirror-active-sync/volume-move-snapshot-task.html 
keywords: SM-BC, SMBC, volume move, troubleshooting, consistency group, Snapshot copy, snapmirror active sync 
summary: Nach einer Verschiebung eines Volumes wird der Referenz-Snapshot für die Verschiebung eines Volumes als der neueste für die SnapMirror Beziehung angezeigt. 
---
= Der Referenz-Snapshot für die Volume-Verschiebung wird als neuster SnapMirror-Snapshot für die ONTAP SnapMirror -Beziehung angezeigt.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Verwenden Sie die folgenden Informationen, wenn der Referenz-Snapshot der Volumeverschiebung nach einer Volumeverschiebungsoperation als der neueste für die SnapMirror -Beziehung angezeigt wird.

.Problem:
Nach Durchführung eines Volume-Verschiebungsvorgangs auf einem Konsistenzgruppenvolume wird der Referenz-Snapshot für Volume-Verschiebung möglicherweise fälschlicherweise als der neueste für die SnapMirror-Beziehung angezeigt.

Sie können den neuesten Snapshot mit dem folgenden Befehl anzeigen:

`snapmirror show -fields newest-snapshot status -expand`

.Lösung:
Führen Sie `snapmirror resync` nach Abschluss des Volume-Verschiebens manuell einen oder warten Sie auf die nächste automatische Neusynchronisierung.

.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["SnapMirror-Neusynchronisierung"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["Snapmirror-Show"^]

