---
permalink: smb-hyper-v-sql/create-ntfs-data-volumes-task.html 
sidebar: sidebar 
keywords: create, ntfs, data, volume, storage, virutal, machine, svm, smb, application, server, volume, configuration 
summary: Sie müssen NTFS-Datenvolumes auf der Storage Virtual Machine erstellen, bevor Sie permanent verfügbare Freigaben für die Verwendung mit Hyper-V- oder SQL Server-over-SMB-Anwendungsservern konfigurieren können. Das Arbeitsblatt zur Volume-Konfiguration dient zur Erstellung der Datenvolumes. 
---
= NTFS-Daten-Volumes erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NTFS-Datenvolumes müssen auf der Storage Virtual Machine (SVM) erstellt werden, bevor permanent verfügbare Freigaben für die Verwendung mit Hyper-V oder SQL Server over SMB-Anwendungsservern konfiguriert werden können. Das Arbeitsblatt zur Volume-Konfiguration dient zur Erstellung der Datenvolumes.

.Über diese Aufgabe
Es gibt optionale Parameter, mit denen Sie ein Datenvolume anpassen können. Weitere Informationen zum Anpassen von Volumes finden Sie im link:../volumes/index.html["Logische Speicherverwaltung"].

Beim Erstellen Ihrer Datenvolumes sollten keine Verbindungspunkte innerhalb eines Volumes erstellt werden, das Folgendes enthält:

* Hyper-V-Dateien, für die ONTAP Schattenkopien erstellt
* SQL Server Datenbankdateien, die mit SQL Server gesichert werden


[NOTE]
====
Wenn Sie versehentlich ein Volume mit gemischtem oder UNIX-Sicherheitsstil erstellen, können Sie das Volume nicht in ein NTFS-Sicherheitsstil-Volume ändern und anschließend direkt für die Erstellung kontinuierlich verfügbarer Freigaben für unterbrechungsfreie Vorgänge verwenden. Unterbrechungsfreie Vorgänge für Hyper-V und SQL Server über SMB funktionieren nur dann korrekt, wenn die in der Konfiguration verwendeten Volumes als NTFS-Sicherheitsstil-Volumes erstellt wurden. Entweder muss das Volume gelöscht und mit NTFS-Sicherheitsstil neu erstellt werden, oder das Volume kann auf einem Windows-Host eingebunden und eine ACL am Anfang des Volumes angewendet sowie auf alle Dateien und Ordner im Volume übertragen werden.

====
.Schritte
. Das Datenvolume wird durch Eingabe des entsprechenden Befehls erstellt:
+
[cols="1, 4"]
|===
| Wenn Sie ein Volume in einer SVM erstellen möchten, in der der Root-Volume-Sicherheitsstil... | Geben Sie den Befehl ein... 


 a| 
NTFS
 a| 
`*volume create -vserver _vserver_name_ -volume _volume_name_ -aggregate _aggregate_name_ -size integer[KB{vbar}MB{vbar}GB{vbar}TB{vbar}PB] -junction-path _path_*`



 a| 
Nicht NTFS
 a| 
`*volume create -vserver _vserver_name_ -volume _volume_name_ -aggregate _aggregate_name_ -size integer[KB{vbar}MB{vbar}GB{vbar}TB{vbar}PB]-security-style ntfs -junction-path path*`

|===
. Es sollte überprüft werden, ob die Volumenkonfiguration korrekt ist:
+
`*volume show -vserver _vserver_name_ -volume _volume_name_*`


