---
permalink: smb-hyper-v-sql/enable-disable-vss-shadow-copies-backups-task.html 
sidebar: sidebar 
keywords: enable, disable, vss, aware, backup, hyper, v, virtual, machine, files, smb, shares, shadow, copy 
summary: Wenn Sie eine VSS-fähige Sicherungsanwendung zum Sichern von Hyper-V-VM-Dateien verwenden, die auf SMB-Freigaben gespeichert sind, muss die VSS-Schattenkopie aktiviert sein. Die VSS-Schattenkopie kann deaktiviert werden, wenn keine VSS-fähigen Sicherungsanwendungen verwendet werden. Standardmäßig ist die VSS-Schattenkopie aktiviert. 
---
= VSS-Schattenkopien für Hyper-V über SMB Backups aktivieren oder deaktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie eine VSS-fähige Sicherungsanwendung zum Sichern von Hyper-V-VM-Dateien verwenden, die auf SMB-Freigaben gespeichert sind, muss die VSS-Schattenkopie aktiviert sein. Die VSS-Schattenkopie kann deaktiviert werden, wenn keine VSS-fähigen Sicherungsanwendungen verwendet werden. Standardmäßig ist die VSS-Schattenkopie aktiviert.

.Über diese Aufgabe
Sie können VSS Schattenkopien jederzeit aktivieren oder deaktivieren.

.Schritte
. Stellen Sie die Berechtigungsstufe auf „Erweitert“ ein:
+
`*set -privilege advanced*`

. Führen Sie eine der folgenden Aktionen aus:
+
|===
| Wenn Sie möchten, dass VSS-Schattenkopien... | Geben Sie den Befehl ein... 


 a| 
Aktiviert
 a| 
`*vserver cifs options modify -vserver _vserver_name_ -shadowcopy-enabled true*`



 a| 
Deaktiviert
 a| 
`*vserver cifs options modify -vserver _vserver_name_ -shadowcopy-enabled false*`

|===
. Zurück zur Administrator-Privilegstufe:
+
`*set -privilege admin*`



.Beispiel
Die folgenden Befehle aktivieren VSS-Schattenkopien auf SVM vs1:

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options modify -vserver vs1 -shadowcopy-enabled true

cluster1::*> set -privilege admin
----