---
permalink: smb-hyper-v-sql/health-monitoring-nondisruptive-operation-concept.html 
sidebar: sidebar 
keywords: health, monitoring, nondisruptive, operation, status, healthy, ndo, hyper, v, sql, server, recovery, cluster, system 
summary: Die Systemzustandsüberwachung liefert Informationen zum Systemzustand im gesamten Cluster. Die Systemzustandsüberwachung überwacht Hyper-V- und SQL Server-over-SMB-Konfigurationen, um unterbrechungsfreien Betrieb der Anwendungsserver zu gewährleisten. Bei einem beeinträchtigten Status können Sie Details zum Problem einsehen, einschließlich der wahrscheinlichen Ursache und empfohlener Wiederherstellungsmaßnahmen. 
---
= Mit der Gesundheitsüberwachung lässt sich feststellen, ob der unterbrechungsfreie Betriebszustand gesund ist.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Systemzustandsüberwachung liefert Informationen zum Systemzustand im gesamten Cluster. Die Zustandsüberwachung überwacht Hyper-V- und SQL Server-over-SMB-Konfigurationen, um unterbrechungsfreie Vorgänge (NDOs) für die Anwendungsserver sicherzustellen. Bei einem beeinträchtigten Status können Sie Details zum Problem einsehen, einschließlich der wahrscheinlichen Ursache und empfohlener Wiederherstellungsmaßnahmen.

Es gibt mehrere Systemzustandsmonitore. ONTAP überwacht sowohl den allgemeinen Systemzustand als auch den Zustand einzelner Systemzustandsmonitore. Der Systemzustandsmonitor für die Knotenkonnektivität umfasst das CIFS-NDO-Subsystem. Der Monitor verfügt über eine Reihe von Richtlinien, die Warnmeldungen auslösen, wenn bestimmte physikalische Bedingungen zu Störungen führen können, und wenn eine Störung vorliegt, werden Warnmeldungen generiert und Informationen zu Korrekturmaßnahmen bereitgestellt. Für NDO over SMB Konfigurationen werden Warnmeldungen für die folgenden beiden Bedingungen generiert:

|===
| Alarm-ID | Schwere | Zustand 


 a| 
`*HaNotReadyCifsNdo_Alert*`
 a| 
Wesentlich
 a| 
Eine oder mehrere Dateien, die von einem Volume in einem Aggregat auf dem Knoten gehostet werden, wurden über eine kontinuierlich verfügbare SMB-Freigabe mit dem Versprechen der Persistenz im Falle eines Ausfalls geöffnet; die HA-Beziehung mit dem Partner ist jedoch entweder nicht konfiguriert oder nicht funktionsfähig.



 a| 
`*NoStandbyLifCifsNdo_Alert*`
 a| 
Geringfügig
 a| 
Die Storage Virtual Machine (SVM) stellt aktiv Daten über SMB über einen Knoten bereit, und es sind SMB-Dateien persistent über kontinuierlich verfügbare Freigaben geöffnet; der Partnerknoten stellt jedoch keine aktiven Daten-LIFs für die SVM bereit.

|===