---
permalink: smb-hyper-v-sql/licensing-requirements-concept.html 
sidebar: sidebar 
keywords: ontap, license, requirement, nondisruptive, hyper, v, smb, sql, server 
summary: Bei der Erstellung von SQL Server oder Hyper-V über SMB-Lösungen müssen Sie bestimmte ONTAP- und Lizenzierungsanforderungen beachten, um den unterbrechungsfreien Betrieb auf SVMs zu gewährleisten. 
---
= ONTAP- und Lizenzierungsanforderungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Erstellung von SQL Server oder Hyper-V über SMB-Lösungen müssen Sie bestimmte ONTAP- und Lizenzierungsanforderungen beachten, um den unterbrechungsfreien Betrieb auf SVMs zu gewährleisten.



== ONTAP-Versionsanforderungen

* Hyper-V über SMB
+
ONTAP unterstützt den unterbrechungsfreien Betrieb über SMB-Freigaben für Hyper-V unter Windows 2012 oder höher.

* SQL Server über SMB
+
ONTAP unterstützt den unterbrechungsfreien Betrieb über SMB-Freigaben für SQL Server 2012 oder höher unter Windows 2012 oder höher.



Aktuelle Informationen zu unterstützten Versionen von ONTAP, Windows Server und SQL Server für unterbrechungsfreien Betrieb über SMB-Freigaben finden Sie in der Interoperabilitäts-Matrix.

https://["NetApp Interoperabilitäts-Matrix-Tool"^]



== Lizenzierungsanforderungen

Die folgenden Lizenzen sind erforderlich:

* CIFS
* FlexClone (nur für Hyper-V über SMB)
+
Diese Lizenz ist erforderlich, wenn Remote VSS für Backups verwendet wird. Der Shadow Copy Service verwendet FlexClone, um zeitpunktgenaue Kopien von Dateien zu erstellen, die dann bei der Erstellung eines Backups verwendet werden.

+
Eine FlexClone Lizenz ist optional, wenn Sie eine Backup-Methode verwenden, die kein Remote VSS verwendet.


