---
permalink: smb-hyper-v-sql/nondisruptive-operations-glossary-concept.html 
sidebar: sidebar 
keywords: key, concepts, nondisruptive, operation, hyper, v, sql, server, smb, configure 
summary: 'Es gibt bestimmte Konzepte zum unterbrechungsfreien Betrieb (NDOS), die Sie verstehen sollten, bevor Sie Ihre Hyper-V oder SQL Server over SMB-Lösung konfigurieren.' 
---
= Wichtige Konzepte zum unterbrechungsfreien Betrieb von Hyper-V und SQL Server over SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es gibt bestimmte Konzepte zum unterbrechungsfreien Betrieb (NDOS), die Sie verstehen sollten, bevor Sie Ihre Hyper-V oder SQL Server over SMB-Lösung konfigurieren.

* *Kontinuierlich verfügbarer Share*
+
Ein SMB 3.0-Share mit kontinuierlich verfügbarer Share-Eigenschaft. Kunden, die sich über kontinuierlich verfügbare Shares verbinden, können störenden Ereignissen wie Takeover, Giveback und Aggregatverschiebung standhalten.

* *Knoten*
+
Ein einziger Controller, der Mitglied eines Clusters ist. Um zwischen den beiden Knoten in einem SFO-Paar zu unterscheiden, wird ein Node manchmal als „_local Node_“ bezeichnet, und der andere Node wird manchmal „_Partner Node_“ oder „_Remote Node_“ genannt. Der primäre Eigentümer des Storage ist der lokale Knoten. Der sekundäre Besitzer, der bei einem Ausfall des primären Eigentümers die Kontrolle über den Storage übernimmt, ist der Partner-Node. Jeder Node ist der primäre Storage-Eigentümer und sekundärer Eigentümer für Storage-Lösungen seiner Partner.

* *Unterbrechungsfreie Aggregatverschiebung*
+
Die Möglichkeit, ein Aggregat zwischen Partner-Nodes innerhalb eines SFO-Paars in einem Cluster zu verschieben, ohne Client-Applikationen zu unterbrechen.

* * Unterbrechungsfreier Failover*
+
Siehe _Übernahme_.

* *Unterbrechungsfreie LIF-Migration*
+
Die Möglichkeit zur Durchführung einer LIF-Migration, ohne dass Client-Applikationen unterbrochen werden, die über diese LIF mit dem Cluster verbunden sind. Bei SMB-Verbindungen ist dies nur für Clients möglich, die eine Verbindung mit SMB 2.0 oder höher herstellen.

* *Unterbrechungsfreier Betrieb*
+
Durchführung umfangreicher ONTAP-Management- und Upgrade-Vorgänge sowie die Möglichkeit, Node-Ausfälle ohne Unterbrechung von Client-Applikationen zu bewältigen. Dieser Begriff bezieht sich auf die Sammlung von Funktionen für die unterbrechungsfreie Übernahme, unterbrechungsfreie Upgrades und die unterbrechungsfreie Migration insgesamt.

* * Unterbrechungsfreies Upgrade*
+
Upgrade von Node-Hardware oder -Software ohne Applikationsunterbrechung

* *Unterbrechungsfreie Volume-Verschiebung*
+
Volume kann frei im gesamten Cluster verschoben werden, ohne dass dazu Applikationen unterbrochen werden, die das Volume verwenden. Bei SMB-Verbindungen unterstützen alle SMB-Versionen unterbrechungsfreie Verschiebung von Volumes.

* * Persistente Griffe*
+
Eine Eigenschaft von SMB 3.0, die kontinuierlich verfügbare Verbindungen ermöglicht, um bei einer Unterbrechung transparent eine Verbindung zum CIFS-Server herzustellen. Ähnlich wie bei langlebigen Griffen werden vom CIFS-Server persistente Griffe über einen Zeitraum gewartet, nachdem die Kommunikation mit dem verbundenen Client verloren gegangen ist. Die persistenten Griffe sind jedoch widerstandsfähiger als die langlebigen Griffe. Der CIFS-Server bietet dem Kunden nicht nur die Möglichkeit, den Griff nach der erneuten Verbindung innerhalb eines 60-sekündigen Fensters zurückzufordern, sondern verweigert auch den Zugriff auf alle anderen Clients, die während dieses 60-Sekunden-Fensters Zugriff auf die Datei anfordern.

+
Informationen zu persistenten Griffen werden auf dem persistenten Storage des SFO-Partners gespiegelt, wodurch Clients mit getrennten persistenten Griffen die langlebigen Griffe zurückgewinnen können, nachdem ein Ereignis, bei dem der SFO-Partner die Verantwortung für den Storage des Nodes übernimmt, übernommen hat. Neben dem unterbrechungsfreien Betrieb für Vorgänge bei LIF-Verschiebungen (die dauerhafte Unterstützung bieten) sorgen persistente Griffe für unterbrechungsfreien Betrieb bei Takeover, Giveback und Aggregatverschiebung.

* *SFO-Rückübertragung*
+
Die Aggregate werden an den eigenen Standorten zurückgegeben, wenn eine Wiederherstellung nach einem Takeover-Ereignis durchgeführt wird.

* *SFO-Paar*
+
Ein Node-Paar, dessen Controller so konfiguriert sind, dass er Daten füreinander bereitstellt, wenn einer der beiden Nodes nicht mehr funktioniert. Je nach Systemmodell können beide Controller sich in einem einzelnen Chassis befinden oder sich die Controller in einem separaten Chassis befinden. Bekannt als HA-Paar in einem Cluster mit zwei Nodes.

* *Übernahme*
+
Der Prozess, durch den der Partner die Kontrolle über den Storage übernimmt, wenn der primäre Eigentümer dieses Speichers ausfällt. Im Zusammenhang mit SFO sind Failover und Takeover gleichbedeutend.


