---
permalink: smb-hyper-v-sql/odx-copy-offload-requirements-concept.html 
sidebar: sidebar 
keywords: odx, copy, offload, requirements, sql, server, hyper, v, smb, virtual 
summary: ODX Copy Offload muss aktiviert sein, wenn virtuelle Maschinen-Dateien migriert oder Datenbankdateien direkt vom Quell- zum Zielspeicherort exportiert und importiert werden sollen, ohne dass die Daten über die Anwendungsserver übertragen werden. Es bestehen bestimmte Anforderungen im Zusammenhang mit der Verwendung von ODX Copy Offload mit SQL Server und Hyper-V über SMB-Lösungen, die zu berücksichtigen sind. 
---
= ODX-Kopierauslagerungsanforderungen für SQL Server und Hyper-V über SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ODX Copy Offload muss aktiviert sein, wenn virtuelle Maschinen-Dateien migriert oder Datenbankdateien direkt vom Quell- zum Zielspeicherort exportiert und importiert werden sollen, ohne dass die Daten über die Anwendungsserver übertragen werden. Es bestehen bestimmte Anforderungen im Zusammenhang mit der Verwendung von ODX Copy Offload mit SQL Server und Hyper-V über SMB-Lösungen, die zu berücksichtigen sind.

Die Verwendung von ODX Copy Offload bietet einen deutlichen Leistungsvorteil. Diese CIFS-Server-Option ist standardmäßig aktiviert.

* SMB 3.0 muss aktiviert sein, um ODX Copy Offload verwenden zu können.
* Die Quellvolumes müssen mindestens 1,25 GB groß sein.
* Die Deduplizierung muss auf Volumes aktiviert sein, die mit Copy Offload verwendet werden.
* Bei Verwendung komprimierter Volumes muss der Komprimierungstyp adaptiv sein und es wird nur die Komprimierungsgruppengröße 8K unterstützt.
+
Sekundärer Kompressionstyp wird nicht unterstützt

* Um ODX Copy Offload für die Migration von Hyper-V-Gästen innerhalb und zwischen Festplatten zu nutzen, müssen die Hyper-V-Server für die Verwendung von SCSI-Festplatten konfiguriert sein.
+
Standardmäßig werden IDE-Festplatten konfiguriert, aber ODX Copy Offload funktioniert nicht, wenn Gäste migriert werden, wenn Festplatten mit IDE-Festplatten erstellt wurden.


