---
permalink: smb-hyper-v-sql/remote-vss-considerations-concept.html 
sidebar: sidebar 
keywords: remote, vss, consideration, hyper, v, smb, configuration, backup, solution, automatic, recovery, shadow, copy 
summary: Bei der Verwendung von Remote VSS-fähigen Backup-Lösungen für Hyper-V over SMB-Konfigurationen sind bestimmte Aspekte zu berücksichtigen. 
---
= Überlegungen zu Remote VSS für Hyper-V over SMB Konfigurationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Verwendung von Remote VSS-fähigen Backup-Lösungen für Hyper-V over SMB-Konfigurationen sind bestimmte Aspekte zu berücksichtigen.



[[general-remote-vss-considerations]]
== Allgemeine Überlegungen zu Remote VSS

* Pro Microsoft-Anwendungsserver können maximal 64 Freigaben konfiguriert werden.
+
Der Schattenkopievorgang schlägt fehl, wenn ein Schattenkopiesatz mehr als 64 Freigaben enthält. Dies ist eine Anforderung von Microsoft.

* Pro CIFS-Server ist nur ein aktiver Schattenkopiesatz zulässig.
+
Ein Schattenkopievorgang schlägt fehl, wenn auf demselben CIFS-Server bereits ein Schattenkopievorgang ausgeführt wird. Dies ist eine Anforderung von Microsoft.

* Innerhalb der Verzeichnisstruktur, auf der Remote VSS eine Schattenkopie erstellt, sind keine Verbindungen zulässig.
+
** Im Fall der automatischen Wiederherstellung schlägt die Erstellung der Schattenkopie fehl, wenn beim Durchlaufen der Freigabe eine Verbindung angetroffen wird.
** Im Fall der nichtautomatischen Wiederherstellung schlägt die Erstellung der Schattenkopie nicht fehl, aber die Verbindung verweist auf nichts.






[[remote-vss-considerations-that-apply-only-for-shadow-copies-with-automatic-recovery]]
== Remote VSS Überlegungen, die nur für Schattenkopien mit automatischer Wiederherstellung gelten

Bestimmte Einschränkungen gelten nur für Schattenkopien mit automatischer Wiederherstellung.

* Für die Erstellung von Schattenkopien ist eine maximale Verzeichnistiefe von fünf Unterverzeichnissen zulässig.
+
Dies ist die Verzeichnistiefe, über die der Schattenkopiedienst einen Schattenkopie-Backup-Satz erstellt. Die Erstellung der Schattenkopie schlägt fehl, wenn Verzeichnisse, die virtuelle Maschinen-Dateien enthalten, tiefer als fünf Ebenen verschachtelt sind. Dies soll die Verzeichnisdurchquerung beim Klonen der Freigabe begrenzen. Die maximale Verzeichnistiefe kann durch eine CIFS-Server-Option geändert werden.

* Der verfügbare Platz im Volume muss ausreichend sein.
+
Der verfügbare Speicherplatz muss mindestens so groß sein wie der gesamte Speicherplatz, der von allen Dateien, Verzeichnissen und Unterverzeichnissen innerhalb der in den Schattenkopie Backup-Satz einbezogenen Freigaben belegt wird.

* Innerhalb der Verzeichnisstruktur, auf der Remote VSS eine Schattenkopie erstellt, sind keine Links oder nicht reguläre Dateien zulässig.
+
Die Erstellung der Schattenkopie schlägt fehl, wenn sich im freigegebenen Verzeichnis Verknüpfungen oder nicht reguläre Dateien befinden, die zur Schattenkopie führen. Der Klonvorgang unterstützt sie nicht.

* Für Verzeichnisse sind keine NFSv4-ACLs zulässig.
+
Obwohl bei der Erstellung von Schattenkopien die NFSv4-ACLs für Dateien erhalten bleiben, gehen die NFSv4-ACLs für Verzeichnisse verloren.

* Für die Erstellung eines Schattenkopiesatzes sind maximal 60 Sekunden zulässig.
+
Die Microsoft-Spezifikationen erlauben maximal 60 Sekunden für die Erstellung des Schattenkopiesatzes. Wenn der VSS-Client den Schattenkopiesatz innerhalb dieser Zeit nicht erstellen kann, schlägt der Schattenkopie-Vorgang fehl; daher ist die Anzahl der Dateien in einem Schattenkopiesatz begrenzt. Die tatsächliche Anzahl der Dateien oder virtuellen Maschinen, die in einen Backup-Satz aufgenommen werden können, variiert; diese Zahl hängt von vielen Faktoren ab und muss für jede Kundenumgebung bestimmt werden.


