---
permalink: smb-hyper-v-sql/server-volume-requirements-hyper-v-concept.html 
sidebar: sidebar 
keywords: smb, cifs, server, volume, requirements, hyper, v, configuration, nondisruptive, operation 
summary: Bei der Erstellung von Hyper-V over SMB Konfigurationen für unterbrechungsfreie Operationen sind bestimmte Anforderungen an den SMB-Server und das Volume zu berücksichtigen. 
---
= SMB-Server und Volumenanforderungen für Hyper-V über SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Erstellung von Hyper-V over SMB Konfigurationen für unterbrechungsfreie Operationen sind bestimmte Anforderungen an den SMB-Server und das Volume zu berücksichtigen.



[[smb-server-requirements]]
== Anforderungen an SMB Server

* SMB 3.0 muss aktiviert sein.
+
Diese Funktion ist standardmäßig aktiviert.

* Die Standard-UNIX-Benutzeroption für den CIFS-Server muss mit einem gültigen UNIX-Benutzerkonto konfiguriert sein.
+
Die Anwendungsserver verwenden das Computerkonto beim Aufbau einer SMB-Verbindung. Da jeder SMB-Zugriff voraussetzt, dass der Windows-Benutzer erfolgreich einem UNIX-Benutzerkonto oder dem Standard-UNIX-Benutzerkonto zugeordnet wird, muss ONTAP das Computerkonto des Anwendungsservers dem Standard-UNIX-Benutzerkonto zuordnen können.

* Automatische Knotenweiterleitungen müssen deaktiviert sein (diese Funktion ist standardmäßig deaktiviert).
+
Wenn automatische Knotenverweise für den Zugriff auf andere Daten als Hyper-V Maschinendateien verwendet werden sollen, ist eine separate SVM für diese Daten zu erstellen.

* Sowohl Kerberos- als auch NTLM-Authentifizierung müssen in der Domäne, zu der der SMB-Server gehört, zugelassen sein.
+
ONTAP bewirbt den Kerberos-Dienst für Remote VSS nicht, daher sollte die Domäne so eingestellt werden, dass NTLM zugelassen wird.

* Die Schattenkopie-Funktionalität muss aktiviert sein.
+
Diese Funktion ist standardmäßig aktiviert.

* Das Windows-Domänenkonto, das der Schattenkopiedienst beim Erstellen von Schattenkopien verwendet, muss Mitglied der lokalen Gruppe BUILTIN\Administrators oder BUILTIN\Backup Operators des SMB-Servers sein.




[[volume-requirements]]
== Volumenanforderungen

* Volumes, die zur Speicherung von Dateien virtueller Maschinen verwendet werden, müssen als NTFS Security-Style-Volumes erstellt werden.
+
Um NDOs für Anwendungsserver mit permanent verfügbaren SMB-Verbindungen bereitzustellen, muss das Volume, das die Freigabe enthält, ein NTFS-Volume sein. Es muss außerdem immer ein NTFS-Volume gewesen sein. Ein Volume mit gemischtem Sicherheitsstil oder UNIX-Sicherheitsstil kann nicht in ein NTFS-Sicherheitsstil-Volume umgewandelt und direkt für NDOs über SMB-Freigaben verwendet werden. Wenn ein Volume mit gemischtem Sicherheitsstil in ein NTFS-Sicherheitsstil-Volume geändert wird und für NDOs über SMB-Freigaben genutzt werden soll, muss eine ACL manuell am Anfang des Volumes gesetzt und auf alle enthaltenen Dateien und Ordner übertragen werden. Andernfalls können Migrationen virtueller Maschinen oder Datenbankdateiexporte und -importe, bei denen Dateien auf ein anderes Volume verschoben werden, fehlschlagen, wenn entweder das Quell- oder das Zielvolume ursprünglich als Volume mit gemischtem oder UNIX-Sicherheitsstil erstellt und später in den NTFS-Sicherheitsstil geändert wurde.

* Damit Schattenkopie-Operationen erfolgreich sind, muss auf dem Volume genügend Speicherplatz verfügbar sein.
+
Der verfügbare Speicherplatz muss mindestens so groß sein wie der gesamte Speicherplatz, der von allen Dateien, Verzeichnissen und Unterverzeichnissen innerhalb der in den Schattenkopie Backup-Satz einbezogenen Freigaben belegt wird. Diese Anforderung gilt nur für Schattenkopien mit automatischer Wiederherstellung.



.Verwandte Informationen
http://technet.microsoft.com/en-us/library/["Microsoft TechNet Bibliothek: technet.microsoft.com/en-us/library/"]
