---
permalink: smb-hyper-v-sql/share-based-backups-remote-vss-concept.html 
sidebar: sidebar 
keywords: share, based, backups, remote, vss, cif, server, hyper, v, virtual, machine, file 
summary: Remote VSS kann verwendet werden, um freigabebasierte Backups von Hyper-V-VM-Dateien durchzuführen, die auf einem CIFS-Server gespeichert sind. 
---
= Übersicht über freigabebasierte Backups mit Remote VSS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Remote VSS kann verwendet werden, um freigabebasierte Backups von Hyper-V-VM-Dateien durchzuführen, die auf einem CIFS-Server gespeichert sind.

Microsoft Remote VSS (Volume Shadow Copy Services) ist eine Erweiterung der bestehenden Microsoft VSS-Infrastruktur. Mit Remote VSS hat Microsoft die VSS-Infrastruktur erweitert, um die Schattenkopie von SMB-Freigaben zu unterstützen. Zusätzlich können Serveranwendungen wie Hyper-V VHD-Dateien auf SMB-Dateifreigaben speichern. Mit diesen Erweiterungen ist es möglich, applikationskonsistente Schattenkopien für virtuelle Maschinen zu erstellen, die Daten- und Konfigurationsdateien auf Freigaben speichern.
