---
permalink: smb-hyper-v-sql/smb-share-config-worksheet-reference.html 
sidebar: sidebar 
keywords: complete, smb, share, configuration, worksheet, information, settings 
summary: Dieses Arbeitsblatt dient dazu, die Werte zu erfassen, die beim Erstellen von kontinuierlich verfügbaren SMB-Freigaben für SQL Server und Hyper-V über SMB Konfigurationen benötigt werden. 
---
= Das Arbeitsblatt zur SMB-Freigabekonfiguration ausfüllen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dieses Arbeitsblatt dient dazu, die Werte zu erfassen, die beim Erstellen von kontinuierlich verfügbaren SMB-Freigaben für SQL Server und Hyper-V über SMB Konfigurationen benötigt werden.



[[information-about-smb-shares-properties-and-configuration-settings]]
== Informationen zu den Eigenschaften und Konfigurationseinstellungen von SMB-Freigaben

Für jede Freigabe müssen Sie die folgenden Informationen angeben:

* Name der Storage Virtual Machine (SVM)
+
Der SVM-Name ist für alle Shares gleich.

* Freigabename
* Pfad
* Freigabeeigenschaften
+
Sie müssen die folgenden beiden Freigabeeigenschaften konfigurieren:

+
** `oplocks`
** `continuously-available`




Die folgenden Eigenschaften der Freigabe dürfen nicht festgelegt werden:

* `homedirectory attributecache`
* `branchcache`
* `access-based-enumeration`
+
** Symlinks müssen deaktiviert sein (der Wert für den  `-symlink-properties` Parameter muss null [""] sein).






[[information-about-share-paths]]
== Informationen zu Freigabepfaden

Wenn Sie Remote VSS zum Sichern von Hyper-V-Dateien verwenden, ist die Wahl der Freigabepfade für die SMB-Verbindungen von den Hyper-V-Servern zu den Speicherorten, an denen die Dateien der virtuellen Maschinen gespeichert sind, wichtig. Freigaben können zwar an jeder beliebigen Stelle im Namespace erstellt werden, jedoch sollten die Pfade der von den Hyper-V-Servern verwendeten Freigaben keine Verbindung-Volumes enthalten. Schattenkopie-Vorgänge können nicht auf Freigabepfaden durchgeführt werden, die Verbindungspunkte enthalten.

SQL Server kann beim Erstellen der Datenbankverzeichnisstruktur keine Verbindungen überqueren. Für SQL Server sollten keine Freigabepfade erstellt werden, die Verbindungspunkte enthalten.

Beispielsweise sollte, ausgehend vom angezeigten Namespace, wenn virtuelle Maschinendateien oder Datenbankdateien auf den Volumes "`vol1`", "`vol2`", "`vol3`" und "`vol4`" gespeichert werden sollen, für die Anwendungsserver Freigaben unter den folgenden Pfaden erstellt werden: `/data1/vol1`, `/data1/vol2`, `/data2/vol3` und `/data2/vol4`.

[listing]
----

                     Junction                       Junction
Vserver Volume       Active   Junction Path         Path Source
------- ------------ -------- -------------------   -----------
vs1     data1         true     /data1               RW_volume
vs1     vol1          true     /data1/vol1          RW_volume
vs1     vol2          true     /data1/vol2          RW_volume
vs1     data2         true     /data2               RW_volume
vs1     vol3          true     /data2/vol3          RW_volume
vs1     vol4          true     /data2/vol4          RW_volume
----
[NOTE]
====
Obwohl Sie Freigaben auf den  `/data1` und  `/data2` Pfaden für die administrative Verwaltung erstellen können, sollten die Anwendungsserver nicht so konfiguriert werden, dass sie diese Freigaben zum Speichern von Daten verwenden.

====


[[planning-worksheet]]
== Planungsarbeitsblatt

|===
| Informationsarten | Werte 


 a| 
_Band 1: Name und Pfad der SMB-Freigabe_
 a| 



 a| 
_Band 2: Name und Pfad der SMB-Freigabe_
 a| 



 a| 
_Band 3: Name und Pfad der SMB-Freigabe_
 a| 



 a| 
_Band 4: Name und Pfad der SMB-Freigabe_
 a| 



 a| 
_Band 5: Name und Pfad der SMB-Freigabe_
 a| 



 a| 
_Band 6: Name und Pfad der SMB-Freigabe_
 a| 



 a| 
_Band 7: Name und Pfad der SMB-Freigabe_
 a| 



 a| 
_Zusätzliche Volumes: SMB-Freigabenamen und -Pfade_
 a| 

|===