---
permalink: smb-hyper-v-sql/verify-continuously-available-share-config-task.html 
sidebar: sidebar 
keywords: verify, continuously, available, smb, share, configuration, hyper, v, sql, server, nondisruptive, application 
summary: Um unterbrechungsfreie Vorgänge zu unterstützen, müssen Hyper-V und SQL Server SMB-Freigaben als kontinuierlich verfügbare Freigaben konfiguriert werden. Zusätzlich gibt es bestimmte weitere Freigabeeinstellungen, die überprüft werden sollten. Es sollte sichergestellt werden, dass die Freigaben ordnungsgemäß konfiguriert sind, um nahtlose unterbrechungsfreie Vorgänge für die Anwendungsserver bei geplanten oder ungeplanten Störungen zu ermöglichen. 
---
= Die Konfiguration der kontinuierlich verfügbaren SMB-Freigabe überprüfen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um unterbrechungsfreie Vorgänge zu unterstützen, müssen Hyper-V und SQL Server SMB-Freigaben als kontinuierlich verfügbare Freigaben konfiguriert werden. Zusätzlich gibt es bestimmte weitere Freigabeeinstellungen, die überprüft werden sollten. Es sollte sichergestellt werden, dass die Freigaben ordnungsgemäß konfiguriert sind, um nahtlose unterbrechungsfreie Vorgänge für die Anwendungsserver bei geplanten oder ungeplanten Störungen zu ermöglichen.

.Über diese Aufgabe
Es ist zu überprüfen, ob die folgenden beiden Freigabeparameter korrekt eingestellt sind:

* Der  `-offline-files` Parameter ist entweder auf  `manual` (Standardwert) oder  `none` gesetzt.
* Symlinks müssen deaktiviert sein.


Für einen ordnungsgemäßen unterbrechungsfreien Betrieb müssen die folgenden Eigenschaften der Freigabe festgelegt werden:

* `continuously-available`
* `oplocks`


Die folgenden Eigenschaften der Freigabe dürfen nicht festgelegt werden:

* `homedirectory`
* `attributecache`
* `branchcache`
* `access-based-enumeration`


.Schritte
. Es sollte überprüft werden, ob die Offline-Dateien auf  `manual` oder  `disabled` gesetzt sind und ob Symlinks deaktiviert sind:
+
`*vserver cifs shares show -vserver _vserver_name_*`

. Es sollte sichergestellt sein, dass die SMB-Freigaben für kontinuierliche Verfügbarkeit konfiguriert sind:
+
`*vserver cifs shares properties show -vserver _vserver_name_*`



.Beispiele
Das folgende Beispiel zeigt die Freigabeeinstellung für eine Freigabe namens "`share1`" auf der Storage Virtual Machine (SVM, ehemals Vserver) vs1. Offline-Dateien sind auf  `manual` gesetzt und symbolische Links sind deaktiviert (gekennzeichnet durch einen Bindestrich im  `Symlink Properties`-Feldausgabe):

[listing]
----
cluster1::> vserver cifs share show -vserver vs1 -share-name share1
                      Vserver: vs1
                        Share: share1
     CIFS Server NetBIOS Name: VS1
                         Path: /data/share1
             Share Properties: oplocks
                               continuously-available
           Symlink Properties: -
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: -
                  Volume Name: -
                Offline Files: manual
Vscan File-Operations Profile: standard
----
Das folgende Beispiel zeigt die Eigenschaften einer Freigabe mit dem Namen "`share1`" auf SVM vs1:

[listing]
----
cluster1::> vserver cifs share properties show -vserver vs1 -share-name share1
Vserver    Share   Properties
---------  ------  ----------
vs1        share1  oplocks
                   continuously-available
----