---
sidebar: sidebar 
permalink: file-system-analytics/considerations-concept.html 
keywords: file system analytics, performance, SVM 
summary: Die Dateisystemanalyse bietet Einblick in Volumes mit aktiven NAS-Daten. Es gibt Einschränkungen und Einschränkungen bei der Verwendung. 
---
= Überlegungen zur Dateisystemanalyse in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten bestimmte Nutzungsbeschränkungen und potenzielle Performance-Auswirkungen im Zusammenhang mit der Implementierung von File System Analytics kennen.



== SVM-geschützte Beziehungen

Wenn Sie die Dateisystemanalyse auf Volumes aktiviert haben, deren SVM sich in einer Sicherungsbeziehung befindet, werden die Analysedaten nicht auf der Ziel-SVM repliziert. Wenn die Quell-SVM in einem Recovery-Vorgang erneut synchronisiert werden muss, müssen Sie die Analysen auf gewünschten Volumes nach der Recovery manuell erneut aktivieren.



== Überlegungen zur Performance

In einigen Fällen kann die Aktivierung von Filesystem-Analysen die Performance während der ersten Metadatensammlung beeinträchtigen. Dies wird meist auf Systemen mit maximaler Auslastung beobachtet. Um Analysen auf solchen Systemen zu vermeiden, können Sie Tools zum Performance-Monitoring von ONTAP System Manager verwenden.

Wenn die Latenz deutlich steigt, lesen Sie den Knowledge Base-Artikel link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/High_or_fluctuating_latency_after_turning_on_NetApp_ONTAP_File_System_Analytics["Hohe oder schwankende Latenz nach Aktivierung von NetApp ONTAP File System Analytics"^].



== Überlegungen zum Scannen

Wenn Sie die Kapazitätsanalyse aktivieren, führt ONTAP einen Initialisierungsscan für Kapazitätsanalysen durch. Der Scan greift auf Metadaten für alle Dateien in Volumes zu, für die die Kapazitätsanalyse aktiviert ist. Während des Scans werden keine Dateidaten gelesen. Ab ONTAP 9.14.1 können Sie den Fortschritt des Scans mit der REST-API, auf der Registerkarte **Explorer** des Systemmanagers oder mit dem CLI-Befehl verfolgen `volume analytics show`. Wenn ein Drosselungsereignis vorhanden ist, gibt ONTAP eine Benachrichtigung aus.

Wenn Sie File System Analytics auf einem Volume aktivieren, stellen Sie sicher, dass mindestens 5 bis 8 Prozent des verfügbaren Speicherplatzes des Volumes frei sind. Wenn das Volume die automatische Größenanpassung aktiviert hat, berechnen Sie die verfügbare Größe basierend auf der maximalen Autogrow-Größe. Ab ONTAP 9.15.1 zeigt ONTAP eine Fehlermeldung an, wenn beim Aktivieren der Dateisystemanalyse auf einem Volume nicht genügend Speicherplatz verfügbar ist.

Nach Abschluss des Scans wird die Dateisystemanalyse kontinuierlich in Echtzeit aktualisiert, wenn sich das Dateisystem ändert.

Die für den Scan benötigte Zeit ist proportional zur Anzahl der Verzeichnisse und Dateien auf dem Volume. Da beim Scan Metadaten erfasst werden, wirkt sich die Dateigröße nicht auf die Scan-Zeit aus.

Weitere Informationen zum Initialisierungsscan finden Sie unter link:https://www.netapp.com/pdf.html?item=/media/20707-tr-4867.pdf["TR-4867: Best Practice Guidelines for File System Analytics"^].



=== Best Practices in sich vereint

Sie sollten den Scan auf Volumes starten, die Aggregate nicht gemeinsam nutzen. Mit dem Befehl können Sie sehen, welche Aggregate derzeit welche Volumes hosten:

`volume show -volume _comma-separated-list_of_volumes_ -fields aggr-list`

Während der Scan ausgeführt wird, bedienen die Volumes weiterhin den Client-Datenverkehr. Es wird empfohlen, den Scan in Zeiträumen zu starten, in denen Sie mit einem geringeren Clientverkehr rechnen.

Wenn der Client-Datenverkehr zunimmt, verbraucht er Systemressourcen und führt dazu, dass der Scan länger dauert.

Ab ONTAP 9.12.1 können Sie die Datenerfassung in System Manager und über die ONTAP CLI unterbrechen.

* Wenn Sie die ONTAP-CLI verwenden:
+
** Sie können die Datenerfassung mit dem folgenden Befehl anhalten: `volume analytics initialization pause -vserver _svm_name_ -volume _volume_name_`
** Sobald der Clientverkehr verlangsamt wurde, können Sie die Datenerfassung mit dem folgenden Befehl fortsetzen: `volume analytics initialization resume -vserver _svm_name_ -volume _volume_name_`


* Wenn Sie den System Manager verwenden, verwenden Sie in der Ansicht *Explorer* des Volume-Menüs die Schaltflächen *Datensammlung anhalten* und *Datenerfassung fortsetzen*, um den Scan zu verwalten.

