---
permalink: antivirus/commands-view-vscan-server-reference.html 
sidebar: sidebar 
keywords: commands, view, vscan, server, connection, status 
summary: Mit den Befehlen vserver vscan connection-status show lassen sich zusammenfassende und detaillierte Informationen zum Verbindungsstatus des Vscan Server anzeigen. 
---
= ONTAP Befehle zum Anzeigen des Vscan Server-Verbindungsstatus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit den  `vserver vscan connection-status show` Befehlen lassen sich eine Zusammenfassung und detaillierte Informationen zum Verbindungsstatus des Vscan Server anzeigen.

|===
| Wenn Sie möchten... | Führen Sie den folgenden Befehl aus... 


 a| 
Zusammenfassung der Vscan Serververbindungen
 a| 
`vserver vscan connection-status show`



 a| 
Details zu Vscan Serververbindungen
 a| 
`vserver vscan connection-status show-all`



 a| 
Details zu verbundenen Vscan Servern
 a| 
`vserver vscan connection-status show-connected`



 a| 
Details zu verfügbaren Vscan-Servern, die nicht verbunden sind, anzeigen
 a| 
`vserver vscan connection-status show-not-connected`

|===
Weitere Informationen zu  `vserver vscan connection-status show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+vscan+connection-status+show["ONTAP-Befehlsreferenz"^].
