---
permalink: antivirus/commands-manage-scanner-pools-reference.html 
sidebar: sidebar 
keywords: commands, manage, scanner pools 
summary: Sie können Scannerpools bearbeiten und löschen sowie privilegierte Benutzer und Vscan Server für einen Scannerpool verwalten. Zusammenfassende Informationen zum Scannerpool sind ebenfalls einsehbar. 
---
= ONTAP Befehle zur Verwaltung von Scannerpools in Vscan
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Scannerpools bearbeiten und löschen sowie privilegierte Benutzer und Vscan Server für einen Scannerpool verwalten. Zusammenfassende Informationen zum Scannerpool sind ebenfalls einsehbar.

|===


| Wenn Sie möchten... | Führen Sie den folgenden Befehl aus... 


 a| 
Einen Scannerpool ändern
 a| 
`vserver vscan scanner-pool modify`



 a| 
Einen Scannerpool löschen
 a| 
`vserver vscan scanner-pool delete`



 a| 
Privilegierte Benutzer zu einem Scannerpool hinzufügen
 a| 
`vserver vscan scanner-pool privileged-users add`



 a| 
Privilegierte Benutzer aus einem Scanner Pool entfernen
 a| 
`vserver vscan scanner-pool privileged-users remove`



 a| 
Vscan-Server zu einem Scannerpool hinzufügen
 a| 
`vserver vscan scanner-pool servers add`



 a| 
Vscan Server aus einem Scannerpool entfernen
 a| 
`vserver vscan scanner-pool servers remove`



 a| 
Zusammenfassung und Details für einen Scannerpool anzeigen
 a| 
`vserver vscan scanner-pool show`



 a| 
Privilegierte Benutzer für einen Scanner-Pool anzeigen
 a| 
`vserver vscan scanner-pool privileged-users show`



 a| 
Vscan Server für alle Scannerpools anzeigen
 a| 
`vserver vscan scanner-pool servers show`

|===
Weitere Informationen zu den in diesem Verfahren beschriebenen Befehlen befinden sich in der link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP-Befehlsreferenz"^].
