---
permalink: antivirus/configure-ontap-antivirus-connector-task.html 
sidebar: sidebar 
keywords: 'configure, antivirus connector, task, SVM"s, connections' 
summary: 'Der Antivirus Connector muss so konfiguriert werden, dass eine oder mehrere Storage Virtual Machines (SVMs) angegeben werden, zu denen eine Verbindung hergestellt werden soll, entweder durch Eingabe des ONTAP Management LIF, der Abfrageinformationen und der ONTAP Admin-Kontozugangsdaten oder nur des Data LIF.' 
---
= ONTAP Vscan Antivirus Connectors konfigurieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der ONTAP Antivirus Connector kann so konfiguriert werden, dass eine oder mehrere Storage Virtual Machines (SVMs) angegeben werden, zu denen eine Verbindung entweder durch Eingabe der ONTAP Management-LIF, der Abfrageinformationen und der ONTAP Admin-Kontozugangsdaten oder nur der Daten-LIF hergestellt werden soll. Auch können die Details einer SVM-Verbindung geändert oder eine SVM-Verbindung entfernt werden. Standardmäßig verwendet der ONTAP Antivirus Connector REST-APIs, um die Liste der Daten-LIFs abzurufen, sofern die ONTAP Management-LIF konfiguriert ist.



[[modify-the-details-of-an-svm-connection]]
== Details einer SVM-Verbindung ändern

Sie können die Details einer Storage Virtual Machine (SVM)-Verbindung, die dem Antivirus Connector hinzugefügt wurde, aktualisieren, indem Sie die ONTAP Management-LIF und die Abfrageinformationen ändern. Daten-LIFs können nach dem Hinzufügen nicht aktualisiert werden. Zum Aktualisieren von Daten-LIFs ist es erforderlich, diese zunächst zu entfernen und dann mit der neuen LIF oder IP-Adresse erneut hinzuzufügen.

.Bevor Sie beginnen
Stellen Sie sicher, dass ein Benutzerkonto für die HTTP-Anwendung erstellt wurde und eine Rolle zugewiesen ist, die (mindestens Lesezugriff) auf die  `/api/network/ip/interfaces` REST API hat.

Weitere Informationen zu  `security login role create` und  `security login create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/security-login-create.html["ONTAP-Befehlsreferenz"^].

Der Domänenbenutzer kann auch als Konto verwendet werden, indem ein Authentifizierungstunnel-SVM für eine administrative SVM hinzugefügt wird. Weitere Informationen zu  `security login domain-tunnel create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/security-login-domain-tunnel-create.html["ONTAP-Befehlsreferenz"^].

.Schritte
. Klicken Sie mit der rechten Maustaste auf das Symbol *Configure ONTAP LIFs*, das nach Abschluss der Antivirus Connector-Installation auf Ihrem Desktop gespeichert wurde, und wählen Sie dann *Als Administrator ausführen*. Das Dialogfeld *Configure ONTAP LIFs* wird geöffnet.
. Wählen Sie die SVM-IP-Adresse aus und klicken Sie dann auf *Aktualisieren*.
. Die Informationen werden bei Bedarf aktualisiert.
. *Speichern* aktualisiert die Verbindungsdetails in der Registrierung.
. Klicken Sie auf *Exportieren*, wenn Sie die Verbindungsliste in eine Registry-Import- oder Registry-Exportdatei exportieren möchten. Dies ist hilfreich, wenn mehrere Vscan Server dieselbe Gruppe von Management- oder Daten-LIFs verwenden.




[[remove-an-svm-connection-from-the-antivirus-connector]]
== Eine SVM-Verbindung aus dem Antivirus Connector entfernen

Wenn Sie keine SVM-Verbindung mehr benötigen, kann sie entfernt werden.

.Schritte
. Klicken Sie mit der rechten Maustaste auf das Symbol *Configure ONTAP LIFs*, das nach Abschluss der Antivirus Connector-Installation auf Ihrem Desktop gespeichert wurde, und wählen Sie dann *Als Administrator ausführen*. Das Dialogfeld *Configure ONTAP LIFs* wird geöffnet.
. Wählen Sie eine oder mehrere SVM IP-Adressen aus und klicken Sie dann auf *Entfernen*.
. *Speichern* aktualisiert die Verbindungsdetails in der Registrierung.
. Klicken Sie auf *Exportieren*, wenn Sie die Verbindungsliste in eine Registry-Import- oder Registry-Exportdatei exportieren möchten. Dies ist hilfreich, wenn mehrere Vscan Server dieselbe Gruppe von Management- oder Daten-LIFs verwenden.




[[troubleshoot]]
== Fehlerbehebung

.Bevor Sie beginnen
Beim Erstellen von Registrierungswerten in diesem Verfahren ist der rechte Bereich zu verwenden.

Sie können die Protokolle des Antivirus Connector für Diagnosezwecke aktivieren oder deaktivieren. Standardmäßig sind diese Protokolle deaktiviert. Für eine verbesserte Leistung sollten die Protokolle des Antivirus Connector deaktiviert bleiben und nur bei kritischen Ereignissen aktiviert werden.

.Schritte
. Wählen Sie *Start* aus, geben Sie "regedit" in das Suchfeld ein und wählen Sie  `regedit.exe` in der Programmliste aus.
. Im *Registrierungseditor* befindet sich der folgende Unterschlüssel für den ONTAP Antivirus Connector:
`HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Data ONTAP\Clustered Data ONTAP Antivirus Connector\v1.0`
. Registrierungswerte werden erstellt, indem der Typ, der Name und die in der folgenden Tabelle aufgeführten Werte angegeben werden:
+
|===


| Typ | Name | Werte 


 a| 
Zeichenkette
 a| 
Tracepath
 a| 
c:\avshim.log

|===
+
Dieser Registrierungswert kann auch ein anderer gültiger Pfad sein.

. Ein weiterer Registrierungswert wird erstellt, indem der Typ, der Name, die Werte und die Protokollierungsinformationen wie in der folgenden Tabelle angegeben bereitgestellt werden:
+
|===


| Typ | Name | Kritische Protokollierung | Intermediate Protokollierung | Ausführliche Protokollierung 


 a| 
DWORD
 a| 
Trace-Level
 a| 
1
 a| 
2 oder 3
 a| 
4

|===
+
Dies ermöglicht Antivirus Connector-Protokolle, die unter dem in TracePath in Schritt 3 angegebenen Pfad gespeichert werden.

. Die Protokolle des Antivirus Connector werden deaktiviert, indem die in den Schritten 3 und 4 erstellten Registrierungswerte gelöscht werden.
. Erstellen Sie einen weiteren Registrierungswert vom Typ „MULTI_SZ“ mit dem Namen „LogRotation“ (ohne Anführungszeichen). In „LogRotation“ ist „logFileSize:1“ als Eintrag für die Rotationsgröße anzugeben (wobei 1 für 1 MB steht), und in der nächsten Zeile ist „logFileCount:5“ als Eintrag für das Rotationslimit anzugeben (5 ist das Limit).
+
[NOTE]
====
Diese Werte sind optional. Wenn sie nicht angegeben werden, werden die Standardwerte von 20MB für die Rotationsgröße und 10 Dateien für das Rotationslimit verwendet. Angegebene Ganzzahlen liefern keine Dezimal- oder Bruchteile. Wenn Werte angegeben werden, die höher als die Standardwerte sind, werden stattdessen die Standardwerte verwendet.

====
. Um die vom Benutzer konfigurierte Protokollrotation zu deaktivieren, müssen die in Schritt 6 erstellten Registrierungswerte gelöscht werden.




[[customizable-banner]]
== Anpassbares Banner

Mit einem benutzerdefinierten Banner kann eine rechtsverbindliche Erklärung und ein Haftungsausschluss für den Systemzugriff im Fenster _Configure ONTAP LIF API_ platziert werden.

.Schritt
. Das Standardbanner kann geändert werden, indem der Inhalt der  `banner.txt` Datei im Installationsverzeichnis aktualisiert und die Änderungen anschließend gespeichert werden. Das Fenster „Configure ONTAP LIF API“ muss erneut geöffnet werden, damit die Änderungen im Banner sichtbar sind.




[[enable-extended-ordinance-eo-mode]]
== Erweiterter Verordnungsmodus (EO) aktivieren

Sie können den Extended Ordinance (EO) Modus für einen sicheren Betrieb aktivieren und deaktivieren.

.Schritte
. Wählen Sie *Start* aus, geben Sie "regedit" in das Suchfeld ein und wählen Sie  `regedit.exe` in der Programmliste aus.
. Im *Registrierungseditor* befindet sich der folgende Unterschlüssel für ONTAP Antivirus Connector:
`HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Data ONTAP\Clustered Data ONTAP Antivirus Connector\v1.0`
. Im rechten Bereich einen neuen Registrierungswert vom Typ "DWORD" mit dem Namen "EO_Mode" (ohne Anführungszeichen) und dem Wert "1" (ohne Anführungszeichen) zum Aktivieren des EO Mode oder dem Wert "0" (ohne Anführungszeichen) zum Deaktivieren des EO Mode erstellen.



NOTE: Standardmäßig ist der EO-Modus deaktiviert, wenn der  `EO_Mode` Registrierungseintrag fehlt. Bei aktiviertem EO-Modus ist sowohl der externe Syslog-Server als auch die gegenseitige Zertifikatsauthentifizierung zu konfigurieren.



[[configure-the-external-syslog-server]]
== Den externen Syslog-Server konfigurieren

.Bevor Sie beginnen
Es ist zu beachten, dass beim Erstellen von Registrierungswerten in diesem Verfahren der rechte Bereich verwendet werden sollte.

.Schritte
. Wählen Sie *Start* aus, geben Sie "regedit" in das Suchfeld ein und wählen Sie  `regedit.exe` in der Programmliste aus.
. Im *Registrierungseditor* wird der folgende Unterschlüssel für ONTAP Antivirus Connector zur Syslog-Konfiguration erstellt:
`HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Data ONTAP\Clustered Data ONTAP Antivirus Connector\v1.0\syslog`
. Ein Registrierungswert wird erstellt, indem Typ, Name und Wert wie in der folgenden Tabelle angegeben bereitgestellt werden:
+
|===


| Typ | Name | Wert 


 a| 
DWORD
 a| 
syslog_enabled
 a| 
1 oder 0

|===
+
Beachten Sie, dass der Wert „1“ das Syslog aktiviert und der Wert „0“ es deaktiviert.

. Ein weiterer Registrierungswert wird erstellt, indem die Informationen wie in der folgenden Tabelle angegeben bereitgestellt werden:
+
|===


| Typ | Name 


 a| 
REG_SZ
 a| 
Syslog_host

|===
+
Geben Sie die IP-Adresse oder den Domainnamen des Syslog-Hosts für das Wertfeld an.

. Ein weiterer Registrierungswert wird erstellt, indem die Informationen wie in der folgenden Tabelle angegeben bereitgestellt werden:
+
|===


| Typ | Name 


 a| 
REG_SZ
 a| 
Syslog Port

|===
+
Geben Sie im Feld „Wert“ die Portnummer an, auf der der Syslog-Server läuft.

. Ein weiterer Registrierungswert wird erstellt, indem die Informationen wie in der folgenden Tabelle angegeben bereitgestellt werden:
+
|===


| Typ | Name 


 a| 
REG_SZ
 a| 
Syslog Protokoll

|===
+
Geben Sie im Feld „Wert“ das auf dem Syslog-Server verwendete Protokoll ein, entweder „tcp“ oder „udp“.

. Ein weiterer Registrierungswert wird erstellt, indem die Informationen wie in der folgenden Tabelle angegeben bereitgestellt werden:
+
|===


| Typ | Name | LOG_CRIT | LOG_NOTICE | LOG_INFO | LOG_DEBUG 


 a| 
DWORD
 a| 
Syslog Level
 a| 
2
 a| 
5
 a| 
6
 a| 
7

|===
. Ein weiterer Registrierungswert wird erstellt, indem die Informationen wie in der folgenden Tabelle angegeben bereitgestellt werden:
+
|===


| Typ | Name | Wert 


 a| 
DWORD
 a| 
syslog_tls
 a| 
1 oder 0

|===


Beachten Sie, dass ein Wert „1“ Syslog mit Transport Layer Security (TLS) aktiviert und ein Wert „0“ Syslog mit TLS deaktiviert.



[[ensure-a-configured-external-syslog-server-runs-smoothly]]
=== Es wird sichergestellt, dass ein konfigurierter externer Syslog Server reibungslos funktioniert.

* Wenn der Schlüssel fehlt oder einen Nullwert hat:
+
** Das Protokoll ist standardmäßig auf "tcp" eingestellt.
** Der Port ist standardmäßig auf „514“ für einfaches „tcp/udp“ und auf „6514“ für TLS eingestellt.
** Der Syslog-Level ist standardmäßig auf 5 (LOG_NOTICE) festgelegt.


* Es lässt sich bestätigen, dass Syslog aktiviert ist, indem überprüft wird, ob der  `syslog_enabled` Wert „1“ ist. Wenn der  `syslog_enabled` Wert „1“ ist, besteht die Möglichkeit, sich beim konfigurierten Remote-Server anzumelden, unabhängig davon, ob der EO-Modus aktiviert ist.
* Wenn der EO-Modus auf „1“ eingestellt ist und der  `syslog_enabled` Wert von „1“ auf „0“ geändert wird, gilt Folgendes:
+
** Der Dienst kann nicht gestartet werden, wenn syslog im EO-Modus nicht aktiviert ist.
** Wenn das System im Normalbetrieb läuft, erscheint eine Warnung, dass syslog im EO-Modus nicht deaktiviert werden kann und syslog zwangsweise auf „1“ gesetzt wird, was in der Registry sichtbar ist. Tritt dies auf, empfiehlt es sich, zuerst den EO-Modus und anschließend syslog zu deaktivieren.


* Wenn der Syslog-Server im EO-Modus und bei aktiviertem Syslog nicht erfolgreich ausgeführt werden kann, wird der Dienst beendet. Dies kann aus einem der folgenden Gründe auftreten:
+
** Es ist kein oder ein ungültiger syslog_host konfiguriert.
** Es ist ein ungültiges Protokoll außer UDP oder TCP konfiguriert.
** Die Portnummer ist ungültig.


* Bei einer TCP- oder TLS-over-TCP-Konfiguration schlägt die Verbindung fehl und der Dienst wird heruntergefahren, wenn der Server nicht am IP-Port lauscht.




[[configure-x-509-mutual-certificate-authentication]]
== X.509 gegenseitige Zertifikatsauthentifizierung

Die auf X.509-Zertifikaten basierende gegenseitige Authentifizierung ist für die Secure Sockets Layer (SSL)-Kommunikation zwischen dem Antivirus Connector und ONTAP im Managementpfad möglich. Wenn der EO-Modus aktiviert ist und das Zertifikat nicht gefunden wird, beendet der AV Connector den Vorgang. Das folgende Verfahren ist auf dem Antivirus Connector auszuführen:

.Schritte
. Der Antivirus Connector sucht im Verzeichnispfad, von dem aus der Antivirus Connector das Installationsverzeichnis ausführt, nach dem Antivirus Connector-Clientzertifikat und dem Zertifizierungsstellenzertifikat (CA-Zertifikat) für den NetApp Server. Die Zertifikate sind in diesen festen Verzeichnispfad zu kopieren.
. Das Clientzertifikat und dessen privaten Schlüssel im PKCS12-Format einbetten und mit "AV_client.P12" benennen.
. Das CA-Zertifikat (sowie alle Zwischenzertifizierungsstellen bis hin zur Root-CA), das zum Signieren des NetApp-Serverzertifikats verwendet wurde, muss im Privacy Enhanced Mail (PEM)-Format vorliegen und den Namen „Ontap_CA.pem“ tragen. Es ist im Installationsverzeichnis des Antivirus Connector abzulegen. Auf dem ONTAP-System ist das CA-Zertifikat (sowie alle Zwischenzertifizierungsstellen bis hin zur Root-CA), das zum Signieren des Clientzertifikats für den Antivirus Connector verwendet wurde, unter „ONTAP“ als Zertifikat vom Typ „client-ca“ zu installieren.

