---
permalink: antivirus/create-scanner-pool-single-cluster-task.html 
sidebar: sidebar 
keywords: create, scanner pool, single cluster 
summary: Ein Scanner-Pool definiert die Vscan-Server und privilegierten Benutzer, die eine Verbindung zu SVMs herstellen können. 
---
= Erstellen Sie einen ONTAP Vscan-Scannerpool auf einem einzelnen Cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Scanner-Pool definiert die Vscan-Server und privilegierten Benutzer, die eine Verbindung zu SVMs herstellen können.

.Bevor Sie beginnen
* SVMs und Vscan-Server müssen sich in derselben Domäne oder in vertrauenswürdigen Domänen befinden.
* Konfigurieren Sie einen ONTAP Antivirus Connector mit der Cluster-Management-LIF.
* Die Liste der privilegierten Benutzer muss den Domänen- und Benutzernamen enthalten, über den der Vscan-Server eine Verbindung zur SVM herstellt.
* Sobald der Scanner-Pool konfiguriert ist, überprüfen Sie den Verbindungsstatus zu den Servern.


.Schritte
. Erstellen eines Scannerpools:
+
`vserver vscan scanner-pool create -vserver cluster_admin_SVM -scanner-pool scanner_pool -hostnames Vscan_server_hostnames -privileged-users privileged_users`

+
** Geben Sie eine Cluster-Admin-SVM an.
** Geben Sie für jeden Host-Namen des Vscan-Servers eine IP-Adresse oder einen FQDN an.
** Geben Sie die Domäne und den Benutzernamen für jeden privilegierten Benutzer an.


+
Erfahren Sie mehr über `vserver vscan scanner-pool create` in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-scanner-pool-create.html["ONTAP-Befehlsreferenz"^].

. Überprüfen Sie, ob der Scannerpool erstellt wurde:
+
`vserver vscan scanner-pool show -vserver cluster_admin_SVM -scanner-pool _scanner_pool_`

+
Mit dem folgenden Befehl werden die Details für den `SP` Scanner-Pool angezeigt:

+
[listing]
----
cluster1::> vserver vscan scanner-pool show -vserver cluster_admin_SVM -scanner-pool SP

                                    Vserver: cluster_admin_SVM
                               Scanner Pool: SP
                             Applied Policy: idle
                             Current Status: off
         Cluster on Which Policy Is Applied: -
                  Scanner Pool Config Owner: cluster
       List of IPs of Allowed Vscan Servers: 1.1.1.1, 10.72.204.27
List of Host Names of Allowed Vscan Servers: 1.1.1.1, vmwin204-27.fsct.nb
                   List of Privileged Users: cifs\u1, cifs\u2
----
+
Mit dem Befehl können Sie auch `vserver vscan scanner-pool show` alle Scanner-Pools im Cluster anzeigen. Erfahren Sie mehr über `vserver vscan scanner-pool show` in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-scanner-pool-show.html["ONTAP-Befehlsreferenz"^].


