---
permalink: antivirus/create-on-access-policy-task.html 
sidebar: sidebar 
keywords: create, on-access, policy 
summary: Eine Zugriffsrichtlinie definiert den Umfang eines Scans beim Zugriff. Sie können eine On-Access-Richtlinie für eine einzelne SVM oder für alle SVMs in einem Cluster erstellen. Falls Sie eine Zugriffsrichtlinie für alle SVMs in einem Cluster erstellt haben, müssen Sie die Richtlinie für jede SVM einzeln aktivieren. 
---
= Erstellen einer Zugriffsrichtlinie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Eine Zugriffsrichtlinie definiert den Umfang eines Scans beim Zugriff. Sie können eine On-Access-Richtlinie für eine einzelne SVM oder für alle SVMs in einem Cluster erstellen. Falls Sie eine Zugriffsrichtlinie für alle SVMs in einem Cluster erstellt haben, müssen Sie die Richtlinie für jede SVM einzeln aktivieren.

.Über diese Aufgabe
* Sie können die maximale Dateigröße für den Scan, Dateierweiterungen und Pfade für den Scan sowie Dateierweiterungen und -Pfade für den Scan angeben.
* Sie können die einstellen `scan-mandatory` Option „aus“, um festzulegen, dass der Dateizugriff zulässig ist, wenn keine Vscan-Server für Virenprüfungen verfügbar sind.
* Standardmäßig erstellt ONTAP eine Zugriffsrichtlinie mit dem Namen „Default_CIFS“ und ermöglicht sie für alle SVMs in einem Cluster.
* Jede Datei, die auf der Grundlage des für den Scanausschluss qualifiziert ist `paths-to-exclude`, `file-ext-to-exclude`, Oder `max-file-size` Parameter werden für das Scannen nicht berücksichtigt, auch wenn der `scan-mandatory` Die Option ist auf ein eingestellt. (Prüfen Sie dies link:vscan-server-connection-concept.html["Fehlerbehebung"] Abschnitt für Konnektivitätsprobleme im Zusammenhang mit `scan-mandatory` Option.)
* Standardmäßig werden nur Lese- und Schreib-Volumes gescannt. Sie können Filter festlegen, die das Scannen von schreibgeschützten Volumes ermöglichen oder das Scannen auf Dateien beschränken, die mit dem Zugriff ausführen geöffnet wurden.
* Ein Virus-Scan wird nicht auf einer SMB-Freigabe durchgeführt, für die der kontinuierlich verfügbare Parameter auf Ja gesetzt ist.
* Siehe link:architecture-concept.html["Virenschutz-Architektur"] Abschnitt für Details zum _Vscan file-Operations Profil_.
* Sie können maximal zehn (10) Zugriffsrichtlinien pro SVM erstellen. Sie können jedoch jeweils nur eine Richtlinie für den Zugriff aktivieren.
+
** Sie können in einer Richtlinie für den Zugriff maximal hundert (100) Pfade und Dateierweiterungen von der Virenüberprüfung ausschließen.


* Einige Empfehlungen zum Dateiausschluss:
+
** Ziehen Sie es in Erwägung, große Dateien (Dateigröße kann angegeben werden) von Virus-Scans auszuschließen, da sie zu einer langsamen Antwortzeit oder Scan-Anfrage-Timeouts für CIFS-Benutzer führen können. Die Standarddateigröße für Ausschluss beträgt 2 GB.
** Es empfiehlt sich, Dateierweiterungen wie z. B. auszuschließen `.vhd` Und `.tmp` Weil Dateien mit diesen Erweiterungen möglicherweise nicht zum Scannen geeignet sind.
** Es empfiehlt sich, Dateipfade wie das Quarantäneverzeichnis oder Pfade auszuschließen, in denen nur virtuelle Festplatten oder Datenbanken gespeichert sind.
** Vergewissern Sie sich, dass alle Ausschlüsse in derselben Richtlinie angegeben sind, da jeweils nur eine Richtlinie aktiviert werden kann. NetApp empfiehlt dringend, die gleichen Ausschlüsse zu verwenden, die in der Antiviren-Engine angegeben sind.




.Schritte
. Erstellen einer Richtlinie für den Zugriff:
+
`vserver vscan on-access-policy create -vserver _data_SVM|cluster_admin_SVM_ -policy-name _policy_name_ -protocol CIFS -max-file-size _max_size_of_files_to_scan_ –filters [scan-ro-volume,][scan-execute-access] -file-ext-to-include _extensions_of_files_to_include_ -file-ext-to-exclude _extensions_of_files_to_exclude_ -scan-files-with-no-ext true|false -paths-to-exclude _paths_of_files_to_exclude_ -scan-mandatory on|off`

+
** Legen Sie eine Daten-SVM für eine Richtlinie fest, die für eine einzelne SVM, einen Cluster-Admin-SVM für eine Richtlinie festgelegt ist, die für alle SVMs in einem Cluster definiert ist.
** Der `-file-ext-to-exclude` Die Einstellung überschreibt den `-file-ext-to-include` Einstellung.
** Einstellen `-scan-files-with-no-ext` Um Dateien ohne Erweiterungen zu scannen.
Mit dem folgenden Befehl wird eine Richtlinie mit dem Namen für den Zugriff erstellt `Policy1` Auf dem `vs1` SVM:


+
[listing]
----
cluster1::> vserver vscan on-access-policy create -vserver vs1 -policy-name Policy1 -protocol CIFS -filters scan-ro-volume -max-file-size 3GB -file-ext-to-include “mp*”,"tx*" -file-ext-to-exclude "mp3","txt" -scan-files-with-no-ext false -paths-to-exclude "\vol\a b\","\vol\a,b\"
----
. Überprüfen Sie, ob die Richtlinie für den Zugriff auf den Zugriff erstellt wurde: `vserver vscan on-access-policy show -instance _data_SVM|cluster_admin_SVM_ -policy-name policy_name`
+
Eine vollständige Liste der Optionen finden Sie auf der man-Page für den Befehl.

+
Mit dem folgenden Befehl werden die Details für das angezeigt `Policy1` Richtlinie:

+
[listing]
----
cluster1::> vserver vscan on-access-policy show -instance vs1 -policy-name Policy1

                           Vserver: vs1
                            Policy: Policy1
                     Policy Status: off
               Policy Config Owner: vserver
              File-Access Protocol: CIFS
                           Filters: scan-ro-volume
                    Mandatory Scan: on
Max File Size Allowed for Scanning: 3GB
            File Paths Not to Scan: \vol\a b\, \vol\a,b\
       File Extensions Not to Scan: mp3, txt
           File Extensions to Scan: mp*, tx*
      Scan Files with No Extension: false
----

