---
permalink: antivirus/enable-virus-scan-svm-task.html 
sidebar: sidebar 
keywords: enable, virus scan, svm 
summary: Die Virenprüfung muss auf einer SVM aktiviert sein, bevor ein On-Access- oder On-Demand-Scan ausgeführt werden kann. 
---
= Virenprüfung auf SVM ONTAP Vscan aktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Virenprüfung muss auf einer SVM aktiviert sein, bevor ein On-Access- oder On-Demand-Scan ausgeführt werden kann.

.Schritte
. Virenprüfung auf einer SVM aktivieren:
+
`vserver vscan enable -vserver data_SVM`

+
Weitere Informationen zu  `vserver vscan enable` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-enable.html["ONTAP-Befehlsreferenz"^].

+
[NOTE]
====
Sie können den  `vserver vscan disable` Befehl verwenden, um die Virenprüfung bei Bedarf zu deaktivieren. Weitere Informationen zu  `vserver vscan disable` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-disable.html["ONTAP-Befehlsreferenz"^].

====
+
Der folgende Befehl aktiviert die Virenprüfung auf der `vs1` SVM:

+
[listing]
----
cluster1::> vserver vscan enable -vserver vs1
----
. Es sollte überprüft werden, ob die Virenprüfung auf der SVM aktiviert ist:
+
`vserver vscan show -vserver data_SVM`

+
Weitere Informationen zu  `vserver vscan show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-show.html["ONTAP-Befehlsreferenz"^].

+
Der folgende Befehl zeigt den Vscan Status der `vs1` SVM an:

+
[listing]
----
cluster1::> vserver vscan show -vserver vs1

                           Vserver: vs1
                      Vscan Status: on
----

