---
permalink: antivirus/install-ontap-antivirus-connector-task.html 
sidebar: sidebar 
keywords: install, ontap, task, antivirus connector 
summary: Der ONTAP Antivirus Connector wird auf dem Vscan Server installiert, um die Kommunikation zwischen dem System mit ONTAP und dem Vscan Server bereitzustellen. 
---
= ONTAP Vscan Antivirus Connectors installieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der ONTAP Antivirus Connector wird auf dem Vscan Server installiert, damit die Kommunikation zwischen dem System mit ONTAP und dem Vscan Server möglich ist. Nach der Installation des ONTAP Antivirus Connectors kann die Antivirensoftware mit einer oder mehreren Storage Virtual Machines (SVMs) kommunizieren.

.Über diese Aufgabe
* Auf der link:../antivirus/vscan-partner-solutions.html["Vscan Partnerlösungen"] Seite sind Informationen zu den unterstützten Datenprotokollen, den Antiviren-Softwareversionen der Anbieter, ONTAP Versionen, Interoperabilitätsanforderungen und Windows Servern verfügbar.
* .NET 4.5.1 oder höher muss installiert sein.
* Der ONTAP Antivirus Connector kann auf einer virtuellen Maschine ausgeführt werden. Für optimale Leistung empfiehlt NetApp jedoch die Verwendung eines dedizierten physischen Rechners für den Virenscan.
* SMB 2.0 muss auf dem Windows Server aktiviert sein, auf dem der ONTAP Antivirus Connector installiert und ausgeführt wird.


.Bevor Sie beginnen
* Die ONTAP Antivirus Connector Setup-Datei kann von der Support-Website heruntergeladen und in einem Verzeichnis auf der Festplatte gespeichert werden.
* Es sollte überprüft werden, ob die Voraussetzungen für die Installation des ONTAP Antivirus Connector erfüllt sind.
* Es sollte überprüft werden, ob Administratorrechte zum Installieren des Antivirus Connector vorhanden sind.


.Schritte
. Der Installationsassistent für den Antivirus Connector wird durch Ausführen der entsprechenden Setup-Datei gestartet.
. Wählen Sie _Weiter_. Das Dialogfeld „Zielordner“ wird geöffnet.
. Wählen Sie _Weiter_, um den Antivirus Connector in dem aufgeführten Ordner zu installieren, oder wählen Sie _Ändern_, um ihn in einem anderen Ordner zu installieren.
. Das Dialogfeld „ONTAP AV Connector Windows Service Credentials“ wird geöffnet.
. Geben Sie Ihre Windows-Dienstanmeldeinformationen ein oder wählen Sie *Hinzufügen*, um einen Benutzer auszuwählen. Für ein ONTAP System muss dieser Benutzer ein gültiger Domänenbenutzer sein und in der Scannerpool-Konfiguration für die SVM vorhanden sein.
. *Weiter* auswählen. Das Dialogfeld „Programm kann installiert werden“ wird geöffnet.
. Wählen Sie *Installieren*, um die Installation zu starten, oder *Zurück*, wenn Sie Änderungen an den Einstellungen vornehmen möchten. Ein Statusfenster öffnet sich und zeigt den Fortschritt der Installation an, anschließend erscheint das Dialogfeld InstallShield Wizard Completed.
. Wählen Sie das Kästchen „Configure ONTAP LIFs“ aus, wenn die Konfiguration von ONTAP Management- oder Daten-LIFs fortgesetzt werden soll. Mindestens eine ONTAP Management- oder Daten-LIF muss konfiguriert werden, bevor dieser Vscan Server verwendet werden kann.
. Aktivieren Sie das Kästchen *Windows Installer-Protokoll anzeigen*, wenn die Installationsprotokolle angezeigt werden sollen.
. Wählen Sie *Fertigstellen*, um die Installation abzuschließen und den InstallShield-Assistenten zu schließen. Das Symbol *Configure ONTAP LIFs* wird auf dem Desktop gespeichert, um die ONTAP LIFs zu konfigurieren.
. Eine SVM zum Antivirus Connector hinzufügen. Eine SVM kann zum Antivirus Connector hinzugefügt werden, indem entweder eine ONTAP Management LIF hinzugefügt wird, die abgefragt wird, um die Liste der Daten-LIFs abzurufen, oder indem die Daten-LIF bzw. die Daten-LIFs direkt konfiguriert werden. Es müssen außerdem die Abfrageinformationen und die Anmeldedaten des ONTAP Admin-Kontos bereitgestellt werden, wenn die ONTAP Management LIF konfiguriert ist.
+
** Es sollte sichergestellt werden, dass die Management-LIF oder die IP-Adresse der SVM für  `management-https` aktiviert ist. Dies ist nicht erforderlich, wenn ausschließlich Daten-LIFs konfiguriert werden.
** Stellen Sie sicher, dass ein Benutzerkonto für die HTTP-Anwendung erstellt wurde und eine Rolle zugewiesen ist, die (mindestens Lesezugriff) auf die  `/api/network/ip/interfaces` REST API hat.
** Weitere Informationen zu  `security login role create` und  `security login create` in der  https://docs.netapp.com/us-en/ontap-cli/security-login-role-create.html["ONTAP-Befehlsreferenz"^].





NOTE: Der Domänenbenutzer kann auch als Konto verwendet werden, indem ein Authentifizierungstunnel-SVM für eine administrative SVM hinzugefügt wird. Weitere Informationen zu  `security login domain-tunnel create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/security-login-domain-tunnel-create.html["ONTAP-Befehlsreferenz"^].

.Schritte
. Klicken Sie mit der rechten Maustaste auf das Symbol *Configure ONTAP LIFs*, das beim Abschluss der Installation des Antivirus Connectors auf Ihrem Desktop gespeichert wurde, und wählen Sie dann *Als Administrator ausführen*.
. Im Dialogfeld „ONTAP LIFs konfigurieren“ den gewünschten Konfigurationstyp auswählen und anschließend die folgenden Aktionen durchführen:
+
[cols="35,65"]
|===


| Um diese Art von LIF zu erstellen... | Führen Sie diese Schritte aus... 


 a| 
Data LIF
 a| 
.. "role" auf "data" setzen
.. Das Datenprotokoll auf „cifs“ setzen
.. Die "firewall policy" auf "data" setzen.
.. "service policy" auf "default-data-files" setzen




 a| 
Management-LIF
 a| 
.. Setzen Sie „role*“ auf „data“
.. „Datenprotokoll“ auf „keine“ setzen
.. Setzen Sie „firewall policy“ auf „mgmt“.
.. "Dienstrichtlinie" auf "Standardverwaltung" setzen


|===
+
Weitere Informationen zu link:../networking/create_a_lif.html["Erstellung eines LIF"].

+
Nachdem eine LIF erstellt wurde, ist die Daten- oder Management-LIF oder die IP-Adresse der SVM, die hinzugefügt werden soll, einzugeben. Alternativ kann auch die Cluster Management-LIF eingegeben werden. Wird die Cluster Management-LIF angegeben, können alle SVMs innerhalb dieses Clusters, die SMB bereitstellen, den Vscan Server verwenden.

+
[NOTE]
====
Wenn für Vscan-Server die Kerberos-Authentifizierung erforderlich ist, muss jede SVM-Daten-LIF einen eindeutigen DNS-Namen haben, und dieser Name muss als Server Principal Name (SPN) im Windows Active Directory registriert werden. Wenn für jede Daten-LIF kein eindeutiger DNS-Name verfügbar ist oder dieser nicht als SPN registriert ist, verwendet der Vscan-Server den NT LAN Manager-Mechanismus zur Authentifizierung. Wenn DNS-Namen und SPNs nach der Verbindung des Vscan-Servers hinzugefügt oder geändert werden, ist ein Neustart des Antivirus Connector-Dienstes auf dem Vscan-Server erforderlich, damit die Änderungen wirksam werden.

====
. Zum Konfigurieren einer Management-LIF wird die Abfragedauer in Sekunden eingegeben. Die Abfragedauer ist die Frequenz, mit der der Antivirus Connector Änderungen an den SVMs oder an der LIF-Konfiguration des Clusters überprüft. Das Standard-Abfrageintervall beträgt 60 Sekunden.
. Geben Sie den Namen und das Passwort des ONTAP-Administratorkontos ein, um eine Management-LIF zu konfigurieren.
. Klicken Sie auf *Test*, um die Verbindung zu prüfen und die Authentifizierung zu verifizieren. Die Authentifizierung wird nur für eine Management LIF-Konfiguration verifiziert.
. Klicken Sie auf *Aktualisieren*, um den LIF zur Liste der LIFs hinzuzufügen, die abgefragt oder verbunden werden sollen.
. *Speichern* speichert die Verbindung zur Registrierung.
. Klicken Sie auf *Exportieren*, wenn Sie die Verbindungsliste in eine Registry-Import- oder Registry-Exportdatei exportieren möchten. Dies ist hilfreich, wenn mehrere Vscan Server dieselbe Gruppe von Management- oder Daten-LIFs verwenden.


Siehe die link:configure-ontap-antivirus-connector-task.html["Seite „ONTAP Antivirus Connector“ konfigurieren"] für Konfigurationsoptionen.
