---
permalink: antivirus/install-ontap-antivirus-connector-task.html 
sidebar: sidebar 
keywords: install, ontap, task, antivirus connector 
summary: Installieren Sie den ONTAP-Virenschutzanschluss auf dem Vscan-Server, um die Kommunikation zwischen dem System, auf dem ONTAP ausgeführt wird, und dem Vscan-Server bereitzustellen. 
---
= Installieren Sie den ONTAP Antivirus Connector
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Installieren Sie den ONTAP-Virenschutzanschluss auf dem Vscan-Server, um die Kommunikation zwischen dem System, auf dem ONTAP ausgeführt wird, und dem Vscan-Server zu ermöglichen. Bei der Installation des ONTAP Antivirus Connectors kann die Virenschutzsoftware mit einer oder mehreren Storage Virtual Machines (SVMs) kommunizieren.

.Über diese Aufgabe
* Siehe link:https://docs.netapp.com/us-en/ontap/antivirus/vscan-partner-solutions.html["Partnerlösungen von Vscan"^] Auf dieser Seite finden Sie Informationen zu unterstützten Protokollen, Softwareversionen von Antivirenanbietern, ONTAP-Versionen, Interoperabilitätsanforderungen und Windows-Servern.
* .NET 4.5.1 oder höher muss installiert sein.
* Der ONTAP Antivirus Connector kann auf einer virtuellen Maschine ausgeführt werden. Um die beste Performance zu erzielen, empfiehlt NetApp jedoch die Verwendung einer dedizierten Virtual Machine für Virenschutzprüfungen.
* SMB 2.0 muss auf dem Windows-Server aktiviert sein, auf dem Sie den ONTAP-Antivirus-Connector installieren und ausführen.


.Bevor Sie beginnen
* Laden Sie die Installationsdatei für den ONTAP Antivirus Connector von der Support-Website herunter und speichern Sie sie in einem Verzeichnis auf Ihrer Festplatte.
* Stellen Sie sicher, dass Sie die Anforderungen für die Installation des ONTAP-Virenschutzanschlusses erfüllen.
* Überprüfen Sie, ob Sie über Administratorrechte für die Installation des Antivirus Connectors verfügen.


.Schritte
. Starten Sie den Antivirus Connector-Installationsassistenten, indem Sie die entsprechende Setup-Datei ausführen.
. Wählen Sie _Next_. Das Dialogfeld Zielordner wird geöffnet.
. Wählen Sie _Next_, um den Antivirus Connector in dem Ordner zu installieren, der aufgelistet ist, oder wählen Sie _Change_, um ihn in einem anderen Ordner zu installieren.
. Das Dialogfeld ONTAP AV-Connector Windows-Dienstanmeldeinformationen wird geöffnet.
. Geben Sie Ihre Windows-Dienstanmeldeinformationen ein, oder wählen Sie *Hinzufügen*, um einen Benutzer auszuwählen. Bei einem ONTAP-System muss dieser Benutzer ein gültiger Domänenbenutzer sein und in der Scannerpoolkonfiguration für die SVM vorhanden sein.
. Wählen Sie *Weiter*. Das Dialogfeld bereit zur Installation des Programms wird geöffnet.
. Wählen Sie *Installieren*, um mit der Installation zu beginnen, oder wählen Sie *Zurück*, wenn Sie Änderungen an den Einstellungen vornehmen möchten.
Ein Statusfeld wird geöffnet und zeigt den Fortschritt der Installation an, gefolgt vom Dialogfeld InstallShield Wizard abgeschlossen.
. Aktivieren Sie das Kontrollkästchen ONTAP LIFs konfigurieren, wenn Sie mit der Konfiguration von ONTAP Management oder Daten-LIFs fortfahren möchten.
Sie müssen mindestens eine ONTAP Management- oder Daten-LIF konfigurieren, bevor dieser Vscan-Server verwendet werden kann.
. Aktivieren Sie das Kontrollkästchen Windows Installer-Protokoll anzeigen*, wenn Sie die Installationsprotokolle anzeigen möchten.
. Wählen Sie *Fertig stellen*, um die Installation zu beenden und den InstallShield-Assistenten zu schließen.
Das Symbol *Configure ONTAP LIFs* wird auf dem Desktop gespeichert, um die ONTAP LIFs zu konfigurieren.
. Fügen Sie dem Antivirus Connector eine SVM hinzu.
Sie können dem VirenschutzConnector eine SVM hinzufügen, indem Sie entweder eine ONTAP-Management-LIF hinzufügen, die zum Abrufen der Liste der Daten-LIFs abgefragt wird, oder die Daten-LIF oder LIFs direkt konfigurieren.
Wenn die ONTAP Management LIF konfiguriert ist, müssen Sie außerdem die Abfrageinformationen und die Anmeldeinformationen des ONTAP Administratorkontos angeben.
+
** Vergewissern Sie sich, dass die Management-LIF oder die IP-Adresse der SVM für aktiviert ist `management-https`. Dies ist nicht erforderlich, wenn Sie nur die Daten-LIFs konfigurieren.
** Vergewissern Sie sich, dass Sie ein Benutzerkonto für die HTTP-Anwendung erstellt und eine Rolle zugewiesen haben, die (mindestens schreibgeschützt) Zugriff auf das hat `/api/network/ip/interfaces` REST-API:
Weitere Informationen zum Erstellen eines Benutzers finden Sie im link:https://docs.netapp.com/us-en/ontap-cli-9131//security-login-role-create.html["Rolle für Sicherheits-Login erstellen"^] Und link:https://docs.netapp.com/us-en/ontap-cli-9131//security-login-create.html["Sicherheits-Login erstellen"^] ONTAP-man-Pages.





NOTE: Sie können den Domänenbenutzer auch als Konto verwenden, indem Sie eine SVM für einen Authentifizierungstunnel für eine administrative SVM hinzufügen. Weitere Informationen finden Sie im link:https://docs.netapp.com/us-en/ontap-cli-9131//security-login-domain-tunnel-create.html["Sicherheit Login Domain-Tunnel erstellen"^] ONTAP-man-Page verwenden oder `/api/security/acccounts` Und `/api/security/roles` REST-APIs zum Konfigurieren des Administratorkontos und der Rolle.

.Schritte
. Klicken Sie mit der rechten Maustaste auf das Symbol *ONTAP-LIFs konfigurieren*, das nach Abschluss der Installation des Virenschutzanschlusses auf Ihrem Desktop gespeichert wurde, und wählen Sie dann *als Administrator ausführen* aus.
. Wählen Sie im Dialogfeld ONTAP LIFs konfigurieren den bevorzugten Konfigurationstyp aus und führen Sie dann die folgenden Aktionen durch:
+
[cols="35,65"]
|===


| Um diesen Typ von LIF zu erstellen... | Führen Sie diese Schritte aus... 


 a| 
Daten-LIF
 a| 
.. „Rolle“ auf „Daten“ setzen
.. Stellen Sie das „Datenprotokoll“ auf „cifs“ ein.
.. Firewall-Richtlinie auf „Daten“ setzen
.. Setzen Sie „Service Policy“ auf „default-Data-files“




 a| 
Management-LIF
 a| 
.. „Rolle* auf „Daten“ setzen
.. Stellen Sie „Datenprotokoll“ auf „keine“ ein.
.. Firewall-Richtlinie auf „Management“ setzen
.. Service-Richtlinie auf Standardmanagement setzen


|===
+
Weitere Informationen link:https://docs.netapp.com/us-en/ontap/networking/create_a_lif.html["Erstellen einer LIF"^].

+
Nachdem Sie eine LIF erstellt haben, geben Sie die Daten- oder Management-LIF- oder IP-Adresse der hinzuzufügenden SVM ein. Sie können auch die Cluster-Management-LIF eingeben. Wenn Sie die Cluster-Management-LIF angeben, können alle SVMs innerhalb des Clusters, die SMB verwenden, den Vscan-Server verwenden.

+
[NOTE]
====
Wenn Kerberos-Authentifizierung für Vscan-Server erforderlich ist, muss jede SVM-Daten-LIF über einen eindeutigen DNS-Namen verfügen. Sie müssen diesen Namen als Server-Principal-Name (SPN) im Windows Active Directory registrieren. Wenn für jede Daten-LIF kein eindeutiger DNS-Name verfügbar oder als SPN registriert ist, verwendet der Vscan-Server den NT LAN Manager-Mechanismus zur Authentifizierung. Wenn Sie die DNS-Namen und SPNs nach der Verbindung mit dem Vscan-Server hinzufügen oder ändern, müssen Sie den Antivirus Connector-Dienst auf dem Vscan-Server neu starten, um die Änderungen anzuwenden.

====
. Geben Sie zum Konfigurieren einer Management-LIF die Abfragedauer in Sekunden ein. Die Abfragedauer ist die Häufigkeit, mit der der Antivirus Connector auf Änderungen an den SVMs oder der LIF-Konfiguration des Clusters prüft. Das standardmäßige Abfrageintervall beträgt 60 Sekunden.
. Geben Sie den Namen und das Passwort des ONTAP Administratorkontos ein, um eine Management-LIF zu konfigurieren.
. Klicken Sie auf *Test*, um die Verbindung zu überprüfen und die Authentifizierung zu überprüfen. Die Authentifizierung wird nur für eine Management-LIF-Konfiguration verifiziert.
. Klicken Sie auf *Update*, um die LIF zur Liste der LIFs hinzuzufügen, zu denen Sie die Abfrage durchführen oder eine Verbindung herstellen möchten.
. Klicken Sie auf *Speichern*, um die Verbindung zur Registrierung zu speichern.
. Klicken Sie auf *Export*, wenn Sie die Liste der Verbindungen in eine Registry-Import- oder Registry-Export-Datei exportieren möchten.
Dies ist nützlich, wenn mehrere Vscan-Server denselben Satz an Management- oder Daten-LIFs verwenden.


Siehe link:configure-ontap-antivirus-connector-task.html["Konfigurieren Sie die Seite ONTAP Antivirus Connector"] Für Konfigurationsoptionen.
