---
permalink: antivirus/modify-vscan-file-profile-smb-share-task.html 
sidebar: sidebar 
keywords: modify, vscan, file-operations, profile, cifs share 
summary: 'Das _Vscan-Dateioperationsprofil_ für eine SMB-Freigabe definiert die Operationen auf der Freigabe, die einen Scan auslösen können. Standardmäßig ist der Parameter auf  `standard` gesetzt. Der Parameter kann bei Bedarf angepasst werden, wenn eine SMB-Freigabe erstellt oder geändert wird.' 
---
= Das ONTAP Vscan Dateioperationsprofil für SMB-Freigaben anpassen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das _Vscan-Dateioperationsprofil_ für eine SMB-Freigabe definiert die Operationen auf der Freigabe, die einen Scan auslösen können. Standardmäßig ist der Parameter auf  `standard` gesetzt. Der Parameter kann bei Bedarf angepasst werden, wenn eine SMB-Freigabe erstellt oder geändert wird.

Einzelheiten zum Abschnitt link:architecture-concept.html["Antivirus Architektur"] bezüglich des _Vscan file-operations profile_.

[NOTE]
====
Die Virenprüfung wird auf einer SMB-Freigabe, bei der der  `continuously-available` Parameter auf  `Yes` gesetzt ist, nicht durchgeführt.

====
.Schritt
. Den Wert des Vscan Dateioperationsprofils für eine SMB-Freigabe anpassen:
+
`vserver cifs share modify -vserver _data_SVM_ -share-name _share_ -path _share_path_ -vscan-fileop-profile no-scan|standard|strict|writes-only`

+
Weitere Informationen zu  `vserver cifs share modify` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-share-modify.html["ONTAP-Befehlsreferenz"^].

+
Der folgende Befehl ändert das Vscan-Dateioperationsprofil für eine SMB-Freigabe zu `strict`:

+
[listing]
----
cluster1::> vserver cifs share modify -vserver vs1 -share-name SALES_SHARE -path /sales -vscan-fileop-profile strict
----

