---
permalink: antivirus/modify-vscan-file-profile-smb-share-task.html 
sidebar: sidebar 
keywords: modify, vscan, file-operations, profile, cifs share 
summary: 'Das Profil _Vscan file-Operations_ für eine SMB-Freigabe definiert die Vorgänge auf der Freigabe, die einen Scan auslösen können. Standardmäßig ist der Parameter auf eingestellt `standard`. Sie können den Parameter beim Erstellen oder Ändern einer SMB-Freigabe nach Bedarf anpassen.' 
---
= Ändern Sie das ONTAP Vscan-Dateioperationsprofil für SMB-Freigaben
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Profil _Vscan file-Operations_ für eine SMB-Freigabe definiert die Vorgänge auf der Freigabe, die einen Scan auslösen können. Standardmäßig ist der Parameter auf eingestellt `standard`. Sie können den Parameter beim Erstellen oder Ändern einer SMB-Freigabe nach Bedarf anpassen.

Weitere link:architecture-concept.html["Virenschutz-Architektur"]Informationen zum Profil _Vscan file-Operations_ finden Sie im  Abschnitt.

[NOTE]
====
Der Virenscan wird nicht auf einer SMB-Freigabe durchgeführt, die den `continuously-available` Parameter auf gesetzt hat `Yes`.

====
.Schritt
. Ändern Sie den Wert des Vscan-Dateioperationsprofils für eine SMB-Freigabe:
+
`vserver cifs share modify -vserver _data_SVM_ -share-name _share_ -path _share_path_ -vscan-fileop-profile no-scan|standard|strict|writes-only`

+
Erfahren Sie mehr über `vserver cifs share modify` in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-share-modify.html["ONTAP-Befehlsreferenz"^].

+
Mit dem folgenden Befehl wird das Profil der Vscan-Dateioperationen für eine SMB-Freigabe in geändert `strict`:

+
[listing]
----
cluster1::> vserver cifs share modify -vserver vs1 -share-name SALES_SHARE -path /sales -vscan-fileop-profile strict
----

