---
permalink: antivirus/monitor-status-performance-activities-reference.html 
sidebar: sidebar 
keywords: monitoring, performance, status, connection, statistics 
summary: Sie können kritische Probleme des Vscan Servers überwachen. 
---
= ONTAP Vscan Status und Leistungsaktivitäten überwachen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die kritischen Aspekte des Vscan-Moduls überwachen, wie beispielsweise den Verbindungsstatus des Vscan-Servers, den Zustand der Vscan-Server und die Anzahl der gescannten Dateien. Diese Informationen unterstützen die Diagnose von Problemen im Zusammenhang mit dem Vscan-Server.



[[view-vscan-server-connection-information]]
== Vscan-Serververbindungsinformationen

Sie können den Verbindungsstatus der Vscan-Server einsehen, um die bereits verwendeten und die verfügbaren Verbindungen zu verwalten. Verschiedene Befehle zeigen Informationen zum Verbindungsstatus der Vscan-Server an.

|===


| Befehl... | Angezeigte Informationen... 


 a| 
`vserver vscan connection-status show`
 a| 
Zusammenfassung des Verbindungsstatus



 a| 
`vserver vscan connection-status show-all`
 a| 
Detaillierte Informationen zum Verbindungsstatus



 a| 
`vserver vscan connection-status show-not-connected`
 a| 
Status der verfügbaren, aber nicht verbundenen Verbindungen



 a| 
`vserver vscan connection-status show-connected`
 a| 
Informationen zum verbundenen Vscan Server

|===
Weitere Informationen zu  `vserver vscan connection-status show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-connection-status-show.html["ONTAP-Befehlsreferenz"^].



[[view-vscan-server-statistics]]
== Vscan Serverstatistiken

Sie können Vscan-Server-spezifische Statistiken anzeigen, um die Leistung zu überwachen und Probleme im Zusammenhang mit der Virenprüfung zu diagnostizieren. Eine Datenerfassung ist erforderlich, bevor der  `statistics show` Befehl zum Anzeigen der Vscan-Serverstatistiken verwendet werden kann.

Weitere Informationen zu  `statistics show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/statistics-show.html["ONTAP-Befehlsreferenz"^].

Um eine Datenprobe zu vervollständigen, ist folgender Schritt erforderlich:

.Schritt
. Den  `statistics start`Befehl und den optionalen  `statistics stop`Befehl ausführen.
+
Weitere Informationen zu  `statistics start` und  `statistics stop` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=statistics["ONTAP-Befehlsreferenz"^].





[[view-statistics-for-vscan-server-requests-and-latencies]]
=== Statistiken zu Vscan Serveranfragen und Latenzen anzeigen

Sie können ONTAP `offbox_vscan` Zähler pro SVM verwenden, um die Rate der pro Sekunde gesendeten und empfangenen Vscan-Serveranfragen sowie die Serverlatenzen aller Vscan-Server zu überwachen. Zum Anzeigen dieser Statistiken ist folgender Schritt erforderlich:

.Schritt
. Den  `statistics show -object offbox_vscan –instance SVM`Befehl mit den folgenden Zählern ausführen:
+
|===


| Zähler... | Angezeigte Informationen... 


 a| 
`scan_request_dispatched_rate`
 a| 
Anzahl der von ONTAP pro Sekunde an die Vscan-Server gesendeten Virenscan-Anfragen



 a| 
`scan_noti_received_rate`
 a| 
Anzahl der von den Vscan-Servern pro Sekunde an ONTAP zurückgesendeten Virenscan-Anfragen



 a| 
`dispatch_latency`
 a| 
Latenz innerhalb von ONTAP beim Ermitteln eines verfügbaren Vscan Servers und beim Senden der Anfrage an diesen Vscan Server



 a| 
`scan_latency`
 a| 
Roundtrip-Latenz von ONTAP zum Vscan Server, einschließlich der Zeit für die Durchführung des Scans

|===




==== Beispiel für Statistiken, die von einem ONTAP Offbox vscan-Zähler generiert wurden

[listing]
----
Object: offbox_vscan
Instance: SVM
Start-time: 10/16/2013 10:13:25
End-time: 10/16/2013 10:25:11
Cluster: cluster01
Number of Constituents: 2 (complete_aggregation)
Counter Value
-------------------------------- --------------------------------
scan_request_dispatched_rate 291
scan_noti_received_rate 292
dispatch_latency 43986us
scan_latency 3433501us
-----------------------------------------------------------------
----


[[view-statistics-for-individual-vscan-server-requests-and-latencies]]
=== Statistiken zu einzelnen Vscan Serveranfragen und Latenzen

Sie können ONTAP `offbox_vscan_server` Zähler pro SVM, pro externem Vscan Server und pro Knoten verwenden, um die Rate der gesendeten Vscan Server-Anfragen und die Serverlatenz jedes einzelnen Vscan Servers zu überwachen. Zum Erfassen dieser Informationen ist folgender Schritt erforderlich:

.Schritt
. Den  `statistics show –object offbox_vscan –instance
SVM:servername:nodename`Befehl mit den folgenden Zählern ausführen:
+
|===


| Zähler... | Angezeigte Informationen... 


 a| 
`scan_request_dispatched_rate`
 a| 
Anzahl der von ONTAP gesendeten Virenscan-Anfragen



 a| 
`scan_latency`
 a| 
Roundtrip-Latenz von ONTAP zum Vscan-Server, einschließlich der Zeit, die der Scan pro Sekunde für die Ausführung zu den Vscan-Servern benötigt

|===




==== Beispiel für Statistiken, die von einem ONTAP offbox_vscan_server Zähler generiert wurden

[listing]
----
Object: offbox_vscan_server
Instance: SVM:vscan_server:node
Start-time: 10/16/2013 10:13:25
End-time: 10/16/2013 10:25:11
Cluster: cluster01
Number of Constituents: 1 (complete_aggregation)
Counter Value
-------------------------------- --------------------------------
scan_request_dispatched_rate 291
scan_latency 3433830us
------------------------------------------------------------------
----


[[view-statistics-for-vscan-server-utilization]]
=== Statistiken zur Vscan Serverauslastung

Sie können auch ONTAP `offbox_vscan_server`-Zähler verwenden, um serverseitige Auslastungsstatistiken für Vscan zu erfassen. Diese Statistiken werden pro SVM, pro externem Vscan-Server und pro Knoten erfasst. Sie umfassen die CPU-Auslastung des Vscan-Servers, die Warteschlangentiefe für Scanvorgänge auf dem Vscan-Server (sowohl aktuell als auch maximal), den verwendeten Speicher und das verwendete Netzwerk. Diese Statistiken werden vom Antivirus Connector an die Statistikzähler innerhalb von ONTAP weitergeleitet. Sie basieren auf Daten, die alle 20 Sekunden abgefragt werden und für genaue Ergebnisse mehrfach erfasst werden müssen, andernfalls spiegeln die in den Statistiken angezeigten Werte nur die letzte Abfrage wider. CPU-Auslastung und Warteschlangen sind besonders wichtig für die Überwachung und Analyse. Ein hoher Wert für eine durchschnittliche Warteschlange kann darauf hinweisen, dass der Vscan-Server einen Engpass hat. Um Auslastungsstatistiken für den Vscan-Server pro SVM, pro externem Vscan-Server und pro Knoten zu erfassen, ist folgender Schritt erforderlich:

.Schritt
. Nutzungsstatistiken für den Vscan Server erfassen
+
Den  `statistics show –object offbox_vscan_server –instance
SVM:servername:nodename` Befehl mit den folgenden  `offbox_vscan_server` Zählern ausführen:



|===


| Zähler... | Angezeigte Informationen... 


 a| 
`scanner_stats_pct_cpu_used`
 a| 
CPU-Auslastung auf dem Vscan Server



 a| 
`scanner_stats_pct_input_queue_avg`
 a| 
Durchschnittliche Warteschlange der Scan-Anfragen auf dem Vscan Server



 a| 
`scanner_stats_pct_input_queue_hiwatermark`
 a| 
Maximale Anzahl an Scan-Anfragen auf dem Vscan Server



 a| 
`scanner_stats_pct_mem_used`
 a| 
Speichernutzung auf dem Vscan Server



 a| 
`scanner_stats_pct_network_used`
 a| 
Im Vscan Server verwendetes Netzwerk

|===


==== Beispiel für Auslastungsstatistiken des Vscan-Servers

[listing]
----
Object: offbox_vscan_server
Instance: SVM:vscan_server:node
Start-time: 10/16/2013 10:13:25
End-time: 10/16/2013 10:25:11
Cluster: cluster01
Number of Constituents: 1 (complete_aggregation)
Counter Value
-------------------------------- --------------------------------
scanner_stats_pct_cpu_used 51
scanner_stats_pct_dropped_requests 0
scanner_stats_pct_input_queue_avg 91
scanner_stats_pct_input_queue_hiwatermark 100
scanner_stats_pct_mem_used 95
scanner_stats_pct_network_used 4
-----------------------------------------------------------------
----
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/index.html["ONTAP-Befehlsreferenz"^]

