---
permalink: antivirus/reset-status-scanned-files-task.html 
sidebar: sidebar 
keywords: reset, status, scanned files 
summary: Gelegentlich möchten Sie den Scanstatus erfolgreich gescannter Dateien auf einer SVM mithilfe des vserver vscan RESET -Befehls zurücksetzen, um die zwischengespeicherten Informationen für die Dateien zu verwerfen. Mit diesem Befehl können Sie beispielsweise die Virenüberprüfung neu starten, wenn ein falsch konfigurierter Scan durchgeführt wird. 
---
= Setzen Sie den Status der gescannten Dateien zurück
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gelegentlich möchten Sie den Scanstatus erfolgreich gescannter Dateien auf einer SVM mithilfe von zurücksetzen `vserver vscan reset` Befehl zum Verwerfen der zwischengespeicherten Informationen für die Dateien. Mit diesem Befehl können Sie beispielsweise die Virenüberprüfung neu starten, wenn ein falsch konfigurierter Scan durchgeführt wird.

.Über diese Aufgabe
Nachdem Sie den ausgeführt haben `vserver vscan reset` Befehl: Alle geeigneten Dateien werden beim nächsten Zugriff gescannt.

[NOTE]
====
Dieser Befehl kann sich nachteilig auf die Performance auswirken, abhängig von der Anzahl und Größe der neu zu speicherenden Dateien.

====
.Bevor Sie beginnen
Für diese Aufgabe sind erweiterte Berechtigungen erforderlich.

.Schritte
. Ändern Sie die erweiterte Berechtigungsebene:
+
`set -privilege advanced`

. Status der gescannten Dateien zurücksetzen:
+
`vserver vscan reset -vserver data_SVM`

+
Mit dem folgenden Befehl wird der Status der gescannten Dateien auf dem zurückgesetzt `vs1` SVM:

+
[listing]
----
cluster1::> vserver vscan reset -vserver vs1
----

