---
permalink: antivirus/schedule-on-demand-task-task.html 
sidebar: sidebar 
keywords: schedule, on-demand, task 
summary: Wenn Sie eine On-Demand-Aufgabe erstellt haben, ohne einen Zeitplan zuzuweisen, oder wenn Sie einer Aufgabe einen anderen Zeitplan zuweisen möchten, können Sie den Befehl vserver vscan On-Demand-Task Schedule verwenden, um der Aufgabe einen Zeitplan zuzuweisen. 
---
= On-Demand-Aufgabe planen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie eine On-Demand-Aufgabe erstellt haben, ohne einen Zeitplan zuzuweisen, oder wenn Sie einer Aufgabe einen anderen Zeitplan zuweisen möchten, können Sie das verwenden `vserver vscan on-demand-task schedule` Befehl zum Zuweisen eines Zeitplans zu der Aufgabe.

Der mit dem zugewiesene Zeitplan `vserver vscan on-demand-task schedule` Der Befehl überschreibt einen Zeitplan, der bereits dem zugewiesen ist `vserver vscan on-demand-task create` Befehl.

.Schritte
. Planung einer On-Demand-Aufgabe:
+
`vserver vscan on-demand-task schedule -vserver data_SVM -task-name task_name -schedule cron_schedule`

+
Der folgende Befehl plant eine Aufgabe mit dem Namen „On Access“ `Task2` Auf dem ``vs2``SVM:

+
[listing]
----
cluster1::> vserver vscan on-demand-task schedule -vserver vs2 -task-name Task2 -schedule daily
[Job 142]: Vscan On-Demand job is queued. Use the "job show -id 142" command to view the status.
----
+
[NOTE]
====
Sie können das verwenden `job show` Befehl zum Anzeigen des Status des Jobs. Sie können das verwenden `job pause` Und `job resume` Befehle zum Anhalten und Neustarten des Jobs oder `job stop` Befehl zum Beenden des Jobs.

====
. Vergewissern Sie sich, dass die On-Demand-Aufgabe geplant ist: `vserver vscan on-demand-task show -instance data_SVM -task-name task_name`
+
Eine vollständige Liste der Optionen finden Sie auf der man-Page für den Befehl.

+
Mit dem folgenden Befehl werden die Details für das angezeigt `Task 2` Aufgabe:

+
[listing]
----
cluster1::> vserver vscan on-demand-task show -instance vs2 -task-name Task2

                           Vserver: vs2
                         Task Name: Task2
                List of Scan Paths: /vol1/, /vol2/cifs/
             Report Directory Path: /report
                      Job Schedule: daily
Max File Size Allowed for Scanning: 5GB
            File Paths Not to Scan: /vol1/cold-files/
       File Extensions Not to Scan: mp3, mp4
           File Extensions to Scan: vmdk, mp*
      Scan Files with No Extension: false
           Request Service Timeout: 5m
                    Cross Junction: true
               Directory Recursion: true
                     Scan Priority: low
                  Report Log Level: info
----


Sie müssen den Scan auf der SVM aktivieren, bevor die Aufgabe geplant werden soll.
