---
permalink: antivirus/schedule-on-demand-task-task.html 
sidebar: sidebar 
keywords: schedule, on demand, task 
summary: Sie können eine Aufgabe erstellen, ohne ihr einen Zeitplan zuzuweisen, oder beim Erstellen der Aufgabe einen Zeitplan hinzufügen. 
---
= Bedarfsabhängige Aufgaben mit ONTAP Vscan planen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Aufgabe erstellen, ohne ihr einen Zeitplan zuzuweisen, und den  `vserver vscan on-demand-task schedule` Befehl verwenden, um einen Zeitplan zuzuweisen, oder beim Erstellen der Aufgabe einen Zeitplan hinzufügen.

.Über diese Aufgabe
Der mit dem  `vserver vscan on-demand-task schedule` Befehl zugewiesene Zeitplan überschreibt einen bereits mit dem  `vserver vscan on-demand-task create` Befehl zugewiesenen Zeitplan.

.Schritte
. Eine Aufgabe auf Abruf planen:
+
`vserver vscan on-demand-task schedule -vserver _data_SVM_ -task-name _task_name_ -schedule cron_schedule`

+
Der folgende Befehl plant eine On-Access-Aufgabe mit dem Namen  `Task2` auf der  `vs2` SVM:

+
[listing]
----
cluster1::> vserver vscan on-demand-task schedule -vserver vs2 -task-name Task2 -schedule daily
[Job 142]: Vscan On-Demand job is queued. Use the "job show -id 142" command to view the status.
----
+
Weitere Informationen zu  `vserver vscan on-demand-task schedule` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-on-demand-task-schedule.html["ONTAP-Befehlsreferenz"^].

+

NOTE: Um den Status des Auftrags anzuzeigen, kann der  `job show` Befehl verwendet werden. Die  `job pause`- und  `job resume`-Befehle pausieren bzw. starten den Auftrag neu, der  `job stop`-Befehl beendet den Auftrag. Weitere Informationen zu  `job` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=job["ONTAP-Befehlsreferenz"^].

. Es sollte überprüft werden, ob die Aufgabe auf Abruf eingeplant wurde:
+
`vserver vscan on-demand-task show -instance _data_SVM_ -task-name _task_name_`

+
Weitere Informationen zu  `vserver vscan on-demand-task show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-on-demand-task-show.html["ONTAP-Befehlsreferenz"^].

+
Der folgende Befehl zeigt die Details für die  `Task 2` Aufgabe an:

+
[listing]
----
cluster1::> vserver vscan on-demand-task show -instance vs2 -task-name Task2

                           Vserver: vs2
                         Task Name: Task2
                List of Scan Paths: /vol1/, /vol2/cifs/
             Report Directory Path: /report
                      Job Schedule: daily
Max File Size Allowed for Scanning: 5GB
            File Paths Not to Scan: /vol1/cold-files/
       File Extensions Not to Scan: mp3, mp4
           File Extensions to Scan: vmdk, mp*
      Scan Files with No Extension: false
           Request Service Timeout: 5m
                    Cross Junction: true
               Directory Recursion: true
                     Scan Priority: low
                  Report Log Level: info
----


.Nachdem Sie fertig sind
Das Scannen auf der SVM muss aktiviert sein, bevor der Task zur Ausführung geplant wird.
