---
permalink: antivirus/troubleshoot-common-virus-scanning-issues-reference.html 
sidebar: sidebar 
keywords: troubleshooting, troubleshoot, virus scanning, vscan, monitoring, connection, connectivity 
summary: Eine Tabelle mit häufigen Problemen beim Virenscannen, deren möglichen Ursachen und Möglichkeiten, diese zu beheben. 
---
= Fehlerbehebung beim Virenscan
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei häufigen Problemen mit der Virenprüfung gibt es mögliche Ursachen und Möglichkeiten, diese zu lösen. Virus-Scan wird auch als Vscan bezeichnet.

|===


| Problem | Wie man es löst 


 a| 
Die Vscan Server können keine Verbindung zum Clustered ONTAP Storage-System herstellen.
 a| 
Prüfen Sie, ob die Scannerpoolkonfiguration die IP-Adresse des Vscan-Servers angibt. Überprüfen Sie auch, ob die zulässigen privilegierten Benutzer in der Scannerpoolliste aktiv sind. Führen Sie zum Überprüfen des Scannerpools den `vserver vscan scanner-pool show` Befehl an der Eingabeaufforderung des Speichersystems aus. Wenn die Vscan-Server immer noch keine Verbindung herstellen können, liegt möglicherweise ein Problem mit dem Netzwerk vor.



 a| 
Bei Clients beobachten wir eine hohe Latenz.
 a| 
Es ist wahrscheinlich an der Zeit, dem Scanner-Pool weitere Vscan-Server hinzuzufügen.



 a| 
Es werden zu viele Scans ausgelöst.
 a| 
Ändern Sie den Wert des `vscan-fileop-profile` Parameters, um die Anzahl der für die Virenprüfung überwachten Dateioperationen einzuschränken.



 a| 
Einige Dateien werden nicht gescannt.
 a| 
Überprüfen Sie die Zugangsrichtlinie. Es ist möglich, dass der Pfad für diese Dateien zur Pfadausschlussliste hinzugefügt wurde oder dass ihre Größe den konfigurierten Wert für Ausschlüsse überschreitet. Führen Sie zum Überprüfen der Richtlinie für den Zugriff den `vserver vscan on-access-policy show` Befehl an der Eingabeaufforderung des Speichersystems aus.



 a| 
Dateizugriff wurde verweigert.
 a| 
Prüfen Sie, ob die Einstellung „_Scan-mandatory_“ in der Richtlinienkonfiguration angegeben ist. Diese Einstellung verweigert den Datenzugriff, wenn keine Vscan-Server verbunden sind. Ändern Sie die Einstellung nach Bedarf.

|===
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-scanner-pool-show.html["vserver vscan scanner-pool zeigen"^]
* link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-on-access-policy-show.html["vserver vscan On-Access-Policy zeigen"^]

