---
permalink: antivirus/troubleshoot-common-virus-scanning-issues-reference.html 
sidebar: sidebar 
keywords: troubleshooting, troubleshoot, virus scanning, vscan, monitoring, connection, connectivity 
summary: Eine Tabelle mit häufigen Problemen beim Virenscannen, deren möglichen Ursachen und Möglichkeiten, diese zu beheben. 
---
= Fehlerbehebung beim Virenscan
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei häufigen Problemen mit der Virenprüfung gibt es mögliche Ursachen und Möglichkeiten, diese zu lösen. Virus-Scan wird auch als Vscan bezeichnet.

|===


| Problem | Wie man es löst 


 a| 
Die Vscan-Server können keine Verbindung herstellen
Dem Storage-System Clustered ONTAP
 a| 
Prüfen Sie, ob die Scannerpoolkonfiguration den angibt
IP-Adresse des Vscan-Servers. Überprüfen Sie auch, ob das zugelassen ist
Privilegierte Benutzer in der Scannerpoolliste sind aktiv. Führen Sie zum Überprüfen des Scannerpools den aus `vserver vscan scanner-pool show` In der Eingabeaufforderung des Storage-Systems.
Wenn die Vscan-Server immer noch keine Verbindung herstellen können, liegt möglicherweise ein Problem mit dem Netzwerk vor.



 a| 
Bei Clients beobachten wir eine hohe Latenz
 a| 
Es ist wahrscheinlich an der Zeit, dem weitere Vscan-Server hinzuzufügen
Scanner-Pool.



 a| 
Es werden zu viele Scans ausgelöst
 a| 
Ändern Sie den Wert des `vscan-fileop-profile`
Parameter, um die Anzahl der Dateioperationen einzuschränken
Überwachung auf Virenscans.



 a| 
Einige Dateien werden nicht gescannt.
 a| 
Überprüfen Sie die Zugangsrichtlinie. Es ist möglich, dass der Pfad für
Diese Dateien wurden der Pfadausschlussliste oder der Liste hinzugefügt
Ihre Größe überschreitet den konfigurierten Wert für Ausschlüsse. Bis
Überprüfen Sie die Richtlinie beim Zugriff, führen Sie den aus `vserver vscan
on-access-policy show` Befehl auf dem Speicher
Eingabeaufforderung des Systems.



 a| 
Dateizugriff wurde verweigert.
 a| 
Prüfen Sie, ob die Einstellung „Scan-obligatorisch“ angegeben ist
In der Richtlinienkonfiguration. Diese Einstellung verweigert den Datenzugriff
Wenn keine Vscan-Server verbunden sind. Ändern Sie die Einstellung als
Angemessen.

|===