---
permalink: antivirus/troubleshoot-common-virus-scanning-issues-reference.html 
sidebar: sidebar 
keywords: troubleshooting, troubleshoot, virus scanning, vscan, monitoring, connection, connectivity 
summary: Eine Tabelle mit häufigen Problemen beim Virenscan, deren möglichen Ursachen und Möglichkeiten zu deren Behebung. 
---
= Fehlerbehebung bei ONTAP Vscan Virenscans
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für häufige Probleme beim Virenscan gibt es mögliche Ursachen und Lösungsansätze. Der Virenscan ist auch als Vscan bekannt.

|===


| Problem | Wie das Problem behoben werden kann 


 a| 
Die Vscan Server können keine Verbindung zum geclusterten ONTAP Speichersystem herstellen.
 a| 
Es ist zu prüfen, ob die Konfiguration des scanner-pool die IP-Adresse des Vscan Server angibt. Ebenso ist zu prüfen, ob die in der scanner-pool Liste aufgeführten privilegierten Benutzer aktiv sind. Zur Überprüfung des scanner-pool ist der  `vserver vscan scanner-pool show` Befehl an der Eingabeaufforderung des Speichersystems auszuführen. Sollten die Vscan Server weiterhin keine Verbindung herstellen können, könnte ein Problem mit dem Netzwerk vorliegen.



 a| 
Clients bemerken hohe Latenzzeiten.
 a| 
Es ist wahrscheinlich an der Zeit, dem scanner-pool weitere Vscan-Server hinzuzufügen.



 a| 
Es werden zu viele Scans ausgelöst.
 a| 
Den Wert des  `vscan-fileop-profile`Parameters anpassen, um die Anzahl der für die Virenprüfung überwachten Dateivorgänge einzuschränken.



 a| 
Einige Dateien werden nicht gescannt.
 a| 
Die On-Access-Richtlinie prüfen. Es ist möglich, dass der Pfad dieser Dateien zur Pfadausschlussliste hinzugefügt wurde oder dass ihre Größe den konfigurierten Wert für Ausschlüsse überschreitet. Zum Prüfen der On-Access-Richtlinie den  `vserver vscan on-access-policy show` Befehl an der Eingabeaufforderung des Speichersystems ausführen.



 a| 
Der Zugriff auf die Datei ist verweigert.
 a| 
Es sollte geprüft werden, ob die Einstellung „scan-mandatory“ in der Richtlinienkonfiguration angegeben ist. Diese Einstellung verweigert den Datenzugriff, wenn keine Vscan Server verbunden sind. Die Einstellung kann bei Bedarf angepasst werden.

|===
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-scanner-pool-show.html["vserver vscan scanner-pool show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-on-access-policy-show.html["vserver vscan on-access-policy show"^]

