---
permalink: antivirus/vscan-server-install-config-concept.html 
sidebar: sidebar 
keywords: vscan, server installation, configuration 
summary: Sie müssen einen oder mehrere Vscan Server einrichten und konfigurieren, um die Virenprüfung zu aktivieren. 
---
= ONTAP Vscan Serverinstallation und -konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein oder mehrere Vscan Server werden eingerichtet, damit die Dateien auf Ihrem System auf Viren überprüft werden. Die vom Anbieter bereitgestellten Anweisungen dienen zur Installation und Konfiguration der Antivirensoftware auf dem Server.

Befolgen Sie die Anweisungen in der README-Datei von NetApp, um den ONTAP Antivirus Connector zu installieren und zu konfigurieren. Alternativ finden sich die Anweisungen auf der link:install-ontap-antivirus-connector-task.html["Seite zur Installation des ONTAP Antivirus Connector"].

[NOTE]
====
Für die Notfallwiederherstellung und MetroCluster Konfigurationen ist es erforderlich, separate Vscan Server für die primären/lokalen und sekundären/Partner ONTAP Cluster einzurichten und zu konfigurieren.

====


[[antivirus-software-requirements]]
== Anforderungen an Antivirensoftware

* Informationen zu den Anforderungen an Antivirensoftware sind in der Dokumentation des Herstellers enthalten.
* Informationen zu den von Vscan unterstützten Anbietern, der Software und den Versionen sind auf der link:../antivirus/vscan-partner-solutions.html["Vscan Partnerlösungen"] Seite zu finden.




[[ontap-antivirus-connector-requirements]]
== Anforderungen an den ONTAP Antivirus Connector

* Sie können den ONTAP Antivirus Connector von der Seite *Software Download* auf der NetApp Support Site herunterladen.link:http://mysupport.netapp.com/NOW/cgi-bin/software["NetApp Downloads: Software"^]
* Informationen zu den vom ONTAP Antivirus Connector unterstützten Windows-Versionen und den Interoperabilitätsanforderungen finden sich unter link:../antivirus/vscan-partner-solutions.html["Vscan Partnerlösungen"].
+
[NOTE]
====
Sie können verschiedene Versionen von Windows Server für unterschiedliche Vscan Server in einem Cluster installieren.

====
* Auf dem Windows Server muss .NET 3.0 oder höher installiert sein.
* SMB 2.0 muss auf dem Windows Server aktiviert sein.

