---
permalink: antivirus/vscan-server-install-config-concept.html 
sidebar: sidebar 
keywords: vscan, server installation, configuration 
summary: Sie müssen einen oder mehrere Vscan-Server einrichten und konfigurieren, um die Virenprüfung zu aktivieren. 
---
= Installation und Konfiguration des Vscan-Servers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen einen oder mehrere Vscan-Server einrichten und konfigurieren, um die Virenprüfung zu aktivieren.

* Befolgen Sie die Anweisungen Ihres Anbieters, um die Antivirensoftware auf dem Server zu installieren und zu konfigurieren.
* Um den ONTAP-Virenschutzanschluss zu installieren und zu konfigurieren, befolgen Sie die Anweisungen im `README.txt` Datei auf dem verfügbar
https://mysupport.netapp.com/site/products/all/details/ontap-antivirus-connector/downloads-tab["NetApp Support Website"].


[NOTE]
====
Für Disaster Recovery- und MetroCluster-Konfigurationen müssen Sie separate Vscan-Server für die primären/lokalen und sekundären/Partner-ONTAP-Cluster einrichten und konfigurieren.

====


== Anforderungen an die Virenschutz-Software

* Informationen zu den Anforderungen an Antivirensoftware finden Sie in der Dokumentation des Anbieters.
* Informationen zu den von Vscan unterstützten Herstellern, Software und Versionen finden Sie im
https://imt.netapp.com/matrix/["NetApp Interoperabilitäts-Matrix-Tool (IMT)"].




== Anforderungen für den Antivirus Connector von ONTAP

* Sie können diese Software von herunterladen
https://mysupport.netapp.com/site/products/all/details/ontap-antivirus-connector/downloads-tab/download/63048/1.0.6["NetApp Support Website"] (Anmeldung erforderlich).
* Informationen zur Unterstützung von Softwareversionen finden Sie im
https://imt.netapp.com/matrix/["NetApp Interoperabilitäts-Matrix-Tool (IMT)"].




== Konfigurationsanforderungen für den Vscan-Server

* Sie müssen .NET 3.0 oder höher installieren und SMB 2.0 auf dem Vscan-Server aktivieren. Für SMB-Server mit einer Exportrichtlinie müssen Sie alle Vscan-Server zur Richtlinie hinzufügen.
* Sie können verschiedene Versionen von Windows Server OS auf verschiedenen Vscan-Servern in einem Cluster installieren. Mindestens Windows Server 2008 ist für den ONTAP Antivirus Connector erforderlich.

