---
permalink: antivirus/vscan-server-connection-concept.html 
sidebar: sidebar 
keywords: potential connectivity, issues, involve, scan-mandatory, option 
summary: Standardmäßig wird durch die Option Scan-obligatorisches Scannen beim Scannen beim Zugriff der Dateizugriff verweigert, wenn keine Vscan-Serververbindung zum Scannen verfügbar ist. Obwohl diese Option wichtige Sicherheitsfunktionen bietet, kann sie in einigen Situationen zu Problemen führen. 
---
= Mögliche Verbindungsprobleme bei der Option „Scannen erforderlich“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit den `vserver vscan connection-status show` Befehlen können Sie Informationen zu Vscan-Serververbindungen anzeigen, die Sie bei der Behebung von Verbindungsproblemen hilfreich finden.

Standardmäßig `scan-mandatory` verweigert die Option zum Scannen beim Zugriff den Dateizugriff, wenn keine Vscan-Serververbindung zum Scannen verfügbar ist. Obwohl diese Option wichtige Sicherheitsfunktionen bietet, kann sie in einigen Situationen zu Problemen führen.

* Bevor Sie den Client-Zugriff aktivieren, müssen Sie sicherstellen, dass mindestens ein Vscan-Server mit einer SVM auf jedem Node mit einer LIF verbunden ist. Wenn Sie nach Aktivierung des Client-Zugriffs Server mit SVMs verbinden müssen, müssen Sie die `scan-mandatory` Option auf der SVM deaktivieren, um sicherzustellen, dass der Dateizugriff nicht verweigert wird, da keine Vscan-Serververbindung verfügbar ist. Sie können die Option wieder einschalten, nachdem der Server verbunden ist.
* Wenn ein Ziel-LIF alle Vscan-Serververbindungen für eine SVM hostet, geht die Verbindung zwischen dem Server und der SVM verloren, wenn die LIF migriert wird. Um sicherzustellen, dass der Dateizugriff nicht verweigert wird, weil keine Vscan-Serververbindung verfügbar ist, müssen Sie die `scan-mandatory` Option vor der Migration der LIF deaktivieren. Sie können die Option wieder einschalten, nachdem das LIF migriert wurde.


Jeder SVM sollten mindestens zwei Vscan-Server zugewiesen sein. Als Best Practice wird empfohlen, Vscan-Server über ein anderes Netzwerk als den für Client-Zugriffe verwendeten Vscan-Servern mit dem Speichersystem zu verbinden.

Erfahren Sie mehr über `vserver vscan connection-status show` in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-connection-status-show.html["ONTAP-Befehlsreferenz"^].
