---
permalink: revert/anti-ransomware-license-task.html 
sidebar: sidebar 
keywords: revert, reverting, reversion, anti-ransomware, autonomous, protection, arp, license, licensing 
summary: Wenn Sie einen Ransomware-Schutz konfiguriert haben und von ONTAP 9.11.1 oder höher auf ONTAP 9.10.1 umkehren, sind möglicherweise Warnhinweise und eine eingeschränkte Anti-Ransomware-Funktionalität vorhanden. 
---
= Überprüfen Sie vor dem Wechsel von ONTAP 9.11.1 oder höher die Lizenz für den autonomen Ransomware-Schutz
:allow-uri-read: 


[role="lead"]
Wenn Sie Autonomous Ransomware Protection (ARP) konfiguriert haben und Sie von ONTAP 9.11.1 oder höher zu ONTAP 9.10.1 oder früher zurückkehren, können Sie möglicherweise Warnmeldungen und eingeschränkte ARP-Funktionalität erleben.

In ONTAP 9.11.1 ersetzte die Anti-Ransomware-Lizenz die Multi-Tenant Key Management (MTKM)-Lizenz. Wenn Ihr System die Anti_Ransomware-Lizenz hat, aber keine MT_EK_MGMT-Lizenz, sehen Sie eine Warnung während Revert, dass ARP auf neuen Volumes bei revert nicht aktiviert werden kann.

Die Volumes mit vorhandenem Schutz funktionieren nach Zurücksetzen weiterhin ordnungsgemäß und der ARP-Status kann mithilfe der ONTAP-CLI angezeigt werden. System Manager kann den ARP-Status ohne die MTKM-Lizenz nicht anzeigen.

Wenn Sie die ARP-Lizenz nach dem Zurücksetzen auf ONTAP 9.10.1 fortsetzen möchten, stellen Sie daher sicher, dass die MTKM-Lizenz installiert ist, bevor Sie sie zurücksetzen. link:../anti-ransomware/index.html["Weitere Informationen zur ARP-Lizenzierung."]
