---
permalink: revert/arp-warning-clear-revert.html 
sidebar: sidebar 
keywords: ontap, revert, ransomware, protection, security, arp 
summary: Bevor ONTAP zurückgesetzt wird, sollten alle Warnungen vor ungewöhnlichen Aktivitäten in ARP berücksichtigt werden. 
---
= Aktivitätswarnungen im Autonomous Ransomware Protection (ARP) sollten vor einem ONTAP-Revert behoben werden.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor auf ONTAP 9.17.1 oder eine frühere Version zurückgekehrt wird, sollten alle von Autonomous Ransomware Protection (ARP) gemeldeten Warnungen zu ungewöhnlichen Aktivitäten berücksichtigt und alle zugehörigen ARP-Screenshots gelöscht werden.

.Bevor Sie beginnen
Sie benötigen „Advanced“ Berechtigungen, um ARP-Snapshots zu löschen.

.Schritte
. Auf alle von link:../anti-ransomware/respond-abnormal-task.html["ARP"] gemeldeten Warnungen zu ungewöhnlichen Aktivitäten reagieren und mögliche Probleme beheben.
. Die Behebung dieser Probleme sollte vor dem Rückgängigmachen bestätigt werden, indem *Aktualisieren und Verdächtige Dateitypen löschen* ausgewählt wird, um die Entscheidung zu protokollieren und die normale ARP-Überwachung fortzusetzen.
. Alle mit den Warnungen verbundenen ARP-Screenshots werden durch Ausführen des folgenden Befehls aufgelistet:
+
[source, cli]
----
volume snapshot snapshot show -fs-version 9.18
----
. Alle ARP-Screenshots, die mit den Warnungen in Verbindung stehen, löschen:
+

NOTE: Dieser Befehl löscht alle Snapshots, die das von der aktuellen Version von ONTAP verwendete Format haben, möglicherweise nicht nur ARP-Snapshots. Es sollte sichergestellt werden, dass alle erforderlichen Maßnahmen für alle Snapshots, die entfernt werden, vor Ausführung dieses Befehls getroffen wurden.

+
[source, cli]
----
volume snapshot prepare-for-revert -node <node_name>
----

