---
permalink: revert/concept_revert_process_considerations.html 
sidebar: sidebar 
keywords: ontap, revert, limitations, issues 
summary: Vor Beginn einer ONTAP Reversion sind die Probleme und Einschränkungen bei der Rücksetzung zu berücksichtigen. 
---
= ONTAP Revert-Probleme und Einschränkungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor dem Zurücksetzen eines ONTAP Clusters sind die möglichen Probleme und Einschränkungen zu berücksichtigen.

* Die Rückführung ist störend.
+
Während der Wiederherstellung darf kein Clientzugriff erfolgen. Bei der Wiederherstellung eines Produktionsclusters sollte diese Unterbrechung in der Planung berücksichtigt werden.

* Die Rücksetzung betrifft alle Knoten im Cluster.
+
Die Rücksetzung betrifft alle Knoten im Cluster, allerdings muss die Rücksetzung auf jedem HA-Paar durchgeführt und abgeschlossen werden, bevor andere HA-Paare rückgesetzt werden.

+
link:https://docs.netapp.com/us-en/ontap-afx/administer/revert-ontap.html["AFX Storage-Systeme"^] Die Rücksetzung wird nicht unterstützt.

* Die Rücksetzung ist abgeschlossen, wenn auf allen Knoten die neue Zielversion ausgeführt wird.
+
Befindet sich der Cluster in einem gemischten Versionszustand, sollten keine Befehle eingegeben werden, die den Clusterbetrieb oder die Konfiguration verändern, es sei denn, dies ist zur Erfüllung der Reversionsanforderungen erforderlich; Überwachungsvorgänge sind zulässig.

+

IMPORTANT: Wenn Sie einige, aber nicht alle Knoten zurückgesetzt haben, sollte der Cluster nicht auf die Quellversion zurückaktualisiert werden.

* Wenn ein Knoten zurückgesetzt wird, werden die zwischengespeicherten Daten in einem Flash Cache Modul gelöscht.
+
Da im Flash Cache-Modul keine zwischengespeicherten Daten vorhanden sind, bedient der Knoten anfängliche Leseanfragen von der Festplatte, was in diesem Zeitraum zu einer verringerten Leseleistung führt. Der Knoten füllt den Cache wieder auf, während er Leseanfragen bearbeitet.

* Eine LUN, die auf Band gesichert wurde, während ONTAP 9.x ausgeführt wurde, kann nur auf 9.x und spätere Versionen wiederhergestellt werden und nicht auf eine frühere Version.
* Wenn Ihre aktuelle Version von ONTAP die In-Band ACP (IBACP)-Funktionalität unterstützt und Sie auf eine Version von ONTAP zurückkehren, die IBACP nicht unterstützt, wird der alternative Pfad zu Ihrem Disk Shelf deaktiviert.
* Wenn LDAP von einer Ihrer Storage Virtual Machines (SVMs) verwendet wird, muss die LDAP-Weiterleitung vor der Rückkehr auf eine frühere Version deaktiviert werden.
* In MetroCluster IP-Systemen mit Switches, die MetroCluster-konform, aber nicht MetroCluster-validiert sind, ist die Rückkehr von ONTAP 9.7 auf 9.6 disruptiv, da es keine Unterstützung für Systeme mit ONTAP 9.6 und älteren Versionen gibt.
* Bevor ein Knoten auf ONTAP 9.13.1 oder eine frühere Version zurückgesetzt wird, ist zunächst ein verschlüsseltes SVM-Root-Volume in ein nicht verschlüsseltes Volume zu konvertieren.
+
Wenn versucht wird, auf eine ONTAP Version zurückzukehren, die die Verschlüsselung des SVM-Root-Volumes nicht unterstützt, gibt das System eine Warnung aus und blockiert die Rückkehr.

* Wenn NFS über TLS in ONTAP 9.19.1 oder höher aktiviert ist, müssen alle NFS over TLS-Konfigurationsinstanzen deaktiviert werden, bevor auf eine frühere Version von ONTAP zurückgegangen werden kann. NFS over TLS wird erst ab ONTAP 9.19.1 unterstützt.

