---
permalink: revert/concept_revert_process_considerations.html 
sidebar: sidebar 
keywords: ontap, revert, considerations 
summary: Vor dem Beginn einer ONTAP-Umversion müssen die Probleme und Einschränkungen bei der Umrüstung berücksichtigt werden. 
---
= Überlegungen zurücksetzen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor dem Beginn einer ONTAP-Umversion müssen die Probleme und Einschränkungen bei der Umrüstung berücksichtigt werden.

* Die Umversion ist störend.
+
Während der Umversion kann kein Clientzugriff auftreten. Beim Wechsel eines Produktions-Clusters sollten Sie diese Störung in Ihrer Planung unbedingt berücksichtigen.

* Reversion wirkt sich auf alle Nodes im Cluster aus.
+
Die Umversion betrifft alle Nodes im Cluster. Die Umversion muss jedoch auf jedem HA-Paar ausgeführt und abgeschlossen werden, bevor andere HA-Paare zurückgesetzt werden.

* Die Umversion ist abgeschlossen, wenn auf allen Nodes der neue Zielversion ausgeführt wird.
+
Wenn sich das Cluster in einem gemischten Versionszustand befindet, sollten Sie keine Befehle eingeben, die den Cluster-Vorgang oder die Cluster-Konfiguration ändern, es sei denn, sie sind erforderlich, um Anforderungen bei der Umversion zu erfüllen. Monitoring-Vorgänge sind zulässig.

+

IMPORTANT: Wenn Sie einige, aber nicht alle Nodes zurückgesetzt haben, versuchen Sie nicht, das Cluster wieder auf die Quellversion zu aktualisieren.

* Wenn Sie einen Node zurücksetzen, werden die im Cache gespeicherten Daten in einem Flash Cache Modul gelöscht.
+
Da im Flash Cache Modul keine gecachten Daten vorhanden sind, stellt der Node die ersten Leseanforderungen von der Festplatte bereit. Dadurch wird während dieses Zeitraums die Lese-Performance verringert. Der Knoten füllt den Cache wieder aus, da er die Leseanforderungen bedient.

* Eine LUN, die auf Tape gesichert wird, die auf ONTAP 9.x ausgeführt wird, kann nur auf 9.x und neuere Versionen wiederhergestellt werden, nicht auf eine frühere Version.
* Wenn Ihre aktuelle Version von ONTAP die in-Band ACP-Funktion (IBACP) unterstützt und Sie eine Version von ONTAP zurücksetzen, die IBACP nicht unterstützt, ist der alternative Pfad zu Ihrem Festplatten-Shelf deaktiviert.
* Wenn LDAP von einer Ihrer Storage Virtual Machines (SVMs) verwendet wird, muss die LDAP-Empfehlung vor der Umversion deaktiviert werden.
* Bei MetroCluster IP-Systemen mit Switches, die MetroCluster-konform, aber nicht MetroCluster-validiert sind, ist die Umversion von ONTAP 9.7 zu 9.6 mit Unterbrechungen verbunden, da Systeme mit ONTAP 9.6 und früheren Versionen nicht unterstützt werden.

