---
permalink: revert/concept_revert_paths.html 
sidebar: sidebar 
keywords: ontap, downgrade, revert, paths 
summary: Sie können Ihre ONTAP Software direkt auf eine Version vor Ihrer aktuellen ONTAP Version zurücksetzen. Sie sollten nicht auf nicht unterstützte ONTAP-Versionen zurückgesetzt werden. 
---
= Unterstützte ONTAP Revert-Pfade
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Ihre ONTAP -Software direkt auf eine Version zurücksetzen, die nur eine Version vor Ihrer aktuellen ONTAP Version liegt.  Wenn Sie beispielsweise Version 9.15.1 verwenden, können Sie nicht direkt auf Version 9.13.1 zurückkehren.  Sie müssen zuerst auf Version 9.14.1 zurücksetzen; anschließend müssen Sie ein separates Zurücksetzen von 9.14.1 auf 9.13.1 durchführen.

Das Zurücksetzen auf ONTAP 9.4 oder eine frühere Version wird nicht unterstützt. Sie sollten nicht auf nicht unterstützte ONTAP-Versionen zurückgesetzt werden.

Sie können mit dem `system image show` Befehl die Version von ONTAP bestimmen, die auf jedem Node ausgeführt wird.

Die folgenden unterstützten Umkehrpfade beziehen sich ausschließlich auf lokale ONTAP Versionen. Informationen zum Zurücksetzen von ONTAP in der Cloud finden Sie unter https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html#reverting-or-downgrading["Zurücksetzen oder Downgrade von Cloud Volumes ONTAP"^].


NOTE: link:https://docs.netapp.com/us-en/ontap-afx/administer/revert-ontap.html["AFX-Speichersysteme"^]Die Rücksetzung der ONTAP -Software wird nicht unterstützt.

[cols="2*"]
|===
| Sie können zurücksetzen von... | An... 


 a| 
ONTAP 9.18.1
| ONTAP 9.17.1 


 a| 
ONTAP 9.17.1
| ONTAP 9.16.1 


 a| 
ONTAP 9.16.1
| ONTAP 9.15.1 


 a| 
ONTAP 9.15.1
| ONTAP 9.14.1 


 a| 
ONTAP 9.14.1
| ONTAP 9.13.1 


 a| 
ONTAP 9.13.1
| ONTAP 9.12.1 


 a| 
ONTAP 9.12.1
| ONTAP 9.11.1 


 a| 
ONTAP 9.11.1
| ONTAP 9.10.1 


 a| 
ONTAP 9.10.1
| ONTAP 9.9.1 


 a| 
ONTAP 9.9.1
| ONTAP 9,8 


 a| 
ONTAP 9,8
| ONTAP 9,7 


 a| 
ONTAP 9,7
| ONTAP 9,6 


 a| 
ONTAP 9,6
| ONTAP 9,5 
|===