---
permalink: revert/concept_reversion_requirements_for_snapmirror_and_snapvault_relationships.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, requirements, snapmirror, snapvault, relationships 
summary: Der Befehl „revert-to“ des Systemknotens benachrichtigt Sie über alle SnapMirror und SnapVault Beziehungen, die für den Abschluss des Rücksetzungsprozesses gelöscht oder neu konfiguriert werden müssen. Allerdings sollten diese Anforderungen vor Beginn der Wiederherstellung bekannt sein. 
---
= ONTAP Rücksetzanforderungen für SnapMirror und SnapVault Beziehungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der  `system node revert-to` Befehl benachrichtigt Sie über alle SnapMirror und SnapVault Beziehungen, die für den Abschluss des Wiederherstellungsprozesses gelöscht oder neu konfiguriert werden müssen. Allerdings sollten diese Anforderungen vor Beginn der Wiederherstellung bekannt sein.

* Alle SnapVault- und Datenschutz-Spiegelbeziehungen müssen stillgelegt und anschließend getrennt werden.
+
Nach Abschluss der Rücksetzung können Sie diese Beziehungen erneut synchronisieren und fortsetzen, sofern ein gemeinsamer Snapshot vorhanden ist.

* SnapVault-Beziehungen dürfen die folgenden SnapMirror-Richtlinientypen nicht enthalten:
+
** async-mirror
+
Alle Beziehungen, die diesen Richtlinientyp verwenden, müssen gelöscht werden.

** MirrorAndVault
+
Falls eine dieser Beziehungen besteht, sollte die SnapMirror Richtlinie auf mirror-vault geändert werden.



* Alle Load Sharing Mirror-Beziehungen und Ziel-Volumes müssen gelöscht werden.
* SnapMirror-Beziehungen mit FlexClone-Zielvolumes müssen gelöscht werden.
* Die Netzwerkkomprimierung muss für jede SnapMirror Richtlinie deaktiviert werden.
* Die Regel all_source_snapshot muss aus allen async-mirror Typ SnapMirror Richtlinien entfernt werden.
+

NOTE: Die Einzeldatei SnapRestore (SFSR) und Partial File Snapshot Restore (PFSR) Operationen sind auf dem Root-Volume veraltet.

* Alle aktuell laufenden Wiederherstellungsvorgänge für einzelne Dateien und Snapshots müssen abgeschlossen sein, bevor die Rücksetzung fortgesetzt werden kann.
+
Sie können entweder warten, bis der Wiederherstellungsvorgang abgeschlossen ist, oder ihn abbrechen.

* Alle unvollständigen Wiederherstellungsvorgänge einzelner Dateien und Snapshots müssen mit dem  `snapmirror restore` Befehl entfernt werden.
+
Weitere Informationen zu  `snapmirror restore` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-restore.html["ONTAP-Befehlsreferenz"^].


