---
permalink: revert/concept_reversion_requirements_for_snapmirror_and_snapvault_relationships.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, requirements, snapmirror, snapvault, relationships 
summary: Der Befehl „System Node revert-to“ informiert Sie über alle SnapMirror und SnapVault Beziehungen, die gelöscht oder neu konfiguriert werden müssen, um den Neuversionsprozess abzuschließen. Diese Anforderungen sollten Sie jedoch kennen, bevor Sie mit der Umversion beginnen. 
---
= Reversionsanforderungen für SnapMirror und SnapVault Beziehungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Befehl „System Node revert-to“ informiert Sie über alle SnapMirror und SnapVault Beziehungen, die gelöscht oder neu konfiguriert werden müssen, um den Neuversionsprozess abzuschließen. Diese Anforderungen sollten Sie jedoch kennen, bevor Sie mit der Umversion beginnen.

* Alle Beziehungen zwischen SnapVault und Datenschutz-Spiegelung müssen stillgelegt und dann beschädigt werden.
+
Nach Abschluss der Reversion können Sie diese Beziehungen neu synchronisieren und wieder aufnehmen, wenn eine gemeinsame Snapshot Kopie vorhanden ist.

* SnapVault-Beziehungen dürfen die folgenden SnapMirror-Richtlinientypen nicht enthalten:
+
** Asynchrone Spiegelung
+
Sie müssen alle Beziehungen löschen, die diesen Richtlinientyp verwenden.

** MirrorAndVault
+
Wenn eine dieser Beziehungen besteht, sollten Sie die SnapMirror-Richtlinie in Mirror-Vault ändern.



* Alle Mirror-Beziehungen und Ziel-Volumes zur Lastverteilung müssen gelöscht werden.
* SnapMirror Beziehungen zu FlexClone Ziel-Volumes müssen gelöscht werden.
* Für jede SnapMirror-Richtlinie muss die Netzwerkkomprimierung deaktiviert werden.
* Die Regel „all_Source_Snapshot“ muss von allen SnapMirror Richtlinien vom Typ „Async-Mirror“ entfernt werden.
+

NOTE: Die Vorgänge Single File Snapshot Restore (SFSR) und PFSR (partial File Snapshot Restore) sind im Root-Volume veraltet.

* Alle derzeit ausgeführten Single-File- und Snapshot-Wiederherstellungen müssen abgeschlossen sein, bevor die Reversion fortgesetzt werden kann.
+
Sie können entweder warten, bis der Wiederherstellungsvorgang abgeschlossen ist, oder Sie können ihn abbrechen.

* Alle unvollständigen Restore-Vorgänge für einzelne Dateien und Snapshots müssen über den snapmirror Restore-Befehl entfernt werden.

