---
permalink: revert/concept_when_to_call_technical_support.html 
sidebar: sidebar 
keywords: ontap, downgrade, revert, paths 
summary: Sie können die Daten ohne Hilfe für neue oder Test-Cluster zurücksetzen. Um die Produktionscluster zurückzusetzen, sollten Sie den technischen Support anrufen. 
---
= Benötige ich technische Unterstützung, um sie rückgängig zu machen?
:allow-uri-read: 


[role="lead"]
Sie können die Daten ohne Hilfe für neue oder Test-Cluster zurücksetzen. Um die Produktionscluster zurückzusetzen, sollten Sie den technischen Support anrufen. Sollten Sie einen der folgenden Ansprechpartner haben, sollten Sie sich auch an den technischen Support wenden:

* Sie befinden sich in einer Produktionsumgebung und revert schlägt fehl oder Sie treten auf Probleme vor oder nach der Revert, z. B.:
+
** Die Wiederherstellung schlägt fehl und kann nicht abgeschlossen werden.
** Die Umrüstung ist beendet, aber in einer Produktionsumgebung kann das Cluster nicht verwendet werden.
** Der Umrüstung ist abgeschlossen und das Cluster geht in die Produktion, aber Sie sind nicht zufrieden mit seinem Verhalten.


* Sie haben Volumes in ONTAP 9.5 oder höher erstellt und müssen auf eine frühere Version zurückgesetzt werden. Volumes mit anpassungsfähiger Komprimierung müssen vor dem Zurücksetzen dekomprimiert werden.

