---
permalink: revert/delete-active-active-svms.html 
sidebar: sidebar 
keywords: delete, active-active, SVMs, storage virtual machines, revert 
summary: Wenn Sie Trunking für Clientverbindungen aktiviert haben und auf eine frühere Version als ONTAP 9.12.1 zurückkehren, muss Trunking auf allen NFSv4.1-Servern deaktiviert werden, bevor die Rückkehr erfolgt. 
---
= Aktiv/Aktiv SVMs müssen gelöscht werden, bevor von ONTAP 9.19.1 zurückgekehrt wird.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SAN Aktiv/Aktiv Multipathing wird in ONTAP 9.18.1 und früher nicht unterstützt. Vor dem Zurücksetzen von ONTAP 9.19.1 müssen alle Storage Virtual Machines (SVMs) mit Aktiv/Aktiv Konfigurationen gelöscht werden.

.Schritte
. Alle SVMs identifizieren, bei denen die Option san-multipathing für Aktiv/Aktiv oder Aktiv/Aktiv-nur-SCSI konfiguriert ist:
+
[source, cli]
----
vserver show
----
. Alle SVMs, die für Aktiv/Aktiv oder Aktiv/Aktiv-SCSI-Only-Multipathing konfiguriert sind, löschen:
+
[source, cli]
----
vserver delete -vserver <SVM>
----
. Es wird überprüft, ob die SVMs gelöscht wurden:
+
[source, cli]
----
vserver show
----


.Verwandte Informationen
Weitere Informationen zu link:../san-admin/multipath-automatic-lif-failover-support.html["SAN Aktiv/Aktiv Multipathing-Unterstützung"] in ONTAP 9.19.1 und späteren Versionen.
