---
permalink: revert/identify-user-sha2-hash-user-accounts.html 
sidebar: sidebar 
keywords: revert, reverting, reversion, password, hash, function, supported, encryption, type 
summary: Wenn Sie zu einer Freigabe vor einer beliebigen Version von ONTAP 9 zurückkehren, können SHA-2-Kontobenutzer nicht mehr mit ihren Passwörtern authentifiziert werden. 
---
= Identifizieren Sie die Benutzerkonten, die die SHA-2-Hash-Funktion nutzen
:allow-uri-read: 


[role="lead"]
Wenn Sie von ONTAP 9.1 oder ONTAP 9.0 auf ONTAP 8.3.x zurücksetzen, können SHA-2-Kontobenutzer nicht mehr mit ihren Passwörtern authentifiziert werden. Bevor Sie das System zurücksetzen, sollten Sie die Benutzerkonten identifizieren, die die SHA-2-Hash-Funktion verwenden, damit Sie nach dem Zurücksetzen die Passwörter zurücksetzen lassen können, um den Verschlüsselungstyp (MD5) zu verwenden, der von der Version unterstützt wird, auf die Sie zurückgesetzt haben.

. Ändern Sie die Berechtigungseinstellung in erweitert: `set -privilege advanced`
. Geben Sie die Benutzerkonten an, die die SHA-2 Funktion nutzen: `security login show -vserver * -username * -application * -authentication-method password -hash-function !md5`
. Behalten Sie die Befehlsausgabe für die Verwendung nach der Zurücksetzen.



NOTE: Während der Umrüstung werden Sie aufgefordert, den erweiterten Befehl auszuführen `security login password-prepare-to-downgrade` So setzen Sie Ihr eigenes Kennwort zurück, um die MD5-Hash-Funktion zu verwenden. Wenn Ihr Kennwort nicht mit MD5 verschlüsselt ist, werden Sie durch den Befehl aufgefordert, ein neues Kennwort einzugeben und mit MD5 zu verschlüsseln. Dadurch wird die Authentifizierung Ihrer Anmeldedaten nach der Zurücksetzen ermöglicht.
