---
permalink: revert/remove-nas-bucket-task.html 
sidebar: sidebar 
keywords: s3, svm, bucket, object, server, filesystems, nas, directories, revert 
summary: Wenn Sie den S3-Clientzugriff für NAS-Daten konfiguriert haben und von ONTAP 9.12.1 oder höher auf ONTAP 9.11.1 oder früher zurückkehren, müssen Sie die NAS-Bucket-Konfiguration entfernen und alle Zuordnungen von S3-Benutzern zu Windows/Unix-Benutzernamen vor dem Zurückkehren entfernen. 
---
= Die S3 NAS-Bucket-Konfiguration sollte entfernt werden, bevor von ONTAP 9.12.1 zurückgekehrt wird.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn der S3-Clientzugriff für NAS-Daten konfiguriert wurde, empfiehlt sich die Verwendung der ONTAP Befehlszeilenschnittstelle (CLI), um die NAS-Bucket-Konfiguration sowie alle Namenszuordnungen (S3-Benutzer zu Windows- oder Unix-Benutzern) zu entfernen, bevor von ONTAP 9.12.1 zurückgekehrt wird.

.Über diese Aufgabe
Die folgenden Aufgaben werden während des Rücksetzungsprozesses im Hintergrund abgeschlossen.

* Alle unvollständig erstellten Singleton-Objekte (also alle Einträge in versteckten Verzeichnissen) entfernen.
* Alle versteckten Verzeichnisse entfernen; möglicherweise existiert für jedes Volume, das vom Stammverzeichnis des aus dem S3 NAS-Bucket gemappten Exports aus zugänglich ist, ein solches Verzeichnis.
* Die Upload-Tabelle wird entfernt.
* Alle default-unix-user- und default-windows-user-Werte für alle konfigurierten S3-Server löschen.


.Schritte
. S3 NAS-Bucket-Konfiguration entfernen:
+
[source, cli]
----
vserver object-store-server bucket delete -vserver <svm_name> -bucket <s3_nas_bucket_name>
----
+
Weitere Informationen zu  `vserver object-store-server bucket delete` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-object-store-server-bucket-delete.html["ONTAP-Befehlsreferenz"^].

. Namenszuordnungen für UNIX entfernen:
+
[source, cli]
----
vserver name-mapping delete -vserver <svm_name> -direction s3-unix
----
+
Weitere Informationen zu  `vserver name-mapping delete` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-name-mapping-delete.html["ONTAP-Befehlsreferenz"^].

. Namenszuordnungen für Windows entfernen:
+
[source, cli]
----
vserver name-mapping delete -vserver <svm_name> -direction s3-win
----
. Die S3-Protokolle aus der SVM entfernen:
+
[source, cli]
----
vserver remove-protocols -vserver <svm_name> -protocols s3
----
+
Weitere Informationen zu  `vserver remove-protocols` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-remove-protocols.html["ONTAP-Befehlsreferenz"^].


