---
permalink: revert/task_identifying_current_cluster_activity.html 
sidebar: sidebar 
keywords: ontap, downgrade, dowgrading, cluster, activity, running, jobs, stop, shutdown, active, SMB, sessions 
summary: Vor Durchführung einer unterbrechungsfreien Downgrade sollten CIFS-Sitzungen identifiziert und ordnungsgemäß beendet werden, die nicht kontinuierlich verfügbar sind. 
---
= Überprüfen Sie die aktuelle Cluster-Aktivität vor dem Downgrade
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor dem Downgrade sollten keine Jobs ausgeführt werden und alle nicht kontinuierlich verfügbaren SMB-Sessions beendet werden.



== Vergewissern Sie sich, dass keine Jobs ausgeführt werden

Vor dem Downgrade der ONTAP-Software müssen Sie den Status von Cluster-Jobs überprüfen. Bei beliebigen Aggregaten, Volumes, NDMP (Dump oder Restore) oder Snapshot Jobs (z. B. Erstellen, Löschen, Verschieben, Ändern, Replizieren, Und Mount-Jobs) werden ausgeführt oder in die Warteschlange gestellt. Sie müssen zulassen, dass die Jobs erfolgreich abgeschlossen werden, oder dass die in der Warteschlange befindlichen Einträge angehalten werden.

. Prüfen Sie die Liste aller laufenden oder wartenden Aggregat-, Volume- oder Snapshot-Jobs in der Warteschlange: `job show`
+
[listing]
----
cluster1::> job show
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
8629   Vol Reaper           cluster1   -              Queued
       Description: Vol Reaper Job
8630   Certificate Expiry Check
                            cluster1   -              Queued
       Description: Certificate Expiry Check
.
.
.
----
. Löschen aller laufenden oder in Warteschlange befindlichen Aggregat-, Volume- oder Snapshot-Kopie-Jobs: `job delete -id job_id`
+
[listing]
----
cluster1::> job delete -id 8629
----
. Vergewissern Sie sich, dass keine Aggregat-, Volume- oder Snapshot-Jobs ausgeführt oder in eine Warteschlange eingereiht werden: `job show`
+
In diesem Beispiel wurden alle laufenden und in der Warteschlange befindlichen Jobs gelöscht:

+
[listing]
----
cluster1::> job show
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
9944   SnapMirrorDaemon_7_2147484678
                            cluster1   node1          Dormant
       Description: Snapmirror Daemon for 7_2147484678
18377  SnapMirror Service Job
                            cluster1   node0          Dormant
       Description: SnapMirror Service Job
2 entries were displayed
----




== Identifizieren Sie aktive SMB-Sessions, die beendet werden sollen

Vor Durchführung einer unterbrechungsfreien Downgrade sollten SMB-Sitzungen, die nicht kontinuierlich verfügbar sind, identifiziert und ordnungsgemäß beendet werden.

Kontinuierlich verfügbare SMB-Freigaben, auf die von Hyper-V oder Microsoft SQL Server Clients mit dem SMB 3.0 Protokoll zugegriffen wird, müssen vor einem Upgrade oder Downgrade nicht beendet werden.

. Ermitteln Sie alle etablierten SMB-Sitzungen, die nicht ständig verfügbar sind: `vserver cifs session show -continuously-available Yes -instance`
+
Dieser Befehl zeigt detaillierte Informationen zu SMB-Sessions an, bei denen keine kontinuierliche Verfügbarkeit vorhanden ist. Sie sollten sie beenden, bevor Sie mit der ONTAP-Herabstufung fortfahren.

+
[listing]
----
cluster1::> vserver cifs session show -continuously-available Yes -instance

                        Node: node1
                     Vserver: vs1
                  Session ID: 1
               Connection ID: 4160072788
Incoming Data LIF IP Address: 198.51.100.5
      Workstation IP address: 203.0.113.20
    Authentication Mechanism: NTLMv2
                Windows User: CIFSLAB\user1
                   UNIX User: nobody
                 Open Shares: 1
                  Open Files: 2
                  Open Other: 0
              Connected Time: 8m 39s
                   Idle Time: 7m 45s
            Protocol Version: SMB2_1
      Continuously Available: No
1 entry was displayed.
----
. Identifizieren Sie bei Bedarf die Dateien, die für jede identifizierte SMB-Sitzung geöffnet sind: `vserver cifs session file show -session-id _session_ID_`
+
[listing]
----
cluster1::> vserver cifs session file show -session-id 1

Node:       node1
Vserver:    vs1
Connection: 4160072788
Session:    1
File    File      Open Hosting                               Continuously
ID      Type      Mode Volume          Share                 Available
------- --------- ---- --------------- --------------------- ------------
1       Regular   rw   vol10           homedirshare          No
Path: \TestDocument.docx
2       Regular   rw   vol10           homedirshare          No
Path: \file1.txt
2 entries were displayed.
----

