---
permalink: revert/task_disabling_qtrees_in_flexgroup_volumes_before_reverting.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, disable, disabling, qtree, functionality, function, flexgroup, volumes 
summary: Qtrees für FlexGroup Volumes werden vor ONTAP 9.3 nicht unterstützt. Sie müssen die qtree-Funktion auf FlexGroup Volumes deaktivieren, bevor Sie ONTAP 9.3 auf eine frühere Version von ONTAP zurücksetzen. 
---
= Deaktivieren Sie vor dem Zurücksetzen die qtree-Funktion in FlexGroup Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Qtrees für FlexGroup Volumes werden vor ONTAP 9.3 nicht unterstützt. Sie müssen die qtree-Funktion auf FlexGroup Volumes deaktivieren, bevor Sie ONTAP 9.3 auf eine frühere Version von ONTAP zurücksetzen.

Die qtree-Funktion wird entweder aktiviert, wenn Sie einen qtree erstellen oder wenn Sie die Attribute des Sicherheitsstils und des Oplock-Modus des Standard-qtree ändern.

. Identifizierung und Löschen aller nicht standardmäßigen qtrees in jedem FlexGroup Volume, die über die qtree-Funktion aktiviert sind:
+
.. Melden Sie sich bei der erweiterten Berechtigungsebene an: `set -privilege advanced`
.. Überprüfung, ob ein FlexGroup Volume durch die qtree-Funktion aktiviert ist
+
Verwenden Sie für ONTAP 9.6 oder höher: `volume show -is-qtree-caching-enabled true`

+
Für ONTAP 9.5 oder eine frühere Version: `volume show -is-flexgroup-qtree-enabled true`

+
[listing]
----
cluster1::*> volume show -is-flexgroup-qtree-enabled true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vs0       fg           -            online     RW        320MB    220.4MB   31%
----
.. Löschen Sie alle nicht standardmäßigen qtrees in jedem FlexGroup Volume, die durch die qtree-Funktion aktiviert sind: `volume qtree delete -vserver svm_name -volume volume_name -qtree qtree_name`
+
Wenn die qtree-Funktion aktiviert ist, da Sie die Attribute des Standard-qtree geändert haben und wenn keine qtrees vorhanden sind, können Sie diesen Schritt überspringen.

+
[listing]
----
cluster1::*> volume qtree delete -vserver vs0 -volume fg -qtree qtree4
WARNING: Are you sure you want to delete qtree qtree4 in volume fg vserver vs0?  {y|n}: y
[Job 38] Job is queued: Delete qtree qtree4 in volume fg vserver vs0.
----


. Deaktivieren Sie die qtree-Funktion auf jedem FlexGroup Volume: `volume flexgroup qtree-disable -vserver svm_name -volume volume_name`
+
[listing]
----
cluster1::*> volume flexgroup qtree-disable -vserver vs0 -volume fg
----
. Identifizieren und löschen Sie alle Snapshot Kopien, die mit der qtree Funktion aktiviert sind.
+
.. Überprüfen Sie, ob die qtree Funktion Snapshot Kopien aktiviert ist: `volume snapshot show -vserver vserver_name -volume volume_name -fields is-flexgroup-qtree-enabled`
+
[listing]
----
cluster1::*> volume snapshot show -vserver vs0 -volume fg -fields is-flexgroup-qtree-enabled
vserver volume snapshot is-flexgroup-qtree-enabled
------- ------ -------- --------------------------
vs0     fg     fg_snap1 true
vs0     fg     daily.2017-09-27_0010 true
vs0     fg     daily.2017-09-28_0010 true
vs0     fg     snapmirror.0241f354-a865-11e7-a1c0-00a098a71764_2147867740.2017-10-04_124524 true
----
.. Löschen Sie alle Snapshot Kopien, die mit der qtree-Funktion aktiviert sind: `volume snapshot delete -vserver svm_name -volume volume_name -snapshot snapshot_name -force true -ignore-owners true`
+
Die zu löschenden Snapshot Kopien umfassen regelmäßige Snapshot Kopien und die für SnapMirror Beziehungen erstellten Snapshot Kopien. Falls Sie eine beliebige SnapMirror Beziehung für die FlexGroup Volumes mit einem Ziel-Cluster erstellt haben, auf dem ONTAP 9.2 oder eine andere Version ausgeführt wird, müssen Sie alle Snapshot-Kopien löschen, die erstellt wurden, als das FlexGroup Quell-Volume für die qtree Funktion aktiviert wurde.

+
[listing]
----
cluster1::> volume snapshot delete -vserver vs0 -volume fg -snapshot daily.2017-09-27_0010 -force true -ignore-owners true
----




.Verwandte Informationen
link:../flexgroup/index.html["Management von FlexGroup Volumes"]
