---
permalink: revert/task_download_and_install_ontap_software_image.html 
sidebar: sidebar 
keywords: ontap, software, image, download, downloading, install, installing 
summary: Sie müssen zuerst die ONTAP-Software herunterladen, dann können Sie sie installieren. 
---
= Laden Sie das ONTAP Software-Image herunter und installieren Sie es
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie die aktuelle ONTAP Software zurücksetzen, müssen Sie die Zielsoftwareversion von der NetApp Support-Website herunterladen und dann installieren.



== Laden Sie das ONTAP Software Image herunter

Software-Images sind für Plattformmodelle spezifisch. Sie müssen das richtige Image für Ihr Cluster erhalten. Software-Images, Informationen zu Firmware-Versionen und die neueste Firmware für Ihr Plattformmodell finden Sie auf der NetApp Support Site. Software-Images enthalten die neueste Version der System-Firmware, die verfügbar war, wenn eine bestimmte Version von ONTAP veröffentlicht wurde.


NOTE: Wenn Sie ein System mit NetApp-Volume-Verschlüsselung von ONTAP 9.5 oder höher zurücksetzen, müssen Sie das ONTAP-Software-Image für Länder ohne Einschränkungen herunterladen, einschließlich NetApp-Volume-Verschlüsselung. Wenn Sie das ONTAP Software-Image für eingeschränkte Länder zum Zurücksetzen eines Systems mit NetApp-Datenträgerverschlüsselung verwenden, Panik des Systems ein und Sie verlieren den Zugriff auf Ihre Volumes.

.Schritte
. Suchen Sie auf link:http://mysupport.netapp.com/NOW/cgi-bin/software["Software-Downloads"^]der NetApp Support-Website nach der Ziel-ONTAP-Software.
. Kopieren Sie das Software-Image (z. B. 97_q_image.tgz) von der NetApp-Support-Website
+
Sie können das Image in das Verzeichnis auf dem HTTP-Server oder FTP-Server kopieren, von dem das Image bereitgestellt wird, oder in einen lokalen Ordner.





== Installieren Sie das ONTAP-Software-Image

Nachdem Sie das Ziel-ONTAP-Software-Image von der NetApp Support-Website heruntergeladen haben, installieren Sie es auf den Cluster-Nodes.

.Schritte
. Legen Sie die Berechtigungsebene auf erweitert fest:
+
[source, cli]
----
set -privilege advanced
----
+
Die erweiterte Eingabeaufforderung (`*>`) wird angezeigt.

. Geben Sie ein `y`, um fortzufahren, wenn Sie dazu aufgefordert werden.
. Installieren Sie das Software-Image:
+
** Geben Sie für Standardkonfigurationen oder eine MetroCluster Konfiguration mit zwei Nodes den folgenden Befehl ein:
+
[source, cli]
----
system node image update -node * -package location -replace-package true -setdefault true -background true
----
+
Mit diesem Befehl wird das Software-Image gleichzeitig auf allen Nodes heruntergeladen und installiert. Geben Sie den Parameter nicht an, um das Image einzeln herunterzuladen und auf jedem Node zu installieren `-background`. Dieser Befehl verwendet auch eine erweiterte Abfrage, um das Ziel-Software-Image, das als alternatives Image installiert wird, als Standard-Image für den Node zu ändern.

** Geben Sie für eine MetroCluster Konfiguration mit vier oder acht Nodes den folgenden Befehl für beide Cluster ein:
+
[source, cli]
----
system node image update -node * -package location -replace-package true true -background true -setdefault false
----
+
Mit diesem Befehl wird das Software-Image gleichzeitig auf allen Nodes heruntergeladen und installiert. Geben Sie den Parameter nicht an, um das Image einzeln herunterzuladen und auf jedem Node zu installieren `-background`. Dieser Befehl verwendet außerdem eine erweiterte Abfrage, um das Ziel-Software-Image zu ändern, das als alternatives Image auf jedem Node installiert wird.



. Geben Sie ein `y`, um fortzufahren, wenn Sie dazu aufgefordert werden.
. Vergewissern Sie sich, dass das Software-Image auf jedem Node heruntergeladen und installiert ist:
+
[source, cli]
----
system node image show-update-progress -node *
----
+
Mit diesem Befehl wird der aktuelle Status des Downloads und der Installation des Software-Images angezeigt. Sie sollten diesen Befehl so lange fortsetzen, bis alle Knoten einen *Run Status* von „beendet“ und einen *Exit Status* von „Erfolg“ melden.

+
Der Befehl zum Aktualisieren des System-Node-Images kann fehlschlagen und zeigt Fehler- oder Warnmeldungen an. Nach Beheben von Fehlern oder Warnungen können Sie den Befehl erneut ausführen.

+
In diesem Beispiel wird ein Cluster mit zwei Nodes angezeigt, in dem das Software-Image auf beiden Nodes heruntergeladen und erfolgreich installiert wird:

+
[listing]
----
cluster1::*> system node image show-update-progress -node *
There is no update/install in progress
Status of most recent operation:
        Run Status:     Exited
        Exit Status:    Success
        Phase:          Run Script
        Exit Message:   After a clean shutdown, image2 will be set as the default boot image on node0.
There is no update/install in progress
Status of most recent operation:
        Run Status:     Exited
        Exit Status:    Success
        Phase:          Run Script
        Exit Message:   After a clean shutdown, image2 will be set as the default boot image on node1.
2 entries were acted on.
----

