---
permalink: revert/task-disable-tls-nvme-host.html 
sidebar: sidebar 
keywords: ontap, revert, reversion, reverting, tls, nvme, host, controller, subsystem, tls secure channel 
summary: Bevor Sie zu einer älteren Version von ONTAP zurückkehren, die TLS für NVMe-Hosts nicht unterstützt, müssen Sie TLS auf den NVMe-Hosts deaktivieren. 
---
= Deaktivieren Sie TLS Secure Channel auf einem NVMe-Host vor dem Zurücksetzen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.16.1 können Sie TLS Secure Channel für NVMe/TCP-Verbindungen konfigurieren. Wenn Sie TLS Secure Channel für NVMe/TCP-Verbindungen in ONTAP 9.16.1 oder höheren Versionen konfiguriert haben, müssen Sie die TLS-Konfiguration auf den NVMe-Hosts deaktivieren, bevor Sie ONTAP auf eine Version zurücksetzen, die TLS Secure Channel für NVMe/TCP nicht unterstützt.

.Schritte
. Entfernen Sie die TLS Secure Channel-Konfiguration vom Host:
+
[source, cli]
----
vserver nvme subsystem host unconfigure-tls-for-revert -vserver <svm_name> -subsystem <subsystem> -host-nqn <host_nqn>
----
+
Mit diesem Befehl wird der Host aus dem Subsystem entfernt und der Host wird dann ohne TLS-Konfiguration im Subsystem neu erstellt.

. Vergewissern Sie sich, dass der TLS-sichere Kanal vom Host entfernt wird:
+
[source, cli]
----
vserver nvme subsystem host show
----


.Weitere Informationen .
Im ONTAP-Handbuch finden Sie die folgenden Befehle:

* https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-subsystem-host-unconfigure-tls-for-revert.html["Konfiguration des nvme-Subsystems von vserver – tls-for-revert"^]
* https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-subsystem-host-show.html["Host des vserver nvme-Subsystems zeigen"^]

