---
permalink: revert/task_reverting_an_ontap_cluster.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, cluster 
summary: Um den Cluster offline zu nehmen, um auf eine frühere ONTAP Version zurückzukehren, müssen das Storage-Failover und die Daten-LIFs deaktiviert, die Voraussetzungen für die Rückkehr erfüllt, die Cluster- und Dateisystemkonfigurationen auf einem Knoten zurückgesetzt und dieser Vorgang dann für jeden weiteren Knoten im Cluster wiederholt werden. 
---
= Ein ONTAP Cluster zurücksetzen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Zurücksetzen eines ONTAP Clusters ist mit Unterbrechungen verbunden. Der Cluster muss für die Dauer des Zurücksetzens offline genommen werden. Ein produktiver Cluster sollte nicht ohne Unterstützung des technischen Supports zurückgesetzt werden.

Um einen neuen oder Test-Cluster zurückzusetzen, müssen Storage-Failover und Daten-LIFs deaktiviert und die Voraussetzungen für die Rücksetzung erfüllt werden; anschließend sind die Cluster- und Dateisystemkonfiguration auf jedem Node im Cluster zurückzusetzen.

.Bevor Sie beginnen.
* Sie sollten die link:task_things_to_verify_before_revert.html["Vorabüberprüfungen vor dem Zurücksetzen"] abgeschlossen haben.
* Sie sollten die erforderlichen link:concept_pre_revert_checks.html["Vorabprüfungen für Ihre spezifische ONTAP Version"] abgeschlossen haben.
* Sie sollten link:task_download_and_install_ontap_software_image.html["das Ziel-ONTAP Software-Image heruntergeladen und installiert"] haben.




[[step-1-prepare-the-cluster-for-reversion]]
== Schritt 1: Cluster für die Rücksetzung vorbereiten

Bevor Sie einen Ihrer Clusterknoten zurücksetzen, sollte überprüft werden, ob Ihr Ziel-ONTAP-Image installiert ist, und alle Daten-LIFs im Cluster sollten deaktiviert werden.

.Schritte
. Stellen Sie die Berechtigungsstufe auf „Erweitert“ ein:
+
[source, cli]
----
set -privilege advanced
----
+
*y* eingeben, wenn zur Fortsetzung aufgefordert wird.

. Es sollte überprüft werden, ob die Ziel ONTAP Software installiert ist:
+
[source, cli]
----
system image show
----
+
Das folgende Beispiel zeigt, dass Version 9.13.1 als alternatives Image auf beiden Knoten installiert ist:

+
[listing]
----
cluster1::*> system image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    9.14.1      MM/DD/YYYY TIME
         image2  false   false   9.13.1      MM/DD/YYYY TIME
node1
         image1  true    true    9.14.1      MM/DD/YYYY TIME
         image2  false   false   9.13.1      MM/DD/YYYY TIME
4 entries were displayed.
----
. Alle Daten-LIFs im Cluster deaktivieren:
+
[source, cli]
----
network interface modify {-role data} -status-admin down
----
. Feststellen, ob zwischen Clustern FlexCache Beziehungen bestehen:
+
[source, cli]
----
flexcache origin show-caches -relationship-type inter-cluster
----
. Falls Intercluster-Flexcaches vorhanden sind, werden die Data-LIFs auf dem Cache-Cluster deaktiviert:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -status-admin down
----




[[step-2-revert-cluster-nodes]]
== Schritt 2: Cluster-Nodes zurücksetzen

Um Ihren Cluster zurückzusetzen, muss zuerst der erste Node eines HA-Paares und anschließend der Partner-Node zurückgesetzt werden. Dieser Vorgang wird für jedes HA-Paar im Cluster wiederholt, bis alle Nodes zurückgesetzt sind. Wenn eine MetroCluster Konfiguration vorliegt, sind diese Schritte für beide Cluster in der Konfiguration zu wiederholen.

[role="tabbed-block"]
====
.4 oder mehr Knoten
--
.Schritte
. Melden Sie sich bei dem Node an, den Sie zurücksetzen möchten.
+
Um einen Node zurückzusetzen, muss eine Anmeldung am Cluster über die Node-Management-LIF des Nodes erfolgen.

. Speicherausfallsicherung für die Knoten im HA-Paar deaktivieren:
+
[source, cli]
----
storage failover modify -node <nodename> -enabled false
----
+
Sie müssen das Speicher-Failover nur einmal für das HA-Paar deaktivieren. Wenn das Speicher-Failover für einen Knoten deaktiviert wird, ist es auch auf dem Partnerknoten deaktiviert.

. Das Ziel-ONTAP-Software-Image des Knotens wird als Standard-Image festgelegt:
+
[source, cli]
----
system image modify -node <nodename> -image <target_image> -isdefault true
----
. Es sollte überprüft werden, dass das Ziel ONTAP Software Image als Standard-Image für den Knoten festgelegt ist, der zurückgesetzt wird:
+
[source, cli]
----
system image show
----
+
Das folgende Beispiel zeigt, dass Version 9.13.1 als Standardimage auf node0 festgelegt ist:

+
[listing]
----
cluster1::*> system image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  false   true    9.14.1      MM/DD/YYYY TIME
         image2  true    false   9.13.1      MM/DD/YYYY TIME
node1
         image1  true    true    9.14.1      MM/DD/YYYY TIME
         image2  false   false   9.13.1      MM/DD/YYYY TIME
4 entries were displayed.
----
. Es sollte überprüft werden, ob der Knoten für die Rücksetzung bereit ist:
+
[source, cli]
----
system node revert-to -node <nodename> -check-only true -version 9.x
----
+
Der  `check-only`Parameter kennzeichnet alle Vorbedingungen, die vor dem Zurücksetzen erfüllt sein müssen, wie das Deaktivieren der Snapshot-Richtlinie oder das Löschen von Snapshots, die nach dem Upgrade auf die neuere Version von ONTAP erstellt wurden.

+
Die  `-version` Option bezieht sich auf die ONTAP Version, auf die Sie zurücksetzen. Wenn Sie beispielsweise von 9.14.1 auf 9.13.1 zurücksetzen, ist der korrekte Wert der `-version` Option 9.13.1.

. Die Clusterkonfiguration des Knotens zurücksetzen:
+
[source, cli]
----
system node revert-to -node <nodename> -version 9.x
----
+
Die Clusterkonfiguration wird zurückgesetzt, und anschließend erfolgt die Abmeldung aus der Clustershell.

. Warten Sie auf die Anmeldeaufforderung; dann *Nein* eingeben, wenn gefragt wird, ob eine Anmeldung an der Systemshell erfolgen soll.
+
Es kann bis zu 30 Minuten oder länger dauern, bis die Anmeldeaufforderung erscheint.

. Anmeldung an der Clustershell mit admin.
. Zum Nodeshell wechseln:
+
[source, cli]
----
run -node <nodename>
----
+
Nach erneuter Anmeldung an der Clustershell kann es einige Minuten dauern, bis der nodeshell-Befehl akzeptiert wird. Falls der Befehl fehlschlägt, empfiehlt es sich, einige Minuten zu warten und es dann erneut zu versuchen.

. Die Dateisystemkonfiguration des Knotens wird zurückgesetzt:
+
[source, cli]
----
revert_to 9.x
----
+
Dieser Befehl prüft, ob die Dateisystemkonfiguration des Knotens zur Wiederherstellung bereit ist, und stellt sie anschließend wieder her. Wenn Vorbedingungen festgestellt werden, müssen diese behoben werden und anschließend der  `revert_to` Befehl erneut ausgeführt werden.

+

NOTE: Die Überwachung des Revert-Prozesses über eine Systemkonsole liefert detailliertere Informationen als in NodeShell.

+
Wenn AUTOBOOT auf „true“ gesetzt ist, startet der Knoten nach Abschluss des Befehls in ONTAP neu.

+
Wenn AUTOBOOT auf „false“ gesetzt ist, wird nach Abschluss des Befehls die LOADER-Eingabeaufforderung angezeigt.  `yes` eingeben, um die Änderung rückgängig zu machen; anschließend  `boot_ontap` verwenden, um den Knoten manuell neu zu starten.

. Nachdem der Knoten neu gestartet wurde, ist zu bestätigen, dass die neue Software ausgeführt wird:
+
[source, cli]
----
system node image show
----
+
Im folgenden Beispiel ist image1 die neue ONTAP Version und als aktuelle Version auf node0 festgelegt:

+
[listing]
----
cluster1::*> system node image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    X.X.X       MM/DD/YYYY TIME
         image2  false   false   Y.Y.Y      MM/DD/YYYY TIME
node1
         image1  true    false   X.X.X      MM/DD/YYYY TIME
         image2  false   true    Y.Y.Y      MM/DD/YYYY TIME
4 entries were displayed.
----
. Es sollte überprüft werden, ob der Wiederherstellungsstatus für den Knoten abgeschlossen ist:
+
[source, cli]
----
system node upgrade-revert show -node <nodename>
----
+
Der Status sollte als „abgeschlossen“, „nicht erforderlich“ oder „es wurden keine Tabelleneinträge zurückgegeben“ aufgeführt sein.

. Diese Schritte sind am anderen Knoten des HA-Paares zu wiederholen, anschließend für jedes weitere HA-Paar.
+
Wenn Sie eine MetroCluster Konfiguration haben, müssen diese Schritte auf beiden Clustern in der Konfiguration wiederholt werden.

. Nachdem alle Knoten zurückgesetzt wurden, wird die Hochverfügbarkeit für den Cluster wieder aktiviert:
+
[source, cli]
----
storage failover modify -node* -enabled true
----


--
.2-Node Cluster
--
. Melden Sie sich bei dem Node an, den Sie zurücksetzen möchten.
+
Um einen Node zurückzusetzen, muss eine Anmeldung am Cluster über die Node-Management-LIF des Nodes erfolgen.

. Cluster-High Availability (HA) deaktivieren:
+
[source, cli]
----
cluster ha modify -configured false
----
. Storage-Failover deaktivieren:
+
[source, cli]
----
storage failover modify -node <nodename> -enabled false
----
+
Sie müssen das Speicher-Failover nur einmal für das HA-Paar deaktivieren. Wenn das Speicher-Failover für einen Knoten deaktiviert wird, ist es auch auf dem Partnerknoten deaktiviert.

. Das Ziel-ONTAP-Software-Image des Knotens wird als Standard-Image festgelegt:
+
[source, cli]
----
system image modify -node <nodename> -image <target_image> -isdefault true
----
. Es sollte überprüft werden, dass das Ziel ONTAP Software Image als Standard-Image für den Knoten festgelegt ist, der zurückgesetzt wird:
+
[source, cli]
----
system image show
----
+
Das folgende Beispiel zeigt, dass Version 9.13.1 als Standardimage auf node0 festgelegt ist:

+
[listing]
----
cluster1::*> system image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  false   true    9.14.1      MM/DD/YYYY TIME
         image2  true    false   9.13.1      MM/DD/YYYY TIME
node1
         image1  true    true    9.14.1      MM/DD/YYYY TIME
         image2  false   false   9.13.1      MM/DD/YYYY TIME
4 entries were displayed.
----
. Es wird geprüft, ob der Knoten aktuell Epsilon enthält:
+
[source, cli]
----
cluster show -node <nodename>
----
+
Das folgende Beispiel zeigt, dass der Knoten Epsilon enthält:

+
[listing]
----
cluster1::*> cluster show -node node1

          Node: node1
          UUID: 026efc12-ac1a-11e0-80ed-0f7eba8fc313
       Epsilon: true
   Eligibility: true
        Health: true
----
+
.. Wenn der Knoten Epsilon enthält, wird Epsilon auf dem Knoten als falsch markiert, sodass Epsilon an den Partnerknoten übertragen werden kann:
+
[source, cli]
----
cluster modify -node <nodename> -epsilon false
----
.. Epsilon wird auf den Partnerknoten übertragen, indem Epsilon auf dem Partnerknoten als „true“ markiert wird:
+
[source, cli]
----
cluster modify -node <node_partner_name> -epsilon true
----


. Es sollte überprüft werden, ob der Knoten für die Rücksetzung bereit ist:
+
[source, cli]
----
system node revert-to -node <nodename> -check-only true -version 9.x
----
+
Der  `check-only`Parameter kennzeichnet alle Bedingungen, die vor dem Zurücksetzen erfüllt sein müssen, wie das Deaktivieren der Snapshot-Richtlinie oder das Löschen von Snapshots, die nach dem Upgrade auf die neuere Version von ONTAP erstellt wurden.

+
Die  `-version` Option bezieht sich auf die ONTAP Version, auf die Sie zurücksetzen. Nur die ersten beiden Werte der ONTAP Version sind erforderlich. Wenn Sie beispielsweise von 9.14.1 auf 9.13.1 zurücksetzen, ist der korrekte Wert der  `-version` Option 9.13.

+
Die Clusterkonfiguration wird zurückgesetzt, und anschließend erfolgt die Abmeldung aus der Clustershell.

. Die Clusterkonfiguration des Knotens zurücksetzen:
+
[source, cli]
----
system node revert-to -node <nodename> -version 9.x
----
. Warten Sie auf die Anmeldeaufforderung, dann  `No` eingeben, wenn Sie gefragt werden, ob Sie sich in der Systemshell anmelden möchten.
+
Es kann bis zu 30 Minuten oder länger dauern, bis die Anmeldeaufforderung erscheint.

. Anmeldung an der Clustershell mit admin.
. Zum Nodeshell wechseln:
+
[source, cli]
----
run -node <nodename>
----
+
Nach erneuter Anmeldung an der Clustershell kann es einige Minuten dauern, bis der nodeshell-Befehl akzeptiert wird. Falls der Befehl fehlschlägt, empfiehlt es sich, einige Minuten zu warten und es dann erneut zu versuchen.

. Die Dateisystemkonfiguration des Knotens wird zurückgesetzt:
+
[source, cli]
----
revert_to 9.x
----
+
Dieser Befehl prüft, ob die Dateisystemkonfiguration des Knotens zur Wiederherstellung bereit ist, und stellt sie anschließend wieder her. Wenn Vorbedingungen festgestellt werden, müssen diese behoben werden und anschließend der  `revert_to` Befehl erneut ausgeführt werden.

+

NOTE: Die Überwachung des Revert-Prozesses über eine Systemkonsole liefert detailliertere Informationen als in NodeShell.

+
Wenn AUTOBOOT auf „true“ gesetzt ist, startet der Knoten nach Abschluss des Befehls in ONTAP neu.

+
Wenn AUTOBOOT auf „false“ gesetzt ist, wird nach Abschluss des Befehls die LOADER-Eingabeaufforderung angezeigt.  `yes` eingeben, um die Änderung rückgängig zu machen; anschließend  `boot_ontap` verwenden, um den Knoten manuell neu zu starten.

. Nachdem der Knoten neu gestartet wurde, ist zu bestätigen, dass die neue Software ausgeführt wird:
+
[source, cli]
----
system node image show
----
+
Im folgenden Beispiel ist image1 die neue ONTAP Version und als aktuelle Version auf node0 festgelegt:

+
[listing]
----
cluster1::*> system node image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    X.X.X       MM/DD/YYYY TIME
         image2  false   false   Y.Y.Y      MM/DD/YYYY TIME
node1
         image1  true    false   X.X.X      MM/DD/YYYY TIME
         image2  false   true    Y.Y.Y      MM/DD/YYYY TIME
4 entries were displayed.
----
. Es wird geprüft, ob der Rücksetzungsstatus für den Knoten abgeschlossen ist:
+
[source, cli]
----
system node upgrade-revert show -node <nodename>
----
+
Der Status sollte als „abgeschlossen“, „nicht erforderlich“ oder „es wurden keine Tabelleneinträge zurückgegeben“ aufgeführt sein.

. Diese Schritte sind am anderen Knoten des HA-Paares ebenfalls auszuführen.
. Nachdem beide Knoten zurückgesetzt wurden, wird die Hochverfügbarkeit für den Cluster wieder aktiviert:
+
[source, cli]
----
cluster ha modify -configured true
----
. Speicherausfallsicherung auf beiden Knoten wieder aktivieren:
+
[source, cli]
----
storage failover modify -node <nodename> -enabled true
----


--
====
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/storage-failover-modify.html["storage failover modify"^]

