---
permalink: revert/task_enabling_and_reverting_lifs_to_home_ports_completing_post_reversion_tasks.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, downgrade, downgrading, enable, enabling, lifs, home, ports 
summary: Während eines Neustarts wurden möglicherweise einige LIFs auf ihre zugewiesenen Failover-Ports migriert. Nach dem Zurücksetzen eines Clusters müssen alle LIFs, die sich nicht auf ihren Home-Ports befinden, aktiviert und zurückgesetzt werden. 
---
= LIFs nach einer ONTAP Umstellung auf die Home-Ports aktivieren und zurücksetzen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Während eines Neustarts wurden möglicherweise einige LIFs auf ihre zugewiesenen Failover-Ports migriert. Nach dem Zurücksetzen eines ONTAP Clusters müssen alle LIFs, die sich nicht auf ihren Home-Ports befinden, aktiviert und zurückgesetzt werden.

Der Befehl `network interface revert` setzt eine LIF, die sich aktuell nicht an ihrem Home-Port befindet, wieder auf ihren Home-Port zurück, sofern dieser funktionsfähig ist. Der Home-Port einer LIF wird bei deren Erstellung festgelegt; der Home-Port einer LIF kann mit dem Befehl `network interface show` ermittelt werden.

.Schritte
. Status aller LIFs anzeigen:
+
[source, cli]
----
network interface show
----
+
Dieses Beispiel zeigt den Status aller LIFs für eine Storage Virtual Machine (SVM).

+
[listing]
----
cluster1::> network interface show -vserver vs0
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            data001    down/down  192.0.2.120/24     node0         e0e     true
            data002    down/down  192.0.2.121/24     node0         e0f     true
            data003    down/down  192.0.2.122/24     node0         e2a     true
            data004    down/down  192.0.2.123/24     node0         e2b     true
            data005    down/down  192.0.2.124/24     node0         e0e     false
            data006    down/down  192.0.2.125/24     node0         e0f     false
            data007    down/down  192.0.2.126/24     node0         e2a     false
            data008    down/down  192.0.2.127/24     node0         e2b     false
8 entries were displayed.
----
+
Wenn LIFs mit dem Status Admin „down“ oder mit dem Status „Is home“ „false“ angezeigt werden, erfolgt der nächste Schritt.

. Die Daten-LIFs aktivieren:
+
[source, cli]
----
network interface modify {-role data} -status-admin up
----
. LIFs auf ihre Home-Ports zurückführen:
+
[source, cli]
----
network interface revert *
----
. Es sollte sichergestellt werden, dass sich alle LIFs in ihren Home-Ports befinden:
+
[source, cli]
----
network interface show
----
+
Dieses Beispiel zeigt, dass sich alle LIFs für SVM vs0 auf ihren Home-Ports befinden.

+
[listing]
----
cluster1::> network interface show -vserver vs0
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            data001      up/up    192.0.2.120/24     node0         e0e     true
            data002      up/up    192.0.2.121/24     node0         e0f     true
            data003      up/up    192.0.2.122/24     node0         e2a     true
            data004      up/up    192.0.2.123/24     node0         e2b     true
            data005      up/up    192.0.2.124/24     node1         e0e     true
            data006      up/up    192.0.2.125/24     node1         e0f     true
            data007      up/up    192.0.2.126/24     node1         e2a     true
            data008      up/up    192.0.2.127/24     node1         e2b     true
8 entries were displayed.
----


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["Netzwerkschnittstelle"^]

