---
permalink: revert/task_reviewing_pre_reversion_resources.html 
sidebar: sidebar 
keywords: ontap, downgrade, downgrading, revert, reverting, reversion, resources, pre-reversion, pre-downgrading, before 
summary: Bevor Sie ONTAP zurücksetzen, sollte die Hardwareunterstützung bestätigt und Ressourcen überprüft werden, um potenzielle Probleme zu verstehen, die auftreten könnten oder gelöst werden müssen. 
---
= Ressourcen zur Überprüfung vor dem Zurücksetzen eines ONTAP Clusters
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie einen ONTAP Cluster zurücksetzen, sollte die Hardwareunterstützung bestätigt und die verfügbaren Ressourcen geprüft werden, um mögliche Probleme zu verstehen oder zu lösen.

. Prüfen Sie link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 Versionshinweise"^] für die Zielversion.
+
Im Abschnitt „Wichtige Hinweise“ werden mögliche Probleme beschrieben, derer Sie sich vor einem Downgrade oder einer Rückkehr zur vorherigen Version bewusst sein sollten.

. Bestätigen Sie, dass Ihre Hardwareplattform in der Zielversion unterstützt ist.
+
https://hwu.netapp.com["NetApp Hardware Universe"^]

. Es sollte bestätigt werden, dass Ihr Cluster und Ihre Management-Switches in der Zielversion unterstützt sind.
+
Es ist zu überprüfen, ob die Softwareversionen von NX-OS (Cluster-Netzwerk-Switches), IOS (Management-Netzwerk-Switches) und der Referenzkonfigurationsdatei (RCF) mit der Version von ONTAP, auf die zurückgesetzt wird, kompatibel sind.

+
https://mysupport.netapp.com/site/downloads["NetApp Downloads: Cisco Ethernet Switch"^]

. Wenn Ihr Cluster für SAN konfiguriert ist, sollte bestätigt werden, dass die SAN-Konfiguration vollständig unterstützt ist.
+
Alle SAN-Komponenten, einschließlich der Ziel-ONTAP Softwareversion, des Host-Betriebssystems und der Patches, der erforderlichen Host Utilities Software sowie der Adaptertreiber und Firmware, sollten unterstützt werden.

+
https://mysupport.netapp.com/matrix["NetApp Interoperabilitätsmatrix-Tool"^]


