---
permalink: smb-admin/access-snapshot-directories-clients-smb2-concept.html 
sidebar: sidebar 
keywords: method, access, snapshot, directory, windows, client, smb, data, store, copies, copy, how to access the snapshot directory from windows clients using smb 2.x 
summary: Die Methode, mit der Sie von Windows-Clients über SMB 2.x auf das Verzeichnis „~snapshot“ zugreifen, unterscheidet sich von der Methode für SMB 1.0. Es ist wichtig zu verstehen, wie bei der Verwendung von SMB 2.x-Verbindungen auf das Verzeichnis „~snapshot“ zugegriffen werden kann, um erfolgreich auf in Snapshots gespeicherte Daten zuzugreifen. 
---
= Informationen zum Zugriff auf das ONTAP ~snapshot-Verzeichnis von Windows-Clients mit SMB 2.x
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Methode, mit der Sie von Windows-Clients mithilfe von SMB 2.x auf das  `~snapshot` Verzeichnis zugreifen, unterscheidet sich von der Methode, die für SMB 1.0 verwendet wird. Es ist erforderlich zu verstehen, wie auf das  `~snapshot` Verzeichnis bei der Nutzung von SMB 2.x-Verbindungen zugegriffen werden kann, um erfolgreich auf in Snapshots gespeicherte Daten zuzugreifen.

Der SVM-Administrator steuert, ob Benutzer auf Windows-Clients das  `~snapshot` Verzeichnis auf einer Freigabe anzeigen und darauf zugreifen können, indem die  `showsnapshot` Freigabeeigenschaft mithilfe von Befehlen aus den vserver cifs share properties-Familien aktiviert oder deaktiviert wird.

Wenn die  `showsnapshot` Freigabeeigenschaft deaktiviert ist, kann ein Benutzer auf einem Windows-Client, der SMB 2.x verwendet, das  `~snapshot` Verzeichnis nicht anzeigen und nicht auf Snapshots innerhalb des  `~snapshot` Verzeichnisses zugreifen, selbst wenn der Pfad zum  `~snapshot` Verzeichnis oder zu bestimmten Snapshots innerhalb des Verzeichnisses manuell eingegeben wird.

Wenn die  `showsnapshot`Freigabeeigenschaft aktiviert ist, kann ein Benutzer auf einem Windows-Client, der SMB 2.x verwendet, das  `~snapshot`Verzeichnis weder im Stammverzeichnis der Freigabe noch in einer Verbindung oder einem Verzeichnis unterhalb des Stammverzeichnisses der Freigabe anzeigen. Nach dem Verbindungsaufbau zu einer Freigabe kann der Benutzer jedoch auf das versteckte  `~snapshot`Verzeichnis zugreifen, indem  `\~snapshot`manuell an das Ende des Freigabepfads angehängt wird. Das versteckte  `~snapshot`Verzeichnis ist über zwei Einstiegspunkte erreichbar:

* Im Stammverzeichnis der Freigabe
* An jedem Verbindungspunkt im Share Space


Das versteckte  `~snapshot`Verzeichnis ist von nicht-Verbindungs-Unterverzeichnissen innerhalb der Freigabe nicht zugänglich.

.Beispiel
Mit der im folgenden Beispiel gezeigten Konfiguration kann ein Benutzer auf einem Windows-Client mit einer SMB 2.x-Verbindung zur Freigabe „eng“ auf das  `~snapshot`Verzeichnis zugreifen, indem  `\~snapshot`zum Freigabepfad am Stamm der Freigabe und an jedem Verbindungspunkt im Pfad manuell hinzugefügt wird. Das versteckte  `~snapshot`Verzeichnis ist über die folgenden drei Pfade zugänglich:

* `\\vs1\eng\~snapshot`
* `\\vs1\eng\projects1\~snapshot`
* `\\vs1\eng\projects2\~snapshot`


[listing]
----
cluster1::> volume show -vserver vs1 -fields volume,junction-path
vserver volume       junction-path
------- ------------ ----------------------------------------
vs1     vs1_root      /
vs1     vs1_vol1      /eng
vs1     vs1_vol2      /eng/projects1
vs1     vs1_vol3      /eng/projects2

cluster1::> vserver cifs share show
Vserver  Share   Path     Properties    Comment  ACL
-------- ------  -------  ----------    -------- ----------
vs1      eng     /eng     oplocks       -        Everyone / Full Control
                          changenotify
                          browsable
                          showsnapshot
----