---
permalink: smb-admin/access-snapshot-directories-clients-smb2-concept.html 
sidebar: sidebar 
keywords: method, access, snapshot, directory, windows, client, smb, data, store, copies, copy, how to access the snapshot directory from windows clients using smb 2.x 
summary: Die Methode, mit der Sie auf das Verzeichnis ~Snapshot von Windows-Clients mit SMB 2.x zugreifen können, unterscheidet sich von der für SMB 1.0 verwendeten Methode. Sie müssen wissen, wie Sie auf das ~Snapshot-Verzeichnis zugreifen, wenn Sie SMB 2.x-Verbindungen verwenden, um erfolgreich auf in Snapshots gespeicherte Daten zuzugreifen. 
---
= Erfahren Sie mehr über den Zugriff auf das ONTAP ~snapshot-Verzeichnis von Windows-Clients mit SMB 2.x
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Methode, die Sie für den Zugriff auf das `~snapshot` Verzeichnis von Windows-Clients mit SMB 2.x verwenden, unterscheidet sich von der für SMB 1.0 verwendeten Methode. Sie müssen wissen, wie Sie auf das Verzeichnis zugreifen `~snapshot`, wenn Sie SMB 2.x-Verbindungen verwenden, um erfolgreich auf in Snapshots gespeicherte Daten zuzugreifen.

Der SVM-Administrator steuert, ob Benutzer auf Windows-Clients das `~snapshot` Verzeichnis einer Freigabe anzeigen und darauf zugreifen können `showsnapshot`, indem sie die Freigabeeigenschaft mithilfe von Befehlen aus den vserver-cifs-Freigabeeigenschaften-Familien aktivieren oder deaktivieren.

Wenn die `showsnapshot` Freigabeeigenschaft deaktiviert ist, kann ein Benutzer auf einem Windows-Client, der SMB 2.x verwendet, das Verzeichnis nicht anzeigen `~snapshot` und kann nicht auf Snapshots innerhalb des Verzeichnisses zugreifen `~snapshot`, selbst wenn er den Pfad zum Verzeichnis oder zu bestimmten Snapshots innerhalb des Verzeichnisses manuell eingibt `~snapshot`.

Wenn die `showsnapshot` Freigabeeigenschaft aktiviert ist, kann ein Benutzer auf einem Windows-Client, der SMB 2.x verwendet `~snapshot`, das Verzeichnis immer noch nicht entweder im Stammverzeichnis der Freigabe oder innerhalb einer Verbindung oder eines Verzeichnisses unter dem Stammverzeichnis der Freigabe anzeigen. Nach der Verbindung mit einer Freigabe kann der Benutzer jedoch auf das verborgene `~snapshot` Verzeichnis zugreifen, indem er `\~snapshot` es manuell an das Ende des Freigabepfads anfügt. Das versteckte `~snapshot` Verzeichnis ist von zwei Eintrittspunkten aus zugänglich:

* Im Stammverzeichnis des Shares
* An jedem Verbindungspunkt im gemeinsamen Raum


 `~snapshot`Auf das versteckte Verzeichnis kann nicht von Unterverzeichnissen ohne Verbindung innerhalb der Freigabe zugegriffen werden.

.Beispiel
Mit der im folgenden Beispiel gezeigten Konfiguration kann ein Benutzer auf einem Windows-Client mit einer SMB 2.x-Verbindung zur „`eng`“-Freigabe auf das `~snapshot` Verzeichnis zugreifen, indem er manuell an `\~snapshot` den Freigabepfad im Stammverzeichnis der Freigabe und an jedem Knotenpunkt im Pfad anfügt.  `~snapshot`Auf das versteckte Verzeichnis kann über die folgenden drei Pfade zugegriffen werden:

* `\\vs1\eng\~snapshot`
* `\\vs1\eng\projects1\~snapshot`
* `\\vs1\eng\projects2\~snapshot`


[listing]
----
cluster1::> volume show -vserver vs1 -fields volume,junction-path
vserver volume       junction-path
------- ------------ ----------------------------------------
vs1     vs1_root      /
vs1     vs1_vol1      /eng
vs1     vs1_vol2      /eng/projects1
vs1     vs1_vol3      /eng/projects2

cluster1::> vserver cifs share show
Vserver  Share   Path     Properties    Comment  ACL
-------- ------  -------  ----------    -------- ----------
vs1      eng     /eng     oplocks       -        Everyone / Full Control
                          changenotify
                          browsable
                          showsnapshot
----