---
permalink: smb-admin/add-ntfs-sacl-entries-security-descriptor-task.html 
sidebar: sidebar 
keywords: add, sacl, system, access, control, list, entires, aces, ntfs, audit, policies, policy, file, folder, svm, add ntfs sacl access control entries to the ntfs security descriptor 
summary: 'Das Hinzufügen von SACL (System Access Control List) Access Control Entries (Aces) zum NTFS-Sicherheitsdeskriptor ist der zweite Schritt bei der Erstellung von NTFS-Audit-Richtlinien für Dateien oder Ordner in SVMs. Jeder Eintrag identifiziert den Benutzer oder die Gruppe, die Sie prüfen möchten. Der SACL-Eintrag definiert, ob Sie erfolgreiche oder fehlgeschlagene Zugriffsversuche prüfen möchten.' 
---
= Fügen Sie NTFS SACL-Zugriffssteuerungseinträge zum NTFS-Sicherheitsdeskriptor hinzu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Hinzufügen von SACL (System Access Control List) Access Control Entries (Aces) zum NTFS-Sicherheitsdeskriptor ist der zweite Schritt bei der Erstellung von NTFS-Audit-Richtlinien für Dateien oder Ordner in SVMs. Jeder Eintrag identifiziert den Benutzer oder die Gruppe, die Sie prüfen möchten. Der SACL-Eintrag definiert, ob Sie erfolgreiche oder fehlgeschlagene Zugriffsversuche prüfen möchten.

.Über diese Aufgabe
Sie können eine oder mehrere Asse zur SACL des Sicherheitsdeskriptors hinzufügen.

Wenn der Sicherheitsdeskriptor eine SACL enthält, die Asse enthält, fügt der Befehl den neuen ACE zur SACL hinzu. Wenn der Sicherheitsdeskriptor keine SACL enthält, erstellt der Befehl die SACL und fügt diesem den neuen ACE hinzu.

Sie können SACL-Einträge konfigurieren, indem Sie angeben, welche Rechte Sie für erfolgreiche Ereignisse oder Fehlerereignisse für das in angegebene Konto prüfen möchten `-account` Parameter. Es gibt drei Methoden, die sich gegenseitig ausschließen, um Rechte anzugeben:

* Rechte
* Erweiterte Rechte
* RAW-Rechte (Advanced-Privilege)


[NOTE]
====
Wenn Sie keine Rechte für den SACL-Eintrag angeben, ist die Standardeinstellung `Full Control`.

====
Sie können optional SACL-Einträge anpassen, indem Sie festlegen, wie Vererbung mit dem angewendet wird `apply to` Parameter. Wenn Sie diesen Parameter nicht angeben, wird dieser SACL-Eintrag standardmäßig auf diesen Ordner, Unterordner und Dateien angewendet.

.Schritte
. Hinzufügen eines SACL-Eintrags zu einem Sicherheitsdeskriptor: `vserver security file-directory ntfs sacl add -vserver vserver_name -ntfs-sd SD_name -access-type {failure|success} -account name_or_SIDoptional_parameters`
+
`vserver security file-directory ntfs sacl add -ntfs-sd sd1 -access-type failure -account domain\joe -rights full-control -apply-to this-folder -vserver vs1`

. Vergewissern Sie sich, dass die SACL-Eingabe korrekt ist: `vserver security file-directory ntfs sacl show -vserver vserver_name -ntfs-sd SD_name -access-type {failure|success} -account name_or_SID`
+
`vserver security file-directory ntfs sacl show -vserver vs1 -ntfs-sd sd1 -access-type deny -account domain\joe`

+
[listing]
----
                                  Vserver: vs1
                        Security Descriptor Name: sd1
         Access type for Specified Access Rights: failure
                             Account Name or SID: DOMAIN\joe
                                   Access Rights: full-control
                          Advanced Access Rights: -
                                        Apply To: this-folder
                                   Access Rights: full-control
----

