---
permalink: smb-admin/add-home-directory-share-task.html 
sidebar: sidebar 
keywords: smb, home, directory, feature, add, property, share, properties, property, add a home directory share 
summary: Wenn Sie die SMB Home-Verzeichnisfunktion nutzen möchten, muss mindestens eine Freigabe mit der Home-Verzeichnis-Eigenschaft in den Freigabeeigenschaften hinzugefügt werden. 
---
= ONTAP SMB-Homeverzeichnisfreigaben hinzufügen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die SMB Home-Verzeichnisfunktion nutzen möchten, muss mindestens eine Freigabe mit der Home-Verzeichnis-Eigenschaft in den Freigabeeigenschaften hinzugefügt werden.

.Über diese Aufgabe
Sie können eine Home-Verzeichnisfreigabe zum Zeitpunkt der Erstellung der Freigabe mit dem  `vserver cifs share create` Befehl erstellen, oder eine bestehende Freigabe jederzeit mit dem  `vserver cifs share modify` Befehl in eine Home-Verzeichnisfreigabe umwandeln.

Um eine Home-Verzeichnisfreigabe zu erstellen, muss der Wert  `homedirectory` in der Option  `-share-properties` beim Erstellen oder Ändern einer Freigabe angegeben werden. Der Freigabename und der Freigabepfad können mithilfe von Variablen festgelegt werden, die beim Verbinden der Benutzer mit ihren Home-Verzeichnissen dynamisch erweitert werden. Verfügbare Variablen, die im Pfad verwendet werden können, sind  `%w`,  `%d` und  `%u`, die jeweils dem Windows-Benutzernamen, der Domäne und dem zugeordneten UNIX-Benutzernamen entsprechen.

.Schritte
. Eine Home-Verzeichnisfreigabe hinzufügen: +
`vserver cifs share create -vserver _vserver_name_ -share-name _share_name_ -path _path_ -share-properties homedirectory[,...]`
+
`-vserver` `vserver`Gibt die CIFS-fähige Storage Virtual Machine (SVM) an, auf der der Suchpfad hinzugefügt werden soll.

+
`-share-name _share-name_` gibt den Namen der Home-Verzeichnisfreigabe an.

+
Zusätzlich zur Angabe einer der erforderlichen Variablen muss, falls der Freigabename eine der Literalzeichenfolgen  `%w`,  `%u` oder  `%d` enthält, der Literalzeichenfolge ein % (Prozent) Zeichen vorangestellt werden, um zu verhindern, dass ONTAP die Literalzeichenfolge als Variable behandelt (zum Beispiel  `%%w`).

+
** Der Freigabename muss entweder die  `%w`- oder die  `%u`-Variable enthalten.
** Der Freigabename kann zusätzlich die  `%d` Variable (zum Beispiel  `%d`/`%w`) oder einen statischen Teil im Freigabenamen (zum Beispiel home1_/`%w`) enthalten.
** Wenn die Freigabe von Administratoren verwendet wird, um eine Verbindung zu den Home-Verzeichnissen anderer Benutzer herzustellen oder um Benutzern zu erlauben, eine Verbindung zu den Home-Verzeichnissen anderer Benutzer herzustellen, muss dem dynamischen Freigabenamensmuster eine Tilde (~) vorangestellt werden.
+
Das  `vserver cifs home-directory modify` wird verwendet, um diesen Zugriff zu ermöglichen, indem die  `-is-home-dirs-access-for-admin-enabled` Option auf  `true` gesetzt wird oder indem die erweiterte Option  `-is-home-dirs-access-for-public-enabled` auf  `true` gesetzt wird.



+
`-path` `path` Gibt den relativen Pfad zum Home Directory an.



`-share-properties homedirectory[,...]` Gibt die Eigenschaften dieser Freigabe an. Der  `homedirectory` Wert muss angegeben werden. Zusätzliche Freigabeeigenschaften können mit einer durch Kommas getrennten Liste angegeben werden.

. Es kann mit dem  `vserver cifs share show` Befehl überprüft werden, ob die Freigabe des Home-Verzeichnisses erfolgreich hinzugefügt wurde.


.Beispiel
Der folgende Befehl erstellt eine Home-Verzeichnisfreigabe mit dem Namen `%w`. Die `oplocks`, `browsable` und `changenotify` Freigabeeigenschaften werden zusätzlich zur Einstellung der `homedirectory` Freigabeeigenschaft festgelegt.

[NOTE]
====
Dieses Beispiel zeigt nicht die Ausgabe für alle Shares auf der SVM an. Die Ausgabe ist gekürzt.

====
[listing]
----
cluster1::> vserver cifs share create -vserver vs1 -share-name %w -path %w -share-properties oplocks,browsable,changenotify,homedirectory

vs1::> vserver cifs share show -vserver vs1
Vserver    Share    Path         Properties     Comment  ACL
---------- -------- ------------ -------------- -------- -----------
vs1        %w       %w           oplocks        -        Everyone / Full Control
                                 browsable
                                 changenotify
                                 homedirectory
----
.Verwandte Informationen
* xref:add-home-directory-search-path-task.adoc[Suchpfade für das Home-Verzeichnis hinzufügen]
* xref:requirements-automatic-node-referrals-concept.adoc[Anforderungen und Richtlinien für die Verwendung automatischer Knotenverweise auf Servern]
* xref:manage-accessibility-users-home-directories-task.adoc[Zugänglichkeit zu Benutzer-Home-Verzeichnissen verwalten]

