---
permalink: smb-admin/add-home-directory-share-task.html 
sidebar: sidebar 
keywords: smb, home, directory, feature, add, property, share, properties, property, add a home directory share 
summary: Wenn Sie die SMB-Home-Verzeichnis-Funktion verwenden möchten, müssen Sie mindestens eine Freigabe mit der Eigenschaft Home Directory hinzufügen, die in den Share-Eigenschaften enthalten ist. 
---
= Fügen Sie eine Home-Directory-Freigabe hinzu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die SMB-Home-Verzeichnis-Funktion verwenden möchten, müssen Sie mindestens eine Freigabe mit der Eigenschaft Home Directory hinzufügen, die in den Share-Eigenschaften enthalten ist.

Sie können eine Home-Directory-Freigabe zum Zeitpunkt der Erstellung der Freigabe mit erstellen `vserver cifs share create` Befehl, oder Sie können eine vorhandene Freigabe jederzeit mit dem in ein Home Directory-Share ändern `vserver cifs share modify` Befehl.

Um eine Home-Directory-Freigabe zu erstellen, müssen Sie das einschließen `homedirectory` Wert im `-share-properties` Option, wenn Sie eine Freigabe erstellen oder ändern. Sie können den Freigabennamen und den Freigabepfad mithilfe von Variablen angeben, die dynamisch erweitert werden, wenn Benutzer eine Verbindung zu ihren Home-Verzeichnissen herstellen. Die verfügbaren Variablen, die Sie im Pfad verwenden können, sind `%w`, `%d`, und `%u`, Entsprechend dem Windows-Benutzernamen, der Domäne und dem zugeordneten UNIX-Benutzernamen.

.Schritte
. Home Directory-Freigabe hinzufügen: +
`vserver cifs share create -vserver _vserver_name_ -share-name _share_name_ -path _path_ -share-properties homedirectory[,...]`
+
`-vserver` `vserver` Gibt die CIFS-fähige Storage Virtual Machine (SVM) an, auf der der Suchpfad hinzugefügt werden soll.

+
`-share-name _share-name_` Gibt den Freigabenamen des Home-Verzeichnisses an.

+
Zusätzlich zu einer der erforderlichen Variablen, wenn der Freigabename einen der wörtlichen Zeichenfolgen enthält `%w`, `%u`, Oder `%d`, Sie müssen vor dem Literal String ein % (Prozent) Zeichen setzen, um zu verhindern, dass ONTAP die Zeichenfolge als Variable behandelt (z. B. `%%w`).

+
** Der Freigeben-Name muss entweder den enthalten `%w` Oder im `%u` Variabel.
** Der Freigeben-Name kann zusätzlich das enthalten `%d` Variable (z. B. `%d`/`%w`) Oder einen statischen Teil im Freigabennamen (z. B. home1_/`%w`).
** Wenn die Freigabe von Administratoren verwendet wird, um eine Verbindung zu den Home-Verzeichnissen anderer Benutzer herzustellen oder um Benutzern die Verbindung zu den Home-Verzeichnissen anderer Benutzer zu ermöglichen, muss dem dynamischen Namensmuster ein Tilde (~) vorangestellt sein.
+
Der `vserver cifs home-directory modify` Wird verwendet, um diesen Zugriff durch Festlegen der zu aktivieren `-is-home-dirs-access-for-admin-enabled` Option auf `true`) Oder durch die Einstellung der erweiterten Option `-is-home-dirs-access-for-public-enabled` Bis `true`.



+
`-path` `path` Gibt den relativen Pfad zum Home-Verzeichnis an.



`-share-properties homedirectory[,...]` Gibt die Freigabeigenschaften für diese Freigabe an. Sie müssen das angeben `homedirectory` Wert: Sie können zusätzliche Freigabegenschaften mithilfe einer kommagetrennten Liste angeben.

. Überprüfen Sie, ob Sie die Home-Directory-Freigabe mithilfe des erfolgreich hinzugefügt haben `vserver cifs share show` Befehl.


Mit dem folgenden Befehl wird eine Home Directory-Freigabe mit dem Namen erstellt `%w`. Der `oplocks`, `browsable`, und `changenotify` Freigabeigenschaften werden zusätzlich zur Einstellung des festgelegt `homedirectory` Eigenschaft freigeben.

[NOTE]
====
Dieses Beispiel zeigt nicht die Ausgabe für alle Freigaben auf der SVM an. Ausgabe wird abgeschnitten.

====
[listing]
----
cluster1::> vserver cifs share create -vserver vs1 -share-name %w -path %w -share-properties oplocks,browsable,changenotify,homedirectory

vs1::> vserver cifs share show -vserver vs1
Vserver    Share    Path         Properties     Comment  ACL
---------- -------- ------------ -------------- -------- -----------
vs1        %w       %w           oplocks        -        Everyone / Full Control
                                 browsable
                                 changenotify
                                 homedirectory
----
xref:add-home-directory-search-path-task.adoc[Hinzufügen eines Suchpfads für das Home-Verzeichnis]

xref:requirements-automatic-node-referrals-concept.adoc[Anforderungen und Richtlinien für die Nutzung automatischer Node-Empfehlungen]

xref:manage-accessibility-users-home-directories-task.adoc[Management des Zugriffs auf die Home Directorys von Benutzern]
