---
permalink: smb-admin/add-ntfs-dacl-entries-security-descriptor-task.html 
sidebar: sidebar 
keywords: add, dacl, discretionary, access, control, list, access, control, entries, aces, ntfs, security, descriptor, acls, add ntfs dacl access control entries to the ntfs security 
summary: 'Das Hinzufügen von DACL (Ermessensliste für die Zugriffssteuerung) zum NTFS-Sicherheitsdeskriptor ist der zweite Schritt bei der Konfiguration und Anwendung von NTFS-ACLs auf eine Datei oder einen Ordner. Jeder Eintrag identifiziert, welches Objekt erlaubt oder verweigert wird, und definiert, was das Objekt für die im ACE definierten Dateien oder Ordner tun kann oder nicht.' 
---
= Fügen Sie NTFS DACL-Zugriffskontrolleinträge zum NTFS-Sicherheitsdeskriptor in ONTAP hinzu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Hinzufügen von DACL (Ermessensliste für die Zugriffssteuerung) zum NTFS-Sicherheitsdeskriptor ist der zweite Schritt bei der Konfiguration und Anwendung von NTFS-ACLs auf eine Datei oder einen Ordner. Jeder Eintrag identifiziert, welches Objekt erlaubt oder verweigert wird, und definiert, was das Objekt für die im ACE definierten Dateien oder Ordner tun kann oder nicht.

.Über diese Aufgabe
Sie können eine oder mehrere Asse zur DACL des Sicherheitsdeskriptors hinzufügen.

Wenn der Sicherheitsdeskriptor eine DACL enthält, die Asse enthält, fügt der Befehl den neuen ACE zum DACL hinzu. Wenn der Sicherheitsdeskriptor keine DACL enthält, erstellt der Befehl die DACL und fügt den neuen ACE hinzu.

Sie können optional DACL-Einträge anpassen, indem Sie angeben, welche Rechte Sie für das im `-account` Parameter angegebene Konto zulassen oder verweigern möchten. Es gibt drei Methoden, die sich gegenseitig ausschließen, um Rechte anzugeben:

* Rechte
* Erweiterte Rechte
* RAW-Rechte (Advanced-Privilege)


[NOTE]
====
Wenn Sie keine Rechte für den DACL-Eintrag angeben, ist die Standardeinstellung, die Rechte auf `Full Control`zu setzen.

====
Sie können optional DACL-Einträge anpassen, indem Sie festlegen, wie Vererbung angewendet wird.

Der Wert für alle optionalen Parameter wird für Storage-Level Access Guard ignoriert. Erfahren Sie mehr über die in diesem Verfahren beschriebenen Befehle im link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP-Befehlsreferenz"^].

.Schritte
. Hinzufügen eines DACL-Eintrags zu einem Sicherheitsdeskriptor: `vserver security file-directory ntfs dacl add -vserver vserver_name -ntfs-sd SD_name -access-type {allow|deny} -account name_or_SIDoptional_parameters`
+
`vserver security file-directory ntfs dacl add -ntfs-sd sd1 -access-type deny -account domain\joe -rights full-control -apply-to this-folder -vserver vs1`

. Überprüfen Sie, ob der DACL-Eintrag korrekt ist: `vserver security file-directory ntfs dacl show -vserver vserver_name -ntfs-sd SD_name -access-type {allow|deny} -account name_or_SID`
+
`vserver security file-directory ntfs dacl show -vserver vs1 -ntfs-sd sd1 -access-type deny -account domain\joe`

+
[listing]
----
                       Vserver: vs1
             Security Descriptor Name: sd1
                        Allow or Deny: deny
                  Account Name or SID: DOMAIN\joe
                        Access Rights: full-control
               Advanced Access Rights: -
                             Apply To: this-folder
                        Access Rights: full-control
----


Erfahren Sie mehr über `vserver security file-directory ntfs dacl` in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+ntfs+dacl["ONTAP-Befehlsreferenz"^].
