---
permalink: smb-admin/add-list-netbios-aliases-server-task.html 
sidebar: sidebar 
keywords: smb, client, connect, cifs, server, alias, create, list, netbios 
summary: Wenn SMB-Clients mithilfe eines Alias eine Verbindung zum CIFS-Server herstellen sollen, können Sie eine Liste von NetBIOS-Aliasen erstellen oder NetBIOS-Aliase zu einer vorhandenen Liste von NetBIOS-Aliasen hinzufügen. 
---
= Fügen Sie dem SMB-Server eine Liste von NetBIOS-Aliase hinzu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn SMB-Clients über einen Alias eine Verbindung zum SMB-Server herstellen möchten, können Sie eine Liste von NetBIOS-Aliasen erstellen oder NetBIOS-Aliase einer vorhandenen NetBIOS-Aliase hinzufügen.

.Über diese Aufgabe
* Der NetBIOS-Aliasname kann 15 bis Zeichen lang sein.
* Sie können bis zu 200 NetBIOS Aliase auf dem SMB-Server konfigurieren.
* Die folgenden Zeichen sind nicht zulässig:
+
@ # * ( ) = + [ ] : " , < > \ / ?



.Schritte
. Fügen Sie die NetBIOS-Aliase hinzu: +
`vserver cifs add-netbios-aliases -vserver _vserver_name_ -netbios-aliases _NetBIOS_alias_,...`
+
`vserver cifs add-netbios-aliases -vserver vs1 -netbios-aliases alias_1,alias_2,alias_3`

+
** Sie können einen oder mehrere NetBIOS-Aliase mithilfe einer durch Komma getrennten Liste angeben.
** Die angegebenen NetBIOS-Aliase werden der vorhandenen Liste hinzugefügt.
** Eine neue Liste von NetBIOS-Aliasen wird erstellt, wenn die Liste derzeit leer ist.


. Überprüfen Sie, ob die NetBIOS-Aliase korrekt hinzugefügt wurden: `vserver cifs show -vserver vserver_name -display-netbios-aliases`
+
`vserver cifs show -vserver vs1 -display-netbios-aliases`

+
[listing]
----
Vserver: vs1

         Server Name: CIFS_SERVER
         NetBIOS Aliases: ALIAS_1, ALIAS_2, ALIAS_3
----


.Verwandte Informationen
xref:remove-netbios-aliases-from-list-task.adoc[Entfernen von NetBIOS-Aliasse aus der NetBIOS-Alialiste]

xref:display-list-netbios-aliases-task.adoc[Anzeigen der Liste der NetBIOS-Aliase auf CIFS-Servern]
