---
permalink: smb-admin/add-home-directory-search-path-task.html 
sidebar: sidebar 
keywords: ontap, smb, directories, directory, add, path, add a home directory search path 
summary: Wenn Sie ONTAP SMB Home Directorys verwenden möchten, müssen Sie mindestens einen Suchpfad für das Home Directory hinzufügen. 
---
= Fügen Sie einen Suchpfad für das Home-Verzeichnis hinzu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ONTAP SMB Home Directorys verwenden möchten, müssen Sie mindestens einen Suchpfad für das Home Directory hinzufügen.

Sie können einen Suchpfad für das Home-Verzeichnis mit dem hinzufügen `vserver cifs home-directory search-path add` Befehl.

Der `vserver cifs home-directory search-path add` Befehl überprüft den im angegebenen Pfad `-path` Option während der Befehlsausführung. Wenn der angegebene Pfad nicht vorhanden ist, generiert der Befehl eine Meldung, in der Sie aufgefordert werden, fortzufahren. Sie entscheiden `y` Oder `n`. Wenn Sie sich entscheiden `y` Um fortzufahren, erstellt ONTAP den Suchpfad. Sie müssen jedoch die Verzeichnisstruktur erstellen, bevor Sie den Suchpfad in der Konfiguration des Home-Verzeichnisses verwenden können. Wenn Sie den Vorgang nicht fortsetzen möchten, schlägt der Befehl fehl; der Suchpfad wird nicht erstellt. Sie können dann die Struktur des Pfad-Verzeichnisses erstellen und den erneut ausführen `vserver cifs home-directory search-path add` Befehl.

.Schritte
. Hinzufügen eines Suchpfads für das Home-Verzeichnis: `vserver cifs home-directory search-path add -vserver vserver -path path`
. Überprüfen Sie, ob Sie den Suchpfad mithilfe des erfolgreich hinzugefügt haben `vserver cifs home-directory search-path show` Befehl.


Im folgenden Beispiel wird der Pfad hinzugefügt `/home1` Zur Home Directory-Konfiguration auf SVM vs1.

[listing]
----
cluster::> vserver cifs home-directory search-path add -vserver vs1 -path /home1

vs1::> vserver cifs home-directory search-path show
Vserver     Position Path
----------- -------- -----------------
vs1         1        /home1
----
Im folgenden Beispiel wird versucht, den Pfad hinzuzufügen `/home2` Zur Home Directory-Konfiguration auf SVM vs1. Der Pfad ist nicht vorhanden. Es wird die Entscheidung getroffen, nicht fortzufahren.

[listing]
----
cluster::> vserver cifs home-directory search-path add -vserver vs1 -path /home2
Warning: The specified path "/home2" does not exist in the namespace
         belonging to Vserver "vs1".
Do you want to continue? {y|n}: n
----
xref:add-home-directory-share-task.adoc[Hinzufügen einer Home-Directory-Freigabe]
