---
permalink: smb-admin/allow-users-groups-bypass-directory-traverse-task.html 
sidebar: sidebar 
keywords: traverse, directories, directory, path, file, permission, sechangenotifyprivilege, privilege, local, smb, user, svm, bypass, traverse, check, allow users or groups to bypass directory traverse checking 
summary: 'Wenn ein Benutzer in der Lage sein soll, alle Verzeichnisse im Pfad zu einer Datei zu durchlaufen, selbst wenn der Benutzer in einem durchlaufenen Verzeichnis keine Berechtigungen besitzt, können Sie die SeChangeNotifyPrivilege-Berechtigung lokalen SMB-Benutzern oder Gruppen auf Storage Virtual Machines (SVMs) hinzufügen. Standardmäßig können Benutzer die Verzeichnisprüfung umgehen.' 
---
= Erlauben Sie Benutzern oder Gruppen, die ONTAP SMB-Verzeichnisdurchquerungsprüfung zu umgehen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie möchten, dass ein Benutzer alle Verzeichnisse im Pfad zu einer Datei durchlaufen kann, selbst wenn der Benutzer keine Berechtigungen für ein durchlauftes Verzeichnis besitzt, können Sie die `SeChangeNotifyPrivilege` Berechtigung lokalen SMB-Benutzern oder Gruppen auf Storage Virtual Machines (SVMs) hinzufügen. Standardmäßig können Benutzer die Verzeichnisprüfung umgehen.

.Bevor Sie beginnen
* Auf der SVM muss ein SMB-Server vorhanden sein.
* Die Option für lokale Benutzer und SMB-Gruppen-Server muss aktiviert sein.
* Der lokale oder Domänenbenutzer oder die Domänengruppe, zu der die `SeChangeNotifyPrivilege` Berechtigung hinzugefügt wird, muss bereits vorhanden sein.


.Über diese Aufgabe
Beim Hinzufügen von Berechtigungen zu einem Domänenbenutzer oder einer Gruppe kann ONTAP den Domänenbenutzer oder die Gruppe validieren, indem er sich an den Domänencontroller wenden kann. Der Befehl schlägt möglicherweise fehl, wenn ONTAP den Domain-Controller nicht kontaktieren kann.

.Schritte
. Aktivieren Sie die Umgehungsdurchgangsprüfung, indem Sie die `SeChangeNotifyPrivilege` Berechtigung zu einem lokalen oder Domänenbenutzer oder einer Gruppe hinzufügen: `vserver cifs users-and-groups privilege add-privilege -vserver _vserver_name_ -user-or-group-name _name_ -privileges SeChangeNotifyPrivilege`
+
Der Wert für den `-user-or-group-name` Parameter ist ein lokaler Benutzer oder eine lokale Gruppe oder ein Domänenbenutzer oder eine Domänengruppe.

. Überprüfen Sie, ob für den angegebenen Benutzer oder die angegebene Gruppe die Umgehungsdurchgangsprüfung aktiviert ist: `vserver cifs users-and-groups privilege show -vserver _vserver_name_ ‑user-or-group-name _name_`


.Beispiel
Mit dem folgenden Befehl können Benutzer, die zur Gruppe „`EXAMPLE` eng\“ gehören, die Prüfung der Verzeichnisdurchfahrt umgehen, indem sie die `SeChangeNotifyPrivilege` Berechtigung zur Gruppe hinzufügen:

[listing]
----
cluster1::> vserver cifs users-and-groups privilege add-privilege -vserver vs1 -user-or-group-name EXAMPLE\eng -privileges SeChangeNotifyPrivilege

cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- ---------------
vs1       EXAMPLE\eng           SeChangeNotifyPrivilege
----
.Verwandte Informationen
xref:disallow-users-groups-bypass-directory-traverse-task.adoc[Benutzer oder Gruppen davon ablassen, die Überprüfung der Verzeichnisdurchgang zu umgehen]
