---
permalink: smb-admin/branchcache-cache-share-content-branch-office-concept.html 
sidebar: sidebar 
keywords: branchcache, develop, microsoft, enable, caching, cache, content, computer, local, request, client, ontap, implementation, reduce, wide-area, network, wan, utilization, response, svm, smb, use branchcache to cache smb share content at a branch office 
summary: BranchCache wurde von Microsoft entwickelt, um das Zwischenspeichern von Inhalten auf Rechnern lokal zu den anfragenden Clients zu ermöglichen. Die ONTAP-Implementierung von BranchCache kann die Auslastung des Weitverkehrsnetzes reduzieren und die Zugriffszeiten verbessern, wenn Benutzer in einer Zweigstelle über SMB auf Inhalte zugreifen, die auf Storage Virtual Machines gespeichert sind. 
---
= Informationen zur Verwendung von BranchCache zum Zwischenspeichern von ONTAP SMB-Freigabeinhalten in einer Zweigstelle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BranchCache wurde von Microsoft entwickelt, um das Zwischenspeichern von Inhalten auf Rechnern lokal zu den anfragenden Clients zu ermöglichen. Die ONTAP Implementierung von BranchCache kann die Auslastung des Weitverkehrsnetzes (WAN) reduzieren und eine verbesserte Zugriffszeit bieten, wenn Benutzer in einer Zweigstelle über SMB auf Inhalte zugreifen, die auf Storage Virtual Machines (SVMs) gespeichert sind.

Wenn BranchCache konfiguriert wird, rufen Windows BranchCache-Clients Inhalte zunächst von der SVM ab und speichern die Inhalte anschließend auf einem Computer innerhalb der Zweigstelle im Cache. Fordert ein anderer BranchCache-fähiger Client in der Zweigstelle dieselben Inhalte an, authentifiziert und autorisiert die SVM zunächst den anfragenden Benutzer. Anschließend prüft die SVM, ob die zwischengespeicherten Inhalte noch aktuell sind, und sendet dem Client, falls dies zutrifft, Metadaten zu den zwischengespeicherten Inhalten. Der Client verwendet dann die Metadaten, um die Inhalte direkt aus dem lokal gespeicherten Cache abzurufen.

.Verwandte Informationen
xref:offline-files-allow-caching-concept.adoc[Informationen zur Verwendung von Offline-Dateien, um das Zwischenspeichern von Dateien für die Offline-Nutzung zu ermöglichen]
