---
permalink: smb-admin/branchcache-when-reverting-concept.html 
sidebar: sidebar 
keywords: revert, ontap, release, support, branchcache, what happens to branchcache when reverting 
summary: Es ist wichtig zu verstehen, was passiert, wenn ONTAP auf eine Version zurückgesetzt wird, die BranchCache nicht unterstützt. 
---
= Was mit ONTAP SMB BranchCache beim Zurücksetzen geschieht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es ist wichtig zu verstehen, was passiert, wenn ONTAP auf eine Version zurückgesetzt wird, die BranchCache nicht unterstützt.

* Wenn auf eine Version von ONTAP zurückgegangen wird, die BranchCache nicht unterstützt, geben die SMB-Freigaben keine BranchCache-Funktionen an BranchCache-fähige Clients bekannt; daher fordern die Clients keine Hash-Informationen an.
+
Stattdessen fordern sie die eigentlichen Inhalte über normale SMB-Leseanfragen an. Als Antwort auf die Anforderung von Inhalten sendet der SMB-Server den tatsächlichen Inhalt, der auf der Storage Virtual Machine (SVM) gespeichert ist.

* Wenn ein Knoten, der einen Hash-Speicher hostet, auf eine Version zurückgesetzt wird, die BranchCache nicht unterstützt, muss der Speicheradministrator die BranchCache-Konfiguration manuell mit einem Befehl zurücksetzen, der während des Rücksetzungsvorgangs ausgegeben wird.
+
Dieser Befehl löscht die BranchCache Konfiguration und Hashes.

+
Nach Abschluss des Revert-Vorgangs kann der Storage-Administrator das Verzeichnis, das den Hash Store enthielt, bei Bedarf manuell löschen.



.Verwandte Informationen
xref:delete-branchcache-config-task.html[Die BranchCache Konfiguration auf Freigaben löschen]
