---
permalink: smb-admin/builtin-groups-local-administrator-account-concept.html 
sidebar: sidebar 
keywords: guideline, mind, builtin, group, local, administrator, account, delete, guidelines for using builtin groups and the local administrator account 
summary: Bestimmte Richtlinien sind zu beachten, wenn integrierte Gruppen und das lokale Administratorkonto verwendet werden. Beispielsweise kann das lokale Administratorkonto umbenannt, jedoch nicht gelöscht werden. 
---
= Informationen zu BUILTIN Gruppen und lokalen Administrator Konten auf ONTAP SMB Servern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bestimmte Richtlinien sind zu beachten, wenn integrierte Gruppen und das lokale Administratorkonto verwendet werden. Beispielsweise kann das lokale Administratorkonto umbenannt, jedoch nicht gelöscht werden.

* Das Administratorkonto kann umbenannt, aber nicht gelöscht werden.
* Das Administratorkonto kann nicht aus der Gruppe BUILTIN\Administrators entfernt werden.
* BUILTIN-Gruppen können umbenannt, aber nicht gelöscht werden.
+
Nach der Umbenennung der BUILTIN-Gruppe kann ein weiteres lokales Objekt mit dem bekannten Namen erstellt werden; dem Objekt wird jedoch eine neue RID zugewiesen.

* Es existiert kein lokales Gastkonto.


.Verwandte Informationen
xref:builtin-groups-default-privileges-reference.adoc[Vordefinierte BUILTIN Gruppen und Standardberechtigungen]
