---
permalink: smb-admin/builtin-groups-default-privileges-reference.html 
sidebar: sidebar 
keywords: assign, membership, local, user, domain, predefined, builtin, ontap, predefined builtin groups and default privileges 
summary: Sie können einer vordefinierten Gruppe von BUILTIN-Gruppen, die von ONTAP bereitgestellt werden, die Mitgliedschaft eines lokalen Benutzers oder eines Domänenbenutzers zuweisen. Vordefinierte Gruppen verfügen über vordefinierte Berechtigungen. 
---
= Vordefinierte BUILTIN-Gruppen und Standardberechtigungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einer vordefinierten Gruppe von BUILTIN-Gruppen, die von ONTAP bereitgestellt werden, die Mitgliedschaft eines lokalen Benutzers oder eines Domänenbenutzers zuweisen. Vordefinierte Gruppen verfügen über vordefinierte Berechtigungen.

In der folgenden Tabelle werden die vordefinierten Gruppen beschrieben:

|===
| Vordefinierte BUILTIN-Gruppe | Standardberechtigungen 


 a| 
``BUILTIN\Administrators``RID 544

Beim ersten Erstellen `Administrator` wird das lokale Konto, mit einem RID von 500, automatisch zu einem Mitglied dieser Gruppe. Wenn die Storage Virtual Machine (SVM) einer Domäne beigetreten ist, `domain\Domain Admins` wird die Gruppe der Gruppe hinzugefügt. Wenn die SVM die Domäne verlässt, `domain\Domain Admins` wird die Gruppe aus der Gruppe entfernt.
 a| 
* `SeBackupPrivilege`
* `SeRestorePrivilege`
* `SeSecurityPrivilege`
* `SeTakeOwnershipPrivilege`
* `SeChangeNotifyPrivilege`




 a| 
``BUILTIN\Power Users``RID 547

Bei der ersten Erstellung verfügt diese Gruppe über keine Mitglieder. Mitglieder dieser Gruppe haben folgende Merkmale:

* Es können lokale Benutzer und Gruppen erstellt und verwaltet werden.
* Sie oder ein anderes Objekt können der `BUILTIN\Administrators` Gruppe nicht hinzugefügt werden.

 a| 
`SeChangeNotifyPrivilege`



 a| 
``BUILTIN\Backup Operators``RID 551

Bei der ersten Erstellung verfügt diese Gruppe über keine Mitglieder. Mitglieder dieser Gruppe können Lese- und Schreibberechtigungen für Dateien oder Ordner überschreiben, wenn sie mit Sicherungsziel geöffnet werden.
 a| 
* `SeBackupPrivilege`
* `SeRestorePrivilege`
* `SeChangeNotifyPrivilege`




 a| 
``BUILTIN\Users``RID 545

Beim ersten Erstellen hat diese Gruppe keine Mitglieder (außer der implizierten `Authenticated Users` Spezialgruppe). Wenn die SVM einer Domäne `domain\Domain Users` hinzugefügt wird, wird die Gruppe dieser Gruppe hinzugefügt. Wenn die SVM die Domäne verlässt, `domain\Domain Users` wird die Gruppe aus dieser Gruppe entfernt.
 a| 
`SeChangeNotifyPrivilege`



 a| 
``Everyone``SID S-1-1-0

Diese Gruppe umfasst alle Benutzer, einschließlich Gäste (aber nicht anonyme Benutzer). Hierbei handelt es sich um eine implizite Gruppe mit einer impliziten Mitgliedschaft.
 a| 
`SeChangeNotifyPrivilege`

|===
.Verwandte Informationen
xref:builtin-groups-local-administrator-account-concept.adoc[Richtlinien für die Nutzung von BUILTIN-Gruppen und dem lokalen Administratorkonto]

xref:list-supported-privileges-reference.adoc[Liste der unterstützten Berechtigungen]

xref:configure-bypass-traverse-checking-concept.adoc[Konfigurieren der Umgehungsüberprüfung]
