---
permalink: smb-admin/case-sensitivity-file-directory-multiprotocol-concept.html 
sidebar: sidebar 
keywords: file, directory, name, case-sensitive, nfs, client, case-preserving, preserve, implication, multiprotocol, environment, action, case-sensitivity of file and directory names in a multiprotocol environment 
summary: Datei- und Verzeichnisnamen werden bei NFS-Clients Groß-/Kleinschreibung berücksichtigt, und die Groß-/Kleinschreibung wird nicht berücksichtigt. Sie müssen die Auswirkungen in einer Multi-Protokoll-Umgebung und die Aktionen verstehen, die Sie bei der Angabe des Pfads beim Erstellen von SMB-Freigaben und beim Zugriff auf Daten innerhalb der Freigaben ergreifen müssen. 
---
= Groß- und Kleinschreibung von ONTAP SMB-Datei- und Verzeichnisnamen in einer Multiprotokollumgebung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Datei- und Verzeichnisnamen werden bei NFS-Clients Groß-/Kleinschreibung berücksichtigt, und die Groß-/Kleinschreibung wird nicht berücksichtigt. Sie müssen die Auswirkungen in einer Multi-Protokoll-Umgebung und die Aktionen verstehen, die Sie bei der Angabe des Pfads beim Erstellen von SMB-Freigaben und beim Zugriff auf Daten innerhalb der Freigaben ergreifen müssen.

Wenn ein SMB-Client ein Verzeichnis mit dem Namen erstellt `testdir`, zeigen sowohl SMB- als auch NFS-Clients den Dateinamen als `testdir`an. Wenn ein SMB-Benutzer jedoch später versucht, einen Verzeichnisnamen zu erstellen `TESTDIR`, ist der Name nicht zulässig, da dieser Name für den SMB-Client derzeit vorhanden ist. Wenn ein NFS-Benutzer später ein Verzeichnis mit `TESTDIR`dem Namen erstellt, zeigen NFS- und SMB-Clients den Verzeichnisnamen anders an, wie folgt:

* Auf NFS-Clients sehen Sie beide Verzeichnisnamen so, wie sie erstellt wurden, z. B. `testdir` und `TESTDIR`, da Verzeichnisnamen zwischen Groß- und Kleinschreibung unterschieden werden.
* SMB-Clients verwenden die 8.3 Namen, um zwischen den beiden Verzeichnissen zu unterscheiden. Ein Verzeichnis hat den Basisdateinamen. Zusätzlichen Verzeichnissen wird ein Dateiname von 8.3 zugewiesen.
+
** Auf SMB-Clients sehen Sie `testdir` und `TESTDI~1`.
** ONTAP erstellt den `TESTDI~1` Verzeichnisnamen, um die beiden Verzeichnisse zu differenzieren.
+
In diesem Fall müssen Sie den Namen 8.3 verwenden, wenn Sie einen Freigabepfad angeben, während Sie eine Freigabe auf einer Storage Virtual Machine (SVM) erstellen oder ändern.





Ähnlich für Dateien, wenn ein SMB-Client erstellt `test.txt`, sowohl SMB- als auch NFS-Clients zeigen den Dateinamen als `text.txt`an. Wenn ein SMB-Benutzer jedoch später versucht, zu erstellen `Test.txt`, ist der Name nicht zulässig, da dieser Name für den SMB-Client derzeit vorhanden ist. Wenn ein NFS-Benutzer später eine Datei mit `Test.txt`dem Namen erstellt, zeigen NFS- und SMB-Clients den Dateinamen anders an, wie folgt:

* Auf NFS-Clients sehen Sie beide Dateinamen so, wie sie erstellt wurden, `test.txt` und `Test.txt`, weil Dateinamen zwischen Groß- und Kleinschreibung unterschieden werden.
* SMB-Clients verwenden die 8.3 Namen, um zwischen den beiden Dateien zu unterscheiden. Eine Datei hat den Basisdateinamen. Zusätzlichen Dateien wird ein Dateiname von 8.3 zugewiesen.
+
** Auf SMB-Clients sehen Sie `test.txt` und `TEST~1.TXT`.
** ONTAP erstellt den `TEST~1.TXT` Dateinamen, um die beiden Dateien zu differenzieren.




[NOTE]
====
Wenn Sie die Zeichenzuordnung über die CIFS-Befehle zur Character Mapping von Vserver aktiviert oder geändert haben, wird bei einer Windows Lookup im Normalfall die Groß-/Kleinschreibung nicht berücksichtigt.

====