---
permalink: smb-admin/client-performance-traditional-lease-oplocks-concept.html 
sidebar: sidebar 
keywords: traditional, oplocks, opportunistic, locks, lease, smb, client, client-side, read-ahead, file-sharing, write-behind, information, access, reducing, reduce, network, traffic, improve client performance with traditional and lease oplocks 
summary: 'Herkömmliche Oplocks (opportunistic Locks) und Leasing-Oplocks ermöglichen einem SMB Client in bestimmten File Sharing-Szenarien das Caching von Read-Ahead-, Write-Behind-Lock-Informationen. Ein Client kann dann eine Datei lesen oder in eine Datei schreiben, ohne regelmäßig den Server daran zu erinnern, dass er Zugriff auf die betreffende Datei benötigt. Dies verbessert die Leistung durch Verringerung des Netzwerkverkehrs.' 
---
= Erfahren Sie mehr über die Verbesserung der ONTAP SMB-Client-Performance mit herkömmlichen und Leasing-Oplocks
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Herkömmliche Oplocks (opportunistic Locks) und Leasing-Oplocks ermöglichen einem SMB Client in bestimmten File Sharing-Szenarien das Caching von Read-Ahead-, Write-Behind-Lock-Informationen. Ein Client kann dann eine Datei lesen oder in eine Datei schreiben, ohne regelmäßig den Server daran zu erinnern, dass er Zugriff auf die betreffende Datei benötigt. Dies verbessert die Leistung durch Verringerung des Netzwerkverkehrs.

Leasing-Oplocks sind eine verbesserte Form von Oplocks, die mit dem SMB 2.1-Protokoll und höher verfügbar sind. Leasing-Oplocks ermöglichen es einem Client, den Caching-Status über mehrere von sich selbst stammende SMB-öffnet abzurufen und zu erhalten.

Oplocks können auf zwei Arten gesteuert werden:

* Durch eine Freigabeeigenschaft, mit dem `vserver cifs share create` Befehl beim Erstellen der Freigabe oder dem `vserver share properties` Befehl nach der Erstellung.
* Mittels einer qtree-Eigenschaft `volume qtree create` oder des Befehls beim Erstellen des qtree oder `volume qtree oplock` nach der Erstellung

