---
permalink: smb-admin/command-options-limit-client-resource-concept.html 
sidebar: sidebar 
keywords: option, vserver, cifs, modify, command, enable, control, resource, consumption, windows, client, bound, notify, request, command options to limit excessive windows client resource consumption 
summary: 'Die Optionen des Befehls `vserver cifs options modify` ermöglichen die Steuerung des Ressourcenverbrauchs von Windows-Clients. Dies kann hilfreich sein, wenn einzelne Clients den normalen Ressourcenverbrauch überschreiten, beispielsweise bei einer ungewöhnlich hohen Anzahl geöffneter Dateien, Sitzungen oder Änderungsbenachrichtigungsanforderungen.' 
---
= ONTAP Befehlsoptionen zur Begrenzung des übermäßigen Ressourcenverbrauchs von Windows Clients
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Optionen des  `vserver cifs options modify` Befehls ermöglichen die Steuerung des Ressourcenverbrauchs von Windows-Clients. Dies kann hilfreich sein, wenn einzelne Clients den normalen Ressourcenverbrauch überschreiten, beispielsweise bei einer ungewöhnlich hohen Anzahl geöffneter Dateien, Sitzungen oder Änderungsbenachrichtigungsanforderungen.

Die folgenden Optionen zum  `vserver cifs options modify` Befehl wurden hinzugefügt, um den Ressourcenverbrauch von Windows-Clients zu steuern. Wird der Maximalwert einer dieser Optionen überschritten, wird die Anfrage abgelehnt und eine EMS-Meldung gesendet. Eine EMS-Warnmeldung wird auch gesendet, wenn 80 Prozent des konfigurierten Grenzwerts für diese Optionen erreicht sind.

* `-max-opens-same-file-per-tree`
+
Maximale Anzahl von Öffnungen derselben Datei pro CIFS-Baum

* `-max-same-user-sessions-per-connection`
+
Maximale Anzahl von Sitzungen, die vom selben Benutzer pro Verbindung geöffnet sind

* `-max-same-tree-connect-per-session`
+
Maximale Anzahl von Baumverbindungen auf derselben Freigabe pro Sitzung

* `-max-watches-set-per-tree`
+
Maximale Anzahl von Überwachungen (auch bekannt als _change notifies_), die pro Baum eingerichtet werden



Weitere Informationen zu  `vserver cifs options modify` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-options-modify.html["ONTAP-Befehlsreferenz"^].

Ab ONTAP 9.4 können Server, auf denen die SMB-Version 2 oder höher ausgeführt wird, die Anzahl der ausstehenden Anforderungen (_SMB-Credits_) begrenzen, die der Client über eine SMB-Verbindung an den Server senden kann. Die Verwaltung von SMB-Credits wird vom Client initiiert und vom Server gesteuert.

Die maximale Anzahl ausstehender Anfragen, die auf einer SMB-Verbindung genehmigt werden können, wird durch die `-max-credits` Option gesteuert. Der Standardwert für diese Option ist 128.
