---
permalink: smb-admin/commands-manage-ntfs-dacl-reference.html 
sidebar: sidebar 
keywords: ontap, command, managing, manage, dacl, access, control, entries, aces, ntfs, modify, deleting, delete, display, information, commands for managing ntfs dacl access control entries 
summary: 'Es gibt bestimmte ONTAP-Befehle zur Verwaltung von DACL Access Control Einträgen (Aces). Sie können Aces zu NTFS DACLs jederzeit hinzufügen. Sie können auch vorhandene NTFS-DACLs verwalten, indem Sie Informationen über Aces in DACLs ändern, löschen und anzeigen.' 
---
= Befehle zum Verwalten von NTFS DACL-Zugriffssteuerungseinträgen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es gibt bestimmte ONTAP-Befehle zur Verwaltung von DACL Access Control Einträgen (Aces). Sie können Aces zu NTFS DACLs jederzeit hinzufügen. Sie können auch vorhandene NTFS-DACLs verwalten, indem Sie Informationen über Aces in DACLs ändern, löschen und anzeigen.

|===
| Ihr Ziel ist | Befehl 


 a| 
Erstellen Sie Aces und fügen Sie sie zu NTFS-DACLs hinzu
 a| 
`vserver security file-directory ntfs dacl add`



 a| 
Vorhandene Asse in NTFS-DACLs ändern
 a| 
`vserver security file-directory ntfs dacl modify`



 a| 
Informationen über vorhandene Asse in NTFS-DACLs anzeigen
 a| 
`vserver security file-directory ntfs dacl show`



 a| 
Entfernen Sie vorhandene Aces aus NTFS-DACLs
 a| 
`vserver security file-directory ntfs dacl remove`

|===
 `vserver security file-directory ntfs dacl`Weitere Informationen zu den Befehlen finden Sie in den man-Pages.
