---
permalink: smb-admin/commands-oplocks-volumes-qtrees-reference.html 
sidebar: sidebar 
keywords: oplock, client, lock, file, cache, performance, operation, qtree, command, enabling, enable, disabling, disable, volume, commands for enabling or disabling oplocks on volumes and qtrees 
summary: Oplocks ermöglichen es Clients, Dateien zu sperren und Inhalte lokal zwischenzuspeichern, was die Leistung bei Dateivorgängen verbessern kann. Sie müssen die Befehle zum Aktivieren oder Deaktivieren von Oplocks auf Volumes oder Qtrees kennen. Sie müssen außerdem wissen, wann Oplocks auf Volumes und Qtrees aktiviert oder deaktiviert werden können. 
---
= ONTAP Befehle zum Aktivieren oder Deaktivieren von Oplocks auf SMB-Volumes und Qtrees
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Oplocks ermöglichen es Clients, Dateien zu sperren und Inhalte lokal zwischenzuspeichern, was die Leistung bei Dateivorgängen verbessern kann. Sie müssen die Befehle zum Aktivieren oder Deaktivieren von Oplocks auf Volumes oder Qtrees kennen. Sie müssen außerdem wissen, wann Oplocks auf Volumes und Qtrees aktiviert oder deaktiviert werden können.

* Oplocks sind auf Volumes standardmäßig aktiviert.
* Oplocks können beim Erstellen eines Volumes nicht deaktiviert werden.
* Sie können Oplocks auf bestehenden Volumes für SVMs jederzeit aktivieren oder deaktivieren.
* Sie können Oplocks auf Qtrees für SVMs aktivieren.
+
Die Oplock-Modus-Einstellung ist eine Eigenschaft des Qtree mit der ID 0, dem Standard-Qtree, den alle Volumes haben. Wird beim Erstellen eines Qtree keine Oplock-Einstellung angegeben, übernimmt der Qtree die Oplock-Einstellung des übergeordneten Volumes, die standardmäßig aktiviert ist. Wird jedoch eine Oplock-Einstellung für den neuen Qtree angegeben, hat diese Vorrang vor der Oplock-Einstellung des Volumes.



|===
| Wenn Sie möchten... | Verwenden Sie diesen Befehl... 


 a| 
Oplocks auf Volumes oder Qtrees aktivieren
 a| 
`volume qtree oplocks` mit dem  `-oplock-mode` Parameter auf  `enable` gesetzt



 a| 
Oplocks auf Volumes oder Qtrees deaktivieren
 a| 
`volume qtree oplocks` mit dem  `-oplock-mode` Parameter auf  `disable` gesetzt

|===
.Verwandte Informationen
xref:monitor-oplock-status-task.adoc[Oplock-Status überwachen]
