---
permalink: smb-admin/commands-manage-servers-reference.html 
sidebar: sidebar 
keywords: command, creating, create, display, modify, stop, start, deleting, delete 
summary: Sie müssen die Befehle zum Erstellen, Anzeigen, Ändern, Stoppen, Starten und Löschen von SMB Servern kennen. Es gibt außerdem Befehle zum Zurücksetzen und erneuten Erkennen von Servern, zum Ändern oder Zurücksetzen von Maschinenkontopasswörtern, zum Planen von Änderungen für Maschinenkontopasswörter sowie zum Hinzufügen oder Entfernen von NetBIOS Aliassen. 
---
= ONTAP Befehle zur Verwaltung von SMB Servern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die Befehle zum Erstellen, Anzeigen, Ändern, Stoppen, Starten und Löschen von SMB Servern kennen. Es gibt außerdem Befehle zum Zurücksetzen und erneuten Erkennen von Servern, zum Ändern oder Zurücksetzen von Maschinenkontopasswörtern, zum Planen von Änderungen für Maschinenkontopasswörter sowie zum Hinzufügen oder Entfernen von NetBIOS Aliassen.

|===


| Wenn Sie möchten... | Verwenden Sie diesen Befehl... 


 a| 
Einen SMB Server erstellen
 a| 
`vserver cifs create`



 a| 
Informationen zu einem SMB Server anzeigen
 a| 
`vserver cifs show`



 a| 
Einen SMB Server modifizieren
 a| 
`vserver cifs modify`



 a| 
Verschieben eines SMB Servers in eine andere Domäne
 a| 
`vserver cifs modify`



 a| 
Anhalten eines SMB-Servers
 a| 
`vserver cifs stop`



 a| 
Einen SMB Server starten
 a| 
`vserver cifs start`



 a| 
Einen SMB Server löschen
 a| 
`vserver cifs delete`



 a| 
Server für den SMB Server zurücksetzen und neu erkennen
 a| 
`vserver cifs domain discovered-servers reset-servers`



 a| 
Das Kennwort des Maschinenkontos des SMB-Servers ändern
 a| 
`vserver cifs domain password change`



 a| 
Das Maschinenkontopasswort des SMB-Servers zurücksetzen
 a| 
`vserver cifs domain password change`



 a| 
Automatische Kennwortänderungen für das Computerkonto des SMB-Servers planen
 a| 
`vserver cifs domain password schedule modify`



 a| 
NetBIOS Aliase für den SMB Server hinzufügen
 a| 
`vserver cifs add-netbios-aliases`



 a| 
NetBIOS-Aliase für den SMB-Server entfernen
 a| 
`vserver cifs remove-netbios-aliases`

|===
Weitere Informationen zu  `vserver cifs` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs["ONTAP-Befehlsreferenz"^].

.Verwandte Informationen
link:local-users-groups-when-deleting-servers-concept.html["Was mit lokalen Benutzern und Gruppen beim Löschen von SMB Servern geschieht"]
