---
permalink: smb-admin/configure-bypass-traverse-checking-concept.html 
sidebar: sidebar 
keywords: bypass, traverse, user, privilege, permission, directory, allow, check, configure, storage, virtual, machine, svm, configure bypass traverse checking 
summary: Die Umgehung der Verzeichnispfadprüfung ist ein Benutzerrecht, das festlegt, ob ein Benutzer alle Verzeichnisse im Pfad zu einer Datei durchlaufen kann, selbst wenn er keine Berechtigungen für das durchlaufene Verzeichnis besitzt. Sie sollten verstehen, was passiert, wenn die Umgehung der Verzeichnispfadprüfung zugelassen oder deaktiviert wird und wie Sie die Umgehung der Verzeichnispfadprüfung für Benutzer auf Storage Virtual Machines konfigurieren. 
---
= Informationen zur Konfiguration der ONTAP SMB Bypass Traverse-Prüfung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Umgehung der Pfadprüfung ist ein Benutzerrecht (auch als Berechtigung bezeichnet), das festlegt, ob ein Benutzer alle Verzeichnisse im Pfad zu einer Datei durchlaufen kann, selbst wenn er keine Berechtigung für das durchlaufene Verzeichnis besitzt. Es ist wichtig zu verstehen, was geschieht, wenn die Umgehung der Pfadprüfung erlaubt oder nicht erlaubt wird, und wie die Umgehung der Pfadprüfung für Benutzer auf Storage Virtual Machines (SVMs) konfiguriert werden kann.



[[what-happens-when-allowing-or-disallowing-bypass-traverse-checking]]
== Was geschieht beim Zulassen oder Verweigern der Bypass Traverse-Prüfung

* Sofern zulässig, prüft ONTAP beim Versuch eines Benutzers, auf eine Datei zuzugreifen, nicht die Traverse-Berechtigung für die Zwischenverzeichnisse, wenn entschieden wird, ob der Zugriff auf die Datei gewährt oder verweigert wird.
* Falls dies nicht zulässig ist, prüft ONTAP die Ausführungsberechtigung für alle Verzeichnisse im Pfad zur Datei.
+
Wenn eines der Zwischenverzeichnisse nicht über die Berechtigung "`X`" (Durchlaufberechtigung) verfügt, verweigert ONTAP den Zugriff auf die Datei.





[[configure-bypass-traverse-checking]]
== Umgehungsüberprüfung konfigurieren

Die Umgehung der Traverse-Prüfung kann mithilfe der ONTAP CLI oder durch die Konfiguration von Active Directory Gruppenrichtlinien mit diesem Benutzerrecht eingerichtet werden.

Die  `SeChangeNotifyPrivilege`Berechtigung steuert, ob Benutzern das Umgehen der Traverse-Prüfung erlaubt ist.

* Das Hinzufügen zu lokalen SMB-Benutzern oder -Gruppen auf der SVM oder zu Domänenbenutzern oder -gruppen ermöglicht das Umgehen der Traverse-Prüfung.
* Das Entfernen aus den lokalen SMB-Benutzern oder Gruppen auf der SVM oder aus den Domänenbenutzern oder Gruppen verhindert die Umgehung der Traverse-Prüfung.


Standardmäßig haben die folgenden BUILTIN-Gruppen auf dem SVM das Recht, die Traversierungsprüfung zu umgehen:

* `BUILTIN\Administrators`
* `BUILTIN\Power Users`
* `BUILTIN\Backup Operators`
* `BUILTIN\Users`
* `Everyone`


Wenn nicht gewünscht ist, dass Mitglieder einer dieser Gruppen die Traverse-Prüfung umgehen, muss dieser Gruppe diese Berechtigung entzogen werden.

Bei der Konfiguration der Umgehung der Traverse-Prüfung für lokale SMB-Benutzer und -Gruppen auf der SVM mithilfe der CLI ist Folgendes zu beachten:

* Wenn Mitglieder einer benutzerdefinierten lokalen oder Domänengruppe die Traverse-Prüfung umgehen dürfen, muss der Gruppe die  `SeChangeNotifyPrivilege` Berechtigung hinzugefügt werden.
* Wenn einem einzelnen lokalen Benutzer oder Domänenbenutzer erlaubt werden soll, die Überprüfung der Zugriffsrechte zu umgehen, und dieser Benutzer kein Mitglied einer Gruppe mit dieser Berechtigung ist, kann die  `SeChangeNotifyPrivilege` Berechtigung diesem Benutzerkonto hinzugefügt werden.
* Sie können die Umgehung der Traverse-Prüfung für lokale oder Domänenbenutzer oder -gruppen deaktivieren, indem Sie die  `SeChangeNotifyPrivilege`Berechtigung jederzeit entfernen.
+
[NOTE]
====
Um die Überprüfung von Bypass-Travers für bestimmte lokale oder Domänenbenutzer oder -gruppen zu deaktivieren, muss außerdem die  `SeChangeNotifyPrivilege` Berechtigung aus der  `Everyone` Gruppe entfernt werden.

====


.Verwandte Informationen
* xref:allow-users-groups-bypass-directory-traverse-task.adoc[Benutzern oder Gruppen das Umgehen der Verzeichnisdurchlaufprüfung erlauben]
* xref:disallow-users-groups-bypass-directory-traverse-task.adoc[Benutzern oder Gruppen das Umgehen der Verzeichnisdurchlaufprüfung untersagen]
* xref:configure-character-mappings-file-name-translation-task.adoc[Zeichenzuordnung für die Dateinamenübersetzung auf Volumes konfigurieren]
* xref:create-share-access-control-lists-task.html[Freigabe-Zugriffskontrolllisten erstellen]
* xref:secure-file-access-storage-level-access-guard-concept.html[Sicherer Dateizugriff mit Storage Level Access Guard]
* xref:assign-privileges-concept.html[Liste der unterstützten Berechtigungen]
* xref:manage-local-privileges.html[Berechtigungen für lokale oder Domänenbenutzer oder -gruppen hinzufügen]

