---
permalink: smb-admin/configure-grant-unix-group-permission-users-task.html 
sidebar: sidebar 
keywords: configure, grant, group, permission, access, file, directories, directory, incoming, cifs, ownder, configure the grant unix group permission to smb users 
summary: Sie können diese Option so konfigurieren, dass Gruppenberechtigungen für den Zugriff auf Dateien oder Verzeichnisse gewährt werden, selbst wenn der eingehende SMB-Benutzer nicht der Eigentümer der Datei ist. 
---
= Konfigurieren Sie die Berechtigung für UNIX-Gruppen für ONTAP SMB-Benutzer
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können diese Option so konfigurieren, dass Gruppenberechtigungen für den Zugriff auf Dateien oder Verzeichnisse gewährt werden, selbst wenn der eingehende SMB-Benutzer nicht der Eigentümer der Datei ist.

.Schritte
. Legen Sie die Berechtigungsebene auf erweitert fest: `set -privilege advanced`
. Konfigurieren Sie die Berechtigung für die UNIX-Gruppe gewähren wie folgt:
+
|===
| Wenn Sie möchten | Geben Sie den Befehl ein 


 a| 
Aktivieren Sie den Zugriff auf die Dateien oder Verzeichnisse, um Gruppenberechtigungen zu erhalten, selbst wenn der Benutzer nicht Eigentümer der Datei ist
 a| 
`vserver cifs options modify –grant-unix-group-perms-to-others true`



 a| 
Deaktivieren Sie den Zugriff auf die Dateien oder Verzeichnisse, um Gruppenberechtigungen zu erhalten, selbst wenn der Benutzer nicht der Eigentümer der Datei ist
 a| 
`vserver cifs options modify –grant-unix-group-perms-to-others false`

|===
. Stellen Sie sicher, dass die Option auf den gewünschten Wert eingestellt ist: `vserver cifs options show –fields grant-unix-group-perms-to-others`
. Kehren Sie zur Administrator-Berechtigungsebene zurück: `set -privilege admin`

