---
permalink: smb-admin/configure-branchcache-task.html 
sidebar: sidebar 
keywords: configure, branchcache, service, per-share, basis, smb, share, configure branchcache on the cifs server 
summary: Sie können BranchCache für einzelne Freigaben oder für alle SMB-Freigaben konfigurieren. Wenn Sie die Konfiguration pro Freigabe wählen, müssen Sie BranchCache auf jeder SMB-Freigabe aktivieren, die Caching bereitstellen soll. 
---
= Konfiguration von BranchCache auf ONTAP SMB-Servern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um BranchCache zu verwenden, müssen Sie Ihre Clients und, falls erforderlich, die gehosteten Cache-Server in Zweigstellen konfigurieren, in denen Inhalte zwischengespeichert werden. Sie können BranchCache für einzelne Freigaben oder für alle SMB-Freigaben konfigurieren. Wenn Sie die Konfiguration pro Freigabe wählen, müssen Sie BranchCache auf jeder SMB-Freigabe aktivieren, die Caching bereitstellen soll. Sie können BranchCache auch so einstellen, dass das Caching automatisch auf allen SMB-Freigaben aktiviert wird.

.Bevor Sie beginnen
Die folgenden Voraussetzungen müssen erfüllt sein, bevor BranchCache auf dem CIFS-Server für Ihre SVM konfiguriert wird:

* ONTAP muss auf allen Knoten im Cluster installiert sein.
* CIFS muss lizenziert und ein SMB-Server konfiguriert sein. Die SMB-Lizenz ist mit link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"] enthalten. Wenn ONTAP One nicht vorhanden ist und die Lizenz nicht installiert ist, sollte der Vertriebsmitarbeiter kontaktiert werden.
* IPv4- oder IPv6-Netzwerkkonnektivität muss konfiguriert werden.
* Für BranchCache 1 muss SMB 2.1 oder höher aktiviert sein.
* Für BranchCache 2 muss SMB 3.0 aktiviert sein und die Remote-Windows-Clients müssen BranchCache 2 unterstützen.


.Über diese Aufgabe
Sie können BranchCache auf SVMs konfigurieren.

* Es kann eine All-Shares-BranchCache Konfiguration erstellt werden, wenn Caching-Dienste für alle Inhalte angeboten werden sollen, die in allen SMB-Freigaben auf dem CIFS-Server enthalten sind.
* Eine BranchCache Konfiguration pro Freigabe kann erstellt werden, um Caching-Dienste für Inhalte bereitzustellen, die sich in ausgewählten SMB-Freigaben auf dem CIFS-Server befinden.


Die folgenden Parameter müssen bei der Konfiguration von BranchCache angegeben werden:

[cols="2,6"]
|===
| Erforderliche Parameter | Beschreibung 


 a| 
_SVM Name_
 a| 
BranchCache ist auf SVM-Basis konfiguriert. Es muss angegeben werden, auf welcher CIFS-aktivierten SVM der BranchCache-Dienst konfiguriert werden soll.



 a| 
_Pfad zum Hash-Store_
 a| 
BranchCache-Hashwerte werden in regulären Dateien auf dem SVM-Volume gespeichert. Der Pfad zu einem vorhandenen Verzeichnis, in dem ONTAP die Hashdaten speichern soll, muss angegeben werden. Der BranchCache-Hashpfad muss les- und schreibbar sein. Schreibgeschützte Pfade, wie beispielsweise Snapshot-Verzeichnisse, sind nicht zulässig. Hashdaten können auf einem Volume gespeichert werden, das bereits andere Daten enthält, oder es kann ein separates Volume zur Speicherung der Hashdaten erstellt werden.

Wenn es sich bei der SVM um eine SVM-Notfallwiederherstellungsquelle handelt, darf sich der Hash-Pfad nicht auf dem Root Volume befinden. Dies liegt daran, dass das Root Volume nicht auf das Notfallwiederherstellungsziel repliziert wird.

Der Hash-Pfad kann Leerzeichen und alle gültigen Dateinamenzeichen enthalten.

|===
Sie können optional die folgenden Parameter angeben:

[cols="2,6"]
|===
| Optionale Parameter | Beschreibung 


 a| 
Unterstützte Versionen
 a| 
ONTAP unterstützt BranchCache 1 und 2. Es ist möglich, Version 1, Version 2 oder beide Versionen zu aktivieren. Standardmäßig sind beide Versionen aktiviert.



 a| 
_Maximale Größe des Hash-Speichers_
 a| 
Sie können die Größe des Hash-Datenspeichers festlegen. Wenn die Hash-Daten diesen Wert überschreiten, löscht ONTAP ältere Hashes, um Platz für neuere Hashes zu schaffen. Die Standardgröße für den Hash-Speicher beträgt 1 GB. BranchCache arbeitet effizienter, wenn Hashes nicht in übermäßigem Maße verworfen werden. Wenn festgestellt wird, dass Hashes häufig verworfen werden, weil der Hash-Speicher voll ist, kann die Größe des Hash-Speichers durch Anpassen der BranchCache-Konfiguration erhöht werden.



 a| 
_Serverschlüssel_
 a| 
Sie können einen Serverschlüssel festlegen, den der BranchCache-Dienst verwendet, um zu verhindern, dass Clients sich als der BranchCache-Server ausgeben. Wenn Sie keinen Serverschlüssel angeben, wird beim Erstellen der BranchCache-Konfiguration ein zufälliger generiert. Sie können den Serverschlüssel auf einen bestimmten Wert setzen, sodass, falls mehrere Server BranchCache-Daten für dieselben Dateien bereitstellen, Clients Hashes von jedem Server mit demselben Serverschlüssel verwenden können. Enthält der Serverschlüssel Leerzeichen, muss er in Anführungszeichen gesetzt werden.



 a| 
_Betriebsart_
 a| 
Standardmäßig ist BranchCache für jede Freigabe einzeln aktiviert.

* Um eine BranchCache Konfiguration zu erstellen, bei der BranchCache pro Freigabe aktiviert wird, kann entweder dieser optionale Parameter nicht angegeben werden oder  `per-share` angegeben werden.
* Um BranchCache auf allen Freigaben automatisch zu aktivieren, muss der Betriebsmodus auf  `all-shares` gesetzt werden.


|===
.Schritte
. SMB 2.1 und 3.0 nach Bedarf aktivieren:
+
.. Stellen Sie die Berechtigungsstufe auf „Erweitert“ ein:
+
[source, cli]
----
set -privilege advanced
----
.. Überprüfen Sie die konfigurierten SVM-SMB-Einstellungen, um festzustellen, ob alle benötigten SMB-Versionen aktiviert sind:
+
[source, cli]
----
vserver cifs options show -vserver <SVM_name>
----
.. Aktivieren Sie gegebenenfalls SMB 2.1:
+
[source, cli]
----
vserver cifs options modify -vserver <SVM_name> -smb2-enabled true
----
+
Der Befehl aktiviert sowohl SMB 2.0 als auch SMB 2.1.

.. Aktivieren Sie gegebenenfalls SMB 3.0:
+
[source, cli]
----
vserver cifs options modify -vserver <SVM_name> -smb3-enabled true
----
.. Zurück zur Administrator-Privilegstufe:
+
[source, cli]
----
set -privilege admin
----


. Konfigurieren BranchCache:
+
[source, cli]
----
vserver cifs branchcache create -vserver <SVM_name> -hash-store-path <path> [-hash-store-max-size {integer[KB|MB|GB|TB|PB]}] [-versions {v1-enable|v2-enable|enable-all}] [-server-key <text>] -operating-mode {per-share|all-shares}
----
+
Der angegebene Hash-Speicherpfad muss existieren und sich auf einem vom SVM verwalteten Volume befinden. Der Pfad muss außerdem auf einem beschreibbaren Volume liegen. Der Befehl schlägt fehl, wenn der Pfad schreibgeschützt ist oder nicht existiert.

+
Wenn Sie denselben Serverschlüssel für zusätzliche SVM BranchCache Konfigurationen verwenden möchten, sollte der eingegebene Wert für den Serverschlüssel festgehalten werden. Der Serverschlüssel wird nicht angezeigt, wenn Informationen zur BranchCache Konfiguration angezeigt werden.

. Überprüfen Sie, ob die BranchCache-Konfiguration korrekt ist:
+
[source, cli]
----
vserver cifs branchcache show -vserver <SVM_name>
----


.Beispiele
Die folgenden Befehle überprüfen, ob sowohl SMB 2.1 als auch 3.0 aktiviert sind, und konfigurieren BranchCache, um das Caching auf allen SMB-Freigaben auf SVM vs1 automatisch zu aktivieren:

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options show -vserver vs1 -fields smb2-enabled,smb3-enabled
vserver smb2-enabled smb3-enabled
------- ------------ ------------
vs1     true         true


cluster1::*> set -privilege admin

cluster1::> vserver cifs branchcache create -vserver vs1 -hash-store-path /hash_data -hash-store-max-size 20GB -versions enable-all -server-key "my server key" -operating-mode all-shares

cluster1::> vserver cifs branchcache show -vserver vs1

                                 Vserver: vs1
          Supported BranchCache Versions: enable_all
                      Path to Hash Store: /hash_data
          Maximum Size of the Hash Store: 20GB
Encryption Key Used to Secure the Hashes: -
        CIFS BranchCache Operating Modes: all_shares
----
Die folgenden Befehle überprüfen, ob sowohl SMB 2.1 als auch 3.0 aktiviert sind, konfigurieren BranchCache, um die Zwischenspeicherung pro Freigabe auf SVM vs1 zu ermöglichen, und überprüfen die BranchCache-Konfiguration:

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options show -vserver vs1 -fields smb2-enabled,smb3-enabled
vserver smb2-enabled smb3-enabled
------- ------------ ------------
vs1     true         true

cluster1::*> set -privilege admin

cluster1::> vserver cifs branchcache create -vserver vs1 -hash-store-path /hash_data -hash-store-max-size 20GB -versions enable-all -server-key "my server key"

cluster1::> vserver cifs branchcache show -vserver vs1

                                 Vserver: vs1
          Supported BranchCache Versions: enable_all
                      Path to Hash Store: /hash_data
          Maximum Size of the Hash Store: 20GB
Encryption Key Used to Secure the Hashes: -
        CIFS BranchCache Operating Modes: per_share
----
.Was kommt als Nächstes?
Nach der Konfiguration von BranchCache auf dem SMB-Server ist BranchCache auf den Clientcomputern und optional auf den Caching-Servern in der Außenstelle zu installieren und zu konfigurieren. Microsoft stellt Anweisungen für die Konfiguration von BranchCache in der Außenstelle bereit.

Anweisungen zur Konfiguration von Clients für Zweigstellen und optional von Caching-Servern zur Nutzung von BranchCache sind auf der Microsoft BranchCache Web Site verfügbar.

http://technet.microsoft.com/EN-US/NETWORK/DD425028["Microsoft BranchCache Docs: Was ist neu?"^]

.Verwandte Informationen
* xref:branchcache-version-support-concept.html[Informationen zur Unterstützung von BranchCache-Versionen]
* xref:create-branchcache-enabled-share-task.adoc[Eine SMB-Freigabe mit aktiviertem BranchCache erstellen]
* xref:enable-branchcache-existing-share-task.adoc[BranchCache auf bestehenden Freigaben aktivieren]
* xref:modify-branchcache-config-task.html[Konfigurationen von BranchCache auf Freigaben ändern]
* xref:disable-branchcache-shares-concept.html[Informationen zum Deaktivieren von BranchCache auf Freigaben]
* xref:delete-branchcache-config-task.html[Die BranchCache Konfiguration auf Freigaben löschen]

