---
permalink: smb-admin/configure-bypass-traverse-checking-concept.html 
sidebar: sidebar 
keywords: bypass, traverse, user, privilege, permission, directory, allow, check, configure, storage, virtual, machine, svm, configure bypass traverse checking 
summary: 'Bypass Traverse Checking ist ein Benutzerrecht (auch als Berechtigung bekannt), das bestimmt, ob ein Benutzer alle Verzeichnisse im Pfad zu einer Datei durchlaufen kann, selbst wenn der Benutzer keine Berechtigungen auf dem durchlaufenen Verzeichnis hat. Sie sollten wissen, was passiert, wenn Umgehungsüberprüfung zuzulassen oder nicht zulässt und wie eine Umgehungsüberprüfung für Benutzer auf Storage Virtual Machines (SVMs) konfiguriert wird.' 
---
= Erfahren Sie mehr über die Konfiguration der ONTAP SMB-Bypass-Traverse-Prüfung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bypass Traverse Checking ist ein Benutzerrecht (auch bekannt als _Privilege_), das bestimmt, ob ein Benutzer alle Verzeichnisse im Pfad zu einer Datei durchlaufen kann, auch wenn der Benutzer keine Berechtigungen auf dem durchlaufenen Verzeichnis hat. Sie sollten wissen, was passiert, wenn Umgehungsüberprüfung zuzulassen oder nicht zulässt und wie eine Umgehungsüberprüfung für Benutzer auf Storage Virtual Machines (SVMs) konfiguriert wird.



== Was passiert, wenn die Überprüfung der Bypass-Traverse erlaubt oder nicht erlaubt wird

* Wenn ein Benutzer versucht, auf eine Datei zuzugreifen, überprüft ONTAP nicht die Traverse-Berechtigung für die Zwischenverzeichnisse, wenn er bestimmt, ob er Zugriff auf die Datei gewährt oder verweigert.
* Wenn nicht zulässig, überprüft ONTAP die Berechtigung zum Traverse (Ausführen) für alle Verzeichnisse im Pfad zur Datei.
+
Wenn eines der Zwischenverzeichnisse nicht über „`X`“ (Traverse-Berechtigung) verfügt, verweigert ONTAP den Zugriff auf die Datei.





== Konfigurieren Sie die Überprüfung der Bypass-Traverse

Sie können die Bypass-Traverse-Überprüfung mithilfe der ONTAP-CLI oder durch Konfiguration der Active Directory-Gruppenrichtlinien mit diesem Benutzerrecht konfigurieren.

Die `SeChangeNotifyPrivilege` Berechtigung steuert, ob Benutzer die Durchgangsprüfung umgehen dürfen.

* Wenn Sie sie lokalen SMB-Benutzern oder -Gruppen in der SVM oder zu Domänenbenutzern oder -Gruppen hinzufügen, ist eine Überbrückung der Überbrückung möglich.
* Wenn Sie sie von lokalen SMB-Benutzern oder -Gruppen auf der SVM oder von Domain-Benutzern oder -Gruppen entfernen, ist die Bypass-Traverse-Überprüfung nicht möglich.


Standardmäßig haben die folgenden BUILTIN-Gruppen auf der SVM das Recht, die Traverse-Kontrolle zu umgehen:

* `BUILTIN\Administrators`
* `BUILTIN\Power Users`
* `BUILTIN\Backup Operators`
* `BUILTIN\Users`
* `Everyone`


Wenn Sie den Mitgliedern einer dieser Gruppen nicht erlauben möchten, die Traverse-Kontrolle zu umgehen, müssen Sie diese Berechtigung aus der Gruppe entfernen.

Bei der Konfiguration der Bypass-Traverse-Überprüfung für lokale SMB-Benutzer und -Gruppen auf der SVM müssen Sie Folgendes beachten:

* Wenn Sie Mitgliedern einer benutzerdefinierten lokalen oder Domänengruppe erlauben möchten, die Durchgangsprüfung `SeChangeNotifyPrivilege` zu umgehen, müssen Sie dieser Gruppe die Berechtigung hinzufügen.
* Wenn Sie einem einzelnen lokalen oder Domänenbenutzer erlauben möchten, die Traversenprüfung zu umgehen, und dieser Benutzer nicht Mitglied einer Gruppe mit dieser Berechtigung ist, können Sie `SeChangeNotifyPrivilege` diesem Benutzerkonto die Berechtigung hinzufügen.
* Sie können die Umgehungsüberprüfung für lokale oder Domänenbenutzer oder -Gruppen deaktivieren, indem Sie die `SeChangeNotifyPrivilege` Berechtigung jederzeit entfernen.
+
[NOTE]
====
Um die Prüfung von Überbrückungsüberprüfungen für bestimmte lokale oder Domänenbenutzer oder -Gruppen `SeChangeNotifyPrivilege` `Everyone` zu deaktivieren, müssen Sie die Berechtigung auch aus der Gruppe entfernen.

====


.Verwandte Informationen
xref:allow-users-groups-bypass-directory-traverse-task.adoc[Benutzern oder Gruppen erlauben, die Überprüfung der Verzeichnisdurchgang zu umgehen]

xref:disallow-users-groups-bypass-directory-traverse-task.adoc[Benutzer oder Gruppen davon ablassen, die Überprüfung der Verzeichnisdurchgang zu umgehen]

xref:configure-character-mappings-file-name-translation-task.adoc[Konfigurieren Sie die Zeichenzuordnung für die Übersetzung von SMB-Dateinamen auf Volumes]

xref:create-share-access-control-lists-task.html[Erstellen Sie SMB-Zugriffssteuerungslisten]

xref:secure-file-access-storage-level-access-guard-concept.html[Sicherer Dateizugriff über Storage-Level Access Guard]

xref:list-supported-privileges-reference.adoc[Liste der unterstützten Berechtigungen]

xref:add-privileges-local-domain-users-groups-task.html[Fügen Sie den lokalen oder Domänenbenutzern oder -Gruppen Berechtigungen hinzu]
