---
permalink: smb-admin/configure-guest-unix-user-task.html 
sidebar: sidebar 
keywords: configuring, configure, guest, unix, user, untrusted, domain, map, connect, cifs, server, configure the guest unix user 
summary: 'Beim Konfigurieren der UNIX-Gast-Option werden Benutzer, die sich von nicht vertrauenswürdigen Domänen anmelden, dem UNIX-Benutzer des Gast zugeordnet und können eine Verbindung mit dem CIFS-Server herstellen. Wenn die Authentifizierung von Benutzern aus nicht vertrauenswürdigen Domänen fehlschlägt, sollten Sie den UNIX-Gastbenutzer nicht konfigurieren. Standardmäßig dürfen Benutzer von nicht vertrauenswürdigen Domänen keine Verbindung zum CIFS-Server herstellen (das UNIX-Gastkonto ist nicht konfiguriert).' 
---
= Konfigurieren Sie den UNIX-Gastbenutzer
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Beim Konfigurieren der UNIX-Gast-Option werden Benutzer, die sich von nicht vertrauenswürdigen Domänen anmelden, dem UNIX-Benutzer des Gast zugeordnet und können eine Verbindung mit dem CIFS-Server herstellen. Wenn die Authentifizierung von Benutzern aus nicht vertrauenswürdigen Domänen fehlschlägt, sollten Sie den UNIX-Gastbenutzer nicht konfigurieren. Standardmäßig dürfen Benutzer von nicht vertrauenswürdigen Domänen keine Verbindung zum CIFS-Server herstellen (das UNIX-Gastkonto ist nicht konfiguriert).

.Über diese Aufgabe
Bei der Konfiguration des UNIX-Gastkontos sollten Sie Folgendes beachten:

* Wenn der CIFS-Server den Benutzer nicht für einen Domain-Controller für die Home-Domäne oder eine vertrauenswürdige Domäne oder die lokale Datenbank authentifizieren kann und diese Option aktiviert ist, wird der CIFS-Server den Benutzer als Gastbenutzer und ordnet den Benutzer dem angegebenen UNIX-Benutzer zu.
* Wenn diese Option auf einen leeren String gesetzt ist, ist der UNIX-Gastbenutzer deaktiviert.
* Sie müssen einen UNIX-Benutzer erstellen, der als UNIX-Gastbenutzer in einer der SVM-Namensdienstdatenbanken (Storage Virtual Machine) verwendet werden soll.
* Ein als Gastbenutzer angemeldeter Benutzer ist automatisch Mitglied der BUILTIN\Gastgruppe auf dem CIFS-Server.
* Die Option 'homedirs-public' gilt nur für authentifizierte Benutzer. Ein als Gastbenutzer angemeldeter Benutzer verfügt nicht über ein Home-Verzeichnis und kann nicht auf die Home-Verzeichnisse anderer Benutzer zugreifen.


.Schritte
. Führen Sie eine der folgenden Aktionen aus:
+
|===
| Ihr Ziel ist | Eingeben... 


 a| 
Konfigurieren Sie den UNIX-Gastbenutzer
 a| 
`vserver cifs options modify -guest-unix-user _unix_name_`



 a| 
Deaktivieren Sie den UNIX-Gastbenutzer
 a| 
`vserver cifs options modify -guest-unix-user ""`

|===
+
`vserver cifs options modify -guest-unix-user pcuser`

. Überprüfen Sie, ob der UNIX Gast-Benutzer richtig konfiguriert ist: `vserver cifs options show -vserver _vserver_name_`
+
Im folgenden Beispiel sind sowohl der UNIX-Standardbenutzer als auch der Gast-UNIX-Benutzer auf SVM vs1 so konfiguriert, dass der UNIX-Benutzer „`pcuser`“ verwendet wird:

+
`vserver cifs options show -vserver vs1`

+
[listing]
----

Vserver: vs1

  Client Session Timeout : 900
  Default Unix Group     : -
  Default Unix User      : pcuser
  Guest Unix User        : pcuser
  Read Grants Exec       : disabled
  Read Only Delete       : disabled
  WINS Servers           : -
----

