---
permalink: smb-admin/configure-guest-unix-user-task.html 
sidebar: sidebar 
keywords: configuring, configure, guest, unix, user, untrusted, domain, map, connect, cifs, server, configure the guest unix user 
summary: Die Konfiguration der Option „Gast-UNIX-Benutzer“ bewirkt, dass Benutzer, die sich von nicht vertrauenswürdigen Domänen anmelden, diesem Gast-UNIX-Benutzer zugeordnet werden und eine Verbindung zum CIFS-Server herstellen können. Alternativ kann, wenn die Authentifizierung von Benutzern aus nicht vertrauenswürdigen Domänen fehlschlagen soll, der Gast-UNIX-Benutzer nicht konfiguriert werden. Standardmäßig ist es nicht erlaubt, dass Benutzer aus nicht vertrauenswürdigen Domänen eine Verbindung zum CIFS-Server herstellen. 
---
= Den Gast-ONTAP SMB UNIX-Benutzer konfigurieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Konfiguration der Option „Gast-UNIX-Benutzer“ bewirkt, dass Benutzer, die sich von nicht vertrauenswürdigen Domänen anmelden, diesem Gast-UNIX-Benutzer zugeordnet werden und eine Verbindung zum CIFS-Server herstellen können. Alternativ kann, wenn die Authentifizierung von Benutzern aus nicht vertrauenswürdigen Domänen fehlschlagen soll, der Gast-UNIX-Benutzer nicht konfiguriert werden. Standardmäßig ist es nicht erlaubt, dass Benutzer aus nicht vertrauenswürdigen Domänen eine Verbindung zum CIFS-Server herstellen (das Gast-UNIX-Konto ist nicht konfiguriert).

.Über diese Aufgabe
Bei der Konfiguration des Gast-UNIX-Kontos ist Folgendes zu beachten:

* Kann der CIFS-Server den Benutzer nicht gegenüber einem Domänencontroller der Home-Domain, einer vertrauenswürdigen Domain oder der lokalen Datenbank authentifizieren und ist diese Option aktiviert, betrachtet der CIFS-Server den Benutzer als Gastbenutzer und ordnet ihn dem angegebenen UNIX-Benutzer zu.
* Wenn diese Option auf eine leere Zeichenkette gesetzt ist, ist der Gast-UNIX-Benutzer deaktiviert.
* Es ist erforderlich, einen UNIX-Benutzer zu erstellen, der als Gast-UNIX-Benutzer in einer der Name-Service-Datenbanken der Storage Virtual Machine (SVM) verwendet wird.
* Ein als Gastbenutzer angemeldeter Benutzer ist automatisch Mitglied der Gruppe BUILTIN\guests auf dem CIFS-Server.
* Die Option „homedirs-public“ gilt nur für authentifizierte Benutzer. Ein als Gast angemeldeter Benutzer besitzt kein Home Directory und kann nicht auf die Home Directory-Pfade anderer Benutzer zugreifen.


.Schritte
. Führen Sie eine der folgenden Aktionen aus:
+
|===
| Wenn Sie möchten... | Eingeben... 


 a| 
Den Gast-UNIX-Benutzer konfigurieren
 a| 
`vserver cifs options modify -guest-unix-user _unix_name_`



 a| 
Den Gast-UNIX-Benutzer deaktivieren
 a| 
`vserver cifs options modify -guest-unix-user ""`

|===
+
`vserver cifs options modify -guest-unix-user pcuser`

. Es sollte überprüft werden, ob der Gast-UNIX-Benutzer korrekt konfiguriert ist: `vserver cifs options show -vserver _vserver_name_`
+
Im folgenden Beispiel sind sowohl der Standard-UNIX-Benutzer als auch der Gast-UNIX-Benutzer auf SVM vs1 so konfiguriert, dass sie den UNIX-Benutzer "`pcuser`" verwenden:

+
`vserver cifs options show -vserver vs1`

+
[listing]
----

Vserver: vs1

  Client Session Timeout : 900
  Default Unix Group     : -
  Default Unix User      : pcuser
  Guest Unix User        : pcuser
  Read Grants Exec       : disabled
  Read Only Delete       : disabled
  WINS Servers           : -
----

