---
permalink: smb-admin/configure-roaming-profiles-task.html 
sidebar: sidebar 
keywords: automatic, user, profile, available, log, computer, network, configure, roam, active, directory, mmc, snap-in, configuring, roam, windows, server, administration, center, configure roam profile 
summary: Wenn Sie das Benutzerprofil automatisch verfügbar machen möchten, wenn sich dieser Benutzer an einem beliebigen Computer im Netzwerk anmeldet, können Sie Roaming-Profile über das Active Directory-Benutzer- und Computer-MMC-Snap-in konfigurieren. Wenn Sie Roaming-Profile auf Windows Server konfigurieren, können Sie das Active Directory Administration Center verwenden. 
---
= Konfiguration von Roaming-Profilen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie das Benutzerprofil automatisch verfügbar machen möchten, wenn sich dieser Benutzer an einem beliebigen Computer im Netzwerk anmeldet, können Sie Roaming-Profile über das Active Directory-Benutzer- und Computer-MMC-Snap-in konfigurieren. Wenn Sie Roaming-Profile auf Windows Server konfigurieren, können Sie das Active Directory Administration Center verwenden.

.Schritte
. Öffnen Sie auf dem Windows-Server die MMC für Active Directory-Benutzer und -Computer (oder das Active Directory-Verwaltungscenter auf Windows-Servern).
. Suchen Sie den Benutzer, für den Sie ein Roaming-Profil konfigurieren möchten.
. Klicken Sie mit der rechten Maustaste auf den Benutzer und klicken Sie auf *Eigenschaften*.
. Geben Sie auf der Registerkarte *Profil* den Profilpfad zur Freigabe ein, in der Sie das Roaming-Profil des Benutzers speichern möchten, gefolgt von `%username%`.
+
Ein Profilpfad kann z. B. die folgenden sein: `\\vs1.example.com\profiles\%username%`. Wenn sich ein Benutzer zum ersten Mal anmeldet, `%username%` Wird durch den Benutzernamen ersetzt.

+
[NOTE]
====
Im Pfad `\\vs1.example.com\profiles\%username%`, `profiles` Ist der Share-Name eines Shares auf Storage Virtual Machine (SVM) vs1 mit vollständigen Kontrollrechten für alle.

====
. Klicken Sie auf *OK*.

