---
permalink: smb-admin/configure-apply-audit-policies-ntfs-files-folders-task.html 
sidebar: sidebar 
keywords: perform, apply, policies, policy, ntfs, file, folder, ontap, cli, security, descriptor, sacl, descriptor, create, storage, virtual, machine, svm, configure and apply audit policies to ntfs files and folders using the cli 
summary: 'Sie müssen mehrere Schritte durchführen, um Überwachungsrichtlinien auf NTFS-Dateien und -Ordner anzuwenden, wenn Sie die ONTAP-CLI verwenden. Zunächst erstellen Sie einen NTFS-Sicherheitsdeskriptor und fügen SACLs zum Sicherheitsdeskriptor hinzu. Als nächstes erstellen Sie eine Sicherheitsrichtlinie und fügen Sie Richtlinienaufgaben hinzu. Anschließend wenden Sie die Sicherheitsrichtlinie auf eine Storage Virtual Machine (SVM) an.' 
---
= Konfigurieren und Anwenden von Audit-Richtlinien auf NTFS-Dateien und -Ordner mithilfe der CLI-Übersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen mehrere Schritte durchführen, um Überwachungsrichtlinien auf NTFS-Dateien und -Ordner anzuwenden, wenn Sie die ONTAP-CLI verwenden. Zunächst erstellen Sie einen NTFS-Sicherheitsdeskriptor und fügen SACLs zum Sicherheitsdeskriptor hinzu. Als nächstes erstellen Sie eine Sicherheitsrichtlinie und fügen Sie Richtlinienaufgaben hinzu. Anschließend wenden Sie die Sicherheitsrichtlinie auf eine Storage Virtual Machine (SVM) an.

Nachdem Sie die Sicherheitsrichtlinie angewendet haben, können Sie den Job der Sicherheitsrichtlinie überwachen und anschließend die Einstellungen für die angewendete Überwachungsrichtlinie überprüfen.


NOTE: Wenn eine Audit-Richtlinie und die zugehörigen SACLs angewendet werden, werden alle vorhandenen DACLs überschrieben. Sie sollten vorhandene Sicherheitsrichtlinien überprüfen, bevor Sie neue erstellen und anwenden.

xref:secure-file-access-storage-level-access-guard-concept.adoc[Dateizugriff wird mithilfe von Storage-Level Access Guard gesichert]

xref:limits-when-cli-set-file-folder-security-concept.adoc[Einschränkungen bei der Verwendung der CLI zum Festlegen der Datei- und Ordnersicherheit]

xref:security-descriptors-apply-file-folder-security-concept.adoc[Anwenden von Sicherheitsdeskriptoren zur Anwendung der Datei- und Ordnersicherheit]

link:../nas-audit/index.html["SMB- und NFS-Auditing und Sicherheits-Tracing"]

xref:create-ntfs-security-descriptor-file-task.adoc[Konfigurieren und Anwenden der Dateisicherheit auf NTFS-Dateien und Ordnern mithilfe der CLI]
