---
permalink: smb-admin/configure-folder-redirection-task.html 
sidebar: sidebar 
keywords: configure, folder, redirection, windows, properties, method, assistance, svm, administrator, configure folder redirection 
summary: Die Ordnerumleitung kann über das Windows-Eigenschaftenfenster konfiguriert werden. Der Vorteil dieser Methode besteht darin, dass der Windows-Benutzer die Ordnerumleitung ohne Unterstützung des SVM-Administrators konfigurieren kann. 
---
= ONTAP SMB-Ordnerumleitung mithilfe der Windows-Eigenschaften konfigurieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Ordnerumleitung kann über das Windows-Eigenschaftenfenster konfiguriert werden. Der Vorteil dieser Methode besteht darin, dass der Windows-Benutzer die Ordnerumleitung ohne Unterstützung des SVM-Administrators konfigurieren kann.

.Schritte
. Im Windows Explorer mit der rechten Maustaste auf den Ordner klicken, der auf eine Netzwerkfreigabe umgeleitet werden soll.
. *Eigenschaften* auswählen.
+
Die Eigenschaften der von Ihnen ausgewählten Freigabe werden angezeigt.

. Im Tab *Verknüpfung* auf *Ziel* klicken und den Pfad zum Netzwerkstandort angeben, zu dem der ausgewählte Ordner umgeleitet werden soll.
+
Wenn beispielsweise ein Ordner in den  `data` Ordner in einem Home-Verzeichnis umgeleitet werden soll, das auf  `Q:\` zugeordnet ist, ist  `Q:\data` als Ziel anzugeben.

. Klicken Sie auf *OK*.
+
Weitere Informationen zur Konfiguration von Offline-Ordnern bietet die Microsoft TechNet Library.



.Verwandte Informationen
http://technet.microsoft.com/en-us/library/["Microsoft TechNet Bibliothek: technet.microsoft.com/en-us/library/"]
