---
permalink: smb-admin/configure-branchcache-enabled-shares-concept.html 
sidebar: sidebar 
keywords: configure, branchcache, smb server, office, enable, smb, share, content, client, configure branchache-enabled smb shares 
summary: Nachdem BranchCache auf dem SMB-Server und in der Zweigstelle konfiguriert wurde, kann BranchCache auf SMB-Freigaben aktiviert werden, die Inhalte enthalten, die Clients in den Zweigstellen zwischenspeichern dürfen. 
---
= Informationen zur Konfiguration von BranchCache-fähigen ONTAP SMB-Freigaben
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem BranchCache auf dem SMB-Server und in der Zweigstelle konfiguriert wurde, kann BranchCache auf SMB-Freigaben aktiviert werden, die Inhalte enthalten, die Clients in den Zweigstellen zwischenspeichern dürfen.

BranchCache-Caching kann für alle SMB-Freigaben auf dem SMB-Server oder für einzelne Freigaben aktiviert werden.

* Wenn BranchCache für einzelne Freigaben aktiviert wird, kann BranchCache entweder beim Erstellen der Freigabe oder durch Ändern bestehender Freigaben aktiviert werden.
+
Wenn das Caching für eine bestehende SMB-Freigabe aktiviert wird, beginnt ONTAP mit der Berechnung von Hashwerten und dem Senden von Metadaten an Clients, die Inhalte anfordern, sobald BranchCache auf dieser Freigabe aktiviert wird.

* Clients, die bereits eine SMB-Verbindung zu einer Freigabe haben, erhalten keine BranchCache-Unterstützung, wenn BranchCache anschließend für diese Freigabe aktiviert wird.
+
ONTAP signalisiert BranchCache Unterstützung für eine Freigabe beim Einrichten der SMB-Sitzung. Clients, die bereits Sitzungen aufgebaut haben, wenn BranchCache aktiviert wird, müssen die Verbindung trennen und erneut herstellen, um zwischengespeicherte Inhalte für diese Freigabe nutzen zu können.



[NOTE]
====
Wenn BranchCache auf einer SMB-Freigabe anschließend deaktiviert wird, stellt ONTAP das Senden von Metadaten an den anfragenden Client ein. Ein Client, der Daten benötigt, ruft diese direkt vom Content-Server (SMB-Server) ab.

====