---
permalink: smb-admin/configure-default-unix-user-task.html 
sidebar: sidebar 
keywords: configure, unix, user, map, fail, individual, windows, authentication, non-mapped, configure the default unix user 
summary: Sie können den standardmäßigen UNIX-Benutzer so konfigurieren, dass er verwendet wird, wenn alle anderen Zuordnungsversuche für einen Benutzer fehlschlagen oder wenn Sie nicht einzelne Benutzer zwischen UNIX und Windows zuordnen möchten. Wenn die Authentifizierung von nicht zugeordneten Benutzern fehlschlägt, sollten Sie den standardmäßigen UNIX-Benutzer nicht konfigurieren. 
---
= Konfigurieren Sie den standardmäßigen ONTAP SMB UNIX-Benutzer
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den standardmäßigen UNIX-Benutzer so konfigurieren, dass er verwendet wird, wenn alle anderen Zuordnungsversuche für einen Benutzer fehlschlagen oder wenn Sie nicht einzelne Benutzer zwischen UNIX und Windows zuordnen möchten. Wenn die Authentifizierung von nicht zugeordneten Benutzern fehlschlägt, sollten Sie den standardmäßigen UNIX-Benutzer nicht konfigurieren.

.Über diese Aufgabe
Standardmäßig lautet der Name des UNIX-Standardbenutzers „`pcuser`“, was bedeutet, dass standardmäßig die Benutzerzuordnung für den standardmäßigen UNIX-Benutzer aktiviert ist. Sie können einen anderen Namen angeben, der als Standard-UNIX-Benutzer verwendet werden soll. Der von Ihnen angegebene Name muss in den für die Storage Virtual Machine (SVM) konfigurierten Servicedatenbanken vorhanden sein. Wenn diese Option auf einen leeren String gesetzt ist, kann niemand als UNIX-Standardbenutzer auf den CIFS-Server zugreifen. Das heißt, jeder Benutzer muss ein Konto in der Kennwortdatenbank haben, bevor er auf den CIFS-Server zugreifen kann.

Damit ein Benutzer über das standardmäßige UNIX-Benutzerkonto eine Verbindung zum CIFS-Server herstellen kann, muss der Benutzer die folgenden Voraussetzungen erfüllen:

* Der Benutzer ist authentifiziert.
* Der Benutzer befindet sich in der lokalen Windows Benutzerdatenbank des CIFS-Servers, in der Home-Domäne des CIFS-Servers oder in einer vertrauenswürdigen Domäne (wenn die Suche nach der Zuordnung von multidomänen Namen auf dem CIFS-Server aktiviert ist).
* Der Benutzername ist nicht explizit einem Null-String zugeordnet.


.Schritte
. Konfigurieren Sie den UNIX-Standardbenutzer:
+
|===
| Wenn Sie wollen, ... | Geben Sie Ein ... 


 a| 
Verwenden Sie den UNIX-Standardbenutzer „`pcuser`“.
 a| 
`vserver cifs options modify -default-unix-user pcuser`



 a| 
Verwenden Sie ein anderes UNIX-Benutzerkonto als Standardbenutzer
 a| 
`vserver cifs options modify -default-unix-user _user_name_`



 a| 
Deaktivieren Sie den UNIX-Standardbenutzer
 a| 
`vserver cifs options modify -default-unix-user ""`

|===
+
`vserver cifs options modify -default-unix-user pcuser`

. Überprüfen Sie, ob der UNIX-Standardbenutzer richtig konfiguriert ist: `vserver cifs options show -vserver _vserver_name_`
+
Im folgenden Beispiel sind sowohl der UNIX-Standardbenutzer als auch der Gast-UNIX-Benutzer auf SVM vs1 so konfiguriert, dass der UNIX-Benutzer „`pcuser`“ verwendet wird:

+
`vserver cifs options show -vserver vs1`

+
[listing]
----

Vserver: vs1

  Client Session Timeout : 900
  Default Unix Group     : -
  Default Unix User      : pcuser
  Guest Unix User        : pcuser
  Read Grants Exec       : disabled
  Read Only Delete       : disabled
  WINS Servers           : -
----

