---
permalink: smb-admin/configure-offline-files-computer-management-mmc-task.html 
sidebar: sidebar 
keywords: permit, user, cache, file, local, offline, configure, computer management, mmc, microsoft, management, console, configure offline files support on smb shares by using the computer management mmc 
summary: 'Wenn Sie Benutzern gestatten möchten, Dateien lokal für die Offline-Verwendung zwischenzuspeichern, können Sie die Unterstützung von Offline-Dateien mithilfe des Computer Management MMC (Microsoft Management Console) konfigurieren.' 
---
= Konfigurieren Sie die Unterstützung von Offline-Dateien für SMB-Freigaben mithilfe des Computer Management MMC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie Benutzern gestatten möchten, Dateien lokal für die Offline-Verwendung zwischenzuspeichern, können Sie die Unterstützung von Offline-Dateien mithilfe des Computer Management MMC (Microsoft Management Console) konfigurieren.

.Schritte
. Um den MMC auf Ihrem Windows-Server zu öffnen, klicken Sie im Windows Explorer mit der rechten Maustaste auf das Symbol für den lokalen Computer und wählen Sie dann *Verwalten* aus.
. Wählen Sie im linken Bereich die Option *Computerverwaltung* aus.
. Wählen Sie *Aktion* > *Verbindung zu einem anderen Computer*.
+
Das Dialogfeld „Computer auswählen“ wird angezeigt.

. Geben Sie den Namen des CIFS-Servers ein, oder klicken Sie auf *Durchsuchen*, um den CIFS-Server zu finden.
+
Wenn der Name des CIFS-Servers mit dem Hostnamen der Storage Virtual Machine (SVM) identisch ist, geben Sie den SVM-Namen ein. Wenn sich der CIFS-Servername vom SVM-Hostnamen unterscheidet, geben Sie den Namen des CIFS-Servers ein.

. Klicken Sie auf *OK*.
. Klicken Sie in der Konsolenstruktur auf *Systemwerkzeuge* > *freigegebene Ordner*.
. Klicken Sie Auf *Shares*.
. Klicken Sie im Ergebnisbereich mit der rechten Maustaste auf die Freigabe.
. Klicken Sie Auf *Eigenschaften*.
+
Die Eigenschaften für die ausgewählte Freigabe werden angezeigt.

. Klicken Sie auf der Registerkarte *Allgemein* auf *Offline-Einstellungen*.
+
Das Dialogfeld Offline-Einstellungen wird angezeigt.

. Konfigurieren Sie die Offline-Verfügbarkeitsoptionen entsprechend.
. Klicken Sie auf *OK*.

