---
permalink: smb-admin/configure-grant-unix-group-permission-users-task.html 
sidebar: sidebar 
keywords: configure, grant, group, permission, access, file, directories, directory, incoming, cifs, ownder, configure the grant unix group permission to smb users 
summary: Diese Option kann so konfiguriert werden, dass Gruppenberechtigungen für den Zugriff auf Dateien oder Verzeichnisse gewährt werden, selbst wenn der eingehende SMB-Benutzer nicht der Eigentümer der Datei ist. 
---
= Die UNIX-Gruppenberechtigung für ONTAP SMB-Benutzer konfigurieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese Option kann so konfiguriert werden, dass Gruppenberechtigungen für den Zugriff auf Dateien oder Verzeichnisse gewährt werden, selbst wenn der eingehende SMB-Benutzer nicht der Eigentümer der Datei ist.

.Schritte
. Die Berechtigungsstufe wird auf „Erweitert“ gesetzt: `set -privilege advanced`
. Die Berechtigung für die UNIX-Gruppe wird entsprechend konfiguriert:
+
|===
| Wenn Sie möchten | Den Befehl eingeben 


 a| 
Der Zugriff auf Dateien oder Verzeichnisse ermöglicht das Erhalten von Gruppenberechtigungen, auch wenn der Benutzer nicht der Eigentümer der Datei ist.
 a| 
`vserver cifs options modify –grant-unix-group-perms-to-others true`



 a| 
Der Zugriff auf Dateien oder Verzeichnisse wird deaktiviert, sodass Gruppenberechtigungen nur dann gelten, wenn der Benutzer nicht der Eigentümer der Datei ist.
 a| 
`vserver cifs options modify –grant-unix-group-perms-to-others false`

|===
. Es wird überprüft, ob die Option auf den gewünschten Wert eingestellt ist: `vserver cifs options show –fields grant-unix-group-perms-to-others`
. Zurück zur Administratorrechteebene: `set -privilege admin`

