---
permalink: smb-admin/configure-roaming-profiles-task.html 
sidebar: sidebar 
keywords: automatic, user, profile, available, log, computer, network, configure, roam, active, directory, mmc, snap-in, configuring, roam, windows, server, administration, center, configure roam profile 
summary: Wenn Sie das Profil eines Benutzers automatisch verfügbar machen möchten, wenn sich dieser Benutzer an einem beliebigen Computer im Netzwerk anmeldet, können Sie Roaming-Profile über das MMC-Snap-in Active Directory-Benutzer und -Computer konfigurieren. Wenn Sie Roaming-Profile auf Windows Server konfigurieren, können Sie das Active Directory-Administrationscenter verwenden. 
---
= Konfigurieren Sie Roaming ONTAP SMB-Profile über die Active Directory-Benutzer und -Computer MMC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie das Profil eines Benutzers automatisch zur Verfügung stellen möchten, wenn sich dieser Benutzer an einem beliebigen Computer im Netzwerk anmeldet, können Sie Roaming-Profile über das MMC-Snap-in Active Directory-Benutzer und -Computer konfigurieren. Wenn Sie Roaming-Profile auf Windows Server konfigurieren, können Sie das Active Directory-Administrationscenter verwenden.

.Schritte
. Öffnen Sie auf dem Windows-Server die MMC für Active Directory-Benutzer und -Computer (oder das Active Directory-Verwaltungscenter auf Windows-Servern).
. Suchen Sie den Benutzer, für den Sie ein Roaming-Profil konfigurieren möchten.
. Klicken Sie mit der rechten Maustaste auf den Benutzer und klicken Sie auf *Eigenschaften*.
. Geben Sie auf der Registerkarte *Profil* den Profilpfad zu der Freigabe ein, in der das Roaming-Profil des Benutzers gespeichert werden soll, gefolgt von `%username%`.
+
Ein Profilpfad kann beispielsweise wie folgt lauten: `\\vs1.example.com\profiles\%username%`. Wenn sich ein Benutzer zum ersten Mal anmeldet, `%username%` wird er durch den Benutzernamen ersetzt.

+
[NOTE]
====
Im Pfad `\\vs1.example.com\profiles\%username%` `profiles` ist der Freigabename eines Share on Storage Virtual Machine (SVM) vs1, der für alle volle Kontrollrechte besitzt.

====
. Klicken Sie auf *OK*.

