---
permalink: smb-admin/configure-ntfs-windows-security-tab-task.html 
sidebar: sidebar 
keywords: configure, standard, ntfs, file, permission, file, folder, windows, security, tab, windows, properties, configure advanced ntfs file permission using the windows security tab 
summary: Sie können Standard-NTFS-Dateiberechtigungen für Dateien und Ordner über die Registerkarte Windows-Sicherheit im Fenster Windows-Eigenschaften konfigurieren. 
---
= Konfigurieren Sie erweiterte NTFS-Dateiberechtigungen mithilfe der Registerkarte „Windows-Sicherheit“ für ONTAP SMB SVMs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Standard-NTFS-Dateiberechtigungen für Dateien und Ordner konfigurieren, indem Sie im Fenster Windows-Eigenschaften die Registerkarte *Windows-Sicherheit* verwenden.

.Bevor Sie beginnen
Der Administrator, der diese Aufgabe ausführt, muss über ausreichende NTFS-Berechtigungen verfügen, um Berechtigungen für die ausgewählten Objekte zu ändern.

.Über diese Aufgabe
Die Konfiguration von NTFS-Dateiberechtigungen erfolgt auf einem Windows-Host durch Hinzufügen von Einträgen zu NTFS-Ermessensary Access Control Lists (DACLs), die mit einem NTFS-Sicherheitsdeskriptor verknüpft sind. Der Sicherheitsdeskriptor wird dann auf NTFS-Dateien und -Verzeichnisse angewendet. Diese Aufgaben werden automatisch von der Windows GUI übernommen.

.Schritte
. Wählen Sie im Menü *Tools* im Windows Explorer die Option *Netzwerklaufwerk zuordnen* aus.
. Füllen Sie das Dialogfeld *Map Network Drive* aus:
+
.. Wählen Sie einen *Drive*-Buchstaben aus.
.. Geben Sie im Feld *Ordner* den CIFS-Servernamen ein, der den Share enthält, der die Daten enthält, auf die Sie Berechtigungen anwenden möchten, und den Namen der Freigabe.
+
Wenn Ihr CIFS-Servername „`CIFS_SERVER`“ lautet und Ihre Freigabe den Namen „`share1`“ hat, sollten Sie eingeben `\\CIFS_SERVER\share1`.

+

NOTE: Sie können anstelle des CIFS-Servernamens die IP-Adresse der Datenschnittstelle für den CIFS-Server angeben.

.. Klicken Sie Auf *Fertig Stellen*.


+
Das ausgewählte Laufwerk ist mit dem Windows Explorer-Fenster verbunden und bereit, in dem die Dateien und Ordner in der Freigabe angezeigt werden.

. Wählen Sie die Datei oder das Verzeichnis aus, für die Sie NTFS-Dateiberechtigungen festlegen möchten.
. Klicken Sie mit der rechten Maustaste auf die Datei oder das Verzeichnis, und wählen Sie dann *Eigenschaften* aus.
. Wählen Sie die Registerkarte *Sicherheit*.
+
Auf der Registerkarte *Sicherheit* wird die Liste der Benutzer und Gruppen angezeigt, für die NTFS-Berechtigungen festgelegt sind. Im Feld *Berechtigungen für* wird eine Liste mit Berechtigungen für jeden ausgewählten Benutzer oder jede ausgewählte Gruppe angezeigt.

. Klicken Sie Auf *Erweitert*.
+
Im Fenster Windows-Eigenschaften werden Informationen über vorhandene Dateiberechtigungen angezeigt, die Benutzern und Gruppen zugewiesen sind.

. Klicken Sie Auf *Berechtigungen Ändern*.
+
Das Fenster Berechtigungen wird geöffnet.

. Führen Sie die gewünschten Aktionen aus:
+
|===
| Ihr Ziel ist | Gehen Sie wie folgt vor... 


 a| 
Einrichten erweiterter NTFS-Berechtigungen für einen neuen Benutzer oder eine neue Gruppe
 a| 
.. Klicken Sie Auf *Hinzufügen*.
.. Geben Sie in das Feld *Geben Sie den Objektnamen ein, den Sie auswählen möchten. Geben Sie den Namen des Benutzers oder der Gruppe ein, den Sie hinzufügen möchten.
.. Klicken Sie auf *OK*.




 a| 
Ändern Sie erweiterte NTFS-Berechtigungen von einem Benutzer oder einer Gruppe
 a| 
.. Wählen Sie im Feld *Berechtigungen Einträge:* den Benutzer oder die Gruppe aus, deren erweiterte Berechtigungen Sie ändern möchten.
.. Klicken Sie Auf *Bearbeiten*.




 a| 
Entfernen Sie erweiterte NTFS-Berechtigungen für einen Benutzer oder eine Gruppe
 a| 
.. Wählen Sie im Feld *Berechtigungen Einträge:* den Benutzer oder die Gruppe aus, die Sie entfernen möchten.
.. Klicken Sie Auf *Entfernen*.
.. Weiter mit Schritt 13.


|===
+
Wenn Sie erweiterte NTFS-Berechtigungen für einen neuen Benutzer oder eine neue Gruppe hinzufügen oder die erweiterten NTFS-Berechtigungen für einen vorhandenen Benutzer oder eine vorhandene Gruppe ändern, wird das Feld Berechtigung für <Objekt> geöffnet.

. Wählen Sie im Feld *Apply to* aus, wie Sie diesen NTFS-Dateiberechtigungseintrag anwenden möchten.
+
Wenn Sie NTFS-Dateiberechtigungen für eine einzelne Datei einrichten, ist das Feld *Apply to* nicht aktiv. Die Einstellung *Apply to* ist standardmäßig auf *nur dieses Objekt* eingestellt.

. Wählen Sie im Feld *Berechtigungen* die Felder *erlauben* oder *verweigern* für die erweiterten Berechtigungen, die Sie für dieses Objekt festlegen möchten.
+
** Um den angegebenen Zugriff zuzulassen, wählen Sie das Feld *Zulassen* aus.
** Um den angegebenen Zugriff nicht zuzulassen, wählen Sie das Feld *Deny* aus. Sie können Berechtigungen für die folgenden erweiterten Rechte festlegen:
** *Volle Kontrolle*
+
Wenn Sie dieses erweiterte Recht wählen, werden alle anderen erweiterten Rechte automatisch ausgewählt (entweder Rechte zulassen oder verweigern).

** *Traverse Ordner / Datei ausführen*
** *Ordner auflisten / Daten lesen*
** *Attribute lesen*
** *Erweiterte Attribute lesen*
** *Dateien erstellen / Daten schreiben*
** *Ordner erstellen / Daten anhängen*
** *Attribute schreiben*
** *Erweiterte Attribute schreiben*
** *Löschen von Unterordnern und Dateien*
** *Löschen*
** *Berechtigungen lesen*
** *Berechtigungen ändern*
** *Besitzrechte übernehmen*


+

NOTE: Wenn eines der Felder mit erweiterten Berechtigungen nicht ausgewählt werden kann, liegt dies daran, dass die Berechtigungen vom übergeordneten Objekt übernommen werden.

. Wenn Sie möchten, dass Unterordner und Dateien dieses Objekts diese Berechtigungen erben, wählen Sie das Feld *Diese Berechtigungen auf Objekte und/oder Container innerhalb dieses Containers only* anwenden.
. Klicken Sie auf *OK*.
. Geben Sie nach dem Hinzufügen, Entfernen oder Bearbeiten von NTFS-Berechtigungen die Vererbung für dieses Objekt an:
+
** Wählen Sie aus dem Feld *include inheritable Berechtigungen aus dem übergeordneten* dieses Objekts aus.
+
Dies ist die Standardeinstellung.

** Wählen Sie aus diesem Objekt* das Feld *Alle Berechtigungen für untergeordnete Objekte mit vererbbaren Berechtigungen ersetzen aus.
+
Diese Einstellung ist nicht im Feld Berechtigungen vorhanden, wenn Sie NTFS-Dateiberechtigungen für eine einzelne Datei festlegen.

+

NOTE: Gehen Sie bei der Auswahl dieser Einstellung vorsichtig vor. Mit dieser Einstellung werden alle bestehenden Berechtigungen für alle untergeordneten Objekte entfernt und durch die Berechtigungseinstellungen dieses Objekts ersetzt. Sie können versehentlich Berechtigungen entfernen, die Sie nicht entfernen möchten. Es ist besonders wichtig, wenn Berechtigungen in einem gemischten Volume oder qtree im Sicherheitsstil festgelegt werden. Wenn untergeordnete Objekte einen effektiven UNIX-Sicherheitsstil haben, führt die Weitergabe von NTFS-Berechtigungen an diese untergeordneten Objekte dazu, dass ONTAP diese Objekte vom UNIX-Sicherheitsstil auf den NTFS-Sicherheitsstil ändert. Alle UNIX-Berechtigungen für diese untergeordneten Objekte werden durch NTFS-Berechtigungen ersetzt.

** Wählen Sie beide Felder aus.
** Wählen Sie keine der Kontrollkästchen aus.


. Klicken Sie auf *OK*, um das Feld *Berechtigungen* zu schließen.
. Klicken Sie auf *OK*, um das Feld *Erweiterte Sicherheitseinstellungen für <Objekt>* zu schließen.
+
Weitere Informationen zum Festlegen erweiterter NTFS-Berechtigungen finden Sie in der Windows-Dokumentation.



.Verwandte Informationen
xref:create-ntfs-security-descriptor-file-task.adoc[Konfigurieren und Anwenden der Dateisicherheit auf NTFS-Dateien und Ordnern mithilfe der CLI]

xref:display-file-security-ntfs-style-volumes-task.adoc[Anzeigen von Informationen zur Dateisicherheit auf NTFS-SicherheitsVolumes]

xref:display-file-security-mixed-style-volumes-task.adoc[Anzeigen von Informationen zur Dateisicherheit auf Volumes mit gemischter Sicherheitsart]

xref:display-file-security-unix-style-volumes-task.adoc[Anzeigen von Informationen zur Dateisicherheit auf UNIX-SicherheitsVolumes]
