---
permalink: smb-admin/configure-ntfs-file-permissions-concept.html 
sidebar: sidebar 
keywords: configure, ntfs, file, permission, directories, directory, ontap, cli, enable, windows, client, how to configure ntfs file permissions using the ontap cli 
summary: NTFS-Dateiberechtigungen für Dateien und Verzeichnisse lassen sich mithilfe der ONTAP-Befehlszeilenschnittstelle konfigurieren. Dies ermöglicht die Konfiguration von NTFS-Dateiberechtigungen, ohne dass eine Verbindung zu den Daten über eine SMB-Freigabe auf einem Windows-Client erforderlich ist. 
---
= ONTAP Befehle für SMB NTFS-Dateiberechtigungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NTFS-Dateiberechtigungen für Dateien und Verzeichnisse lassen sich mithilfe der ONTAP-Befehlszeilenschnittstelle konfigurieren. Dies ermöglicht die Konfiguration von NTFS-Dateiberechtigungen, ohne dass eine Verbindung zu den Daten über eine SMB-Freigabe auf einem Windows-Client erforderlich ist.

Sie können NTFS-Dateiberechtigungen konfigurieren, indem Sie Einträge zu den NTFS-Zugriffskontrolllisten (DACLs) hinzufügen, die einem NTFS-Sicherheitsdeskriptor zugeordnet sind. Der Sicherheitsdeskriptor wird anschließend auf NTFS-Dateien und Verzeichnisse angewendet.

NTFS-Dateiberechtigungen können nur über die Befehlszeile konfiguriert werden. NFSv4-ACLs können über die Befehlszeile nicht konfiguriert werden.

.Schritte
. Ein NTFS-Sicherheitsdeskriptor wird erstellt.
+
`vserver security file-directory ntfs create -vserver _svm_name_ -ntfs-sd _ntfs_security_descriptor_name_ -owner _owner_name_ -group _primary_group_name_ -control-flags-raw _raw_control_flags_`

. DACLs zum NTFS-Sicherheitsdeskriptor hinzufügen.
+
`vserver security file-directory ntfs dacl add -vserver _svm_name_ -ntfs-sd _ntfs_security_descriptor_name_ -access-type {deny|allow} -account _account_name_ -rights {no-access|full-control|modify|read-and-execute|read|write} -apply-to {this-folder|sub-folders|files}`

. Eine Datei-/Verzeichnissicherheitsrichtlinie erstellen.
+
`vserver security file-directory policy create -vserver _svm_name_ -policy-name _policy_name_`


