---
permalink: smb-admin/configure-security-styles-qtrees-task.html 
sidebar: sidebar 
keywords: configure, qtree, volume, security, style, permission, data, configure security styles on qtrees 
summary: Sie konfigurieren den Sicherheitsstil des qtree Volume, um die Art der Berechtigungen zu bestimmen, die für Daten in qtrees verwendet werden. 
---
= Konfigurieren Sie SMB-Sicherheitstile in ONTAP qtrees
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie konfigurieren den Sicherheitsstil des qtree Volume, um die Art der Berechtigungen zu bestimmen, die für Daten in qtrees verwendet werden.

.Schritte
. Führen Sie eine der folgenden Aktionen aus:
+
|===
| Wenn der qtree... | Verwenden Sie den Befehl... 


 a| 
Ist noch nicht vorhanden
 a| 
`volume qtree create` Und schließen Sie den `-security-style` Parameter ein, um den Sicherheitsstil festzulegen.



 a| 
Ist bereits vorhanden
 a| 
`volume qtree modify` Und schließen Sie den `-security-style` Parameter ein, um den Sicherheitsstil festzulegen.

|===
+
Mögliche Optionen für den qtree Sicherheitsstil sind `unix`, , `ntfs` oder `mixed`.

+
Wenn Sie beim Erstellen eines qtree keinen Sicherheitsstil angeben `mixed`.

+
Weitere Informationen zu den `volume qtree create` `volume qtree modify` Befehlen oder finden Sie unter link:../volumes/index.html["Logisches Storage-Management"].

. Geben Sie den folgenden Befehl ein, um die Konfiguration einschließlich des Sicherheitstils des von Ihnen erstellten qtree anzuzeigen: `volume qtree show -qtree qtree_name -instance`

