---
permalink: smb-admin/configure-default-user-task.html 
sidebar: sidebar 
keywords: configure, default, user, map, fail, authentication, non-mapped, fail, alternative, configure the default user 
summary: Sie können einen Standardbenutzer so konfigurieren, dass er verwendet wird, wenn alle anderen Zuordnungsversuche für einen Benutzer fehlschlagen oder wenn Sie nicht einzelne Benutzer zwischen UNIX und Windows zuordnen möchten. Wenn die Authentifizierung von nicht zugeordneten Benutzern fehlschlägt, sollten Sie keinen Standardbenutzer konfigurieren. 
---
= Konfigurieren Sie den ONTAP-SMB-Standardbenutzer
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen Standardbenutzer so konfigurieren, dass er verwendet wird, wenn alle anderen Zuordnungsversuche für einen Benutzer fehlschlagen oder wenn Sie nicht einzelne Benutzer zwischen UNIX und Windows zuordnen möchten. Wenn die Authentifizierung von nicht zugeordneten Benutzern fehlschlägt, sollten Sie keinen Standardbenutzer konfigurieren.

.Über diese Aufgabe
Wenn Sie bei der CIFS-Authentifizierung nicht jeden Windows-Benutzer einem einzelnen UNIX-Benutzer zuordnen möchten, können Sie stattdessen einen standardmäßigen UNIX-Benutzer festlegen.

Wenn Sie bei der NFS-Authentifizierung nicht jeden UNIX-Benutzer einem einzelnen Windows-Benutzer zuordnen möchten, können Sie stattdessen einen standardmäßigen Windows-Benutzer festlegen.

.Schritte
. Führen Sie eine der folgenden Aktionen aus:
+
|===
| Ihr Ziel ist | Geben Sie den folgenden Befehl ein... 


 a| 
Konfigurieren Sie den UNIX-Standardbenutzer
 a| 
`vserver cifs options modify -default-unix-user _user_name_`



 a| 
Konfigurieren Sie den Windows-Standardbenutzer
 a| 
`vserver nfs modify -default-win-user _user_name_`

|===

