---
permalink: smb-admin/configure-lifetime-metadata-cache-entries-task.html 
sidebar: sidebar 
keywords: configure, lifetime, smb, metadata, cache, entries, optimise, environment, configure the lifetime of smb metadata cache entries 
summary: Sie können die Nutzungsdauer von SMB-Metadaten-Cache-Einträgen konfigurieren, um die Performance des SMB-Metadaten-Caches in Ihrer Umgebung zu optimieren. Die Standardeinstellung ist 10 Sekunden. 
---
= Konfigurieren der Lebensdauer von ONTAP SMB-Metadaten-Cache-Einträgen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Nutzungsdauer von SMB-Metadaten-Cache-Einträgen konfigurieren, um die Performance des SMB-Metadaten-Caches in Ihrer Umgebung zu optimieren. Die Standardeinstellung ist 10 Sekunden.

.Bevor Sie beginnen
Sie müssen die SMB-Metadaten-Cache-Funktion aktiviert haben. Wenn das SMB-Metadaten-Caching nicht aktiviert ist, wird die TTL-Einstellung des SMB-Caches nicht verwendet.

.Schritt
. Führen Sie die gewünschte Aktion aus:
+
|===
| Wenn Sie die Lebensdauer von SMB-Metadaten-Cache-Einträgen konfigurieren möchten, wenn Sie... | Geben Sie den Befehl ein... 


 a| 
Erstellen Sie eine Freigabe
 a| 
`vserver cifs share -create -vserver _vserver_name_ -share-name _share_name_ -path _path_ -attribute-cache-ttl [integerh][integerm][integers]`



 a| 
Vorhandene Freigabe ändern
 a| 
`vserver cifs share -modify -vserver _vserver_name_ -share-name _share_name_ -attribute-cache-ttl [integerh][integerm][integers]`

|===
+
Sie können zusätzliche Optionen und Eigenschaften für die Freigabkonfiguration beim Erstellen oder Ändern von Freigaben festlegen. Erfahren Sie mehr über `vserver cifs share` in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs+share["ONTAP-Befehlsreferenz"^].


