---
permalink: smb-admin/control-domain-controller-discovery-task.html 
sidebar: sidebar 
keywords: ontap, modify, default, process, domain, controller, dc, enable, limit, site, pool, performance, improvement, environment, manage, manage domain controller discovery 
summary: 'Ab ONTAP 9.3 können Sie den Standardprozess ändern, mit dem Domänencontroller (DCs) erkannt werden. So können Sie die Erkennung auf Ihren Standort oder einen Pool von bevorzugten DCs beschränken, was je nach Umgebung zu Performance-Verbesserungen führen kann.' 
---
= Verwalten der Domänen-Controller-Erkennung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.3 können Sie den Standardprozess ändern, mit dem Domänencontroller (DCs) erkannt werden. So können Sie die Erkennung auf Ihren Standort oder einen Pool von bevorzugten DCs beschränken, was je nach Umgebung zu Performance-Verbesserungen führen kann.

.Über diese Aufgabe
Standardmäßig werden durch den dynamischen Erkennungsprozess alle verfügbaren Datacenter erkannt, einschließlich bevorzugter Datacenter, aller Datacenter am lokalen Standort und aller Remote-Datacenter. Diese Konfiguration kann in bestimmten Umgebungen zu einer Verzögerung bei der Authentifizierung und beim Zugriff auf Freigaben führen. Wenn Sie bereits den Pool von DCs bestimmt haben, die Sie verwenden möchten, oder wenn die Remote-DCs nicht ausreichend oder nicht zugänglich sind, können Sie die Ermittlungsmethode ändern.

In ONTAP 9.3 und neueren Versionen `discovery-mode` `cifs domain discovered-servers` ermöglicht der Parameter des Befehls, eine der folgenden Ermittlungs-Optionen auszuwählen:

* Alle DCs in der Domäne werden ermittelt.
* Es werden nur die DCs auf dem lokalen Standort entdeckt.
+
Der `default-site` Parameter für den SMB-Server kann für die Verwendung dieses Modus bei LIFs definiert werden, die keinem Standort in Sites-and-Services zugewiesen sind.

* Server-Erkennung wird nicht durchgeführt, die SMB-Server-Konfiguration hängt nur von den bevorzugten Datacentern ab.
+
Um diesen Modus zu nutzen, müssen Sie zunächst die bevorzugten DCs für den SMB-Server definieren.



.Bevor Sie beginnen
Sie müssen sich auf der erweiterten Berechtigungsebene befinden.

.Schritt
. Geben Sie die gewünschte Ermittlungsoption an: `vserver cifs domain discovered-servers discovery-mode modify -vserver _vserver_name_ -mode {all|site|none}`
+
Optionen für den `mode` Parameter:

+
** `all`
+
Ermitteln Sie alle verfügbaren DCs (Standard).

** `site`
+
Beschränken Sie die DC-Erkennung auf Ihren Standort.

** `none`
+
Nutzung nur bevorzugter Datacenter und keine Bestandsaufnahme




