---
permalink: smb-admin/create-ntfs-security-descriptor-file-task.html 
sidebar: sidebar 
keywords: create, creating, ntfs, security, descriptor, file, policy, configuring, configure, apply, access, control, acl, file, folder, residing, reside, storage, virtual, machine, svm, associate, task 
summary: 'Das Erstellen eines NTFS-Sicherheitsdeskriptors (Dateisicherheitsrichtlinie) ist der erste Schritt bei der Konfiguration und Anwendung von NTFS-Zugriffssteuerungslisten (NTFS Access Control Lists, ACLs) auf Dateien und Ordner innerhalb der Storage Virtual Machines (SVMs). Sie können den Sicherheitsdeskriptor in einer Richtlinienaufgabe dem Datei- oder Ordnerpfad zuordnen.' 
---
= Erstellen Sie einen NTFS-Sicherheitsdeskriptor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Erstellen eines NTFS-Sicherheitsdeskriptors (Dateisicherheitsrichtlinie) ist der erste Schritt bei der Konfiguration und Anwendung von NTFS-Zugriffssteuerungslisten (NTFS Access Control Lists, ACLs) auf Dateien und Ordner innerhalb der Storage Virtual Machines (SVMs). Sie können den Sicherheitsdeskriptor in einer Richtlinienaufgabe dem Datei- oder Ordnerpfad zuordnen.

.Über diese Aufgabe
NTFS-Sicherheitsdeskriptoren können für Dateien und Ordner erstellt werden, die sich in NTFS-Volumes im Sicherheitsstil befinden, oder für Dateien und Ordner, die sich auf gemischten Volumes im Sicherheitsstil befinden.

Wenn ein Sicherheitsdeskriptor erstellt wird, werden standardmäßig vier DACL-Einträge (Discretionary Access Control List) zur Sicherheitsbeschreibung hinzugefügt. Die vier Standard-Aces sind wie folgt:

|===
| Objekt | Zugriffstyp | Zugriffsrechte | Anwenden der Berechtigungen 


 a| 
BUILTIN\Administratoren
 a| 
Zulassen
 a| 
Volle Kontrolle
 a| 
Dieser Ordner, Unterordner, Dateien



 a| 
BUILTIN\Benutzer
 a| 
Zulassen
 a| 
Volle Kontrolle
 a| 
Dieser Ordner, Unterordner, Dateien



 a| 
CREATOR-BESITZER
 a| 
Zulassen
 a| 
Volle Kontrolle
 a| 
Dieser Ordner, Unterordner, Dateien



 a| 
NT AUTHORITY\SYSTEM
 a| 
Zulassen
 a| 
Volle Kontrolle
 a| 
Dieser Ordner, Unterordner, Dateien

|===
Sie können die Konfiguration der Sicherheitsdeskriptoren mithilfe der folgenden optionalen Parameter anpassen:

* Besitzer des Sicherheitsdeskriptors
* Primäre Gruppe des Eigentümers
* RAW-Kontrollfahnen


Der Wert für alle optionalen Parameter wird für Storage-Level Access Guard ignoriert. Weitere Informationen finden Sie auf den man-Pages.
