---
permalink: smb-admin/create-branchcache-enabled-share-task.html 
sidebar: sidebar 
keywords: enable, branchcache, smb, create, share, setting, property, create a bracnhcache-enabled smb share 
summary: Sie können BranchCache auf einer SMB-Freigabe aktivieren, wenn Sie die Freigabe erstellen, indem Sie die Eigenschaft branchcache-Freigabe festlegen. 
---
= Erstellen Sie BranchCache-fähige ONTAP SMB-Freigaben
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können BranchCache auf einer SMB-Freigabe aktivieren, wenn Sie die `branchcache` Freigabe erstellen, indem Sie die Share-Eigenschaft festlegen.

.Über diese Aufgabe
* Wenn BranchCache auf der SMB-Freigabe aktiviert ist, muss die Konfiguration der Offline-Dateien auf manuelle Cache-Speicherung festgelegt sein.
+
Dies ist die Standardeinstellung, wenn Sie eine Freigabe erstellen.

* Sie können auch zusätzliche optionale Freigabeparameter festlegen, wenn Sie die BranchCache-fähige Freigabe erstellen.
* Sie können die `branchcache` Eigenschaft auf einer Freigabe selbst dann festlegen, wenn BranchCache auf der Storage Virtual Machine (SVM) nicht konfiguriert und aktiviert ist.
+
Um jedoch gecachte Inhalte bereitstellen zu können, müssen BranchCache auf der SVM konfiguriert und aktiviert werden.

* Da `-share-properties` `branchcache` für die Freigabe keine Standardfreigabeeigenschaften angewendet wurden, müssen Sie mit Hilfe des Parameters alle anderen Freigabeeigenschaften angeben, die Sie zusätzlich zur Freigabeeigenschaft auf die Freigabe anwenden möchten, indem Sie eine kommagetrennte Liste verwenden.
* Erfahren Sie mehr über `vserver cifs share create` in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-share-create.html["ONTAP-Befehlsreferenz"^].


.Schritt
. Erstellen Sie eine SMB-Freigabe mit BranchCache: +
`vserver cifs share create -vserver _vserver_name_ -share-name _share_name_ -path _path_ -share-properties branchcache[,...]`
. Überprüfen Sie mit dem `vserver cifs share show` Befehl, ob die Eigenschaft BranchCache-Freigabe auf der SMB-Freigabe festgelegt ist.


.Beispiel
Mit dem folgenden Befehl wird eine SMB-Freigabe mit BranchCache namens „`data`“ mit einem Pfad von `/data` auf SVM vs1 erstellt. Standardmäßig ist die Einstellung für Offline-Dateien auf eingestellt `manual`:

[listing]
----
cluster1::> vserver cifs share create -vserver vs1 -share-name data -path /data -share-properties branchcache,oplocks,browsable,changenotify

cluster1::> vserver cifs share show -vserver vs1 -share-name data
                      Vserver: vs1
                        Share: data
     CIFS Server NetBIOS Name: VS1
                         Path: /data
             Share Properties: branchcache
                               oplocks
                               browsable
                               changenotify
           Symlink Properties: enable
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: -
                  Volume Name: data
                Offline Files: manual
Vscan File-Operations Profile: standard
----
.Verwandte Informationen
xref:disable-branchcache-single-share-task.adoc[Deaktivieren von BranchCache auf einer einzelnen Freigabe]
