---
permalink: smb-admin/create-name-mapping-task.html 
sidebar: sidebar 
keywords: vserver, name-mapping, create, command, name, map, windows, enable, user, access, unix, security, style, volume, reverse, create a name mapping 
summary: 'Mit dem Befehl `vserver name-mapping create` kann eine Namenszuordnung erstellt werden. Namenszuordnungen werden verwendet, damit Windows-Benutzer auf UNIX Security Style Volumes zugreifen können und umgekehrt.' 
---
= ONTAP SMB-Namenszuordnung erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den  `vserver name-mapping create` Befehl verwenden, um eine Namenszuordnung zu erstellen. Namenszuordnungen werden verwendet, damit Windows-Benutzer auf UNIX Security Style Volumes zugreifen können und umgekehrt.

.Über diese Aufgabe
ONTAP unterstützt für jede SVM bis zu 12.500 Namenszuordnungen pro Richtung.

.Schritt
. Namenszuordnung erstellen: `vserver name-mapping create -vserver _vserver_name_ -direction {krb-unix|win-unix|unix-win} -position _integer_ -pattern text -replacement _text_`
+
[NOTE]
====
Die  `-pattern` und  `-replacement`-Anweisungen können als reguläre Ausdrücke formuliert werden. Die  `-replacement`-Anweisung kann auch verwendet werden, um dem Benutzer eine Zuordnung explizit zu verweigern, indem die Null-Ersetzungszeichenkette  `" "` (das Leerzeichen) verwendet wird. Weitere Informationen zu  `vserver name-mapping create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-name-mapping-create.html["ONTAP-Befehlsreferenz"^].

====
+
Wenn Windows-zu-UNIX-Zuordnungen erstellt werden, müssen sich alle SMB-Clients, die zum Zeitpunkt der Erstellung der neuen Zuordnungen offene Verbindungen zum ONTAP System haben, ausloggen und sich erneut anmelden, um die neuen Zuordnungen zu sehen.



.Beispiele
Der folgende Befehl erstellt eine Namenszuordnung auf der SVM mit dem Namen vs1. Die Zuordnung ist eine Zuordnung von UNIX zu Windows an Position 1 in der Prioritätsliste. Die Zuordnung ordnet den UNIX-Benutzer johnd dem Windows-Benutzer ENG\JohnDoe zu.

[listing]
----
vs1::> vserver name-mapping create -vserver vs1 -direction unix-win -position 1 -pattern johnd
-replacement "ENG\\JohnDoe"
----
Der folgende Befehl erstellt eine weitere Namenszuordnung auf der SVM mit dem Namen vs1. Die Zuordnung ist eine Zuordnung von Windows zu UNIX an Position 1 in der Prioritätsliste. Hier beinhalten Muster und Ersetzung reguläre Ausdrücke. Die Zuordnung ordnet jeden CIFS-Benutzer in der Domäne ENG Benutzern in der mit der SVM verknüpften LDAP-Domäne zu.

[listing]
----
vs1::> vserver name-mapping create -vserver vs1 -direction win-unix -position 1 -pattern "ENG\\(.+)"
-replacement "\1"
----
Der folgende Befehl erstellt eine weitere Namenszuordnung auf der SVM mit dem Namen vs1. Das Muster enthält hierbei das Zeichen "`$`" im Windows-Benutzernamen, das maskiert werden muss. Die Zuordnung ordnet den Windows-Benutzer ENG\john$ops dem UNIX-Benutzer john_ops zu.

[listing]
----
vs1::> vserver name-mapping create -direction win-unix -position 1 -pattern ENG\\john\$ops
-replacement john_ops
----