---
permalink: smb-admin/create-share-access-control-lists-task.html 
sidebar: sidebar 
keywords: configuring, configure, permission, share, creating, create, control, list, acl, smb, enable, level, access, user, group, create smb share access control lists 
summary: Durch die Konfiguration von Freigabeberechtigungen mittels Zugriffssteuerungslisten für SMB-Freigaben können Sie die Zugriffsebene für Benutzer und Gruppen auf eine Freigabe steuern. 
---
= Erstellen von ONTAP SMB-Freigabe-Zugriffssteuerungslisten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Konfiguration von Freigabeberechtigungen durch das Erstellen von Zugriffssteuerungslisten (ACLs) für SMB-Freigaben ermöglicht die Kontrolle der Zugriffsebene auf eine Freigabe für Benutzer und Gruppen.

.Über diese Aufgabe
Sie können Zugriffssteuerungslisten auf Freigabeebene konfigurieren, indem Sie lokale oder Domänen-Windows-Benutzer- oder Gruppennamen oder UNIX-Benutzer- oder Gruppennamen verwenden.

Bevor Sie eine neue ACL erstellen, sollten Sie die standardmäßige Freigabe-ACL  `Everyone / Full Control` löschen, da diese ein Sicherheitsrisiko darstellt.

Im Arbeitsgruppenmodus ist der lokale Domänenname der SMB-Servername.

.Schritte
. Die Standard-Freigabe-ACL löschen: `vserver cifs share access-control delete -vserver <vserver_name> -share <share_name> -user-or-group Everyone`
. Die neue Zugriffssteuerungsliste (ACL) konfigurieren:
+
|===
| Wenn Sie Zugriffssteuerungslisten (ACLs) mithilfe von... konfigurieren möchten | Geben Sie den Befehl ein... 


 a| 
Windows Benutzer
 a| 
`vserver cifs share access-control create -vserver <vserver_name> -share <share_name> -user-group-type windows -user-or-group <Windows_domain_name\user_name> -permission <access_right>`



 a| 
Windows Gruppe
 a| 
`vserver cifs share access-control create -vserver <vserver_name> -share <share_name> -user-group-type windows -user-or-group <Windows_domain_name\group_name> -permission <access_right>`



 a| 
UNIX-Benutzer
 a| 
`vserver cifs share access-control create -vserver <vserver_name> -share <share_name> -user-group-type <unix-user> -user-or-group <UNIX_user_name> -permission <access_right>`



 a| 
UNIX-Gruppe
 a| 
`vserver cifs share access-control create -vserver <vserver_name> -share <share_name> -user-group-type <unix-group> -user-or-group <UNIX_group_name> -permission <access_right>`

|===
. Es kann überprüft werden, ob die auf die Freigabe angewendete Zugriffssteuerungsliste (ACL) korrekt ist, indem der  `vserver cifs share access-control show` Befehl verwendet wird.


.Beispiel
Der folgende Befehl erteilt `Change` der Windows-Gruppe "`Sales Team`" Berechtigungen für die Freigabe "`sales`" auf der "`vs1.example.com`"-SVM:

[listing]
----
cluster1::> vserver cifs share access-control create -vserver vs1.example.com -share sales -user-or-group "DOMAIN\Sales Team" -permission Change

cluster1::> vserver cifs share access-control show -vserver vs1.example.com
                 Share       User/Group              User/Group  Access
Vserver          Name        Name                    Type        Permission
---------------- ----------- --------------------    ---------   -----------
vs1.example.com  c$          BUILTIN\Administrators  windows     Full_Control
vs1.example.com  sales       DOMAIN\Sales Team     windows     Change
----
Der folgende Befehl erteilt  `Read` der UNIX-Gruppe „engineering“ die Berechtigung für die Freigabe „eng“ auf der SVM „vs2.example.com“:

[listing]
----
cluster1::> vserver cifs share access-control create -vserver vs2.example.com -share eng -user-group-type unix-group -user-or-group  engineering -permission Read

cluster1::> vserver cifs share access-control show -vserver vs2.example.com
                 Share       User/Group               User/Group  Access
Vserver          Name        Name                     Type        Permission
---------------- ----------- -------------------      ----------- -----------
vs2.example.com  c$          BUILTIN\Administrators   windows     Full_Control
vs2.example.com  eng         engineering              unix-group  Read
----
Die folgenden Befehle erteilen  `Change`der lokalen Windows-Gruppe „Tiger Team“ und  `Full_Control`dem lokalen Windows-Benutzer „Sue Chang“ die Berechtigung für die Freigabe „datavol5“ auf der SVM „vs1“:

[listing]
----
cluster1::> vserver cifs share access-control create -vserver vs1 -share datavol5 -user-group-type windows -user-or-group "Tiger Team" -permission Change

cluster1::> vserver cifs share access-control create -vserver vs1 -share datavol5 -user-group-type windows -user-or-group "Sue Chang" -permission Full_Control

cluster1::> vserver cifs share access-control show -vserver vs1
               Share       User/Group                  User/Group  Access
Vserver        Name        Name                        Type        Permission
-------------- ----------- --------------------------- ----------- -----------
vs1            c$          BUILTIN\Administrators      windows     Full_Control
vs1            datavol5    Tiger Team         windows     Change
vs1            datavol5    Sue Chang          windows     Full_Control
----