---
permalink: smb-admin/create-security-policies-file-task.html 
sidebar: sidebar 
keywords: create, creating, file, security, policy, svm, configuring, configure, apply, acl, folder, act, container, entry, applied, create security policies 
summary: Das Erstellen einer Dateisicherheitsrichtlinie für SVMs ist der dritte Schritt beim Konfigurieren und Anwenden von Zugriffssteuerungslisten auf eine Datei oder einen Ordner. Eine Richtlinie dient als Container für verschiedene Aufgaben, wobei jede Aufgabe einen einzelnen Eintrag darstellt, der auf Dateien oder Ordner angewendet werden kann. Aufgaben können der Sicherheitsrichtlinie später hinzugefügt werden. 
---
= ONTAP SMB Sicherheitsrichtlinien erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Erstellen einer Dateisicherheitsrichtlinie für SVMs ist der dritte Schritt beim Konfigurieren und Anwenden von Zugriffssteuerungslisten auf eine Datei oder einen Ordner. Eine Richtlinie dient als Container für verschiedene Aufgaben, wobei jede Aufgabe einen einzelnen Eintrag darstellt, der auf Dateien oder Ordner angewendet werden kann. Aufgaben können der Sicherheitsrichtlinie später hinzugefügt werden.

.Über diese Aufgabe
Die Aufgaben, die Sie einer Sicherheitsrichtlinie hinzufügen, enthalten Verknüpfungen zwischen dem NTFS-Sicherheitsdeskriptor und den Datei- oder Ordnerpfaden. Daher sollte die Sicherheitsrichtlinie mit jedem SVM (das NTFS-Sicherheitsstil-Volumes oder gemischte Sicherheitsstil-Volumes enthält) verknüpft werden.

.Schritte
. Eine Sicherheitsrichtlinie erstellen: `vserver security file-directory policy create -vserver vserver_name -policy-name policy_name`
+
`vserver security file-directory policy create -policy-name policy1 -vserver vs1`

. Die Sicherheitsrichtlinie wird überprüft: `vserver security file-directory policy show`
+
[listing]
----

            vserver security file-directory policy show
               Vserver          Policy Name
             ------------     --------------
                 vs1              policy1
----

