---
permalink: smb-admin/default-administrative-shares-concept.html 
sidebar: sidebar 
keywords: create, cifs, server, storage, virtual, machine, svm, default, administrative, share, automatic, what the default administrative shares are 
summary: 'Wenn Sie einen CIFS-Server auf Ihrer Storage Virtual Machine (SVM) erstellen, werden automatisch standardmäßige administrative Freigaben erstellt. Sie sollten verstehen, was diese Standardfreigaben sind und wie sie verwendet werden.' 
---
= Erfahren Sie mehr über die standardmäßigen administrativen ONTAP-SMB-Freigaben
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie einen CIFS-Server auf Ihrer Storage Virtual Machine (SVM) erstellen, werden automatisch standardmäßige administrative Freigaben erstellt. Sie sollten verstehen, was diese Standardfreigaben sind und wie sie verwendet werden.

ONTAP erstellt beim Erstellen des CIFS-Servers die folgenden Standard-Administratorfreigaben:


NOTE: Ab ONTAP 9.8 wird der Anteil der Admin-Kosten nicht mehr standardmäßig erstellt.

* ipc-Kosten
* Admin-Kosten (nur ONTAP 9.7 und früher)
* c€


Da die mit dem Zeichen € enden Freigaben verborgene Freigaben sind, werden die standardmäßigen administrativen Freigaben nicht auf meinem Computer angezeigt, Sie können sie jedoch mithilfe von freigegebenen Ordnern anzeigen.



== Wie die standardanteile von ipc € und Admin€ verwendet werden

Die ipc-Kosten und die Admin-Dollar-Freigaben werden von ONTAP genutzt und können von Windows-Administratoren nicht für den Zugriff auf die auf der SVM gespeicherten Daten verwendet werden.

* ipc-Aktie
+
Der ipc-USD-Anteil ist eine Ressource, die die benannten Rohre teilt, die für die Kommunikation zwischen den Programmen wesentlich sind. Die ipc-€-Freigabe wird während der Remote-Administration eines Computers und bei der Anzeige der gemeinsam genutzten Ressourcen eines Computers verwendet. Sie können die Freigabereinstellungen, Freigabeigenschaften oder ACLs der ipc-€-Freigabe nicht ändern. Sie können die ipc-€-Freigabe auch nicht umbenennen oder löschen.

* Anteil von Admin-Dollar (nur ONTAP 9.7 und früher)
+

NOTE: Ab ONTAP 9.8 wird der Anteil der Admin-Kosten nicht mehr standardmäßig erstellt.

+
Der Anteil der Admin-Kosten wird bei der Remote-Administration der SVM verwendet. Der Pfad dieser Ressource ist immer der Pfad zum SVM-Stammverzeichnis. Sie können die Freigabeneinstellungen, Freigabeigenschaften oder ACLs für die USD-Freigabe nicht ändern. Sie können auch die „Administrator-Dollar-Freigabe“ nicht umbenennen oder löschen.





== Wie der Standardanteil c€ verwendet wird

Die C€-Freigabe ist eine administrative Freigabe, die der Cluster- oder SVM-Administrator zum Zugriff und Managen des SVM-Root-Volumes verwenden kann.

Die folgenden Merkmale sind die c-Dollar-Aktie:

* Der Pfad für diese Freigabe ist immer der Pfad zum SVM-Root-Volume und kann nicht geändert werden.
* Die Standard-ACL für die Aktie von c€ ist Administrator / Full Control.
+
Dieser Benutzer ist der BUILTIN\Administrator. Standardmäßig kann der BUILTIN\-Administrator Dateien und Ordner im zugeordneten Stammverzeichnis teilen und anzeigen, erstellen, ändern oder löschen. Beim Verwalten von Dateien und Ordnern in diesem Verzeichnis ist Vorsicht geboten.

* Sie können die ACL der c€-Aktie ändern.
* Sie können die Einstellungen für die gemeinsame Nutzung von € ändern und Eigenschaften freigeben.
* Sie können die Freigabe von € nicht löschen.
* Der SVM-Administrator kann über die Namespace-Verbindungen auf den Rest des SVM Namespace zugreifen und dabei die zugewiesene C€-Freigabe verwenden.
* Auf die C€-Aktie kann über die Microsoft Management Console zugegriffen werden.


.Verwandte Informationen
xref:configure-ntfs-windows-security-tab-task.adoc[Konfigurieren Sie erweiterte Dateiberechtigungen über die Registerkarte „Windows-Sicherheit“]
