---
permalink: smb-admin/deploy-offline-files-concept.html 
sidebar: sidebar 
keywords: important, guideline, understand, deploy, offline, file, home, directory, share, showsnapshot, property, set, home, directories, directory, guidelines for deploying offline files 
summary: Es gibt einige wichtige Richtlinien, die Sie verstehen müssen, wenn Sie Offline-Dateien auf Home-Verzeichnis-Shares bereitstellen, die die ShowSnapshot-Share-Eigenschaft auf Home-Verzeichnissen gesetzt haben. 
---
= Richtlinien für die Bereitstellung von Offline-Dateien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es gibt einige wichtige Richtlinien, die Sie verstehen müssen, wenn Sie Offline-Dateien auf Home Directory-Freigaben bereitstellen, die über die verfügen `showsnapshot` Auf Home Directorys festgelegte Freigabegenschaft.

Wenn der `showsnapshot` Die Eigenschaft „Freigabe“ wird auf einer Home Directory Freigabe festgelegt, bei der Offline-Dateien konfiguriert sind. Windows Clients speichern alle Snapshot Kopien unter dem `~snapshot` Ordner im Home-Verzeichnis des Benutzers.

Windows Clients speichern alle Snapshot Kopien unter dem Home Directory, wenn eine der folgenden Bedingungen zutrifft:

* Der Benutzer stellt das Home-Verzeichnis vom Client offline zur Verfügung.
+
Der Inhalt des `~snapshot` Ordner im Home-Verzeichnis ist enthalten und offline verfügbar gemacht.

* Der Benutzer konfiguriert die Ordnerumleitung, um einen Ordner wie umzuleiten `My Documents` Im Stammverzeichnis auf dem CIFS Server Share.
+
Einige Windows-Clients stellen den umgeleiteten Ordner möglicherweise automatisch offline zur Verfügung. Wenn der Ordner zum Stammverzeichnis des Home-Verzeichnisses umgeleitet wird, wird der angezeigt `~snapshot` Der Ordner ist im Offline-Inhalt des Cache enthalten.



[NOTE]
====
Offline-Dateibereitstellungen, bei denen der `~snapshot` Der Ordner ist in Offline-Dateien enthalten, sollte vermieden werden. Die Snapshot Kopien in `~snapshot` Der Ordner enthält alle Daten auf dem Volume, an dem ONTAP die Snapshot Kopie erstellt hat. Daher wird eine Offline-Kopie des erstellt `~snapshot` Der Ordner verbraucht großen lokalen Speicher auf dem Client, verbraucht während der Synchronisierung von Offline-Dateien Netzwerkbandbreite und erhöht die Zeit zur Synchronisierung von Offline-Dateien.

====