---
permalink: smb-admin/determine-statistics-objects-counters-available-task.html 
sidebar: sidebar 
keywords: obtain, information, cifs, smb, auditing, audit, branchcache, obtain, data, determine, determine which statistics objects and counters are available 
summary: Bevor Informationen über CIFS, SMB, Auditing und BranchCache Hash-Statistiken und die Performance überwacht werden können, müssen Unternehmen wissen, welche Objekte und Zähler verfügbar sind, von denen sie Daten beziehen können. 
---
= Legen Sie fest, welche Statistikobjekte und Zähler in ONTAP zur Verfügung stehen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Informationen über CIFS, SMB, Auditing und BranchCache Hash-Statistiken und die Performance überwacht werden können, müssen Unternehmen wissen, welche Objekte und Zähler verfügbar sind, von denen sie Daten beziehen können.

.Schritte
. Legen Sie die Berechtigungsebene auf erweitert fest: `set -privilege advanced`
. Führen Sie eine der folgenden Aktionen aus:
+
|===
| Sie können ermitteln, ob... | Eingeben... 


 a| 
Welche Objekte sind verfügbar
 a| 
`statistics catalog object show`



 a| 
Verfügbare spezifische Objekte
 a| 
`statistics catalog object show object object_name`



 a| 
Welche Zähler stehen zur Verfügung
 a| 
`statistics catalog counter show object object_name`

|===
+
Erfahren Sie mehr über `statistics catalog object show`, einschließlich der verfügbaren Objekte und Zähler , in der link:https://docs.netapp.com/us-en/ontap-cli/statistics-catalog-object-show.html["ONTAP-Befehlsreferenz"^].

. Kehren Sie zur Administrator-Berechtigungsebene zurück: `set -privilege admin`


.Beispiele
Mit dem folgenden Befehl werden Beschreibungen ausgewählter Statistikobjekte angezeigt, die mit dem CIFS- und SMB-Zugriff im Cluster in Verbindung stehen, wie sie auf der erweiterten Berechtigungsebene angezeigt werden:

[listing]
----
cluster1::> set -privilege advanced

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by support personnel.
Do you want to continue? {y|n}: y

cluster1::*> statistics catalog object show -object audit
    audit_ng                    CM object for exporting audit_ng performance counters

cluster1::*> statistics catalog object show -object cifs
    cifs                        The CIFS object reports activity of the
                                Common Internet File System protocol
                                ...

cluster1::*> statistics catalog object show -object nblade_cifs
    nblade_cifs                 The Common Internet File System (CIFS)
                                protocol is an implementation of the Server
                                ...

cluster1::*> statistics catalog object show -object smb1
    smb1                        These counters report activity from the SMB
                                revision of the protocol. For information
                                ...

cluster1::*> statistics catalog object show -object smb2
    smb2                        These counters report activity from the
                                SMB2/SMB3 revision of the protocol. For
                                ...

cluster1::*> statistics catalog object show -object hashd
    hashd                       The hashd object provides counters to measure
                                the performance of the BranchCache hash daemon.
cluster1::*> set -privilege admin
----
Mit dem folgenden Befehl werden Informationen zu einigen der Zähler für das `cifs` Objekt angezeigt, die auf der erweiterten Berechtigungsebene angezeigt werden:

[NOTE]
====
In diesem Beispiel werden nicht alle verfügbaren Zähler für das `cifs` Objekt angezeigt; die Ausgabe wird abgeschnitten.

====
[listing]
----
cluster1::> set -privilege advanced

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by support personnel.
Do you want to continue? {y|n}: y

cluster1::*> statistics catalog counter show -object cifs

Object: cifs
    Counter                     Description
    --------------------------- ----------------------------------------------
    active_searches             Number of active searches over SMB and SMB2
    auth_reject_too_many        Authentication refused after too many
                                requests were made in rapid succession
    avg_directory_depth         Average number of directories crossed by SMB
                                and SMB2 path-based commands
    ...                         ...

cluster2::> statistics start -object client -sample-id
Object: client
    Counter                                                     Value
    -------------------------------- --------------------------------
    cifs_ops                                                        0
    cifs_read_ops                                                   0
    cifs_read_recv_ops                                              0
    cifs_read_recv_size                                            0B
    cifs_read_size                                                 0B
    cifs_write_ops                                                  0
    cifs_write_recv_ops                                             0
    cifs_write_recv_size                                           0B
    cifs_write_size                                                0B
    instance_name                             vserver_1:10.72.205.179
    instance_uuid                                     2:10.72.205.179
    local_ops                                                       0
    mount_ops                                                       0


[...]
----
.Verwandte Informationen
xref:display-statistics-task.adoc[Statistiken für ONTAP NFS SVMs anzeigen]
