---
permalink: smb-admin/directory-case-sensitivity-share-multiprotocol-concept.html 
sidebar: sidebar 
keywords: create, share, svm, naming, name, scheme, distinguish, directory, difference, share, path, ensure, client, connect, desire, directory, path, directory case-sensitivity requirements when creating shares in a multiprotocol environment 
summary: Wenn Sie in einer SVM Freigaben erstellen, bei denen das Benennungsschema 8.3 verwendet wird, um zwischen Verzeichnisnamen zu unterscheiden, bei denen nur Groß-/Kleinschreibung zwischen den Namen besteht, müssen Sie den Namen 8.3 im Freigabepfad verwenden, um sicherzustellen, dass der Client eine Verbindung zum gewünschten Verzeichnispfad herstellt. 
---
= Erfahren Sie mehr über die Anforderungen an die Groß- und Kleinschreibung von ONTAP SMB-Verzeichnissen bei der Erstellung von Freigaben in einer Multi-Protokoll-Umgebung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie in einer SVM Freigaben erstellen, bei denen das Benennungsschema 8.3 verwendet wird, um zwischen Verzeichnisnamen zu unterscheiden, bei denen nur Groß-/Kleinschreibung zwischen den Namen besteht, müssen Sie den Namen 8.3 im Freigabepfad verwenden, um sicherzustellen, dass der Client eine Verbindung zum gewünschten Verzeichnispfad herstellt.

Im folgenden Beispiel wurden auf einem Linux-Client zwei Verzeichnisse mit dem Namen „`testdir`“ und „`TESTDIR`“ erstellt. Der Verbindungspfad des Volume mit den Verzeichnissen ist `/home`. Die erste Ausgabe stammt von einem Linux-Client und die zweite Ausgabe stammt von einem SMB-Client.

[listing]
----
 ls -l
drwxrwxr-x 2 user1 group1   4096 Apr 17 11:23 testdir
drwxrwxr-x 2 user1 group1   4096 Apr 17 11:24 TESTDIR
----
[listing]
----
dir

 Directory of Z:\

04/17/2015  11:23 AM    <DIR>          testdir
04/17/2015  11:24 AM    <DIR>          TESTDI~1
----
Wenn Sie eine Freigabe für das zweite Verzeichnis erstellen, müssen Sie den Namen 8.3 im Freigabepfad verwenden. In diesem Beispiel ist der Freigabepfad zum ersten Verzeichnis `/home/testdir` und der Freigabepfad zum zweiten Verzeichnis `/home/TESTDI~1` .
