---
permalink: smb-admin/disable-enable-branchcache-task.html 
sidebar: sidebar 
keywords: disable, enable, branchcache, storage, virtual, machine, svm, changing, change, operating, mode, operate, per-share, automatic, branch, office, client, cache 
summary: Sie können BranchCache auf der Storage Virtual Machine deaktivieren, indem Sie den BranchCache-Betriebsmodus auf deaktiviert ändern. Sie können BranchCache jederzeit aktivieren, indem Sie den Betriebsmodus so ändern, dass BranchCache-Dienste entweder pro Freigabe angeboten oder automatisch für alle Freigaben bereitgestellt werden. 
---
= Deaktivieren oder Aktivieren von BranchCache auf einer ONTAP SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie zuvor BranchCache konfiguriert haben, aber nicht möchten, dass die Clients der Zweigstelle zwischengespeicherte Inhalte verwenden, können Sie das Caching auf dem CIFS-Server deaktivieren. Sie müssen sich darüber im Klaren sein, was passiert, wenn Sie BranchCache deaktivieren. Sie können BranchCache auf der Storage Virtual Machine deaktivieren, indem Sie den BranchCache-Betriebsmodus auf „Deaktiviert“ ändern. Sie können BranchCache jederzeit wieder aktivieren, indem Sie den Betriebsmodus so ändern, dass entweder BranchCache-Dienste pro Freigabe oder automatisch für alle Freigaben angeboten werden.

Wenn Sie BranchCache deaktivieren, berechnet ONTAP nicht mehr die Hash-Werte und sendet die Metadaten nicht mehr an den Client, den die Anforderung stellt. Der Dateizugriff wird jedoch nicht unterbrochen. Wenn Clients mit BranchCache-Unterstützung anschließend Metadateninformationen für Inhalte anfordern, auf die sie zugreifen möchten, antwortet ONTAP mit einem Microsoft-definierten Fehler. Dies führt dazu, dass der Client eine zweite Anforderung sendet und den tatsächlichen Inhalt anfordert. Als Antwort auf die Inhaltsanfrage sendet der CIFS-Server die tatsächlichen Inhalte, die auf der Storage Virtual Machine (SVM) gespeichert sind.

Nachdem BranchCache auf dem CIFS-Server deaktiviert wurde, werben SMB-Freigaben nicht für BranchCache-Funktionen. Um auf Daten über neue SMB-Verbindungen zuzugreifen, führen Clients normale SMB-Leseanforderungen durch.

Sie können BranchCache jederzeit auf dem CIFS-Server reaktivieren.

* Da der Hash-Speicher beim Deaktivieren von BranchCache nicht gelöscht wird, kann ONTAP nach der erneuten Aktivierung von BranchCache die gespeicherten Hash-Werte verwenden, vorausgesetzt, der angeforderte Hash ist weiterhin gültig.
* Alle Clients, die während der Deaktivierung von BranchCache SMB-Verbindungen zu BranchCache-fähigen Freigaben hergestellt haben, erhalten keine Unterstützung für BranchCache, wenn BranchCache anschließend wieder aktiviert wird.
+
Der Grund dafür ist, dass ONTAP zum Zeitpunkt der Einrichtung der SMB-Session Support für BranchCache für eine Freigabe wirbt. Clients, die Sitzungen zu mit BranchCache-fähigen Freigaben erstellt haben, während BranchCache deaktiviert wurde, müssen die Verbindung trennen und eine erneute Verbindung herstellen, um zwischengespeicherte Inhalte für diese Freigabe zu verwenden.



[NOTE]
====
Wenn Sie den Hash-Speicher nicht speichern möchten, nachdem Sie BranchCache auf einem CIFS-Server deaktiviert haben, können Sie ihn manuell löschen. Wenn Sie BranchCache erneut aktivieren, müssen Sie sicherstellen, dass das Hash-Speicherverzeichnis vorhanden ist. Nach der reaktivierten BranchCache-Funktion werden die BranchCache-aktivierten Freigaben für BranchCache-Funktionen angekündigt. ONTAP erstellt neue Hash-Funktionen, wenn neue Anforderungen von Clients mit BranchCache-Unterstützung gestellt werden.

====
.Schritte
. Führen Sie den entsprechenden Befehl aus:
+
|===
| Ihr Ziel ist | Geben Sie anschließend Folgendes ein... 


 a| 
Deaktivieren Sie BranchCache
 a| 
`vserver cifs branchcache modify -vserver vserver_name -operating-mode disable`



 a| 
Aktivieren Sie BranchCache pro Freigabe
 a| 
`vserver cifs branchcache modify -vserver vserver_name -operating-mode per-share`



 a| 
Aktivieren Sie BranchCache für alle Freigaben
 a| 
`vserver cifs branchcache modify -vserver vserver_name -operating-mode all-shares`

|===
. Vergewissern Sie sich, dass der BranchCache-Betriebsmodus mit der gewünschten Einstellung konfiguriert ist: `vserver cifs branchcache show -vserver vserver_name`


.Beispiel
Im folgenden Beispiel wird BranchCache auf SVM vs1 deaktiviert:

[listing]
----
cluster1::> vserver cifs branchcache modify -vserver vs1 -operating-mode disable

cluster1::> vserver cifs branchcache show -vserver vs1

                                 Vserver: vs1
          Supported BranchCache Versions: enable_all
                      Path to Hash Store: /hash_data
          Maximum Size of the Hash Store: 20GB
Encryption Key Used to Secure the Hashes: -
        CIFS BranchCache Operating Modes: disable
----