---
permalink: smb-admin/disallow-users-groups-bypass-directory-traverse-task.html 
sidebar: sidebar 
keywords: user, traverse, directories, directory, path, file, permission, sechangenotifyprivilege, privilege, local, smb, group, storage, virtual, machine, svm, disallow users or groups from bypassing directory traverse checking 
summary: 'Wenn ein Benutzer nicht alle Verzeichnisse im Pfad zu einer Datei durchlaufen soll, weil der Benutzer im durchlaufenen Verzeichnis keine Berechtigungen hat, können Sie die SeChangeNotifyPrivilege-Berechtigung von lokalen SMB-Benutzern oder Gruppen auf Storage Virtual Machines (SVMs) entfernen.' 
---
= Verhindern Sie, dass Benutzer oder Gruppen die ONTAP SMB-Verzeichnisdurchquerungsprüfung umgehen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie nicht möchten, dass ein Benutzer alle Verzeichnisse im Pfad zu einer Datei durchläuft, weil der Benutzer keine Berechtigungen für das durchzogene Verzeichnis besitzt, können Sie die `SeChangeNotifyPrivilege` Berechtigung von lokalen SMB-Benutzern oder Gruppen auf Storage Virtual Machines (SVMs) entfernen.

.Bevor Sie beginnen
Der lokale Benutzer oder die Domänengruppe, aus der Berechtigungen entfernt werden sollen, muss bereits vorhanden sein.

.Über diese Aufgabe
Wenn Sie Berechtigungen von einem Domänenbenutzer oder einer Gruppe entfernen, kann ONTAP den Domänenbenutzer oder die Gruppe validieren, indem Sie sich an den Domänencontroller wenden. Der Befehl schlägt möglicherweise fehl, wenn ONTAP den Domain-Controller nicht kontaktieren kann.

.Schritte
. Prüfung der Bypass-Traverse deaktivieren: `vserver cifs users-and-groups privilege remove-privilege -vserver _vserver_name_ -user-or-group-name _name_ -privileges SeChangeNotifyPrivilege`
+
Der Befehl entfernt die `SeChangeNotifyPrivilege` Berechtigung vom lokalen oder Domänenbenutzer oder der Gruppe, die Sie mit dem Wert für den `-user-or-group-name _name_` Parameter angeben.

. Überprüfen Sie, ob für den angegebenen Benutzer oder die angegebene Gruppe die Umgehungsdurchgangsprüfung deaktiviert ist: `vserver cifs users-and-groups privilege show -vserver _vserver_name_ ‑user-or-group-name _name_`


.Beispiel
Mit dem folgenden Befehl werden Benutzer, die zur Gruppe „`EXAMPLE\eng`“ gehören, nicht mehr bei der Überprüfung der Verzeichnisübergang unterstützt:

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- -----------------------
vs1       EXAMPLE\eng           SeChangeNotifyPrivilege

cluster1::> vserver cifs users-and-groups privilege remove-privilege -vserver vs1 -user-or-group-name EXAMPLE\eng -privileges SeChangeNotifyPrivilege

cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- -----------------------
vs1       EXAMPLE\eng           -
----
.Verwandte Informationen
xref:allow-users-groups-bypass-directory-traverse-task.adoc[Benutzern oder Gruppen erlauben, die Überprüfung der Verzeichnisdurchgang zu umgehen]
