---
permalink: smb-admin/disallow-users-groups-bypass-directory-traverse-task.html 
sidebar: sidebar 
keywords: user, traverse, directories, directory, path, file, permission, sechangenotifyprivilege, privilege, local, smb, group, storage, virtual, machine, svm, disallow users or groups from bypassing directory traverse checking 
summary: Wenn Sie nicht möchten, dass ein Benutzer alle Verzeichnisse im Pfad zu einer Datei durchläuft, weil der Benutzer keine Berechtigungen für das durchlaufene Verzeichnis hat, können Sie die SeChangeNotifyPrivilege-Berechtigung von lokalen SMB-Benutzern oder -Gruppen auf Storage Virtual Machines entfernen. 
---
= Benutzern oder Gruppen das Umgehen der ONTAP SMB-Verzeichnisdurchlaufprüfung untersagen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn nicht gewünscht ist, dass ein Benutzer alle Verzeichnisse im Pfad zu einer Datei durchläuft, weil der Benutzer keine Berechtigungen für das durchlaufene Verzeichnis hat, kann die  `SeChangeNotifyPrivilege` Berechtigung von lokalen SMB-Benutzern oder Gruppen auf Storage Virtual Machines (SVMs) entfernt werden.

.Bevor Sie beginnen
Der lokale oder Domänenbenutzer oder die Gruppe, von der Berechtigungen entfernt werden, muss bereits existieren.

.Über diese Aufgabe
Beim Entfernen von Berechtigungen von einem Domänenbenutzer oder einer Domänengruppe kann ONTAP den Domänenbenutzer oder die Domänengruppe durch Kontaktaufnahme mit dem Domänencontroller validieren. Der Befehl kann fehlschlagen, wenn ONTAP den Domänencontroller nicht erreichen kann.

.Schritte
. Umgehung der Traversierungsprüfung nicht zulassen: `vserver cifs users-and-groups privilege remove-privilege -vserver _vserver_name_ -user-or-group-name _name_ -privileges SeChangeNotifyPrivilege`
+
Der Befehl entfernt die `SeChangeNotifyPrivilege`Berechtigung vom lokalen oder Domänen-Benutzer oder der Gruppe, die mit dem Wert für den `-user-or-group-name _name_`Parameter angegeben wird.

. Es sollte überprüft werden, ob für den angegebenen Benutzer oder die Gruppe die Umgehung der Traversierungsprüfung deaktiviert ist: `vserver cifs users-and-groups privilege show -vserver _vserver_name_ ‑user-or-group-name _name_`


.Beispiel
Der folgende Befehl verhindert, dass Benutzer der Gruppe "`EXAMPLE\eng`" die Verzeichnisdurchsuchungsprüfung umgehen:

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- -----------------------
vs1       EXAMPLE\eng           SeChangeNotifyPrivilege

cluster1::> vserver cifs users-and-groups privilege remove-privilege -vserver vs1 -user-or-group-name EXAMPLE\eng -privileges SeChangeNotifyPrivilege

cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- -----------------------
vs1       EXAMPLE\eng           -
----
.Verwandte Informationen
xref:allow-users-groups-bypass-directory-traverse-task.adoc[Benutzern oder Gruppen das Umgehen der Verzeichnisdurchlaufprüfung erlauben]
