---
permalink: smb-admin/disable-reenable-branchcache-server-concept.html 
sidebar: sidebar 
keywords: previous, configure, branchcache, branch, office, client, cache, content, disable, what happens when you disable or reenable branchcache on the cifs server 
summary: Wenn Sie zuvor BranchCache konfiguriert haben, die Filialclients aber nicht möchten, dass sie zwischengespeicherte Inhalte verwenden, können Sie das Caching auf dem CIFS-Server deaktivieren. Wenn Sie BranchCache deaktivieren, müssen Sie sich bewusst sein, was passiert. 
---
= Erfahren Sie, was passiert, wenn Sie BranchCache auf ONTAP SMB-Servern deaktivieren oder erneut aktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie zuvor BranchCache konfiguriert haben, die Filialclients aber nicht möchten, dass sie zwischengespeicherte Inhalte verwenden, können Sie das Caching auf dem CIFS-Server deaktivieren. Wenn Sie BranchCache deaktivieren, müssen Sie sich bewusst sein, was passiert.

Wenn Sie BranchCache deaktivieren, berechnet ONTAP nicht mehr die Hash-Werte und sendet die Metadaten nicht mehr an den Client, den die Anforderung stellt. Der Dateizugriff wird jedoch nicht unterbrochen. Wenn Clients mit BranchCache-Unterstützung anschließend Metadateninformationen für Inhalte anfordern, auf die sie zugreifen möchten, antwortet ONTAP mit einem Microsoft-definierten Fehler. Dies führt dazu, dass der Client eine zweite Anforderung sendet und den tatsächlichen Inhalt anfordert. Als Antwort auf die Inhaltsanfrage sendet der CIFS-Server die tatsächlichen Inhalte, die auf der Storage Virtual Machine (SVM) gespeichert sind.

Nachdem BranchCache auf dem CIFS-Server deaktiviert wurde, werben SMB-Freigaben nicht für BranchCache-Funktionen. Um auf Daten über neue SMB-Verbindungen zuzugreifen, führen Clients normale SMB-Leseanforderungen durch.

Sie können BranchCache jederzeit auf dem CIFS-Server reaktivieren.

* Da der Hash-Speicher beim Deaktivieren von BranchCache nicht gelöscht wird, kann ONTAP nach der erneuten Aktivierung von BranchCache die gespeicherten Hash-Werte verwenden, vorausgesetzt, der angeforderte Hash ist weiterhin gültig.
* Alle Clients, die während der Deaktivierung von BranchCache SMB-Verbindungen zu BranchCache-fähigen Freigaben hergestellt haben, erhalten keine Unterstützung für BranchCache, wenn BranchCache anschließend wieder aktiviert wird.
+
Der Grund dafür ist, dass ONTAP zum Zeitpunkt der Einrichtung der SMB-Session Support für BranchCache für eine Freigabe wirbt. Clients, die Sitzungen zu mit BranchCache-fähigen Freigaben erstellt haben, während BranchCache deaktiviert wurde, müssen die Verbindung trennen und eine erneute Verbindung herstellen, um zwischengespeicherte Inhalte für diese Freigabe zu verwenden.



[NOTE]
====
Wenn Sie den Hash-Speicher nicht speichern möchten, nachdem Sie BranchCache auf einem CIFS-Server deaktiviert haben, können Sie ihn manuell löschen. Wenn Sie BranchCache erneut aktivieren, müssen Sie sicherstellen, dass das Hash-Speicherverzeichnis vorhanden ist. Nach der reaktivierten BranchCache-Funktion werden die BranchCache-aktivierten Freigaben für BranchCache-Funktionen angekündigt. ONTAP erstellt neue Hash-Funktionen, wenn neue Anforderungen von Clients mit BranchCache-Unterstützung gestellt werden.

====