---
permalink: smb-admin/display-open-files-task.html 
sidebar: sidebar 
keywords: display, information, smb, file, connection, session, if, list, volume, share, name, contiuous, available, protection, level, helpful, nondisruptive, operation, display information about open smb files 
summary: Es lassen sich Informationen zu geöffneten SMB-Dateien anzeigen, einschließlich der SMB-Verbindungs- und Sitzungs-ID, des Host-Volumes, des Freigabenamens und des Freigabepfads. Informationen zum Schutzlevel der kontinuierlichen Verfügbarkeit einer Datei können angezeigt werden, was hilfreich ist, um festzustellen, ob sich eine geöffnete Datei in einem Zustand befindet, der unterbrechungsfreie Vorgänge unterstützt. 
---
= Informationen zu geöffneten ONTAP SMB-Dateien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es lassen sich Informationen zu geöffneten SMB-Dateien anzeigen, einschließlich der SMB-Verbindungs- und Sitzungs-ID, des Host-Volumes, des Freigabenamens und des Freigabepfads. Es lassen sich Informationen zum kontinuierlich verfügbaren Schutzniveau einer Datei anzeigen, was hilfreich ist, um festzustellen, ob sich eine geöffnete Datei in einem Zustand befindet, der unterbrechungsfreie Vorgänge unterstützt.

.Über diese Aufgabe
Informationen über geöffnete Dateien in einer bestehenden SMB-Sitzung können angezeigt werden. Die angezeigten Informationen sind hilfreich, wenn SMB-Sitzungsinformationen für bestimmte Dateien innerhalb einer SMB-Sitzung ermittelt werden müssen.

Wenn Sie beispielsweise eine SMB-Sitzung haben, bei der einige der geöffneten Dateien mit kontinuierlich verfügbarem Schutz geöffnet sind und andere nicht (der Wert für das  `-continuously-available` Feld in  `vserver cifs session show` der Befehlsausgabe ist  `Partial`), lässt sich mit diesem Befehl ermitteln, welche Dateien nicht kontinuierlich verfügbar sind.

Informationen zu allen geöffneten Dateien in etablierten SMB-Sitzungen auf Storage Virtual Machines (SVMs) können in zusammengefasster Form angezeigt werden, wenn der  `vserver cifs session file show` Befehl ohne optionale Parameter verwendet wird.

In vielen Fällen ist die Ausgabemenge jedoch groß. Die angezeigten Informationen lassen sich durch Angabe optionaler Parameter anpassen. Dies kann hilfreich sein, wenn Informationen nur für eine kleine Teilmenge der geöffneten Dateien angezeigt werden sollen.

* Der optionale  `-fields`Parameter ermöglicht die Anzeige der Ausgabe auf den von Ihnen ausgewählten Feldern.
+
Sie können diesen Parameter entweder allein oder in Kombination mit anderen optionalen Parametern verwenden.

* Sie können den  `-instance` Parameter verwenden, um detaillierte Informationen über geöffnete SMB-Dateien anzuzeigen.
+
Sie können diesen Parameter entweder allein oder in Kombination mit anderen optionalen Parametern verwenden.



.Schritt
. Führen Sie eine der folgenden Aktionen aus:
+
|===
| Wenn Sie geöffnete SMB-Dateien anzeigen möchten... | Führen Sie den folgenden Befehl aus... 


 a| 
In zusammengefasster Form auf der SVM
 a| 
`vserver cifs session file show -vserver vserver_name`



 a| 
Auf einem bestimmten Knoten
 a| 
`vserver cifs session file show -vserver vserver_name -node {node_name|local}`



 a| 
Bei einer bestimmten Datei-ID
 a| 
`vserver cifs session file show -vserver vserver_name -file-id integer`



 a| 
Bei einer bestimmten SMB-Verbindungs-ID
 a| 
`vserver cifs session file show -vserver vserver_name -connection-id integer`



 a| 
Bei einer bestimmten SMB-Sitzungs-ID
 a| 
`vserver cifs session file show -vserver vserver_name -session-id integer`



 a| 
Auf dem angegebenen Hosting Aggregat
 a| 
`vserver cifs session file show -vserver vserver_name -hosting-aggregate aggregate_name`



 a| 
Auf dem angegebenen Volume
 a| 
`vserver cifs session file show -vserver vserver_name -hosting-volume volume_name`



 a| 
Auf der angegebenen SMB-Freigabe
 a| 
`vserver cifs session file show -vserver vserver_name -share share_name`



 a| 
Auf dem angegebenen SMB-Pfad
 a| 
`vserver cifs session file show -vserver vserver_name -path path`



 a| 
Mit dem festgelegten Niveau an kontinuierlich verfügbarem Schutz
 a| 
`vserver cifs session file show -vserver vserver_name -continuously-available {No|Yes}`

[NOTE]
====
Wenn der Status „Dauerhaft verfügbar“  `No` ist, bedeutet dies, dass diese geöffneten Dateien nicht in der Lage sind, sich nach einer Übernahme und Rückgabe unterbrechungsfrei zu erholen. Sie können sich auch nicht von einer allgemeinen Aggregat-Verschiebung zwischen Partnern in einer Hochverfügbarkeitsbeziehung erholen.

====


 a| 
Mit dem angegebenen wiederverbundenen Zustand
 a| 
`vserver cifs session file show -vserver vserver_name -reconnected {No|Yes}`

[NOTE]
====
Wenn der wiederverbundene Status  `No` ist, wird die geöffnete Datei nach einem Verbindungsabbruch nicht wieder verbunden. Dies kann bedeuten, dass die Datei nie getrennt wurde oder dass die Datei getrennt wurde und nicht erfolgreich wieder verbunden ist. Wenn der wiederverbundene Status  `Yes` ist, bedeutet dies, dass die geöffnete Datei nach einem Verbindungsabbruch erfolgreich wieder verbunden wurde.

====
|===
+
Es gibt zusätzliche optionale Parameter, mit denen Sie die Ausgaberesultate verfeinern können. Weitere Informationen zu  `vserver cifs session file show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-session-file-show.html["ONTAP-Befehlsreferenz"^].



.Beispiele
Das folgende Beispiel zeigt Informationen über geöffnete Dateien auf SVM vs1:

[listing]
----
cluster1::> vserver cifs session file show -vserver vs1
Node:       node1
Vserver:    vs1
Connection: 3151274158
Session:    1
File    File      Open Hosting               Continuously
ID      Type      Mode Volume    Share       Available
------- --------- ---- --------- ----------- ------------
41      Regular   r    data      data        Yes
Path: \mytest.rtf
----
Das folgende Beispiel zeigt detaillierte Informationen zu geöffneten SMB-Dateien mit der Datei-ID 82 auf SVM vs1:

[listing]
----
cluster1::> vserver cifs session file show -vserver vs1 -file-id 82 -instance

                  Node: node1
               Vserver: vs1
               File ID: 82
         Connection ID: 104617
            Session ID: 1
             File Type: Regular
             Open Mode: rw
Aggregate Hosting File: aggr1
   Volume Hosting File: data1
            CIFS Share: data1
  Path from CIFS Share: windows\win8\test\test.txt
            Share Mode: rw
           Range Locks: 1
Continuously Available: Yes
           Reconnected: No
----
.Verwandte Informationen
xref:display-session-task.adoc[Sitzungsinformationen anzeigen]
