---
permalink: smb-admin/display-volume-mount-junction-point-task.html 
sidebar: sidebar 
keywords: display, information, mount, volume, storage, virtual, machine, svm, junction, point, namespace, display volume mount and junction point information 
summary: Sie können Informationen zu eingebundenen Volumes für Storage Virtual Machines und die Verbindungspunkte anzeigen, an denen die Volumes eingebunden sind. Es lässt sich auch feststellen, welche Volumes nicht an einen Verbindungspunkt eingebunden sind. Diese Informationen ermöglichen ein besseres Verständnis und eine effektivere Verwaltung Ihres SVM-Namespaces. 
---
= Informationen zu ONTAP SMB-Volume-Mounts und Verbindungspunkten anzeigen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Informationen zu eingebundenen Volumes für Storage Virtual Machines (SVMs) und den Verbindungspunkten, an die die Volumes eingebunden sind, anzeigen. Es lässt sich auch feststellen, welche Volumes nicht an einen Verbindungspunkt eingebunden sind. Diese Informationen ermöglichen ein besseres Verständnis und eine effektivere Verwaltung Ihres SVM-Namespaces.

.Schritte
. Die gewünschte Aktion ausführen:
+
|===
| Wenn Sie anzeigen möchten... | Geben Sie den Befehl ein... 


 a| 
Zusammenfassende Informationen zu eingebundenen und nicht eingebundenen Volumes auf dem SVM
 a| 
`volume show -vserver vserver_name -junction`



 a| 
Detaillierte Informationen zu eingebundenen und nicht eingebundenen Volumes auf dem SVM
 a| 
`volume show -vserver vserver_name -volume volume_name -instance`



 a| 
Spezifische Informationen zu eingebundenen und nicht eingebundenen Volumes auf dem SVM
 a| 
.. Bei Bedarf lassen sich die gültigen Felder für den  `-fields`Parameter mit folgendem Befehl anzeigen: `volume show -fields ?`
.. Die gewünschten Informationen werden mit dem  `-fields` Parameter angezeigt: volume show -vserver vserver_name -fields fieldname,...


|===


.Beispiele
Das folgende Beispiel zeigt eine Zusammenfassung der eingebundenen und nicht eingebundenen Volumes auf SVM vs1:

[listing]
----
cluster1::> volume show -vserver vs1 -junction
                     Junction                 Junction
Vserver   Volume     Active   Junction Path   Path Source
--------- ---------- -------- --------------- -----------
vs1       data       true     /data           RW_volume
vs1       home4      true     /eng/home       RW_volume
vs1       vs1_root   -        /               -
vs1       sales      true     /sales          RW_volume
----
Das folgende Beispiel zeigt Informationen zu bestimmten Feldern für Volumes auf SVM vs2:

[listing]
----
cluster1::> volume show -vserver vs2 -fields vserver,volume,aggregate,size,state,type,security-style,junction-path,junction-parent,node
vserver volume   aggregate size state  type security-style junction-path junction-parent node
------- ------   --------- ---- ------ ---- -------------- ------------- --------------- -----
vs2     data1    aggr3     2GB  online RW   unix           -             -               node3
vs2     data2    aggr3     1GB  online RW   ntfs           /data2        vs2_root        node3
vs2     data2_1  aggr3     8GB  online RW   ntfs           /data2/d2_1   data2           node3
vs2     data2_2  aggr3     8GB  online RW   ntfs           /data2/d2_2   data2           node3
vs2     pubs     aggr1     1GB  online RW   unix           /publications vs2_root        node1
vs2     images   aggr3     2TB  online RW   ntfs           /images       vs2_root        node3
vs2     logs     aggr1     1GB  online RW   unix           /logs         vs2_root        node1
vs2     vs2_root aggr3     1GB  online RW   ntfs           /             -               node3
----