---
permalink: smb-admin/display-discovered-trusted-domains-task.html 
sidebar: sidebar 
keywords: display, information, discover, trust, domain, cifs, server, home, contain, computer, trusted-domain, list, display information about discover trusted domains 
summary: Informationen zu den erkannten vertrauenswürdigen Domänen für die CIFS-Server Heimatdomäne, also die Domäne, die das Computerkonto des CIFS-Servers enthält, können angezeigt werden. Dies kann hilfreich sein, wenn Sie wissen möchten, welche vertrauenswürdigen Domänen ermittelt wurden und wie sie in der Liste der ermittelten vertrauenswürdigen Domänen angeordnet sind. 
---
= Informationen zu erkannten vertrauenswürdigen ONTAP SMB-Domänen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Informationen zu den ermittelten vertrauenswürdigen Domänen für die Heimatdomäne des CIFS-Servers anzeigen, also die Domäne, die das Computerkonto des CIFS-Servers enthält. Dies kann hilfreich sein, wenn Sie wissen möchten, welche vertrauenswürdigen Domänen ermittelt wurden und wie sie in der Liste der ermittelten vertrauenswürdigen Domänen angeordnet sind.

.Über diese Aufgabe
Es werden nur Domänen mit bidirektionalen Vertrauensstellungen zur Heimatdomäne ermittelt. Da der Domänencontroller (DC) der Heimatdomäne die Liste der vertrauenswürdigen Domänen in einer vom DC festgelegten Reihenfolge zurückgibt, lässt sich die Reihenfolge der Domänen in der Liste nicht vorhersagen. Durch die Anzeige der Liste der vertrauenswürdigen Domänen lässt sich die Suchreihenfolge für Namenszuordnungen in mehreren Domänen ermitteln.

Die angezeigten Informationen zur vertrauenswürdigen Domäne sind nach Knoten und Storage Virtual Machine (SVM) gruppiert.

.Schritt
. Informationen über erkannte vertrauenswürdige Domänen werden mit dem  `vserver cifs domain trusts show` Befehl angezeigt.
+
`vserver cifs domain trusts show -vserver vs1`

+
[listing]
----
   Node: node1
Vserver: vs1

Home Domain            Trusted Domain
---------------------  -----------------------------------
EXAMPLE.COM            CIFS1.EXAMPLE.COM,
                       CIFS2.EXAMPLE.COM
                       EXAMPLE.COM

   Node: node2
Vserver: vs1

Home Domain            Trusted Domain
---------------------  -----------------------------------
EXAMPLE.COM            CIFS1.EXAMPLE.COM,
                       CIFS2.EXAMPLE.COM
                       EXAMPLE.COM
----


.Verwandte Informationen
xref:reset-rediscover-trusted-domains-task.adoc[Vertrauenswürdige Domänen zurücksetzen und neu erkennen]
