---
permalink: smb-admin/display-local-groups-task.html 
sidebar: sidebar 
keywords: display, list, local, group, configure, cluster, storage, virtual, machine, svm, information, useful, troubleshoot, issue, data, user-right, privilege, display information about local groups 
summary: 'Sie können eine Liste aller auf dem Cluster konfigurierten lokalen Gruppen oder auf einer angegebenen SVM (Storage Virtual Machine) anzeigen. Diese Informationen können nützlich sein, wenn Sie Probleme beim Dateizugriff bei den Daten in der SVM oder Problemen mit den Benutzerrechten (Berechtigungen) auf der SVM beheben.' 
---
= Zeigt Informationen zu lokalen Gruppen an
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Liste aller auf dem Cluster konfigurierten lokalen Gruppen oder auf einer angegebenen SVM (Storage Virtual Machine) anzeigen. Diese Informationen können nützlich sein, wenn Sie Probleme beim Dateizugriff bei den Daten in der SVM oder Problemen mit den Benutzerrechten (Berechtigungen) auf der SVM beheben.

.Schritt
. Führen Sie eine der folgenden Aktionen aus:
+
|===
| Wenn Sie Informationen über... | Geben Sie den Befehl ein... 


 a| 
Alle lokalen Gruppen im Cluster
 a| 
`vserver cifs users-and-groups local-group show`



 a| 
Alle lokalen Gruppen auf der SVM
 a| 
`vserver cifs users-and-groups local-group show -vserver _vserver_name_`

|===
+
Es gibt weitere optionale Parameter, die Sie bei der Ausführung dieses Befehls auswählen können. Weitere Informationen finden Sie auf der man-Seite.



.Beispiel
Das folgende Beispiel zeigt Informationen zu allen lokalen Gruppen auf SVM vs1:

[listing]
----
cluster1::> vserver cifs users-and-groups local-group show -vserver vs1
Vserver  Group Name                  Description
-------- --------------------------- ----------------------------
vs1      BUILTIN\Administrators      Built-in Administrators group
vs1      BUILTIN\Backup Operators    Backup Operators group
vs1      BUILTIN\Power Users         Restricted administrative privileges
vs1      BUILTIN\Users               All users
vs1      CIFS_SERVER\engineering
vs1      CIFS_SERVER\sales
----