---
permalink: smb-admin/display-preferred-trusted-domain-list-task.html 
sidebar: sidebar 
keywords: display, information, trust, domain, perfer, list, order, multidomain, name, map, search, enable, configure, alternative, display information about the preferred trusted domain list 
summary: Sie können Informationen darüber anzeigen, welche vertrauenswürdigen Domänen in der Liste der bevorzugten vertrauenswürdigen Domänen enthalten sind und in welcher Reihenfolge sie durchsucht werden, wenn multidomain Namenszuordnungs-Suchen aktiviert sind. Eine bevorzugte vertrauenswürdige Domänenliste kann als Alternative zur automatisch ermittelten Liste vertrauenswürdiger Domänen konfiguriert werden. 
---
= Informationen zur bevorzugten vertrauenswürdigen ONTAP SMB-Domänenliste anzeigen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Informationen darüber anzeigen, welche vertrauenswürdigen Domänen in der Liste der bevorzugten vertrauenswürdigen Domänen enthalten sind und in welcher Reihenfolge sie durchsucht werden, wenn multidomain Namenszuordnungs-Suchen aktiviert sind. Eine bevorzugte vertrauenswürdige Domänenliste kann als Alternative zur automatisch ermittelten Liste vertrauenswürdiger Domänen konfiguriert werden.

.Schritte
. Führen Sie eine der folgenden Aktionen aus:
+
|===
| Wenn Informationen zu Folgendem angezeigt werden sollen... | Verwenden Sie den Befehl... 


 a| 
Alle bevorzugten vertrauenswürdigen Domänen im Cluster, gruppiert nach Storage Virtual Machine (SVM)
 a| 
`vserver cifs domain name-mapping-search show`



 a| 
Alle bevorzugten vertrauenswürdigen Domänen für eine bestimmte SVM
 a| 
`vserver cifs domain name-mapping-search show -vserver _vserver_name_`

|===
+
Der folgende Befehl zeigt Informationen zu allen bevorzugten vertrauenswürdigen Domänen im Cluster an:

+
[listing]
----
cluster1::> vserver cifs domain name-mapping-search show
Vserver         Trusted Domains
--------------  ----------------------------------
vs1             CIFS1.EXAMPLE.COM
----


.Verwandte Informationen
xref:add-remove-replace-trusted-domains-preferred-lists-task.adoc[Vertrauenswürdige Domänen in bevorzugten Listen hinzufügen, entfernen oder ersetzen]
