---
permalink: smb-admin/display-types-users-connected-task.html 
sidebar: sidebar 
keywords: display, information, type, connect, smb, session, appropriate, type, storage, virtual, machine, svm 
summary: 'Sie können Informationen darüber anzeigen, welche Benutzertypen über SMB-Sitzungen verbunden sind. Dadurch kann sichergestellt werden, dass nur der geeignete Benutzertyp über SMB-Sitzungen auf der Storage Virtual Machine (SVM) verbunden ist.' 
---
= Anzeige von Informationen darüber, welche Benutzertypen über SMB-Sitzungen verbunden sind
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Informationen darüber anzeigen, welche Benutzertypen über SMB-Sitzungen verbunden sind. Dadurch kann sichergestellt werden, dass nur der geeignete Benutzertyp über SMB-Sitzungen auf der Storage Virtual Machine (SVM) verbunden ist.

.Über diese Aufgabe
Die folgenden Benutzertypen können sich über SMB-Sitzungen verbinden:

* `local-user`
+
Wird als lokaler CIFS-Benutzer authentifiziert

* `domain-user`
+
Wird als Domain-Benutzer authentifiziert (entweder über die Home-Domain des CIFS-Servers oder über eine vertrauenswürdige Domäne)

* `guest-user`
+
Authentifizierung als Gastbenutzer

* `anonymous-user`
+
Authentifiziert als anonymer oder Null-Benutzer



.Schritte
. Legen Sie fest, welcher Benutzertyp über eine SMB-Sitzung verbunden ist: `vserver cifs session show -vserver _vserver_name_ -windows-user _windows_user_name_ -fields windows-user,address,lif-address,user-type`
+
|===
| Wenn Benutzerinformationen für etablierte Sitzungen angezeigt werden sollen... | Geben Sie den folgenden Befehl ein... 


 a| 
Für alle Sitzungen mit einem angegebenen Benutzertyp
 a| 
`vserver cifs session show -vserver _vserver_name_ -user-type {local-user|domain-user|guest-user|anonymous-user}`



 a| 
Für einen bestimmten Benutzer
 a| 
`vserver cifs session show -vserver _vserver_name_ -windows-user _windows_user_name_ -fields windows-user,address,lif-address,user-type`

|===


.Beispiele
Mit dem folgenden Befehl werden Sitzungsinformationen zum Benutzertyp für Sitzungen auf SVM vs1 angezeigt, die vom Benutzer „` iePubs\user1`“ eingerichtet wurden:

[listing]
----
cluster1::> vserver cifs session show -vserver pub1 -windows-user iepubs\user1 -fields windows-user,address,lif-address,user-type
node      vserver session-id connection-id lif-address  address       windows-user         user-type
--------- ------- ---------- ------------- ------------ ------------- -------------------- -----------
pub1node1 pub1    1          3439441860    10.0.0.1     10.1.1.1      IEPUBS\user1         domain-user
----