---
permalink: smb-admin/display-file-security-mixed-style-volumes-task.html 
sidebar: sidebar 
keywords: display, information, file, directory, security, mix, security-style, volume, style, unix, owner, group, result, troubleshoot, display information about file security, on mixed security-style volumes 
summary: Sie können Informationen über die Datei- und Verzeichnissicherheit auf Volumes mit gemischter Sicherheitsart anzeigen, einschließlich des Sicherheitsstils und der effektiven Sicherheitsstile, der angewandten Berechtigungen und Informationen zu UNIX-Eigentümern und -Gruppen. Sie können die Ergebnisse verwenden, um Ihre Sicherheitskonfiguration zu überprüfen oder Probleme mit dem Dateizugriff zu beheben. 
---
= Zeigt Informationen zur Dateisicherheit auf Volumes mit gemischter Sicherheitsart an
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Informationen über die Datei- und Verzeichnissicherheit auf Volumes mit gemischter Sicherheitsart anzeigen, einschließlich des Sicherheitsstils und der effektiven Sicherheitsstile, der angewandten Berechtigungen und Informationen zu UNIX-Eigentümern und -Gruppen. Sie können die Ergebnisse verwenden, um Ihre Sicherheitskonfiguration zu überprüfen oder Probleme mit dem Dateizugriff zu beheben.

.Über diese Aufgabe
Sie müssen den Namen der Storage Virtual Machine (SVM) und den Pfad zu den Daten angeben, deren Sicherheitsinformationen für Datei oder Ordner angezeigt werden sollen. Sie können die Ausgabe als Übersichtsformular oder als detaillierte Liste anzeigen.

* Gemischte sicherheitsrelevante Volumes und qtrees können einige Dateien und Ordner enthalten, die UNIX-Dateiberechtigungen verwenden, entweder Modus-Bits oder NFSv4-ACLs und einige Dateien und Verzeichnisse, die NTFS-Dateiberechtigungen verwenden.
* Die oberste Ebene eines gemischten Volumes im Sicherheitsstil kann entweder UNIX oder NTFS effektiven Schutz haben.
* Die ACL-Ausgabe wird nur für Dateien und Ordner mit NTFS- oder NFSv4-Sicherheit angezeigt.
+
Dieses Feld ist leer für Dateien und Verzeichnisse, die UNIX-Sicherheit verwenden, die nur Modus-Bit-Berechtigungen angewendet haben (keine NFSv4 ACLs).

* Die Felder „Eigentümer“ und „Gruppenausgabe“ in der ACL-Ausgabe gelten nur bei NTFS-Sicherheitsdeskriptoren.
* Da die Sicherheit des Storage-Level Access Guard auf einem Volume oder qtree mit gemischtem Sicherheitsstil konfiguriert werden kann, selbst wenn der effektive Sicherheitsstil des Volume Root oder qtree UNIX ist, Die Ausgabe für einen Volume oder qtree-Pfad, wo Storage-Level Access Guard konfiguriert ist, kann möglicherweise sowohl UNIX Dateiberechtigungen als auch Storage-Level Access Guard ACLs anzeigen.
* Wenn der im Befehl eingegebene Pfad zu Daten mit NTFS-effektiver Sicherheit besteht, zeigt die Ausgabe auch Informationen über Dynamic Access Control Aces an, wenn Dynamic Access Control für den angegebenen Datei- oder Verzeichnispfad konfiguriert ist.


.Schritt
. Anzeige der Dateisicherheitseinstellungen und des Verzeichnisses mit der gewünschten Detailebene:
+
|===
| Informationen anzeigen... | Geben Sie den folgenden Befehl ein... 


 a| 
In zusammengefassener Form
 a| 
`vserver security file-directory show -vserver vserver_name -path path`



 a| 
Mit mehr Details
 a| 
`vserver security file-directory show -vserver vserver_name -path path -expand-mask true`

|===


.Beispiele
Im folgenden Beispiel werden die Sicherheitsinformationen über den Pfad angezeigt `/projects` In SVM vs1 als erweiterte Maske. Dieser Pfad im gemischten Sicherheitsstil verfügt über effektive UNIX-Sicherheit.

[listing]
----
cluster1::> vserver security file-directory show -vserver vs1 -path /projects -expand-mask true

                Vserver: vs1
              File Path: /projects
      File Inode Number: 78
         Security Style: mixed
        Effective Style: unix
         DOS Attributes: 10
 DOS Attributes in Text: ----D---
Expanded Dos Attributes: 0x10
     ...0 .... .... .... = Offline
     .... ..0. .... .... = Sparse
     .... .... 0... .... = Normal
     .... .... ..0. .... = Archive
     .... .... ...1 .... = Directory
     .... .... .... .0.. = System
     .... .... .... ..0. = Hidden
     .... .... .... ...0 = Read Only
           Unix User Id: 0
          Unix Group Id: 1
         Unix Mode Bits: 700
 Unix Mode Bits in Text: rwx------
                   ACLs: -
----
Im folgenden Beispiel werden die Sicherheitsinformationen über den Pfad angezeigt `/data` In SVM vs1. Dieser Pfad mit gemischtem Sicherheitsstil verfügt über eine NTFS-effektive Sicherheit.

[listing]
----
cluster1::> vserver security file-directory show -vserver vs1 -path /data

                                 Vserver: vs1
                               File Path: /data
                       File Inode Number: 544
                          Security Style: mixed
                         Effective Style: ntfs
                          DOS Attributes: 10
                  DOS Attributes in Text: ----D---
                 Expanded Dos Attributes: -
                            Unix User Id: 0
                           Unix Group Id: 0
                          Unix Mode Bits: 777
                  Unix Mode Bits in Text: rwxrwxrwx
                                    ACLs: NTFS Security Descriptor
                                          Control:0x8004
                                          Owner:BUILTIN\Administrators
                                          Group:BUILTIN\Administrators
                                          DACL - ACEs
                                            ALLOW-Everyone-0x1f01ff
                                            ALLOW-Everyone-0x10000000-OI|CI|IO
----
Im folgenden Beispiel werden die Sicherheitsinformationen zum Volume im Pfad angezeigt `/datavol5` In SVM vs1. Auf der obersten Ebene dieses gemischten Volumes im Sicherheitsstil ist UNIX effektive Sicherheit. Das Volume verfügt über Sicherheit auf Storage-Ebene beim Access Guard.

[listing]
----
cluster1::> vserver security file-directory show -vserver vs1 -path /datavol5
                Vserver: vs1
              File Path: /datavol5
      File Inode Number: 3374
         Security Style: mixed
        Effective Style: unix
         DOS Attributes: 10
 DOS Attributes in Text: ----D---
Expanded Dos Attributes: -
           Unix User Id: 0
          Unix Group Id: 0
         Unix Mode Bits: 755
 Unix Mode Bits in Text: rwxr-xr-x
                   ACLs: Storage-Level Access Guard security
                         SACL (Applies to Directories):
                           AUDIT-EXAMPLE\Domain Users-0x120089-FA
                           AUDIT-EXAMPLE\engineering-0x1f01ff-SA
                           AUDIT-EXAMPLE\market-0x1f01ff-SA
                         DACL (Applies to Directories):
                           ALLOW-BUILTIN\Administrators-0x1f01ff
                           ALLOW-CREATOR OWNER-0x1f01ff
                           ALLOW-EXAMPLE\Domain Users-0x120089
                           ALLOW-EXAMPLE\engineering-0x1f01ff
                           ALLOW-EXAMPLE\market-0x1f01ff
                         SACL (Applies to Files):
                           AUDIT-EXAMPLE\Domain Users-0x120089-FA
                           AUDIT-EXAMPLE\engineering-0x1f01ff-SA
                           AUDIT-EXAMPLE\market-0x1f01ff-SA
                         DACL (Applies to Files):
                           ALLOW-BUILTIN\Administrators-0x1f01ff
                           ALLOW-CREATOR OWNER-0x1f01ff
                           ALLOW-EXAMPLE\Domain Users-0x120089
                           ALLOW-EXAMPLE\engineering-0x1f01ff
                           ALLOW-EXAMPLE\market-0x1f01ff
----
.Verwandte Informationen
xref:display-file-security-ntfs-style-volumes-task.adoc[Anzeigen von Informationen zur Dateisicherheit auf NTFS-SicherheitsVolumes]

xref:display-file-security-unix-style-volumes-task.adoc[Anzeigen von Informationen zur Dateisicherheit auf UNIX-Volumes im Sicherheitsstil]
