---
permalink: smb-admin/display-restricted-group-gpos-task.html 
sidebar: sidebar 
keywords: display, detail, information, restrict, group, define, group, policy, object, gpo, active, directory, applied, apply, cifs, server, display detailed information about restricted group gpos 
summary: 'Sie können detaillierte Informationen zu eingeschränkten Gruppen anzeigen, die als Gruppenrichtlinienobjekte (Gruppenrichtlinienobjekte, Gruppenrichtlinienobjekte) in Active Directory definiert sind und auf den CIFS-Server angewendet werden.' 
---
= Zeigt Informationen zu Gruppenrichtlinienobjekten mit eingeschränktem ONTAP SMB-Standard an
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können detaillierte Informationen zu eingeschränkten Gruppen anzeigen, die als Gruppenrichtlinienobjekte (Gruppenrichtlinienobjekte, Gruppenrichtlinienobjekte) in Active Directory definiert sind und auf den CIFS-Server angewendet werden.

.Über diese Aufgabe
Standardmäßig werden die folgenden Informationen angezeigt:

* Name der Gruppenrichtlinie
* Version der Gruppenrichtlinien
* Verlinken
+
Gibt die Ebene an, auf der die Gruppenrichtlinie konfiguriert ist. Mögliche Ausgabewerte sind:

+
** `Local` Wenn die Gruppenrichtlinie in ONTAP konfiguriert ist
** `Site` Wenn die Gruppenrichtlinie auf Standortebene im Domänencontroller konfiguriert ist
** `Domain` Wenn die Gruppenrichtlinie auf Domänenebene im Domänencontroller konfiguriert ist
** `OrganizationalUnit` Wenn die Gruppenrichtlinie auf der Ebene der Organisationseinheit (OU) im Domänencontroller konfiguriert ist
** `RSOP` Für die sich daraus ergebenden Richtlinien, die aus allen Gruppenrichtlinien abgeleitet wurden, die auf verschiedenen Ebenen definiert sind


* Eingeschränkter Gruppenname
* Die Benutzer und Gruppen, die der Gruppe gehören und nicht zur eingeschränkten Gruppe gehören
* Die Liste der Gruppen, denen die eingeschränkte Gruppe hinzugefügt wird
+
Eine Gruppe kann ein Mitglied von Gruppen sein, die nicht den hier aufgeführten Gruppen angehören.



.Schritt
. Informationen zu allen Gruppenrichtlinienobjekten anzeigen, indem Sie eine der folgenden Aktionen ausführen:
+
|===
| Wenn Sie Informationen zu allen Gruppenrichtlinienobjekten anzeigen möchten... | Geben Sie den Befehl ein... 


 a| 
In Active Directory definiert
 a| 
`vserver cifs group-policy restricted-group show-defined -vserver vserver_name`



 a| 
Wird auf einen CIFS-Server angewendet
 a| 
`vserver cifs group-policy restricted-group show-applied -vserver vserver_name`

|===


.Beispiel
Im folgenden Beispiel werden Informationen zu Gruppenrichtlinienobjekten angezeigt, die in der Active Directory-Domäne definiert sind, zu denen die CIFS-fähige SVM mit dem Namen vs1 gehört:

[listing]
----
cluster1::> vserver cifs group-policy restricted-group show-defined -vserver vs1

Vserver: vs1
-------------

     Group Policy Name: gpo1
               Version: 16
                  Link: OrganizationalUnit
            Group Name: group1
               Members: user1
              MemberOf: EXAMPLE\group9

     Group Policy Name: Resultant Set of Policy
               Version: 0
                  Link: RSOP
            Group Name: group1
               Members: user1
              MemberOf: EXAMPLE\group9
----
Im folgenden Beispiel werden Informationen zu Gruppenrichtlinienobjekten angezeigt, die auf die CIFS-fähige SVM vs1 angewendet wurden:

[listing]
----
cluster1::> vserver cifs group-policy restricted-group show-applied -vserver vs1

Vserver: vs1
-------------

     Group Policy Name: gpo1
               Version: 16
                  Link: OrganizationalUnit
            Group Name: group1
               Members: user1
              MemberOf: EXAMPLE\group9

     Group Policy Name: Resultant Set of Policy
               Version: 0
                  Link: RSOP
            Group Name: group1
               Members: user1
              MemberOf: EXAMPLE\group9
----
.Verwandte Informationen
xref:display-gpo-config-task.adoc[Zeigt Informationen zu GPO-Konfigurationen an]
