---
permalink: smb-admin/display-local-users-task.html 
sidebar: sidebar 
keywords: display, list, local, user, summary, form, determine, account, setting, configure, specific, user, detail, troubleshoot, authentication, file, access, issue, display information about local users 
summary: Sie können eine Liste aller lokalen Benutzer in einem Übersichtsformular anzeigen. Wenn Sie festlegen möchten, welche Kontoeinstellungen für einen bestimmten Benutzer konfiguriert sind, können Sie detaillierte Kontoinformationen für diesen Benutzer sowie die Kontoinformationen für mehrere Benutzer anzeigen. Diese Informationen können Ihnen dabei helfen festzustellen, ob Sie die Einstellungen eines Benutzers ändern müssen, und auch Probleme mit der Authentifizierung oder dem Dateizugriff beheben. 
---
= Zeigt Informationen zu lokalen Benutzern in ONTAP an
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Liste aller lokalen Benutzer in einem Übersichtsformular anzeigen. Wenn Sie festlegen möchten, welche Kontoeinstellungen für einen bestimmten Benutzer konfiguriert sind, können Sie detaillierte Kontoinformationen für diesen Benutzer sowie die Kontoinformationen für mehrere Benutzer anzeigen. Mithilfe dieser Informationen können Sie feststellen, ob Sie die Einstellungen eines Benutzers ändern müssen, und auch Probleme mit der Authentifizierung oder dem Dateizugriff beheben.

.Über diese Aufgabe
Es werden nie Informationen zum Passwort eines Benutzers angezeigt.

.Schritt
. Führen Sie eine der folgenden Aktionen aus:
+
|===
| Ihr Ziel ist | Geben Sie den Befehl ein... 


 a| 
Informationen über alle Benutzer auf der Storage Virtual Machine (SVM) anzeigen
 a| 
`vserver cifs users-and-groups local-user show -vserver _vserver_name_`



 a| 
Anzeigen detaillierter Kontoinformationen für einen Benutzer
 a| 
`vserver cifs users-and-groups local-user show -instance -vserver _vserver_name_ -user-name _user_name_`

|===
+
Es gibt weitere optionale Parameter, die Sie wählen können, wenn Sie den Befehl ausführen. Erfahren Sie mehr über `vserver cifs` in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs["ONTAP-Befehlsreferenz"^].



.Beispiel
Das folgende Beispiel zeigt Informationen über alle lokalen Benutzer auf SVM vs1:

[listing]
----
cluster1::> vserver cifs users-and-groups local-user show -vserver vs1
Vserver  User Name                   Full Name     Description
-------- --------------------------- ------------- -------------
vs1      CIFS_SERVER\Administrator   James Smith   Built-in administrator account
vs1      CIFS_SERVER\sue             Sue   Jones
----