---
permalink: smb-admin/display-open-files-task.html 
sidebar: sidebar 
keywords: display, information, smb, file, connection, session, if, list, volume, share, name, contiuous, available, protection, level, helpful, nondisruptive, operation, display information about open smb files 
summary: Sie können Informationen zu offenen SMB-Dateien anzeigen, einschließlich SMB-Verbindung und Session-ID, Hosting-Volume, Share-Name und Freigabepfad. Sie können Informationen über die kontinuierlich verfügbare Schutzebene einer Datei anzeigen, was hilfreich ist, um zu bestimmen, ob sich eine offene Datei in einem Zustand befindet, der den unterbrechungsfreien Betrieb unterstützt. 
---
= Zeigt Informationen zu geöffneten SMB-Dateien an
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Informationen zu offenen SMB-Dateien anzeigen, einschließlich SMB-Verbindung und Session-ID, Hosting-Volume, Share-Name und Freigabepfad. Sie können Informationen über den kontinuierlich verfügbaren Sicherungsgrad einer Datei anzeigen. Dies ist hilfreich bei der Feststellung, ob sich eine offene Datei in einem Zustand befindet, der den unterbrechungsfreien Betrieb unterstützt.

.Über diese Aufgabe
Sie können Informationen über offene Dateien in einer festgelegten SMB-Sitzung anzeigen. Die angezeigten Informationen sind nützlich, wenn Sie SMB-Sitzungsinformationen für bestimmte Dateien innerhalb einer SMB-Sitzung bestimmen müssen.

Wenn Sie zum Beispiel eine SMB-Sitzung haben, in der einige der geöffneten Dateien mit kontinuierlich verfügbarem Schutz geöffnet sind und einige nicht mit kontinuierlich verfügbarem Schutz geöffnet sind (der Wert für das `-continuously-available` Feld in der `vserver cifs session show` Befehlsausgabe ist `Partial`), können Sie mit diesem Befehl bestimmen, welche Dateien nicht kontinuierlich verfügbar sind.

Sie können Informationen für alle offenen Dateien in festgelegten SMB-Sitzungen auf Storage Virtual Machines (SVMs) in zusammengefasster Form anzeigen, indem Sie den `vserver cifs session file show` Befehl ohne optionale Parameter verwenden.

In vielen Fällen ist jedoch die zurückgegebene Menge an Output groß. Sie können die in der Ausgabe angezeigten Informationen durch optionale Parameter anpassen. Dies kann hilfreich sein, wenn Sie Informationen nur für einen kleinen Teil der offenen Dateien anzeigen möchten.

* Sie können den optionalen `-fields` Parameter verwenden, um die Ausgabe in den ausgewählten Feldern anzuzeigen.
+
Sie können diesen Parameter entweder allein oder in Kombination mit anderen optionalen Parametern verwenden.

* Sie können den `-instance` Parameter verwenden, um detaillierte Informationen über offene SMB-Dateien anzuzeigen.
+
Sie können diesen Parameter entweder allein oder in Kombination mit anderen optionalen Parametern verwenden.



.Schritt
. Führen Sie eine der folgenden Aktionen aus:
+
|===
| Wenn Sie öffnen SMB-Dateien anzeigen möchten... | Geben Sie den folgenden Befehl ein... 


 a| 
Auf der SVM in Übersichtsform
 a| 
`vserver cifs session file show -vserver vserver_name`



 a| 
Auf einem angegebenen Node
 a| 
`vserver cifs session file show -vserver vserver_name -node {node_name|local}`



 a| 
Für eine angegebene Datei-ID
 a| 
`vserver cifs session file show -vserver vserver_name -file-id integer`



 a| 
Für eine angegebene SMB-Verbindungs-ID
 a| 
`vserver cifs session file show -vserver vserver_name -connection-id integer`



 a| 
Für eine angegebene SMB-Session-ID
 a| 
`vserver cifs session file show -vserver vserver_name -session-id integer`



 a| 
Auf dem angegebenen Hosting-Aggregat
 a| 
`vserver cifs session file show -vserver vserver_name -hosting-aggregate aggregate_name`



 a| 
Auf dem angegebenen Volume
 a| 
`vserver cifs session file show -vserver vserver_name -hosting-volume volume_name`



 a| 
In der angegebenen SMB-Freigabe
 a| 
`vserver cifs session file show -vserver vserver_name -share share_name`



 a| 
Auf dem angegebenen SMB-Pfad
 a| 
`vserver cifs session file show -vserver vserver_name -path path`



 a| 
Mit der angegebenen Stufe des kontinuierlichen verfügbaren Schutzes
 a| 
`vserver cifs session file show -vserver vserver_name -continuously-available {No|Yes}`

[NOTE]
====
Wenn der Status „kontinuierlich verfügbar `No`“ lautet, bedeutet dies, dass diese offenen Dateien nicht unterbrechungsfrei nach Takeover und Giveback wiederhergestellt werden können. Sie sind auch bei der allgemeinen Aggregatverschiebung zwischen den Partnern in einer Hochverfügbarkeitbeziehung nicht wiederherstellbar.

====


 a| 
Mit dem angegebenen Status „erneut verbunden“
 a| 
`vserver cifs session file show -vserver vserver_name -reconnected {No|Yes}`

[NOTE]
====
Wenn der Status erneut verbunden ist `No`, wird die geöffnete Datei nach einem Verbindungsabtrennen nicht wieder verbunden. Dies kann bedeuten, dass die Datei nie getrennt wurde oder dass die Datei getrennt wurde und nicht erfolgreich wieder verbunden wurde. Wenn der Status erneut verbunden ist `Yes`, bedeutet dies, dass die geöffnete Datei nach einem Verbindungsabtrennen erfolgreich wieder verbunden wird.

====
|===
+
Es gibt weitere optionale Parameter, mit denen Sie die Ausgabeergebnisse verfeinern können. Weitere Informationen finden Sie auf der man-Seite.



.Beispiele
Im folgenden Beispiel werden Informationen über offene Dateien auf SVM vs1 angezeigt:

[listing]
----
cluster1::> vserver cifs session file show -vserver vs1
Node:       node1
Vserver:    vs1
Connection: 3151274158
Session:    1
File    File      Open Hosting               Continuously
ID      Type      Mode Volume    Share       Available
------- --------- ---- --------- ----------- ------------
41      Regular   r    data      data        Yes
Path: \mytest.rtf
----
Im folgenden Beispiel werden ausführliche Informationen über offene SMB-Dateien mit der Datei-ID 82 auf SVM vs1 angezeigt:

[listing]
----
cluster1::> vserver cifs session file show -vserver vs1 -file-id 82 -instance

                  Node: node1
               Vserver: vs1
               File ID: 82
         Connection ID: 104617
            Session ID: 1
             File Type: Regular
             Open Mode: rw
Aggregate Hosting File: aggr1
   Volume Hosting File: data1
            CIFS Share: data1
  Path from CIFS Share: windows\win8\test\test.txt
            Share Mode: rw
           Range Locks: 1
Continuously Available: Yes
           Reconnected: No
----
.Verwandte Informationen
xref:display-session-task.adoc[Anzeigen von SMB-Sitzungsinformationen]
