---
permalink: smb-admin/display-statistics-task.html 
sidebar: sidebar 
keywords: display, various, statistic, cifs, smb, audit, branchcache, has, monitor, performance, diagnose, issue 
summary: Sie können zur Überwachung der Performance und Diagnose von Problemen verschiedene Statistiken, darunter Statistiken zu CIFS und SMB, Audits und BranchCache-Hash, anzeigen. 
---
= ONTAP SMB-Statistiken anzeigen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können zur Überwachung der Performance und Diagnose von Problemen verschiedene Statistiken, darunter Statistiken zu CIFS und SMB, Audits und BranchCache-Hash, anzeigen.

.Bevor Sie beginnen
Bevor `statistics start` `statistics stop` Sie Informationen zu Objekten anzeigen können, müssen Sie mithilfe der Befehle und Datenproben erfasst haben.

Erfahren Sie mehr über  `statistics start` Und  `statistics stop` im link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=statistics["ONTAP-Befehlsreferenz"^] .

.Schritte
. Legen Sie die Berechtigungsebene auf erweitert fest: `set -privilege advanced`
. Führen Sie eine der folgenden Aktionen aus:
+
|===
| Wenn Sie Statistiken anzeigen möchten für... | Eingeben... 


 a| 
Alle SMB-Versionen
 a| 
`statistics show -object cifs`



 a| 
SMB 1,0
 a| 
`statistics show -object smb1`



 a| 
SMB 2.x und SMB 3.0
 a| 
`statistics show -object smb2`



 a| 
CIFS-Subsystem des Node
 a| 
`statistics show -object nblade_cifs`



 a| 
Multi-Protokoll-Prüfung
 a| 
`statistics show -object audit_ng`



 a| 
BranchCache-Hash-Service
 a| 
`statistics show -object hashd`



 a| 
Dynamisches DNS
 a| 
`statistics show -object ddns_update`

|===
+
Erfahren Sie mehr über `statistics show` in der link:https://docs.netapp.com/us-en/ontap-cli/statistics-show.html["ONTAP-Befehlsreferenz"^].

. Kehren Sie zur Administrator-Berechtigungsebene zurück: `set -privilege admin`


.Verwandte Informationen
* xref:determine-statistics-objects-counters-available-task.adoc[Ermitteln, welche Statistiken, Objekte und Zähler auf Servern verfügbar sind]
* xref:monitor-signed-session-statistics-task.adoc[Überwachen der Statistiken von SMB-signierten Sitzungen]
* xref:display-branchcache-statistics-task.adoc[Zeigt BranchCache-Statistiken an]
* xref:statistics-monitor-automatic-node-referral-task.adoc[Mithilfe von Statistiken können Sie die Aktivitäten der automatischen Knotenverweisung überwachen]
* link:../smb-hyper-v-sql/index.html["SMB-Konfiguration für Microsoft Hyper-V und SQL Server"]
* link:../performance-config/index.html["Einrichtung der Performance-Überwachung"]

