---
permalink: smb-admin/display-server-security-settings-task.html 
sidebar: sidebar 
keywords: display, information, smb, cifs, server, security, settings, storage, virtual, machine, svm, verify, setting 
summary: Sie können Informationen zu den SMB-Server-Sicherheitseinstellungen auf Ihren Storage Virtual Machines anzeigen lassen. Diese Informationen ermöglichen die Überprüfung, ob die Sicherheitseinstellungen korrekt sind. 
---
= Informationen zu den Sicherheitseinstellungen des ONTAP SMB-Servers anzeigen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Informationen zu den Sicherheitseinstellungen des SMB-Servers auf den Storage Virtual Machines (SVMs) können angezeigt werden. Diese Informationen ermöglichen die Überprüfung, ob die Sicherheitseinstellungen korrekt sind.

.Über diese Aufgabe
Eine angezeigte Sicherheitseinstellung kann der Standardwert für dieses Objekt oder ein nicht standardmäßiger Wert sein, der entweder über die ONTAP CLI oder über Active Directory Gruppenrichtlinienobjekte (GPOs) konfiguriert wird.

Der  `vserver cifs security show` Befehl sollte für SMB-Server im Arbeitsgruppenmodus nicht verwendet werden, da einige Optionen ungültig sind.

.Schritt
. Führen Sie eine der folgenden Aktionen aus:
+
|===
| Wenn Informationen über ... angezeigt werden sollen | Geben Sie den Befehl ein... 


 a| 
Alle Sicherheitseinstellungen auf einer bestimmten SVM
 a| 
`vserver cifs security show -vserver _vserver_name_`



 a| 
Eine oder mehrere spezifische Sicherheitseinstellungen auf dem SVM
 a| 
`+vserver cifs security show -vserver _vserver_name_ -fields [fieldname,...]+`Sie können  `-fields ?` eingeben, um festzustellen, welche Felder Sie verwenden können.

|===


.Beispiel
Das folgende Beispiel zeigt alle Sicherheitseinstellungen für SVM vs1:

[listing]
----
cluster1::> vserver cifs security show -vserver vs1

Vserver: vs1

                          Kerberos Clock Skew:        5 minutes
                          Kerberos Ticket Age:        10 hours
                         Kerberos Renewal Age:        7 days
                         Kerberos KDC Timeout:        3 seconds
                          Is Signing Required:        false
              Is Password Complexity Required:        true
         Use start_tls For AD LDAP connection:        false
                    Is AES Encryption Enabled:        false
                       LM Compatibility Level:        lm-ntlm-ntlmv2-krb
                   Is SMB Encryption Required:        false
                      Client Session Security:        none
              SMB1 Enabled for DC Connections:        false
              SMB2 Enabled for DC Connections:        system-default
LDAP Referral Enabled For AD LDAP connections:        false
             Use LDAPS for AD LDAP connection:        false
    Encryption is required for DC Connections:        false
 AES session key enabled for NetLogon channel:        false
  Try Channel Binding For AD LDAP Connections:        false
----
Beachten Sie, dass die angezeigten Einstellungen von der ausgeführten ONTAP Version abhängen.

Das folgende Beispiel zeigt die Kerberos-Taktabweichung für SVM vs1:

[listing]
----
cluster1::> vserver cifs security show -vserver vs1 -fields kerberos-clock-skew

            vserver kerberos-clock-skew
            ------- -------------------
            vs1     5
----
.Verwandte Informationen
xref:display-gpo-config-task.adoc[Informationen zu GPO-Konfigurationen anzeigen]
