---
permalink: smb-admin/display-branchcache-group-policy-objects-task.html 
sidebar: sidebar 
keywords: display, information, cifs, server, group, policy, object, gpo, configuration, branchcache, define, domain, server, display information about branchcache group policy objects 
summary: 'Sie können Informationen über die Konfiguration des Gruppenrichtlinienobjekts (Gruppenrichtlinienobjekts) des CIFS-Servers anzeigen, um zu bestimmen, ob BranchCache-GPOs für die Domäne definiert sind, zu der der CIFS-Server gehört, und wenn ja, welche Einstellungen zulässig sind. Sie bestimmen auch, ob BranchCache GPO-Einstellungen auf den CIFS-Server angewendet werden.' 
---
= Informationen zu den Gruppenrichtlinienobjekten von BranchCache anzeigen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Informationen zur Konfiguration des Gruppenrichtlinienobjekts (Group Policy Object, GPO) des CIFS-Servers anzeigen, um zu bestimmen, ob BranchCache-GPOs für die Domäne definiert sind, zu der der CIFS-Server gehört, und falls ja, welche Einstellungen zulässig sind. Sie bestimmen auch, ob BranchCache GPO-Einstellungen auf den CIFS-Server angewendet werden.

.Über diese Aufgabe
Obwohl in der Domäne, zu der der CIFS-Server gehört, eine GPO-Einstellung definiert ist, wird sie nicht unbedingt auf die Organisationseinheit (OU) angewendet, die die CIFS-fähige Storage Virtual Machine (SVM) enthält. Bei der angewendeten Gruppenrichtlinieneinstellung handelt es sich um eine Untergruppe aller definierten Gruppenrichtlinienobjekte, die auf die CIFS-fähige SVM angewendet werden. Über die Gruppenrichtlinienobjekte angewandte BranchCache-Einstellungen überschreiben die über die CLI angewendeten Einstellungen.

.Schritte
. Zeigen Sie die definierte Gruppenrichtlinieneinstellung für BranchCache für die Active Directory-Domäne mit dem `vserver cifs group-policy show-defined` Befehl an.
+
[NOTE]
====
In diesem Beispiel werden nicht alle verfügbaren Ausgabefelder für den Befehl angezeigt. Ausgabe wird abgeschnitten.

====
+
[listing]
----
cluster1::> vserver cifs group-policy show-defined -vserver vs1

Vserver: vs1
-----------------------------
       GPO Name: Default Domain Policy
       Level: Domain
      Status: enabled
  Advanced Audit Settings:
      Object Access:
          Central Access Policy Staging: failure
  Registry Settings:
      Refresh Time Interval: 22
      Refresh Random Offset: 8
      Hash Publication Mode for BranchCache: per-share
      Hash Version Support for BranchCache: version1
  [...]

    GPO Name: Resultant Set of Policy
      Status: enabled
  Advanced Audit Settings:
      Object Access:
          Central Access Policy Staging: failure
  Registry Settings:
      Refresh Time Interval: 22
      Refresh Random Offset: 8
      Hash Publication for Mode BranchCache: per-share
      Hash Version Support for BranchCache: version1
  [...]
----
. Zeigen Sie mit dem `vserver cifs group-policy show-applied` Befehl die auf den CIFS-Server angewendete Gruppenrichtlinieneinstellung BranchCache an. ``
+
[NOTE]
====
In diesem Beispiel werden nicht alle verfügbaren Ausgabefelder für den Befehl angezeigt. Ausgabe wird abgeschnitten.

====
+
[listing]
----
cluster1::> vserver cifs group-policy show-applied -vserver vs1

Vserver: vs1
-----------------------------
     GPO Name: Default Domain Policy
       Level: Domain
      Status: enabled
  Advanced Audit Settings:
      Object Access:
          Central Access Policy Staging: failure
  Registry Settings:
      Refresh Time Interval: 22
      Refresh Random Offset: 8
      Hash Publication Mode for BranchCache: per-share
      Hash Version Support for BranchCache: version1
  [...]

    GPO Name: Resultant Set of Policy
       Level: RSOP
  Advanced Audit Settings:
      Object Access:
          Central Access Policy Staging: failure
  Registry Settings:
      Refresh Time Interval: 22
      Refresh Random Offset: 8
      Hash Publication Mode for BranchCache: per-share
      Hash Version Support for BranchCache: version1
 [...]
----


.Verwandte Informationen
* xref:enable-disable-gpo-support-task.adoc[Aktivieren oder Deaktivieren der GPO-Unterstützung auf einem CIFS-Server]
* link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-group-policy-show-defined.html["svm cifs Gruppen-Policy show-defined"^]
* link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-group-policy-show-applied.html["vserver cifs-Gruppen-Policy wird angewendet"^]

