---
permalink: smb-admin/display-storage-level-access-guard-task.html 
sidebar: sidebar 
keywords: storage-level, access, guard, third, layer, security, applied, apply, qtree, view, windows, properties, window, troubleshoot, configuration, display information about storage-level access guard 
summary: Storage-Level Access Guard ist eine dritte Sicherheitsebene, die auf ein Volume oder einen Qtree angewendet wird. Storage-Level Access Guard-Einstellungen können nicht über das Windows-Eigenschaftenfenster angezeigt werden. Zur Anzeige von Informationen zur Storage-Level Access Guard-Sicherheit, die zur Validierung der Konfiguration oder zur Fehlerbehebung bei Dateizugriffsproblemen verwendet werden können, ist die ONTAP CLI zu nutzen. 
---
= Informationen zu Storage-Level Access Guard auf ONTAP SMB-Servern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage-Level Access Guard ist eine dritte Sicherheitsebene, die auf ein Volume oder einen Qtree angewendet wird. Storage-Level Access Guard-Einstellungen können nicht über das Windows-Eigenschaftenfenster angezeigt werden. Zur Anzeige von Informationen zur Storage-Level Access Guard-Sicherheit, die zur Validierung der Konfiguration oder zur Fehlerbehebung bei Dateizugriffsproblemen verwendet werden können, ist die ONTAP CLI zu nutzen.

.Über diese Aufgabe
Sie müssen den Namen der Storage Virtual Machine (SVM) und den Pfad zum Volume oder Qtree angeben, dessen Storage-Level Access Guard Sicherheitsinformationen angezeigt werden sollen. Die Ausgabe kann in zusammengefasster Form oder als detaillierte Liste angezeigt werden.

.Schritt
. Storage-Level Access Guard-Sicherheitseinstellungen mit dem gewünschten Detaillierungsgrad anzeigen:
+
|===
| Wenn Informationen angezeigt werden sollen... | Führen Sie den folgenden Befehl aus... 


 a| 
Zusammengefasst
 a| 
`vserver security file-directory show -vserver _vserver_name_ -path _path_`



 a| 
Mit erweiterten Details
 a| 
`vserver security file-directory show -vserver _vserver_name_ -path _path_ -expand-mask true`

|===


.Beispiele
Das folgende Beispiel zeigt die Storage-Level Access Guard-Sicherheitsinformationen für das NTFS-Sicherheitsvolume mit dem Pfad `/datavol1` in SVM vs1:

[listing]
----
cluster::> vserver security file-directory show -vserver vs1 -path /datavol1

                Vserver: vs1
              File Path: /datavol1
      File Inode Number: 77
         Security Style: ntfs
        Effective Style: ntfs
         DOS Attributes: 10
 DOS Attributes in Text: ----D---
Expanded Dos Attributes: -
           Unix User Id: 0
          Unix Group Id: 0
         Unix Mode Bits: 777
 Unix Mode Bits in Text: rwxrwxrwx
                   ACLs: NTFS Security Descriptor
                         Control:0x8004
                         Owner:BUILTIN\Administrators
                         Group:BUILTIN\Administrators
                         DACL - ACEs
                           ALLOW-Everyone-0x1f01ff
                           ALLOW-Everyone-0x10000000-OI|CI|IO


                         Storage-Level Access Guard security
                         SACL (Applies to Directories):
                           AUDIT-EXAMPLE\Domain Users-0x120089-FA
                           AUDIT-EXAMPLE\engineering-0x1f01ff-SA
                         DACL (Applies to Directories):
                           ALLOW-EXAMPLE\Domain Users-0x120089
                           ALLOW-EXAMPLE\engineering-0x1f01ff
                           ALLOW-NT AUTHORITY\SYSTEM-0x1f01ff
                         SACL (Applies to Files):
                           AUDIT-EXAMPLE\Domain Users-0x120089-FA
                           AUDIT-EXAMPLE\engineering-0x1f01ff-SA
                         DACL (Applies to Files):
                           ALLOW-EXAMPLE\Domain Users-0x120089
                           ALLOW-EXAMPLE\engineering-0x1f01ff
                           ALLOW-NT AUTHORITY\SYSTEM-0x1f01ff
----
Das folgende Beispiel zeigt die Storage-Level Access Guard-Informationen zum Volume mit gemischtem Sicherheitsstil am Pfad `/datavol5` in SVM vs1. Die oberste Ebene dieses Volumes hat effektive UNIX-Sicherheit. Das Volume verfügt über Storage-Level Access Guard-Sicherheit.

[listing]
----
cluster1::> vserver security file-directory show -vserver vs1 -path /datavol5
                Vserver: vs1
              File Path: /datavol5
      File Inode Number: 3374
         Security Style: mixed
        Effective Style: unix
         DOS Attributes: 10
 DOS Attributes in Text: ----D---
Expanded Dos Attributes: -
           Unix User Id: 0
          Unix Group Id: 0
         Unix Mode Bits: 755
 Unix Mode Bits in Text: rwxr-xr-x
                   ACLs: Storage-Level Access Guard security
                         SACL (Applies to Directories):
                           AUDIT-EXAMPLE\Domain Users-0x120089-FA
                           AUDIT-EXAMPLE\engineering-0x1f01ff-SA
                         DACL (Applies to Directories):
                           ALLOW-EXAMPLE\Domain Users-0x120089
                           ALLOW-EXAMPLE\engineering-0x1f01ff
                           ALLOW-NT AUTHORITY\SYSTEM-0x1f01ff
                         SACL (Applies to Files):
                           AUDIT-EXAMPLE\Domain Users-0x120089-FA
                           AUDIT-EXAMPLE\engineering-0x1f01ff-SA
                         DACL (Applies to Files):
                           ALLOW-EXAMPLE\Domain Users-0x120089
                           ALLOW-EXAMPLE\engineering-0x1f01ff
                           ALLOW-NT AUTHORITY\SYSTEM-0x1f01ff
----