---
permalink: smb-admin/dynamic-access-control-concept.html 
sidebar: sidebar 
keywords: consideration, dynamic, access, control, dac, central, policies, policy, secure, file, folder, cifs, server, consideration when using dynamic access control and central access policies with cifs servers 
summary: Bei der Verwendung von Dynamic Access Control und zentralen Zugriffsrichtlinien zum Schutz von Dateien und Ordnern auf CIFS-Servern müssen bestimmte Aspekte berücksichtigt werden. 
---
= Informationen zur Verwendung von DAC und zentralen Zugriffsrichtlinien mit ONTAP SMB-Servern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Verwendung von Dynamic Access Control (DAC) und zentralen Zugriffsrichtlinien zum Schutz von Dateien und Ordnern auf CIFS-Servern sind bestimmte Aspekte zu berücksichtigen.



[[nfs-access-can-be-denied-to-root-if-policy-rule-applies-to-domainadministrator-user]]
== Der NFS-Zugriff kann dem Root-Benutzer verweigert werden, wenn eine Richtlinienregel für den Benutzer „domain\administrator“ gilt.

Unter bestimmten Umständen kann der NFS-Zugriff auf Root verweigert werden, wenn auf die Daten, auf die der Root-Benutzer zugreifen möchte, eine zentrale Zugriffsrichtlinie angewendet wird. Das Problem tritt auf, wenn die zentrale Zugriffsrichtlinie eine Regel enthält, die auf domain\administrator angewendet wird und das Root-Konto dem domain\administrator-Konto zugeordnet ist.

Anstatt die Regel auf den Benutzer domain\administrator anzuwenden, sollte die Regel auf eine Gruppe mit administrativen Rechten angewendet werden, wie zum Beispiel die domain\administrators Gruppe. Auf diese Weise kann root dem domain\administrator Konto zugeordnet werden, ohne dass root von diesem Problem betroffen ist.



[[cifs-servers-builtinadministrators-group-has-access-to-resources-when-the-applied-central-access-policy-is-not-found-in-active-directory]]
== Die Gruppe BUILTIN\Administrators des CIFS-Servers hat Zugriff auf Ressourcen, wenn die angewendete zentrale Zugriffsrichtlinie in Active Directory nicht gefunden wird.

Es ist möglich, dass auf Ressourcen innerhalb des CIFS-Servers zentrale Zugriffsrichtlinien angewendet werden. Wenn der CIFS-Server versucht, mithilfe der SID der zentralen Zugriffsrichtlinie Informationen aus Active Directory abzurufen, stimmt die SID mit keiner vorhandenen SID einer zentralen Zugriffsrichtlinie in Active Directory überein. Unter diesen Umständen wendet der CIFS-Server die lokale Standardwiederherstellungsrichtlinie für diese Ressource an.

Die lokale Standardwiederherstellungsrichtlinie gewährt der Gruppe BUILTIN\Administrators des CIFS-Servers Zugriff auf diese Ressource.
