---
permalink: smb-admin/enable-ldap-signing-sealing-task.html 
sidebar: sidebar 
keywords: cifs, server, sign, seal, secure, communication, active, directory, ldap, modify, security, setting, sign, seal, enable, enable ldap signing and sealing on the cifs server 
summary: Bevor Ihr CIFS-Server die Signierung und Versiegelung für die sichere Kommunikation mit einem Active Directory LDAP-Server verwenden kann, sind die Sicherheitseinstellungen des CIFS-Servers so zu ändern, dass LDAP-Signierung und -Versiegelung aktiviert werden. 
---
= LDAP-Signierung und -Versiegelung auf ONTAP SMB-Servern aktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Ihr CIFS-Server die Signierung und Versiegelung für die sichere Kommunikation mit einem Active Directory LDAP-Server verwenden kann, sind die Sicherheitseinstellungen des CIFS-Servers so zu ändern, dass LDAP-Signierung und -Versiegelung aktiviert werden.

.Bevor Sie beginnen
Es ist erforderlich, sich mit Ihrem AD-Serveradministrator abzustimmen, um die geeigneten Sicherheitskonfigurationswerte zu ermitteln.

.Schritte
. Die CIFS-Server-Sicherheitseinstellung konfigurieren, die signierten und versiegelten Datenverkehr mit Active Directory LDAP-Servern ermöglicht: `vserver cifs security modify -vserver _vserver_name_ -session-security-for-ad-ldap {none|sign|seal}`
+
Sie können Signieren (`sign`, Datenintegrität, Signieren und Versiegeln (`seal`, Datenintegrität und Verschlüsselung oder keines von beidem  `none`, keine Signierung oder Versiegelung, aktivieren. Der Standardwert ist `none`.

. Überprüfen, ob die LDAP-Signatur- und Versiegelungssicherheitseinstellung korrekt konfiguriert ist: `vserver cifs security show -vserver _vserver_name_`
+
[NOTE]
====
Wenn die SVM denselben LDAP-Server für die Abfrage von Namenszuordnungen oder anderen UNIX-Informationen wie Benutzern, Gruppen und Netzgruppen verwendet, muss die entsprechende Einstellung mit der  `-session-security` Option des  `vserver services name-service ldap client modify` Befehls aktiviert werden.

====

