---
permalink: smb-admin/enable-disable-gpo-support-task.html 
sidebar: sidebar 
keywords: enable, disable, group, policy, object, gpo, support, cifs, server, applicable, define, policy, organizational, unit, ou, enable or disable gpo support on a cifs server 
summary: 'Sie können die Unterstützung für Gruppenrichtlinienobjekte (GPOs) auf einem CIFS-Server aktivieren oder deaktivieren. Wenn Sie die GPO-Unterstützung auf einem CIFS-Server aktivieren, werden die entsprechenden GPOs, die in der Gruppenrichtlinie definiert sind – also der Richtlinie, die auf die Organisationseinheit angewendet wird, die das Computerobjekt des CIFS-Servers enthält –, auf den CIFS-Server angewendet.' 
---
= GPO-Unterstützung auf ONTAP SMB-Servern aktivieren oder deaktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Unterstützung für Gruppenrichtlinienobjekte (GPO) kann auf einem CIFS-Server aktiviert oder deaktiviert werden. Wenn die GPO-Unterstützung auf einem CIFS-Server aktiviert ist, werden die entsprechenden GPOs, die in der Gruppenrichtlinie definiert sind (der Richtlinie, die auf die Organisationseinheit (OU) angewendet wird, die das CIFS-Server-Computerobjekt enthält), auf den CIFS-Server angewendet.

[NOTE]
.Über diese Aufgabe
====
Gruppenrichtlinienobjekte (GPOs) können auf CIFS-Servern im Arbeitsgruppenmodus nicht aktiviert werden.

====
.Schritte
. Führen Sie eine der folgenden Aktionen aus:
+
|===
| Wenn Sie möchten... | Geben Sie den Befehl ein... 


 a| 
Gruppenrichtlinienobjekte aktivieren
 a| 
`vserver cifs group-policy modify -vserver _vserver_name_ -status enabled`



 a| 
Gruppenrichtlinien deaktivieren
 a| 
`vserver cifs group-policy modify -vserver _vserver_name_ -status disabled`

|===
. Es sollte überprüft werden, ob die GPO-Unterstützung den gewünschten Status aufweist: `vserver cifs group-policy show -vserver +vserver_name_`
+
Der Gruppenrichtlinienstatus für CIFS-Server im Arbeitsgruppenmodus wird als "`disabled`" angezeigt.



.Beispiel
Das folgende Beispiel aktiviert die GPO-Unterstützung auf der Storage Virtual Machine (SVM) vs1:

[listing]
----
cluster1::> vserver cifs group-policy modify -vserver vs1 -status enabled

cluster1::> vserver cifs group-policy show -vserver vs1

            Vserver: vs1
Group Policy Status: enabled
----
.Verwandte Informationen
xref:supported-gpos-concept.adoc[Informationen zu unterstützten Gruppenrichtlinienobjekten (GPOs)]

xref:requirements-gpos-concept.adoc[Serveranforderungen für Gruppenrichtlinien]

xref:gpos-updated-server-concept.adoc[Informationen zum Aktualisieren von Gruppenrichtlinienobjekten (GPOs) auf SMB-Servern]

xref:manual-update-gpo-settings-task.adoc[Gruppenrichtlinieneinstellungen auf SMB-Servern manuell aktualisieren]

xref:display-gpo-config-task.adoc[Informationen zu GPO-Konfigurationen anzeigen]
