---
permalink: smb-admin/enable-metadata-cache-task.html 
sidebar: sidebar 
keywords: smb, performance, client, enabling, enable, metadata, cache, disable, enable the smb metadata cache 
summary: Durch die Aktivierung des SMB Metadaten-Caches können Sie die Performance von SMB 1.0 Clients verbessern. Standardmäßig ist das Caching von SMB-Metadaten deaktiviert. 
---
= Aktivieren Sie den ONTAP SMB-Metadatencache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durch die Aktivierung des SMB Metadaten-Caches können Sie die Performance von SMB 1.0 Clients verbessern. Standardmäßig ist das Caching von SMB-Metadaten deaktiviert.

.Schritt
. Führen Sie die gewünschte Aktion aus:
+
|===
| Ihr Ziel ist | Geben Sie den Befehl ein... 


 a| 
Aktivieren Sie SMB-Metadaten-Caching beim Erstellen einer Freigabe
 a| 
`vserver cifs share create -vserver _vserver_name_ -share-name _share_name_ -path _path_ -share-properties attributecache`



 a| 
SMB-Metadaten-Caching bei einer vorhandenen Freigabe aktivieren
 a| 
`vserver cifs share properties add -vserver _vserver_name_ -share-name _share_name_ -share-properties attributecache`

|===


.Verwandte Informationen
* xref:configure-lifetime-metadata-cache-entries-task.adoc[Konfigurieren der Lebensdauer von Metadaten-Cache-Einträgen]
* xref:add-remove-share-properties-existing-share-task.adoc[Hinzufügen oder Entfernen von Freigabeeigenschaften zu vorhandenen Freigaben]

