---
permalink: smb-admin/enable-encrypted-connections-domain-controllers-task.html 
sidebar: sidebar 
keywords: ontap, connection, domain, controller, encrypt, enable, enable encrypted connections to domain controllers 
summary: Ab ONTAP 9.8 kann angegeben werden, dass Verbindungen zu Domänencontrollern verschlüsselt werden. 
---
= Verschlüsselte Verbindungen zu ONTAP SMB-Domänencontrollern aktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.8 kann angegeben werden, dass Verbindungen zu Domänencontrollern verschlüsselt werden.

.Über diese Aufgabe
ONTAP erfordert die Verschlüsselung der Kommunikation mit Domänencontrollern (DC), wenn die  `-encryption-required-for-dc-connection` Option auf  `true` gesetzt ist; standardmäßig ist  `false` eingestellt. Wenn die Option gesetzt ist, wird für ONTAP DC-Verbindungen ausschließlich das SMB3-Protokoll verwendet, da Verschlüsselung nur von SMB3 unterstützt wird.

Wenn verschlüsselte DC-Kommunikation erforderlich ist, wird die  `-smb2-enabled-for-dc-connections` Option ignoriert, da ONTAP ausschließlich SMB3-Verbindungen aushandelt. Unterstützt ein DC weder SMB3 noch Verschlüsselung, stellt ONTAP keine Verbindung zu ihm her.

.Schritt
. Verschlüsselte Kommunikation mit dem DC aktivieren: `vserver cifs security modify -vserver _svm_name_ -encryption-required-for-dc-connection true`

