---
permalink: smb-admin/enable-disable-encryption-incoming-traffic-task.html 
sidebar: sidebar 
keywords: require, smb, encryption, traffic, enable, cifs, server, share, level, default, enable or disable required smb encyrption for incoming smb traffic 
summary: Wenn die SMB-Verschlüsselung für eingehenden SMB-Datenverkehr erforderlich sein soll, kann sie auf dem CIFS-Server oder auf Freigabeebene aktiviert werden. Standardmäßig ist die SMB-Verschlüsselung nicht erforderlich. 
---
= ONTAP SMB-Verschlüsselung für eingehenden Datenverkehr aktivieren oder deaktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn die SMB-Verschlüsselung für eingehenden SMB-Datenverkehr erforderlich sein soll, kann sie auf dem CIFS-Server oder auf Freigabeebene aktiviert werden. Standardmäßig ist die SMB-Verschlüsselung nicht erforderlich.

.Über diese Aufgabe
Sie können die SMB-Verschlüsselung auf dem CIFS-Server aktivieren, wodurch sie für alle Freigaben auf dem CIFS-Server gilt. Wenn für alle Freigaben auf dem CIFS-Server keine verpflichtende SMB-Verschlüsselung erforderlich sein soll oder wenn verpflichtende SMB-Verschlüsselung für eingehenden SMB-Datenverkehr nur für einzelne Freigaben aktiviert werden soll, kann die verpflichtende SMB-Verschlüsselung auf dem CIFS-Server deaktiviert werden.

Wenn Sie eine Storage Virtual Machine (SVM) Notfallwiederherstellungsbeziehung einrichten, bestimmt der Wert, den Sie für die  `-identity-preserve` Option des  `snapmirror create` Befehls auswählen, die Konfigurationsdetails, die in die Ziel-SVM repliziert werden.

Wenn die  `-identity-preserve` Option auf  `true` (ID-preserve) gesetzt ist, wird die SMB-Verschlüsselungssicherheitseinstellung auf das Ziel repliziert.

Wenn die  `-identity-preserve` Option auf  `false` (non-ID-preserve) gesetzt ist, wird die SMB-Verschlüsselungssicherheitseinstellung nicht auf das Ziel repliziert. In diesem Fall werden die CIFS-Server-Sicherheitseinstellungen auf dem Ziel auf die Standardwerte gesetzt. Wenn auf der Quell-SVM die SMB-Verschlüsselung aktiviert ist, muss die CIFS-Server-SMB-Verschlüsselung auf dem Ziel manuell aktiviert werden.

.Schritte
. Führen Sie eine der folgenden Aktionen aus:
+
|===
| Wenn die erforderliche SMB-Verschlüsselung für eingehenden SMB-Datenverkehr auf dem CIFS-Server benötigt wird... | Geben Sie den Befehl ein... 


 a| 
Aktiviert
 a| 
`vserver cifs security modify -vserver _vserver_name_ -is-smb-encryption-required true`



 a| 
Deaktiviert
 a| 
`vserver cifs security modify -vserver _vserver_name_ -is-smb-encryption-required false`

|===
. Es sollte überprüft werden, ob die erforderliche SMB-Verschlüsselung auf dem CIFS-Server wie gewünscht aktiviert oder deaktiviert ist: `vserver cifs security show -vserver _vserver_name_ -fields is-smb-encryption-required`
+
Das  `is-smb-encryption-required` Feld zeigt  `true` an, wenn die erforderliche SMB-Verschlüsselung auf dem CIFS-Server aktiviert ist, und  `false` wenn sie deaktiviert ist.



.Beispiel
Das folgende Beispiel aktiviert die erforderliche SMB-Verschlüsselung für eingehenden SMB-Datenverkehr für den CIFS-Server auf SVM vs1:

[listing]
----
cluster1::> vserver cifs security modify -vserver vs1 -is-smb-encryption-required true

cluster1::> vserver cifs security show -vserver vs1 -fields is-smb-encryption-required
vserver  is-smb-encryption-required
-------- -------------------------
vs1      true
----
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["snapmirror create"^]

