---
permalink: smb-admin/enable-ipv6-task.html 
sidebar: sidebar 
keywords: ipv6, network, enable, cluster, setup, administrator, smb, enable ipv6 for smb, cluster administrator only 
summary: IPv6-Netzwerke sind während der Cluster-Einrichtung nicht aktiviert. Ein Cluster-Administrator muss IPv6 nach Abschluss der Cluster-Einrichtung aktivieren, um IPv6 für SMB zu verwenden. Wenn der Cluster-Administrator IPv6 aktiviert, ist es für den gesamten Cluster aktiviert. 
---
= IPv6 für ONTAP SMB Server aktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IPv6-Netzwerke sind während der Cluster-Einrichtung nicht aktiviert. Ein Cluster-Administrator muss IPv6 nach Abschluss der Cluster-Einrichtung aktivieren, um IPv6 für SMB zu verwenden. Wenn der Cluster-Administrator IPv6 aktiviert, ist es für den gesamten Cluster aktiviert.

.Schritt
. IPv6 aktivieren: `network options ipv6 modify -enabled true`
+
IPv6 ist aktiviert. IPv6-Daten-LIFs für SMB-Zugriff können konfiguriert werden.



.Verwandte Informationen
* xref:monitor-display-ipv6-sessions-task.adoc[Informationen zu IPv6-Sitzungen überwachen und anzeigen]
* link:../networking/networking_reference.html["Das Netzwerk mithilfe von System Manager visualisieren"]
* link:https://pubs.lenovo.com/network_management_guide/2EFD6EDE-1846-41F1-9C63-723BA6972BC4_["Aktivierung von IPv6 auf dem Cluster"^]
* link:https://docs.netapp.com/us-en/ontap-cli/network-options-ipv6-modify.html["Netzwerkoptionen IPv6 ändern"^]

