---
permalink: smb-admin/enable-disable-dynamic-access-control-task.html 
sidebar: sidebar 
keywords: option, enable, dynamic, access, control, dac, secure, object, cifs, server, disable, default, enable or disable dynamic access control 
summary: 'Die Option, mit der Sie Dynamic Access Control (DAC) zum Sichern von Objekten auf Ihrem CIFS-Server verwenden können, ist standardmäßig deaktiviert. Sie müssen die Option aktivieren, wenn Sie die dynamische Zugriffssteuerung auf Ihrem CIFS-Server verwenden möchten. Wenn Sie später entscheiden, dass Sie Dynamic Access Control nicht zum Sichern von auf dem CIFS-Server gespeicherten Objekten verwenden möchten, können Sie die Option deaktivieren.' 
---
= Aktiviert oder deaktiviert die Übersicht über die dynamische Zugriffskontrolle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Option, mit der Sie Dynamic Access Control (DAC) zum Sichern von Objekten auf Ihrem CIFS-Server verwenden können, ist standardmäßig deaktiviert. Sie müssen die Option aktivieren, wenn Sie die dynamische Zugriffssteuerung auf Ihrem CIFS-Server verwenden möchten. Wenn Sie später entscheiden, dass Sie Dynamic Access Control nicht zum Sichern von auf dem CIFS-Server gespeicherten Objekten verwenden möchten, können Sie die Option deaktivieren.

Informationen zur Konfiguration der dynamischen Zugriffssteuerung in Active Directory finden Sie in der Microsoft TechNet-Bibliothek.

http://technet.microsoft.com/library/hh831717.aspx["Microsoft TechNet: Dynamic Access Control Scenario Overview"^]

.Über diese Aufgabe
Ist die Dynamic Access Control aktiviert, kann das Dateisystem ACLs mit Einträgen im Zusammenhang mit Dynamic Access Control enthalten. Wenn die dynamische Zugriffskontrolle deaktiviert ist, werden die aktuellen Einträge für die dynamische Zugriffskontrolle ignoriert und neue Einträge werden nicht zugelassen.

Diese Option ist nur auf der erweiterten Berechtigungsebene verfügbar.

.Schritt
. Legen Sie die Berechtigungsebene auf erweitert fest: `set -privilege advanced`
. Führen Sie eine der folgenden Aktionen aus:
+
|===


| Wenn Sie die dynamische Zugriffskontrolle benötigen, | Geben Sie den Befehl ein... 


 a| 
Aktiviert
 a| 
`vserver cifs options modify -vserver _vserver_name_ -is-dac-enabled true`



 a| 
Deaktiviert
 a| 
`vserver cifs options modify -vserver _vserver_name_ -is-dac-enabled false`

|===
. Kehren Sie zur Administrator-Berechtigungsebene zurück: `set -privilege admin`


.Verwandte Informationen
xref:configure-central-access-policies-secure-data-task.adoc[Konfiguration von zentralen Zugriffsrichtlinien zur Sicherung von Daten auf CIFS-Servern]
