---
permalink: smb-admin/enable-disable-access-based-enumeration-task.html 
sidebar: sidebar 
keywords: enable, disable, access-based, enumeration, abe, smb, allow, prevent, user, permission, access, enable or disable access-based enumeration on smb shares 
summary: 'Sie können ABE (Access-Based Enumeration) auf SMB-Freigaben aktivieren oder deaktivieren, um Benutzern zu ermöglichen oder zu verhindern, dass sie freigegebene Ressourcen sehen, auf die sie keinen Zugriff haben.' 
---
= Aktivieren oder Deaktivieren der zugriffsbasierten Aufzählung auf ONTAP SMB-Freigaben
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Sie können ABE (Access-Based Enumeration) auf SMB-Freigaben aktivieren oder deaktivieren, um Benutzern zu ermöglichen oder zu verhindern, dass sie freigegebene Ressourcen sehen, auf die sie keinen Zugriff haben.

.Über diese Aufgabe
ABE ist standardmäßig deaktiviert.

.Schritte
. Führen Sie eine der folgenden Aktionen aus:
+
|===
| Ihr Ziel ist | Geben Sie den Befehl ein... 


 a| 
Aktivieren Sie ABE für eine neue Freigabe
 a| 
`vserver cifs share create -vserver vserver_name -share-name share_name -path path -share-properties access-based-enumeration` Sie können zusätzliche optionale Freigabeeinstellungen und zusätzliche Freigabeeigenschaften angeben, wenn Sie eine SMB-Freigabe erstellen. Erfahren Sie mehr über `vserver cifs share create` in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-share-create.html["ONTAP-Befehlsreferenz"^].



 a| 
Aktivieren Sie ABE für eine vorhandene Freigabe
 a| 
`vserver cifs share properties add -vserver vserver_name -share-name share_name -share-properties access-based-enumeration` Vorhandene Freigabeeigenschaften bleiben erhalten. Die ABE-Share-Eigenschaft wird der bestehenden Liste der Freigabeliegenschaften hinzugefügt.



 a| 
Deaktivieren Sie ABE für eine vorhandene Freigabe
 a| 
`vserver cifs share properties remove -vserver vserver_name -share-name share_name -share-properties access-based-enumeration` Andere Freigabeeigenschaften bleiben erhalten. Nur die ABE-Share-Eigenschaft wird aus der Liste der Share-Eigenschaften entfernt.

|===
. Überprüfen Sie mit dem `vserver cifs share show` Befehl, ob die Freigabekonfiguration korrekt ist.


.Beispiele
Im folgenden Beispiel wird eine ABE SMB-Freigabe namens „`sales`“ mit einem Pfad von `/sales` auf SVM vs1 erstellt. Die Freigabe wird mit `access-based-enumeration` als Share-Eigenschaft erstellt:

[listing]
----
cluster1::> vserver cifs share create -vserver vs1 -share-name sales -path /sales  -share-properties access-based-enumeration,oplocks,browsable,changenotify

cluster1::> vserver cifs share show -vserver vs1 -share-name sales

                      Vserver: vs1
                        Share: sales
     CIFS Server NetBIOS Name: VS1
                         Path: /sales
             Share Properties: access-based-enumeration
                               oplocks
                               browsable
                               changenotify
           Symlink Properties: enable
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: -
                  Volume Name: -
                Offline Files: manual
Vscan File-Operations Profile: standard
----
Im folgenden Beispiel wird die `access-based-enumeration` Share-Eigenschaft zu einer SMB-Freigabe namens „`data2`“ hinzugefügt:

[listing]
----
cluster1::> vserver cifs share properties add -vserver vs1 -share-name data2 -share-properties access-based-enumeration

cluster1::> vserver cifs share show -vserver vs1 -share-name data2 -fields share-name,share-properties
server  share-name share-properties
------- ---------- -------------------------------------------------------
vs1     data2      oplocks,browsable,changenotify,access-based-enumeration
----
.Verwandte Informationen
xref:add-remove-share-properties-existing-share-task.adoc[Hinzufügen oder Entfernen von Share-Eigenschaften für eine vorhandene SMB-Freigabe]
