---
permalink: smb-admin/enable-disable-oplocks-when-creating-shares-task.html 
sidebar: sidebar 
keywords: oplock, client, lock, file, cache, content, local, performance, operation, storage, virtual, machine, svm, circumstance, disable, share-by-share, basis, enable, disable, enable or disable oplocks when creating smb shares 
summary: 'Oplocks ermöglichen Clients das lokale Sperren von Dateien und den Cache von Inhalten, wodurch die Performance von Dateivorgängen verbessert wird. Oplocks sind auf SMB Shares aktiviert, die sich auf Storage Virtual Machines (SVMs) befinden. Unter bestimmten Umständen möchten Sie Oplocks deaktivieren. Sie können Oplocks auf Share-by-Share-Basis aktivieren oder deaktivieren.' 
---
= Aktivieren oder deaktivieren Sie Oplocks beim Erstellen von ONTAP SMB-Freigaben
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Oplocks ermöglichen Clients das lokale Sperren von Dateien und den Cache von Inhalten, wodurch die Performance von Dateivorgängen verbessert wird. Oplocks sind auf SMB Shares aktiviert, die sich auf Storage Virtual Machines (SVMs) befinden. Unter bestimmten Umständen möchten Sie Oplocks deaktivieren. Sie können Oplocks auf Share-by-Share-Basis aktivieren oder deaktivieren.

.Über diese Aufgabe
Wenn Oplocks auf dem Volume aktiviert sind, das eine Freigabe enthält, aber die Oplock-Share-Eigenschaft für diese Freigabe deaktiviert ist, sind Oplocks für diese Freigabe deaktiviert. Das Deaktivieren von Oplocks auf einem Share hat Vorrang vor der Einstellung Volume Oplock. Wenn Sie Oplocks auf dem Share deaktivieren, werden sowohl opportunistische als auch Leasingoplocks deaktiviert.

Sie können weitere Freigabeliegenschaften angeben, indem Sie die Oplock-Share-Eigenschaft mit einer durch Komma getrennten Liste angeben. Sie können auch andere Freigabeparameter festlegen.

.Schritte
. Führen Sie die entsprechende Aktion aus:
+
|===
| Ihr Ziel ist | Dann... 


 a| 
Während der Erstellung von Shares Oplocks auf einem Share aktivieren
 a| 
Geben Sie den folgenden Befehl ein: `+vserver cifs share create -vserver _vserver_name_ -share-name share_name -path path_to_share -share-properties [oplocks,...]+`

[NOTE]
====
Wenn Sie möchten, dass die Freigabe nur die Standardfreigabeeigenschaften hat, die `oplocks` , `browsable` und `changenotify` aktiviert sind, müssen Sie `-share-properties` beim Erstellen einer SMB-Freigabe den Parameter nicht angeben. Wenn Sie eine andere Kombination von Freigabeeigenschaften als die Standardwerte `-share-properties` verwenden möchten, müssen Sie den Parameter mit der Liste der Freigabeeigenschaften angeben, die für diese Freigabe verwendet werden sollen.

====


 a| 
Während der Share-Erstellung die Oplocks auf einem Share deaktivieren
 a| 
Geben Sie den folgenden Befehl ein: `+vserver cifs share create -vserver _vserver_name_ -share-name _share_name_ -path _path_to_share_ -share-properties [other_share_property,...]+`

[NOTE]
====
Wenn Sie Oplocks deaktivieren, müssen Sie beim Erstellen der Freigabe eine Liste mit Freigabeeigenschaften angeben, die `oplocks` Eigenschaft sollte jedoch nicht angegeben werden.

====
|===


.Verwandte Informationen
xref:enable-disable-oplocks-existing-shares-task.adoc[Oplocks auf vorhandenen SMB-Freigaben aktivieren oder deaktivieren]

xref:monitor-oplock-status-task.adoc[Überwachung des Oplock-Status]
