---
permalink: smb-admin/enable-disable-aes-encryption-kerberos-task.html 
sidebar: sidebar 
keywords: advantage, security, kerberos-based, communication, aes-256, aes-128, aes, encryption, active, directory, ad, kdc, cifs, smb 
summary: 'Damit Sie die beste Sicherheit mit Kerberos-basierter Kommunikation nutzen können, können Sie die AES-256- und AES-128-Verschlüsselung auf dem SMB-Server aktivieren. Wenn Sie nicht möchten, dass der SMB-Server die AES-Verschlüsselungstypen für Kerberos-basierte Kommunikation mit dem Active Directory (AD) KDC wählt, können Sie die AES-Verschlüsselung deaktivieren. Die AES-Verschlüsselung ist standardmäßig deaktiviert.' 
---
= Aktiviert oder deaktiviert die AES-Verschlüsselung für Kerberos-basierte Kommunikation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um die höchste Sicherheit mit Kerberos-basierter Kommunikation zu nutzen, sollten Sie AES-256- und AES-128-Verschlüsselung auf dem SMB-Server verwenden. Ab ONTAP 9.13.1 ist die AES-Verschlüsselung standardmäßig aktiviert.  Wenn Sie nicht möchten, dass der SMB-Server die AES-Verschlüsselungstypen für Kerberos-basierte Kommunikation mit dem Active Directory (AD) KDC wählt, können Sie die AES-Verschlüsselung deaktivieren.

Ob die AES-Verschlüsselung standardmäßig aktiviert ist und ob Sie die Möglichkeit haben, Verschlüsselungstypen anzugeben, hängt von Ihrer ONTAP-Version ab.

[cols="3"]
|===
| ONTAP-Version | AES-Verschlüsselung wird aktiviert durch... | Sie können Verschlüsselungstypen angeben? 


| 9.13.1 und höher | Standardmäßig | Ja. 


| 9.12.1 | Manuell | Ja. 


| 9.11.1 und früher | Manuell | Nein 
|===
Ab ONTAP 9.12.1 wird die AES-Verschlüsselung mit dem aktiviert und deaktiviert `-advertised-enc-types` Option, mit der Sie die Verschlüsselungstypen angeben können, die für das AD KDC angekündigt werden. Die Standardeinstellung ist `rc4` Und `des`, Wenn aber ein AES-Typ angegeben wird, ist AES-Verschlüsselung aktiviert. Sie können auch die Option verwenden, um die schwächeren RC4- und DES-Verschlüsselungstypen explizit zu deaktivieren. In ONTAP 9.11.1 und früheren Versionen müssen Sie den verwenden `-is-aes-encryption-enabled` Option zum Aktivieren und Deaktivieren von AES-Verschlüsselung, und Verschlüsselungstypen können nicht angegeben werden.

Zur Verbesserung der Sicherheit ändert die Storage Virtual Machine (SVM) bei jeder Änderung der AES-Sicherheitsoption ihr Passwort für das Computerkonto in der AD. Wenn Sie das Passwort ändern, sind möglicherweise administrative AD-Anmeldeinformationen für die Organisationseinheit (Organisationseinheit, OU) erforderlich, die das Computerkonto enthält.

Wenn eine SVM als Disaster-Recovery-Ziel konfiguriert ist, wo sie nicht erhalten wird (das `-identity-preserve` Die Option ist auf festgelegt `false` In der SnapMirror-Konfiguration) werden die nicht standardmäßigen SMB-Server-Sicherheitseinstellungen nicht auf das Ziel repliziert. Wenn Sie die AES-Verschlüsselung auf der Quell-SVM aktiviert haben, müssen Sie sie manuell aktivieren.

.Schritte
[role="tabbed-block"]
====
.ONTAP 9.12.1 und höher
--
. Führen Sie eine der folgenden Aktionen aus:
+
|===
| Wenn Sie möchten, dass die AES-Verschlüsselungstypen für Kerberos Kommunikation... | Geben Sie den Befehl ein... 


 a| 
Aktiviert
 a| 
`vserver cifs security modify -vserver vserver_name -advertised-enc-types aes-128,aes-256`



 a| 
Deaktiviert
 a| 
`vserver cifs security modify -vserver vserver_name -advertised-enc-types des,rc4`

|===
+
*Hinweis:* Das `-is-aes-encryption-enabled` Die Option ist veraltet in ONTAP 9.12.1 und kann in einer späteren Version entfernt werden.

. Vergewissern Sie sich, dass die AES-Verschlüsselung nach Bedarf aktiviert oder deaktiviert ist: `vserver cifs security show -vserver vserver_name -fields advertised-enc-types`


.Beispiele
Im folgenden Beispiel werden die AES-Verschlüsselungstypen für den SMB-Server auf SVM vs1 aktiviert:

[listing]
----
cluster1::> vserver cifs security modify -vserver vs1 -advertised-enc-types aes-128,aes-256

cluster1::> vserver cifs security show -vserver vs1 -fields advertised-enc-types

vserver  advertised-enc-types
-------- --------------------
vs1      aes-128,aes-256
----
Im folgenden Beispiel werden die AES-Verschlüsselungstypen für den SMB-Server auf SVM vs2 aktiviert. Der Administrator wird aufgefordert, die Administrator-AD-Anmeldedaten für die Organisationseinheit einzugeben, die den SMB-Server enthält.

[listing]
----
cluster1::> vserver cifs security modify -vserver vs2 -advertised-enc-types aes-128,aes-256
----
Info: Um die SMB AES Verschlüsselung zu aktivieren, das Passwort für den SMB Server
Computerkonto muss zurückgesetzt werden. Geben Sie den Benutzernamen und das Kennwort für den ein
SMB-Domäne „example.com“.

Geben Sie Ihre Benutzer-ID ein: Administrator

Geben Sie Ihr Kennwort ein:

Cluster1::> vserver cifs Security show -vserver vs2 -fields advertised-enc-types

vserver Advertised-enc-Typen
------- ----------------------
vs2 aes-128, aes-256

--
.ONTAP 9.11.1 und früher
--
. Führen Sie eine der folgenden Aktionen aus:
+
|===
| Wenn Sie möchten, dass die AES-Verschlüsselungstypen für Kerberos Kommunikation... | Geben Sie den Befehl ein... 


 a| 
Aktiviert
 a| 
`vserver cifs security modify -vserver vserver_name -is-aes-encryption-enabled true`



 a| 
Deaktiviert
 a| 
`vserver cifs security modify -vserver vserver_name -is-aes-encryption-enabled false`

|===
. Vergewissern Sie sich, dass die AES-Verschlüsselung nach Bedarf aktiviert oder deaktiviert ist: `vserver cifs security show -vserver vserver_name -fields is-aes-encryption-enabled`
+
Der `is-aes-encryption-enabled` Feld wird angezeigt `true` Bei Aktivierung der AES-Verschlüsselung und `false` Wenn sie deaktiviert ist.



.Beispiele
Im folgenden Beispiel werden die AES-Verschlüsselungstypen für den SMB-Server auf SVM vs1 aktiviert:

[listing]
----
cluster1::> vserver cifs security modify -vserver vs1 -is-aes-encryption-enabled true

cluster1::> vserver cifs security show -vserver vs1 -fields is-aes-encryption-enabled

vserver  is-aes-encryption-enabled
-------- -------------------------
vs1      true
----
Im folgenden Beispiel werden die AES-Verschlüsselungstypen für den SMB-Server auf SVM vs2 aktiviert. Der Administrator wird aufgefordert, die Administrator-AD-Anmeldedaten für die Organisationseinheit einzugeben, die den SMB-Server enthält.

[listing]
----
cluster1::> vserver cifs security modify -vserver vs2 -is-aes-encryption-enabled true

Info: In order to enable SMB AES encryption, the password for the CIFS server
machine account must be reset. Enter the username and password for the
SMB domain "EXAMPLE.COM".

Enter your user ID: administrator

Enter your password:

cluster1::> vserver cifs security show -vserver vs2 -fields is-aes-encryption-enabled

vserver  is-aes-encryption-enabled
-------- -------------------------
vs2      true
----
--
====