---
permalink: smb-admin/enable-encrypted-connections-domain-controllers-task.html 
sidebar: sidebar 
keywords: ontap, connection, domain, controller, encrypt, enable, enable encrypted connections to domain controllers 
summary: Ab ONTAP 9.8 können Sie festlegen, dass Verbindungen zu Domänencontrollern verschlüsselt werden. 
---
= Aktivieren Sie verschlüsselte Verbindungen zu ONTAP SMB-Domänencontrollern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.8 können Sie festlegen, dass Verbindungen zu Domänencontrollern verschlüsselt werden.

.Über diese Aufgabe
ONTAP erfordert Verschlüsselung für die Kommunikation mit dem Domänencontroller (DC), wenn die `-encryption-required-for-dc-connection` Option auf eingestellt `true` ist; die Standardeinstellung ist `false`. Wenn die Option eingestellt ist, wird nur das SMB3-Protokoll für ONTAP-DC-Verbindungen verwendet, da Verschlüsselung nur von SMB3 unterstützt wird.

Wenn verschlüsselte DC-Kommunikation erforderlich ist, `-smb2-enabled-for-dc-connections` wird die Option ignoriert, da ONTAP nur SMB3-Verbindungen aushandelt. Wenn ein DC SMB3 und Verschlüsselung nicht unterstützt, stellt ONTAP keine Verbindung damit her.

.Schritt
. Verschlüsselte Kommunikation mit dem DC aktivieren: `vserver cifs security modify -vserver _svm_name_ -encryption-required-for-dc-connection true`

