---
permalink: smb-admin/enable-disable-oplocks-existing-shares-task.html 
sidebar: sidebar 
keywords: oplock, enable, smb, share, storage, virtual, machine, svm, default, circumstance, disable, alternative, enable or disable oplocks on existing smb shares 
summary: Oplocks sind auf SMB-Freigaben auf Storage Virtual Machines standardmäßig aktiviert. Unter bestimmten Umständen möchten Sie möglicherweise Oplocks deaktivieren. Alternativ, wenn Sie Oplocks zuvor auf einer Freigabe deaktiviert haben, möchten Sie sie möglicherweise wieder aktivieren. 
---
= Oplocks auf bestehenden ONTAP SMB-Freigaben aktivieren oder deaktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Oplocks sind auf SMB-Freigaben auf Storage Virtual Machines (SVMs) standardmäßig aktiviert. Unter bestimmten Umständen kann es sinnvoll sein, Oplocks zu deaktivieren; alternativ kann, falls Oplocks zuvor für eine Freigabe deaktiviert wurden, eine erneute Aktivierung erfolgen.

.Über diese Aufgabe
Wenn Oplocks auf dem Volume, das eine Freigabe enthält, aktiviert sind, die Oplock-Freigabeeigenschaft für diese Freigabe jedoch deaktiviert ist, sind Oplocks für diese Freigabe deaktiviert. Die Deaktivierung von Oplocks für eine Freigabe hat Vorrang vor der Aktivierung von Oplocks für das Volume. Durch die Deaktivierung von Oplocks für die Freigabe werden sowohl opportunistische als auch Lease Oplocks deaktiviert. Oplocks können für bestehende Freigaben jederzeit aktiviert oder deaktiviert werden.

.Schritt
. Die entsprechende Maßnahme ausführen:
+
|===
| Wenn Sie möchten... | Dann... 


 a| 
Oplocks für eine Freigabe aktivieren, indem eine bestehende Freigabe geändert wird
 a| 
Geben Sie den folgenden Befehl ein: `vserver cifs share properties add -vserver _vserver_name_ -share-name share_name -share-properties oplocks`

[NOTE]
====
Sie können zusätzliche Freigabeeigenschaften mithilfe einer durch Kommas getrennten Liste angeben.

====
Neu hinzugefügte Eigenschaften werden der bestehenden Liste der Share-Eigenschaften hinzugefügt. Alle zuvor festgelegten Share-Eigenschaften bleiben bestehen.



 a| 
Oplocks für eine Freigabe durch Ändern einer bestehenden Freigabe deaktivieren
 a| 
Geben Sie den folgenden Befehl ein: `vserver cifs share properties remove -vserver _vserver_name_ -share-name _share_name_ -share-properties oplocks`

[NOTE]
====
Sie können zusätzliche zu entfernende Freigabeeigenschaften mit einer durch Kommas getrennten Liste angeben.

====
Die von Ihnen entfernten Freigabeeigenschaften werden aus der bestehenden Liste der Freigabeeigenschaften gelöscht; zuvor konfigurierte Freigabeeigenschaften, die Sie nicht entfernen, bleiben jedoch weiterhin wirksam.

|===


.Beispiele
Der folgende Befehl aktiviert Oplocks für die Freigabe mit dem Namen "`Engineering`" auf der Storage Virtual Machine (SVM, ehemals bekannt als Vserver) vs1:

[listing]
----
cluster1::> vserver cifs share properties add -vserver vs1 -share-name Engineering -share-properties oplocks

cluster1::> vserver cifs share properties show
Vserver          Share            Properties
---------------- ---------------- -----------------
vs1              Engineering      oplocks
                                  browsable
                                  changenotify
                                  showsnapshot
----
Der folgende Befehl deaktiviert Oplocks für die Freigabe mit dem Namen "`Engineering`" auf SVM vs1:

[listing]
----
cluster1::> vserver cifs share properties remove -vserver vs1 -share-name Engineering -share-properties oplocks

cluster1::> vserver cifs share properties show
Vserver          Share            Properties
---------------- ---------------- -----------------
vs1              Engineering      browsable
                                  changenotify
                                  showsnapshot
----
.Verwandte Informationen
* xref:enable-disable-oplocks-when-creating-shares-task.adoc[Oplocks beim Erstellen von SMB-Freigaben aktivieren oder deaktivieren]
* xref:monitor-oplock-status-task.adoc[Oplock-Status überwachen]
* xref:add-remove-share-properties-existing-share-task.adoc[Freigabeeigenschaften bei bestehenden Shares hinzufügen oder entfernen]

