---
permalink: smb-admin/enable-disable-export-policies-task.html 
sidebar: sidebar 
keywords: enable, disable, export, policies, policy, smb, access, storage, virtual, machine, svm, control, resource, enable or disable export policies for smb access 
summary: 'Sie können Exportrichtlinien für SMB-Zugriff auf Storage Virtual Machines (SVMs) aktivieren oder deaktivieren. Die Verwendung von Exportrichtlinien zur Steuerung des SMB-Zugriffs auf Ressourcen ist optional.' 
---
= Aktivieren oder Deaktivieren von Exportrichtlinien für SMB-Zugriff
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Exportrichtlinien für SMB-Zugriff auf Storage Virtual Machines (SVMs) aktivieren oder deaktivieren. Die Verwendung von Exportrichtlinien zur Steuerung des SMB-Zugriffs auf Ressourcen ist optional.

.Bevor Sie beginnen
Nachfolgend sind die Anforderungen für die Aktivierung von Exportrichtlinien für SMB aufgeführt:

* Der Client muss über einen „PTR“-Datensatz in DNS verfügen, bevor Sie die Exportregeln für diesen Client erstellen.
* Ein zusätzlicher Satz von „A“- und „PTR“-Datensätzen für Hostnamen ist erforderlich, wenn die SVM den Zugriff auf NFS-Clients ermöglicht, und der Hostname, den Sie für den NFS-Zugriff verwenden möchten, sich vom CIFS-Servernamen unterscheidet.


.Über diese Aufgabe
Beim Einrichten eines neuen CIFS-Servers auf Ihrer SVM ist die Verwendung von Exportrichtlinien für SMB-Zugriff standardmäßig deaktiviert. Sie können Exportrichtlinien für SMB-Zugriffe aktivieren, wenn Sie den Zugriff auf Basis des Authentifizierungsprotokoll oder anhand von Client-IP-Adressen oder Host-Namen steuern möchten. Die Exportrichtlinien für SMB-Zugriff können jederzeit aktiviert oder deaktiviert werden.


NOTE: Durch die Aktivierung von Exportrichtlinien für CIFS/SMB in einer NFS-fähigen SVM kann ein Linux Client mithilfe des Befehls auf der SVM die Verbindungspfade aller SMB-Volumes mit zugehörigen Regeln für `showmount -e` die Exportrichtlinie anzeigen.

.Schritte
. Legen Sie die Berechtigungsebene auf erweitert fest: `set -privilege advanced`
. Exportrichtlinien aktivieren oder deaktivieren:
+
** Exportrichtlinien aktivieren: `vserver cifs options modify -vserver _vserver_name_ -is-exportpolicy-enabled true`
** Exportrichtlinien deaktivieren: `vserver cifs options modify -vserver _vserver_name_ -is-exportpolicy-enabled false`


. Kehren Sie zur Administrator-Berechtigungsebene zurück: `set -privilege admin`


.Beispiel
Im folgenden Beispiel können Exportrichtlinien verwendet werden, um den Zugriff von SMB-Clients auf Ressourcen von SVM vs1 zu kontrollieren:

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options modify -vserver vs1 -is-exportpolicy-enabled true

cluster1::*> set -privilege admin
----