---
permalink: smb-admin/enable-ipv6-task.html 
sidebar: sidebar 
keywords: ipv6, network, enable, cluster, setup, administrator, smb, enable ipv6 for smb, cluster administrator only 
summary: IPv6-Netzwerke sind während der Cluster-Einrichtung nicht aktiviert. Ein Cluster-Administrator muss IPv6 aktivieren, nachdem das Cluster-Setup abgeschlossen ist, um IPv6 für SMB zu verwenden. Wenn der Cluster-Administrator IPv6 aktiviert, wird er für den gesamten Cluster aktiviert. 
---
= Aktivieren Sie IPv6 für ONTAP-SMB-Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IPv6-Netzwerke sind während der Cluster-Einrichtung nicht aktiviert. Ein Cluster-Administrator muss IPv6 aktivieren, nachdem das Cluster-Setup abgeschlossen ist, um IPv6 für SMB zu verwenden. Wenn der Cluster-Administrator IPv6 aktiviert, wird er für den gesamten Cluster aktiviert.

.Schritt
. IPv6 aktivieren: `network options ipv6 modify -enabled true`
+
Weitere Informationen zur Aktivierung von IPv6 im Cluster und zum Konfigurieren von IPv6-LIFs finden Sie im _Network Management Guide_.

+
IPv6 ist aktiviert. IPv6-Daten-LIFs für SMB-Zugriff können konfiguriert werden.



.Verwandte Informationen
* xref:monitor-display-ipv6-sessions-task.adoc[Überwachen und Anzeigen von Informationen zu IPv6-SMB-Sitzungen]
* link:../networking/networking_reference.html["Netzwerkvisualisierung mit System Manager"]
* link:https://docs.netapp.com/us-en/ontap-cli/network-options-ipv6-modify.html["Netzwerkoptionen ipv6 ändern"^]

