---
permalink: smb-admin/enable-branchcache-existing-share-task.html 
sidebar: sidebar 
keywords: enable, branchcache, exist, smb, share, add, share, property, exist, list, enable branchcache on an existing smb share 
summary: Sie können BranchCache auf einer vorhandenen SMB-Freigabe aktivieren, indem Sie die Eigenschaft branchcache-Freigabe zur vorhandenen Liste der Freigabeneigenschaften hinzufügen. 
---
= Aktivieren Sie BranchCache auf einer vorhandenen SMB-Freigabe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können BranchCache auf einer vorhandenen SMB-Freigabe aktivieren, indem Sie die hinzufügen `branchcache` Eigenschaft für die vorhandene Liste der Freigabegenschaften freigeben.

.Über diese Aufgabe
* Wenn BranchCache auf der SMB-Freigabe aktiviert ist, muss die Konfiguration der Offline-Dateien auf manuelle Cache-Speicherung festgelegt sein.
+
Wenn die Einstellung der Offline-Dateien der vorhandenen Freigabe nicht auf manuelles Caching eingestellt ist, müssen Sie sie durch Ändern der Freigabe konfigurieren.

* Sie können die einstellen `branchcache` Eigenschaft auf einer Freigabe, auch wenn BranchCache nicht konfiguriert und auf der Storage Virtual Machine (SVM) aktiviert ist.
+
Um jedoch gecachte Inhalte bereitstellen zu können, müssen BranchCache auf der SVM konfiguriert und aktiviert werden.

* Wenn Sie die hinzufügen `branchcache` Freigabegenschaft für die Freigabe, bestehende Freigabeneinstellungen und Freigabegenschaften bleiben erhalten.
+
Die Eigenschaft BranchCache-Freigabe wird zur bestehenden Liste der Freigabeneigenschaften hinzugefügt. Weitere Informationen zur Verwendung des `vserver cifs share properties add` Befehl, siehe die man-Pages.



.Schritte
. Konfigurieren Sie bei Bedarf die Einstellung Offline-Dateifreigabe für manuelles Caching:
+
.. Legen Sie fest, welche Einstellungen für die Offline-Dateifreigabe verwendet werden `vserver cifs share show` Befehl.
.. Wenn die Einstellung Offline-Dateifreigabe nicht auf manuell eingestellt ist, ändern Sie sie in den gewünschten Wert: `vserver cifs share modify -vserver vserver_name -share-name share_name -offline-files manual`


. BranchCache auf einer vorhandenen SMB-Freigabe aktivieren: `vserver cifs share properties add -vserver vserver_name -share-name share_name -share-properties branchcache`
. Vergewissern Sie sich, dass die Eigenschaft BranchCache-Freigabe auf der SMB-Freigabe festgelegt ist: `vserver cifs share show -vserver vserver_name -share-name share_name`


.Beispiel
Mit dem folgenden Befehl wird BranchCache auf einer vorhandenen SMB-Freigabe mit dem Namen „`data2`“ mit dem Pfad von aktiviert `/data2` Auf SVM vs1:

[listing]
----
cluster1::> vserver cifs share show -vserver vs1 -share-name data2

                      Vserver: vs1
                        Share: data2
     CIFS Server NetBIOS Name: VS1
                         Path: /data2
             Share Properties: oplocks
                               browsable
                               changenotify
                               showsnapshot
           Symlink Properties: -
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: 10s
                  Volume Name: -
                Offline Files: manual
Vscan File-Operations Profile: standard

cluster1::> vserver cifs share properties add  -vserver vs1 -share-name data2 -share-properties branchcache

cluster1::> vserver cifs share show -vserver vs1 -share-name data2

                      Vserver: vs1
                        Share: data2
     CIFS Server NetBIOS Name: VS1
                         Path: /data2
             Share Properties: oplocks
                               browsable
                               showsnapshot
                               changenotify
                               branchcache
           Symlink Properties: -
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: 10s
                  Volume Name: -
                Offline Files: manual
Vscan File-Operations Profile: standard
----
.Verwandte Informationen
xref:add-remove-share-properties-eexisting-share-task.adoc[Hinzufügen oder Entfernen von Share-Eigenschaften für eine vorhandene SMB-Freigabe]

xref:disable-branchcache-single-share-task.adoc[Deaktivieren von BranchCache auf einer einzelnen SMB-Freigabe]
