---
permalink: smb-admin/enable-disable-odx-task.html 
sidebar: sidebar 
keywords: enable, disable, odx, storage, virtual, machine, svm, default, support, copy, offload, smb, enable, enable or disable odx 
summary: 'ODX lässt sich auf Storage Virtual Machines (SVMs) aktivieren oder deaktivieren. Der Standard soll die Unterstützung für einen ODX Copy-Offload ermöglichen, wenn SMB 3.0 ebenfalls aktiviert ist.' 
---
= Aktivieren oder Deaktivieren von ODX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ODX lässt sich auf Storage Virtual Machines (SVMs) aktivieren oder deaktivieren. Der Standard soll die Unterstützung für einen ODX Copy-Offload ermöglichen, wenn SMB 3.0 ebenfalls aktiviert ist.

SMB 3.0 muss aktiviert sein.

Wenn Sie SMB 3.0 deaktivieren, deaktiviert ONTAP auch SMB ODX. Wenn Sie SMB 3.0 erneut aktivieren, müssen Sie SMB ODX manuell neu aktivieren.

.Schritte
. Legen Sie die Berechtigungsebene auf erweitert fest: `set -privilege advanced`
. Führen Sie eine der folgenden Aktionen aus:
+
|===
| Falls eine ODX Copy-Offload sein soll: | Geben Sie den Befehl ein... 


 a| 
Aktiviert
 a| 
`vserver cifs options modify -vserver vserver_name -copy-offload-enabled true`



 a| 
Deaktiviert
 a| 
`vserver cifs options modify -vserver vserver_name -copy-offload-enabled false`

|===
. Zurück zur Administratorberechtigungsebene: `set -privilege admin`


Das folgende Beispiel ermöglicht den ODX Copy-Offload auf SVM vs1:

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options modify -vserver vs1 -copy-offload-enabled true

cluster1::*> set -privilege admin
----
xref:server-options-reference.adoc[Verfügbare SMB-Server-Optionen]
