---
permalink: smb-admin/enable-disable-local-users-groups-authentication.html 
sidebar: sidebar 
keywords: local, user, group, access, control, ntfs, security-style, data, enable, authentication, disable, enable or disable local users and groups functionality 
summary: Bevor Sie lokale Benutzer und Gruppen für die Zugriffskontrolle von NTFS-Sicherheitsdaten verwenden können, müssen die Funktionen lokaler Benutzer und Gruppen aktiviert sein. Wenn Sie außerdem lokale Benutzer zur SMB-Authentifizierung verwenden möchten, muss die lokale Benutzerauthentifizierungsfunktion aktiviert sein. 
---
= Aktivieren oder Deaktivieren der lokalen ONTAP SMB-Benutzer- und Gruppenfunktionalität
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie lokale Benutzer und Gruppen für die Zugriffskontrolle von NTFS-Sicherheitsdaten verwenden können, müssen die Funktionen lokaler Benutzer und Gruppen aktiviert sein. Wenn Sie außerdem lokale Benutzer zur SMB-Authentifizierung verwenden möchten, muss die lokale Benutzerauthentifizierungsfunktion aktiviert sein.

Die Funktionen für lokale Benutzer und Gruppen und die lokale Benutzerauthentifizierung sind standardmäßig aktiviert. Wenn sie nicht aktiviert sind, müssen Sie sie aktivieren, bevor Sie lokale Benutzer und Gruppen konfigurieren und verwenden können. Sie können die Funktionen für lokale Benutzer und Gruppen jederzeit deaktivieren.

Zusätzlich zum ausdrücklichen Deaktivieren von Funktionen für lokale Benutzer und Gruppen deaktiviert ONTAP Funktionen für lokale Benutzer und Gruppen, wenn ein Node im Cluster auf eine ONTAP Version zurückgesetzt wird, die die Funktionen nicht unterstützt. Die Funktionen lokaler Benutzer und Gruppen sind erst aktiviert, wenn alle Nodes im Cluster eine Version von ONTAP ausführen, die sie unterstützt.

.Verwandte Informationen
* xref:manage-local-user-accounts.html[Lokale Benutzerkonten ändern]
* xref:manage-local-groups.html[Ändern von lokalen Gruppen]
* xref:manage-local-privileges.html[Fügen Sie den lokalen oder Domänenbenutzern oder -Gruppen Berechtigungen hinzu]




[[enable-or-disable-local-users-and-groups-on-ontap-smb-servers]]
== Aktivieren oder Deaktivieren lokaler Benutzer und Gruppen auf ONTAP SMB-Servern

Lokale Benutzer und Gruppen können für den SMB-Zugriff auf Storage Virtual Machines (SVMs) aktiviert oder deaktiviert werden. Die Funktion für lokale Benutzer und Gruppen ist standardmäßig aktiviert.

.Über diese Aufgabe
Sie können lokale Benutzer und Gruppen beim Konfigurieren von SMB-Freigaben- und NTFS-Dateiberechtigungen verwenden und können optional lokale Benutzer zur Authentifizierung verwenden, wenn Sie eine SMB-Verbindung erstellen. Um lokale Benutzer für die Authentifizierung zu verwenden, müssen Sie außerdem die Authentifizierungsoption für lokale Benutzer und Gruppen aktivieren.

.Schritte
. Legen Sie die Berechtigungsebene auf erweitert fest:
+
[source, cli]
----
set -privilege advanced
----
. Lokale Benutzer und Gruppen aktivieren oder deaktivieren:
+
** Lokale Benutzer und Gruppen aktivieren:
+
[source, cli]
----
vserver cifs options modify -vserver <SVM_name> -is-local-users-and-groups-enabled true
----
** Lokale Benutzer und Gruppen deaktivieren:
+
[source, cli]
----
vserver cifs options modify -vserver <SVM_name> -is-local-users-and-groups-enabled false
----


. Zurück zur Administratorberechtigungsebene:
+
[source, cli]
----
set -privilege admin
----


.Beispiel
Das folgende Beispiel bietet lokale Benutzer und Gruppen-Funktionen auf SVM vs1:

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options modify -vserver vs1 -is-local-users-and-groups-enabled true

cluster1::*> set -privilege admin
----
.Verwandte Informationen
* xref:manage-local-user-accounts.adoc[Lokale Benutzerkonten verwalten] == Lokale Benutzerauthentifizierung auf ONTAP SMB-Servern aktivieren oder deaktivieren


Die Authentifizierung von lokalen Benutzern für SMB-Zugriff auf Storage Virtual Machines (SVMs) lässt sich aktivieren oder deaktivieren. Die Standardeinstellung erlaubt die lokale Benutzerauthentifizierung. Dies ist nützlich, wenn die SVM keinen Domänencontroller kontaktieren kann oder Sie keine Zugriffssteuerungen auf Domänenebene verwenden möchten.

.Bevor Sie beginnen
Lokale Benutzer und Gruppen müssen auf dem CIFS-Server aktiviert sein.

.Über diese Aufgabe
Sie können die lokale Benutzerauthentifizierung jederzeit aktivieren oder deaktivieren. Wenn Sie lokale Benutzer zur Authentifizierung beim Erstellen einer SMB-Verbindung verwenden möchten, müssen Sie auch die Option für lokale Benutzer und Gruppen des CIFS-Servers aktivieren.

.Schritte
. Legen Sie die Berechtigungsebene auf erweitert fest:
+
[source, cli]
----
set -privilege advanced
----
. Lokale Benutzerauthentifizierung aktivieren oder deaktivieren:
+
** Lokale Benutzerauthentifizierung aktivieren:
+
[source, cli]
----
vserver cifs options modify -vserver <SVM_name> -is-local-auth-enabled true
----
** Lokale Benutzerauthentifizierung deaktivieren:
+
[source, cli]
----
vserver cifs options modify -vserver <SVM_name> -is-local-auth-enabled false
----


. Zurück zur Administratorberechtigungsebene:
+
[source, cli]
----
set -privilege admin
----


.Beispiel
Das folgende Beispiel ermöglicht die lokale Benutzerauthentifizierung auf SVM vs1:

[listing]
----
cluster1::>set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options modify -vserver vs1 -is-local-auth-enabled true

cluster1::*> set -privilege admin
----
.Verwandte Informationen
* xref:local-user-authentication-concept.adoc[Erfahren Sie mehr über die lokale Benutzerauthentifizierung]
* xref:enable-disable-local-users-groups-authentication.html[Aktivieren oder Deaktivieren lokaler Benutzer und Gruppen auf Servern]

