---
permalink: smb-admin/export-policies-access-concept.html 
sidebar: sidebar 
keywords: export, policies, policy, smb, access, enable, cifs, server, control, svm, volume, client, data, associate, how export policies are used with smb access 
summary: Wenn auf dem SMB-Server Exportregeln für den SMB-Zugriff aktiviert sind, werden Exportregeln verwendet, um den Zugriff von SMB-Clients auf SVM-Volumes zu steuern. Für den Datenzugriff kann eine Exportregel erstellt werden, die den SMB-Zugriff erlaubt, und anschließend der Richtlinie die Volumes zugeordnet werden, die SMB-Freigaben enthalten. 
---
= Informationen zur Verwendung von Exportrichtlinien mit ONTAP SMB-Zugriff
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn auf dem SMB-Server Exportregeln für den SMB-Zugriff aktiviert sind, werden Exportregeln verwendet, um den Zugriff von SMB-Clients auf SVM-Volumes zu steuern. Für den Datenzugriff kann eine Exportregel erstellt werden, die den SMB-Zugriff erlaubt, und anschließend der Richtlinie die Volumes zugeordnet werden, die SMB-Freigaben enthalten.

Für eine Exportregel gilt eine oder mehrere Regeln, die festlegen, welche Clients Zugriff auf die Daten erhalten und welche Authentifizierungsprotokolle für Lese- und Schreibzugriff unterstützt werden. Exportregeln können so konfiguriert werden, dass der Zugriff über SMB für alle Clients, ein Subnetz von Clients oder einen bestimmten Client erlaubt ist und dass die Authentifizierung mittels Kerberos-Authentifizierung, NTLM-Authentifizierung oder sowohl Kerberos- als auch NTLM-Authentifizierung bei der Bestimmung des Lese- und Schreibzugriffs auf Daten zulässig ist.

Nach der Verarbeitung aller auf die Exportregel angewendeten Exportregeln kann ONTAP feststellen, ob dem Client Zugriff gewährt wird und welche Zugriffsebene gewährt wird. Exportregeln gelten für Client-Rechner, nicht für Windows-Benutzer und -Gruppen. Exportregeln ersetzen nicht die Windows-Benutzer- und -gruppenbasierte Authentifizierung und Autorisierung. Exportregeln bieten eine zusätzliche Sicherheitsebene zum Schutz des Zugriffs, zusätzlich zu den Berechtigungen für Freigaben und Dateizugriff.

Jedem Volume wird genau eine Exportregel zugeordnet, um den Clientzugriff auf das Volume zu konfigurieren. Jede SVM kann mehrere Exportregeln enthalten. Dadurch ergeben sich für SVMs mit mehreren Volumes folgende Möglichkeiten:

* Weisen Sie jedem Volume der SVM unterschiedliche Exportrichtlinien zu, um die Zugriffskontrolle für jeden einzelnen Client auf jedes Volume in der SVM zu ermöglichen.
* Dieselbe Exportregel kann mehreren Volumes der SVM zugewiesen werden, sodass eine identische Clientzugriffskontrolle möglich ist, ohne für jedes Volume eine neue Exportregel erstellen zu müssen.


Jede SVM verfügt über mindestens eine Export-Richtlinie namens „`default`“, die keine Regeln enthält. Sie können diese Export-Richtlinie nicht löschen, aber Sie können sie umbenennen oder ändern. Jedes Volume auf der SVM ist standardmäßig der Standard-Export-Richtlinie zugeordnet. Wenn Export-Richtlinien für den SMB-Zugriff auf der SVM deaktiviert sind, hat die Export-Richtlinie „`default`“ keine Auswirkungen auf den SMB-Zugriff.

Es ist möglich, Regeln zu konfigurieren, die sowohl NFS- als auch SMB-Hosts Zugriff gewähren, und diese Regel mit einer Exportregel zu verknüpfen, die anschließend dem Volume zugeordnet werden kann, das Daten enthält, auf die sowohl NFS- als auch SMB-Hosts zugreifen müssen. Alternativ kann für einige Volumes, auf die nur SMB-Clients zugreifen müssen, eine Exportregel mit Regeln konfiguriert werden, die ausschließlich den Zugriff über das SMB-Protokoll erlauben und für die Authentifizierung bei Lese- und Schreibzugriffen ausschließlich Kerberos oder NTLM (oder beides) verwenden. Die Exportregel wird dann den Volumes zugeordnet, bei denen ausschließlich SMB-Zugriff erforderlich ist.

Wenn Exportregeln für SMB aktiviert sind und ein Client eine Zugriffsanfrage stellt, die von der entsprechenden Exportregel nicht zugelassen wird, schlägt die Anfrage mit einer „Zugriff verweigert“-Meldung fehl. Wenn ein Client keiner Regel in der Exportregel des Volumes entspricht, wird der Zugriff verweigert. Ist eine Exportregel leer, werden alle Zugriffe implizit verweigert. Dies gilt auch dann, wenn die Freigabe- und Dateiberechtigungen den Zugriff ansonsten erlauben würden. Das bedeutet, dass die Exportregel auf Volumes mit SMB-Freigaben mindestens Folgendes zulassen muss:

* Zugriff für alle Clients oder die entsprechende Teilmenge der Clients zulassen
* Zugriff über SMB zulassen
* Angemessener Lese- und Schreibzugriff durch Kerberos- oder NTLM-Authentifizierung (oder beides) möglich


Informationen dazu link:../nfs-config/export-policies-concept.html["Konfiguration und Verwaltung von Exportrichtlinien"].
