---
permalink: smb-admin/flush-hashes-svm-branchcache-task.html 
sidebar: sidebar 
keywords: flush, cache, hash, branchcache, store, storage, virtual, machine, svm, caching, mode, distribute, host, flush hashes from the svm branchcache hash store 
summary: 'Sie können alle Hash-Speicher des BranchCache auf der Storage Virtual Machine (SVM) spülen, die im Cache gespeichert sind. Dies kann nützlich sein, wenn Sie die Konfiguration von BranchCache in der Zweigstelle geändert haben. Wenn Sie beispielsweise den Caching-Modus vor kurzem vom verteilten Caching- zum gehosteten Caching-Modus neu konfigurieren, sollten Sie den Hash-Speicher spülen.' 
---
= Hashes aus dem ONTAP SMB SVM BranchCache-Hash-Speicher leeren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können alle Hash-Speicher des BranchCache auf der Storage Virtual Machine (SVM) spülen, die im Cache gespeichert sind. Dies kann nützlich sein, wenn Sie die Konfiguration von BranchCache in der Zweigstelle geändert haben. Wenn Sie beispielsweise den Caching-Modus vor kurzem vom verteilten Caching- zum gehosteten Caching-Modus neu konfigurieren, sollten Sie den Hash-Speicher spülen.

.Über diese Aufgabe
Nach der Hash-Funktion erstellt ONTAP neue Hash-Funktionen, wenn neue Anforderungen von Clients mit BranchCache-Aktivierung gestellt werden.

.Schritt
. Leeren Sie die Hashes aus dem BranchCache-Hash-Speicher: `vserver cifs branchcache hash-flush -vserver _vserver_name_`
+
`vserver cifs branchcache hash-flush -vserver vs1`


