---
permalink: smb-admin/flush-hashes-svm-branchcache-task.html 
sidebar: sidebar 
keywords: flush, cache, hash, branchcache, store, storage, virtual, machine, svm, caching, mode, distribute, host, flush hashes from the svm branchcache hash store 
summary: Sie können alle zwischengespeicherten Hashes aus dem BranchCache Hash-Speicher auf der Storage Virtual Machine löschen. Dies kann hilfreich sein, wenn die BranchCache Konfiguration der Zweigstelle geändert wurde. Wenn beispielsweise der Caching-Modus kürzlich von verteiltem Caching auf gehosteten Caching-Modus umgestellt wurde, empfiehlt sich das Leeren des Hash-Speichers. 
---
= Hashes aus dem ONTAP SMB SVM BranchCache Hash-Speicher löschen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können alle zwischengespeicherten Hashes aus dem BranchCache Hash-Speicher auf der Storage Virtual Machine (SVM) löschen. Dies kann hilfreich sein, wenn die BranchCache Konfiguration der Zweigstelle geändert wurde. Wenn beispielsweise der Caching-Modus kürzlich von verteiltem Caching auf gehosteten Caching-Modus umgestellt wurde, empfiehlt sich das Leeren des Hash-Speichers.

.Über diese Aufgabe
Nach dem Leeren der Hashes erstellt ONTAP neue Hashes, sobald neue Anfragen von BranchCache-aktivierten Clients gestellt werden.

.Schritt
. Die Hashes aus dem BranchCache Hash-Speicher werden entfernt: `vserver cifs branchcache hash-flush -vserver _vserver_name_`
+
`vserver cifs branchcache hash-flush -vserver vs1`


