---
permalink: smb-admin/folder-redirection-store-data-concept.html 
sidebar: sidebar 
keywords: ontap, support, microsoft, folder, redirection, enable, administrator, redirect, location, cifs, server, windows, client, store, smb, share, use folder redirection to store data on a cifs server 
summary: ONTAP unterstützt die Microsoft Ordnerumleitung, sodass Benutzer oder Administratoren den Pfad eines lokalen Ordners an einen Ort des CIFS-Servers umleiten können. Es erscheint, als ob umgeleitete Ordner auf dem lokalen Windows-Client gespeichert werden, obwohl die Daten auf einer SMB-Freigabe gespeichert sind. 
---
= Verwenden Sie die Ordnerumleitung, um Daten auf einer SMB-Server-Übersicht zu speichern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP unterstützt die Microsoft Ordnerumleitung, sodass Benutzer oder Administratoren den Pfad eines lokalen Ordners an einen Ort des CIFS-Servers umleiten können. Es erscheint, als ob umgeleitete Ordner auf dem lokalen Windows-Client gespeichert werden, obwohl die Daten auf einer SMB-Freigabe gespeichert sind.

Die Ordnerumleitung ist hauptsächlich für Unternehmen gedacht, die bereits Home Directories implementiert haben und die Kompatibilität mit der vorhandenen Home Directory Umgebung beibehalten möchten.

* `Documents`, `Desktop` Und `Start Menu` sind Beispiele für Ordner, die Sie umleiten können.
* Benutzer können Ordner von ihrem Windows-Client umleiten.
* Administratoren können die Ordnerumleitung zentral konfigurieren und verwalten, indem sie Gruppenrichtlinienobjekte in Active Directory konfigurieren.
* Wenn Administratoren Roaming-Profile konfiguriert haben, können Administratoren mithilfe der Ordnerumleitung Benutzerdaten von Profildaten trennen.
* Administratoren können mithilfe der Ordnerumleitung und der Offline-Dateien die Datenspeicherung für lokale Ordner auf den CIFS-Server umleiten, während Benutzer den Inhalt lokal zwischenspeichern können.


.Verwandte Informationen
xref:offline-files-allow-caching-concept.adoc[Verwendung von Offline-Dateien, um das Caching von Dateien für die Offline-Verwendung zu ermöglichen]

xref:roaming-profiles-store-user-profiles-concept.adoc[Mithilfe von Roaming-Profilen können Sie Benutzerprofile zentral auf einem CIFS-Server speichern, der der SVM zugeordnet ist]
