---
permalink: smb-admin/gpo-updates-failing-reference.html 
sidebar: sidebar 
keywords: circumstance, group, policy, object, gpo, update, windows, domain, controller, fail, visible, central, access, policy, setting, section, output, verserver, cifs, group-policy, show-defined, command, correct, what to do if gpo updates are failing 
summary: Unter bestimmten Umständen schlägt die Aktualisierung von Gruppenrichtlinienobjekten von Windows 2012-Domänencontrollern fehl, was dazu führt, dass im Abschnitt „Central Access Policy Settings“ der Ausgabe des Befehls „vserver cifs Group-Policy show-defined“ nichts sichtbar ist. Sie sollten wissen, wie dieses Problem zu beheben, wenn es auftritt. 
---
= Was tun, wenn GPO-Aktualisierungen fehlschlagen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unter bestimmten Umständen schlägt die Aktualisierung von Gruppenrichtlinienobjekten (GPO) von Windows 2012-Domänencontrollern fehl, was dazu führt, dass unter dem nichts sichtbar ist `Central Access Policy Settings` Abschnitt der Ausgabe für das `vserver cifs group-policy show-defined` Befehl. Sie sollten wissen, wie dieses Problem zu beheben, wenn es auftritt.

|===
| Zugrunde liegende Ursache | Abhilfe 


 a| 
Wenn ONTAP versucht, eine Verbindung zum Windows 2012-Domänencontroller herzustellen, um das GPO-Update durchzuführen, kann die Verbindung mit dem Fehler fehlschlagen `error 0xc00000bd (NT STATUS_DUPLICATE_NAME)`.

Dieser Fehler tritt auf, wenn sich der Servername, der für die Verbindung verwendet wird, vom NetBIOS-Namen des CIFS-Servers unterscheidet. Es gibt verschiedene Gründe, warum dies auftreten könnte, einschließlich der Verwendung von Aliasen. Darüber hinaus wird der bei der Verbindung mit dem Domänencontroller verwendete NetBIOS-Name von ONTAP so angepasst, dass die Namenslänge 15 Zeichen entspricht. Dadurch kann es angezeigt werden, dass der CIFS-Servername und der NetBIOS-Name sich unterscheiden.
 a| 
. Deaktivieren Sie NetBIOS-Namensprüfung auf dem Windows-Server, indem Sie den folgenden Registrierungsschlüssel mit dem Wert auf hinzufügen `1`:
+
`"HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanmanServer\Parameters\DisableStrictNameChecking"`

+
Weitere Informationen zu diesem Registrierungsschlüssel erhalten Sie vom Microsoft Support.

+
http://["Microsoft Support"]

. Starten Sie den Domain Controller neu.


|===