---
permalink: smb-admin/grant-null-users-access-file-system-shares-task.html 
sidebar: sidebar 
keywords: access, storage, system, resource, null, session, client, assign, group, ip, adress, null, session, grant, grant null users access to file system shares 
summary: Sie können den Zugriff auf Ihre Speichersystemressourcen durch Null-Session-Clients ermöglichen, indem Sie eine Gruppe zuweisen, die von Null-Session-Clients verwendet werden soll, und die IP-Adressen von Null-Session-Clients erfassen, um der Liste der Clients des Speichersystems hinzuzufügen, die über Null-Sessions auf Daten zugreifen dürfen. 
---
= Gewähren Sie null Benutzern Zugriff auf File System Shares
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Zugriff auf Ihre Speichersystemressourcen durch Null-Session-Clients ermöglichen, indem Sie eine Gruppe zuweisen, die von Null-Session-Clients verwendet werden soll, und die IP-Adressen von Null-Session-Clients erfassen, um der Liste der Clients des Speichersystems hinzuzufügen, die über Null-Sessions auf Daten zugreifen dürfen.

.Schritte
. Verwenden Sie die `vserver name-mapping create` Befehl zum Zuordnen des Null-Benutzers zu einem gültigen Windows-Benutzer, mit einem IP-Qualifier.
+
Der folgende Befehl ordnet den Null-Benutzer Nutzer1 mit einem gültigen Hostnamen google.com zu:

+
[listing]
----
vserver name-mapping create –direction win-unix  -position 1 –pattern “ANONYMOUS LOGON” –replacement user1 – hostname google.com
----
+
Der folgende Befehl ordnet den Null-Benutzer Nutzer1 mit einer gültigen IP-Adresse 10.238.2.54/32 zu:

+
[listing]
----
vserver name-mapping create –direction win-unix  -position 2 –pattern “ANONYMOUS LOGON” –replacement user1 –address 10.238.2.54/32
----
. Verwenden Sie die `vserver name-mapping show` Bestätigen Sie mit dem Befehl die Namenszuweisung.
+
[listing]
----
vserver name-mapping show

Vserver:   vs1
Direction: win-unix
Position Hostname         IP Address/Mask
-------- --------         ----------------
1       -                 10.72.40.83/32      Pattern: anonymous logon
                                          Replacement: user1
----
. Verwenden Sie die `vserver cifs options modify –win-name-for-null-user` Befehl zum Zuweisen der Windows-Mitgliedschaft an den Null-Benutzer.
+
Diese Option ist nur anwendbar, wenn für den Null-Benutzer eine gültige Namenszuweisung vorliegt.

+
[listing]
----
vserver cifs options modify -win-name-for-null-user user1
----
. Verwenden Sie die `vserver cifs options show` Befehl, um die Zuordnung des Null-Benutzers zu dem Windows-Benutzer oder der Windows-Gruppe zu bestätigen.
+
[listing]
----
vserver cifs options show

Vserver :vs1

Map Null User to Windows User of Group: user1
----

