---
permalink: smb-admin/how-ontap-creates-file-directory-names-concept.html 
sidebar: sidebar 
keywords: ontap, create, maintain, name, file, directories, directory, access, smb, format, how ontap creates file and directory names 
summary: ONTAP erstellt und verwaltet zwei Namen für Dateien oder Verzeichnisse in jedem Verzeichnis, auf das ein SMB-Client zugreifen kann – den ursprünglichen langen Namen und einen Namen im 8.3-Format. 
---
= Informationen zur Erstellung von ONTAP SMB Datei- und Verzeichnisnamen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP erstellt und verwaltet zwei Namen für Dateien oder Verzeichnisse in jedem Verzeichnis, auf das ein SMB-Client zugreifen kann: den ursprünglichen langen Namen und einen Namen im 8.3-Format.

Für Datei- oder Verzeichnisnamen, die die Grenze von acht Zeichen für den Namen oder die Grenze von drei Zeichen für die Dateierweiterung überschreiten, generiert ONTAP einen Namen im 8.3-Format wie folgt:

* Es kürzt den ursprünglichen Datei- oder Verzeichnisnamen auf sechs Zeichen, wenn der Name mehr als sechs Zeichen umfasst.
* Es hängt eine Tilde (~) und eine Zahl von eins bis fünf an Datei- oder Verzeichnisnamen an, die nach dem Kürzen nicht mehr eindeutig sind.
+
Wenn keine weiteren Zahlen mehr verfügbar sind, weil es mehr als fünf ähnliche Namen gibt, wird ein eindeutiger Name erstellt, der keinerlei Bezug zum ursprünglichen Namen hat.

* Im Falle von Dateien wird die Dateinamenerweiterung auf drei Zeichen gekürzt.


Wenn ein NFS-Client beispielsweise eine Datei mit dem Namen  `specifications.html` erstellt, ist der von ONTAP im 8.3-Format generierte Dateiname  `specif~1.htm`. Falls dieser Name bereits existiert, verwendet ONTAP eine andere Zahl am Ende des Dateinamens. Wenn ein NFS-Client anschließend eine weitere Datei mit dem Namen  `specifications_new.html` erstellt, ist das 8.3-Format von  `specifications_new.html`  `specif~2.htm`.
