---
permalink: smb-admin/how-ontap-creates-file-directory-names-concept.html 
sidebar: sidebar 
keywords: ontap, create, maintain, name, file, directories, directory, access, smb, format, how ontap creates file and directory names 
summary: 'ONTAP erstellt und pflegt zwei Namen für Dateien oder Verzeichnisse in jedem Verzeichnis, das Zugriff auf einen SMB-Client hat: Den ursprünglichen Long-Namen und einen Namen im 8.3-Format.' 
---
= Wie ONTAP Datei- und Verzeichnisnamen erstellt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP erstellt und pflegt zwei Namen für Dateien oder Verzeichnisse in jedem Verzeichnis, das Zugriff auf einen SMB-Client hat: Den ursprünglichen Long-Namen und einen Namen im 8.3-Format.

Bei Datei- oder Verzeichnisnamen, die den Namen von acht Zeichen oder die maximal drei Zeichen (für Dateien) überschreiten, generiert ONTAP wie folgt einen Namen im 8.3-Format:

* Der ursprüngliche Datei- oder Verzeichnisname wird auf sechs Zeichen gekürzt, wenn der Name sechs Zeichen überschreitet.
* Er fügt einen Tilde (~) und eine Zahl, eine bis fünf, an Datei- oder Verzeichnisnamen an, die nach dem Abschneiden nicht mehr eindeutig sind.
+
Wenn es aus Zahlen heraus läuft, weil es mehr als fünf ähnliche Namen gibt, erstellt es einen eindeutigen Namen, der keine Beziehung zum ursprünglichen Namen hat.

* Bei Dateien schneidet es die Dateinamenerweiterung auf drei Zeichen ab.


Beispiel: Wenn ein NFS-Client eine Datei mit dem Namen erstellt `specifications.html`, Der Dateiname im Format 8.3, der von ONTAP erstellt wurde, ist `specif~1.htm`. Wenn dieser Name bereits vorhanden ist, verwendet ONTAP am Ende des Dateinamens eine andere Nummer. Beispiel: Wenn ein NFS-Client dann eine andere Datei mit dem Namen erstellt `specifications_new.html`, Das Format 8.3 von `specifications_new.html` Ist `specif~2.htm`.
