---
permalink: smb-admin/improve-client-response-node-referrals-concept.html 
sidebar: sidebar 
keywords: auto, location, smb, automatic, node, referral, increase, client, performance, storage, virtual, machine, svm, request, host, response, improve, improve client response time by providing smb automatic node referrals with auto location 
summary: Auto Location nutzt automatische Knotenverweise von SMB, um die Leistung von SMB-Clients auf Storage Virtual Machines zu steigern. Automatische Knotenverweise leiten den anfragenden Client automatisch an eine LIF auf der Node-SVM weiter, die das Volume hostet, in dem sich die Daten befinden, was zu verbesserten Client-Antwortzeiten führen kann. 
---
= Informationen zur Verbesserung der Client-Reaktionszeit durch Bereitstellung von ONTAP SMB automatischen Knotenverweisen mit Auto Location
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auto Location nutzt automatische Knotenverweise von SMB, um die Leistung von SMB-Clients auf Storage Virtual Machines (SVMs) zu steigern. Automatische Knotenverweise leiten den anfragenden Client automatisch an eine LIF auf der Node-SVM weiter, die das Volume hostet, in dem sich die Daten befinden, was zu verbesserten Client-Antwortzeiten führen kann.

Wenn ein SMB-Client eine Verbindung zu einer auf der SVM gehosteten SMB-Freigabe herstellt, kann die Verbindung über eine LIF erfolgen, die sich auf einem Knoten befindet, dem die angeforderten Daten nicht gehören. Der Knoten, mit dem der Client verbunden ist, greift über das Clusternetzwerk auf Daten eines anderen Knotens zu. Der Client kann schnellere Antwortzeiten erzielen, wenn die SMB-Verbindung eine LIF auf dem Knoten verwendet, der die angeforderten Daten enthält.

* ONTAP stellt diese Funktionalität bereit, indem Microsoft DFS-Verweise verwendet werden, um SMB-Clients darüber zu informieren, dass eine angeforderte Datei oder ein Ordner im Namespace an einem anderen Ort gehostet wird.
+
Ein Knoten führt eine Weiterleitung durch, wenn er feststellt, dass sich auf dem Knoten, der die Daten enthält, ein SVM LIF befindet.

* Automatische Knotenweiterleitungen werden für IPv4- und IPv6-LIF-IP-Adressen unterstützt.
* Weiterleitungen erfolgen auf Grundlage des Speicherorts des Stammverzeichnisses der Freigabe, über die der Client verbunden ist.
* Die Weiterleitung erfolgt während der SMB-Aushandlung.
+
Die Weiterleitung erfolgt vor dem Verbindungsaufbau. Nachdem ONTAP den SMB-Client an den Zielknoten weitergeleitet hat, wird die Verbindung hergestellt und der Client greift ab diesem Zeitpunkt über den weitergeleiteten LIF-Pfad auf die Daten zu. Dies ermöglicht den Clients einen schnelleren Zugriff auf die Daten und vermeidet zusätzliche Cluster-Kommunikation.

+
[NOTE]
====
Wenn sich eine Freigabe über mehrere Verbindungspunkte erstreckt und einige der Verbindungen auf Volumes auf anderen Knoten liegen, sind die Daten innerhalb der Freigabe auf mehrere Knoten verteilt. Da ONTAP Verweise bereitstellt, die lokal zum Stamm der Freigabe sind, muss ONTAP das Cluster-Netzwerk verwenden, um die Daten in diesen nicht-lokalen Volumes abzurufen. Bei dieser Art von Namespace-Architektur bieten automatische Knotenverweise möglicherweise keine signifikanten Leistungsvorteile.

====


Verfügt der Knoten, auf dem die Daten gehostet werden, über keine verfügbare LIF, stellt ONTAP die Verbindung über die vom Client gewählte LIF her. Nachdem eine Datei von einem SMB-Client geöffnet wurde, erfolgt der Zugriff weiterhin über dieselbe verwiesene Verbindung.

Kann der CIFS-Server aus irgendeinem Grund keine Weiterleitung vornehmen, kommt es zu keiner Unterbrechung des SMB-Dienstes. Die SMB-Verbindung wird so hergestellt, als wären automatische Knoten-Weiterleitungen nicht aktiviert.

.Verwandte Informationen
xref:improve-microsoft-remote-copy-performance-concept.adoc[Verbesserung der Leistung von Microsoft Remote Copy]
