---
permalink: smb-admin/limits-configuring-unix-symbolic-links-concept.html 
sidebar: sidebar 
keywords: limit, configuring, configure, unix, symbolic, link, smb, access, limits when configuring unix symbolic links for smb access 
summary: Bei der Konfiguration von UNIX-Symbol-Links für den SMB-Zugriff sind bestimmte Einschränkungen zu beachten. 
---
= Einschränkungen bei der Konfiguration von UNIX-Symbol-Links für ONTAP SMB-Zugriff
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Konfiguration von UNIX-Symbol-Links für den SMB-Zugriff sind bestimmte Einschränkungen zu beachten.

|===
| Limit | Beschreibung 


 a| 
45
 a| 
Maximale Länge des CIFS-Servernamens, die bei Verwendung eines FQDN für den CIFS-Servernamen angegeben werden kann.

[NOTE]
====
Alternativ kann der CIFS-Servername auch als NetBIOS-Name angegeben werden, der auf 15 Zeichen beschränkt ist.

====


 a| 
80
 a| 
Maximale Länge des Freigabenamens.



 a| 
256
 a| 
Maximale Länge des UNIX-Pfads, die beim Erstellen eines Symbol-Links oder beim Ändern des UNIX-Pfads eines bestehenden Symbol-Links angegeben werden kann. Der UNIX-Pfad muss mit einem "`/`" (slash) and end with a "`/`" beginnen. Sowohl der erste als auch der letzte Schrägstrich zählen zur 256-Zeichen-Grenze.



 a| 
256
 a| 
Maximale Länge des CIFS-Pfads, die beim Erstellen eines Symbol-Links oder beim Ändern des CIFS-Pfads eines bestehenden Symbol-Links angegeben werden kann. Der CIFS-Pfad muss mit einem "`/`" (slash) and end with a "`/`" beginnen. Sowohl der erste als auch der letzte Schrägstrich zählen zur 256-Zeichen-Grenze.

|===
.Verwandte Informationen
xref:create-symbolic-link-mappings-task.adoc[Symbol-Link-Zuordnungen für Shares erstellen]
