---
permalink: smb-admin/manage-acls-dynamic-access-control-aces-task.html 
sidebar: sidebar 
keywords: resource, acl, applied, apply, dynamic, access, control, ace, disable, dynamic, storage, virtual, machine, svm, remove, non-dynamic, manage acls that contain dynamic access control aces when dynamic access control is disabled 
summary: 'Wenn Sie Ressourcen haben, bei denen ACLs mit Dynamic Access Control Aces angewendet werden, und Sie Dynamic Access Control auf der Storage Virtual Machine (SVM) deaktivieren, müssen Sie die Dynamic Access Control Aces entfernen, bevor Sie die nicht-dynamischen Zugriffssteuerungsmaßnahmen dieser Ressource verwalten können.' 
---
= Verwalten von ACLs mit DAC ACEs, wenn DAC auf ONTAP SMB-Servern deaktiviert ist
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie Ressourcen haben, bei denen ACLs mit Dynamic Access Control Aces angewendet werden, und Sie Dynamic Access Control auf der Storage Virtual Machine (SVM) deaktivieren, müssen Sie die Dynamic Access Control Aces entfernen, bevor Sie die nicht-dynamischen Zugriffssteuerungsmaßnahmen dieser Ressource verwalten können.

.Über diese Aufgabe
Nachdem die Dynamic Access Control deaktiviert ist, können Sie vorhandene nicht-dynamische Access Control Aces nicht entfernen oder neue nicht-dynamische Access Control Aces hinzufügen, bis Sie die vorhandenen Dynamic Access Control Aces entfernt haben.

Sie können das jeweils verwendete Tool zum Verwalten von ACLs verwenden, um diese Schritte durchzuführen.

.Schritte
. Legen Sie fest, welche Dynamic Access Control Aces auf die Ressource angewendet werden.
. Entfernen Sie die Dynamic Access Control Aces aus der Ressource.
. Hinzufügen oder Entfernen von nicht-dynamischen Zugriffssteuerungsaces wie gewünscht aus der Ressource.

