---
permalink: smb-admin/manage-security-policy-jobs-concept.html 
sidebar: sidebar 
keywords: security, policy, job, exist, circumstance, modify, security, task, assign, condition, modify, modification, add, remove, removing, delete, deleting, considerations when managing security policy jobs 
summary: Wenn ein Job für die Sicherheitsrichtlinien vorhanden ist, können Sie diese Sicherheitsrichtlinie oder die Aufgaben, die dieser Richtlinie zugewiesen sind, nicht ändern. Sie sollten unter welchen Bedingungen Sie die Sicherheitsrichtlinien ändern können oder können, damit alle Änderungsversuche erfolgreich sind. Änderungen an der Richtlinie umfassen das Hinzufügen, Entfernen oder Ändern von Aufgaben, die der Richtlinie zugewiesen sind, sowie das Löschen oder Ändern der Richtlinie. 
---
= Überlegungen bei der Verwaltung von Aufgaben mit Sicherheitsrichtlinien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ein Job für die Sicherheitsrichtlinien vorhanden ist, können Sie diese Sicherheitsrichtlinie oder die Aufgaben, die dieser Richtlinie zugewiesen sind, nicht ändern. Sie sollten unter welchen Bedingungen Sie die Sicherheitsrichtlinien ändern können oder können, damit alle Änderungsversuche erfolgreich sind. Änderungen an der Richtlinie umfassen das Hinzufügen, Entfernen oder Ändern von Aufgaben, die der Richtlinie zugewiesen sind, sowie das Löschen oder Ändern der Richtlinie.

Sie können eine Sicherheitsrichtlinie oder eine Aufgabe, die dieser Richtlinie zugewiesen ist, nicht ändern, wenn ein Job für diese Richtlinie existiert und sich dieser Job in den folgenden Status befindet:

* Der Job wird ausgeführt oder wird ausgeführt.
* Der Job wurde angehalten.
* Der Job wird wieder aufgenommen und befindet sich im laufenden Zustand.
* Wenn der Job auf ein Failover auf einen anderen Node wartet.


Wenn ein Job für eine Sicherheitsrichtlinie vorhanden ist, können Sie unter folgenden Umständen diese Sicherheitsrichtlinie oder eine dieser Richtlinie zugewiesene Aufgabe erfolgreich ändern:

* Der Richtlinienjob wird angehalten.
* Der Richtlinienjob wurde erfolgreich abgeschlossen.

