---
permalink: smb-admin/manage-ntfs-security-audit-policies-slag-concept.html 
sidebar: sidebar 
keywords: manage, ntfs, file, security, ntfs, audit, policies, policy, storage-level, access, guard, storage, virtual, machine, svm, cli, manage ntfs file security, ntfs audit policies, and storage-level access guard on svms using the cli 
summary: Sie können die NTFS-Dateisicherheit, NTFS-Überwachungsrichtlinien und Storage-Level Access Guard auf virtuellen Speichermaschinen mithilfe der CLI verwalten. 
---
= ONTAP Befehle zur Verwaltung der SMB NTFS-Dateisicherheit, NTFS-Audit-Richtlinien und des Storage-Level Access Guard
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die NTFS-Dateisicherheit, NTFS-Überwachungsrichtlinien und Storage-Level Access Guard auf Storage Virtual Machines (SVMs) lassen sich mithilfe der CLI verwalten.

Die NTFS-Dateisicherheit und Überwachungsrichtlinien können von SMB-Clients oder über die CLI verwaltet werden. Die Verwendung der CLI zur Konfiguration von Dateisicherheit und Überwachungsrichtlinien macht es jedoch unnötig, einen Remote-Client zur Verwaltung der Dateisicherheit zu nutzen. Die Nutzung der CLI kann die Zeit, die für das Anwenden von Sicherheitsmaßnahmen auf viele Dateien und Ordner mit einem einzigen Befehl benötigt wird, erheblich verkürzen.

Sie können Storage-Level Access Guard konfigurieren, eine zusätzliche Sicherheitsebene, die von ONTAP auf SVM-Volumes angewendet wird. Storage-Level Access Guard gilt für Zugriffe aller NAS-Protokolle auf das Speicherobjekt, auf das Storage-Level Access Guard angewendet wird.

Storage-Level Access Guard kann nur über die ONTAP-Befehlszeile konfiguriert und verwaltet werden. Einstellungen von Storage-Level Access Guard können nicht von SMB-Clients aus verwaltet werden. Zudem wird beim Anzeigen der Sicherheitseinstellungen einer Datei oder eines Verzeichnisses von einem NFS- oder SMB-Client die Storage-Level Access Guard-Sicherheit nicht angezeigt. Die Storage-Level Access Guard-Sicherheit kann von einem Client, selbst durch einen Systemadministrator (Windows oder UNIX), nicht aufgehoben werden. Storage-Level Access Guard bietet daher eine zusätzliche Sicherheitsebene für den Datenzugriff, die unabhängig vom Speicheradministrator festgelegt und verwaltet wird.


NOTE: Auch wenn für Storage-Level Access Guard nur NTFS-Zugriffsberechtigungen unterstützt werden, kann ONTAP Sicherheitsprüfungen für den Zugriff über NFS auf Daten auf Volumes durchführen, auf denen Storage-Level Access Guard angewendet wird, wenn der UNIX-Benutzer einem Windows-Benutzer auf der SVM zugeordnet ist, der das Volume besitzt.



[[ntfs-security-style-volumes]]
== NTFS Security-Style Volumes

Alle Dateien und Ordner in NTFS Security-Style-Volumes und Qtrees verfügen über effektive NTFS-Sicherheit. Die  `vserver security file-directory` Befehlsfamilie ermöglicht die Implementierung der folgenden Sicherheitsarten auf NTFS Security-Style-Volumes:

* Dateiberechtigungen und Überwachungsrichtlinien für Dateien und Ordner im Volume
* Storage-Level Access Guard-Sicherheit auf Volumes




[[mixed-security-style-volumes]]
== Volumes mit gemischtem Security-Style

Volumes und Qtrees mit gemischtem Security-Style können einige Dateien und Ordner enthalten, die über UNIX-effektive Sicherheit verfügen und UNIX-Dateiberechtigungen verwenden, entweder Modusbits oder NFSv4.x-ACLs und NFSv4.x-Überwachungsrichtlinien, sowie einige Dateien und Ordner, die über NTFS-effektive Sicherheit verfügen und NTFS-Dateiberechtigungen und Überwachungsrichtlinien verwenden. Mit der  `vserver security file-directory`Befehlsfamilie lassen sich die folgenden Sicherheitstypen auf Daten mit gemischtem Security-Style anwenden:

* Dateiberechtigungen und Überwachungsrichtlinien für Dateien und Ordner mit NTFS-Effektivsicherheitsstil im gemischten Volume oder qtree
* Storage-Level Access Guard für Volumes mit entweder NTFS- oder UNIX-effektivem Sicherheitsstil




[[unix-security-style-volumes]]
== UNIX Security-Style Volumes

UNIX Security-Style-Volumes und Qtrees enthalten Dateien und Ordner mit effektiver UNIX-Sicherheit (entweder Mode-Bits oder NFSv4.x-ACLs). Folgendes ist zu beachten, wenn die  `vserver security file-directory` Command-Family zur Implementierung von Sicherheit auf UNIX Security-Style-Volumes verwendet wird:

* Die  `vserver security file-directory`Befehlsfamilie kann nicht zur Verwaltung von UNIX-Dateisicherheits- und Überwachungsrichtlinien auf UNIX Security-Style Volumes und qtrees verwendet werden.
* Die  `vserver security file-directory`Befehlsfamilie kann zur Konfiguration von Storage-Level Access Guard auf UNIX-Sicherheitsvolumes verwendet werden, sofern die SVM mit dem Ziel-Volume einen CIFS-Server enthält.


.Verwandte Informationen
* xref:display-file-security-audit-policies-concept.adoc[Informationen zur Anzeige von Dateisicherheits- und Prüfrichtlinien]
* xref:create-ntfs-security-descriptor-file-task.adoc[NTFS-Sicherheitsdeskriptoren auf Servern erstellen]
* xref:configure-apply-audit-policies-ntfs-files-folders-task.adoc[Befehle zum Konfigurieren und Anwenden von Überwachungsrichtlinien auf Dateien und Ordner]
* xref:secure-file-access-storage-level-access-guard-concept.adoc[Informationen zum sicheren Dateizugriff mit Storage Level Access Guard]

