---
permalink: smb-admin/manage-netbios-aliases-concept.html 
sidebar: sidebar 
keywords: netbios, alternative, name, smb, client, configuring, configure, consolidate, consolidating, data, original, file, server, manage netbios aliases for smb servers 
summary: NetBIOS Aliase sind alternative Namen für Ihren SMB-Server, die SMB-Clients bei der Verbindung mit dem SMB-Server verwenden können. Das Konfigurieren von NetBIOS-Aliase für einen SMB-Server kann nützlich sein, wenn Sie Daten von anderen Dateiservern auf den SMB-Server konsolidieren und den SMB-Server auf die Namen der ursprünglichen Dateiserver antworten möchten. 
---
= NetBIOS Aliase für SMB-Server verwalten – Übersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetBIOS Aliase sind alternative Namen für Ihren SMB-Server, die SMB-Clients bei der Verbindung mit dem SMB-Server verwenden können. Das Konfigurieren von NetBIOS-Aliase für einen SMB-Server kann nützlich sein, wenn Sie Daten von anderen Dateiservern auf den SMB-Server konsolidieren und den SMB-Server auf die Namen der ursprünglichen Dateiserver antworten möchten.

Sie können eine Liste von NetBIOS-Aliase angeben, wenn Sie den SMB-Server erstellen oder nach dem Erstellen des SMB-Servers jederzeit. Sie können NetBIOS-Aliase jederzeit aus der Liste hinzufügen oder entfernen. Sie können eine Verbindung zum SMB-Server mit einem beliebigen Namen in der NetBIOS-Alialiste herstellen.

xref:display-netbios-over-tcp-connections-task.adoc[Anzeigen von Informationen über NetBIOS über TCP-Verbindungen]
