---
permalink: smb-admin/manage-local-groups.html 
sidebar: sidebar 
keywords: modify, exist, local, group, description, exist, local, group, renaming, rename, modify local groups 
summary: Sie können vorhandene lokale Gruppen ändern, indem Sie die Beschreibung für eine vorhandene lokale Gruppe ändern oder die Gruppe umbenennen. 
---
= Lokale ONTAP SMB-Gruppen verwalten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine lokale Gruppe ändern, indem Sie ihre Beschreibung aktualisieren oder sie umbenennen. Sie können auch alle lokalen Gruppen im Cluster oder auf einer bestimmten Storage Virtual Machine (SVM) anzeigen und sehen, wer zu welcher Gruppe gehört. Diese Informationen können Ihnen bei der Fehlerbehebung von Dateizugriffs- und Benutzerrechtenproblemen auf der SVM helfen.

[cols="2,4a"]
|===
| Ihr Ziel ist | Verwenden Sie den Befehl... 


 a| 
Alle lokalen Gruppen im Cluster anzeigen
 a| 
`vserver cifs users-and-groups local-group show`



 a| 
Alle lokalen Gruppen auf der SVM anzeigen
 a| 
`vserver cifs users-and-groups local-group show -vserver <SVM_name>`



 a| 
Mitglieder aller lokalen Gruppen im Cluster anzeigen
 a| 
`vserver cifs users-and-groups local-group show-members`



 a| 
Mitglieder aller lokalen Gruppen auf der SVM anzeigen
 a| 
`vserver cifs users-and-groups local-group show-members -vserver <SVM_name>`



 a| 
Ändern Sie die Beschreibung der lokalen Gruppe
 a| 
`vserver cifs users-and-groups local-group modify -vserver <SVM_name> -group-name <group_name> -description text`

Enthält die Beschreibung ein Leerzeichen, so muss sie in doppelte Anführungszeichen gesetzt werden.



 a| 
Benennen Sie die lokale Gruppe um
 a| 
`vserver cifs users-and-groups local-group rename -vserver <SVM_name> -group-name <group_name> -new-group-name <new_group_name>`

|===
.Befehlsbeispiele
[%collapsible]
====
.Beispiele
Im folgenden Beispiel wird die lokale Gruppe „`CIFS_SERVER\Engineering`“ in „`CIFS_SERVER\Engineering_New`“ umbenannt:

[listing]
----
cluster1::> vserver cifs users-and-groups local-group rename -vserver vs1 -group-name CIFS_SERVER\engineering -new-group-name CIFS_SERVER\engineering_new
----
Im folgenden Beispiel wird die Beschreibung der lokalen Gruppe „`CIFS_SERVER\Engineering`“ geändert:

[listing]
----
cluster1::> vserver cifs users-and-groups local-group modify -vserver vs1 -group-name CIFS_SERVER\engineering -description "New Description"
----
.Beispiel
Das folgende Beispiel zeigt Informationen zu allen lokalen Gruppen auf SVM vs1:

[listing]
----
cluster1::> vserver cifs users-and-groups local-group show -vserver vs1
Vserver  Group Name                  Description
-------- --------------------------- ----------------------------
vs1      BUILTIN\Administrators      Built-in Administrators group
vs1      BUILTIN\Backup Operators    Backup Operators group
vs1      BUILTIN\Power Users         Restricted administrative privileges
vs1      BUILTIN\Users               All users
vs1      CIFS_SERVER\engineering
vs1      CIFS_SERVER\sales
----
.Beispiel
Im folgenden Beispiel werden Informationen über Mitglieder aller lokalen Gruppen auf SVM vs1 angezeigt:

[listing]
----
cluster1::> vserver cifs users-and-groups local-group show-members -vserver vs1
Vserver   Group Name                   Members
--------- ---------------------------- ------------------------
vs1       BUILTIN\Administrators       CIFS_SERVER\Administrator
                                       AD_DOMAIN\Domain Admins
                                       AD_DOMAIN\dom_grp1
          BUILTIN\Users                AD_DOMAIN\Domain Users
                                       AD_DOMAIN\dom_usr1
          CIFS_SERVER\engineering      CIFS_SERVER\james
----
====


== Löschen Sie lokale ONTAP SMB-Gruppen

Sie können eine lokale Gruppe von der Storage Virtual Machine (SVM) löschen, wenn sie nicht mehr zum ermitteln der Zugriffsrechte für Daten benötigt wird, die dieser SVM zugeordnet sind, oder wenn sie nicht mehr zum Zuweisen von SVM-Benutzerrechten (Berechtigungen) zu Gruppenmitgliedern benötigt wird.

.Über diese Aufgabe
Beachten Sie beim Löschen von lokalen Gruppen Folgendes:

* Das Dateisystem wird nicht verändert.
+
Windows-Sicherheitsdeskriptoren für Dateien und Verzeichnisse, die sich auf diese Gruppe beziehen, werden nicht angepasst.

* Wenn die Gruppe nicht vorhanden ist, wird ein Fehler zurückgegeben.
* Die spezielle _Everyone_-Gruppe kann nicht gelöscht werden.
* Integrierte Gruppen wie _BUILTIN\Administrators_ _BUILTIN\Users_ können nicht gelöscht werden.


.Schritte
. Ermitteln Sie den Namen der lokalen Gruppe, die Sie löschen möchten, indem Sie die Liste der lokalen Gruppen auf dem SVM anzeigen:
+
[source, cli]
----
vserver cifs users-and-groups local-group show -vserver <SVM_name>
----
. Lokale Gruppe löschen:
+
[source, cli]
----
vserver cifs users-and-groups local-group delete -vserver <SVM_name> -group-name <group_name>
----
. Überprüfen Sie, ob die Gruppe gelöscht wurde:
+
[source, cli]
----
vserver cifs users-and-groups local-group show -vserver <SVM_name>
----


.Befehlsbeispiel
[%collapsible]
====
Im folgenden Beispiel wird die lokale Gruppe „`CIFS_SERVER\Sales`“ gelöscht, die mit SVM vs1 verknüpft ist:

[listing]
----
cluster1::> vserver cifs users-and-groups local-group show -vserver vs1
Vserver   Group Name                   Description
--------- ---------------------------- ----------------------------
vs1       BUILTIN\Administrators       Built-in Administrators group
vs1       BUILTIN\Backup Operators     Backup Operators group
vs1       BUILTIN\Power Users          Restricted administrative privileges
vs1       BUILTIN\Users                All users
vs1       CIFS_SERVER\engineering
vs1       CIFS_SERVER\sales

cluster1::> vserver cifs users-and-groups local-group delete -vserver vs1 -group-name CIFS_SERVER\sales

cluster1::> vserver cifs users-and-groups local-group show -vserver vs1
Vserver   Group Name                   Description
--------- ---------------------------- ----------------------------
vs1       BUILTIN\Administrators       Built-in Administrators group
vs1       BUILTIN\Backup Operators     Backup Operators group
vs1       BUILTIN\Power Users          Restricted administrative privileges
vs1       BUILTIN\Users                All users
vs1       CIFS_SERVER\engineering
----
====


== Fügen Sie ein Mitglied zu einer lokalen ONTAP SMB-Gruppe hinzu

Sie können die Mitgliedschaft in lokalen Gruppen verwalten, indem Sie lokale Benutzer, Domänenbenutzer oder Domänengruppen hinzufügen. Dies ist nützlich, wenn Sie den Zugriff auf Daten basierend auf den für die Gruppe festgelegten Zugriffskontrollen steuern oder wenn Sie möchten, dass Benutzer die mit dieser Gruppe verbundenen Berechtigungen erhalten.

.Über diese Aufgabe
* Sie können keine Benutzer zur speziellen _everyone_-Gruppe hinzufügen.
* Die lokale Gruppe muss vorhanden sein, bevor Sie einen Benutzer hinzufügen können.
* Der Benutzer muss vorhanden sein, bevor Sie den Benutzer einer lokalen Gruppe hinzufügen können.
* Sie können einer anderen lokalen Gruppe keine lokale Gruppe hinzufügen.
* Um einen Domänenbenutzer oder eine Gruppe zu einer lokalen Gruppe hinzuzufügen, muss Data ONTAP in der Lage sein, den Namen zu einem SID aufzulösen.


.Schritt
. Füge ein Mitglied zu einer Gruppe hinzu:
+
[source, cli]
----
vserver cifs users-and-groups local-group add-members -vserver _vserver_name_ -group-name _group_name_ -member-names name[,...]
----


Sie können eine kommagetrennte Liste von lokalen Benutzern, Domänenbenutzern oder Domänengruppen angeben, die der angegebenen lokalen Gruppe hinzugefügt werden sollen.

.Befehlsbeispiel
[%collapsible]
====
Im folgenden Beispiel wird der lokalen Gruppe „`SMB_SERVER\sue`“ und der lokalen Gruppe „`AD_DOM\dom_eng`“ auf SVM vs1 ein lokaler Benutzer „`SMB_SERVER\Engineering`“ hinzugefügt:

[listing]
----
cluster1::> vserver cifs users-and-groups local-group add-members -vserver vs1 -group-name SMB_SERVER\engineering -member-names SMB_SERVER\sue,AD_DOMAIN\dom_eng
----
====


== Ein Mitglied aus einer lokalen ONTAP SMB-Gruppe entfernen

Sie können die Mitgliedschaft in lokalen Gruppen verwalten, indem Sie lokale Benutzer, Domänenbenutzer oder Domänengruppen entfernen. Dies ist hilfreich, wenn Sie den Zugriff auf Daten basierend auf den für die Gruppe festgelegten Zugriffskontrollen steuern oder wenn Sie möchten, dass Benutzer die mit dieser Gruppe verbundenen Berechtigungen erhalten.

.Über diese Aufgabe
* Sie können keine Mitglieder aus der speziellen _everyone_-Gruppe entfernen.
* Die Gruppe, aus der Sie ein Mitglied entfernen möchten, muss vorhanden sein.
* ONTAP muss in der Lage sein, die Namen der Mitglieder zu lösen, die Sie aus der Gruppe zu einem entsprechenden SID entfernen möchten.


.Schritt
. Ein Mitglied aus einer Gruppe entfernen:
+
[source, cli]
----
vserver cifs users-and-groups local-group remove-members -vserver _vserver_name_ -group-name _group_name_ -member-names name[,...]
----


Sie können eine durch Komma getrennte Liste der lokalen Benutzer, Domänenbenutzer oder Domänengruppen angeben, die aus der angegebenen lokalen Gruppe entfernt werden sollen.

.Befehlsbeispiel
[%collapsible]
====
Im folgenden Beispiel werden die lokalen Benutzer „`SMB_SERVER\sue`“ und „`SMB_SERVER\james`“ aus der lokalen Gruppe „`SMB_SERVER\Engineering`“ auf SVM vs1 entfernt:

[listing]
----
cluster1::> vserver cifs users-and-groups local-group remove-members -vserver vs1 -group-name SMB_SERVER\engineering -member-names SMB_SERVER\sue,SMB_SERVER\james
----
====


== Aktualisieren Sie ONTAP SMB-Domänenbenutzer- und -Gruppennamen in lokalen Datenbanken

Sie können den lokalen Gruppen eines CIFS-Servers Domänenbenutzer und -Gruppen hinzufügen. Diese Domänenobjekte sind in lokalen Datenbanken auf dem Cluster registriert. Wenn ein Domänenobjekt umbenannt wird, müssen die lokalen Datenbanken manuell aktualisiert werden.

.Über diese Aufgabe
Sie müssen den Namen der Storage Virtual Machine (SVM) angeben, auf der Sie Domänennamen aktualisieren möchten.

.Schritte
. Legen Sie die Berechtigungsebene auf erweitert fest:
+
[source, cli]
----
set -privilege advanced
----
. Aktualisieren Sie die Namen der Domänenbenutzer und -gruppen, die der Storage Virtual Machine zugeordnet sind:
+
[source, cli]
----
vserver cifs users-and-groups update-names -vserver <SVM_name>
----
. Anzeige der Domänenbenutzer und -gruppen, deren Aktualisierung erfolgreich war und deren Aktualisierung fehlgeschlagen ist:
+
[source, cli]
----
vserver cifs users-and-groups update-names -vserver <SVM_name> -display-failed-only false|true
----
. Um alle Statusinformationen zu Aktualisierungen zu unterdrücken, verwenden Sie folgenden Befehl:
+
[source, cli]
----
vserver cifs users-and-groups update-names -vserver <SVM_name> -suppress-all-output true
----
. Zurück zur Administratorberechtigungsebene:
+
[source, cli]
----
set -privilege admin
----


.Befehlsbeispiel
[%collapsible]
====
Im folgenden Beispiel werden die Namen der Domänenbenutzer und Gruppen aktualisiert, die mit der Storage Virtual Machine (SVM, ehemals Vserver genannt) vs1 verknüpft sind. Für das letzte Update gibt es eine abhängige Kette von Namen, die aktualisiert werden müssen:

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs users-and-groups update-names -vserver vs1

   Vserver:           vs1
   SID:               S-1-5-21-123456789-234565432-987654321-12345
   Domain:            EXAMPLE1
   Out-of-date Name:  dom_user1
   Updated Name:      dom_user2
   Status:            Successfully updated

   Vserver:           vs1
   SID:               S-1-5-21-123456789-234565432-987654322-23456
   Domain:            EXAMPLE2
   Out-of-date Name:  dom_user1
   Updated Name:      dom_user2
   Status:            Successfully updated

   Vserver:           vs1
   SID:               S-1-5-21-123456789-234565432-987654321-123456
   Domain:            EXAMPLE1
   Out-of-date Name:  dom_user3
   Updated Name:      dom_user4
   Status:            Successfully updated; also updated SID "S-1-5-21-123456789-234565432-987654321-123457"
                      to name "dom_user5"; also updated SID "S-1-5-21-123456789-234565432-987654321-123458"
                      to name "dom_user6"; also updated SID "S-1-5-21-123456789-234565432-987654321-123459"
                      to name "dom_user7"; also updated SID "S-1-5-21-123456789-234565432-987654321-123460"
                      to name "dom_user8"

The command completed successfully. 7 Active Directory objects have been updated.

cluster1::*> set -privilege admin
----
====
.Verwandte Informationen
Erfahren Sie mehr über `vserver cifs` in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs["ONTAP-Befehlsreferenz"^].
