---
permalink: smb-admin/manage-ntfs-security-audit-policies-slag-concept.html 
sidebar: sidebar 
keywords: manage, ntfs, file, security, ntfs, audit, policies, policy, storage-level, access, guard, storage, virtual, machine, svm, cli, manage ntfs file security, ntfs audit policies, and storage-level access guard on svms using the cli 
summary: 'Sie können die NTFS-Dateisicherheit, NTFS-Audit-Richtlinien und Storage-Level Access Guard auf Storage Virtual Machines (SVMs) über die Befehlszeilenschnittstelle managen.' 
---
= Managen Sie mithilfe der CLI-Übersicht NTFS-Dateisicherheit, NTFS-Audit-Richtlinien und Storage-Level Access Guard auf SVMs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die NTFS-Dateisicherheit, NTFS-Audit-Richtlinien und Storage-Level Access Guard auf Storage Virtual Machines (SVMs) über die Befehlszeilenschnittstelle managen.

Die NTFS-Dateisicherheitsrichtlinien und Audit-Richtlinien können von SMB-Clients oder über die CLI gemanagt werden. Die Verwendung der CLI zur Konfiguration von Dateisicherheitsrichtlinien und Audit-Richtlinien erfordert jedoch keinen Remote-Client zum Verwalten der Dateisicherheit. Die Verwendung der CLI kann den Zeitaufwand für das Anwenden der Sicherheit auf viele Dateien und Ordner mit einem einzigen Befehl erheblich reduzieren.

Sie können den Storage-Level Access Guard konfigurieren. Dies ist eine weitere Sicherheitsschicht, die von ONTAP auf SVM Volumes angewendet wird. Storage-Level Access Guard gilt für Zugriffe aller NAS-Protokolle auf das Storage-Objekt, auf das Storage-Level Access Guard angewendet wird.

Der Storage-Level Access Guard kann nur über die ONTAP-CLI konfiguriert und gemanagt werden. Sie können Storage-Level Access Guard-Einstellungen von SMB-Clients nicht verwalten. Wenn Sie darüber hinaus die Sicherheitseinstellungen einer Datei oder eines Verzeichnisses von einem NFS- oder SMB-Client aus anzeigen, wird die Sicherheit des Storage-Level Access Guard nicht angezeigt. Die Sicherheit des Access Guard auf Storage-Ebene kann nicht von einem Client entzogen werden, selbst wenn ein System-Administrator (Windows oder UNIX) dies durchführt. Daher bietet Storage-Level Access Guard eine zusätzliche Sicherheitsschicht für den Datenzugriff, die vom Storage-Administrator unabhängig festgelegt und gemanagt wird.


NOTE: Obwohl nur NTFS-Zugriffsberechtigungen für Storage-Level Access Guard unterstützt werden, kann ONTAP Sicherheitsprüfungen für den Zugriff über NFS auf Daten auf Volumes durchführen, auf denen Storage-Level Access Guard angewendet wird, wenn der UNIX-Benutzer einem Windows-Benutzer auf der SVM, der das Volume besitzt, zuordnet.



== NTFS Security-Volumes

Alle Dateien und Ordner in NTFS-SicherheitsVolumes und qtrees haben NTFS-basierte Sicherheitsoptionen. Sie können das verwenden `vserver security file-directory` Befehlsfamilie, um die folgenden Sicherheitstypen auf NTFS Security-Volumes zu implementieren:

* Dateiberechtigungen und Audit-Richtlinien für Dateien und Ordner im Volume
* Sicherheit des Storage-Level Access Guard auf Volumes




== Unterschiedliche Volumes im Sicherheitsstil

Volumes und qtrees im gemischten Sicherheitsstil können einige Dateien und Ordner enthalten, die für UNIX effektive Sicherheit haben und UNIX-Dateiberechtigungen verwenden, entweder Mode-Bits oder NFSv4.x-ACLs und NFSv4.x-Audit-Richtlinien sowie einige Dateien und Ordner, die NTFS-effektive Sicherheit haben und NTFS-Dateiberechtigungen sowie Audit-Richtlinien verwenden. Sie können das verwenden `vserver security file-directory` Befehlsfamilie, um die folgenden Sicherheitsarten auf Daten im gemischten Sicherheitsstil anzuwenden:

* Dateiberechtigungen und Audit-Richtlinien für Dateien und Ordner mit NTFS effizientem Sicherheitsstil im gemischten Volume oder qtree
* Storage-Level Access Guard für Volumes mit NTFS und UNIX effektivem Sicherheitsstil




== UNIX Volumes im Sicherheitsstil

UNIX Security-Volumes und qtrees enthalten Dateien und Ordner, die über effektive UNIX-Sicherheit verfügen (entweder Mode-Bits oder NFSv4.x ACLs). Wenn Sie den verwenden möchten, müssen Sie Folgendes beachten `vserver security file-directory` Befehlfamilie zur Implementierung der Sicherheit auf UNIX-Volumes im Sicherheitsstil:

* Der `vserver security file-directory` Mit der Befehlszeile kann nicht die UNIX-Dateisicherheitsrichtlinien und Audit-Richtlinien für UNIX-Volumes und -qtrees verwaltet werden.
* Sie können das verwenden `vserver security file-directory` Produktfamilie zur Konfiguration der Storage-Level Access Guard auf UNIX Volumes im Sicherheitsstil, vorausgesetzt, die SVM mit dem Ziel-Volume enthält einen CIFS-Server.


xref:display-file-security-audit-policies-concept.adoc[Zeigt Informationen zur Dateisicherheit und zu den Audit-Richtlinien an]

xref:create-ntfs-security-descriptor-file-task.adoc[Konfigurieren und Anwenden der Dateisicherheit auf NTFS-Dateien und Ordnern mithilfe der CLI]

xref:configure-apply-audit-policies-ntfs-files-folders-task.adoc[Konfigurieren und Anwenden von Audit-Richtlinien auf NTFS-Dateien und -Ordner mithilfe der CLI]

xref:secure-file-access-storage-level-access-guard-concept.adoc[Sicherer Dateizugriff über Storage-Level Access Guard]
