---
permalink: smb-admin/modify-server-kerberos-security-settings-task.html 
sidebar: sidebar 
keywords: modify, cifs, server, kerberos, security, setting, clock, skew, time, ticket, lifetime, renewal, modify the cifs server kerberos security ticket settings 
summary: Sie können bestimmte Kerberos-Sicherheitseinstellungen des CIFS-Servers ändern, einschließlich der maximal zulässigen Skew-Zeit für Kerberos-Uhren, der Lebensdauer des Kerberos-Tickets und der maximalen Anzahl an Tagen für die Ticketverlängerung. 
---
= Ändern Sie die Kerberos-Sicherheitseinstellungen des CIFS-Servers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können bestimmte Kerberos-Sicherheitseinstellungen des CIFS-Servers ändern, einschließlich der maximal zulässigen Skew-Zeit für Kerberos-Uhren, der Lebensdauer des Kerberos-Tickets und der maximalen Anzahl an Tagen für die Ticketverlängerung.

.Über diese Aufgabe
Ändern der Kerberos-Einstellungen des CIFS-Servers mit `vserver cifs security modify` Befehl ändert die Einstellungen nur auf der einzelnen Storage Virtual Machine (SVM), die Sie mit angeben `-vserver` Parameter. Kerberos-Sicherheitseinstellungen für alle SVMs im Cluster, die zur selben Active Directory-Domäne gehören, lassen sich mithilfe von Gruppenrichtlinienobjekten (Active Directory Group Policy Objects, GPOs) zentral managen.

.Schritte
. Führen Sie eine oder mehrere der folgenden Aktionen aus:
+
|===


| Ihr Ziel ist | Eingeben... 


 a| 
Geben Sie die maximal zulässige Kerberos-Uhr-Spiezeit in Minuten an.
 a| 
`vserver cifs security modify -vserver _vserver_name_ -kerberos-clock-skew _integer_in_minutes_`

Die Standardeinstellung ist 5 Minuten.



 a| 
Geben Sie die Lebensdauer des Kerberos-Tickets in Stunden an.
 a| 
`vserver cifs security modify -vserver _vserver_name_ -kerberos-ticket-age integer_in_hours`

Die Standardeinstellung ist 10 Stunden.



 a| 
Geben Sie die maximale Anzahl an Tagen für die Ticketverlängerung an.
 a| 
`vserver cifs security modify -vserver _vserver_name_ -kerberos-renew-age _integer_in_days_`

Die Standardeinstellung ist 7 Tage.



 a| 
Geben Sie die Zeitüberschreitung für Sockets auf KDCs an, nach der alle KDCs als nicht erreichbar markiert sind.
 a| 
`vserver cifs security modify -vserver _vserver_name_ -kerberos-kdc-timeout _integer_in_seconds_`

Die Standardeinstellung ist 3 Sekunden.

|===
. Überprüfen Sie die Kerberos-Sicherheitseinstellungen:
+
`vserver cifs security show -vserver _vserver_name_`



.Beispiel
Im folgenden Beispiel werden die folgenden Änderungen an der Kerberos-Sicherheit vorgenommen: „`Kerberos Clock Skew`“ ist auf 3 Minuten eingestellt und „`Kerberos Ticket Age`“ ist für SVM vs1 auf 8 Stunden eingestellt:

[listing]
----
cluster1::> vserver cifs security modify -vserver vs1 -kerberos-clock-skew 3 -kerberos-ticket-age 8

cluster1::> vserver cifs security show -vserver vs1

Vserver: vs1

                    Kerberos Clock Skew:                   3 minutes
                    Kerberos Ticket Age:                   8 hours
                   Kerberos Renewal Age:                   7 days
                   Kerberos KDC Timeout:                   3 seconds
                    Is Signing Required:               false
        Is Password Complexity Required:                true
   Use start_tls For AD LDAP connection:               false
              Is AES Encryption Enabled:               false
                 LM Compatibility Level:  lm-ntlm-ntlmv2-krb
             Is SMB Encryption Required:               false
----
.Verwandte Informationen
link:display-server-security-settings-task.html["Anzeigen von Informationen zu den Sicherheitseinstellungen des CIFS-Servers"]

link:supported-gpos-concept.html["Unterstützte Gruppenrichtlinienobjekte"]

link:applying-group-policy-objects-concept.html["Werden Gruppenrichtlinienobjekte auf CIFS-Server angewendet"]
