---
permalink: smb-admin/modify-branchcache-config-task.html 
sidebar: sidebar 
keywords: modify, configuration, branchcache, service, svm, store, directory, path, hash, maximum, size, operating, mode, version, modify branchcache configurations 
summary: Sie können die Konfiguration des BranchCache-Service auf SVMs ändern, einschließlich des Hash-Speicherverzeichnispfads, der maximalen Verzeichnisgröße des Hash-Speichers, des Betriebsmodus und der unterstützten BranchCache-Versionen. Sie können auch die Größe des Volumens erhöhen, das den Hash-Speicher enthält. 
---
= Ändern Sie BranchCache-Konfigurationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Konfiguration des BranchCache-Service auf SVMs ändern, einschließlich des Hash-Speicherverzeichnispfads, der maximalen Verzeichnisgröße des Hash-Speichers, des Betriebsmodus und der unterstützten BranchCache-Versionen. Sie können auch die Größe des Volumens erhöhen, das den Hash-Speicher enthält.

.Schritte
. Führen Sie die entsprechende Aktion aus:
+
|===
| Ihr Ziel ist | Geben Sie Folgendes ein... 


 a| 
Ändern Sie die Verzeichnisgröße des Hash-Speichers
 a| 
`vserver cifs branchcache modify -vserver vserver_name -hash-store-max-size {integer[KB|MB|GB|TB|PB]}`



 a| 
Erhöhen Sie die Größe des Volumens, das den Hash-Speicher enthält
 a| 
`volume size -vserver vserver_name -volume volume_name -new-size new_size[k|m|g|t]` Wenn sich das Volume mit dem Hash-Speicher füllt, können Sie die Volume-Größe möglicherweise erhöhen. Sie können die neue Volume-Größe als Zahl festlegen, gefolgt von einer Einheitenbezeichnung.

Siehe link:../volumes/index.html["Logisches Storage-Management"] Weitere Informationen über die Vergrößerung von Volumes.



 a| 
Ändern Sie den Verzeichnispfad für den Hash-Speicher
 a| 
`vserver cifs branchcache modify -vserver vserver_name -hash-store-path path -flush-hashes {true|false}` Wenn die SVM eine SVM Disaster-Recovery-Quelle ist, kann sich der Hash-Pfad nicht auf dem Root-Volume befinden. Das liegt daran, dass das Root-Volume nicht zum Disaster-Recovery-Ziel repliziert wird.

Der Hash-Pfad für BranchCache kann Leerzeichen und gültige Dateinamenzeichen enthalten.

Wenn Sie den Hash-Pfad ändern, `-flush-hashes` Ist ein erforderlicher Parameter, der angibt, ob ONTAP die Hash-Werte vom ursprünglichen Hash-Speicherort spülen soll. Sie können die folgenden Werte für das festlegen `-flush-hashes` Parameter:

** Wenn Sie angeben `true`, ONTAP löscht die Hash-Werte am ursprünglichen Standort und erstellt neue Hash-Werte am neuen Standort, sobald neue Anfragen von den branchCache-fähigen Clients gestellt werden.
** Wenn Sie angeben `false`, Die Hashes werden nicht gespült.
+
In diesem Fall können Sie die bestehenden Hashes später wieder verwenden, indem Sie den Hash-Speicherpfad zurück zur ursprünglichen Position ändern.





 a| 
Den Betriebsmodus ändern
 a| 
`vserver cifs branchcache modify -vserver vserver_name -operating-mode {per-share|all-shares|disable}`

[NOTE]
====
Beim Ändern des Betriebsmodus sollten Sie Folgendes beachten: - ONTAP wirbt für BranchCache-Unterstützung für eine Freigabe, wenn die SMB-Sitzung eingerichtet wird. - Clients, die bereits Sitzungen eingerichtet haben, wenn BranchCache aktiviert ist, müssen die Verbindung trennen und erneut herstellen, um den zwischengespeicherten Inhalt für diese Freigabe zu verwenden.

====


 a| 
Ändern Sie die Unterstützung der BranchCache-Version
 a| 
`vserver cifs branchcache modify -vserver vserver_name -versions {v1-enable|v2-enable|enable-all}`

|===
. Überprüfen Sie die Konfigurationsänderungen mit der `vserver cifs branchcache show` Befehl.


.Verwandte Informationen
link:../volumes/index.html["Logischer Storage-Management-Leitfaden"]
