---
permalink: smb-admin/monitor-oplock-status-task.html 
sidebar: sidebar 
keywords: monitor, display, information, oplock, status, file, state, leasing, lease, determine, manual, monitor oplock status 
summary: Informationen zum Oplock-Status können überwacht und angezeigt werden. Diese Informationen ermöglichen die Feststellung, welche Dateien Oplocks haben, welches Oplock-Level und welcher Oplock-Status vorliegen und ob Oplock-Leasing verwendet wird. Es lässt sich außerdem ermitteln, welche Informationen zu Sperren vorliegen, die möglicherweise manuell aufgehoben werden müssen. 
---
= ONTAP SMB Oplock-Status überwachen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Informationen zum Oplock-Status können überwacht und angezeigt werden. Diese Informationen ermöglichen die Feststellung, welche Dateien Oplocks haben, welches Oplock-Level und welcher Oplock-Status vorliegen und ob Oplock-Leasing verwendet wird. Es lässt sich außerdem ermitteln, welche Informationen zu Sperren vorliegen, die möglicherweise manuell aufgehoben werden müssen.

.Über diese Aufgabe
Informationen zu allen Oplocks können in zusammengefasster oder detaillierter Listenform angezeigt werden. Optionale Parameter ermöglichen die Anzeige von Informationen zu einer kleineren Teilmenge der vorhandenen Sperren. So kann beispielsweise festgelegt werden, dass nur Sperren mit der angegebenen Client-IP-Adresse oder dem angegebenen Pfad ausgegeben werden.

Folgende Informationen über traditionelle und Lease-Oplocks können angezeigt werden:

* SVM, Knoten, Volume und LIF, auf denen der Oplock besteht
* Lock-UUID
* IP-Adresse des Clients mit dem Oplock
* Pfad, auf dem der Oplock etabliert wird
* Sperrprotokoll (SMB) und Typ (oplock)
* Sperrzustand
* Oplock-Ebene
* Verbindungsstatus und SMB-Ablaufzeit
* Open Group ID, wenn ein Lease Oplock gewährt wird


Weitere Informationen zu  `vserver oplocks show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+oplocks+show["ONTAP-Befehlsreferenz"^].

.Schritte
. Der Oplock-Status wird mit dem  `vserver locks show` Befehl angezeigt.


.Beispiele
Der folgende Befehl zeigt Standardinformationen zu allen Sperren an. Die Oplock-Sperre für die angezeigte Datei ist mit einer  `read-batch` Oplock-Ebene vergeben:

[listing]
----
cluster1::> vserver locks show

Vserver: vs0
Volume   Object Path        LIF         Protocol  Lock Type   Client
-------- ------------------ ----------- --------- ----------- ----------
vol1     /vol1/notes.txt    node1_data1
                                        cifs      share-level 192.168.1.5
         Sharelock Mode: read_write-deny_delete
                                                  op-lock     192.168.1.5
         Oplock Level: read-batch
----
Das folgende Beispiel zeigt detailliertere Informationen zur Sperre einer Datei mit dem Pfad `/data2/data2_2/intro.pptx`. Eine Lease Oplock wird für die Datei mit einem `batch` Oplock-Level an einen Client mit der IP-Adresse `10.3.1.3` gewährt:

[NOTE]
====
Bei der Anzeige detaillierter Informationen liefert der Befehl separate Ausgaben für Oplock- und Sharelock-Informationen. Dieses Beispiel zeigt nur die Ausgabe des Oplock-Abschnitts.

====
[listing]
----
cluster1::> vserver lock show -instance -path /data2/data2_2/intro.pptx

                   Vserver: vs1
                    Volume: data2_2
         Logical Interface: lif2
               Object Path: /data2/data2_2/intro.pptx
                 Lock UUID: ff1cbf29-bfef-4d91-ae06-062bf69212c3
             Lock Protocol: cifs
                 Lock Type: op-lock
   Node Holding Lock State: node3
                Lock State: granted
  Bytelock Starting Offset: -
    Number of Bytes Locked: -
     Bytelock is Mandatory: -
     Bytelock is Exclusive: -
     Bytelock is Superlock: -
          Bytelock is Soft: -
              Oplock Level: batch
   Shared Lock Access Mode: -
       Shared Lock is Soft: -
           Delegation Type: -
            Client Address: 10.3.1.3
             SMB Open Type: -
         SMB Connect State: connected
SMB Expiration Time (Secs): -
         SMB Open Group ID: 78a90c59d45ae211998100059a3c7a00a007f70da0f8ffffcd445b0300000000
----
.Verwandte Informationen
xref:enable-disable-oplocks-when-creating-shares-task.adoc[Oplocks beim Erstellen von SMB-Freigaben aktivieren oder deaktivieren]

xref:enable-disable-oplocks-existing-shares-task.adoc[Oplocks auf bestehenden SMB-Freigaben aktivieren oder deaktivieren]

xref:commands-oplocks-volumes-qtrees-reference.adoc[Befehle zum Aktivieren oder Deaktivieren von Oplocks auf SMB-Volumes und Qtrees]
