---
permalink: smb-admin/move-servers-different-ous-task.html 
sidebar: sidebar 
keywords: cifs, server, create-process, default, organizational, unit, ou, cn, computer, move cifs servers to different ous 
summary: 'Beim Erstellen des CIFS-Servers wird während der Einrichtung die Standard-Organisationseinheit (OU) CN=Computers verwendet, es sei denn, Sie geben eine andere Organisationseinheit an. Nach dem Setup können Sie CIFS-Server in verschiedene Organisationseinheiten verschieben.' 
---
= Verschieben Sie CIFS-Server in andere Organisationseinheiten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Beim Erstellen des CIFS-Servers wird während der Einrichtung die Standard-Organisationseinheit (OU) CN=Computers verwendet, es sei denn, Sie geben eine andere Organisationseinheit an. Nach dem Setup können Sie CIFS-Server in verschiedene Organisationseinheiten verschieben.

.Schritte
. Öffnen Sie auf dem Windows-Server die Struktur *Active Directory-Benutzer und -Computer*.
. Suchen Sie das Active Directory-Objekt für die Storage Virtual Machine (SVM).
. Klicken Sie mit der rechten Maustaste auf das Objekt und wählen Sie *Verschieben* aus.
. Wählen Sie die Organisationseinheit aus, die Sie der SVM zuordnen möchten


Das SVM-Objekt wird in der ausgewählten Organisationseinheit platziert.
