---
permalink: smb-admin/multi-byte-file-directory-qtree-names-concept.html 
sidebar: sidebar 
keywords: ontap, suppot, byte, utf, encode, name, enable, creation, display, file, directory, tree, unicode, supplement, character, multilingual, plane, bmp, release, display, environment, how ontap handles multi-byte file, qtree 
summary: Ab ONTAP 9.5 ermöglicht die Unterstützung von 4-Byte-UTF-8-kodierten Namen die Erstellung und Anzeige von Datei-, Verzeichnis- und Baumnamen, die Unicode-Zusatzzeichen außerhalb der Basic Multilingual Plane enthalten. In früheren Versionen wurden diese Zusatzzeichen in Multiprotokollumgebungen nicht korrekt angezeigt. 
---
= Informationen zu ONTAP SMB Multibyte-Datei-, Verzeichnis- und Qtree-Namen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.5 ermöglicht die Unterstützung von 4-Byte-UTF-8-kodierten Namen die Erstellung und Anzeige von Datei-, Verzeichnis- und Baumnamen, die Unicode-Zusatzzeichen außerhalb der Basic Multilingual Plane (BMP) enthalten. In früheren Versionen wurden diese Zusatzzeichen in Multiprotokollumgebungen nicht korrekt angezeigt.

Um die Unterstützung für 4-Byte-UTF-8-kodierte Namen zu ermöglichen, steht für die  `vserver` und  `volume` Befehlsfamilien ein neuer Sprachcode _utf8mb4_ zur Verfügung.

Sie müssen ein neues Volume auf eine der folgenden Arten erstellen:

* Die Option für das Volume `-language` explizit festlegen: `volume create -language utf8mb4 {…}`
* Übernahme der  `-language` Volumenoption von einer SVM, die mit dieser Option erstellt oder für diese Option geändert wurde: `vserver [create|modify] -language utf8mb4 {…}``volume create {…}`
* In ONTAP 9.6 und früheren Versionen können bestehende Volumes nicht für die Unterstützung von utf8mb4 geändert werden; es ist erforderlich, ein neues utf8mb4-fähiges Volume zu erstellen und die Daten anschließend mithilfe clientbasierter Kopierwerkzeuge zu migrieren.
+
SVMs können für die Unterstützung von utf8mb4 aktualisiert werden, bestehende Volumes behalten jedoch ihre ursprünglichen Sprachcodes.

+
Wenn Sie ONTAP 9.7P1 oder höher verwenden, können bestehende Volumes für utf8mb4 mit einer Supportanfrage modifiziert werden. Weitere Informationen finden sich unter link:https://kb.netapp.com/onprem/ontap/da/NAS/Can_the_volume_language_be_changed_after_creation_in_ONTAP["Kann die Volume-Sprache nach der Erstellung in ONTAP geändert werden?"^].



* Ab ONTAP 9.8 kann der  `[-language <Language code>]`Parameter verwendet werden, um die Volume-Sprache von *.UTF-8 auf utf8mb4 zu ändern. Für eine Änderung der Sprache eines Volumes ist link:http://mysupport.netapp.com/["NetApp Support"^]zu kontaktieren.



NOTE: LUN-Namen mit 4-Byte-UTF-8-Zeichen werden derzeit nicht unterstützt.

* Unicode-Zeichendaten werden in Windows-Dateisystemanwendungen typischerweise mit dem 16-Bit-Unicode-Transformationsformat (UTF-16) und in NFS-Dateisystemen mit dem 8-Bit-Unicode-Transformationsformat (UTF-8) dargestellt.
+
In Versionen vor ONTAP 9.5 wurden Namen mit UTF-16-Zusatzzeichen, die von Windows-Clients erstellt wurden, zwar anderen Windows-Clients korrekt angezeigt, jedoch nicht korrekt in UTF-8 für NFS-Clients übersetzt. Ebenso wurden Namen mit UTF-8-Zusatzzeichen, die von NFS-Clients erstellt wurden, nicht korrekt in UTF-16 für Windows-Clients übersetzt.

* Wenn auf Systemen, auf denen ONTAP 9.4 oder früher ausgeführt wird, Dateinamen erstellt werden, die gültige oder ungültige Zusatzzeichen enthalten, lehnt ONTAP den Dateinamen ab und gibt eine Fehlermeldung wegen eines ungültigen Dateinamens zurück.
+
Um dieses Problem zu vermeiden, sollten in Dateinamen ausschließlich BMP-Zeichen verwendet und auf die Verwendung von Zusatzzeichen verzichtet werden, oder es ist ein Upgrade auf ONTAP 9.5 oder höher durchzuführen.



Ab ONTAP 9 sind Unicode-Zeichen in qtree-Namen zulässig.

* Sie können entweder die  `volume qtree` Befehlsfamilie oder den System Manager verwenden, um Qtree-Namen festzulegen oder zu ändern.
* Qtree Namen können Mehrbytezeichen im Unicode-Format enthalten, wie zum Beispiel japanische und chinesische Schriftzeichen.
* In Versionen vor ONTAP 9.5 wurden nur BMP-Zeichen (das heißt, solche, die in 3 Bytes dargestellt werden konnten) unterstützt.
+

NOTE: In Versionen vor ONTAP 9.5 kann der Verbindungspfad des übergeordneten Volumes eines Qtrees Qtree- und Verzeichnisnamen mit Unicode-Zeichen enthalten. Der  `volume show` Befehl zeigt diese Namen korrekt an, wenn das übergeordnete Volume eine UTF-8-Spracheneinstellung hat. Wenn jedoch die Sprache des übergeordneten Volumes nicht zu den UTF-8-Spracheneinstellungen gehört, werden einige Teile des Verbindungspfads mit einem numerischen NFS-Alternativnamen angezeigt.

* In Version 9.5 und späteren Versionen werden 4-Byte-Zeichen in Qtree-Namen unterstützt, vorausgesetzt, der Qtree befindet sich in einem Volume, das für utf8mb4 aktiviert ist.

