---
permalink: smb-admin/performance-impact-encryption-concept.html 
sidebar: sidebar 
keywords: smb, session, encryption, communication, windows, client, experience, performance, impact, affect, server, node, svm, performance impact of smb encryption 
summary: Wenn SMB-Sitzungen SMB-Verschlüsselung verwenden, kommt es bei der gesamten SMB-Kommunikation mit Windows-Clients zu Leistungseinbußen, die sowohl die Clients als auch den Server betreffen. 
---
= Informationen zu den Auswirkungen der ONTAP SMB-Verschlüsselung auf die Performance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn SMB-Sitzungen SMB-Verschlüsselung verwenden, kommt es bei der gesamten SMB-Kommunikation mit Windows-Clients zu Leistungseinbußen, die sowohl die Clients als auch den Server betreffen (das heißt, die Knoten im Cluster, auf denen die SVM ausgeführt wird, die den SMB-Server enthält).

Die Auswirkungen auf die Leistung zeigen sich in einer erhöhten CPU-Auslastung sowohl auf den Clients als auch auf dem Server, obwohl sich das Netzwerkverkehr nicht ändert.

Das Ausmaß der Leistungseinbußen hängt von der Version von ONTAP 9 ab, die Sie verwenden. Ab ONTAP 9.7 kann ein neuer Verschlüsselungs-Offload-Algorithmus eine bessere Performance im verschlüsselten SMB-Datenverkehr ermöglichen. Die SMB-Verschlüsselungsauslagerung ist standardmäßig aktiviert, wenn die SMB-Verschlüsselung aktiviert ist.

Für eine verbesserte SMB-Verschlüsselungsleistung ist die AES-NI-Offload-Funktion erforderlich. Im Hardware Universe (HWU) kann überprüft werden, ob für Ihre Plattform AES-NI-Offload unterstützt wird.

Weitere Leistungsverbesserungen sind ebenfalls möglich, wenn Sie SMB Version 3.11 verwenden können, die den wesentlich schnelleren GCM Algorithmus unterstützt.

Je nach Netzwerk, ONTAP 9 Version, SMB Version und SVM-Implementierung kann der Einfluss der SMB-Verschlüsselung auf die Leistung stark variieren; dies lässt sich nur durch Tests in Ihrer Netzwerkumgebung überprüfen.

Die SMB-Verschlüsselung ist auf dem SMB-Server standardmäßig deaktiviert. Die SMB-Verschlüsselung sollte nur für diejenigen SMB-Freigaben oder SMB-Server aktiviert werden, die eine Verschlüsselung benötigen. Mit SMB-Verschlüsselung führt ONTAP für jede Anfrage eine zusätzliche Verarbeitung durch, indem die Anfragen entschlüsselt und die Antworten verschlüsselt werden. Die SMB-Verschlüsselung sollte daher nur bei Bedarf aktiviert werden.
