---
permalink: smb-admin/previous-versions-view-manage-snapshot-data-task.html 
sidebar: sidebar 
keywords: windows, client, machine, previous, version, tab, properties, restore, data, store, snapshot, copies, copy, storage, virtual, machine, svm, administrator, use the previous versions tab to view and manage snapshot copy data 
summary: Benutzer von Windows-Clientrechnern können über die Registerkarte „Vorherige Versionen“ im Fenster „Windows-Eigenschaften“ Daten wiederherstellen, die in Snapshots gespeichert sind, ohne den Administrator der virtuellen Speichermaschine einbeziehen zu müssen. 
---
= ONTAP SMB-Snapshot-Daten lassen sich mit der Registerkarte „Windows Vorherige Versionen“ anzeigen und verwalten.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Benutzer auf Windows-Clientrechnern können die Registerkarte „Vorherige Versionen“ im Fenster „Windows-Eigenschaften“ verwenden, um Daten wiederherzustellen, die in Snapshots gespeichert sind, ohne den Administrator der Storage Virtual Machine (SVM) einbeziehen zu müssen.

.Über diese Aufgabe
Die Registerkarte „Vorherige Versionen“ kann nur zum Anzeigen und Verwalten von Daten in Snapshots von auf der SVM gespeicherten Daten verwendet werden, wenn der Administrator Snapshots auf dem Volume, das die Freigabe enthält, aktiviert hat und die Freigabe so konfiguriert ist, dass Snapshots angezeigt werden.

.Schritte
. Im Windows Explorer werden die Inhalte des zugeordneten Laufwerks mit den auf dem CIFS-Server gespeicherten Daten angezeigt.
. Klicken Sie mit der rechten Maustaste auf die Datei oder den Ordner im zugeordneten Netzlaufwerk, dessen Snapshots Sie anzeigen oder verwalten möchten.
. *Eigenschaften* auswählen.
+
Die Eigenschaften der ausgewählten Datei oder des ausgewählten Ordners werden angezeigt.

. Die Registerkarte *Vorherige Versionen* auswählen.
+
Im Feld „Ordnerversionen“ wird eine Liste der verfügbaren Snapshots der ausgewählten Datei oder des ausgewählten Ordners angezeigt. Die aufgelisteten Snapshots werden durch das Snapshot-Namenspräfix und den Erstellungszeitstempel identifiziert.

. Im Feld *Ordnerversionen:* mit der rechten Maustaste auf die Kopie der Datei oder des Ordners klicken, die verwaltet werden soll.
. Die entsprechende Maßnahme ausführen:
+
|===
| Wenn Sie möchten... | Führen Sie folgende Schritte aus... 


 a| 
Daten aus diesem Snapshot anzeigen
 a| 
Auf *Öffnen* klicken.



 a| 
Eine Kopie der Daten aus diesem Snapshot erstellen
 a| 
Auf *Kopieren* klicken.

|===
+
Die Daten in Snapshots sind schreibgeschützt. Wenn Änderungen an den im Tab „Vorherige Versionen“ aufgeführten Dateien und Ordnern vorgenommen werden sollen, ist eine Kopie der zu ändernden Dateien und Ordner an einem beschreibbaren Speicherort zu speichern und die Änderungen an den Kopien vorzunehmen.

. Nachdem Sie die Verwaltung der Snapshot-Daten abgeschlossen haben, wird das Dialogfeld *Eigenschaften* durch Klicken auf *OK* geschlossen.
+
Weitere Informationen zur Verwendung der Registerkarte „Vorherige Versionen“ zum Anzeigen und Verwalten von Snapshot-Daten bietet die Microsoft TechNet Library.



.Verwandte Informationen
http://technet.microsoft.com/en-us/library/["Microsoft TechNet Bibliothek: technet.microsoft.com/en-us/library/"]
