---
permalink: smb-admin/provide-security-access-based-enumeration-task.html 
sidebar: sidebar 
keywords: access-based, enumeration, abe, enable, smb, share, user, folder, file, contain, within, share, individual, permission, restriction, resource, environment, provide folder security on shares with access-based enumeration 
summary: 'Wenn Access-Based Enumeration (ABE) auf einer SMB-Freigabe aktiviert ist, sehen Benutzer, die nicht über die Berechtigung verfügen, auf einen Ordner oder eine Datei in der Freigabe zuzugreifen (sei es durch einzelne oder Gruppen-Berechtigungsbeschränkungen), nicht, dass gemeinsam genutzte Ressourcen in ihrer Umgebung angezeigt werden.' 
---
= Sorgen Sie für ONTAP SMB-Ordnersicherheit auf Freigaben mit zugriffsbasierter Aufzählung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Access-Based Enumeration (ABE) auf einer SMB-Freigabe aktiviert ist, sehen Benutzer, die nicht über die Berechtigung zum Zugriff auf einen Ordner oder eine Datei in der Freigabe verfügen (sei es durch einzelne oder Gruppen-Berechtigungsbeschränkungen), nicht, dass freigegebene Ressourcen in ihrer Umgebung angezeigt werden, obwohl die Freigabe selbst sichtbar bleibt.

Mit herkömmlichen Freigabeeigenschaften können Sie festlegen, welche Benutzer (einzeln oder in Gruppen) die Berechtigung haben, Dateien oder Ordner in der Freigabe anzuzeigen oder zu ändern. Sie erlauben Ihnen jedoch nicht, zu steuern, ob Ordner oder Dateien innerhalb der Freigabe für Benutzer sichtbar sind, die nicht über die Berechtigung zum Zugriff auf sie verfügen. Dies kann zu Problemen führen, wenn die Namen dieser Ordner oder Dateien innerhalb der Freigabe vertrauliche Informationen beschreiben, z. B. die Namen der Kunden oder Produkte, die in der Entwicklung sind.

Access-Based Enumeration (ABE) erweitert die Share-Eigenschaften um die Aufzählung von Dateien und Ordnern innerhalb der Freigabe. ABE ermöglicht es Ihnen daher, die Anzeige von Dateien und Ordnern innerhalb der Freigabe anhand von Benutzerzugriffsrechten zu filtern. Das heißt, die Freigabe selbst wäre für alle Benutzer sichtbar, aber Dateien und Ordner innerhalb der Freigabe können angezeigt oder ausgeblendet werden von bestimmten Benutzern. Neben dem Schutz sensibler Informationen in Ihrem Arbeitsplatz ermöglicht Ihnen ABE, die Darstellung großer Verzeichnisstrukturen zu vereinfachen, und zwar zum Vorteil von Anwendern, die keinen Zugriff auf Ihre gesamte Bandbreite benötigen. Beispielsweise würde die Freigabe selbst für alle Benutzer sichtbar sein, aber Dateien und Ordner innerhalb der Freigabe können angezeigt oder ausgeblendet werden.

Erfahren Sie mehr über link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Performance_impact_when_using_CIFS_Access_Based_Enumeration["Auswirkungen auf die Performance bei Verwendung von SMB/CIFS Access Based Enumeration"^].
