---
permalink: smb-admin/reasons-invalidates-branchcache-hashes-concept.html 
sidebar: sidebar 
keywords: understand, ontap, invalidate, hash, branchcache, configuration, share, reasons ontap invalidates branchcache hashes 
summary: Das Verständnis der Gründe, warum ONTAP Hashes ungültig macht, kann bei der Planung Ihrer BranchCache Konfiguration hilfreich sein. Dies kann bei der Entscheidung unterstützen, welchen Betriebsmodus konfiguriert werden sollte, und bei der Auswahl helfen, auf welchen Freigaben BranchCache aktiviert werden soll. 
---
= Informationen zu den Gründen, aus denen ONTAP SMB BranchCache-Hashes für ungültig erklärt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Verständnis der Gründe, warum ONTAP Hashes ungültig macht, kann bei der Planung Ihrer BranchCache Konfiguration hilfreich sein. Dies kann bei der Entscheidung unterstützen, welchen Betriebsmodus konfiguriert werden sollte, und bei der Auswahl helfen, auf welchen Freigaben BranchCache aktiviert werden soll.

ONTAP muss BranchCache-Hashwerte verwalten, um sicherzustellen, dass die Hashwerte gültig sind. Ist ein Hashwert ungültig, erklärt ONTAP den Hashwert für ungültig und berechnet beim nächsten Anfordern desselben Inhalts einen neuen Hashwert, sofern BranchCache weiterhin aktiviert ist.

ONTAP macht Hashes aus folgenden Gründen ungültig:

* Der Serverschlüssel wurde geändert.
+
Wenn der Serverschlüssel geändert wird, macht ONTAP alle Hashes im Hash-Speicher ungültig.

* Ein Hashwert wird aus dem Cache gelöscht, da die maximale Größe des BranchCache Hashspeichers erreicht wurde.
+
Dies ist ein anpassbarer Parameter und kann entsprechend Ihren Geschäftsanforderungen geändert werden.

* Eine Datei wird entweder über SMB- oder NFS-Zugriff geändert.
* Eine Datei, für die berechnete Hashwerte vorliegen, wird mit dem  `snap restore` Befehl wiederhergestellt.
* Ein Volume, das SMB-Freigaben enthält, die für BranchCache aktiviert sind, wird mit dem  `snap restore` Befehl wiederhergestellt.

