---
permalink: smb-admin/requirements-gpos-concept.html 
sidebar: sidebar 
keywords: group, policy, object, gpo, smb, server, system, requirement, requirements for using gpos with your smb server 
summary: 'Um Gruppenrichtlinienobjekte (Gruppenrichtlinienobjekte, GPOs) auf Ihrem SMB-Server zu verwenden, muss Ihr System mehrere Anforderungen erfüllen.' 
---
= Anforderungen für die Verwendung von Gruppenrichtlinienobjekten mit Ihrem SMB-Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um Gruppenrichtlinienobjekte (Gruppenrichtlinienobjekte, GPOs) auf Ihrem SMB-Server zu verwenden, muss Ihr System mehrere Anforderungen erfüllen.

* SMB muss auf dem Cluster lizenziert sein. Die SMB-Lizenz ist im Lieferumfang enthaltenlink:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"]. Wenn Sie ONTAP One nicht besitzen und die Lizenz nicht installiert ist, wenden Sie sich an Ihren Vertriebsmitarbeiter.
* Ein SMB Server muss konfiguriert und einer Windows Active Directory Domäne hinzugefügt werden.
* Der Status des SMB-Server-Administrators muss sich im befinden.
* Gruppenrichtlinienobjekte müssen konfiguriert und auf die Organisationseinheit (OU) von Windows Active Directory angewendet werden, die das SMB-Servercomputer-Objekt enthält.
* Die GPO-Unterstützung muss auf dem SMB-Server aktiviert sein.

