---
permalink: smb-admin/requirements-gpos-concept.html 
sidebar: sidebar 
keywords: group, policy, object, gpo, smb, server, system, requirement, requirements for using gpos with your smb server 
summary: Um Gruppenrichtlinienobjekte mit Ihrem SMB-Server verwenden zu können, muss Ihr System mehrere Voraussetzungen erfüllen. 
---
= ONTAP SMB-Server Anforderungen für Gruppenrichtlinienobjekte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um Gruppenrichtlinienobjekte (GPOs) mit Ihrem SMB-Server verwenden zu können, muss Ihr System mehrere Voraussetzungen erfüllen.

* SMB muss auf dem Cluster lizenziert sein. Die SMB-Lizenz ist mit link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"] enthalten. Wenn ONTAP One nicht vorhanden ist und die Lizenz nicht installiert ist, sollte der Vertriebsmitarbeiter kontaktiert werden.
* Ein SMB-Server muss konfiguriert und einer Windows Active Directory-Domäne hinzugefügt werden.
* Der SMB-Server-Adminstatus muss aktiviert sein.
* Gruppenrichtlinienobjekte (GPOs) müssen für die Windows Active Directory Abteilung (OU) konfiguriert und angewendet werden, die das SMB-Server-Computerobjekt enthält.
* Die GPO-Unterstützung muss auf dem SMB-Server aktiviert sein.

