---
permalink: smb-admin/reset-privileges-local-domain-users-groups-task.html 
sidebar: sidebar 
keywords: reset, privilege, local, domain, user, group, modification, reset privilege for local or domain users and groups 
summary: Sie können Berechtigungen für lokale Benutzer oder Domänenbenutzer und -Gruppen zurücksetzen. Dies kann nützlich sein, wenn Sie Änderungen an Berechtigungen für einen lokalen Benutzer oder eine Domänengruppe vorgenommen haben und diese Änderungen nicht mehr gewünscht oder erforderlich sind. 
---
= Berechtigungen für lokale oder Domänenbenutzer und -Gruppen zurücksetzen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Berechtigungen für lokale Benutzer oder Domänenbenutzer und -Gruppen zurücksetzen. Dies kann nützlich sein, wenn Sie Änderungen an Berechtigungen für einen lokalen Benutzer oder eine Domänengruppe vorgenommen haben und diese Änderungen nicht mehr gewünscht oder erforderlich sind.

.Über diese Aufgabe
Beim Zurücksetzen der Berechtigungen für einen lokalen oder Domänenbenutzer oder eine Gruppe werden alle Berechtigungseinträge für dieses Objekt entfernt.

.Schritte
. Zurücksetzen der Berechtigungen für einen lokalen Benutzer oder eine Domänenbenutzer oder -Gruppe: `vserver cifs users-and-groups privilege reset-privilege -vserver _vserver_name_ -user-or-group-name _name_`
. Vergewissern Sie sich, dass die Berechtigungen auf dem Objekt zurückgesetzt wurden: `vserver cifs users-and-groups privilege show -vserver _vserver_name_ ‑user-or-group-name _name_`


.Beispiele
Im folgenden Beispiel werden die Berechtigungen des Benutzers „`CIFS_SERVER\sue`“ auf der Storage Virtual Machine (SVM, früher als Vserver bezeichnet) vs1 zurückgesetzt. Standardmäßig verfügen normale Benutzer über keine Berechtigungen, die mit ihren Konten verknüpft sind:

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show
Vserver   User or Group Name    Privileges
--------- --------------------- ---------------
vs1       CIFS_SERVER\sue       SeTcbPrivilege
                                SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege reset-privilege -vserver vs1 -user-or-group-name CIFS_SERVER\sue

cluster1::> vserver cifs users-and-groups privilege show
This table is currently empty.
----
Das folgende Beispiel setzt die Berechtigungen für die Gruppe „`BUILTIN\Administrators`“ zurück und entfernt damit effektiv den Eintrag für Berechtigungen:

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show
Vserver   User or Group Name       Privileges
--------- ------------------------ -------------------
vs1       BUILTIN\Administrators   SeRestorePrivilege
                                   SeSecurityPrivilege
                                   SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege reset-privilege -vserver vs1 -user-or-group-name BUILTIN\Administrators

cluster1::> vserver cifs users-and-groups privilege show
This table is currently empty.
----