---
permalink: smb-admin/reset-rediscovering-servers-task.html 
sidebar: sidebar 
keywords: reset, discover, rediscover, server, cifs, server, discard, store, information, ldap, domain, controller, information, external, respond, reset and rediscover servers 
summary: Durch das Zurücksetzen und die erneute Erkennung von Servern auf Ihrem CIFS-Server kann der CIFS-Server gespeicherte Informationen über LDAP-Server und Domänen-Controller verwerfen. Nach der Entfernung von Serverinformationen erfasst der CIFS-Server aktuelle Informationen zu diesen externen Servern. Dies kann nützlich sein, wenn die verbundenen Server nicht entsprechend reagieren. 
---
= ONTAP SMB-Server zurücksetzen und neu ermitteln
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durch das Zurücksetzen und die erneute Erkennung von Servern auf Ihrem CIFS-Server kann der CIFS-Server gespeicherte Informationen über LDAP-Server und Domänen-Controller verwerfen. Nach der Entfernung von Serverinformationen erfasst der CIFS-Server aktuelle Informationen zu diesen externen Servern. Dies kann nützlich sein, wenn die verbundenen Server nicht entsprechend reagieren.

.Schritte
. Geben Sie den folgenden Befehl ein: `vserver cifs domain discovered-servers reset-servers -vserver _vserver_name_`
. Informationen zu den neu erkannten Servern anzeigen: `vserver cifs domain discovered-servers show -vserver _vserver_name_`


.Beispiel
Im folgenden Beispiel werden Server für Storage Virtual Machine (SVM, ehemals Vserver) vs1 zurückgesetzt und neu erkannt:

[listing]
----
cluster1::> vserver cifs domain discovered-servers reset-servers -vserver vs1

cluster1::> vserver cifs domain discovered-servers show

Node: node1
Vserver: vs1

Domain Name     Type     Preference DC-Name     DC-Address    Status
--------------- -------- ---------- ----------- ------------- -------
example.com     MS-LDAP  adequate   DC-1        1.1.3.4       OK
example.com     MS-LDAP  adequate   DC-2        1.1.3.5       OK
example.com     MS-DC    adequate   DC-1        1.1.3.4       OK
example.com     MS-DC    adequate   DC-2        1.1.3.5       OK
----
.Verwandte Informationen
xref:display-discovered-servers-task.adoc[Anzeigen von Informationen zu erkannten Servern]

xref:stop-start-server-task.adoc[Beenden oder Starten des CIFS-Servers]
