---
permalink: smb-admin/restore-directories-that-contain-junctions-concept.html 
sidebar: sidebar 
keywords: guideline, version, restore, folder, junction, point, guidelines for restoring directories that contain junctions 
summary: Es gibt bestimmte Richtlinien, die Sie beachten sollten, wenn Sie frühere Versionen verwenden, um Ordner wiederherzustellen, die Verbindungspunkte enthalten. 
---
= Richtlinien zum Wiederherstellen von Verzeichnissen, die Verbindungen enthalten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es gibt bestimmte Richtlinien, die Sie beachten sollten, wenn Sie frühere Versionen verwenden, um Ordner wiederherzustellen, die Verbindungspunkte enthalten.

Wenn Sie frühere Versionen verwenden, um Ordner wiederherzustellen, die untergeordnete Ordner haben, die Verbindungspunkte sind, kann die Wiederherstellung mit einem fehlschlagen `Access Denied` Fehler.

Sie können feststellen, ob der Ordner, den Sie wiederherstellen möchten, eine Verbindung enthält, indem Sie den verwenden `vol show` Befehl mit dem `-parent` Option. Sie können auch die verwenden `vserver security trace` Befehle zum Erstellen detaillierter Protokolle über Probleme beim Datei- und Ordnerzugriff.

.Verwandte Informationen
xref:create-manage-data-volumes-nas-namespaces-concept.adoc[Daten-Volumes werden in NAS-Namespaces erstellt und gemanagt]
