---
permalink: smb-admin/restore-directories-that-contain-junctions-concept.html 
sidebar: sidebar 
keywords: guideline, version, restore, folder, junction, point, guidelines for restoring directories that contain junctions 
summary: Bestimmte Richtlinien sind zu beachten, wenn „Vorherige Versionen“ zum Wiederherstellen von Ordnern mit Verbindungspunkten verwendet wird. 
---
= Informationen zur Wiederherstellung von Verzeichnissen mit früheren Versionen, die ONTAP SMB-Verbindungen enthalten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bestimmte Richtlinien sind zu beachten, wenn „Vorherige Versionen“ zum Wiederherstellen von Ordnern mit Verbindungspunkten verwendet wird.

Wenn „Vorherige Versionen“ zum Wiederherstellen von Ordnern verwendet wird, die untergeordnete Ordner als Verbindungspunkte enthalten, kann die Wiederherstellung mit einem  `Access Denied` Fehler fehlschlagen.

Es lässt sich feststellen, ob der Ordner, den Sie wiederherstellen möchten, eine Verbindung enthält, indem der  `vol show` Befehl mit der  `-parent` Option verwendet wird. Auch die  `vserver security trace` Befehle können genutzt werden, um detaillierte Protokollierung zu Problemen beim Dateizugriff und Ordnerzugriff zu erstellen.

.Verwandte Informationen
xref:create-manage-data-volumes-nas-namespaces-concept.adoc[Erstellen und Verwalten von Datenvolumes in NAS-Namespaces]
