---
permalink: smb-admin/roaming-profiles-store-user-profiles-concept.html 
sidebar: sidebar 
keywords: ontap, support, storing, store, windows, roam, profile, cifs, server, associate, storage, virtual, machine, svm, configuring, configure, automatic, resource, availability, available, regardless, use roaming profiles to store user profiles centrally on a cifs server associated with the svm 
summary: 'ONTAP unterstützt das Speichern von Windows Roaming-Profilen auf einem CIFS-Server, der der Storage Virtual Machine (SVM) zugeordnet ist. Die Konfiguration von Roaming-Profilen für Benutzer bietet Vorteile für den Benutzer, z. B. die automatische Verfügbarkeit von Ressourcen, unabhängig davon, wo sich der Benutzer anmeldet. Roaming-Profile vereinfachen zudem die Administration und das Management von Benutzerprofilen.' 
---
= Nutzen Sie die Roaming-Profile, um Benutzerprofile zentral auf einem SMB-Server zu speichern, der der SVM Übersicht zugeordnet ist
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP unterstützt das Speichern von Windows Roaming-Profilen auf einem CIFS-Server, der der Storage Virtual Machine (SVM) zugeordnet ist. Die Konfiguration von Roaming-Profilen für Benutzer bietet Vorteile für den Benutzer, z. B. die automatische Verfügbarkeit von Ressourcen, unabhängig davon, wo sich der Benutzer anmeldet. Roaming-Profile vereinfachen zudem die Administration und das Management von Benutzerprofilen.

Roaming-Benutzerprofile bieten die folgenden Vorteile:

* Automatische Ressourcenverfügbarkeit
+
Das eindeutige Profil eines Benutzers steht automatisch zur Verfügung, wenn sich dieser Benutzer bei jedem Computer im Netzwerk anmeldet, auf dem Windows 8, Windows 7, Windows 2000 oder Windows XP ausgeführt wird. Benutzer müssen kein Profil auf jedem Computer erstellen, den sie in einem Netzwerk verwenden.

* Vereinfachte Computerbereitstellung
+
Da alle Profilinformationen des Benutzers separat im Netzwerk verwaltet werden, kann das Benutzerprofil leicht auf einen neuen Ersatzcomputer heruntergeladen werden. Wenn sich der Benutzer zum ersten Mal beim neuen Computer anmeldet, wird die Serverkopie des Benutzerprofils auf den neuen Computer kopiert.



xref:offline-files-allow-caching-concept.adoc[Verwendung von Offline-Dateien, um das Caching von Dateien für die Offline-Verwendung zu ermöglichen]

xref:folder-redirection-store-data-concept.adoc[Verwenden der Ordnerumleitung zum Speichern von Daten auf einem CIFS-Server]
