---
permalink: smb-admin/secure-file-access-dynamic-access-control-concept.html 
sidebar: sidebar 
keywords: secure, access, dynamic, control, creating, create, central, policies, policy, active, directory, apply, file, folder, group, policy, object, gpo, staging, stage, change, secure file access by using dynamic access control, dac 
summary: Sie können den Zugriff sichern, indem Sie Dynamic Access Control nutzen und zentrale Zugriffsrichtlinien in Active Directory erstellen und diese über angewendete Gruppenrichtlinienobjekte auf Dateien und Ordner auf SVMs anwenden. Es besteht die Möglichkeit, die Protokollierung so zu konfigurieren, dass zentrale Zugriffsrichtlinien-Staging-Ereignisse verwendet werden, um die Auswirkungen von Änderungen an zentralen Zugriffsrichtlinien zu sehen, bevor diese angewendet werden. 
---
= Informationen zur DAC-Dateizugriffsicherheit für ONTAP SMB-Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Zugriff sichern, indem Sie die dynamische Zugriffssteuerung nutzen und zentrale Zugriffsrichtlinien in Active Directory erstellen und diese über angewendete Gruppenrichtlinienobjekte (GPOs) auf Dateien und Ordner auf SVMs anwenden. Es besteht die Möglichkeit, die Protokollierung so zu konfigurieren, dass zentrale Zugriffsrichtlinien-Staging-Ereignisse verwendet werden, um die Auswirkungen von Änderungen an zentralen Zugriffsrichtlinien zu sehen, bevor diese angewendet werden.



[[additions-to-cifs-credentials]]
== Ergänzungen zu den CIFS-Anmeldeinformationen

Vor der dynamischen Zugriffssteuerung enthielt eine CIFS-Anmeldeinformation die Identität des Sicherheitsprinzipals (des Benutzers) und die Windows-Gruppenzugehörigkeit. Mit der dynamischen Zugriffssteuerung werden der Anmeldeinformation drei weitere Informationstypen hinzugefügt: Geräteidentität, Geräteansprüche und Benutzeransprüche.

* Geräteidentität
+
Das Analogon zu den Identitätsinformationen des Benutzers, nur dass es sich um die Identität und Gruppenzugehörigkeit des Geräts handelt, von dem sich der Benutzer einloggt.

* Geräteansprüche
+
Aussagen über einen Gerätesicherheitsprinzipal. Beispielsweise könnte eine Geräteaussage lauten, dass das Gerät Mitglied einer bestimmten Organisationseinheit (OU) ist.

* Benutzeransprüche
+
Aussagen über einen Benutzer-Sicherheitsprinzipal. Beispielsweise könnte eine Benutzer-Assertion lauten, dass das AD-Konto Mitglied einer bestimmten OU ist.





[[central-access-policies]]
== Zentrale Zugriffsrichtlinien

Zentrale Zugriffsrichtlinien für Dateien ermöglichen Organisationen, Autorisierungsrichtlinien, die bedingte Ausdrücke mit Benutzergruppen, Benutzeransprüchen, Geräteansprüchen und Ressourceneigenschaften enthalten, zentral bereitzustellen und zu verwalten.

Beispielsweise muss ein Benutzer, um auf geschäftskritische Daten zuzugreifen, Vollzeitbeschäftigter sein und darf nur von einem verwalteten Gerät aus auf die Daten zugreifen. Zentrale Zugriffsrichtlinien werden in Active Directory definiert und über den GPO-Mechanismus an Dateiserver verteilt.



[[central-access-policy-staging-with-advanced-auditing]]
== Zentrale Bereitstellung von Zugriffsrichtlinien mit erweiterter Protokollierung

Zentrale Zugriffsrichtlinien können „staged“ werden, wobei sie bei Dateizugriffsprüfungen in einer „what-if“-Manier ausgewertet werden. Die Ergebnisse dessen, was passiert wäre, wenn die Richtlinie wirksam gewesen wäre, und wie sich das von der aktuellen Konfiguration unterscheidet, werden als Protokollierungsereignis erfasst. Auf diese Weise können Administratoren Protokollierungsereignisse nutzen, um die Auswirkungen einer Änderung der Zugriffsrichtlinie zu untersuchen, bevor die Richtlinie tatsächlich angewendet wird. Nach der Bewertung der Auswirkungen einer Änderung der Zugriffsrichtlinie kann die Richtlinie über GPOs auf die gewünschten SVMs bereitgestellt werden.

.Verwandte Informationen
* xref:supported-gpos-concept.adoc[Informationen zu unterstützten Gruppenrichtlinienobjekten (GPOs)]
* xref:applying-group-policy-objects-concept.adoc[Informationen zur Anwendung von Gruppenrichtlinienobjekten auf SMB-Server]
* xref:enable-disable-gpo-support-task.adoc[GPO-Unterstützung auf Servern aktivieren oder deaktivieren]
* xref:display-gpo-config-task.adoc[Informationen zu GPO-Konfigurationen anzeigen]
* xref:display-central-access-policies-task.adoc[Informationen zu zentralen Zugriffsrichtlinien anzeigen]
* xref:display-central-access-policy-rules-task.adoc[Informationen zu zentralen Zugriffsrichtlinienregeln]
* xref:configure-central-access-policies-secure-data-task.adoc[Zentrale Zugriffsrichtlinien konfigurieren, um Daten auf Servern zu sichern.]
* xref:display-dynamic-access-control-security-task.adoc[Informationen zur Serversicherheit]
* link:../nas-audit/index.html["SMB und NFS Auditierung und Sicherheitsverfolgung"]

