---
permalink: smb-admin/server-security-settings-svm-disaster-recovery-concept.html 
sidebar: sidebar 
keywords: create, creating, svm, configure, disaster, recovery, destination, identity, preserve, snapmirror, configuration, smb, guideline, guidelines for smb server security settings in an svm disaster recovery configuration 
summary: 'Vor dem Erstellen einer SVM, die als Disaster-Recovery-Ziel konfiguriert ist und wo die Identität nicht erhalten bleibt (die Option -identitätsbewahrung ist in der SnapMirror Konfiguration auf „false“ gesetzt), sollten Sie wissen, wie SMB-Server-Sicherheitseinstellungen auf der Ziel-SVM gemanagt werden.' 
---
= Richtlinien für die Sicherheitseinstellungen von SMB-Servern in einer SVM-Disaster-Recovery-Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie eine SVM erstellen, die als Disaster-Recovery-Ziel konfiguriert ist, bei dem die Identität nicht erhalten bleibt ( `-identity-preserve` `false`in der SnapMirror-Konfiguration ist die Option auf festgelegt), sollten Sie wissen, wie die Sicherheitseinstellungen von SMB-Servern auf der Ziel-SVM gemanagt werden.

* Nicht standardmäßige SMB-Server-Sicherheitseinstellungen werden nicht auf das Ziel repliziert.
+
Wenn Sie einen SMB-Server auf der Ziel-SVM erstellen, sind alle SMB-Server-Sicherheitseinstellungen auf die Standardwerte festgelegt. Wenn das SVM Disaster-Recovery-Ziel initialisiert, aktualisiert oder neu synchronisiert wird, werden die SMB-Server-Sicherheitseinstellungen auf der Quelle nicht zum Ziel repliziert.

* Sie müssen die Sicherheitseinstellungen für nicht standardmäßige SMB-Server manuell konfigurieren.
+
Wenn Sie auf der Quell-SVM nicht standardmäßige SMB-Server-Sicherheitseinstellungen konfiguriert haben, müssen Sie diese Einstellungen nach Lese-/Schreibzugriff des Ziels manuell auf der Ziel-SVM konfigurieren (nachdem die SnapMirror Beziehung unterbrochen wurde).


