---
permalink: smb-admin/server-security-settings-svm-disaster-recovery-concept.html 
sidebar: sidebar 
keywords: create, creating, svm, configure, disaster, recovery, destination, identity, preserve, snapmirror, configuration, smb, guideline, guidelines for smb server security settings in an svm disaster recovery configuration 
summary: Bevor Sie eine SVM erstellen, die als Disaster-Recovery-Ziel konfiguriert ist, bei dem die Identität nicht erhalten bleibt, sollten Sie wissen, wie die SMB-Server-Sicherheitseinstellungen auf der Ziel-SVM verwaltet werden. 
---
= Informationen zu den SMB-Server-Sicherheitseinstellungen für die ONTAP SVM-Disaster Recovery Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor eine SVM erstellt wird, die als Disaster Recovery-Ziel konfiguriert ist, bei dem die Identität nicht erhalten bleibt (die  `-identity-preserve` Option ist auf  `false` in der SnapMirror-Konfiguration gesetzt), ist es wichtig, Informationen darüber zu haben, wie die SMB-Server-Sicherheitseinstellungen auf der Ziel-SVM verwaltet werden.

* Nicht standardmäßige SMB-Server-Sicherheitseinstellungen werden nicht auf das Ziel repliziert.
+
Beim Erstellen eines SMB-Servers auf der Ziel-SVM werden alle Sicherheitseinstellungen des SMB-Servers auf die Standardwerte gesetzt. Bei der Initialisierung, Aktualisierung oder Resynchronisierung der SVM für die Notfallwiederherstellung werden die Sicherheitseinstellungen des SMB-Servers auf der Quelle nicht auf das Ziel repliziert.

* Die von den Standardeinstellungen abweichenden Sicherheitseinstellungen des SMB-Servers sind manuell zu konfigurieren.
+
Wenn auf der Quell-SVM nicht standardmäßige SMB-Server-Sicherheitseinstellungen konfiguriert sind, müssen diese Einstellungen auf der Ziel-SVM manuell konfiguriert werden, nachdem die Ziel-SVM Lese- und Schreibzugriff erhält (nachdem die SnapMirror Beziehung aufgehoben wurde).


