---
permalink: smb-admin/signing-multiple-data-lifs-concept.html 
sidebar: sidebar 
keywords: enable, disable, require, smb, sign, server, guideline, lifs, configuration, svm, guidelines for smb signing when multiple data lifs are configured 
summary: Wenn Sie die erforderliche SMB-Signatur auf dem SMB-Server aktivieren bzw. deaktivieren, sollten Sie die Richtlinien für mehrere Daten-LIFS-Konfigurationen für eine SVM kennen. 
---
= Richtlinien für das SMB-Signing beim Konfigurieren mehrerer Daten-LIFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die erforderliche SMB-Signatur auf dem SMB-Server aktivieren bzw. deaktivieren, sollten Sie die Richtlinien für mehrere Daten-LIFS-Konfigurationen für eine SVM kennen.

Wenn Sie einen SMB Server konfigurieren, sind möglicherweise mehrere Daten-LIFs konfiguriert. Wenn dies der Fall ist, enthält der DNS-Server mehrere `A` Notieren Sie Einträge für den CIFS-Server, die alle denselben SMB-Serverhostnamen verwenden, jedoch jeweils über eine eindeutige IP-Adresse verfügen. Ein SMB-Server mit zwei konfigurierten Daten-LIFs hat beispielsweise den folgenden DNS `A` Eintragseinträge:

[listing]
----
10.1.1.128 A VS1.IEPUB.LOCAL VS1
10.1.1.129 A VS1.IEPUB.LOCAL VS1
----
Das normale Verhalten besteht darin, dass beim Ändern der erforderlichen SMB-Signing-Einstellung nur neue Verbindungen von Clients von der Änderung der SMB-Signing-Einstellung betroffen sind. Allerdings gibt es eine Ausnahme von diesem Verhalten. Es gibt einen Fall, in dem ein Client eine bestehende Verbindung zu einer Freigabe hat, und der Client erstellt eine neue Verbindung zu derselben Freigabe, nachdem die Einstellung geändert wurde, während die ursprüngliche Verbindung beibehalten wird. In diesem Fall übernehmen sowohl die neue als auch die bestehende SMB-Verbindung die neuen SMB-Signaturanforderungen.

Beispiel:

. Client1 stellt eine Verbindung zu einem Share ohne die erforderliche SMB-Signatur über den Pfad her `O:\`.
. Der Storage-Administrator ändert die SMB Server-Konfiguration, für die SMB-Signaturen erforderlich sind.
. Client1 verbindet sich mit demselben Share mit der erforderlichen SMB-Signatur über den Pfad `S:\` (Während die Verbindung über den Pfad aufrechterhalten wird `O:\`).
. Infolgedessen wird SMB Signing verwendet, wenn der Zugriff auf Daten über beide erfolgt `O:\` Und `S:\` Laufwerke.

