---
permalink: smb-admin/statistics-monitor-automatic-node-referral-task.html 
sidebar: sidebar 
keywords: smb, connection, refer, monitor, automatic, node, referral, extent, locating, locate, host, redistribute, lif, local, access, cifs, use statistics to monitor automatic node referral activity 
summary: Um zu bestimmen, wie viele SMB-Verbindungen weitergeleitet werden, können Sie die automatische Node-Weiterleitungsaktivität mithilfe des Statistiken-Befehls überwachen. Durch die Überwachung der Weiterleitungen lässt sich feststellen, inwieweit automatische Weiterleitungen Verbindungen auf Knoten herstellen, die die Freigaben hosten, und ob eine Neuzuordnung der Daten-LIFs sinnvoll ist, um einen besseren lokalen Zugriff auf Freigaben auf dem CIFS-Server zu ermöglichen. 
---
= Statistiken dienen zur Überwachung der automatischen Node-Referral-Aktivität von ONTAP SMB.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um die Anzahl der weitergeleiteten SMB-Verbindungen zu ermitteln, kann die automatische Knotenweiterleitungsaktivität mithilfe des  `statistics` Befehls überwacht werden. Durch die Überwachung der Weiterleitungen lässt sich feststellen, inwieweit automatische Weiterleitungen Verbindungen auf Knoten herstellen, die die Freigaben hosten, und ob eine Neuzuordnung der Daten-LIFs sinnvoll ist, um einen besseren lokalen Zugriff auf Freigaben auf dem CIFS-Server zu ermöglichen.

.Über diese Aufgabe
Das  `cifs`Objekt stellt auf der Ebene erweiterter Berechtigungen mehrere Zähler bereit, die bei der Überwachung automatischer Knotenverweise in SMB hilfreich sind:

* `node_referral_issued`
+
Anzahl der Clients, die eine Weiterleitung zum Knoten des Share-Root erhalten haben, nachdem sich der Client über eine LIF verbunden hat, die von einem anderen Knoten als dem Share-Root-Knoten gehostet wird.

* `node_referral_local`
+
Anzahl der Clients, die sich über einen LIF verbunden haben, der vom selben Knoten gehostet wird wie das Stammverzeichnis der Freigabe. Lokaler Zugriff bietet im Allgemeinen optimale Leistung.

* `node_referral_not_possible`
+
Anzahl der Clients, denen nach der Verbindung über eine LIF, die von einem anderen Knoten als dem des Share-Root gehostet wird, keine Weiterleitung zum Knoten mit dem Share-Root zugewiesen wurde. Dies ist darauf zurückzuführen, dass keine aktive Daten-LIF für den Knoten mit dem Share-Root gefunden wurde.

* `node_referral_remote`
+
Anzahl der Clients, die sich über eine LIF verbunden haben, die von einem anderen Knoten als dem Knoten, der das Stammverzeichnis der Freigabe hostet, gehostet wird. Remotezugriff kann zu einer verringerten Performance führen.



Sie können automatische Node-Referral-Statistiken auf Ihrer Storage Virtual Machine (SVM) überwachen, indem Sie Daten für einen bestimmten Zeitraum (eine Stichprobe) erfassen und anzeigen. Daten aus der Stichprobe können angezeigt werden, wenn die Datenerfassung nicht gestoppt wird. Das Stoppen der Datenerfassung ergibt eine feste Stichprobe. Wenn die Datenerfassung nicht gestoppt wird, besteht die Möglichkeit, aktualisierte Daten zu erhalten, die zum Vergleich mit früheren Abfragen verwendet werden können. Der Vergleich kann dabei helfen, Leistungstrends zu identifizieren.

[NOTE]
====
Um die mit dem  `statistics` Befehl gesammelten Informationen auszuwerten und zu nutzen, sollte die Verteilung der Clients in Ihren Umgebungen verstanden werden.

====
.Schritte
. Die Berechtigungsstufe wird auf „Erweitert“ gesetzt: `set -privilege advanced`
. Automatische Knotenweiterleitungsstatistiken werden mit dem  `statistics` Befehl angezeigt.
+
In diesem Beispiel werden automatische Node-Referral-Statistiken angezeigt, indem Daten für einen ausgewählten Zeitraum gesammelt und angezeigt werden:

+
.. Die Sammlung wird gestartet: `statistics start -object cifs -instance vs1 -sample-id sample1`
+
[listing]
----
Statistics collection is being started for Sample-id: sample1
----
.. Warten, bis die gewünschte Erfassungszeit verstrichen ist.
.. Die Sammlung anhalten: `statistics stop -sample-id sample1`
+
[listing]
----
Statistics collection is being stopped for Sample-id: sample1
----
+
Weitere Informationen zu  `statistics start` und  `statistics stop` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=statistics["ONTAP-Befehlsreferenz"^].

.. Automatische Knotenverweis-Statistiken anzeigen: `statistics show -sample-id sample1 -counter *node*`
+
[listing]
----
Object: cifs
Instance: vs1
Start-time: 2/4/2013 19:27:02
End-time: 2/4/2013 19:30:11
Cluster: cluster1

    Counter                                             Value
    ----------------------------- ---------------------------
    node_name                                          node1
    node_referral_issued                                    0
    node_referral_local                                     1
    node_referral_not_possible                              2
    node_referral_remote                                    2
    ...

    node_name                                          node2
    node_referral_issued                                    2
    node_referral_local                                     1
    node_referral_not_possible                              0
    node_referral_remote                                    2
    ...
----
+
Die Ausgabe zeigt Zähler für alle Knoten an, die an SVM vs1 teilnehmen. Zur besseren Übersicht werden im Beispiel nur Ausgabefelder bereitgestellt, die sich auf Statistiken zur automatischen Knotenzuweisung beziehen.

+
Weitere Informationen zu  `statistics show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/statistics-show.html["ONTAP-Befehlsreferenz"^].



. Zurück zur Administratorrechteebene: `set -privilege admin`


.Verwandte Informationen
* xref:display-statistics-task.adoc[Statistiken anzeigen]
* link:../performance-config/index.html["Einrichtung der Leistungsüberwachung"]

