---
permalink: smb-admin/support-branchcache-group-policy-objects-concept.html 
sidebar: sidebar 
keywords: ontap, branchcache, support, group, policy, object, gpo, centralize, management, configuration, parameter, hash, publication, support for branchcache group policy objects 
summary: 'ONTAP BranchCache bietet Unterstützung für BranchCache Gruppenrichtlinienobjekte, die eine zentrale Verwaltung bestimmter BranchCache Konfigurationsparameter ermöglichen. Es gibt zwei GPOs, die für BranchCache verwendet werden: die Hash Publication for BranchCache GPO und die Hash Version Support for BranchCache GPO.' 
---
= Informationen zur ONTAP SMB-Unterstützung für BranchCache Gruppenrichtlinienobjekte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP BranchCache bietet Unterstützung für BranchCache Gruppenrichtlinienobjekte (GPOs), die eine zentrale Verwaltung bestimmter BranchCache Konfigurationsparameter ermöglichen. Es gibt zwei GPOs, die für BranchCache verwendet werden: die Hash Publication for BranchCache GPO und die Hash Version Support for BranchCache GPO.

* *Hash-Veröffentlichung für BranchCache GPO*
+
Die Hash-Veröffentlichung für BranchCache GPO entspricht dem  `-operating-mode` Parameter. Bei GPO-Aktualisierungen wird dieser Wert auf Storage Virtual Machine (SVM)-Objekte angewendet, die sich in der Organisationseinheit (OU) befinden, auf die die Gruppenrichtlinie zutrifft.

* *Unterstützung von Hash-Versionen für BranchCache GPO*
+
Die Hash-Versionsunterstützung für BranchCache GPO entspricht dem  `-versions` Parameter. Bei GPO-Aktualisierungen wird dieser Wert auf SVM-Objekte angewendet, die sich in der Organisationseinheit befinden, auf die die Gruppenrichtlinie angewendet wird.



.Verwandte Informationen
xref:applying-group-policy-objects-concept.adoc[Informationen zur Anwendung von Gruppenrichtlinienobjekten auf SMB-Server]
