---
permalink: smb-admin/supported-versions-functionality-concept.html 
sidebar: sidebar 
keywords: server, message, block, smb, remote, file-sharing, protocol, microsoft, windows, client, server, ontap, functionality, environment, supported smb versions and functionality 
summary: 'Server Message Block (SMB) ist ein Remote-File-Sharing-Protokoll, das von Microsoft Windows Clients und Servern verwendet wird. Alle SMB-Versionen werden unterstützt. Sie sollten überprüfen, ob der ONTAP SMB-Server die in Ihrer Umgebung erforderlichen Clients und Funktionen unterstützt.' 
---
= Unterstützte ONTAP SMB-Versionen und -Funktionen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Server Message Block (SMB) ist ein Remote-File-Sharing-Protokoll, das von Microsoft Windows Clients und Servern verwendet wird. Alle SMB-Versionen werden unterstützt. Sie sollten überprüfen, ob der ONTAP SMB-Server die in Ihrer Umgebung erforderlichen Clients und Funktionen unterstützt.

Die neuesten Informationen darüber, welche SMB-Clients und Domänencontroller ONTAP unterstützen, sind unter _Interoperability Matrix Tool_ verfügbar.

SMB 2.0 und neuere Versionen sind für ONTAP SMB Server standardmäßig aktiviert und können bei Bedarf aktiviert oder deaktiviert werden. SMB 1.0 kann nach Bedarf aktiviert oder deaktiviert werden.

[NOTE]
====
Standardeinstellungen für SMB 1.0- und 2.0-Verbindungen zu Domain-Controllern hängen auch von der ONTAP-Version ab. Erfahren Sie mehr über `vserver cifs security modify` in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-security-modify.html["ONTAP-Befehlsreferenz"^]. Bei Umgebungen mit vorhandenen CIFS-Servern, auf denen SMB 1.0 ausgeführt wird, sollten Sie so schnell wie möglich auf eine höhere SMB-Version migrieren, um sich auf Sicherheits- und Compliance-Verbesserungen vorzubereiten. Genaue Informationen erhalten Sie bei Ihrem NetApp Ansprechpartner.

====
Die folgende Tabelle zeigt, welche SMB-Funktionen in jeder SMB-Version unterstützt werden. Einige SMB-Funktionen sind standardmäßig aktiviert, sodass in einigen Funktionen eine zusätzliche Konfiguration erforderlich ist.

|===
| *Diese Funktionalität:* | *Erfordert Aktivierung:* 2+| *Wird in ONTAP 9 für diese SMB-Versionen unterstützt:* 


 a| 
 a| 
 a| 
3,0
 a| 
3.1.1



 a| 
Funktionen für ältere SMB 1.0
 a| 
 a| 
X
 a| 
X



 a| 
Langlebige Griffe
 a| 
 a| 
X
 a| 
X



 a| 
Kumulierte Prozesse
 a| 
 a| 
X
 a| 
X



 a| 
Asynchroner Betrieb
 a| 
 a| 
X
 a| 
X



 a| 
Erhöhte Pufferkapazität für Lese- und Schreibvorgänge
 a| 
 a| 
X
 a| 
X



 a| 
Höhere Skalierbarkeit
 a| 
 a| 
X
 a| 
X



 a| 
SMB-Signing
 a| 
X
 a| 
X
 a| 
X



 a| 
Das Dateiformat Alternate Data Stream (ADS)
 a| 
X
 a| 
X
 a| 
X



 a| 
Große MTU (standardmäßig aktiviert ab ONTAP 9.7)
 a| 
X
 a| 
X
 a| 
X



 a| 
Lease Oplocks
 a| 
 a| 
X
 a| 
X



 a| 
Kontinuierlich verfügbare Aktien
 a| 
X
 a| 
X
 a| 
X



 a| 
Persistente Griffe
 a| 
 a| 
X
 a| 
X



 a| 
Zeuge
 a| 
 a| 
X
 a| 
X



 a| 
SMB-VERSCHLÜSSELUNG: AES-128-CCM
 a| 
X
 a| 
X
 a| 
X



 a| 
Scale-out (erforderlich durch CA-Freigaben)
 a| 
 a| 
X
 a| 
X



 a| 
Transparenter Failover
 a| 
 a| 
X
 a| 
X



 a| 
SMB-Mehrkanal (ab ONTAP 9.4)
 a| 
X
 a| 
X
 a| 
X



 a| 
Integrität vor der Authentifizierung
 a| 
 a| 
 a| 
X



 a| 
Cluster-Client-Failover v.2 (CCFv2)
 a| 
 a| 
 a| 
X



 a| 
SMB-VERSCHLÜSSELUNG: AES-128-GCM
 a| 
X
 a| 
 a| 
X

|===
.Verwandte Informationen
xref:signing-enhance-network-security-concept.adoc[Erfahren Sie mehr über die Verwendung der ONTAP-Signatur zur Verbesserung der Netzwerksicherheit]

xref:set-server-minimum-authentication-security-level-task.adoc[Festlegen der Mindestsicherheitsstufe für die Serverauthentifizierung]

xref:configure-required-encryption-concept.adoc[Konfiguration der erforderlichen SMB-Verschlüsselung auf SMB-Servern für Datentransfers über SMB]

https://mysupport.netapp.com/NOW/products/interoperability["NetApp Interoperabilität"^]
