---
permalink: smb-admin/use-cases-storage-level-access-guard-concept.html 
sidebar: sidebar 
keywords: storage-level, access, guard, additional, security, storage, level, visible, administrator, client, side, desktop, revoke, user, beneficial, use cases for using storage-level access guard 
summary: Storage-Level Access Guard bietet zusätzliche Sicherheit auf Speicherebene, die für Clients nicht sichtbar ist. Daher kann sie von keinem Benutzer oder Administrator von seinem Desktop aus aufgehoben werden. In bestimmten Anwendungsfällen ist die Möglichkeit, den Zugriff auf Speicherebene zu steuern, von Vorteil. 
---
= Anwendungsfälle für den Einsatz von Storage-Level Access Guard
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage-Level Access Guard bietet zusätzliche Sicherheit auf Speicherebene, die für Clients nicht sichtbar ist, daher kann sie weder von Benutzern noch von Administratoren von ihren Desktops aus aufgehoben werden. In bestimmten Anwendungsfällen ist die Möglichkeit, den Zugriff auf Speicherebene zu steuern, von Vorteil.

Typische Anwendungsfälle für diese Funktion umfassen die folgenden Szenarien:

* Schutz des geistigen Eigentums durch Prüfung und Kontrolle aller Benutzerzugriffe auf Speicherebene
* Storage für Finanzdienstleistungsunternehmen, einschließlich Banken und Handelsgruppen
* Regierungsdienste mit separatem Dateispeicher für einzelne Abteilungen
* Universitäten schützen alle Studentendateien

