---
permalink: smb-admin/use-cases-cli-set-file-folder-security-concept.html 
sidebar: sidebar 
keywords: apply, manage, file, folder, security, local, involvement, remote, client, significant, reduce, use cases for using the cli to set file and folder security 
summary: Da Sie die Datei- und Ordnersicherheit lokal anwenden und verwalten können, ohne dass ein Remote-Client beteiligt ist, kann die Zeit für die Massensicherheitsfestlegung bei einer großen Anzahl von Dateien oder Ordnern erheblich reduziert werden. 
---
= ONTAP Befehle zum Festlegen der SMB-Datei- und Ordnersicherheit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Da Sie die Datei- und Ordnersicherheit lokal anwenden und verwalten können, ohne dass ein Remote-Client beteiligt ist, kann die Zeit für die Massensicherheitsfestlegung bei einer großen Anzahl von Dateien oder Ordnern erheblich reduziert werden.

Die Verwendung der Befehlszeilenschnittstelle (CLI) zum Festlegen der Datei- und Ordnersicherheit kann in folgenden Anwendungsfällen von Vorteil sein:

* Speicherung von Dateien in großen Unternehmensumgebungen, wie zum Beispiel Dateispeicherung in Home-Verzeichnissen
* Migration von Daten
* Änderung der Windows-Domäne
* Standardisierung von Dateisicherheits- und Überwachungsrichtlinien für NTFS-Dateisysteme

