---
permalink: smb-admin/verify-applied-audit-policy-task.html 
sidebar: sidebar 
keywords: verify, audit, policy, confirm, file, folder, storage, virtual, machine, svm, applied, apply, security, desire, verify the applied audit policy 
summary: Sie können die Überwachungsrichtlinie überprüfen, um sicherzustellen, dass die Dateien oder Ordner auf der Storage Virtual Machine, auf die Sie die Sicherheitsrichtlinie angewendet haben, die gewünschten Überwachungssicherheitseinstellungen aufweisen. 
---
= ONTAP SMB Auditrichtlinien überprüfen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Überwachungsrichtlinie kann überprüft werden, um zu bestätigen, dass die Dateien oder Ordner auf der Storage Virtual Machine (SVM), auf die die Sicherheitsrichtlinie angewendet wurde, die gewünschten Überwachungssicherheitseinstellungen aufweisen.

.Über diese Aufgabe
Sie verwenden den  `vserver security file-directory show` Befehl, um Informationen zur Überwachungsrichtlinie anzuzeigen. Es muss der Name der SVM, die die Daten enthält, sowie der Pfad zu den Daten angegeben werden, deren Datei- oder Ordner-Überwachungsrichtlinieninformationen angezeigt werden sollen.

.Schritt
. Einstellungen für die Überwachungsrichtlinie anzeigen: `vserver security file-directory show -vserver _vserver_name_ -path _path_`


.Beispiel
Der folgende Befehl zeigt die auf den Pfad "`/corp`" in SVM vs1 angewendeten Überwachungsrichtlinieninformationen an. Auf den Pfad sind sowohl ein SUCCESS- als auch ein SUCCESS/FAIL-SACL-Eintrag angewendet:

[listing]
----
cluster::> vserver security file-directory show -vserver vs1 -path /corp

                Vserver: vs1
              File Path: /corp
         Security Style: ntfs
        Effective Style: ntfs
         DOS Attributes: 10
 DOS Attributes in Text: ----D---
Expanded Dos Attributes: -
           Unix User Id: 0
          Unix Group Id: 0
         Unix Mode Bits: 777
 Unix Mode Bits in Text: rwxrwxrwx
                   ACLs: NTFS Security Descriptor
                         Control:0x8014
                         Owner:DOMAIN\Administrator
                         Group:BUILTIN\Administrators
                         SACL - ACEs
                           ALL-DOMAIN\Administrator-0x100081-OI|CI|SA|FA
                           SUCCESSFUL-DOMAIN\user1-0x100116-OI|CI|SA
                         DACL - ACEs
                           ALLOW-BUILTIN\Administrators-0x1f01ff-OI|CI
                           ALLOW-BUILTIN\Users-0x1f01ff-OI|CI
                           ALLOW-CREATOR OWNER-0x1f01ff-OI|CI
                           ALLOW-NT AUTHORITY\SYSTEM-0x1f01ff-OI|CI
----