---
permalink: smb-admin/view-shares-mmc-task.html 
sidebar: sidebar 
keywords: information, smb, share, svm, perform, management, task, microsoft, management, console, mmc, view, share, connect, svm, view information about smb shares using the mmc 
summary: 'Sie können Informationen zu SMB-Freigaben auf Ihrer SVM anzeigen und verschiedene Managementaufgaben mithilfe der Microsoft Management Console (MMC) ausführen. Bevor Sie die Freigaben anzeigen können, müssen Sie MMC mit der SVM verbinden.' 
---
= Zeigen Sie Informationen zu SMB-Freigaben mithilfe von MMC an
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Informationen zu SMB-Freigaben auf Ihrer SVM anzeigen und verschiedene Managementaufgaben mithilfe der Microsoft Management Console (MMC) ausführen. Bevor Sie die Freigaben anzeigen können, müssen Sie MMC mit der SVM verbinden.

.Über diese Aufgabe
Sie können die folgenden Aufgaben für Shares in SVMs mithilfe des MMC ausführen:

* Freigaben anzeigen
* Anzeigen aktiver Sitzungen
* Öffnen Sie Dateien anzeigen
* Listen Sie die Liste der Sitzungen, Dateien und Baumverbindungen im System auf
* Schließen Sie offene Dateien im System
* Offene Sitzungen schließen
* Freigaben erstellen/managen


[NOTE]
====
Die von den vorhergehenden Funktionen angezeigten Ansichten sind Node-spezifisch und nicht Cluster-spezifisch. Wenn Sie die MMC verwenden, um sich mit dem Host-Namen des SMB-Servers (d. h. cifs01.Domain.local) zu verbinden, werden Sie, basierend auf der Art und Weise, wie Sie DNS eingerichtet haben, an eine einzelne LIF innerhalb Ihres Clusters weitergeleitet.

====
Die folgenden Funktionen werden in MMC für ONTAP nicht unterstützt:

* Erstellen neuer lokaler Benutzer/Gruppen
* Verwalten/Anzeigen vorhandener lokaler Benutzer/Gruppen
* Anzeigen von Ereignissen oder Performance-Protokollen
* Storage
* Services und Applikationen


In Fällen, in denen der Vorgang nicht unterstützt wird, können Sie möglicherweise Erfahrung haben `remote procedure call failed` Fehler.

https://["FAQ: Verwendung von Windows MMC mit ONTAP"]

.Schritte
. Um Computer Management MMC auf einem beliebigen Windows-Server zu öffnen, wählen Sie in der Systemsteuerung* die Option *Verwaltung* > *Computerverwaltung*.
. Wählen Sie *Aktion* > *Verbindung zu einem anderen Computer*.
+
Das Dialogfeld „Computer auswählen“ wird angezeigt.

. Geben Sie den Namen des Speichersystems ein, oder klicken Sie auf *Durchsuchen*, um das Speichersystem zu finden.
. Klicken Sie auf *OK*.
+
Der MMC stellt eine Verbindung zur SVM her.

. Klicken Sie im Navigationsbereich auf *freigegebene Ordner* > *Freigaben*.
+
Im rechten Anzeigefenster wird eine Liste der Freigaben auf der SVM angezeigt.

. Um die Freigabeigenschaften für eine Freigabe anzuzeigen, doppelklicken Sie auf die Freigabe, um das Dialogfeld *Eigenschaften* zu öffnen.
. Wenn Sie mithilfe von MMC keine Verbindung zum Speichersystem herstellen können, können Sie den Benutzer zur BUILTIN\Administrators Group oder BUILTIN\Power Users Group hinzufügen, indem Sie einen der folgenden Befehle auf dem Speichersystem verwenden:
+
[listing]
----

cifs users-and-groups local-groups add-members -vserver <vserver_name> -group-name BUILTIN\Administrators -member-names <domainuser>

cifs users-and-groups local-groups add-members -vserver <vserver_name> -group-name "BUILTIN\Power Users" -member-names <domainuser>
----

