---
permalink: smb-admin/windows-hosts-version-requirements-concept.html 
sidebar: sidebar 
keywords: ontap, branch, office, windows, host, version, requirement, configure, branchcache, ontap and windows hosts version requirements 
summary: ONTAP und Windows-Hosts in Zweigstellen müssen bestimmte Versionsanforderungen erfüllen, bevor BranchCache konfiguriert werden kann. 
---
= Versionsanforderungen für ONTAP und Windows Hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP und Windows-Hosts in Zweigstellen müssen bestimmte Versionsanforderungen erfüllen, bevor BranchCache konfiguriert werden kann.

Bevor Sie BranchCache konfigurieren, müssen Sie sicherstellen, dass die ONTAP Version auf dem Cluster und die teilnehmenden Zweigstellen-Clients SMB 2.1 oder höher unterstützen und die BranchCache Funktion unterstützen. Wenn Sie den Hosted Cache-Modus konfigurieren, müssen Sie außerdem sicherstellen, dass Sie einen unterstützten Host für den Cache-Server verwenden.

BranchCache 1 wird auf den folgenden ONTAP-Versionen und Windows-Hosts unterstützt:

* Content Server: Storage Virtual Machine (SVM) mit ONTAP
* Cache Server: Windows Server 2008 R2 oder Windows Server 2012 oder höher
* Peer oder Client: Windows 7 Enterprise, Windows 7 Ultimate, Windows 8, Windows Server 2008 R2 oder Windows Server 2012 oder höher


BranchCache 2 wird auf den folgenden ONTAP-Versionen und Windows-Hosts unterstützt:

* Content Server: SVM mit ONTAP
* Cache-Server: Windows Server 2012 oder höher
* Peer oder Client: Windows 8 oder Windows Server 2012 oder höher


Aktuelle Informationen dazu, welche Windows Clients BranchCache unterstützen, finden Sie in der Interoperabilitäts-Matrix.

http://["mysupport.netapp.com/matrix"]
