---
permalink: smb-admin/write-cache-data-loss-oplocks-concept.html 
sidebar: sidebar 
keywords: circumstance, process, exclusive, oplock, file, flush, cache, data, write, lock, relinquish, network, failure, write cache data-loss considerations when using oplocks 
summary: Unter bestimmten Umständen muss ein Prozess, der eine exklusive Oplock-Sperre für eine Datei hält, wenn ein zweiter Prozess versucht, die Datei zu öffnen, zwischengespeicherte Daten ungültig machen und Schreibvorgänge sowie Sperren leeren. Der Client muss anschließend die Oplock-Sperre und den Zugriff auf die Datei freigeben. Tritt während dieses Leervorgangs ein Netzwerkausfall auf, können zwischengespeicherte Schreibdaten verloren gehen. 
---
= Informationen zu Überlegungen zum Datenverlust im ONTAP SMB-Cache beim Einsatz von Oplocks
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unter bestimmten Umständen muss ein Prozess, der eine exklusive Oplock-Sperre für eine Datei hält, wenn ein zweiter Prozess versucht, die Datei zu öffnen, zwischengespeicherte Daten ungültig machen und Schreibvorgänge sowie Sperren leeren. Der Client muss anschließend die Oplock-Sperre und den Zugriff auf die Datei freigeben. Tritt während dieses Leervorgangs ein Netzwerkausfall auf, können zwischengespeicherte Schreibdaten verloren gehen.

* Möglichkeiten für Datenverlust
+
Jede Anwendung, die Daten im Schreibcache speichert, kann diese Daten unter den folgenden Umständen verlieren:

+
** Die Verbindung wird über SMB 1.0 hergestellt.
** Es verfügt über eine exklusive Oplock für die Datei.
** Es wird angewiesen, entweder die Oplock Sperre aufzuheben oder die Datei zu schließen.
** Beim Leeren des Schreibcaches erzeugt das Netzwerk oder das Zielsystem einen Fehler.


* Fehlerbehandlung und Schreibabschluss
+
Der Cache selbst verfügt über keine Fehlerbehandlung, die Anwendungen übernehmen diese. Wenn die Anwendung einen Schreibvorgang in den Cache ausführt, wird der Schreibvorgang immer abgeschlossen. Wenn der Cache seinerseits einen Schreibvorgang über ein Netzwerk an das Zielsystem ausführt, muss er davon ausgehen, dass der Schreibvorgang abgeschlossen ist, da die Daten andernfalls verloren gehen.


