---
permalink: svm-migrate/cancel-task.html 
sidebar: sidebar 
keywords: svm, migrate, cancel, abort 
summary: 'Wenn Sie eine SVM-Migration abbrechen müssen, bevor sie abgeschlossen ist, können Sie die verwenden `vserver migrate abort` Befehl. Sie können eine SVM-Migration nur abbrechen, wenn sich der Vorgang im Status „Pause“ oder „fehlgeschlagen“ befindet. Sie können eine SVM-Migration nicht abbrechen, wenn der Status „gestartet“ lautet und die Umstellung abgeschlossen ist. Sie können das nicht verwenden `abort` Option, wenn eine SVM-Migration durchgeführt wird.' 
---
= SVM-Migration abbrechen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie eine SVM-Migration abbrechen müssen, bevor sie abgeschlossen ist, können Sie die verwenden `vserver migrate abort` Befehl. Sie können eine SVM-Migration nur abbrechen, wenn sich der Vorgang im Status „Pause“ oder „fehlgeschlagen“ befindet. Sie können eine SVM-Migration nicht abbrechen, wenn der Status „gestartet“ lautet und die Umstellung abgeschlossen ist. Sie können das nicht verwenden `abort` Option, wenn eine SVM-Migration durchgeführt wird.

.Schritte
. Prüfen Sie den Migrationsstatus:
+
`dest_cluster> vserver migrate show -vserver <vserver name>`

. Abbrechen der Migration:
+
`dest_cluster> vserver migrate abort -vserver <vserver name>`

. Überprüfen Sie den Status des Abbruchtvorgangs:
+
`dest_cluster> vserver migrate show`

+
Der Migrationsstatus zeigt das Migrieren-Abbruch, während der Abbruch läuft. Nach Abschluss des Vorgangs wird im Migrationsstatus nichts angezeigt.


