---
permalink: mediator/download-install-pkg-task.html 
sidebar: sidebar 
keywords: mediator, new, release, update, install, download, package 
summary: Das Mediator Installationspaket wird als Teil des Installationsprozesses heruntergeladen. 
---
= Das Installationspaket für ONTAP Mediator herunterladen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Laden Sie das ONTAP Mediator Installationspaket herunter und installieren Sie es.

.Schritte
. Das ONTAP Mediator Installationspaket steht auf der ONTAP Mediator Downloadseite zum Herunterladen bereit.
+
https://mysupport.netapp.com/site/products/all/details/ontap-mediator/downloads-tab["ONTAP Mediator Downloadseite"^]

. Platzieren Sie das Mediator-Installationspaket im aktuellen Arbeitsverzeichnis:
+
[listing]
----
[root@sdot-r730-0003a-d6 ~]# ls ontap-mediator-1.12.1.tgz
----
+
[listing]
----
ontap-mediator-1.12.1.tgz
----
+

NOTE: Für ONTAP Mediator Versionen 1.4 und früher heißt das Installationsprogramm  `ontap-mediator`.

+
Falls Ihr System keinen Internetzugang hat, muss das Installationsprogramm auf die erforderlichen Pakete zugreifen können.

. Verschieben Sie das Mediator Installationspaket gegebenenfalls in das Installationsverzeichnis.
. Das Installationspaket entpacken:
+
`tar xvfz ontap-mediator-1.12.1.tgz`

+
[listing]
----
ontap-mediator-1.12.1/
ontap-mediator-1.12.1/csc-prod-ONTAP-Mediator.pem
ontap-mediator-1.12.1/csc-prod-chain-ONTAP-Mediator.pem
ontap-mediator-1.12.1/tsa-prod-ONTAP-Mediator.pem
ontap-mediator-1.12.1/tsa-prod-chain-ONTAP-Mediator.pem
ontap-mediator-1.12.1/ONTAP-Mediator-production.pub
ontap-mediator-1.12.1/ontap-mediator-1.12.1
ontap-mediator-1.12.1/ontap-mediator-1.12.1.sig.tsr
ontap-mediator-1.12.1/ontap-mediator-1.12.1.tsr
ontap-mediator-1.12.1/ontap-mediator-1.12.1.sig
----

