---
permalink: mediator/download-install-pkg-task.html 
sidebar: sidebar 
keywords: mediator, new, release, update, install, download, package 
summary: Laden Sie das Mediator-Installationspaket im Rahmen des Installationsprozesses herunter. 
---
= Laden Sie das Installationspaket für ONTAP Mediator herunter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Laden Sie im Rahmen des Installationsvorgangs das ONTAP Mediator-Installationspaket herunter.

.Schritte
. Laden Sie das ONTAP Mediator-Installationspaket von der ONTAP Mediator-Downloadseite herunter.
+
https://mysupport.netapp.com/site/products/all/details/ontap-mediator/downloads-tab["Download-Seite für ONTAP Mediator"^]

. Vergewissern Sie sich, dass sich das Mediator-Installationspaket im aktuellen Arbeitsverzeichnis befindet:
+
[listing]
----
[root@sdot-r730-0003a-d6 ~]# ls ontap-mediator-1.9.0.tgz
----
+
[listing]
----
ontap-mediator-1.9.0.tgz
----
+

NOTE: Für ONTAP Mediator Versionen 1.4 und früher wird der Installer benannt `ontap-mediator`.

+
Wenn Sie sich an einem Ort ohne Zugang zum Internet befinden, müssen Sie sicherstellen, dass der Installer Zugriff auf die erforderlichen Pakete hat.

. Verschieben Sie bei Bedarf das Mediator-Installationspaket aus dem Download-Verzeichnis in das Installationsverzeichnis auf dem Linux Mediator-Host.
. Entpacken Sie das Installationspaket:
+
`tar xvfz ontap-mediator-1.9.0.tgz`

+
[listing]
----
ontap-mediator-1.9.0/
ontap-mediator-1.9.0/csc-prod-ONTAP-Mediator.pem
ontap-mediator-1.9.0/csc-prod-chain-ONTAP-Mediator.pem
ontap-mediator-1.9.0/tsa-prod-ONTAP-Mediator.pem
ontap-mediator-1.9.0/tsa-prod-chain-ONTAP-Mediator.pem
ontap-mediator-1.9.0/ONTAP-Mediator-production.pub
ontap-mediator-1.9.0/ontap-mediator-1.9.0
ontap-mediator-1.9.0/ontap-mediator-1.9.0.sig.tsr
ontap-mediator-1.9.0/ontap-mediator-1.9.0.tsr
ontap-mediator-1.9.0/ontap-mediator-1.9.0.sig
----

