---
permalink: mediator/index.html 
sidebar: sidebar 
keywords: ontap mediator service, install requirements, mediator requirements 
summary: Um den ONTAP Mediator-Dienst zu installieren, müssen Sie sicherstellen, dass alle Voraussetzungen erfüllt sind, das Installationspaket abrufen und das Installationsprogramm auf dem Host ausführen. 
---
= Bereiten Sie die Installation oder das Upgrade des ONTAP Mediatordienstes vor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um den ONTAP Mediator-Dienst zu installieren, müssen Sie sicherstellen, dass alle Voraussetzungen erfüllt sind, das Installationspaket abrufen und das Installationsprogramm auf dem Host ausführen. Dieses Verfahren wird für eine Installation oder ein Upgrade einer vorhandenen Installation verwendet.

.Über diese Aufgabe
* Ab ONTAP 9.7 können Sie eine beliebige Version des ONTAP Mediators verwenden, um eine MetroCluster IP-Konfiguration zu überwachen.
* Ab ONTAP 9.8 können Sie jede Version von ONTAP Mediator verwenden, um eine aktive SnapMirror Sync Beziehung zu überwachen.


.Bevor Sie beginnen
Sie müssen die folgenden Voraussetzungen erfüllen.

[cols="30,70"]
|===


| Version des ONTAP Mediators | Unterstützte Linux-Versionen 


 a| 
1.7
 a| 
* Red Hat Enterprise Linux: 8.5, 8.6, 8.7, 8.8, 8.9 9.0, 9.1, 9.2 und 9.3
* Rocky Linux 8 und 9




 a| 
1.6
 a| 
* Red Hat Enterprise Linux: 8.4, 8.5, 8.6, 8.7, 8.8 9.0, 9.1, 9.2
* Rocky Linux 8 und 9




 a| 
1.5
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.1 8.2, 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.4
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.1 8.2, 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.3
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.1 8.2, 8.3
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.2
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 8.1
* CentOS: 7.6, 7.7, 7.8


|===

NOTE: Die Kernel-Version muss mit der Betriebssystemversion übereinstimmen.

* 64-Bit physische Installation oder virtuelle Maschine
* 8 GB RAM
* 1 GB Festplattenspeicher (wird für die Installation von Anwendungen, Serverprotokollen und die Datenbank verwendet)
* Benutzer: Root-Zugriff


Alle Bibliothekspakete mit Ausnahme des Kernels können sicher aktualisiert werden, erfordern jedoch möglicherweise einen Neustart, um in der ONTAP Mediator-Anwendung wirksam zu werden. Wenn ein Neustart erforderlich ist, wird ein Service-Fenster empfohlen.

Wenn Sie den installieren `yum-utils` Die Sie verwenden können `needs-restarting` Befehl.

Der Kernelkern kann aktualisiert werden, wenn er auf eine Version aktualisiert wird, die noch von der ONTAP Mediator Versionsmatrix unterstützt wird. Ein Neustart ist obligatorisch, daher ist ein Service-Fenster erforderlich.

Das SCST-Kernelmodul muss vor dem Neustart deinstalliert und nach dem Neustart neu installiert werden.


NOTE: Die Aktualisierung auf einen Kernel, der über die unterstützte Betriebssystemversion für die spezifische ONTAP Mediator-Version hinausgeht, wird nicht unterstützt. (Dies deutet wahrscheinlich darauf hin, dass das getestete SCST-Modul nicht kompiliert).



== Registrieren Sie einen Sicherheitsschlüssel, wenn UEFI Secure Boot aktiviert ist

Wenn UEFI Secure Boot aktiviert ist, müssen Sie zur Installation von ONTAP Mediator einen Sicherheitsschlüssel registrieren, bevor der ONTAP Mediator Dienst gestartet werden kann. So stellen Sie fest, ob das System UEFI-aktiviert und Secure Boot eingeschaltet ist:

.Schritte
. Wenn mokutil nicht installiert ist, führen Sie den folgenden Befehl aus:
+
`yum install mokutil`

. Führen Sie den folgenden Befehl aus, um zu ermitteln, ob UEFI Secure Boot auf Ihrem System aktiviert ist:
+
`mokutil --sb-state`

+
Die Ergebnisse zeigen, ob UEFI Secure Boot auf diesem System aktiviert ist.

+

NOTE: ONTAP Mediator 1.2.0 und frühere Versionen unterstützen diesen Modus nicht.





== Deaktivieren Sie UEFI Secure Boot

Sie können auch den sicheren UEFI-Start deaktivieren, bevor Sie ONTAP Mediator installieren.

.Schritte
. Deaktivieren Sie in den BIOS-Einstellungen des physischen Computers die Option „UEFI Secure Boot“.
. Deaktivieren Sie in den VMware-Einstellungen für die VM die Option „Sicherer Start“ für vSphere 6.x oder die Option „Sicherer Start“ für vSphere 7.x

