---
permalink: mediator/mediator-overview-concept.html 
sidebar: sidebar 
keywords: ontap mediator, install requirements, mediator requirements 
summary: ONTAP Mediator bietet verschiedene Funktionen für ONTAP-Funktionen. 
---
= Erfahren Sie mehr über ONTAP Mediator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP Mediator bietet mehrere Funktionen für ONTAP-Features:

* Persistenter Speicher mit Fencing für HA-Metadaten
* Dient als Ping-Proxy für Controller-Lebendigkeit.
* Bietet synchrone Funktionen für die Integritätsabfrage von Nodes zur Unterstützung der Quorumbestimmung.


ONTAP Mediator bietet zwei zusätzliche systemctl-Dienste:

* *`ontap_mediator.service`*
+
Wartet den REST-API-Server zur Verwaltung der ONTAP-Beziehungen.

* *`mediator-scst.service`*
+
Steuert das Starten und Herunterfahren des iSCSI-Moduls (SCST).





== Für den Systemadministrator bereitgestellte Tools

Für den Systemadministrator bereitgestellte Tools:

* *`/usr/local/bin/mediator_change_password`*
+
Legt ein neues API-Passwort fest, wenn der aktuelle API-Benutzername und das aktuelle Passwort angegeben werden.

* *`/usr/local/bin/mediator_change_user`*
+
Legt einen neuen API-Benutzernamen fest, wenn der aktuelle API-Benutzername und das aktuelle Passwort angegeben werden.

* *`/usr/local/bin/mediator_generate_support_bundle`*
+
Generiert eine lokale tgz-Datei mit allen nützlichen Support-Informationen, die für die Kommunikation mit dem NetApp Kunden-Support benötigt werden. Dazu gehören Anwendungskonfiguration, Protokolle und einige Systeminformationen. Die Bundles werden auf der lokalen Festplatte generiert und können bei Bedarf manuell übertragen werden. Speicherort: /Opt/netapp/Data/Support_Bundles/

* *`/usr/local/bin/uninstall_ontap_mediator`*
+
Entfernt das Paket ONTAP Mediator und das SCST-Kernelmodul. Dies schließt sämtliche Konfigurations-, Protokoll- und Mailbox-Daten ein.

* *`/usr/local/bin/mediator_unlock_user`*
+
Gibt eine Sperre für das API-Benutzerkonto frei, wenn das Limit für Authentifizierungsversuche erreicht wurde. Diese Funktion wird verwendet, um die Herleitung von Brute Force-Passwörtern zu verhindern. Der Benutzer wird aufgefordert, den richtigen Benutzernamen und das richtige Passwort einzugeben.

* *`/usr/local/bin/mediator_add_user`*
+
(Nur Support) wird verwendet, um den API-Benutzer bei der Installation hinzuzufügen.





== Besondere Hinweise

ONTAP Mediator setzt bei der iSCSI-Bereitstellung auf SCST (siehe http://scst.sourceforge.net/index.html[]). Dieses Paket ist ein Kernelmodul, das während der Installation speziell für den Kernel kompiliert wird. Für Aktualisierungen des Kernels muss SCST möglicherweise neu installiert werden. Alternativ können Sie ONTAP Mediator deinstallieren und anschließend erneut installieren und anschließend die ONTAP-Beziehung neu konfigurieren.


NOTE: Alle Aktualisierungen des Server-OS-Kernels sollten mit einem Wartungsfenster in ONTAP koordiniert werden.
