---
permalink: mediator/upgrade-host-os-mediator-task.html 
sidebar: sidebar 
keywords: mediator, new, release, update, install, 
summary: Im Rahmen des Installationsprozesses aktualisieren Sie das Host-Betriebssystem und anschließend den ONTAP Mediator. 
---
= Aktualisieren Sie das Host-Betriebssystem und anschließend den ONTAP Mediator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um das Host-Betriebssystem für ONTAP Mediator auf eine neuere Version zu aktualisieren, müssen Sie ONTAP Mediator zuerst deinstallieren.

.Bevor Sie beginnen
Die Best Practices für die Installation von Red hat Enterprise Linux oder Rocky Linux und den zugehörigen Repositorys auf Ihrem System sind unten aufgeführt. Eine andere Konfiguration oder Installation von Systemen erfordert möglicherweise zusätzliche Schritte.

* Sie müssen Red hat Enterprise Linux oder Rocky Linux gemäß den Best Practices von Red hat installieren. Da die CentOS 8.x-Versionen Unterstützung zum Ende der Lebensdauer bieten, werden kompatible Versionen von CentOS 8.x nicht empfohlen.
* Bei der Installation des ONTAP Mediator-Dienstes auf Red hat Enterprise Linux oder Rocky Linux muss das System Zugriff auf das entsprechende Repository haben, damit das Installationsprogramm auf alle erforderlichen Softwareabhängigkeiten zugreifen und diese installieren kann.
* Damit der yum-Installer nach abhängiger Software in den Red hat Enterprise Linux-Repositorys sucht, müssen Sie das System während der Red hat Enterprise Linux-Installation oder danach mit einem gültigen Red hat-Abonnement registriert haben.
+
Informationen zum Red hat Subscription Manager finden Sie in der Red hat Dokumentation.

* Die folgenden Ports müssen nicht verwendet und für den Mediator verfügbar sein:
+
** 31784
** 3260


* Wenn Sie eine Firewall eines Drittanbieters verwenden, lesen Sie link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_mediator_requirements.html#firewall-requirements-for-ontap-mediator["Firewall-Anforderungen für ONTAP Mediator"^]
* Wenn sich der Linux-Host an einem Standort ohne Zugriff auf das Internet befindet, müssen Sie sicherstellen, dass die erforderlichen Pakete in einem lokalen Repository verfügbar sind.
+
Wenn Sie das Link Aggregation Control Protocol (LACP) in einer Linux-Umgebung verwenden, müssen Sie den Kernel korrekt konfigurieren und sicherstellen, dass der `sysctl net.ipv4.conf.all.arp_ignore` Ist auf „2“ eingestellt.



.Was Sie benötigen
Folgende Pakete werden vom ONTAP Mediator Service benötigt:

[cols="34,33,33"]
|===


| Alle RHEL/CentOS Versionen | Zusätzliche Pakete für RHEL 8.x / Rocky Linux 8 | Zusätzliche Pakete für RHEL 9.x / Rocky Linux 9 


 a| 
* openssl
* openssl-devel
* Kernel-devel-€ (uname -r)
* gcc
* Make
* Libselinux-utils
* Patch
* Bzip2
* perl-Data-Dumper
* perl-ExtUtils-MakeuMaker
* Efibootmgr
* Mokutil

 a| 
* python3-Pip
* Elfutils-libelf-devel
* Politicoreutils-Python-utils
* Redhat-lsb-Core
* Python39
* Python39-devel

 a| 
* python3-Pip
* Elfutils-libelf-devel
* Politicoreutils-Python-utils
* python3
* python3-devel


|===
Das Mediator-Installationspaket ist eine selbst extrahierende komprimierte tar-Datei, die Folgendes enthält:

* Eine RPM-Datei, die alle Abhängigkeiten enthält, die nicht aus dem Repository des unterstützten Release abgerufen werden können.
* Ein Installationsskript.


Eine gültige SSL-Zertifizierung wird empfohlen.

.Über diese Aufgabe
Wenn Sie das Host-Betriebssystem für ONTAP Mediator mit dem Leapp-Upgrade-Tool auf eine neuere Hauptversion (z. B. von 7.x auf 8.x) aktualisieren, Sie müssen ONTAP Mediator deinstallieren, da das Tool versucht, neue Versionen aller RPMs zu erkennen, die in den Repositories installiert sind, die beim System registriert sind.

Da eine rpm-Datei als Teil des Installationsprogramms für ONTAP Mediator installiert wurde, wird sie in diese Suche aufgenommen. Da diese rpm-Datei jedoch als Teil des Installers entpackt und nicht von einem registrierten Repository heruntergeladen wurde, kann kein Upgrade gefunden werden. In diesem Fall deinstalliert das Leapp-Upgrade-Tool das Paket.

Um die Protokolldateien zu erhalten, die zur Einstufung von Support-Fällen verwendet werden, sollten Sie die Dateien vor einem Betriebssystem-Upgrade sichern und nach einer Neuinstallation des ONTAP Mediator-Pakets wiederherstellen. Da der ONTAP Mediator neu installiert wird, müssen alle ONTAP-Cluster, die mit ihm verbunden sind, nach der neuen Installation erneut verbunden werden.


NOTE: Die folgenden Schritte sollten in der angegebenen Reihenfolge ausgeführt werden. Unmittelbar nach der Neuinstallation von ONTAP Mediator sollten Sie den ontap_Mediator Service beenden, die Protokolldateien ersetzen und den Service neu starten. Dadurch wird sichergestellt, dass keine Protokolle verloren gehen.

.Schritte
. Sichern Sie die Protokolldateien.
+
....
[rootmediator-host ~]# tar -czf ontap_mediator_file_backup.tgz -C /opt/netapp/lib/ontap_mediator ./log ./ontap_mediator/server_config/ontap_mediator.user_config.yaml
[rootmediator-host ~]# tar -tf ontap_mediator_file_backup.tgz
./log/
./log/ontap_mediator.log
./log/scstadmin.log
./log/ontap_mediator_stdout.log
./log/ontap_mediator_requests.log
./log/install_20230419134611.log
./log/scst.log
./log/ontap_mediator_syslog.log
./ontap_mediator/server_config/ontap_mediator.user_config.yaml
[rootmediator-host ~]#
....
. Upgrade mit leapp-Upgrade-Tool durchführen.
+
....
[rootmediator-host ~]# leapp preupgrade --target 8.4
  ..<snip upgrade checks>..
  ..<fix issues found>..
[rootmediator-host ~]# leapp upgrade --target 8.4
  ..<snip upgrade>..
[rootmediator-host ~]# cat /etc/os-release | head -2
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
[rootmediator-host ~]#
....
. Installieren Sie ONTAP Mediator neu.
+

NOTE: Führen Sie die restlichen Schritte unmittelbar nach der Neuinstallation von ONTAP Mediator aus, um einen Verlust von Protokolldateien zu verhindern.

+
....
[rootmediator-host ~]# ontap-mediator-1.6.0/ontap-mediator-1.6.0

ONTAP Mediator: Self Extracting Installer

  ..<snip installation>..
[rootmediator-host ~]#
....
. Stoppen Sie den ontap_Mediator Service.
+
....
[rootmediator-host ~]# systemctl stop ontap_mediator
[rootmediator-host ~]#
....
. Ersetzen Sie die Protokolldateien.
+
....
[rootmediator-host ~]# tar -xf ontap_mediator_log_backup.tgz -C /opt/netapp/lib/ontap_mediator
[rootmediator-host ~]#
....
. starten Sie den ontap_Mediator Service.
+
....
[rootmediator-host ~]# systemctl start ontap_mediator
[rootmediator-host ~]#
....
. Schließen Sie alle ONTAP-Cluster wieder an den aktualisierten ONTAP Mediator an
+
.Verfahren für MetroCluster über IP
[%collapsible]
====
....
siteA::> metrocluster configuration-settings mediator show
Mediator IP     Port    Node                    Configuration Connection
                                                Status        Status
--------------- ------- ----------------------- ------------- -----------
172.31.40.122
                31784   siteA-node2             true          false
                        siteA-node1             true          false
                        siteB-node2             true          false
                        siteB-node2             true          false
siteA::> metrocluster configuration-settings mediator remove
Removing the mediator and disabling Automatic Unplanned Switchover. It may take a few minutes to complete.
Please enter the username for the mediator: mediatoradmin
Please enter the password for the mediator:
Confirm the mediator password:
Automatic Unplanned Switchover is disabled for all nodes...
Removing mediator mailboxes...
Successfully removed the mediator.

siteA::> metrocluster configuration-settings mediator add -mediator-address 172.31.40.122
Adding the mediator and enabling Automatic Unplanned Switchover. It may take a few minutes to complete.
Please enter the username for the mediator: mediatoradmin
Please enter the password for the mediator:
Confirm the mediator password:
Successfully added the mediator.

siteA::> metrocluster configuration-settings mediator show
Mediator IP     Port    Node                    Configuration Connection
                                                Status        Status
--------------- ------- ----------------------- ------------- -----------
172.31.40.122
                31784   siteA-node2             true          true
                        siteA-node1             true          true
                        siteB-node2             true          true
                        siteB-node2             true          true
siteA::>
....
====


.Verfahren für SnapMirror Active Sync
[%collapsible]
====
Wenn Sie für SnapMirror Active Sync das TLS-Zertifikat außerhalb des /opt/netapp-Verzeichnisses installiert haben, müssen Sie es nicht erneut installieren. Wenn Sie das automatisch generierte, selbstsignierte Standardzertifikat verwenden oder Ihr benutzerdefiniertes Zertifikat im Verzeichnis /opt/netapp ablegen, sollten Sie es sichern und wiederherstellen.

....
peer1::> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
172.31.49.237    peer2            unreachable       true

peer1::> snapmirror mediator remove -mediator-address 172.31.49.237 -peer-cluster peer2

Info: [Job 39] 'mediator remove' job queued

peer1::> job show -id 39
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
39     mediator remove      peer1      peer1-node1    Success
     Description: Removing entry in mediator

peer1::> security certificate show -common-name ONTAPMediatorCA
Vserver    Serial Number   Certificate Name                       Type
---------- --------------- -------------------------------------- ------------
peer1
        4A790360081F41145E14C5D7CE721DC6C210007F
                        ONTAPMediatorCA                        server-ca
    Certificate Authority: ONTAP Mediator CA
        Expiration Date: Mon Apr 17 10:27:54 2073

peer1::> security certificate delete -common-name ONTAPMediatorCA *
1 entry was deleted.

 peer1::> security certificate install -type server-ca -vserver peer1

Please enter Certificate: Press <Enter> when done
  ..<snip ONTAP Mediator CA public key>..

You should keep a copy of the CA-signed digital certificate for future reference.

The installed certificate's CA and serial number for reference:
CA: ONTAP Mediator CA
serial: 44786524464C5113D5EC966779D3002135EA4254

The certificate's generated name for reference: ONTAPMediatorCA

peer2::> security certificate delete -common-name ONTAPMediatorCA *
1 entry was deleted.

peer2::> security certificate install -type server-ca -vserver peer2

 Please enter Certificate: Press <Enter> when done
..<snip ONTAP Mediator CA public key>..


You should keep a copy of the CA-signed digital certificate for future reference.

The installed certificate's CA and serial number for reference:
CA: ONTAP Mediator CA
serial: 44786524464C5113D5EC966779D3002135EA4254

The certificate's generated name for reference: ONTAPMediatorCA

peer1::> snapmirror mediator add -mediator-address 172.31.49.237 -peer-cluster peer2 -username mediatoradmin

Notice: Enter the mediator password.

Enter the password:
Enter the password again:

Info: [Job: 43] 'mediator add' job queued

peer1::> job show -id 43
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
43     mediator add         peer1      peer1-node2    Success
    Description: Creating a mediator entry

peer1::> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
172.31.49.237    peer2            connected         true

peer1::>

....
====