---
sidebar: sidebar 
permalink: flexcache-hot-spot/flexcache-hotspot-remediation-overview.html 
keywords: hotspot, FlexCache, HDFA, problem, solution, ONTAP 
summary: Informationen zur Behebung von Hotspotting, einem häufigen Problem bei vielen Hochleistungs-Workloads wie Animationsrendering oder EDA, mit FlexCache. 
---
= Behebung von Hotspots in Hochleistungsrechen-Workloads mit ONTAP FlexCache Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein häufiges Problem bei vielen Hochleistungs-Compute-Workloads, wie Animationsrendering oder EDA, ist Hotspotting. Hotspotting ist eine Situation, in der ein bestimmter Teil des Clusters oder Netzwerks im Vergleich zu anderen Bereichen eine deutlich höhere Auslastung erfährt, was zu Leistungsengpässen und einer geringeren Gesamteffizienz führt, da sich der Datenverkehr an diesem Ort konzentriert. Beispielsweise ist eine Datei oder sind mehrere Dateien für den laufenden Job stark nachgefragt, was zu einem Engpass an der CPU führt, die die Anfragen (über eine Volume-Affinität) zu dieser Datei bedient. FlexCache kann helfen, diesen Engpass zu verringern, muss jedoch korrekt eingerichtet werden.

Diese Dokumentation erläutert, wie FlexCache zur Behebung von Hotspotting eingerichtet wird.


NOTE: Ab Juli 2024 wurden Inhalte aus zuvor als PDFs veröffentlichten technischen Berichten in die ONTAP Produktdokumentation integriert. Diese Inhalte des technischen Berichts zur Hotspot-Behebung in ONTAP sind zum Zeitpunkt der Veröffentlichung neu, ein früheres Format wurde nie erstellt.



[[key-concepts]]
== Schlüsselkonzepte

Bei der Planung der Hotspot-Behebung ist es wichtig, diese grundlegenden Konzepte zu verstehen.

* *High-Density FlexCache (HDF)*: Ein FlexCache, der so komprimiert ist, dass er sich über so wenige Knoten wie die Cache-Kapazitätsanforderungen erlauben, erstreckt.
* *HDF Array (HDFA)*: Eine Gruppe von HDFs, die Caches desselben Ursprungs sind, verteilt über den Cluster
* *Inter-SVM HDFA*: Ein HDF vom HDFA pro Server-Storage Virtual Machine (SVM)
* *Intra-SVM HDFA*: Alle HDFs im HDFA in einer SVM
* *Ost-West-Verkehr*: Cluster-Backend-Verkehr, der durch indirekten Datenzugriff generiert wird


.Was kommt als Nächstes
* link:flexcache-hotspot-remediation-architecture.html["Erfahren Sie, wie mit hochdichter FlexCache Architektur Hotspotting behoben werden kann"]
* link:flexcache-hotspot-remediation-hdfa-examples.html["Über die FlexCache Arraydichte entscheiden"]
* link:flexcache-hotspot-remediation-intra-inter-svm-hdfa.html["Bestimmen Sie die Dichte Ihrer HDFs und entscheiden Sie, ob auf die HDFs über NFS mit Inter-SVM-HDFAs und Intra-SVM-HDFAs zugegriffen wird."]
* link:flexcache-hotspot-remediation-ontap-config.html["HDFA und die Daten-LIFs so konfigurieren, dass die Vorteile der Nutzung von Intracluster-Caching mit ONTAP Konfiguration realisiert werden."]
* link:flexcache-hotspot-remediation-client-config.html["Informationen zur Konfiguration von Clients zur Verteilung von ONTAP NAS-Verbindungen mit der Clientkonfiguration"]

