---
sidebar: sidebar 
permalink: task_metrocluster_ANDU_upgrade.html 
keywords: metrocluster, upgrade, update, ONTAP, cluster, nodes, mcc, ANDU, automated, automatic, non-disruptive 
summary: Aktualisieren Sie die Cluster in einer MetroCluster Konfiguration auf eine neue Version von ONTAP, während der Storage-Service online bleibt. 
---
= Aktualisierung von ONTAP auf MetroCluster Clustern
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Dieses Thema bietet einen allgemeinen Überblick über das Verfahren zum Upgrade eines ONTAP Clusters von ONTAP 9.7 oder höher auf eine neuere Version von ONTAP 9 mithilfe der System Manager Schnittstelle.

Wenn Sie Informationen zu einem anderen ONTAP Cluster-Upgrade-Szenario benötigen, gehen Sie weiter link:./upgrade/index.html["Hier"].

Mit System Manager können Sie beide Cluster einer MetroCluster Konfiguration auf eine neuere Version von ONTAP aufrüsten. Während des Upgrades bleibt der Storage-Service online.

.Bevor Sie beginnen
* Laden Sie das ONTAP-Image über ein lokales Laufwerk oder einen HTTP-Server auf beiden Clustern der MetroCluster-Konfiguration hoch.


.Schritte
. Melden Sie sich bei System Manager an.
. Wählen Sie *Cluster > Aktualisieren*.
+
Im Fenster *ONTAP-Aktualisierung* wird eine Liste der Bilder angezeigt, die zum Hochladen verfügbar sind.

. Bewegen Sie den Mauszeiger über einen beliebigen Bildnamen, den Sie hochladen möchten _NOT_ und klicken Sie auf das Papierkorb-Symbol.
. Wählen Sie das Optionsfeld neben dem Bildnamen, den Sie aktualisieren möchten, und klicken Sie auf *Aktualisieren*.
. Warten Sie, bis das System die Bilder überprüft.
+
Wenn die Images erfolgreich validiert wurden, beginnt der Aktualisierungsvorgang, eine neue ONTAP-Version auf beiden Clustern zu installieren.

+
Sie können jederzeit auf *Pause* klicken, um den Aktualisierungsprozess anzuhalten.

. Klicken Sie nach Abschluss des Aktualisierungsvorgangs auf *Relaunch System Manager*.

