---
permalink: data-protection/autodelete-snapshot-copies-task.html 
sidebar: sidebar 
keywords: autodelete, snapshot, copies 
summary: Mit dem Befehl „Volume Snapshot Autodelete modify“ können Sie Snapshot-Kopien automatisch löschen, wenn die Snapshot-Reserve überschritten wird. Standardmäßig werden die ältesten Snapshot Kopien zuerst gelöscht. 
---
= Automatisches Löschen von Snapshot Kopien mit ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den `volume snapshot autodelete modify` Befehl verwenden, um das automatische Löschen von Snapshot Kopien zu starten, wenn die Snapshot Reserve überschritten wird. Standardmäßig werden die ältesten Snapshot Kopien zuerst gelöscht.

.Über diese Aufgabe
LUN- und Dateiklone werden gelöscht, wenn keine weiteren Snapshot Kopien gelöscht werden müssen.

.Schritt
. Automatisches Löschen von Snapshot-Kopien:
+
`volume snapshot autodelete modify -vserver _SVM_ -volume _volume_ -enabled true|false -trigger volume|snap_reserve`

+
Erfahren Sie mehr über `volume snapshot autodelete modify` in der link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-autodelete-modify.html["ONTAP-Befehlsreferenz"^].

+
Im folgenden Beispiel werden Snapshot Kopien automatisch gelöscht `vol1`, wenn die Snapshot Kopie-Reserve erschöpft ist:

+
[listing]
----
cluster1::> volume snapshot autodelete modify -vserver vs0 -volume vol1 -enabled true -trigger snap_reserve
----

