---
sidebar: sidebar 
permalink: data-protection/cloud-backup-using-cbs-task.html 
keywords: cloud, data, backup, back up, storage, volume, lun, connector, secret key, access key, bluexp back and recovery service, Cloud Backup service, CBS, restore data, protect volumes, ipspace, storagegrid, storage grid, archive, archival, archiving, cost, calculator, glacier, deep archive 
summary: Ab ONTAP 9.19.1 unterstützt System Manager die Datensicherung in der Cloud mit dem NetApp Backup and Recovery Service nicht mehr. Stattdessen müssen Sie die NetApp Console verwenden, um den NetApp Backup and Recovery Service zu konfigurieren und eine SnapMirror Beziehung zu einem Cloud-Ziel herzustellen. 
---
= Daten mit NetApp Backup and Recovery sichern
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.19.1 unterstützt System Manager die Datensicherung in der Cloud mit dem NetApp Backup and Recovery Service nicht mehr. Stattdessen müssen Sie die NetApp Console verwenden, um den NetApp Backup and Recovery Service zu konfigurieren und eine SnapMirror Beziehung zu einem Cloud-Ziel herzustellen.

Backup and Recovery unterstützt FlexVol Read-Write-Volumes und Data-Protection-Volumes (DP-Volumes). Ab ONTAP 9.12.1 unterstützt Backup and Recovery FlexGroup Volumes und SnapLock Volumes.

Weitere Informationen zu link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["NetApp Backup and Recovery"^].

.Bevor Sie beginnen
Sie sollten die folgenden Verfahren durchführen, um ein Konto in der NetApp Console einzurichten. Für das Dienstkonto ist die Rolle „Account Admin“ zu erstellen.

. link:https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html["Ein Konto in der NetApp Console erstellen"^].
. link:https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html["Einen Console-Agenten in der NetApp Console erstellen"^] mit einem der folgenden Cloud-Anbieter:
+
** Microsoft Azure
** Amazon Web Services (AWS)
** Google Cloud Platform (GCP)
** StorageGRID (ONTAP 9.10.1)
+

NOTE: Ab ONTAP 9.10.1 kann StorageGRID als Cloud-Backup-Anbieter ausgewählt werden, jedoch nur, wenn die NetApp Console lokal bereitgestellt ist. Der Console-Agent muss lokal installiert und über die NetApp Console Software-as-a-Service (SaaS) Anwendung verfügbar sein.



. link:https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["NetApp Backup and Recovery in der NetApp Console abonnieren"^] (erfordert die entsprechende Lizenz).
. link:https://docs.netapp.com/us-en/console-setup-admin/concept-identity-and-access-management.html["Einen Zugriffsschlüssel und einen geheimen Schlüssel mithilfe der NetApp Console generieren"^].




[[use-netapp-console-and-netapp-backup-and-recovery-to-manage-ontap-backups]]
== Verwenden Sie NetApp Console und NetApp Backup and Recovery, um ONTAP-Backups zu verwalten.

Ab ONTAP 9.19.1 unterstützt System Manager NetApp Backup and Recovery nicht mehr. Siehe link:https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-backup-manage.html["Verwalten Sie Backups für Ihre ONTAP-Systeme mit NetApp Backup and Recovery"^] für weitere Informationen zur Verwendung von NetApp Backup and Recovery mit NetApp Console.



[[restore-data-from-backup-files]]
== Daten aus Sicherungsdateien wiederherstellen

Sie können Backup-Management-Vorgänge wie das Wiederherstellen von Daten, das Aktualisieren von Beziehungen und das Löschen von Beziehungen nur bei Verwendung der NetApp Console durchführen. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-backup-manage.html["Wiederherstellen von Daten aus Sicherungsdateien"^].
