---
permalink: data-protection/configure-destination-volume-data-access-concept.html 
sidebar: sidebar 
keywords: configure, destination, volume, data, access 
summary: Nachdem das Ziel-Volume schreibbar gemacht wurde, muss das Volume für den Datenzugriff konfiguriert werden. NAS-Clients, NVMe-Subsystem und SAN-Hosts können auf die Daten vom Ziel-Volume zugreifen, bis das Quell-Volume wieder aktiviert ist. 
---
= Konfigurieren Sie das ONTAP SnapMirror Ziel-Volume für den Datenzugriff
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem das Ziel-Volume schreibbar gemacht wurde, muss das Volume für den Datenzugriff konfiguriert werden. NAS-Clients, NVMe-Subsystem und SAN-Hosts können auf die Daten vom Ziel-Volume zugreifen, bis das Quell-Volume wieder aktiviert ist.

NAS-Umgebung:

. Mounten Sie das NAS-Volume mithilfe desselben Verbindungspfads, an den das Quell-Volume in der Quell-SVM angehängt war, in den Namespace.
. Wenden Sie die entsprechenden ACLs auf die SMB-Freigaben am Ziel-Volume an.
. Weisen Sie die NFS-Exportrichtlinien dem Ziel-Volume zu.
. Wenden Sie die Kontingentregeln auf das Ziel-Volume an.
. Leiten Sie die Clients an das Ziel-Volume weiter.
. NFS- und SMB-Freigaben erneut auf den Clients einbinden.


SAN-Umgebung:

. Ordnen Sie die LUNs im Volume der entsprechenden Initiatorgruppe zu.
. Erstellen Sie für iSCSI-Sitzungen von den SAN-Host-Initiatoren zu den SAN-LIFs.
. Führen Sie auf dem SAN-Client einen erneuten Speicherscan durch, um die verbundenen LUNs zu erkennen.


Weitere Informationen zur NVMe Umgebung finden Sie unter link:../san-admin/index.html["SAN Administration"].
