---
permalink: data-protection/convert-mode-snapmirror-synchronous-task.html 
sidebar: sidebar 
keywords: convert, mode, snapmirror, synchronous, relationship 
summary: Ab ONTAP 9.5 werden synchrone SnapMirror Beziehungen unterstützt. Sie können den Modus einer synchronen SnapMirror-Beziehung von StructSync in Sync umwandeln oder umgekehrt. 
---
= Konvertieren Sie den Modus einer synchronen SnapMirror-Beziehung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.5 werden synchrone SnapMirror Beziehungen unterstützt. Sie können den Modus einer synchronen SnapMirror-Beziehung von StructSync in Sync umwandeln oder umgekehrt.

.Über diese Aufgabe
Sie können die Richtlinie einer synchronen SnapMirror-Beziehung nicht ändern, um ihren Modus zu konvertieren.

.Schritte
. Beenden Sie aus dem Ziel-Cluster die vorhandene synchrone SnapMirror-Beziehung:
+
`snapmirror quiesce -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster2::> snapmirror quiesce -destination-path vs1_dr:vol1
----
. Löschen Sie auf dem Ziel-Cluster die vorhandene synchrone SnapMirror-Beziehung:
+
`snapmirror delete -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster2::> snapmirror delete -destination-path vs1_dr:vol1
----
. Geben Sie die SnapMirror Beziehung aus dem Quell-Cluster frei, ohne die gemeinsamen Snapshot Kopien zu löschen:
+
`snapmirror release -relationship-info-only true -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster1::> snapmirror release -relationship-info-only true -destination-path vs1_dr:vol1
----
. Erstellen Sie aus dem Ziel-Cluster eine synchrone SnapMirror-Beziehung, indem Sie den Modus angeben, in den Sie die synchrone SnapMirror-Beziehung konvertieren möchten:
+
`snapmirror create -source-path vs1:vol1 -destination-path <destination_SVM>:<destination_volume> -policy Sync|StrictSync`

+
[listing]
----
cluster2::> snapmirror create -source-path vs1:vol1 -destination-path vs1_dr:vol1 -policy Sync
----
. Synchronisieren Sie die SnapMirror Beziehung vom Ziel-Cluster neu:
+
`snapmirror resync -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster2::> snapmirror resync -destination-path vs1_dr:vol1
----

