---
permalink: data-protection/convert-mode-snapmirror-synchronous-task.html 
sidebar: sidebar 
keywords: convert, mode, snapmirror, synchronous, relationship 
summary: Ab ONTAP 9.5 werden SnapMirror synchron Beziehungen unterstützt. Der Modus einer SnapMirror synchron Beziehung kann von StrictSync auf Sync oder umgekehrt geändert werden. 
---
= Den Modus einer ONTAP SnapMirror synchronen Beziehung konvertieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.5 werden SnapMirror synchron Beziehungen unterstützt. Der Modus einer SnapMirror synchron Beziehung kann von StrictSync auf Sync oder umgekehrt geändert werden.

.Über diese Aufgabe
Die Richtlinie einer SnapMirror synchronen Beziehung kann nicht geändert werden, um deren Modus zu konvertieren.

.Schritte
. Vom Ziel-Cluster die bestehende SnapMirror synchron Beziehung stilllegen:
+
`snapmirror quiesce -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster2::> snapmirror quiesce -destination-path vs1_dr:vol1
----
. Vom Ziel-Cluster aus die bestehende SnapMirror synchron Beziehung löschen:
+
`snapmirror delete -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster2::> snapmirror delete -destination-path vs1_dr:vol1
----
. Vom Quell-Cluster die SnapMirror Beziehung freigeben, ohne die gemeinsamen Snapshots zu löschen:
+
`snapmirror release -relationship-info-only true -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster1::> snapmirror release -relationship-info-only true -destination-path vs1_dr:vol1
----
. Vom Ziel-Cluster aus eine SnapMirror synchron Beziehung erstellen, indem der Modus angegeben wird, in den die SnapMirror synchron Beziehung konvertiert werden soll:
+
`snapmirror create -source-path vs1:vol1 -destination-path <destination_SVM>:<destination_volume> -policy Sync|StrictSync`

+
[listing]
----
cluster2::> snapmirror create -source-path vs1:vol1 -destination-path vs1_dr:vol1 -policy Sync
----
. Vom Ziel-Cluster aus die SnapMirror Beziehung neu synchronisieren:
+
`snapmirror resync -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster2::> snapmirror resync -destination-path vs1_dr:vol1
----


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["snapmirror create"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["snapmirror delete"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["snapmirror quiesce"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["SnapMirror Release"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["SnapMirror Resynchronisierung"^]

