---
permalink: data-protection/convert-type-snapmirror-task.html 
sidebar: sidebar 
keywords: convert, snapmirror, relationship, asynchronous, synchronous, baseline, convert 
summary: Ab ONTAP 9.5 wird SnapMirror synchron unterstützt. Eine SnapMirror asynchron Beziehung kann in eine SnapMirror synchron Beziehung oder umgekehrt umgewandelt werden, ohne dass ein Basistransfer erforderlich ist. 
---
= Den Typ einer ONTAP SnapMirror Beziehung konvertieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.5 wird SnapMirror synchron unterstützt. Eine SnapMirror asynchron Beziehung kann in eine SnapMirror synchron Beziehung oder umgekehrt umgewandelt werden, ohne dass ein Basistransfer erforderlich ist.

.Über diese Aufgabe
Sie können eine SnapMirror asynchron Beziehung nicht durch Ändern der SnapMirror Richtlinie in eine SnapMirror synchron Beziehung oder umgekehrt umwandeln.

.Schritte
* *Umwandlung einer SnapMirror asynchronen Beziehung in eine SnapMirror synchronen Beziehung*
+
.. Vom Ziel-Cluster aus die SnapMirror asynchrone Beziehung löschen:
+
`snapmirror delete -destination-path <SVM:volume>`

+
[listing]
----
cluster2::>snapmirror delete -destination-path vs1_dr:vol1
----
.. Vom Quell-Cluster die SnapMirror Beziehung freigeben, ohne die gemeinsamen Snapshots zu löschen:
+
`snapmirror release -relationship-info-only true -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster1::>snapmirror release -relationship-info-only true -destination-path vs1_dr:vol1
----
.. Vom Ziel-Cluster aus eine SnapMirror synchron Beziehung erstellen:
+
`snapmirror create -source-path _src_SVM:src_volume_ -destination-path <destination_SVM>:<destination_volume> -policy sync-mirror`

+
[listing]
----
cluster2::>snapmirror create -source-path vs1:vol1 -destination-path vs1_dr:vol1 -policy sync
----
.. Die SnapMirror synchron Beziehung erneut synchronisieren:
+
`snapmirror resync -destination-path <destination_SVM:destination_volume>`

+
[listing]
----
cluster2::>snapmirror resync -destination-path vs1_dr:vol1
----


* *Umwandlung einer SnapMirror synchronen Beziehung in eine SnapMirror asynchrone Beziehung*
+
.. Vom Ziel-Cluster die bestehende SnapMirror synchron Beziehung stilllegen:
+
`snapmirror quiesce -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster2::> snapmirror quiesce -destination-path vs1_dr:vol1
----
.. Vom Ziel-Cluster aus die SnapMirror asynchrone Beziehung löschen:
+
`snapmirror delete -destination-path <SVM:volume>`

+
[listing]
----
cluster2::>snapmirror delete -destination-path vs1_dr:vol1
----
.. Vom Quell-Cluster die SnapMirror Beziehung freigeben, ohne die gemeinsamen Snapshots zu löschen:
+
`snapmirror release -relationship-info-only true -destination-path <destination_SVM:destination_volume>`

+
[listing]
----
cluster1::>snapmirror release -relationship-info-only true -destination-path vs1_dr:vol1
----
.. Vom Ziel-Cluster aus eine SnapMirror asynchrone Beziehung erstellen:
+
`snapmirror create -source-path _src_SVM:src_volume_ -destination-path <destination_SVM:destination_volume> -policy MirrorAllSnapshots`

+
[listing]
----
cluster2::>snapmirror create -source-path vs1:vol1 -destination-path vs1_dr:vol1 -policy sync
----
.. Die SnapMirror synchron Beziehung erneut synchronisieren:
+
`snapmirror resync -destination-path <destination_SVM:destination_volume>`

+
[listing]
----
cluster2::>snapmirror resync -destination-path vs1_dr:vol1
----




.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["snapmirror create"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["snapmirror delete"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["snapmirror quiesce"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["SnapMirror Release"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["SnapMirror Resynchronisierung"^]

