---
permalink: data-protection/define-schedule-create-local-copy-destination-task.html 
sidebar: sidebar 
keywords: define, schedule, create, local copy, destination 
summary: Für SnapVault und einheitliche Replikationsbeziehungen besteht Schutz vor der Möglichkeit, dass ein aktualisierter Snapshot beschädigt ist, indem eine Kopie des zuletzt übertragenen Snapshots auf dem Ziel erstellt wird. Diese „lokale Kopie“ bleibt unabhängig von den Aufbewahrungsregeln auf dem Quell-Cluster erhalten, sodass selbst dann, wenn der ursprünglich von SnapMirror übertragene Snapshot auf dem Quell-Cluster nicht mehr verfügbar ist, eine Kopie davon auf dem Ziel vorhanden ist. 
---
= Einen ONTAP SnapMirror Zeitplan definieren, um eine lokale Kopie auf dem Ziel zu erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für SnapVault und einheitliche Replikationsbeziehungen besteht Schutz vor der Möglichkeit, dass ein aktualisierter Snapshot beschädigt ist, indem eine Kopie des zuletzt übertragenen Snapshots auf dem Ziel erstellt wird. Diese „lokale Kopie“ bleibt unabhängig von den Aufbewahrungsregeln auf dem Quell-Cluster erhalten, sodass selbst wenn der ursprünglich von SnapMirror übertragene Snapshot auf dem Quell-Cluster nicht mehr verfügbar ist, eine Kopie davon auf dem Ziel vorhanden ist.

.Über diese Aufgabe
Den Zeitplan für die Erstellung einer lokalen Kopie geben Sie in der  `-schedule` Option des  `snapmirror policy add-rule` Befehls an.

.Schritt
. Ein Zeitplan für die Erstellung einer lokalen Kopie auf dem Zielsystem wird definiert:
+
`snapmirror policy add-rule -vserver _SVM_ -policy _policy_for_rule_ -snapmirror-label _snapmirror-label_ -schedule _schedule_`

+
Ein Beispiel für die Erstellung eines Arbeitsplans ist unter link:create-replication-job-schedule-task.html["Erstellen eines Replikationsjob-Zeitplans"] zu finden.

+
Das folgende Beispiel fügt der Standard `MirrorAndVault`richtlinie einen Zeitplan für die Erstellung einer lokalen Kopie hinzu:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy MirrorAndVault -snapmirror-label my_monthly -schedule my_monthly
----
+
Das folgende Beispiel fügt der benutzerdefinierten  `my_unified` Policy einen Zeitplan für die Erstellung einer lokalen Kopie hinzu:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy my_unified -snapmirror-label my_monthly -schedule my_monthly
----
+
Weitere Informationen zu  `snapmirror policy add-rule` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-add-rule.html["ONTAP-Befehlsreferenz"^].


