---
permalink: data-protection/destination-volume-grows-automatically-concept.html 
sidebar: sidebar 
keywords: destination, volume, grow, automatic 
summary: Während einer Spiegelübertragung zum Datenschutz wächst das Ziel-Volume automatisch, wenn das Quell-Volume gewachsen ist, vorausgesetzt, im Aggregat, das das Volume enthält, ist noch Speicherplatz verfügbar. 
---
= Wenn ein ONTAP Datensicherungsziel-Volume automatisch wächst
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Während einer Spiegelübertragung zum Datenschutz wächst das Ziel-Volume automatisch, wenn das Quell-Volume gewachsen ist, vorausgesetzt, im Aggregat, das das Volume enthält, ist noch Speicherplatz verfügbar.

Dieses Verhalten tritt unabhängig von jeglichen Einstellungen für automatisches Wachstum am Ziel auf. Das Wachstum des Volumes kann nicht begrenzt werden, und ONTAP kann nicht daran gehindert werden, es zu vergrößern.

Standardmäßig sind Datensicherungsvolumes auf den  `grow_shrink` automatische Größenanpassung-Modus eingestellt, wodurch das Volume je nach belegtem Speicherplatz wächst oder schrumpft. Die maximale automatische Größenanpassung für Datensicherungsvolumes entspricht der maximalen FlexVol-Größe und ist plattformabhängig. Beispiel:

* FAS8200, Standard-DP Volume maximale automatische Größenanpassung = 100TB


Weitere Informationen finden sich unter  https://hwu.netapp.com/["NetApp Hardware Universe"^].
