---
permalink: data-protection/dpo-systems-feature-enhancements-reference.html 
sidebar: sidebar 
keywords: dpo, systems, feature, enhancements, snapmirror, dp optimized, optimised, backoff, back off, deduplication, deduplicate, snapshot blocks, donors, compact, flexvol, license 
summary: 'Ab ONTAP 9.6 erhöht sich bei Installation der DP_optimized (DPO) Lizenz die maximal unterstützte Anzahl von FlexVol Volumes. Ab ONTAP 9.4 unterstützen Systeme mit der DPO-Lizenz das Zurückschalten von SnapMirror, die Volume-übergreifende Hintergrund-Deduplizierung, die Nutzung der Snapshot-Blöcke als Spender und die Data-Compaction.' 
---
= DPO-Systeme bieten Verbesserungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.6 erhöht sich bei Installation der DP_optimized (DPO) Lizenz die maximal unterstützte Anzahl von FlexVol Volumes. Ab ONTAP 9.4 unterstützen Systeme mit der DPO-Lizenz das Zurückschalten von SnapMirror, die Volume-übergreifende Hintergrund-Deduplizierung, die Nutzung der Snapshot-Blöcke als Spender und die Data-Compaction.

Ab ONTAP 9.6 ist die maximal unterstützte Anzahl an FlexVol-Volumes auf sekundären oder Datensicherungssystemen gestiegen, wodurch Sie auf bis zu 2,500 FlexVol-Volumes pro Node oder im Failover-Modus auf bis zu 5,000 skalieren können. Die Erhöhung der FlexVol-Volumes wird mit aktiviertlink:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html#data-protection-optimized-license["DP_Optimized (DPO)-Lizenz"]. A link:https://docs.netapp.com/us-en/ontap/system-admin/manage-license-task.html#view-details-about-a-license["SnapMirror Lizenz"] ist weiterhin sowohl auf den Quell- als auch auf den Ziel-Nodes erforderlich.

Ab ONTAP 9.4 werden die folgenden Funktionsverbesserungen für DPO-Systeme vorgenommen:

* „SnapMirror Backoff“: In DPO-Systemen wird der Replizierungsdatenverkehr dieselbe Priorität zugewiesen, die Client-Workloads zugewiesen werden.
+
Bei DPO-Systemen ist das Backoff SnapMirror standardmäßig deaktiviert.

* Hintergrund-Deduplizierung von Volumes und Volume-übergreifende Hintergrund-Deduplizierung: Hintergrunddeduplizierung für Volumes und Volume-übergreifende Hintergrund-Deduplizierung sind in DPO Systemen aktiviert.
+
Sie können den `storage aggregate efficiency cross-volume-dedupe start -aggregate _aggregate_name_ -scan-old-data true` Befehl ausführen, um die vorhandenen Daten zu deduplizieren. Als Best Practice empfiehlt es sich, den Befehl in Zeiten geringerer Auslastung auszuführen, um die Auswirkungen auf die Performance zu verringern.

* Erhöhte Einsparungen durch Einsatz von Snapshot-Blöcken als Spender: Die Datenblöcke, die im aktiven File-System nicht verfügbar sind, aber in Snapshot-Kopien gefangen sind, werden als Spender für die Volume-Deduplizierung verwendet.
+
Die neuen Daten können mit den Daten dedupliziert werden, die in Snapshot-Kopien gefangen sind, und zwar durch eine effektive gemeinsame Nutzung der Snapshot-Blöcke. Der größere Spenderbedarf sorgt für weitere Einsparungen, insbesondere wenn das Volume über eine große Anzahl von Snapshot-Kopien verfügt.

* Data-Compaction: Data-Compaction ist auf DPO Volumes standardmäßig aktiviert.

