---
permalink: data-protection/exclude-network-name-service-svm-replication-task.html 
sidebar: sidebar 
keywords: exclude, network, name service, other settings, svm replication 
summary: Mit der Option -identitätsbebeibehalten false lässt sich der befehl snapmirror create nur die Volumes und Sicherheitskonfigurationen einer SVM replizieren. Einige Protokoll- und Namensdiensteinstellungen bleiben ebenfalls erhalten. 
---
= Schließen Sie Netzwerk-, Name-Service- und andere Einstellungen von der SVM-Replizierung aus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `-identity-preserve false` Option des `snapmirror create` Befehl zum Replizieren nur der Volumes und Sicherheitskonfigurationen einer SVM Einige Protokoll- und Namensdiensteinstellungen bleiben ebenfalls erhalten.

.Über diese Aufgabe
Eine Liste der erhaltenen Protokoll- und Namensdiensteinstellungen finden Sie unter link:snapmirror-svm-replication-concept.html#configurations-replicated-in-svm-dr-relationships["Konfigurationen in SVM-DR-Beziehungen repliziert"].

Eine vollständige Befehlssyntax finden Sie in der man-Page.

.Bevor Sie beginnen
Quell- und Ziel-Cluster sowie SVMs müssen Peering durchgeführt werden.

Weitere Informationen finden Sie unter link:../peering/create-cluster-relationship-93-later-task.html["Erstellen einer Cluster-Peer-Beziehung"] Und link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["Erstellen einer SVM-Peer-Beziehung"].

.Schritte
. Ziel-SVM erstellen:
+
`vserver create -vserver _SVM_ -subtype dp-destination`

+
Der SVM-Name muss über die Quell- und Ziel-Cluster hinweg eindeutig sein.

+
Im folgenden Beispiel wird eine Ziel-SVM mit dem Namen erstellt `svm_backup`:

+
[listing]
----
cluster_dst:> vserver create -vserver svm_backup -subtype dp-destination
----
. Erstellen Sie aus dem Ziel-Cluster eine SVM-Peer-Beziehung mit dem `vserver peer create` Befehl.
+
Weitere Informationen finden Sie unter link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["Erstellen einer SVM-Peer-Beziehung"].

. Erstellen eines Replikationsauftragplans:
+
`job schedule cron create -name _job_name_ -month _month_ -dayofweek _day_of_week_ -day _day_of_month_ -hour _hour_ -minute _minute_`

+
Für `-month`, `-dayofweek`, und `-hour`, Sie können angeben `all` Zum Ausführen des Jobs jeden Monat, Wochentag und Stunde.

+
[NOTE]
====
Der unterstützte Zeitplan (RPO) für FlexVol Volumes in einer SVM SnapMirror Beziehung beträgt mindestens 15 Minuten. Der unterstützte Zeitplan (RPO) für FlexGroup Volumes in einer SVM SnapMirror Beziehung beträgt mindestens 30 Minuten.

====
+
Im folgenden Beispiel wird ein Job-Zeitplan mit dem Namen erstellt `my_weekly` Das läuft samstags um 3:00 Uhr:

+
[listing]
----
cluster_dst::> job schedule cron create -name my_weekly -dayofweek "Saturday" -hour 3 -minute 0
----
. Erstellen einer Replikationsbeziehung, die Netzwerk, Name Service und andere Konfigurationseinstellungen ausschließt:
+
`snapmirror create -source-path _SVM_: -destination-path _SVM_: -type DP|XDP -schedule schedule -policy policy -identity-preserve false`

+
[NOTE]
====
Sie müssen nach dem SVM-Namen in einen Doppelpunkt (:) eingeben `-source-path` Und `-destination-path` Optionen: Sehen Sie sich die Beispiele unten an. Sie müssen diesen Befehl über die Ziel-SVM oder das Ziel-Cluster ausführen.

====
+
Im folgenden Beispiel wird eine SnapMirror DR-Beziehung mit dem Standard erstellt `MirrorAllSnapshots` Richtlinie: Bei der Beziehung werden Netzwerk, Name Service und andere Konfigurationseinstellungen von der SVM-Replizierung ausgeschlossen:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy MirrorAllSnapshots -identity-preserve false
----
+
Im folgenden Beispiel wird eine einheitliche Replizierungsbeziehung mit dem Standard erstellt `MirrorAndVault` Richtlinie: Die Beziehung schließt Netzwerk-, Namensdienst- und andere Konfigurationseinstellungen aus:

+
[listing]
----
cluster_dst:> snapmirror create svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy MirrorAndVault -identity-preserve false
----
+
Angenommen, Sie haben eine benutzerdefinierte Richtlinie mit dem Richtlinientyp erstellt `async-mirror`, Das folgende Beispiel erstellt eine SnapMirror DR-Beziehung. Bei der Beziehung werden Netzwerk, Name Service und andere Konfigurationseinstellungen von der SVM-Replizierung ausgeschlossen:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy my_mirrored -identity-preserve false
----
+
Angenommen, Sie haben eine benutzerdefinierte Richtlinie mit dem Richtlinientyp erstellt `mirror-vault`, Das folgende Beispiel erstellt eine einheitliche Replikationsbeziehung. Bei der Beziehung werden Netzwerk, Name Service und andere Konfigurationseinstellungen von der SVM-Replizierung ausgeschlossen:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy my_unified -identity-preserve false
----
. Ziel-SVM stoppen:
+
`vserver stop`

+
`_SVM name_`

+
Im folgenden Beispiel wird eine Ziel-SVM namens dvs1 angehalten:

+
[listing]
----
destination_cluster::> vserver stop -vserver dvs1
----
. Wenn Sie SMB verwenden, müssen Sie auch einen SMB-Server konfigurieren.
+
Siehe link:create-smb-server-task.html["Nur SMB: Erstellen eines SMB-Servers"].

. Initialisieren Sie die SVM-Replizierungsbeziehung von der Ziel-SVM oder dem Ziel-Cluster:
+
`snapmirror initialize -source-path _SVM_name_: -destination-path _SVM_name_:`



.Nachdem Sie fertig sind
Sie müssen das Netzwerk und die Protokolle auf der Ziel-SVM für den Datenzugriff bei einem Ausfall konfigurieren.
