---
permalink: data-protection/exclude-volumes-svm-replication-task.html 
sidebar: sidebar 
keywords: exclude, volumes, svm replication 
summary: Standardmäßig werden alle RW-Daten-Volumes der Quell-SVM repliziert. Wenn Sie nicht alle Volumes auf der Quell-SVM sichern möchten, können Sie die Option -vserver-dr-protected Option des Befehls Volume modify verwenden, um Volumes von der SVM-Replizierung auszuschließen. 
---
= Schließen Sie Volumes von der SVM-Replizierung aus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Standardmäßig werden alle RW-Daten-Volumes der Quell-SVM repliziert. Wenn Sie nicht alle Volumes auf der Quell-SVM sichern möchten, können Sie die verwenden `-vserver-dr-protection unprotected` Option des `volume modify` Befehl zum Ausschließen von Volumes aus der SVM-Replizierung.

.Schritte
. Volume von SVM-Replizierung ausschließen:
+
`volume modify -vserver _SVM_ -volume _volume_ -vserver-dr-protection unprotected`

+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
Das Volume ist im folgenden Beispiel nicht enthalten `volA_src` Über SVM-Replizierung:

+
[listing]
----
cluster_src::> volume modify -vserver SVM1 -volume volA_src -vserver-dr-protection unprotected
----
+
Wenn Sie später ein Volume in die SVM-Replizierung aufnehmen möchten, die Sie ursprünglich ausgeschlossen haben, führen Sie den folgenden Befehl aus:

+
`volume modify -vserver _SVM_ -volume _volume_ -vserver-dr-protection protected`

+
Das folgende Beispiel beinhaltet das Volume `volA_src` In der SVM-Replizierung:

+
[listing]
----
cluster_src::> volume modify -vserver SVM1 -volume volA_src -vserver-dr-protection protected
----
. Erstellen und Initialisieren der SVM-Replizierungsbeziehung, wie in beschrieben link:replicate-entire-svm-config-task.html["Replizierung einer gesamten SVM-Konfiguration"].

