---
permalink: data-protection/extended-queries-many-snapmirror-relationships-task.html 
sidebar: sidebar 
keywords: extend, query, act, snapmirror, relationships 
summary: Sie können erweiterte Abfragen verwenden, um SnapMirror Operationen an vielen SnapMirror Beziehungen gleichzeitig auszuführen. Beispielsweise könnten Sie mehrere nicht initialisierte SnapMirror Beziehungen haben, die Sie mit einem Befehl initialisieren möchten. 
---
= Verwendung erweiterter Abfragen für viele SnapMirror Beziehungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können _erweiterte Abfragen_ verwenden, um SnapMirror Operationen gleichzeitig an vielen SnapMirror Beziehungen durchzuführen. Beispielsweise könnten Sie mehrere nicht initialisierte SnapMirror Beziehungen haben, die Sie mit einem Befehl initialisieren möchten.

Sie können erweiterte Anfragen auf folgende SnapMirror Vorgänge anwenden:

* Nicht initialisierte Beziehungen
* Fortsetzen von stillgelegten Beziehungen
* Unterbrochene Beziehungen werden neu synchronisiert
* Aktualisierung von nicht aktiven Beziehungen
* Übertragung von Beziehungsdaten wird abgebrochen


.Schritt
. Ausführung eines SnapMirror Vorgangs über viele Beziehungen:
+
`_snapmirror command_ {-state state } *`

+
Mit dem folgenden Befehl werden SnapMirror Beziehungen in einem initialisiert `Uninitialized` Bundesland:

+
[listing]
----
vs1::> snapmirror initialize {-state Uninitialized} *
----

