---
permalink: data-protection/limitations-mirror-relationships-concept.html 
sidebar: sidebar 
keywords: snapmirror, limitations 
summary: Es ist wichtig, sich der grundlegenden SnapMirror Einschränkungen bewusst zu sein, bevor eine Datenschutzbeziehung erstellt wird. 
---
= Informationen zu den Einschränkungen von ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es ist wichtig, sich der grundlegenden SnapMirror Einschränkungen bewusst zu sein, bevor eine Datenschutzbeziehung erstellt wird.

* Ein Zielvolume kann nur ein Quellvolume haben.
+

NOTE: Ein Quellvolume kann mehrere Zielvolumes haben. Das Zielvolume kann für jede Art von SnapMirror Replikationsbeziehung als Quellvolume dienen.

* Je nach Array-Modell können maximal acht oder sechzehn Zielvolumes von einem einzelnen Quellvolume aus verteilt werden. Siehe link:https://hwu.netapp.com/["Hardware Universe"^] für Details zu Ihrer spezifischen Konfiguration.
* Dateien können nicht am Zielort einer SnapMirror DR-Beziehung wiederhergestellt werden.
* Quell- oder Ziel-SnapVault Volumes dürfen nicht 32-Bit sein.
* Das Quell-Volume für eine SnapVault Beziehung sollte kein FlexClone Volume sein.
+

NOTE: Die Beziehung wird funktionieren, aber die durch FlexClone Volumes gebotene Effizienz wird nicht erhalten bleiben.


