---
permalink: data-protection/long-term-retention-snapshots-concept.html 
sidebar: sidebar 
keywords: local, snapshot, retention, snapmirror, vault 
summary: Sie können Snapshots zur langfristigen Aufbewahrung direkt auf dem sekundären Volume einer SnapMirror -Beziehung erstellen, indem Sie entweder den Richtlinientyp „Vault“ oder „Mirror-Vault“ verwenden.  Diese Snapshots werden als Backups auf dem Ziel gespeichert. 
---
= Erfahren Sie mehr über ONTAP Snapshots zur Langzeitaufbewahrung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror -Beziehungen mit dem Richtlinientyp „Vault“ oder „Mirror-Vault“ ermöglichen die Erstellung von Snapshots direkt auf dem sekundären Volume der SnapMirror -Beziehung.  Diese Snapshots werden als Backups auf dem Ziel gespeichert.  Diese Snapshots werden häufig zur langfristigen Aufbewahrung erstellt und als Long-Term Retention (LTR)-Snapshots bezeichnet.

Sie erstellen einen Snapshot zur langfristigen Aufbewahrung, indem Sie in der SnapMirror Richtlinienregel einen Zeitplan für die Snapshot-Erstellung, das SnapMirror-Namenspräfix, die SnapMirror -Bezeichnung und die Aufbewahrungsanzahl angeben.  Dieser Snapshot wird auf dem SnapMirror Zielvolume unabhängig von den Aufbewahrungsregeln der Quelle aufbewahrt.

Snapshots zur langfristigen Aufbewahrung sind nur für FlexVol SnapMirror Konfigurationen verfügbar.  Sie können keine LTR-Snapshots für FlexGroup SnapMirror -Konfigurationen erstellen.

In einer SnapMirror Kaskadenbeziehung können Snapshots zur langfristigen Aufbewahrung nur auf dem letzten Volume der Kaskade erstellt werden.



== Verwandte Informationen

link:define-schedule-create-local-copy-destination-task.html["Definieren Sie einen ONTAP SnapMirror Zeitplan, um eine lokale Kopie auf dem Ziel zu erstellen"]
