---
permalink: data-protection/make-destination-volume-writeable-task.html 
sidebar: sidebar 
keywords: destination, volume, writeable, write, serve data, snapmirror, quiesce, pause, abort, transfers 
summary: Sie müssen das Ziel-Volume schreibbar machen, bevor Sie Daten vom Volume an die Clients bereitstellen können. Mit dem Befehl snapmirror quiesce können Sie geplante Transfers zum Ziel anhalten, den befehl snapmirror Abbruch abbrechen, um laufende Transfers zu stoppen, und mit dem snapmirror Break-Befehl wird das Ziel beschreibbar gemacht. 
---
= Das Zielvolumen schreibbar machen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen das Ziel-Volume schreibbar machen, bevor Sie Daten vom Volume an die Clients bereitstellen können. Sie können das verwenden `snapmirror quiesce` Befehl zum Anhalten geplanter Transfers an das Ziel, das `snapmirror abort` Befehl zum Beenden laufender Transfers, und `snapmirror break` Befehl, um das Ziel beschreibbar zu machen.

.Über diese Aufgabe
Sie müssen diese Aufgabe über die Ziel-SVM oder das Ziel-Cluster ausführen.

.Schritte
. Geplante Transfers zum Ziel anhalten:
+
`snapmirror quiesce -source-path _SVM:volume|cluster://SVM/volume_, ... -destination-path _SVM:volume|cluster://SVM/volume_, ...`

+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
Im folgenden Beispiel werden geplante Transfers zwischen dem Quell-Volume angehalten `volA` Ein `svm1` Und dem Ziel-Volume `volA_dst` Ein `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror quiesce -source-path svm1:volA -destination-path svm_backup:volA_dst
----
. Laufende Transfers zum Ziel anhalten:
+
`snapmirror abort -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`

+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
[NOTE]
====
Dieser Schritt ist für synchrone SnapMirror Beziehungen nicht erforderlich (unterstützt ab ONTAP 9.5).

====
+
Im folgenden Beispiel werden kontinuierliche Transfers zwischen dem Quell-Volume angehalten `volA` Ein `svm1` Und dem Ziel-Volume `volA_dst` Ein `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror abort -source-path svm1:volA -destination-path svm_backup:volA_dst
----
. SnapMirror DR-Beziehung unterbrechen:
+
`snapmirror break -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`

+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
Im folgenden Beispiel wird die Beziehung zwischen dem Quell-Volume unterbrochen `volA` Ein `svm1` Und dem Ziel-Volume `volA_dst` Ein `svm_backup` Und dem Ziel-Volume `volA_dst` Ein `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm1:volA -destination-path svm_backup:volA_dst
----




== Weitere Möglichkeiten dies in ONTAP zu tun

[cols="2"]
|===
| So führen Sie diese Aufgaben durch: | Inhalt anzeigen... 


| Der neu gestaltete System Manager (verfügbar ab ONTAP 9.7) | link:https://docs.netapp.com/us-en/ontap/task_dp_serve_data_from_destination.html["Stellen Sie Daten von einem SnapMirror Ziel bereit"^] 


| System Manager Classic (verfügbar mit ONTAP 9.7 und älter) | link:https://docs.netapp.com/us-en/ontap-sm-classic/volume-disaster-recovery/index.html["Übersicht über die Disaster Recovery von Volumes"^] 
|===