---
permalink: data-protection/preserve-snapshot-copy-primary-source-volume-task.html 
sidebar: sidebar 
keywords: ensure, snapshot, copy, mirror-vault, deployment 
summary: Sie können den Befehl SnapMirror Snapshot-owner create verwenden, um einen gekennzeichneten Snapshot auf dem sekundären in einer Mirror-Vault-Bereitstellung beizubehalten. Dadurch wird sichergestellt, dass für die Aktualisierung der Vault-Beziehung ein gemeinsamer Snapshot vorhanden ist. 
---
= Mit ONTAP wird ein gemeinsamer Snapshot in einer Mirror-Vault-Implementierung sichergestellt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit dem Befehl können Sie `snapmirror snapshot-owner create` einen beschrifteten Snapshot auf dem sekundären in einer Mirror-Vault-Bereitstellung beibehalten. Dadurch wird sichergestellt, dass für die Aktualisierung der Vault-Beziehung ein gemeinsamer Snapshot vorhanden ist. Erfahren Sie mehr über `snapmirror snapshot-owner create` in der link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-snapshot-owner-create.html["ONTAP-Befehlsreferenz"^].

.Über diese Aufgabe
Wenn Sie eine kombinierte Mirror-Vault Fan-out- oder Kaskadenbereitstellung verwenden, sollten Sie beachten, dass Updates fehlschlagen, wenn kein gemeinsamer Snapshot auf den Quell- und Ziel-Volumes vorhanden ist.

Das ist nie ein Problem für die Spiegelbeziehung in einer Fan-out- oder Kaskadenimplementierung, da SnapMirror vor der Aktualisierung immer einen Snapshot des Quell-Volumes erstellt.

Es kann jedoch ein Problem für die Vault-Beziehung sein, da SnapMirror bei Aktualisierung einer Vault-Beziehung keinen Snapshot des Quell-Volumes erstellt. Sie müssen den verwenden `snapmirror snapshot-owner create`, um sicherzustellen, dass es mindestens einen gemeinsamen Snapshot sowohl auf der Quelle als auch auf dem Ziel der Vault-Beziehung gibt.

.Schritte
. Weisen Sie dem beschrifteten Snapshot, den Sie beibehalten möchten, auf dem Quell-Volume einen Eigentümer zu:
+
`snapmirror snapshot-owner create -vserver <SVM> -volume <volume> -snapshot <snapshot> -owner <owner>`

+
Im folgenden Beispiel wird als Eigentümer des `snap1` Snapshots zugewiesen `ApplicationA`:

+
[listing]
----
clust1::> snapmirror snapshot-owner create -vserver vs1 -volume vol1
-snapshot snap1 -owner ApplicationA
----
. Aktualisieren Sie die Spiegelbeziehung, wie in beschriebenlink:update-replication-relationship-manual-task.html["Manuelles Aktualisieren einer Replikationsbeziehung"].
+
Alternativ können Sie auf die geplante Aktualisierung der Spiegelbeziehung warten.

. Den beschrifteten Snapshot an das Vault-Ziel übertragen:
+
`snapmirror update -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ... -source-snapshot snapshot`

+
Erfahren Sie mehr über `snapmirror update` in der link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["ONTAP-Befehlsreferenz"^].

+
Im folgenden Beispiel wird der Snapshot übertragen `snap1`::
+
--
[listing]
----
clust1::> snapmirror update -vserver vs1 -volume vol1
-source-snapshot snap1
----
Der beschriftete Snapshot wird beibehalten, wenn die Vault-Beziehung aktualisiert wird.

--


. Entfernen Sie auf dem Quell-Volume den Eigentümer aus dem beschrifteten Snapshot:
+
`snapmirror snapshot-owner delete -vserver _SVM_ -volume _volume_ -snapshot _snapshot_ -owner _owner_`

+
In den folgenden Beispielen wird als Eigentümer des `snap1` Snapshots entfernt `ApplicationA`:

+
[listing]
----
clust1::> snapmirror snapshot-owner delete -vserver vs1 -volume vol1
-snapshot snap1 -owner ApplicationA
----
+
Erfahren Sie mehr über `snapmirror snapshot-owner delete` in der link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-snapshot-owner-delete.html["ONTAP-Befehlsreferenz"^].


