---
permalink: data-protection/replicate-entire-svm-config-task.html 
sidebar: sidebar 
keywords: replicate, entire, svm, storage vm, disaster, protection, configuration, snapmirror, snap mirror, replication, mirror vault policy, snapshot 
summary: 'Es kann eine SVM Disaster Recovery (SVM DR) Beziehung erstellt werden, um eine SVM Konfiguration auf eine andere zu replizieren. Bei einem Ausfall am primären Standort lässt sich die Ziel-SVM schnell aktivieren.' 
---
= Eine vollständige ONTAP SVM Konfiguration replizieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es kann eine SVM Disaster Recovery (SVM DR) Beziehung erstellt werden, um eine SVM Konfiguration auf eine andere zu replizieren. Bei einem Ausfall am primären Standort lässt sich die Ziel-SVM schnell aktivieren.

.Bevor Sie beginnen
* Die Quell- und Ziel-Cluster sowie die SVMs müssen miteinander verbunden sein.
+
Weitere Informationen finden Sie unter link:../peering/create-cluster-relationship-93-later-task.html["Erstellen einer Cluster Peer-Beziehung"] und link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["Erstellen einer SVM Intercluster Peer-Beziehung"].

* Ab ONTAP 9.19.1 wird die Aktivierung von IPsec auf SVMs, die für SVM DR konfiguriert sind, nicht unterstützt. Wenn Sie IPsec verwenden, muss es deaktiviert werden oder eine andere SVM für die Konfiguration einer SVM DR Beziehung ausgewählt werden. Eine Fehlermeldung erscheint, wenn ONTAP 9.19.1 oder höher verwendet wird und versucht wird, IPsec auf einer für SVM DR konfigurierten SVM zu aktivieren.


Weitere Informationen zu den in diesem Verfahren beschriebenen Befehlen befinden sich in der link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP-Befehlsreferenz"^].

.Über diese Aufgabe
Dieser Workflow setzt voraus, dass Sie bereits eine Standardrichtlinie oder eine benutzerdefinierte Replikationsrichtlinie verwenden.

Ab ONTAP 9.9.1 ist es bei Verwendung der mirror-vault Richtlinie möglich, unterschiedliche Snapshot-Richtlinien auf der Quell- und Ziel-SVM zu erstellen, wobei die Snapshots auf dem Ziel nicht durch Snapshots auf der Quelle überschrieben werden. Weitere Informationen finden sich unter link:snapmirror-svm-replication-concept.html["Überblick über die SnapMirror SVM-Replikation"].

Diese Prozedur ist vom Ziel aus durchzuführen. Falls eine neue Datensicherungsstrategie erforderlich ist, zum Beispiel wenn die Quell-Speicher-VM mit SMB konfiguriert ist, sollte die Strategie erstellt und die Option *Identity preserve* verwendet werden. Weitere Informationen finden sich unter link:create-custom-replication-policy-concept.html["Benutzerdefinierte Datensicherungsstrategien erstellen"].

.Schritte
Diese Aufgabe kann über den System Manager oder die ONTAP CLI ausgeführt werden.

[role="tabbed-block"]
====
.System Manager
--
. Im Ziel-Cluster auf *Schutz > Beziehungen* klicken.
. Unter *Beziehungen* auf *Schützen* klicken und *Storage VMs (DR)* auswählen.
. Wählen Sie eine Datensicherungsstrategie. Wenn Sie eine benutzerdefinierte Datensicherungsstrategie erstellt haben, wählen Sie diese aus und anschließend den Quell-Cluster sowie die Speicher-VM, die repliziert werden soll. Es besteht auch die Möglichkeit, eine neue Ziel-Speicher-VM zu erstellen, indem ein neuer Name für die Speicher-VM eingegeben wird.
. Bei Bedarf lassen sich die Zieleinstellungen ändern, um die Identitätsbeibehaltung zu überschreiben sowie Netzwerkschnittstellen und Protokolle ein- oder auszuschließen.
. Auf *Speichern* klicken.


--
.CLI
--
. Erstellen einer Ziel-SVM:
+
[source, cli]
----
vserver create -vserver <SVM_name> -subtype dp-destination
----
+
Der SVM-Name muss sowohl im Quell-Cluster als auch im Ziel-Cluster eindeutig sein.

+
Das folgende Beispiel erstellt eine Ziel-SVM mit dem Namen `svm_backup`:

+
[listing]
----
cluster_dst:> vserver create -vserver svm_backup -subtype dp-destination
----
+
Weitere Informationen zu  `vserver create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-create.html["ONTAP-Befehlsreferenz"^].

. Vom Ziel-Cluster aus eine SVM Peer-Beziehung mit dem  `vserver peer create` Befehl erstellen.
+
Weitere Informationen finden sich unter link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["Erstellen einer SVM Intercluster Peer-Beziehung"].

+
Weitere Informationen zu  `vserver peer create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-peer-create.html["ONTAP-Befehlsreferenz"^].

. Erstellen eines Replikationsauftragszeitplans:
+
[source, cli]
----
job schedule cron create -name <job_name> -month <month> -dayofweek <day_of_week> -day <day_of_month> -hour <hour> -minute <minute>
----
+
Für  `-month`,  `-dayofweek` und  `-hour` kann  `all` angegeben werden, damit der Job jeden Monat, an jedem Wochentag bzw. zu jeder Stunde ausgeführt wird.

+

NOTE: Der minimal unterstützte Zeitplan (RPO) für FlexVol Volumes in einer SVM SnapMirror Beziehung beträgt 15 Minuten. Der minimal unterstützte Zeitplan (RPO) für FlexGroup Volumes in einer SVM SnapMirror Beziehung beträgt 30 Minuten.

+
Das folgende Beispiel erstellt einen Jobplan mit dem Namen  `my_weekly`, der samstags um 3:00 Uhr morgens ausgeführt wird:

+
[listing]
----
cluster_dst::> job schedule cron create -name my_weekly -dayofweek saturday -hour 3 -minute 0
----
+
Weitere Informationen zu  `job schedule cron create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/job-schedule-cron-create.html["ONTAP-Befehlsreferenz"^].

. Vom Ziel-SVM oder Ziel-Cluster aus eine Replikationsbeziehung erstellen:
+
[source, cli]
----
snapmirror create -source-path <SVM_name>: -destination-path <SVM_name>: -type <DP|XDP> -schedule <schedule> -policy <policy> -identity-preserve true
----
+

NOTE: Sie müssen nach dem SVM-Namen in den  `-source-path` und  `-destination-path` Optionen einen Doppelpunkt (:) eingeben.

+
Das folgende Beispiel erstellt eine SnapMirror DR-Beziehung unter Verwendung der Standard `MirrorAllSnapshots`richtlinie:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy MirrorAllSnapshots -identity-preserve true
----
+
Das folgende Beispiel erstellt eine einheitliche Replikationsbeziehung mit der Standard `MirrorAndVault`richtlinie:

+
[listing]
----
cluster_dst:> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy MirrorAndVault -identity-preserve true
----
+
Angenommen, Sie haben eine benutzerdefinierte Richtlinie mit dem Richtlinientyp  `async-mirror` erstellt, erstellt das folgende Beispiel eine SnapMirror DR-Beziehung:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy my_mirrored -identity-preserve true
----
+
Angenommen, Sie haben eine benutzerdefinierte Richtlinie mit dem Richtlinientyp  `mirror-vault` erstellt, erzeugt das folgende Beispiel eine einheitliche Replikationsbeziehung:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy my_unified -identity-preserve true
----
+
Weitere Informationen zu  `snapmirror create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["ONTAP-Befehlsreferenz"^].

. Die Ziel-SVM anhalten:
+
[source, cli]
----
vserver stop -vserver <SVM_name>
----
+
Das folgende Beispiel stoppt eine Ziel-SVM mit dem Namen svm_backup:

+
[listing]
----
cluster_dst::> vserver stop -vserver svm_backup
----
+
Weitere Informationen zu  `vserver stop` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/vserver-stop.html["ONTAP-Befehlsreferenz"^].

. Vom Ziel-SVM oder Ziel-Cluster aus die SVM-Replikationsbeziehung initialisieren:
+
[source, cli]
----
snapmirror initialize -source-path <SVM_name>: -destination-path <SVM_name>:
----
+

NOTE: Sie müssen nach dem SVM-Namen in den  `-source-path` und  `-destination-path` Optionen einen Doppelpunkt (:) eingeben.

+
Das folgende Beispiel initialisiert die Beziehung zwischen der Quell-SVM, `svm1`, und der Ziel-SVM, `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror initialize -source-path svm1: -destination-path svm_backup:
----
+
Weitere Informationen zu  `snapmirror initialize` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["ONTAP-Befehlsreferenz"^].



--
====