---
permalink: data-protection/restore-part-file-snapshot-task.html 
sidebar: sidebar 
keywords: restore, part, file, snapshot copy 
summary: 'Mit dem Befehl `volume snapshot partial-restore-file` kann ein Datenbereich aus einem Snapshot auf eine LUN oder in eine NFS- oder SMB-Containerdatei wiederhergestellt werden, sofern der Startbyte-Offset der Daten und die Byte-Anzahl bekannt sind. Dieser Befehl kann beispielsweise genutzt werden, um eine der Datenbanken auf einem Host wiederherzustellen, der mehrere Datenbanken in derselben LUN speichert.' 
---
= Einen Teil einer Datei aus einem ONTAP Snapshot wiederherstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den  `volume snapshot partial-restore-file` Befehl verwenden, um einen Datenbereich aus einem Snapshot auf eine LUN oder in eine NFS- oder SMB-Containerdatei wiederherzustellen, sofern der Startbyte-Offset der Daten und die Byte-Anzahl bekannt sind. Dieser Befehl kann beispielsweise genutzt werden, um eine der Datenbanken auf einem Host wiederherzustellen, der mehrere Datenbanken in derselben LUN speichert.

Ab ONTAP 9.12.1 ist die teilweise Wiederherstellung für Volumes mit xref:../snapmirror-active-sync/index.html[SnapMirror Active Sync] verfügbar.

.Schritte
. Snapshots in einem Volume auflisten:
+
`volume snapshot show -vserver _SVM_ -volume _volume_`

+
Weitere Informationen zu  `volume snapshot show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-show.html["ONTAP-Befehlsreferenz"^].

+
Das folgende Beispiel zeigt die Momentaufnahmen in `vol1`:

+
[listing]
----

clus1::> volume snapshot show -vserver vs1 -volume vol1

Vserver Volume Snapshot                State    Size  Total% Used%
------- ------ ---------- ----------- ------   -----  ------ -----
vs1	    vol1   hourly.2013-01-25_0005  valid   224KB     0%    0%
               daily.2013-01-25_0010   valid   92KB      0%    0%
               hourly.2013-01-25_0105  valid   228KB     0%    0%
               hourly.2013-01-25_0205  valid   236KB     0%    0%
               hourly.2013-01-25_0305  valid   244KB     0%    0%
               hourly.2013-01-25_0405  valid   244KB     0%    0%
               hourly.2013-01-25_0505  valid   244KB     0%    0%

7 entries were displayed.
----
. Einen Teil einer Datei aus einem Snapshot wiederherstellen:
+
`volume snapshot partial-restore-file -vserver _SVM_ -volume _volume_ -snapshot _snapshot_ -path _file_path_ -start-byte _starting_byte_ -byte-count _byte_count_`

+
Der Startbyte-Offset und die Byteanzahl müssen Vielfache von 4.096 sein.

+
Das folgende Beispiel stellt die ersten 4096 Bytes der Datei  `myfile.txt` wieder her:

+
[listing]
----
cluster1::> volume snapshot partial-restore-file -vserver vs0 -volume vol1 -snapshot daily.2013-01-25_0010 -path /myfile.txt -start-byte 0 -byte-count 4096
----

