---
permalink: data-protection/restore-single-file-snapshot-task.html 
sidebar: sidebar 
keywords: restore, single file, snapshot copy 
summary: Sie können den Befehl zum Wiederherstellen der Datei eines Volume-Snapshots verwenden, um eine einzelne Datei oder LUN aus einem Snapshot wiederherzustellen. Sie können die Datei an einem anderen Speicherort im übergeordneten Datenträger mit Lese- und Schreibvorgängen wiederherstellen, wenn Sie eine vorhandene Datei nicht ersetzen möchten. 
---
= Stellen Sie eine einzelne Datei aus einem ONTAP-Snapshot wieder her
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit dem Befehl können Sie `volume snapshot restore-file` eine einzelne Datei oder LUN aus einem Snapshot wiederherstellen. Sie können die Datei an einem anderen Speicherort im übergeordneten Datenträger mit Lese- und Schreibvorgängen wiederherstellen, wenn Sie eine vorhandene Datei nicht ersetzen möchten.

.Über diese Aufgabe
Wenn Sie eine vorhandene LUN wiederherstellen, wird ein LUN-Klon erstellt und in Form eines Snapshots gesichert. Während des Wiederherstellungsvorgangs können Sie von lesen und auf die LUN schreiben.

Dateien mit Streams werden standardmäßig wiederhergestellt.

.Schritte
. Listen Sie die Snapshots in einem Volume auf:
+
`volume snapshot show -vserver _SVM_ -volume _volume_`

+
Erfahren Sie mehr über `volume snapshot show` in der link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-show.html["ONTAP-Befehlsreferenz"^].

+
Das folgende Beispiel zeigt die Snapshots in `vol1`:

+
[listing]
----

clus1::> volume snapshot show -vserver vs1 -volume vol1

Vserver Volume Snapshot                State    Size  Total% Used%
------- ------ ---------- ----------- ------   -----  ------ -----
vs1	    vol1   hourly.2013-01-25_0005  valid   224KB     0%    0%
               daily.2013-01-25_0010   valid   92KB      0%    0%
               hourly.2013-01-25_0105  valid   228KB     0%    0%
               hourly.2013-01-25_0205  valid   236KB     0%    0%
               hourly.2013-01-25_0305  valid   244KB     0%    0%
               hourly.2013-01-25_0405  valid   244KB     0%    0%
               hourly.2013-01-25_0505  valid   244KB     0%    0%

7 entries were displayed.
----
. Wiederherstellen einer Datei aus einem Snapshot:
+
`volume snapshot restore-file -vserver _SVM_ -volume _volume_ -snapshot _snapshot_ -path _file_path_ -restore-path _destination_path_`

+
Erfahren Sie mehr über `volume snapshot restore-file` in der link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-restore-file.html["ONTAP-Befehlsreferenz"^].

+
Das folgende Beispiel stellt die Datei wieder her `myfile.txt`:

+
[listing]
----
cluster1::> volume snapshot restore-file -vserver vs0 -volume vol1 -snapshot daily.2013-01-25_0010 -path /myfile.txt
----

