---
permalink: data-protection/restore-single-file-lun-task.html 
sidebar: sidebar 
keywords: restore, single file, lun, nvme, namespace, snapmirror, destination, snapshot, copy, snap mirror, baseline, 
summary: Sie können eine einzelne Datei, eine LUN, eine Gruppe von Dateien oder LUNs aus einer Snapshot Kopie oder einen NVMe Namespace über ein SnapMirror Ziel-Volume wiederherstellen. Ab ONTAP 9.7 können auch NVMe-Namespaces von einem synchronen SnapMirror-Ziel wiederhergestellt werden. Sie können Dateien auf dem ursprünglichen Quell-Volume oder auf einem anderen Volume wiederherstellen. 
---
= Mit ONTAP kann eine einzelne Datei, eine LUN oder ein NVMe Namespace über ein SnapMirror Ziel wiederhergestellt werden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine einzelne Datei, eine LUN, eine Gruppe von Dateien oder LUNs aus einer Snapshot Kopie oder einen NVMe Namespace über ein SnapMirror Ziel-Volume wiederherstellen. Ab ONTAP 9.7 können auch NVMe-Namespaces von einem synchronen SnapMirror-Ziel wiederhergestellt werden. Sie können Dateien auf dem ursprünglichen Quell-Volume oder auf einem anderen Volume wiederherstellen.

.Was Sie benötigen
Um eine Datei oder LUN von einem synchronen SnapMirror-Ziel wiederherzustellen (unterstützt ab ONTAP 9.5), müssen Sie zuerst die Beziehung löschen und freigeben.

.Über diese Aufgabe
Das Volume, auf dem Sie Dateien oder LUNs wiederherstellen (das Zielvolume), muss ein Lese-/Schreib-Volume sein:

* SnapMirror führt eine _inkrementelle Wiederherstellung durch_, wenn die Quell- und Ziel-Volumes eine gemeinsame Snapshot Kopie aufweisen (wie normalerweise bei der Wiederherstellung des ursprünglichen Quell-Volumes der Fall ist).
* Anderenfalls führt SnapMirror eine _Baseline Restore_ durch, bei der die angegebene Snapshot Kopie und alle Datenblöcke, auf die sie Bezug nehmen, an das Ziel-Volume übertragen werden.


.Schritte
. Auflisten der Snapshot Kopien auf dem Ziel-Volume:
+
`volume snapshot show -vserver <SVM> -volume volume`

+
Erfahren Sie mehr über `volume snapshot show` in der link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-show.html["ONTAP-Befehlsreferenz"^].

+
Im folgenden Beispiel werden die Snapshot Kopien auf dem `vserverB:secondary1` Ziel angezeigt:

+
[listing]
----

cluster_dst::> volume snapshot show -vserver vserverB -volume secondary1

Vserver     Volume      Snapshot                State    Size  Total% Used%
-------     ------      ---------- ----------- ------   -----  ------ -----
vserverB    secondary1  hourly.2013-01-25_0005  valid   224KB     0%    0%
                        daily.2013-01-25_0010   valid   92KB      0%    0%
                        hourly.2013-01-25_0105  valid   228KB     0%    0%
                        hourly.2013-01-25_0205  valid   236KB     0%    0%
                        hourly.2013-01-25_0305  valid   244KB     0%    0%
                        hourly.2013-01-25_0405  valid   244KB     0%    0%
                        hourly.2013-01-25_0505  valid   244KB     0%    0%

7 entries were displayed.
----
. Wiederherstellung einer einzelnen Datei oder einer LUN oder eines Satzes von Dateien oder LUNs aus einer Snapshot Kopie in einem SnapMirror Ziel-Volume:
+
`snapmirror restore -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ... -source-snapshot snapshot -file-list <source_file_path,@destination_file_path>`

+
Erfahren Sie mehr über `snapmirror restore` in der link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-restore.html["ONTAP-Befehlsreferenz"^].

+
[NOTE]
====
Sie müssen diesen Befehl über die Ziel-SVM oder das Ziel-Cluster ausführen.

====
+
Mit dem folgenden Befehl werden die Dateien `file1` und `file2` die Snapshot-Kopie `daily.2013-01-25_0010` des ursprünglichen Zieldatenträgers `secondary1` an demselben Ort im aktiven Dateisystem des ursprünglichen Quelldatenträgers wiederhergestellt `primary1`:

+
[listing]
----

cluster_dst::> snapmirror restore -source-path vserverB:secondary1 -destination-path vserverA:primary1 -source-snapshot daily.2013-01-25_0010 -file-list /dir1/file1,/dir2/file2

[Job 3479] Job is queued: snapmirror restore for the relationship with destination vserverA:primary1
----
+
Mit dem folgenden Befehl werden die Dateien `file1` und `file2` die Snapshot-Kopie `daily.2013-01-25_0010` im ursprünglichen Zielvolume `secondary1` an einem anderen Ort im aktiven Dateisystem des ursprünglichen Quellvolume wiederhergestellt `primary1`.

+
Der Zieldateipfad beginnt mit dem Symbol @, gefolgt vom Pfad der Datei aus dem Stammverzeichnis des ursprünglichen Quell-Volumes. In diesem Beispiel `file1` wird in wiederhergestellt `/dir1/file1.new`, und file2 wird wiederhergestellt auf `/dir2.new/file2` `primary1`:

+
[listing]
----

cluster_dst::> snapmirror restore -source-path vserverB:secondary1 -destination-path vserverA:primary1 -source-snapshot daily.2013-01-25_0010 -file-list /dir/file1,@/dir1/file1.new,/dir2/file2,@/dir2.new/file2

[Job 3479] Job is queued: snapmirror restore for the relationship with destination vserverA:primary1
----
+
Mit dem folgenden Befehl werden die Dateien `file1` und `file3` von der Snapshot-Kopie `daily.2013-01-25_0010` im ursprünglichen Zielvolume `secondary1` an verschiedenen Orten im aktiven Dateisystem des ursprünglichen Quellvolume `primary1` wiederhergestellt und `file2` von `snap1` an demselben Ort im aktiven Dateisystem von wiederhergestellt `primary1`.

+
In diesem Beispiel `file1` wird die Datei wiederhergestellt `/dir1/file1.new` und `file3` wiederhergestellt in `/dir3.new/file3`:

+
[listing]
----

cluster_dst::> snapmirror restore -source-path vserverB:secondary1 -destination-path vserverA:primary1 -source-snapshot daily.2013-01-25_0010 -file-list /dir/file1,@/dir1/file1.new,/dir2/file2,/dir3/file3,@/dir3.new/file3

[Job 3479] Job is queued: snapmirror restore for the relationship with destination vserverA:primary1
----

