---
permalink: data-protection/restore-svm-root-volume-promote-mirror-task.html 
sidebar: sidebar 
keywords: promote, load-sharing, mirror 
summary: 'Wenn ein Root-Volume dauerhaft nicht verfügbar ist, kann das Load-Sharing Mirror (LSM) Volume hochgestuft werden, um Schreibzugriff auf die Daten des Root-Volumes bereitzustellen.' 
---
= Eine ONTAP Load-Sharing Mirror befördern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ein Root-Volume dauerhaft nicht verfügbar ist, kann das Load-Sharing Mirror (LSM) Volume hochgestuft werden, um Schreibzugriff auf die Daten des Root-Volumes bereitzustellen.

.Bevor Sie beginnen
Für diese Aufgabe müssen Sie Befehle auf dem erweiterten Berechtigungsniveau verwenden.

.Schritte
. Wechsel zum erweiterten Berechtigungslevel:
+
[source, cli]
----
set -privilege advanced
----
. Ein LSM-Volumen promoten:
+
Vor dem Ausführen dieses Befehls sind die Variablen in spitzen Klammern durch die erforderlichen Werte zu ersetzen.

+
[source, cli]
----
snapmirror promote -destination-path <SVM:volume>
----
+
Im folgenden Beispiel wird das Volume `svm1_m2` als neues SVM Root Volume festgelegt:

+
[listing]
----
cluster_src::*> snapmirror promote -destination-path svm1:svm1_m2

Warning: Promote will delete the offline read-write volume
         cluster_src://svm1/svm1_root and replace it with
         cluster_src://svm1/svm1_m2. Because the volume is offline,
         it is not possible to determine whether this promote will
         affect other relationships associated with this source.
Do you want to continue? {y|n}: y
----
+
Drücken Sie  `y`. ONTAP macht das LSM-Volume zu einem lesen/schreiben-Volume und löscht das ursprüngliche Root-Volume, falls dieses zugänglich ist.

+
[NOTE]
====
Das neu hochgestufte Root-Volume enthält möglicherweise nicht alle Daten, die sich im ursprünglichen Root-Volume befanden, wenn die letzte Aktualisierung nicht kürzlich erfolgte.

====
+
Weitere Informationen zu  `snapmirror promote` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-promote.html["ONTAP-Befehlsreferenz"^].

. Zurück zur Administrator-Berechtigungsebene:
+
[source, cli]
----
set -privilege admin
----
. Das hochgestufte Volume ist gemäß der Namenskonvention umzubenennen, die für das Root-Volume verwendet wurde:
+
Vor dem Ausführen dieses Befehls sind die Variablen in spitzen Klammern durch die erforderlichen Werte zu ersetzen.

+
[source, cli]
----
volume rename -vserver <SVM> -volume <volume> -newname <new_name>
----
+
Im folgenden Beispiel wird das hochgestufte Volume `svm1_m2` mit dem Namen `svm1_root` umbenannt:

+
[listing]
----
cluster_src::> volume rename -vserver svm11 -volume svm1_m2 -newname svm1_root
----
. Das umbenannte Root-Volume wird geschützt, wie in Schritt 3 bis Schritt 4 in link:create-load-sharing-mirror-task.html["Erstellen und Initialisieren von Load-Sharing Mirror-Beziehungen"] beschrieben.

