---
permalink: data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html 
sidebar: sidebar 
keywords: snapmirror, synchronous, disaster, recovery 
summary: 'Ab ONTAP 9.5 wird SnapMirror Synchronous (SM-S) Technologie auf allen FAS und AFF Plattformen mit mindestens 16 GB Arbeitsspeicher sowie auf allen ONTAP Select Plattformen unterstützt. Die SnapMirror Synchronous Technologie ist eine pro Node lizenzierte Funktion zur synchronen Datenreplizierung auf Volume-Ebene.' 
---
= Grundlagen von SnapMirror Synchronous Disaster Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.5 wird SnapMirror Synchronous (SM-S) Technologie auf allen FAS und AFF Plattformen mit mindestens 16 GB Arbeitsspeicher sowie auf allen ONTAP Select Plattformen unterstützt. Die SnapMirror Synchronous Technologie ist eine pro Node lizenzierte Funktion zur synchronen Datenreplizierung auf Volume-Ebene.

Diese Funktionalität ist sowohl den gesetzlichen als auch den nationalen Vorgaben für synchrone Replizierung in Finanz-, Gesundheitswesen und anderen Branchen gerecht, in denen Datenverluste nicht erforderlich sind.

Die Obergrenze der Anzahl der synchronen SnapMirror Replizierungsvorgänge pro HA-Paar hängt vom Controller-Modell ab.

In der folgenden Tabelle ist die Anzahl der synchronen SnapMirror Vorgänge aufgeführt, die pro HA-Paar entsprechend dem Plattformtyp und ONTAP Release zulässig sind.

|===


| Plattform | Versionen vor ONTAP 9.9.1 | ONTAP 9.9.1 | ONTAP 9.10.1 | ONTAP 9.11.1 bis ONTAP 9.14.1 


 a| 
AFF
 a| 
80
 a| 
160
 a| 
200
 a| 
400



 a| 
ASA
 a| 
80
 a| 
160
 a| 
200
 a| 
400



 a| 
FAS
 a| 
40
 a| 
80
 a| 
80
 a| 
80



 a| 
ONTAP Select
 a| 
20
 a| 
40
 a| 
40
 a| 
40

|===


== Unterstützte Funktionen

In der folgenden Tabelle sind die Funktionen aufgeführt, die von SnapMirror Synchronous und den ONTAP Versionen unterstützt werden, in denen Unterstützung verfügbar ist.

[cols="3,1,4"]
|===


| Merkmal | Release wird zuerst unterstützt | Weitere Informationen 


| Antivirus auf dem primären Volume der SnapMirror Synchronous Beziehung | ONTAP 9.6 |  


| Replizierung von applikationserstellten Snapshot Kopien | ONTAP 9.7 | Wenn eine Snapshot Kopie zum Zeitpunkt der mit der entsprechenden Beschriftung versehen wird `snapshot create` Betrieb SnapMirror Synchronous repliziert über die CLI oder die ONTAP-API die Snapshot Kopien, sowohl von Benutzern als auch mit externen Skripts erstellt, nachdem die Applikationen stillgelegt wurden. Geplante Snapshot Kopien, die unter Verwendung einer Snapshot Richtlinie erstellt wurden, werden nicht repliziert. Weitere Informationen zum Replizieren von von durch Applikationen erstellten Snapshot-Kopien finden Sie im Knowledge Base-Artikel: link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/How_to_replicate_application_created_snapshots_with_SnapMirror_Synchronous["Wie repliziert man Snapshots von Anwendungen mit SnapMirror Synchronous"^]. 


| Automatisches Löschen von Klonen | ONTAP 9.6 |  


| FabricPool Aggregate mit einer Tiering-Richtlinie von „Keine“, „Snapshot“ oder „automatisch“ werden von SnapMirror Synchronous Quell- und Zielsystem unterstützt. | ONTAP 9.5 | Das Ziel-Volume in einem FabricPool-Aggregat kann nicht auf „Alle Tiering-Richtlinien“ gesetzt werden. 


| FC | ONTAP 9.5 | Über alle Netzwerke, bei denen die Latenz nicht mehr als 10 ms beträgt 


| FC-NVMe | ONTAP 9.7 |  


| FPolicy für das primäre Volume der SnapMirror Synchronous Beziehung | ONTAP 9.6 |  


| Hard- und Soft-Quoten auf dem primären Volume der SnapMirror Synchronous Beziehung | ONTAP 9.6 | Die Quota-Regeln werden nicht auf das Ziel repliziert, daher wird die Quota-Datenbank nicht auf das Ziel repliziert. 


| ISCSI | ONTAP 9.5 |  


| LUN-Klone und NVMe Namespace-Klone | ONTAP 9.7 |  


| LUN-Klone, die durch applikationserstellte Snapshot Kopien gesichert werden | ONTAP 9.7 |  


| Zugriff auf gemischte Protokolle (NFS v3 und SMB) | ONTAP 9.6 |  


| NDMP/NDMP-Wiederherstellung | ONTAP 9.13.1 | Sowohl auf dem Quell- als auch auf dem Zielcluster muss ONTAP 9.13.1 oder höher ausgeführt werden, um NDMP mit SnapMirror Synchronous zu verwenden. Weitere Informationen finden Sie unter xref:../tape-backup/transfer-data-ndmpcopy-task.html[Datenübertragung mithilfe einer ndmp-Kopie]. 


| Unterbrechungsfreier SnapMirror Synchronous Operations (NDO) nur für AFF/ASA-Plattformen | ONTAP 9.12.1 | Dank der Support-Funktion für unterbrechungsfreien Betrieb können Sie viele gängige Wartungsaufgaben ohne Ausfallzeiten durchführen. Zu den unterstützten Vorgängen gehören Takeover und Giveback. Außerdem werden Volumes verschoben, sofern zwischen jedem der beiden Cluster ein einziger Node übrigbleibt. 


| NFS v4.2 | ONTAP 9.10.1 |  


| NFS v4.3 | ONTAP 9.5 |  


| NFS Version 4.0 | ONTAP 9.6 |  


| NFS 4.1 | ONTAP 9.6 |  


| NVMe/TCP | 9.10.1 |  


| Entfernung hoher Metadaten Frequenzbegrenzung | ONTAP 9.6 |  


| Sicherheit für sensible Daten während der Übertragung mithilfe von TLS 1.2-Verschlüsselung | ONTAP 9.6 |  


| Wiederherstellung einzelner Dateien und teilweise Dateien | ONTAP 9.13.1 |  


| SMB 2.0 oder höher | ONTAP 9.6 |  


| SnapMirror Kaskadenspiegelung mit synchroner Spiegelung | ONTAP 9.6 | Die Beziehung zum Ziel-Volume der SnapMirror Synchronous Beziehung muss eine asynchrone SnapMirror-Beziehung sein. 


| Disaster Recovery für SVM | ONTAP 9.6 | * Eine SnapMirror Synchronous Quelle kann auch eine SVM Disaster-Recovery-Quelle sein, zum Beispiel eine Fan-out-Konfiguration mit SnapMirror Synchronous als ein Bein und SVM Disaster Recovery als der andere.

* Eine SnapMirror Synchronous Quelle kann kein SVM Disaster-Recovery-Ziel sein, da SnapMirror Synchronous keine Kaskadierung einer Datensicherungsquelle unterstützt.
Sie müssen die synchrone Beziehung freigeben, bevor Sie eine SVM-Disaster-Recovery-Flip-Resynchronisierung im Ziel-Cluster durchführen.

* Ein SnapMirror Synchronous Ziel kann keine SVM Disaster-Recovery-Quelle sein, da SVM Disaster Recovery keine Replikation von DP-Volumes unterstützt.
Eine Flip-Resynchronisierung der synchronen Quelle würde eine Disaster Recovery der SVM mit Ausnahme des DP-Volumes im Ziel-Cluster zur Folge haben. 


| Zeitstempel der Parität zwischen Quell- und Ziel-Volumes für NAS | ONTAP 9.6 | Wenn Sie ein Upgrade von ONTAP 9.5 auf ONTAP 9.6 durchgeführt haben, wird der Zeitstempel nur für neue und geänderte Dateien im Quell-Volume repliziert. Der Zeitstempel vorhandener Dateien im Quell-Volume wird nicht synchronisiert. 
|===


== Nicht unterstützte Funktionen

Die folgenden Funktionen werden nicht mit synchronen SnapMirror Beziehungen unterstützt:

* Konsistenzgruppen
* DP_Optimized (DPO)-Systeme
* FlexGroup Volumes
* FlexCache Volumes
* Globale Drosselung
* In einer Fan-out-Konfiguration kann nur eine Beziehung eine SnapMirror synchrone Beziehung sein. Alle anderen Beziehungen des Quell-Volumes müssen asynchrone SnapMirror Beziehungen sein.
* LUN-Verschiebung
* LUN-Klon/Datei-Klon
* MetroCluster Konfigurationen
* LUNs mit gemischten SAN- und NVMe-Zugriffs sowie NVMe Namespaces werden nicht auf demselben Volume oder derselben SVM unterstützt.
* SnapCenter
* SnapLock Volumes
* Manipulationssichere Snapshot Kopien
* Tape Backup oder Wiederherstellung mithilfe von Dump und SMTape auf dem Ziel-Volume
* Tape-basierte Wiederherstellung auf dem Quell-Volume
* Durchsatzboden (QoS Min.) für Quell-Volumes
* Volume SnapRestore
* VVol




== Betriebsmodi

SnapMirror Synchronous verfügt über zwei Betriebsmodi, abhängig vom Typ der verwendeten SnapMirror-Richtlinie:

* *Sync-Modus* im Sync-Modus werden Applikations-I/O-Vorgänge parallel zu den primären und sekundären Speichersystemen gesendet. Wenn der Schreibvorgang auf dem sekundären Storage aus irgendeinem Grund nicht abgeschlossen wird, kann die Applikation das Schreiben auf den primären Storage fortsetzen. Wenn die Fehlerbedingung korrigiert wird, werden SnapMirror Synchronous Technologie automatisch mit dem sekundären Storage neu synchronisiert und die Replizierung vom primären Speicher zum sekundären Storage im synchronen Modus fortgesetzt. Im synchronen Modus ist RPO=0 und RTO sehr niedrig, bis ein sekundärer Replizierungsausfall auftritt. RPO und RTO sind nicht bestimmt, entsprechen aber der Zeit zur Behebung des Problems, das zum Scheitern der sekundären Replizierung und zum Abschluss der Resync-Synchronisierung geführt hat.
* *StrictSync-Modus* SnapMirror Synchronous kann optional im StrictSync-Modus betrieben werden. Wenn der Schreibvorgang auf den sekundären Storage aus irgendeinem Grund nicht abgeschlossen wird, fällt der Applikations-I/O aus. Dadurch wird sichergestellt, dass der Primär- und der Sekundärspeicher identisch sind. Der Applikations-I/O zum primären System wird erst wieder aufgenommen, nachdem die SnapMirror Beziehung wieder auf zurückkehrt `InSync` Status: Falls der primäre Storage ausfällt, kann der Applikations-I/O nach dem Failover auf dem sekundären Storage fortgesetzt werden, ohne dass die Daten verloren gehen. Im Modus StrictSync ist die RPO immer null und die RTO ist sehr niedrig.




== Beziehungsstatus

Der Status einer SnapMirror Synchronous-Beziehung befindet sich immer im `InSync` Status während des normalen Betriebs. Wenn der SnapMirror Transfer aus irgendeinem Grund fehlschlägt, befindet sich das Ziel nicht im synchronen Modus mit der Quelle und kann mit dem fortfahren `OutofSync` Status:

Bei SnapMirror synchronen Beziehungen überprüft das System automatisch den Beziehungsstatus  `InSync` Oder `OutofSync`) In einem festen Intervall. Wenn der Beziehungsstatus lautet `OutofSync`, ONTAP löst automatisch den automatischen Resync-Prozess, um die Beziehung auf die zurückzubringen `InSync` Status: Die automatische Neusynchronisierung wird nur dann ausgelöst, wenn der Transfer aufgrund eines Vorgangs, z. B. ungeplanten Storage-Failover am Quell- oder Ziel-System oder aufgrund eines Netzwerkausfalls, ausfällt. Vom Benutzer initiierte Funktionen wie z. B. `snapmirror quiesce` Und `snapmirror break` Führen Sie keine automatische Neusynchronisierung durch.

Wenn der Beziehungsstatus lautet `OutofSync` Für eine SnapMirror Synchronous-Beziehung im StrictSync-Modus werden alle I/O-Vorgänge zum primären Volume angehalten. Der `OutofSync` Status für SnapMirror Synchronous-Beziehung im Sync-Modus verursacht keine Unterbrechung für das primäre Volume und I/O-Vorgänge sind auf dem primären Volume zulässig.

.Verwandte Informationen
http://www.netapp.com/us/media/tr-4733.pdf["Technischer Bericht 4733 von NetApp: SnapMirror Synchronous Configration und Best Practices"^]
