---
permalink: data-protection/snapmirror-licensing-concept.html 
sidebar: sidebar 
keywords: snapmirror, licensing, snapvault, vault, mirror, relationship, replication, backup, back up, disaster recovery, dr 
summary: Ab ONTAP 9.3 wurde die Lizenzierung für die Replizierung zwischen ONTAP Instanzen vereinfacht. In ONTAP 9 Versionen unterstützt die SnapMirror Lizenz sowohl Vault- als auch Mirror-Beziehungen. Benutzer können nun eine SnapMirror Lizenz erwerben, um ONTAP Replizierung für Anwendungsfälle wie Backup und Disaster Recovery zu unterstützen. 
---
= Übersicht über die SnapMirror Lizenzierung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.3 wurde die Lizenzierung für die Replizierung zwischen ONTAP Instanzen vereinfacht. In ONTAP 9 Versionen unterstützt die SnapMirror Lizenz sowohl Vault- als auch Mirror-Beziehungen. Sie können eine SnapMirror Lizenz verwenden, um ONTAP Replizierung für Backup- und Disaster-Recovery-Anwendungsfälle zu unterstützen.

Vor Version ONTAP 9.3 war eine separate SnapVault Lizenz erforderlich, um Vault Beziehungen zwischen ONTAP Instanzen zu konfigurieren, bei denen die DP-Instanz eine höhere Anzahl an Snapshot Kopien behalten konnte, um Backup-Anwendungsfälle mit längeren Aufbewahrungszeiten zu unterstützen. außerdem wurde eine SnapMirror Lizenz benötigt, um Beziehungen zwischen ONTAP-Instanzen zu konfigurieren _mirror_, wobei jede ONTAP Instanz dieselbe Anzahl an Snapshot-Kopien beibehalten würde (d. h. ein _mirror_ Image), um Disaster-Recovery-Anwendungsfälle zu unterstützen, um einen Cluster-Failover zu ermöglichen. Sowohl SnapMirror als auch SnapVault Lizenzen werden weiterhin verwendet und werden von den Versionen ONTAP 8.x und 9.x unterstützt.

SnapVault Lizenzen funktionieren weiterhin und werden sowohl für ONTAP 8.x- als auch für 9.x-Versionen unterstützt. Die SnapMirror Lizenz kann anstelle einer SnapVault Lizenz verwendet werden und kann sowohl für Spiegelungs- als auch für Vault-Konfigurationen verwendet werden.

Für die asynchrone Replizierung von ONTAP wird ab ONTAP 9.3 eine einzelne Unified Replication Engine zur Konfiguration von Richtlinien für den erweiterten Datensicherungsmodus (XDP) verwendet. Dabei kann die SnapMirror Lizenz für eine Spiegelrichtlinie, eine Vault-Richtlinie oder eine Mirror-Vault-Richtlinie konfiguriert werden. Es ist eine SnapMirror Lizenz auf den Quell- und Ziel-Clustern erforderlich. Wenn bereits eine SnapMirror Lizenz installiert ist, ist keine SnapVault Lizenz erforderlich. Die zeitlich unbegrenzte SnapMirror Lizenz ist in der ONTAP One Softwaresuite enthalten, die auf den neuen AFF und FAS Systemen installiert ist.

Einschränkungen für die Datensicherungskonfiguration werden unter Verwendung verschiedener Faktoren bestimmt, einschließlich Ihrer ONTAP Version, Hardware-Plattform und der installierten Lizenzen. Weitere Informationen finden Sie unter https://hwu.netapp.com/["Hardware Universe"^].



== SnapMirror Synchronous Lizenz

Ab ONTAP 9.5 werden SnapMirror Synchronous Beziehungen unterstützt. Für die Erstellung einer SnapMirror Synchronous-Beziehung benötigen Sie die folgenden Lizenzen:

* Die SnapMirror Synchronous Lizenz ist sowohl auf dem Quell-Cluster als auch auf dem Ziel-Cluster erforderlich.
+
Die SnapMirror Synchronous Lizenz ist Teil der https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["ONTAP One Lizenzsuite"].

+
Wenn Ihr System vor Juni 2019 mit einem Premium oder Flash Bundle erworben wurde, können Sie einen NetApp Master Key herunterladen, um die erforderliche SnapMirror Synchronous Lizenz von der NetApp Support Website zu erhalten: https://mysupport.netapp.com/NOW/knowledge/docs/olio/guides/master_lickey/["Master-Lizenzschlüssel"].

* Die SnapMirror Lizenz ist sowohl auf dem Quell-Cluster als auch auf dem Ziel-Cluster erforderlich.




== SnapMirror Cloud Lizenz

Ab ONTAP 9.8 ermöglicht die SnapMirror Cloud Lizenz die asynchrone Replizierung von Snapshot Kopien von ONTAP Instanzen in Objekt-Storage-Endpunkte. Replizierungsziele können unter Verwendung von On-Premises-Objektspeichern sowie S3- und S3-kompatiblen Public-Cloud-Objekt-Storage-Services konfiguriert werden. SnapMirror Cloud Beziehungen werden von ONTAP Systemen auf vorkonfigurierte Objekt-Storage-Ziele unterstützt.

SnapMirror Cloud ist nicht als Standalone-Lizenz verfügbar. Pro ONTAP Cluster ist nur eine Lizenz erforderlich. Zusätzlich zu einer SnapMirror Cloud Lizenz ist auch die asynchrone SnapMirror Lizenz erforderlich.

Für den Aufbau einer SnapMirror Cloud-Beziehung benötigen Sie die folgenden Lizenzen:

* Sowohl eine SnapMirror Lizenz als auch eine SnapMirror Cloud Lizenz zur direkten Replizierung auf den Objektspeicher-Endpunkt.
* Bei der Konfiguration eines Workflows für die Replizierung mehrerer Richtlinien (z. B. Disk-to-Disk-to-Cloud) ist für alle ONTAP Instanzen eine SnapMirror Lizenz erforderlich, während die SnapMirror Cloud Lizenz nur für das Quellcluster erforderlich ist, das sich direkt auf den Objekt-Storage-Endpunkt repliziert.


Ab ONTAP 9.9 ist dies möglich https://docs.netapp.com/us-en/ontap/task_dp_back_up_to_cloud.html["Verwenden Sie System Manager für die SnapMirror Cloud-Replizierung"].

Eine Liste autorisierter SnapMirror Cloud Applikationen von Drittanbietern wird auf der NetApp Website veröffentlicht.

DPO-Lizenzen (Data Protection Optimized) werden nicht mehr verkauft und DPO wird auf aktuellen Plattformen nicht unterstützt. Wenn Sie jedoch eine DPO-Lizenz auf einer unterstützten Plattform installiert haben, bietet NetApp bis zum Ende der Verfügbarkeit dieser Plattform weiterhin Support.

DPO ist nicht im ONTAP One-Lizenzpaket enthalten, und Sie können kein Upgrade auf das ONTAP One-Lizenzpaket durchführen, wenn die DPO-Lizenz auf einem System installiert ist.

Informationen zu unterstützten Plattformen finden Sie unter https://hwu.netapp.com/["Hardware Universe"^].
