---
permalink: data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html 
sidebar: sidebar 
keywords: snapmirror, synchronous, disaster, recovery 
summary: 'Ab ONTAP 9.5 wird SnapMirror synchron (SM-S) Technologie auf allen FAS und AFF Plattformen mit mindestens 16 GB Arbeitsspeicher sowie auf allen ONTAP Select Plattformen unterstützt. Die SnapMirror synchron Technologie ist eine lizenzpflichtige Funktion pro Node, die synchrone Datenreplizierung auf Volume-Ebene bereitstellt.' 
---
= Informationen zu ONTAP SnapMirror synchroner Disaster Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.5 wird SnapMirror synchron (SM-S) Technologie auf allen FAS und AFF Plattformen mit mindestens 16 GB Arbeitsspeicher sowie auf allen ONTAP Select Plattformen unterstützt. Die SnapMirror synchron Technologie ist eine lizenzpflichtige Funktion pro Node, die synchrone Datenreplizierung auf Volume-Ebene bereitstellt.

Diese Funktionalität erfüllt die regulatorischen und nationalen Vorgaben für synchrone Replizierung im Finanzwesen, im Gesundheitswesen und anderen regulierten Branchen, in denen kein Datenverlust zulässig ist.



[[snapmirror-synchronous-operations-allowed]]
== SnapMirror synchron Operationen zulässig

Das Limit für die Anzahl der SnapMirror synchronen Replizierungsvorgänge pro HA-Paar hängt vom Controller-Modell ab.

Die folgende Tabelle listet die Anzahl der SnapMirror synchronen Operationen auf, die pro HA-Paar je nach Plattformtyp und ONTAP Version zulässig sind.

|===


| Plattform | ONTAP 9.14.1 bis ONTAP 9.11.1 | ONTAP 9.10.1 | ONTAP 9.9.1 | Versionen vor ONTAP 9.9.1 


 a| 
AFF
 a| 
400
 a| 
200
 a| 
160
 a| 
80



 a| 
ASA
 a| 
400
 a| 
200
 a| 
160
 a| 
80



 a| 
FAS
 a| 
80
 a| 
80
 a| 
80
 a| 
40



 a| 
ONTAP Select
 a| 
40
 a| 
40
 a| 
40
 a| 
20

|===


[[supported-features]]
== Unterstützte Funktionen

Die folgende Tabelle zeigt die mit SnapMirror synchron unterstützten Funktionen und die ONTAP Versionen, in denen diese Unterstützung verfügbar ist.

[cols="3,1,4"]
|===


| Funktion | Erste unterstützte Release | Weitere Informationen 


| Antivirus auf dem primären Volume der SnapMirror synchronen Beziehung | ONTAP 9.6 |  


| Replikation von anwendungserstellten Snapshots | ONTAP 9.7 | Wenn ein Snapshot zum Zeitpunkt der  `snapshot create` Operation über die CLI oder die ONTAP API mit dem entsprechenden Label versehen wird, repliziert SnapMirror synchron die Snapshots – sowohl benutzererstellte als auch solche, die mit externen Skripten erstellt wurden – nach dem Quiescing der Anwendungen. Ab ONTAP 9.14.1 ist die Label-Anforderung für die Replikation von anwendungserstellten Snapshots nicht mehr erforderlich. Weitere Informationen zur Replikation von anwendungserstellten Snapshots finden Sie unter link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/How_to_replicate_application_created_snapshots_with_SnapMirror_Synchronous["NetApp Knowledge Base: Wie sich von Anwendungen erstellte Snapshots mit SnapMirror synchron replizieren lassen"^]. 


| Autonomer Ransomware-Schutz | ONTAP 9.19.1 |  


| Automatisches Löschen von Klonen | ONTAP 9.6 |  


| FabricPool Aggregate mit den Tiering-Richtlinien Keine, Snapshot oder Auto werden mit SnapMirror synchronem Quell- und Ziel-Cluster unterstützt. | ONTAP 9.5 | Das Zielvolumen in einem FabricPool Aggregat kann nicht auf die Tiering-Policy „All“ eingestellt werden. 


| FC | ONTAP 9.5 | Über alle Netzwerke, bei denen die Latenz 10 ms nicht überschreitet 


| FC-NVMe | ONTAP 9.7 |  


| Dateiklone | ONTAP 9.7 |  


| FPolicy auf dem primären Volume der SnapMirror synchronen Beziehung | ONTAP 9.6 |  


| Harte und weiche Quoten für das primäre Volumen der SnapMirror synchronen Beziehung | ONTAP 9.6 | Die Quotenregeln werden nicht an den Ziel-Cluster repliziert; daher wird die Quoten-Datenbank nicht an den Ziel-Cluster repliziert. 


| Intracluster synchron Beziehungen | ONTAP 9.14.1 | Hochverfügbarkeit wird gewährleistet, wenn Quell- und Ziel-Volumes auf unterschiedlichen HA-Paaren platziert werden. Wenn der gesamte Cluster ausfällt, ist der Zugriff auf die Volumes erst nach der Wiederherstellung des Clusters wieder möglich. Intra-Cluster-SnapMirror-synchrone Beziehungen tragen zur Gesamtgrenze der gleichzeitigen xref:SnapMirror synchronous operations allowed[Beziehungen pro HA Paar] bei. 


| iSCSI | ONTAP 9.5 |  


| LUN-Klone und NVMe-Namespace-Klone | ONTAP 9.7 |  


| LUN-Klone, die durch von Anwendungen erstellte Snapshots unterstützt werden | ONTAP 9.7 |  


| Zugriff über gemischte Protokolle (NFS v3 und SMB) | ONTAP 9.6 |  


| NDMP/NDMP Wiederherstellung | ONTAP 9.13.1 | Sowohl der Quell- als auch der Ziel-Cluster müssen ONTAP 9.13.1 oder höher ausführen, um NDMP mit SnapMirror Synchronous zu verwenden. Weitere Informationen finden sich unter xref:../tape-backup/transfer-data-ndmpcopy-task.html[Daten mit ndmp copy übertragen]. 


| Unterbrechungsfreie SnapMirror synchron Operationen (NDO) nur auf AFF/ASA-Plattformen. | ONTAP 9.12.1 | Die Unterstützung unterbrechungsfreier Betriebsabläufe ermöglicht die Durchführung vieler gängiger Wartungsaufgaben ohne geplante Ausfallzeiten. Zu den unterstützten Vorgängen gehören Takeover und Giveback sowie Volume Move, vorausgesetzt, dass in jedem der beiden Cluster mindestens ein Node aktiv ist. 


| NFS v4.2 | ONTAP 9.10.1 |  


| NFS v4.0 | ONTAP 9.6 |  


| NFS v4.1 | ONTAP 9.6 |  


| NVMe/TCP | 9.10.1 |  


| Aufhebung der Beschränkung der hohen Metadaten-Operationsfrequenz | ONTAP 9.6 |  


| Replikation von Snapshot-Verwaltungsvorgängen | ONTAP 9.19.1 | Ab ONTAP 9.19.1 werden die Snapshot-Management-Operationen `snapshot delete`, `snapshot rename` und `snapshot modify` auf den sekundären Cluster repliziert. 


| Geplante Snapshot-Replikation | ONTAP 9.19.1 | Ab ONTAP 9.19.1 können Sie die Replikation geplanter Snapshots mithilfe einer SnapMirror-Richtlinie aktivieren. In Versionen vor ONTAP 9.19.1 werden geplante Snapshots, die mithilfe einer Snapshot-Richtlinie erstellt wurden, nicht repliziert. 


| Sicherheit für sensible Daten während der Übertragung mit TLS 1.2 Verschlüsselung | ONTAP 9.6 |  


| Wiederherstellung einzelner Dateien und teilweiser Dateiinhalte | ONTAP 9.13.1 |  


| SMB 2.0 oder höher | ONTAP 9.6 |  


| SnapMirror synchron Spiegel-Spiegel-Kaskade | ONTAP 9.6 | Die Beziehung vom Ziel-Volume der SnapMirror synchronen Beziehung muss eine SnapMirror asynchrone Beziehung sein. 


| SVM Disaster Recovery | ONTAP 9.6  a| 
* Eine SnapMirror synchron Quelle kann auch eine SVM Disaster Recovery Quelle sein, zum Beispiel eine Fan-Out-Konfiguration mit SnapMirror synchron als einem Zweig und SVM Disaster Recovery als dem anderen.
* Eine SnapMirror synchron Quelle kann nicht als SVM Disaster Recovery Ziel dienen, da SnapMirror synchron die Kaskadierung einer Datensicherungsquelle nicht unterstützt. Die synchron Beziehung muss aufgehoben werden, bevor eine SVM Disaster Recovery Flip Resynchronisierung im Ziel-Cluster durchgeführt wird.
* Ein SnapMirror synchrones Ziel kann keine SVM-Disaster-Recovery-Quelle sein, da die SVM-Disaster-Recovery die Replikation von DP Volumes nicht unterstützt. Eine Flip-Resynchronisierung der synchronen Quelle hätte zur Folge, dass die SVM-Disaster-Recovery das DP Volume im Ziel-Cluster ausschließt.




| link:../snaplock/snapshot-lock-concept.html["Manipulationssichere Schnappschüsse"] | ONTAP 9.19.1 | Die Ablaufzeit kann nur bei der Erstellung von Snapshots festgelegt werden. Sie können die Ablaufzeit für vorhandene Snapshots nicht festlegen oder verlängern. 


| Bandbasierte Wiederherstellung auf das Quellvolume | ONTAP 9.13.1 |  


| Zeitstempelparität zwischen Quell- und Ziel-Volumes für NAS | ONTAP 9.6 | Wenn Sie von ONTAP 9.5 auf ONTAP 9.6 aktualisiert haben, wird der Zeitstempel nur für neue und geänderte Dateien im Quell-Volume repliziert. Der Zeitstempel bereits vorhandener Dateien im Quell-Volume wird nicht synchronisiert. 
|===


[[unsupported-features]]
== Nicht unterstützte Funktionen

Folgende Funktionen werden bei SnapMirror synchronen Beziehungen nicht unterstützt:

* Konsistenzgruppen
* DP_Optimized (DPO) Systeme
* FlexGroup Volumes
* FlexCache Volumes
* Globale Drosselung
* In einer Fan-Out-Konfiguration kann nur eine Beziehung eine SnapMirror synchron Beziehung sein, alle anderen Beziehungen vom Quellvolume müssen SnapMirror asynchron Beziehungen sein.
* LUN-Verschiebung
* MetroCluster Konfigurationen
* Gemischte SAN- und NVMe-Zugriffs-LUNs und NVMe-Namespaces werden auf demselben Volume oder derselben SVM nicht unterstützt.
* SnapCenter
* SnapLock Volumes
* Bandsicherung oder Wiederherstellung mittels Dump und SMTape auf dem Ziel-Volume
* Mindestdurchsatz (QoS Min) für Quellvolumes
* Volume SnapRestore
* VVol




[[modes-of-operation]]
== Betriebsarten

SnapMirror synchron verfügt über zwei Betriebsmodi, basierend auf der Art der verwendeten SnapMirror Richtlinie:

* *Synchronmodus* Im Synchronmodus werden die E/A-Operationen der Anwendung parallel an das primäre und sekundäre Speichersystem gesendet. Wenn der Schreibvorgang auf dem sekundären Speicher aus irgendeinem Grund nicht abgeschlossen wird, kann die Anwendung weiterhin auf den primären Speicher schreiben. Wenn der Fehlerzustand behoben ist, synchronisiert die SnapMirror synchron Technologie sich automatisch mit dem sekundären Speicher und setzt die Replizierung vom primären zum sekundären Speicher im synchronen Modus fort. Im Synchronmodus gilt RPO=0 und RTO ist sehr niedrig, bis ein Fehler bei der sekundären Replizierung auftritt. Zu diesem Zeitpunkt sind RPO und RTO unbestimmt, entsprechen jedoch der Zeit, die zur Behebung des Problems, das zum Ausfall der sekundären Replizierung geführt hat, und zum Abschluss der Resynchronisierung benötigt wird.
* *StrictSync-Modus* SnapMirror synchron kann optional im StrictSync-Modus betrieben werden. Wenn der Schreibvorgang auf den Sekundärspeicher aus irgendeinem Grund nicht abgeschlossen wird, schlägt die Anwendungs-I/O fehl, wodurch sichergestellt wird, dass Primär- und Sekundärspeicher identisch sind. Die Anwendungs-I/O auf dem Primärspeicher wird erst wieder aufgenommen, nachdem die SnapMirror Beziehung wieder den `InSync` Status erreicht hat. Wenn der Primärspeicher ausfällt, kann die Anwendungs-I/O nach dem Failover auf dem Sekundärspeicher ohne Datenverlust fortgesetzt werden. Im StrictSync-Modus ist RPO immer null und RTO sehr niedrig.




[[relationship-status]]
== Beziehungsstatus

Der Status einer SnapMirror synchronen Beziehung ist während des Normalbetriebs immer im  `InSync` Status. Wenn die SnapMirror Übertragung aus irgendeinem Grund fehlschlägt, ist das Ziel nicht mit der Quelle synchron und kann in den  `OutofSync` Status wechseln.

Bei SnapMirror synchronen Beziehungen prüft das System den Beziehungsstatus automatisch  `InSync` oder  `OutofSync` in einem festgelegten Intervall. Ist der Beziehungsstatus  `OutofSync`, löst ONTAP automatisch den Auto-Resync-Prozess aus, um die Beziehung wieder in den  `InSync` Status zu versetzen. Die automatische Resynchronisierung wird nur ausgelöst, wenn die Übertragung aufgrund eines Vorgangs fehlschlägt, wie etwa eines ungeplanten Storage-Failovers am Quell- oder Ziel-Cluster oder eines Netzwerkausfalls. Benutzerinitiierte Vorgänge wie  `snapmirror quiesce` und  `snapmirror break` lösen keine automatische Resynchronisierung aus.

Wenn der Beziehungsstatus  `OutofSync` für eine SnapMirror synchrone Beziehung im StrictSync-Modus erreicht wird, werden alle I/O-Operationen auf dem primären Volume gestoppt. Der  `OutofSync`-Zustand für eine SnapMirror synchrone Beziehung im Sync-Modus ist für das primäre Volume nicht störend, und I/O-Operationen sind auf dem primären Volume zulässig.



[[scheduled-snapshot-replication]]
== Geplante Snapshot-Replikation

Ab ONTAP 9.19.1 können Sie den SnapMirror Policy-Parameter `-sync-snapshot-replication-mode` im erweiterten Berechtigungsmodus verwenden, um geplante Snapshots zum SnapMirror Ziel zu replizieren. Die Replikation geplanter Snapshots bietet Symmetrie zwischen den primären und sekundären Volumes in einer SnapsMirror synchronen Beziehung.

.Voraussetzungen
* Sie müssen Cluster- oder SVM-Administrator sein
* Sie müssen sich im erweiterten Berechtigungsmodus befinden
* Sie müssen eine benutzerdefinierte SnapMirror-Richtlinie konfigurieren, die den Parameter  `-sync-snapshot-replication-mode` verwendet und die Option  `sched_created` enthält.
+
** Systemdefinierte Richtlinien können nicht geändert werden. Sie müssen eine neue Richtlinie erstellen und die Beziehung neu herstellen.
** Änderungen an benutzerdefinierten Richtlinien erfordern eine Resynchronisierung (Quiesce gefolgt von Resume), um bei bestehenden Beziehungen wirksam zu werden.




Der Parameter akzeptiert folgende Optionen:

* `none`- Deaktiviert die Replikation von nicht-SnapMirror synchronen Snapshots
* `application_created`- repliziert von der Anwendung erstellte Snapshots
* `sched_created` - repliziert geplante Snapshots
* `sm_created` - repliziert von SnapMirror asynchron (Fanout-Leg) erstellte Snapshots
* Eine durch Kommas getrennte Liste von Typen: `application_created`, `sched_created` und `sm_created`.


Der Parameter wird erst wirksam, wenn der Beziehungsstatus `InSync` ist. Nicht aufgeführte Snapshot-Typen werden nur auf dem primären Volume gespeichert.

Ab ONTAP 9.19.1, `snapmirror initialize` werden alle Snapshots auf den sekundären Cluster repliziert, während  `snapmirror resync` nur neue Snapshots repliziert werden, die nach dem letzten gemeinsamen Snapshot erstellt wurden. Bei einer Resynchronisierung werden nicht replizierte Snapshots, die als primary-only gekennzeichnet sind, wenn der Beziehungsstatus  `InSync` ist, nicht auf den sekundären Cluster repliziert, und diese Snapshots bleiben nach einer Flip-Resynchronisierung im neuen sekundären Cluster erhalten.


NOTE: Das Erstellen von Snapshots auf SnapMirror synchronen Volumes kann die Benutzer-I/O-Latenz erhöhen. Es wird empfohlen, Snapshot-Zeitpläne mit einer Frequenz von mehr als 30 Minuten zu verwenden.

.Verwandte Informationen
* https://www.netapp.com/pdf.html?item=/media/17174-tr4733.pdf["NetApp Technical Report 4733: SnapMirror synchron Konfiguration und bewährte Verfahren"^]
* link:https://docs.netapp.com/us-en/ontap-cli//volume-snapshot-create.html["Volume-Snapshot erstellen"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-delete.html["Volume-Snapshot löschen"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-modify.html["Volume Snapshot ändern"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-rename.html["Volume-Snapshot umbenennen"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-break.html["snapmirror break"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["snapmirror quiesce"^]

