---
permalink: data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html 
sidebar: sidebar 
keywords: snapmirror, synchronous, disaster, recovery 
summary: 'Ab ONTAP 9.5 wird SnapMirror Synchronous (SM-S) Technologie auf allen FAS und AFF Plattformen mit mindestens 16 GB Arbeitsspeicher sowie auf allen ONTAP Select Plattformen unterstützt. Die SnapMirror Synchronous Technologie ist eine pro Node lizenzierte Funktion zur synchronen Datenreplizierung auf Volume-Ebene.' 
---
= Grundlagen von SnapMirror Synchronous Disaster Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.5 wird SnapMirror Synchronous (SM-S) Technologie auf allen FAS und AFF Plattformen mit mindestens 16 GB Arbeitsspeicher sowie auf allen ONTAP Select Plattformen unterstützt. Die SnapMirror Synchronous Technologie ist eine pro Node lizenzierte Funktion zur synchronen Datenreplizierung auf Volume-Ebene.

Diese Funktionalität ist sowohl den gesetzlichen als auch den nationalen Vorgaben für synchrone Replizierung in Finanz-, Gesundheitswesen und anderen Branchen gerecht, in denen Datenverluste nicht erforderlich sind.

Die Obergrenze der Anzahl der synchronen SnapMirror Replizierungsvorgänge pro HA-Paar hängt vom Controller-Modell ab.

In der folgenden Tabelle ist die Anzahl der synchronen SnapMirror Vorgänge aufgeführt, die pro HA-Paar entsprechend dem Plattformtyp und ONTAP Release zulässig sind.

|===


| Plattform | Versionen vor ONTAP 9.9.1 | ONTAP 9.9.1 | ONTAP 9.10.1 | ONTAP 9.11.1\ONTAP 9.12.1 


 a| 
AFF
 a| 
80
 a| 
160
 a| 
200
 a| 
400



 a| 
FAS
 a| 
40
 a| 
80
 a| 
80
 a| 
80



 a| 
ONTAP Select
 a| 
20
 a| 
40
 a| 
40
 a| 
40

|===


== Unterstützte Funktionen

ONTAP 9.12.1 unterstützt nur auf All Flash FAS/ASA Plattformen einen unterbrechungsfreien SnapMirror Synchronous Betrieb (NDO). Dank der Support-Funktion für unterbrechungsfreien Betrieb können Sie viele gängige Wartungsaufgaben ohne Ausfallzeiten durchführen. Zu den unterstützten Vorgängen gehören Takeover und Giveback. Außerdem werden Volumes verschoben, sofern zwischen jedem der beiden Cluster ein einziger Node übrigbleibt.

Die folgenden Funktionen werden für SnapMirror Synchronous Technologie in ONTAP 9.10.1 unterstützt, sofern alle Knoten im Quell- und Ziel-Cluster ONTAP 9.10.1 verwenden:

* NFSv4.2
* NVMe/TCP


In ONTAP 9.5 und höher unterstützt SnapMirror Synchronous Technologie die Protokolle NFSv3, FC und iSCSI über alle Netzwerke, bei denen die Latenz nicht mehr als 10ms beträgt.

SnapMirror Synchronous unterstützt Quell- und Ziel-Volumes auf FabricPool Aggregaten mit einer Tiering-Richtlinie ohne, Snapshot oder automatisch. Das Ziel-Volume in einem FabricPool-Aggregat kann nicht auf „Alle Tiering-Richtlinien“ gesetzt werden.

Die folgenden Funktionen werden für SnapMirror Synchronous Technologie in ONTAP 9.7 unterstützt:

* Replizierung von von durch Applikationen erstellten Snapshot Kopien Wenn eine Snapshot Kopie mit dem entsprechenden Etikett zum Zeitpunkt der versehen wird `snapshot create` Betrieb SnapMirror Synchronous repliziert über die CLI oder die ONTAP-API die Snapshot Kopien, sowohl von Benutzern als auch mit externen Skripts erstellt, nachdem die Applikationen stillgelegt wurden. Geplante Snapshot Kopien, die unter Verwendung einer Snapshot Richtlinie erstellt wurden, werden nicht repliziert. Weitere Informationen zum Replizieren von von durch Applikationen erstellten Snapshot-Kopien finden Sie im Knowledge Base-Artikel: link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/How_to_replicate_application_created_snapshots_with_SnapMirror_Synchronous["Wie repliziert man Snapshots von Anwendungen mit SnapMirror Synchronous"^].
* FC-NVMe
* LUN-Klone und NVMe Namespace-Klone LUN-Klone, die durch von Applikationen erstellte Snapshot-Kopien gesichert werden, werden ebenfalls unterstützt.


Die folgenden Funktionen werden für SnapMirror Synchronous Technologie in ONTAP 9.6 unterstützt, sofern alle Knoten im Quell- und Ziel-Cluster ONTAP 9.6 verwenden:

* SVM-DR
+
** Eine SnapMirror Synchronous Source kann auch eine SVM-DR-Quelle sein, beispielsweise eine Fan-out-Konfiguration mit SM-S als One Leg und SVM-DR als andere.
** Eine synchrone SnapMirror Quelle kann kein SVM-DR-Ziel sein, da SM-S keine Kaskadierung einer DP-Quelle unterstützt. Sie müssen die synchrone Beziehung freigeben, bevor Sie eine SVM-DR-Flip-Resynchronisierung im Ziel-Cluster durchführen.
** Ein synchroner SnapMirror Ziel kann keine SVM-DR-Quelle sein, da SVM DR die Replizierung von DP-Volumes nicht unterstützt. Eine Flip-Resynchronisierung der synchronen Quelle würde dazu führen, dass SVM-DR ohne das DP-Volume im Ziel-Cluster durchgeführt wird.


* NFSv4.0 und NFSv4.1
* SMB 2.0 oder höher
* Multiprotokollzugriff (NFSv3 und SMB)
* Antivirus auf dem primären Volume der SnapMirror Synchronous Beziehung
* Harte oder weiche Quoten auf dem primären Volume der SnapMirror Synchronbeziehung die Kontingentregeln werden nicht zum Bestimmungsort repliziert, daher wird die Quota-Datenbank nicht zum Zielort repliziert.
* FPolicy für das primäre Volume der SnapMirror Synchronous Beziehung
* SnapMirror Synchronous Mirror-Mirror Kaskadierung die Beziehung vom Ziel-Volume der SnapMirror Synchronbeziehung muss eine asynchrone SnapMirror Beziehung sein.
* Zeitstempel zwischen Quell- und Ziel-Volumes für NAS bei einem Upgrade von ONTAP 9.5 auf ONTAP 9.6 wird der Zeitstempel nur für neue und geänderte Dateien im Quell-Volume repliziert. Der Zeitstempel vorhandener Dateien im Quell-Volume wird nicht synchronisiert.
* Entfernung hoher Metadaten Frequenzbegrenzung
* Sicherheit für sensible Daten während der Übertragung mithilfe von TLS 1.2-Verschlüsselung
* Automatisches Löschen von Klonen


Ab ONTAP 9.13.1 wird NDMP mit SnapMirror Synchronous unterstützt. Sowohl auf dem Quell- als auch auf dem Zielcluster muss ONTAP 9.13.1 oder höher ausgeführt werden, um NDMP mit SnapMirror Synchronous zu verwenden. Weitere Informationen finden Sie unter xref:../tape-backup/transfer-data-ndmpcopy-task.html[Datenübertragung mithilfe einer ndmp-Kopie].



== Nicht unterstützte Funktionen

Die folgenden Funktionen werden nicht mit synchronen SnapMirror Beziehungen unterstützt:

* Manipulationssichere Snapshot Kopien
* Konsistenzgruppen
* MetroCluster Konfigurationen
* SFMoD
* SFCoD
* VVol
* LUNs mit gemischten SAN- und NVMe-Zugriffs sowie NVMe Namespaces werden nicht auf demselben Volume oder derselben SVM unterstützt.
* SnapLock Volumes
* FlexGroup Volumes
* FlexCache Volumes
* SnapRestore
* DP_Optimized (DPO)-Systeme
* Tape Backup oder Wiederherstellung mithilfe von Dump und SMTape auf dem Ziel-Volume
* Tape-basierte Wiederherstellung auf dem Quell-Volume
* Durchsatzboden (QoS Min.) für Quell-Volumes
* In einer Fan-out-Konfiguration kann nur eine Beziehung eine SnapMirror synchrone Beziehung sein. Alle anderen Beziehungen des Quell-Volumes müssen asynchrone SnapMirror Beziehungen sein.
* Globale Drosselung




== Betriebsmodi

SnapMirror Synchronous verfügt über zwei Betriebsmodi, abhängig vom Typ der verwendeten SnapMirror-Richtlinie:

* *Sync-Modus* im Sync-Modus werden Applikations-I/O-Vorgänge parallel zu den primären und sekundären Speichersystemen gesendet. Wenn der Schreibvorgang auf dem sekundären Storage aus irgendeinem Grund nicht abgeschlossen wird, kann die Applikation das Schreiben auf den primären Storage fortsetzen. Wenn die Fehlerbedingung korrigiert wird, werden SnapMirror Synchronous Technologie automatisch mit dem sekundären Storage neu synchronisiert und die Replizierung vom primären Speicher zum sekundären Storage im synchronen Modus fortgesetzt. Im synchronen Modus ist RPO=0 und RTO sehr niedrig, bis ein sekundärer Replizierungsausfall auftritt. RPO und RTO sind nicht bestimmt, entsprechen aber der Zeit zur Behebung des Problems, das zum Scheitern der sekundären Replizierung und zum Abschluss der Resync-Synchronisierung geführt hat.
* *StrictSync-Modus* SnapMirror Synchronous kann optional im StrictSync-Modus betrieben werden. Wenn der Schreibvorgang auf den sekundären Storage aus irgendeinem Grund nicht abgeschlossen wird, fällt der Applikations-I/O aus. Dadurch wird sichergestellt, dass der Primär- und der Sekundärspeicher identisch sind. Der Applikations-I/O zum primären System wird erst wieder aufgenommen, nachdem die SnapMirror Beziehung wieder auf zurückkehrt `InSync` Status: Falls der primäre Storage ausfällt, kann der Applikations-I/O nach dem Failover auf dem sekundären Storage fortgesetzt werden, ohne dass die Daten verloren gehen. Im Modus StrictSync ist die RPO immer null und die RTO ist sehr niedrig.




== Beziehungsstatus

Der Status einer SnapMirror Synchronous-Beziehung befindet sich immer im `InSync` Status während des normalen Betriebs. Wenn der SnapMirror Transfer aus irgendeinem Grund fehlschlägt, befindet sich das Ziel nicht im synchronen Modus mit der Quelle und kann mit dem fortfahren `OutofSync` Status:

Bei SnapMirror synchronen Beziehungen überprüft das System automatisch den Beziehungsstatus  `InSync` Oder `OutofSync`) In einem festen Intervall. Wenn der Beziehungsstatus lautet `OutofSync`, ONTAP löst automatisch den automatischen Resync-Prozess, um die Beziehung auf die zurückzubringen `InSync` Status: Die automatische Neusynchronisierung wird nur dann ausgelöst, wenn der Transfer aufgrund eines Vorgangs, z. B. ungeplanten Storage-Failover am Quell- oder Ziel-System oder aufgrund eines Netzwerkausfalls, ausfällt. Vom Benutzer initiierte Funktionen wie z. B. `snapmirror quiesce` Und `snapmirror break` Führen Sie keine automatische Neusynchronisierung durch.

Wenn der Beziehungsstatus lautet `OutofSync` Für eine SnapMirror Synchronous-Beziehung im StrictSync-Modus werden alle I/O-Vorgänge zum primären Volume angehalten. Der `OutofSync` Status für SnapMirror Synchronous-Beziehung im Sync-Modus verursacht keine Unterbrechung für das primäre Volume und I/O-Vorgänge sind auf dem primären Volume zulässig.

.Verwandte Informationen
http://www.netapp.com/us/media/tr-4733.pdf["Technischer Bericht 4733 von NetApp: SnapMirror Synchronous Configration und Best Practices"^]
