---
permalink: data-protection/snapmirror-licensing-concept.html 
sidebar: sidebar 
keywords: snapmirror, licensing, snapvault, vault, mirror, relationship, replication, backup, back up, disaster recovery, dr 
summary: Die SnapMirror Lizenz unterstützt sowohl Vault- als auch Mirror-Beziehungen und ONTAP Replikation für Backup- und Disaster-Recovery-Anwendungsfälle. 
---
= Informationen zur ONTAP SnapMirror Lizenzierung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.3 ist die Lizenzierung für die Replikation zwischen ONTAP Instanzen vereinfacht. In ONTAP 9 Releases unterstützt die SnapMirror Lizenz sowohl Vault- als auch Mirror-Beziehungen. Mit einer SnapMirror Lizenz kann die ONTAP Replizierung sowohl für Backup- als auch für Disaster Recovery Anwendungsfälle unterstützt werden.

Vor der Einführung von ONTAP 9.3 war eine separate SnapVault Lizenz erforderlich, um _Vault_-Beziehungen zwischen ONTAP Instanzen zu konfigurieren, wobei die DP-Instanz eine höhere Anzahl von Snapshots behalten konnte, um Backup-Anwendungsfälle mit längeren Aufbewahrungszeiten zu unterstützen. Eine SnapMirror Lizenz war erforderlich, um _Mirror_-Beziehungen zwischen ONTAP Instanzen zu konfigurieren, bei denen jede ONTAP Instanz die gleiche Anzahl von Snapshots (also ein _Mirror_-Abbild) behielt, um Disaster-Recovery-Anwendungsfälle zu unterstützen und Cluster-Failover zu ermöglichen. Sowohl SnapMirror als auch SnapVault Lizenzen werden weiterhin für ONTAP 8.x und 9.x Releases verwendet und unterstützt.

Während SnapVault Lizenzen weiterhin funktionieren und sowohl für ONTAP 8.x als auch für 9.x unterstützt werden, kann die SnapMirror Lizenz anstelle einer SnapVault Lizenz verwendet werden und kann sowohl für Mirror- als auch für Vault-Konfigurationen eingesetzt werden.

Für die ONTAP asynchrone Replizierung wird ab ONTAP 9.3 eine einheitliche Replikations-Engine verwendet, um Richtlinien für den erweiterten Datenschutzmodus (XDP) zu konfigurieren, wobei die SnapMirror Lizenz für eine Spiegelrichtlinie, eine Vault-Richtlinie oder eine Spiegel-Vault-Richtlinie konfiguriert werden kann. Eine SnapMirror Lizenz ist sowohl auf dem Quell-Cluster als auch auf dem Ziel-Cluster erforderlich. Eine SnapVault Lizenz ist nicht erforderlich, wenn bereits eine SnapMirror Lizenz installiert ist. Die SnapMirror asynchron unbefristete Lizenz ist in der ONTAP One Software Suite enthalten, die auf neuen AFF und FAS Systemen installiert ist.

Die Konfigurationsgrenzen für den Datenschutz werden anhand verschiedener Faktoren bestimmt, darunter Ihre ONTAP Version, die Hardwareplattform und die installierten Lizenzen. Weitere Informationen finden sich unter  https://hwu.netapp.com/["Hardware Universe"^].



[[snapmirror-synchronous-license]]
== SnapMirror synchron Lizenz

Ab ONTAP 9.5 werden SnapMirror synchron Beziehungen unterstützt. Für die Erstellung einer SnapMirror synchron Beziehung sind die folgenden Lizenzen erforderlich:

* Die SnapMirror synchron Lizenz ist sowohl auf dem Quell-Cluster als auch auf dem Ziel-Cluster erforderlich.
+
Die SnapMirror synchron Lizenz ist Teil der link:../system-admin/manage-licenses-concept.html["ONTAP One Lizenzpaket"].

+
Wenn Ihr System vor Juni 2019 mit einem Premium oder Flash Bundle erworben wurde, kann ein NetApp Lizenzschlüssel heruntergeladen werden, um die erforderliche SnapMirror synchron Lizenz von der NetApp Support Site zu erhalten: https://mysupport.netapp.com/NOW/knowledge/docs/olio/guides/master_lickey/["Lizenzschlüssel"^].

* Die SnapMirror Lizenz ist sowohl auf dem Quell-Cluster als auch auf dem Ziel-Cluster erforderlich.




[[snapmirror-cloud-license]]
== SnapMirror Cloud-Lizenz

Ab ONTAP 9.8 bietet die SnapMirror Cloud-Lizenz asynchrone Replizierung von Snapshots von ONTAP Instanzen zu Objektspeicher-Endpunkten. Replikationsziele können sowohl mit lokalen Objektspeichern als auch mit S3 und S3-kompatiblen öffentlichen Cloud Objektspeicherdiensten konfiguriert werden. SnapMirror Cloud-Beziehungen von ONTAP Systemen zu vorqualifizierten Objektspeicherzielen werden unterstützt.

SnapMirror cloud ist nicht als Einzellizenz erhältlich. Es wird nur eine Lizenz pro ONTAP Cluster benötigt. Zusätzlich zu einer SnapMirror cloud Lizenz ist auch die SnapMirror asynchron Lizenz erforderlich.

Für die Erstellung einer SnapMirror Cloud-Beziehung sind die folgenden Lizenzen erforderlich:

* Sowohl eine SnapMirror Lizenz als auch eine SnapMirror Cloud-Lizenz für die Replikation direkt zum Objektspeicher-Endpunkt.
* Bei der Konfiguration eines Replikationsworkflows mit mehreren Richtlinien (z. B. Disk-to-Disk-to-Cloud) ist eine SnapMirror Lizenz auf allen ONTAP Instanzen erforderlich, während die SnapMirror Cloud-Lizenz nur für den Quell-Cluster erforderlich ist, der direkt zum Objektspeicher-Endpunkt repliziert.


Ab ONTAP 9.9.1 ist es möglich, link:cloud-backup-with-snapmirror-task.html["System Manager für SnapMirror Cloud-Replikation verwenden"].

Eine Liste der autorisierten SnapMirror Cloud-Drittanbieteranwendungen ist auf der NetApp Website veröffentlicht.



[[data-protection-optimized-license]]
== Data Protection Optimized Lizenz

Data Protection Optimized (DPO) Lizenzen werden nicht mehr verkauft, und DPO wird auf aktuellen Plattformen nicht unterstützt; wenn jedoch eine DPO Lizenz auf einer unterstützten Plattform installiert ist, bietet NetApp weiterhin Support bis zum Ende der Verfügbarkeit dieser Plattform.

DPO ist nicht im ONTAP One Lizenzpaket enthalten, und ein Upgrade auf das ONTAP One Lizenzpaket ist nicht möglich, wenn die DPO Lizenz auf einem System installiert ist.

Informationen zu den unterstützten Plattformen sind unter  https://hwu.netapp.com/["Hardware Universe"^] zu finden.
