---
permalink: data-protection/update-load-sharing-mirror-set-task.html 
sidebar: sidebar 
keywords: update, loaad-sharing, mirror, relationship, LSM, manual update 
summary: 'LSM-Beziehungen (Load-Sharing Mirror) werden automatisch für SVM-Root-Volumes aktualisiert, nachdem ein Volume in der SVM gemountet oder abgehängt wurde, sowie während `volume create` Operationen, die die Option `Junction-Path`umfassen. Sie können eine LSM-Beziehung manuell aktualisieren, wenn sie vor dem nächsten geplanten Update aktualisiert werden soll.' 
---
= Aktualisieren einer ONTAP-Beziehung zur Lastverteilung einer Spiegelung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
LSM-Beziehungen (Load-Sharing Mirror) werden automatisch für SVM-Root-Volumes aktualisiert, nachdem ein Volume in der SVM gemountet oder abgehängt wurde, sowie während `volume create` Operationen, die die Option umfassen `junction-path`. Sie können eine LSM-Beziehung manuell aktualisieren, wenn sie vor dem nächsten geplanten Update aktualisiert werden soll.

Mirror Relationships werden unter folgenden Umständen automatisch aktualisiert:

* Es ist Zeit für ein geplantes Update
* Auf einem Volume im SVM-Root-Volume wird ein Mount- oder Unmount-Vorgang durchgeführt
* A  `volume create` Befehl ausgegeben wird, der die  `junction-path` Option
+
Erfahren Sie mehr über `volume create` in der link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["ONTAP-Befehlsreferenz"^].



.Schritt
. Manuelles Aktualisieren einer Mirror-Beziehung zur Lastverteilung:
+
Sie müssen die Variablen in Winkelklammern durch die erforderlichen Werte ersetzen, bevor Sie diesen Befehl ausführen.

+
[source, cli]
----
snapmirror update-ls-set -source-path <SVM:volume>
----
+
Das folgende Beispiel aktualisiert die Load-Sharing-Spiegelbeziehung für das Root-Volume `svm1_root`:

+
[listing]
----
cluster_src::> snapmirror update-ls-set -source-path svm1:svm1_root
----
+
Erfahren Sie mehr über `snapmirror update` in der link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["ONTAP-Befehlsreferenz"^].


