---
permalink: data-protection/vol-placement-criteria-svm-dest-reference.html 
sidebar: sidebar 
keywords: snapmirror, svm, replication, disaster recovery, aggregate, volume 
summary: Bei der Replizierung von Volumes von der Quell-SVM zu der Ziel-SVM ist es wichtig, die Kriterien bei der Auswahl der Aggregate zu kennen. 
---
= Kriterien für die Platzierung von Volumes auf Ziel-SVMs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Replizierung von Volumes von der Quell-SVM zu der Ziel-SVM ist es wichtig, die Kriterien bei der Auswahl der Aggregate zu kennen.

Aggregate werden basierend auf den folgenden Kriterien ausgewählt:

* Volumes werden immer in nicht-Root-Aggregaten platziert.
* Nicht-Root-Aggregate werden basierend auf dem verfügbaren freien Speicherplatz und der Anzahl der Volumes ausgewählt, die bereits auf dem Aggregat gehostet sind.
+
Aggregate mit mehr freiem Speicherplatz und weniger Volumes werden vorrangig behandelt. Es wird das Aggregat mit der höchsten Priorität ausgewählt.

* Quell-Volumes auf FabricPool-Aggregaten werden mit derselben Tiering-Richtlinie auf FabricPool-Aggregaten am Ziel-Volume platziert.
* Wenn sich ein Volume auf der Quell-SVM auf einem Flash Pool Aggregat befindet, wird das Volume auf einem Flash Pool Aggregat auf der Ziel-SVM platziert, sofern ein solches Aggregat existiert und über genügend freien Speicherplatz verfügt.
* Wenn der `-space-guarantee` Die Option für das zu replizierende Volume wird festgelegt `volume`, Nur Aggregate mit freiem Speicherplatz, der größer ist als die Volume-Größe, werden berücksichtigt.
* Die Volume-Größe wird während der Replizierung automatisch auf der Ziel-SVM vergrößert, basierend auf der Größe des Quell-Volumes.
+
Falls Sie die Größe der Ziel-SVM vorab reservieren möchten, müssen Sie die Größe des Volume ändern. Die Volume-Größe verkleinert sich nicht automatisch auf der Ziel-SVM basierend auf der Quell-SVM.



Wenn Sie ein Volume von einem Aggregat zu einem anderen verschieben möchten, können Sie das verwenden `volume move` Befehl auf der Ziel-SVM.
