---
permalink: release-notes/index.html 
sidebar: sidebar 
keywords: release notes, new features, ontap 9, digital advisor 
summary: Erfahren Sie mehr über die neuen in ONTAP 9 verfügbaren Funktionen. 
---
= Highlights der Version ONTAP 9
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Jede neue Version der ONTAP 9 Datenmanagement-Software verfügt über neue und erweiterte Funktionen zur Verbesserung der Funktionen, Managebarkeit, Performance und Sicherheit von ONTAP.

Zusätzlich zu diesen Highlights finden Sie umfangreiche versionsbasierte Abdeckung aller neuen und erweiterten Funktionen der letzten ONTAP Versionen.

* Erfahren Sie mehr über https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["Neue und verbesserte ONTAP MetroCluster-Funktionen"^].
* Erfahren Sie mehr über  https://docs.netapp.com/us-en/ontap-afx/release-notes/whats-new-9171.html["neue und verbesserte ONTAP -Softwarefunktionen für NetApp AFX-Speichersysteme"^] .
* Erfahren Sie mehr über  https://docs.netapp.com/us-en/asa-r2/release-notes/whats-new-9171.html["neue und verbesserte ONTAP -Softwarefunktionen für NetApp ASA r2-Speichersysteme"^] .
* Erfahren Sie mehr über  https://docs.netapp.com/us-en/ontap-systems/whats-new.html["neue und erweiterte Unterstützung für AFF, ASA und FAS Systeme und unterstützte Switches"^] .
* Erfahren Sie mehr über Updates zum https://docs.netapp.com/us-en/ontap-automation/whats_new.html["ONTAP REST API"^] .


Details zu bekannten Problemen, Einschränkungen und Upgrade-Warnhinweisen in aktuellen ONTAP 9 Versionen finden Sie im https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 – Versionshinweise"^]. Sie müssen sich mit Ihrem NetApp Konto anmelden oder ein Konto erstellen, um auf die Versionshinweise zuzugreifen.

Informationen zum Upgrade auf die neueste Version von ONTAP finden Sie unter xref:../upgrade/prepare.html[Führen Sie ein Upgrade auf die neueste Version von ONTAP durch] und xref:../upgrade/when-to-upgrade.html[Wann sollte ich ein Upgrade von ONTAP durchführen?]



== Highlights von ONTAP 9.17.1

ONTAP 9.17.1 bietet Innovationen im KI-gestützten autonomen Ransomware-Schutz für SAN und fügt NVMe-Front-End-Host-Unterstützung mit SnapMirror Active Sync und hierarchischer Verwaltung von Konsistenzgruppen hinzu.  Diese Verbesserungen untermauern die Führungsrolle von NetApp in den Bereichen Datensicherheit und Cyber-Resilienz und verbessern die Leistung, Skalierbarkeit, Effizienz und Geschäftskontinuität von ONTAP . Eine vollständige Liste der neuen Funktionen und Verbesserungen finden Sie unter xref:whats-new-9171.adoc[Was ist neu in ONTAP 9.17.1] .

* xref:../anti-ransomware/index.html[Unterstützung für SAN mit autonomem Ransomware-Schutz]
+
ARP unterstützt SAN-Volumes mit verschlüsselungsbasierter Anomalieerkennung, führt neue Befehle für detaillierte Entropiestatistiken ein und vereinheitlicht die Ransomware-Schutzmeldungen im System Manager, die sich bisher auf NAS konzentrierten. Konfigurierbare Erkennungsschwellenwerte und eine deterministischere Snapshot-Aufbewahrung bieten mehr Flexibilität für unterschiedliche Workloads.

* xref:../system-admin/use-hsts-task.html[HTTP Strict Transport Security (HSTS)-Unterstützung]
+
ONTAP 9.17.1 unterstützt HTTP Strict Transport Security für Webdienste und ermöglicht die Durchsetzung einer sicheren HTTPS-Kommunikation zwischen dem Browser eines Benutzers und ONTAP.

* xref:../networking/ipsec-prepare.html[IPsec-Hardware-Offload mit Link-Aggregationsgruppen]
+
ONTAP 9.17.1 unterstützt IPsec-Hardware-Offload für Link-Aggregationsgruppen und erweitert damit die in ONTAP 9.16.1 eingeführte Hardware-Offload-Unterstützung.

* xref:../networking/ipsec-prepare.html[IPsec-Postquantum-Pre-Shared-Key-Unterstützung]
+
ONTAP unterstützt Post-Quantum-Pre-Shared-Keys für IPsec zum Schutz vor potenziellen zukünftigen Quantencomputerangriffen.

* xref:../encryption-at-rest/manage-keys-barbican-task.html[Unterstützung für OpenStack Barbican-Schlüsselmanager]
+
ONTAP unterstützt den Barbican-Schlüsselmanager von OpenStack für NetApp Volume Encryption (NVE)-Schlüssel.

* xref:../authentication/configure-jit-elevation-task.html[Unterstützung für Just-in-Time-Rechteerweiterung (JIT)]
+
ONTAP unterstützt die JIT-Berechtigungserweiterung für die rollenbasierte Zugriffskontrolle (RBAC). Benutzer können eine temporäre Erhöhung auf eine konfigurierte Rolle anfordern, um bei Bedarf auf privilegierte Befehle zugreifen zu können. Clusteradministratoren können konfigurieren, wer auf die JIT-Berechtigungserweiterung zugreifen kann und wann und wie lange der Zugriff erlaubt ist.

* xref:../system-admin/configure-saml-authentication-task.html[Unterstützung für Entra IdP und IdP-Gruppenunterstützung für SAML-Authentifizierung]
+
ONTAP unterstützt Microsoft Entra als SAML-Identitätsanbieter. Darüber hinaus können vom IdP bereitgestellte Gruppeninformationen ONTAP Rollen zugeordnet werden.

* xref:../nvme/support-limitations.html#features[SnapMirror Active Sync-Unterstützung für Hostzugriff über NVMe]
+
SnapMirror Active Sync unterstützt NVMe-Zugriff für VMware-Workloads mit NVMe/TCP- und NVMe/FC-Hostzugriff für ONTAP Cluster mit zwei Knoten.

* xref:../snapmirror-active-sync/index.html[ONTAP Cloud Mediator-Unterstützung mit SnapMirror Active Sync]
+
ONTAP Cloud Mediator wurde in ONTAP 9.17.1 eingeführt und unterstützt SnapMirror Active-Sync-Beziehungen. Der Cloud-basierte Mediator fungiert wie ONTAP Mediator als Quorum Witness für SnapMirror Active-Sync-Beziehungen und gewährleistet so transparentes Failover. Gleichzeitig reduziert er den operativen Aufwand für die Wartung und Verwaltung eines dritten Standorts.





== Highlights von ONTAP 9.16.1

ONTAP 9.16.1 bietet neue und verbesserte Funktionen in den Bereichen Sicherheitsmanagement, Datensicherung, Networking, SAN Management und Storage Management. Eine vollständige Liste der neuen Funktionen und Verbesserungen finden Sie unter xref:whats-new-9161.adoc[Neues in ONTAP 9.16.1].

* xref:../multi-admin-verify/index.html#rule-protected-commands[Verbesserungen zur Verifizierung durch mehrere Administratoren (Multi-Admin Verification, MAV)]
+
ONTAP 9.16.1 fügt weitere Befehle zum MAV-Framework hinzu, um so vor böswilligen Insidern zu schützen. Zu diesen Verbesserungen zählen zahlreiche Managementfunktionen für Konsistenzgruppen (CG), das Management von Vscan und Autonomous Ransomware Protection (ARP) sowie NVMe-Konfigurationsbefehle.

* xref:../anti-ransomware/index.html[Autonomer Ransomware-Schutz mit KI-Verbesserungen (ARP/AI)]
+
ARP wurde mit neuen KI-Funktionen aufgerüstet, wodurch die IT Ransomware-Angriffe mit 99 % Präzision und Rückruf erkennen und darauf reagieren kann. Da die AI auf einem umfassenden Datensatz trainiert wird, gibt es keine Lernphase für die Ausführung von ARP auf FlexVol Volumes und ARP/AI startet sofort im aktiven Modus. ARP/AI bietet darüber hinaus eine automatische Update-Funktion unabhängig von einem ONTAP Upgrade, um einen konstanten Schutz und Schutz vor neuesten Bedrohungen zu gewährleisten.

* NVMe/TCP über TLS 1.3
+
Schützen Sie NVMe/TCP „über das Netzwerk“ auf der Protokollebene mit einer vereinfachten Konfiguration und einer verbesserten Performance im Vergleich zu IPSec.

* xref:../networking/ipsec-prepare.html[IPsec HW-Offload-Unterstützung für neue Netzwerkkarten]
+
ONTAP 9.16.1 bietet eine höhere Verschlüsselungs-Performance über das Netzwerk, wenn die IPSec-Hardware-Offload-Funktionen auf Offload-Karten verwendet werden, die in der neuesten Generation der Systemplattformen der AFF A-Series und AFF-C Serie eingeführt wurden.

* xref:../san-admin/enable-space-allocation.html[Unterstützung für NVMe-Platzräumung]
+
Die Freigabe von Speicherplatz (auch „Hole Punching“ und „Unmap“ genannt) wird jetzt für NVMe-Namespaces unterstützt.  Durch die Freigabe von Speicherplatz können Thin-Provisioning-Volumes und NVMe-Namespaces ungenutzten Speicherplatz zurückgewinnen, wenn Daten von der Hostanwendung gelöscht werden.  Dies verbessert die allgemeine Speichereffizienz erheblich, insbesondere bei Dateisystemen mit hohem Datendurchsatz.

* xref:../flexgroup/enable-adv-capacity-flexgroup-task.html[Erweiterter Kapazitätsausgleich für FlexGroup Volumes]
+
Optional können NetApp FlexGroup Volumes die Daten in einer einzelnen Datei über mehrere Back-End-KomponentenzVolumes verteilen, wodurch Performance-Engpässe reduziert und der Kapazitätsausgleich über die Back-End-Komponentenzvolumes erhöht wird.

* xref:../svm-migrate/index.html[Unterstützung der SVM-Datenmobilität für die Migration von MetroCluster Konfigurationen]
+
ONTAP unterstützt die folgenden MetroCluster SVM-Migrationen:

+
** Migration einer SVM zwischen einer nicht-MetroCluster-Konfiguration und einer MetroCluster IP-Konfiguration
** Migrieren einer SVM zwischen zwei MetroCluster IP-Konfigurationen
** Migration einer SVM zwischen einer MetroCluster FC-Konfiguration und einer MetroCluster IP-Konfiguration






== Highlights von ONTAP 9.15.1

ONTAP 9.15.1 bietet neue und erweiterte Funktionen in den Bereichen Sicherheitsmanagement, Datensicherung und Unterstützung von NAS-Workloads. Eine vollständige Liste der neuen Funktionen und Verbesserungen finden Sie unter xref:whats-new-9151.adoc[Was ist neu in ONTAP 9.15.1].

* https://www.netapp.com/data-storage/aff-a-series/["Unterstützung für die neuen AFF Systeme der A-Series, Storage für KI"^]
+
ONTAP 9.15.1 unterstützt die neuen hochperformanten Systeme AFF A1K, AFF A90 und AFF A70, die für Business-Workloads der nächsten Generation wie KI/ML-Training und Inferenz entwickelt wurden. Diese neue Systemklasse bietet eine bis zu doppelt so hohe Performance wie vorhandene Angebote der AFF A-Series und sorgt ohne Performance-Einbußen für eine verbesserte Always-on-Storage-Effizienz.

* xref:../smb-admin/windows-backup-symlinks.html[Windows-Backup-Anwendungen und Unix-artige Symlinks auf Servern]
+
Ab ONTAP 9.15.1 haben Sie auch die Möglichkeit, das Symlink selbst zu sichern, anstatt auf die Daten, auf die es verweist. Dies kann zu mehreren Vorteilen führen, darunter zu einer verbesserten Performance Ihrer Backup-Applikationen. Sie können die Funktion mit der ONTAP-CLI oder REST-API aktivieren.

* xref:../authentication/dynamic-authorization-overview.html[Dynamische Autorisierung]
+
ONTAP 9.15.1 bietet ein erstes Framework für die dynamische Autorisierung, eine Sicherheitsfunktion, mit der festgelegt werden kann, ob ein von einem Administratorkonto ausgegebener Befehl abgelehnt, zur weiteren Authentifizierung aufgefordert oder fortgesetzt werden darf. Die Bestimmungen basieren auf der Vertrauensbewertung des Benutzerkontos und berücksichtigen Faktoren wie Tageszeit, Standort, IP-Adresse, Nutzung vertrauenswürdiger Geräte sowie den Authentifizierungs- und Autorisierungsverlauf des Benutzers.

* xref:../multi-admin-verify/index.html#rule-protected-commands[Erweiterter Umfang der Auswirkungen für die Verifizierung durch mehrere Administratoren]
+
ONTAP 9.15.1 RC1 erweitert das MAV-Framework um über hundert neue Befehle und bietet so zusätzlichen Schutz vor böswilligen Insidern.

* Unterstützung der TLS 1.3-Verschlüsselung für Cluster-Peering und mehr
+
ONTAP 9.15.1 ermöglicht die TLS 1.3-Verschlüsselung für S3 Storage, FlexCache, SnapMirror und Cluster-Peering. Applikationen wie FabricPool, Storage von Microsoft Azure Page Blobs und SnapMirror Cloud nutzen weiterhin TLS 1.2 für die Version 9.15.1.

* Unterstützung für SMTP-Datenverkehr über TLS
+
Sichere Übertragung von AutoSupport-Daten per E-Mail mit TLS-Unterstützung

* xref:../snapmirror-active-sync/index.html[SnapMirror Active Sync für symmetrische aktiv/aktiv-Konfigurationen]
+
Diese neue Funktion bietet synchrone bidirektionale Replikation für Business Continuity und Disaster Recovery. Sichern Sie Ihren Datenzugriff für kritische SAN Workloads mit gleichzeitigem Lese- und Schreibzugriff auf Daten über mehrere Ausfall-Domains hinweg. So gewährleisten Sie einen unterbrechungsfreien Betrieb und minimieren Ausfallzeiten bei Notfällen oder Systemausfällen.

* xref:../flexcache-writeback/flexcache-writeback-enable-task.html[FlexCache Write-Back]
+
Mit dem FlexCache Write-Back-Vorgang können Clients lokal auf FlexCache Volumes schreiben, wodurch Latenz verringert und die Performance im Vergleich zum direkten Schreiben in das Ursprungs-Volume verbessert wird. Die neu geschriebenen Daten werden asynchron zurück auf das Ursprungs-Volume repliziert.

* xref:../nfs-rdma/index.html[NFSv3 über RDMA]
+
Die Unterstützung von NFSv3 über RDMA hilft Ihnen, hohe Performance-Anforderungen zu erfüllen, indem Sie einen Zugriff mit niedriger Latenz und hoher Bandbreite über TCP bieten.





== Highlights von ONTAP 9.14.1

ONTAP 9.14.1 bietet neue und verbesserte Funktionen in den Bereichen FabricPool, Ransomware-Schutz, OAuth und mehr. Eine vollständige Liste der neuen Funktionen und Verbesserungen finden Sie unter xref:whats-new-9141.adoc[Was ist neu in ONTAP 9.14.1].

* xref:../volumes/determine-space-usage-volume-aggregate-concept.html[Reduktion der WAFL-Reservierung]
+
ONTAP 9.14.1 führt eine sofortige Steigerung des nutzbaren Speicherplatzes auf FAS- und Cloud Volumes ONTAP-Systemen um fünf Prozent ein, indem die WAFL-Reserve auf Aggregaten mit 30 TB oder mehr reduziert wird.

* xref:../fabricpool/enable-disable-volume-cloud-write-task.html[Verbesserungen von FabricPool]
+
FabricPool xref:../fabricpool/enable-disable-aggressive-read-ahead-task.html[Lese-Performance]ermöglicht ein erhöhtes direktes Schreiben in die Cloud, wodurch das Risiko eines Speicherplatzbedarfs verringert wird und die Storage-Kosten durch das Verschieben selten genutzter Daten auf eine kostengünstigere Storage-Tier gesenkt werden.

* link:../authentication/oauth2-deploy-ontap.html["Unterstützung für OAuth 2.0"]
+
ONTAP unterstützt das OAuth 2.0 Framework, das mit System Manager konfiguriert werden kann. Mit OAuth 2.0 können Sie sicheren Zugriff auf ONTAP für Automatisierungs-Frameworks bereitstellen, ohne Benutzer-IDs und Passwörter für Klartextskripte und Runbooks erstellen oder offenlegen zu müssen.

* link:../anti-ransomware/manage-parameters-task.html["ARP-Verbesserungen (Autonomous Ransomware Protection)"]
+
ARP gibt Ihnen mehr Kontrolle über die Ereignissicherheit, wodurch Sie die Bedingungen anpassen können, die Warnungen erzeugen, und die Möglichkeit von False-positive-Meldungen verringert wird.

* xref:../data-protection/create-delete-snapmirror-failover-test-task.html[SnapMirror Disaster Recovery-Probe in System Manager]
+
System Manager bietet einen einfachen Workflow zum einfachen Testen der Disaster Recovery an einem Remote-Standort und zur Bereinigung nach dem Test. Diese Funktion ermöglicht einfachere und häufigere Tests sowie mehr Vertrauen in die Recovery Time Objectives.

* xref:../s3-config/index.html[S3-Objektsperrung wird unterstützt]
+
ONTAP S3 unterstützt den API-Befehl „Object-Lock“. Dadurch können Sie in ONTAP geschriebene Daten mit S3 über standardmäßige S3 API-Befehle vor dem Löschen schützen und wichtige Daten für eine angemessene Zeit sichern.

* xref:../assign-tags-cluster-task.html[Cluster] Und xref:../assign-tags-volumes-task.html[Datenmenge] Tagging
+
Fügen Sie Metadaten-Tags zu Volumes und Clustern hinzu. Diese folgen den Daten, wenn sie von On-Premises in die Cloud und umgekehrt verschoben werden.





== Highlights von ONTAP 9.13.1

ONTAP 9.13.1 bietet neue und verbesserte Funktionen in den Bereichen Ransomware-Schutz, Konsistenzgruppen, Quality of Service, Mandantenkapazitätsmanagement und mehr. Eine vollständige Liste der neuen Funktionen und Verbesserungen finden Sie unter xref:whats-new-9131.adoc[Was ist neu in ONTAP 9.13.1].

* ARP-Verbesserungen (Autonomous Ransomware Protection):
+
** xref:../anti-ransomware/enable-default-task.adoc[Automatische Aktivierung]
+
Bei ONTAP 9.13.1 wechselt ARP automatisch vom Training in den Produktionsmodus, nachdem ausreichende Lerndaten vorhanden sind. Dadurch ist es nicht mehr erforderlich, dass ein Administrator die Funktion nach 30 Tagen aktivieren muss.

** xref:../anti-ransomware/use-cases-restrictions-concept.html#multi-admin-verification-with-volumes-protected-with-arp[Unterstützung bei der Verifizierung durch mehrere Administratoren]
+
ARP-Deaktivierungsbefehle werden durch eine Überprüfung durch mehrere Administratoren unterstützt, sodass kein einzelner Administrator ARP deaktivieren kann, um die Daten einem potenziellen Ransomware-Angriff auszusetzen.

** xref:../anti-ransomware/use-cases-restrictions-concept.html[FlexGroup-Support]
+
ARP unterstützt FlexGroup Volumes ab ONTAP 9.13.1. ARP kann FlexGroup Volumes überwachen und sichern, die sich über mehrere Volumes und Nodes im Cluster erstrecken. Dadurch können sogar umfangreichste Datensätze mit ARP gesichert werden.



* xref:../consistency-groups/index.html[Performance- und Kapazitätsüberwachung für Konsistenzgruppen in System Manager]
+
Das Performance- und Kapazitäts-Monitoring bietet detaillierte Informationen für jede Konsistenzgruppe, mit der Sie potenzielle Probleme auf Applikationsebene und nicht nur auf Datenobjektebene identifizieren und melden können.

* xref:../volumes/manage-svm-capacity.html[Mandantenkapazitätsmanagement]
+
Mandantenfähige Kunden und Service-Provider können für jede SVM eine Kapazitätsgrenze festlegen, sodass Mandanten eine Self-Service-Provisionierung durchführen können, ohne dass ein Mandant mehr Kapazität im Cluster verbraucht.

* xref:../performance-admin/adaptive-policy-template-task.html[Quality of Service Decken und Böden]
+
Mit ONTAP 9.13.1 können Sie Objekte wie Volumes, LUNs oder Dateien in Gruppen gruppieren und eine QoS-Obergrenze (IOPS-Maximum) bzw. -Mindestgröße (IOPS-Minimum) zuweisen. Dies verbessert die Erwartungen an die Applikations-Performance.





== Highlights von ONTAP 9.12.1

ONTAP 9.12.1 bietet neue und erweiterte Funktionen in den Bereichen Erhöhung der Sicherheit, Aufbewahrung, Performance und vieles mehr. Eine vollständige Liste der neuen Funktionen und Verbesserungen finden Sie unter xref:whats-new-9121.adoc[Was ist neu in ONTAP 9.12.1].

* xref:../snaplock/snapshot-lock-concept.html[Manipulationssichere Snapshots]
+
Mit der SnapLock Technologie können Snapshots vor dem Löschen auf dem Quell- oder Zielsystem geschützt werden.

+
Sichern Sie mehr Recovery-Punkte, indem Sie Snapshots auf primärem und sekundärem Storage vor dem Löschen durch Ransomware-Angreifer oder betrügerische Administratoren schützen.

* xref:../anti-ransomware/index.html[ARP-Verbesserungen (Autonomous Ransomware Protection)]
+
Profitieren Sie sofort von intelligentem, autonomem Ransomware-Schutz auf Basis des bereits für den primären Storage abgeschlossenen Screening-Modells.

+
Nach einem Failover erkennen Sie potenzielle Ransomware-Angriffe auf sekundären Storage sofort. Es wird sofort ein Snapshot der betroffenen Daten erstellt und Administratoren werden benachrichtigt, was einen Angriff stoppt und die Recovery verbessert.

* xref:../nas-audit/plan-fpolicy-event-config-concept.html[FPolicy]
+
ONTAP FPolicy mit nur einem Klick aktivieren, um das automatische Blockieren bekannter schädlicher Dateien zu ermöglichen. Durch die vereinfachte Aktivierung können Sie sich vor typischen Ransomware-Angriffen schützen, die häufig bekannte Dateierweiterungen verwenden.

* xref:../system-admin/ontap-implements-audit-logging-concept.html[Verstärkte Sicherheit: Manipulationssichere Protokollierung der Aufbewahrung]
+
Manipulationssichere Protokollierung der Aufbewahrung in ONTAP zur Sicherstellung, dass kompromittierte Administratorkonten keine böswilligen Aktionen verbergen können. Admin und Benutzerverlauf können ohne Kenntnis des Systems nicht geändert oder gelöscht werden.

+
Protokollierung und Prüfung aller Admin-Aktionen unabhängig vom Ursprung, wobei sichergestellt ist, dass alle Aktionen, die sich auf die Daten auswirken, erfasst werden. Eine Warnmeldung wird generiert, wenn die Systemauditprotokolle manipuliert wurden und Administratoren über die Änderung informiert wurden.

* xref:../authentication/setup-ssh-multifactor-authentication-task.html[Verstärkte Sicherheit: Erweiterte Multi-Faktor-Authentifizierung]
+
Multi-Faktor-Authentifizierung (MFA) für CLI (SSH) unterstützt YubiKey-Geräte für physische Hardwaretoken und stellt sicher, dass ein Angreifer nicht mit gestohlenen Anmeldeinformationen oder einem kompromittierten Clientsystem auf das ONTAP-System zugreifen kann. Cisco DUO wird für MFA mit System Manager unterstützt.

* Datei-/Objekt-Dualität (Multi-Protokoll-Zugriff)
+
Die Datei-/Objekt-Dualität ermöglicht nativen Lese- und Schreibzugriff über S3-Protokolle auf dieselbe Datenquelle, die bereits über NAS-Protokollzugriff verfügt. Der Storage kann gleichzeitig als Dateien oder als Objekte aus derselben Datenquelle zugegriffen werden. Es sind also keine doppelten Datenkopien zur Verwendung mit verschiedenen Protokollen (S3 oder NAS) erforderlich, beispielsweise für Analysen mit Objektdaten.

* xref:../flexgroup/manage-flexgroup-rebalance-task.html[FlexGroup-Ausbalancierung]
+
Bei unausgeglichenen FlexGroup-Komponenten lässt sich FlexGroup unterbrechungsfrei neu verteilen und über die CLI, REST API und System Manager managen. Um eine optimale Performance zu erzielen, sollten die verwendeten Kapazitäten der einzelnen Mitglieder eines FlexGroup gleichmäßig verteilt sein.

* Verbesserung der Storage-Kapazität
+
Die WAFL-Platzreservierung wurde deutlich reduziert. Sie bietet bis zu 40 tib mehr nutzbare Kapazität pro Aggregat.





== Highlights von ONTAP 9.11.1

ONTAP 9.11.1 bietet neue und verbesserte Funktionen in den Bereichen Sicherheit, Aufbewahrung, Performance und mehr. Eine vollständige Liste der neuen Funktionen und Verbesserungen finden Sie unter xref:whats-new-9111.adoc[Was ist neu in ONTAP 9.11.1].

* xref:../multi-admin-verify/index.html[Überprüfung durch mehrere Administratoren]
+
Die Multi-Admin-Verifizierung (MAV) ist eine branchenweit erste native Verifizierungsmethode, die mehrere Genehmigungen für sensible administrative Aufgaben wie das Löschen von Snapshots oder Volumes erfordert. Die Genehmigungen, die in einer MAV-Implementierung erforderlich sind, verhindern böswillige Angriffe und versehentliche Änderungen der Daten.

* xref:../anti-ransomware/index.html[Verbesserungen am autonomen Ransomware-Schutz]
+
Autonomous Ransomware Protection (ARP) nutzt maschinelles Lernen, um Ransomware-Bedrohungen mit höherer Granularität zu erkennen, damit Sie Bedrohungen schnell identifizieren und im Falle einer Sicherheitsverletzung die Recovery beschleunigen können.

* xref:../flexgroup/supported-unsupported-config-concept.html#features-supported-beginning-with-ontap-9-11-1[SnapLock Compliance für FlexGroup Volumes]
+
Sichern Sie Datensätze mit einem Volumen von mehreren Petabyte für Workloads wie Electronic Design Automation sowie Medien- und Entertainment-Systeme, indem Sie die Daten mit WORM-Dateisperrung schützen, sodass sie weder geändert noch gelöscht werden können.

* xref:../flexgroup/fast-directory-delete-asynchronous-task.html[Asynchrones Verzeichnis löschen]
+
Bei ONTAP 9.11.1 erfolgt das Löschen von Dateien im Hintergrund des ONTAP Systems. Dadurch können Sie große Verzeichnisse einfach löschen und gleichzeitig Auswirkungen auf Performance und Latenz auf den Host I/O vermeiden

* xref:../s3-config/index.html[Verbesserungen von S3]
+
Vereinfachen und erweitern Sie die Objektdatenmanagement-Funktionen von S3 mit ONTAP durch zusätzliche API-Endpunkte und Objektversionierung auf Bucket-Ebene, sodass mehrere Versionen eines Objekts in demselben Bucket gespeichert werden können.

* Verbesserungen von System Manager
+
System Manager unterstützt erweiterte Funktionen zur Optimierung der Storage-Ressourcen und Verbesserung des Audit-Managements. Diese Updates umfassen erweiterte Funktionen für das Management und die Konfiguration von Storage-Aggregaten, verbesserte Transparenz bei Systemanalysen und Hardware-Visualisierung für FAS Systeme.





== Highlights von ONTAP 9.10.1

ONTAP 9.10.1 bietet neue und erweiterte Funktionen in den Bereichen Erhöhung der Sicherheit, Performance-Analysen, Unterstützung für NVMe-Protokolle und Objekt-Storage-Backup-Optionen. Eine vollständige Liste der neuen Funktionen und Verbesserungen finden Sie unter xref:whats-new-9101.adoc[Was ist neu in ONTAP 9.10.1].

* xref:../anti-ransomware/index.html[Autonomer Schutz Durch Ransomware]
+
Autonomous Ransomware Protection erstellt automatisch einen Snapshot des Volumes und benachrichtigt Administratoren, wenn ungewöhnliche Aktivitäten erkannt werden. So können Sie Ransomware-Angriffe schnell erkennen und eine schnellere Recovery durchführen.

* Verbesserungen von System Manager
+
System Manager lädt automatisch Firmware-Updates für Festplatten, Shelfs und Serviceprozessoren herunter und bietet außerdem neue Integrationen mit Active IQ Digital Advisor (auch bekannt als Digital Advisor), NetApp Console und Zertifikatsverwaltung.  Diese Verbesserungen vereinfachen die Verwaltung und gewährleisten die Geschäftskontinuität.

* xref:../concept_nas_file_system_analytics_overview.html[Verbesserungen bei der Dateisystemanalyse]
+
Filesystem-Analysen bieten zusätzliche Telemetrie zur Identifizierung der wichtigsten Dateien, Verzeichnisse und Benutzer in der Dateifreigabe. So können Sie Workload-Performance-Probleme identifizieren und so die Ressourcenplanung und QoS-Implementierung verbessern.

* xref:../nvme/support-limitations.html[Unterstützung von NVMe over TCP (NVMe/TCP) für AFF-Systeme]
+
Erzielen Sie hohe Performance und reduzieren Sie die TCO für Ihr Enterprise-SAN und moderne Workloads auf einem AFF-System, wenn Sie NVMe/TCP in Ihrem vorhandenen Ethernet-Netzwerk verwenden.

* xref:../nvme/support-limitations.html[Unterstützung von NVMe over Fibre Channel (NVMe/FC) für NetApp FAS-Systeme]
+
Nutzen Sie das NVMe/FC-Protokoll für Ihre Hybrid-Arrays, um eine einheitliche Migration auf NVMe zu ermöglichen.

* xref:../s3-snapmirror/index.html[Natives Hybrid-Cloud-Backup für Objekt-Storage]
+
Sichern Sie Ihre ONTAP S3 Daten mit einem Objekt-Storage-Ziel Ihrer Wahl. Mit SnapMirror Replizierung können Kunden Backups in On-Premises-Storage mit StorageGRID, in der Cloud mit Amazon S3 oder in einem anderen ONTAP S3 Bucket auf NetApp AFF und FAS Systemen erstellen.

* xref:../flexcache/global-file-locking-task.html[Globale Dateisperrung mit FlexCache]
+
Mit globaler Dateisperrung unter Verwendung von FlexCache sorgen Sie am Cache-Speicherort für die Dateikonsistenz bei Updates für Quelldateien am Ursprungsort. Diese Verbesserung ermöglicht exklusive Dateilesesperren in einer „Ursprungs-Cache“-Beziehung für Workloads, die eine erweiterte Sperrung erfordern.





== Highlights von ONTAP 9.9.1

ONTAP 9.91.1 bietet neue und erweiterte Funktionen in den Bereichen Storage-Effizienz, Multi-Faktor-Authentifizierung, Disaster Recovery und vieles mehr. Eine vollständige Liste der neuen Funktionen und Verbesserungen finden Sie unter xref:whats-new-991.adoc[Neues in ONTAP 9.9.1].

* Verbesserte Sicherheit für CLI-Remote-Zugriffsverwaltung
+
Die Unterstützung von SHA512 und SSH A512-Passwort-Hashing schützt die Anmeldeinformationen des Administratorkontos vor böswilligen Akteuren, die versuchen, Systemzugriff zu erlangen.

* https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_and_cable_the_mcc_components.html["MetroCluster IP-Verbesserungen: Unterstützung von 8-Node-Clustern"^]
+
Das neue Limit ist doppelt so groß wie das vorherige, es unterstützt MetroCluster-Konfigurationen und ermöglicht eine kontinuierliche Datenverfügbarkeit.

* xref:../snapmirror-active-sync/index.html[SnapMirror Active Sync]
+
Bietet mehr Replizierungsoptionen für Backup und Disaster Recovery für große Daten-Container für NAS-Workloads.

* xref:../san-admin/storage-virtualization-vmware-copy-offload-concept.html[Höhere SAN-Performance]
+
Liefert bis zu viermal höhere SAN Performance für einzelne LUN-Applikationen wie VMware Datastores, sodass Sie in Ihrer SAN-Umgebung eine hohe Performance erzielen können.

* xref:../task_cloud_backup_data_using_cbs.html[Neue Objekt-Storage-Option für Hybrid Cloud]
+
Ermöglicht die Nutzung von StorageGRID als Ziel für NetApp Cloud Backup Service, um das Backup Ihrer lokalen ONTAP-Daten zu vereinfachen und zu automatisieren.



.Nächste Schritte
* xref:../upgrade/prepare.html[Führen Sie ein Upgrade auf die neueste Version von ONTAP durch]
* xref:../upgrade/when-to-upgrade.html[Wann sollte ich ein Upgrade von ONTAP durchführen?]

