---
permalink: release-notes/index.html 
sidebar: sidebar 
keywords: release notes, new features, ontap 9, digital advisor 
summary: Informationen zu den neuen Funktionen in ONTAP 9. 
---
= Highlights der ONTAP 9 Version
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Jede Version der ONTAP 9 Datenverwaltungssoftware bietet neue und verbesserte Funktionen, die die Fähigkeiten, die Verwaltbarkeit, die Performance und die Sicherheitsfunktionen in ONTAP verbessern.

Zusätzlich zu diesen Highlights ist eine umfassende, versionsspezifische Übersicht aller neuen und erweiterten Funktionen verfügbar, die in den letzten ONTAP Releases eingeführt wurden.

* Weitere Informationen https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["neue und verbesserte ONTAP MetroCluster Funktionen"^].
* Weitere Informationen https://docs.netapp.com/us-en/ontap-afx/release-notes/whats-new-9191.html["neue und verbesserte ONTAP Softwarefunktionen für NetApp AFX Speichersysteme"^].
* Weitere Informationen https://docs.netapp.com/us-en/asa-r2/release-notes/whats-new-9191.html["Neue und verbesserte ONTAP Softwarefunktionen für NetApp ASA r2 Speichersysteme"^].
* Weitere Informationen https://docs.netapp.com/us-en/ontap-systems/whats-new.html["Neue und verbesserte Unterstützung für AFF, ASA und FAS Systeme sowie unterstützte Switches"^].
* Informationen zu Aktualisierungen der  https://docs.netapp.com/us-en/ontap-automation/whats_new.html["ONTAP REST API"^].


Detaillierte Informationen zu bekannten Problemen, Einschränkungen und Hinweisen zum Upgrade in den aktuellen ONTAP 9-Versionen sind in den  https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 Versionshinweise"^] zu finden. Eine Anmeldung mit Ihrem NetApp Account oder die Erstellung eines Accounts ist erforderlich, um auf die Release Notes zuzugreifen.

Informationen zum Upgrade auf die neueste Version von ONTAP finden Sie unter xref:../upgrade/prepare.html[Upgrade auf die neueste Version von ONTAP] und xref:../upgrade/when-to-upgrade.html[Wann sollte ONTAP aktualisiert werden?]



[[ontap-9-19-1-highlights]]
== ONTAP 9.19.1 Highlights

ONTAP 9.19.1 bietet neue und verbesserte Funktionen in den Bereichen Sicherheit, Skalierbarkeit und Speichermanagement zur Unterstützung der Modernisierung der Dateninfrastruktur. Diese Verbesserungen ermöglichen eine bessere Skalierbarkeit, effizientere Abläufe und eine zukunftssichere Sicherung der Daten. Eine vollständige Liste der neuen Funktionen und Verbesserungen ist unter xref:whats-new-9191.adoc[Was ist neu in ONTAP 9.19.1] zu finden.

* xref:../performance-admin/guarantee-throughput-qos-task.html[Konfigurierbare QoS Burst-Richtlinien]
+
Konfigurierbare QoS Burst-Richtlinien ermöglichen kontrollierte, zeitlich begrenzte Leistungsspitzen oberhalb der QoS-Grenzwerte, wodurch die Reaktionsfähigkeit bei Spitzenereignissen verbessert wird, ohne die Fairness zu beeinträchtigen oder eine Überprovisionierung zu erfordern.

* xref:../nfs-admin/enable-nfs-over-tls-task.html[NFS über TLS 1.3]
+
Sichert NFS-Daten während der Übertragung mit standardbasierter TLS 1.3-Verschlüsselung, was den Schutz stärkt und die Einführung von verschlüsseltem NFS im Unternehmensmaßstab vereinfacht. 

* xref:../s3-config/regenerate-access-keys.html[Mehrere S3 Zugriffsschlüssel pro Benutzer]
+
Fügt Unterstützung für mehrere aktive S3-Zugriffsschlüssel pro Benutzer hinzu, ermöglicht eine nahtlose Rotation der Anmeldeinformationen ohne Ausfallzeit der Anwendung und trägt dazu bei, die Sicherheit und Compliance zu stärken, während der ununterbrochene Zugriff auf Objekt-Workloads erhalten bleibt.

* xref:../snapmirror-active-sync/protect-nas-task.html[SnapMirror Active Sync für NAS]
+
Mit NAS-Unterstützung ist SnapMirror Active Sync nun eine einheitliche Business-Continuity-Lösung, die einen RPO von null mit transparentem Failover bietet. 

* xref:../san-config/configure-fc-nvme-hosts-ha-pairs-reference.html[FC Direct Attached]
+
Führt die Unterstützung sicherer FC HBA-Karten ein, ermöglicht eine vertrauenswürdige Host-Konnektivität und schafft die Grundlage für hardwaregestützte, während der Übertragung abgesicherte FC-Sicherheit, wobei die Leistung erhalten bleibt und die Compliance-Anforderungen von Unternehmen unterstützt werden. 

* xref:../san-admin/multipath-automatic-lif-failover-support.html[Einheitliches Aktiv/Aktiv LIF Failover]
+
AFF Systeme bieten Aktiv/Aktiv-Multipathing mit automatischem LIF-Failover, wobei alle SAN-Pfade aktiv optimiert bleiben, sodass die Host-I/O während des Failovers sofort fortgesetzt wird. 

* xref:https://docs.netapp.com/us-en/ontap-fli/get-started/learn-about-data-migration.html[iSCSI Unterstützung in FLI]
+
Fügt iSCSI-Unterstützung für Foreign LUN Import (FLI) hinzu, wodurch die Migration von Blockdaten von Drittanbieterspeichersystemen zu ONTAP unter Verwendung der bestehenden iSCSI-Konnektivität mit minimaler Unterbrechung möglich ist. 

* xref:../s3-config/create-modify-bucket-policy-task.html[Bedingte Schreib- und Löschvorgänge in S3]
+
Ermöglicht die Unterstützung bedingter Schreib- und Löschvorgänge mit der S3 API, sodass Anwendungen Datenkonsistenzprüfungen während Objektaktualisierungen und -entfernungen durchsetzen können, wodurch das Risiko versehentlicher Überschreibungen oder Löschungen bei gleichzeitigen und verteilten Objekt-Workloads reduziert wird.

* xref:../concepts/path-failover-concept.html#nas-path-failover[Kombiniertes LIF-Failover]
+
Automatisches LIF-Failover wird auf AFF und ASA Systemen für iSCSI Protokoll LIFs in Aktiv/Aktiv und Aktiv/Aktiv-SCSI-only Multipath Konfigurationen sowie für NVMe/TCP Protokoll LIFs in Aktiv/Aktiv Multipath Konfigurationen unterstützt. 

* xref:../networking/improve-tcp-wan-performance.html[Verbesserte WAN Performance]
+
Die verbesserte WAN-Performance mit TCP RACK steigert Durchsatz und Ausfallsicherheit in überlasteten Netzwerken, wodurch der Dateizugriff und standortübergreifende Datendienste beschleunigt werden. 

* xref:../networking/configure-tls-offload.html[Hardware-beschleunigtes kTLS für schnellere Backend Cluster-Verschlüsselung]
+
Verbessert die Backend-Cluster-Verschlüsselung durch die Einführung von hardwarebeschleunigtem kTLS, wobei die Verschlüsselungsverarbeitung auf unterstützte SmartNICs ausgelagert wird, um höhere Leistung und geringere CPU-Last zu ermöglichen und gleichzeitig stets sichere Kommunikation über Cluster- und HA-Datenverkehr aufrechtzuerhalten. 

* xref:../anti-ransomware/use-cases-restrictions-concept.html#snapmirror[KI-gestützte Ransomware-Erkennung für synchron replizierte Workloads]
+
Erweitert den autonomen Ransomware-Schutz (ARP/AI) auf SnapMirror synchron synchron für SAN- und NAS-Umgebungen sowie SnapMirror active sync SAN-Umgebungen, wobei die Erkennungs- und Wiederherstellungssignale in Zero‑RPO-Architekturen erhalten bleiben. 

* xref:../concept-svm-admin-dashboard-sm.html[Überwachen und verwalten Sie die SVM mithilfe des neuen ONTAP System Manager-Dashboards]
+
Bietet eine mandantenfreundliche grafische Benutzeroberfläche für die SVM-Verwaltung, wodurch die Notwendigkeit einer komplexen CLI-Schnittstelle entfällt. 





[[ontap-9-18-1-highlights]]
== ONTAP 9.18.1 Highlights

ONTAP 9.18.1 bietet neue und verbesserte Funktionen in den Bereichen Sicherheit, Skalierbarkeit und Speichermanagement zur Unterstützung der Modernisierung der Dateninfrastruktur. Diese Verbesserungen ermöglichen eine bessere Skalierbarkeit, effizientere Abläufe und eine zukunftssichere Sicherung der Daten. Eine vollständige Liste der neuen Funktionen und Verbesserungen ist unter xref:whats-new-9181.adoc[Was ist neu in ONTAP 9.18.1] zu finden.

* xref:../networking/configure-backend-encryption.html[Backend Cluster HA-Verschlüsselung]
+
Fähigkeit zur Verwendung von mTLS zur Verschlüsselung des Backend-Cluster-Netzwerks.

* xref:../networking/configure_network_security_using_federal_information_processing_standards_fips.html[PQC-Unterstützung für Daten während der Übertragung]
+
Fähigkeit zur Anwendung von Post-Quanten-Algorithmen für Daten während der Übertragung.

* xref:../networking/ipsec-prepare.html[IPv6 IPSec-Unterstützung mit Hardware-Offload]
+
Unterstützung für IPSec mit Hardware-Offload mit IPv6-Adresse.

* xref:../anti-ransomware/use-cases-restrictions-concept.html#supported-configurations[ARP/AI-Unterstützung für FlexGroup volumes]
+
NetApp FlexGroup Volumes unterstützen ARP/AI und bieten fortschrittliche, auf maschinellem Lernen basierende Ransomware-Erkennung und -Schutz.

* xref:../san-admin/nvme-copy-offload.html[Copy Offload für NVMe]
+
Beschleunigt große Datenübertragungen durch direkte Auslagerung von Kopiervorgängen auf den Speicher, wodurch die CPU- und Netzwerklast des Hosts reduziert wird.

* xref:../s3-snapshots/list-restore-s3-snapshot.html[Speichergesteuerte S3-Bucket-Snapshot-Wiederherstellungen]
+
Bietet die Möglichkeit, beschädigte Objekte in einem S3-Bucket wiederherzustellen oder den gesamten Bucket über einen bestehenden Bucket wiederherzustellen.





[[ontap-9-17-1-highlights]]
== ONTAP 9.17.1 Highlights

ONTAP 9.17.1 bietet Innovationen im Bereich KI-gestützter autonomer Ransomware-Schutz für SAN und erweitert die Unterstützung um NVMe Frontend-Hosts mit SnapMirror Aktiv/Aktiv-Synchronisierung und hierarchischer Verwaltung von Konsistenzgruppen. Diese Verbesserungen stärken die Führungsposition von NetApp im Bereich Datensicherheit und Cyber-Resilienz und verbessern die ONTAP Leistung, Skalierbarkeit, Effizienz und Geschäftskontinuität. Eine vollständige Liste der neuen Funktionen und Verbesserungen ist unter xref:whats-new-9171.adoc[Was ist neu in ONTAP 9.17.1] zu finden.

* xref:../anti-ransomware/index.html[Unterstützung für SAN mit autonomem Ransomware-Schutz]
+
ARP unterstützt SAN-Volumes mit verschlüsselungsbasierter Anomalieerkennung, führt neue Befehle für detaillierte Entropie-Statistiken ein und vereinheitlicht die Ransomware-Schutzmeldungen im System Manager, die sich zuvor auf NAS-Workload konzentrierten. Konfigurierbare Erkennungsschwellenwerte und eine deterministischere Snapshot-Aufbewahrung bieten mehr Flexibilität für unterschiedliche Workloads.

* xref:../system-admin/use-hsts-task.html[HTTP Strict Transport Security (HSTS) Unterstützung]
+
ONTAP 9.17.1 unterstützt HTTP Strict Transport Security für Webdienste, wodurch die Durchsetzung einer sicheren HTTPS-Kommunikation zwischen dem Browser eines Benutzers und ONTAP ermöglicht wird.

* xref:../networking/ipsec-prepare.html[IPsec-Hardware-Offload mit Link-Aggregation-Gruppen]
+
ONTAP 9.17.1 unterstützt IPsec-Hardware-Offload für Link-Aggregation-Gruppen und erweitert die in ONTAP 9.16.1 eingeführte Hardware-Offload-Unterstützung.

* xref:../networking/ipsec-prepare.html[IPsec-Postquanten-Pre-Shared-Key-Unterstützung]
+
ONTAP unterstützt Postquanten-Pre-Shared Keys für IPsec, um vor potenziellen zukünftigen Quantencomputerangriffen zu schützen.

* xref:../encryption-at-rest/manage-keys-barbican-task.html[OpenStack Barbican-Schlüsselmanager-Unterstützung]
+
ONTAP unterstützt den OpenStack Barbican Key Manager für NetApp Volume Encryption (NVE)-Schlüssel.

* xref:../authentication/configure-jit-elevation-task.html[Just in Time (JIT)-Unterstützung für die Rechteerweiterung]
+
ONTAP unterstützt die JIT-Berechtigungserweiterung für rollenbasierte Zugriffssteuerung (RBAC). Benutzer können eine temporäre Erhöhung der Berechtigungen auf eine konfigurierte Rolle anfordern, wodurch der Zugriff auf privilegierte Befehle bei Bedarf ermöglicht wird. Cluster-Administratoren können festlegen, wer auf die JIT-Berechtigungserweiterung zugreifen kann sowie wann und wie lange der Zugriff erlaubt ist.

* xref:../system-admin/configure-saml-authentication-task.html[Unterstützung für Entra IdP und IdP-Gruppenunterstützung für SAML-Authentifizierung]
+
ONTAP unterstützt Microsoft Entra als SAML-Identitätsanbieter. Zusätzlich kann die vom IdP bereitgestellte Gruppeninformation ONTAP Rollen zugeordnet werden.

* xref:../nvme/support-limitations.html#features[SnapMirror Active Sync-Unterstützung für den Hostzugriff über NVMe]
+
SnapMirror active sync erweitert die Unterstützung für NVMe-Zugriff für VMware-Workloads mit NVMe/TCP- und NVMe/FC-Hostzugriff für ONTAP Cluster mit zwei Knoten.

* xref:../snapmirror-active-sync/index.html[ONTAP Cloud Mediator Support mit SnapMirror Active Sync]
+
ONTAP Cloud Mediator wurde in ONTAP 9.17.1 eingeführt und unterstützt SnapMirror Aktiv/Aktiv-Sync-Beziehungen. Der Cloud-basierte Mediator fungiert wie ONTAP Mediator als Quorum-Zeuge für SnapMirror Aktiv/Aktiv-Sync-Beziehungen, wodurch ein transparentes Failover sichergestellt wird und die operative Komplexität bei der Wartung und Verwaltung eines dritten Standorts reduziert wird.





[[ontap-9-16-1-highlights]]
== ONTAP 9.16.1 Highlights

ONTAP 9.16.1 bietet neue und verbesserte Funktionen in den Bereichen Sicherheitsmanagement, Datenschutz, Netzwerk, SAN-Management und Speichermanagement. Eine vollständige Liste der neuen Funktionen und Verbesserungen ist unter xref:whats-new-9161.adoc[Was ist neu in ONTAP 9.16.1] zu finden.

* xref:../multi-admin-verify/index.html#rule-protected-commands[Verbesserungen der Multi-Admin-Verifizierung (MAV)]
+
ONTAP 9.16.1 erweitert das MAV-Framework um zusätzliche Befehle für verbesserten Schutz vor böswilligen Insidern. Zu diesen Erweiterungen gehören zahlreiche Befehle für die Verwaltung von Consistency Group (CG), VScan und Autonomous Ransomware Protection (ARP) sowie für die NVMe-Konfiguration.

* xref:../anti-ransomware/index.html[Autonomer Ransomware-Schutz mit KI-Erweiterungen (ARP/AI)]
+
ARP wurde mit neuen KI-Funktionen ausgestattet, wodurch es Ransomware-Angriffe mit 99 % Präzision und Recall erkennen und darauf reagieren kann. Da die KI mit einem umfassenden Datensatz trainiert wurde, entfällt die Lernphase für ARP auf FlexVol Volumes und ARP/AI startet sofort im aktiven Modus. ARP/AI führt außerdem eine automatische Update-Funktion ein, die unabhängig von einem ONTAP Upgrade arbeitet, um einen konstanten Schutz und eine hohe Resilienz gegenüber den neuesten Bedrohungen sicherzustellen.

* NVMe/TCP über TLS 1.3
+
NVMe/TCP „über die Leitung“ wird auf der Protokollschicht mit einer vereinfachten Konfiguration und verbesserter Leistung im Vergleich zu IPSec geschützt.

* xref:../networking/ipsec-prepare.html[IPSec-HW-Offload-Unterstützung für neue Netzwerkkarten]
+
ONTAP 9.16.1 bietet eine höhere „Over-the-Wire“-Verschlüsselungsleistung, wenn die IPSec-Hardware-Offload-Funktionalität auf Offload-Karten genutzt wird, die in der neuesten Generation der AFF A-Series und AFF-C Series Systemplattformen eingeführt wurden.

* xref:../san-admin/enable-space-allocation.html[Unterstützung für die Freigabe von NVMe-Speicherplatz]
+
Die Speicherplatzfreigabe (auch „Hole Punching“ und „Unmap“ genannt) wird jetzt für NVMe-Namespaces unterstützt. Die Speicherplatzfreigabe hilft Thin-Provisioned-Volumes und NVMe-Namespaces, ungenutzten Speicherplatz zurückzugewinnen, wenn Daten von der Host-Anwendung gelöscht werden. Dies verbessert die gesamte Speichereffizienz erheblich, insbesondere bei Dateisystemen mit hohem Datenumsatz.

* xref:../flexgroup/enable-adv-capacity-flexgroup-task.html[Erweiterter Kapazitätsausgleich für FlexGroup Volumen]
+
NetApp FlexGroup Volumes können optional Daten innerhalb einer einzelnen Datei über mehrere Backend-Bestandteile verteilen, wodurch Leistungsengpässe reduziert und die Konsistenz beim Kapazitätsausgleich zwischen den Backend-Bestandteilen erhöht wird.

* xref:../svm-migrate/index.html[SVM Datenmobilität-Support für die Migration von MetroCluster Konfigurationen]
+
ONTAP unterstützt die folgenden MetroCluster SVM-Migrationen:

+
** Migration einer SVM zwischen einer Nicht-MetroCluster Konfiguration und einer MetroCluster IP Konfiguration
** Migration einer SVM zwischen zwei MetroCluster IP-Konfigurationen
** Migration einer SVM zwischen einer MetroCluster FC-Konfiguration und einer MetroCluster IP-Konfiguration






[[ontap-9-15-1-highlights]]
== ONTAP 9.15.1 Highlights

ONTAP 9.15.1 bietet neue und verbesserte Funktionen in den Bereichen Sicherheitsmanagement, Datenschutz und NAS-Workload-Unterstützung. Eine vollständige Liste der neuen Funktionen und Verbesserungen ist unter xref:whats-new-9151.adoc[Was ist neu in ONTAP 9.15.1] zu finden.

* https://www.netapp.com/data-storage/aff-a-series/["Unterstützung für neue AFF A-Serie Systeme, Speicher speziell für KI"^]
+
ONTAP 9.15.1 unterstützt die neuen Hochleistungs-Systeme AFF A1K, AFF A90 und AFF A70, die für die nächste Generation von Geschäfts-Workloads wie KI/ML-Training und Inferenz entwickelt wurden. Diese neue Systemklasse bietet bis zu doppelte Leistung im Vergleich zu den bisherigen AFF A-Series-Angeboten und sorgt für eine „Always-on“-Speichereffizienz ohne Leistungseinbußen.

* xref:../smb-admin/windows-backup-symlinks.html[Windows-Sicherungsanwendungen und Unix-Style-Symlinks auf Servern]
+
Ab ONTAP 9.15.1 besteht auch die Möglichkeit, den Symlink selbst anstelle der Daten, auf die er verweist, zu sichern. Dies kann verschiedene Vorteile bieten, darunter eine verbesserte Leistung der Sicherungsanwendungen. Die Funktion lässt sich über die ONTAP CLI oder die ONTAP REST API aktivieren.

* xref:../authentication/dynamic-authorization-overview.html[Dynamische Autorisierung]
+
ONTAP 9.15.1 führt ein erstes Framework für dynamische Autorisierung ein, eine Sicherheitsfunktion, die bestimmen kann, ob ein von einem Administratorkonto ausgegebener Befehl abgelehnt, zur zusätzlichen Authentifizierung aufgefordert oder ausgeführt werden darf. Die Entscheidungen basieren auf dem Vertrauenswert des Benutzerkontos und berücksichtigen Faktoren wie Tageszeit, Standort, IP-Adresse, Nutzung vertrauenswürdiger Geräte sowie den Authentifizierungs- und Autorisierungsverlauf des Benutzers.

* xref:../multi-admin-verify/index.html#rule-protected-commands[Erweiterter Wirkungsbereich für die Multi-Admin-Verifizierung]
+
ONTAP 9.15.1 RC1 fügt dem MAV-Framework über hundert neue Befehle für zusätzlichen Schutz vor böswilligen Insidern hinzu.

* TLS 1.3-Verschlüsselungsunterstützung für Cluster-Peering und mehr
+
ONTAP 9.15.1 führt TLS 1.3-Verschlüsselungsunterstützung für S3-Speicher, FlexCache, SnapMirror und Cluster-Peering-Verschlüsselung ein. Anwendungen wie FabricPool, Microsoft Azure Page Blobs Storage und SnapMirror Cloud verwenden in der Version 9.15.1 weiterhin TLS 1.2.

* Unterstützung für SMTP-Datenverkehr über TLS
+
Sichere Übertragung von AutoSupport-Daten per E-Mail mit TLS-Unterstützung.

* xref:../snapmirror-active-sync/index.html[SnapMirror Active Sync für symmetrische Aktiv/Aktiv Konfigurationen]
+
Diese neue Funktion bietet synchron bidirektionale Replikation für Geschäftskontinuität und Notfallwiederherstellung. Der Datenzugriff für kritische SAN-Workloads wird durch gleichzeitigen Lese- und Schreibzugriff auf Daten über mehrere Ausfalldomänen hinweg geschützt, wodurch ein unterbrechungsfreier Betrieb ermöglicht und Ausfallzeiten bei Katastrophen oder Systemausfällen minimiert werden.

* xref:../flexcache-writeback/flexcache-writeback-enable-task.html[FlexCache Write-Back]
+
FlexCache Write-Back ermöglicht es Clients, lokal auf FlexCache Volumes zu schreiben, wodurch die Latenz reduziert und die Leistung im Vergleich zum direkten Schreiben auf das Ursprungsvolume verbessert wird. Die neu geschriebenen Daten werden asynchron zurück auf das Ursprungsvolume repliziert.

* xref:../nfs-rdma/index.html[NFSv3 über RDMA]
+
Die Unterstützung von NFSv3 über RDMA kann helfen, hohe Leistungsanforderungen zu erfüllen, indem sie mit niedriger Latenz und mit einer hohen Bandbreite Zugriff über TCP bereitstellt.





[[ontap-9-14-1-highlights]]
== ONTAP 9.14.1 Highlights

ONTAP 9.14.1 bietet neue und erweiterte Funktionen in den Bereichen FabricPool, Anti-Ransomware-Schutz, OAuth und mehr. Eine vollständige Liste der neuen Funktionen und Verbesserungen ist unter xref:whats-new-9141.adoc[Was ist neu in ONTAP 9.14.1] zu finden.

* xref:../volumes/determine-space-usage-volume-aggregate-concept.html[WAFL Reservierungsreduzierung]
+
ONTAP 9.14.1 führt eine sofortige Erhöhung des nutzbaren Speicherplatzes um fünf Prozent auf FAS und Cloud Volumes ONTAP Systemen ein, indem die WAFL Reserve auf Aggregaten mit 30 TB oder mehr reduziert wird.

* xref:../fabricpool/enable-disable-volume-cloud-write-task.html[FabricPool-Verbesserungen]
+
FabricPool bietet eine Steigerung der xref:../fabricpool/enable-disable-aggressive-read-ahead-task.html[Leseleistung] und ermöglicht das direkte Schreiben in die Cloud, wodurch das Risiko eines Speicherplatzmangels verringert und die Speicherkosten gesenkt werden, indem selten genutzte Daten auf eine kostengünstigere Speicherebene verschoben werden.

* link:../authentication/oauth2-deploy-ontap.html["Unterstützung für OAuth 2.0"]
+
ONTAP unterstützt das OAuth 2.0-Framework, das über System Manager konfiguriert werden kann. Mit OAuth 2.0 lässt sich ein sicherer Zugriff auf ONTAP für Automatisierungs-Frameworks bereitstellen, ohne Benutzer-IDs und Passwörter in Klartext-Skripten und Runbooks zu erstellen oder offenzulegen.

* link:../anti-ransomware/manage-parameters-task.html["Verbesserungen des autonomen Ransomware Protection (ARP)"]
+
ARP bietet Ihnen mehr Kontrolle über die Ereignissicherheit, ermöglicht es Ihnen, die Bedingungen anzupassen, die Warnmeldungen auslösen, und verringert die Wahrscheinlichkeit von Fehlalarmen.

* xref:../data-protection/create-delete-snapmirror-failover-test-task.html[SnapMirror Notfallwiederherstellungsübung im System Manager]
+
System Manager bietet einen einfachen Workflow, um die Notfallwiederherstellung an einem entfernten Standort unkompliziert zu testen und anschließend aufzuräumen. Diese Funktion ermöglicht einfachere und häufigere Tests und erhöht das Vertrauen in die Einhaltung der Wiederherstellungszeitvorgaben.

* xref:../s3-config/index.html[S3 Object Lock Unterstützung]
+
ONTAP S3 unterstützt den object-lock API-Befehl, wodurch Daten, die mit S3 in ONTAP geschrieben werden, mithilfe von Standard-S3-API-Befehlen vor dem Löschen geschützt werden können und sichergestellt ist, dass wichtige Daten für die angemessene Zeit geschützt bleiben.

* xref:../assign-tags-cluster-task.html[Cluster] und xref:../assign-tags-volumes-task.html[Volumen] Tagging
+
Metadaten-Tags können Volumes und Clustern hinzugefügt werden, die den Daten beim Übergang von lokalen Systemen in die Cloud und umgekehrt folgen.





[[ontap-9-13-1-highlights]]
== ONTAP 9.13.1 Highlights

ONTAP 9.13.1 bietet neue und verbesserte Funktionen in den Bereichen Anti-Ransomware-Schutz, Konsistenzgruppen, Dienstqualität, Kapazitätsmanagement für Mandanten und mehr. Eine vollständige Liste der neuen Funktionen und Verbesserungen ist unter xref:whats-new-9131.adoc[Was ist neu in ONTAP 9.13.1] zu finden.

* Verbesserungen des autonomen Ransomware Protection (ARP):
+
** xref:../anti-ransomware/enable-default-task.adoc[Automatische Aktivierung]
+
Mit ONTAP 9.13.1 wechselt ARP automatisch vom Trainings- in den Produktionsmodus, sobald ausreichend Lerndaten vorliegen, wodurch die Notwendigkeit entfällt, dass ein Administrator dies nach dem 30-tägigen Zeitraum aktiviert.

** xref:../anti-ransomware/use-cases-restrictions-concept.html#multi-admin-verification-with-volumes-protected-with-arp[Unterstützung für die Multi-Admin-Verifizierung]
+
Die Deaktivierungsbefehle für ARP werden durch eine Multi-Admin-Verifizierung unterstützt, wodurch sichergestellt wird, dass kein einzelner Administrator ARP deaktivieren kann, um die Daten potenziellen Ransomware-Angriffen auszusetzen.

** xref:../anti-ransomware/use-cases-restrictions-concept.html[FlexGroup Unterstützung]
+
ARP unterstützt FlexGroup Volumes ab ONTAP 9.13.1. ARP kann FlexGroup Volumes überwachen und schützen, die sich über mehrere Volumes und Knoten im Cluster erstrecken, wodurch selbst die größten Datensätze mit ARP geschützt werden können.



* xref:../consistency-groups/index.html[Leistungs- und Kapazitätsüberwachung für Konsistenzgruppen im System Manager]
+
Die Leistungs- und Kapazitätsüberwachung liefert detaillierte Informationen für jede Konsistenzgruppe, sodass potenzielle Probleme schnell auf Anwendungsebene statt nur auf Datenobjektebene erkannt und gemeldet werden können.

* xref:../volumes/manage-svm-capacity.html[Kapazitätsmanagement für Mandanten]
+
Kunden und Serviceprovider mit mehreren Mandanten können für jede SVM ein Kapazitätslimit festlegen, sodass Mandanten die Bereitstellung im Self-Service durchführen können, ohne dass das Risiko besteht, dass ein einzelner Mandant die Kapazität des Clusters übermäßig beansprucht.

* xref:../performance-admin/adaptive-policy-template-task.html[Quality of Service Obergrenzen und Untergrenzen]
+
ONTAP 9.13.1 ermöglicht das Gruppieren von Objekten wie Volumes, LUNs oder Dateien und das Zuweisen einer QoS-Obergrenze (maximale IOPS) oder Untergrenze (minimale IOPS), wodurch die Erwartungen an die Anwendungsleistung verbessert werden.





[[ontap-9-12-1-highlights]]
== ONTAP 9.12.1 Highlights

ONTAP 9.12.1 bietet neue und erweiterte Funktionen in den Bereichen Sicherheitshärtung, Aufbewahrung, Leistung und mehr. Eine vollständige Liste der neuen Funktionen und Verbesserungen ist unter xref:whats-new-9121.adoc[Was ist neu in ONTAP 9.12.1] zu finden.

* xref:../snaplock/snapshot-lock-concept.html[Manipulationssichere Schnappschüsse]
+
Mit der SnapLock Technologie können Snapshots sowohl auf dem Quell- als auch auf dem Zielsystem vor dem Löschen geschützt werden.

+
Mehr Wiederherstellungspunkte bleiben erhalten, wenn Snapshots auf primärem und sekundärem Speicher vor dem Löschen durch Ransomware-Angreifer oder böswillige Administratoren geschützt werden.

* xref:../anti-ransomware/index.html[Verbesserungen des autonomen Ransomware Protection (ARP)]
+
Intelligenter, autonomer Ransomware-Schutz kann unmittelbar auf dem Sekundärspeicher aktiviert werden, basierend auf dem bereits für den Primärspeicher abgeschlossenen Screening-Modell.

+
Nach einem Failover werden potenzielle Ransomware-Angriffe auf den Sekundärspeicher sofort erkannt. Es wird umgehend ein Snapshot der Daten erstellt, die gerade betroffen zu werden beginnen, und Administratoren werden benachrichtigt, was dazu beiträgt, einen Angriff zu stoppen und die Wiederherstellung zu verbessern.

* xref:../nas-audit/plan-fpolicy-event-config-concept.html[FPolicy]
+
Die Aktivierung von ONTAP FPolicy mit einem Klick ermöglicht das automatische Blockieren bekannter schädlicher Dateien. Die vereinfachte Aktivierung trägt dazu bei, vor typischen Ransomware-Angriffen zu schützen, die gängige, bekannte Dateierweiterungen verwenden.

* xref:../system-admin/ontap-implements-audit-logging-concept.html[Sicherheitsverbesserung: Manipulationssichere Protokollierung der Aufbewahrung]
+
Manipulationssichere Protokollierung in ONTAP stellt sicher, dass kompromittierte Administratorkonten keine böswilligen Aktionen verbergen können. Administrator- und Benutzerhistorie können nicht ohne Wissen des Systems geändert oder gelöscht werden.

+
Alle Administratoraktionen werden unabhängig von ihrer Herkunft protokolliert und geprüft, wodurch garantiert wird, dass alle Aktionen, die Daten betreffen, erfasst werden. Sobald Systemprotokolle in irgendeiner Weise manipuliert wurden, wird eine Warnung generiert, die Administratoren über die Änderung informiert.

* xref:../authentication/setup-ssh-multifactor-authentication-task.html[Sicherheitsverbesserung: Erweiterte Multifaktor-Authentifizierung]
+
Die Multifaktor-Authentifizierung (MFA) für die CLI (SSH) unterstützt Yubikey-Hardware-Token-Geräte und stellt sicher, dass ein Angreifer nicht mit gestohlenen Zugangsdaten oder einem kompromittierten Client-System auf das ONTAP-System zugreifen kann. Cisco DUO wird für MFA mit System Manager unterstützt.

* Datei-Objekt-Dualität (Multi-Protokoll-Zugriff)
+
Die Dualität zwischen Datei- und Objektzugriff ermöglicht nativen Lese- und Schreibzugriff des S3-Protokolls auf dieselbe Datenquelle, die bereits über das NAS-Protokoll zugänglich ist. Der Speicher kann gleichzeitig als Dateien oder als Objekte aus derselben Datenquelle genutzt werden, wodurch keine doppelten Kopien von Daten für die Verwendung mit unterschiedlichen Protokollen (S3 oder NAS) erforderlich sind, etwa für Analysen, die Objektdaten verwenden.

* xref:../flexgroup/manage-flexgroup-rebalance-task.html[FlexGroup Neuausrichtung]
+
Wenn FlexGroup-Bestandteile unausgewogen werden, kann FlexGroup unterbrechungsfrei über die ONTAP CLI, die ONTAP REST API und den System Manager neu ausbalanciert und verwaltet werden. Für eine optimale Leistung sollte die genutzte Kapazität der einzelnen Bestandteile innerhalb einer FlexGroup gleichmäßig verteilt sein.

* Speicherkapazitätserweiterungen
+
Die WAFL Speicherplatzreservierung wurde deutlich reduziert, sodass pro Aggregat bis zu 40 TiB mehr nutzbare Kapazität bereitgestellt werden.





[[ontap-9-11-1-highlights]]
== ONTAP 9.11.1-Highlights

ONTAP 9.11.1 bietet neue und erweiterte Funktionen in den Bereichen Sicherheit, Aufbewahrung, Leistung und mehr. Eine vollständige Liste der neuen Funktionen und Verbesserungen ist unter xref:whats-new-9111.adoc[Was ist neu in ONTAP 9.11.1] zu finden.

* xref:../multi-admin-verify/index.html[Multi-Admin-Verifizierung]
+
Die Multi-Admin-Verifizierung (MAV) ist ein branchenweit erster nativer Ansatz zur Verifizierung, der für sensible administrative Aufgaben wie das Löschen eines Snapshots oder Volumes mehrere Genehmigungen erfordert. Die in einer MAV-Implementierung erforderlichen Genehmigungen verhindern böswillige Angriffe und versehentliche Änderungen an Daten.

* xref:../anti-ransomware/index.html[Verbesserungen beim autonomen Ransomware-Schutz]
+
Autonomous Ransomware Protection (ARP) verwendet maschinelles Lernen, um Ransomware-Bedrohungen mit erhöhter Granularität zu erkennen, sodass Bedrohungen schnell identifiziert und die Wiederherstellung im Falle eines Sicherheitsvorfalls beschleunigt werden können.

* xref:../flexgroup/supported-unsupported-config-concept.html#features-supported-beginning-with-ontap-9-11-1[SnapLock Compliance für FlexGroup Volumes]
+
Multi-Petabyte-Datensätze für Workloads wie elektronische Designautomatisierung sowie Medien & Unterhaltung werden durch den Schutz der Daten mit WORM-Dateisperrung gesichert, sodass sie nicht verändert oder gelöscht werden können.

* xref:../flexgroup/fast-directory-delete-asynchronous-task.html[Asynchrones Löschen eines Verzeichnisses]
+
Mit ONTAP 9.11.1 erfolgt das Löschen von Dateien im Hintergrund des ONTAP Systems, wodurch das Löschen großer Verzeichnisse erleichtert wird und Leistungs- sowie Latenzbeeinträchtigungen bei der Host-I/O vermieden werden.

* xref:../s3-config/index.html[S3 Erweiterungen]
+
Die Objektdatenverwaltungsfunktionen von S3 mit ONTAP werden durch zusätzliche API-Endpunkte und Objektversionierung auf Bucket-Ebene vereinfacht und erweitert, sodass mehrere Versionen eines Objekts im selben Bucket gespeichert werden können.

* System Manager Erweiterungen
+
System Manager unterstützt erweiterte Funktionen zur Optimierung von Speicherressourcen und zur Verbesserung des Audit-Managements. Zu diesen Aktualisierungen gehören verbesserte Möglichkeiten zur Verwaltung und Konfiguration von Speicheraggregaten, eine optimierte Transparenz der Systemanalysen sowie die Hardware-Visualisierung für FAS Systeme.





[[ontap-9-10-1-highlights]]
== ONTAP 9.10.1 Highlights

ONTAP 9.10.1 bietet neue und verbesserte Funktionen in den Bereichen Sicherheitsoptimierung, Leistungsanalyse, NVMe-Protokollunterstützung und Optionen zur Sicherung von Objektspeichern. Eine vollständige Liste der neuen Funktionen und Verbesserungen ist unter xref:whats-new-9101.adoc[Neues in ONTAP 9.10.1] zu finden.

* xref:../anti-ransomware/index.html[Autonomous Ransomware Protection]
+
Autonomous Ransomware Protection erstellt automatisch eine Snapshot-Kopie Ihres Volumes und benachrichtigt Administratoren, wenn ungewöhnliche Aktivitäten erkannt werden, wodurch Ransomware-Angriffe schnell erkannt und eine schnellere Wiederherstellung ermöglicht werden.

* System Manager Erweiterungen
+
System Manager lädt automatisch Firmware-Updates für Festplatten, Gehäuse und Serviceprozessoren herunter und bietet darüber hinaus neue Integrationen mit Active IQ Digital Advisor (auch bekannt als Digital Advisor), NetApp Console und der Zertifikatsverwaltung. Diese Verbesserungen vereinfachen die Administration und erhalten die Geschäftskontinuität.

* xref:../concept_nas_file_system_analytics_overview.html[Verbesserungen der Dateisystemanalyse]
+
File System Analytics liefert zusätzliche Telemetriedaten, um die wichtigsten Dateien, Verzeichnisse und Benutzer in Ihrer Dateifreigabe zu identifizieren, wodurch sich Leistungsprobleme bei Arbeitslasten erkennen lassen, um die Ressourcenplanung und die Implementierung von QoS zu verbessern.

* xref:../nvme/support-limitations.html[NVMe over TCP (NVMe/TCP) Unterstützung für AFF Systeme]
+
Hohe Leistung und geringere Gesamtbetriebskosten für Ihr Enterprise SAN und moderne Workloads auf AFF Systemen werden erreicht, wenn NVMe/TCP im bestehenden Ethernet-Netzwerk verwendet wird.

* xref:../nvme/support-limitations.html[NVMe over Fibre Channel (NVMe/FC) Unterstützung für NetApp FAS Systeme]
+
Das NVMe/FC-Protokoll kann auf Hybrid-Arrays verwendet werden, um eine einheitliche Migration zu NVMe zu ermöglichen.

* xref:../s3-snapmirror/index.html[Nativ Cloud-Backup für Objektspeicher]
+
Schützen Sie Ihre ONTAP S3-Daten mit einem Objektspeicherziel Ihrer Wahl. Mit SnapMirror Replikation kann ein Backup auf lokalem Speicher mit StorageGRID, in der Cloud mit Amazon S3 oder in einem anderen ONTAP S3-Bucket auf NetApp AFF und FAS Systemen erfolgen.

* xref:../flexcache/global-file-locking-task.html[Globale Dateisperrung mit FlexCache]
+
Die Dateikonsistenz an Cache-Standorten während Aktualisierungen von Quelldateien am Ursprung wird mit globaler Dateisperrung mithilfe von FlexCache sichergestellt. Diese Erweiterung ermöglicht exklusive Dateilesesperren in einer Ursprung-zu-Cache-Beziehung für Workloads, die eine erweiterte Sperrung erfordern.





[[ontap-9-9-1-highlights]]
== ONTAP 9.9.1-Highlights

ONTAP 9.91.1 bietet neue und verbesserte Funktionen in den Bereichen Speichereffizienz, Multifaktor-Authentifizierung, Notfallwiederherstellung und mehr. Eine vollständige Liste der neuen Funktionen und Verbesserungen ist unter xref:whats-new-991.adoc[Was ist neu in ONTAP 9.9.1] zu finden.

* Verbesserte Sicherheit für die Fernzugriffsverwaltung über die Befehlszeile
+
Die Unterstützung für SHA512 und SSH A512 Passwort-Hashing schützt die Anmeldeinformationen des Administratorkontos vor böswilligen Akteuren, die versuchen, Systemzugriff zu erlangen.

* https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_and_cable_the_mcc_components.html["MetroCluster IP-Erweiterungen: Unterstützung für 8-Knoten-Cluster"^]
+
Das neue Limit ist doppelt so hoch wie das vorherige, bietet Unterstützung für MetroCluster Konfigurationen und ermöglicht eine kontinuierliche Datenverfügbarkeit.

* xref:../snapmirror-active-sync/index.html[SnapMirror Active Sync]
+
Bietet mehr Replikationsoptionen für Backup und Disaster Recovery großer Datencontainer für NAS-Workloads.

* xref:../san-admin/storage-virtualization-vmware-copy-offload-concept.html[Erhöhte SAN-Performance]
+
Bietet eine bis zu viermal höhere SAN-Leistung für Anwendungen mit einer einzelnen LUN wie VMware Datenspeicher, sodass in Ihrer SAN-Umgebung eine hohe Leistung erreicht werden kann.

* xref:../task_cloud_backup_data_using_cbs.html[Neue Objektspeicheroption für Hybrid Cloud]
+
Ermöglicht die Nutzung von StorageGRID als Ziel für NetApp Cloud Backup Service, um die Sicherung Ihrer lokalen ONTAP-Daten zu vereinfachen und zu automatisieren.



.Nächste Schritte
* xref:../upgrade/prepare.html[Upgrade auf die neueste Version von ONTAP]
* xref:../upgrade/when-to-upgrade.html[Wann sollte ONTAP aktualisiert werden?]

