---
permalink: release-notes/release-support-reference.html 
sidebar: sidebar 
keywords: release notes, release support, support levels 
summary: Erfahren Sie mehr über die neuen in ONTAP 9 verfügbaren Funktionen. 
---
= Unterstützung für ONTAP 9 Version
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.8 veröffentlicht NetApp zweimal pro Kalenderjahr ONTAP Releases. Änderungen an den Plänen sind zwar vorbehalten, jedoch sollen im zweiten und vierten Quartal jedes Kalenderjahres neue ONTAP-Versionen veröffentlicht werden. Mithilfe dieser Informationen können Sie den Zeitrahmen für Ihr Upgrade so planen, dass Sie die aktuelle ONTAP Version nutzen können.

[cols="50,50"]
|===
| Version | Veröffentlichungsdatum 


 a| 
9.17.1
 a| 
September 2025



 a| 
9.16.1
 a| 
Januar 2025



 a| 
9.15.1
 a| 
Juli 2024



 a| 
9.14.1
 a| 
Januar 2024



 a| 
9.13.1
 a| 
Juni 2023



 a| 
9.12.1
 a| 
Februar 2023



 a| 
9.11.1
 a| 
Juli 2022



 a| 
9.10.1
 a| 
Januar 2022



 a| 
9.9.1
 a| 
Juni 2021



 a| 

NOTE: Wenn Sie eine ONTAP-Version vor 9.10 verwenden, liegt die Wahrscheinlichkeit im eingeschränkten Support oder Self-Service-Support. Erwägen Sie ein Upgrade auf Versionen mit voller Unterstützung. Sie können den Support-Level für Ihre Version von ONTAP auf der überprüfen https://mysupport.netapp.com/site/info/version-support#ontap_svst["NetApp Support-Website"^].

|===


== Support-Level

Die für eine bestimmte Version von ONTAP verfügbare Support-Stufe hängt vom Zeitpunkt der Softwareveröffentlichung ab.

[cols="20,10,10,10,10,10,10,10,10"]
|===
| Supportstufe 3+| Volle Unterstützung 2+| Eingeschränkter Support 3+| Self-Service-Support 


 a| 
Jahr
 a| 
1
 a| 
2
 a| 
3
 a| 
4
 a| 
5
 a| 
6
 a| 
7
 a| 
8



 a| 
Zugriff auf Online-Dokumentation
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.



 a| 
Technischer Support
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
 a| 
 a| 



 a| 
Ursachenanalyse
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
 a| 
 a| 



 a| 
Software-Downloads
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
 a| 
 a| 



 a| 
Service-Updates (Patch-Releases [P-Releases])
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
 a| 
 a| 
 a| 
 a| 



 a| 
Warnmeldungen zu Schwachstellen
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
 a| 
 a| 
 a| 
 a| 

|===
Informationen zum Upgrade auf die neueste Version von ONTAP finden Sie unter xref:../upgrade/prepare.html[Führen Sie ein Upgrade auf die neueste Version von ONTAP durch] und xref:../upgrade/when-to-upgrade.html[Wann sollte ich ein Upgrade von ONTAP durchführen?]
