---
permalink: release-notes/whats-new-9161.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 9.16.1' 
summary: Erfahren Sie mehr über die neuen in ONTAP 9 verfügbaren Optionen.16.1. 
---
= Neuerungen in ONTAP 9.16.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie mehr über die neuen in ONTAP 9 verfügbaren Optionen.16.1.

Details zu bekannten Problemen, Einschränkungen und Upgrade-Warnhinweisen in aktuellen ONTAP 9 Versionen finden Sie im https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 – Versionshinweise"^]. Sie müssen sich mit Ihrem NetApp Konto anmelden oder ein Konto erstellen, um auf die Versionshinweise zuzugreifen.

Erfahren Sie mehr über neue und verbesserte https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["Funktionen von ONTAP MetroCluster"^].

Erfahren Sie mehr über neue und verbesserte Unterstützung für https://docs.netapp.com/us-en/ontap-systems/whats-new.html["Plattformen und unterstützte Switches von FAS, ASA und AFF"^].

Erfahren Sie mehr über Updates zum https://docs.netapp.com/us-en/ontap-automation/whats_new.html["ONTAP REST API"^] .

Informationen zum Upgrade auf die neueste Version von ONTAP finden Sie unter link:../upgrade/create-upgrade-plan.html["Bereiten Sie sich auf das Upgrade von ONTAP vor"].



== Datensicherung

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../snapmirror-active-sync/index.html[Unterstützung für SnapMirror Active Sync mit mehreren Nodes]
 a| 
SnapMirror Active Sync wird ausgehend von der vorherigen Grenze mit zwei Nodes erweitert und unterstützt Cluster mit vier Nodes, was die Datenreplizierung für größere Workloads ermöglicht.



 a| 
xref:../data-protection/cloud-backup-with-snapmirror-task.html[SnapMirror Cloud-Unterstützung zum Erstellen von Fan-out-Beziehungen]
 a| 
SnapMirror Cloud unterstützt Fan-out-Beziehungen aus demselben Quell-Volume oder FlexGroup auf zwei verschiedene Objektspeicher. Fan-Outs können für zwei Objektspeicher und für einen oder zwei Buckets in den Objektspeichern verwendet werden.



 a| 
xref:../data-protection/cloud-backup-with-snapmirror-task.html[Unterstützung für SnapMirror Cloud Backups von einem migrierten Volume]
 a| 
Die SnapMirror Cloud unterstützt Backups von Volumes, die über vorhandene ONTAP REST-APIs in die Cloud migriert wurden. Die neue Funktion unterstützt SnapMirror Cloud-Backups von einem migrierten Volume in der Cloud auf den gleichen Ziel-Objektspeicher-Endpunkt, ohne dass ein neuer Basisplanvorgang erforderlich ist. Es werden sowohl FlexVol- als auch FlexGroup-Volumes unterstützt.

|===


== Netzwerkbetrieb

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../networking/configure_virtual_ip_vip_lifs.html#set-up-border-gateway-protocol-bgp[MD5-Authentifizierungsunterstützung für BGP-Peer-Gruppen]
 a| 
ONTAP unterstützt MD5-Authentifizierung auf BGP-Peer-Gruppen zum Schutz von BGP-Sitzungen. Wenn MD5 aktiviert ist, können BGP-Sitzungen nur unter autorisierten Peers eingerichtet und verarbeitet werden. So werden Angriffe wie das Routen-Hijacking verhindert, bei denen ein Angreifer versucht, falsche Routinginformationen ins Netzwerk einzuschleusen, indem er BGP-Updates vortäuscht.



 a| 
xref:../networking/ipsec-prepare.html[Unterstützung von IPsec-Hardware-Offload]
 a| 
IP-Sicherheit (IPsec) ist eine Data-in-Motion-Sicherheitsoption zum Schutz des gesamten IP-Datenverkehrs zwischen einem Client und einem ONTAP-Knoten. Das Protokoll war zunächst mit ONTAP 9.8 verfügbar und wurde nur als Software implementiert. Ab ONTAP 9.16.1 haben Sie die Möglichkeit, bestimmte rechenintensive Vorgänge, wie z. B. Verschlüsselungs- und Integritätsprüfungen, auf eine unterstützte NIC-Karte (Network Interface Controller) zu laden, die auf den Storage-Nodes installiert ist. Durch die Verwendung dieser Hardware-Offload-Option können die Leistung und der Durchsatz des durch IPsec geschützten Netzwerkverkehrs erheblich verbessert werden.

|===


== S3 Objekt-Storage

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
Multiprotokoll-S3-Bucket-Unterstützung für S3-Objektmetadaten und Tagging
 a| 
Ab ONTAP 9.16.1 wird das S3-Objekt-Tagging von ONTAP S3-Buckets ohne mehrere Protokolle bis hin zu NAS- und S3-Multi-Protokoll-ONTAP-S3-Buckets erweitert. Die Tags sind nur im S3-Protokoll sichtbar. Mit der Anwendung https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-tagging.html["tags und Metadaten"^] auf S3-Objekte mithilfe von S3-Clients können Sie Lebenszyklen, Rückgebühren, Datenkategorien und benutzerdefinierte Workflows für die als Objekt oder Dateien in ONTAP gespeicherten Daten definieren. Bei der Integration in AWS Datenservices wie Bedrock oder Athena sind Tagging und Metadaten zentral für die durch diese Services bereitgestellten Data Processing.


NOTE: In ONTAP 9.9 begann die Unterstützung für Tags und benutzerdefinierte Metadaten in nativen S3 Buckets.



 a| 
xref:../s3-multiprotocol/index.html[Multi-Protokoll-S3-Bucket unterstützt Multi-Part-Uploads]
 a| 
Bei mehrteiligen Uploads handelt es sich um eine grundlegende S3-Funktion, die seit ihrer Gründung für ONTAP-S3-Buckets ohne Multiprotokoll verfügbar ist. Ab ONTAP 9.16.1 ist diese Kernfunktion auch für ONTAP S3 Buckets mit mehreren Protokollen und NAS und S3 verfügbar.



 a| 
xref:../s3-config/cors-integration.html[Unterstützung für CORS (Cross-Origin Resource Sharing) für ONTAP S3 Buckets]
 a| 
Nutzen Sie das volle Potenzial Ihrer Web-Anwendungen mit Cross-Origin Resource Sharing (CORS). CORS ermöglicht eine nahtlose Interaktion zwischen Client-Anwendungen von einer Domäne und Ressourcen in einer anderen. Durch die Integration der CORS-Unterstützung können Sie Ihren ONTAP S3-basierten Webanwendungen einen selektiven Cross-Origin-Zugriff auf Ihre Ressourcen ermöglichen.



 a| 
xref:../s3-snapshots/index.html[ONTAP unterstützt das Erstellen von Snapshots von ONTAP S3 Buckets]
 a| 
Es können schreibgeschützte, zeitpunktgenaue Snapshots der ONTAP S3 Buckets generiert werden. Mit der S3-Snapshot-Funktion können Sie Snapshots manuell erstellen oder automatisch durch Snapshot-Richtlinien generieren. Darüber hinaus können Sie S3 Snapshots anzeigen, durchsuchen und löschen sowie den Snapshot Inhalt über S3-Clients wiederherstellen.

|===


== San

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../san-admin/enable-space-allocation.html[Der NVMe-Leerraum ist standardmäßig aktiviert]
 a| 
Space deallocation (auch „Hole Punching“ und „unmap“ genannt) ist standardmäßig für NVMe-Namespaces aktiviert. Space deallocation ermöglicht einem Host, nicht verwendete Blöcke aus Namespaces zu Zuordnung zu machen, um Speicherplatz zurückzugewinnen. Dies verbessert die gesamte Speichereffizienz erheblich, insbesondere bei Dateisystemen mit hohem Datenumsatz.

|===


== Sicherheit

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../multi-admin-verify/index.html#rule-protected-commands[Berechtigter Satz regelgeschützter Befehle erweitert zur Verifizierung durch mehrere Administratoren]
 a| 
Administratoren können Verifizierungsregeln für mehrere Administratoren erstellen, um Konsistenzgruppen zu schützen, einschließlich Erstellen, Löschen und Ändern von Vorgängen, Erstellen und Löschen von Konsistenzgruppen-Snapshots und anderen Befehlen.



 a| 
xref:../anti-ransomware/index.html[Autonomer Ransomware-Schutz mit KI-Verbesserungen (ARP/AI)]
 a| 
ARP wurde mit neuen KI-Funktionen aufgerüstet, wodurch die IT Ransomware-Angriffe mit 99 % Präzision und Rückruf erkennen und darauf reagieren kann. Da die AI auf einem umfassenden Datensatz trainiert wird, gibt es keine Lernphase für die Ausführung von ARP auf FlexVol Volumes und ARP/AI startet sofort im aktiven Modus. ARP/AI verfügt außerdem über eine automatische Update-Funktion, um ständigen Schutz und Ausfallsicherheit vor den neuesten Bedrohungen zu gewährleisten.


NOTE: Die ARP/AI-Funktion unterstützt derzeit nur NAS. Obwohl die automatische Aktualisierungsfunktion die Verfügbarkeit neuer Sicherheitsdateien für die Bereitstellung in System Manager anzeigt, sind diese Aktualisierungen nur für den NAS-Workload-Schutz anwendbar.



 a| 
xref:../nvme/set-up-tls-secure-channel-nvme-task.html[NVMe/TCP über TLS 1.3]
 a| 
Schützen Sie NVMe/TCP „über das Netzwerk“ auf der Protokollebene mit einer vereinfachten Konfiguration und einer verbesserten Performance im Vergleich zu IPSec.



 a| 
Unterstützung von TLS 1.3 für die FabricPool-Objektspeicher-Kommunikation
 a| 
ONTAP unterstützt TLS 1.3 für die FabricPool-Objektspeicher-Kommunikation.



 a| 
xref:../authentication/overview-oauth2.html[OAuth 2.0 für Microsoft Entra ID]
 a| 
Die Unterstützung für OAuth 2.0, die erstmals mit ONTAP 9.14.1 eingeführt wurde, wurde verbessert, um den Microsoft Entra ID-Autorisierungsserver (ehemals Azure AD) mit standardmäßigen OAuth 2.0-Ansprüchen zu unterstützen. Darüber hinaus werden die Entra ID-Standardgruppen-Ansprüche auf Basis von UUID-Stilwerten durch neue Gruppen- und Rollenzuordnungsfunktionen unterstützt. Es wurde auch eine neue Funktion zur externen Rollenzuordnung eingeführt, die mit der Entra-ID getestet wurde, aber mit jedem der unterstützten Autorisierungsserver verwendet werden kann.

|===


== Storage-Effizienz

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../volumes/qtrees-partition-your-volumes-concept.html[Erweiterte qtree Performance-Überwachung durch Einbeziehung von Latenzmetriken und Verlaufsstatistiken]
 a| 
Frühere ONTAP Versionen liefern solide Echtzeitkennzahlen für die qtree-Nutzung, wie z. B. I/O-Operationen pro Sekunde und Durchsatz in mehreren Kategorien, einschließlich Lese- und Schreibvorgänge. Ab ONTAP 9.16.1 haben Sie auch die Möglichkeit, auf Latenzstatistiken in Echtzeit zuzugreifen und archivierte Archivdaten anzuzeigen. Diese neuen Funktionen bieten IT-Storage-Administratoren einen besseren Einblick in die System-Performance und ermöglichen Trendanalysen über längere Zeiträume. So können Sie fundierte, datenbasierte Entscheidungen für den Betrieb und die Planung Ihrer Datacenter- und Cloud-Storage-Ressourcen treffen.

|===


== Verbesserungen beim Storage-Ressourcenmanagement

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../volumes/manage-svm-capacity.html[Unterstützung für Datensicherungs-Volumes in SVMs bei aktivierter Storage-Grenze]
 a| 
SVMs mit aktivierten Storage-Begrenzungen können Datensicherungs-Volumes enthalten. FlexVol Volumes in asynchronen Disaster-Recovery-Beziehungen ohne Kaskadenbeziehungen, synchrone Disaster-Recovery-Beziehungen und Wiederherstellungsbeziehungen werden unterstützt.

[NOTE]
====
In ONTAP 9.15.1 und älteren Versionen können die Storage-Grenzwerte nicht für jede SVM konfiguriert werden, die Datensicherungs-Volumes, Volumes in einer SnapMirror Beziehung oder in einer MetroCluster Konfiguration enthält.

====


 a| 
xref:../flexgroup/enable-adv-capacity-flexgroup-task.html[Unterstützung für erweiterte Kapazitätsverteilung mit FlexGroup]
 a| 
Wenn diese Option aktiviert ist, verteilt der erweiterte Kapazitätsausgleich Daten innerhalb einer Datei zwischen FlexGroup-Mitglieds-Volumes, wenn sehr große Dateien wachsen und Speicherplatz auf einem Mitglied-Volume verbrauchen.



 a| 
xref:../svm-migrate/index.html[Unterstützung der SVM-Datenmobilität für die Migration von MetroCluster Konfigurationen]
 a| 
ONTAP unterstützt die folgenden MetroCluster SVM-Migrationen:

* Migration einer SVM zwischen einer nicht-MetroCluster-Konfiguration und einer MetroCluster IP-Konfiguration
* Migrieren einer SVM zwischen zwei MetroCluster IP-Konfigurationen
* Migration einer SVM von einer MetroCluster FC-Konfiguration auf eine MetroCluster IP-Konfiguration


|===


== System Manager

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../authentication-access-control/webauthn-mfa-overview.html[Unterstützung für Phishing-resistente WebAuthn-Multi-Faktor-Authentifizierung in System Manager]
 a| 
ONTAP 9.16.1 unterstützt WebAuthn-MFA-Anmeldungen, sodass Sie bei der Anmeldung bei System Manager Hardware-Sicherheitsschlüssel als zweite Authentifizierungsmethode verwenden können.



 a| 
Unterstützung für Air-Gap-FSX-Implementierungen
 a| 
Wenn Ihre Amazon FSX for NetApp ONTAP-Bereitstellungen erkennen, dass Sie sich in einer luftgeappten Region befinden, gelangen Sie auf der Anmeldeseite in den System Manager, sodass Sie FSX for ONTAP mit System Manager verwalten können.

|===