---
permalink: release-notes/whats-new-9181.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 9.18.1' 
summary: Informationen zu den neuen Funktionen in ONTAP 9.18.1. 
---
= Was ist neu in ONTAP 9.18.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Informationen zu den neuen Funktionen in ONTAP 9.18.1.

Detaillierte Informationen zu bekannten Problemen, Einschränkungen und Hinweisen zum Upgrade in den aktuellen ONTAP 9-Versionen sind in den  https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 Versionshinweise"^] zu finden. Eine Anmeldung mit Ihrem NetApp Account oder die Erstellung eines Accounts ist erforderlich, um auf die Release Notes zuzugreifen.

* Informationen zu neuen und verbesserten Funktionen https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["ONTAP MetroCluster Funktionen"^].
* Weitere Informationen https://docs.netapp.com/us-en/ontap-afx/release-notes/whats-new-9171.html["neue und verbesserte ONTAP Softwarefunktionen für NetApp AFX Speichersysteme"^].
* Weitere Informationen https://docs.netapp.com/us-en/asa-r2/release-notes/whats-new-9171.html["Neue und verbesserte ONTAP Softwarefunktionen für NetApp ASA r2 Speichersysteme"^].
* Weitere Informationen https://docs.netapp.com/us-en/ontap-systems/whats-new.html["Neue und verbesserte Unterstützung für AFF, ASA und FAS Systeme sowie unterstützte Switches"^].
* Informationen zu Aktualisierungen der  https://docs.netapp.com/us-en/ontap-automation/whats_new.html["ONTAP REST API"^].


Ein Upgrade auf die neueste Version von ONTAP ist unter link:../upgrade/create-upgrade-plan.html["Vorbereitung auf das Upgrade von ONTAP"] beschrieben.



[[data-protection]]
== Datenschutz

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../data-protection/cloud-backup-with-snapmirror-task.html[SnapMirror Cloud-Unterstützung für MetroCluster FlexGroup Volumes]
 a| 
SnapMirror cloud unterstützt Sicherungs- und Wiederherstellungsvorgänge für FlexGroup Volumes in MetroCluster Konfigurationen.

|===


[[networking]]
== Netzwerk

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../networking/ipsec-prepare.html[IPsec Hardware Offload IPv6-Unterstützung]
 a| 
Die Unterstützung für IPsec-Hardware-Offload ist auf IPv6 ausgeweitet.



 a| 
xref:../networking/configure_network_security_using_federal_information_processing_standards_fips.html[OpenSSL PQC-Algorithmen]
 a| 
ONTAP unterstützt kryptografische Algorithmen für SSL, die auf Postquantum-Computing basieren. Diese Algorithmen bieten zusätzlichen Schutz vor potenziellen zukünftigen Quantencomputerangriffen und sind verfügbar, wenn der SSL-FIPS-Modus deaktiviert ist.



 a| 
xref:../networking/configure-backend-encryption.html[ONTAP Backend-Cluster-Netzwerkverschlüsselung]
 a| 
TLS-Verschlüsselung für Daten während der Übertragung im ONTAP Backend-Cluster-Netzwerk kann aktiviert werden.



 a| 
xref:../high-availability/ha-pair-encryption.html[ONTAP HA Netzwerkverschlüsselung]
 a| 
Sie können die Verschlüsselung für den Datenverkehr zwischen Knoten in Hochverfügbarkeitspaaren (HA) aktivieren.

|===


[[san]]
== SAN

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../san-admin/nvme-copy-offload.html[NVMe Copy Offload]
 a| 
NVMe Copy Offload ermöglicht einem NVMe-Host, Kopiervorgänge von seiner CPU auf die CPU des ONTAP Storage Controllers auszulagern. Der Host kann Daten von einem NVMe-Namespace in einen anderen kopieren, während seine CPU-Ressourcen für Anwendungsworkloads reserviert bleiben.

|===


[[s3-object-storage]]
== S3 Objektspeicher

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../s3-snapshots/list-restore-s3-snapshot.html[Unterstützung für die zeitpunktgenaue Wiederherstellung von S3-Snapshots]
 a| 
Der S3-Snapshot-Bucket ist jetzt nativ über die ONTAP CLI zugänglich. Zusätzlich besteht die Möglichkeit, auf einem S3 Client ein einzelnes Objekt, eine Gruppe von Objekten oder einen gesamten Bucket aus einem S3 Snapshot wiederherzustellen.



 a| 
xref:../s3-multiprotocol/create-nas-bucket-task.html[Unterstützung für die Erstellung von NAS-Buckets auf FlexCache volumes]
 a| 
Sie können NAS-Buckets auf FlexCache Volumes erstellen, und Anwendungen können mit dem S3-Protokoll auf Daten auf FlexCache Volumes zugreifen, wenn alle Knoten im Cluster ONTAP 9.18.1 oder höher verwenden. Weitere Informationen zum Aktivieren des S3-Zugriffs auf NAS FlexCache Volumes finden Sie unter link:../flexcache/enable-flexcache-duality.html["S3-Zugriff auf NAS-FlexCache-Volumes aktivieren"].

|===


[[security]]
== Sicherheit

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../anti-ransomware/use-cases-restrictions-concept.html#supported-configurations[FlexGroup Volume-Unterstützung für ARP/AI]
 a| 
NetApp FlexGroup Volumes unterstützen ARP/AI und bieten fortschrittliche, auf maschinellem Lernen basierende Ransomware-Erkennung und -Schutz. In ONTAP 9.17.1 und früher war nur die erste Generation von ARP für FlexGroup Volumes verfügbar. Ab ONTAP 9.18.1 verfügen FlexGroup Volumes über Parität mit FlexVol Volumes sowohl auf lokalen ONTAP Plattformen (AFF und FAS) als auch in virtuellen ONTAP Umgebungen (einschließlich Cloud Volumes ONTAP und ONTAP Select). Damit wird ARP/AI zur Standard-ARP-Technologie für sowohl FlexVol als auch FlexGroup Volumes.



 a| 
xref:../anti-ransomware/index.html#enablement-options-for-arp[ARP/AI ist für neue Volumes auf unterstützten Systemen standardmäßig aktiviert]
 a| 
Wenn Sie einen neuen Cluster erstellen oder Ihren Cluster auf 9.18.1 aktualisieren, wird ARP/AI nach einer 12-stündigen Übergangsfrist standardmäßig auf allen neuen Volumes für AFF A series, AFF C series, ASA und https://docs.netapp.com/us-en/asa-r2/secure-data/enable-anti-ransomware-protection.html["ASA r2"] Systemen automatisch aktiviert. Während dieser Übergangsfrist können Sie die standardmäßige Aktivierung ablehnen.

|===


[[storage-resource-management-enhancements]]
== Verbesserungen im Ressourcenmanagement für Speicher

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../performance-admin/adaptive-qos-policy-groups-task.html[Unterstützung für zweistufig verschachtelte QoS-Richtliniengruppen auf SVMs und Volumes]
 a| 
Sie können einer SVM und gleichzeitig den Volumes unter der SVM eine QoS-Richtlinie zuweisen.



 a| 
xref:../flexcache/create-volume-task.html[Erstellen von SVM FlexCache Volumes aus Ursprungsvolumes in einer SVM-DR-Beziehung]
 a| 
Es können SVM FlexCache Volumes von Ursprungsvolumes erstellt werden, die Teil einer SVM-DR Beziehung sind.



 a| 
xref:../volumes/commands-display-space-usage-reference.html[Befehle zur Anzeige von Informationen zur Speicherplatznutzung]
 a| 
In ONTAP 9.18.1 und höher ändert der `storage aggregate show-space` Befehl, wie die logisch referenzierte Kapazität und die logisch nicht referenzierte Kapazität gemeldet werden. Die logische referenzierte Kapazität meldet referenzierte Blöcke in allen Objekten und nicht referenzierte Blöcke in fragmentierten Objekten. Die logische nicht referenzierte Kapazität meldet nur nicht referenzierte Blöcke in Objekten, die den Füllschwellenwert überschritten haben und für die Objektlöschung und Defragmentierung in Frage kommen.

Wenn Sie beispielsweise den standardmäßigen Schwellenwert für die aggregierte Auslastung von 40 % für ONTAP S3 und StorageGRID verwenden, müssen 60 % der Blöcke in einem Objekt nicht referenziert sein, bevor die Blöcke als nicht referenzierte Kapazität gemeldet werden.

In Versionen vor ONTAP 9.18.1 meldet die logische referenzierte Kapazität referenzierte Blöcke in allen Objekten (sowohl vollständigen als auch fragmentierten Objekten). Die logische nicht referenzierte Kapazität meldet nicht referenzierte Blöcke in allen Objekten.

|===