---
permalink: release-notes/whats-new-9181.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 9.18.1' 
summary: Erfahren Sie mehr über die neuen Funktionen von ONTAP 9.18.1. 
---
= Was ist neu in ONTAP 9.18.1?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Informieren Sie sich über die neuen Funktionen in ONTAP 9.17.1.

Details zu bekannten Problemen, Einschränkungen und Upgrade-Warnhinweisen in aktuellen ONTAP 9 Versionen finden Sie im https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 – Versionshinweise"^]. Sie müssen sich mit Ihrem NetApp Konto anmelden oder ein Konto erstellen, um auf die Versionshinweise zuzugreifen.

* Erfahren Sie mehr über neue und verbesserte https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["Funktionen von ONTAP MetroCluster"^].
* Erfahren Sie mehr über  https://docs.netapp.com/us-en/ontap-afx/release-notes/whats-new-9171.html["neue und verbesserte ONTAP -Softwarefunktionen für NetApp AFX-Speichersysteme"^] .
* Erfahren Sie mehr über  https://docs.netapp.com/us-en/asa-r2/release-notes/whats-new-9171.html["neue und verbesserte ONTAP -Softwarefunktionen für NetApp ASA r2-Speichersysteme"^] .
* Erfahren Sie mehr über  https://docs.netapp.com/us-en/ontap-systems/whats-new.html["neue und erweiterte Unterstützung für AFF, ASA und FAS Systeme und unterstützte Switches"^] .
* Erfahren Sie mehr über Updates zum https://docs.netapp.com/us-en/ontap-automation/whats_new.html["ONTAP REST API"^] .


Informationen zum Upgrade auf die neueste Version von ONTAP finden Sie unter link:../upgrade/create-upgrade-plan.html["Bereiten Sie sich auf das Upgrade von ONTAP vor"].



== Netzwerkbetrieb

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../networking/ipsec-prepare.html[IPsec-Hardware-Offload IPv6-Unterstützung]
 a| 
Die Unterstützung für IPsec-Hardware-Offloading wurde auf IPv6 erweitert.



 a| 
xref:../networking/configure_network_security_using_federal_information_processing_standards_fips.html[OpenSSL PQC-Algorithmen]
 a| 
ONTAP unterstützt kryptografische Algorithmen für SSL, die auf Post-Quanten-Computing basieren. Diese Algorithmen bieten zusätzlichen Schutz vor potenziellen zukünftigen Quantencomputerangriffen und sind auch dann verfügbar, wenn der SSL-FIPS-Modus deaktiviert ist.



 a| 
xref:../networking/configure-backend-encryption.html[ONTAP Backend-Cluster-Netzwerkverschlüsselung]
 a| 
Sie können die TLS-Verschlüsselung für Daten während der Übertragung im ONTAP Backend-Clusternetzwerk aktivieren.



 a| 
xref:../high-availability/ha-pair-encryption.html[ONTAP HA-Netzwerkverschlüsselung]
 a| 
Sie können die Verschlüsselung für den Datenverkehr zwischen Knoten in Hochverfügbarkeitspaaren (HA) aktivieren.

|===


== San

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../san-admin/nvme-copy-offload.html[NVMe-Kopierauslagerung]
 a| 
NVMe Copy Offload ermöglicht es einem NVMe-Host, Kopiervorgänge von seiner CPU auf die CPU des ONTAP -Speichercontrollers auszulagern. Der Host kann Daten von einem NVMe-Namespace in einen anderen kopieren und dabei seine CPU-Ressourcen für Anwendungsworkloads reservieren.

|===


== S3 Objekt-Storage

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../s3-snapshots/list-restore-s3-snapshot.html[Unterstützung für die Wiederherstellung von S3-Snapshots zu einem bestimmten Zeitpunkt]
 a| 
Bietet die Möglichkeit, beschädigte Objekte in einem S3-Bucket wiederherzustellen oder den gesamten Bucket über einen bestehenden Bucket wiederherzustellen.

|===


== Sicherheit

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../anti-ransomware/use-cases-restrictions-concept.html#supported-configurations[FlexGroup Volume-Unterstützung für ARP/AI]
 a| 
NetApp FlexGroup -Volumes unterstützen ARP/AI und bieten so eine fortschrittliche, auf maschinellem Lernen basierende Ransomware-Erkennung und -Abwehr.  In ONTAP 9.17.1 und früheren Versionen war für FlexGroup -Volumes nur die erste Generation von ARP verfügbar.  Ab ONTAP 9.18.1 sind FlexGroup -Volumes mit FlexVol Volumes auf On-Premises ONTAP Plattformen (AFF und FAS) sowie auf virtuellen ONTAP Bereitstellungen (einschließlich Cloud Volumes ONTAP und ONTAP Select) identisch.  Daher wird ARP/AI zur Standard-ARP-Technologie sowohl für FlexVol als auch für FlexGroup -Volumes.

|===


== Verbesserungen beim Storage-Ressourcenmanagement

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../performance-admin/adaptive-qos-policy-groups-task.html[Unterstützung für zweistufige, verschachtelte QoS-Richtliniengruppen auf SVMs und Volumes]
 a| 
Sie können einer SVM und gleichzeitig den Volumes unter der SVM eine QoS-Richtlinie zuweisen.



 a| 
xref:../flexcache/create-volume-task.html[Erstellen von SVM FlexCache Volumes von Ursprungsvolumes in einer SVM-DR-Beziehung]
 a| 
Sie können SVM FlexCache Volumes von Ursprungsvolumes erstellen, die Teil einer SVM-DR-Beziehung sind.

|===