---
permalink: release-notes/whats-new-9161.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 9.16.1' 
summary: Informationen zu den neuen Funktionen in ONTAP 9.16.1. 
---
= Neues in ONTAP 9.16.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Informationen zu den neuen Funktionen in ONTAP 9.16.1.

Detaillierte Informationen zu bekannten Problemen, Einschränkungen und Hinweisen zum Upgrade in den aktuellen ONTAP 9-Versionen sind in den  https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 Versionshinweise"^] zu finden. Eine Anmeldung mit Ihrem NetApp Account oder die Erstellung eines Accounts ist erforderlich, um auf die Release Notes zuzugreifen.

* Informationen zu neuen und verbesserten Funktionen https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["ONTAP MetroCluster Funktionen"^].
* Weitere Informationen https://docs.netapp.com/us-en/asa-r2/release-notes/whats-new-9171.html["Neue und verbesserte ONTAP Softwarefunktionen für NetApp ASA r2 Speichersysteme"^].
* Weitere Informationen https://docs.netapp.com/us-en/ontap-systems/whats-new.html["Neue und verbesserte Unterstützung für AFF, ASA und FAS Systeme sowie unterstützte Switches"^].
* Informationen zu Aktualisierungen der  https://docs.netapp.com/us-en/ontap-automation/whats_new.html["ONTAP REST API"^].


Ein Upgrade auf die neueste Version von ONTAP ist unter link:../upgrade/create-upgrade-plan.html["Vorbereitung auf das Upgrade von ONTAP"] beschrieben.



[[data-protection]]
== Datenschutz

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../snapmirror-active-sync/index.html[Multinode-Unterstützung für SnapMirror Active Sync]
 a| 
Durch die Erweiterung der bisherigen Beschränkung auf zwei Knoten unterstützt SnapMirror active sync nun Cluster mit vier Knoten, was die Datenreplizierung für größere Arbeitslasten ermöglicht.



 a| 
xref:../data-protection/cloud-backup-with-snapmirror-task.html[SnapMirror Cloud-Unterstützung für die Erstellung von Fan-Out-Beziehungen]
 a| 
SnapMirror cloud unterstützt Fan-out-Beziehungen vom selben Quellvolume oder FlexGroup zu zwei verschiedenen Objektspeichern. Fan-outs können zu zwei Objektspeichern und zu einem oder zwei Buckets in den Objektspeichern bestehen.



 a| 
xref:../data-protection/cloud-backup-with-snapmirror-task.html[Unterstützung für SnapMirror Cloud-Backups von einem migrierten Volume]
 a| 
SnapMirror cloud unterstützt Backups von Volumes, die mithilfe der bestehenden ONTAP REST APIs in die Cloud migriert wurden. Die neue Funktionalität unterstützt SnapMirror cloud Backups von einem migrierten Volume in der Cloud zum selben Ziel-Objektspeicher-Endpunkt, ohne dass eine erneute Baseline-Operation erforderlich ist. Sowohl FlexVol als auch FlexGroup Volumes werden unterstützt.

|===


[[networking]]
== Netzwerk

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../networking/configure_virtual_ip_vip_lifs.html#set-up-border-gateway-protocol-bgp[MD5-Authentifizierung für BGP-Peer-Gruppen]
 a| 
ONTAP unterstützt die MD5-Authentifizierung für BGP-Peer-Gruppen zum Schutz von BGP-Sitzungen. Wenn MD5 aktiviert ist, können BGP-Sitzungen nur zwischen autorisierten Peers aufgebaut und verarbeitet werden, wodurch Angriffe wie Route Hijacking verhindert werden, bei denen ein Angreifer versucht, durch das Fälschen von BGP-Updates falsche Routing-Informationen in das Netzwerk einzuschleusen.



 a| 
xref:../networking/ipsec-prepare.html[IPsec Hardware Offload Unterstützung]
 a| 
IP-Sicherheit (IPsec) ist eine Option zur Sicherheit von Daten in Bewegung, die den gesamten IP-Verkehr zwischen einem Client und einem ONTAP-Knoten schützt. Das Protokoll war zunächst mit ONTAP 9.8 verfügbar und wurde ausschließlich als Software implementiert. Ab ONTAP 9.16.1 besteht die Möglichkeit, bestimmte rechenintensive Operationen wie Verschlüsselung und Integritätsprüfungen auf eine unterstützte Network Interface Controller (NIC)-Karte auszulagern, die in den Speicherknoten installiert ist. Die Nutzung dieser Hardware-Auslagerungsoption kann die Leistung und den Durchsatz des durch IPsec geschützten Netzwerkverkehrs erheblich verbessern.

|===


[[s3-object-storage]]
== S3 Objektspeicher

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
Multiprotokoll-S3-Bucket-Unterstützung für S3-Objektmetadaten und -Tagging
 a| 
Ab ONTAP 9.16.1 wird die S3-Objektkennzeichnung von nicht-multiprotokoll ONTAP S3 Buckets auf NAS- und S3-multiprotokoll ONTAP S3 Buckets ausgeweitet. Die Kennzeichnungen sind nur im S3-Protokoll sichtbar. Die Anwendung von  https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-tagging.html["Tags und Metadaten"^] auf S3-Objekte mithilfe von S3-Clients ermöglicht die Definition von Lebenszyklen, Rückverrechnung, Datenkategorien und benutzerdefinierten Workflows für Daten, die als Objekte oder Dateien in ONTAP gespeichert sind. Bei Integration mit AWS Data Services wie Bedrock oder Athena werden Kennzeichnung und Metadaten zu zentralen Elementen der von diesen Diensten bereitgestellten Datenverarbeitung.


NOTE: Die Unterstützung für Tags und benutzerdefinierte Metadaten in nativen S3-Buckets begann in ONTAP 9.9.1.



 a| 
xref:../s3-multiprotocol/index.html[Multiprotokoll S3 Bucket unterstützt mehrteiligen Upload]
 a| 
Multipart Uploads sind eine Kernfunktion von S3, die seit jeher für nicht-multiprotokollfähige ONTAP S3 Buckets verfügbar ist. Ab ONTAP 9.16.1 wird diese Kernfunktion auch auf NAS- und S3-Multiprotokoll ONTAP S3 Buckets ausgeweitet.



 a| 
xref:../s3-config/cors-integration.html[Cross-Origin Resource Sharing (CORS) Unterstützung für ONTAP S3 Buckets]
 a| 
Das volle Potenzial Ihrer Webanwendungen lässt sich mit Cross-Origin Resource Sharing (CORS) ausschöpfen. CORS ermöglicht eine nahtlose Interaktion zwischen Clientanwendungen einer Domäne und Ressourcen einer anderen. Durch die Integration von CORS-Unterstützung erhalten Ihre ONTAP S3-basierten Webanwendungen selektiven, ursprungsübergreifenden Zugriff auf Ihre Ressourcen.



 a| 
xref:../s3-snapshots/index.html[ONTAP unterstützt das Erstellen von Snapshots von ONTAP S3 Buckets.]
 a| 
Sie können schreibgeschützte, zeitpunktgenaue Snapshots Ihrer ONTAP S3-Buckets erstellen. Mit der S3 Snapshots Funktion lassen sich Snapshots manuell erstellen oder automatisch über Snapshot Richtlinien generieren. Zudem besteht die Möglichkeit, S3-Snapshots anzuzeigen, zu durchsuchen und zu löschen sowie den Snapshot-Inhalt über S3-Clients wiederherzustellen.

|===


[[san]]
== SAN

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../san-admin/enable-space-allocation.html[NVMe Speicherplatzfreigabe standardmäßig aktiviert]
 a| 
Die Speicherplatzfreigabe (auch „Hole Punching“ und „Unmap“ genannt) ist für NVMe-Namespaces standardmäßig aktiviert. Die Speicherplatzfreigabe ermöglicht es einem Host, ungenutzte Blöcke aus Namespaces freizugeben, um Speicherplatz zurückzugewinnen. Dies verbessert die gesamte Speichereffizienz erheblich, insbesondere bei Dateisystemen mit hohem Datenumsatz.

|===


[[security]]
== Sicherheit

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../multi-admin-verify/index.html#rule-protected-commands[Zulässiger Satz regelgeschützter Befehle für die Multi-Admin-Überprüfung erweitert]
 a| 
Administratoren können Multi-Admin-Verifizierungsregeln erstellen, um Konsistenzgruppen zu schützen, einschließlich der Operationen Erstellen, Löschen und Ändern, Erstellen und Löschen von Konsistenzgruppen-Snapshots sowie anderer Befehle.



 a| 
xref:../anti-ransomware/index.html[Autonomer Ransomware-Schutz mit KI-Erweiterungen (ARP/AI)]
 a| 
ARP wurde mit neuen KI-Funktionen ausgestattet, wodurch es Ransomware-Angriffe mit 99 % Präzision und Recall erkennen und darauf reagieren kann. Da die KI mit einem umfassenden Datensatz trainiert wurde, entfällt die Lernphase für ARP auf FlexVol Volumes und ARP/AI startet sofort im aktiven Modus. ARP/AI verfügt zudem über eine automatische Update-Funktion, die einen konstanten Schutz und eine hohe Resilienz gegenüber den neuesten Bedrohungen sicherstellt.


NOTE: Die ARP/AI-Funktion unterstützt derzeit nur NAS. Obwohl die automatische Update-Funktion die Verfügbarkeit neuer Sicherheitsdateien zur Bereitstellung im System Manager anzeigt, sind diese Updates ausschließlich für den Schutz von NAS-Workloads anwendbar.



 a| 
xref:../nvme/set-up-tls-secure-channel-nvme-task.html[NVMe/TCP über TLS 1.3]
 a| 
NVMe/TCP „über die Leitung“ wird auf der Protokollschicht mit einer vereinfachten Konfiguration und verbesserter Leistung im Vergleich zu IPSec geschützt.



 a| 
Unterstützung für TLS 1.3 für FabricPool Objektspeicherkommunikation
 a| 
ONTAP unterstützt TLS 1.3 für die Kommunikation mit FabricPool Objektspeichern.



 a| 
xref:../authentication/overview-oauth2.html[OAuth 2.0 für Microsoft Entra ID]
 a| 
Die OAuth 2.0-Unterstützung, die erstmals mit ONTAP 9.14.1 eingeführt wurde, wurde erweitert, um den Microsoft Entra ID Autorisierungsserver (ehemals Azure AD) mit standardmäßigen OAuth 2.0 Claims zu unterstützen. Zusätzlich werden die Entra ID Standard-Gruppen-Claims auf Basis von UUID-Werten durch neue Gruppen- und Rollenzuordnungsfunktionen unterstützt. Eine neue Funktion zur externen Rollenzuordnung wurde ebenfalls eingeführt, die mit Entra ID getestet wurde, aber mit jedem der unterstützten Autorisierungsserver verwendet werden kann.

|===


[[storage-efficiency]]
== Speichereffizienz

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../volumes/qtrees-partition-your-volumes-concept.html[Erweiterte Qtree-Leistungsüberwachung um Latenzmetriken und historische Statistiken]
 a| 
Frühere ONTAP-Versionen bieten robuste Echtzeit-Metriken zur Qtree-Nutzung, wie I/O-Operationen pro Sekunde und Durchsatz in mehreren Kategorien, einschließlich Lese- und Schreibvorgängen. Ab ONTAP 9.16.1 sind zusätzlich Echtzeit-Latenzstatistiken sowie archivierte historische Daten verfügbar. Diese neuen Funktionen bieten IT-Speicheradministratoren einen besseren Einblick in die Systemleistung und ermöglichen die Analyse von Trends über längere Zeiträume. Dadurch sind fundiertere, datengestützte Entscheidungen im Zusammenhang mit dem Betrieb und der Planung von Rechenzentrums- und Cloud-Speicherressourcen möglich.

|===


[[storage-resource-management-enhancements]]
== Verbesserungen im Ressourcenmanagement für Speicher

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../volumes/manage-svm-capacity.html[Unterstützung für Datenschutzvolumes in SVMs mit aktiviertem Speicherlimit]
 a| 
SVMs mit aktivierten Speicherbeschränkungen können Datensicherungs-Volumes enthalten. FlexVol-Volumes in asynchronen Disaster-Recovery-Beziehungen ohne Kaskadierung, synchronen Disaster-Recovery-Beziehungen und Wiederherstellungsbeziehungen werden unterstützt.

[NOTE]
====
In ONTAP 9.15.1 und früheren Versionen können Speichergrenzen nicht für SVMs konfiguriert werden, die Datensicherungs-Volumes, Volumes in einer SnapMirror Beziehung oder in einer MetroCluster Konfiguration enthalten.

====


 a| 
xref:../flexgroup/enable-adv-capacity-flexgroup-task.html[Unterstützung für FlexGroup fortschrittliche Kapazitätsverteilung]
 a| 
Wenn diese Funktion aktiviert ist, verteilt der erweiterte Kapazitätsausgleich die Daten innerhalb einer Datei zwischen FlexGroup Mitgliedsvolumes, wenn sehr große Dateien wachsen und Speicherplatz auf einem Mitgliedsvolume belegen.



 a| 
xref:../svm-migrate/index.html[SVM Datenmobilität-Support für die Migration von MetroCluster Konfigurationen]
 a| 
ONTAP unterstützt die folgenden MetroCluster SVM-Migrationen:

* Migration einer SVM zwischen einer Nicht-MetroCluster Konfiguration und einer MetroCluster IP Konfiguration
* Migration einer SVM zwischen zwei MetroCluster IP-Konfigurationen
* Migration einer SVM von einer MetroCluster FC Konfiguration zu einer MetroCluster IP Konfiguration


|===


[[system-manager]]
== System Manager

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../authentication-access-control/webauthn-mfa-overview.html[Unterstützung für phishingresistente WebAuthn Multifaktor-Authentifizierung im System Manager]
 a| 
ONTAP 9.16.1 unterstützt WebAuthn MFA-Logins, wodurch Hardware-Sicherheitsschlüssel als zweites Authentifizierungsverfahren beim Anmelden am System Manager verwendet werden können.

|===