---
permalink: fabricpool/create-mirror-task.html 
sidebar: sidebar 
keywords: creating, fabricpool, mirror 
summary: Um eine FabricPool Spiegelung zu erstellen, werden zwei Objektspeicher an eine einzelne FabricPool angehängt. Eine FabricPool Spiegelung kann entweder durch das Anhängen eines zweiten Objektspeichers an eine bestehende, einzelne Objektspeicher FabricPool Konfiguration erstellt werden, oder es wird eine neue, einzelne Objektspeicher FabricPool Konfiguration erstellt und anschließend ein zweiter Objektspeicher daran angehängt. FabricPool Spiegelungen können auch auf MetroCluster Konfigurationen erstellt werden. 
---
= Eine ONTAP FabricPool Spiegelung erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um eine FabricPool Spiegelung zu erstellen, werden zwei Objektspeicher an eine einzelne FabricPool angehängt. Eine FabricPool Spiegelung kann entweder durch das Anhängen eines zweiten Objektspeichers an eine bestehende, einzelne Objektspeicher FabricPool Konfiguration erstellt werden, oder es wird eine neue, einzelne Objektspeicher FabricPool Konfiguration erstellt und anschließend ein zweiter Objektspeicher daran angehängt. FabricPool Spiegelungen können auch auf MetroCluster Konfigurationen erstellt werden.

.Bevor Sie beginnen
* Die beiden Objektspeicher müssen bereits mit dem  `storage aggregate object-store config` Befehl erstellt worden sein.
* Wenn FabricPool Spiegel auf MetroCluster Konfigurationen erstellt werden:
+
** Die MetroCluster muss bereits eingerichtet und konfiguriert sein.
** Die Objektspeicher-Konfigurationen müssen auf dem ausgewählten Cluster erstellt worden sein.
+
Wenn FabricPool Spiegel auf beiden Clustern in einer MetroCluster Konfiguration erstellt werden, müssen auf beiden Clustern Objektspeicherkonfigurationen vorhanden sein.

** Wenn Sie keine lokalen Objektspeicher für MetroCluster Konfigurationen verwenden, sollte sichergestellt sein, dass eines der folgenden Szenarien vorliegt:
+
*** Objektspeicher befinden sich in unterschiedlichen Verfügbarkeitszonen
*** Objektspeicher sind so konfiguriert, dass Kopien von Objekten in mehreren Verfügbarkeitszonen aufbewahrt werden.
+
link:setup-object-stores-mcc-task.html["Einrichten von Objektspeichern für FabricPool in einer MetroCluster Konfiguration"]







.Über diese Aufgabe
Der Objektspeicher, den Sie für den FabricPool Spiegel verwenden, muss sich vom primären Objektspeicher unterscheiden.

Das Verfahren zum Erstellen eines FabricPool Spiegels ist für MetroCluster und Nicht-MetroCluster Konfigurationen gleich.

.Schritte
. Wenn keine bestehende FabricPool Konfiguration verwendet wird, kann eine neue erstellt werden, indem ein Objektspeicher mit dem  `storage aggregate object-store attach` Befehl an eine lokale Ebene angehängt wird.
+
Dieses Beispiel erstellt ein neues FabricPool, indem ein Objektspeicher an eine lokale Ebene angehängt wird.

+
[listing]
----
cluster1::> storage aggregate object-store attach -aggregate aggr1 -name my-store-1
----
. Ein zweiter Objektspeicher kann mit dem  `storage aggregate object-store mirror` Befehl an die lokale Ebene angehängt werden.
+
Dieses Beispiel bindet einen zweiten Objektspeicher an eine lokale Ebene an, um einen FabricPool Spiegel zu erstellen.

+
[listing]
----
cluster1::> storage aggregate object-store mirror -aggregate aggr1 -name my-store-2
----


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-attach.html["storage aggregate Objektspeicher anhängen"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+aggregate+object-store+config["storage aggregate Objektspeicher-Konfiguration"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-mirror.html["Speicheraggregate Objektspeicher Spiegelung"^]

