---
permalink: fabricpool/fabricpool-object-deletion.html 
sidebar: sidebar 
keywords: fabricpool, fabric pool, tiering, delete, defrag, unreclaimed, threshold 
summary: FabricPool löscht Objekte, nachdem ein bestimmter Prozentsatz der Blöcke im Objekt nicht mehr von ONTAP referenziert wird. 
---
= Anpassen der ONTAP FabricPool Objektlöschung und Defragmentierung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool löscht keine Blöcke aus angehängten Objektspeichern. Stattdessen löscht FabricPool Objekte, nachdem ein bestimmter Prozentsatz der Blöcke im Objekt nicht mehr von ONTAP referenziert wird.

Beispielsweise gibt es 1.024 4-KB-Blöcke in einem 4-MB-Objekt, das in Amazon S3 ausgelagert ist. Defragmentierung und Löschung finden erst statt, wenn weniger als 205 4-KB-Blöcke (20 % von 1.024) von ONTAP referenziert werden. Wenn genügend (1.024) Blöcke keine Referenzen mehr haben, werden ihre ursprünglichen 4-MB-Objekte gelöscht und ein neues Objekt wird erstellt.

Sie können den Schwellenwert für den nicht freigegebenen Speicherplatz in Prozent anpassen und für verschiedene Objektspeicher unterschiedliche Standardwerte festlegen. Die Standardeinstellungen sind:

|===


| Objektspeicher | ONTAP 9.8 und höher | ONTAP 9.7 bis 9.4 | ONTAP 9.3 und früher | Cloud Volumes ONTAP 


 a| 
Amazon S3
 a| 
20%
 a| 
20%
 a| 
0%
 a| 
30%



 a| 
Google Cloud Storage
 a| 
20%
 a| 
12%
 a| 
n/a
 a| 
35%



 a| 
Microsoft Azure Blob Storage
 a| 
25%
 a| 
15%
 a| 
n/a
 a| 
35%



 a| 
NetApp ONTAP S3
 a| 
40%
 a| 
n/a
 a| 
n/a
 a| 
n/a



 a| 
NetApp StorageGRID
 a| 
40%
 a| 
40%
 a| 
0%
 a| 
n/a

|===


[[unreclaimed-space-threshold]]
== Schwellenwert für nicht zurückgewonnenen Speicherplatz

Durch Ändern der Standardeinstellungen für den Schwellenwert des nicht freigegebenen Speicherplatzes wird die zulässige Objektfragmentierung erhöht oder verringert. Eine geringere Fragmentierung reduziert die vom Cloud-Tier genutzte physische Kapazität, erfordert jedoch zusätzliche Objektspeicherressourcen (Lese- und Schreibvorgänge).



[[threshold-reduction]]
=== Schwellenwertreduzierung

Um zusätzliche Kosten zu vermeiden, empfiehlt es sich, die Schwellenwerte für nicht freigegebenen Speicherplatz zu reduzieren, wenn Objektspeicher Preismodelle verwendet werden, die zwar die Speicherkosten senken, aber die Lesekosten erhöhen. Beispiele hierfür sind Amazon Standard-IA und Azure Blob Storage Cool.

Die Staffelung eines Volumens von zehn Jahre alten Projekten, das aus rechtlichen Gründen aufbewahrt wurde, kann beispielsweise mit einem Preismodell wie Standard-IA oder Cool günstiger sein als mit herkömmlichen Preismodellen. Obwohl Lesevorgänge für ein solches Volumen, einschließlich der für die Objektdefragmentierung erforderlichen Lesevorgänge, teurer sind, treten sie wahrscheinlich nicht häufig auf.



[[threshold-increases]]
=== Schwellenwerterhöhungen

Alternativ kann eine Erhöhung der Schwellenwerte für nicht freigegebenen Speicherplatz in Betracht gezogen werden, wenn die Objektfragmentierung dazu führt, dass deutlich mehr Objektspeicher-Kapazität genutzt wird, als für die von ONTAP referenzierten Daten erforderlich ist. Beispielsweise bedeutet die Verwendung eines Schwellenwerts von 20 % für nicht freigegebenen Speicherplatz in einem Worst-Case-Szenario, in dem alle Objekte maximal zulässig fragmentiert sind, dass bis zu 80 % der Gesamtkapazität in der Cloud-Tier von ONTAP nicht referenziert werden. Beispiel:

2 TB von ONTAP referenziert + 8 TB nicht von ONTAP referenziert = 10 TB Gesamtkapazität, die von der Cloud-Tier genutzt wird.

In dieser Situation könnte es vorteilhaft sein, den Schwellenwert für nicht zurückgewonnenen Speicherplatz anzuheben oder die Mindestanzahl an Kühltagen für Volumes zu erhöhen, um die von nicht referenzierten Blöcken beanspruchte Kapazität zu reduzieren.

[NOTE]
====
Während das System Objekte defragmentiert und deren Speichereffizienz erhöht, kann es zu einer Fragmentierung der zugrunde liegenden Dateien kommen, da referenzierte Blöcke in neue, effizientere Objekte geschrieben werden. Wenn der Schwellenwert für nicht zurückgewonnenen Speicherplatz deutlich erhöht wird, können Objekte entstehen, die speichereffizienter sind, jedoch eine geringere sequenzielle Leseleistung aufweisen.

Diese zusätzliche Aktivität führt zu höheren Kosten bei externen S3-Anbietern wie AWS, Azure und Google.

NetApp empfiehlt, den Schwellenwert für nicht zurückgewonnenen Speicherplatz nicht über 60% anzuheben.

====


[[change-the-unreclaimed-space-threshold]]
== Schwellenwert für nicht zurückgewonnenen Speicherplatz ändern

Sie können den Schwellenwert für den Prozentsatz des nicht zurückgewonnenen Speicherplatzes für verschiedene Objektspeicher anpassen.

.Bevor Sie beginnen
Es ist eine erweiterte Berechtigungsstufe erforderlich.

.Schritte
. Um den Standardschwellenwert für nicht zurückgewonnenen Speicherplatz zu ändern, kann der folgende Befehl angepasst und ausgeführt werden:
+
[source, cli]
----
storage aggregate object-store modify -aggregate <name> -object-store-name <name> -unreclaimed-space-threshold <%> (0%-99%)
----


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-modify.html["storage aggregate object-store modify"^]

