---
permalink: fabricpool/index.html 
sidebar: sidebar 
keywords: deciding, use, managing, storage tiers, fabricpool 
summary: FabricPool ermöglicht das automatische Tiering von Daten, je nach Häufigkeit des Zugriffs auf Daten. 
---
= Mehr über Daten-Tiering mit ONTAP FabricPool erfahren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool ermöglicht das automatische Tiering von Daten, je nach Häufigkeit des Zugriffs auf Daten.

FabricPool ist eine Hybrid-Storage-Lösung auf AFF Systemen, die ein All-Flash-Aggregat (nur SSDs) verwendet. In FAS Systemen wird entweder ein All-Flash- (nur SSDs) oder ein HDD-Aggregat als Performance-Tier und ein Objektspeicher als Cloud-Tier verwendet. Mit einer FabricPool senken Sie die Storage-Kosten, ohne dabei Einbußen bei Performance, Effizienz oder Sicherung hinnehmen zu müssen.

Der Cloud-Tier kann auf NetApp StorageGRID oder ONTAP S3 (ab ONTAP 9.8) oder auf einem der folgenden Service-Provider gespeichert werden:

* Alibaba Cloud
* Amazon S3
* Amazon Commercial Cloud Services
* Google Cloud
* IBM Cloud
* Microsoft Azure Blob Storage


[NOTE]
====
Ab ONTAP 9.7 können weitere Objektspeicher-Provider, die generische S3-APIs unterstützen, durch Auswahl des S3_Compatible Object Store-Providers verwendet werden.

====
.Verwandte Informationen
Siehe auch die https://docs.netapp.com/us-en/occm/concept_cloud_tiering.html["NetApp Cloud Tiering"^] Dokumentation.
