---
permalink: fabricpool/index.html 
sidebar: sidebar 
keywords: deciding, use, managing, storage tiers, fabricpool 
summary: FabricPool ermöglicht das automatische Tiering von Daten, je nach Häufigkeit des Zugriffs auf Daten. 
---
= FabricPool Tier Management – Überblick
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool ermöglicht das automatische Tiering von Daten, je nach Häufigkeit des Zugriffs auf Daten.

FabricPool ist eine Hybrid-Storage-Lösung mit einem All-Flash-Aggregat (nur SSDs) als Performance-Tier und einem Objektspeicher als Cloud-Tier. Mit einer FabricPool senken Sie die Storage-Kosten, ohne dabei Einbußen bei Performance, Effizienz oder Sicherung hinnehmen zu müssen.

Der Cloud-Tier kann auf NetApp StorageGRID oder ONTAP S3 (ab ONTAP 9.8) oder auf einem der folgenden Service-Provider gespeichert werden:

* Alibaba Cloud
* Amazon S3
* Google Cloud
* IBM Cloud
* Microsoft Azure Blob Storage




== Video: Tier Data und geringere Kosten – Anwendungsfall

video::Vs1-WMvj9fI[youtube,width=848,height=480]
.Verwandte Informationen
Siehe auch die https://docs.netapp.com/us-en/occm/concept_cloud_tiering.html["NetApp Cloud Tiering"^] Dokumentation.
