---
permalink: fabricpool/install-ca-certificate-storagegrid-task.html 
sidebar: sidebar 
keywords: installing, ca certificate, storagegrid 
summary: Wenn Sie die Zertifikatsprüfung für StorageGRID nicht deaktivieren möchten, müssen Sie ein StorageGRID-CA-Zertifikat auf dem Cluster installieren, damit ONTAP sich mit StorageGRID als Objektspeicher für FabricPool authentifizieren kann. 
---
= Installieren Sie ein CA-Zertifikat, wenn Sie StorageGRID verwenden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durch die Verwendung von CA-Zertifikaten wird eine vertrauenswürdige Beziehung zwischen Client-Anwendungen und StorageGRID erstellt.

Wenn Sie die Zertifikatsprüfung für StorageGRID nicht deaktivieren möchten, müssen Sie ein StorageGRID-CA-Zertifikat auf dem Cluster installieren, damit ONTAP sich mit StorageGRID als Objektspeicher für FabricPool authentifizieren kann.

Obwohl StorageGRID selbstsignierte Zertifikate generieren kann, empfiehlt sich die Verwendung signierter Zertifikate einer Zertifizierungsstelle eines Drittanbieters.

.Über diese Aufgabe
Obwohl die Installation und Verwendung von Zertifizierungsstellenzertifikaten als Best Practices empfohlen wird, ist ab ONTAP 9.4 die Installation von Zertifizierungsstellenzertifikaten für StorageGRID nicht erforderlich.

.Schritte
. Wenden Sie sich an Ihren StorageGRID-Administrator, um die https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-storagegrid-certificates-for-fabricpool.html["CA-Zertifikat des StorageGRID Systems"^]zu erhalten.
. Verwenden Sie den `security certificate install` Befehl mit dem `-type` `server-ca` Parameter, um das StorageGRID CA-Zertifikat im Cluster zu installieren.
+
Der vollständig qualifizierte Domänenname (FQDN), den Sie eingeben, muss mit dem benutzerdefinierten gemeinsamen Namen des StorageGRID-CA-Zertifikats übereinstimmen.





== Aktualisieren eines abgelaufenen Zertifikats

Um ein abgelaufenes Zertifikat zu aktualisieren, empfiehlt es sich, eine vertrauenswürdige CA zum Generieren des neuen Serverzertifikats zu verwenden. Darüber hinaus sollten Sie sicherstellen, dass das Zertifikat auf dem StorageGRID Server und auf dem ONTAP Cluster gleichzeitig aktualisiert wird, um Ausfallzeiten auf ein Minimum zu reduzieren.

.Verwandte Informationen
https://docs.netapp.com/us-en/storagegrid-family/["StorageGRID-Ressourcen"^]
