---
permalink: fabricpool/migration-controls-override-tiering-policy-task.html 
sidebar: sidebar 
keywords: cloud migration, controls, override, volume, default, tiering policy 
summary: Sie können die Standard-Tiering-Richtlinie eines Volumes für die Kontrolle der Benutzerdatenabfrage von der Cloud-Tier zu Performance-Tier ändern, indem Sie die Option -Cloud-Retrieval-Policy verwenden, die in ONTAP 9.8 eingeführt wurde. 
---
= Cloud-Migrationssteuerung zur Überbrückung der Standard-Tiering-Richtlinie eines Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die standardmäßige Tiering-Richtlinie eines Volumes ändern, um den Zugriff von Benutzerdaten über das Cloud-Tier auf das Performance-Tier zu steuern `-cloud-retrieval-policy` Option wurde in ONTAP 9.8 eingeführt.

.Was Sie benötigen
* Ändern eines Volumes mithilfe des `-cloud-retrieval-policy` Option erfordert ONTAP 9.8 oder höher.
* Sie müssen über die erweiterte Berechtigungsebene verfügen, um diesen Vorgang auszuführen.
* Sie sollten das Verhalten der Tiering-Richtlinien mit verstehen `-cloud-retrieval-policy`.
+
link:tiering-policies-concept.html#how-tiering-policies-work-with-cloud-migration["Funktionsweise von Tiering-Richtlinien bei der Cloud-Migration"]



.Schritt
. Ändern Sie das Tiering-Richtlinienverhalten eines vorhandenen Volumes mit `volume modify` Befehl mit dem `-cloud-retrieval-policy` Option:
+
[listing]
----
 volume create -volume <volume_name> -vserver <vserver_name> - tiering-policy <policy_name> -cloud-retrieval-policy
----
+
[listing]
----
vol modify -volume fp_volume4 -vserver vs0 -cloud-retrieval-policy promote
----

