---
permalink: fabricpool/modify-tiering-policy-cooling-period-task.html 
sidebar: sidebar 
keywords: managing, storage, tiering, modifying, volume, tiering, policy, tiering, minimum, cooling period 
summary: 'Sie können die Tiering-Richtlinie eines Volumes ändern, um zu kontrollieren, ob Daten zum Cloud-Tier verschoben werden, wenn sie inaktiv (nicht kalt) sind. Bei Volumes mit der Richtlinie für das rein Snapshot-basierte oder automatische Tiering können Sie auch den minimalen Kühlzeitraum für das Tiering festlegen, der die Benutzerdaten inaktiv bleiben müssen, bevor sie in die Cloud-Tier verschoben werden.' 
---
= Ändern Sie die Tiering-Richtlinie eines ONTAP Volumes sowie den minimalen Kühlzeitraum
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Tiering-Richtlinie eines Volumes ändern, um zu kontrollieren, ob Daten zum Cloud-Tier verschoben werden, wenn sie inaktiv (_Cold_) werden. Für ein Volume mit der `snapshot-only` `auto` Tiering-Richtlinie oder können Sie auch den minimalen Kühlzeitraum für das Tiering festlegen, für den Benutzerdaten vor dem Verschieben in die Cloud-Tier inaktiv bleiben müssen.

.Bevor Sie beginnen
Das Ändern eines Volumes zur `auto` Tiering Policy oder das Ändern der minimalen Kühlperiode des Tiering erfordert ONTAP 9.4 oder höher.

.Über diese Aufgabe
Durch das Ändern der Tiering-Richtlinie für ein Volume wird nur das nachfolgende Tiering-Verhalten des Volume geändert. Die Daten werden rückwirkend in die Cloud-Tier verschoben.

Eine Änderung der Tiering-Richtlinie kann beeinflussen, wie lange Daten selten benötigt werden und auf die Cloud-Tier verschoben werden.

link:tiering-policies-concept.html#what-happens-when-you-modify-the-tiering-policy-of-a-volume-in-fabricpool["Was passiert, wenn Sie die Tiering-Richtlinie eines Volumes in FabricPool ändern"]


NOTE: In einer SVM-DR-Beziehung müssen Quell- und Ziel-Volumes keine FabricPool-Aggregate verwenden, sondern sie müssen dieselbe Tiering-Richtlinie verwenden.

.Schritte
. Ändern Sie die Tiering-Richtlinie für ein vorhandenes Volume, indem Sie den `volume modify` Befehl mit dem `-tiering-policy` Parameter:
+
Sie können eine der folgenden Tiering-Richtlinien angeben:

+
** `snapshot-only` (Standard)
** `auto`
** `all`
** `none`
+
link:tiering-policies-concept.html#types-of-fabricpool-tiering-policies["Arten von FabricPool Tiering-Richtlinien"]



. Wenn das Volume die `snapshot-only` `auto` Tiering-Richtlinie oder verwendet und Sie den minimalen Kühlzeitraum für das Tiering ändern möchten, verwenden Sie den `volume modify` Befehl mit dem `-tiering-minimum-cooling-days` optionalen Parameter in der erweiterten Berechtigungsebene.
+
Sie können einen Wert zwischen 2 und 183 für die Mindestkühltage für das Tiering angeben. Wenn Sie eine Version von ONTAP vor 9.8 verwenden, können Sie für die minimalen Kühltage für das Tiering einen Wert zwischen 2 und 63 angeben.



.Beispiel einer Änderung der Tiering-Richtlinie und der Tiering-Mindestkühldauer eines Volume
Im folgenden Beispiel wird die Tiering-Richtlinie für das Volume „` yvol `m“ in der SVM „`vs1`“ in `auto` und der Tiering-Mindestkühlzeitraum auf 45 Tage geändert:

[listing]
----
cluster1::> volume modify -vserver vs1 -volume myvol
-tiering-policy auto -tiering-minimum-cooling-days 45
----