---
permalink: fabricpool/monitor-space-utilization-task.html 
sidebar: sidebar 
keywords: monitoring, space, utilization, fabricpool 
summary: Sie müssen wissen, wie viele Daten in den Performance- und Cloud-Tiers für FabricPool gespeichert werden. Anhand dieser Informationen können Sie feststellen, ob die Tiering-Richtlinie eines Volumes geändert, das FabricPool-Lizenzlimit erhöht oder der Storage-Speicherplatz des Cloud-Tiers erhöht werden muss. 
---
= Überwachung der Speicherauslastung eines FabricPool-fähigen ONTAP-Aggregats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen wissen, wie viele Daten in den Performance- und Cloud-Tiers für FabricPool gespeichert werden. Anhand dieser Informationen können Sie feststellen, ob die Tiering-Richtlinie eines Volumes geändert, das FabricPool-Lizenzlimit erhöht oder der Storage-Speicherplatz des Cloud-Tiers erhöht werden muss.

.Schritte
. Überwachen Sie die Speicherplatznutzung für FabricPool-fähige Aggregate mithilfe eines der folgenden Befehle zur Anzeige der Informationen:
+
|===


| Sie möchten Folgendes anzeigen: | Verwenden Sie dann diesen Befehl: 


 a| 
Die genutzte Größe der Cloud-Tier in einem Aggregat
 a| 
`storage aggregate show` Mit dem `-instance` Parameter



 a| 
Details zur Speicherplatznutzung in einem Aggregat, einschließlich der referenzierten Kapazität des Objektspeichers
 a| 
`storage aggregate show-space` Mit dem `-instance` Parameter



 a| 
Speicherplatzauslastung der Objektspeicher, die an die Aggregate angeschlossen sind, einschließlich der Menge an Lizenzspeicherplatz
 a| 
`storage aggregate object-store show-space`



 a| 
Eine Liste der Volumes in einem Aggregat und die Footprints ihrer Daten und Metadaten
 a| 
`volume show-footprint`

|===
+
Zusätzlich zum Verwenden von CLI-Befehlen können Sie Active IQ Unified Manager (ehemals OnCommand Unified Manager) zusammen mit FabricPool Advisor verwenden, das auf ONTAP 9.4 und höher Clustern unterstützt wird, oder System Manager zum Überwachen der Speicherauslastung.

+
Im folgenden Beispiel werden Möglichkeiten zum Anzeigen der Speicherauslastung und der damit verbundenen Informationen für FabricPool angezeigt:

+
[listing]
----
cluster1::> storage aggregate show-space -instance

                          Aggregate: MyFabricPool
                                                                   ...
                                               Aggregate Display Name: MyFabricPool
                                                                   ...
                          Total Object Store Logical Referenced Capacity: -
                          Object Store Logical Referenced Capacity Percentage: -
                                                                   ...
                                                       Object Store Size: -
                          Object Store Space Saved by Storage Efficiency: -
                          Object Store Space Saved by Storage Efficiency Percentage: -
                                                 Total Logical Used Size: -
                                                 Logical Used Percentage: -
                                           Logical Unreferenced Capacity: -
                                         Logical Unreferenced Percentage: -

----
+
[listing]
----
cluster1::> storage aggregate show -instance

                           Aggregate: MyFabricPool
                           ...
                           Composite: true
                           Capacity Tier Used Size:
                           ...
----
+
[listing]
----
cluster1::> volume show-footprint

Vserver : vs1
Volume : rootvol

Feature                          Used       Used%
-------------------------------- ---------- -----
Volume Footprint                 KB          %
Volume Guarantee                 MB          %
Flexible Volume Metadata         KB          %
Delayed Frees                    KB          %
Total Footprint                  MB          %

Vserver : vs1
Volume : vol

Feature                          Used       Used%
-------------------------------- ---------- -----
Volume Footprint                 KB          %
Footprint in Performance Tier    KB          %
Footprint in Amazon01            KB          %
Flexible Volume Metadata         MB          %
Delayed Frees                    KB          %
Total Footprint                  MB          %
...
----
. Führen Sie bei Bedarf eine der folgenden Aktionen durch:
+
|===


| Ihr Ziel ist | Dann... 


 a| 
Ändern Sie die Tiering-Richtlinie eines Volumes
 a| 
Befolgen Sie das Verfahren in link:modify-tiering-policy-cooling-period-task.html["Managen von Storage Tiering durch Ändern der Tiering-Richtlinie eines Volumes oder durch das Tiering einer minimalen Kühldauer"].



 a| 
Erhöhen Sie das Nutzungslimit für FabricPool
 a| 
Wenden Sie sich an Ihren NetApp Ansprechpartner oder einen unserer Partner.

https://mysupport.netapp.com/site/global/dashboard["NetApp Support"^]



 a| 
Erhöhen Sie den Speicherplatz des Cloud-Tiers
 a| 
Wenden Sie sich an den Anbieter des Objektspeichers, den Sie für das Cloud-Tier verwenden.

|===

