---
permalink: fabricpool/setup-google-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, google cloud storage, cloud tier 
summary: Wenn Sie ONTAP 9.6 oder höher verwenden, können Sie Google Cloud Storage als Cloud-Tier für FabricPool einrichten. 
---
= Google Cloud-Storage als ONTAP FabricPool-Cloud-Tier einrichten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ONTAP 9.6 oder höher verwenden, können Sie Google Cloud Storage als Cloud-Tier für FabricPool einrichten.



== Weitere Überlegungen bei der Verwendung von Google Cloud Storage mit FabricPool

* A link:https://bluexp.netapp.com/cloud-tiering["BlueXP Tiering Lizenz"] ist bei Tiering in Google Cloud Storage erforderlich.
* Es wird empfohlen, dass sich die logische Schnittstelle, die ONTAP für die Verbindung mit dem Google Cloud Storage-Objektserver verwendet, auf einem 10-Gbit/s-Port befindet.
* Auf AFF- und FAS-Systemen und ONTAP Select unterstützt FabricPool die folgenden Google-Cloud-Objektspeicherklassen:
+
** Google Cloud – Mehrere Regionen
** Google Cloud Regional
** Google Cloud Nearline
** Google Cloud Coldline
+
https://cloud.google.com/storage/docs/storage-classes["Google Cloud: Speicherklassen"^]





.Schritte
. Geben Sie die Konfigurationsinformationen von Google Cloud Storage mit dem `storage aggregate object-store config create` Befehl mit dem `-provider-type` `GoogleCloud` Parameter an.
+
** Der `storage aggregate object-store config create` Befehl schlägt fehl, wenn ONTAP nicht mit den angegebenen Informationen auf Google Cloud Storage zugreifen kann.
** Mit dem `-access-key` Parameter geben Sie den Zugriffsschlüssel für die Autorisierung von Anfragen an den Google Cloud Storage-Objektspeicher an.
** Wenn das Passwort für den Google Cloud-Speicher geändert wird, sollten Sie das entsprechende Passwort, das in ONTAP gespeichert ist, sofort aktualisieren.
+
So kann ONTAP unterbrechungsfrei auf die Daten in Google Cloud Storage zugreifen.



+
[listing]
----
storage aggregate object-store config create my_gcp_store_1 -provider-type GoogleCloud  -container-name my-gcp-bucket1 -access-key GOOGAUZZUV2USCFGHGQ511I8
----
. Mit dem `storage aggregate object-store config show` Befehl können Sie die Konfigurationsinformationen von Google Cloud Storage anzeigen und überprüfen.
+
 `storage aggregate object-store config modify`Mit dem Befehl können Sie die Konfigurationsinformationen zu Google Cloud Storage für FabricPool ändern.


