---
permalink: fabricpool/setup-ontap-s3-cloud-tier-task.html 
sidebar: sidebar 
keywords: tr-4814, fabricpool, setting up, ontap s3, cloud tier, local tier, tiering, storage tiering, storage tier, lif 
summary: Wenn Sie ONTAP 9.8 oder höher verwenden, können Sie ONTAP S3 als Cloud-Tier für FabricPool einrichten. 
---
= ONTAP S3 als FabricPool-Cloud-Tier einrichten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ONTAP 9.8 oder höher verwenden, können Sie ONTAP S3 als Cloud-Tier für FabricPool einrichten.

.Bevor Sie beginnen
* Sie müssen im Remote-Cluster den ONTAP S3-Servernamen und die IP-Adresse der zugehörigen LIFs haben.
+

NOTE: Der Servername wird von Client-Anwendungen als vollständig qualifizierter Domänenname (FQDN) verwendet. Außerhalb von ONTAP sollten Sie DNS-Einträge zu den verwendeten SVM-Daten-LIFs bestätigen.

* Es muss sich  auf dem lokalen Cluster befinden<<create-lif,Intracluster-LIFs>>.
+
Wenn eine lokale Cluster-Tier (in der ONTAP CLI auch als Storage-Aggregat bezeichnet) für lokales Cluster-Tiering konfiguriert wird, wird sie mit einem lokalen Bucket verbunden. FabricPool verwendet Cluster LIFs für Intracluster-Traffic.

+

NOTE: Wenn die LIF-Ressourcen des Clusters gesättigt werden, kann es zu Performance-Einbußen kommen. Zur Vermeidung dieses Vorfalls empfiehlt NetApp beim Tiering auf einen lokalen Bucket mit vier Nodes oder mehr sowie ein HA-Paar für die lokale Tier und ein HA-Paar für den lokalen Bucket. Das Tiering in lokale Buckets auf einem einzelnen HA-Paar wird nicht empfohlen.

* Um Remote-Tiering für FabricPool-Kapazität (Cloud) mit ONTAP S3 zu aktivieren, müssen Sie link:../s3-config/create-intercluster-lifs-remote-fabricpool-tiering-task.html["Konfigurieren Sie Intercluster LIFs"]auf dem FabricPool-Client und link:../s3-config/create-data-lifs-task.html["Konfigurieren Sie Daten-LIFs"] auf dem Objektspeicher-Server sein.


.Über diese Aufgabe
Der Lastausgleich ist für ONTAP S3 Server in ONTAP 9.8 und höher aktiviert. Wenn der Hostname des Servers auf mehr als eine IP-Adresse auflöst, stellt ONTAP Client-Verbindungen mit allen zurückgegebenen IP-Adressen her (bis zu 16 IP-Adressen). Die IP-Adressen werden bei Verbindungsaufbau in einer Round-Robin-Methode erfasst.

.Verfahren
Sie können ONTAP S3 als Cloud-Tier für FabricPool mit ONTAP System Manager oder über die ONTAP-CLI einrichten.

[role="tabbed-block"]
====
.System Manager
--
. Klicken Sie auf *Storage > Tiers > Cloud Tier hinzufügen* und wählen Sie ONTAP S3 als Objektspeicher-Provider aus.
. Füllen Sie die angeforderten Informationen aus.
. Wenn Sie einen Cloud-Spiegel erstellen möchten, klicken Sie auf *als FabricPool-Spiegel hinzufügen*.


Ein FabricPool Mirror stellt eine Methode für Sie zum nahtlosen Austausch eines Datenspeichers dar und stellt sicher, dass im Falle eines Ausfalls Ihre Daten verfügbar sind.

--
.CLI
--
. Fügen Sie Einträge für den S3-Server und LIFs Ihrem DNS-Server hinzu.
+
|===


| Option | Beschreibung 


 a| 
*Wenn Sie einen externen DNS-Server verwenden*
 a| 
Geben Sie den S3-Servernamen und die IP-Adressen dem DNS-Serveradministrator ein.



 a| 
*Wenn Sie die DNS-Host-Tabelle Ihres lokalen Systems verwenden*
 a| 
Geben Sie den folgenden Befehl ein:

[listing]
----
dns host create -vserver <svm_name> -address ip_address -hostname <s3_server_name>
----
|===
. Geben Sie die Konfigurationsinformationen für ONTAP S3 mit dem `storage aggregate object-store config create` Befehl mit dem `-provider-type` `ONTAP_S3` Parameter an.
+
** Der `storage aggregate object-store config create` Befehl schlägt fehl, wenn das lokale ONTAP-System nicht auf den ONTAP S3-Server mit den angegebenen Informationen zugreifen kann.
** Mit dem `-access-key` Parameter geben Sie den Zugriffsschlüssel für die Autorisierung von Anfragen an den ONTAP S3-Server an.
** Mit dem `-secret-password` Parameter geben Sie das Passwort (geheimer Zugriffsschlüssel) für die Authentifizierung von Anfragen an den ONTAP S3-Server an.
** Wenn das ONTAP S3-Serverpasswort geändert wird, sollten Sie das entsprechende Passwort, das im lokalen ONTAP-System gespeichert ist, sofort aktualisieren.
+
Dies ermöglicht den Zugriff auf die Daten im ONTAP S3-Objektspeicher ohne Unterbrechung.

** Wenn Sie den `-is-certificate-validation-enabled` Parameter auf festlegen, `false` wird die Zertifikatüberprüfung für ONTAP S3 deaktiviert. Die Verwendung von signierten Zertifikaten (`-is-certificate-validation-enabled true`) von einer Drittzertifizierungsstelle ist eine empfohlene Best Practice.


+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name myS3 -provider-type ONTAP_S3 -server myS3server
-container-name myS3container -access-key myS3key
-secret-password myS3pass
----
. Mit dem `storage aggregate object-store config show` Befehl können Sie die Konfigurationsinformationen von ONTAP_S3 anzeigen und überprüfen.
+
 `storage aggregate object-store config modify`Mit dem Befehl können Sie die `ONTAP_S3` Konfigurationsinformationen für FabricPool ändern.



--
====
[[create-lif]]
.Verwandte Informationen
* link:../smb-config/create-lif-task.html["LIF für SMB erstellen"]
* link:../nfs-config/create-lif-task.html["LIF für NFS erstellen"]

