---
permalink: fabricpool/setup-ibm-object-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, ibm cloud, object storage, cloud tier 
summary: Wenn Sie ONTAP 9.5 oder höher verwenden, kann IBM Cloud Object Storage als Cloud-Ebene für FabricPool eingerichtet werden. 
---
= IBM Cloud Object Storage als ONTAP FabricPool Cloud-Tier einrichten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ONTAP 9.5 oder höher verwenden, kann IBM Cloud Object Storage als Cloud-Ebene für FabricPool eingerichtet werden.

.Überlegungen zur Verwendung von IBM Cloud Object Storage mit FabricPool
* A link:install-license-aws-azure-ibm-task.html["FabricPool Lizenz"] ist erforderlich, wenn von lokalen Clustern zu IBM Cloud Object Storage migriert wird.
* Es wird empfohlen, dass der LIF, den ONTAP zur Verbindung mit dem IBM Cloud Objektspeicher verwendet, an einem 10 Gbit/s Port angeschlossen ist.


.Schritte
. Die Konfigurationsinformationen für IBM Cloud Object Storage werden mit dem  `storage aggregate object-store config create` Befehl und dem  `-provider-type` `IBM_COS` Parameter angegeben.
+
** Der  `storage aggregate object-store config create` Befehl schlägt fehl, wenn ONTAP mit den angegebenen Informationen nicht auf IBM Cloud Object Storage zugreifen kann.
** Der  `-access-key`Parameter wird verwendet, um den Zugriffsschlüssel für die Autorisierung von Anfragen an den IBM Cloud Object Storage Objektspeicher anzugeben.
** Der  `-secret-password`Parameter wird verwendet, um das Passwort (geheimer Zugriffsschlüssel) für die Authentifizierung von Anfragen an den IBM Cloud Object Storage Objektspeicher anzugeben.
** Wenn das Passwort für IBM Cloud Object Storage geändert wird, ist das entsprechende in ONTAP gespeicherte Passwort umgehend zu aktualisieren.
+
Dadurch kann ONTAP ohne Unterbrechung auf die Daten im IBM Cloud Object Storage zugreifen.



+
[listing]
----
storage aggregate object-store config create
-object-store-name MyIBM -provider-type IBM_COS
-server s3.us-east.objectstorage.softlayer.net
-container-name my-ibm-cos-bucket -access-key DXJRXHPXHYXA9X31X3JX
----
. Die Konfigurationsinformationen von IBM Cloud Object Storage werden mit dem  `storage aggregate object-store config show` Befehl angezeigt und überprüft.
+
Der  `storage aggregate object-store config modify`Befehl ermöglicht die Änderung der IBM Cloud Object Storage-Konfigurationsinformationen für FabricPool.



.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-create.html["storage aggregate Objektspeicher config create"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-object-store-config-modify.html["storage aggregate Objektspeicher config modify"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-show.html["storage aggregate Objektspeicher-Konfiguration anzeigen"^]

