---
permalink: fabricpool/setup-ibm-object-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, ibm cloud, object storage, cloud tier 
summary: Wenn Sie ONTAP 9.5 oder höher verwenden, können Sie IBM Cloud Object Storage als Cloud-Tier für FabricPool einrichten. 
---
= IBM Cloud Object Storage als Cloud-Tier für ONTAP FabricPool einrichten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ONTAP 9.5 oder höher verwenden, können Sie IBM Cloud Object Storage als Cloud-Tier für FabricPool einrichten.

.Überlegungen bei der Verwendung von IBM Cloud Object Storage with FabricPool
* Alink:https://console.netapp.com/cloud-tiering["NetApp Cloud Tiering-Lizenz"] ist beim Tiering auf IBM Cloud Object Storage erforderlich.
* Es wird empfohlen, sich die logische Schnittstelle, die ONTAP für die Verbindung mit dem IBM Cloud-Objektserver verwendet, auf einem 10-Gbit/s-Port zu befinden.


.Schritte
. Geben Sie die Konfigurationsinformationen `storage aggregate object-store config create` `-provider-type` `IBM_COS` für IBM Cloud Object Storage mithilfe des Befehls mit dem Parameter an.
+
** Der `storage aggregate object-store config create` Befehl schlägt fehl, wenn ONTAP nicht mit den angegebenen Informationen auf IBM Cloud Object Storage zugreifen kann.
** Sie verwenden den `-access-key` Parameter, um den Zugriffsschlüssel für die Autorisierung von Anfragen zum IBM Cloud Object Storage-Objektspeicher anzugeben.
** Sie verwenden den `-secret-password` Parameter, um das Passwort (geheimer Zugriffsschlüssel) für die Authentifizierung von Anfragen an den IBM Cloud Object Storage-Objektspeicher anzugeben.
** Wenn das IBM Cloud Object Storage-Passwort geändert wird, sollten Sie das entsprechende Passwort, das in ONTAP gespeichert ist, sofort aktualisieren.
+
Somit ist es ONTAP möglich, ohne Unterbrechung auf die Daten in IBM Cloud Object Storage zuzugreifen.



+
[listing]
----
storage aggregate object-store config create
-object-store-name MyIBM -provider-type IBM_COS
-server s3.us-east.objectstorage.softlayer.net
-container-name my-ibm-cos-bucket -access-key DXJRXHPXHYXA9X31X3JX
----
. Mit dem `storage aggregate object-store config show` Befehl können Sie die Konfigurationsinformationen für IBM Cloud Object Storage anzeigen und überprüfen.
+
 `storage aggregate object-store config modify`Mit dem Befehl können Sie die Konfigurationsinformationen für IBM Cloud Object Storage für FabricPool ändern.



.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-create.html["Speicheraggregat Objektspeicher Konfiguration erstellen"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-object-store-config-modify.html["Speicheraggregat Objektspeicher Konfiguration ändern"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-show.html["Speicheraggregat Objektspeicher Konfiguration anzeigen"^]

