---
permalink: fabricpool/setup-alibaba-object-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting, up, alibaba cloud object, storage, cloud tier 
summary: Wenn Sie ONTAP 9.6 oder höher verwenden, können Sie Alibaba Cloud-Objekt-Storage als Cloud-Tier für FabricPool einrichten. 
---
= Alibaba Cloud-Objekt-Storage als ONTAP FabricPool-Cloud-Tier einrichten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ONTAP 9.6 oder höher verwenden, können Sie Alibaba Cloud-Objekt-Storage als Cloud-Tier für FabricPool einrichten.

.Überlegungen zur Verwendung von Alibaba Cloud Objekt-Storage mit FabricPool
* Bei Tiering auf Alibaba Cloud Object Storage ist A link:https://bluexp.netapp.com/cloud-tiering["BlueXP Tiering Lizenz"]erforderlich. Weitere Informationen finden Sie unter link:install-license-aws-azure-ibm-task.html["Installieren Sie eine FabricPool-Lizenz auf einem ONTAP-Cluster"].
* Auf AFF- und FAS-Systemen und ONTAP Select unterstützt FabricPool die folgenden Alibaba-Objektspeicherservice-Klassen:
+
** Alibaba Object Storage Service Standard
** Alibaba Object Storage Service Infrequent Access
+
https://www.alibabacloud.com/help/doc-detail/51374.htm["Alibaba Cloud: Einführung in Storage-Klassen"^]





Wenden Sie sich an Ihren NetApp Vertriebsmitarbeiter, um Informationen zu Storage-Klassen zu erhalten, die nicht aufgeführt sind.

.Schritte
. Geben Sie die Konfigurationsinformationen `storage aggregate object-store config create` `-provider-type` `AliCloud` für Alibaba Cloud Object Storage mithilfe des Befehls mit dem Parameter an.
+
** Der `storage aggregate object-store config create` Befehl schlägt fehl, wenn ONTAP nicht mit den bereitgestellten Informationen auf Alibaba Cloud Object Storage zugreifen kann.
** Sie verwenden den `-access-key` Parameter, um den Zugriffsschlüssel für die Autorisierung von Anfragen an den Alibaba Cloud Object Storage-Objektspeicher anzugeben.
** Wenn das Alibaba Cloud Object Storage-Passwort geändert wird, sollten Sie das entsprechende Passwort, das in ONTAP gespeichert ist, sofort aktualisieren.
+
So kann ONTAP ohne Unterbrechung auf die Daten in Alibaba Cloud-Objekt-Storage zugreifen.



+
[listing]
----
storage aggregate object-store config create my_ali_oss_store_1
-provider-type AliCloud -server oss-us-east-1.aliyuncs.com
-container-name my-ali-oss-bucket -access-key DXJRXHPXHYXA9X31X3JX
----
. Mit dem `storage aggregate object-store config show` Befehl können Sie die Konfigurationsinformationen für Alibaba Cloud Object Storage anzeigen und überprüfen.
+
 `storage aggregate object-store config modify`Mit dem Befehl können Sie die Konfigurationsinformationen zum Alibaba Cloud-Objektspeicher für FabricPool ändern.



.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-create.html["Speicheraggregat Objektspeicher Konfiguration erstellen"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-object-store-config-modify.html["Speicheraggregat Objektspeicher Konfiguration ändern"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-show.html["Speicheraggregat Objektspeicher Konfiguration anzeigen"^]

