---
permalink: nfs-config/add-storage-capacity-nfs-enabled-svm-concept.html 
sidebar: sidebar 
keywords: add, storage, capacity, nfs-enabled, svm 
summary: Um einer NFS-fähigen SVM Storage-Kapazität hinzuzufügen, müssen Sie ein Volume oder qtree erstellen, um einen Storage-Container bereitzustellen, und eine Exportrichtlinie für diesen Container erstellen oder ändern. Anschließend können Sie den NFS-Client-Zugriff vom Cluster aus überprüfen und den Zugriff von Client-Systemen testen. 
---
= Erfahren Sie, wie Sie einem ONTAP NFS-fähigen SVM Speicherkapazität hinzufügen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um einer NFS-fähigen SVM Storage-Kapazität hinzuzufügen, müssen Sie ein Volume oder qtree erstellen, um einen Storage-Container bereitzustellen, und eine Exportrichtlinie für diesen Container erstellen oder ändern. Anschließend können Sie den NFS-Client-Zugriff vom Cluster aus überprüfen und den Zugriff von Client-Systemen testen.

.Bevor Sie beginnen
* NFS muss vollständig auf der SVM eingerichtet sein.
* Die standardmäßige Exportrichtlinie für das SVM-Root-Volume muss eine Regel enthalten, die den Zugriff auf alle Clients gestattet.
* Alle Aktualisierungen Ihrer Namensdienstkonfiguration müssen abgeschlossen sein.
* Alle Erweiterungen oder Änderungen an einer Kerberos-Konfiguration müssen abgeschlossen sein.

