---
permalink: nfs-config/assign-export-policy-qtree-task.html 
sidebar: sidebar 
keywords: assign, export, policy, qtree 
summary: Anstatt ein ganzes Volume zu exportieren, können Sie auch einen bestimmten qtree auf ein Volume exportieren und direkt für Clients zugänglich machen. Sie können einen qtree exportieren, indem Sie ihm eine Exportrichtlinie zuweisen. Sie können die Exportrichtlinie entweder beim Erstellen eines neuen qtree oder durch Ändern eines vorhandenen qtree zuweisen. 
---
= Weisen Sie einem Qtree eine ONTAP NFS-Exportrichtlinie zu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Anstatt ein ganzes Volume zu exportieren, können Sie auch einen bestimmten qtree auf ein Volume exportieren und direkt für Clients zugänglich machen. Sie können einen qtree exportieren, indem Sie ihm eine Exportrichtlinie zuweisen. Sie können die Exportrichtlinie entweder beim Erstellen eines neuen qtree oder durch Ändern eines vorhandenen qtree zuweisen.

.Bevor Sie beginnen
Die Exportrichtlinie muss vorhanden sein.

.Über diese Aufgabe
Standardmäßig übernehmen die qtrees die übergeordneten Exportrichtlinien des enthaltenden Volumes, wenn dies zum Zeitpunkt der Erstellung nicht anders angegeben wird.

Sie können eine Exportrichtlinie einem qtree zuweisen, wenn Sie den qtree erstellen oder jederzeit nach dem Erstellen des qtree. Sie können eine Exportrichtlinie dem qtree zuordnen, obwohl eine Richtlinie mit vielen qtrees verknüpft werden kann.

.Schritte
. Wenn beim Erstellen des qtree keine Exportrichtlinie angegeben wurde, weisen Sie dem qtree eine Exportrichtlinie zu:
+
`volume qtree modify -vserver _vserver_name_ -qtree-path /vol/_volume_name/qtree_name_ -export-policy _export_policy_name_`

. Vergewissern Sie sich, dass die Richtlinie dem qtree zugewiesen war:
+
`volume qtree show -qtree _qtree_name_ -fields export-policy`



.Beispiel
Die folgenden Befehle ordnen Sie der SVM vs1 die Exportrichtlinie nfs_Policy dem qtree qt1 zu und überprüfen Sie die Zuweisung:

[listing]
----
cluster::> volume modify -v1server vs1 -qtree-path /vol/vol1/qt1 -policy nfs_policy

cluster::>volume qtree show -volume vol1 -fields export-policy
vserver volume qtree export-policy
------- ------ ----- -------------
vs1     data1  qt01  nfs_policy
----