---
permalink: nfs-config/configure-dns-host-name-resolution-task.html 
sidebar: sidebar 
keywords: enabling, dns, host-name, resolution, enable, host, name, resolve, automatic configuration validation 
summary: Sie können den Name-Service dns-Befehl der vServer-Dienste verwenden, um DNS für eine SVM zu aktivieren und ihn für die Host-Name-Auflösung zu konfigurieren. Host-Namen werden mithilfe externer DNS-Server aufgelöst. 
---
= Aktivieren Sie DNS für die Auflösung des Host-Namens
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können mit dem `vserver services name-service dns` Befehl DNS auf einer SVM aktivieren und für die Verwendung von DNS für die Auflösung von Host-Namen konfigurieren. Host-Namen werden mithilfe externer DNS-Server aufgelöst.

.Was Sie benötigen
Ein standortweiter DNS-Server muss für die Suche nach Hostnamen verfügbar sein.

Sie sollten mehrere DNS-Server konfigurieren, um Single Point of Failure zu vermeiden.  `vserver services name-service dns create`Wenn Sie nur einen DNS-Servernamen eingeben, gibt der Befehl eine Warnung aus.

.Über diese Aufgabe
Der _Network Management Guide_ enthält Informationen zur Konfiguration von dynamischem DNS auf der SVM.

.Schritte
. DNS auf der SVM aktivieren:
+
`vserver services name-service dns create -vserver _vserver_name_ -domains _domain_name_ -name-servers _ip_addresses_ -state enabled`

+
Mit dem folgenden Befehl werden externe DNS-Server auf der SVM vs1 aktiviert:

+
[listing]
----
vserver services name-service dns create -vserver vs1.example.com -domains example.com -name-servers 192.0.2.201,192.0.2.202 -state enabled
----
+
[NOTE]
====
Ab ONTAP 9.2 `vserver services name-service dns create` führt der Befehl eine automatische Konfigurationsprüfung durch und meldet eine Fehlermeldung, wenn ONTAP den Name Server nicht kontaktieren kann.

====
. Zeigen Sie die DNS-Domänenkonfigurationen mit dem `vserver services name-service dns show` Befehl an.
+
Mit dem folgenden Befehl werden die DNS-Konfigurationen für alle SVMs im Cluster angezeigt:

+
[listing]
----
vserver services name-service dns show
                                             Name
Vserver           State     Domains             Servers
----------------- --------- ------------------- -------------
cluster1          enabled   example.com         192.0.2.201,
                                                192.0.2.202
vs1.example.com   enabled   example.com         192.0.2.201,
                                                192.0.2.202
----
+
Mit dem folgenden Befehl werden detaillierte DNS-Konfigurationsinformationen für SVM vs1 angezeigt:

+
[listing]
----
vserver services name-service dns show -vserver vs1.example.com
               Vserver: vs1.example.com
               Domains: example.com
          Name Servers: 192.0.2.201, 192.0.2.202
    Enable/Disable DNS: enabled
        Timeout (secs): 2
      Maximum Attempts: 1
----
. Überprüfen Sie den Status der Namensserver mit dem `vserver services name-service dns check` Befehl.
+
Der `vserver services name-service dns check` Befehl ist ab ONTAP 9.2 verfügbar.

+
[listing]
----
vserver services name-service dns check -vserver vs1.example.com

Vserver           Name Server     Status       Status Details
----------------  -------------   ----------   --------------------------
vs1.example.com   10.0.0.50         up         Response time (msec): 2
vs1.example.com   10.0.0.51         up         Response time (msec): 2
----

