---
permalink: nfs-config/configure-name-services-concept.html 
sidebar: sidebar 
keywords: configure, name, services 
summary: Abhängig von der Konfiguration Ihres Speichersystems muss ONTAP Host-, Benutzer-, Gruppen- oder Netzgruppeninformationen abrufen können, um den Clients den korrekten Zugriff zu ermöglichen. Namensdienste müssen so konfiguriert werden, dass ONTAP auf lokale oder externe Namensdienste zugreifen kann, um diese Informationen zu erhalten. 
---
= Informationen zu ONTAP NFS Namensdiensten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Abhängig von der Konfiguration Ihres Speichersystems muss ONTAP Host-, Benutzer-, Gruppen- oder Netzgruppeninformationen abrufen können, um den Clients den korrekten Zugriff zu ermöglichen. Namensdienste müssen so konfiguriert werden, dass ONTAP auf lokale oder externe Namensdienste zugreifen kann, um diese Informationen zu erhalten.

Es empfiehlt sich, einen Namensdienst wie NIS oder LDAP zu verwenden, um Namensauflösungen während der Client-Authentifizierung zu erleichtern. Nach Möglichkeit sollte LDAP für eine höhere Sicherheit eingesetzt werden, insbesondere bei der Bereitstellung von NFSv4 oder höher. Lokale Benutzer und Gruppen sollten ebenfalls konfiguriert werden, falls externe Namensserver nicht verfügbar sind.

Namensdienstinformationen müssen auf allen Quellen synchron gehalten werden.
