---
permalink: nfs-config/create-local-unix-user-task.html 
sidebar: sidebar 
keywords: create, local, unix, user 
summary: 'Der Befehl `vserver services name-service unix-user create` kann verwendet werden, um lokale UNIX-Benutzer zu erstellen. Ein lokaler UNIX-Benutzer ist ein UNIX-Benutzer, der auf der SVM als Option für UNIX-Name Services erstellt wird und bei der Verarbeitung von Namenszuordnungen verwendet werden kann.' 
---
= Lokale UNIX-Benutzer auf ONTAP NFS SVMs erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der  `vserver services name-service unix-user create` Befehl kann verwendet werden, um lokale UNIX-Benutzer zu erstellen. Ein lokaler UNIX-Benutzer ist ein UNIX-Benutzer, der auf der SVM als Option für UNIX-Name Services erstellt wird und bei der Verarbeitung von Namenszuordnungen verwendet werden kann.

.Schritt
. Einen lokalen UNIX-Benutzer erstellen:
+
`vserver services name-service unix-user create -vserver _vserver_name_ -user _user_name_ -id _integer_ -primary-gid _integer_ -full-name _full_name_`

+
`-user _user_name_`Gibt den Benutzernamen an. Der Benutzername darf maximal 64 Zeichen lang sein.

+
`-id _integer_` gibt die von Ihnen zugewiesene Benutzer-ID an.

+
`-primary-gid _integer_` Gibt die primäre Gruppen-ID an. Dadurch wird der Benutzer zur primären Gruppe hinzugefügt. Nach der Erstellung des Benutzers ist eine manuelle Hinzufügung zu jeder gewünschten weiteren Gruppe möglich.



.Beispiel
Der folgende Befehl erstellt einen lokalen UNIX-Benutzer namens johnm (vollständiger Name "John Miller") auf der SVM namens vs1. Der Benutzer hat die ID 123 und die primäre Gruppen-ID 100.

[listing]
----
node::> vserver services name-service unix-user create -vserver vs1 -user johnm -id 123
-primary-gid 100 -full-name "John Miller"
----