---
permalink: nfs-config/create-nis-domain-config-task.html 
sidebar: sidebar 
keywords: create, nis, domain, configuration, configure 
summary: 'Wenn in Ihrer Umgebung ein Network Information Service (NIS) für Name Services verwendet wird, müssen Sie eine NIS-Domänenkonfiguration für die SVM mit dem Befehl Name-Service nis-Domain create für die vserver-Services erstellen.' 
---
= Erstellen Sie eine NIS-Domänenkonfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn in Ihrer Umgebung ein Network Information Service (NIS) für Name-Services verwendet wird, müssen Sie eine NIS-Domänenkonfiguration für die SVM mithilfe von erstellen `vserver services name-service nis-domain create` Befehl.

.Was Sie benötigen
Alle konfigurierten NIS-Server müssen verfügbar sein und erreichbar sein, bevor Sie die NIS-Domäne auf der SVM konfigurieren.

Wenn Sie NIS für die Verzeichnissuchung verwenden möchten, dürfen die Karten in Ihren NIS-Servern nicht mehr als 1,024 Zeichen für jeden Eintrag enthalten. Geben Sie den NIS-Server nicht an, der dieser Beschränkung nicht entspricht. Andernfalls kann der Client-Zugriff, der von NIS-Einträgen abhängig ist, fehlschlagen.

.Über diese Aufgabe
Sie können mehrere NIS-Domänen erstellen. Sie können jedoch nur ein Gerät verwenden, das auf festgelegt ist `active`.

Wenn Ihre NIS-Datenbank eine enthält `netgroup.byhost` ONTAP kann das Programm für schnellere Suchvorgänge verwenden. Der `netgroup.byhost` Und `netgroup` Karten im Verzeichnis müssen stets synchron gehalten werden, um Clientzugriffsprobleme zu vermeiden. Ab ONTAP 9.7 ist NIS verfügbar `netgroup.byhost` Einträge können mit dem zwischengespeichert werden `vserver services name-service nis-domain netgroup-database` Befehle.

Die Verwendung von NIS für die Auflösung des Host-Namens wird nicht unterstützt.

.Schritte
. Erstellen einer NIS-Domänenkonfiguration:
+
`vserver services name-service nis-domain create -vserver vs1 -domain _domain_name_ -active true _-servers IP_addresses_`

+
Sie können bis zu 10 NIS-Server angeben.

+
[NOTE]
====
Ab ONTAP 9.2 Field Portal `-nis-servers` Ersetzt das Feld `-servers`. Dieses neue Feld kann entweder einen Hostnamen oder eine IP-Adresse für den NIS-Server enthalten.

====
. Vergewissern Sie sich, dass die Domäne erstellt wurde:
+
`vserver services name-service nis-domain show`



.Beispiel
Mit dem folgenden Befehl wird eine aktive NIS-Domain-Konfiguration für eine NIS-Domäne namens nisdomain auf der SVM mit dem Namen vs1 erstellt und mit einem NIS-Server unter der IP-Adresse 192.0.2.180 erstellt:

[listing]
----
vs1::> vserver services name-service nis-domain create -vserver vs1
-domain nisdomain -active true -nis-servers 192.0.2.180
----