---
permalink: nfs-config/load-local-unix-groups-uri-task.html 
sidebar: sidebar 
keywords: load, local, unix, groups, uri 
summary: Alternativ zur manuellen Erstellung einzelner lokaler UNIX-Gruppen können Sie eine Liste lokaler UNIX-Gruppen aus einem Uniform Resource Identifier in SVMs laden, indem Sie den Befehl vserver services name-service unix-group load-from-uri verwenden. 
---
= Lokale UNIX-Gruppen von URIs auf ONTAP NFS SVMs laden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Alternativ zur manuellen Erstellung einzelner lokaler UNIX-Gruppen kann eine Liste lokaler UNIX-Gruppen mithilfe des  `vserver services name-service unix-group load-from-uri` Befehls aus einem Uniform Resource Identifier (URI) in SVMs geladen werden.

.Schritte
. Erstellen Sie eine Datei mit der Liste der lokalen UNIX-Gruppen, die geladen werden sollen.
+
Die Datei muss Gruppeninformationen im UNIX `/etc/group`-Format enthalten:

+
`_group_name: password: group_ID: comma_separated_list_of_users_`

+
Der Befehl verwirft den Wert des  `_password_` Feldes.

+
Die maximal unterstützte Dateigröße beträgt 1 MB.

+
Die maximale Länge jeder Zeile in der Gruppendatei beträgt 32.768 Zeichen.

. Es ist sicherzustellen, dass die Liste keine doppelten Einträge enthält.
+
Die Liste darf keine doppelten Einträge enthalten, da sonst das Laden fehlschlägt. Sind bereits Einträge in der SVM vorhanden, muss entweder der  `-overwrite` Parameter auf  `true` gesetzt werden, um alle vorhandenen Einträge mit der neuen Datei zu überschreiben, oder es muss sichergestellt werden, dass die neue Datei keine Einträge enthält, die vorhandene Einträge duplizieren.

. Kopieren Sie die Datei auf einen Server.
+
Der Server muss vom Speichersystem über HTTP, HTTPS, FTP oder FTPS erreichbar sein.

. Ermittelt wird, welcher URI für die Datei gilt.
+
Der URI ist die Adresse, die Sie dem Speichersystem angeben, um den Speicherort der Datei zu kennzeichnen.

. Die Datei mit der Liste der lokalen UNIX-Gruppen wird aus dem URI in die SVM geladen:
+
`vserver services name-service unix-group load-from-uri -vserver _vserver_name_ -uri {ftp|http|ftps|https}://_uri_ -overwrite {true|false}`

+
`-overwrite`  `true` `false`} gibt an, ob Einträge überschrieben werden. Der Standardwert ist `false`. Wird dieser Parameter als  `true` angegeben, ersetzt ONTAP die gesamte vorhandene lokale UNIX-Gruppendatenbank der angegebenen SVM durch die Einträge aus der Datei, die geladen wird.



.Beispiel
Der folgende Befehl lädt eine Liste lokaler UNIX-Gruppen aus dem URI `+ftp://ftp.example.com/group+` in die SVM mit dem Namen vs1. Vorhandene Gruppen auf der SVM werden durch die Informationen aus dem URI nicht überschrieben.

[listing]
----
vs1::> vserver services name-service unix-group load-from-uri -vserver vs1
-uri ftp://ftp.example.com/group -overwrite false
----