---
permalink: nfs-config/open-export-policy-svm-root-volume-task.html 
sidebar: sidebar 
keywords: open, export, policy, svm, root, volume 
summary: Die Standardexportrichtlinie des SVM-Root-Volumes muss eine Regel enthalten, die allen Clients den offenen Zugriff über NFS ermöglicht. Ohne eine solche Regel wird allen NFS-Clients der Zugriff auf die SVM und ihre Volumes verweigert. 
---
= NFS-Client-Zugriff auf der ONTAP SVM öffnen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Standardexportrichtlinie des SVM-Root-Volumes muss eine Regel enthalten, die allen Clients den offenen Zugriff über NFS ermöglicht. Ohne eine solche Regel wird allen NFS-Clients der Zugriff auf die SVM und ihre Volumes verweigert.

.Über diese Aufgabe
Wenn eine neue SVM erstellt wird, wird automatisch eine Standard-Exportregel (genannt default) für das Root-Volume der SVM erstellt. Es müssen eine oder mehrere Regeln für die Standard-Exportregel erstellt werden, bevor Clients auf Daten auf der SVM zugreifen können.

Es empfiehlt sich zu überprüfen, ob der Zugriff für alle NFS-Clients in der Standard-Exportregel offen ist; anschließend kann der Zugriff auf einzelne Volumes eingeschränkt werden, indem benutzerdefinierte Exportregeln für einzelne Volumes oder qtrees erstellt werden.

.Schritte
. Wenn Sie eine vorhandene SVM verwenden, überprüfen Sie die Standard-Exportregel für das Root-Volume:
+
`vserver export-policy rule show`

+
Die Ausgabe des Befehls sollte in etwa wie folgt aussehen:

+
[listing]
----

cluster::> vserver export-policy rule show -vserver vs1.example.com -policyname default -instance

                                    Vserver: vs1.example.com
                                Policy Name: default
                                 Rule Index: 1
                            Access Protocol:  nfs
Client Match Hostname, IP Address, Netgroup, or Domain: 0.0.0.0/0
                             RO Access Rule: any
                             RW Access Rule: any
User ID To Which Anonymous Users Are Mapped: 65534
                   Superuser Security Types: any
               Honor SetUID Bits in SETATTR: true
                  Allow Creation of Devices: true
----
+
Existiert eine solche Regel, die offenen Zugang erlaubt, ist diese Aufgabe abgeschlossen. Falls nicht, folgt der nächste Schritt.

. Eine Exportregel für das SVM-Root-Volume erstellen:
+
`vserver export-policy rule create -vserver _vserver_name_ -policyname default -ruleindex 1 -protocol nfs -clientmatch 0.0.0.0/0 -rorule any ‑rwrule any -superuser any`

+
Wenn die SVM nur Volumes enthält, die durch Kerberos gesichert sind, können die Exportregeloptionen `-rorule`, `-rwrule` und `-superuser` für das Root-Volume auf  `krb5` oder  `krb5i` gesetzt werden. Beispiel:

+
`-rorule krb5i -rwrule krb5i -superuser krb5i`

. Die Regelerstellung kann mithilfe des  `vserver export-policy rule show` Befehls überprüft werden.


.Ergebnis
Jeder NFS-Client kann nun auf jedes Volume oder jeden Qtree zugreifen, der auf der SVM erstellt wurde.
