---
permalink: nfs-config/set-export-rules-index-number-task.html 
sidebar: sidebar 
keywords: manage, processing, order, export rules 
summary: Mit dem Befehl vserver Export-Policy rule setindex können Sie manuell die Indexnummer einer vorhandenen Exportregel festlegen. Dadurch können Sie festlegen, durch welche Priorität ONTAP Exportregeln auf Client-Anforderungen anwendet. 
---
= Verwalten der Verarbeitungsreihenfolge der Exportregeln
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit dem `vserver export-policy rule setindex` Befehl können Sie die Indexnummer einer vorhandenen Exportregel manuell festlegen. Dadurch können Sie festlegen, durch welche Priorität ONTAP Exportregeln auf Client-Anforderungen anwendet.

.Über diese Aufgabe
Wenn die neue Indexnummer bereits verwendet wird, fügt der Befehl die Regel an der angegebenen Stelle ein und ordnet die Liste entsprechend neu an.

.Schritt
. Die Indexnummer einer angegebenen Exportregel ändern:
+
`vserver export-policy rule setindex -vserver _virtual_server_name_ -policyname _policy_name_ -ruleindex _integer_ -newruleindex _integer_`



.Beispiel
Mit dem folgenden Befehl wird die Indexnummer einer Exportregel unter Indexnummer 3 in die Indexnummer 2 in einer Exportrichtlinie namens rs1 auf der SVM mit dem Namen vs1 geändert:

[listing]
----
vs1::> vserver export-policy rule setindex -vserver vs1
-policyname rs1 -ruleindex 3 -newruleindex 2
----