---
permalink: nfs-config/test-access-client-systems-task.html 
sidebar: sidebar 
keywords: testing, nfs, access, client, systems 
summary: Nachdem der NFS-Zugriff auf das neue Speicherobjekt überprüft wurde, empfiehlt es sich, die Konfiguration zu testen, indem Sie sich an einem NFS-Administrationshost anmelden und Daten vom SVM lesen sowie Daten auf das SVM schreiben. Anschließend empfiehlt es sich, den Vorgang als Nicht-Root-Benutzer auf einem Client-System zu wiederholen. 
---
= ONTAP NFS-Zugriff von Clientsystemen testen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem der NFS-Zugriff auf das neue Speicherobjekt überprüft wurde, empfiehlt es sich, die Konfiguration zu testen, indem Sie sich an einem NFS-Administrationshost anmelden und Daten vom SVM lesen sowie Daten auf das SVM schreiben. Anschließend empfiehlt es sich, den Vorgang als Nicht-Root-Benutzer auf einem Client-System zu wiederholen.

.Bevor Sie beginnen
* Das Clientsystem muss über eine IP-Adresse verfügen, die von der zuvor angegebenen Exportregel erlaubt ist.
* Sie benötigen die Anmeldeinformationen für den Root-Benutzer.


.Schritte
. Im Cluster lässt sich die IP-Adresse des LIF überprüfen, das das neue Volume hostet:
+
`network interface show –vserver _svm_name_`

+
Weitere Informationen zu  `network interface show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["ONTAP-Befehlsreferenz"^].

. Als Root-Benutzer am Administrationshost-Clientsystem anmelden.
. Das Verzeichnis wird in den Mount-Ordner geändert:
+
`cd /mnt/`

. Einen neuen Ordner unter Verwendung der IP-Adresse der SVM erstellen und einbinden:
+
.. Einen neuen Ordner erstellen: +
`mkdir /mnt/_folder_`
.. Das neue Volume in diesem neuen Verzeichnis einbinden: +
`mount -t nfs -o hard _IPAddress_:/_volume_name_ /mnt/_folder_`
.. Das Verzeichnis in den neuen Ordner ändern: +
`cd _folder_`
+
Die folgenden Befehle erstellen einen Ordner namens test1, mounten das Volume vol1 an der IP-Adresse 192.0.2.130 im Mount-Ordner test1 und wechseln in das neue Verzeichnis test1:

+
[listing]
----
host# mkdir /mnt/test1
host# mount -t nfs -o hard 192.0.2.130:/vol1 /mnt/test1
host# cd /mnt/test1
----


. Eine neue Datei wird erstellt, das Vorhandensein überprüft und Text hineingeschrieben:
+
.. Eine Testdatei erstellen: +
`touch _filename_`
.. Es wird überprüft, ob die Datei existiert.
`ls -l _filename_`
.. Eingabe: +
`cat > _filename_`
+
Geben Sie einen Text ein und anschließend Strg+D, um den Text in die Testdatei zu schreiben.

.. Den Inhalt der Testdatei anzeigen. +
`cat _filename_`
.. Die Testdatei entfernen: +
`rm _filename_`
.. Zurück zum übergeordneten Verzeichnis: +
`cd ..`
+
[listing]
----
host# touch myfile1
host# ls -l myfile1
-rw-r--r-- 1 root root 0 Sep 18 15:58 myfile1
host# cat >myfile1
This text inside the first file
host# cat myfile1
This text inside the first file
host# rm -r myfile1
host# cd ..
----


. Als Root-Benutzer die gewünschten UNIX-Besitzrechte und Berechtigungen für das gemountete Volume festlegen.
. Auf einem in Ihren Exportregeln angegebenen UNIX-Clientsystem als einer der autorisierten Benutzer mit Zugriff auf das neue Volume anmelden und die Schritte 3 bis 5 wiederholen, um zu überprüfen, ob das Volume gemountet und eine Datei erstellt werden kann.

