---
permalink: nfs-config/work-netgroups-task.html 
sidebar: sidebar 
keywords: work, netgroups 
summary: 'Sie können Netzgruppen zur Benutzerauthentifizierung verwenden und Clients in den Regeln für Exportrichtlinien zuordnen. Sie können über externe Nameserver (LDAP oder NIS) auf Netzgruppen zugreifen oder Netzgruppen über einen einheitlichen Resource Identifier (URI) in SVMs laden. Verwenden Sie dazu den vserver Services Name-Service netgroup load-Befehl.' 
---
= Arbeiten mit Netzgruppen Übersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Netzgruppen zur Benutzerauthentifizierung verwenden und Clients in den Regeln für Exportrichtlinien zuordnen. Sie können über externe Nameserver (LDAP oder NIS) den Zugriff auf Netzgruppen ermöglichen oder Netgroups über eine einheitliche Resource Identifier (URI) in SVMs laden `vserver services name-service netgroup load` Befehl.

Bevor Sie mit Netzgruppen arbeiten, müssen Sie sicherstellen, dass die folgenden Bedingungen erfüllt sind:

* Alle Hosts in Netgroups, unabhängig von den Quelldateien (NIS, LDAP oder lokale Dateien), müssen sowohl vorwärts (A) als auch rückwärts (PTR) DNS-Einträge enthalten, um eine konsistente vorwärts- und rückwärts-DNS-Suche zu ermöglichen.
+
Wenn zudem eine IP-Adresse eines Clients mehrere PTR-Datensätze hat, müssen alle diese Hostnamen Mitglieder der Netzwerkgruppe sein und entsprechende Datensätze haben.

* Die Namen aller Hosts in Netzwerkgruppen müssen unabhängig von ihrer Quelle (NIS, LDAP oder lokale Dateien) korrekt geschrieben werden und den richtigen Fall verwenden. Falls Inkonsistenzen bei in Netzgruppen verwendeten Hostnamen zu unerwarteten Verhaltensweisen führen können, z. B. fehlgeschlagene Exportprüfungen.
* Alle IPv6-Adressen, die in Netzgruppen angegeben sind, müssen gekürzt und komprimiert werden, wie in RFC 5952 angegeben.
+
Beispiel: 2011:hu9:0:0:0:0:3:1 muss verkürzt werden auf 2011:hu9::3:1.



Wenn Sie mit Netzgruppen arbeiten, können Sie die folgenden Vorgänge ausführen:

* Sie können das verwenden `vserver export-policy netgroup check-membership` Befehl, um zu ermitteln, ob eine Client-IP Mitglied einer bestimmten Netzwerkgruppe ist.
* Sie können das verwenden `vserver services name-service getxxbyyy netgrp` Befehl, um zu überprüfen, ob ein Client Teil einer Netzwerkgruppe ist.
+
Der zugrunde liegende Service für die Suche wird basierend auf der konfigurierten Name-Service-Switch-Reihenfolge ausgewählt.


