---
permalink: nfs-config/work-netgroups-task.html 
sidebar: sidebar 
keywords: work, netgroups 
summary: Sie können Netzgruppen zur Benutzerauthentifizierung und zum Abgleich von Clients in Exportrichtlinienregeln verwenden. Sie können Zugriff auf Netzgruppen von externen Namensservern bereitstellen oder Netzgruppen aus einem Uniform Resource Identifier in SVMs mithilfe des Befehls vserver services name-service netgroup load laden. 
---
= Informationen zu Netgroups auf ONTAP NFS SVMs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Netzgruppen zur Benutzerauthentifizierung und zum Abgleich von Clients in Exportrichtlinienregeln verwenden. Der Zugriff auf Netzgruppen kann von externen Namensservern (LDAP oder NIS) bereitgestellt werden, oder Netzgruppen können mithilfe des  `vserver services name-service netgroup load` Befehls aus einem Uniform Resource Identifier (URI) in SVMs geladen werden.

.Bevor Sie beginnen
Bevor Sie mit Netgroups arbeiten, muss sichergestellt sein, dass die folgenden Bedingungen erfüllt sind:

* Alle Hosts in Netgroups, unabhängig von der Quelle (NIS, LDAP oder lokale Dateien), müssen sowohl Forward- (A) als auch Reverse- (PTR) DNS-Einträge besitzen, um konsistente Forward- und Reverse-DNS-Lookups bereitzustellen.
+
Wenn eine IP-Adresse eines Clients über mehrere PTR-Einträge verfügt, müssen außerdem alle diese Hostnamen Mitglieder der Netgroup sein und über entsprechende A-Einträge verfügen.

* Die Namen aller Hosts in Netgroups müssen, unabhängig von ihrer Quelle (NIS, LDAP oder lokale Dateien), korrekt geschrieben sein und die richtige Groß-/Kleinschreibung aufweisen. Inkonsistenzen bei der Groß-/Kleinschreibung von Hostnamen in Netgroups können zu unerwartetem Verhalten führen, wie zum Beispiel zu fehlgeschlagenen Exportprüfungen.
* Alle in Netzgruppen angegebenen IPv6-Adressen müssen gemäß RFC 5952 gekürzt und komprimiert sein.
+
Beispielsweise muss 2011:hu9:0:0:0:0:3:1 zu 2011:hu9::3:1 verkürzt werden.



.Über diese Aufgabe
Bei der Arbeit mit Netzwerkgruppen können die folgenden Operationen durchgeführt werden:

* Der  `vserver export-policy netgroup check-membership`Befehl kann verwendet werden, um festzustellen, ob eine Client-IP-Adresse Mitglied einer bestimmten Netzgruppe ist.
* Mit dem  `vserver services name-service getxxbyyy netgrp` Befehl lässt sich überprüfen, ob ein Client Teil einer Netgroup ist.
+
Der für die Namensauflösung zugrunde liegende Dienst wird basierend auf der konfigurierten Reihenfolge des Name Service Switch ausgewählt.


