---
permalink: system-admin/accessg-node-log-core-dump-mib-files-task.html 
sidebar: sidebar 
keywords: service, processor, infrastructure, spi, web, service, node, log, core, dump, mib, file, browser 
summary: 'Der Webdienst für die Service Processor Infrastructure (spi) ist standardmäßig aktiviert, um einen Webbrowser den Zugriff auf die Protokoll-, Core Dump- und MIB-Dateien eines Knotens im Cluster zu ermöglichen. Der Zugriff auf die Dateien bleibt auch dann möglich, wenn der Node ausfällt, wenn der Node vom Partner übernommen wird.' 
---
= Zugriff über einen Webbrowser auf ONTAP Node-Protokolle, Core Dumps und MIB-Dateien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der (`spi`Webdienst Service Processor Infrastructure ) ist standardmäßig aktiviert, um einen Webbrowser zu ermöglichen, auf die Protokoll-, Core Dump- und MIB-Dateien eines Knotens im Cluster zuzugreifen. Der Zugriff auf die Dateien bleibt auch dann möglich, wenn der Node ausfällt, wenn der Node vom Partner übernommen wird.

.Bevor Sie beginnen
* Die Cluster-Management-LIF muss aktiv sein.
+
Sie können die Management-LIF des Clusters oder einen Node für den Zugriff auf den `spi` Web-Service verwenden. Allerdings wird die Verwendung der Cluster-Management-LIF empfohlen.

+
Der `network interface show` Befehl zeigt den Status aller LIFs im Cluster an.

* Sie müssen ein lokales Benutzerkonto verwenden `spi`, um auf den Webdienst zuzugreifen. Domänenbenutzerkonten werden nicht unterstützt.
* Wenn Ihr Benutzerkonto nicht über die Rolle „`admin`“ verfügt (die `spi` standardmäßig Zugriff auf den Webdienst hat), muss Ihre Zugriffskontrollfunktion Zugriff auf den `spi` Webdienst erhalten.
+
Der `vserver services web access show` Befehl zeigt an, welchen Rollen Zugriff auf welche Webservices gewährt wird.

* Wenn Sie das Benutzerkonto „`admin`“ nicht verwenden (das `http` standardmäßig die Zugriffsmethode enthält), muss Ihr Benutzerkonto mit der Zugriffsmethode eingerichtet werden `http`.
+
Der `security login show` Befehl zeigt die Zugriffs- und Anmeldemethoden von Benutzerkonten und ihre Zugriffskontrollrollen an.

* Wenn Sie HTTPS für sicheren Webzugriff verwenden möchten, muss SSL aktiviert und ein digitales Zertifikat installiert werden.
+
Mit dem `system services web show` Befehl wird die Konfiguration der Web-Protokoll-Engine auf Cluster-Ebene angezeigt.



.Über diese Aufgabe
Der `spi` Webdienst ist standardmäßig aktiviert, und der Dienst kann manuell deaktiviert werden (`vserver services web modify -vserver * -name spi -enabled false`).

Die Rolle "`admin`" wird `spi` standardmäßig Zugriff auf den Webdienst gewährt, und der Zugriff kann manuell deaktiviert werden (`services web access delete -vserver _cluster_name_ -name spi -role admin`).

.Schritte
. Zeigen Sie im Webbrowser `spi` in einem der folgenden Formate auf die Webservice-URL:
+
** `http://_cluster-mgmt-LIF_/spi/`
** `https://_cluster-mgmt-LIF_/spi/`
+
`cluster-mgmt-LIF` Ist die IP-Adresse der Cluster-Management-LIF.



. Wenn Sie vom Browser dazu aufgefordert werden, geben Sie Ihr Benutzerkonto und Ihr Passwort ein.
+
Nachdem Ihr Konto authentifiziert wurde, zeigt der Browser Links zu den `/mroot/etc/log/` `/mroot/etc/crash/` `/mroot/etc/mib/` Verzeichnissen , und der einzelnen Knoten im Cluster an.


