---
permalink: system-admin/access-cluster-telnet-task.html 
sidebar: sidebar 
keywords: access, cluster, telnet, administrative, tasks, disable, default 
summary: Sie können Telnet-Anfragen an den Cluster senden, um administrative Aufgaben auszuführen. Telnet ist standardmäßig deaktiviert. 
---
= Zugriff auf einen ONTAP Cluster mit Telnet-Anfragen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Telnet-Anfragen an den Cluster senden, um administrative Aufgaben auszuführen. Telnet ist standardmäßig deaktiviert.

Telnet und RSH sind keine sicheren Protokolle, die Verwendung von SSH für den Zugriff auf den Cluster wird empfohlen. SSH bietet eine sichere Remote-Shell und eine interaktive Netzwerksitzung. Weitere Informationen finden sich unter link:./access-cluster-ssh-task.html["Zugriff auf den Cluster über SSH"].

.Bevor Sie beginnen
Folgende Bedingungen müssen erfüllt sein, bevor Sie mit Telnet auf den Cluster zugreifen können:

* Sie benötigen ein lokales Cluster-Benutzerkonto, das für die Verwendung von Telnet als Zugriffsmethode konfiguriert ist.
+
Der  `-application`Parameter der  `security login`Befehle gibt das Zugriffsverfahren für ein Benutzerkonto an. Weitere Informationen zu  `security login` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+login["ONTAP-Befehlsreferenz"^].



.Über diese Aufgabe
* ONTAP unterstützt maximal 50 gleichzeitige Telnet-Sitzungen pro Knoten.
+
Befindet sich die Cluster-Management-LIF auf dem Node, teilt sie sich dieses Limit mit der Node-Management-LIF.

+
Wenn die Anzahl der eingehenden Verbindungen 10 pro Sekunde übersteigt, wird der Service für 60 Sekunden vorübergehend deaktiviert.

* Wenn von einem Windows-Host aus auf die ONTAP-CLI zugegriffen werden soll, kann ein Drittanbieter-Tool wie PuTTY verwendet werden.
* Für RSH Befehle sind erweiterte Berechtigungen erforderlich.


[role="tabbed-block"]
====
.ONTAP 9.10.1 oder höher
--
.Schritte
. Bestätigen Sie, dass das Telnet Sicherheitsprotokoll aktiviert ist:
+
`security protocol show`

+
.. Wenn das Telnet-Sicherheitsprotokoll aktiviert ist, erfolgt der nächste Schritt.
.. Falls das Telnet-Sicherheitsprotokoll nicht aktiviert ist, kann es mit dem folgenden Befehl aktiviert werden:
+
`security protocol modify -application telnet -enabled true`



+
Weitere Informationen zu  `security protocol show` und  `security protocol modify` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+protocol["ONTAP-Befehlsreferenz"^].

. Bestätigen Sie, dass der  `management-telnet-server` Dienst auf den Management-LIFs vorhanden ist:
+
`network interface show -services management-telnet-server`

+
Weitere Informationen zu  `network interface show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["ONTAP-Befehlsreferenz"^].

+
.. Falls der  `management-telnet-server` Dienst existiert, wird mit dem nächsten Schritt fortgefahren.
.. Falls der  `management-telnet-server` Dienst nicht existiert, kann der folgende Befehl zum Hinzufügen verwendet werden:
+
`network interface service-policy add-service -vserver cluster1 -policy default-management -service management-telnet-server`

+
Weitere Informationen zu  `network interface service-policy add-service` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-service-policy-add-service.html["ONTAP-Befehlsreferenz"^].





--
.ONTAP 9.9 oder früher
--
.Bevor Sie beginnen
Folgende Bedingungen müssen erfüllt sein, bevor Sie mit Telnet auf den Cluster zugreifen können:

* Telnet muss bereits in der Management-Firewall-Richtlinie aktiviert sein, die von den Cluster- oder Knotenmanagement-LIFs verwendet wird, damit Telnet-Anfragen die Firewall passieren können.
+
Telnet ist standardmäßig deaktiviert. Der  `system services firewall policy show` Befehl mit dem  `-service telnet` Parameter zeigt an, ob Telnet in einer Firewall-Richtlinie aktiviert ist. Weitere Informationen zu  `system services firewall policy` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+services+firewall+policy["ONTAP-Befehlsreferenz"^].

* Wenn Sie IPv6-Verbindungen verwenden, muss IPv6 auf dem Cluster bereits konfiguriert und aktiviert sein, und die Firewall-Richtlinien müssen bereits mit IPv6-Adressen konfiguriert sein.
+
Der  `network options ipv6 show`Befehl zeigt an, ob IPv6 aktiviert ist. Weitere Informationen zu  `network options ipv6 show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/network-options-ipv6-show.html["ONTAP-Befehlsreferenz"^]. Der  `system services firewall policy show`Befehl zeigt Firewall-Richtlinien an.



.Schritte
. Auf einem Administrationsrechner ist folgender Befehl einzugeben:
+
`telnet hostname_or_IP`

+
`hostname_or_IP` ist der Hostname oder die IP-Adresse des Cluster-Management-LIF oder eines Node-Management-LIF. Die Verwendung des Cluster-Management-LIF wird empfohlen. Es kann eine IPv4- oder IPv6-Adresse verwendet werden.



--
====
.Beispiel einer Telnet-Anfrage
Das folgende Beispiel zeigt, wie der Benutzer mit dem Namen „joe“, der mit Telnet-Zugriff eingerichtet wurde, eine Telnet-Anfrage stellen kann, um auf einen Cluster zuzugreifen, dessen Cluster-Management-LIF 10.72.137.28 ist:

[listing]
----

admin_host$ telnet 10.72.137.28

Data ONTAP
login: joe
Password:

cluster1::>

----