---
permalink: system-admin/access-man-pages-concept.html 
sidebar: sidebar 
keywords: method, access, ontap, man, pages, command, line 
summary: 'ONTAP Handbuch (man) Seiten erläutern die Verwendung von ONTAP Befehlen. Sie sind über die Befehlszeile und auf der NetApp Support Site verfügbar.' 
---
= Methoden für den Zugriff auf ONTAP man-Pages
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Seiten im ONTAP Handbuch (man) erläutern die Verwendung von ONTAP CLI Befehlen. Diese Seiten sind in der Befehlszeile verfügbar und werden auch in Release-specific _command references_ veröffentlicht.

Verwenden Sie in der ONTAP-Befehlszeile den `man _command_name_` Befehl zum Anzeigen der manuellen Seite des angegebenen Befehls. Wenn Sie keinen Befehlsnamen angeben, wird der manuelle Seitenindex angezeigt. Sie können das verwenden `man man` Befehl zum Anzeigen von Informationen über das `man` Befehl selbst. Sie können eine man-Page verlassen, indem Sie eingeben `*q*`.

Siehe xref:../concepts/manual-pages.html[Befehlsreferenz für Ihre Version von ONTAP 9] Um mehr über die in Ihrer Version verfügbaren ONTAP-Befehle für Administratoren und Fortgeschrittene zu erfahren.
