---
permalink: system-admin/accounts-access-sp-concept.html 
sidebar: sidebar 
keywords: account, access, sp, cluster, user, cli, node 
summary: Wenn Sie versuchen, auf den SP zuzugreifen, werden Sie nach Berechtigungen gefragt. Cluster-Benutzerkonten, die mit der Applikation des Service-Prozessors erstellt wurden, haben Zugriff auf die SP-CLI auf jedem Node des Clusters. SP-Benutzerkonten werden über ONTAP verwaltet und per Passwort authentifiziert. Ab ONTAP 9.9 müssen SP-Benutzerkonten die Administratorrolle aufweisen. 
---
= Konten, die auf den SP zugreifen können
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie versuchen, auf den SP zuzugreifen, werden Sie nach Berechtigungen gefragt. Cluster-Benutzerkonten, die mit dem `service-processor` Applikationstyp erstellt werden, haben Zugriff auf die SP-CLI auf einem beliebigen Node des Clusters. SP-Benutzerkonten werden über ONTAP verwaltet und per Passwort authentifiziert. Ab ONTAP 9.9.1 müssen SP-Benutzerkonten die `admin` Rolle besitzen.

Benutzerkonten für den Zugriff auf den SP werden über ONTAP statt über die SP-CLI verwaltet. Ein Cluster-Benutzerkonto kann auf die SP zugreifen, wenn es mit dem `-application` Parameter des `security login create` Befehls set to `service-processor` und dem `-authmethod` Parameter set to erstellt wird `password`. Der SP unterstützt nur die Passwort-Authentifizierung.

Sie müssen den `-role` Parameter angeben, wenn Sie ein SP-Benutzerkonto erstellen.

* In Versionen von ONTAP 9.9.1 und neueren Versionen müssen Sie `admin` für den `-role` Parameter angeben, und alle Änderungen an einem Konto erfordern die `admin` Rolle. Andere Rollen sind aus Sicherheitsgründen nicht mehr zulässig.
+
** Wenn Sie ein Upgrade auf ONTAP 9.9.1 oder höhere Versionen durchführen, finden Sie unter link:../upgrade/sp-user-accounts-change-concept.html["Ändern von Benutzerkonten, die auf den Service Processor zugreifen können"].
** Wenn Sie auf ONTAP 9 8 oder frühere Versionen zurückkehren, siehe link:../revert/verify-sp-user-accounts-task.html["Überprüfen Sie, ob Benutzerkonten, die auf den Service Processor zugreifen können"].


* In ONTAP 9 8 und früheren Versionen kann jede Rolle auf das SP zugreifen, `admin` wird aber empfohlen.


Standardmäßig enthält das Cluster-Benutzerkonto mit dem Namen „`admin`“ den `service-processor` Anwendungstyp und hat Zugriff auf die SP.

ONTAP verhindert, dass Sie Benutzerkonten mit Namen erstellen, die für das System reserviert sind (z. B. „`root`“ und „`naroot`“). Sie können keinen systemreservierten Namen für den Zugriff auf das Cluster oder den SP verwenden.

Sie können mit dem `-application service-processor` Parameter des `security login show` Befehls aktuelle SP-Benutzerkonten anzeigen.
