---
permalink: system-admin/administrative-privilege-levels-concept.html 
sidebar: sidebar 
keywords: administrative, privilege, levels, parameters, commands, admin, advanced, diagnostic 
summary: 'ONTAP-Befehle und -Parameter werden auf drei Berechtigungsebenen definiert: Admin, Advanced und Diagnostic. Die Berechtigungsebenen zeigen die bei der Ausführung der Aufgaben erforderlichen Skill-Level an.' 
---
= Verwendung von administrativen Berechtigungsebenen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP-Befehle und -Parameter werden auf drei Berechtigungsebenen definiert: _Admin_, _Advanced_ und _diagnostic_. Die Berechtigungsebenen zeigen die bei der Ausführung der Aufgaben erforderlichen Skill-Level an.

* * Admin*
+
Die meisten Befehle und Parameter sind auf dieser Ebene verfügbar. Sie werden für allgemeine oder Routineaufgaben verwendet.

* * Fortgeschrittene *
+
Befehle und Parameter auf dieser Ebene werden nur selten verwendet, erfordern erweitertes Wissen und können bei Verwendung unangemessen zu Problemen führen.

+
Sie verwenden erweiterte Befehle oder Parameter nur mit Ratschlag von Support-Mitarbeitern.

* *Diagnose*
+
Diagnosebefehle und Parameter unterbrechen potenziell den Betrieb. Sie werden nur vom Support-Personal eingesetzt, um Probleme zu diagnostizieren und zu beheben.


