---
permalink: system-admin/autosupport-severity-types-concept.html 
sidebar: sidebar 
keywords: autosupport, severity, types, message 
summary: AutoSupport-Nachrichten haben Schweregradtypen, die dabei helfen, den Zweck jeder Nachricht zu verstehen, zum Beispiel um sofort auf ein Notfallproblem aufmerksam zu machen oder lediglich Informationen bereitzustellen. 
---
= Informationen zu den ONTAP AutoSupport Schweregraden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport-Meldungen haben Schweregradtypen, die dabei helfen, den Zweck jeder Meldung zu verstehen, zum Beispiel um sofort auf ein Notfallproblem aufmerksam zu machen oder lediglich Informationen bereitzustellen.

Nachrichten haben einen der folgenden Schweregrade:

* *Achtung*: Warnmeldungen weisen darauf hin, dass ein Ereignis der nächsthöheren Stufe eintreten könnte, wenn keine Maßnahmen ergriffen werden.
+
Innerhalb von 24 Stunden ist eine Maßnahme gegen Warnmeldungen erforderlich.

* *Notfall*: Notfallmeldungen werden angezeigt, wenn eine Störung aufgetreten ist.
+
Sie müssen unverzüglich auf Notfallmeldungen reagieren.

* *Fehler*: Fehlerbedingungen geben an, was passieren könnte, wenn sie ignoriert werden.
* *Hinweis*: Normaler, aber bedeutsamer Zustand.
* *Info*: Diese Informationsmeldung enthält Details zum Problem, die ignoriert werden können.
* *Debug*: Meldungen auf Debug-Ebene enthalten Anweisungen, die auszuführen sind.


Wenn Ihre interne Supportorganisation AutoSupport-Nachrichten per E-Mail empfängt, erscheint der Schweregrad in der Betreffzeile der E-Mail-Nachricht.
