---
permalink: system-admin/cluster-management-server-concept.html 
sidebar: sidebar 
keywords: cluster, management, server, adminsvm, svm, single, entity 
summary: 'Der Cluster-Managementserver, auch als „adminSVM“ bezeichnet, ist eine spezialisierte Implementierung von Storage Virtual Machines (SVM), durch die das Cluster als eine Einheit, die sich einfach managen lässt. Der Cluster-Management-Server dient nicht nur als grundlegende administrative Domäne, sondern ist auch Eigentümer von Ressourcen, die nicht logisch zu einer Daten-SVM gehören.' 
---
= Was ist der Cluster-Management-Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Cluster-Management-Server, auch als __admin__SVM bezeichnet, ist eine spezialisierte Implementierung der Storage Virtual Machine (SVM), die den Cluster als eine einzelne, einfach zu verwaltende Einheit darstellt. Der Cluster-Management-Server dient nicht nur als grundlegende administrative Domäne, sondern ist auch Eigentümer von Ressourcen, die nicht logisch zu einer Daten-SVM gehören.

Der Cluster-Verwaltungsserver ist immer im Cluster verfügbar. Sie können über die Konsole oder Cluster-Management-LIF auf den Cluster-Managementserver zugreifen.

Bei Ausfall des Home-Netzwerk-Ports erfolgt automatisch ein Failover der Cluster-Management-LIF auf einen anderen Node im Cluster. Abhängig von den Konnektivitätsoptionen des verwendeten Managementprotokolls kann das Failover möglicherweise nicht bemerkt werden. Wenn Sie ein verbindungsloses Protokoll (z. B. SNMP) verwenden oder eine begrenzte Verbindung (z. B. HTTP) haben, werden Sie wahrscheinlich nicht bemerken, dass das Failover stattfindet. Wenn Sie jedoch eine langfristige Verbindung (z. B. SSH) verwenden, müssen Sie nach dem Failover eine Verbindung zum Cluster-Managementserver herstellen.

Wenn Sie ein Cluster erstellen, werden alle Merkmale der Cluster-Management-LIF konfiguriert, einschließlich seiner IP-Adresse, Netmask, des Gateway und des Ports.

Im Gegensatz zu einer Daten-SVM oder Node-SVM verfügt ein Cluster-Managementserver über keine Root-Volumes oder Host-Benutzer-Volumes (obwohl er System-Volumes hosten kann). Darüber hinaus kann ein Cluster-Management-Server nur LIFs des Cluster-Managementtyps nutzen.

Wenn Sie den `vserver show` Befehl ausführen, wird der Cluster-Management-Server in der Ausgabeliste des Befehls angezeigt.
