---
permalink: system-admin/commands-manage-feature-licenses-reference.html 
sidebar: sidebar 
keywords: command, manage, license, cli, command, cluster, system, feature, usage, usage 
summary: Sie können die Lizenzbefehle für das ONTAP-CLI-System verwenden, um Funktionslizenzen für das Cluster zu verwalten. Sie verwenden die Befehle zur Nutzung der Systemfunktionen, um die Nutzung der Funktionen zu überwachen. 
---
= Befehle zum Verwalten von Lizenzen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die ONTAP CLI verwenden `system license` Befehle zum Verwalten von Funktionslizenzen für den Cluster. Sie verwenden das `system feature-usage` Befehle für das Überwachen der Funktionsnutzung.

In der folgenden Tabelle sind einige der allgemeinen CLI-Befehle zum Verwalten von Lizenzen sowie Links zu den Command-man-Pages aufgeführt, um weitere Informationen zu erhalten.

[cols="2,4"]
|===
| Ihr Ziel ist | Befehl 


 a| 
Alle Pakete anzeigen, die Lizenzen und ihren aktuellen Lizenzstatus benötigen, einschließlich:

* Der Paketname
* Die lizenzierte Methode
* Das Ablaufdatum, falls zutreffend

 a| 
link:https://docs.netapp.com/us-en/ontap-cli-9141/system-license-show-status.html["Systemlizenz zeigt-Status"]



 a| 
Abgelaufene oder nicht verwendete Lizenzen anzeigen oder entfernen
 a| 
link:https://docs.netapp.com/us-en/ontap-cli-9141/system-license-clean-up.html["Bereinigung der Systemlizenz"]



 a| 
Zusammenfassung der Funktionsnutzung im Cluster pro Node anzeigen
 a| 
https://docs.netapp.com/us-en/ontap-cli-9141/system-feature-usage-show-summary.html["Übersicht über die Nutzung von Systemfunktionen"]



 a| 
Anzeige des Funktionsnutzungsstatus im Cluster auf Node- und Wochenbasis
 a| 
https://docs.netapp.com/us-en/ontap-cli-9141/system-feature-usage-show-history.html["System-Feature-Usage-Verlauf"]



 a| 
Zeigen Sie den Status des Lizenzrisikos für jedes Lizenzpaket an
 a| 
https://docs.netapp.com/us-en/ontap-cli-9141/system-license-entitlement-risk-show.html["Anzeige der Systemlizenz für das Berechtigungsrisiko"]

|===
.Verwandte Informationen
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9-Befehle"^]

https://kb.netapp.com/onprem/ontap/os/ONTAP_9.10.1_and_later_licensing_overview["Knowledge Base-Artikel: ONTAP 9.10.1 und höher Lizenzübersicht"^]

https://docs.netapp.com/us-en/ontap/system-admin/install-license-task.html["Verwenden Sie System Manager, um eine NetApp Lizenzdatei zu installieren"^]
