---
permalink: system-admin/commands-manage-mount-points-nodes-reference.html 
sidebar: sidebar 
keywords: command, manage, mount, point, nodes, spi, web, service, root, volume, root 
summary: Der spi-Webdienst erstellt automatisch einen Bereitstellungspunkt von einem Knoten zum Root-Volume eines anderen Knotens auf eine Anforderung, auf die Protokolldateien oder Kerndateien des Knotens zuzugreifen. Obwohl Sie Mount-Punkte nicht manuell verwalten müssen, können Sie dies mit den System-Node-Root-Mount-Befehlen tun. 
---
= Befehle zum Verwalten von Mount-Punkten auf den Nodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `spi` Webservice erstellt bei Anforderung einen Mount-Punkt automatisch von einem Node zum Root-Volume eines anderen Nodes, um auf die Log-Dateien oder Kerndateien des Node zuzugreifen. Obwohl Sie Mount-Punkte nicht manuell verwalten müssen, können Sie dies mit dem tun `system node root-mount` Befehle.

|===
| Ihr Ziel ist | Befehl 


 a| 
Erstellen Sie manuell einen Mount-Punkt von einem Node zum Root-Volume eines anderen Nodes
 a| 
`system node root-mount create` Nur ein einzelner Mount-Punkt kann von einem Node zum anderen vorhanden sein.



 a| 
Zeigen Sie vorhandene Mount-Punkte auf den Nodes im Cluster an, einschließlich der Zeit, die ein Mount-Punkt erstellt wurde, und des aktuellen Status
 a| 
`system node root-mount show`



 a| 
Löschen Sie einen Bereitstellungspunkt von einem Node zum Root-Volume eines anderen Node, und erzwingen Sie die Verbindungen zum Mount-Punkt zum Schließen
 a| 
`system node root-mount delete`

|===
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9-Befehle"^]
