---
permalink: system-admin/commands-manage-timeout-period-reference.html 
sidebar: sidebar 
keywords: system, timeout, command, manage, automatic, timeout, period, cli 
summary: Mit den Befehlen für das System-Timeout verwalten Sie die automatische Zeitüberschreitung von CLI-Sitzungen. 
---
= Befehle zum Verwalten der automatischen Zeitüberschreitung von CLI-Sitzungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Wert für das Zeitlimit gibt an, wie lange eine CLI-Sitzung inaktiv bleibt, bevor sie automatisch beendet wird. Der Wert für die CLI-Zeitüberschreitung ist das gesamte Cluster. Das bedeutet, dass jeder Node in einem Cluster denselben CLI-Zeitüberschreitungswert verwendet.

Standardmäßig beträgt die automatische Zeitüberschreitung von CLI-Sitzungen 30 Minuten.

Sie verwenden das `system timeout` Befehle zum Verwalten der automatischen Zeitüberschreitung von CLI-Sitzungen.

|===
| Ihr Ziel ist | Befehl 


 a| 
Zeigt den automatischen Zeitüberschreitungszeitraum für CLI-Sessions an
 a| 
`system timeout show`



 a| 
Ändern Sie den automatischen Zeitüberschreitungszeitraum für CLI-Sitzungen
 a| 
`system timeout modify`

|===
.Verwandte Informationen
http://["ONTAP 9-Befehle"^]
