---
permalink: system-admin/commands-manage-feature-licenses-reference.html 
sidebar: sidebar 
keywords: command, manage, license, command, cluster, system, feature, usage, usage 
summary: Sie verwenden die Systemlizenzbefehle, um Funktionslizenzen für den Cluster zu verwalten. Sie verwenden die Befehle zur Nutzung der Systemfunktionen, um die Nutzung der Funktionen zu überwachen. 
---
= Befehle zum Verwalten von Lizenzen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie verwenden das `system license` Befehle zum Verwalten von Funktionslizenzen für den Cluster. Sie verwenden das `system feature-usage` Befehle für das Überwachen der Funktionsnutzung.

|===
| Ihr Ziel ist | Befehl 


 a| 
Fügen Sie eine oder mehrere Lizenzen hinzu
 a| 
`system license add`



 a| 
Informationen über installierte Lizenzen anzeigen, z. B.:

* Name und Beschreibung des Lizenzpakets
* Lizenztyp (`site`, `license`, Oder `demo`)
* Ablaufdatum, falls zutreffend
* Den Cluster oder Nodes, für die ein Paket lizenziert ist
* Gibt an, ob die Lizenz vor Data ONTAP 8.2 installiert wurde (`legacy`)
* Kunden-ID

 a| 
`system license show`

[NOTE]
====
Einige Informationen werden nur angezeigt, wenn Sie das verwenden `–instance` Parameter.

====


 a| 
Alle Pakete anzeigen, die Lizenzen und ihren aktuellen Lizenzstatus benötigen, einschließlich:

* Der Paketname
* Die lizenzierte Methode
* Das Ablaufdatum, falls zutreffend

 a| 
`system license status show`



 a| 
Löschen Sie die Lizenz eines Pakets aus dem Cluster oder einem Node, dessen Seriennummer Sie angeben
 a| 
`system license delete`



 a| 
Abgelaufene oder nicht verwendete Lizenzen anzeigen oder entfernen
 a| 
`system license clean-up`



 a| 
Zusammenfassung der Funktionsnutzung im Cluster pro Node anzeigen
 a| 
`system feature-usage show-summary`



 a| 
Anzeige des Funktionsnutzungsstatus im Cluster auf Node- und Wochenbasis
 a| 
`system feature-usage show-history`



 a| 
Zeigen Sie den Status des Lizenzrisikos für jedes Lizenzpaket an
 a| 
`system license entitlement-risk show`

[NOTE]
====
Einige Informationen werden nur angezeigt, wenn Sie das verwenden `-detail` Und `-instance` Parameter.

====
|===
.Verwandte Informationen
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9-Befehle"^]
