---
permalink: system-admin/commands-manage-system-time-reference.html 
sidebar: sidebar 
keywords: command, manage, cluster, time, ntp, server, date, ntp, time, manually 
summary: Sie verwenden die Cluster-Befehle für den Zeitdienst-ntp-Server zum Verwalten der NTP-Server für das Cluster. Sie verwenden die Cluster-Befehle, um die Cluster-Zeit manuell zu verwalten. 
---
= Befehle zum Verwalten der Cluster-Zeit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie verwenden das `cluster time-service ntp server` Befehle zum Verwalten der NTP-Server für das Cluster. Sie verwenden das `cluster date` Befehle zum manuellen Verwalten der Cluster-Zeit.

Ab ONTAP 9.5 können Sie Ihren NTP-Server mit symmetrischer Authentifizierung konfigurieren.

Mit den folgenden Befehlen können Sie die NTP-Server für das Cluster verwalten:

|===
| Ihr Ziel ist | Befehl 


 a| 
Verbinden Sie das Cluster ohne symmetrische Authentifizierung mit einem externen NTP-Server
 a| 
`cluster time-service ntp server create -server server_name`



 a| 
Verbinden Sie den Cluster mit einem externen NTP-Server mit symmetrischer AuthentifizierungVerfügbar in ONTAP 9.5 oder höher
 a| 
`cluster time-service ntp server create -server server_ip_address -key-id key_id`

[NOTE]
====
Der `key_id` Beziehen Sie sich auf einen vorhandenen gemeinsamen Schlüssel, der mit '`Cluster Time-Service ntp key' konfiguriert ist.

====


 a| 
Symmetrische Authentifizierung für einen vorhandenen NTP-Server aktivieren ein vorhandener NTP-Server kann angepasst werden, um die Authentifizierung durch Hinzufügen der erforderlichen Schlüssel-ID zu ermöglichen

Verfügbar in ONTAP 9.5 oder höher
 a| 
`cluster time-service ntp server modify -server server_name -key-id key_id`



 a| 
Deaktivieren Sie die symmetrische Authentifizierung
 a| 
`cluster time-service ntp server modify -server server_name -authentication disabled`



 a| 
Konfigurieren Sie einen freigegebenen NTP-Schlüssel
 a| 
`cluster time-service ntp key create -id shared_key_id -type shared_key_type -value shared_key_value`

[NOTE]
====
Freigegebene Schlüssel werden durch eine ID bezeichnet. Die ID, der Typ und der Wert müssen auf dem Node und dem NTP-Server identisch sein

====


 a| 
Zeigt Informationen zu den NTP-Servern an, die mit dem Cluster verbunden sind
 a| 
`cluster time-service ntp server show`



 a| 
Ändern Sie die Konfiguration eines externen NTP-Servers, der mit dem Cluster verbunden ist
 a| 
`cluster time-service ntp server modify`



 a| 
Distanzieren Sie einen NTP-Server vom Cluster
 a| 
`cluster time-service ntp server delete`



 a| 
Setzen Sie die Konfiguration zurück, indem Sie alle externen NTP-Server-Verknüpfungen mit dem Cluster löschen
 a| 
`cluster time-service ntp server reset`

[NOTE]
====
Dieser Befehl erfordert die erweiterte Berechtigungsebene.

====
|===
Mit den folgenden Befehlen können Sie die Cluster-Zeit manuell verwalten:

|===
| Ihr Ziel ist | Befehl 


 a| 
Zeitzone, Datum und Uhrzeit einstellen oder ändern
 a| 
`cluster date modify`



 a| 
Zeigt die Zeitzone, das Datum und die Zeiteinstellungen für das Cluster an
 a| 
`cluster date show`

|===
.Verwandte Informationen
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9-Befehle"^]
