---
permalink: system-admin/commands-manage-core-dumps-reference.html 
sidebar: sidebar 
keywords: command, manage, core, dump, coredump, config, files, node, application, report 
summary: Sie verwenden die System-Node coredump-Konfigurationsbefehle zum Verwalten der Konfiguration von Core Dumps, der Systemknoten coredump-Befehle zum Verwalten der Core Dump-Dateien und der Befehle zum Verwalten von Kernberichten von Applikationen im Systemknoten. 
---
= Befehle zum Verwalten von Core Dumps
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie verwenden das `system node coredump config` Befehle zum Verwalten der Konfiguration von Core Dumps, die `system node coredump` Befehle zum Verwalten der Core Dump-Dateien und des `system node coredump reports` Befehle zum Managen von Kernberichten für Anwendungen.

|===
| Ihr Ziel ist | Befehl 


 a| 
Konfigurieren von Core Dumps
 a| 
`system node coredump config modify`



 a| 
Zeigt die Konfigurationseinstellungen für Core Dumps an
 a| 
`system node coredump config show`



 a| 
Zeigt grundlegende Informationen zu Core Dumps an
 a| 
`system node coredump show`



 a| 
Lösen Sie manuell einen Core Dump aus, wenn Sie einen Node neu booten
 a| 
`system node reboot` Mit beiden `-dump` Und `-skip-lif-migration` Parameter



 a| 
Lösen Sie beim Herunterfahren eines Node manuell einen Core Dump aus
 a| 
`system node halt` Mit beiden `-dump` Und `-skip-lif-migration` Parameter



 a| 
Speichern eines angegebenen Core Dump
 a| 
`system node coredump save`



 a| 
Speichern Sie alle nicht gespeicherten Core Dumps auf einem angegebenen Node
 a| 
`system node coredump save-all`



 a| 
Generieren und senden Sie eine AutoSupport-Nachricht mithilfe einer Core Dump-Datei, die Sie angeben
 a| 
`system node autosupport invoke-core-upload`

[NOTE]
====
Der `-uri` Der optionale Parameter gibt ein alternatives Ziel für die AutoSupport Meldung an.

====


 a| 
Zeigt Statusinformationen zu Core Dumps an
 a| 
`system node coredump status`



 a| 
Löschen eines angegebenen Core Dump
 a| 
`system node coredump delete`



 a| 
Löschen Sie alle nicht gespeicherten Core Dumps oder alle gespeicherten Core-Dateien auf einem Node
 a| 
`system node coredump delete-all`



 a| 
Zeigt die Berichte zum Anwendungs-Core-Dump an
 a| 
`system node coredump reports show`



 a| 
Löschen eines Core Dump-Berichts der Anwendung
 a| 
`system node coredump reports delete`

|===
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9-Befehle"^]
