---
permalink: system-admin/commands-manage-job-schedules-reference.html 
sidebar: sidebar 
keywords: command, manage, job, schedule, volume, snapshot, copy, cron, interval 
summary: 'Viele Aufgaben, wie z. B. Volume Snapshot Kopien, können für die Ausführung auf bestimmten Zeitplänen konfiguriert werden. Zeitpläne, die zu bestimmten Zeiten ausgeführt werden, werden als Cron-Zeitpläne bezeichnet (ähnlich wie UNIX Cron-Zeitpläne). Zeitpläne, die in Intervallen ausgeführt werden, werden als Intervallzeitpläne bezeichnet. Sie verwenden die Job-Schedule-Befehle zum Verwalten von Job-Zeitplänen.' 
---
= Befehle zum Verwalten von Job-Zeitplänen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Viele Aufgaben – beispielsweise Volume Snapshot Kopien – können für die Ausführung auf bestimmten Zeitplänen konfiguriert werden.Zeitpläne, die zu bestimmten Zeiten ausgeführt werden, werden als _cron_ Zeitpläne bezeichnet (ähnlich wie bei UNIX `cron` Zeitpläne). Zeitpläne, die in Intervallen ausgeführt werden, werden als „_interval_“-Zeitpläne bezeichnet. Sie verwenden das `job schedule` Befehle zum Verwalten von Job-Zeitplänen.

Job-Zeitpläne passen nicht auf manuelle Änderungen am Cluster-Datum und -Uhrzeit an. Diese Jobs werden planmäßig ausgeführt, basierend auf der aktuellen Cluster-Zeit, zu der der Job erstellt wurde oder zum Zeitpunkt der letzten Ausführung des Jobs. Wenn Sie daher das Cluster-Datum oder die -Zeit manuell ändern, sollten Sie das verwenden `job show` Und `job history show` Befehle zur Überprüfung, ob alle geplanten Jobs entsprechend Ihren Anforderungen in eine Warteschlange verschoben und abgeschlossen werden.

Wenn das Cluster Teil einer MetroCluster-Konfiguration ist, müssen die Job-Zeitpläne auf beiden Clustern identisch sein. Wenn Sie einen Job-Zeitplan erstellen, ändern oder löschen, müssen Sie diesen Vorgang auf dem Remote-Cluster ausführen.

|===
| Ihr Ziel ist | Befehl 


 a| 
Informationen zu allen Zeitplänen anzeigen
 a| 
`job schedule show`



 a| 
Zeigt die Liste der Jobs nach Zeitplan an
 a| 
`job schedule show-jobs`



 a| 
Informationen zu cron-Zeitplänen anzeigen
 a| 
`job schedule cron show`



 a| 
Zeigt Informationen zu Intervallzeitplänen an
 a| 
`job schedule interval show`



 a| 
Erstellen Sie einen Cron-Zeitplan^1^
 a| 
`job schedule cron create`



 a| 
Erstellen eines Intervallplans
 a| 
`job schedule interval create`

Sie müssen mindestens einen der folgenden Parameter angeben: `-days`, `-hours`, `-minutes`, Oder `-seconds`.



 a| 
Ändern Sie einen Cron-Zeitplan
 a| 
`job schedule cron modify`



 a| 
Ändern eines Intervallplans
 a| 
`job schedule interval modify`



 a| 
Löschen Sie einen Zeitplan
 a| 
`job schedule delete`



 a| 
Löschen Sie einen Cron-Zeitplan
 a| 
`job schedule cron delete`



 a| 
Einen Intervallzeitplan löschen
 a| 
`job schedule interval delete`

|===
^1^beginnt mit ONTAP 9.10.1, wenn Sie einen Job-Zeitplan mithilfe des erstellen `job schedule cron create` Sie können den Vserver für Ihren Job-Zeitplan angeben.

.Verwandte Informationen
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9-Befehle"^]
