---
permalink: system-admin/commands-manage-config-backup-files-reference.html 
sidebar: sidebar 
keywords: command, manage, configuration, backup, file 
summary: Mit den Systemkonfigurationssicherungsbefehlen werden die Sicherungsdateien der Cluster- und Knotenkonfiguration verwaltet. 
---
= ONTAP Befehle zur Verwaltung von Sicherungsdateien für die Knotenkonfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie verwenden die  `system configuration backup` Befehle, um Sicherungsdateien für die Cluster- und Knotenkonfiguration zu verwalten.

Diese Befehle sind auf der Zugangsstufe „Erweitert“ verfügbar.

|===
| Wenn Sie möchten... | Verwenden Sie diesen Befehl... 


 a| 
Eine neue Sicherungsdatei für die Knoten- oder Clusterkonfiguration erstellen
 a| 
`system configuration backup create`



 a| 
Kopieren einer Konfigurationssicherungsdatei von einem Knoten auf einen anderen Knoten im Cluster
 a| 
`system configuration backup copy`



 a| 
Eine Konfigurationssicherungsdatei von einem Knoten im Cluster auf eine Remote-URL (FTP, HTTP, HTTPS oder FTPS) hochladen
 a| 
`system configuration backup upload`

Wenn Sie HTTPS in der Remote-URL verwenden, kann die  `-validate-certification` Option zum Aktivieren oder Deaktivieren der digitalen Zertifikatsvalidierung verwendet werden. Die Zertifikatsvalidierung ist standardmäßig deaktiviert.

[NOTE]
====
Der Webserver, auf den Sie die Konfigurationssicherungsdatei hochladen, muss PUT-Operationen für HTTP und POST-Operationen für HTTPS aktiviert haben. Auf manchen Webservern ist möglicherweise ein zusätzliches Modul erforderlich. Weitere Informationen enthält die Dokumentation Ihres Webservers. Die unterstützten URL-Formate variieren je nach ONTAP Version. Weitere Informationen zu Systemkonfigurationsbefehlen finden Sie im  https://docs.netapp.com/us-en/ontap-cli/["ONTAP-Befehlsreferenz"^].

====


 a| 
Eine Konfigurationssicherungsdatei kann von einer Remote-URL auf einen Knoten im Cluster heruntergeladen und, falls angegeben, das digitale Zertifikat validiert werden.
 a| 
`system configuration backup download`

Wenn Sie HTTPS in der Remote-URL verwenden, kann die  `-validate-certification` Option zum Aktivieren oder Deaktivieren der digitalen Zertifikatsvalidierung verwendet werden. Die Zertifikatsvalidierung ist standardmäßig deaktiviert.



 a| 
Eine Konfigurationssicherungsdatei auf einem Knoten im Cluster umbenennen
 a| 
`system configuration backup rename`



 a| 
Sicherungsdateien der Knoten- und Clusterkonfiguration für einen oder mehrere Knoten im Cluster anzeigen
 a| 
`system configuration backup show`



 a| 
Löschen einer Konfigurationssicherungsdatei auf einem Node
 a| 
`system configuration backup delete`

[NOTE]
====
Dieser Befehl löscht die Konfigurationssicherungsdatei nur auf dem angegebenen Knoten. Wenn die Konfigurationssicherungsdatei auch auf anderen Knoten im Cluster vorhanden ist, bleibt sie auf diesen Knoten erhalten.

====
|===
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+configuration+backup["Sicherung der Systemkonfiguration"^]

