---
permalink: system-admin/configure-access-web-services-task.html 
sidebar: sidebar 
keywords: configure, access, web, services, http, https, svm 
summary: 'Durch die Konfiguration des Zugriffs auf Webservices können autorisierte Benutzer HTTP oder HTTPS verwenden, um auf den Service-Inhalt des Clusters oder eine Storage Virtual Machine (SVM) zuzugreifen.' 
---
= Konfigurieren des Zugriffs auf ONTAP Webdienste
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durch die Konfiguration des Zugriffs auf Webservices können autorisierte Benutzer HTTP oder HTTPS verwenden, um auf den Service-Inhalt des Clusters oder eine Storage Virtual Machine (SVM) zuzugreifen.

.Schritte
. Wenn eine Firewall aktiviert ist, stellen Sie sicher, dass in der Firewallrichtlinie für die LIF HTTP- oder HTTPS-Zugriffe eingerichtet sind, die für Web-Services verwendet werden:
+
[NOTE]
====
Mit dem `system services firewall show` Befehl können Sie überprüfen, ob eine Firewall aktiviert ist.

====
+
.. Um zu überprüfen, ob HTTP oder HTTPS in der Firewallrichtlinie eingerichtet `system services firewall policy show` sind, verwenden Sie den Befehl.
+
Sie setzen den `-service` Parameter des `system services firewall policy create` Befehls auf `http` oder `https`, um die Richtlinie für den Webzugriff zu aktivieren.

.. Um zu überprüfen, ob die Firewallrichtlinie, die HTTP oder HTTPS unterstützt, mit der logischen Schnittstelle verknüpft ist, die Webservices bereitstellt, verwenden Sie den `network interface show` Befehl mit dem `-firewall-policy` Parameter.
+
Erfahren Sie mehr über `network interface show` in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["ONTAP-Befehlsreferenz"^].

+
Sie verwenden den `network interface modify` Befehl mit dem `-firewall-policy` Parameter, um die Firewallrichtlinie für eine LIF anzuwenden.

+
Erfahren Sie mehr über `network interface modify` in der link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html["ONTAP-Befehlsreferenz"^].



. Um die Web-Protokoll-Engine auf Cluster-Ebene zu konfigurieren und den Zugriff auf Web-Service-Inhalte `system services web modify` zu ermöglichen, verwenden Sie den Befehl.
. Wenn Sie planen, sichere Webservices (HTTPS) zu verwenden, aktivieren Sie SSL und stellen Sie mit dem `security ssl modify` Befehl digitale Zertifikatinformationen für den Cluster oder die SVM bereit.
+
Erfahren Sie mehr über `security ssl modify` in der link:https://docs.netapp.com/us-en/ontap-cli/security-ssl-modify.html["ONTAP-Befehlsreferenz"^].

. Um einen Web Service für das Cluster oder die SVM zu aktivieren, verwenden Sie den `vserver services web modify` Befehl.
+
Sie müssen diesen Schritt für jeden Service wiederholen, den Sie für das Cluster oder die SVM aktivieren möchten.

. Um eine Rolle für den Zugriff auf Webservices im Cluster oder der SVM `vserver services web access create` zu autorisieren, verwenden Sie den Befehl.
+
Die Rolle, die Sie Zugriff gewähren, muss bereits vorhanden sein. Sie können vorhandene Rollen mit dem `security login role show` Befehl anzeigen oder mit dem `security login role create` Befehl neue Rollen erstellen.

+
Erfahren Sie mehr über `security login role show` und `security login role create` in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+login+role["ONTAP-Befehlsreferenz"^].

. Für eine Rolle, die für den Zugriff auf einen Webdienst autorisiert wurde, stellen Sie sicher `security login show`, dass die Benutzer auch mit der richtigen Zugriffsmethode konfiguriert sind, indem Sie die Ausgabe des Befehls überprüfen.
+
Um auf den Webservice der ONTAP API zuzugreifen `ontapi`, muss ein Benutzer mit der `ontapi` Zugriffsmethode konfiguriert werden. Um auf alle anderen Webservices zugreifen `http` zu können, muss ein Benutzer mit der Zugriffsmethode konfiguriert sein.

+
Erfahren Sie mehr über `security login show` in der link:https://docs.netapp.com/us-en/ontap-cli/security-login-show.html["ONTAP-Befehlsreferenz"^].

+
[NOTE]
====
Sie verwenden den `security login create` Befehl, um eine Zugriffsmethode für einen Benutzer hinzuzufügen. Erfahren Sie mehr über `security login create` in der link:https://docs.netapp.com/us-en/ontap-cli/security-login-create.html["ONTAP-Befehlsreferenz"^].

====

