---
permalink: system-admin/control-system-health-alerts-concept.html 
sidebar: sidebar 
keywords: system, health, alert, customization, monitor, enable, disable 
summary: Sie können steuern, welche Meldungen eine Systemzustandsüberwachung generiert, indem Sie die Systemintegritätsrichtlinien aktivieren und deaktivieren, die definieren, wann Meldungen ausgelöst werden. So können Sie das System zur Statusüberwachung für Ihre spezifische Umgebung anpassen. 
---
= Anpassung der Systemzustandsmeldung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können steuern, welche Meldungen eine Systemzustandsüberwachung generiert, indem Sie die Systemintegritätsrichtlinien aktivieren und deaktivieren, die definieren, wann Meldungen ausgelöst werden. So können Sie das System zur Statusüberwachung für Ihre spezifische Umgebung anpassen.

Sie können den Namen einer Richtlinie erlernen, indem Sie ausführliche Informationen über eine generierte Meldung anzeigen oder Richtliniendefinitionen für eine bestimmte Systemzustandsüberwachung, Node oder Alarm-ID anzeigen.

Das Deaktivieren von Integritätsrichtlinien unterscheidet sich vom Unterdrücken von Meldungen. Wenn Sie eine Meldung unterdrücken, hat dies keine Auswirkung auf den Systemzustand des Subsystems, aber die Meldung kann immer noch auftreten.

Wenn Sie eine Richtlinie deaktivieren, löst die im Richtlinienausdruck definierte Bedingung oder der Status keine Meldung mehr aus.

.Beispiel für eine Meldung, die Sie deaktivieren möchten
Angenommen, eine Meldung tritt auf, die für Sie nicht hilfreich ist. Sie verwenden den `system health alert show –instance` Befehl, um die Richtlinien-ID für die Meldung zu erhalten. Sie verwenden die Richtlinien-ID im `system health policy definition show` Befehl, um Informationen zur Richtlinie anzuzeigen. Nachdem Sie den Regelausdruck und andere Informationen über die Richtlinie geprüft haben, entscheiden Sie, die Richtlinie zu deaktivieren. Sie verwenden den `system health policy definition modify` Befehl, um die Richtlinie zu deaktivieren.
