---
permalink: system-admin/create-banner-task.html 
sidebar: sidebar 
keywords: create, banner, svm, access, cluster, ssh, session 
summary: 'Sie können ein Banner erstellen, um eine Meldung an jemanden anzuzeigen, der versucht, auf das Cluster oder die SVM zuzugreifen. Das Banner wird in einer Konsolensitzung (nur für Cluster-Zugriff) oder in einer SSH-Sitzung (für Cluster- oder SVM-Zugriff) angezeigt, bevor ein Benutzer zur Authentifizierung aufgefordert wird.' 
---
= Erstellen Sie ein Banner
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Banner erstellen, um eine Meldung an jemanden anzuzeigen, der versucht, auf das Cluster oder die SVM zuzugreifen. Das Banner wird in einer Konsolensitzung (nur für Cluster-Zugriff) oder in einer SSH-Sitzung (für Cluster- oder SVM-Zugriff) angezeigt, bevor ein Benutzer zur Authentifizierung aufgefordert wird.

.Schritte
. Verwenden Sie die `security login banner modify` Befehl zum Erstellen eines Banners für das Cluster oder SVM:
+
|===
| Ihr Ziel ist | Dann... 


 a| 
Geben Sie eine Nachricht an, die eine einzelne Zeile ist
 a| 
Verwenden Sie die `-message` „[.code]``text``" Parameter, um den Text anzugeben.



 a| 
Fügen Sie neue Zeilen (auch als Zeilenende bezeichnet) in die Nachricht ein
 a| 
Verwenden Sie den Befehl ohne das `-message` Oder `-uri` Parameter zum Starten des interaktiven Modus zum Bearbeiten des Banners.



 a| 
Laden Sie Inhalte von einem Speicherort hoch, um für das Banner zu verwenden
 a| 
Verwenden Sie die `-uri` Parameter zum Festlegen des FTP- oder HTTP-Speicherorts des Inhalts.

|===
+
Die maximale Größe eines Banners beträgt 2,048 Byte, einschließlich Newlines.

+
Ein Banner, das mit dem erstellt wurde `-uri` Parameter ist statisch. Es wird nicht automatisch aktualisiert, um nachfolgende Änderungen des Quellinhalts wiederzugeben.

+
Das für das Cluster erstellte Banner wird auch für alle SVMs angezeigt, die über kein vorhandenes Banner verfügen. Jedes nachträglich erstellte Banner für eine SVM überschreibt das Banner auf Cluster-Ebene für diese SVM. Angeben des `-message` Parameter mit einem Bindestrich innerhalb doppelter Anführungszeichen (`"-"`) Bei der SVM wird die SVM zurückgesetzt, um den Banner auf Cluster-Ebene zu verwenden.

. Überprüfen Sie, ob das Banner erstellt wurde, indem Sie es mit dem anzeigen `security login banner show` Befehl.
+
Angeben des `-message` Parameter mit leerem String (`""`) Zeigt Banner an, die keinen Inhalt haben.

+
Angeben des `-message` Parameter mit `"-"` Zeigt alle (Admin oder Daten) SVMs an, die nicht über ein Banner konfiguriert sind.



Im folgenden Beispiel wird der nicht interaktive Modus verwendet, um ein Banner für den Cluster „`cluster1`“ zu erstellen:

[listing]
----
cluster1::> security login banner modify -message "Authorized users only!"

cluster1::>
----
Im folgenden Beispiel wird mithilfe des interaktiven Modus ein Banner für die SVM „`svm1`“ erstellt:

[listing]
----
cluster1::> security login banner modify -vserver svm1

Enter the message of the day for Vserver "svm1".
Max size: 2048. Enter a blank line to terminate input. Press Ctrl-C to abort.
0        1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
The svm1 SVM is reserved for authorized users only!


cluster1::>
----
Im folgenden Beispiel werden die Banner angezeigt, die erstellt wurden:

[listing]
----
cluster1::> security login banner show
Vserver: cluster1
Message
-----------------------------------------------------------------------------
Authorized users only!

Vserver: svm1
Message
-----------------------------------------------------------------------------
The svm1 SVM is reserved for authorized users only!

2 entries were displayed.

cluster1::>
----
xref:manage-banner-reference.adoc[Verwalten des Banners]
