---
permalink: system-admin/different-shells-cli-commands-concept-cluster-admin.html 
sidebar: sidebar 
keywords: diag, secd, different, shells, cli, commands, cluster, administrators, clustershell, nodeshell, systemshell, display, list, help 
summary: Der Cluster verfügt über drei verschiedene Shells für CLI-Befehle, die Clustershell, die Nodeshell und die Systemshell. Die Shells dienen unterschiedlichen Zwecken und verfügen jeweils über einen anderen Befehlssatz. 
---
= Informationen zu den verschiedenen ONTAP Shells für CLI-Befehle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Cluster verfügt über drei verschiedene Shells für CLI-Befehle, die _clustershell_, die _nodeshell_ und die _systemshell_. Die Shells dienen unterschiedlichen Zwecken und verfügen jeweils über einen anderen Befehlssatz.

* Die Clustershell ist die native Shell, die automatisch gestartet wird, wenn Sie sich im Cluster anmelden.
+
Es stellt alle Befehle bereit, die Sie zum Konfigurieren und Verwalten des Clusters benötigen. Die Clustershell CLI-Hilfe (aufgerufen durch  `?` an der Clustershell-Eingabeaufforderung) zeigt die verfügbaren Clustershell-Befehle an. Der  `man`-Befehl in der Clustershell zeigt die Manpage für den angegebenen Clustershell-Befehl an (`man <command_name>`. Weitere Informationen zu  `man` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/man.html["ONTAP-Befehlsreferenz"^].

* Die Nodeshell ist eine spezielle Shell für Befehle, die nur auf Knotenebene wirksam sind.
+
Die nodeshell ist über den  `system node run` Befehl zugänglich. Weitere Informationen zu  `system node run` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/system-node-run.html["ONTAP-Befehlsreferenz"^].

+
Die nodeshell CLI-Hilfe (aufgerufen durch  `?` oder  `help` an der nodeshell-Eingabeaufforderung) zeigt die verfügbaren nodeshell-Befehle an. Der  `man`-Befehl in der nodeshell zeigt die Manpage für den angegebenen nodeshell-Befehl an.

+
Viele häufig verwendete Nodeshell-Befehle und Optionen werden in die Clustershell getunnelt oder als Aliase bereitgestellt und können auch von der Clustershell aus ausgeführt werden.

* Die Systemshell ist eine Low-Level-Shell, die ausschließlich zu Diagnose- und Fehlerbehebungszwecken verwendet wird.
+
Die systemshell und das zugehörige  `diag` Konto sind für Low-Level-Diagnosezwecke vorgesehen. Für den Zugriff ist die Berechtigungsstufe „Diagnose“ erforderlich und er ist ausschließlich dem technischen Support zur Durchführung von Fehlerbehebungsaufgaben vorbehalten.



Weitere Informationen zu den in diesem Verfahren beschriebenen Befehlen befinden sich in der link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP-Befehlsreferenz"^].



[[access-of-nodeshell-commands-and-options-in-the-clustershell]]
== Zugriff auf Nodeshell-Befehle und Optionen in der Clustershell

Nodeshell-Befehle und Optionen sind über die Nodeshell zugänglich:

`system node run –node _nodename_`

Viele häufig verwendete Nodeshell-Befehle und Optionen werden in die Clustershell getunnelt oder als Aliase bereitgestellt und können auch von der Clustershell aus ausgeführt werden.

Die in der Clustershell unterstützten Nodeshell-Optionen können über den  `vserver options clustershell` Befehl aufgerufen werden. Diese Optionen lassen sich durch eine Abfrage der Clustershell-CLI mit  `vserver options -vserver _nodename_or_clustername_ -option-name ?` anzeigen.

Wenn in der Clustershell ein Nodeshell- oder Legacy-Befehl oder eine entsprechende Option eingegeben wird und dieser Befehl oder diese Option einen entsprechenden Clustershell-Befehl hat, informiert ONTAP über den zu verwendenden Clustershell-Befehl.

Wenn ein Node-Shell- oder Legacy-Befehl oder eine Option eingegeben wird, die in der Cluster-Shell nicht unterstützt wird, informiert ONTAP über den Status „`nicht unterstützt`“ für den Befehl oder die Option.



[[display-available-nodeshell-commands]]
== Verfügbare Nodeshell-Befehle

Eine Liste der verfügbaren nodeshell Befehle ist über die CLI-Hilfe der nodeshell abrufbar.

.Schritte
. Um auf die Nodeshell zuzugreifen, den folgenden Befehl an der Systemeingabeaufforderung der Clustershell eingeben:
+
`*system node run -node {_nodename_|local}*`

+
`local` ist der Knoten, den Sie für den Zugriff auf den Cluster verwendet haben.

+
[NOTE]
====
Der  `system node run`Befehl hat einen Aliasbefehl,  `run`.

====
. Im Nodeshell kann mit dem folgenden Befehl die Liste der verfügbaren Nodeshell-Befehle angezeigt werden:
+
`*[_commandname_] help*`

+
 `_commandname_` ist der Name des Befehls, dessen Verfügbarkeit Sie anzeigen möchten. Wenn  `_commandname_` nicht angegeben wird, zeigt die CLI alle verfügbaren nodeshell Befehle an.

+
Sie drücken die Eingabetaste `exit` oder geben Strg+d ein, um zur Clustershell CLI zurückzukehren.

+
Weitere Informationen zu  `exit` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/exit.html["ONTAP-Befehlsreferenz"^].



.Beispiel für die Anzeige der verfügbaren Nodeshell-Befehle
Das folgende Beispiel greift auf die Nodeshell eines Knotens namens node2 zu und zeigt Informationen für den Nodeshell-Befehl  `environment` an:

[listing]
----
cluster1::> system node run -node node2
Type 'exit' or 'Ctrl-D' to return to the CLI

node2> environment help
Usage: environment status |
     [status] [shelf [<adapter>[.<shelf-number>]]] |
     [status] [shelf_log] |
     [status] [shelf_stats] |
     [status] [shelf_power_status] |
     [status] [chassis [all | list-sensors | Temperature | PSU 1 |
     PSU 2 | Voltage | SYS FAN | NVRAM6-temperature-3 | NVRAM6-battery-3]]
----