---
permalink: system-admin/download-nlf-task.html 
sidebar: sidebar 
keywords: install, license, convert, download, add, record, software, entitlement, keys, codes, cluster, administrator, nlf, ontap one 
summary: Wenn auf Ihrem System ONTAP 9.10.1 oder eine neuere Version läuft, können die Lizenzdateien oder 28-stelligen Lizenzschlüssel auf bestehenden Systemen aktualisiert werden, indem die NLF für ONTAP One oder ONTAP Core von der NetApp Support Site heruntergeladen wird. 
---
= Lizenzdateien (NLF) von NetApp von der NetApp Support Site herunterladen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn auf Ihrem System ONTAP 9.10.1 oder höher ausgeführt wird, können die Bundle-Lizenzdateien auf bestehenden Systemen durch Herunterladen der NLF für ONTAP One oder ONTAP Core von der NetApp Support Site aktualisiert werden.


NOTE: Die SnapMirror Cloud- und SnapMirror S3-Lizenzen sind nicht im Lieferumfang von ONTAP One enthalten. Sie sind Teil des ONTAP One Compatibility Bundle, das kostenlos erhältlich ist, wenn ONTAP One und link:../data-protection/install-snapmirror-cloud-license-task.html["separat anfordern"] vorhanden sind.

.Schritte
Sie können ONTAP One-Lizenzdateien für Systeme mit vorhandenen NetApp Lizenzdateipaketen und für Systeme mit 28-stelligen Lizenzschlüsseln herunterladen, die in NetApp Lizenzdateien auf Systemen mit ONTAP 9.10.1 und höher konvertiert wurden. Gegen Gebühr können Sie Systeme auch von ONTAP Base auf ONTAP One aktualisieren. Weitere Informationen zum Herunterladen von NetApp Lizenzdateien finden Sie im KB-Artikel link:https://kb.netapp.com/nss/Licensing/How_to_download_NLF_licenses_from_the_NetApp_Support_Site["So laden Sie NLF-Lizenzen von der NetApp Support Site herunter"^].

[role="tabbed-block"]
====
.Upgrade der bestehenden NLF
--
. Wenden Sie sich an Ihr NetApp Vertriebsteam und fordern Sie das Lizenzdateipaket an, das für ein Upgrade oder eine Konvertierung gewünscht wird (zum Beispiel von ONTAP Base zu ONTAP One oder von Core Bundle und Data Protection Bundle zu ONTAP One).
+
Wenn Ihre Anfrage bearbeitet wurde, erhalten Sie eine E-Mail von netappsw@netapp.com mit dem Betreff "NetApp Software Licensing Notification for SO# [SO Number]", und die E-Mail enthält einen PDF-Anhang, der Ihre Lizenzseriennummer enthält.

. Melden Sie sich bei der link:https://mysupport.netapp.com/site/["NetApp Support Site"^] an.
. *Systeme > Softwarelizenzen* auswählen.
. Im Menü *Seriennummer* auswählen, die erhaltene Seriennummer eingeben und auf *Neue Suche* klicken.
. Das gewünschte Lizenzpaket zum Konvertieren ermitteln.
. Für jedes Lizenzpaket auf *Get NetApp License File* klicken und die NLFs herunterladen, sobald sie verfügbar sind.
. link:../system-admin/install-license-task.html["Installieren"]die ONTAP One Datei.


--
.Upgrade NLF aus Lizenzschlüssel konvertiert
--
. Melden Sie sich bei der link:https://mysupport.netapp.com/site/["NetApp Support Site"^] an.
. *Systeme > Softwarelizenzen* auswählen.
. Im Menü *Seriennummer* auswählen, die Seriennummer des Systems eingeben und auf *Neue Suche* klicken.
. Die gewünschte Lizenz zum Konvertieren in der Spalte *Berechtigung* suchen und dort auf *Prüfen* klicken.
. Im Formular „Berechtigung prüfen“ die Option „Lizenzen für 9.10.x und höher generieren“ auswählen.
. Das *Formular zur Überprüfung der Berechtigung* schließen.
+
Es ist mit einer Wartezeit von mindestens 2 Stunden zu rechnen, bis die Lizenzen generiert sind.

. Schritte 1 bis 3 wiederholen.
. Die ONTAP One Lizenz suchen, auf *Get NetApp License File* klicken und die Zustellungsmethode auswählen.
. link:../system-admin/install-license-task.html["Installieren"]die ONTAP One Datei.


--
====