---
permalink: system-admin/download-nlf-task.html 
sidebar: sidebar 
keywords: install, license, convert, download, add, record, software, entitlement, keys, codes, cluster, administrator, nlf, ontap one 
summary: Wenn auf Ihrem System ONTAP 9.10.1 oder höher ausgeführt wird, können Sie die Lizenzdateien oder den 28-stelligen Lizenzschlüssel auf vorhandenen Systemen aktualisieren, indem Sie die Lizenzdatei für ONTAP One oder den ONTAP-Kern von der NetApp Support-Website herunterladen. 
---
= Laden Sie die NetApp-Lizenzdateien (NLF) von der NetApp Support-Website herunter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn auf Ihrem System ONTAP 9.10.1 oder höher ausgeführt wird, können Sie die Lizenzdateien für Bündel auf vorhandenen Systemen aktualisieren, indem Sie die Lizenzdatei für ONTAP One oder ONTAP Core von der NetApp Support-Website herunterladen.


NOTE: Die Lizenzen für SnapMirror Cloud und SnapMirror S3 sind nicht in ONTAP One enthalten. Sie sind Teil des ONTAP One Kompatibilitätspaket, das Sie kostenlos erhalten können, wenn Sie ONTAP One und habenlink:../data-protection/install-snapmirror-cloud-license-task.html["Separat anfordern"].

.Schritte
Sie können ONTAP One-Lizenzdateien für Systeme mit vorhandenen NetApp-Lizenzdateipaketen und für Systeme mit 28-stelligen Lizenzschlüsseln herunterladen, die auf Systemen mit ONTAP 9.10.1 und höher in NetApp-Lizenzdateien konvertiert wurden. Gegen eine Gebühr haben Sie auch die Möglichkeit, Systeme von ONTAP Base auf ONTAP One aufzurüsten.

[role="tabbed-block"]
====
.Vorhandene Lizenzdatei aktualisieren
--
. Wenden Sie sich an Ihr NetApp Vertriebsteam und fordern Sie das Lizenzdateipaket an, das Sie aktualisieren oder konvertieren möchten (z. B. ONTAP Base zu ONTAP One oder Core Bundle und Datensicherungs-Bundle zu ONTAP One).
+
Wenn Ihre Anfrage bearbeitet wird, erhalten Sie eine E-Mail von netappsw@netapp.com mit dem Betreff „NetApp Softwarelizenzierungsbenachrichtigung für SO# [SO-Nummer]“. Die E-Mail enthält einen PDF-Anhang mit Ihrer Lizenzseriennummer.

. Melden Sie sich beim an link:https://mysupport.netapp.com/site/["NetApp Support-Website"^].
. Wählen Sie *Systeme > Softwarelizenzen*.
. Wählen Sie im Menü die Option *Seriennummer*, geben Sie die Seriennummer ein, die Sie erhalten haben, und klicken Sie auf *Neue Suche*.
. Suchen Sie das Lizenzpaket, das Sie konvertieren möchten.
. Klicken Sie für jedes Lizenzpaket auf *NetApp-Lizenzdatei abrufen* und laden Sie die NLFs herunter, wenn sie verfügbar sind.
. link:../system-admin/install-license-task.html["Installieren"] Die ONTAP One-Datei.


--
.Upgrade-NLF vom Lizenzschlüssel konvertiert
--
. Melden Sie sich beim an link:https://mysupport.netapp.com/site/["NetApp Support-Website"^].
. Wählen Sie *Systeme > Softwarelizenzen*.
. Wählen Sie im Menü *Seriennummer*, geben Sie die Seriennummer des Systems ein und klicken Sie auf *Neue Suche*.
. Suchen Sie die Lizenz, die Sie konvertieren möchten, und klicken Sie in der Spalte *Berechtigung* auf *Check*.
. Klicken Sie im Formular *Berechtigung prüfen* auf *Lizenzen für 9.10.x und höher generieren*.
. Schließen Sie das Formular *Eignungsberechtigung prüfen*.
+
Sie müssen mindestens 2 Stunden warten, bis die Lizenzen erstellt werden.

. Wiederholen Sie die Schritte 1 bis 3.
. Suchen Sie die ONTAP One-Lizenz, klicken Sie auf *NetApp-Lizenzdatei abrufen*, und wählen Sie die Liefermethode aus.
. link:../system-admin/install-license-task.html["Installieren"] Die ONTAP One-Datei.


--
====