---
permalink: system-admin/files-sent-event-triggered-autosupport-messages-concept.html 
sidebar: sidebar 
keywords: files, event, triggered, autosupport, message, troubleshoot, subsystem, problem 
summary: Ereignisgesteuerte AutoSupport-Meldungen enthalten ausschließlich grundlegende Informationen und Hinweise zur Fehlerbehebung aus Subsystemen, die mit dem Ereignis verknüpft sind, das AutoSupport zur Generierung der Meldung veranlasst hat. Die spezifischen Daten unterstützen NetApp Support und Support-Partner bei der Fehlerbehebung. 
---
= Informationen zu Dateien, die in ereignisgesteuerten ONTAP AutoSupport-Nachrichten gesendet werden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ereignisgesteuerte AutoSupport-Meldungen enthalten ausschließlich grundlegende Informationen und Hinweise zur Fehlerbehebung aus Subsystemen, die mit dem Ereignis verknüpft sind, das AutoSupport zur Generierung der Meldung veranlasst hat. Die spezifischen Daten unterstützen NetApp Support und Support-Partner bei der Fehlerbehebung.

AutoSupport verwendet die folgenden Kriterien zur Steuerung des Inhalts in ereignisgesteuerten AutoSupport-Nachrichten:

* Welche Teilsysteme sind enthalten
+
Die Daten werden in Subsysteme gruppiert, darunter allgemeine Subsysteme wie Protokolldateien und spezifische Subsysteme wie RAID. Jedes Ereignis löst eine Nachricht aus, die nur die Daten aus bestimmten Subsystemen enthält.

* Der Detaillierungsgrad jedes enthaltenen Subsystems
+
Daten für jedes enthaltene Subsystem sind auf grundlegender oder Fehlerbehebungsebene verfügbar.



Alle möglichen Ereignisse können angezeigt werden, und es lässt sich mit dem  `system node autosupport trigger show` Befehl und dem  `-instance` Parameter ermitteln, welche Subsysteme in den Meldungen zu jedem Ereignis enthalten sind.

Zusätzlich zu den Subsystemen, die standardmäßig für jedes Ereignis enthalten sind, können zusätzliche Subsysteme entweder auf Basisebene oder auf Fehlerbehebungsebene mit dem  `system node autosupport trigger modify` Befehl hinzugefügt werden.
