---
permalink: system-admin/files-sent-event-triggered-autosupport-messages-concept.html 
sidebar: sidebar 
keywords: files, event, triggered, autosupport, message, troubleshoot, subsystem, problem 
summary: Ereignisgesteuerte AutoSupport Meldungen enthalten nur grundlegende und Fehlerbehebungsinformationen aus Subsystemen, die mit dem Ereignis verknüpft sind, die zum Generieren der Meldung durch AutoSupport geführt haben. Diese Daten helfen NetApp Support und Support Partnern bei der Problemlösung. 
---
= In ereignisausgelösten AutoSupport Meldungen gesendete Dateien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ereignisgesteuerte AutoSupport Meldungen enthalten nur grundlegende und Fehlerbehebungsinformationen aus Subsystemen, die mit dem Ereignis verknüpft sind, die zum Generieren der Meldung durch AutoSupport geführt haben. Diese Daten helfen NetApp Support und Support Partnern bei der Problemlösung.

AutoSupport verwendet die folgenden Kriterien, um Inhalte in ereignisausgelösten AutoSupport Meldungen zu kontrollieren:

* Welche Subsysteme sind im Lieferumfang enthalten
+
Daten werden zu Subsystemen wie allgemeinen Subsystemen wie z. B. Log-Dateien und speziellen Subsystemen wie z. B. RAID gruppiert. Jedes Ereignis löst eine Meldung aus, die nur die Daten aus spezifischen Subsystemen enthält.

* Die Detailebene jedes enthaltenen Subsystems
+
Die Daten für jedes enthaltene Subsystem werden auf Basis- oder Fehlerbehebungsebene bereitgestellt.



Mit dem `system node autosupport trigger show` Befehl mit dem `-instance` Parameter können Sie alle möglichen Ereignisse anzeigen und bestimmen, welche Subsysteme in Meldungen zu den einzelnen Ereignissen enthalten sind.

Zusätzlich zu den Subsystemen, die standardmäßig für jedes Ereignis enthalten sind, können Sie mit dem `system node autosupport trigger modify` Befehl zusätzliche Subsysteme entweder auf Basis- oder auf Fehlerbehebungsebene hinzufügen.
