---
permalink: system-admin/find-config-recover-cluster-task.html 
sidebar: sidebar 
keywords: cluster, configuration, recover, node, backup, file 
summary: Zur Wiederherstellung eines Clusters verwenden Sie die Konfiguration entweder für einen Node im Cluster oder für eine Backup-Datei einer Cluster-Konfiguration. 
---
= Suchen Sie die Backup-Datei für die ONTAP-Cluster-Konfiguration, um ein Cluster wiederherzustellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zur Wiederherstellung eines Clusters verwenden Sie die Konfiguration entweder für einen Node im Cluster oder für eine Backup-Datei einer Cluster-Konfiguration.

.Schritte
. Wählen Sie eine Art von Konfiguration, um das Cluster wiederherzustellen.
+
** Ein Node im Cluster
+
Wenn das Cluster mehr als einen Node enthält und einer der Nodes über eine Cluster-Konfiguration verfügt, als sich das Cluster in der gewünschten Konfiguration befand, können Sie das Cluster mithilfe der auf diesem Node gespeicherten Konfiguration wiederherstellen.

+
In den meisten Fällen ist der Knoten, der den Replikationsring mit der letzten Transaktions-ID enthält, der für das Wiederherstellen der Cluster-Konfiguration am besten verwendet werden kann.  `cluster ring show`Mit dem Befehl auf der erweiterten Berechtigungsebene können Sie eine Liste der replizierten Ringe anzeigen, die auf jedem Node im Cluster verfügbar sind.

** Eine Backup-Datei für die Cluster-Konfiguration
+
Wenn Sie keinen Node mit der korrekten Cluster-Konfiguration identifizieren können oder wenn das Cluster aus einem einzelnen Node besteht, können Sie eine Backup-Datei für die Cluster-Konfiguration verwenden, um das Cluster wiederherzustellen.

+
Wenn Sie das Cluster von einer Backup-Datei der Konfiguration wiederherstellen, gehen alle seit dem Backup vorgenommenen Konfigurationsänderungen verloren. Nach der Wiederherstellung müssen alle Abweichungen zwischen der Backup-Datei der Konfiguration und der vorhandenen Konfiguration behoben werden. Weitere link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/ONTAP_Configuration_Backup_Resolution_Guide["ONTAP Konfigurations-Backup Resolution Guide"]Informationen zur Fehlerbehebung finden Sie im Knowledge Base Artikel.



. Wenn Sie sich für eine Backup-Datei der Cluster-Konfiguration entscheiden, stellen Sie die Datei dem Knoten zur Verfügung, den Sie verwenden möchten, um das Cluster wiederherzustellen.
+
|===
| Wenn sich die Backup-Datei der Konfiguration befindet... | Dann... 


 a| 
Unter einer Remote-URL
 a| 
 `system configuration backup download`Laden Sie den Node mit dem Befehl auf der erweiterten Berechtigungsebene auf den Recovery-Node herunter.



 a| 
Auf einem Node im Cluster
 a| 
.. Verwenden Sie den `system configuration backup show` Befehl auf der erweiterten Berechtigungsebene, um eine Backup-Datei für die Cluster-Konfiguration zu suchen, die erstellt wurde, als sich das Cluster in der gewünschten Konfiguration befand.
.. Wenn sich die Backup-Datei für die Cluster-Konfiguration nicht auf dem Node befindet, den Sie zum Wiederherstellen des Clusters verwenden möchten, `system configuration backup copy` kopieren Sie sie mit dem Befehl auf den Wiederherstellungsknoten.


|===

