---
permalink: system-admin/generate-certificate-signing-request-cluster-task.html 
sidebar: sidebar 
keywords: generate, certificate, sign, request, cluster, csr, ca 
summary: 'Sie können den Befehl „Erzeugen-csr“ verwenden, um eine Zertifikatsignierungsanforderung (CSR) zu erstellen. Nach Bearbeitung Ihrer Anfrage sendet Ihnen die Zertifizierungsstelle (CA) das signierte digitale Zertifikat.' 
---
= Generieren Sie eine Anforderung zum Signieren eines Zertifikats für das Cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den `generate-csr` Befehl Sicherheitszertifikat verwenden, um eine Zertifikatsignierungsanforderung (CSR) zu generieren. Nach Bearbeitung Ihrer Anfrage sendet Ihnen die Zertifizierungsstelle (CA) das signierte digitale Zertifikat.

.Bevor Sie beginnen
Um diese Aufgabe auszuführen, müssen Sie ein Cluster-Administrator oder SVM-Administrator sein.

.Schritte
. CSR erstellen:
+
`*security certificate generate-csr -common-name _FQDN_or_common_name_ -size 512|1024|1536|2048 -country _country_ -state _state_ -locality _locality_ -organization _organization_ -unit _unit_ -email-addr _email_of_contact_ -hash-function SHA1|SHA256|MD5*`

+
Eine vollständige Befehlssyntax finden Sie in den man-Pages.

+
Der folgende Befehl erzeugt einen CSR mit einem 2,048-bit privaten Schlüssel, der von der SHA256 Hashing-Funktion erzeugt wird, zur Verwendung durch die Software-Gruppe in der IT-Abteilung eines Unternehmens mit individuellem gemeinsamen Namen server1.companyname.com, mit Sitz in Sunnyvale, Kalifornien, USA. Die E-Mail-Adresse des SVM-Kontaktadministrators lautet \web@example.com. Das System zeigt den CSR und den privaten Schlüssel in der Ausgabe an.

+
[listing]
----
cluster1::>security certificate generate-csr -common-name
server1.companyname.com -size 2048 -country US -state California -
locality Sunnyvale -organization IT -unit Software -email-addr
web@example.com -hash-function SHA256
Certificate Signing Request :
-----BEGIN CERTIFICATE REQUEST-----
<certificate_value>
-----END CERTIFICATE REQUEST-----
Private Key :
24 | Administrator Authentication and RBAC
-----BEGIN RSA PRIVATE KEY-----
<key_value>
-----END RSA PRIVATE KEY-----
Note: Please keep a copy of your certificate request and private key
for future reference.
----
. Kopieren Sie die Zertifikatanforderung aus der CSR-Ausgabe, und senden Sie sie dann in elektronischer Form (z. B. E-Mail) an eine vertrauenswürdige Drittanbieter-CA zum Signieren.
+
Nach Bearbeitung Ihrer Anfrage sendet Ihnen die CA das signierte digitale Zertifikat. Sie sollten eine Kopie des privaten Schlüssels und des CA-signierten digitalen Zertifikats aufbewahren.


