---
permalink: system-admin/install-ca-signed-client-certificate-kmip-server-task.html 
sidebar: sidebar 
keywords: install, ca, signed, client, certificate, kmip, server, key, management, interoperability, protocol, server 
summary: 'Der Zertifikatsubtyp des Key Management Interoperability Protocol (KMIP) (der Parameter -subtype kmip-cert) legt gemeinsam mit den Client- und Server-Ca-Typen fest, dass das Zertifikat für die wechselseitige Authentifizierung des Clusters und einen externen Schlüsselmanager, z. B. einen KMIP-Server, verwendet wird.' 
---
= Installieren Sie ein CA-signiertes Client-Zertifikat für den KMIP-Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Zertifikatsubtyp des Key Management Interoperability Protocol (KMIP) (der Parameter -subtype kmip-cert) legt gemeinsam mit den Client- und Server-Ca-Typen fest, dass das Zertifikat für die wechselseitige Authentifizierung des Clusters und einen externen Schlüsselmanager, z. B. einen KMIP-Server, verwendet wird.

.Über diese Aufgabe
Installieren Sie ein KMIP-Zertifikat, um einen KMIP-Server als SSL-Server für das Cluster zu authentifizieren.

.Schritte
. Verwenden Sie den `security certificate install` Befehl mit den `-type server-ca` `-subtype kmip-cert` Parametern und, um ein KMIP-Zertifikat für den KMIP-Server zu installieren.
. Wenn Sie aufgefordert werden, geben Sie das Zertifikat ein, und drücken Sie anschließend die Eingabetaste.
+
ONTAP erinnert Sie daran, dass Sie eine Kopie des Zertifikats zur späteren Verwendung aufbewahren.

+
[listing]
----
cluster1::> security certificate install -type server-ca -subtype kmip-cert
-vserver cluster1

Please enter Certificate: Press <Enter> when done
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----


You should keep a copy of the CA-signed digital certificate for future reference.

cluster1::>
----


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-install.html["Sicherheitszertifikat installieren"^]

