---
permalink: system-admin/manage-cluster-time-concept.html 
sidebar: sidebar 
keywords: manage, cluster, time, administrator, ntp, network, time, protocol, zone 
summary: Obwohl ONTAP es Ihnen ermöglicht, Zeitzone, Datum und Uhrzeit im Cluster manuell einzustellen, wird empfohlen, NTP-Server zu konfigurieren, um die Clusterzeit zu synchronisieren. 
---
= ONTAP Clusterzeit verwalten (nur für Clusteradministratoren)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Probleme können auftreten, wenn die Clusterzeit ungenau ist. Obwohl ONTAP die manuelle Einstellung von Zeitzone, Datum und Uhrzeit im Cluster ermöglicht, wird empfohlen, die Network Time Protocol (NTP)-Server zu konfigurieren, um die Clusterzeit zu synchronisieren.

Ab ONTAP 9.5 kann der NTP-Server mit symmetrischer Authentifizierung konfiguriert werden.

NTP ist immer aktiviert. Dennoch ist eine Konfiguration erforderlich, damit der Cluster mit einer externen Zeitquelle synchronisiert wird. ONTAP ermöglicht die Verwaltung der NTP-Konfiguration des Clusters auf folgende Weise:

* Sie können maximal 10 externe NTP-Server mit dem Cluster verknüpfen (`cluster time-service ntp server create`).
+
** Zur Gewährleistung von Redundanz und Qualität des Zeitdienstes sollten mindestens drei externe NTP-Server mit dem Cluster verbunden werden.
** Ein NTP-Server kann über seine IPv4- oder IPv6-Adresse oder seinen vollqualifizierten Hostnamen angegeben werden.
** Die zu verwendende NTP-Version (v3 oder v4) kann manuell angegeben werden.
+
Standardmäßig wählt ONTAP automatisch die NTP-Version aus, die für einen bestimmten externen NTP-Server unterstützt wird.

+
Wenn die von Ihnen angegebene NTP-Version vom NTP-Server nicht unterstützt wird, kann kein Zeitaustausch stattfinden.

** Auf der erweiterten Berechtigungsstufe kann ein externer NTP-Server, der mit dem Cluster verknüpft ist, als primäre Zeitquelle für die Korrektur und Anpassung der Clusterzeit angegeben werden.


* Sie können die mit dem Cluster verbundenen NTP-Server anzeigen (`cluster time-service ntp server show`.
* Sie können die NTP-Konfiguration des Clusters ändern (`cluster time-service ntp server modify`).
* Sie können den Cluster von einem externen NTP-Server trennen (`cluster time-service ntp server delete`).
* Auf der erweiterten Berechtigungsstufe kann die Konfiguration zurückgesetzt werden, indem die Verbindung aller externen NTP-Server mit dem Cluster aufgehoben wird (`cluster time-service ntp server reset`).


Ein Knoten, der einem Cluster beitritt, übernimmt automatisch die NTP-Konfiguration des Clusters.

Neben der Verwendung von NTP ermöglicht ONTAP auch die manuelle Verwaltung der Clusterzeit. Diese Funktion ist hilfreich, wenn fehlerhafte Zeitangaben korrigiert werden müssen (zum Beispiel wenn die Zeit eines Knotens nach einem Neustart erheblich falsch ist). In diesem Fall kann eine ungefähre Zeit für den Cluster angegeben werden, bis NTP mit einem externen Zeitserver synchronisieren kann. Die manuell festgelegte Zeit gilt für alle Knoten im Cluster.

Sie können die Clusterzeit auf folgende Weise manuell verwalten:

* Sie können die Zeitzone, das Datum und die Uhrzeit im Cluster festlegen oder ändern (`cluster date modify`).
* Sie können die aktuelle Zeitzone, das Datum und die Uhrzeiteinstellungen des Clusters anzeigen (`cluster date show`).


[NOTE]
====
Jobpläne werden nicht an manuelle Änderungen von Datum und Uhrzeit des Clusters angepasst. Diese Jobs werden basierend auf der aktuellen Clusterzeit geplant, die zum Zeitpunkt der Erstellung des Jobs oder der letzten Ausführung galt. Wenn Datum oder Uhrzeit des Clusters manuell geändert werden, sind die  `job show` und  `job history show` Befehle zu verwenden, um zu überprüfen, ob alle geplanten Jobs entsprechend Ihren Anforderungen in die Warteschlange gestellt und abgeschlossen werden.

====


[[commands-for-managing-the-cluster-time]]
== Befehle zur Verwaltung der Clusterzeit

Sie verwenden die  `cluster time-service ntp server` Befehle, um die NTP-Server für den Cluster zu verwalten. Sie verwenden die  `cluster date` Befehle, um die Clusterzeit manuell zu verwalten.

Ab ONTAP 9.5 kann der NTP-Server mit symmetrischer Authentifizierung konfiguriert werden.

Mit den folgenden Befehlen ist die Verwaltung der NTP-Server für den Cluster möglich:

|===
| Wenn Sie möchten... | Verwenden Sie diesen Befehl... 


 a| 
Den Cluster mit einem externen NTP-Server ohne symmetrische Authentifizierung verknüpfen
 a| 
`cluster time-service ntp server create -server server_name`



 a| 
Den Cluster mit einem externen NTP-Server mit symmetrischer authenticationAvailable in ONTAP 9.5 oder höher verknüpfen
 a| 
`cluster time-service ntp server create -server server_ip_address -key-id key_id`

[NOTE]
====
Der  `key_id` muss auf einen vorhandenen gemeinsam genutzten Schlüssel verweisen, der mit '`cluster time-service ntp key' konfiguriert ist.

====


 a| 
Symmetrische Authentifizierung für einen bestehenden NTP serverAn Server aktivieren. Ein bestehender NTP Server kann modifiziert werden, um die Authentifizierung durch Hinzufügen der erforderlichen Schlüssel-ID zu ermöglichen.

Verfügbar in ONTAP 9.5 oder höher
 a| 
`cluster time-service ntp server modify -server server_name -key-id key_id`



 a| 
Symmetrische Authentifizierung deaktivieren
 a| 
`cluster time-service ntp server modify -server server_name -is-authentication-enabled false`



 a| 
Einen gemeinsamen NTP-Schlüssel konfigurieren
 a| 
`cluster time-service ntp key create -id shared_key_id -type shared_key_type -value shared_key_value`

[NOTE]
====
Gemeinsame Schlüssel werden über eine ID referenziert. Die ID, ihr Typ und ihr Wert müssen sowohl auf dem Knoten als auch auf dem NTP Server identisch sein.

====


 a| 
Informationen zu den mit dem Cluster verbundenen NTP-Servern
 a| 
`cluster time-service ntp server show`



 a| 
Die Konfiguration eines externen NTP-Servers, der mit dem Cluster verbunden ist, anpassen
 a| 
`cluster time-service ntp server modify`



 a| 
Einen NTP-Server vom Cluster trennen
 a| 
`cluster time-service ntp server delete`



 a| 
Die Konfiguration wird zurückgesetzt, indem die Zuordnung aller externen NTP-Server zum Cluster entfernt wird.
 a| 
`cluster time-service ntp server reset`

[NOTE]
====
Für diesen Befehl ist die erweiterte Berechtigungsebene erforderlich.

====
|===
Mit den folgenden Befehlen ist eine manuelle Verwaltung der Clusterzeit möglich:

|===
| Wenn Sie möchten... | Verwenden Sie diesen Befehl... 


 a| 
Zeitzone, Datum und Uhrzeit festlegen oder ändern
 a| 
`cluster date modify`



 a| 
Zeitzonen-, Datums- und Uhrzeiteinstellungen für den Cluster anzeigen
 a| 
`cluster date show`

|===
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/cluster-date-show.html["cluster date show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/cluster-date-modify.html["cluster date modify"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=cluster+time-service+ntp["Cluster Zeitdienst NTP"^]
* link:https://docs.netapp.com/us-en/ontap-cli/job-show.html["Job anzeigen"^]

