---
permalink: system-admin/manage-web-services-concept.html 
sidebar: sidebar 
keywords: manage, web, services, svm, storage, virtual, machine, cluster, controller, user 
summary: 'Sie können einen Webdienst für das Cluster oder eine Storage Virtual Machine (SVM) aktivieren bzw. deaktivieren, die Einstellungen für Webservices anzeigen und festlegen, ob Benutzer einer Rolle auf einen Webservice zugreifen können.' 
---
= Web Services-Übersicht verwalten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen Webdienst für das Cluster oder eine Storage Virtual Machine (SVM) aktivieren bzw. deaktivieren, die Einstellungen für Webservices anzeigen und festlegen, ob Benutzer einer Rolle auf einen Webservice zugreifen können.

Es gibt folgende Möglichkeiten, Web-Services für das Cluster oder eine SVM zu managen:

* Aktivieren oder Deaktivieren eines bestimmten Webservice
* Festlegen, ob der Zugriff auf einen Webdienst nur auf verschlüsseltes HTTP (SSL) beschränkt ist
* Anzeigen der Verfügbarkeit von Webservices
* Benutzern einer Rolle den Zugriff auf einen Webservice zu ermöglichen oder zu verdrängen
* Anzeigen der Rollen, die auf einen Webdienst zugreifen dürfen


Damit ein Benutzer auf einen Webdienst zugreifen kann, müssen alle folgenden Bedingungen erfüllt sein:

* Der Benutzer muss authentifiziert sein.
+
Beispielsweise kann ein Webdienst einen Benutzernamen und ein Kennwort anfordern. Die Antwort des Benutzers muss mit einem gültigen Konto übereinstimmen.

* Der Benutzer muss mit der richtigen Zugriffsmethode eingerichtet sein.
+
Authentifizierung ist nur für Benutzer mit der richtigen Zugriffsmethode für den angegebenen Webdienst erfolgreich. Für den Webservice der ONTAP API  `ontapi`), Benutzer müssen die haben `ontapi` Zugriffsmethode. Für alle anderen Web-Dienste müssen die Benutzer über die verfügen `http` Zugriffsmethode.

+
[NOTE]
====
Sie verwenden das `security login` Befehle zum Verwalten der Zugriffsmethoden und Authentifizierungsmethoden von Benutzern.

====
* Der Webdienst muss so konfiguriert sein, dass die Zugriffskontrollrolle des Benutzers zugelassen wird.
+
[NOTE]
====
Sie verwenden das `vserver services web access` Befehle, um den Zugriff einer Rolle auf einen Webdienst zu steuern.

====


Wenn eine Firewall aktiviert ist, muss die Firewallrichtlinie für die Nutzung von LIF für Web-Services so eingerichtet sein, dass HTTP oder HTTPS möglich sind.

Wenn Sie HTTPS für den Webservice-Zugriff verwenden, muss auch die SSL für das Cluster oder die SVM mit dem Webservice aktiviert sein. Des Weiteren müssen Sie ein digitales Zertifikat für das Cluster oder die SVM vorlegen.
