---
permalink: system-admin/manage-cli-sessions.html 
sidebar: sidebar 
keywords: record, cli, script, start, stop, session 
summary: Sie können eine CLI-Sitzung in eine Datei mit einem festgelegten Namen und Größenlimit aufnehmen und anschließend die Datei auf ein FTP- oder HTTP-Ziel hochladen. 
---
= Verwalten von CLI-Sitzungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine CLI-Sitzung in eine Datei mit einem festgelegten Namen und Größenlimit aufnehmen und anschließend die Datei auf ein FTP- oder HTTP-Ziel hochladen. Sie können auch Dateien anzeigen oder löschen, in denen Sie zuvor CLI-Sitzungen aufgezeichnet haben.



== Notieren Sie eine CLI-Sitzung

Ein Datensatz einer CLI-Sitzung wird beendet, wenn Sie die Aufzeichnung beenden oder die CLI-Sitzung beenden oder wenn die Datei die angegebene Größenbeschränkung erreicht. Die standardmäßige Dateigröße beträgt 1 MB. Die maximale Dateigröße beträgt 2 GB.

Das Aufzeichnen einer CLI-Sitzung ist beispielsweise nützlich, wenn Sie ein Problem beheben und detaillierte Informationen speichern möchten oder wenn Sie eine permanente Aufzeichnung der Speichernutzung zu einem bestimmten Zeitpunkt erstellen möchten.

.Schritte
. Starten Sie die Aufzeichnung der aktuellen CLI-Sitzung in einer Datei:
+
[source, cli]
----
system script start
----
+
Weitere Informationen zur Verwendung des `system script start` Befehl, siehe die man-Page.

+
ONTAP beginnt mit der Aufzeichnung Ihrer CLI-Sitzung in der angegebenen Datei.

. Fahren Sie mit Ihrer CLI-Sitzung fort.
. Wenn Sie fertig sind, beenden Sie die Aufzeichnung der Sitzung:
+
[source, cli]
----
system script stop
----
+
Weitere Informationen zur Verwendung des `system script stop` Befehl, siehe die man-Page.

+
ONTAP beendet die Aufzeichnung Ihrer CLI-Sitzung.





== Befehle zum Verwalten von Datensätzen von CLI-Sitzungen

Sie verwenden das `system script` Befehle zum Verwalten von Datensätzen von CLI-Sitzungen.

|===
| Ihr Ziel ist | Befehl 


 a| 
Starten Sie die Aufzeichnung der aktuellen CLI-Sitzung in in einer bestimmten Datei
 a| 
`system script start`



 a| 
Aufzeichnung der aktuellen CLI-Sitzung beenden
 a| 
`system script stop`



 a| 
Zeigt Informationen zu Datensätzen von CLI-Sitzungen an
 a| 
`system script show`



 a| 
Laden Sie einen Datensatz einer CLI-Sitzung auf ein FTP- oder HTTP-Ziel hoch
 a| 
`system script upload`



 a| 
Löschen eines Datensatzes einer CLI-Sitzung
 a| 
`system script delete`

|===
.Verwandte Informationen
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9-Befehle"^]



== Befehle zum Verwalten der automatischen Zeitüberschreitung von CLI-Sitzungen

Der Wert für das Zeitlimit gibt an, wie lange eine CLI-Sitzung inaktiv bleibt, bevor sie automatisch beendet wird. Der Wert für die CLI-Zeitüberschreitung ist das gesamte Cluster. Das bedeutet, dass jeder Node in einem Cluster denselben CLI-Zeitüberschreitungswert verwendet.

Standardmäßig beträgt die automatische Zeitüberschreitung von CLI-Sitzungen 30 Minuten.

Sie verwenden das `system timeout` Befehle zum Verwalten der automatischen Zeitüberschreitung von CLI-Sitzungen.

|===
| Ihr Ziel ist | Befehl 


 a| 
Zeigt den automatischen Zeitüberschreitungszeitraum für CLI-Sessions an
 a| 
`system timeout show`



 a| 
Ändern Sie den automatischen Zeitüberschreitungszeitraum für CLI-Sitzungen
 a| 
`system timeout modify`

|===
.Verwandte Informationen
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9-Befehle"^]
