---
permalink: system-admin/manage-licenses-concept.html 
sidebar: sidebar 
keywords: manage, license, ontap one, enable, add, record, software, entitlement, keys, codes, risk, usage, cluster, administrator, nlf, bundle 
summary: Eine Lizenz ist ein Nachweis für eine oder mehrere Softwareberechtigungen. Ab ONTAP 9.10.1 werden alle Lizenzen als NetApp Lizenzdatei bereitgestellt, bei der es sich um eine einzelne Datei handelt, die mehrere Funktionen aktiviert. Ab Mai 2023 werden alle AFF-Systeme und FAS-Systeme entweder mit der ONTAP One Software Suite oder der ONTAP Base Software Suite verkauft, und ab Juni 2023 werden alle ASA-Systeme mit ONTAP One für SAN verkauft. 
---
= ONTAP-Lizenzierungsübersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Eine Lizenz ist ein Nachweis für eine oder mehrere Softwareberechtigungen. Ab ONTAP 9.10.1 werden alle Lizenzen als NetApp Lizenzdatei (NLF) bereitgestellt, bei der es sich um eine einzelne Datei handelt, die mehrere Funktionen aktiviert. Ab Mai 2023 werden alle AFF Systeme (sowohl A-Serie als auch C-Serie) und FAS Systeme entweder mit der ONTAP One Software Suite oder der ONTAP Base Software Suite verkauft, und ab Juni 2023 werden alle ASA Systeme mit ONTAP One für SAN verkauft. Jede Software Suite wird als einzelne NLF bereitgestellt und ersetzt die separaten NLF-Bundles, die erstmals in ONTAP 9.10.1 eingeführt wurden.



[[licenses-included-with-ontap-one]]
== In ONTAP One enthaltene Lizenzen

ONTAP One umfasst alle verfügbaren lizenzierten Funktionen. Es enthält eine Kombination der Inhalte der ehemaligen Core Bundle, Data Protection Bundle, Security and Compliance Bundle, Hybrid Cloud Bundle und Encryption Bundle, wie in der Tabelle dargestellt. Verschlüsselung ist in eingeschränkten Ländern nicht verfügbar.

|===


| Früherer Bundle Name | ONTAP Schlüssel enthalten 


.5+| Kernpaket | FlexClone 


| SnapRestore 


| NFS, SMB, S3 


| FC, iSCSI 


| NVME-oF 


.3+| Security and Compliance Bundle | Autonomous Ransomware Protection 


| MTKM 


| SnapLock 


.3+| Datenschutzpaket | SnapMirror (asynchron, synchron, active sync) 


| SnapCenter 


| SnapMirror S3 für NetApp Ziele 


.2+| Hybrid Cloud Paket | SnapMirror Cloud 


| SnapMirror S3 für Nicht-NetApp-Ziele 


.2+| Verschlüsselungspaket | NetApp Volume Encryption 


| Trusted Platform Module 
|===


[[licenses-not-included-with-ontap-one]]
== Lizenzen, die nicht in ONTAP One enthalten sind

ONTAP One beinhaltet keine der von NetApp bereitgestellten Cloud-Services, einschließlich der folgenden:

* NetApp Cloud Tiering
* Data Infrastructure Insights
* NetApp Backup and Recovery
* Data Governance




[[ontap-one-for-existing-systems]]
== ONTAP One für bestehende Systeme

Wenn Sie bestehende Systeme haben, die aktuell unter NetApp Support stehen, aber noch nicht auf ONTAP One aktualisiert wurden, bleiben die vorhandenen Lizenzen auf diesen Systemen gültig und funktionieren wie erwartet. Wenn zum Beispiel die SnapMirror Lizenz bereits auf bestehenden Systemen installiert ist, ist kein Upgrade auf ONTAP One erforderlich, um eine neue SnapMirror Lizenz zu erhalten. Wenn jedoch keine SnapMirror Lizenz auf einem bestehenden System installiert ist, kann diese Lizenz nur durch ein kostenpflichtiges Upgrade auf ONTAP One erworben werden.

Ab Juni 2023 können ONTAP-Systeme, die 28-stellige Lizenzschlüssel verwenden, auch link:https://kb.netapp.com/onprem/ontap/os/How_to_get_an_ONTAP_One_license_when_the_system_has_28_character_keys["Upgrade auf das ONTAP One oder ONTAP Base Kompatibilitätspundle"^].



[[licenses-included-with-ontap-base]]
== In ONTAP Base enthaltene Lizenzen

ONTAP Base ist eine optionale Software-Suite, die eine Alternative zu ONTAP One für ONTAP Systeme darstellt. Sie ist für spezielle Anwendungsfälle vorgesehen, in denen Datenschutztechnologien wie SnapMirror und SnapCenter sowie Sicherheitsfunktionen wie Autonomous Ransomware nicht erforderlich sind, beispielsweise bei Nicht-Produktionssystemen für dedizierte Test- oder Entwicklungsumgebungen. Zusätzliche Lizenzen können zu ONTAP Base nicht hinzugefügt werden. Wenn zusätzliche Lizenzen wie SnapMirror benötigt werden, ist ein Upgrade auf ONTAP One erforderlich.

|===


| Früherer Bundle Name | ONTAP Schlüssel enthalten 


.5+| Kernpaket | FlexClone 


| SnapRestore 


| NFS, SMB, S3 


| FC, iSCSI 


| NVME-oF 


.2+| Verschlüsselungspaket | NetApp Volume Encryption 


| Trusted Platform Module 
|===


[[licenses-included-with-ontap-one-for-san]]
== Lizenzen, die in ONTAP One für SAN enthalten sind

ONTAP One für SAN ist für ASA A-Series und C-Series Systeme verfügbar. Dies ist die einzige Software Suite, die für SAN verfügbar ist. ONTAP One für SAN enthält die folgenden Lizenzen:

|===


| ONTAP Schlüssel enthalten 


| FlexClone 


| SnapRestore 


| FC, iSCSI 


| NVME-oF 


| MTKM 


| SnapLock 


| SnapMirror (asynchron, synchron, active sync) 


| SnapCenter 


| SnapMirror Cloud 


| NetApp Volume Encryption 


| Trusted Platform Module 
|===


[[other-license-delivery-methods]]
== Andere Methoden zur Lizenzbereitstellung

In ONTAP 8.2 bis ONTAP 9.9.1 werden Lizenzschlüssel als 28-stellige Zeichenketten bereitgestellt, und es gibt einen Schlüssel pro ONTAP-Funktion. Die Installation von Lizenzschlüsseln erfolgt über die ONTAP CLI, wenn ONTAP 8.2 bis ONTAP 9.9.1 verwendet wird.

[NOTE]
====
ONTAP 9.10.1 unterstützt die Installation von 28-stelligen Lizenzschlüsseln mit System Manager oder der CLI. Wenn jedoch für eine Funktion eine NLF-Lizenz installiert ist, kann kein 28-stelliger Lizenzschlüssel über die NetApp Lizenzdatei für dieselbe Funktion installiert werden. Informationen zur Installation von NLFs oder Lizenzschlüsseln mit System Manager sind unter link:../system-admin/install-license-task.html["ONTAP-Lizenzen installieren"] zu finden.

====
.Verwandte Informationen
https://kb.netapp.com/onprem/ontap/os/How_to_get_an_ONTAP_One_license_when_the_system_has_NLFs_already["Wie eine ONTAP One Lizenz erhältlich ist, wenn das System bereits NLFs enthält"]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_verify_Data_ONTAP_Software_Entitlements_and_related_License_Keys_using_the_Support_Site["Überprüfung von ONTAP Software-Berechtigungen und zugehörigen Lizenzschlüsseln über die Support-Website"^]

http://mysupport.netapp.com/licensing/ontapentitlementriskstatus["NetApp: ONTAP-Berechtigungsrisikostatus"^]
