---
permalink: system-admin/manage-ssl-concept.html 
sidebar: sidebar 
keywords: manage, command, ssl, cluster, storage, svm, security, web, access, digital, certificate, encrypted, connection, server, browser 
summary: SSL-Befehle dienen zur Verwaltung des SSL-Protokolls, um die Sicherheit des Webzugriffs mithilfe eines digitalen Zertifikats zur Herstellung einer verschlüsselten Verbindung zu erhöhen. 
---
= SSL in ONTAP verwalten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die  `security ssl` Befehle dienen zur Verwaltung des SSL-Protokolls für den Cluster oder eine Storage Virtual Machine (SVM). Das SSL-Protokoll verbessert die Sicherheit des Webzugriffs, indem ein digitales Zertifikat verwendet wird, um eine verschlüsselte Verbindung zwischen einem Webserver und einem Browser herzustellen.

Sie können SSL für den Cluster oder eine Storage Virtual Machine (SVM) auf folgende Weise verwalten:

* SSL-Aktivierung
* Generieren und Installieren eines digitalen Zertifikats und dessen Zuordnung zum Cluster oder zur SVM
* Anzeigen der SSL-Konfiguration, um festzustellen, ob SSL aktiviert ist und, falls verfügbar, der Name des SSL-Zertifikats
* Einrichten von Firewall-Richtlinien für den Cluster oder die SVM, sodass Webzugriffsanfragen durchgelassen werden können
* Festlegen, welche SSL-Versionen verwendet werden können
* Beschränkung des Zugriffs auf einen Webdienst auf HTTPS-Anfragen




[[commands-for-managing-ssl]]
== Befehle zur Verwaltung von SSL

Sie verwenden die  `security ssl` Befehle, um das SSL-Protokoll für den Cluster oder eine Storage Virtual Machine (SVM) zu verwalten.

|===
| Wenn Sie möchten... | Verwenden Sie diesen Befehl... 


 a| 
SSL für den Cluster oder eine SVM aktivieren und ein digitales Zertifikat zuordnen
 a| 
`security ssl modify`



 a| 
Die SSL-Konfiguration und den Zertifikatsnamen für den Cluster oder eine SVM anzeigen
 a| 
`security ssl show`

|===
Weitere Informationen zu  `security ssl modify` und  `security ssl show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+ssl["ONTAP-Befehlsreferenz"^].
