---
permalink: system-admin/manage-ssl-concept.html 
sidebar: sidebar 
keywords: manage, ssl, security, web, access, digital, certificate, encrypted, connection, server, browser 
summary: Das SSL-Protokoll verbessert die Sicherheit des Webzugriffs, indem ein digitales Zertifikat verwendet wird, um eine verschlüsselte Verbindung zwischen einem Webserver und einem Browser herzustellen. 
---
= SSL verwalten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das SSL-Protokoll verbessert die Sicherheit des Webzugriffs, indem ein digitales Zertifikat verwendet wird, um eine verschlüsselte Verbindung zwischen einem Webserver und einem Browser herzustellen.

Sie haben folgende Möglichkeiten, SSL für das Cluster oder eine Storage Virtual Machine (SVM) zu verwalten:

* Aktivieren von SSL
* Generieren und Installieren eines digitalen Zertifikats und Verknüpfen eines Zertifikats mit dem Cluster oder der SVM
* Anzeigen der SSL-Konfiguration zur Bestätigung, ob SSL aktiviert wurde, und, falls verfügbar, der Name des SSL-Zertifikats
* Einrichtung von Firewallrichtlinien für das Cluster oder SVM, um Webzugriffsanfragen durchzuführen
* Definieren, welche SSL-Versionen verwendet werden können
* Beschränkung des Zugriffs auf nur HTTPS-Anforderungen für einen Webdienst

