---
permalink: system-admin/manage-banner-reference.html 
sidebar: sidebar 
keywords: manage, banner, svm, cluster, configure 
summary: Sie können das Banner auf Cluster- oder SVM-Ebene verwalten und die Anzeige des Banners ändern 
---
= Verwalten Sie den Bannertext, der auf ONTAP-Cluster- und SVM-Ebene angezeigt wird
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das Banner auf Cluster- oder SVM-Ebene managen. Das für den Cluster konfigurierte Banner wird auch für alle SVMs verwendet, die keine Bannernachricht definiert haben. Ein nachträglich erstelltes Banner für eine SVM überschreibt das Cluster-Banner für diese SVM.

.Wahlmöglichkeiten
* Managen Sie das Banner auf Cluster-Ebene:
+
|===
| Ihr Ziel ist | Dann... 


 a| 
Erstellen Sie ein Banner, das für alle Anmeldesitzungen angezeigt werden soll
 a| 
Setzen Sie ein Banner auf Cluster-Ebene:

`security login banner modify -vserver <cluster_name> { [-message "text"] | [-uri <ftp_or_http_addr>] }`



 a| 
Entfernen Sie das Banner für alle Anmeldungen (Cluster und SVM)
 a| 
Setzen Sie den Banner auf einen leeren String (`""`):

`security login banner modify -vserver * -message ""`



 a| 
Überschreiben eines Banners, das von einem SVM-Administrator erstellt wurde
 a| 
Ändern der SVM-Banner-Meldung:

`security login banner modify -vserver <svm_name> { [-message "<text>"] | [-uri <ftp_or_http_addr>] }`

|===
* Banner auf SVM-Ebene managen:
+
Die Angabe `-vserver <svm_name>` ist im SVM-Kontext nicht erforderlich.

+
|===
| Ihr Ziel ist | Dann... 


 a| 
Setzen Sie das vom Cluster-Administrator bereitgestellte Banner mit einem anderen Banner für die SVM außer Kraft
 a| 
Banner für SVM erstellen:

`security login banner modify -vserver <svm_name> { [-message "text"] | [-uri <ftp_or_http_addr>] }`



 a| 
Unterdrücken Sie das vom Cluster-Administrator bereitgestellte Banner, sodass für die SVM kein Banner angezeigt wird
 a| 
Setzen Sie das SVM-Banner auf einen leeren String für die SVM:

`security login banner modify -vserver <svm_name> -message ""`



 a| 
Verwenden Sie das Banner auf Cluster-Ebene, wenn die SVM derzeit ein Banner auf SVM-Ebene verwendet
 a| 
Stellen Sie das SVM-Banner auf `"-"`:

`security login banner modify -vserver <svm_name> -message "-"`

|===

