---
permalink: system-admin/manage-ip-addresses-access-sp-task.html 
sidebar: sidebar 
keywords: manage, ip, addresses, access, sp, ssh, connection, node, cluster 
summary: Standardmäßig akzeptiert der SP SSH-Verbindungsanfragen von Administrationshosts mit beliebigen IP-Adressen. Der SP kann so konfiguriert werden, dass er SSH-Verbindungsanfragen nur von Administrationshosts mit den von Ihnen angegebenen IP-Adressen akzeptiert. Die vorgenommenen Änderungen gelten für den SSH-Zugriff auf den SP aller Knoten im Cluster. 
---
= Die IP-Adresse des Administrationshosts wird hinzugefügt, um auf den ONTAP Service Processor zuzugreifen.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Standardmäßig akzeptiert der SP SSH-Verbindungsanfragen von Administrationshosts mit beliebigen IP-Adressen. Der SP kann so konfiguriert werden, dass er SSH-Verbindungsanfragen nur von Administrationshosts mit den von Ihnen angegebenen IP-Adressen akzeptiert. Die vorgenommenen Änderungen gelten für den SSH-Zugriff auf den SP aller Knoten im Cluster.

.Schritte
. SP-Zugriff wird nur den von Ihnen angegebenen IP-Adressen gewährt, indem der  `system service-processor ssh add-allowed-addresses` Befehl mit dem  `-allowed-addresses` Parameter verwendet wird.
+
** Der Wert des  `-allowed-addresses` Parameters muss im Format  `address`/`netmask` angegeben werden, und mehrere  `address`/`netmask` Paare müssen durch Kommas getrennt werden, zum Beispiel  `10.98.150.10/24, fd20:8b1e:b255:c09b::/64`.
+
Das Setzen des  `-allowed-addresses`Parameters auf  `0.0.0.0/0, ::/0`ermöglicht allen IP-Adressen den Zugriff auf den SP (Standard).

** Wenn die Standardeinstellung geändert wird, indem der SP-Zugriff auf nur die von Ihnen angegebenen IP-Adressen beschränkt wird, fordert ONTAP Sie auf zu bestätigen, dass die angegebenen IP-Adressen die Standardeinstellung „`allow all`“ ersetzen (`0.0.0.0/0, ::/0`).
** Der  `system service-processor ssh show`Befehl zeigt die IP-Adressen an, die auf den SP zugreifen können.


. Wenn eine bestimmte IP-Adresse vom Zugriff auf den SP ausgeschlossen werden soll, ist der  `system service-processor ssh remove-allowed-addresses` Befehl mit dem  `-allowed-addresses` Parameter zu verwenden.
+
Wenn alle IP-Adressen vom Zugriff auf den SP ausgeschlossen werden, ist der SP von keinem Administrationshost mehr erreichbar.



.Beispiele für die Verwaltung der IP-Adressen, die auf den SP zugreifen können
Die folgenden Beispiele zeigen die Standardeinstellung für den SSH-Zugriff auf den SP, die Standardeinstellung wird geändert, indem der SP-Zugriff auf nur die angegebenen IP-Adressen beschränkt wird, die angegebenen IP-Adressen aus der Zugriffsliste entfernt werden und anschließend der SP-Zugriff für alle IP-Adressen wiederhergestellt wird:

[listing]
----
cluster1::> system service-processor ssh show
  Allowed Addresses: 0.0.0.0/0, ::/0

cluster1::> system service-processor ssh add-allowed-addresses -allowed-addresses 192.168.1.202/24, 192.168.10.201/24

Warning: The default "allow all" setting (0.0.0.0/0, ::/0) will be replaced
         with your changes. Do you want to continue? {y|n}: y

cluster1::> system service-processor ssh show
  Allowed Addresses: 192.168.1.202/24, 192.168.10.201/24

cluster1::> system service-processor ssh remove-allowed-addresses -allowed-addresses 192.168.1.202/24, 192.168.10.201/24

Warning: If all IP addresses are removed from the allowed address list, all IP
         addresses will be denied access. To restore the "allow all" default,
         use the "system service-processor ssh add-allowed-addresses
         -allowed-addresses 0.0.0.0/0, ::/0" command. Do you want to continue?
          {y|n}: y

cluster1::> system service-processor ssh show
  Allowed Addresses: -

cluster1::> system service-processor ssh add-allowed-addresses -allowed-addresses 0.0.0.0/0, ::/0

cluster1::> system service-processor ssh show
  Allowed Addresses: 0.0.0.0/0, ::/0
----