---
permalink: system-admin/methods-extended-queries-concept.html 
sidebar: sidebar 
keywords: method, extended, queries, operations, perform, specified, values 
summary: Sie können erweiterte Abfragen verwenden, um für Objekte mit bestimmten Werten zu stimmen und Vorgänge durchzuführen. 
---
= Methoden zur Verwendung erweiterter Abfragen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können erweiterte Abfragen verwenden, um für Objekte mit bestimmten Werten zu stimmen und Vorgänge durchzuführen.

Sie geben erweiterte Abfragen an, indem Sie sie in geschweiften Klammern ({}) schließen. Eine erweiterte Abfrage muss vor allen anderen Parametern als erstes Argument nach dem Befehlsnamen angegeben werden. So legen Sie z. B. alle Volumes offline fest, deren Namen den String enthalten `tmp`, Sie führen den Befehl im folgenden Beispiel aus:

[listing]
----
cluster1::> volume modify {-volume *tmp*} -state offline
----
Erweiterte Abfragen sind in der Regel nur mit nützlich `modify` Und `delete` Befehle. Sie haben keine Bedeutung in `create` Oder `show` Befehle.

Die Kombination von Abfragen und Änderungsvorgängen ist ein nützliches Werkzeug. Es kann jedoch zu Verwirrung und Fehlern führen, wenn es falsch umgesetzt wird. Beispiel: Verwenden der (erweiterten Berechtigung) `system node image modify` Befehl zum Festlegen des Standard-Software-Images eines Node wird automatisch das andere Software-Image als nicht das Standard festgelegt. Der Befehl im folgenden Beispiel ist effektiv ein null Vorgang:

[listing]
----
cluster1::*> system node image modify {-isdefault true} -isdefault false
----
Mit diesem Befehl wird das aktuelle Standard-Image als nicht-Standard-Image festgelegt und dann das neue Standard-Image (das vorherige nicht-Standard-Image) auf das nicht-Standard-Image gesetzt. Dadurch werden die ursprünglichen Standardeinstellungen beibehalten. Sie können den Befehl wie im folgenden Beispiel angegeben verwenden, um den Vorgang ordnungsgemäß auszuführen:

[listing]
----
cluster1::*> system node image modify {-iscurrent false} -isdefault true
----