---
permalink: system-admin/methods-navigating-cli-command-directories-concept.html 
sidebar: sidebar 
keywords: method, navigating, cli, command, directories, hierarchy, path, structure 
summary: 'Die Befehle in der Befehlszeilenschnittstelle (CLI) sind in einer Hierarchie durch Befehlsverzeichnisse organisiert. Befehle in der Hierarchie können entweder durch Eingabe des vollständigen Befehlspfads oder durch Navigation durch die Verzeichnisstruktur ausgeführt werden.' 
---
= Navigation durch die ONTAP CLI-Befehlsverzeichnisse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Befehle in der Befehlszeilenschnittstelle (CLI) sind in einer Hierarchie durch Befehlsverzeichnisse organisiert. Befehle in der Hierarchie können entweder durch Eingabe des vollständigen Befehlspfads oder durch Navigation durch die Verzeichnisstruktur ausgeführt werden.

Bei Verwendung der Befehlszeilenschnittstelle (CLI) kann auf ein Befehlsverzeichnis zugegriffen werden, indem der Name des Verzeichnisses an der Eingabeaufforderung eingegeben und anschließend die Eingabetaste gedrückt wird. Der Verzeichnisname erscheint dann in der Eingabeaufforderung, um anzuzeigen, dass mit dem entsprechenden Befehlsverzeichnis interagiert wird. Um tiefer in die Befehlshierarchie zu gelangen, wird der Name eines Befehlsunterverzeichnisses eingegeben und anschließend die Eingabetaste gedrückt. Der Name des Unterverzeichnisses erscheint dann in der Eingabeaufforderung, und der Kontext wechselt zu diesem Unterverzeichnis.

Sie können durch mehrere Befehlsverzeichnisse navigieren, indem Sie den gesamten Befehl eingeben. Beispielsweise können Sie Informationen über Festplattenlaufwerke anzeigen, indem Sie den  `storage disk show` Befehl an der Eingabeaufforderung eingeben. Der Befehl kann auch ausgeführt werden, indem jeweils durch ein Befehlsverzeichnis navigiert wird, wie im folgenden Beispiel dargestellt:

[listing]
----
cluster1::> storage
cluster1::storage> disk
cluster1::storage disk> show
----
Weitere Informationen zu  `storage disk show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-show.html["ONTAP-Befehlsreferenz"^].

Sie können Befehle abkürzen, indem Sie nur die Mindestanzahl an Buchstaben eingeben, die den Befehl im aktuellen Verzeichnis eindeutig macht. Beispielsweise kann zur Abkürzung des Befehls im vorherigen Beispiel  `st d sh` eingegeben werden. Die Tabulatortaste kann auch verwendet werden, um abgekürzte Befehle zu vervollständigen und die Parameter eines Befehls, einschließlich der Standardparameterwerte, anzuzeigen.

Mit dem  `top` Befehl wird zur obersten Ebene der Befehlshierarchie gewechselt, und mit dem  `up` Befehl oder  `..` Befehl wird eine Ebene höher in der Befehlshierarchie gewechselt.

[NOTE]
====
Befehle und Befehlsoptionen, denen in der CLI ein Sternchen (*) vorangestellt ist, können nur auf der erweiterten Berechtigungsstufe oder höher ausgeführt werden.

====
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/top.html["Spitze"^]
* link:https://docs.netapp.com/us-en/ontap-cli/up.html["hoch"^]

