---
permalink: system-admin/methods-manage-sp-bmc-firmware-updates-concept.html 
sidebar: sidebar 
keywords: methods, manage, sp, bmc, firmware, update, image, baseline, download 
summary: ONTAP enthält ein SP-Firmware-Image, das als Basis-Image bezeichnet wird. Falls nachfolgend eine neue Version der SP-Firmware verfügbar wird, können Sie die SP-Firmware herunterladen und auf die heruntergeladene Version aktualisieren, ohne die ONTAP-Version aktualisieren zu müssen. 
---
= Managen von Updates der ONTAP SP/BMC-Firmware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die ONTAP enthält ein SP-Firmware-Image, das als _Baseline Image_ bezeichnet wird. Falls nachfolgend eine neue Version der SP-Firmware verfügbar wird, können Sie die SP-Firmware herunterladen und auf die heruntergeladene Version aktualisieren, ohne die ONTAP-Version aktualisieren zu müssen.

[NOTE]
====
Dieses Thema gilt sowohl für den SP als auch für den BMC.

====
ONTAP bietet folgende Methoden zum Verwalten von SP-Firmware-Updates:

* Die Funktion für die automatische Aktualisierung des SP ist standardmäßig aktiviert, sodass die SP-Firmware in folgenden Szenarien automatisch aktualisiert werden kann:
+
** Wenn Sie ein Upgrade auf eine neue Version von ONTAP durchführen
+
Das ONTAP-Upgrade umfasst automatisch das Update der SP-Firmware, vorausgesetzt, dass die in ONTAP enthaltene SP-Firmware-Version höher ist als die auf dem Node ausgeführte SP-Version.

+
[NOTE]
====
ONTAP erkennt ein automatisches Update auf dem SP und löst eine Korrekturmaßnahme aus, um die automatische SP-Aktualisierung bis zu dreimal zu wiederholen. Wenn alle drei Wiederholungen fehlschlagen, lesen Sie den Link zum Knowledge Base-Artikel: https://kb.NetApp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Health_Monitor_SPAutoUpgradeFailedMajorAlert__SP_Upgrade_Failes_-_AutoSupport_Message[Funktionsüberwachung SPAutoUpgradeFailedMajorAlert SP Upgrade failes - AutoSupport-Meldung].

====
** Wenn Sie eine Version der SP-Firmware von der NetApp Support Site herunterladen und die heruntergeladene Version ist neuer als die Version, auf der der SP derzeit ausgeführt wird
** Wenn Sie ein Downgrade oder ein Wechsel zu einer früheren Version von ONTAP durchführen
+
Die SP-Firmware wird automatisch auf die neueste kompatible Version aktualisiert, die von der ONTAP-Version unterstützt wird, auf die Sie zurückgesetzt oder heruntergestuft wurden. Ein manuelles Update der SP-Firmware ist nicht erforderlich.



+
Sie haben die Möglichkeit, die automatische SP-Update-Funktion mit dem `system service-processor image modify` Befehl zu deaktivieren. Es wird jedoch empfohlen, die Funktion aktiviert zu lassen. Die Deaktivierung der Funktionalität kann zu suboptimalen oder nicht qualifizierten Kombinationen zwischen dem ONTAP-Image und dem SP-Firmware-Image führen.

* Mit ONTAP können Sie ein SP Update manuell auslösen und mit dem `system service-processor image update` Befehl angeben, wie das Update erfolgen soll.
+
Sie können die folgenden Optionen angeben:

+
** Das zu verwendende SP-Firmware-Paket (`-package`)
+
Sie können die SP-Firmware auf ein heruntergeladenes Paket aktualisieren, indem Sie den Namen der Paketdatei angeben. Mit dem erweiterten `system image package show` Befehl werden alle Paketdateien (einschließlich der Dateien für das SP-Firmware-Paket) angezeigt, die auf einem Node verfügbar sind.

** Ob das SP-Firmware-Paket für das SP-Update verwendet (`-baseline`werden soll )
+
Sie können die SP-Firmware auf die Baseline-Version aktualisieren, die mit der derzeit ausgeführten ONTAP-Version gebündelt wird.



+
[NOTE]
====
Wenn Sie einige der erweiterten Update-Optionen oder -Parameter verwenden, werden die Konfigurationseinstellungen des BMC möglicherweise vorübergehend gelöscht. Nach dem Neustart kann es bis zu 10 Minuten dauern, bis ONTAP die BMC-Konfiguration wiederherstellen kann.

====
* ONTAP ermöglicht Ihnen, mit dem `system service-processor image update-progress show` Befehl den Status des neuesten SP-Firmware-Updates anzuzeigen, das von ONTAP ausgelöst wurde.


Jede vorhandene Verbindung zum SP wird beendet, wenn die SP-Firmware aktualisiert wird. In diesem Fall wird das Update der SP-Firmware automatisch oder manuell ausgelöst.

.Verwandte Informationen
https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["NetApp Downloads: System-Firmware und -Diagnose"^]
