---
permalink: system-admin/modify-cluster-attributes-task.html 
sidebar: sidebar 
keywords: modify, cluster, attributes, name, location, contact, information 
summary: Sie können die Attribute eines Clusters, z. B. den Cluster-Namen, den Standort und die Kontaktinformationen nach Bedarf ändern. 
---
= Cluster-Attribute ändern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können bei Bedarf die Attribute eines Clusters, z. B. den Cluster-Namen, den Standort und die Kontaktinformationen ändern.

.Über diese Aufgabe
Sie können die UUID eines Clusters nicht ändern. Diese ist beim Erstellen des Clusters festgelegt.

.Schritte
. Verwenden Sie zum Ändern von Cluster-Attributen das `cluster identity modify` Befehl.
+
Der `-name` Der Parameter gibt den Namen des Clusters an. Der `cluster identity modify` Auf der man-Page werden die Regeln zur Angabe des Namens des Clusters beschrieben.

+
Der `-location` Der Parameter gibt den Speicherort für das Cluster an.

+
Der `-contact` Parameter gibt die Kontaktinformationen an, z. B. einen Namen oder eine E-Mail-Adresse.



.Beispiel für die Umbenennung eines Clusters
Mit dem folgenden Befehl wird das aktuelle Cluster („`cluster1`") in „`cluster2`“ umbenannt:

[listing]
----
cluster1::> cluster identity modify -name cluster2
----