---
permalink: system-admin/modify-node-attributes-task.html 
sidebar: sidebar 
keywords: modify, node, attributes, owner, information, location, asset, tag, eligibility, cluster 
summary: Sie können die Attribute eines Node nach Bedarf ändern. Zu den Attributen, die Sie ändern können, gehören die Besitzinformationen des Knotens, Standortinformationen, Asset-Tag und die Berechtigung zur Teilnahme am Cluster. 
---
= Ändern von Node-Attributen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Attribute eines Node nach Bedarf ändern. Zu den Attributen, die Sie ändern können, gehören die Besitzinformationen des Node, die Ortinformationen, das Asset-Tag und die Berechtigung, am Cluster teilzunehmen.

.Über diese Aufgabe
Die Berechtigung eines Node, um am Cluster teilzunehmen, kann auf der erweiterten Berechtigungsebene mithilfe von geändert werden `–eligibility` Parameter von `system node modify` Oder `cluster modify` Befehl. Wenn Sie die Berechtigung eines Node auf festlegen `false`, Der Knoten wird im Cluster inaktiv.

[NOTE]
====
Sie können die Node-Berechtigung nicht lokal ändern. Er muss von einem anderen Node geändert werden. Auch bei einer Cluster-HA-Konfiguration kann die Node-eligility nicht geändert werden.

====
[NOTE]
====
Sie sollten vermeiden, die Berechtigung eines Node auf einzustellen `false`, Mit Ausnahme von Situationen wie Wiederherstellen der Node-Konfiguration oder verlängerte Node-Wartung. DER SAN- und NAS-Datenzugriff auf den Node kann davon betroffen sein, wenn der Node nicht verfügbar ist.

====
.Schritte
. Verwenden Sie die `system node modify` Befehl zum Ändern der Attribute eines Node.


.Beispiel zum Ändern von Node-Attributen
Mit dem folgenden Befehl werden die Attribute des Node „`node1`“ geändert. Der Eigentümer des Knotens ist auf „`Joe Smith`“ eingestellt und die Asset-Tag-Nummer ist auf „`js1234`“ eingestellt:

[listing]
----
cluster1::> system node modify -node node1 -owner "Joe Smith" -assettag js1234
----