---
permalink: system-admin/node-cluster-config-backed-up-automatically-concept.html 
sidebar: sidebar 
keywords: node, cluster, configuration, backup, up, automatically 
summary: Drei separate Zeitpläne erstellen automatisch Backup-Dateien für die Cluster- und Node-Konfiguration und replizieren sie auf den Nodes im Cluster. 
---
= Erfahren Sie mehr über die Planung von Backups von ONTAP-Cluster- und Node-Konfigurationsdateien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Drei separate Zeitpläne erstellen automatisch Backup-Dateien für die Cluster- und Node-Konfiguration und replizieren sie auf den Nodes im Cluster.

Die Backup-Dateien der Konfiguration werden automatisch gemäß den folgenden Zeitplänen erstellt:

* Alle 8 Stunden
* Täglich
* Wöchentlich


Zu jeder dieser Zeiten wird auf jedem gesunden Node im Cluster eine Backup-Datei für die Node-Konfiguration erstellt. Alle Backup-Dateien der Node-Konfiguration werden dann in einer Backup-Datei mit einer einzelnen Cluster-Konfiguration zusammen mit der replizierten Cluster-Konfiguration erfasst und auf einem oder mehreren Nodes im Cluster gespeichert.
