---
permalink: system-admin/online-help-at-sp-bmc-cli-task.html 
sidebar: sidebar 
keywords: online, help, sp, bmc, cli, command 
summary: In der Online-Hilfe werden die SP/BMC CLI-Befehle und -Optionen angezeigt. 
---
= Verwenden Sie die Online-Hilfe von SP/BMC CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In der Online-Hilfe werden die SP/BMC CLI-Befehle und -Optionen angezeigt.

.Über diese Aufgabe
Diese Aufgabe gilt sowohl für den SP als auch für den BMC.

.Schritte
. Geben Sie zum Anzeigen von Hiltinformationen für die SP/BMC-Befehle Folgendes ein:
+
|===
| Um auf die SP-Hilfe zuzugreifen... | Um auf die BMC-Hilfe zuzugreifen... 


 a| 
Geben Sie `help` an der SP-Eingabeaufforderung ein.
 a| 
Geben Sie `system` an der BMC-Eingabeaufforderung ein.

|===
+
Das folgende Beispiel zeigt die SP CLI Online-Hilfe.

+
[listing]
----
SP> help
date - print date and time
exit - exit from the SP command line interface
events - print system events and event information
help - print command help
priv - show and set user mode
sp - commands to control the SP
system - commands to control the system
version - print SP version
----
+
Das folgende Beispiel zeigt die BMC CLI Online-Hilfe.

+
[listing]
----
BMC> system
system acp - acp related commands
system battery - battery related commands
system console - connect to the system console
system core - dump the system core and reset
system cpld - cpld commands
system log - print system console logs
system power - commands controlling system power
system reset - reset the system using the selected firmware
system sensors - print environmental sensors status
system service-event - print service-event status
system fru - fru related commands
system watchdog - system watchdog commands

BMC>
----
. Um Hilfeinformationen für die Option eines Befehls „SP/BMC `help`“ anzuzeigen, geben Sie vor oder nach dem Befehl „SP/BMC“ ein.
+
Im folgenden Beispiel wird die SP-CLI-Online-Hilfe für den `events` Befehl SP angezeigt.

+
[listing]
----
SP> help events
events all - print all system events
events info - print system event log information
events newest - print newest system events
events oldest - print oldest system events
events search - search for and print system events
----
+
Im folgenden Beispiel wird die BMC-CLI-Online-Hilfe für den `system power` Befehl BMC angezeigt.

+
[listing]
----
BMC> system power help
system power cycle - power the system off, then on
system power off - power the system off
system power on - power the system on
system power status - print system power status

BMC>
----

