---
permalink: system-admin/ontap-implements-audit-logging-concept.html 
sidebar: sidebar 
keywords: ontap, implement, audit, logging, management, autosupport, ems, messages, log, cli, web, browser 
summary: Die im Audit-Protokoll aufgezeichneten Managementaktivitäten sind Teil der AutoSupport-Standardberichte und bestimmte Protokollierungsaktivitäten werden in EMS-Nachrichten erfasst. Sie können das Auditprotokoll auch an die von Ihnen angegebenen Ziele weiterleiten und Audit-Log-Dateien über die CLI oder einen Webbrowser anzeigen. 
---
= So implementiert ONTAP Audit-Protokollierung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die im Audit-Protokoll aufgezeichneten Managementaktivitäten sind Teil der AutoSupport-Standardberichte und bestimmte Protokollierungsaktivitäten werden in EMS-Nachrichten erfasst. Sie können das Auditprotokoll auch an die von Ihnen angegebenen Ziele weiterleiten und Audit-Log-Dateien über die CLI oder einen Webbrowser anzeigen.

Ab ONTAP 9.11.1 können Sie den Inhalt des Revisionsprotokolls mithilfe von System Manager anzeigen.

Ab Version 9.12.1 sind Audit-Protokolle manipulationssicher. Das heißt, jede Protokolldatei, die eine Admin-Aktion aufzeichnet, kann selbst in Cluster-Administratorkonten nicht geändert oder gelöscht werden.

ONTAP protokolliert Managementaktivitäten, die auf dem Cluster ausgeführt werden, beispielsweise eine Anfrage, den Benutzer, der die Anforderung ausgelöst hat, die Zugriffsmethode des Benutzers und die Zeit der Anfrage.

Die Management-Aktivitäten können eine der folgenden Arten sein:

* LEGEN Sie Anforderungen FEST, die in der Regel für Befehle oder Vorgänge ohne Anzeige gelten
+
** Diese Anfragen werden ausgegeben, wenn Sie ein ausführen `create`, `modify`, Oder `delete` Befehl zum Beispiel.
** Festgelegte Anforderungen werden standardmäßig protokolliert.


* ABRUFEN von Anforderungen, die Informationen abrufen und in der Managementoberfläche anzeigen
+
** Diese Anfragen werden ausgegeben, wenn Sie ein ausführen `show` Befehl zum Beispiel.
** GET Requests werden nicht standardmäßig protokolliert, Sie können jedoch kontrollieren, ob GET Requests from the ONTAP CLI gesendet WERDEN (`-cliget`) Oder von den ONTAP APIs (`-ontapiget`) Sind in der Datei protokolliert.




ONTAP zeichnet die Managementaktivitäten in auf `/mroot/etc/log/mlog/audit.log` Datei eines Node. Befehle aus den drei Shells für CLI-Befehle - die clustershell, die nodeshell, und die nicht-interaktive Systemshell (interaktive Systemshell-Befehle werden nicht protokolliert)- sowie API-Befehle werden hier protokolliert. In den Audit-Protokollen werden Zeitstempel verwendet, um anzuzeigen, ob alle Nodes in einem Cluster Zeit synchronisiert sind.

Der `audit.log` Die Datei wird vom AutoSupport-Tool an die angegebenen Empfänger gesendet. Sie können den Inhalt auch sicher an angegebene externe Ziele weiterleiten, z. B. an einen Splunk oder Syslog-Server.

Der `audit.log` Die Datei wird täglich gedreht. Die Rotation tritt auch auf, wenn sie 100 MB groß erreicht, und die vorherigen 48 Kopien erhalten bleiben (mit maximal 49 Dateien). Wenn die Audit-Datei ihre tägliche Rotation durchführt, wird keine EMS-Nachricht erzeugt. Wenn die Überwachungsdatei sich dreht, weil ihre Dateigröße überschritten wird, wird eine EMS-Nachricht generiert.
