---
permalink: system-admin/receive-system-health-alerts-automatic-task.html 
sidebar: sidebar 
keywords: receive, system, health, alert, automatically, system, show, command, ems, event, management, monito 
summary: Sie können Systemzustandswarnungen manuell mit dem Befehl „system health alert show“ anzeigen. Sie sollten jedoch bestimmte Meldungen des Event Management System abonnieren, um automatisch Benachrichtigungen zu erhalten, wenn ein Health Monitor eine Warnung generiert. 
---
= ONTAP-Systemzustandswarnungen automatisch empfangen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Systemzustandswarnungen manuell mit dem  `system health alert show` Befehl anzeigen. Es empfiehlt sich jedoch, bestimmte Meldungen des Event Management System (EMS) zu abonnieren, um automatisch Benachrichtigungen zu erhalten, wenn ein Systemzustandsmonitor eine Warnung generiert.

.Über diese Aufgabe
Das folgende Verfahren zeigt, wie Benachrichtigungen für alle hm.alert.raised Meldungen und alle hm.alert.cleared Meldungen eingerichtet werden.

Alle hm.alert.raised-Meldungen und alle hm.alert.cleared-Meldungen enthalten einen SNMP-Trap. Die Namen der SNMP-Traps lauten `HealthMonitorAlertRaised` und `HealthMonitorAlertCleared`.

Weitere Informationen zu  `system health alert show` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/system-health-alert-show.html["ONTAP-Befehlsreferenz"^].

.Schritte
. Mit dem  `event destination create` Befehl wird das Ziel definiert, an das die EMS-Nachrichten gesendet werden sollen.
+
[listing]
----
cluster1::> event destination create -name health_alerts -mail admin@example.com
----
+
Weitere Informationen zu  `event destination create` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=event+destination+create["ONTAP-Befehlsreferenz"^].

. Mit dem  `event route add-destinations` Befehl werden die  `hm.alert.raised` Nachricht und die  `hm.alert.cleared` Nachricht an ein Ziel weitergeleitet.
+
[listing]
----
cluster1::> event route add-destinations -messagename hm.alert* -destinations health_alerts
----
+
Weitere Informationen zu  `event route add-destinations` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=event+route+add-destinations["ONTAP-Befehlsreferenz"^].



.Verwandte Informationen
* link:../networking/networking_reference.html["Das ONTAP Netzwerk lässt sich mit System Manager visualisieren."]
* link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_SNMP_monitoring_on_DATA_ONTAP["Konfiguration der SNMP-Überwachung auf DATA ONTAP"^]

