---
permalink: system-admin/relocate-root-volumes-new-aggregates-task.html 
sidebar: sidebar 
keywords: relocate, root, volume, new, aggregates, disks, disruption, replacement 
summary: Beim Root-Austauschverfahren wird das aktuelle Root-Aggregat ohne Unterbrechung zu einem anderen Festplattensatz migriert. 
---
= Verschieben von Root-Volumes in neue Aggregate
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Beim Root-Austauschverfahren wird das aktuelle Root-Aggregat ohne Unterbrechung zu einem anderen Festplattensatz migriert.

.Über diese Aufgabe
Storage-Failover muss aktiviert sein, um Root-Volumes zu verschieben. Sie können das verwenden `storage failover modify -node _nodename_ -enable true` Befehl zum Aktivieren des Failovers.

Sie können den Speicherort des Root-Volumes in ein neues Aggregat in den folgenden Szenarien ändern:

* Wenn sich die Wurzelaggregate nicht auf der Festplatte befinden, die Sie bevorzugen
* Wenn Sie die mit dem Node verbundenen Festplatten neu anordnen möchten
* Wenn Sie einen Shelf-Austausch der EOS Platten-Shelves durchführen


.Schritte
. Legen Sie die Berechtigungsebene auf erweitert fest:
+
`*set privilege advanced*`

. Verschieben des Root-Aggregats:
+
`*system node migrate-root -node _nodename_ -disklist _disklist_ -raid-type _raid-type_*`

+
** *-Node*
+
Gibt den Knoten an, der das Root-Aggregat besitzt, das Sie migrieren möchten.

** *-disklist*
+
Gibt die Liste der Festplatten an, auf denen das neue Root-Aggregat erstellt wird. Alle Festplatten müssen Ersatzteile und Eigentum des gleichen Knotens sein. Die Mindestanzahl der benötigten Festplatten hängt vom RAID-Typ ab.

** *-RAID-Typ*
+
Gibt den RAID-Typ des Root-Aggregats an. Der Standardwert ist `raid-dp`.



. Überwachen des Fortschritts des Jobs:
+
`*job show -id _jobid_ -instance*`



.Ergebnisse
Wenn alle Vorprüfungen erfolgreich sind, startet der Befehl einen Ersatzauftrag für das Root-Volume und wird beendet. Erwarten Sie, dass der Node neu gestartet wird.
