---
permalink: system-admin/remove-nodes-cluster-concept.html 
sidebar: sidebar 
keywords: remove, node, cluster, failover, partner, erase, inaccessible 
summary: Sie können unerwünschte Knoten aus einem Cluster entfernen, jeweils einen nach dem anderen. Nach der Entfernung eines Knotens muss auch dessen Failover-Partner entfernt werden. Wenn ein Knoten entfernt wird, sind dessen Daten nicht mehr zugänglich oder werden gelöscht. 
---
= Knoten aus einem ONTAP Cluster entfernen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können unerwünschte Knoten aus einem Cluster entfernen, jeweils einen nach dem anderen. Nach der Entfernung eines Knotens muss auch dessen Failover-Partner entfernt werden. Wenn ein Knoten entfernt wird, sind dessen Daten nicht mehr zugänglich oder werden gelöscht.

.Bevor Sie beginnen
Bevor Sie Knoten aus dem Cluster entfernen, müssen folgende Bedingungen erfüllt sein:

* Mehr als die Hälfte der Knoten im Cluster muss fehlerfrei sein.
* Sämtliche Daten, Volumes und Nicht-Root-Aggregate müssen vom Node verschoben oder entfernt werden.
+
** Alle Daten auf dem Node, den Sie entfernen möchten, müssen evakuiert worden sein. Dies kann link:../encryption-at-rest/secure-purge-data-encrypted-volume-concept.html["Daten aus einem verschlüsselten Volume entfernen"] umfassen.
** Alle Nicht-Root-Volumes wurden link:../volumes/move-volume-task.html["verschoben"] aus Aggregaten entfernt, die dem Node gehören.
** Alle Nicht-Root-Aggregate wurden link:../disks-aggregates/commands-manage-aggregates-reference.html["gelöscht"] vom Node entfernt.


* Alle LIFs und VLANs wurden vom Node verschoben oder entfernt.
+
** Daten-LIFs wurden link:../networking/delete_a_lif.html["gelöscht"] oder link:../networking/migrate_a_lif.html["verschoben"] vom Node entfernt.
** Die Cluster-Management-LIFs wurden link:../networking/migrate_a_lif.html["verschoben"] vom Node entfernt und die Home-Ports geändert.
** Alle Intercluster-LIFs wurden link:../networking/delete_a_lif.html["Entfernung"]. Beim Entfernen von Intercluster-LIFs wird eine Warnung angezeigt, die ignoriert werden kann.
** Alle VLANs auf dem Knoten wurden link:../networking/configure_vlans_over_physical_ports.html#delete-a-vlan["gelöscht"].


* Der Knoten ist an keiner Failover-Beziehung beteiligt.
+
** Storage-Failover wurde für den Knoten link:../high-availability/ha_commands_for_enabling_and_disabling_storage_failover.html["deaktiviert"] aktiviert.
** Alle LIF-Failover-Regeln wurden link:../networking/commands_for_managing_failover_groups_and_policies.html["modifiziert"] zur Entfernung von Ports auf dem Node angepasst.


* Wenn der Knoten über Federal Information Processing Standards (FIPS) Datenträger oder selbstverschlüsselnde Datenträger (SEDs) verfügt, link:../encryption-at-rest/return-seds-unprotected-mode-task.html["Die Festplattenverschlüsselung wurde entfernt"] indem die Datenträger in den ungeschützten Modus zurückversetzt werden.
+
** Möglicherweise besteht auch Interesse daran, link:../encryption-at-rest/sanitize-fips-drive-sed-task.html["FIPS-Laufwerke oder SEDs löschen"].


* Wenn sich auf dem zu entfernenden Knoten LUNs befinden, sollten Sie link:../san-admin/modify-slm-reporting-nodes-task.html["die Liste der Reporting-Nodes der Selective LUN Map (SLM) ändern"] entfernen, bevor Sie den Knoten entfernen.
+
Wenn Sie den Node und seinen HA-Partner nicht aus der SLM Reporting-Nodes-Liste entfernen, kann der Zugriff auf die zuvor auf dem Node befindlichen LUNs verloren gehen, selbst wenn die Volumes, die die LUNs enthalten, auf einen anderen Node verschoben wurden.



Es wird empfohlen, eine AutoSupport-Nachricht zu senden, um den NetApp technischen Support darüber zu informieren, dass die Entfernung eines Node im Gange ist.


IMPORTANT: Operationen wie  `cluster remove-node`,  `cluster unjoin` und  `node rename` sollten nicht durchgeführt werden, wenn ein automatisiertes ONTAP Upgrade im Gange ist.

.Über diese Aufgabe
* Wenn Sie einen Cluster mit gemischten Versionen betreiben, kann der letzte Node mit niedriger Version mithilfe eines der erweiterten Berechtigungsbefehle ab ONTAP 9.3 entfernt werden:
+
** ONTAP 9.3: `cluster unjoin -skip-last-low-version-node-check`
** ONTAP 9.4 und höher: `cluster remove-node -skip-last-low-version-node-check`


* Wenn Sie zwei Knoten aus einem vier-Knoten-Cluster entfernen, wird Cluster HA automatisch auf den beiden verbleibenden Knoten aktiviert.


[NOTE]
====
Alle System- und Benutzerdaten von allen mit dem Knoten verbundenen Festplatten müssen für die Benutzer unzugänglich gemacht werden, bevor ein Knoten aus dem Cluster entfernt wird.

Falls ein Knoten fälschlicherweise aus einem Cluster entfernt wurde, wenden Sie sich an den NetApp Support, um Unterstützung bei den Wiederherstellungsoptionen zu erhalten.

====
[[disable-ha]]
.Schritte
. Ändern Sie die Berechtigungsstufe auf „advanced“:
+
[source, cli]
----
set -privilege advanced
----
. Identifizieren Sie den Knoten im Cluster, der epsilon hat:
+
[source, cli]
----
cluster show
----
+
Im folgenden Beispiel hält "node0" derzeit epsilon:

+
[listing]
----
cluster::*>
Node                 Health  Eligibility  Epsilon
-------------------- ------- ------------ ------------
node0                true    true         true
node1                true    true         false
node2                true    true         false
node3                true    true         false
----
. [[epsilon-true]]Wenn der Knoten, den Sie entfernen, Epsilon enthält:
+
.. Verschiebe epsilon von dem Knoten, den du entfernst:
+
[source, cli]
----
cluster modify -node <name_of_node_to_be_removed> -epsilon false
----
.. Verschieben Sie epsilon auf einen Knoten, den Sie nicht entfernen:
+
[source, cli]
----
cluster modify -node <node_name> -epsilon true
----


. Aktueller primärer Knoten identifizieren:
+
[source, cli]
----
cluster ring show
----
+
Der primäre Knoten ist der Knoten, der Prozesse wie  `mgmt`,  `vldb`,  `vifmgr`,  `bcomd` und  `crs` enthält.

. Falls der zu entfernende Knoten der aktuelle primäre Knoten ist, kann ein anderer Knoten im Cluster als primärer Knoten gewählt werden:
+
.. Den aktuellen primären Knoten für die Teilnahme am Cluster als nicht berechtigt markieren:
+
[source, cli]
----
cluster modify -node <node_name> -eligibility false
----
+
Der Knoten wird als fehlerhaft markiert, bis seine Eignung wiederhergestellt ist. Wenn der primäre Knoten seine Eignung verliert, wählt das Cluster-Quorum einen der verbleibenden Knoten als neuen primären Knoten.

+
[NOTE]
====
Wenn Sie diesen Schritt auf dem ersten Knoten eines HA-Paares durchführen, sollten Sie nur diesen Knoten als nicht geeignet markieren. Ändern Sie nicht den Status des HA-Partners.

Wird der Partnerknoten als neuer primärer Knoten ausgewählt, muss vor seiner Deaktivierung überprüft werden, ob er Epsilon enthält. Wenn der Partnerknoten Epsilon enthält, muss Epsilon auf einen anderen, im Cluster verbleibenden Knoten verschoben werden, bevor er deaktiviert wird. Dies geschieht, wenn diese Schritte zum Entfernen des Partnerknotens wiederholt werden.

====
.. Den vorherigen primären Knoten wieder für die Teilnahme am Cluster berechtigen:
+
[source, cli]
----
cluster modify -node <node_name> -eligibility true
----


. Melden Sie sich bei der Remote-Knotenverwaltungs-LIF oder der Clusterverwaltungs-LIF auf einem Knoten an, den Sie nicht aus dem Cluster entfernen.
. Entfernen Sie die Knoten aus dem Cluster:
+
|===
| Für diese ONTAP Version... | Verwenden Sie diesen Befehl... 


 a| 
ONTAP 9.3
 a| 
[source, cli]
----
cluster unjoin
----


 a| 
ONTAP 9.4 und höher
 a| 
Mit Node-Name:

[source, cli]
----
cluster remove-node -node <node_name>
----
Mit Node-IP:

[source, cli]
----
cluster remove-node -cluster_ip <node_ip>
----
|===
+
Wenn Sie einen Cluster mit gemischten Versionen haben und den letzten Knoten mit der niedrigeren Version entfernen, sollte der  `-skip-last-low-version-node-check` Parameter bei diesen Befehlen verwendet werden.

+
Das System informiert Sie über Folgendes:

+
** Außerdem ist der Failover-Partner des Knotens aus dem Cluster zu entfernen.
** Nachdem der Node entfernt wurde und bevor er wieder einem Cluster beitreten kann, müssen Sie die Bootmenüoption *(4) Clean configuration and initialize all disks* oder die Option *(9) Configure Advanced Drive Partitioning* verwenden, um die Konfiguration des Node zu löschen und alle Datenträger zu initialisieren.
+
Eine Fehlermeldung wird generiert, wenn Bedingungen vorliegen, die Sie vor dem Entfernen des Knotens beheben müssen. Die Meldung kann beispielsweise darauf hinweisen, dass der Knoten gemeinsam genutzte Ressourcen hat, die entfernt werden müssen, oder dass sich der Knoten in einer Cluster HA-Konfiguration oder einer Storage Failover-Konfiguration befindet, die deaktiviert werden muss.

+
Wenn der Knoten der primäre Quorumknoten ist, verliert der Cluster kurzzeitig das Quorum und stellt es anschließend wieder her. Dieser Quorumverlust ist vorübergehend und hat keine Auswirkungen auf Datenoperationen.



. Wenn eine Fehlermeldung auf Fehlerbedingungen hinweist, sollten diese Bedingungen behoben und der  `cluster remove-node` oder  `cluster unjoin` Befehl erneut ausgeführt werden.
+
Der Knoten startet nach erfolgreicher Entfernung aus dem Cluster automatisch neu.

. Wenn der Node für einen anderen Zweck verwendet wird, werden die Node-Konfiguration gelöscht und alle Festplatten initialisiert:
+
.. Während des Bootvorgangs Strg+C drücken, um das Bootmenü anzuzeigen, wenn dazu aufgefordert wird.
.. Wählen Sie die Bootmenü-Option *(4) Konfiguration bereinigen und alle Festplatten initialisieren*.


. [[return-admin]]Zurück zur Administrator-Berechtigungsstufe:
+
[source, cli]
----
set -privilege admin
----
. Wiederholen Sie die Schritte <<disable-ha,1>> bis <<return-admin,9>>, um den Failover-Partner aus dem Cluster zu entfernen.


.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/cluster-remove-node.html["cluster remove-node"^]

