---
permalink: system-admin/respond-degraded-system-health-task.html 
sidebar: sidebar 
keywords: respond, degraded, system, health, status, show, alerts, corrective, probable, cause 
summary: Wenn der Systemzustand beeinträchtigt ist, können Warnmeldungen angezeigt, die wahrscheinliche Ursache und Korrekturmaßnahmen eingesehen, Informationen zum beeinträchtigten Teilsystem angezeigt und das Problem behoben werden. Unterdrückte Warnmeldungen werden ebenfalls angezeigt, sodass sie geändert werden können und ersichtlich ist, ob sie bestätigt wurden. 
---
= Auf eine Beeinträchtigung des ONTAP Systemzustands reagieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn der Systemzustand beeinträchtigt ist, lassen sich Warnmeldungen anzeigen, Informationen zur wahrscheinlichen Ursache und zu Korrekturmaßnahmen abrufen, Details zum beeinträchtigten Teilsystem einsehen und das Problem beheben. Unterdrückte Warnmeldungen werden ebenfalls angezeigt, sodass sie geändert werden können und ersichtlich ist, ob sie bestätigt wurden.

.Über diese Aufgabe
Es lässt sich feststellen, dass eine Warnung ausgelöst wurde, indem eine AutoSupport-Nachricht oder ein EMS-Ereignis angezeigt wird oder indem die  `system health` Befehle verwendet werden.

.Schritte
. Mit dem  `system health alert show`Befehl lassen sich die Warnmeldungen anzeigen, die die Systemintegrität beeinträchtigen.
. Die wahrscheinliche Ursache, die möglichen Auswirkungen und die Korrekturmaßnahmen der Warnmeldung geben Aufschluss darüber, ob das Problem selbst gelöst werden kann oder weitere Informationen erforderlich sind.
. Falls Sie weitere Informationen benötigen, verwenden Sie den  `system health alert show -instance` Befehl, um zusätzliche Informationen zu dieser Warnung anzuzeigen.
. Verwenden Sie den  `system health alert modify` Befehl mit dem  `-acknowledge` Parameter, um anzugeben, dass Sie an einer bestimmten Warnung arbeiten.
. Korrekturmaßnahme ergreifen, um das im  `Corrective Actions`-Feld des Warnhinweises beschriebene Problem zu beheben.
+
Zu den Korrekturmaßnahmen könnte ein Neustart des Systems gehören.

+
Sobald das Problem behoben ist, wird die Warnung automatisch gelöscht. Wenn für das Subsystem keine weiteren Warnungen vorliegen, ändert sich dessen Zustand auf  `OK`. Wenn der Zustand aller Subsysteme in Ordnung ist, ändert sich der Gesamtsystemzustand auf  `OK`.

. Mit dem  `system health status show`Befehl lässt sich bestätigen, dass der Systemzustand  `OK` ist.
+
Falls der Systemzustand nicht  `OK` ist, sollte dieses Verfahren wiederholt werden.



.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/system-health-alert-modify.html["Systemzustandswarnung ändern"^]

