---
permalink: system-admin/restore-node-config-backup-file-task.html 
sidebar: sidebar 
keywords: restore, node, configuration, backup, file, recovering 
summary: Sie stellen die Node-Konfiguration mithilfe der Backup-Datei der Konfiguration wieder her, die Sie für den Wiederherstellungsknoten identifiziert und bereitgestellt haben. 
---
= Stellen Sie einen Node mithilfe der Backup-Datei für die ONTAP-Node-Konfiguration wieder her
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie stellen die Node-Konfiguration mithilfe der Backup-Datei der Konfiguration wieder her, die Sie für den Wiederherstellungsknoten identifiziert und bereitgestellt haben.

.Über diese Aufgabe
Sie sollten diese Aufgabe nur durchführen, um nach einem Notfall, der zum Verlust der lokalen Konfigurationsdateien des Knotens führte, wiederherzustellen.

.Schritte
. Ändern Sie die erweiterte Berechtigungsebene:
+
`set -privilege advanced`

. Wenn sich der Node in einem ordnungsgemäßen Zustand `cluster modify` `-node` `-eligibility` befindet, verwenden Sie auf der erweiterten Berechtigungsebene eines anderen Node den Befehl mit den Parametern und, um ihn als nicht zulässig zu markieren und ihn vom Cluster zu isolieren.
+
Wenn der Knoten nicht ordnungsgemäß ist, sollten Sie diesen Schritt überspringen.

+
In diesem Beispiel wird node2 so geändert, dass er nicht zur Teilnahme am Cluster berechtigt ist, damit seine Konfiguration wiederhergestellt werden kann:

+
[listing]
----
cluster1::*> cluster modify -node node2 -eligibility false
----
+
Erfahren Sie mehr über `cluster modify` in der link:https://docs.netapp.com/us-en/ontap-cli/cluster-modify.html["ONTAP-Befehlsreferenz"^].

. Verwenden Sie den `system configuration recovery node restore` Befehl auf der erweiterten Berechtigungsebene, um die Konfiguration des Node aus einer Backup-Konfigurationsdatei wiederherzustellen.
+
Wenn der Node seine Identität einschließlich seines Namens verloren `-nodename-in-backup` hat, sollten Sie den Node-Namen in der Konfigurations-Backup-Datei mit dem Parameter angeben.

+
In diesem Beispiel wird die Konfiguration des Node mithilfe einer der auf dem Node gespeicherten Backup-Konfigurationsdateien wiederhergestellt:

+
[listing]
----
cluster1::*> system configuration recovery node restore -backup cluster1.8hour.2011-02-22.18_15_00.7z

Warning: This command overwrites local configuration files with
         files contained in the specified backup file. Use this
         command only to recover from a disaster that resulted
         in the loss of the local configuration files.
         The node will reboot after restoring the local configuration.
Do you want to continue? {y|n}: y
----
+
Die Konfiguration wird wiederhergestellt und der Node wird neu gebootet.

. Wenn Sie den Node als nicht zulässig markiert haben, verwenden Sie `system configuration recovery cluster sync` den Befehl, um den Node als berechtigt zu markieren und ihn mit dem Cluster zu synchronisieren.
. Wenn Sie in einer SAN-Umgebung arbeiten, verwenden Sie den `system node reboot` Befehl, um den Node neu zu booten und das SAN-Quorum wiederherzustellen.


.Nachdem Sie fertig sind
Wenn Sie das Cluster zuvor neu erstellt haben und wenn Sie die Node-Konfiguration mithilfe einer Backup-Konfigurationsdatei wiederherstellen, die vor der erneuten Erstellung dieses Clusters erstellt wurde, müssen Sie das Cluster erneut erstellen.
