---
permalink: system-admin/restore-cluster-config-from-existing-task.html 
sidebar: sidebar 
keywords: restore, cluster, configuration, existing, configuration, failure, recovering, node, rejoin, cluster 
summary: Um nach einem Clusterausfall eine Clusterkonfiguration aus einer bestehenden Konfiguration wiederherzustellen, wird der Cluster mithilfe der ausgewählten und dem wiederherstellenden Node zur Verfügung gestellten Clusterkonfiguration neu erstellt, und anschließend wird jeder zusätzliche Node dem neuen Cluster wieder hinzugefügt. 
---
= Einen Cluster mithilfe der ONTAP Clusterkonfigurations-Sicherungsdatei wiederherstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um nach einem Clusterausfall eine Clusterkonfiguration aus einer bestehenden Konfiguration wiederherzustellen, wird der Cluster mithilfe der ausgewählten und dem wiederherstellenden Node zur Verfügung gestellten Clusterkonfiguration neu erstellt, und anschließend wird jeder zusätzliche Node dem neuen Cluster wieder hinzugefügt.

.Über diese Aufgabe
Diese Aufgabe sollte nur durchgeführt werden, um sich von einem Desaster zu erholen, das zum Verlust der Cluster-Konfiguration geführt hat.

[NOTE]
====
Wenn Sie den Cluster aus einer Konfigurationssicherungsdatei neu erstellen, muss der technische Support kontaktiert werden, um etwaige Diskrepanzen zwischen der Konfigurationssicherungsdatei und der im Cluster vorhandenen Konfiguration zu klären.

Wenn Sie den Cluster aus einer Konfigurationssicherungsdatei wiederherstellen, gehen alle seit der Sicherung vorgenommenen Konfigurationsänderungen verloren. Nach der Wiederherstellung müssen alle Abweichungen zwischen der Konfigurationssicherungsdatei und der aktuellen Konfiguration behoben werden. Siehe link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/ONTAP_Configuration_Backup_Resolution_Guide["NetApp Knowledge Base: ONTAP Konfigurationssicherungs-Resolution Guide"^] für Hinweise zur Fehlerbehebung.

====
.Schritte
. Storage-Failover für jedes HA-Paar deaktivieren:
+
`*storage failover modify -node _node_name_ -enabled false*`

+
Das Speicher-Failover muss nur einmal pro HA-Paar deaktiviert werden. Wenn das Speicher-Failover für einen Knoten deaktiviert wird, ist es auch auf dem Partnerknoten deaktiviert.

. Jeden Knoten außer dem sich erholenden Knoten anhalten:
+
`*system node halt -node _node_name_ -reason "text"*`

+
[listing]
----
cluster1::*> system node halt -node node0 -reason "recovering cluster"

Warning: Are you sure you want to halt the node? {y|n}: y
----
. Stellen Sie die Berechtigungsstufe auf „Erweitert“ ein:
+
`*set -privilege advanced*`

. Auf dem wiederherstellenden Knoten kann der Cluster mit dem  `*system configuration recovery cluster recreate*` Befehl neu erstellt werden.
+
Dieses Beispiel erstellt das Cluster mithilfe der auf dem wiederherstellenden Node gespeicherten Konfigurationsinformationen neu:

+
[listing]
----
cluster1::*> configuration recovery cluster recreate -from node

Warning: This command will destroy your existing cluster. It will
         rebuild a new single-node cluster consisting of this node
         and its current configuration. This feature should only be
         used to recover from a disaster. Do not perform any other
         recovery operations while this operation is in progress.
Do you want to continue? {y|n}: y
----
+
Auf dem wiederherstellenden Node wird ein neuer Cluster erstellt.

. Wenn Sie den Cluster aus einer Konfigurationssicherungsdatei wiederherstellen, überprüfen Sie, ob die Clusterwiederherstellung noch läuft:
+
`*system configuration recovery cluster show*`

+
Sie müssen den Wiederherstellungsstatus des Clusters nicht überprüfen, wenn Sie den Cluster von einem fehlerfreien Node aus neu erstellen.

+
[listing]
----
cluster1::*> system configuration recovery cluster show
 Recovery Status: in-progress
 Is Recovery Status Persisted: false
----
. Jeder Node, der dem neu erstellten Cluster wieder beitreten muss, wird neu gestartet.
+
Die Knoten müssen einzeln neu gestartet werden.

. Für jeden Node, der dem neu erstellten Cluster hinzugefügt werden soll, ist Folgendes zu beachten:
+
.. Von einem fehlerfreien Node im neu erstellten Cluster aus erfolgt der erneute Beitritt des Ziel-Node:
+
`*system configuration recovery cluster rejoin -node _node_name_*`

+
Dieses Beispiel fügt den Ziel-Node "`node2`" dem neu erstellten Cluster wieder hinzu:

+
[listing]
----
cluster1::*> system configuration recovery cluster rejoin -node node2

Warning: This command will rejoin node "node2" into the local
         cluster, potentially overwriting critical cluster
         configuration files. This command should only be used
         to recover from a disaster. Do not perform any other
         recovery operations while this operation is in progress.
         This command will cause node "node2" to reboot.
Do you want to continue? {y|n}: y
----
+
Der Zielknoten startet neu und tritt anschließend dem Cluster bei.

.. Es sollte sichergestellt werden, dass der Zielknoten fehlerfrei funktioniert und ein Quorum mit den übrigen Knoten im Cluster gebildet wurde:
+
`*cluster show -eligibility true*`

+
Der Zielknoten muss dem neu erstellten Cluster wieder beitreten, bevor Sie einen anderen Knoten wieder beitreten können.

+
[listing]
----
cluster1::*> cluster show -eligibility true
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node0                true    true          false
node1                true    true          false
2 entries were displayed.
----


. Wenn Sie den Cluster aus einer Konfigurationssicherungsdatei neu erstellt haben, den Wiederherstellungsstatus auf „Abgeschlossen“ setzen:
+
`*system configuration recovery cluster modify -recovery-status complete*`

. Zurück zur Administrator-Privilegstufe:
+
`*set -privilege admin*`

. Besteht der Cluster nur aus zwei Knoten, kann der  `*cluster ha modify*` Befehl zum erneuten Aktivieren von Cluster-HA verwendet werden.
. Mit dem  `*storage failover modify*`Befehl lässt sich das Storage-Failover für jedes HA-Paar wieder aktivieren.


.Nachdem Sie fertig sind
Wenn der Cluster SnapMirror Peer-Beziehungen aufweist, müssen diese Beziehungen ebenfalls neu erstellt werden. Weitere Informationen finden sich unter link:../data-protection/index.html["Datensicherung"].

.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP-Befehlsreferenz"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-failover-modify.html["storage failover modify"^]

