---
permalink: system-admin/set-display-preferences-task.html 
sidebar: sidebar 
keywords: set, display, preferences, cli, session, set, rows 
summary: Sie können die Anzeigeeinstellungen für eine CLI-Sitzung mithilfe des Befehls Set und Zeilen festlegen. Die festgelegten Einstellungen gelten nur für die Sitzung, in der Sie sich befinden. Sie sind nicht persistent über Sitzungen. 
---
= Legen Sie die Anzeigeeinstellungen in der CLI fest
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Anzeigeeinstellungen für eine CLI-Sitzung mithilfe der festlegen `set` Befehl und `rows` Befehl. Die festgelegten Einstellungen gelten nur für die Sitzung, in der Sie sich befinden. Sie sind nicht persistent über Sitzungen.

Sie können die folgenden CLI-Anzeigeeinstellungen festlegen:

* Die Berechtigungsebene der Befehlssitzung
* Gibt an, ob Bestätigungen für möglicherweise zu störenden Befehle ausgegeben werden
* Ob `show` Befehle zeigen alle Felder an
* Das Zeichen oder Zeichen, das als Feldtrennzeichen verwendet werden soll
* Standardeinheit bei der Meldung von Datengrößen
* Die Anzahl der Zeilen, die in der aktuellen CLI-Sitzung angezeigt werden, bevor die Schnittstelle die Ausgabe unterbricht
+
Wenn die bevorzugte Anzahl von Zeilen nicht angegeben wird, wird sie automatisch auf der Grundlage der tatsächlichen Höhe des Terminals angepasst. Wenn die tatsächliche Höhe nicht definiert ist, ist die Standardanzahl der Zeilen 24.

* Die standardmäßige Storage Virtual Machine (SVM) oder Node
* Ob ein fortgesetzte Befehl beendet werden soll, wenn ein Fehler auftritt


.Schritte
. Verwenden Sie zum Festlegen von CLI-Anzeigeeinstellungen den `set` Befehl.
+
Um die Anzahl der Zeilen festzulegen, die in der aktuellen CLI-Sitzung angezeigt werden, können Sie auch die verwenden `rows` Befehl.

+
Weitere Informationen finden Sie auf den man-Pages für die `set` Befehl und `rows` Befehl.



Im folgenden Beispiel wird ein Komma als Feldtrennzeichen festgelegt `GB` Als Standardeinheit für die Datengröße und setzt die Anzahl der Zeilen auf 50:

[listing]
----
cluster1::> set -showseparator "," -units GB
cluster1::> rows 50
----