---
sidebar: sidebar 
permalink: system-admin/setup-autosupport-task.html 
keywords: autosupport, set up autosupport, technical support 
summary: Konfigurieren Sie einen ONTAP Cluster, damit AutoSupport-Nachrichten an den technischen Support von NetApp gesendet werden, und senden Sie E-Mail-Kopien an den internen Support. 
---
= AutoSupport einrichten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen ONTAP Cluster so konfigurieren, dass AutoSupport-Nachrichten an den technischen Support von NetApp gesendet werden, und E-Mail-Kopien an den internen Support senden. Im Rahmen dieser Funktion können Sie die Konfiguration auch testen, bevor Sie sie in einer Produktionsumgebung verwenden.

.Über diese Aufgabe
Ab ONTAP 9.5 können Sie AutoSupport für alle Nodes eines Clusters gleichzeitig aktivieren und konfigurieren. Wenn ein neuer Node dem Cluster Beitritt, übernimmt der Node automatisch die gleiche AutoSupport-Konfiguration. Dies wird vom Umfang des CLI-Befehls unterstützt `system node autosupport modify` Cluster-Ebene. Der `-node` Die Befehlsoption wird aus Gründen der Abwärtskompatibilität beibehalten, wird jedoch ignoriert.


NOTE: In ONTAP 9.4 und älteren Versionen ist der Befehl `system node autosupport modify` Ist für jeden Knoten spezifisch. Wenn auf dem Cluster ONTAP 9.4 oder eine frühere Version ausgeführt wird, müssen Sie auf jedem Node im Cluster AutoSupport aktivieren und konfigurieren.

.Bevor Sie beginnen
Die empfohlene Transportkonfiguration für die Übertragung von AutoSupport Meldungen an NetApp ist HTTPS (HTTP mit TLS). Diese Option bietet die robustesten Funktionen und die beste Sicherheit.

Prüfen link:requirements-autosupport-reference.html["Bereiten Sie die Verwendung von AutoSupport vor"] Weitere Informationen finden Sie vor dem Konfigurieren des ONTAP-Clusters.

.Schritte
. Vergewissern Sie sich, dass AutoSupport aktiviert ist:
+
[listing]
----
system node autosupport modify -state enable
----
. Wenn der technische Support von NetApp AutoSupport Meldungen erhalten soll, verwenden Sie den folgenden Befehl:
+
[listing]
----
system node autosupport modify -support enable
----
+
Sie müssen diese Option aktivieren, wenn Sie AutoSupport aktivieren möchten, um mit AutoSupport OnDemand zu arbeiten, oder wenn Sie große Dateien wie Core Dump- und Performance-Archivdateien auf technischen Support oder eine angegebene URL hochladen möchten.

. Wenn der technische Support von NetApp den Empfang von AutoSupport Meldungen ermöglicht, geben Sie das für die Meldungen zu verwendende Transportprotokoll an.
+
Sie können aus folgenden Optionen wählen:

+
|===


| Ihr Ziel ist | Stellen Sie dann die folgenden Parameter des ein `system node autosupport modify` Befehl... 


 a| 
Verwenden Sie das HTTPS-Standardprotokoll
 a| 
.. Einstellen `-transport` Bis `https`.
.. Wenn Sie einen Proxy verwenden, legen Sie fest `-proxy-url` An die URL Ihres Proxy. Diese Konfiguration unterstützt die Kommunikation mit AutoSupport OnDemand und das Hochladen großer Dateien.




 a| 
Verwenden Sie SMTP
 a| 
Einstellen `-transport` Bis `smtp`.

Diese Konfiguration unterstützt weder AutoSupport OnDemand noch Uploads großer Dateien.

|===
. Wenn Sie möchten, dass Ihre interne Support-Abteilung oder ein Support-Partner AutoSupport-Meldungen erhalten, führen Sie die folgenden Aktionen durch:
+
.. Identifizieren Sie die Empfänger in Ihrem Unternehmen, indem Sie die folgenden Parameter des festlegen `system node autosupport modify` Befehl:
+
|===


| Diesen Parameter festlegen... | Künftige Situation 


 a| 
`-to`
 a| 
Bis zu fünf kommagetrennte einzelne E-Mail-Adressen oder Verteilerlisten in Ihrer internen Support-Organisation, die wichtige AutoSupport-Nachrichten empfangen



 a| 
`-noteto`
 a| 
Bis zu fünf kommagetrennte einzelne E-Mail-Adressen oder Verteilerlisten in Ihrer internen Support-Organisation, die eine verkürzte Version von wichtigen AutoSupport-Nachrichten erhalten, die für Mobiltelefone und andere mobile Geräte entwickelt wurden



 a| 
`-partner-address`
 a| 
Bis zu fünf kommagetrennte einzelne E-Mail-Adressen oder Verteilerlisten in Ihrer Support-Partnerorganisation, die alle AutoSupport Meldungen erhalten

|===
.. Überprüfen Sie, ob die Adressen richtig konfiguriert sind, indem Sie die Ziele mithilfe des auflisten `system node autosupport destinations show` Befehl.


. Wenn Sie Meldungen an Ihre interne Support-Organisation senden oder SMTP-Transport für Meldungen an den technischen Support gewählt haben, konfigurieren Sie SMTP, indem Sie die folgenden Parameter des festlegen `system node autosupport modify` Befehl:
+
** Einstellen `-mail-hosts` An einen oder mehrere E-Mail-Hosts, getrennt durch Kommas.
+
Sie können maximal fünf festlegen.

+
Sie können einen Portwert für jeden Mail-Host konfigurieren, indem Sie einen Doppelpunkt und eine Portnummer nach dem Namen des Mail-Hosts angeben: Z. B. `mymailhost.example.com:5678`, Wo 5678 ist der Port für den Mail-Host.

** Einstellen `-from` An die E-Mail-Adresse, die die AutoSupport-Nachricht sendet.


. Konfigurieren Sie DNS.
. Optional können Sie Befehlsoptionen hinzufügen, wenn Sie bestimmte Einstellungen ändern möchten:
+
|===


| Wenn Sie das wollen... | Stellen Sie dann die folgenden Parameter des ein `system node autosupport modify` Befehl... 


 a| 
Verbergen Sie private Daten, indem Sie sensible Daten in den Nachrichten entfernen, maskieren oder kodieren
 a| 
Einstellen `-remove-private-data` Bis `true`. Wenn Sie von wechseln `false` Bis `true`, Alle AutoSupport-Verlauf und alle zugehörigen Dateien werden gelöscht.



 a| 
Beenden Sie das Senden von Performance-Daten in regelmäßigen AutoSupport Meldungen
 a| 
Einstellen `-perf` Bis `false`.

|===
. Wenn Sie SMTP verwenden, um AutoSupport-Nachrichten an NetApp zu senden, können Sie TLS optional aktivieren, um die Sicherheit zu verbessern.
+
.. Zeigt die für den neuen Parameter verfügbaren Werte an:
+
[listing]
----
cluster1::> system node autosupport modify -smtp-encryption ?
----
.. TLS für SMTP-Nachrichtenversand aktivieren:
+
[listing]
----
cluster1::> system node autosupport modify -smtp-encryption start_tls
----
.. Aktuelle Konfiguration anzeigen:
+
[listing]
----
cluster1::> system node autosupport show -fields smtp-encryption
----


. Überprüfen Sie die Gesamtkonfiguration mithilfe von `system node autosupport show` Befehl mit dem `-node` Parameter.
. Überprüfen Sie den AutoSupport-Vorgang mit `system node autosupport check show` Befehl.
+
Wenn Probleme gemeldet werden, verwenden Sie das `system node autosupport check show-details` Befehl zum Anzeigen weiterer Informationen.

. Testen, ob AutoSupport Meldungen gesendet und empfangen werden:
+
.. Verwenden Sie die `system node autosupport invoke` Befehl mit dem `-type` Parameter auf gesetzt `test`:
+
[listing]
----
cluster1::> system node autosupport invoke -type test -node node1
----
.. Bestätigen Sie, dass NetApp Ihre AutoSupport Mitteilungen erhält:
+
[listing]
----
system node autosupport history show -node local
----
+
Der Status der letzten ausgehenden AutoSupport-Meldung sollte schließlich in geändert werden `sent-successful` Für alle geeigneten Protokollziele.

.. Sie können optional überprüfen, ob AutoSupport Meldungen an Ihre interne Support-Organisation oder Ihren Support-Partner gesendet werden, indem Sie die E-Mail-Adresse einer beliebigen Adresse prüfen, die Sie für das konfiguriert haben `-to`, `-noteto`, Oder `-partner-address`  Parameter des `system node autosupport modify` Befehl.



