---
permalink: system-admin/sp-bmc-network-config-concept.html 
sidebar: sidebar 
keywords: consideration, sp, bmc, network, configuration, cluster, level, disable, configuration 
summary: 'Sie können die automatische Netzwerkkonfiguration auf Cluster-Ebene für den SP aktivieren (empfohlen). Sie können die automatische SP-Netzwerkkonfiguration auch deaktiviert (die Standardeinstellung) lassen und die SP-Netzwerkkonfiguration manuell auf Node-Ebene verwalten. Für jeden Fall sind einige Überlegungen zu beachten.' 
---
= Überlegungen zur SP/BMC-Netzwerkkonfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die automatische Netzwerkkonfiguration auf Cluster-Ebene für den SP aktivieren (empfohlen). Sie können die automatische SP-Netzwerkkonfiguration auch deaktiviert (die Standardeinstellung) lassen und die SP-Netzwerkkonfiguration manuell auf Node-Ebene verwalten. Für jeden Fall sind einige Überlegungen zu beachten.

[NOTE]
====
Dieses Thema gilt sowohl für den SP als auch für den BMC.

====
Die automatische SP-Netzwerkkonfiguration ermöglicht dem SP, Adress-Ressourcen (einschließlich IP-Adresse, Subnetzmaske und Gateway-Adresse) aus dem angegebenen Subnetz zu verwenden, um das Netzwerk automatisch einzurichten. Bei der automatischen SP-Netzwerkkonfiguration müssen Sie für den SP jedes Node keine IP-Adressen manuell zuweisen. Standardmäßig ist die automatische SP-Netzwerkkonfiguration deaktiviert. Dies liegt daran, dass bei Aktivierung der Konfiguration zunächst das für die Konfiguration zu verwendenden Subnetz im Cluster definiert werden muss.

Wenn Sie die automatische Netzwerkkonfiguration des SP aktivieren, gelten die folgenden Szenarien und Überlegungen:

* Wenn der SP noch nie konfiguriert wurde, wird das SP-Netzwerk automatisch basierend auf dem für die automatische SP-Netzwerkkonfiguration angegebenen Subnetz konfiguriert.
* Wenn der SP zuvor manuell konfiguriert wurde oder wenn die bestehende SP-Netzwerkkonfiguration auf einem anderen Subnetz basiert, wird das SP-Netzwerk aller Nodes im Cluster basierend auf dem Subnetz neu konfiguriert, das Sie in der automatischen SP-Netzwerkkonfiguration angeben.
+
Die Neukonfiguration kann dazu führen, dass dem SP eine andere Adresse zugewiesen wird. Dies hat möglicherweise Auswirkungen auf die DNS-Konfiguration und ihre Fähigkeit zur Behebung von SP-Hostnamen. Aus diesem Grund müssen Sie möglicherweise Ihre DNS-Konfiguration aktualisieren.

* Ein Node, der dem Cluster hinzugefügt wird, verwendet das angegebene Subnetz, um sein SP-Netzwerk automatisch zu konfigurieren.
* Der `system service-processor network modify` Mit dem Befehl können Sie die SP-IP-Adresse nicht ändern.
+
Wenn die automatische SP-Netzwerkkonfiguration aktiviert ist, können Sie mit dem Befehl nur die SP-Netzwerkschnittstelle aktivieren oder deaktivieren.

+
** Wenn zuvor die automatische SP-Netzwerkkonfiguration aktiviert war, führt das Deaktivieren der SP-Netzwerkschnittstelle dazu, dass die zugewiesene Adressressource freigegeben wird und zum Subnetz zurückgegeben wird.
** Wenn Sie die SP-Netzwerkschnittstelle deaktivieren und dann erneut aktivieren, wird möglicherweise der SP mit einer anderen Adresse neu konfiguriert.




Wenn die automatische SP-Netzwerkkonfiguration deaktiviert ist (standardmäßig), gelten die folgenden Szenarien und Überlegungen:

* Wenn der SP noch nie konfiguriert wurde, wird die SP-IPv4-Netzwerkkonfiguration standardmäßig mit IPv4 DHCP verwendet und IPv6 ist deaktiviert.
+
Ein Node, der dem Cluster hinzugefügt wird, verwendet standardmäßig auch IPv4 DHCP für seine SP-Netzwerkkonfiguration.

* Der `system service-processor network modify` Mit dem Befehl können Sie die SP-IP-Adresse eines Node konfigurieren.
+
Wenn Sie versuchen, das SP-Netzwerk manuell mit Adressen zu konfigurieren, die einem Subnetz zugewiesen sind, wird eine Warnmeldung angezeigt. Wenn Sie die Warnung ignorieren und mit der manuellen Adresszuweisung fortfahren, kann dies zu einem Szenario mit doppelten Adressen führen.



Wenn die automatische SP-Netzwerkkonfiguration nach erfolgter Aktivierung deaktiviert ist, gelten die folgenden Szenarien und Überlegungen:

* Wenn bei der automatischen SP-Netzwerkkonfiguration die IPv4-Adressfamilie deaktiviert ist, verwendet das SP-IPv4-Netzwerk standardmäßig DHCP, und das `system service-processor network modify` Mit dem Befehl können Sie die SP-IPv4-Konfiguration für einzelne Nodes ändern.
* Wenn bei der automatischen SP-Netzwerkkonfiguration die IPv6-Adressfamilie deaktiviert ist, ist das SP-IPv6-Netzwerk ebenfalls deaktiviert, und die `system service-processor network modify` Mit dem Befehl können Sie die SP-IPv6-Konfiguration für einzelne Nodes aktivieren und ändern.

