---
permalink: system-admin/sp-bmc-network-interface--firmware-updates-concept.html 
sidebar: sidebar 
keywords: sp, bmc, network, interface, firmware, update 
summary: Ein SP Firmware-Update, das von ONTAP ausgelöst wird und bei dem auf dem SP die Version 1.5, 2.5, 3.1 oder höher ausgeführt wird, unterstützt die Verwendung eines IP-basierten Dateiübertragungsmechanismus über die SP Netzwerkschnittstelle. 
---
= ONTAP SP/BMC und Netzwerkschnittstelle für Firmware-Updates
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein SP Firmware-Update, das von ONTAP ausgelöst wird und bei dem auf dem SP die Version 1.5, 2.5, 3.1 oder höher ausgeführt wird, unterstützt die Verwendung eines IP-basierten Dateiübertragungsmechanismus über die SP Netzwerkschnittstelle.

[NOTE]
====
Dieses Thema gilt sowohl für den SP als auch für den BMC.

====
Ein SP-Firmware-Update über die Netzwerkschnittstelle ist schneller als ein Update über die serielle Schnittstelle. Dadurch verkürzt sich das Wartungsfenster, während das SP-Firmware-Update durchgeführt wird, und der ONTAP-Betrieb bleibt zudem unterbrechungsfrei. Die SP Versionen, die diese Funktion unterstützen, sind in ONTAP enthalten. Sie sind außerdem auf der NetApp Support Site verfügbar und können auf Controllern installiert werden, die eine kompatible Version von ONTAP ausführen.

Wenn Sie SP Version 1.5, 2.5, 3.1 oder höher verwenden, gelten die folgenden Verhaltensweisen beim Firmware-Upgrade:

* Ein SP-Firmware-Update, das _automatisch_ von ONTAP ausgelöst wird, verwendet standardmäßig die Netzwerkschnittstelle für das Update; das automatische SP-Update wechselt jedoch zur Verwendung der seriellen Schnittstelle für das Firmware-Update, wenn eine der folgenden Bedingungen eintritt:
+
** Die SP-Netzwerkschnittstelle ist nicht konfiguriert oder nicht verfügbar.
** Die IP-basierte Dateiübertragung schlägt fehl.
** Der SP API-Service ist deaktiviert.




Unabhängig von der verwendeten SP-Version nutzt ein über die SP-CLI ausgelöstes SP-Firmware-Update immer die SP Netzwerkschnittstelle für das Update.

.Verwandte Informationen
https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["NetApp Downloads: System Firmware und Diagnose"^]
