---
permalink: system-admin/sp-cli-system-console-sessions-concept.html 
sidebar: sidebar 
keywords: relationship, sp, cli, console, system, sessions, shell, environment, login, authentication 
summary: Sie können eine SP-CLI-Sitzung öffnen, um einen Knoten remote zu verwalten, und eine separate SP-Konsolensitzung öffnen, um auf die Konsole des Knotens zuzugreifen. Die SP-Konsolensitzung spiegelt die Ausgabe wider, die in einer gleichzeitig laufenden Systemkonsolensitzung angezeigt wird. Der SP und die Systemkonsole verfügen über unabhängige Shell-Umgebungen mit unabhängiger Authentifizierung. 
---
= Wie die ONTAP SP CLI, SP Konsole und Systemkonsolensitzungen zusammenhängen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine SP-CLI-Sitzung öffnen, um einen Knoten remote zu verwalten, und eine separate SP-Konsolensitzung öffnen, um auf die Konsole des Knotens zuzugreifen. Die SP-Konsolensitzung spiegelt die Ausgabe wider, die in einer gleichzeitig laufenden Systemkonsolensitzung angezeigt wird. Der SP und die Systemkonsole verfügen über unabhängige Shell-Umgebungen mit unabhängiger Authentifizierung.

Das Verständnis, wie die SP-CLI-, SP-Konsolen- und Systemkonsolen-Sitzungen miteinander zusammenhängen, unterstützt bei der Remoteverwaltung eines Knotens. Im Folgenden wird die Beziehung zwischen den Sitzungen beschrieben:

* Nur ein Administrator kann sich gleichzeitig in die SP CLI-Sitzung einloggen; jedoch ermöglicht der SP, sowohl eine SP CLI-Sitzung als auch eine separate SP-Konsolensitzung gleichzeitig zu öffnen.
+
Die SP CLI wird durch die SP-Eingabeaufforderung (`SP>` angezeigt. Aus einer SP CLI-Sitzung kann mit dem SP `system console`-Befehl eine SP-Konsolensitzung initiiert werden. Gleichzeitig kann eine separate SP CLI-Sitzung über SSH gestartet werden. Beim Drücken von Strg+D zum Beenden der SP-Konsolensitzung erfolgt automatisch die Rückkehr zur SP CLI-Sitzung. Falls bereits eine SP CLI-Sitzung besteht, erscheint eine Meldung mit der Nachfrage, ob die bestehende SP CLI-Sitzung beendet werden soll. Bei Eingabe von „y“ wird die bestehende SP CLI-Sitzung beendet, sodass eine Rückkehr von der SP Konsole zur SP CLI möglich ist. Diese Aktion wird im SP-Ereignisprotokoll aufgezeichnet.

+
In einer ONTAP CLI-Sitzung, die über SSH verbunden ist, kann zur Systemkonsole eines Knotens gewechselt werden, indem der ONTAP `system node run-console` Befehl von einem anderen Knoten ausgeführt wird.

* Aus Sicherheitsgründen verfügen die SP CLI-Sitzung und die Systemkonsolensitzung über eine unabhängige Authentifizierung.
+
Wenn eine SP-Konsolensitzung von der SP-CLI (mithilfe des SP `system console` Befehls) initiiert wird, erfolgt eine Aufforderung zur Eingabe der Systemkonsolen-Anmeldeinformationen. Beim Zugriff auf die SP-CLI aus einer Systemkonsolensitzung (durch Drücken von Strg+G) erfolgt eine Aufforderung zur Eingabe der SP-CLI-Anmeldeinformationen.

* Die SP-Konsolensitzung und die Systemkonsolensitzung verfügen über unabhängige Shell-Umgebungen.
+
Die SP-Konsolensitzung spiegelt die Ausgabe einer gleichzeitig laufenden Systemkonsolensitzung wider. Die gleichzeitig laufende Systemkonsolensitzung spiegelt jedoch nicht die SP-Konsolensitzung wider.

+
Die SP-Konsolensitzung spiegelt die Ausgabe gleichzeitig laufender SSH-Sitzungen nicht wider.


