---
permalink: system-admin/troubleshoot-autosupport-messages-not-received-task.html 
sidebar: sidebar 
keywords: troubleshoot, autosupport, messagem receive, deliver, generate 
summary: Wenn das System die AutoSupport-Nachricht nicht sendet, kann festgestellt werden, ob dies daran liegt, dass AutoSupport die Nachricht nicht generieren oder nicht zustellen kann. 
---
= Fehlerbehebung bei ONTAP AutoSupport, wenn keine Nachrichten empfangen werden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn das System die AutoSupport-Nachricht nicht sendet, kann festgestellt werden, ob dies daran liegt, dass AutoSupport die Nachricht nicht generieren oder nicht zustellen kann.

.Schritte
. Der Zustellungsstatus der Nachrichten kann mit dem  `system node autosupport history show` Befehl überprüft werden.
. Der Status kann eingesehen werden.
+
[cols="25,75"]
|===
| Dieser Status | Bedeutet 


 a| 
Initialisierung
 a| 
Der Datenerfassungsprozess startet. Wenn dieser Zustand nur vorübergehend ist, ist alles in Ordnung. Hält dieser Zustand jedoch an, liegt ein Problem vor.



 a| 
Sammlung fehlgeschlagen
 a| 
AutoSupport kann den AutoSupport-Inhalt im Spool-Verzeichnis nicht erstellen. Es lässt sich anzeigen, was AutoSupport zu sammeln versucht, indem der  `system node autosupport history show -detail` Befehl eingegeben wird.



 a| 
Sammlung im Gange
 a| 
AutoSupport sammelt AutoSupport-Inhalte. Es kann angezeigt werden, welche Inhalte AutoSupport sammelt, indem der  `system node autosupport manifest show` Befehl eingegeben wird.



 a| 
in der Warteschlange
 a| 
AutoSupport-Nachrichten befinden sich in der Warteschlange zur Zustellung, wurden aber noch nicht zugestellt.



 a| 
Übertragung
 a| 
AutoSupport sendet derzeit Nachrichten.



 a| 
erfolgreich gesendet
 a| 
AutoSupport hat die Nachricht erfolgreich zugestellt. Wo AutoSupport die Nachricht zugestellt hat, lässt sich durch Eingabe des  `system node autosupport history show -delivery` Befehls herausfinden.



 a| 
ignorieren
 a| 
AutoSupport hat keine Ziele für die Nachricht. Die Zustellungsdetails sind durch Eingabe des  `system node autosupport history show -delivery` Befehls einsehbar.



 a| 
erneut in die Warteschlange gestellt
 a| 
AutoSupport hat versucht, Nachrichten zuzustellen, aber der Versuch ist fehlgeschlagen. Infolgedessen hat AutoSupport die Nachrichten wieder in die Zustellwarteschlange für einen weiteren Versuch gestellt. Der Fehler kann angezeigt werden, indem der  `system node autosupport history show` Befehl eingegeben wird.



 a| 
Übertragungsfehler
 a| 
AutoSupport konnte die Nachricht die angegebene Anzahl von Malen nicht zustellen und hat die Zustellversuche eingestellt. Der Fehler kann angezeigt werden, indem der  `system node autosupport history show` Befehl eingegeben wird.



 a| 
ondemand-ignore
 a| 
Die AutoSupport-Nachricht wurde erfolgreich verarbeitet, aber der AutoSupport OnDemand-Dienst hat entschieden, sie zu ignorieren.

|===
. Führen Sie eine der folgenden Aktionen aus:
+
|===
| Für diesen Status | Tun Sie Folgendes 


 a| 
Initialisierung oder Sammlung fehlgeschlagen
 a| 
Wenden Sie sich an den NetApp Support, da AutoSupport die Meldung nicht generieren kann. Dabei sollte auf den folgenden Knowledge Base Artikel hingewiesen werden:

link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/AutoSupport_is_failing_to_deliver%3A_status_is_stuck_in_initializing["AutoSupport schlägt bei der Zustellung fehl: Der Status bleibt bei Initialisierung stehen"^]



 a| 
ignoriert, erneut in die Warteschlange gestellt oder Übertragung fehlgeschlagen
 a| 
Überprüfen Sie, ob die Ziele für SMTP, HTTP oder HTTPS korrekt konfiguriert sind, da AutoSupport die Nachricht nicht zustellen kann.

|===

