---
permalink: system-admin/troubleshoot-autosupport-subsystem-task.html 
sidebar: sidebar 
keywords: troubleshoot, autosupport, subsystem, node, check, show, command, issue, problem, delivery 
summary: Mit den Check show-Befehlen für den Systemknoten können alle Probleme in Bezug auf die Konfiguration und Bereitstellung von AutoSupport überprüft und behoben werden. 
---
= Fehlerbehebung für das ONTAP AutoSupport-Subsystem
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit den `system node check show` Befehlen können Sie sämtliche Probleme in Verbindung mit der AutoSupport-Konfiguration und -Bereitstellung überprüfen und beheben.

.Schritt
. Zeigen Sie mit den folgenden Befehlen den Status des AutoSupport-Subsystems an.
+
|===
| Befehl | Hier... 


 a| 
`system node autosupport check show`
 a| 
Zeigt den Gesamtstatus des AutoSupport-Subsystems an, z. B. den Status von AutoSupport HTTP- oder HTTPS-Ziel, AutoSupport SMTP-Ziele, AutoSupport OnDemand Server und AutoSupport-Konfiguration



 a| 
`system node autosupport check show-details`
 a| 
Anzeige des detaillierten Status des AutoSupport-Subsystems, z. B. detaillierte Beschreibungen der Fehler und der Korrekturmaßnahmen

|===

