---
permalink: system-admin/types-autosupport-messages-reference.html 
sidebar: sidebar 
keywords: active, iq, active iq, digital advisor, autosupport, messages, content, support, subsystems 
summary: AutoSupport-Meldungen enthalten Statusinformationen zu unterstützten Subsystemen. Wenn Sie erfahren, welche AutoSupport-Nachrichten enthalten, können Sie Nachrichten, die Sie per E-Mail erhalten oder auf der Digital Advisor-Website anzeigen, interpretieren oder darauf antworten. 
---
= Arten von AutoSupport Nachrichten und deren Inhalt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport-Meldungen enthalten Statusinformationen zu unterstützten Subsystemen. Wenn Sie erfahren, welche AutoSupport-Nachrichten enthalten, können Sie Nachrichten, die Sie per E-Mail erhalten oder auf der Digital Advisor-Website anzeigen, interpretieren oder darauf antworten.

|===
| Nachrichtentyp | Typ der Daten, die die Nachricht enthält 


 a| 
Ereignis ausgelöst
 a| 
Dateien, die kontextsensitive Daten über das spezifische Subsystem enthalten, in dem das Ereignis aufgetreten ist



 a| 
Täglich
 a| 
Log-Dateien



 a| 
Performance
 a| 
Performance-Daten, die in den letzten 24 Stunden erfasst wurden



 a| 
Wöchentlich
 a| 
Konfigurations- und Statusdaten



 a| 
Wird durch den `system node autosupport invoke` Befehl ausgelöst
 a| 
Abhängig vom im `-type` Parameter angegebenen Wert:

* `test` Sendet eine vom Benutzer ausgelöste Meldung mit einigen Basisdaten.
+
Diese Meldung löst außerdem eine automatische E-Mail-Antwort des technischen Supports an beliebige angegebene E-Mail-Adressen aus `-to`, sodass Sie mit der Option den Empfang von AutoSupport Meldungen bestätigen können.

* `performance` Sendet Leistungsdaten.
* `all` Sendet eine vom Benutzer ausgelöste Meldung mit einem vollständigen Datensatz ähnlich der wöchentlichen Meldung, einschließlich der Fehlerbehebungsdaten von jedem Subsystem.
+
Technischer Support fordert diese Meldung in der Regel an.





 a| 
Wird durch den `system node autosupport invoke-core-upload` Befehl ausgelöst
 a| 
Core Dump-Dateien für einen Node



 a| 
Wird durch den `system node autosupport invoke-performance-archive` Befehl ausgelöst
 a| 
Performance-Archivdateien für einen bestimmten Zeitraum



 a| 
Wird von AutoSupport OnDemand ausgelöst
 a| 
AutoSupport OnDemand kann neue Nachrichten oder frühere Nachrichten anfordern:

* Neue Nachrichten, je nach Typ der AutoSupport-Sammlung, können `test` , `all` oder sein `performance`.
* Frühere Nachrichten hängen von der Art der Nachricht ab, die neu gesendet wird.


AutoSupport OnDemand kann neue Nachrichten anfordern, die die folgenden Dateien auf die NetApp Support-Website hochladen http://mysupport.netapp.com/["mysupport.netapp.com"^]:

* Core Dump
* Performance-Archivierung


|===