---
permalink: system-admin/upload-performance-archive-files-task.html 
sidebar: sidebar 
keywords: upload, performance, archive, files, autosupport, message, technical 
summary: Sie können eine AutoSupport-Nachricht erstellen und versenden, die ein Leistungsarchiv enthält. Standardmäßig erhält der technische Support von NetApp die AutoSupport-Nachricht, und das Leistungsarchiv wird auf die NetApp Support-Website hochgeladen. Ein alternatives Ziel für die Nachricht und den Upload kann angegeben werden. 
---
= ONTAP AutoSupport Performance-Archivdateien hochladen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine AutoSupport-Nachricht erstellen und versenden, die ein Leistungsarchiv enthält. Standardmäßig erhält der technische Support von NetApp die AutoSupport-Nachricht, und das Leistungsarchiv wird auf die NetApp Support-Website hochgeladen. Ein alternatives Ziel für die Nachricht und den Upload kann angegeben werden.

.Bevor Sie beginnen
* Sie müssen AutoSupport mit den folgenden Einstellungen eingerichtet haben:
+
** AutoSupport ist auf dem Knoten aktiviert.
** AutoSupport ist so konfiguriert, dass Nachrichten an den technischen Support gesendet werden.
** AutoSupport ist für die Verwendung des HTTPS-Transportprotokolls konfiguriert.
+
Das SMTP-Transportprotokoll wird beim Senden von Nachrichten, die große Dateien wie Performance-Archivdateien enthalten, nicht unterstützt.





.Über diese Aufgabe
Sie müssen ein Startdatum für die Leistungsarchivdaten angeben, die Sie hochladen möchten. Die meisten Speichersysteme bewahren Leistungsarchive zwei Wochen lang auf, sodass Sie ein Startdatum bis zu zwei Wochen in der Vergangenheit festlegen können. Wenn heute beispielsweise der 15. Januar ist, kann als Startdatum der 2. Januar angegeben werden.

.Schritt
. Eine AutoSupport-Nachricht generieren und die Performance-Archivdatei mit dem  `system node autosupport invoke-performance-archive` Befehl hochladen.
+
Im folgenden Beispiel werden 4 Stunden Performance-Archivdateien vom 12. Januar 2015 einer AutoSupport-Nachricht hinzugefügt und an den Standardspeicherort, die NetApp Support-Website, hochgeladen:

+
[listing]
----
cluster1::> system node autosupport invoke-performance-archive -node local -start-date 1/12/2015 13:42:09 -duration 4h
----
+
Im folgenden Beispiel werden 4 Stunden Performance-Archivdateien vom 12. Januar 2015 einer AutoSupport-Nachricht hinzugefügt und an den durch die URI angegebenen Speicherort hochgeladen:

+
[listing]
----
cluster1::> system node autosupport invoke-performance-archive -node local -start-date 1/12/2015 13:42:09 -duration 4h -uri https://files.company.com
----

