---
permalink: system-admin/upload-core-dump-files-task.html 
sidebar: sidebar 
keywords: upload, core, dump, file, autosupport, device, send, messages, email 
summary: Wenn eine Core Dump-Datei gespeichert wird, wird eine Ereignismeldung generiert. Wenn der AutoSupport Service aktiviert und konfiguriert ist, um Meldungen an den NetApp Support zu senden, wird eine AutoSupport-Meldung übertragen und eine automatische E-Mail-Bestätigung an Sie gesendet. 
---
= Laden Sie Core Dump-Dateien hoch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn eine Core Dump-Datei gespeichert wird, wird eine Ereignismeldung generiert. Wenn der AutoSupport Service aktiviert und konfiguriert ist, um Meldungen an den NetApp Support zu senden, wird eine AutoSupport-Meldung übertragen und eine automatische E-Mail-Bestätigung an Sie gesendet.

.Was Sie benötigen
* Sie müssen AutoSupport mit den folgenden Einstellungen einrichten:
+
** AutoSupport ist auf dem Node aktiviert.
** AutoSupport wurde konfiguriert, um Meldungen an den technischen Support zu senden.
** AutoSupport ist für die Verwendung des HTTP- oder HTTPS-Transportprotokolls konfiguriert.
+
Das SMTP-Transportprotokoll wird nicht unterstützt, wenn Meldungen mit großen Dateien, wie z. B. Core Dump-Dateien, gesendet werden.





.Über diese Aufgabe
Sie können die Core Dump-Datei auch über den AutoSupport-Service über HTTPS hochladen, indem Sie die verwenden `system node autosupport invoke-core-upload` Befehl, falls durch den NetApp Support angefordert.

https://kb.netapp.com/Advice_and_Troubleshooting/Miscellaneous/How_to_upload_a_file_to_NetApp["Wie zum Hochladen einer Datei auf NetApp"^]

.Schritte
. Zeigen Sie die Core Dump-Dateien für einen Node an, indem Sie den verwenden `system node coredump show` Befehl.
+
Im folgenden Beispiel werden Core Dump-Dateien für den lokalen Node angezeigt:

+
[listing]
----
cluster1::> system node coredump show -node local
Node:Type Core Name Saved Panic Time
--------- ------------------------------------------- ----- -----------------
node:kernel
core.4073000068.2013-09-11.15_05_01.nz true 9/11/2013 15:05:01
----
. Generieren Sie eine AutoSupport Meldung und laden Sie mithilfe der eine Core Dump-Datei hoch `system node autosupport invoke-core-upload` Befehl.
+
Im folgenden Beispiel wird eine AutoSupport Meldung generiert und an den Standardspeicherort gesendet, d. h. technischen Support. Und die Core Dump-Datei wird an den Standardspeicherort hochgeladen, der die NetApp Support Site ist:

+
[listing]
----
cluster1::> system node autosupport invoke-core-upload -core-filename
core.4073000068.2013-09-11.15_05_01.nz -node local
----
+
Im folgenden Beispiel wird eine AutoSupport Meldung generiert und an den in der URI angegebenen Speicherort gesendet, und die Core Dump-Datei wird auf den URI hochgeladen:

+
[listing]
----
cluster1::> system node autosupport invoke-core-upload -uri https//files.company.com -core-filename
core.4073000068.2013-09-11.15_05_01.nz -node local
----

