---
permalink: system-admin/verify-identity-remote-servers-certificates-concept.html 
sidebar: sidebar 
keywords: verify, identity, remote, servers, certificate 
summary: ONTAP unterstützt die Funktionen für Sicherheitszertifikate zur Überprüfung der Identität von Remote-Servern. 
---
= Überprüfen Sie die Identität von Remote-Servern mithilfe der Zertifikatübersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP unterstützt die Funktionen für Sicherheitszertifikate zur Überprüfung der Identität von Remote-Servern.

Die ONTAP Software ermöglicht sichere Verbindungen unter Verwendung dieser digitalen Zertifikatfunktionen und -Protokolle:

* Online Certificate Status Protocol (OCSP) validiert den Status von digitalen Zertifikatsanforderungen von ONTAP-Diensten mithilfe von SSL- und TLS-Verbindungen (Transport Layer Security). Diese Funktion ist standardmäßig deaktiviert.
* Die ONTAP-Software enthält standardmäßig vertrauenswürdige Stammzertifikate.
* KMIP-Zertifikate (Key Management Interoperability Protocol) ermöglichen die gegenseitige Authentifizierung eines Clusters und eines KMIP-Servers.

