---
permalink: system-admin/verify-monitor-cluster-management-network-switches-task.html 
sidebar: sidebar 
keywords: verify, monitor, cluster, management, network, switches, heath, monitor 
summary: Die Cluster-Switch-Systemzustandsüberwachung versucht automatisch, die Switches zu überwachen, die sie erkannt haben. Die Überwachung erfolgt jedoch möglicherweise nicht automatisch, wenn die Switches nicht richtig konfiguriert sind. Sie sollten überprüfen, ob die Systemzustandsüberwachung ordnungsgemäß für das Monitoring Ihrer Switches konfiguriert ist. 
---
= Überprüfen Sie die Überwachung von Cluster- und Managementnetzwerk-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Cluster-Switch-Systemzustandsüberwachung versucht automatisch, die Switches zu überwachen, die sie erkannt haben. Die Überwachung erfolgt jedoch möglicherweise nicht automatisch, wenn die Switches nicht richtig konfiguriert sind. Sie sollten überprüfen, ob die Systemzustandsüberwachung ordnungsgemäß für das Monitoring Ihrer Switches konfiguriert ist.

.Schritte
. Geben Sie den folgenden Befehl ein, um die Switches zu identifizieren, die die Systemzustandsüberwachung des Cluster-Switch erkannt haben:
+
[role="tabbed-block"]
====
.ONTAP 9.8 und höher
--
`system switch ethernet show`

--
.ONTAP 9.7 und früher
--
`system cluster-switch show`

--
====
+
Wenn der `Model` Spalte zeigt den Wert an `OTHER`, Dann kann ONTAP den Schalter nicht überwachen. ONTAP setzt den Wert auf `OTHER` Wenn ein automatisch erkannte Switch nicht für das Monitoring des Systemzustands unterstützt wird.

+
[NOTE]
====
Wenn in der Befehlsausgabe des Befehls kein Switch angezeigt wird, müssen Sie die Erkennung des Switches konfigurieren.

====
. Führen Sie ein Upgrade auf die neueste unterstützte Switch-Software durch, und verwenden Sie die Konfigurationsdatei (RCF) von der NetApp Support Site.
+
http://support.netapp.com/NOW/download/software/cm_switches/["NetApp Support Downloads Seite"^]

+
Die Community-Zeichenfolge in der RCF des Switches muss mit der Community-Zeichenfolge übereinstimmen, die die Systemzustandsüberwachung konfiguriert ist. Standardmäßig verwendet die Systemzustandsüberwachung die Community-Zeichenfolge `cshm1!`.

+
[NOTE]
====
Derzeit unterstützt die Systemzustandsüberwachung nur SNMPv2.

====
+
Wenn Sie Informationen über einen Switch ändern müssen, der vom Cluster überwacht wird, können Sie den Community-String, den die Systemzustandsüberwachung mit dem folgenden Befehl verwendet, ändern:

+
[role="tabbed-block"]
====
.ONTAP 9.8 und höher
--
`system switch ethernet modify`

--
.ONTAP 9.7 und früher
--
`system cluster-switch modify`

--
====
. Vergewissern Sie sich, dass der Managementport des Switch mit dem Managementnetzwerk verbunden ist.
+
Diese Verbindung ist erforderlich, um SNMP-Abfragen durchzuführen.


