---
permalink: system-admin/view-default-certificates-tls-based-applications-task.html 
sidebar: sidebar 
keywords: view, default, certificates, tls, applications, transport 
summary: 'Ab ONTAP 9.2 bietet ONTAP einen Standardsatz an vertrauenswürdigen Root-Zertifikaten für ONTAP-Anwendungen mithilfe von Transport Layer Security (TLS).' 
---
= Anzeigen von Standardzertifikaten für TLS-basierte Anwendungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.2 bietet ONTAP einen Standardsatz an vertrauenswürdigen Root-Zertifikaten für ONTAP-Anwendungen mithilfe von Transport Layer Security (TLS).

Die Standardzertifikate werden während der Erstellung oder beim Upgrade auf ONTAP 9.2 nur auf der Administrator-SVM installiert.

Die aktuellen Applikationen, die als Client fungieren und eine Zertifikatvalidierung erfordern, sind AutoSupport, EMS, LDAP, Audit Logging, FabricPool, Und KMIP.

Wenn Zertifikate ablaufen, wird eine EMS-Nachricht aufgerufen, die den Benutzer zum Löschen der Zertifikate auffordert. Die Standardzertifikate können nur auf der erweiterten Berechtigungsebene gelöscht werden.

[NOTE]
====
Das Löschen der Standardzertifikate kann dazu führen, dass einige ONTAP-Anwendungen nicht wie erwartet funktionieren (z. B. AutoSupport- und Audit-Protokollierung).

====
.Schritt
. Sie können die Standardzertifikate, die auf der Admin-SVM installiert sind, anzeigen. Verwenden Sie dazu den Befehl „Security Certificate show“:
+
`*security certificate show -vserver –type server-ca*`

+
[listing]
----

fas2552-2n-abc-3::*> security certificate show -vserver fas2552-2n-abc-3 -type server-ca
Vserver    Serial Number   Common Name                            Type
---------- --------------- -------------------------------------- ------------
fas2552-2n-abc-3
           01              AAACertificateServices                 server-ca
    Certificate Authority: AAA Certificate Services
          Expiration Date: Sun Dec 31 18:59:59 2028
----

