---
permalink: system-admin/when-where-autosupport-messages-sent-concept.html 
sidebar: sidebar 
keywords: active, iq, digital advisor, active iq, autosupport, messages, email, manual, scheduled, event, triggered 
summary: AutoSupport sendet Nachrichten an unterschiedliche Empfänger, abhängig vom Nachrichtentyp. Zu wissen, wann und wohin AutoSupport Nachrichten sendet, kann dabei helfen, die Nachrichten, die per E-Mail empfangen oder auf der Digital Advisor Website angezeigt werden, besser zu verstehen. 
---
= Informationen darüber, wann und wo ONTAP AutoSupport-Nachrichten gesendet werden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport sendet Nachrichten an unterschiedliche Empfänger, abhängig vom Nachrichtentyp. Zu wissen, wann und wohin AutoSupport Nachrichten sendet, kann dabei helfen, die Nachrichten, die per E-Mail empfangen oder auf der Digital Advisor Website angezeigt werden, besser zu verstehen.

Sofern nicht anders angegeben, sind die Einstellungen in den folgenden Tabellen Parameter des  `system node autosupport modify` Befehls.



[[event-triggered-messages]]
== Ereignisgesteuerte Nachrichten

Wenn im System Ereignisse auftreten, die eine Korrekturmaßnahme erfordern, sendet AutoSupport automatisch eine ereignisgesteuerte Nachricht.

|===
| Wenn die Nachricht gesendet wird | Wohin die Nachricht gesendet wird 


 a| 
AutoSupport reagiert auf ein auslösendes Ereignis im EMS
 a| 
Adressen, die in  `-to` und  `-noteto` angegeben sind. (Es werden nur kritische, dienstbeeinträchtigende Ereignisse gesendet.)

Adressen, die in `-partner-address`

Technischer Support, wenn  `-support` auf  `enable` gesetzt ist

|===


[[scheduled-messages]]
== Geplante Nachrichten

AutoSupport sendet automatisch in regelmäßigen Abständen mehrere Nachrichten.

|===
| Wenn die Nachricht gesendet wird | Wohin die Nachricht gesendet wird 


 a| 
Täglich (standardmäßig zwischen 0:00 Uhr und 1:00 Uhr als Protokollnachricht gesendet)
 a| 
Adressen, die in `-partner-address`

Technischer Support, wenn  `-support` auf  `enable` gesetzt ist



 a| 
Täglich (standardmäßig zwischen 0:00 Uhr und 1:00 Uhr als Leistungsmeldung gesendet), wenn der  `-perf` Parameter auf  `true` gesetzt ist
 a| 
Adressen, die in -partner-address angegeben sind

Technischer Support, wenn  `-support` auf  `enable` gesetzt ist



 a| 
Wöchentlich (standardmäßig, Versand sonntags zwischen 0:00 und 1:00 Uhr)
 a| 
Adressen, die in `-partner-address`

Technischer Support, wenn  `-support` auf  `enable` gesetzt ist

|===


[[manually-triggered-messages]]
== Manuell ausgelöste Nachrichten

Sie können eine AutoSupport-Nachricht manuell initiieren oder erneut senden.

|===
| Wenn die Nachricht gesendet wird | Wohin die Nachricht gesendet wird 


 a| 
Sie initiieren manuell eine Nachricht mit dem  `system node autosupport invoke` Befehl
 a| 
Wenn eine URI mit dem  `-uri` Parameter im  `system node autosupport invoke` Befehl angegeben wird, wird die Nachricht an diese URI gesendet.

Wenn `-uri` weggelassen wird, wird die Nachricht an die in `-to` und `-partner-address` angegebenen Adressen gesendet. Die Nachricht wird auch an den technischen Support gesendet, wenn `-support` auf `enable` gesetzt ist.



 a| 
Sie initiieren manuell eine Nachricht mit dem  `system node autosupport invoke-core-upload` Befehl
 a| 
Wenn ein URI mit dem  `-uri`-Parameter im  `system node autosupport invoke-core-upload`-Befehl angegeben wird, wird die Nachricht an diesen URI gesendet und die Core-Dump-Datei an den URI hochgeladen.

Wenn  `-uri` im  `system node autosupport invoke-core-upload` Befehl weggelassen wird, wird die Meldung an den technischen Support gesendet und die Core-Dump-Datei auf die technische Support-Website hochgeladen.

In beiden Szenarien muss  `-support` auf  `enable` gesetzt sein und  `-transport` auf  `https` oder  `http` gesetzt sein.

Aufgrund der großen Größe der Core-Dump-Dateien wird die Nachricht nicht an die in den  `-to` und  `-partner-addresses` Parametern angegebenen Adressen gesendet.



 a| 
Sie initiieren manuell eine Nachricht mit dem  `system node autosupport invoke-performance-archive` Befehl
 a| 
Wenn ein URI mit dem  `-uri` Parameter im  `system node autosupport invoke-performance-archive` Befehl angegeben wird, wird die Nachricht an diesen URI gesendet und die Performance-Archivdatei an den URI hochgeladen.

Wenn `-uri` in der `system node autosupport invoke-performance-archive` weggelassen wird, wird die Nachricht an den technischen Support gesendet und die Performance-Archivdatei auf die technische Support-Website hochgeladen.

In beiden Szenarien muss  `-support` auf  `enable` gesetzt sein und  `-transport` auf  `https` oder  `http` gesetzt sein.

Aufgrund der großen Größe der Performance-Archivdateien wird die Nachricht nicht an die in den  `-to` und  `-partner-addresses` angegebenen Adressen gesendet.



 a| 
Eine zuvor gesendete Nachricht wird manuell erneut gesendet, indem der  `system node autosupport history retransmit` Befehl verwendet wird.
 a| 
Nur an die URI, die im  `-uri`Parameter des  `system node autosupport history retransmit`Befehls angegeben wird

|===


[[messages-triggered-by-technical-support]]
== Meldungen, die vom technischen Support ausgelöst wurden

Der technische Support kann Nachrichten von AutoSupport mit der AutoSupport OnDemand Funktion anfordern.

|===
| Wenn die Nachricht gesendet wird | Wohin die Nachricht gesendet wird 


 a| 
Wenn AutoSupport Zustellanweisungen zum Generieren neuer AutoSupport-Nachrichten erhält
 a| 
Adressen, die in `-partner-address`

Technischer Support, wenn  `-support` auf  `enable` und  `-transport` auf  `https` gesetzt ist



 a| 
Wenn AutoSupport Zustellanweisungen zum erneuten Senden früherer AutoSupport-Nachrichten erhält
 a| 
Technischer Support, wenn  `-support` auf  `enable` und  `-transport` auf  `https` gesetzt ist



 a| 
Wenn AutoSupport Zustellungsanweisungen erhält, um neue AutoSupport-Nachrichten zu generieren, die Core Dump- oder Leistungsarchivdateien hochladen
 a| 
Technischer Support, falls  `-support` auf  `enable` und  `-transport` auf  `https` gesetzt ist. Die Core Dump- oder Performance-Archivdatei wird auf die technische Support-Website hochgeladen.

|===