---
permalink: authentication/create-name-service-switch-task.html 
sidebar: sidebar 
keywords: create, name, service, switch 
summary: Mit der Namensdienst-Switch-Funktion können Sie LDAP oder NIS als alternative Namensdienstquellen verwenden. Sie können den Befehl vserver Services Name-Service ns-Switch modify verwenden, um die Reihenfolge für Namensdienstquellen festzulegen. 
---
= Erstellen Sie einen Namensdienstschalter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit der Namensdienst-Switch-Funktion können Sie LDAP oder NIS als alternative Namensdienstquellen verwenden. Sie können das verwenden `vserver services name-service ns-switch modify` Befehl zum Festlegen der Reihenfolge für Name-Service-Quellen.

.Was Sie benötigen
* Sie müssen LDAP- und NIS-Serverzugriff konfiguriert haben.
* Um diese Aufgabe auszuführen, müssen Sie ein Cluster-Administrator oder SVM-Administrator sein.


.Schritt
. Geben Sie die Suchreihenfolge für Namensdienstquellen an:
+
`vserver services name-service ns-switch modify -vserver SVM_name -database name_service_switch_database -sources name_service_source_order`

+
Eine vollständige Befehlssyntax finden Sie im link:config-worksheets-reference.html["Arbeitsblatt"].

+
Mit dem folgenden Befehl wird die Suchreihenfolge der LDAP- und NIS-Namensdienstquellen für die festgelegt `passwd` Datenbank auf dem ``engData``SVM:

+
[listing]
----
cluster1::>vserver services name-service ns-switch
modify -vserver engData -database passwd -source files ldap,nis
----

