---
permalink: authentication/create-svm-computer-account-domain-task.html 
sidebar: sidebar 
keywords: create, svm, computer, account, domain, cifs server 
summary: Wenn Sie keinen SMB-Server für eine Daten-SVM konfiguriert haben, können Sie den Befehl vserver Active Directory create verwenden, um ein Computerkonto für die SVM in der Domäne zu erstellen. 
---
= Erstellen Sie ein SVM-Computerkonto in der Domäne
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Falls Sie noch keinen SMB-Server für eine Daten-SVM konfiguriert haben, können Sie den verwenden `vserver active-directory create` Befehl zum Erstellen eines Computerkontos für die SVM in der Domäne.

Sie müssen ein Cluster- oder SVM-Administrator sein, um diese Aufgabe durchzuführen.

Nach der Eingabe des `vserver active-directory create` Befehl, Sie werden aufgefordert, die Anmeldeinformationen für ein AD-Benutzerkonto mit ausreichenden Berechtigungen bereitzustellen, um der angegebenen Organisationseinheit in der Domäne Computer hinzuzufügen. Das Passwort des Kontos darf nicht leer sein.

.Schritt
. Erstellen eines Computerkontos für eine SVM in der AD-Domäne:
+
`vserver active-directory create -vserver _SVM_name_ -account-name _NetBIOS_account_name_ -domain _domain_ -ou _organizational_unit_`

+
Eine vollständige Befehlssyntax finden Sie im link:config-worksheets-reference.html["Arbeitsblatt"].

+
Mit dem folgenden Befehl wird ein Computerkonto mit dem Namen erstellt `ADSERVER1` In der Domäne `example.com` Für die SVM `engData`. Sie werden nach Eingabe des Befehls zur Eingabe der Anmeldedaten für das AD-Benutzerkonto aufgefordert.

+
[listing]
----
cluster1::>vserver active-directory create -vserver engData -account-name ADSERVER1 -domain example.com

In order to create an Active Directory machine account, you must supply the name and password of a Windows account with sufficient privileges to add computers to the "CN=Computers" container within the "example.com" domain.

Enter the user name: Administrator

Enter the password:
----

