---
permalink: authentication/create-svm-user-accounts-task.html 
sidebar: sidebar 
keywords: create, login accounts 
summary: Sie können lokale oder Remote-Cluster- und SVM-Administratorkonten aktivieren. Bei einem lokalen Konto befinden sich die Kontoinformationen, der öffentliche Schlüssel oder das Sicherheitszertifikat auf dem Speichersystem. AD-Kontoinformationen werden auf einem Domänencontroller gespeichert. LDAP- und NIS-Konten befinden sich auf LDAP- bzw. NIS-Servern. 
---
= Informationen zur Erstellung von ONTAP Anmeldekonten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können lokale oder Remote-Cluster- und SVM-Administratorkonten aktivieren. Bei einem lokalen Konto befinden sich die Kontoinformationen, der öffentliche Schlüssel oder das Sicherheitszertifikat auf dem Speichersystem. AD-Kontoinformationen werden auf einem Domänencontroller gespeichert. LDAP- und NIS-Konten befinden sich auf LDAP- bzw. NIS-Servern.



[[cluster-and-svm-administrators]]
== Cluster- und SVM-Administratoren

Ein Clusteradministrator greift auf die administrative SVM des Clusters zu. Die administrative SVM und ein Clusteradministrator mit dem reservierten Namen `admin` werden beim Einrichten des Clusters automatisch erstellt.

Ein Clusteradministrator mit der Standard `admin`rolle kann den gesamten Cluster und seine Ressourcen verwalten. Der Clusteradministrator kann bei Bedarf weitere Clusteradministratoren mit unterschiedlichen Rollen erstellen.

Ein _SVM Administrator_ greift auf eine Daten SVM zu. Der Cluster-Administrator erstellt Daten SVMs und SVM Administratoren nach Bedarf.

SVM-Administratoren wird standardmäßig die  `vsadmin` Rolle zugewiesen. Der Cluster-Administrator kann SVM-Administratoren bei Bedarf unterschiedliche Rollen zuweisen.



[[naming-conventions]]
=== Namenskonventionen

Die folgenden generischen Namen können nicht für Remote-Cluster- und SVM-Administratorkonten verwendet werden:

* "adm"
* "bin"
* "cli"
* "Daemon"
* "ftp"
* "Spiele"
* "halt"
* "lp"
* "Mail"
* "man"
* "naroot"
* "netapp"
* "News"
* "niemand"
* "Operator"
* "root"
* "shutdown"
* "sshd"
* "sync"
* "sys"
* "uucp"
* "www"




[[merged-roles]]
== Zusammengeführte Rollen

Wenn Sie mehrere Remote-Konten für denselben Benutzer aktivieren, wird diesem Benutzer die Vereinigung aller für die Konten festgelegten Rollen zugewiesen. Das heißt, wenn einem LDAP- oder NIS-Konto die  `vsadmin` Rolle und dem Active Directory Gruppe Konto desselben Benutzers die  `vsadmin-volume` Rolle zugewiesen ist, meldet sich der AD-Benutzer mit den umfassenderen  `vsadmin` Berechtigungen an. Die Rollen werden als „zusammengeführt“ bezeichnet.
