---
permalink: authentication/create-svm-user-accounts-task.html 
sidebar: sidebar 
keywords: create, login accounts 
summary: Sie können lokale oder Remote-Cluster und SVM-Administratorkonten aktivieren. Bei einem lokalen Konto handelt es sich um ein Konto, in dem die Kontoinformationen, der öffentliche Schlüssel oder das Sicherheitszertifikat im Speichersystem gespeichert sind. INFORMATIONEN zu ANZEIGENKONTOKONTEN werden auf einem Domänencontroller gespeichert. LDAP- und NIS-Konten befinden sich auf LDAP- und NIS-Servern. 
---
= Erstellen Sie die Übersicht über Login-Konten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können lokale oder Remote-Cluster und SVM-Administratorkonten aktivieren. Bei einem lokalen Konto handelt es sich um ein Konto, in dem die Kontoinformationen, der öffentliche Schlüssel oder das Sicherheitszertifikat im Speichersystem gespeichert sind. INFORMATIONEN zu ANZEIGENKONTOKONTEN werden auf einem Domänencontroller gespeichert. LDAP- und NIS-Konten befinden sich auf LDAP- und NIS-Servern.



== Cluster- und SVM-Administratoren

Ein_Cluster-Administrator_ greift auf die Admin-SVM für das Cluster zu. Der Administrator-SVM und ein Cluster-Administrator mit dem reservierten Namen `admin` Werden automatisch erstellt, wenn das Cluster eingerichtet ist.

Ein Clusteradministrator mit dem Standardwert `admin` Rolle kann den gesamten Cluster und seine Ressourcen verwalten. Der Cluster-Administrator kann bei Bedarf weitere Cluster-Administratoren mit unterschiedlichen Rollen erstellen.

Ein _SVM-Administrator_ greift auf eine Daten-SVM zu. Je nach Bedarf erstellt der Cluster-Administrator Daten-SVMs und SVM-Administratoren.

Den werden SVM-Administratoren zugewiesen `vsadmin` Rolle standardmäßig. Der Cluster-Administrator kann je nach Bedarf SVM-Administratoren verschiedene Rollen zuweisen.



=== Namenskonventionen

Die folgenden allgemeinen Namen können nicht für Remote-Cluster- und SVM-Administratorkonten verwendet werden:

* „adm“
* „Bin“
* „cli“
* „Daemon“
* „ftp“
* „Spiele“
* „Anhalten“
* „lp“
* „E-Mail“
* „Mann“
* „Naroot“
* NetApp
* „news“
* „Niemand“
* „Operator“
* „Root“
* „Herunterfahren“
* „Sshd“
* „Synchronisieren“
* „Sys“
* „uucp“
* „Www“




== Zusammengeführte Rollen

Wenn Sie mehrere Remote-Konten für denselben Benutzer aktivieren, wird dem Benutzer die Zuordnung aller für die Konten angegebenen Rollen zugewiesen. Das heißt, wenn einem LDAP- oder NIS-Konto das zugewiesen ist `vsadmin` Rolle und das AD-Gruppenkonto für denselben Benutzer wird der zugewiesen `vsadmin-volume` Rolle, der AD-Benutzer meldet sich mit dem Inklusiveren an `vsadmin` Sorgen. Die Rollen sollen _fusioniert werden_.
