---
permalink: authentication/dynamic-authorization-overview.html 
sidebar: sidebar 
keywords: dynamic, authorization, framework, security, login, ssh 
summary: Konfigurieren Sie das Dynamic Authorization Framework, um die Sicherheit von SSH-Anmeldungen zu erhöhen und die Ausführung bestimmter Befehle unter verdächtigen Umständen zu beschränken. 
---
= Dynamische Autorisierung – Übersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.15.1 können Administratoren dynamische Autorisierungen konfigurieren und aktivieren, um die Sicherheit des Remote-Zugriffs auf ONTAP zu erhöhen und gleichzeitig potenzielle Schäden zu minimieren, die durch einen böswilligen Akteur verursacht werden können. Mit ONTAP 9.15.1 bietet die dynamische Autorisierung einen ersten Rahmen für die Zuweisung einer Sicherheitsbewertung für Benutzer. Wenn ihre Aktivität verdächtig aussieht, werden sie durch zusätzliche Berechtigungsprüfungen oder die völlige Ablehnung eines Vorgangs in Frage gestellt. Administratoren können Regeln erstellen, Vertrauenswerte zuweisen und Befehle einschränken, um zu bestimmen, wann bestimmte Aktivitäten für einen Benutzer zugelassen oder verweigert werden. Administratoren können Cluster-weit oder für einzelne Storage VMs eine dynamische Autorisierung aktivieren.



== Wie die dynamische Autorisierung funktioniert

Die dynamische Autorisierung verwendet ein System zur Vertrauensbewertung, um Benutzern je nach den Autorisierungsrichtlinien eine andere Vertrauensebene zuzuweisen. Je nach Vertrauensstufe des Benutzers kann eine Aktivität, die er durchführt, zugelassen oder verweigert werden, oder der Benutzer kann zur weiteren Authentifizierung aufgefordert werden.

Nehmen wir das Beispiel von drei verschiedenen Benutzern, die versuchen, ein Volume zu löschen. Bei dem Versuch, den Vorgang durchzuführen, wird die Risikoeinstufung für jeden Benutzer untersucht:

* Der erste Benutzer meldet sich von einem vertrauenswürdigen Gerät zu normalen Geschäftszeiten an, wodurch seine Risikoeinstufung gering wird. Der Vorgang ist ohne zusätzliche Authentifizierung zulässig.
* Der zweite Benutzer meldet sich außerhalb der Bürozeiten von einem vertrauenswürdigen Gerät in seinem Haus an, was die Risikoeinstufung moderat macht. Er wird aufgefordert, eine zusätzliche Authentifizierung durchzuführen, bevor der Vorgang zugelassen wird.
* Der dritte Benutzer meldet sich von einem nicht vertrauenswürdigen Gerät außerhalb der Bürozeiten an einem neuen Standort an, wodurch die Risikoeinstufung hoch ist. Der Vorgang ist nicht zulässig.


.Wie es weiter geht
* link:configure-dynamic-authorization.html["Dynamische Autorisierung anpassen"^]
* link:enable-disable-dynamic-authorization.html["Aktivieren oder Deaktivieren der dynamischen Autorisierung"^]

