---
permalink: authentication/enable-password-account-access-task.html 
sidebar: sidebar 
keywords: enable, password, account, access 
summary: Mit dem Befehl Security Login create können Sie Administratorkonten für den Zugriff auf einen Administrator oder eine Daten-SVM mit einem Passwort aktivieren. Nachdem Sie den Befehl eingegeben haben, werden Sie zur Eingabe des Passworts aufgefordert. 
---
= Aktivieren Sie den Zugriff auf das Passwort-Konto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `security login create` Befehl zum Aktivieren von Administratorkonten für den Zugriff auf einen Administrator oder Daten-SVM mit einem Passwort Nachdem Sie den Befehl eingegeben haben, werden Sie zur Eingabe des Passworts aufgefordert.

Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.

Wenn Sie sich nicht sicher sind, welche Rolle bei der Zugriffssteuerung Sie dem Login-Konto zuweisen möchten, können Sie das verwenden `security login modify` Befehl, um die Rolle später hinzuzufügen.

.Schritt
. Ermöglichen Sie lokalen Administratorkonten den Zugriff auf eine SVM über ein Passwort:
+
`security login create -vserver SVM_name -user-or-group-name user_or_group_name -application application -authmethod authentication_method -role role -comment comment`

+
Eine vollständige Befehlssyntax finden Sie im link:config-worksheets-reference.html["Arbeitsblatt"].

+
Mit dem folgenden Befehl wird das Cluster-Administratorkonto aktiviert `admin1` Mit dem vordefinierten `backup` Rolle für den Zugriff auf die Administrator-SVM``engCluster`` Mit einem Passwort. Nachdem Sie den Befehl eingegeben haben, werden Sie zur Eingabe des Passworts aufgefordert.

+
[listing]
----
cluster1::>security login create -vserver engCluster -user-or-group-name admin1 -application ssh -authmethod password -role backup
----

