---
permalink: authentication/grant-access-active-directory-users-groups-task.html 
sidebar: sidebar 
keywords: enable, active directory, account access 
summary: 'Sie können mit dem Befehl Security Login create Active Directory (AD)-Benutzer- oder Gruppenkonten für den Zugriff auf einen Administrator oder eine Daten-SVM aktivieren. Jeder Benutzer der AD-Gruppe kann mit der Rolle, die der Gruppe zugewiesen ist, auf die SVM zugreifen.' 
---
= Aktivieren Sie den Zugriff auf Active Directory-Konten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `security login create` Befehl zum Aktivieren von Active Directory-Benutzer- oder Gruppenkonten für den Zugriff auf einen Administrator oder eine Daten-SVM Jeder Benutzer der AD-Gruppe kann mit der Rolle, die der Gruppe zugewiesen ist, auf die SVM zugreifen.

.Über diese Aufgabe
* Sie müssen AD-Domänencontroller-Zugriff auf das Cluster oder SVM konfigurieren, bevor das Konto auf die SVM zugreifen kann.
+
xref:enable-ad-users-groups-access-cluster-svm-task.adoc[Active Directory-Domänencontroller-Zugriff wird konfiguriert]

+
Sie können diese Aufgabe vor oder nach dem Aktivieren des Kontozugriffs ausführen.

* Ab ONTAP 9.13.1 können Sie einen öffentlichen SSH-Schlüssel als primäre oder sekundäre Authentifizierungsmethode mit einem AD-Benutzerpasswort verwenden.
+
Wenn Sie einen öffentlichen SSH-Schlüssel als primäre Authentifizierung verwenden, findet keine AD-Authentifizierung statt.

* Ab ONTAP 9.11.1 können Sie dies nutzen link:../nfs-admin/ldap-fast-bind-nsswitch-authentication-task.html["LDAP fast bind für nsswitch-Authentifizierung"] Wenn es vom AD LDAP-Server unterstützt wird.
* Wenn Sie sich nicht sicher sind, welche Rolle bei der Zugriffssteuerung Sie dem Login-Konto zuweisen möchten, können Sie das verwenden `security login modify` Befehl, um die Rolle später hinzuzufügen.
+
xref:modify-role-assigned-administrator-task.adoc[Ändern der Rolle, die einem Administrator zugewiesen ist]




NOTE: Der Zugriff auf das Konto FÜR DIE ANZEIGENGRUPPE wird nur mit dem unterstützt `SSH`, `ontapi`, und `rest` Applikationen unterstützt. AD-Gruppen werden mit der SSH-Authentifizierung für öffentliche Schlüssel, die häufig für Multi-Faktor-Authentifizierung verwendet wird, nicht unterstützt.

.Bevor Sie beginnen
* Die Cluster-Zeit muss innerhalb von fünf Minuten nach der Zeit auf dem AD Domain Controller synchronisiert werden.
* Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.


.Schritt
. Aktivieren Sie AD-Benutzer- oder Gruppenadministratorkonten für den Zugriff auf eine SVM:
+
*Für AD-Nutzer:*

+
[cols="1,1,1,4"]
|===
| ONTAP-Version | Primäre Authentifizierung | Sekundäre Authentifizierung | Befehl 


| 9.13.1 und höher | Öffentlicher Schlüssel | Keine  a| 
[listing]
----
security login create -vserver <svm_name> -user-or-group-name <user_name> -application ssh -authentication-method publickey -role <role>
----


| 9.13.1 und höher | Domäne | Öffentlicher Schlüssel  a| 
*Für einen neuen Benutzer*

[listing]
----
security login create -vserver <svm_name> -user-or-group-name <user_name> -application ssh -authentication-method domain -second-authentication-method publickey -role <role>
----
*Für einen bestehenden Benutzer*

[listing]
----
security login modify -vserver <svm_name> -user-or-group-name <user_name> -application ssh -authentication-method domain -second-authentication-method publickey -role <role>
----


| 9.0 und höher | Domäne | Keine  a| 
[listing]
----
security login create -vserver <svm_name> -user-or-group-name <user_name> -application <application> -authentication-method domain -role <role> -comment <comment> [-is-ldap-fastbind true]
----
|===
+
*Für AD-Gruppen:*

+
[cols="1,1,1,4"]
|===
| ONTAP-Version | Primäre Authentifizierung | Sekundäre Authentifizierung | Befehl 


| 9.0 und höher | Domäne | Keine  a| 
[listing]
----
security login create -vserver <svm_name> -user-or-group-name <user_name> -application <application> -authentication-method domain -role <role> -comment <comment> [-is-ldap-fastbind true]
----
|===
+
Eine vollständige Befehlssyntax finden Sie unter link:config-worksheets-reference.html["Worksheets zur Administratorauthentifizierung und RBAC-Konfiguration"]



.Nachdem Sie fertig sind
Falls Sie keinen Zugriff von AD-Domänen-Controllern auf das Cluster oder SVM konfiguriert haben, müssen Sie dies tun, bevor das Konto auf die SVM zugreifen kann.

xref:enable-ad-users-groups-access-cluster-svm-task.adoc[Active Directory-Domänencontroller-Zugriff wird konfiguriert]
