---
permalink: authentication/index.html 
sidebar: sidebar 
keywords: decide, overview, administrator, authentication, rbac, role-based, access, control 
summary: 'Sie können Anmeldekonten für ONTAP Clusteradministratoren und Administratoren von Storage Virtual Machines (SVM) aktivieren. Mit der rollenbasierten Zugriffssteuerung (RBAC) lassen sich die Berechtigungen der Administratoren definieren.' 
---
= Informationen zur Administratorauthentifizierung und rollenbasierten Zugriffssteuerung (RBAC) in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Anmeldekonten für ONTAP Clusteradministratoren und Administratoren von Storage Virtual Machines (SVM) aktivieren. Mit der rollenbasierten Zugriffssteuerung (RBAC) lassen sich die Berechtigungen der Administratoren definieren.

Lokale Administratorkonten können für den Zugriff auf eine Admin Storage Virtual Machine (SVM) oder eine Data SVM mit den folgenden Authentifizierungsverfahren aktiviert werden:

* link:enable-password-account-access-task.html["Passwort"]
* link:enable-ssh-public-key-accounts-task.html["SSH öffentlicher Schlüssel"]
* link:enable-ssl-certificate-accounts-task.html["SSL-Zertifikat"]
* link:mfa-overview.html["SSH Multifaktor-Authentifizierung (MFA)"]
+
Ab ONTAP 9.3 wird die Authentifizierung mit Passwort und öffentlichem Schlüssel unterstützt.



Remote-Administratorkonten können Zugriff auf eine Admin-SVM oder eine Daten-SVM mit den folgenden Authentifizierungsverfahren erhalten:

* link:grant-access-active-directory-users-groups-task.html["Active Directory"]
+
Ab ONTAP 9.13.1 kann ein SSH Public Key entweder als primäres oder sekundäres Authentifizierungsverfahren für einen Active Directory Benutzer verwendet werden.

* link:../system-admin/configure-saml-authentication-task.html["SAML-Authentifizierung (nur für Admin SVM)"]
+
Ab ONTAP 9.3 kann die Security Assertion Markup Language (SAML) Authentifizierung für den Zugriff auf die Admin-SVM über einen der folgenden Webdienste verwendet werden: Service Processor Infrastructure, ONTAP APIs oder System Manager.

* link:grant-access-nis-ldap-user-accounts-task.html["LDAP oder NIS"]
+
Ab ONTAP 9.4 kann SSH MFA für Remote-Benutzer auf LDAP- oder NIS-Servern verwendet werden. Die Authentifizierung mit nsswitch und Public Key wird unterstützt.


