---
permalink: authentication/lock-unlock-user-account-task.html 
sidebar: sidebar 
keywords: lock, unlock, administrator account 
summary: Sie können den Befehl zum Sperren der Sicherheitsanmeldung verwenden, um ein Administratorkonto zu sperren, und den Befehl zum Entsperren der Sicherheitsanmeldung, um das Konto zu entsperren. 
---
= Sperren und Entsperren eines ONTAP-Administratorkontos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit dem `security login lock` Befehl können Sie ein Administratorkonto sperren und mit dem `security login unlock` Befehl das Konto entsperren.

.Bevor Sie beginnen
Sie müssen ein Cluster-Administrator sein, um diese Aufgaben auszuführen.

.Schritte
. Administratorkonto sperren:
+
`security login lock -vserver SVM_name -username user_name`

+
Mit dem folgenden Befehl wird das Administratorkonto `admin1` für die SVM gesperrt``vs1.example.com``:

+
[listing]
----
cluster1::>security login lock -vserver engData -username admin1
----
+
Erfahren Sie mehr über `security login lock` in der link:https://docs.netapp.com/us-en/ontap-cli/security-login-lock.html["ONTAP-Befehlsreferenz"^].

. Administratorkonto entsperren:
+
`security login unlock -vserver SVM_name -username user_name`

+
Mit dem folgenden Befehl wird das Administratorkonto `admin1` für die SVM entsperrt``vs1.example.com``:

+
[listing]
----
cluster1::>security login unlock -vserver engData -username admin1
----
+
Erfahren Sie mehr über `security login unlock` in der link:https://docs.netapp.com/us-en/ontap-cli/security-login-unlock.html["ONTAP-Befehlsreferenz"^].



.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+login["Sicherheitsanmeldung"^]

