---
permalink: authentication/lock-unlock-user-account-task.html 
sidebar: sidebar 
keywords: lock, unlock, administrator account 
summary: Mit dem Befehl „security login lock“ lässt sich ein Administratorkonto sperren, und mit dem Befehl „security login unlock“ wird das Konto wieder entsperrt. 
---
= Sperren und Entsperren eines ONTAP Administratorkontos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den  `security login lock`-Befehl verwenden, um ein Administratorkonto zu sperren, und den  `security login unlock`-Befehl, um das Konto zu entsperren.

.Bevor Sie beginnen
Sie müssen Cluster-Administrator sein, um diese Aufgaben ausführen zu können.

.Schritte
. Administratorkonto sperren:
+
`security login lock -vserver SVM_name -username user_name`

+
Der folgende Befehl sperrt das Administratorkonto `admin1` für die SVM ``vs1.example.com``:

+
[listing]
----
cluster1::>security login lock -vserver engData -username admin1
----
+
Weitere Informationen zu  `security login lock` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/security-login-lock.html["ONTAP-Befehlsreferenz"^].

. Entsperren eines Administratorkontos:
+
`security login unlock -vserver SVM_name -username user_name`

+
Der folgende Befehl entsperrt das Administratorkonto `admin1` für die SVM ``vs1.example.com``:

+
[listing]
----
cluster1::>security login unlock -vserver engData -username admin1
----
+
Weitere Informationen zu  `security login unlock` finden sich in der link:https://docs.netapp.com/us-en/ontap-cli/security-login-unlock.html["ONTAP-Befehlsreferenz"^].



.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+login["Security Login"^]

