---
permalink: authentication/modify-role-assigned-administrator-task.html 
sidebar: sidebar 
keywords: modify, role, assigned, administrator 
summary: Sie können mit dem Befehl zum Ändern der Sicherheitsanmeldung die Rolle eines Cluster- oder SVM-Administratorkontos ändern. Sie können eine vordefinierte oder benutzerdefinierte Rolle zuweisen. 
---
= Ändern Sie die einem Administrator zugewiesene Rolle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `security login modify` Befehl zum Ändern der Rolle eines Cluster- oder SVM-Administratorkontos. Sie können eine vordefinierte oder benutzerdefinierte Rolle zuweisen.

.Was Sie benötigen
Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.

.Schritt
. Ändern Sie die Rolle eines Clusters oder SVM-Administrators:
+
`security login modify -vserver SVM_name -user-or-group-name user_or_group_name -application application -authmethod authentication_method -role role -comment comment`

+
Eine vollständige Befehlssyntax finden Sie im link:config-worksheets-reference.html["Arbeitsblatt"].

+
link:config-worksheets-reference.html["Erstellen oder Ändern von Anmeldekonten"]

+
Mit dem folgenden Befehl wird die Rolle des AD-Cluster-Administratorkontos geändert `DOMAIN1\guest1` Für den vordefinierten `readonly` Rolle:

+
[listing]
----
cluster1::>security login modify -vserver engCluster -user-or-group-name DOMAIN1\guest1 -application ssh -authmethod domain -role readonly
----
+
Mit dem folgenden Befehl wird die Rolle der SVM-Administratorkonten im AD-Gruppenkonto geändert `DOMAIN1\adgroup` Auf den Benutzer `vol_role` Rolle:

+
[listing]
----
cluster1::>security login modify -vserver engData -user-or-group-name DOMAIN1\adgroup -application ssh -authmethod domain -role vol_role
----

