---
permalink: authentication/predefined-roles-svm-administrators-concept.html 
sidebar: sidebar 
keywords: predefined roles, cluster administrators 
summary: Die vordefinierten Rollen für SVM-Administratoren sollten die meisten Ihrer Anforderungen erfüllen. Sie können bei Bedarf benutzerdefinierte Rollen erstellen. Standardmäßig wird einem SVM-Administrator die vordefinierte vsadmin-Rolle zugewiesen. 
---
= Vordefinierte Rollen für SVM-Administratoren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die vordefinierten Rollen für SVM-Administratoren sollten die meisten Ihrer Anforderungen erfüllen. Sie können bei Bedarf benutzerdefinierte Rollen erstellen. Standardmäßig wird einem SVM-Administrator die vordefinierte `vsadmin` Rolle zugewiesen.

In der folgenden Tabelle sind die vordefinierten Rollen für SVM-Administratoren aufgeführt:

|===


| Rollenname | Sorgen 


 a| 
Vsadmin
 a| 
* Verwaltung des eigenen Benutzerkontos mit lokalem Passwort und Schlüsselinformationen
* Verwalten von Volumes, außer Verschieben von Volumes
* Managen von Kontingenten, qtrees, Snapshots und Dateien
* Verwalten von LUNs
* Durchführung von SnapLock-Vorgängen mit Ausnahme von privilegierten Löschen
* Konfiguration von Protokollen: NFS, SMB, iSCSI, FC, FCoE, NVMe/FC und NVMe/TCP
* Dienste konfigurieren: DNS, LDAP und NIS
* Überwachen von Jobs
* Monitoring von Netzwerkverbindungen und Netzwerkschnittstelle
* Monitoring des Systemzustands der SVM




 a| 
Vsadmin-Volume
 a| 
* Verwaltung des eigenen Benutzerkontos mit lokalem Passwort und Schlüsselinformationen
* Managen von Volumes, einschließlich Volume-Verschiebungen
* Managen von Kontingenten, qtrees, Snapshots und Dateien
* Verwalten von LUNs
* Konfiguration von Protokollen: NFS, SMB, iSCSI, FC, FCoE, NVMe/FC und NVMe/TCP
* Dienste konfigurieren: DNS, LDAP und NIS
* Monitoring der Netzwerkschnittstelle
* Monitoring des Systemzustands der SVM




 a| 
Vsadmin-Protokoll
 a| 
* Verwaltung des eigenen Benutzerkontos mit lokalem Passwort und Schlüsselinformationen
* Konfiguration von Protokollen: NFS, SMB, iSCSI, FC, FCoE, NVMe/FC und NVMe/TCP
* Dienste konfigurieren: DNS, LDAP und NIS
* Verwalten von LUNs
* Monitoring der Netzwerkschnittstelle
* Monitoring des Systemzustands der SVM




 a| 
Vsadmin-Backup
 a| 
* Verwaltung des eigenen Benutzerkontos mit lokalem Passwort und Schlüsselinformationen
* Verwalten des NDMP-Betriebs
* Erstellung eines wiederhergestellten Lese-/Schreibvorgangs eines Volumes
* Verwalten von SnapMirror Beziehungen und Snapshots
* Anzeigen von Volumes und Netzwerkinformationen




 a| 
Vsadmin-snaplock
 a| 
* Verwaltung des eigenen Benutzerkontos mit lokalem Passwort und Schlüsselinformationen
* Verwalten von Volumes, außer Verschieben von Volumes
* Managen von Kontingenten, qtrees, Snapshots und Dateien
* Durchführung von SnapLock-Vorgängen einschließlich privilegierter Löschung
* Konfiguration von Protokollen: NFS und SMB
* Dienste konfigurieren: DNS, LDAP und NIS
* Überwachen von Jobs
* Monitoring von Netzwerkverbindungen und Netzwerkschnittstelle




 a| 
Vsadmin-Readonly
 a| 
* Verwaltung des eigenen Benutzerkontos mit lokalem Passwort und Schlüsselinformationen
* Monitoring des Systemzustands der SVM
* Monitoring der Netzwerkschnittstelle
* Anzeigen von Volumes und LUNs
* Anzeigen von Services und Protokollen


|===