---
permalink: authentication/setup-ssh-multifactor-authentication-task.html 
sidebar: sidebar 
keywords: enable, ssh, multifactor authentication, mfa, hardware authentication device 
summary: Ab ONTAP 9.3 können Sie mit dem Befehl zum Erstellen von Sicherheitsanmeldung die Sicherheit erhöhen, da Administratoren sich bei einem Administrator oder einer Daten-SVM sowohl mit einem öffentlichen SSH-Schlüssel als auch mit einem Benutzerpasswort anmelden müssen. 
---
= Multi-Faktor-SSH-Authentifizierung (MFA) aktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.3 können Sie den verwenden `security login create` Um die Sicherheit zu verbessern, müssen sich Administratoren bei einem Administrator oder einer Daten-SVM sowohl mit einem öffentlichen SSH-Schlüssel als auch mit einem Benutzerpasswort einloggen.

Ab ONTAP 9.12.1 können Sie Yubikey-Hardware-Authentifizierungsgeräte für SSH-Client MFA verwenden, indem Sie die Authentifizierungsstandards FIDO2 (Fast Identity Online) oder PIV (Personal Identity Verification) verwenden.

Weitere Informationen zu link:https://www.netapp.com/pdf.html?item=/media/17055-tr4647pdf.pdf["Mehrstufige Authentifizierung in ONTAP 9 (TR-4647)"^].

Sie müssen ein Cluster-Administrator sein, um diese Aufgabe auszuführen.

.Über diese Aufgabe
* Sie müssen den öffentlichen Schlüssel dem Konto zuordnen, bevor das Konto auf die SVM zugreifen kann.
+
link:manage-public-key-authentication-concept.html["Einem Benutzerkonto einen öffentlichen Schlüssel zuordnen"]

+
Sie können diese Aufgabe vor oder nach dem Aktivieren des Kontozugriffs ausführen.

* Wenn Sie sich nicht sicher sind, welche Rolle bei der Zugriffssteuerung Sie dem Login-Konto zuweisen möchten, können Sie das verwenden `security login modify` Befehl, um die Rolle später hinzuzufügen.
+
link:modify-role-assigned-administrator-task.html["Ändern der Rolle, die einem Administrator zugewiesen ist"]

* Der Benutzer wird immer mit Authentifizierung des öffentlichen Schlüssels und der Kennwortauthentifizierung authentifiziert.


.Schritt
. Lokale Administratorkonten erforderlich, um über SSH MFA auf eine SVM zuzugreifen:
+
`security login create -vserver _SVM_ -user-or-group-name _user_name_ -application ssh -authentication-method password|publickey -role admin -second-authentication-method password|publickey`

+
Der folgende Befehl erfordert das SVM-Administratorkonto `admin2` Mit dem vordefinierten `admin` Rolle zum Anmelden bei der SVM``engData1`` Sowohl mit einem öffentlichen SSH-Schlüssel als auch mit einem Benutzerpasswort:

+
[listing]
----
cluster-1::> security login create -vserver engData1 -user-or-group-name admin2 -application ssh -authentication-method publickey -role admin -second-authentication-method password

Please enter a password for user 'admin2':
Please enter it again:
Warning: To use public-key authentication, you must create a public key for user "admin2".
----


Falls Sie dem Administratorkonto keinen öffentlichen Schlüssel zugeordnet haben, müssen Sie dies tun, bevor das Konto auf die SVM zugreifen kann.

link:manage-public-key-authentication-concept.html["Verknüpfen eines öffentlichen Schlüssels mit einem Benutzerkonto"]
